### ISSUE TITLE
Duplicate games in system tray context menu

### ISSUE THREAD

**Issue by guihkx** [Heroic-Games-Launcher/HeroicGamesLauncher#1000]
### Describe the bug

I only have Rocket League installed on Heroic, and when I click on the tray icon I see two entries for Rocket League.

### Add logs

(17:46:23) INFO:    [Legendary]:       Location: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary
(17:46:23) INFO:    [Gog]:             Location: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl
(17:46:24) INFO:    [Backend]:         
  Heroic Version: 2.2.0 Rayleigh
  Legendary Version:  0.20.25 Our Benefactors
  OS: Arch Linux KERNEL: 5.16.10-arch1-1 ARCH: x64
  CPU: Intel Core™ i5-3570K @3.4 GOVERNOR: powersave
  RAM: Total: 8.25 GB Available: 1.13 GB
  GRAPHICS: GPU0: NVIDIA GeForce GTX 660 VRAM: 1996MB DRIVER: 470.103.01 
  PROTOCOL: x11
  
(17:46:24) WARNING: [Backend]:         Protocol already registered.
(17:46:26) INFO:    [Frontend]:        Refreshing Library
(17:46:26) INFO:    [Legendary]:       Refreshing library...
(17:46:26) INFO:    [Legendary]:       Refreshing Epic Games...
(17:46:26) INFO:    [Legendary]:       Refreshing Epic Games...
(17:46:27) INFO:    [Legendary]:       [cli] INFO: Logging in...
(17:46:27) INFO:    [Legendary]:       [Core] INFO: Trying to re-use existing login session...
(17:46:27) INFO:    [Legendary]:       [cli] INFO: Getting game list... (this may take a while)
(17:46:28) INFO:    [Legendary]:       Updating game list
(17:46:28) INFO:    [Legendary]:       Game List Updated
(17:46:30) INFO:    [Legendary]:       Checking for game updates
(17:46:30) INFO:    [Legendary]:       Found 1 game(s) to update
(17:46:30) INFO:    [Gog]:             Found 0 game(s) to update
(17:46:30) INFO:    [Backend]:         checking for heroic updates

### Steps to reproduce

N/A

### Expected behavior

No duplicated entries

### Screenshots

![image](https://user-images.githubusercontent.com/626206/155405338-35602fa1-2c9f-44cd-b189-b8f01c5a2ddc.png)

### System Information

- OS [e. g. "Ubuntu"]:  Arch Linux
- Heroic Version [e. g. 2.1.1]: 2.2.0

**Comment by arielj** [comment]
is this still an issue? if so, can you check the content of the file `.config/heroic/store/config.json`? it should have something like

```
{
	"games": {
		"recent": [
			{
				"appName": "stargazer",
				"title": "Magic The Gathering Arena"
			},
			{
				"appName": "1423049311",
				"title": "Cyberpunk 2077"
			},
			{
				"appName": "1dea8a6ddb544842a58e4b5c8675ff58",
				"title": "Cave Story+"
			},
			{
				"appName": "Peony",
				"title": "The Escapists"
			}
		],
```

can you share that?

**Comment by guihkx** [comment]
Here you go:

```json
{
        "games": {
                "recent": [
                        {
                                "appName": "Sugar",
                                "title": "Rocket League®"
                        },
                        {
                                "game": "Sugar",
                                "title": "Rocket League®"
                        }
                ]
        },
        "settings": {
                "altLeg": ""
        },
        "general-logs": {
                "currentLogFile": "/home/gui/.config/heroic/logs/heroic-2022-04-24T15_13:25.561Z.log",
                "lastLogFile": "/home/gui/.config/heroic/logs/heroic-2022-03-21T21_37:36.897Z.log"
        },
        "window-props": {
                "x": 227,
                "y": 257,
                "width": 1200,
                "height": 690
        }
}
```

**Comment by arielj** [comment]
thanks, I can see the issue, the second one is incorrect, you can modify that by hand now replacing:

```
"recent": [
                        {
                                "appName": "Sugar",
                                "title": "Rocket League®"
                        },
                        {
                                "game": "Sugar",
                                "title": "Rocket League®"
                        }
                ]
```

with:

```
"recent": [
                        {
                                "appName": "Sugar",
                                "title": "Rocket League®"
                        }
                ]
```

also, it shouldn't happen again for you after that change. I'll send a PR that prevents this to happen for other people in the future
