### ISSUE TITLE
Launcher should look in ~/.steam/steam/compatibilitytools.d

### ISSUE THREAD

**Issue by CoralCunt** [Heroic-Games-Launcher/HeroicGamesLauncher#1002]
### Problem description

When I first tried setting up Proton GE, I couldn't get Steam to detect it, even though it was in `~/.steam/root/compatibilitytools.d`. After some research, I found out that `~/.local/share/Steam/compatibilitytools.d` and `~/.steam/steam/compatibilitytools.d` are also directories that Steam uses, seemingly dependent on the distro. `~/.steam/steam/compatibilitytools.d` worked for me.

### Feature description

HGL already checks in `~/.steam/root/compatibilitytools.d` by default. It would be great if other directories such as `~/.local/share/Steam/compatibilitytools.d` and `~/.steam/steam/compatibilitytools.d` would be on the list too.

### Alternatives

There's already a feature that lets you add custom directories. However, you have to select the actual binary file, which is already a bit of a chore, and then do that for each Proton GE version. Not very convenient if you have many versions installed. 
You could also copy all of your Steam Proton GE versions over to `~/.config/heroic/tools/proton`, but that would double the used hard drive space you use for Proton GE, which is a lot if, again, you own many versions of Proton GE that each would need to be doubled.

**Comment by flavioislima** [comment]
You don't need to copy the proton folder, just create a symlink to the folder Heroic looks at.
But still, which distro is that?

**Comment by CoralCunt** [comment]
> just create a symlink

Yeah that worked, thanks. 

> But still, which distro is that?

Just plain Arch.

**Comment by Nocifer** [comment]
I'm on Arch as well and on launch Steam by default creates `~/.steam/root` and `~/.steam/steam` which are both symlinks pointing to `~/.local/share/Steam`, so I don't get how HGL using any one of these would prevent it from picking up the stuff it's looking for, since they're all the exact same folder...

**Comment by CoralCunt** [comment]
If that is so, then I don't know why. I just know that `root` didn't work for me, but `steam` did. While I had that problem I came across posts on reddit and the steam forums by people that had the same issue, and stating that a certain other directory worked for them instead, such as this one. 

![image](https://user-images.githubusercontent.com/87242503/155861286-e06036d8-23ac-4c98-a8be-21ca63b44ee5.png)

**Comment by flavioislima** [comment]
I am pretty sure Heroic is looking into the right folder. 
.steam should be the one and from there root or or .steam/steamapps/common.

So I am closing this one
