### ISSUE TITLE
GOG games aren't avaiable in the correct folder

### ISSUE THREAD

**Issue by benjamimgois** [Heroic-Games-Launcher/HeroicGamesLauncher#1003]
### Describe the bug

I can install my GOG games from the new 2.2 version, but none of then launch after i click to start. I just found they weren't installed in the folder i choose. 

### Add logs

Error - Command failed: mangohud --dlsym     /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl launch "'/mnt/NVME/Games/heroic'/Shadow Tactics - Blades of the Shogun" 1601442230 --platform=linux  

### Steps to reproduce

- Install a GOG Game to a folder in /mnt/NVME/Games/Heroic/
- Try to launch it

### Expected behavior

The game folder should be in the /mnt/NVME/Heroic/

### Screenshots

![image](https://user-images.githubusercontent.com/7688496/155439431-2d03a3a7-cd25-4fb7-b2e1-f7e7e58095ec.png)

See that "Shadow Tactics..." isn't avaiable in the installation folder. Investigating the image, i observed that this single quotes might be a problem.

### System Information

- Arch Linux
- Heroic 2.2

**Comment by imLinguin** [comment]
This is the big which appears when using file picker popup. When path is passed manually it works fine.

**Comment by flavioislima** [comment]
@benjamimgois 
Fixed on the new release.
