### ISSUE TITLE
Heroic don't load GOG list 

### ISSUE THREAD

**Issue by TaxAkla** [Heroic-Games-Launcher/HeroicGamesLauncher#1007]
### Describe the bug

I've successfully logged on GOG through Heroic but the program don't show any game.

### Add logs

(09:55:34) INFO:    [Legendary]:       Location: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary
(09:55:34) INFO:    [Gog]:             Location: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl
(09:55:37) INFO:    [Backend]:         
  Heroic Version: 2.2.0 Rayleigh
  Legendary Version:  0.20.25 Our Benefactors
  OS: LinuxMint KERNEL: 5.14.21-xanmod1 ARCH: x64
  CPU: AMD Ryzen 3 2200G with Radeon Vega Graphics @3.5 GOVERNOR: ondemand
  RAM: Total: 8.26 GB Available: 4.57 GB
  GRAPHICS: GPU0: Ellesmere [Radeon RX 470/480/570/570X/580/580X/590] VRAM: 256MB DRIVER:  
  PROTOCOL: x11
  
(09:55:37) INFO:    [Gog]:             Getting data about the user
(09:55:38) WARNING: [Backend]:         Protocol already registered.
(09:55:39) INFO:    [Gog]:             Saved user data to config
(09:55:39) INFO:    [Frontend]:        Refreshing Library
(09:55:39) INFO:    [Gog]:             Getting GOG library
(09:55:40) INFO:    [Gog]:             Number of library pages: 7
(09:55:40) INFO:    [Gog]:             Getting data for page 2
(09:55:41) INFO:    [Gog]:             Getting data for page 3
(09:55:42) INFO:    [Gog]:             Getting data for page 4
(09:55:43) INFO:    [Gog]:             Getting data for page 5
(09:55:44) INFO:    [Backend]:         checking for heroic updates
(09:55:44) INFO:    [Gog]:             Getting data for page 6
(09:55:45) INFO:    [Gog]:             Getting data for page 7
(09:55:47) WARNING: [Gog]:             Unable to get covers from gamesdb for Cave Story®'s Secret Santa. Trying to get it from api.gog.com
(09:55:48) ERROR:   [Frontend]:        Error: Error invoking remote method 'refreshLibrary': TypeError: Cannot read properties of null (reading '_links')
(09:55:49) INFO:    [Legendary]:       Checking for game updates
(09:55:49) INFO:    [Legendary]:       Found 0 game(s) to update
(09:55:49) INFO:    [Gog]:             Found 0 game(s) to update
(09:57:09) INFO:    [Frontend]:        Refreshing Library
(09:57:09) INFO:    [Gog]:             Getting GOG library
(09:57:10) INFO:    [Gog]:             Number of library pages: 7
(09:57:10) INFO:    [Gog]:             Getting data for page 2
(09:57:11) INFO:    [Gog]:             Getting data for page 3
(09:57:12) INFO:    [Gog]:             Getting data for page 4
(09:57:13) INFO:    [Gog]:             Getting data for page 5
(09:57:13) INFO:    [Gog]:             Getting data for page 6
(09:57:14) INFO:    [Gog]:             Getting data for page 7
(09:57:16) WARNING: [Gog]:             Unable to get covers from gamesdb for Cave Story®'s Secret Santa. Trying to get it from api.gog.com
(09:57:17) ERROR:   [Frontend]:        Error: Error invoking remote method 'refreshLibrary': TypeError: Cannot read properties of null (reading '_links')
(09:58:21) INFO:    [Frontend]:        Refreshing Library
(09:58:21) INFO:    [Gog]:             Getting GOG library
(09:58:22) INFO:    [Gog]:             Number of library pages: 7
(09:58:22) INFO:    [Gog]:             Getting data for page 2
(09:58:23) INFO:    [Gog]:             Getting data for page 3
(09:58:24) INFO:    [Gog]:             Getting data for page 4
(09:58:25) INFO:    [Gog]:             Getting data for page 5
(09:58:26) INFO:    [Gog]:             Getting data for page 6
(09:58:27) INFO:    [Gog]:             Getting data for page 7
(09:58:28) WARNING: [Gog]:             Unable to get covers from gamesdb for Cave Story®'s Secret Santa. Trying to get it from api.gog.com
(09:58:29) ERROR:   [Frontend]:        Error: Error invoking remote method 'refreshLibrary': TypeError: Cannot read properties of null (reading '_links')
(09:58:31) INFO:    [Legendary]:       Checking for game updates
(09:58:31) INFO:    [Legendary]:       Found 0 game(s) to update
(09:58:31) INFO:    [Gog]:             Found 0 game(s) to update

### Steps to reproduce

1. Go to Library
2. Click on GOG
3. Click Refresh
4. No game pops up.

### Expected behavior

I expect to see my GOG library

### System Information

OS:              Linux Mint 20.3 una
- Heroic Version: 2.2.0_amd64

**Comment by flavioislima** [comment]
Fixed on new release
