### ISSUE TITLE
Heroic Launcher doesn't launch

### ISSUE THREAD

**Issue by ShimonHoranek** [Heroic-Games-Launcher/HeroicGamesLauncher#1009]
### Describe the bug

Whenever I open Heroic Games Launcher, it crashes immediately 

### Add logs

(17:46:00) INFO:    [Legendary]:       Location: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary
(17:46:00) INFO:    [Gog]:             Location: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl

This is all I get when launching from terminal

### Steps to reproduce

Open Heroic Games Launcher

### Expected behavior

Upon opening it should open :)

### System Information

Archlinux 5.16.10-arch1-1
Heroic version: AUR 2.2.1-1

**Comment by flavioislima** [comment]
Have it worked on other versions of Heroic?

**Comment by ShimonHoranek** [comment]
Solved by removing a RAM stick I added yesterday. For some reason that caused it.
