### ISSUE TITLE
Installation of German Version of Anno 1503 fails

### ISSUE THREAD

**Issue by JakobDev** [Heroic-Games-Launcher/HeroicGamesLauncher#1010]
### Describe the bug

The Installation of the GOG version of [Anno 1503](https://www.gog.com/game/anno_1503_ad) fails when selecting German as language. The installation is cancelled direct after start. English seems to have no problem.

### Add logs

(18:17:50) INFO:    [Legendary]:       Location: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary
(18:17:50) INFO:    [Gog]:             Location: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl
(18:17:50) INFO:    [Backend]:         
  Heroic Version: 2.2.1 Oden
  Legendary Version:  0.20.25 Our Benefactors
  OS: ManjaroLinux KERNEL: 5.10.98-1-MANJARO ARCH: x64
  CPU: AMD Ryzen 5 2600 Six-Core Processor @3.4 GOVERNOR: schedutil
  RAM: Total: 16.8 GB Available: 8.92 GB
  GRAPHICS: GPU0: NVIDIA GeForce RTX 2060 SUPER VRAM: 8192MB DRIVER: 510.47.03 
  PROTOCOL: x11
  
(18:17:51) ERROR:   [Backend]:         Failed to register protocol with OS.
(18:17:52) INFO:    [Frontend]:        Refreshing Library
(18:17:52) INFO:    [Legendary]:       Refreshing library...
(18:17:52) INFO:    [Legendary]:       Refreshing Epic Games...
(18:17:52) INFO:    [Legendary]:       Refreshing Epic Games...
(18:17:52) INFO:    [Legendary]:       [cli] INFO: Logging in...
(18:17:53) INFO:    [Legendary]:       [Core] INFO: Logging in...
(18:17:53) INFO:    [DXVKInstaller]:   Updating dxvk to: dxvk-1.9.4
(18:17:53) INFO:    [DXVKInstaller]:   Updating vkd3d to: vkd3d-proton-2.5
(18:17:53) INFO:    [Legendary]:       [EPCAPI] WARNING: Login to EGS API failed with errorCode: errors.com.epicgames.account.auth_token.invalid_refresh_token
(18:17:53) ERROR:   [Legendary]:       [Core] ERROR: Stored credentials are no longer valid! Please login again.
[cli] ERROR: Login failed, cannot continue!
(18:17:53) INFO:    [Legendary]:       Updating game list
(18:17:53) INFO:    [Legendary]:       Game List Updated
(18:17:53) INFO:    [Gog]:             Found 0 game(s) to update
(18:17:54) INFO:    [DXVKInstaller]:   downloaded vkd3d
(18:17:54) INFO:    [DXVKInstaller]:   extracting vkd3d
(18:17:54) INFO:    [DXVKInstaller]:   extracting vkd3d updated!
(18:17:55) INFO:    [DXVKInstaller]:   downloaded dxvk
(18:17:55) INFO:    [DXVKInstaller]:   extracting dxvk
(18:17:55) INFO:    [DXVKInstaller]:   extracting dxvk updated!
(18:17:57) INFO:    [Backend]:         checking for heroic updates
(18:20:09) INFO:    [Legendary]:       Logging with Legendary...
(18:20:09) INFO:    [Legendary]:       Logging with Legendary...
(18:20:09) INFO:    [Legendary]:       stderr: [cli] INFO: Testing existing login data if present...

(18:20:09) INFO:    [Legendary]:       stderr: [cli] INFO: Testing existing login data if present...

(18:20:10) INFO:    [Legendary]:       stderr: [cli] INFO: Successfully logged in as "JakobDev"

(18:20:10) INFO:    [Legendary]:       finished login
(18:20:11) INFO:    [Legendary]:       stderr: [cli] INFO: Successfully logged in as "JakobDev"

(18:20:11) INFO:    [Legendary]:       finished login
(18:20:49) INFO:    [Gog]:             Logging using GOG credentials
(18:20:49) INFO:    [Gog]:             Login Successful
(18:20:49) INFO:    [Gog]:             Getting data about the user
(18:20:50) INFO:    [Gog]:             Saved user data to config
(18:20:52) INFO:    [Frontend]:        Refreshing Library
(18:20:52) INFO:    [Gog]:             Getting GOG library
(18:20:52) INFO:    [Gog]:             Number of library pages: 1
(18:20:57) INFO:    [Gog]:             Saved games data
(18:20:57) INFO:    [Legendary]:       Refreshing library...
(18:20:57) INFO:    [Legendary]:       Refreshing Epic Games...
(18:20:57) INFO:    [Legendary]:       Refreshing Epic Games...
(18:20:57) INFO:    [Legendary]:       [cli] INFO: Logging in...
(18:20:57) INFO:    [Legendary]:       [Core] INFO: Trying to re-use existing login session...
(18:20:58) INFO:    [Legendary]:       [cli] INFO: Getting game list... (this may take a while)
(18:20:58) INFO:    [Legendary]:       [Core] INFO: Fetching metadata for 12 app(s).
(18:20:59) INFO:    [Legendary]:       Updating game list
(18:20:59) INFO:    [Legendary]:       Game List Updated
(18:20:59) INFO:    [Frontend]:        Force Update
(18:22:10) INFO:    [Gog]:             Installing 1438074791 with: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl download 1438074791 --platform windows --path="/run/media/jakob/Datenplatte/Heroic" --skip-dlcs --lang="German"  |& tee "/home/jakob/.config/heroic/GamesConfig/1438074791.log"
(18:22:11) INFO:    [Backend]:         Progress: 1438074791 /MiB/undefined
(18:22:12) INFO:    [Backend]:         finished installing
(18:22:12) INFO:    [Backend]:         operation interrupted
(18:22:12) INFO:    [Frontend]:        Refreshing Library
(18:22:12) INFO:    [Gog]:             Getting GOG library
(18:22:12) INFO:    [Gog]:             Number of library pages: 1
(18:22:12) INFO:    [Gog]:             Saved games data
(18:22:12) INFO:    [Legendary]:       Refreshing library...
(18:22:12) INFO:    [Legendary]:       Updating game list
(18:22:12) INFO:    [Legendary]:       Game List Updated
(18:22:19) INFO:    [Gog]:             Installing 1438074791 with: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl download 1438074791 --platform windows --path="/run/media/jakob/Datenplatte/Heroic" --skip-dlcs --lang="English"  |& tee "/home/jakob/.config/heroic/GamesConfig/1438074791.log"
(18:22:20) INFO:    [Backend]:         Progress: 1438074791 /0.00
MiB/undefined
(18:22:22) INFO:    [Backend]:         Progress: 1438074791 0.09/1.23
MiB/00:39:01

(18:22:23) INFO:    [Backend]:         Progress: 1438074791 0.09/1.24
MiB/00:58:02

(18:22:25) INFO:    [Backend]:         Progress: 1438074791 0.09/1.26
MiB/01:37:04

(18:22:26) INFO:    [Backend]:         Progress: 1438074791 0.09/1.27
MiB/01:37:05

(18:22:28) INFO:    [Backend]:         Progress: 1438074791 0.09/1.36
MiB/94:37:07

(18:22:28) INFO:    [Gog]:             killing 1438074791
(18:22:28) INFO:    [Gog]:             1438074791 killed
(18:22:28) INFO:    [Gog]:             Installaton canceled
(18:22:28) INFO:    [Backend]:         finished installing
(18:22:29) INFO:    [Frontend]:        Refreshing Library
(18:22:29) INFO:    [Gog]:             Getting GOG library
(18:22:29) INFO:    [Gog]:             Number of library pages: 1
(18:22:29) INFO:    [Gog]:             Saved games data
(18:22:29) INFO:    [Legendary]:       Refreshing library...
(18:22:29) INFO:    [Legendary]:       Updating game list
(18:22:29) INFO:    [Legendary]:       Game List Updated
(18:22:35) INFO:    [Gog]:             Installing 1438074791 with: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl download 1438074791 --platform windows --path="/run/media/jakob/Datenplatte/Heroic" --skip-dlcs --lang="German"  |& tee "/home/jakob/.config/heroic/GamesConfig/1438074791.log"
(18:22:36) INFO:    [Backend]:         Progress: 1438074791 /MiB/undefined
(18:22:37) INFO:    [Backend]:         finished installing
(18:22:37) INFO:    [Backend]:         operation interrupted
(18:22:37) INFO:    [Frontend]:        Refreshing Library
(18:22:37) INFO:    [Gog]:             Getting GOG library
(18:22:38) INFO:    [Gog]:             Number of library pages: 1
(18:22:38) INFO:    [Gog]:             Saved games data
(18:22:38) INFO:    [Legendary]:       Refreshing library...
(18:22:38) INFO:    [Legendary]:       Updating game list
(18:22:38) INFO:    [Legendary]:       Game List Updated
(18:22:48) INFO:    [Gog]:             Installing 1438074791 with: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl download 1438074791 --platform windows --path="/run/media/jakob/Datenplatte/Heroic" --skip-dlcs --lang="English"  |& tee "/home/jakob/.config/heroic/GamesConfig/1438074791.log"
(18:22:49) INFO:    [Backend]:         Progress: 1438074791 /MiB/undefined
(18:22:51) INFO:    [Backend]:         Progress: 1438074791 0.00/1.65
MiB/42035:56:00

(18:22:52) INFO:    [Backend]:         Progress: 1438074791 0.14/2.06
MiB/00:38:02

(18:22:54) INFO:    [Backend]:         Progress: 1438074791 0.21/3.02
MiB/00:44:03

(18:22:55) INFO:    [Backend]:         Progress: 1438074791 0.69/9.93
MiB/00:32:05

(18:22:57) INFO:    [Backend]:         Progress: 1438074791 1.17/16.84
MiB/00:37:06

(18:22:58) INFO:    [Backend]:         Progress: 1438074791 1.89/27.32
MiB/00:29:08

(18:23:00) INFO:    [Backend]:         Progress: 1438074791 2.15/30.97
MiB/00:30:09

(18:23:01) INFO:    [Backend]:         Progress: 1438074791 2.78/40.09
MiB/00:44:11

(18:23:03) INFO:    [Backend]:         Progress: 1438074791 3.11/44.87
MiB/00:47:12

(18:23:04) INFO:    [Backend]:         Progress: 1438074791 3.81/55.05
MiB/00:57:14

(18:23:06) INFO:    [Backend]:         Progress: 1438074791 3.89/56.09
MiB/01:09:15

(18:23:07) INFO:    [Backend]:         Progress: 1438074791 4.53/65.37
MiB/01:23:17

(18:23:09) INFO:    [Backend]:         Progress: 1438074791 4.64/67.02
MiB/01:35:18

(18:23:10) INFO:    [Backend]:         Progress: 1438074791 5.26/75.93
MiB/01:42:20

(18:23:12) INFO:    [Backend]:         Progress: 1438074791 5.61/80.95
MiB/01:49:21

(18:23:13) INFO:    [Backend]:         Progress: 1438074791 6.27/90.46
MiB/01:40:23

(18:23:15) INFO:    [Backend]:         Progress: 1438074791 6.58/95.03
MiB/01:42:24

(18:23:15) INFO:    [Gog]:             killing 1438074791
(18:23:15) INFO:    [Gog]:             Installaton canceled
(18:23:15) INFO:    [Backend]:         finished installing
(18:23:15) INFO:    [Gog]:             1438074791 killed
(18:23:16) INFO:    [Frontend]:        Refreshing Library
(18:23:16) INFO:    [Gog]:             Getting GOG library
(18:23:16) INFO:    [Gog]:             Number of library pages: 1
(18:23:16) INFO:    [Gog]:             Saved games data
(18:23:16) INFO:    [Legendary]:       Refreshing library...
(18:23:16) INFO:    [Legendary]:       Updating game list
(18:23:16) INFO:    [Legendary]:       Game List Updated

### Steps to reproduce

Try to install the German version of Anno 1503, if you own it.

### Expected behavior

It should install

### System Information

- OS: Manjaro
- Heroic Version: 2.2.1

**Comment by imLinguin** [comment]
is there any error in `/home/jakob/.config/heroic/GamesConfig/1438074791.log`?

**Comment by JakobDev** [comment]
No, but it might by from my try to download the English version.
```
[DOWNLOAD_MANAGER] INFO: Checking compatibility of Anno 1503 A.D. with windows
[DOWNLOAD_MANAGER] INFO: Game is compatible
[DOWNLOAD_MANAGER] INFO: Depot version: 1
[API] INFO: Getting Dependencies repository
[API] INFO: Getting repository manifest
[DOWNLOAD_MANAGER] INFO: Calculating download size
[DOWNLOAD_MANAGER] INFO: Download size: 1.41GB
[DOWNLOAD_MANAGER] INFO: Size on disk: 1.41GB
[PROGRESS] INFO: = Progress: 0.00 0/1513293910, Running for: 00:00:00, ETA: 42035:56:00
[PROGRESS] INFO: = Downloaded: 0.00 MiB
[PROGRESS] INFO: = Progress: 0.11 1725186/1513293910, Running for: 00:00:00, ETA: 00:29:01
[PROGRESS] INFO: = Downloaded: 1.65 MiB
[PROGRESS] INFO: = Progress: 0.14 2160749/1513293910, Running for: 00:00:00, ETA: 00:38:02
[PROGRESS] INFO: = Downloaded: 2.06 MiB
[PROGRESS] INFO: = Progress: 0.21 3162337/1513293910, Running for: 00:00:00, ETA: 00:44:03
[PROGRESS] INFO: = Downloaded: 3.02 MiB
[PROGRESS] INFO: = Progress: 0.34 5215151/1513293910, Running for: 00:00:00, ETA: 00:45:04
[PROGRESS] INFO: = Downloaded: 4.97 MiB
[PROGRESS] INFO: = Progress: 0.69 10408174/1513293910, Running for: 00:00:00, ETA: 00:32:05
[PROGRESS] INFO: = Downloaded: 9.93 MiB
[PROGRESS] INFO: = Progress: 1.17 17661337/1513293910, Running for: 00:00:00, ETA: 00:37:06
[PROGRESS] INFO: = Downloaded: 16.84 MiB
[PROGRESS] INFO: = Progress: 1.45 21912067/1513293910, Running for: 00:00:00, ETA: 00:33:07
[PROGRESS] INFO: = Downloaded: 20.90 MiB
[PROGRESS] INFO: = Progress: 1.89 28649057/1513293910, Running for: 00:00:00, ETA: 00:29:08
[PROGRESS] INFO: = Downloaded: 27.32 MiB
[PROGRESS] INFO: = Progress: 2.15 32478235/1513293910, Running for: 00:00:00, ETA: 00:30:09
[PROGRESS] INFO: = Downloaded: 30.97 MiB
[PROGRESS] INFO: = Progress: 2.43 36716187/1513293910, Running for: 00:00:00, ETA: 00:35:10
[PROGRESS] INFO: = Downloaded: 35.02 MiB
[PROGRESS] INFO: = Progress: 2.78 42035096/1513293910, Running for: 00:00:00, ETA: 00:44:11
[PROGRESS] INFO: = Downloaded: 40.09 MiB
[PROGRESS] INFO: = Progress: 3.11 47048880/1513293910, Running for: 00:00:00, ETA: 00:47:12
[PROGRESS] INFO: = Downloaded: 44.87 MiB
[PROGRESS] INFO: = Progress: 3.35 50667923/1513293910, Running for: 00:00:00, ETA: 01:00:13
[PROGRESS] INFO: = Downloaded: 48.32 MiB
[PROGRESS] INFO: = Progress: 3.81 57719889/1513293910, Running for: 00:00:00, ETA: 00:57:14
[PROGRESS] INFO: = Downloaded: 55.05 MiB
[PROGRESS] INFO: = Progress: 3.89 58812740/1513293910, Running for: 00:00:00, ETA: 01:09:15
[PROGRESS] INFO: = Downloaded: 56.09 MiB
[PROGRESS] INFO: = Progress: 4.23 64000329/1513293910, Running for: 00:00:00, ETA: 01:15:16
[PROGRESS] INFO: = Downloaded: 61.04 MiB
[PROGRESS] INFO: = Progress: 4.53 68547602/1513293910, Running for: 00:00:00, ETA: 01:23:17
[PROGRESS] INFO: = Downloaded: 65.37 MiB
[PROGRESS] INFO: = Progress: 4.64 70276774/1513293910, Running for: 00:00:00, ETA: 01:35:18
[PROGRESS] INFO: = Downloaded: 67.02 MiB
[PROGRESS] INFO: = Progress: 4.92 74458371/1513293910, Running for: 00:00:00, ETA: 02:02:19
[PROGRESS] INFO: = Downloaded: 71.01 MiB
[PROGRESS] INFO: = Progress: 5.26 79621729/1513293910, Running for: 00:00:00, ETA: 01:42:20
[PROGRESS] INFO: = Downloaded: 75.93 MiB
[PROGRESS] INFO: = Progress: 5.61 84881896/1513293910, Running for: 00:00:00, ETA: 01:49:21
[PROGRESS] INFO: = Downloaded: 80.95 MiB
[PROGRESS] INFO: = Progress: 6.01 91010302/1513293910, Running for: 00:00:00, ETA: 01:47:22
[PROGRESS] INFO: = Downloaded: 86.79 MiB
[PROGRESS] INFO: = Progress: 6.27 94851873/1513293910, Running for: 00:00:00, ETA: 01:40:23
[PROGRESS] INFO: = Downloaded: 90.46 MiB
[PROGRESS] INFO: = Progress: 6.58 99642205/1513293910, Running for: 00:00:00, ETA: 01:42:24
[PROGRESS] INFO: = Downloaded: 95.03 MiB
[PROGRESS] INFO: = Progress: 6.86 103881992/1513293910, Running for: 00:00:00, ETA: 01:50:25
[PROGRESS] INFO: = Downloaded: 99.07 MiB
```

**Comment by wiryfuture** [comment]
Is this fixed orrr?

**Comment by JakobDev** [comment]
This Bug has been fixed. Forgot to close. Sorry.
