### ISSUE TITLE
I miss an Dosbox support for Dosboxgames they dosn't support for Linux/Unix in GOG

### ISSUE THREAD

**Issue by SaschaVasarrhelyi** [Heroic-Games-Launcher/HeroicGamesLauncher#1011]
### Problem description

Dosbox Games they not supportet for Linux/Unix from GoG are provided an manual configuration for Dosbox otherwise they not run throw Heroic cause Heroic just make it avaiable throw WINE. In Lutris there is an integrated Dosbox System to configure dosbox.game.config (for use with Dosbox) and an integrated starter setup.

### Feature description

Dosbox Starter + Configuration selecter for dosbox.conf / dosbox.game.conf / dosbox.game.starter.conf skripts. And it were a good thing to select an various Dosbox version and /or location on the System.

### Additional information

My System:
Ubuntu-MATE Version 20.04.4 LTS (Focal Fossa) 64-bit
Kernel Linux 5.13.0-30-generic x86_64
MATE 1.24.0

**Comment by imLinguin** [comment]
I believe we could support ScummVM like that too.

**Comment by arrowgent** [comment]
a system similar to boxtron for steam?
https://github.com/dreamer/boxtron

**Comment by flavioislima** [comment]
please follow the wiki: https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/wiki/How-To:-DOSBOX-and-SCUMMVM
