### ISSUE TITLE
[GOG] [23938] Error loading Python lib '/tmp/_MEIhDx2ZK/libpython3.9.so.1.0':

### ISSUE THREAD

**Issue by arrowgent** [Heroic-Games-Launcher/HeroicGamesLauncher#1015]
### Describe the bug

trying to install any GOG game
check the log it says libpython3.9 and glibc

EGS games download and launch correctly.

### Add logs

ERROR:   [Backend]:         Error: Command failed: /home/catbox/.local/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl info 1207664623 --token="removed" --lang=en-US --os windows
[23938] Error loading Python lib '/tmp/_MEIhDx2ZK/libpython3.9.so.1.0': dlopen: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /tmp/_MEIhDx2ZK/libpython3.9.so.1.0)

### Steps to reproduce

1. Go to '...' gog
2. Click on '...' any game
3. Scroll down to '...' install

### Expected behavior

game downloads
is playable in wine/proton

### System Information

- OS [e. g. "Ubuntu"]: ubuntu 18.04 x86_64 - with lots and LOTS of patches and updates.
python3 --version
Python 3.8.12
sudo update-alternatives --config python3
python3 --version
Python 3.9.10

- Heroic Version [e. g. 2.1.1]: 2.2.1 - compiled AppImage & tar.gz versions

### Additional information

i have python3.6, python3.7, 3.8, & 3.9

because python3.6 is required by the majority of my system:
sudo update-alternatives --config python3
then launch heroic for testing

i tried to compile heroic itself using yarn & nodejs 16 LTS to see if your AppImage release was forced using glibc 1.29
glibc 1.29 wont be possible with debian 10 or ubuntu 18.04

https://packages.ubuntu.com/search?keywords=glibc
https://packages.debian.org/search?keywords=glibc

https://endoflife.software/operating-systems/linux/debian
https://endoflife.software/operating-systems/linux/ubuntu

please make compiling against the system glibc & libpython3.9 possible for this CI build enviornment

**Comment by arrowgent** [comment]
ah, separate module

https://github.com/Heroic-Games-Launcher/heroic-gogdl

needs a bit of refining

**Comment by arrowgent** [comment]
https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/tree/main/public/bin/linux

yes, so youre precompiling binaries and the yarn is just using them for the build that git clone has
if instead this can be replaced in the CI to curl the released src.zip and compile it during the build process?

**Comment by Nocccer** [comment]
That does not change anything and makes things more complicated. Because we will not role out different gogdl for different ubuntu versions. 18.04 is pretty outdated.

**Comment by imLinguin** [comment]
We are not dependant on os libraries in most cases. Here we can see that python embedded in binary is requiring some newer glibc version.

@arrowgent could you test if binary built on your version of Ubuntu works on newer one? 

Yarn embeds binaries from `public/bin/linux` directory, so if you compile gogdl just make it executable and swap it there.

**Comment by arrowgent** [comment]
yes gogdl compiled and works,  see the

> [Heroic-Games-Launcher/heroic-gogdl#1](https://github.com/Heroic-Games-Launcher/heroic-gogdl/issues/1)
> 
> this is now working when compiled on ubuntu 18.04 & using python 3.6.9
>

**Comment by arrowgent** [comment]
from what i gather elswhere is youre using python3.9 because windows 10 requires it and is the only official python3 supported in that OS

which translates back over to your dependency for python3.9 in linux, which isnt the case
however, appimage building has its own set of library dependencies, complicating this further, since it will refuse to run due to glibc <+ 2.29+

whether ubuntu 18.04 is _old_ shouldnt be the issue, it still has canonical developer support (5 years) until 2023.  going into semantics, people still use and backport to 16.04
setting up your CI build structure to use only `ubuntu-latest` or `debian-latest` ensures that anything other than the newest versions from the OS distro will be abandoned within 6 months - 2 years.

**Comment by wiryfuture** [comment]
It has been four years since 18.04 not two years. And we're talking about in the consumer desktop, not server, so that is plenty of time.
However, having working builds is still a valid point lol.
