### ISSUE TITLE
Games cannot start because Epic has logged out

### ISSUE THREAD

**Issue by parkejunior** [Heroic-Games-Launcher/HeroicGamesLauncher#1017]
### Describe the bug

Games cannot start after updating to version 2.2.1 because Epic has logged out.

After the update I tried to run RocketLeague but the game didn't start, it stops without an error message. 

I tried to run with another wineprefix and another version of wine and it didn't work.
I tried to put the alternative EXE but it didn't work either, the error is the same.

In the log message I realized that Epic might be disconnected. Logging in, the game started running again, but it would be great to have a message warning about the account being logged out.
I spent a good few minutes looking for the problem, I didn't understand what the log meant by "No saved credentials".

### Add logs

Launch Command:     WINEESYNC=1      STEAM_COMPAT_CLIENT_INSTALL_PATH=/home/patrick/.steam/steam STEAM_COMPAT_DATA_PATH='/mnt/BARRACUDA/.Wine/heroic'   /opt/heroic/resources/app.asar.unpacked/build/bin/linux/legendary launch Sugar   --no-wine --wrapper "'/home/patrick/.steam/steam/steamapps/common/Proton 6.3/proton' run"   
        System Info:
        
  Heroic Version: 2.2.1 Oden
  Legendary Version:  0.20.25 Our Benefactors
  OS: Solus KERNEL: 5.14.21-210.current ARCH: x64
  CPU: AMD Ryzen 7 1700 Eight-Core Processor @3 GOVERNOR: ondemand
  RAM: Total: 16.7 GB Available: 14 GB
  GRAPHICS: GPU0: Tonga PRO [Radeon R9 285/380] VRAM: 256MB DRIVER:  
  PROTOCOL: x11
  
        Game Settings: {
	"audioFix": false,
	"autoInstallDxvk": false,
	"autoInstallVkd3d": false,
	"autoSyncSaves": false,
	"enableEsync": true,
	"enableFSR": false,
	"enableFsync": false,
	"maxSharpness": 5,
	"enableResizableBar": false,
	"launcherArgs": "",
	"nvidiaPrime": false,
	"offlineMode": false,
	"otherOptions": "",
	"savesPath": "",
	"showFps": false,
	"showMangohud": false,
	"targetExe": "",
	"useGameMode": false,
	"wineCrossoverBottle": "Heroic",
	"winePrefix": "/mnt/BARRACUDA/.Wine/heroic",
	"wineVersion": {
		"bin": "'/home/patrick/.steam/steam/steamapps/common/Proton 6.3/proton'",
		"name": "Proton - Proton 6.3"
	},
	"useSteamRuntime": false
}

        Game Log:
        [cli] INFO: Logging in...
Traceback (most recent call last):
  File "legendary/cli.py", line 3004, in <module>
  File "legendary/cli.py", line 2919, in main
  File "legendary/cli.py", line 582, in launch_game
  File "legendary/core.py", line 188, in login
ValueError: No saved credentials
[5566] Failed to execute script 'cli' due to unhandled exception!

### Steps to reproduce

1. Start game
2. Game stops

### Expected behavior

Game running

### System Information

- OS: Solus 4.3 Fortitude
- Heroic Version:  2.2.1 Oden

**Comment by parkejunior** [comment]
> Are you logged in via sid ?

I'm not sure but I think so

**Comment by flavioislima** [comment]
If it was a bug was fixed on 2.2.6, if not you can reopen the issue

**Comment by parkejunior** [comment]
> If it was a bug was fixed on 2.2.6, if not you can reopen the issue

Thank you!
