### ISSUE TITLE
[gogdl] remove token string from logs to prevent others downloading games

### ISSUE THREAD

**Issue by arrowgent** [Heroic-Games-Launcher/HeroicGamesLauncher#1020]
### Describe the bug

i believe the unique token string from gogdl is the api token for accessing user games

removing this from the log or error logs would avoid people from looking here and using it to access games they do not own
and avoid errors submitted with api token keys

### Add logs

ERROR: [Backend]: Error: Command failed: /home/catbox/.local/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl info 1207664623 --token="removed" --lang=en-US --os windows

ERROR: [Backend]: Error: Command failed: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl info 2 --token="removed" --lang=en-US --os windows

### Steps to reproduce

error occurs
goes to logs
copies log to github issue
api token is in the log

### Expected behavior

obfuscate tokens from log

### System Information

- OS [e. g. "Ubuntu"]:  linux
- Heroic Version [e. g. 2.1.1]: 2.2.1

**Comment by flavioislima** [comment]
@imLinguin I believe this was solved long time ago since we are using a protected command for the logs, right?

**Comment by imLinguin** [comment]
I believe yes, however it still leaks the token in case command fails. Probably catching in those cases would suffice

**Comment by wiryfuture** [comment]
#1044 resolves this
