### ISSUE TITLE
Search box 'x' disappears after switching to game page

### ISSUE THREAD

**Issue by TabulateJarl8** [Heroic-Games-Launcher/HeroicGamesLauncher#1025]
### Describe the bug

If you search for something and click on a game to view its page and then click the library button to go back to your library, the 'x' button in the search bar is gone. I'm not entirely sure why this happens, and I can't remember if it was there when I first added this feature

### Add logs

```
(23:30:32) INFO:    [Legendary]:       Location: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary
(23:30:32) INFO:    [Gog]:             Location: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl
(23:30:32) INFO:    [Backend]:         
  Heroic Version: 2.2.1 Oden
  Legendary Version:  0.20.25 Our Benefactors
  OS: Arch KERNEL: 5.16.11-arch1-1 ARCH: x64
  CPU: AMD Ryzen 5 3600 6-Core Processor @3.6 GOVERNOR: performance
  RAM: Total: 33.7 GB Available: 22.6 GB
  GRAPHICS: GPU0: NVIDIA GeForce RTX 2070 SUPER VRAM: 8192MB DRIVER: 510.54 
  PROTOCOL: x11
  
(23:30:33) WARNING: [Backend]:         Protocol already registered.
(23:30:33) INFO:    [Frontend]:        Refreshing Library
(23:30:33) INFO:    [Legendary]:       Refreshing library...
(23:30:33) INFO:    [Legendary]:       Refreshing Epic Games...
(23:30:33) INFO:    [Legendary]:       Refreshing Epic Games...
(23:30:34) INFO:    [Legendary]:       [cli] INFO: Logging in...
(23:30:35) INFO:    [Legendary]:       [Core] INFO: Logging in...
(23:30:35) INFO:    [Legendary]:       [cli] INFO: Getting game list... (this may take a while)
(23:30:35) INFO:    [Legendary]:       [Core] INFO: Fetching metadata for 4 app(s).
(23:30:35) INFO:    [Legendary]:       Updating game list
(23:30:35) INFO:    [Legendary]:       Game List Updated
(23:30:36) INFO:    [Legendary]:       Checking for game updates
(23:30:36) INFO:    [Legendary]:       Found 0 game(s) to update
(23:30:36) INFO:    [Gog]:             Found 0 game(s) to update
(23:30:36) INFO:    [Frontend]:        Force Update
(23:30:38) INFO:    [Backend]:         checking for heroic updates
(23:30:44) INFO:    [Legendary]:       Getting Info from Epic API
(23:30:44) INFO:    [Legendary]:       Getting More details with Legendary info command... 
(23:30:46) INFO:    [Legendary]:       Getting More details with Legendary info command... 
(23:30:56) INFO:    [Legendary]:       Getting More details with Legendary info command... 
```

### Steps to reproduce

1. Search for a game
2. Click on the game
3. Click the library button

### Expected behavior

The 'x' button should still be there

### System Information

- OS [e. g. "Ubuntu"]: Arch Linux
- Heroic Version [e. g. 2.1.1]: 2.2.1

**Comment by arielj** [comment]
I was not able to reproduce this:

https://user-images.githubusercontent.com/188464/159361036-55a88724-82de-4601-bda2-69546dd9dc8d.mp4

Using the code from the main branch

**Comment by TabulateJarl8** [comment]
Strange, I still can on version 2.2.6

https://user-images.githubusercontent.com/58576759/159362315-3208c203-adb7-4b67-acb8-142c81cf60b1.mp4

**Comment by arielj** [comment]
weird, some things I see different:

- the search bad has no yellow outline when focused on your recording (compared to mine)
- you seem to have only one store when you click Library and I have both GOG and Epic

I understand that you added the searchbar? it would be great if you can debug what's going on there, at least on my end I can't reproduce it

**Comment by TabulateJarl8** [comment]
I havent linked my GOG account, might be why that's not showing. No clue as to the yellow outline though

**Comment by flavioislima** [comment]
I cannot reproduce it on 2.3.2. If still persist reopen it.
