### ISSUE TITLE
Unable to install Game on external drive

### ISSUE THREAD

**Issue by Dattito** [Heroic-Games-Launcher/HeroicGamesLauncher#1026]
### Describe the bug

Because GTA V is a really heavy game, I tried to install it on my external drive. I changed the "Default Installation Path" for games to the drive and started the download. After a few seconds, it shows "Installation finished", but nothing really happened.

I think it is because Heroic is not allowed to enter the external drive, but it also doesn't request access.

### Add logs

(08:16:24) INFO:    [Legendary]:       Location: /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/legendary
(08:16:24) INFO:    [Gog]:             Location: /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/gogdl
(08:16:28) INFO:    [Backend]:         
  Heroic Version: 2.2.1 Oden
  Legendary Version:  0.20.25 Our Benefactors
  OS: macOS KERNEL: 21.3.0 ARCH: x64
  CPU: Apple M1 Pro @2.4 
  RAM: Total: 17.2 GB Available: 10.7 GB
  GRAPHICS: GPU0: Apple M1 Pro VRAM: nullMB DRIVER:  
  
  
(08:16:28) WARNING: [Backend]:         Protocol already registered.
(08:16:31) INFO:    [Frontend]:        Refreshing Library
(08:16:31) INFO:    [Legendary]:       Refreshing library...
(08:16:31) INFO:    [Legendary]:       Refreshing Epic Games...
(08:16:31) INFO:    [Legendary]:       Refreshing Epic Games...
(08:16:34) INFO:    [Legendary]:       [cli] INFO: Logging in...
(08:16:34) INFO:    [Legendary]:       [Core] INFO: Trying to re-use existing login session...
(08:16:35) INFO:    [Legendary]:       [cli] INFO: Getting game list... (this may take a while)
(08:16:36) INFO:    [Backend]:         checking for heroic updates
(08:16:37) INFO:    [Legendary]:       Updating game list
(08:16:37) INFO:    [Legendary]:       Game List Updated
(08:16:40) INFO:    [Legendary]:       Getting More details with Legendary info command... 
(08:16:42) INFO:    [Legendary]:       Checking for game updates
(08:16:42) INFO:    [Legendary]:       Found 0 game(s) to update
(08:16:42) INFO:    [Gog]:             Found 0 game(s) to update
(08:16:42) INFO:    [Legendary]:       Installing 9d2d0eb64d5c44529cece33fe2a46482 with: /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/legendary install 9d2d0eb64d5c44529cece33fe2a46482 --platform Windows --base-path /Volumes/SanDisk SSD/Heroic-Spiele --skip-dlcs --skip-sdl  -y |& tee "/Users/dattito/.config/heroic/GamesConfig/9d2d0eb64d5c44529cece33fe2a46482.log"
(08:16:43) INFO:    [Backend]:         Progress: 9d2d0eb64d5c44529cece33fe2a46482 /MiB/undefined
(08:16:44) INFO:    [Backend]:         Progress: 9d2d0eb64d5c44529cece33fe2a46482 /MiB/undefined
(08:16:46) INFO:    [Backend]:         Progress: 9d2d0eb64d5c44529cece33fe2a46482 /MiB/undefined
(08:16:46) INFO:    [Backend]:         finished installing
(08:16:46) INFO:    [Frontend]:        Refreshing Library
(08:16:46) INFO:    [Legendary]:       Refreshing library...
(08:16:46) INFO:    [Legendary]:       Updating game list
(08:16:47) INFO:    [Legendary]:       Game List Updated

### Steps to reproduce

1. Change the Default Installation Path to a folder inside the SSD
2. Try to install GTA V
3. "Installation started"
4. "Installation finished"

### Expected behavior

Download the >100gb or throw an error-message.

### System Information

- OS [e. g. "Ubuntu"]: 
- Heroic Version [e. g. 2.1.1]:

**Comment by raulcraveiro** [comment]
I have the same problem, but installing Neverwinter on a external drive on macOS.

**Comment by montogeek** [comment]
I have this same problem with Cyberpunk 2077 on a Steam Deck when installing it on a microSD card.

**Comment by flavioislima** [comment]
> I have this same problem with Cyberpunk 2077 on a Steam Deck when installing it on a microSD card.

For the Steam deck follow the latest tutorial on Gaming on Linux.

For the Mac I will need to investigate.

**Comment by thereald3bug** [comment]
My problem is the game will install but will not launch because it does not find the bottle.
Apparently "Wineprefix" was removed from the GUI interface so it keeps looking on my Primary HDD not my Secondary drive where all my Bottles are.  MacOS of course.

My bottles are in "/Volumes/Storage/Crossover Bottles". and instead it's looking for bottles on some variation of $HOME.
There seems to be no way to correct this behavior.

**Comment by crazyquark** [comment]
What I did is: I made a symlink in my home folder(/home/deck/Games) to a folder in the sdcard bypassing the need for adding a proper path in settings. Delete /home/deck/Games before doing this. Now the games install to sd card seamlessly.

**Comment by M1guelJesus** [comment]
I have the same problem in Linux PopOS but the symlink hack didn't work.

**Comment by fabmm** [comment]
I have the same issue, I just switched from Windows 11 to pop OS, and I'm trying to install games through Heroic Launcher but what used to be my 1 TB D drive on Windows is not being found in "Other Locations" in Heroic path selection GUI... I've been trying to figure this out for 3 days… Please help!

**Comment by flavioislima** [comment]
> I have the same issue, I just switched from Windows 11 to pop OS, and I'm trying to install games through Heroic Launcher but what used to be my 1 TB D drive on Windows is not being found in "Other Locations" in Heroic path selection GUI... I've been trying to figure this out for 3 days… Please help!

in your case, are you using the version installed using the pop store?
if yes, you are using the Flatpak. It doesnt have access to all your system folders.
so you need to install another app called FLATSEAL. And use it to give Heroic permission to access your Hard Drive.

**Comment by zakariyaIaka** [comment]
Has a solution been found for macos as of yet?

**Comment by mistaluai** [comment]
any solution for macOS ?

**Comment by Wiertelsus** [comment]
create a symlink to a folder on the external drive, to do this:
-create a folder somewhere heroic can access
-create a folder on the external drive (something like "Games")
-open terminal and type in:` ln -s (path to the folder on the external drive) (path to the folder heroic can access)`
-open heroic and point it to the symlink
