### ISSUE TITLE
Auto-Install/Update DXVK doesn't work on GOG Windows game

### ISSUE THREAD

**Issue by redromnon** [Heroic-Games-Launcher/HeroicGamesLauncher#1028]
### Describe the bug

When toggling the **Auto Install/Update DXVK on Prefix** checkbox for _Symphonia_, it fails to install DXVK automatically. I believe it'll be the same case for other GOG Windows titles too.

### Add logs

```
(07:09:41) INFO:    [DXVKInstaller]:   installing dxvk on... /home/redromnon/Games/Heroic/Prefixes/Symphonia
(07:09:41) ERROR:   [DXVKInstaller]:   Error: Command failed: PATH=/home/redromnon/.config/heroic/tools/wine/Wine-7.1-GE-1/bin/:$PATH WINEPREFIX='/home/redromnon/Games/Heroic/Prefixes/Symphonia' bash /home/redromnon/.config/heroic/tools/dxvk/dxvk-1.9.4/setup*.sh install --symlink
wine: Not a wine executable. Check your $wine.

(07:09:41) ERROR:   [DXVKInstaller]:   error when installing DXVK, please try launching the game again
```

### Steps to reproduce

1. Go to any Windows GOG game
2. Go to Settings
3. Under Wine, toggle Auto Install/Update DXVK on Prefix

### Expected behavior

Show the wine dialog box & install or remove DXVK automatically

### Screenshots

None

### System Information

- OS : Pop OS 20.04 
- Heroic Version : 2.2.1 

### Additional information

None

**Comment by flavioislima** [comment]
Hi, this is not a Heroic bug it's a Wine-GE bug that they seems to have fixed on 7.2-GE.
So you can upgrade to latest one or downgrade to 6.20, install DXVK and then select the 7.1 again.
