### ISSUE TITLE
Library not load in version 2.2.1-1

### ISSUE THREAD

**Issue by kayosu1031** [Heroic-Games-Launcher/HeroicGamesLauncher#1029]
### Describe the bug

after update to version 2.2.1-1 my game library doesn't show anymore. just an empty tab

### Add logs

(23:34:08) INFO: [Legendary]: Location: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary

(23:34:08) INFO: [Gog]: Location: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl

(23:34:09) INFO: [Backend]:

Heroic Version: 2.2.1 Oden

Legendary Version: 0.20.25 Our Benefactors

OS: ManjaroLinux KERNEL: 5.16.11-2-MANJARO ARCH: x64

CPU: Intel Xeon® E3-1220 v3 @3.1 GOVERNOR: schedutil

RAM: Total: 8.27 GB Available: 5.12 GB

GRAPHICS: GPU0: NVIDIA GeForce GTX 750 Ti VRAM: 2048MB DRIVER: 510.54

PROTOCOL: x11

(23:34:09) ERROR: [Backend]: Failed to register protocol with OS.

(23:34:10) INFO: [Frontend]: Refreshing Library

(23:34:10) INFO: [Legendary]: Refreshing library...

(23:34:10) INFO: [Legendary]: Refreshing Epic Games...

(23:34:10) INFO: [Legendary]: Refreshing Epic Games...

(23:34:11) INFO: [Legendary]: [cli] INFO: Logging in...

(23:34:11) INFO: [Legendary]: [Core] INFO: Trying to re-use existing login session...

(23:34:12) INFO: [Legendary]: [cli] INFO: Getting game list... (this may take a while)

(23:34:13) INFO: [Legendary]: Updating game list

(23:34:13) INFO: [Legendary]: Game List Updated

(23:34:14) INFO: [Backend]: checking for heroic updates

(23:34:14) INFO: [Backend]: skipping heroic updates

(23:34:16) INFO: [Legendary]: Checking for game updates

(23:34:16) INFO: [Legendary]: Found 0 game(s) to update

(23:34:16) INFO: [Gog]: Found 0 game(s) to update

### Steps to reproduce

open heroic game launcher

### Expected behavior

game library doesn't show

### Screenshots
 
![Screenshot_2022-03-01_23-52-53](https://user-images.githubusercontent.com/100711359/156212823-0d62863f-253b-46c8-b4a5-bf1707d398e0.png)

### System Information

- OS: ManjaroLinux KERNEL: 5.16.11-2-MANJARO ARCH: x64
- Heroic Version 2.2.1

**Comment by imLinguin** [comment]
Workaround: Go to Account Manager and press continue
