### ISSUE TITLE
Disable HTTPS for CDNs

### ISSUE THREAD

**Issue by jkms** [Heroic-Games-Launcher/HeroicGamesLauncher#1032]
### Problem description

Heroic does not appear to be working with my LanCache setup.  I suspect (but have not confirmed) that it's defaulting to SSL instead of HTTP.

### Feature description

Please add an option to force HTTP instead of HTTPS so that my LanCache server can cache downloads

### Alternatives

N/A

### Additional information

LanCache: https://lancache.net/

**Comment by wiryfuture** [comment]
I think this might be an upstream issue as well bc i dont think legendary supports it.

**Comment by arielj** [comment]
Actually, Legendary supports the `--no-https` option with this exact description `Download games via plaintext HTTP (like EGS), e.g. for use with a lan cache`, so it's should be fairly easy to implement (just a switch/boolean and adding the flag to the install command if the value is true)
