### ISSUE TITLE
Silent crash when zstd was not installed

### ISSUE THREAD

**Issue by safijari** [Heroic-Games-Launcher/HeroicGamesLauncher#1033]
### Describe the bug

The launcher would just hang on getting the games list. When I launched from the terminal and watched the console spam I found that the tar command for updating dxvk was crashing because zstd was not found, which apparently took down whatever thread/process was updating the games list. Installing zstd fixed this issue, but the lack of any feedback on the UI end would make this a pretty frustrating issue.

### Add logs

(18:09:24) INFO:    [Legendary]:       Location: /tmp/.mount_Heroic6rwPQN/resources/app.asar.unpacked/build/bin/linux/legendary
(18:09:24) INFO:    [Gog]:             Location: /tmp/.mount_Heroic6rwPQN/resources/app.asar.unpacked/build/bin/linux/gogdl
(18:09:26) INFO:    [Backend]:         
  Heroic Version: 2.2.1 Oden
  Legendary Version:  0.20.25 Our Benefactors
  OS: Ubuntu KERNEL: 5.11.0-49-generic ARCH: x64
  CPU: Intel Core™ i9-9980HK @2.4 GOVERNOR: performance
  RAM: Total: 33.3 GB Available: 27.8 GB
  GRAPHICS: GPU0: CoffeeLake-H GT2 [UHD Graphics 630]  VRAM: 256MB DRIVER:  GPU1: Quadro T2000 VRAM: 3914MB DRIVER: 495.46 
  PROTOCOL: x11
  
(18:09:26) INFO:    [Gog]:             Getting data about the user
(18:09:26) ERROR:   [Backend]:         Failed to register protocol with OS.
(18:09:27) INFO:    [Frontend]:        Refreshing Library
(18:09:27) INFO:    [Gog]:             Getting GOG library
(18:09:30) INFO:    [Gog]:             Saved user data to config
(18:09:31) INFO:    [Gog]:             Number of library pages: 1
(18:09:31) WARNING: [Gog]:             Unable to get covers from gamesdb for The Witcher Goodies Collection. Trying to get it from api.gog.com
(18:09:31) INFO:    [Backend]:         checking for heroic updates
(18:09:31) INFO:    [DXVKInstaller]:   Updating vkd3d to: vkd3d-proton-2.5
(18:09:34) WARNING: [Gog]:             Couldn't get info from api.gog.com, Using fallback vertical image
(18:09:43) INFO:    [DXVKInstaller]:   downloaded vkd3d
(18:09:43) INFO:    [DXVKInstaller]:   extracting vkd3d
(18:09:43) INFO:    [DXVKInstaller]:   extracting vkd3d updated!
(18:09:46) WARNING: [Gog]:             Unable to get covers from gamesdb for Warhammer Skulls Digital Goodies. Trying to get it from api.gog.com
(18:09:49) WARNING: [Gog]:             Couldn't get info from api.gog.com, Using fallback vertical image
(18:09:58) INFO:    [Gog]:             Saved games data
(18:09:58) INFO:    [Legendary]:       Refreshing library...
(18:09:58) INFO:    [Legendary]:       Refreshing Epic Games...
(18:09:58) INFO:    [Legendary]:       Refreshing Epic Games...
(18:10:03) INFO:    [Legendary]:       [cli] INFO: Logging in...
(18:10:03) INFO:    [Legendary]:       [Core] INFO: Trying to re-use existing login session...
(18:10:05) INFO:    [Legendary]:       [cli] INFO: Getting game list... (this may take a while)
(18:10:10) INFO:    [Legendary]:       Updating game list
(18:10:10) INFO:    [Legendary]:       Game List Updated
(18:10:10) INFO:    [Frontend]:        No cache found, getting data from legendary...
(18:10:10) INFO:    [Legendary]:       Refreshing library...
(18:10:10) INFO:    [Legendary]:       Updating game list
(18:10:10) INFO:    [Legendary]:       Game List Updated
(18:10:24) INFO:    [Legendary]:       Checking for game updates
(18:10:24) INFO:    [Legendary]:       Found 1 game(s) to update
(18:10:24) INFO:    [Gog]:             Found 0 game(s) to update
(18:10:24) INFO:    [Frontend]:        Force Update

### Steps to reproduce

On a fresh install, ensure zstd is not installed in the system and run heroic launcher and login. 

### Expected behavior

Games list would populate despite the dxvk update failing. An error would be shown that a dependency was not found (or better yet, zstd would be bundled with the appimage)

### System Information

2.2.1 Heroic, 21.04 Ubuntu

**Comment by Nocccer** [comment]
This should only happen with AppImage! If you installed heroic vis deb package it dhould actually chrck if zstd is installed

**Comment by arrowgent** [comment]
zstd and zlib1g are required etc.

the `legendary` is built against a newer glibc/libc6, i actually need to recompile this to use my system libs...

appimage and yarn compile both complain about this


```
(22:22:22) INFO:    [Legendary]:       Refreshing Epic Games...
(22:22:22) INFO:    [Legendary]:       /home/catbox/.local/bin/heroic_dist/resources/app.asar.unpacked/build/bin/linux/legendary: error while loading shared libraries: libz.so.1: failed to map segment from shared object
(22:22:22) INFO:    [Legendary]:       Updating game list
(22:22:22) INFO:    [Legendary]:       Game List Updated
(22:22:23) ERROR:   [Legendary]:       Error: Command failed: /home/catbox/.local/bin/heroic_dist/resources/app.asar.unpacked/build/bin/linux/legendary list-installed --check-updates --tsv
/home/catbox/.local/bin/heroic_dist/resources/app.asar.unpacked/build/bin/linux/legendary: error while loading shared libraries: libz.so.1: failed to map segment from shared object
```

```
Error occurred in handler for 'checkGameUpdates': TypeError: legendaryUpdates is not iterable
    at /home/catbox/.local/bin/heroic_dist/resources/app.asar/build/main.js:406:16
    at async node:electron/js2c/browser_init:193:563
(22:22:23) ERROR:   [Frontend]:        Error: Error invoking remote method 'checkGameUpdates': TypeError: legendaryUpdates is not iterable
```


which i guess i dont care too much,  it downloads and runs fine currently.
and of course it doesnt crash...

**Comment by safijari** [comment]
> This should only happen with AppImage! If you installed heroic vis deb package it dhould actually chrck if zstd is installed

Yes I was using appimage. I guess if most people aren't going to use it via appimage then it makes less sense to fix this

**Comment by flavioislima** [comment]
Ideally we will figure it out how to have vkd3d in a zip format, but for now Heroic will show a proper error:
![image](https://user-images.githubusercontent.com/26871415/171613074-0f8a82c6-c455-43bf-ad01-3b7b2d98cb6f.png)
