### ISSUE TITLE
Game installations silently fails unless default install folder is selected

### ISSUE THREAD

**Issue by safijari** [Heroic-Games-Launcher/HeroicGamesLauncher#1034]
### Describe the bug

Game installation would not start. No error would be shown. A folder was already selected when installing (~/Games/Heroic) but the installation wasn't starting until I went into settings and set this as the default install directory.

### Add logs

(18:23:21) INFO:    [Legendary]:       Location: /tmp/.mount_HeroicVff1rW/resources/app.asar.unpacked/build/bin/linux/legendary
(18:23:21) INFO:    [Gog]:             Location: /tmp/.mount_HeroicVff1rW/resources/app.asar.unpacked/build/bin/linux/gogdl
(18:23:23) INFO:    [Backend]:         
  Heroic Version: 2.2.1 Oden
  Legendary Version:  0.20.25 Our Benefactors
  OS: Ubuntu KERNEL: 5.11.0-49-generic ARCH: x64
  CPU: Intel Core™ i9-9980HK @2.4 GOVERNOR: performance
  RAM: Total: 33.3 GB Available: 27.9 GB
  GRAPHICS: GPU0: CoffeeLake-H GT2 [UHD Graphics 630]  VRAM: 256MB DRIVER:  GPU1: Quadro T2000 VRAM: 3914MB DRIVER: 495.46 
  PROTOCOL: x11
  
(18:23:23) INFO:    [Gog]:             Getting data about the user
(18:23:23) ERROR:   [Backend]:         Failed to register protocol with OS.
(18:23:24) INFO:    [Frontend]:        Refreshing Library
(18:23:24) INFO:    [Gog]:             Getting GOG library
(18:23:24) INFO:    [Gog]:             Saved user data to config
(18:23:26) INFO:    [Gog]:             Number of library pages: 1
(18:23:26) INFO:    [Gog]:             Saved games data
(18:23:26) INFO:    [Legendary]:       Refreshing library...
(18:23:26) INFO:    [Legendary]:       Refreshing Epic Games...
(18:23:26) INFO:    [Legendary]:       Refreshing Epic Games...
(18:23:29) INFO:    [Legendary]:       [cli] INFO: Logging in...
(18:23:29) INFO:    [Legendary]:       [Core] INFO: Trying to re-use existing login session...
(18:23:29) INFO:    [Backend]:         checking for heroic updates
(18:23:29) INFO:    [Legendary]:       Getting More details with Legendary info command... 
(18:23:29) INFO:    [Legendary]:       [cli] INFO: Getting game list... (this may take a while)
(18:23:30) INFO:    [Legendary]:       Updating game list
(18:23:30) INFO:    [Legendary]:       Game List Updated
(18:23:33) INFO:    [Legendary]:       Getting More details with Legendary info command... 
(18:23:35) INFO:    [Legendary]:       Checking for game updates
(18:23:35) INFO:    [Legendary]:       Found 1 game(s) to update
(18:23:35) INFO:    [Gog]:             Found 0 game(s) to update
(18:23:36) INFO:    [Legendary]:       Getting More details with Legendary info command... 
(18:24:18) INFO:    [Frontend]:        Refreshing wine downloader releases
(18:24:18) INFO:    [WineDownloader]:  Updating wine versions info
(18:24:22) INFO:    [WineDownloader]:  wine versions updated
(18:24:48) INFO:    [Legendary]:       
(18:24:50) INFO:    [Frontend]:        Refreshing Library
(18:24:50) INFO:    [Gog]:             Getting GOG library
(18:24:51) INFO:    [Gog]:             Number of library pages: 1
(18:24:51) INFO:    [Gog]:             Saved games data
(18:24:51) INFO:    [Legendary]:       Refreshing library...
(18:24:51) INFO:    [Legendary]:       Refreshing Epic Games...
(18:24:51) INFO:    [Legendary]:       Refreshing Epic Games...
(18:24:53) INFO:    [Legendary]:       [cli] INFO: Logging in...
(18:24:53) INFO:    [Legendary]:       [Core] INFO: Trying to re-use existing login session...
(18:24:54) INFO:    [Legendary]:       [cli] INFO: Getting game list... (this may take a while)
(18:24:55) INFO:    [Legendary]:       Updating game list
(18:24:55) INFO:    [Legendary]:       Game List Updated
(18:25:03) INFO:    [Legendary]:       Getting More details with Legendary info command... 
(18:25:11) INFO:    [Legendary]:       Installing f7a0ebb44f93430fb1c4388a395eba96 with: /tmp/.mount_HeroicVff1rW/resources/app.asar.unpacked/build/bin/linux/legendary install f7a0ebb44f93430fb1c4388a395eba96 --platform Windows --base-path /home/jari/Games/Heroic --skip-dlcs --skip-sdl  -y |& tee "/home/jari/.config/heroic/GamesConfig/f7a0ebb44f93430fb1c4388a395eba96.log"
(18:25:12) INFO:    [Backend]:         Progress: f7a0ebb44f93430fb1c4388a395eba96 /MiB/undefined
(18:25:13) INFO:    [Backend]:         Progress: f7a0ebb44f93430fb1c4388a395eba96 /MiB/undefined
(18:25:15) INFO:    [Backend]:         Progress: f7a0ebb44f93430fb1c4388a395eba96 0.00%/0.00
MiB/00:00:00

(18:25:16) INFO:    [Backend]:         Progress: f7a0ebb44f93430fb1c4388a395eba96 0.00%/0.00
MiB/00:00:00

(18:25:18) INFO:    [Backend]:         Progress: f7a0ebb44f93430fb1c4388a395eba96 0.00%/0.00
MiB/00:00:00

(18:25:19) INFO:    [Backend]:         Progress: f7a0ebb44f93430fb1c4388a395eba96 0.00%/0.00
MiB/00:00:00

(18:25:21) INFO:    [Backend]:         Progress: f7a0ebb44f93430fb1c4388a395eba96 0.00%/6.31
MiB/00:00:00

(18:25:21) INFO:    [Legendary]:       Getting More details with Legendary info command... 
(18:25:22) INFO:    [Backend]:         Progress: f7a0ebb44f93430fb1c4388a395eba96 0.57%/11.66
MiB/00:20:26

(18:25:24) INFO:    [Backend]:         Progress: f7a0ebb44f93430fb1c4388a395eba96 9.09%/14.65
MiB/00:01:30

(18:25:25) INFO:    [Backend]:         Progress: f7a0ebb44f93430fb1c4388a395eba96 9.09%/14.65
MiB/00:01:40

(18:25:27) INFO:    [Backend]:         Progress: f7a0ebb44f93430fb1c4388a395eba96 9.09%/14.65
MiB/00:02:00

(18:25:28) INFO:    [Backend]:         Progress: f7a0ebb44f93430fb1c4388a395eba96 10.23%/15.65
MiB/00:01:54

(18:25:30) INFO:    [Backend]:         Progress: f7a0ebb44f93430fb1c4388a395eba96 14.20%/27.39
MiB/00:01:30

(18:25:31) INFO:    [Backend]:         Progress: f7a0ebb44f93430fb1c4388a395eba96 14.20%/29.28
MiB/00:01:36

(18:25:33) INFO:    [Backend]:         Progress: f7a0ebb44f93430fb1c4388a395eba96 19.32%/31.20
MiB/00:01:15

(18:25:34) INFO:    [Backend]:         Progress: f7a0ebb44f93430fb1c4388a395eba96 19.32%/32.14
MiB/00:01:19

(18:25:36) INFO:    [Backend]:         Progress: f7a0ebb44f93430fb1c4388a395eba96 19.32%/33.07
MiB/00:01:27

(18:25:37) INFO:    [Backend]:         Progress: f7a0ebb44f93430fb1c4388a395eba96 22.73%/36.81
MiB/00:01:14

(18:25:39) INFO:    [Backend]:         Progress: f7a0ebb44f93430fb1c4388a395eba96 28.41%/46.31
MiB/00:01:00

(18:25:40) INFO:    [Backend]:         Progress: f7a0ebb44f93430fb1c4388a395eba96 28.41%/46.31
MiB/00:01:03

(18:25:42) INFO:    [Backend]:         Progress: f7a0ebb44f93430fb1c4388a395eba96 28.41%/47.30
MiB/00:01:08

(18:25:43) INFO:    [Backend]:         Progress: f7a0ebb44f93430fb1c4388a395eba96 30.68%/49.28
MiB/00:01:03

(18:25:45) INFO:    [Backend]:         Progress: f7a0ebb44f93430fb1c4388a395eba96 32.39%/56.23
MiB/00:01:02

(18:25:46) INFO:    [Backend]:         Progress: f7a0ebb44f93430fb1c4388a395eba96 34.66%/59.21
MiB/00:00:58

(18:25:48) INFO:    [Backend]:         Progress: f7a0ebb44f93430fb1c4388a395eba96 35.80%/62.06
MiB/00:00:59

(18:25:49) INFO:    [Backend]:         Progress: f7a0ebb44f93430fb1c4388a395eba96 38.64%/64.05
MiB/00:00:54

(18:25:51) INFO:    [Backend]:         Progress: f7a0ebb44f93430fb1c4388a395eba96 39.20%/68.74
MiB/00:00:55

(18:25:53) INFO:    [Backend]:         Progress: f7a0ebb44f93430fb1c4388a395eba96 48.30%/73.91
MiB/00:00:40

(18:25:54) INFO:    [Backend]:         Progress: f7a0ebb44f93430fb1c4388a395eba96 48.86%/75.80
MiB/00:00:40

(18:25:59) INFO:    [Legendary]:       Getting More details with Legendary info command... 
(18:26:07) INFO:    [Legendary]:       Installed game list updated
(18:26:07) INFO:    [Legendary]:       Installed game list updated
(18:26:07) INFO:    [Backend]:         finished installing
(18:26:07) INFO:    [Frontend]:        Refreshing Library
(18:26:07) INFO:    [Gog]:             Getting GOG library
(18:26:08) INFO:    [Legendary]:       Getting More details with Legendary info command... 
(18:26:08) INFO:    [Gog]:             Number of library pages: 1
(18:26:08) INFO:    [Gog]:             Saved games data
(18:26:08) INFO:    [Legendary]:       Refreshing library...
(18:26:08) INFO:    [Legendary]:       Updating game list
(18:26:08) INFO:    [Legendary]:       Game List Updated
(18:26:10) INFO:    [Legendary]:       Getting More details with Legendary info command... 
(18:26:11) INFO:    [Legendary]:       Getting More details with Legendary info command... 
(18:26:15) INFO:    [Legendary]:       Getting More details with Legendary info command... 
(18:26:15) INFO:    [Legendary]:       Installing Salt with: /tmp/.mount_HeroicVff1rW/resources/app.asar.unpacked/build/bin/linux/legendary install Salt --platform Windows --base-path /home/jari/Games/Heroic --skip-dlcs --skip-sdl  -y |& tee "/home/jari/.config/heroic/GamesConfig/Salt.log"
(18:26:15) INFO:    [Backend]:         Progress: Salt /MiB/undefined
(18:26:16) INFO:    [Legendary]:       Getting More details with Legendary info command... 
(18:26:17) INFO:    [Backend]:         Progress: Salt /MiB/undefined
(18:26:18) INFO:    [Backend]:         Progress: Salt /MiB/undefined
(18:26:20) INFO:    [Backend]:         Progress: Salt 0.00%/0.00
MiB/00:00:00

(18:26:21) INFO:    [Backend]:         Progress: Salt 0.00%/0.00
MiB/00:00:00

(18:26:23) INFO:    [Backend]:         Progress: Salt 0.21%/2.76
MiB/00:31:59

(18:26:24) INFO:    [Backend]:         Progress: Salt 0.58%/3.38
MiB/00:14:13

(18:26:26) INFO:    [Backend]:         Progress: Salt 0.58%/4.09
MiB/00:19:55

(18:26:27) INFO:    [Backend]:         Progress: Salt 3.12%/5.76
MiB/00:04:08

(18:26:29) INFO:    [Backend]:         Progress: Salt 3.25%/8.75
MiB/00:04:58

(18:26:30) INFO:    [Backend]:         Progress: Salt 3.25%/8.75
MiB/00:05:28

(18:26:32) INFO:    [Backend]:         Progress: Salt 3.75%/20.73
MiB/00:05:34

(18:26:33) INFO:    [Backend]:         Progress: Salt 3.83%/22.73
MiB/00:05:51

(18:26:35) INFO:    [Backend]:         Progress: Salt 3.87%/23.73
MiB/00:06:37

(18:26:36) INFO:    [Backend]:         Progress: Salt 3.92%/25.73
MiB/00:06:57

(18:26:38) INFO:    [Backend]:         Progress: Salt 4.04%/31.72
MiB/00:07:31

(18:26:39) INFO:    [Backend]:         Progress: Salt 4.25%/37.72
MiB/00:07:31

(18:26:41) INFO:    [Backend]:         Progress: Salt 4.33%/39.72
MiB/00:08:06

(18:26:42) INFO:    [Backend]:         Progress: Salt 4.62%/40.72
MiB/00:07:55

(18:26:44) INFO:    [Backend]:         Progress: Salt 4.62%/42.71
MiB/00:08:36

(18:26:45) INFO:    [Backend]:         Progress: Salt 4.75%/44.72
MiB/00:08:42

(18:26:47) INFO:    [Backend]:         Progress: Salt 4.75%/46.71
MiB/00:09:22

(18:26:48) INFO:    [Backend]:         Progress: Salt 5.04%/52.71
MiB/00:09:07

(18:26:50) INFO:    [Backend]:         Progress: Salt 5.37%/58.71
MiB/00:09:06

(18:26:51) INFO:    [Backend]:         Progress: Salt 5.37%/60.71
MiB/00:09:24

(18:26:53) INFO:    [Backend]:         Progress: Salt 5.50%/62.71
MiB/00:09:45

(18:26:54) INFO:    [Backend]:         Progress: Salt 5.54%/65.41
MiB/00:09:57

(18:26:56) INFO:    [Backend]:         Progress: Salt 5.91%/71.38
MiB/00:09:49

(18:26:57) INFO:    [Backend]:         Progress: Salt 6.04%/75.37
MiB/00:09:51

(18:26:59) INFO:    [Backend]:         Progress: Salt 6.29%/78.36
MiB/00:09:56

(18:27:00) INFO:    [Backend]:         Progress: Salt 6.29%/78.36
MiB/00:10:11

(18:27:02) INFO:    [Backend]:         Progress: Salt 6.50%/84.34
MiB/00:10:19

(18:27:03) INFO:    [Backend]:         Progress: Salt 6.50%/84.34
MiB/00:10:33

(18:27:05) INFO:    [Backend]:         Progress: Salt 6.71%/90.33
MiB/00:10:40

(18:27:06) INFO:    [Backend]:         Progress: Salt 6.87%/91.54
MiB/00:10:37

(18:27:08) INFO:    [Backend]:         Progress: Salt 7.00%/96.08
MiB/00:10:52

(18:27:09) INFO:    [Backend]:         Progress: Salt 7.12%/99.08
MiB/00:10:52

(18:27:11) INFO:    [Backend]:         Progress: Salt 7.58%/103.95
MiB/00:10:34

(18:27:12) INFO:    [Backend]:         Progress: Salt 7.66%/105.95
MiB/00:10:39

(18:27:14) INFO:    [Backend]:         Progress: Salt 7.79%/109.95
MiB/00:10:51

(18:27:15) INFO:    [Backend]:         Progress: Salt 7.79%/112.94
MiB/00:11:03

(18:27:17) INFO:    [Backend]:         Progress: Salt 8.16%/117.93
MiB/00:10:53

(18:27:18) INFO:    [Backend]:         Progress: Salt 8.25%/119.92
MiB/00:10:57

(18:27:20) INFO:    [Backend]:         Progress: Salt 8.37%/122.92
MiB/00:11:08

(18:27:21) INFO:    [Backend]:         Progress: Salt 8.37%/124.92
MiB/00:11:19

(18:27:23) INFO:    [Backend]:         Progress: Salt 8.70%/131.89
MiB/00:11:12

(18:27:24) INFO:    [Backend]:         Progress: Salt 8.70%/132.89
MiB/00:11:22

(18:27:26) INFO:    [Backend]:         Progress: Salt 9.04%/137.87
MiB/00:11:15

### Steps to reproduce

Clear the default install directory setting?

### Expected behavior

Game would start installing when told to install.

### System Information

2.2.1 Heroic
21.04 Ubuntu

**Comment by Seraaron** [comment]
I'm also getting this issue. I wanted to change the default install folder to my other harddrive, and then when i click install on a GoG game it just hangs. This is my log when I try it

```
(12:44:52) INFO:    [Legendary]:       Location: "C:\Users\Seraaron\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\legendary.exe"
(12:44:52) INFO:    [Gog]:             Location: C:\Users\Seraaron\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\gogdl.exe
(12:45:01) INFO:    [Backend]:         
  Heroic Version: 2.2.4 Oden
  Legendary Version:  0.20.25 Our Benefactors
  OS: Microsoft Windows 10 Home KERNEL: 10.0.19044 ARCH: x64
  CPU: AMD Ryzen 5 3600 6-Core Processor @3.6 
  RAM: Total: 34.3 GB Available: 24.4 GB
  GRAPHICS: GPU0: NVIDIA GeForce RTX 2060 SUPER VRAM: 8192MB DRIVER: 511.23 
  
  
(12:45:01) INFO:    [Backend]:         User Not Found, removing it from Store
(12:45:01) INFO:    [Gog]:             Getting data about the user
(12:45:01) WARNING: [Backend]:         Protocol already registered.
(12:45:01) INFO:    [Gog]:             Saved user data to config
(12:45:02) INFO:    [Frontend]:        Refreshing Library
(12:45:02) INFO:    [Gog]:             Getting GOG library
(12:45:02) INFO:    [Gog]:             Number of library pages: 1
(12:45:02) INFO:    [Gog]:             Saved games data
(12:45:02) INFO:    [Legendary]:       Refreshing library...
(12:45:02) INFO:    [Frontend]:        No cache found, getting data from legendary...
(12:45:02) INFO:    [Legendary]:       Refreshing library...
(12:45:02) INFO:    [Gog]:             Found 0 game(s) to update
(12:45:06) INFO:    [Backend]:         checking for heroic updates
(12:46:22) ERROR:   [Gog]:             Info command failed "C:\Users\Seraaron\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\gogdl.exe" info 1412601690 --token="[REDACTED]" --lang=en-US --os windows

```

I don't have an Epic games account so I can't test that. Also when I hit 'reset' on the settings menu, the default install path doesn't come back. And I have no idea what it was before I changed it. So now the whole application is basically useless to me. :/

**Comment by flavioislima** [comment]
Can you guys try on the latest release?
@Seraaron the default folder it `$HOME/Games/Heroic`

Check if you guys have space available since this might be the same problem as #967

**Comment by snoozysoft** [comment]
Just writing in here to say I'm getting the exact same issue as Seraaron with GOG games. No indication of anything happening outside of a spinner and "Loading", with the log repeatedly stating "Info command failed". Epic games seems to install fine to a non default folder for me though there's not much indication again of anything happening and inexplicably it told me "Install cancelled" after it finished installing. Game was definitely actually installed despite that.

**Comment by Nocccer** [comment]
Does this still exist in new beta version (https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/releases/tag/v2.4.0-beta.2)?

I will close the ticket for now. If it is still a problem, reopen this ticket.
