### ISSUE TITLE
Add the ability to install windows games over the linux native (GOG Games)

### ISSUE THREAD

**Issue by Dragon20C** [Heroic-Games-Launcher/HeroicGamesLauncher#1037]
### Problem description

Some native games perform worse compared to their windows version, so installing the linux native version might not even work correctly!

### Feature description

I would love to have the ability to change which os version of the game I want to play.

**Comment by flavioislima** [comment]
Yes, this is duplicated.

**Comment by Dragon20C** [comment]
Sorry should of done a search before asking.
