### ISSUE TITLE
[GOG] Display info about game updates and allow to pin a specific version (like GOG Galaxy does it)

### ISSUE THREAD

**Issue by Nocifer** [Heroic-Games-Launcher/HeroicGamesLauncher#1038]
### Problem description

There are some cases where users may wish to forego a game update. The best and also first case that comes to mind is that of Witcher 3: it currently sits at 1.32, but every mod under the sun for that game is compatible with and only recommends the previous 1.31 version, because even though 1.32 officially only added a new Chinese localization, it also had a bunch of undocumented internal changes that messed up both the folder structure and the contents of some very critical files, which resulted in most mods (which are no longer updated by their creators because the game is too old) going haywire.

Another good case would be e.g. the recent(ish) release of Baldur's Gate Enhanced v2.6 patch, which rendered many mods incompatible that will need a substantial amount of time to be brought up to speed again.

In general, this feature request has mostly to do with modding in one way or another. Also, I know that updates do not install automatically, but still, my OCD is kind of triggered by this constant "NEW UPDATES YO!" label/icon in some of my game entries, because it makes me desperately want to update them :P

### Feature description

Add the ability to list game patch versions and to pin a game to a specific version; also, showing the changelogs (if they exist) would be a nice little addition.

### Alternatives

Completely turn off updates for a game (i.e. do not even show the "updates are available" label/icon).

**Comment by arrowgent** [comment]
is it supported by gog's api?  i know its in gog galaxy but doesnt mean its a public access api
just curious.

yes lots of games i dont update on purpose.

**Comment by flavioislima** [comment]
I think the best approach here would be to add a game setting to skip updates.

**Comment by arielj** [comment]
Closing, the latest release includes a fix for this
