### ISSUE TITLE
Only recently played games in library after update to 2.2.1

### ISSUE THREAD

**Issue by Pihkal82** [Heroic-Games-Launcher/HeroicGamesLauncher#1043]
### Describe the bug

Only recently played games are visible in library, all other games are missing after upgrade to latest version.
Was working fine before the update.

### Add logs

(18:30:51) INFO:    [Legendary]:       Location: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary
(18:30:51) INFO:    [Gog]:             Location: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl
(18:30:51) INFO:    [Backend]:         
  Heroic Version: 2.2.1 Oden
  Legendary Version:  0.20.25 Our Benefactors
  OS: ManjaroLinux KERNEL: 5.16.11-2-MANJARO ARCH: x64
  CPU: AMD Ryzen 5 3600 6-Core Processor @3.6 GOVERNOR: ondemand
  RAM: Total: 16.8 GB Available: 12.5 GB
  GRAPHICS: GPU0: Navi 10 [Radeon RX 5600 OEM/5600 XT / 5700/5700 XT] VRAM: 512MB DRIVER:  
  PROTOCOL: wayland
  
(18:30:52) WARNING: [Backend]:         Protocol already registered.
(18:30:52) INFO:    [Frontend]:        Refreshing Library
(18:30:52) INFO:    [Legendary]:       Refreshing library...
(18:30:52) INFO:    [Legendary]:       Refreshing Epic Games...
(18:30:52) INFO:    [Legendary]:       Refreshing Epic Games...
(18:30:52) INFO:    [Legendary]:       [cli] INFO: Logging in...
(18:30:52) INFO:    [Legendary]:       [Core] INFO: Trying to re-use existing login session...
(18:30:53) INFO:    [Legendary]:       [cli] INFO: Getting game list... (this may take a while)
(18:30:53) INFO:    [Legendary]:       Updating game list
(18:30:53) INFO:    [Legendary]:       Game List Updated
(18:30:54) INFO:    [Legendary]:       Checking for game updates
(18:30:54) INFO:    [Legendary]:       Found 0 game(s) to update
(18:30:54) INFO:    [Gog]:             Found 0 game(s) to update
(18:30:56) INFO:    [Backend]:         checking for heroic updates

### Steps to reproduce

Update to latest version on my machine....

### Expected behavior

Show all games.

### Screenshots

![image](https://user-images.githubusercontent.com/44177026/156813346-ec206771-9c69-4a88-b56d-701597122dd9.png)

### System Information

System:
  Kernel: 5.16.11-2-MANJARO x86_64 bits: 64 compiler: gcc v: 11.2.0
    parameters: BOOT_IMAGE=/boot/vmlinuz-5.16-x86_64
    root=UUID=7d1d7a9e-1068-40f1-8aef-7c288669f8a3 rw quiet splash apparmor=1
    security=apparmor udev.log_priority=3 amdgpu.ppfeaturemask=0xffffffff
  Console: pty pts/0 wm: gnome-shell DM: GDM 41.3 Distro: Manjaro Linux
    base: Arch Linux
CPU:
  Info: 6-core AMD Ryzen 5 3600 [MT MCP] arch: Zen 2 speed (MHz): avg: 2200
    min/max: 2200/5026
Graphics:
  Device-1: AMD Navi 10 [Radeon RX 5600 OEM/5600 XT / 5700/5700 XT]
    vendor: Gigabyte driver: amdgpu v: kernel pcie: gen: 4 speed: 16 GT/s
    lanes: 16 ports: active: DP-3 empty: DP-1,DP-2,HDMI-A-1 bus-ID: 0a:00.0
    chip-ID: 1002:731f class-ID: 0300
  Display: server: X.org v: 1.21.1.3 compositor: gnome-shell driver:
    gpu: amdgpu note:  X driver n/a resolution: 2560x1440~144Hz
  OpenGL: renderer: AMD Radeon RX 5700 XT (NAVI10 DRM 3.44.0
    5.16.11-2-MANJARO LLVM 13.0.1)
    v: 4.6 Mesa 21.3.7 direct render: Yes
Drives:
  Local Storage: total: 6.15 TiB lvm-free: 6.48 GiB used: 1.63 TiB (26.5%)
Info:
  Processes: 399 Uptime: 9m wakeups: 0 Memory: 15.62 GiB
  used: 4.06 GiB (26.0%) Init: systemd v: 250 tool: systemctl Compilers:
  gcc: 11.2.0 clang: 13.0.1 Packages: 1855 pacman: 1818 lib: 516 flatpak: 24
  snap: 13 Shell: Zsh (sudo) v: 5.8.1 default: Bash v: 5.1.16
  running-in: gnome-terminal inxi: 3.3.13

**Comment by flavioislima** [comment]
It's a known bug. Just click on your user name > manage accounts > continue.

**Comment by Pihkal82** [comment]
That worked, thanks!
Sorry, wasn't aware it was a known bug.
