### ISSUE TITLE
Heroic doesn't generate the json files for epic games that were copied over from local storage

### ISSUE THREAD

**Issue by DanBaur** [Heroic-Games-Launcher/HeroicGamesLauncher#1048]
### Describe the bug

I discovered that epic game json files (stored in ~/.config/heroic/GamesConfig/) are only generated if the game is downloaded from the internet. If I first copy the game files to the default installation path for heroic before clicking the install button the corresponding json files don't get generated.

### Add logs

(21:07:15) INFO:    [Legendary]:       Location: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary
(21:07:15) INFO:    [Gog]:             Location: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl
(21:07:15) INFO:    [Backend]:         
  Heroic Version: 2.2.1 Oden
  Legendary Version:  0.20.25 Our Benefactors
  OS: Fedora Linux KERNEL: 5.16.12-200.fc35.x86_64 ARCH: x64
  CPU: AMD Ryzen 5 3600 6-Core Processor @3.6 GOVERNOR: schedutil
  RAM: Total: 16.7 GB Available: 11.5 GB
  GRAPHICS: GPU0: Navi 10 [Radeon RX 5600 OEM/5600 XT / 5700/5700 XT] VRAM: 512MB DRIVER:  
  PROTOCOL: wayland
  
(21:07:16) WARNING: [Backend]:         Protocol already registered.
(21:07:16) INFO:    [Frontend]:        Refreshing Library
(21:07:16) INFO:    [Legendary]:       Refreshing library...
(21:07:16) INFO:    [Legendary]:       Refreshing Epic Games...
(21:07:16) INFO:    [Legendary]:       Refreshing Epic Games...
(21:07:17) INFO:    [Legendary]:       [cli] INFO: Logging in...
(21:07:17) INFO:    [Legendary]:       [Core] INFO: Logging in...
(21:07:17) INFO:    [Legendary]:       [cli] INFO: Getting game list... (this may take a while)
(21:07:18) INFO:    [Legendary]:       Updating game list
(21:07:18) INFO:    [Legendary]:       Game List Updated
(21:07:19) INFO:    [Legendary]:       Checking for game updates
(21:07:19) INFO:    [Legendary]:       Found 0 game(s) to update
(21:07:19) INFO:    [Gog]:             Found 0 game(s) to update
(21:07:21) INFO:    [Backend]:         checking for heroic updates
(21:17:59) INFO:    [Legendary]:       Getting Info from Epic API
(21:17:59) INFO:    [Legendary]:       Getting More details with Legendary info command... 
(21:24:56) ERROR:   [Legendary]:       Error Getting Info from Epic API
(21:24:56) INFO:    [Legendary]:       Getting More details with Legendary info command... 

### Steps to reproduce

copy /old_egs_directory/GameA/  to /default_heroic_installation_path/

search GameA in your library and then click install and wait for the file validation to finish

open ~/.config/heroic/GamesConfig/

### Expected behavior

I expected to see the JSON files for all my games including the vast majority of which were installed from local storage in the ~/.config/heroic/GamesConfig/ directory.

### System Information

- OS [Fedora 35]: 
- Heroic Version [2.1.1 rpm]:
all packages are up to date

### Additional information

I discovered this issue when I tried/failed to generate launcher scripts for my games using this:

https://api.mtr.pub/redromnon/HeroicBashLauncher

**Comment by flavioislima** [comment]
Can you replicate this on 2.3.2?

**Comment by DanBaur** [comment]
not replicable anymore on 2.3.2 or newer.
