### ISSUE TITLE
Support Rockstar Launcher

### ISSUE THREAD

**Issue by CHJ85** [Heroic-Games-Launcher/HeroicGamesLauncher#1049]
Hi there. Support for Rockstar games would be nice.
As a next major milestone in the Heroic launcher development, support for Rockstar games would make a lot of sense.
If Rockstar aren't gonna develop a Linux launcher, then someone has to do it. Because if you own a Rockstar game as a Linux user, you're kinda screwed unless you own it on Steam or Epic.

**Comment by flavioislima** [comment]
Sorry this is not planned at all. 
Its not easy and also not all launchers can be reverse-engineered especially when they have DRM.

**Comment by CHJ85** [comment]
@flavioislima Wait. The launcher has DRM?
Why? I mean. I can understand that the games have DRM in order to prevent piracy and whatnot.
But the launcher? 
Oh well.
Thanks anyway.

**Comment by flavioislima** [comment]
The games. 
Heroic needs to launch the games and the proprietary launcher controls the DRM.
That's why there is no alternative to steam, for instance. It is impossible to break their DRM and launch their games without calling the launcher itself
