### ISSUE TITLE
No longer seeing Library after upgrading to 2.2.2

### ISSUE THREAD

**Issue by bearcatjamboree** [Heroic-Games-Launcher/HeroicGamesLauncher#1053]
### Describe the bug

I just upgraded to 2.2.2 after being prompted to upgrade, and now I cant seem to get anything after logging in to Epic games.

### Add logs

(10:55:30) INFO:    [Legendary]:       Logging with Legendary...
(10:55:30) INFO:    [Legendary]:       Logging with Legendary...
(10:55:30) INFO:    [Legendary]:       stderr: [cli] INFO: Testing existing login data if present...

(10:55:30) INFO:    [Legendary]:       stderr: [Core] INFO: Trying to re-use existing login session...

(10:55:30) INFO:    [Legendary]:       stderr: [cli] INFO: Testing existing login data if present...
[Core] INFO: Trying to re-use existing login session...

(10:55:31) INFO:    [Legendary]:       Logging with Legendary...
(10:55:31) INFO:    [Legendary]:       stderr: [cli] INFO: Stored credentials are still valid, if you wish to switch to a different account, run "legendary auth --delete" and try again.

(10:55:31) INFO:    [Legendary]:       stderr: [cli] INFO: Stored credentials are still valid, if you wish to switch to a different account, run "legendary auth --delete" and try again.

(10:55:31) INFO:    [Legendary]:       finished login
(10:55:31) INFO:    [Legendary]:       finished login
(10:55:31) INFO:    [Legendary]:       stderr: [cli] INFO: Testing existing login data if present...

(10:55:31) INFO:    [Legendary]:       stderr: [Core] INFO: Trying to re-use existing login session...

(10:55:31) INFO:    [Legendary]:       stderr: [cli] INFO: Stored credentials are still valid, if you wish to switch to a different account, run "legendary auth --delete" and try again.

(10:55:31) INFO:    [Legendary]:       finished login
(10:55:36) INFO:    [Frontend]:        Refreshing Library
(10:55:36) INFO:    [Legendary]:       Refreshing library...
(10:55:36) INFO:    [Frontend]:        No cache found, getting data from legendary...
(10:55:36) INFO:    [Legendary]:       Refreshing library...

### Steps to reproduce

1. Go to App
2. Log in
3. No library

### Expected behavior

Go to App
Log in
See Library

### System Information

- Mac OS Monterey
- Heroic 2.2.2

**Comment by flavioislima** [comment]
Or maybe go to Manage Accounts and click continue. I thought this bug was fixed but maybe it wasn't on Mac.

**Comment by Henry-Hiles** [comment]
I had a similar issue, i just had to select epic games under library.

**Comment by raulcraveiro** [comment]
I can't access my library as well. Tried uninstalling and installing again and nothing happenned. I'm using macOS Monterey on Mac Mini M1.

**Comment by imLinguin** [comment]
We are aware of the issue. This is related to Windows and MacOS. For now downgrade to 2.2.1, hotfix for that will be released tomorrow.

**Comment by bearcatjamboree** [comment]
I tried but it is the same after I log in

Sent from my iPhone

On Mar 7, 2022, at 11:03 AM, Flávio F Lima ***@***.***> wrote:

﻿

Thats pretty weird. Can you try to Logout and Login Again?

—
Reply to this email directly, view it on GitHub<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FHeroic-Games-Launcher%2FHeroicGamesLauncher%2Fissues%2F1053%23issuecomment-1061027816&data=04%7C01%7Ccrbox%40crimson.ua.edu%7C1b4ad918c380470af08c08da006d3617%7C2a00728ef0d040b4a4e8ce433f3fbca7%7C0%7C0%7C637822766321056021%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=xjRtkPVEd9u1DPP7g2b%2BOEcBOfOt1U3b3TWz%2Fv9jeEE%3D&reserved=0>, or unsubscribe<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAV2REL5P7DUI5CXJQKFB27TU6ZHJJANCNFSM5QEFJDLQ&data=04%7C01%7Ccrbox%40crimson.ua.edu%7C1b4ad918c380470af08c08da006d3617%7C2a00728ef0d040b4a4e8ce433f3fbca7%7C0%7C0%7C637822766321056021%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=3L24jeliGlX5jk9hw5ArqtUwMPWwLMnSWybOTtKT%2BEY%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Ccrbox%40crimson.ua.edu%7C1b4ad918c380470af08c08da006d3617%7C2a00728ef0d040b4a4e8ce433f3fbca7%7C0%7C0%7C637822766321056021%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=Rtctj8LTC6zS6cRwND2AvamO9vUux%2BqariNFECTv1eg%3D&reserved=0> or Android<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Ccrbox%40crimson.ua.edu%7C1b4ad918c380470af08c08da006d3617%7C2a00728ef0d040b4a4e8ce433f3fbca7%7C0%7C0%7C637822766321056021%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=w5QcCSIN08IFsKT2%2Fr6IhRWkoZaLm99J6wuABZQvsUg%3D&reserved=0>.

**Comment by flavioislima** [comment]
was this fixed? otherwise try 2.2.6

**Comment by raulcraveiro** [comment]
It's working here! Heroic 2.2.6 on macOS. Thank you! 🥰
