### ISSUE TITLE
some games are missing

### ISSUE THREAD

**Issue by Shiroe93** [Heroic-Games-Launcher/HeroicGamesLauncher#1055]
### Describe the bug

some games like daemon x machina and genshin impact from the EGS are missing from my library in the launcher but present in the official client (I'm on windows)

### Add logs

(02:17:20) INFO:    [Legendary]:       Location: C:\Users\Shiroe\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\legendary.exe
(02:17:20) INFO:    [Gog]:             Location: C:\Users\Shiroe\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\gogdl.exe
(02:17:24) INFO:    [Backend]:         
  Heroic Version: 2.2.2 Oden
  Legendary Version:  0.20.25 Our Benefactors
  OS: Microsoft Windows 10 Enterprise KERNEL: 10.0.19044 ARCH: x64
  CPU: Intel Core™ i7-8700K @3.7 
  RAM: Total: 34.3 GB Available: 22.5 GB
  GRAPHICS: GPU0: Intel(R) UHD Graphics 630 VRAM: 1024MB DRIVER:  GPU1: NVIDIA GeForce RTX 3080 VRAM: 10240MB DRIVER: 511.79 
  
  
(02:17:24) INFO:    [Backend]:         User Not Found, removing it from Store
(02:17:24) INFO:    [Gog]:             Getting data about the user
(02:17:24) WARNING: [Backend]:         Protocol already registered.
(02:17:25) INFO:    [Gog]:             Saved user data to config
(02:17:25) INFO:    [Frontend]:        Refreshing Library
(02:17:25) INFO:    [Gog]:             Getting GOG library
(02:17:26) INFO:    [Gog]:             Number of library pages: 2
(02:17:26) INFO:    [Gog]:             Getting data for page 2
(02:17:26) INFO:    [Gog]:             Saved games data
(02:17:26) INFO:    [Legendary]:       Refreshing library...
(02:17:26) INFO:    [Frontend]:        No cache found, getting data from legendary...
(02:17:26) INFO:    [Legendary]:       Refreshing library...
(02:17:26) INFO:    [Gog]:             Found 0 game(s) to update
(02:17:30) INFO:    [Backend]:         checking for heroic updates
(02:17:45) INFO:    [Legendary]:       
(02:17:45) ERROR:   [Legendary]:       [cli] ERROR: Legendary is missing game metadata, please login (if not already) and use the "status" command to fetch necessary information to set-up syncing.

(02:18:05) INFO:    [Backend]:         Changing Language to: en
(02:18:14) INFO:    [Backend]:         Changing Tray icon Color...
(02:22:58) INFO:    [Frontend]:        Refreshing Library
(02:22:58) INFO:    [Gog]:             Getting GOG library
(02:22:59) INFO:    [Gog]:             Number of library pages: 2
(02:22:59) INFO:    [Gog]:             Getting data for page 2
(02:22:59) INFO:    [Gog]:             Saved games data
(02:22:59) INFO:    [Legendary]:       Refreshing library...
(02:22:59) INFO:    [Frontend]:        No cache found, getting data from legendary...
(02:22:59) INFO:    [Legendary]:       Refreshing library...

### Steps to reproduce

1. Go to library 
2 games are missing 

### Expected behavior

the previously mentioned games to show up in the list

### Screenshots

![Screenshot_342](https://user-images.githubusercontent.com/56954468/157148986-fcc507a3-d36d-428c-bb35-84a762821fa5.png)

### System Information

- OS windows
- Heroic Version 2.2.2 Oden

**Comment by 8Bitz0** [comment]
This is a current issue (see [#1053](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/issues/1053)). Until this is fixed use [v2.2.1](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/releases/tag/v2.2.1).

**Comment by Shiroe93** [comment]
No I don't think so because, unlike the issue you linked me to, I can see certain games but not others

**Comment by Shiroe93** [comment]
Because I used the search to show you the game that didn't show up but some others do appear

**Comment by Shiroe93** [comment]
Because I used the search to show you the game that didn't show up but some others do appear Il 9 mar 2022 08:59, Flávio F Lima ***@***.***> ha scritto:
I cannot see any game on your library.

**Comment by livejamie** [comment]
Daemon X Machina is also not showing for me in Heroic but also in the main client, also having this issue with Tiny Tina's Wonderlands

**Comment by Shiroe93** [comment]
After the last update (done a few minutes ago) the issue seems to be solved

**Comment by arielj** [comment]
@flavioislima I think this can be closed, issue seems to be solved.
