### ISSUE TITLE
Rocket League using Steam Proton

### ISSUE THREAD

**Issue by thePaulRichard** [Heroic-Games-Launcher/HeroicGamesLauncher#1056]
### Describe the bug

When trying to use the Proton from the steam (which is automatically detected), the game won't launch.
Download Proton from the Wine Manager works fine.

After some tests, I found that if I create the file **tracked_files** in **~/Games/Heroic/Prefixes/Rocket-League®/** the game will run normally with the Proton from the steam folder.

### Add logs

Launch Command: DXVK_HUD=fps STEAM_COMPAT_CLIENT_INSTALL_PATH=/home/paulrichard/.steam/steam STEAM_COMPAT_DATA_PATH='/home/paulrichard/Games/Heroic/Prefixes/Rocket-League®' /usr/bin/gamemoderun /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary launch Sugar --no-wine --wrapper "'/home/paulrichard/.steam/steam/steamapps/common/Proton - Experimental/proton' run"
        System Info:
        
  Heroic Version: 2.2.2 Oden
  Legendary Version:  0.20.25 Our Benefactors
  OS: Fedora Linux KERNEL: 5.16.11-200.fc35.x86_64 ARCH: x64
  CPU: Intel Core™ i5-10210U @1.6 GOVERNOR: powersave
  RAM: Total: 16.4 GB Available: 11.8 GB
  GRAPHICS: GPU0: CometLake-U GT2 [UHD Graphics]  VRAM: 512MB DRIVER:  
  PROTOCOL: wayland
  
        Game Settings: {
	"autoInstallDxvk": false,
	"autoInstallVkd3d": false,
	"maxSharpness": 2,
	"launcherArgs": "",
	"nvidiaPrime": false,
	"otherOptions": "",
	"savesPath": "",
	"showFps": true,
	"targetExe": "",
	"useGameMode": true,
	"wineCrossoverBottle": "Heroic",
	"winePrefix": "/home/paulrichard/Games/Heroic/Prefixes/Rocket-League®",
	"wineVersion": {
		"bin": "'/home/paulrichard/.steam/steam/steamapps/common/Proton - Experimental/proton'",
		"name": "Proton - Proton - Experimental",
		"type": "proton"
	},
	"useSteamRuntime": false
}

        Game Log:
        [cli] INFO: Logging in...
[Core] INFO: Trying to re-use existing login session...
[cli] INFO: Checking for updates...
[Core] INFO: Getting authentication token...
[cli] INFO: Launching Sugar...
gamemodeauto: 
Proton: Upgrading prefix from None to 7.0-100 (/home/paulrichard/Games/Heroic/Prefixes/Rocket-League®/)
Traceback (most recent call last):
  File "/home/paulrichard/.steam/steam/steamapps/common/Proton - Experimental/proton", line 1401, in <module>
    g_session.init_session(sys.argv[1] != "runinprefix")
  File "/home/paulrichard/.steam/steam/steamapps/common/Proton - Experimental/proton", line 1206, in init_session
    g_compatdata.setup_prefix()
  File "/home/paulrichard/.steam/steam/steamapps/common/Proton - Experimental/proton", line 806, in setup_prefix
    self.update_builtin_libs(builtin_dll_copy)
  File "/home/paulrichard/.steam/steam/steamapps/common/Proton - Experimental/proton", line 605, in update_builtin_libs
    with open(self.tracked_files_file, "r") as tracked_files:
FileNotFoundError: [Errno 2] No such file or directory: '/home/paulrichard/Games/Heroic/Prefixes/Rocket-League®/tracked_files'

        

### Steps to reproduce

1. Go to '...' Heroic - Rocket League
2. Click on '...' Play
3. See an error

### Expected behavior

The game should be launched.

### System Information

- OS [e. g. "Ubuntu"]: Fedora 35 
- Heroic Version [e. g. 2.1.1]: 2.2.2

### Additional information

After execute the following command:
 `touch ~/Games/Heroic/Prefixes/Rocket-League®/tracked_files`

The game runs normally.

**Comment by thePaulRichard** [comment]
[tracked_files.zip](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/files/8202506/tracked_files.zip)

If curious, this is the content of the file, after running the game.

**Comment by flavioislima** [comment]
When I get this error normally I need to create a new prefix.
Eventually we will add support for steam runtime for proton so this will improve the compatibility.
Also, try using Wine-GE + DXVK and keep proton as last resource.
