### ISSUE TITLE
Alternative GOGDL Binary not working

### ISSUE THREAD

**Issue by redromnon** [Heroic-Games-Launcher/HeroicGamesLauncher#1057]
### Describe the bug

The **Choose an Alternative GOGDL Binary to use** doesn't save the path to the gogdl's binary location. It instead tries to save in **Choose an Alternative Legendary Binary** and says _Invalid_ under the field (since it doesn't find a legendary binary but a gogdl one).

### Add logs

Nothing related to specifying alternative GOG binary shows in the log.

### Steps to reproduce

1. Go to **Settings**
2. Under **Global Settings**
3. Click on folder icon in **Choose an Alternative GOGDL Binary to use**

### Expected behavior

Display and store the path to the gogdl's binary location

### Screenshots

![Heroic_alt_GOG_binary_issue](https://user-images.githubusercontent.com/74495920/157187567-003d7ac0-a2cc-4324-bd1f-356177caa12d.png)

### System Information

- OS: Pop OS 20.04
- Heroic Version: 2.2.2

### Additional information

None

**Comment by imLinguin** [comment]
Don't know if it matters but on the screenshot you pasted the location in Legendary field.

**Comment by redromnon** [comment]
I've uploaded a video for better clarity. Here's what happens -

https://user-images.githubusercontent.com/74495920/157199030-00b9d235-06a7-4732-b3db-28dcd64c57f5.mp4

**Comment by flavioislima** [comment]
Yes, I will fix it on my PR.
