### ISSUE TITLE
[Windows/Mac] Cannot login into to the EGS after updating to 2.2.2

### ISSUE THREAD

**Issue by Rafii2198** [Heroic-Games-Launcher/HeroicGamesLauncher#1058]
### Describe the bug

So I suffered from the similar bug from #1053, I could only see my recently played games, but in addition, I couldn't launch them at all. I then decided to clear cache, I thought it might help but it got worse, (if I understand logs correctly) it seems like Heroic thinks I am logged out but Legendary says I am logged it and whenever I try to log into the EGS nothing happens at all.
Upgrading on my Linux machine did not suffer from any of this stuff.

### Add logs

```
(13:22:27) INFO:    [Legendary]:       Location: C:\Users\Rafii2198\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\legendary.exe
(13:22:27) INFO:    [Gog]:             Location: C:\Users\Rafii2198\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\gogdl.exe
(13:22:31) INFO:    [Backend]:         
  Heroic Version: 2.2.2 Oden
  Legendary Version:  0.20.25 Our Benefactors
  OS: Microsoft Windows 10 Home KERNEL: 10.0.19043 ARCH: x64
  CPU: AMD Ryzen 5 1600X Six-Core Processor @3.6 
  RAM: Total: 34.3 GB Available: 25.5 GB
  GRAPHICS: GPU0: Radeon RX 580 Series VRAM: 8192MB DRIVER:  
  
  
(13:22:31) INFO:    [Backend]:         User Not Found, removing it from Store
(13:22:31) WARNING: [Backend]:         Protocol already registered.
(13:22:37) INFO:    [Backend]:         checking for heroic updates
(13:27:22) INFO:    [Legendary]:       Logging with Legendary...
(13:27:22) INFO:    [Legendary]:       stderr: [cli] INFO: Testing existing login data if present...

(13:27:22) INFO:    [Legendary]:       stderr: [Core] INFO: Trying to re-use existing login session...

(13:27:23) INFO:    [Legendary]:       stderr: [cli] INFO: Stored credentials are still valid, if you wish to switch to a different account, run "legendary auth --delete" and try again.

(13:27:23) INFO:    [Legendary]:       finished login
(13:27:23) INFO:    [Frontend]:        Called Login
(13:27:41) INFO:    [Gog]:             Logging using GOG credentials
(13:27:41) INFO:    [Gog]:             Login Successful
(13:27:41) INFO:    [Gog]:             Getting data about the user
(13:27:41) INFO:    [Gog]:             Saved user data to config
```

### Steps to reproduce

1. Go to log in section
2. Click on any of both login methods (same results)
3. Log in
4. You'll still see log in section, without being logged in

### Expected behavior

I should be logged into EGS

### System Information

- OS: Windows 10
- Heroic Version: 2.2.2

**Comment by mirronake** [comment]
Same

**Comment by mirronake** [comment]
![image](https://user-images.githubusercontent.com/96698262/157241274-94690cdd-8e17-4f24-b605-10cdffc28460.png)
After press "Continue" button in Log in menu

**Comment by flavioislima** [comment]
@mirronake can you test the build from here after finish:
https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/actions/runs/1951496755

**Comment by mirronake** [comment]
Waiting build

**Comment by mirronake** [comment]
It did not help, it is still not authorized

https://user-images.githubusercontent.com/96698262/157245266-9150c383-d778-4666-86da-d2fb6c306451.mp4

.

**Comment by flavioislima** [comment]
Can you go to Settings >  Logs again?
Paste them here.

**Comment by mirronake** [comment]
(15:17:24) INFO:    [Legendary]:       Location: C:\Users\MARTIN\AppData\Local\Temp\266X6ctbTNpY1lcZiT1rir0i16l\resources\app.asar.unpacked\build\bin\win32\legendary.exe
(15:17:24) INFO:    [Gog]:             Location: C:\Users\MARTIN\AppData\Local\Temp\266X6ctbTNpY1lcZiT1rir0i16l\resources\app.asar.unpacked\build\bin\win32\gogdl.exe
(15:17:32) INFO:    [Backend]:         
  Heroic Version: 2.2.3 Oden
  Legendary Version:  0.20.25 Our Benefactors
  OS: Microsoft Windows 11 Pro KERNEL: 10.0.22000 ARCH: x64
  CPU: Intel Core™ i7-9700K @3.6 
  RAM: Total: 17.1 GB Available: 13.1 GB
  GRAPHICS: GPU0: NVIDIA GeForce GTX 1060 3GB VRAM: 3072MB DRIVER: 511.79 
  
  
(15:17:32) INFO:    [Backend]:         User Not Found, removing it from Store
(15:17:32) WARNING: [Backend]:         Protocol already registered.
(15:17:37) INFO:    [Legendary]:       Logging with Legendary...
(15:17:37) INFO:    [Backend]:         checking for heroic updates
(15:17:37) INFO:    [Legendary]:       stderr: [cli] INFO: Testing existing login data if present...

(15:17:37) INFO:    [Legendary]:       stderr: [Core] INFO: Trying to re-use existing login session...

(15:17:38) INFO:    [Legendary]:       Logging with Legendary...
(15:17:38) INFO:    [Legendary]:       Logging with Legendary...
(15:17:38) INFO:    [Legendary]:       stderr: [cli] INFO: Stored credentials are still valid, if you wish to switch to a different account, run "legendary auth --delete" and try again.

(15:17:38) INFO:    [Legendary]:       finished login
(15:17:38) INFO:    [Legendary]:       stderr: [cli] INFO: Testing existing login data if present...
[Core] INFO: Trying to re-use existing login session...

(15:17:38) INFO:    [Legendary]:       stderr: [cli] INFO: Testing existing login data if present...
[Core] INFO: Trying to re-use existing login session...

(15:17:38) INFO:    [Legendary]:       stderr: [cli] INFO: Stored credentials are still valid, if you wish to switch to a different account, run "legendary auth --delete" and try again.

(15:17:38) INFO:    [Legendary]:       stderr: [cli] INFO: Stored credentials are still valid, if you wish to switch to a different account, run "legendary auth --delete" and try again.

(15:17:38) INFO:    [Legendary]:       finished login
(15:17:38) INFO:    [Legendary]:       finished login
(15:17:40) INFO:    [Frontend]:        Refreshing Library
(15:17:40) INFO:    [Legendary]:       Refreshing library...
(15:17:40) INFO:    [Frontend]:        No cache found, getting data from legendary...
(15:17:40) INFO:    [Legendary]:       Refreshing library...

**Comment by flavioislima** [comment]
found the issue, try this one now: https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/actions/runs/1951663814
tried here on windows and it worked fine

**Comment by mirronake** [comment]
It was not even necessary to log in, the problem was solved.

**Comment by mirronake** [comment]
![image](https://user-images.githubusercontent.com/96698262/157250116-d9267450-ce54-4dbd-a7ff-1845321daa33.png)
Now my games are not displayed.

**Comment by mirronake** [comment]
(15:43:51) INFO:    [Legendary]:       Location: C:\Users\MARTIN\AppData\Local\Temp\266bFGLICkFHBQCl3bTWzx3Dk6F\resources\app.asar.unpacked\build\bin\win32\legendary.exe
(15:43:51) INFO:    [Gog]:             Location: C:\Users\MARTIN\AppData\Local\Temp\266bFGLICkFHBQCl3bTWzx3Dk6F\resources\app.asar.unpacked\build\bin\win32\gogdl.exe
(15:43:59) INFO:    [Backend]:         
  Heroic Version: 2.2.3 Oden
  Legendary Version:  0.20.25 Our Benefactors
  OS: Microsoft Windows 11 Pro KERNEL: 10.0.22000 ARCH: x64
  CPU: Intel Core™ i7-9700K @3.6 
  RAM: Total: 17.1 GB Available: 11.7 GB
  GRAPHICS: GPU0: NVIDIA GeForce GTX 1060 3GB VRAM: 3072MB DRIVER: 511.79 
  
  
(15:44:00) INFO:    [Backend]:         Registered protocol with OS.
(15:44:00) INFO:    [Frontend]:        Refreshing Library
(15:44:00) INFO:    [Legendary]:       Refreshing library...
(15:44:00) INFO:    [Legendary]:       Refreshing Epic Games...
(15:44:00) INFO:    [Legendary]:       Refreshing Epic Games...
(15:44:01) INFO:    [Legendary]:       [cli] INFO: Logging in...
(15:44:01) INFO:    [Legendary]:       [Core] INFO: Trying to re-use existing login session...
(15:44:01) INFO:    [Legendary]:       [cli] INFO: Getting game list... (this may take a while)
(15:44:02) INFO:    [Legendary]:       [Core] INFO: Fetching metadata for 12 app(s).
(15:44:02) INFO:    [Legendary]:       Updating game list
(15:44:02) INFO:    [Legendary]:       Game List Updated
(15:44:02) INFO:    [Frontend]:        No cache found, getting data from legendary...
(15:44:02) INFO:    [Legendary]:       Refreshing library...
(15:44:02) INFO:    [Legendary]:       Updating game list
(15:44:02) INFO:    [Legendary]:       Game List Updated
(15:44:03) INFO:    [Legendary]:       Checking for game updates
(15:44:03) INFO:    [Legendary]:       Found 0 game(s) to update
(15:44:03) INFO:    [Gog]:             Found 0 game(s) to update
(15:44:03) INFO:    [Frontend]:        Force Update
(15:44:05) INFO:    [Backend]:         checking for heroic updates
(15:44:55) INFO:    [Frontend]:        Refreshing Library
(15:44:55) INFO:    [Legendary]:       Refreshing library...
(15:44:55) INFO:    [Legendary]:       Refreshing Epic Games...
(15:44:55) INFO:    [Legendary]:       Refreshing Epic Games...
(15:44:56) INFO:    [Legendary]:       [cli] INFO: Logging in...
(15:44:56) INFO:    [Legendary]:       [Core] INFO: Trying to re-use existing login session...
(15:44:56) INFO:    [Legendary]:       [cli] INFO: Getting game list... (this may take a while)
(15:44:56) INFO:    [Legendary]:       Updating game list
(15:44:56) INFO:    [Legendary]:       Game List Updated
(15:44:57) INFO:    [Legendary]:       Checking for game updates
(15:44:57) INFO:    [Legendary]:       Found 0 game(s) to update
(15:44:57) INFO:    [Gog]:             Found 0 game(s) to update
(15:45:02) INFO:    [Frontend]:        Refreshing Library
(15:45:02) INFO:    [Legendary]:       Refreshing library...
(15:45:02) INFO:    [Legendary]:       Refreshing Epic Games...
(15:45:02) INFO:    [Legendary]:       Refreshing Epic Games...
(15:45:03) INFO:    [Legendary]:       [cli] INFO: Logging in...
(15:45:03) INFO:    [Legendary]:       [Core] INFO: Trying to re-use existing login session...
(15:45:03) INFO:    [Legendary]:       [cli] INFO: Getting game list... (this may take a while)
(15:45:04) INFO:    [Legendary]:       Updating game list
(15:45:04) INFO:    [Legendary]:       Game List Updated
(15:45:05) INFO:    [Legendary]:       Checking for game updates
(15:45:05) INFO:    [Legendary]:       Found 0 game(s) to update
(15:45:05) INFO:    [Gog]:             Found 0 game(s) to update
(15:45:13) INFO:    [Frontend]:        Refreshing Library
(15:45:13) INFO:    [Legendary]:       Refreshing library...
(15:45:13) INFO:    [Gog]:             Found 0 game(s) to update
(15:45:19) INFO:    [Backend]:         checking for heroic updates
(15:45:44) INFO:    [Legendary]:       Logging with Legendary...
(15:45:44) INFO:    [Legendary]:       stderr: [cli] INFO: Testing existing login data if present...

(15:45:45) INFO:    [Legendary]:       Logging with Legendary...
(15:45:45) INFO:    [Legendary]:       Logging with Legendary...
(15:45:45) INFO:    [Legendary]:       stderr: [cli] INFO: Testing existing login data if present...

(15:45:45) INFO:    [Legendary]:       stderr: [cli] INFO: Testing existing login data if present...

(15:45:45) ERROR:   [Legendary]:       [Core] ERROR: Getting exchange code failed: {'errorCode': 'errors.com.epicgames.unauthorized', 'message': 'You are not authenticated. Please authenticate.', 'correlationId': '14924640-9ee6-11ec-b00d-adb31036a5ab'}
[cli] CRITICAL: No exchange token, cannot login.

(15:45:45) INFO:    [Legendary]:       finished login
(15:45:46) INFO:    [Legendary]:       stderr: [cli] INFO: Successfully logged in as "MIRRO_NAKE"

(15:45:46) INFO:    [Legendary]:       stderr: [cli] INFO: Successfully logged in as "MIRRO_NAKE"

(15:45:46) INFO:    [Legendary]:       finished login
(15:45:46) INFO:    [Legendary]:       finished login
(15:45:48) INFO:    [Frontend]:        Refreshing Library
(15:45:48) INFO:    [Legendary]:       Refreshing library...
(15:45:48) INFO:    [Legendary]:       Refreshing Epic Games...
(15:45:48) INFO:    [Legendary]:       Refreshing Epic Games...
(15:45:49) INFO:    [Legendary]:       [cli] INFO: Logging in...
(15:45:49) INFO:    [Legendary]:       [Core] INFO: Trying to re-use existing login session...
(15:45:49) INFO:    [Legendary]:       [cli] INFO: Getting game list... (this may take a while)
(15:45:50) INFO:    [Legendary]:       Updating game list
(15:45:50) INFO:    [Legendary]:       Game List Updated
(15:45:50) INFO:    [Frontend]:        No cache found, getting data from legendary...
(15:45:50) INFO:    [Legendary]:       Refreshing library...
(15:45:50) INFO:    [Legendary]:       Updating game list
(15:45:50) INFO:    [Legendary]:       Game List Updated
(15:45:50) INFO:    [Frontend]:        Force Update
(15:45:51) INFO:    [Frontend]:        Refreshing Library
(15:45:51) INFO:    [Legendary]:       Refreshing library...
(15:45:51) INFO:    [Legendary]:       Refreshing Epic Games...
(15:45:51) INFO:    [Legendary]:       Refreshing Epic Games...
(15:45:52) INFO:    [Legendary]:       [cli] INFO: Logging in...
[Core] INFO: Trying to re-use existing login session...
(15:45:52) INFO:    [Legendary]:       [cli] INFO: Getting game list... (this may take a while)
(15:45:52) INFO:    [Legendary]:       Updating game list
(15:45:52) INFO:    [Legendary]:       Game List Updated
(15:45:53) INFO:    [Legendary]:       Checking for game updates
(15:45:53) INFO:    [Legendary]:       Found 0 game(s) to update
(15:45:53) INFO:    [Gog]:             Found 0 game(s) to update
(15:46:33) INFO:    [Frontend]:        Refreshing Library
(15:46:33) INFO:    [Legendary]:       Refreshing library...
(15:46:33) INFO:    [Legendary]:       Refreshing Epic Games...
(15:46:33) INFO:    [Legendary]:       Refreshing Epic Games...
(15:46:34) INFO:    [Legendary]:       [cli] INFO: Logging in...
(15:46:34) INFO:    [Legendary]:       [Core] INFO: Trying to re-use existing login session...
(15:46:34) INFO:    [Legendary]:       [cli] INFO: Getting game list... (this may take a while)
(15:46:34) INFO:    [Legendary]:       Updating game list
(15:46:34) INFO:    [Legendary]:       Game List Updated
(15:46:35) INFO:    [Legendary]:       Checking for game updates
(15:46:35) INFO:    [Legendary]:       Found 0 game(s) to update
(15:46:35) INFO:    [Gog]:             Found 0 game(s) to update

**Comment by flavioislima** [comment]
pretty weird. This I cannot reproduce.
I am sending some new fixes, check them after the build https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/runs/5465349310?check_suite_focus=true

**Comment by mirronake** [comment]
It didn't help, the games are still not displayed.
![image](https://user-images.githubusercontent.com/96698262/157253573-81b7edbc-546d-47e8-a145-88de8d74a595.png)

(16:04:53) INFO:    [Legendary]:       Location: C:\Users\MARTIN\AppData\Local\Temp\266dzHQvVO8DlSllMomTM8iXhVq\resources\app.asar.unpacked\build\bin\win32\legendary.exe
(16:04:53) INFO:    [Gog]:             Location: C:\Users\MARTIN\AppData\Local\Temp\266dzHQvVO8DlSllMomTM8iXhVq\resources\app.asar.unpacked\build\bin\win32\gogdl.exe
(16:05:02) INFO:    [Backend]:         
  Heroic Version: 2.2.3 Oden
  Legendary Version:  0.20.25 Our Benefactors
  OS: Microsoft Windows 11 Pro KERNEL: 10.0.22000 ARCH: x64
  CPU: Intel Core™ i7-9700K @3.6 
  RAM: Total: 17.1 GB Available: 11.7 GB
  GRAPHICS: GPU0: NVIDIA GeForce GTX 1060 3GB VRAM: 3072MB DRIVER: 511.79 
  
  
(16:05:02) INFO:    [Backend]:         Registered protocol with OS.
(16:05:02) INFO:    [Frontend]:        Refreshing Library
(16:05:02) INFO:    [Legendary]:       Refreshing library...
(16:05:02) INFO:    [Legendary]:       Refreshing Epic Games...
(16:05:02) INFO:    [Legendary]:       Refreshing Epic Games...
(16:05:03) INFO:    [Legendary]:       [cli] INFO: Logging in...
(16:05:03) INFO:    [Legendary]:       [Core] INFO: Trying to re-use existing login session...
(16:05:03) INFO:    [Legendary]:       [cli] INFO: Getting game list... (this may take a while)
(16:05:04) INFO:    [Legendary]:       Updating game list
(16:05:04) INFO:    [Legendary]:       Game List Updated
(16:05:05) INFO:    [Frontend]:        Refreshing Library
(16:05:05) INFO:    [Legendary]:       Refreshing library...
(16:05:05) INFO:    [Legendary]:       Refreshing Epic Games...
(16:05:05) INFO:    [Legendary]:       Refreshing Epic Games...
(16:05:05) INFO:    [Legendary]:       Checking for game updates
(16:05:05) INFO:    [Legendary]:       Found 0 game(s) to update
(16:05:05) INFO:    [Gog]:             Found 0 game(s) to update
(16:05:05) INFO:    [Legendary]:       [cli] INFO: Logging in...
(16:05:05) INFO:    [Legendary]:       [Core] INFO: Trying to re-use existing login session...
(16:05:06) INFO:    [Legendary]:       [cli] INFO: Getting game list... (this may take a while)
(16:05:06) INFO:    [Legendary]:       Updating game list
(16:05:06) INFO:    [Legendary]:       Game List Updated
(16:05:07) INFO:    [Backend]:         checking for heroic updates
(16:05:07) INFO:    [Legendary]:       Checking for game updates
(16:05:07) INFO:    [Legendary]:       Found 0 game(s) to update
(16:05:07) INFO:    [Gog]:             Found 0 game(s) to update
(16:05:15) INFO:    [Frontend]:        Refreshing Library
(16:05:15) INFO:    [Legendary]:       Refreshing library...
(16:05:15) INFO:    [Legendary]:       Refreshing Epic Games...
(16:05:15) INFO:    [Legendary]:       Refreshing Epic Games...
(16:05:16) INFO:    [Legendary]:       [cli] INFO: Logging in...
(16:05:16) INFO:    [Legendary]:       [Core] INFO: Trying to re-use existing login session...
(16:05:16) INFO:    [Legendary]:       [cli] INFO: Getting game list... (this may take a while)
(16:05:17) INFO:    [Legendary]:       Updating game list
(16:05:17) INFO:    [Legendary]:       Game List Updated
(16:05:18) INFO:    [Legendary]:       Checking for game updates
(16:05:18) INFO:    [Legendary]:       Found 0 game(s) to update
(16:05:18) INFO:    [Gog]:             Found 0 game(s) to update

**Comment by flavioislima** [comment]
That's pretty weird, other people tested on discord and it worked. Can you go to Settings and click on Reset Heroic?
It wont delete your games or your credentials.

**Comment by mirronake** [comment]
https://user-images.githubusercontent.com/96698262/157254891-cec71437-6ce3-4855-b8aa-cc0fc972c92c.mp4

**Comment by flavioislima** [comment]
Ok. Lets drop the bomb then:
Delete/rename the folder:
USERNAME/.config/legendary
USERNAME/.config/heroic
APPDATA/Roaming/heroic

And try to login again.

**Comment by flavioislima** [comment]
maybe go to our discord and we can help there, its faster than here

**Comment by mirronake** [comment]
I must say right away that I do not know English, so I use a translator.

**Comment by mirronake** [comment]
Logged into Discord Server
