### ISSUE TITLE
Cannot load the library

### ISSUE THREAD

**Issue by DJdijana** [Heroic-Games-Launcher/HeroicGamesLauncher#1065]
### Describe the bug

I have installed multiple versions of Heroic and for some reason the library won't open in none of them. This means that for the newer versions when I logged in to Heroic I could use my account in the store, but the library wouldn't load and when I clicked login or external login again it would return to the same page. For some older versions the launcher would load endlessly when I entered the SID number. 

### Add logs

(17:10:50) INFO:    [Legendary]:       Location: /tmp/.mount_Heroicel6KE7/resources/app.asar.unpacked/build/bin/linux/legendary
(17:10:50) INFO:    [Gog]:             Location: /tmp/.mount_Heroicel6KE7/resources/app.asar.unpacked/build/bin/linux/gogdl
(17:10:52) ERROR:   [Legendary]:       Error: Command failed: /tmp/.mount_Heroicel6KE7/resources/app.asar.unpacked/build/bin/linux/legendary --version
[1459] Error loading Python lib '/tmp/_MEIT8hlwT/libpython3.8.so.1.0': dlopen: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.25' not found (required by /tmp/_MEIT8hlwT/libpython3.8.so.1.0)

(17:10:53) INFO:    [Backend]:         
  Heroic Version: 2.2.3 Oden
  Legendary Version: invalid
  OS: LinuxMint KERNEL: 4.10.0-38-generic ARCH: x64
  CPU: Intel Pentium® 4 3.00GHz @2.9 GOVERNOR: ondemand
  RAM: Total: 4.14 GB Available: 2.2 GB
  GRAPHICS: GPU0: Caicos [Radeon HD 6450/7450/8450 / R5 230 OEM] VRAM: 128MB DRIVER:  
  PROTOCOL: x11
  
(17:10:53) INFO:    [Backend]:         User Not Found, removing it from Store
(17:10:53) ERROR:   [Backend]:         Failed to register protocol with OS.
(17:11:01) INFO:    [Backend]:         checking for heroic updates
(17:11:16) INFO:    [Legendary]:       Logging with Legendary...
(17:11:16) INFO:    [Legendary]:       Logging with Legendary...
(17:11:16) INFO:    [Legendary]:       stderr: [1581] Error loading Python lib '/tmp/_MEIsnn7Pp/libpython3.8.so.1.0': dlopen: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.25' not found (required by /tmp/_MEIsnn7Pp/libpython3.8.so.1.0)

(17:11:16) INFO:    [Legendary]:       finished login
(17:11:17) INFO:    [Legendary]:       stderr: [1582] Error loading Python lib '/tmp/_MEIn9UqQs/libpython3.8.so.1.0': dlopen: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.25' not found (required by /tmp/_MEIn9UqQs/libpython3.8.so.1.0)

(17:11:17) INFO:    [Legendary]:       finished login
(17:11:56) ERROR:   [Gog]:             Error: Command failed: "/tmp/.mount_Heroicel6KE7/resources/app.asar.unpacked/build/bin/linux/gogdl" --version
[1645] Error loading Python lib '/tmp/_MEIVgtl4H/libpython3.9.so.1.0': dlopen: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /tmp/_MEIVgtl4H/libpython3.9.so.1.0)

(17:11:56) ERROR:   [Legendary]:       Error: Command failed: /tmp/.mount_Heroicel6KE7/resources/app.asar.unpacked/build/bin/linux/legendary --version
[1647] Error loading Python lib '/tmp/_MEIx9r8lX/libpython3.8.so.1.0': dlopen: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.25' not found (required by /tmp/_MEIx9r8lX/libpython3.8.so.1.0)

### Steps to reproduce

Log in
No library

### Expected behavior

I would expect that the login page would disappear and my library appears.

### System Information

- OS Linux Mint 18.3
- Heroic Version 2.2.3

**Comment by flavioislima** [comment]
can you try now on 2.2.6?

**Comment by flavioislima** [comment]
This is a GLIBC issue, you can find other issues that were fixed here on github about it.
