### ISSUE TITLE
[macOS] 2.2.4 ignores wineprefix and creates empty .wine in home directory

### ISSUE THREAD

**Issue by bearcatjamboree** [Heroic-Games-Launcher/HeroicGamesLauncher#1066]
### Describe the bug

defaultWinePrefix and winePrefix are both specified in the config.json file but Heroic creates a ~/.wine path with nothing inside and tries to launch the game using that environment instead of the one specified.

### Add logs

(13:17:44) INFO:    [Backend]:         launching Rocket League® Sugar
(13:17:44) INFO:    [Legendary]:       Launch Command: /opt/homebrew/bin/legendary launch Sugar --wine '/Users/cboxgo/Applications/Legendary.app/Contents/SharedSupport/wine/bin/wine32on64' --wine-prefix '/Users/cboxgo/.wine'
(13:18:07) INFO:    [Backend]:         Log was written to /Users/cboxgo/Library/Application Support/heroic/GamesConfig/Sugar-lastPlay.log

### Steps to reproduce

Add wineprefix to config.json and run game

### Expected behavior

use existing prefix instead of creating a new one

### System Information

- Mac OS Monterey 
- Heroic Version 2.2.4

**Comment by bearcatjamboree** [comment]
Are you no longer using the .config/heroic directory?  I removed and reinstalled heroic and it doesn't seem to create the config.json or anything anymore...

**Comment by flavioislima** [comment]
For now heroic doesn't support Wine on Mac, only Crossover.
This was because Wine itself wasn't working on a Mac and the compatibility without DXVK is pretty low.
So we have removed the wineprefix option. If you can see the `defaultWinePrefix` then we should remove it as well.
Only the Default Bottle should be shown.

**Comment by flavioislima** [comment]
Heroic settings on Mac now follow the standard for other apps there so the settings are on ˜/Library/ApplicationSupport/heroic.
One way you can overcome this issue, if you really want to use wine, is to edit the config.json manually on that folder.

**Comment by flavioislima** [comment]
Closing this issue since, like I said, we don't support wine on Mac.

**Comment by flavioislima** [comment]
We bundle the current release version of legendary.
