### ISSUE TITLE
[All] Can't login to Epic Games in Heroic 2.2.4

### ISSUE THREAD

**Issue by anhinton** [Heroic-Games-Launcher/HeroicGamesLauncher#1067]
### Describe the bug

After doing a fresh install of Heroic Games Launcher 2.2.4 with nothing in `~/config/heroic` I am unable to login to Epic Games. Heroic hangs on "Loggin In..." animation.

### Add logs

(13:45:11) INFO:    [Legendary]:       Location: "/opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary"
(13:45:11) INFO:    [Gog]:             Location: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl
(13:45:12) INFO:    [Backend]:         
  Heroic Version: 2.2.4 Oden
  Legendary Version:  0.20.25 Our Benefactors
  OS: Ubuntu KERNEL: 5.13.0-35-generic ARCH: x64
  CPU: AMD Ryzen 7 3700X 8-Core Processor @3.6 
  RAM: Total: 16.7 GB Available: 14.7 GB
  GRAPHICS: GPU0: Navi 10 [Radeon RX 5600 OEM/5600 XT / 5700/5700 XT] VRAM: 512MB DRIVER:  
  PROTOCOL: tty
  
(13:45:12) INFO:    [Backend]:         User Not Found, removing it from Store
(13:45:12) WARNING: [Backend]:         Protocol already registered.
(13:45:17) INFO:    [DXVKInstaller]:   Updating dxvk to: dxvk-1.10
(13:45:17) INFO:    [DXVKInstaller]:   Updating vkd3d to: vkd3d-proton-2.6
(13:45:18) INFO:    [DXVKInstaller]:   downloaded vkd3d
(13:45:18) INFO:    [DXVKInstaller]:   extracting vkd3d
(13:45:18) INFO:    [DXVKInstaller]:   extracting vkd3d updated!
(13:45:19) INFO:    [Backend]:         checking for heroic updates
(13:45:22) INFO:    [DXVKInstaller]:   downloaded dxvk
(13:45:22) INFO:    [DXVKInstaller]:   extracting dxvk
(13:45:22) INFO:    [DXVKInstaller]:   extracting dxvk updated!
(13:45:42) INFO:    [Legendary]:       Logging with Legendary...
(13:45:42) ERROR:   [Backend]:         Error: spawn "/opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary" ENOENT
(13:45:42) INFO:    [Legendary]:       Logging with Legendary...
(13:45:42) ERROR:   [Backend]:         Error: spawn "/opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary" ENOENT

### Steps to reproduce

1. Delete `~/.config/heroic` if it exists
2. Install Heroic 2.2.4 via `dpkg -s heroic_2.2.4_amd64.deb`
3. Launch Heroic
4. Click Epic Games > Log in
5. Enter Epic Games credentials

### Expected behavior

Login completes and Heroic shows my games library.

### System Information

- OS [e. g. "Ubuntu"]: Ubuntu 20.04.4
- Heroic Version [e. g. 2.1.1]: 2.2.4 deb

**Comment by UnDoxa** [comment]
Same thing on windows.

**Comment by Refrained-LM** [comment]
Can confirm the same thing happens on the latest version of Manjaro.

(23:32:56) INFO:    [Legendary]:       Location: "/opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary"
(23:32:56) INFO:    [Gog]:             Location: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl
(23:32:56) INFO:    [Backend]:         
  Heroic Version: 2.2.4 Oden
  Legendary Version:  0.20.25 Our Benefactors
  OS: ManjaroLinux KERNEL: 5.13.19-2-MANJARO ARCH: x64
  CPU: AMD Ryzen 5 5600X 6-Core Processor @3.7 GOVERNOR: schedutil
  RAM: Total: 67.3 GB Available: 64.6 GB
  GRAPHICS: GPU0: Ellesmere [Radeon RX 470/480/570/570X/580/580X/590] VRAM: 256MB DRIVER:  
  PROTOCOL: x11
  
(23:32:56) INFO:    [Backend]:         User Not Found, removing it from Store
(23:32:56) ERROR:   [Backend]:         Failed to register protocol with OS.
(23:32:59) INFO:    [Legendary]:       Logging with Legendary...
(23:32:59) ERROR:   [Backend]:         Error: spawn "/opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary" ENOENT

**Comment by xtertristl** [comment]
Same thing on a fresh install of Arch linux.

**Comment by bitbucket90** [comment]
+1 
Manjaro

**Comment by Risethar** [comment]
+1
Pop OS

**Comment by flavioislima** [comment]
Yes, can confirm the issue and will release fix later today.

**Comment by ascazzola** [comment]
I sill having same issue after clone main branch, remove ./config/hero and build the app using yarn.

And now the browser does not open when I try to log in using the external login option

**Comment by flavioislima** [comment]
@ascazzola can you try the release instead of cloning the branch?

**Comment by ascazzola** [comment]
@flavioislima  yes same issue, I can open the browser on external login but when I click "login" nothing happens. And using the "Log in" button it still loading with the next logs:
```
(15:16:08) INFO:    [Legendary]:       Location: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary
(15:16:08) INFO:    [Gog]:             Location: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl
(15:16:08) ERROR:   [Legendary]:       Error: Command failed: legendary --version
/bin/sh: line 1: legendary: command not found

(15:16:09) INFO:    [Backend]:         
  Heroic Version: 2.2.5 Oden
  Legendary Version: invalid
  OS: ManjaroLinux KERNEL: 5.15.25-1-MANJARO ARCH: x64
  CPU: Intel Core™ i7-10750H @2.6 GOVERNOR: powersave
  RAM: Total: 16.7 GB Available: 7.01 GB
  GRAPHICS: GPU0: NVIDIA GeForce RTX 2060 VRAM: 6144MB DRIVER: 510.54 
  PROTOCOL: x11
  
(15:16:09) INFO:    [Backend]:         User Not Found, removing it from Store
(15:16:09) WARNING: [Backend]:         Protocol already registered.
(15:16:11) INFO:    [DXVKInstaller]:   Updating dxvk to: dxvk-1.10
(15:16:12) INFO:    [DXVKInstaller]:   Updating vkd3d to: vkd3d-proton-2.6
(15:16:14) INFO:    [Backend]:         checking for heroic updates
(15:16:14) INFO:    [DXVKInstaller]:   downloaded vkd3d
(15:16:14) INFO:    [DXVKInstaller]:   extracting vkd3d
(15:16:14) INFO:    [DXVKInstaller]:   extracting vkd3d updated!
(15:16:16) INFO:    [DXVKInstaller]:   downloaded dxvk
(15:16:16) INFO:    [DXVKInstaller]:   extracting dxvk
(15:16:16) INFO:    [DXVKInstaller]:   extracting dxvk updated!
(15:16:30) INFO:    [Legendary]:       Logging with Legendary...
(15:16:30) ERROR:   [Backend]:         Error: spawn legendary ENOENT
(15:16:30) INFO:    [Legendary]:       Logging with Legendary...
(15:16:30) ERROR:   [Backend]:         Error: spawn legendary ENOENT
(15:16:31) INFO:    [Legendary]:       Logging with Legendary...
(15:16:31) ERROR:   [Backend]:         Error: spawn legendary ENOENT
(15:16:31) INFO:    [Legendary]:       Logging with Legendary...
(15:16:31) ERROR:   [Backend]:         Error: spawn legendary ENOENT
(15:16:31) INFO:    [Legendary]:       Logging with Legendary...
(15:16:31) ERROR:   [Backend]:         Error: spawn legendary ENOENT
(15:16:42) ERROR:   [Legendary]:       Error: Command failed: legendary --version
/bin/sh: line 1: legendary: command not found
```

**Comment by ascazzola** [comment]
@flavioislima  Installed legendary and logged in now

**Comment by bitbucket90** [comment]
Tried updated version on Manjaro and seeing same issue as before. 

**_Went ahead and manually installed legendary via AUR and I was able to login_**

**Comment by umnikos** [comment]
Tried .deb package version 2.2.5 and the login button does nothing.

**Comment by anhinton** [comment]
I installed the new 2.2.5 .deb package and still see the same issue. From the tail of the log:
```
(10:22:40) INFO:    [Legendary]:       Logging with Legendary...
(10:22:40) ERROR:   [Backend]:         Error: spawn legendary ENOENT
(10:22:40) INFO:    [Legendary]:       Logging with Legendary...
(10:22:40) ERROR:   [Backend]:         Error: spawn legendary ENOENT
(10:23:24) ERROR:   [Legendary]:       Error: Command failed: legendary --version
/bin/sh: 1: legendary: not found
```

**Comment by ascazzola** [comment]
@anhinton  did you try installing legendary?

**Comment by anhinton** [comment]
> 

No I did't. The workaround I used yesterday was to install heroic 2.2.3 and login to Epic, then upgrade to 2.2.4. This kept my login credentials so I was able to access my library, and confirm that the issue was in 2.2.4.

**Comment by anhinton** [comment]
> @anhinton did you try installing legendary?

No I did'nt. The workaround I used yesterday was to install heroic 2.2.3 and login to Epic, then upgrade to 2.2.4. This kept my login credentials so I was able to access my library, and confirm that the issue was in 2.2.4.

**Comment by anhinton** [comment]
Just a not to confirm that 2.2.6 fixes this issue for me.
