### ISSUE TITLE
The Metadata for Apps does not exist so it cannot launch, Mac, when trying to play Rocket League

### ISSUE THREAD

**Issue by KrishWu** [Heroic-Games-Launcher/HeroicGamesLauncher#1068]
### Describe the bug

When I click run it says running for a few seconds, then goes back to not running. Nothing happens. I have set everything right according to the apple gaming wiki.

### Add logs

(17:32:40) INFO:    [Legendary]:       Refreshing library...
(17:32:40) INFO:    [Legendary]:       Refreshing Epic Games...
(17:32:40) INFO:    [Legendary]:       Refreshing Epic Games...
(17:32:42) ERROR:   [Legendary]:       Error: spawn "/Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/legendary" ENOENT
(17:32:42) INFO:    [Legendary]:       Updating game list
(17:32:42) INFO:    [Legendary]:       Game List Updated
(17:32:43) INFO:    [Backend]:         launching Rocket League® Sugar
(17:32:44) INFO:    [Legendary]:       Checking for game updates
(17:32:44) INFO:    [Legendary]:       Found 0 game(s) to update
(17:32:44) INFO:    [Gog]:             Found 0 game(s) to update
(17:32:44) INFO:    [Legendary]:       Launch Command: "/Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/legendary" launch Sugar    
(17:32:46) INFO:    [Backend]:         checking for heroic updates
(17:32:46) ERROR:   [Backend]:         Error - Command failed: "/Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/legendary" launch Sugar    
[cli] INFO: Logging in...
[Core] INFO: Trying to re-use existing login session...
[cli] INFO: Checking for updates...
[cli] CRITICAL: Metadata for "Sugar" does not exist, cannot launch!

### Steps to reproduce

1. Go to 'the launcher'
2. Click on 'Launch Rocket League.'
3. Scroll down to 'where the logs are in the thing.'

### Expected behavior

I hoped the app would open. It did not. I don't know quite why.

### System Information

- OS [Mac OS]: 
- Heroic Version [2.2.4]:

### Additional information

Thats it!

**Comment by flavioislima** [comment]
yes, its caused by the same issue as #1067
