### ISSUE TITLE
[Feature Request] Navigate and launch games by gamepad

### ISSUE THREAD

**Issue by clebercasali** [Heroic-Games-Launcher/HeroicGamesLauncher#107]
Like Steam Big Picture mode, it would be nice if we could launch games using only a gamepad.

**Comment by flavioislima** [comment]
> Like Steam Big Picture mode, it would be nice if we could launch games using only a gamepad.

This would be a nice feature but I have no idea on how to implement it on Heroic. 🤔

**Comment by clebercasali** [comment]
Is that what you need?
https://xaviergeerinck.com/post/coding/javascript/xbox-controller

**Comment by onadrog** [comment]
I've made an experimental branch here [Expermental_controller](https://github.com/onadrog/HeroicGamesLauncher/tree/experimental_controller) if you're interested it still in progress for now it work on Xbox360 controller (I don't have a Playstation one, so I don't know if it work as inteded).
### What work:
* Navigation through GameCard view NOT lists.
* Launching games and come back to GameCards view.

___
@flavioislima  If you wanna create a branch here so i can push it directlty into this repo for next features.

**Comment by ianwijma** [comment]
I can look at it during the weekends maybe. I might have access to PS4 and PS5 controllers.

**Comment by flavioislima** [comment]
> I've made an experimental branch here [Expermental_controller](https://github.com/onadrog/HeroicGamesLauncher/tree/experimental_controller) if you're interested it still in progress for now it work on Xbox360 controller (I don't have a Playstation one, so I don't know if it work as inteded).
> ### What work:
> 
>     * Navigation through GameCard view NOT lists.
> 
>     * Launching games and come back to GameCards view.
> 
> 
> @flavioislima If you wanna create a branch here so i can push it directlty into this repo for next features.

I'll find time to test it this weekend, but I added it to the 1.5.7 Roadmap so maybe we can test and try to add basic support at least for Xbox controllers for now :D

**Comment by onadrog** [comment]
Oi! I'm a bit busy for now. In last push (weeks ago) PS controller should work. I think the `GamePadApi.ts` provide a good start if someone want retake it.

___
### Changes
* Y button switch layout
* Select focus search bar
* X button open gamepage info
* A button launch game
* B button return to list
___
The Api use QuerySelector not the best idea i think especially if classeNames changes with new layout...

**Comment by dragonDScript** [comment]
I think that we should build a release and ask people to test it. Also, what is missing here? I'm interested in this.

**Comment by flavioislima** [comment]
> I think that we should build a release and ask people to test it. Also, what is missing here? I'm interested in this.

It's working but needs some fine tuning. I had another branch with all fixed conflicts, etc but could not push it and windows deleted my Linux partition, corrupted my home as well and I lost everything. So I need to start over. Feel free to try it as well. But most of the things are working.

**Comment by dragonDScript** [comment]
OK
