### ISSUE TITLE
GTA V not launching

### ISSUE THREAD

**Issue by isiddharthasharma** [Heroic-Games-Launcher/HeroicGamesLauncher#1078]
### Describe the bug

GTA V is not launching on latest version

### Add logs

> Error - Command failed: ./legendary launch 9d2d0eb64d5c44529cece33fe2a46482    
> [cli] INFO: Logging in...
> [Core] INFO: Trying to re-use existing login session...
> [cli] INFO: Checking for updates...
> [cli] CRITICAL: Metadata for "9d2d0eb64d5c44529cece33fe2a46482" does not exist, cannot launch!

### Steps to reproduce

1. Go to 'GTA V'
2. Click on 'Play'
4. See error (log)

### Expected behavior

Working in older version, I just installed this oden hot-fix and it stopped launching.

However it is still working on older version

### System Information

- OS [e. g. "Ubuntu"]: MacOS
- Heroic Version [e. g. 2.1.1]: 2.2.5 Oden Hotfix #4

### Additional information

I tried to logout thinking maybe login is problem but it does not let me logout, just refreshes. window.

**Comment by flavioislima** [comment]
can you try now on 2.2.6?

**Comment by draskin00** [comment]
On 2.2.6 it doesn't start. The rockstar game launcher does not open and stops with this error:
"Failed to connect to the Rockstar Games Library Service. If you continue to see this message, please contact Rockstar Games Customer Service at ..."

**Comment by flavioislima** [comment]
ok but thats now is another issue related with wine and not heroic anymore. I can confirm that the previous one was related with heroic, since it wasn't downloading the metadata files.

Follow this article here about GTAV: https://github.com/CommandMC/EpicLinux/wiki/GTA-V---Heroic-specific-guide
if it doesn't work, go to our Discord to get help. 👍🏽

**Comment by isiddharthasharma** [comment]
> On 2.2.6 it doesn't start. The rockstar game launcher does not open and stops with this error: "Failed to connect to the Rockstar Games Library Service. If you continue to see this message, please contact Rockstar Games Customer Service at ..."

It is Crossover issue fixed in 21.2 however if you have 21.1 and getting this message, 
go to your bottle, run command and type regedit then go to

> HKEY_LOCAL_MACHINE -> System -> Current Control Set -> Control

Create a new registry type 'string'
Name it ServicesPipeTimeout and set value to 20000

or go to this video https://www.youtube.com/watch?v=h7lMcy6EWQ4 if you still have problem.

**Comment by isiddharthasharma** [comment]
> can you try now on 2.2.6?

It is working now. Thank you for the update.

**Comment by rordi99** [comment]
i am facing same issue stucking at loading screen in gta V i tried running rockstars and logging first but its not working can you help please!!

**Comment by wiryfuture** [comment]
> i am facing same issue stucking at loading screen in gta V i tried running rockstars and logging first but its not working can you help please!!

It's always a wine/gtav issue not with heroic sry,

**Comment by isiddharthasharma** [comment]
> > i am facing same issue stucking at loading screen in gta V i tried running rockstars and logging first but its not working can you help please!!
> 
> It's always a wine/gtav issue not with heroic sry,

Did you run Rockstar Launcher first on Crossover and came to main screen after login?

**Comment by NAXEMO** [comment]
I was experimenting with the crossover bottles...And now the 'Play now' doesnt seem to be working.. I tried changing the wine in heroic to another bottle and ever since.. its not working
