### ISSUE TITLE
Game title link should always go back to the game page

### ISSUE THREAD

**Issue by LiamDawe** [Heroic-Games-Launcher/HeroicGamesLauncher#1080]
### Describe the bug

It seems when you click the game title link, sometimes instead of going back to the game page, it goes back to the library. Seems like that's not intentional.

### Add logs

Not really needed here.

### Steps to reproduce

Click any game title from a few places and see.

### Expected behavior

Game title should go correctly back to the game page.

### System Information

Steam Deck

**Comment by flavioislima** [comment]
This is a known issue, the UX for the navigation is not the best, should be improvement

**Comment by flavioislima** [comment]
I believe this is the same problem as #919
