### ISSUE TITLE
Heroic installed through Discover on Steam Deck always says update is available on launch

### ISSUE THREAD

**Issue by marmite22** [Heroic-Games-Launcher/HeroicGamesLauncher#1083]
### Describe the bug

I've just installed Heroic via Discover on my Steam Deck. Every time I launch it I get a popup that tells me that there is a new version and asks if I want to update. Clicking yes or no closes the popup but neither option seems to get rid of the message, it just pops back up the next time I launch Heroic.

### Add logs

(14:14:40) INFO:    [Legendary]:       Location: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary
(14:14:40) INFO:    [Gog]:             Location: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl
(14:14:41) INFO:    [Backend]:         
  Heroic Version: 2.2.5 Oden
  Legendary Version:  0.20.25 Our Benefactors
  OS: [Freedesktop.org](http://freedesktop.org/) KERNEL: 5.13.0-valve10.1-1-neptune-02144-g7fffaf925dfb ARCH: x64
  CPU: AMD Custom APU 0405 @1.82 GOVERNOR: schedutil
  RAM: Total: 15.6 GB Available: 13.9 GB
  GRAPHICS: GPU0: Device 163f VRAM: 512MB DRIVER:  
  PROTOCOL: x11
  
(14:14:42) ERROR:   [Backend]:         Failed to register protocol with OS.
(14:14:44) INFO:    [Frontend]:        Refreshing Library
(14:14:44) INFO:    [Legendary]:       Refreshing library...
(14:14:44) INFO:    [Legendary]:       Refreshing Epic Games...
(14:14:44) INFO:    [Legendary]:       Refreshing Epic Games...
(14:14:46) INFO:    [Legendary]:       [cli] INFO: Logging in...
(14:14:46) INFO:    [Legendary]:       [Core] INFO: Trying to re-use existing login session...
(14:14:46) INFO:    [Legendary]:       [cli] INFO: Getting game list... (this may take a while)
(14:14:47) INFO:    [Legendary]:       Updating game list
(14:14:47) INFO:    [Legendary]:       Game List Updated
(14:14:48) INFO:    [Backend]:         checking for heroic updates
(14:14:49) INFO:    [Legendary]:       Checking for game updates
(14:14:49) INFO:    [Legendary]:       Found 0 game(s) to update
(14:14:49) INFO:    [Gog]:             Found 0 game(s) to update

### Steps to reproduce

1. Open Heroic
2. Wait a few moments
3. The new update available popup will show

### Expected behavior

Either there is an update - in which case clicking "Yes" should install it. Or there isn't in which case the popup shouldn't show. Or perhaps updates should be handled entirely though Discover? I don't know.

### System Information

Steam Deck
Discover says Heroic is up to date

**Comment by flavioislima** [comment]
it takes up to 12h to update, unfortunately.

**Comment by flavioislima** [comment]
also, disable the Check for updates on startup when using flatpak. On new installs it will be disabled by default from now on

**Comment by marmite22** [comment]
Thanks for your tireless efforts. Great work.
