### ISSUE TITLE
Bundle the bash launcher

### ISSUE THREAD

**Issue by whise** [Heroic-Games-Launcher/HeroicGamesLauncher#1089]
### Problem description

It would be great if you could bundle the heroic bash launcher and add a button in the main application to make it automatically

### Feature description

It would be great if you could bundle the heroic bash launcher and add a button in the main application to make it automatically

**Comment by redromnon** [comment]
[Re-implementation of Bash Launcher](https://github.com/Heroic-Games-Launcher/heroic-bash-launcher) is in the works.

**Comment by felipecrs** [comment]
For me, the best part of bringing it to the core would be support for Windows (hopefully).

I also hope that the Heroic executable can support the needed options for handling such a case without the need of a Bash script for that.

Something like:

```console
$ heroic --oneshot <game-to-open>
```

That would cause Heroic to open, maybe hidden, automatically launch the game and close after the game is closed.

**Comment by Nocccer** [comment]
Close to be in beta.
On Linux Appimage and deb, rpm works great. Flatpak needs to be tested
AppImage: https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/suites/7153348627/artifacts/284597728
Windows: https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/suites/7153348628/artifacts/284601502
MacOS: https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/suites/7153348631/artifacts/284600918

Let me know if something does not work!
I know if steam is not installed on default paths, it does not work.

You can add a game via GamePage > Tools > Add to steam
Make sure the game is running without steam

Also a problem i can't solve yet:
- Legendary can't get the locale enviroment variable inside steam and defaults to en_US. Launch will fail if the epic username uses special characters like (ö, ü, ä, ...). No Workaround yet.
