### ISSUE TITLE
error while loading shared libraries: libcaca.so.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by dbasinge** [Heroic-Games-Launcher/HeroicGamesLauncher#1094]
### Describe the bug

Dosbox games not lauching

### Add logs

Command:   "/app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl" launch "/home/dbasinge/Games/Heroic/Eye of the Beholder II"  1432576039 --platform=linux  
        System Info:
        
  Heroic Version: 2.2.6 Oden
  Legendary Version:  0.20.25 Our Benefactors
  OS: Freedesktop.org KERNEL: 5.16.12-200.fc35.x86_64 ARCH: x64
  CPU: Intel Core™ i7-8550U @1.8 GOVERNOR: powersave
  RAM: Total: 16.7 GB Available: 10.4 GB
  GRAPHICS: GPU0: UHD Graphics 620  VRAM: 512MB DRIVER:  
  PROTOCOL: wayland
  
        Game Settings: {
	"checkUpdatesInterval": 10,
	"enableUpdates": false,
	"addDesktopShortcuts": false,
	"addStartMenuShortcuts": false,
	"autoInstallDxvk": false,
	"autoInstallVkd3d": false,
	"checkForUpdatesOnStartup": false,
	"customWinePaths": [],
	"defaultInstallPath": "/home//Games/Heroic",
	"defaultWinePrefix": "/home//Games/Heroic/Prefixes",
	"language": "en",
	"maxWorkers": 0,
	"minimizeOnLaunch": false,
	"nvidiaPrime": false,
	"otherOptions": "",
	"showUnrealMarket": false,
	"showFps": false,
	"useGameMode": false,
	"userInfo": {
		"epicId": "",
		"name": 
	},
	"wineCrossoverBottle": "Heroic",
	"winePrefix": "/home/dbasinge/Games/Heroic/Prefixes/Eye-of-the-Beholder-II-The-Legend-of-Darkmoon",
	"wineVersion": {
		"bin": "",
		"name": "Default Wine - Not Found",
		"type": "wine"
	},
	"altLegendaryBin": "",
	"altGogdlBin": "",
	"egsLinkedPath": "",
	"maxRecentGames": 5
}

        Game Log:
        /home//Games/Heroic/Eye of the Beholder II/dosbox/dosbox_x86_64: error while loading shared libraries: libcaca.so.0: cannot open shared object file: No such file or directory

### Steps to reproduce

1. Try to open Dosbox game

### Expected behavior

Game launches

### System Information

- Fedora 35
- Heroic Version: 2.2.6 Oden Flatpak

**Comment by flavioislima** [comment]
Have you looked at: https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/wiki/How-To:-DOSBOX-and-SCUMMVM

If it doesn't work:
Have you tried to enable the steam runtime?

If still doesn't work you will need to ask help from the developers to see whats happening since they might need to update some libs or something like this. And in this case there is nothing we can do about it.

**Comment by LockeCole42** [comment]
Hello, apologies for my denseness, but I am new to Linux and I'm trying to learn. I used DOS back in the day and I thought that rusty knowledge would help me a little here, but seemingly not enough... 
I went to flavioislima's link and while I feel I somewhat understand what I am supposed to do, I also am at a loss of what to do with that information on that page. 

Here's my issues:

1: Where exactly am I putting this line: 
dosbox -conf "${conf_1}" -conf "${conf_2}" -no-console -c exit
I tried both under Advanced Options (Environment Variables) and Game Arguments (To run after the command)

2: I am under the impression that conf_1 and conf_2 are meant to be replaced and the only thing that I could find that seemed to fit the bill in start.sh was "dosboxTex3.conf" followed by "dosboxTex3_single.conf" basically back to back on a line in the code.

I tried the line above both with conf_1/2 and the dosboxTex3 parts as replacement, both with and without the quotes that are in the start.sh file. 

I'm feeling stupid as hell that I couldn't seem to figure this out myself and was hoping you could help with a better explanation of what I am supposed to add, where exactly I can find it, and where exactly I am supposed to be inputting it.

Thanks for any and all help.

![IMG_20220331_165625__01](https://user-images.githubusercontent.com/102766632/161153679-14865391-c62d-4421-9a2c-fe5112f70177.jpg)

**Comment by imLinguin** [comment]
In start.sh file you attached on the screenshot there is a line:
`run_dosbox "dosboxTex3.conf" "dosboxTex3_single.conf"`

These are two files you have to replace, you most likely should create other .sh script with the command.

So for you, script would look like.
I assume you installed DOSbox through Flatpak.

```
#!/bin/bash

flatpak run com.dosbox.DOSBox -conf "dosboxTex3.conf" -conf "dosboxTex3_single.conf" -no-console -c exit

```

I understand it is confusing, in the future we aim to to that stuff automatically.

**Comment by DigTheDoug** [comment]
I have a similar issue, it doesn't look like it's running from the alternative script? The targetExe is pointing to the new custom script.

If I run the command in the custom script in the terminal the game does run, but not if through Heroic?

```
Launch Command:   "/app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl" launch "/home/deck/Games/Heroic/Star Wars - X-Wing CD (1994)"  1207667213 --platform=linux  
        System Info:
        
  Heroic Version: 2.2.6 Oden
  Legendary Version:  0.20.25 Our Benefactors
  OS: Freedesktop.org KERNEL: 5.13.0-valve10.3-1-neptune-02176-g5fe416c4acd8 ARCH: x64
  CPU: AMD Custom APU 0405 @1.75 GOVERNOR: schedutil
  RAM: Total: 15.6 GB Available: 12 GB
  GRAPHICS: GPU0: Device 163f VRAM: 512MB DRIVER:  
  PROTOCOL: x11
  
        Game Settings: {
	"audioFix": false,
	"autoInstallDxvk": false,
	"autoInstallVkd3d": false,
	"maxSharpness": 2,
	"nvidiaPrime": false,
	"otherOptions": "",
	"savesPath": "",
	"showFps": false,
	"targetExe": "'/home/deck/Games/Heroic/Star Wars - X-Wing CD (1994)/start_hero.sh'",
	"useGameMode": false,
	"wineCrossoverBottle": "Heroic",
	"winePrefix": "/home/deck/Games/Heroic/Prefixes/STAR-WARS®-X-Wing-Collectors-CD-(1994)",
	"wineVersion": {
		"bin": "",
		"name": "Default Wine - Not Found",
		"type": "wine"
	},
	"useSteamRuntime": false
}

        Game Log:
        /home/deck/Games/Heroic/Star Wars - X-Wing CD (1994)/dosbox/dosbox_x86_64: error while loading shared libraries: libcaca.so.0: cannot open shared object file: No such file or directory
```

Here's the start_hero.sh script
```
flatpak run io.github.dosbox-staging -conf "dosbox_xwingcd.conf" -conf "dosbox_xwingcd_single.conf" -no-console -c exit
```

**Comment by flavioislima** [comment]
Is this still an issue on 2.5.2?

**Comment by flavioislima** [comment]
> Is this still an issue on 2.5.2?

If it is, reopen the issue.
