### ISSUE TITLE
Indiana Jones and the Emperor's Tomb can not start. FileNotFoundError: [Errno 2] No such file or directory:

### ISSUE THREAD

**Issue by SaschaVasarrhelyi** [Heroic-Games-Launcher/HeroicGamesLauncher#1095]
### Describe the bug

If i would start the Game Heroic Window opens and wrote: An error has... please see the log.
I have all tested what i can do. other Wine or Proton versions, to set the right install file manually and so on but nothing help. Heroic dose not find the indi.exe and no directory.

### Add logs

[1425034773-lastPlay.log](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/files/8237123/1425034773-lastPlay.log)

### Steps to reproduce

1. Install Indiana Jones and the Emperor's Tomb
2. Click on start
3. See the result
4. See error look to the lock and then exit

### Expected behavior

It would be good, if the game find Directory and indi.exe File.

### System Information

- OS [e. g. "Ubuntu"]: Version 20.04.4 LTS (Focal Fossa) 64-bit : Kernel Linux 5.13.0-35-generic x86_64 : MATE 1.24.0
- Heroic Version [e. g. 2.1.1]: Heroic 2.2.6 Oden

### Additional information

Thanks in advanced.

**Comment by flavioislima** [comment]
@imLinguin perhaps gogdl is missing some file when installing?

**Comment by imLinguin** [comment]
To me it looks like path is parsed incorrectly
```
/home/user/Games/Heroic/Indiana Jones and the Emperor's Tomb/GameData\\bin
```
I'll try to fix that later.
I'll send the gogdl binary to test

**Comment by imLinguin** [comment]
https://github.com/Heroic-Games-Launcher/heroic-gogdl/actions/runs/1973754980
Could you check if that solves the issue?
- Download and extract zip
- Make binary executable
- Set it as alternative in Heroic
- Relaunch heroic

**Comment by SaschaVasarrhelyi** [comment]
Thanks,
the new gogdl binery you send me, dose the trick. :)

**Comment by imLinguin** [comment]
It'll be included in next release probably
