### ISSUE TITLE
Fail to refresh the library

### ISSUE THREAD

**Issue by Newbie997** [Heroic-Games-Launcher/HeroicGamesLauncher#1097]
### Describe the bug

It is loading all the time, but no game appears.

### Add logs

[7054:0314/095912.119634:ERROR:sandbox_linux.cc(377)] InitializeSandbox() called with multiple threads in process gpu-process.
(09:59:12) INFO:    [Backend]:         
  Heroic Version: 2.2.6 Oden
  Legendary Version:  0.20.25 Our Benefactors
  OS: Arch KERNEL: 5.16.14-arch1-1 ARCH: x64
  CPU: Intel Core™ i7-8565U @1.8 GOVERNOR: powersave
  RAM: Total: 8.18 GB Available: 4.33 GB
  GRAPHICS: GPU0: WhiskeyLake-U GT2 [UHD Graphics 620]  VRAM: 256MB DRIVER:  GPU1: GP108M [GeForce MX150]  VRAM: 32MB DRIVER:  
  PROTOCOL: x11
  
(09:59:12) WARNING: [Backend]:         Protocol already registered.
[7023:0314/095912.945606:ERROR:browser_main_loop.cc(267)] Gtk: gtk_widget_add_accelerator: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed
[7023:0314/095912.945699:ERROR:browser_main_loop.cc(267)] Gtk: gtk_widget_add_accelerator: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed
[7023:0314/095912.945838:ERROR:browser_main_loop.cc(267)] Gtk: gtk_widget_add_accelerator: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed
(09:59:13) INFO:    [Frontend]:        Refreshing Library
(09:59:13) INFO:    [Legendary]:       Refreshing library...
(09:59:13) INFO:    [Legendary]:       Refreshing Epic Games...
(09:59:13) INFO:    [Legendary]:       Refreshing Epic Games...
(09:59:14) INFO:    [Legendary]:       [cli] INFO: Logging in...
(09:59:14) INFO:    [Legendary]:       [Core] INFO: Trying to re-use existing login session...
(09:59:15) INFO:    [Legendary]:       [cli] INFO: Getting game list... (this may take a while)
(09:59:15) ERROR:   [Legendary]:       TypeError: Cannot read properties of undefined (reading 'includes')
Error occurred in handler for 'refreshLibrary': TypeError: Cannot read properties of null (reading 'title')
    at /opt/Heroic/resources/app.asar/build/legendary/library.js:142:29
    at Array.sort (<anonymous>)
    at LegendaryLibrary.getGames (/opt/Heroic/resources/app.asar/build/legendary/library.js:141:55)
    at async /opt/Heroic/resources/app.asar/build/main.js:539:12
    at async node:electron/js2c/browser_init:193:563
(node:7023) UnhandledPromiseRejectionWarning: TypeError: Cannot read properties of undefined (reading 'includes')
    at LegendaryLibrary.loadFile (/opt/Heroic/resources/app.asar/build/legendary/library.js:393:43)
    at /opt/Heroic/resources/app.asar/build/legendary/library.js:421:99
    at Array.map (<anonymous>)
    at LegendaryLibrary.loadAll (/opt/Heroic/resources/app.asar/build/legendary/library.js:421:76)
    at /opt/Heroic/resources/app.asar/build/legendary/library.js:92:18
    at async LegendaryLibrary.getGames (/opt/Heroic/resources/app.asar/build/legendary/library.js:128:17)
    at async /opt/Heroic/resources/app.asar/build/main.js:539:12
    at async node:electron/js2c/browser_init:193:563
(Use `heroic --trace-warnings ...` to show where the warning was created)
(node:7023) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(09:59:15) ERROR:   [Frontend]:        Error: Error invoking remote method 'refreshLibrary': TypeError: Cannot read properties of null (reading 'title')
(09:59:15) INFO:    [Frontend]:        No cache found, getting data from legendary...
(09:59:15) INFO:    [Legendary]:       Refreshing library...
(09:59:15) ERROR:   [Legendary]:       TypeError: Cannot read properties of undefined (reading 'includes')
Error occurred in handler for 'readConfig': TypeError: Cannot read properties of null (reading 'title')
    at /opt/Heroic/resources/app.asar/build/legendary/library.js:142:29
    at Array.sort (<anonymous>)
    at LegendaryLibrary.getGames (/opt/Heroic/resources/app.asar/build/legendary/library.js:141:55)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async /opt/Heroic/resources/app.asar/build/main.js:499:20
    at async node:electron/js2c/browser_init:193:563
(09:59:18) INFO:    [Backend]:         checking for heroic updates

### Steps to reproduce

1.Log in
2.Load the library

### Expected behavior

show all games in my library

### Screenshots

![2022-03-12_16-13](https://user-images.githubusercontent.com/61965533/158009917-0ecef622-ffde-427a-9b91-e2372bd63f3c.png)

### System Information

- OS: Arch Linux
- Heroic Version: 2.2.6

**Comment by flavioislima** [comment]
Can you open the Debug Window?
Click on the tray icon > Debug. Check if it shows some error there.

**Comment by MrAn0nym** [comment]
```(14:09:20) INFO:    [Legendary]:       Location: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary
(14:09:20) INFO:    [Gog]:             Location: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl
(14:09:21) INFO:    [Backend]:         
  Heroic Version: 2.2.6 Oden
  Legendary Version:  0.20.25 Our Benefactors
  OS: Pop KERNEL: 5.16.11-76051611-generic ARCH: x64
  CPU: AMD Ryzen 5 2400G with Radeon Vega Graphics @3.6 GOVERNOR: schedutil
  RAM: Total: 16.8 GB Available: 9.11 GB
  GRAPHICS: GPU0: NVIDIA GeForce GT 710 VRAM: 1994MB DRIVER: 470.86 
  PROTOCOL: x11
```
```(14:09:45) INFO:    [Frontend]:        Refreshing Library
(14:09:45) INFO:    [Legendary]:       Refreshing library...
(14:09:45) INFO:    [Legendary]:       Refreshing Epic Games...
(14:09:45) INFO:    [Legendary]:       Refreshing Epic Games...
(14:09:46) INFO:    [Legendary]:       [cli] INFO: Logging in...
(14:09:46) INFO:    [Legendary]:       [Core] INFO: Trying to re-use existing login session...
(14:09:47) INFO:    [Legendary]:       [cli] INFO: Getting game list... (this may take a while)
[123101:0313/140951.509754:ERROR:CONSOLE(1)] "Uncaught TypeError: Cannot read properties of undefined (reading 'instance')", source:  (1)
(14:09:52) INFO:    [Legendary]:       Updating game list
(14:09:52) INFO:    [Legendary]:       Game List Updated
(14:09:54) INFO:    [Legendary]:       Checking for game updates
(14:09:54) INFO:    [Legendary]:       Found 3 game(s) to update
(14:09:54) INFO:    [Gog]:             Found 0 game(s) to update
```

Pretty sure that that's the same error, already installed games are showing up just as usual

> Can you open the Debug Window?
Click on the tray icon > Debug. Check if it shows some error there.

No error shown

**Comment by Nocccer** [comment]
No this is actually a error coming from legendary and not from heroic. So it is a different failure here

**Comment by MrAn0nym** [comment]
> No this is actually a error coming from legendary i assume and not from heroic. So it is a different failure here.

Error in the report is `[Legendary]: TypeError: Cannot read properties of undefined (reading 'includes')` as well…

**Comment by Newbie997** [comment]
> 
The error shows `Uncaught (in promise) Error: Error invoking remote method 'readConfig': TypeError: Cannot read properties of null (reading 'title') at EventEmitter.i.invoke (node:electron/js2c/renderer_init:57:526)`

**Comment by Newbie997** [comment]
> Can you open the Debug Window? Click on the tray icon > Debug. Check if it shows some error there.

The error is `Uncaught (in promise) Error: Error invoking remote method 'readConfig': TypeError: Cannot read properties of null (reading 'title')
    at EventEmitter.i.invoke (node:electron/js2c/renderer_init:57:526)`

**Comment by MrAn0nym** [comment]
Logging in and out fixed it for me

**Comment by cadbusca** [comment]
This is what fixed this issue to me: 
1) Logged out of the Epic Account on legendary via Heroic (just in case, but what solved the issue, I´m sure were the steps below).
2) opened a command line in the legendary folder that in my case is: 
C:\Users\[USER]\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32 
and executed:
legendary.exe cleanup

3) After that in the legendary config folder which in my case is:
C:\Users\[USER]\.config\legendary
I deleted the folder: metadata

4) Opened Heroic and logged back to Epic

**Comment by Newbie997** [comment]
> This is what fixed this issue to me: 
> 1) opened a command line in the legendary folder that in my case is: 
> `C:\Users\[USER]\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32`
> and executed:
> legendary.exe cleanup
> 
> 2) After that in the legendary config folder which in my case is:
> `C:\Users\[USER]\.config\legendary`
> I deleted the folder: metadata
> 

Thanks, it works for me!😃

**Comment by flavioislima** [comment]
Add a link to the issue in the wiki in case someone has the same issue in the future. Thanks, @cadbusca for finding it out.
