### ISSUE TITLE
.Appimage 2.2.6 can play what i have installed can't installed new!!!

### ISSUE THREAD

**Issue by supernova874** [Heroic-Games-Launcher/HeroicGamesLauncher#1101]
### Describe the bug

What game i have installed prior to 2.2.6 works , i tried installed any different game on my account and doesn't installed even tried to add some games currently downloaded to import but doesn't work , with version 2.2.1 , i can install any game and import without any issue with 2.2.6 in flatpak i can install all of them.

### Add logs

(18:17:03) INFO:    [Legendary]:       Location: /tmp/.mount_HeroicaQiTJU/resources/app.asar.unpacked/build/bin/linux/legendary
(18:17:03) INFO:    [Gog]:             Location: /tmp/.mount_HeroicaQiTJU/resources/app.asar.unpacked/build/bin/linux/gogdl
(18:17:04) INFO:    [Backend]:         
  Heroic Version: 2.2.6 Oden
  Legendary Version:  0.20.25 Our Benefactors
  OS: Solus KERNEL: 5.15.26-211.current ARCH: x64
  CPU: AMD Ryzen 5 2600X Six-Core Processor @3.6 GOVERNOR: performance
  RAM: Total: 16.8 GB Available: 7.92 GB
  GRAPHICS: GPU0: Tonga PRO [Radeon R9 285/380] VRAM: 256MB DRIVER:  
  PROTOCOL: x11
  
(18:17:04) ERROR:   [Backend]:         Failed to register protocol with OS.
(18:17:05) INFO:    [Frontend]:        Refreshing Library
(18:17:05) INFO:    [Legendary]:       Refreshing library...
(18:17:05) INFO:    [Legendary]:       Refreshing Epic Games...
(18:17:05) INFO:    [Legendary]:       Refreshing Epic Games...
(18:17:06) INFO:    [Legendary]:       [cli] INFO: Logging in...
(18:17:06) INFO:    [Legendary]:       [Core] INFO: Trying to re-use existing login session...
(18:17:06) INFO:    [Legendary]:       [cli] INFO: Getting game list... (this may take a while)
(18:17:07) INFO:    [Legendary]:       Updating game list
(18:17:07) INFO:    [Legendary]:       Game List Updated
(18:17:07) ERROR:   [Legendary]:       Error: Command failed: legendary list-installed --check-updates --tsv
/bin/bash: line 1: legendary: command not found

(18:17:07) INFO:    [Gog]:             Found 0 game(s) to update
(18:17:07) ERROR:   [Frontend]:        Error: Error invoking remote method 'checkGameUpdates': TypeError: legendaryUpdates is not iterable
(18:17:09) INFO:    [Backend]:         checking for heroic updates

### Steps to reproduce

2. Click on '...'
3. Scroll down to '...'

### Expected behavior

instead starting download it stops and a message appears that it has finished...

### System Information

- OS [e. g. "Ubuntu"]: SOLUS Budgie 4.3
- Heroic Version [e. g. 2.1.1]: 2.2.6
-

**Comment by flavioislima** [comment]
Can you try installing it from flathub or from the solus repository?

**Comment by supernova874** [comment]
I installed the 2.2.4 from Solus Repo and works fine , so i wan't try anything with appimage 2.26 cause the repo is better and updates automatic when i get my weekly updates , so thanks for your time anyway :)
