### ISSUE TITLE
Rocket League does not Launch, Mac, Metadata not found.

### ISSUE THREAD

**Issue by KrishWu** [Heroic-Games-Launcher/HeroicGamesLauncher#1104]
### Describe the bug

When I try to open the game rocket league on mac it says playing for a few seconds, nothing happens, and then it goes back to not playing.

### Add logs

(10:14:53) INFO:    [Legendary]:       Location: /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/legendary
(10:14:53) INFO:    [Gog]:             Location: /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/gogdl
(10:15:06) INFO:    [Backend]:         
  Heroic Version: 2.2.6 Oden
  Legendary Version:  0.20.25 Our Benefactors
  OS: macOS KERNEL: 21.3.0 ARCH: x64
  CPU: Intel Core™ i7-6920HQ @2.9 
  RAM: Total: 17.2 GB Available: 11.1 GB
  GRAPHICS: GPU0: Intel HD Graphics 530 VRAM: 1536MB DRIVER:  GPU1: AMD Radeon Pro 460 VRAM: 4096MB DRIVER:  
  
  
(10:15:07) WARNING: [Backend]:         Protocol already registered.
(10:15:08) INFO:    [Frontend]:        Refreshing Library
(10:15:08) INFO:    [Legendary]:       Refreshing library...
(10:15:08) INFO:    [Legendary]:       Refreshing Epic Games...
(10:15:08) INFO:    [Legendary]:       Refreshing Epic Games...
(10:15:11) INFO:    [Backend]:         launching Rocket League® Sugar
(10:15:11) INFO:    [Legendary]:       Launch Command: 
(10:15:13) INFO:    [Legendary]:       [cli] INFO: Logging in...
[Core] INFO: Logging in...
(10:15:13) INFO:    [Backend]:         checking for heroic updates
(10:15:13) INFO:    [Legendary]:       [cli] INFO: Getting game list... (this may take a while)
(10:15:17) INFO:    [Legendary]:       Updating game list
(10:15:17) INFO:    [Legendary]:       Game List Updated
(10:15:21) ERROR:   [Backend]:         Error - Command failed: legendary launch Sugar    
[cli] INFO: Logging in...
[Core] INFO: Trying to re-use existing login session...
[cli] INFO: Checking for updates...
[cli] CRITICAL: Metadata for "Sugar" does not exist, cannot launch!

(10:15:27) INFO:    [Legendary]:       Checking for game updates
(10:15:27) INFO:    [Legendary]:       Found 0 game(s) to update
(10:15:27) INFO:    [Gog]:             Found 0 game(s) to update

### Steps to reproduce

1. Go to 'Heroic Launcher'
2. Click on 'Play'
3. Scroll down to 'Logs'

### Expected behavior

I hoped the game would open.

### System Information

- OS ["Macos"]: 
- Heroic Version [e. g. 2.2.6]:

### Additional information

Thats it!

**Comment by flavioislima** [comment]
Can you check in .config/legendary/metadata there is a file called Sugar.json?
Thia folder called .config is hidden so you need to enable finder to show hidden files first.

**Comment by KrishWu** [comment]
Would this be in the game's files or heroic launcher's files. I checked both and cannot find a .config. In Rocket League the game there is a Config folder under the engine. I cannot find a .config folder.

**Comment by flavioislima** [comment]
No, it is inside your USER folder.

Like:
`john.doe/.config/legendary/metadata`

**Comment by KrishWu** [comment]
It's there.
Here is the log.
For sugar.json

`{
  "app_name": "Sugar",
  "app_title": "Rocket League\u00ae",
  "asset_infos": {
    "Windows": {
      "app_name": "Sugar",
      "asset_id": "Sugar",
      "build_version": "BC2_Update37+368596",
      "catalog_item_id": "530145df28a24424923f5828cc9031a1",
      "label_name": "Live-Windows",
      "metadata": {},
      "namespace": "9773aa1aa54f4f7b80e44bef04986cea"
    }
  },
  "base_urls": [
    "https://epicgames-download1.akamaized.net/Builds/Org/o-98larctxyhn55kqjq5xjb9wzjl9hf9/e6bcca5b37d0457ca881aec508205542/default",
    "https://download.epicgames.com/Builds/Org/o-98larctxyhn55kqjq5xjb9wzjl9hf9/e6bcca5b37d0457ca881aec508205542/default",
    "https://download2.epicgames.com/Builds/Org/o-98larctxyhn55kqjq5xjb9wzjl9hf9/e6bcca5b37d0457ca881aec508205542/default",
    "https://download3.epicgames.com/Builds/Org/o-98larctxyhn55kqjq5xjb9wzjl9hf9/e6bcca5b37d0457ca881aec508205542/default",
    "https://download4.epicgames.com/Builds/Org/o-98larctxyhn55kqjq5xjb9wzjl9hf9/e6bcca5b37d0457ca881aec508205542/default",
    "https://fastly-download.epicgames.com/Builds/Org/o-98larctxyhn55kqjq5xjb9wzjl9hf9/e6bcca5b37d0457ca881aec508205542/default"
  ],
  "metadata": {
    "ageGatings": {},
    "applicationId": "fghi4567OXA1CdeeCuAmUWMhmfiO3EAl",
    "categories": [
      {
        "path": "public"
      },
      {
        "path": "games"
      },
      {
        "path": "applications"
      }
    ],
    "creationDate": "2019-07-17T15:21:47.846Z",
    "customAttributes": {
      "CanRunOffline": {
        "type": "STRING",
        "value": "true"
      },
      "CanSkipKoreanIdVerification": {
        "type": "STRING",
        "value": "true"
      },
      "FolderName": {
        "type": "STRING",
        "value": "rocketleague"
      },
      "MonitorPresence": {
        "type": "STRING",
        "value": "true"
      },
      "PresenceId": {
        "type": "STRING",
        "value": "9773aa1aa54f4f7b80e44bef04986cea"
      },
      "RequirementsJson": {
        "type": "STRING",
        "value": "[]"
      },
      "UseAccessControl": {
        "type": "STRING",
        "value": "false"
      }
    },
    "description": "Rocket League\u00ae",
    "developer": "Psyonix LLC",
    "developerId": "o-98larctxyhn55kqjq5xjb9wzjl9hf9",
    "dlcItemList": [
      {
        "ageGatings": {},
        "categories": [
          {
            "path": "audience"
          },
          {
            "path": "public"
          }
        ],
        "creationDate": "2020-03-30T17:56:38.757Z",
        "customAttributes": {
          "SupportedPlatforms": {
            "type": "STRING",
            "value": "Windows"
          }
        },
        "description": "ContentPackAudience",
        "developer": "Psyonix LLC",
        "developerId": "o-98larctxyhn55kqjq5xjb9wzjl9hf9",
        "endOfSupport": false,
        "entitlementName": "c06bc2321cc24fa889bca5c711e34cb7",
        "entitlementType": "AUDIENCE",
        "eulaIds": [
          "egstore"
        ],
        "id": "c06bc2321cc24fa889bca5c711e34cb7",
        "itemType": "DURABLE",
        "keyImages": [],
        "lastModifiedDate": "2020-09-23T14:51:19.611Z",
        "mainGameItem": {
          "id": "530145df28a24424923f5828cc9031a1",
          "namespace": "9773aa1aa54f4f7b80e44bef04986cea",
          "unsearchable": false
        },
        "namespace": "9773aa1aa54f4f7b80e44bef04986cea",
        "status": "ACTIVE",
        "title": "ContentPackAudience",
        "unsearchable": false
      },
      {
        "ageGatings": {},
        "applicationId": "",
        "categories": [
          {
            "path": "addons"
          }
        ],
        "creationDate": "2021-03-25T03:21:03.271Z",
        "customAttributes": {
          "SupportedPlatforms": {
            "type": "STRING",
            "value": "Windows"
          }
        },
        "description": "Octane ZSR Starter Pack Audience",
        "developer": "Psyonix LLC",
        "developerId": "o-98larctxyhn55kqjq5xjb9wzjl9hf9",
        "endOfSupport": false,
        "entitlementName": "98ad5389c6184a0cad24c4ff10254128",
        "entitlementType": "AUDIENCE",
        "eulaIds": [
          "egstore"
        ],
        "id": "98ad5389c6184a0cad24c4ff10254128",
        "installModes": [],
        "itemType": "DURABLE",
        "keyImages": [],
        "lastModifiedDate": "2021-08-17T01:26:47.998Z",
        "mainGameItem": {
          "id": "530145df28a24424923f5828cc9031a1",
          "namespace": "9773aa1aa54f4f7b80e44bef04986cea",
          "unsearchable": false
        },
        "namespace": "9773aa1aa54f4f7b80e44bef04986cea",
        "releaseInfo": [],
        "requiresSecureAccount": false,
        "status": "ACTIVE",
        "title": "Octane ZSR Starter Pack Audience",
        "unsearchable": true
      },
      {
        "ageGatings": {},
        "applicationId": "",
        "categories": [
          {
            "path": "addons"
          }
        ],
        "creationDate": "2021-03-25T03:26:50.061Z",
        "customAttributes": {
          "SupportedPlatforms": {
            "type": "STRING",
            "value": "Windows"
          }
        },
        "description": "Peregrine Pack Audience",
        "developer": "Psyonix LLC",
        "developerId": "o-98larctxyhn55kqjq5xjb9wzjl9hf9",
        "endOfSupport": false,
        "entitlementName": "e8c4a827f664488d8cb4a0048d7d30c7",
        "entitlementType": "AUDIENCE",
        "eulaIds": [
          "egstore"
        ],
        "id": "e8c4a827f664488d8cb4a0048d7d30c7",
        "installModes": [],
        "itemType": "DURABLE",
        "keyImages": [],
        "lastModifiedDate": "2021-08-24T15:33:41.197Z",
        "mainGameItem": {
          "id": "530145df28a24424923f5828cc9031a1",
          "namespace": "9773aa1aa54f4f7b80e44bef04986cea",
          "unsearchable": false
        },
        "namespace": "9773aa1aa54f4f7b80e44bef04986cea",
        "releaseInfo": [],
        "requiresSecureAccount": false,
        "status": "ACTIVE",
        "title": "Peregrine Pack Audience",
        "unsearchable": true
      },
      {
        "ageGatings": {},
        "applicationId": "",
        "categories": [
          {
            "path": "addons"
          }
        ],
        "creationDate": "2021-06-25T03:09:11.840Z",
        "customAttributes": {
          "SupportedPlatforms": {
            "type": "STRING",
            "value": "Windows"
          }
        },
        "description": "Road Hog XL Starter Pack Audience",
        "developer": "Psyonix LLC",
        "developerId": "o-98larctxyhn55kqjq5xjb9wzjl9hf9",
        "endOfSupport": false,
        "entitlementName": "1702c40536ee445bb6d5af856c2b2499",
        "entitlementType": "AUDIENCE",
        "eulaIds": [
          "egstore"
        ],
        "id": "1702c40536ee445bb6d5af856c2b2499",
        "installModes": [],
        "itemType": "DURABLE",
        "keyImages": [],
        "lastModifiedDate": "2021-11-23T16:45:47.303Z",
        "mainGameItem": {
          "id": "530145df28a24424923f5828cc9031a1",
          "namespace": "9773aa1aa54f4f7b80e44bef04986cea",
          "unsearchable": false
        },
        "namespace": "9773aa1aa54f4f7b80e44bef04986cea",
        "releaseInfo": [],
        "requiresSecureAccount": false,
        "status": "ACTIVE",
        "title": "Road Hog XL Starter Pack Audience",
        "unsearchable": true
      },
      {
        "ageGatings": {},
        "applicationId": "",
        "categories": [
          {
            "path": "addons"
          }
        ],
        "creationDate": "2021-06-25T03:10:58.096Z",
        "customAttributes": {
          "SupportedPlatforms": {
            "type": "STRING",
            "value": "Windows"
          }
        },
        "description": "Werewolf Pack Audience",
        "developer": "Psyonix LLC",
        "developerId": "o-98larctxyhn55kqjq5xjb9wzjl9hf9",
        "endOfSupport": false,
        "entitlementName": "3e4da909263442c2954ea5a5a155c56e",
        "entitlementType": "AUDIENCE",
        "eulaIds": [
          "egstore"
        ],
        "id": "3e4da909263442c2954ea5a5a155c56e",
        "installModes": [],
        "itemType": "DURABLE",
        "keyImages": [],
        "lastModifiedDate": "2021-10-13T15:37:31.062Z",
        "mainGameItem": {
          "id": "530145df28a24424923f5828cc9031a1",
          "namespace": "9773aa1aa54f4f7b80e44bef04986cea",
          "unsearchable": false
        },
        "namespace": "9773aa1aa54f4f7b80e44bef04986cea",
        "releaseInfo": [],
        "requiresSecureAccount": false,
        "status": "ACTIVE",
        "title": "Werewolf Pack Audience",
        "unsearchable": true
      },
      {
        "ageGatings": {},
        "applicationId": "",
        "categories": [
          {
            "path": "addons"
          }
        ],
        "creationDate": "2021-09-02T20:50:49.505Z",
        "customAttributes": {
          "SupportedPlatforms": {
            "type": "STRING",
            "value": "Windows"
          }
        },
        "description": "Red Hot Bundle Audience",
        "developer": "Psyonix LLC",
        "developerId": "o-98larctxyhn55kqjq5xjb9wzjl9hf9",
        "endOfSupport": false,
        "entitlementName": "4829fa02053f4f72a4db0bee2f01e189",
        "entitlementType": "AUDIENCE",
        "eulaIds": [
          "egstore"
        ],
        "id": "4829fa02053f4f72a4db0bee2f01e189",
        "installModes": [],
        "itemType": "DURABLE",
        "keyImages": [],
        "lastModifiedDate": "2021-11-30T17:54:32.394Z",
        "mainGameItem": {
          "id": "530145df28a24424923f5828cc9031a1",
          "namespace": "9773aa1aa54f4f7b80e44bef04986cea",
          "unsearchable": false
        },
        "namespace": "9773aa1aa54f4f7b80e44bef04986cea",
        "releaseInfo": [],
        "requiresSecureAccount": false,
        "status": "ACTIVE",
        "title": "Red Hot Bundle Audience",
        "unsearchable": true
      },
      {
        "ageGatings": {},
        "applicationId": "",
        "categories": [
          {
            "path": "addons"
          }
        ],
        "creationDate": "2021-10-20T01:36:05.707Z",
        "customAttributes": {
          "SupportedPlatforms": {
            "type": "STRING",
            "value": "Windows"
          }
        },
        "description": "Starter Pack Audience",
        "developer": "Psyonix LLC",
        "developerId": "o-98larctxyhn55kqjq5xjb9wzjl9hf9",
        "endOfSupport": false,
        "entitlementName": "80e03ffd60e24be39d96f7792c467687",
        "entitlementType": "AUDIENCE",
        "eulaIds": [
          "egstore"
        ],
        "id": "80e03ffd60e24be39d96f7792c467687",
        "installModes": [],
        "itemType": "DURABLE",
        "keyImages": [],
        "lastModifiedDate": "2021-11-23T16:45:47.304Z",
        "mainGameItem": {
          "id": "530145df28a24424923f5828cc9031a1",
          "namespace": "9773aa1aa54f4f7b80e44bef04986cea",
          "unsearchable": false
        },
        "namespace": "9773aa1aa54f4f7b80e44bef04986cea",
        "releaseInfo": [],
        "requiresSecureAccount": false,
        "status": "ACTIVE",
        "title": "Starter Pack Audience",
        "unsearchable": true
      },
      {
        "ageGatings": {},
        "applicationId": "",
        "categories": [
          {
            "path": "addons"
          }
        ],
        "creationDate": "2021-10-20T01:36:22.756Z",
        "customAttributes": {
          "SupportedPlatforms": {
            "type": "STRING",
            "value": "Windows"
          }
        },
        "description": "TPack Audience",
        "developer": "Psyonix LLC",
        "developerId": "o-98larctxyhn55kqjq5xjb9wzjl9hf9",
        "endOfSupport": false,
        "entitlementName": "33e5486bcf6147b8923acce3b71e55b1",
        "entitlementType": "AUDIENCE",
        "eulaIds": [
          "egstore"
        ],
        "id": "33e5486bcf6147b8923acce3b71e55b1",
        "installModes": [],
        "itemType": "DURABLE",
        "keyImages": [],
        "lastModifiedDate": "2021-11-30T17:54:32.393Z",
        "mainGameItem": {
          "id": "530145df28a24424923f5828cc9031a1",
          "namespace": "9773aa1aa54f4f7b80e44bef04986cea",
          "unsearchable": false
        },
        "namespace": "9773aa1aa54f4f7b80e44bef04986cea",
        "releaseInfo": [],
        "requiresSecureAccount": false,
        "status": "ACTIVE",
        "title": "TPack Audience",
        "unsearchable": true
      },
      {
        "ageGatings": {},
        "applicationId": "",
        "categories": [
          {
            "path": "addons"
          }
        ],
        "creationDate": "2021-10-20T01:36:44.800Z",
        "customAttributes": {
          "SupportedPlatforms": {
            "type": "STRING",
            "value": "Windows"
          }
        },
        "description": "Bundle Audience",
        "developer": "Psyonix LLC",
        "developerId": "o-98larctxyhn55kqjq5xjb9wzjl9hf9",
        "endOfSupport": false,
        "entitlementName": "3eb5b517b0ff47608b31ad1bafdf4694",
        "entitlementType": "AUDIENCE",
        "eulaIds": [
          "egstore"
        ],
        "id": "3eb5b517b0ff47608b31ad1bafdf4694",
        "installModes": [],
        "itemType": "DURABLE",
        "keyImages": [],
        "lastModifiedDate": "2021-10-20T01:36:44.800Z",
        "mainGameItem": {
          "id": "530145df28a24424923f5828cc9031a1",
          "namespace": "9773aa1aa54f4f7b80e44bef04986cea",
          "unsearchable": false
        },
        "namespace": "9773aa1aa54f4f7b80e44bef04986cea",
        "releaseInfo": [],
        "requiresSecureAccount": false,
        "status": "ACTIVE",
        "title": "Bundle Audience",
        "unsearchable": true
      },
      {
        "ageGatings": {},
        "applicationId": "",
        "categories": [
          {
            "path": "addons"
          }
        ],
        "creationDate": "2022-02-11T22:29:29.546Z",
        "customAttributes": {
          "SupportedPlatforms": {
            "type": "STRING",
            "value": "Windows"
          }
        },
        "description": "S6 Starter Pack Audience",
        "developer": "Psyonix LLC",
        "developerId": "o-98larctxyhn55kqjq5xjb9wzjl9hf9",
        "endOfSupport": false,
        "entitlementName": "b4d00a583bcb424ea5d472cddf126b6b",
        "entitlementType": "AUDIENCE",
        "eulaIds": [
          "egstore"
        ],
        "id": "b4d00a583bcb424ea5d472cddf126b6b",
        "installModes": [],
        "itemType": "DURABLE",
        "keyImages": [],
        "lastModifiedDate": "2022-02-11T22:29:29.546Z",
        "mainGameItem": {
          "id": "530145df28a24424923f5828cc9031a1",
          "namespace": "9773aa1aa54f4f7b80e44bef04986cea",
          "unsearchable": false
        },
        "namespace": "9773aa1aa54f4f7b80e44bef04986cea",
        "releaseInfo": [],
        "requiresSecureAccount": false,
        "status": "ACTIVE",
        "title": "S6 Starter Pack Audience",
        "unsearchable": true
      },
      {
        "ageGatings": {},
        "applicationId": "",
        "categories": [
          {
            "path": "addons"
          }
        ],
        "creationDate": "2022-02-11T22:29:49.505Z",
        "customAttributes": {
          "SupportedPlatforms": {
            "type": "STRING",
            "value": "Windows"
          }
        },
        "description": "S6 Customization Pack Audience",
        "developer": "Psyonix LLC",
        "developerId": "o-98larctxyhn55kqjq5xjb9wzjl9hf9",
        "endOfSupport": false,
        "entitlementName": "96f824698fb940ca8111381fda1e006d",
        "entitlementType": "AUDIENCE",
        "eulaIds": [
          "egstore"
        ],
        "id": "96f824698fb940ca8111381fda1e006d",
        "installModes": [],
        "itemType": "DURABLE",
        "keyImages": [],
        "lastModifiedDate": "2022-02-11T22:30:41.691Z",
        "mainGameItem": {
          "id": "530145df28a24424923f5828cc9031a1",
          "namespace": "9773aa1aa54f4f7b80e44bef04986cea",
          "unsearchable": false
        },
        "namespace": "9773aa1aa54f4f7b80e44bef04986cea",
        "releaseInfo": [],
        "requiresSecureAccount": false,
        "status": "ACTIVE",
        "title": "S6 Customization Pack Audience",
        "unsearchable": true
      }
    ],
    "endOfSupport": false,
    "entitlementName": "530145df28a24424923f5828cc9031a1",
    "entitlementType": "EXECUTABLE",
    "eulaIds": [
      "(egstore && rocket_league)"
    ],
    "id": "530145df28a24424923f5828cc9031a1",
    "installModes": [],
    "itemType": "DURABLE",
    "keyImages": [
      {
        "height": 1600,
        "md5": "f0107f8dec9b4659b77ef166f92b3637",
        "size": 575502,
        "type": "DieselGameBoxTall",
        "uploadedDate": "2021-12-03T17:21:24.307Z",
        "url": "https://cdn1.epicgames.com/item/9773aa1aa54f4f7b80e44bef04986cea/5748aa76-eaff-451a-b5bb-3bff8a4f4fc2_1200x1600-f0107f8dec9b4659b77ef166f92b3637",
        "width": 1200
      },
      {
        "height": 1440,
        "md5": "071db7b0d39d5635f684940c1e3c4ec3",
        "size": 691285,
        "type": "DieselGameBox",
        "uploadedDate": "2021-12-03T17:21:32.474Z",
        "url": "https://cdn1.epicgames.com/item/9773aa1aa54f4f7b80e44bef04986cea/6609d2e1-62d9-4094-9cb7-26d9a7f5ba3f_2560x1440-071db7b0d39d5635f684940c1e3c4ec3",
        "width": 2560
      }
    ],
    "lastModifiedDate": "2021-12-03T17:21:37.702Z",
    "namespace": "9773aa1aa54f4f7b80e44bef04986cea",
    "releaseInfo": [
      {
        "appId": "Sugar",
        "dateAdded": "2020-09-23T00:00:00.000Z",
        "id": "2fb949176d3a44eb90622de9aae7dfc3",
        "platform": [
          "Windows"
        ]
      }
    ],
    "status": "ACTIVE",
    "title": "Rocket League\u00ae",
    "unsearchable": true
  }
}`

**Comment by nonoche2** [comment]
I have the same issue, except with every game I have installed. They work fine if I launch them with Crossover

**Comment by nonoche2** [comment]
in the Heroic Bottle, double click on "launch command", select the game you want on your hard disk, and click on "create shortcut for this command", you'll see the game icon in your heroic bottle and from then on you can launch it with Crossover

**Comment by KrishWu** [comment]
That didn't work for me 😢.

**Comment by flavioislima** [comment]
@KrishWu did you fixed that? if not can you try the beta?

**Comment by KrishWu** [comment]
Unfortunately same issue.

**Comment by KrishWu** [comment]
Error - Command failed: ./legendary launch Sugar    
[cli] INFO: Logging in...
[Core] INFO: Trying to re-use existing login session...
[cli] INFO: Checking for updates...
[cli] CRITICAL: Metadata for "Sugar" does not exist, cannot launch!

**Comment by flavioislima** [comment]
I belive you will need to open an issue on legendary github then. I don't know what is happening.

**Comment by flavioislima** [comment]
> Any news about this? The issue happens when i try to log on a different account that i used to play ... If i log on the main account, the game runs. OBS.: I'm running on Ubuntu 20.04.4 LTS

If you are changing your account then you need to try to Clear the HEroic cache or reset it.

**Comment by flavioislima** [comment]
This issue should be fixed since 2.5.0 now
