### ISSUE TITLE
I can't access other disks (HD, USB ...) in the Flatpak version

### ISSUE THREAD

**Issue by pupilo-py** [Heroic-Games-Launcher/HeroicGamesLauncher#1117]
### Describe the bug

My Epic Games games are on another HD, but I can't access it in the Flatpak version (in the Appimage version it works).

### Add logs

none

### Steps to reproduce

2. Click on '...'
3. Scroll down to '...'

### Expected behavior

I expected the program to access other discs.

### System Information

- OS [e. g. "Kubuntu 20.04"]: 
- Heroic Version [e. g. 2.2.6]:

**Comment by imLinguin** [comment]
Flatpak is sandboxed, it means applications you run, don't have full access to your PC by default. You can use Flatseal to manage permissions to different locations on the system.

**Comment by pupilo-py** [comment]
> Flatpak is sandboxed, it means applications you run, don't have full access to your PC by default. You can use Flatseal to manage permissions to different locations on the system.

Sorry, I didn't know.
