### ISSUE TITLE
Gogdl Issues don't fail gracefully

### ISSUE THREAD

**Issue by miketweaver** [Heroic-Games-Launcher/HeroicGamesLauncher#1125]
### Describe the bug

When you go to download a game and `gogdl` has an error, the heroic launcher just sits at the spinning icon. It doesn't report to the user that there has been an error or what that error was.

![image](https://user-images.githubusercontent.com/5581855/158700300-0a9be21c-b32d-42dc-8ea9-51dcd106e6f4.png)

### Add logs

When you view debug:
![image](https://user-images.githubusercontent.com/5581855/158700354-7cde15eb-ab89-46d9-8cbd-4316e1cbbf9c.png)

Relevant logs:
```
(20:23:35) ERROR:   [Gog]:             Info command failed "/app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl" info 1207659093 --token="redacted" --lang=en-US --os windows
(20:23:35) ERROR:   [Gog]:             Info command failed "/app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl" info 1207659093 --token="redacted" --lang=en-US --os windows
```

### Steps to reproduce

1. Attempt to install a game that causes gogdl to crash. Current broken example: `Ultima 9: Ascension`. (this could get fixed at any time)

### Expected behavior

A popup that appears showing there was an error that occurred and any relevant longs.

### System Information

  SteamDeck
  
  Heroic Version: 2.2.6 Oden
  Legendary Version:  0.20.25 Our Benefactors
  OS: Freedesktop.org KERNEL: 5.13.0-valve10.1-1-neptune-02144-g7fffaf925dfb ARCH: x64
  CPU: AMD Custom APU 0405 @1.94 GOVERNOR: schedutil
  RAM: Total: 15.6 GB Available: 13.9 GB
  GRAPHICS: GPU0: Device 163f VRAM: 512MB DRIVER:
  PROTOCOL: x11

### Additional information

I have filed another bug for the gogdl issue that appeared here, but this is a separate problem.

https://github.com/Heroic-Games-Launcher/heroic-gogdl/issues/2

**Comment by miketweaver** [comment]
![mstsc_ewKk2NTfz4](https://user-images.githubusercontent.com/5581855/159313246-31f48081-b14c-4e92-9bc7-a4f5c2884c14.gif)

It throws the error on both games I've had the issue with! 

At first glance, I missed the error text, but it's there.

**Comment by imLinguin** [comment]
Use gogdl from testing branch, it's not updated yet in Heroic
https://github.com/Heroic-Games-Launcher/heroic-gogdl/actions/runs/2006118486

**Comment by miketweaver** [comment]
Sorry. That error throwing was the _goal_ of this bug. They now fail gracefully.

**Comment by imLinguin** [comment]
Oh yes. Then consider my previous message as information for others that might run into that issue :smile:
