### ISSUE TITLE
Recent commit #1092 broke download canceling for GOG

### ISSUE THREAD

**Issue by dawidgarus** [Heroic-Games-Launcher/HeroicGamesLauncher#1136]
### Describe the bug

When you try to pause/cancel downloading game from GOG, it will report as installed

### Add logs

(02:43:57) DEBUG: [Legendary]: Running Legendary command: /home/user/Projects/github/my/HeroicGamesLauncher/public/bin/linux/legendary --version

(02:43:57) INFO: [Legendary]: Legendary location: /home/user/Projects/github/my/HeroicGamesLauncher/public/bin/linux/legendary

(02:43:57) INFO: [Gog]: GOGDL location: /home/user/Projects/github/my/HeroicGamesLauncher/public/bin/linux/gogdl

(02:43:57) INFO: [Backend]:

Heroic Version: 2.2.6 Oden

Legendary Version: 0.20.25 Our Benefactors

OS: Arch KERNEL: 5.16.15-arch1-1 ARCH: x64

CPU: AMD Ryzen 5 3600 6-Core Processor @3.6

RAM: Total: 33.7 GB Available: 23 GB

GRAPHICS: GPU0: NVIDIA GeForce RTX 2060 SUPER VRAM: 8192MB DRIVER: 510.54

PROTOCOL: x11

(02:43:57) INFO: [Gog]: Getting data about the user

(02:43:57) ERROR: [Backend]: Failed to register protocol with OS.

(02:43:58) INFO: [Gog]: Saved user data to config

(02:43:58) INFO: [Frontend]: Refreshing Library

(02:43:58) INFO: [Gog]: Getting GOG library

(02:43:58) INFO: [Gog]: Number of library pages: 1

(02:43:58) INFO: [Gog]: Saved games data

(02:43:58) INFO: [Legendary]: Refreshing library...

(02:43:58) INFO: [Legendary]: Refreshing Epic Games...

(02:43:58) INFO: [Legendary]: Refreshing Epic Games...

(02:43:59) DEBUG: [Legendary]: Running Legendary command: /home/user/Projects/github/my/HeroicGamesLauncher/public/bin/linux/legendary list --include-ue

(02:43:59) INFO: [Legendary]: Updating game list

(02:43:59) INFO: [Legendary]: Game List Updated

(02:44:00) INFO: [Legendary]: Checking for game updates: /home/user/Projects/github/my/HeroicGamesLauncher/public/bin/linux/legendary list-installed --check-updates --tsv

(02:44:00) DEBUG: [Legendary]: Running Legendary command: /home/user/Projects/github/my/HeroicGamesLauncher/public/bin/linux/legendary list-installed --check-updates --tsv

(02:44:00) INFO: [Legendary]: Found 0 game(s) to update

(02:44:00) INFO: [Gog]: Found 0 game(s) to update

(02:44:01) INFO: [Gog]: Getting game metadata: /home/user/Projects/github/my/HeroicGamesLauncher/public/bin/linux/gogdl info 1207661143 --lang=en-US --os windows

(02:44:01) DEBUG: [Gog]: Running GOGDL command: /home/user/Projects/github/my/HeroicGamesLauncher/public/bin/linux/gogdl info 1207661143 --lang=en-US --os windows

(02:44:03) INFO: [Backend]: checking for heroic updates

(02:44:03) INFO: [Backend]: skipping heroic updates

(02:44:07) INFO: [Gog]: Installing 1207661143 with: /home/user/Projects/github/my/HeroicGamesLauncher/public/bin/linux/gogdl download 1207661143 --platform windows --path=/home/user/Games/Heroic --skip-dlcs --lang=en-US

(02:44:07) DEBUG: [Gog]: Running GOGDL command: /home/user/Projects/github/my/HeroicGamesLauncher/public/bin/linux/gogdl download 1207661143 --platform windows --path=/home/user/Games/Heroic --skip-dlcs --lang=en-US

(02:44:07) DEBUG: [Gog]: Logging to file "/home/user/.config/heroic/GamesConfig/1207661143.log"

(02:44:08) INFO: [Backend]: Progress for 1207661143: 0.00/0.00MiB/66931:27:00

(02:44:09) INFO: [Backend]: Progress for 1207661143: 12.68/291.38MiB/00:00:01

(02:44:11) INFO: [Backend]: Progress for 1207661143: 16.68/383.28MiB/00:00:03

(02:44:11) INFO: [Gog]: killing 1207661143

(02:44:11) INFO: [Gog]: 1207661143 killed

(02:44:11) INFO: [Gog]: Getting game metadata: /home/user/Projects/github/my/HeroicGamesLauncher/public/bin/linux/gogdl info 1207661143 --lang=en-US --os windows

(02:44:11) DEBUG: [Gog]: Running GOGDL command: /home/user/Projects/github/my/HeroicGamesLauncher/public/bin/linux/gogdl info 1207661143 --lang=en-US --os windows

(02:44:12) INFO: [Backend]: finished installing

(02:44:12) INFO: [Backend]: Progress for 1207661143: 16.68/383.28MiB/00:00:03

(02:44:13) INFO: [Frontend]: Refreshing Library

(02:44:13) INFO: [Gog]: Getting GOG library

(02:44:13) INFO: [Gog]: Number of library pages: 1

(02:44:13) INFO: [Gog]: Saved games data

(02:44:13) INFO: [Legendary]: Refreshing library...

(02:44:13) INFO: [Legendary]: Updating game list

(02:44:13) INFO: [Legendary]: Game List Updated

(02:44:51) DEBUG: [Gog]: Running GOGDL command: /home/user/Projects/github/my/HeroicGamesLauncher/public/bin/linux/gogdl --version

(02:44:51) DEBUG: [Legendary]: Running Legendary command: /home/user/Projects/github/my/HeroicGamesLauncher/public/bin/linux/legendary --version

(02:45:12) DEBUG: [Gog]: Running GOGDL command: /home/user/Projects/github/my/HeroicGamesLauncher/public/bin/linux/gogdl --version

(02:45:12) DEBUG: [Legendary]: Running Legendary command: /home/user/Projects/github/my/HeroicGamesLauncher/public/bin/linux/legendary --version

### Steps to reproduce

1.Click on install game
2. Cancel/pause download before it finishes

### Expected behavior

Pause/cancel download should work

### System Information

- OS [e. g. "Ubuntu"]: arch linux
- Heroic Version [e. g. 2.1.1]: branch main

### Additional information

I think that https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/pull/1092 broke the process.
From what I see, canceling download kills process gracefully and it doesn't generate error

**Comment by flavioislima** [comment]
Good catch! 
@CommandMC I belive we forgot to test this part.
Should be a simple fix though. 👍

**Comment by dawidgarus** [comment]
I made a fix:
https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/pull/1137

Also tested in a case when gogdl process was killed manually (not by Heroic)

IMHO the assumption that if the command terminates gracefully => download was completed is flawed.
The command should return confirmation that it finished successfully, for example with a json object to stdout as it does with other type of actions.
This is the only way to make sure. Assume failure until success is confirmed, not the other way around.

**Comment by flavioislima** [comment]
@dawidgarus nice, that was quick.
I will test it later.
BTW, what is your username in our discord server?

**Comment by dawidgarus** [comment]
@flavioislima I don't have discord account for privacy and ethical reasons

**Comment by flavioislima** [comment]
> @flavioislima I don't have discord account for privacy and ethical reasons

Not a problem. 👍
