### ISSUE TITLE
German translation: Consider changing "Sie" to "Du"

### ISSUE THREAD

**Issue by 3ole** [Heroic-Games-Launcher/HeroicGamesLauncher#1139]
### Problem description

I've noticed that the German translation uses the possessive pronoun "Sie" when addressing the user. Epic Games, GOG and most other gaminig related services use "Du".

For non German speakers: In German there are two ways to directly address someone (saying "you") in German.

- There's "Sie", which is more formal. In real life it is used to talk to strangers, your boss, etc.
- And there's "Du", which is more informal. In real life it's used when talking to your friends, relatives and generally younger people (~<30 y.o.) talking amongst themselves.

### Feature description

I'd like to rewrite the German translation to use the possessive pronoun "Du". Since it feels more modern and the reasons above. Before changing hundreds of lines I wanted to ask if there are any objections, opinions, etc.

**Comment by flavioislima** [comment]
You can fix translations on our Weblate link:
https://hosted.weblate.org/projects/heroic-games-launcher/
