### ISSUE TITLE
Adjust icon size in tray for Flatpak

### ISSUE THREAD

**Issue by KiritoStorm** [Heroic-Games-Launcher/HeroicGamesLauncher#1140]
### Problem description

It would be cool if they icon size would be normal like the other tray icons on Zorin.
I have the same Issue with ActivityWatch as you see on the screenshot, but they don't know how to fix it maybe you find a solution because in the AppImage Version it's correctly sized. (the right one has the correct size)

![image](https://user-images.githubusercontent.com/46503102/159141004-d1a00868-0998-43f5-b600-3e3063a83d7b.png)

### Feature description

It's more a improvement then I feature. A small quality of life change.

**Comment by flavioislima** [comment]
Just tried to replicate this and on KDE both icons have the same size.
Also, the icon is the same since Heroic flatpak is just an unpacked AppImage. So might be something on flatpak or Zorin side that is not on our control.
