### ISSUE TITLE
[General] "Latest Log" is hard to find

### ISSUE THREAD

**Issue by CommandMC** [Heroic-Games-Launcher/HeroicGamesLauncher#1148]
### Problem description

Currently, the "Latest Log" is hidden away behind the "Tools" tab / the settings. This is rather hard to find.

### Feature description

When Heroic is maximized, there is a lot of space on the main game's page.
![image](https://user-images.githubusercontent.com/34034631/159499745-9e538a62-63e1-4758-b076-19c06568528f.png)
Maybe we could check how much space there is, and based on that move the options in "Tools" back to the main game's page?

### Alternatives

The options could just be moved to the main page all the time, I don't think it'll be a huge issue

**Comment by arielj** [comment]
I'm thinking about something like this:

https://user-images.githubusercontent.com/188464/163093645-9c838476-74b0-4775-8664-5c45e93fa0bf.mp4
