### ISSUE TITLE
[GOG - Linux/macOS] Add ability to install the Wine version of a GOG game even if a native version is available

### ISSUE THREAD

**Issue by tonikarppi** [Heroic-Games-Launcher/HeroicGamesLauncher#1150]
### Problem description

Games on GOG that are available on both Windows and Linux do not always have feature parity. For example, the Linux version of Absolute Drift is missing leaderboard on Linux. Currently Heroic Games Launcher only gives the option to run the native version of a game if the game has one.

### Feature description

An option (global or per-game) that allows the user to display both Windows and native versions of GOG games should fix this problem. This would also allow separate installations of the Windows and native versions.

### Alternatives

A configuration option to switch between native and Windows for each game. This would however prevent both native and Windows variants to be installed at the same time.

### Additional information

Current version: Heroic Games Launcher 2.2.6 from Flatpak

**Comment by flavioislima** [comment]
This is planned. Perhaps for next version already.

**Comment by tonikarppi** [comment]
Awesome, thanks!
