### ISSUE TITLE
[General UI/UX] Update Login Screen with new Designs

### ISSUE THREAD

**Issue by flavioislima** [Heroic-Games-Launcher/HeroicGamesLauncher#1153]
### Problem description

Right now we have a login screen that suffices for two stores, but as soon as Heroic starts adding support for more stores, would be important to have a design that could fit them.

### Feature description

We should have the design as on the screenshots below (Amazon Games is an example but could be other stores as well):

![image](https://user-images.githubusercontent.com/26871415/159680300-c02418f0-a0cc-4a62-b137-089d4d2d4ca5.png)
![image](https://user-images.githubusercontent.com/26871415/159680348-9161b16f-bbc4-40fb-b7a6-a31f34834bf0.png)

**Comment by tildemarky** [comment]
I'd love to work on this if it's still available!

**Comment by flavioislima** [comment]
@tildemarky 
Yes, no one is working on it. Feel free to grab it 👍🏽

**Comment by flavioislima** [comment]
@tildemarky you can check for the design specs here
https://www.figma.com/file/Zv89aBtLJ8yN4BwFS0AwNb/Heroic-Games?node-id=0%3A1

I forgot to share before, sorry.

**Comment by tildemarky** [comment]
> @tildemarky you can check for the design specs here https://www.figma.com/file/Zv89aBtLJ8yN4BwFS0AwNb/Heroic-Games?node-id=0%3A1
> 
> I forgot to share before, sorry.

No problem! Thank you that is super useful 🙌

**Comment by flavioislima** [comment]
done
