### ISSUE TITLE
Add shortcut for manually installed games

### ISSUE THREAD

**Issue by adocampo** [Heroic-Games-Launcher/HeroicGamesLauncher#1158]
### Problem description

I have some games installed from a ISO/DVD, I tried to make them work with Lutris, PoL or Boxes, even manually, but they have a lot of tinkering for my side and just tried to drag the executable on Heroic... all of them worked out of the box.

I would like to add a shortcut for those kind of installations: installed manually through wine, and then make a shortcut to be executed inside Heroic's prefix and settings.

### Feature description

Inside Settings --> Wine, beside the "Run EXE on Prefix", should be another button "Create shortcut for an EXE", so users could create a shorcut for those EXE they tried beforehand with the "Run EXE on Prefix".

**Comment by flavioislima** [comment]
In the future we want to add a Heroic type of games that you could add anything to run with it. But not like you are proposing since its not that practial.
so just wait for future updates that we will add this feature to Heroic.

**Comment by adocampo** [comment]
Cool! As long as we can add any kind of game regardless of their origin, it will be more than cool. Surely you already thought a good way to add them, and surely that way will include a mechanism to let a `.desktop` file so users can call the game from the desktop launcher, without any need to open previously Heroic.

Will keep an eye for futures updates, I hope it will not be too difficult to implement and  this feature will be released soon, as I have several games installed manually outside Epic, Steam or GoG.
