### ISSUE TITLE
Inconsistent behaviour on game card with controller

### ISSUE THREAD

**Issue by arshubham** [Heroic-Games-Launcher/HeroicGamesLauncher#1161]
### Describe the bug

Pressing A on the game card with a controller launches the game. It should take to the game details page. Only play button on the card should launch the game.

Edit: Pressing Y opens the game page if the game is installed. If the game is not installed Y does nothing. Also Pressing A on a non-installed game takes user to game page.

### Add logs

Not Applicable

### Steps to reproduce

1. Connect a controller.
2. Navigate to Store home.
3. Navigate and select game (should be installed)
4. Press A.
5. Game is launched.

### Expected behavior

User is taken to the game details page. Works correctly on a non-installed game.

Edit: Pressing A when game card is focused should always have consistent behavior for installed and not installed games.

### Screenshots

https://user-images.githubusercontent.com/14235191/160234359-41cdaf9b-c25a-4757-9bc7-156dd7e61913.mp4

### System Information

- Operating System: Arch Linux
- KDE Plasma Version: 5.24.3
- KDE Frameworks Version: 5.92.0
- Qt Version: 5.15.3
- Kernel Version: 5.16.16-arch1-1 (64-bit)
- Graphics Platform: Wayland
- Processors: 24 × AMD Ryzen 9 3900X 12-Core Processor
- Memory: 15.6 GiB of RAM
- Graphics Processor: AMD Radeon RX 580 Series

### Additional information

Using Xbox Series controller with latest firmware.

**Comment by imLinguin** [comment]
I think this was intended. Primary action - A runs a game if it's installed, Y opens a game page. I agree that might be a little unintuitive.

**Comment by arshubham** [comment]
However there is no way to reach the game details page by controller at all to access system requirements/Tools page at all.

**Comment by arielj** [comment]
Pressing A to run the game when highlighting the card was requested, but I would try to follow whatever Steam Deck does for consistency, we actually have some hacky code to run the game instead of opening the game details

Though I think different people expect different things to happen and maybe a poll is needed. Some people want to get rid of the play/gear icons for example.

**Comment by flavioislima** [comment]
Is this still the case? we had a few PRs addressing controller navigation since this was opened.
@arshubham @arielj
