### ISSUE TITLE
Contoller Navigation Enhancement

### ISSUE THREAD

**Issue by arshubham** [Heroic-Games-Launcher/HeroicGamesLauncher#1162]
### Problem description

Some controller navigation enhancements I would like heroic to implement.

### Feature description

1. First Played, Last Played should by excluded from Navigation. No Actions are linked.
![Screenshot_20220326_154803](https://user-images.githubusercontent.com/14235191/160235178-a585c93c-dcaf-4487-a1f7-3b4a849cda96.png)
2. Play Now/ Install should be auto selected on loading the game details page when navigating by controller. Currently nothing is selected. It takes 5 button presses to reach the button.

https://user-images.githubusercontent.com/14235191/160235292-b9c1513e-0156-4053-b2a1-21191bfc48be.mp4

3. Install Path should be excluded from controller navigation. Pressing A on it opens file browser not navigable by controller. Maybe a popup with link open confirmation solve the issue.
![Screenshot_20220326_154732](https://user-images.githubusercontent.com/14235191/160235503-cd7291e2-f578-4223-be3c-8e3e27846ea6.png)

4. Tabs on game details page should be navigable by Left and Right Button Shoulder buttons (LB and RB). Many games use the same scheme for setting navigation. 
![image](https://user-images.githubusercontent.com/14235191/160235524-2eec01ef-46a8-4115-a2ac-852e8be26189.png)

5. Remove Install, Play and Settings Buttons from game cards in home page. They make navigation unnecessarily  cumbersome (it takes 3 button presses to go to next card in case of installed games). Pressing A on card should take to game details page directly like Steam Deck.
![Screenshot_20220326_155756](https://user-images.githubusercontent.com/14235191/160235497-175584df-c6a4-4f7c-b3de-e720e10109fb.png)

6. Show Controller specific icons for navigation to aid discoverability. For eg (Status bar should show button combination to access search, Select, Back Etc). Tabs in game page should show LB and RB button on either side of the tabs in case Point 4 is implemented.

### Alternatives

Not Applicable. 

### Additional information

All observations are based navigating with a  Xbox Series Controller.

**Comment by flavioislima** [comment]
Is this still the case? we had a few PRs addressing controller navigation since this was opened.
@arshubham
