### ISSUE TITLE
Select game language

### ISSUE THREAD

**Issue by MrArdillo** [Heroic-Games-Launcher/HeroicGamesLauncher#1164]
An option to select the game language before the instalation proccess

**Comment by imLinguin** [comment]
It's already there for GOG games that support it. I'm not sure if Epic has options like that in their official launcher.

**Comment by MrArdillo** [comment]
I remember a menu for that in fornite. I said that because i wanted to install a batman game in spanish and it was installed in english. Luckily i found how to change the language by modifing a archive in the game. But it will be better if the game language can be selected before (i dont know if it is a game problem or a epic problem)

**Comment by flavioislima** [comment]
Epic doesn't support this and GOG already has an implementation. So closing this one.

**Comment by doppelhelix** [comment]
Apparently it does. Take Maneater for example: [https://forums.tripwireinteractive.com/index.php?threads/cant-change-language.2336360](https://forums.tripwireinteractive.com/index.php?threads/cant-change-language.2336360)  Right now the only way to change the language with Heric Games Launcher for e.g. the game "Maneater" is to change the environment variable LC_ALL to whatever language I want to play with

**Comment by arielj** [comment]
> Apparently it does. Take Maneater for example: https://forums.tripwireinteractive.com/index.php?threads/cant-change-language.2336360 Right now the only way to change the language with Heric Games Launcher for e.g. the game "Maneater" is to change the environment variable LC_ALL to whatever language I want to play with

the next beta release will include a game language setting, it doesn't work for every game since it depends on game developers adhering to epic's arguments, but it will work for some (I'll try if it actually works with maneater later)

**Comment by arielj** [comment]
I just tested maneater with the beta build and the language setting applied by Heroic does in fact changes the game's language, not sure how that will play with the LC_ALL variable though, haven't tried that.

**Comment by MrArdillo** [comment]
Nice, thanks for the job!!

**Comment by dLeandroT** [comment]
**I found a solution** on the Discord server.
Change my Legendary `config.ini` file. It looks just like this:

```
[Legendary]
; Disables the automatic update check
disable_update_check = false
; Disables the notice about an available update on exit
disable_update_notice = false
; locale override, must be in RFC 1766 format (e.g. "en-US")
locale = es-co

[a64dcf9b711a4a60a3c0b6f052dfc7da]
; override language with two-letter language code
language = es-co
```
The file path is:
`~/.config/legendary/config.ini`

Now my games run in Spanish.
Thanks to @arieljuod in the "🇪🇸-spanish-chat"

**Comment by Sightlyjester** [comment]
> **I found a solution** on the Discord server. Change my Legendary `config.ini` file. It looks just like this:
> 
> ```
> [Legendary]
> ; Disables the automatic update check
> disable_update_check = false
> ; Disables the notice about an available update on exit
> disable_update_notice = false
> ; locale override, must be in RFC 1766 format (e.g. "en-US")
> locale = es-co
> 
> [a64dcf9b711a4a60a3c0b6f052dfc7da]
> ; override language with two-letter language code
> language = es-co
> ```
> 
> The file path is: `~/.config/legendary/config.ini`
> 
> Now my games run in Spanish. Thanks to @arieljuod in the "🇪🇸-spanish-chat"

Hi Leandro, I need your help. I saw this comment where you said that you changed with a config.ini file the configuration of Heroic Games Launcher so that it would launch the games in Spanish. I have tried but I get this error:
![Heroic Games Launcher](https://user-images.githubusercontent.com/105895386/177217837-8dd68b8e-4df3-4dd4-a639-95bdf9637b62.jpg)

In the path you put, in .config, I created the legendary folder, and then I created the .ini file with the lines you put, I just copied and pasted. Then with Heroic I tried to open the config.ini in the path and it gave me the error you see in this image

**Comment by dLeandroT** [comment]
try the beta version first, they are working on adding that feature. 

Although, for now, modifying the file worked fine for me.
