### ISSUE TITLE
[Flatpak] Shortcut creation not working due to missing folder and permissions

### ISSUE THREAD

**Issue by Krezzlu** [Heroic-Games-Launcher/HeroicGamesLauncher#1165]
### Describe the bug

In the Flatpak version the 'Add shortcut' button does not create .desktop files due to the missing folder `~/.var/app/com.heroicgameslauncher.hgl/.local/share/applications` and missing permissions for `~/Desktop`.

### Add logs

```
(17:28:51) INFO:    [Legendary]:       Location: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary
(17:28:51) INFO:    [Gog]:             Location: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl
(17:28:52) INFO:    [Backend]:         
  Heroic Version: 2.2.6 Oden
  Legendary Version:  0.20.25 Our Benefactors
  OS: Freedesktop.org KERNEL: 5.16.16-200.fc35.x86_64 ARCH: x64
  CPU: Intel Core™ i7-5820K @3.3 GOVERNOR: schedutil
  RAM: Total: 16.6 GB Available: 11.9 GB
  GRAPHICS: GPU0: GM204 [GeForce GTX 980]  VRAM: 32MB DRIVER:  
  PROTOCOL: x11
  
(17:28:52) INFO:    [Gog]:             Getting data about the user
(17:28:52) ERROR:   [Backend]:         Failed to register protocol with OS.
(17:28:52) INFO:    [Gog]:             Saved user data to config
(17:28:53) INFO:    [Frontend]:        Refreshing Library
(17:28:53) INFO:    [Gog]:             Getting GOG library
(17:28:53) INFO:    [Gog]:             Number of library pages: 1
(17:28:53) INFO:    [Gog]:             Saved games data
(17:28:53) INFO:    [Legendary]:       Refreshing library...
(17:28:53) INFO:    [Legendary]:       Refreshing Epic Games...
(17:28:53) INFO:    [Legendary]:       Refreshing Epic Games...
(17:28:54) INFO:    [Legendary]:       [cli] INFO: Logging in...
(17:28:54) INFO:    [Legendary]:       [Core] INFO: Trying to re-use existing login session...
(17:28:54) INFO:    [Legendary]:       [cli] INFO: Getting game list... (this may take a while)
(17:28:55) INFO:    [Legendary]:       Updating game list
(17:28:55) INFO:    [Legendary]:       Game List Updated
(17:28:56) INFO:    [Legendary]:       Checking for game updates
(17:28:56) INFO:    [Legendary]:       Found 0 game(s) to update
(17:28:56) INFO:    [Gog]:             Found 0 game(s) to update
(17:28:57) INFO:    [Backend]:         checking for heroic updates
(17:28:57) INFO:    [Backend]:         skipping heroic updates
(17:29:01) INFO:    [Backend]:         Shortcut saved on /var/home/USER/.var/app/com.heroicgameslauncher.hgl/.local/share/applications/Into the Breach.desktop
(17:29:01) INFO:    [Backend]:         Shortcut saved on /var/home/USER/Desktop/Into the Breach.desktop

```

### Steps to reproduce

1. Go to any game in library
2. Click on 'Tools'
3. Click on 'Add shortcut'
4. Nothing Happens

### Expected behavior

According to the logs a .desktop file should be created in `~/.var/app/com.heroicgameslauncher.hgl/.local/share/applications` and `~/Desktop`.

### System Information

- **OS**: Fedora Silverblue 35
- **Heroic Version**: 2.2.6 Oden Flatpak

**Comment by flavioislima** [comment]
Yes, we need for this new launcher portal to be implemented in Electron for then it starts working in Heroic.
Because even if Heroic creates the shortcut file, it will fail to launch it.

I am closing this one for now since it's not a Heroic issue.

**Comment by JakobDev** [comment]
@flavioislima You can call the D-Bus API by yourself. There is no need for electron to do that. If you use a internal function of Electron, to create the .desktop file, it will take a lot of time. The Dynamic Launcher Portal has been added in version 1.14.0 which released 11 Days ago, so it will probably take a lot of time. for Electron to adopt this. It should be better to use something like if if Flatpak then call Dynamic Launchers Portal with D-Bus else use the current existing code.

**Comment by flavioislima** [comment]
I was meaning the protocol register actually.
Do protocols already work on Flatpaks? 
The desktop file we handle in Heroic. But they just call the protocol `heroic://launch/Sugar` for instance.

**Comment by Krezzlu** [comment]
It works in the steam flatpak eg.: `Exec=xdg-open steam://rungameid/240720`.

**Comment by JakobDev** [comment]
@flavioislima The registration of the MimeType is done through the .desktop file, so it works in Flatpak
