### ISSUE TITLE
[Flatpakt] Heroic Launcher v. 2.2.6 dont find any winetricks (on Steam Deck) 

### ISSUE THREAD

**Issue by Sasuchisama** [Heroic-Games-Launcher/HeroicGamesLauncher#1168]
### Describe the bug

If i want to setting up winetricks (on button), nothing happens. The Game log says something like: "Check if winetricks available or check (Path to wine-prefix-path). "Ive checked the path.

I tested it with the Appimage v2.2.6 and winetricks works without problems. @

### Add logs

- No logs available ( havent a sd card to copy easily the log) - I edit this later today.

### Steps to reproduce

- I ve installed Heroic Games Launcher from Discovery on Steam Deck
- Setup EPIC Account
- Download a Game (Horizon Zero Dawn)
- Use Wine 7.2 GE-2
- click on the winetricks button

### Expected behavior

Click on button "winetricks" should open winetricks.

### System Information

- Updated Steam Deck on latest version: Holo OS - Kernel 5.13.0-valve10.1-1-neptune-02144

**Comment by flavioislima** [comment]
Yes, this was fixed already so will be fixed on the next release.

**Comment by safijari** [comment]
When do you expect the next release on flathub would be for this?
