### ISSUE TITLE
Save Sync not working with games like Tiny's Tinas Wonderlands 

### ISSUE THREAD

**Issue by larsstrandos** [Heroic-Games-Launcher/HeroicGamesLauncher#1175]
### Describe the bug

When I install Tiny Tina's Wonderlands and want to Sync Saves its's not working and I am not getting the saves.

### Add logs

No logs to show

### Steps to reproduce

Download the game and try syncing trough the launcher

### Expected behavior

Getting saves from Epic Games Launcher Cloud Saves

### System Information

- OS [e. g. "Pop!_OS 21.10"]:
- Running Wine 7.4 and it is emulating Windows 7 - No changes made to the default 
- Heroic Version [e. g. 2.2.6]:

### Additional information

My solution to fix the problem:
```
cd ~/Games/Heroic/Prefixes/Tiny-Tinas-Wonderlands/drive_c/users/<your username>/Documents/My Games
ln -s Tiny\ Tina\'s\ Wonderlands Tiny\ Tinas\ `Wonderlands
```

Inside Heroic Launcher go to game setting > Save-Sync and change Override Cloud Sync Save and change "My Documents" to "Documents"

The Launcher try's to sync into a folder named "My Documents" but the game uses "Documents", and also the launcher doesn't support syncing to a folder with the ' inside the name as Tiny Tina's Wonderlands has. So creating a symlink and changing the folder name inside the Heroic launcher fixes the problems.

**Comment by wiryfuture** [comment]
This appears to be an issue with [Legendary](https://github.com/derrod/legendary), which is what actually handles getting save states and launching the game etc, please create an issue there.
Cheers.

**Comment by pmarreck** [comment]
Since it seems like no one else created the issue against Legendary, I just did FYI
