### ISSUE TITLE
Flatpak wasn't updated to 2.2.6 on Org Repository

### ISSUE THREAD

**Issue by andybe** [Heroic-Games-Launcher/HeroicGamesLauncher#1177]
diff --git a/flatpak/com.heroicgameslauncher.hgl.yml b/flatpak/com.heroicgameslauncher.hgl.yml
index 79189b2..251caf3 100644
--- a/flatpak/com.heroicgameslauncher.hgl.yml
+++ b/flatpak/com.heroicgameslauncher.hgl.yml
@@ -129,8 +129,8 @@ modules:
         x-checker-data:
           type: electron-updater
           url: https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/releases/latest/download/latest-linux.yml
-        url: https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/releases/download/v2.2.5/Heroic-2.2.5.AppImage
-        sha512: 26b78115c75d45101df506ed65ccb2ba19a0900fb0ac03615a64af6424271a121600724214c3737ccc62e8f888adf258e6a3131a13b1632fd7c43008b7521dd7
+        url: https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/releases/download/v2.2.6/Heroic-2.2.6.AppImage
+        sha512: 316fe8c4590e77355dbe936cb3eb96e9710ab53ace6a2644bedbafbf4d62bcd3aaf30edf9896fe13ac3322d6c53c27e270e0af534cd51ee377a88c57ee297ffc
 
   - name: platform-bootstrap
     buildsystem: simple

**Comment by flavioislima** [comment]
Flatpak is currently on 2.2.6.
Can you check on your tray icon > About?

**Comment by andybe** [comment]
Did a pull today. Wired and rebuild with only flatpak-build.

**Comment by flavioislima** [comment]
A-ha, ok, but that's the wrong repository. I need to setup a CI build to update that one.
this is the correct one:
https://github.com/flathub/com.heroicgameslauncher.hgl

**Comment by andybe** [comment]
> A-ha, ok, but that's the wrong repository. I need to setup a CI build to update that one. this is the correct one: https://github.com/flathub/com.heroicgameslauncher.hgl

Hm,- why two different? I just ask.
