### ISSUE TITLE
Add game time tracking option

### ISSUE THREAD

**Issue by stiw91** [Heroic-Games-Launcher/HeroicGamesLauncher#1180]
### Feature description

Although unnecessary, the option to track game time and display it in the game library would be welcome, and if possible, when importing a game from EGS or GOG, it also imports the game time as well, if it's even possible to import/export gam time

**Comment by flavioislima** [comment]
Heroic already track play time, it shows it on the game page.
It is not possible to import game time when importing a game since this information is not available.
