### ISSUE TITLE
Heroic Library missing games and cannot install new games

### ISSUE THREAD

**Issue by wouter1984** [Heroic-Games-Launcher/HeroicGamesLauncher#1181]
### Describe the bug

I claim the Epic weekly free games and the last few weeks I have trouble with Heroic:

I claimed Cities Skylines, Demon Tilt, In Sound Mind, Total War Warhammer and City of Brass, none of these games are listed in my Heroic Library. When I open Epic Games on a windows machine I do see these games in my library there.
Yesterday I also noticed I cannot install any new games, When I click an install button the arrows keep spinning and no installation popup appears, Even waiting 2+ hours doesn't popup the installation screen.
(Last games that were added to my library is Centipede Recharched and Black Widow Recharged which I claimed the 3rd of March)

I tried the "heroic reset" and "Clear Heroic cache" options. I have logged out multiple times and tried reloading several times to no avail. Also I logged out and back in using the SID login method, but nothing seems to work.

### Add logs

(09:12:39) INFO:    [Legendary]:       Location: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary
(09:12:39) INFO:    [Gog]:             Location: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl
(09:12:40) INFO:    [Backend]:         
  Heroic Version: 2.2.6 Oden
  Legendary Version:  0.20.6 A Red Letter Day
  OS: Ubuntu KERNEL: 5.15.32-xanmod1 ARCH: x64
  CPU: Intel Core™2 Quad Q9650 @3 GOVERNOR: ondemand
  RAM: Total: 8.34 GB Available: 5.95 GB
  GRAPHICS: GPU0: NVIDIA GeForce GTX 960 VRAM: 4096MB DRIVER: 510.60.02 
  PROTOCOL: x11
  
(09:12:40) INFO:    [Gog]:             Getting data about the user
(09:12:41) WARNING: [Backend]:         Protocol already registered.
(09:12:41) INFO:    [Gog]:             Saved user data to config
(09:12:43) INFO:    [Frontend]:        Refreshing Library
(09:12:43) INFO:    [Gog]:             Getting GOG library
(09:12:43) INFO:    [Gog]:             Number of library pages: 2
(09:12:43) INFO:    [Gog]:             Getting data for page 2
(09:12:43) INFO:    [Gog]:             Saved games data
(09:12:43) INFO:    [Legendary]:       Refreshing library...
(09:12:43) INFO:    [Legendary]:       Refreshing Epic Games...
(09:12:43) INFO:    [Legendary]:       Refreshing Epic Games...
(09:12:44) INFO:    [Legendary]:       usage: legendary [-h] [-v] [-y] [-V]
                 {auth,install,download,update,repair,uninstall,launch,list-games,list-installed,list-files,list-saves,download-saves,sync-saves,verify-game,import-game,egl-sync,status,cleanup}
                 ...
legendary: error: argument subparser_name: invalid choice: 'list' (choose from 'auth', 'install', 'download', 'update', 'repair', 'uninstall', 'launch', 'list-games', 'list-installed', 'list-files', 'list-saves', 'download-saves', 'sync-saves', 'verify-game', 'import-game', 'egl-sync', 'status', 'cleanup')
(09:12:44) INFO:    [Legendary]:       Updating game list
(09:12:44) INFO:    [Legendary]:       Game List Updated
(09:12:46) INFO:    [Legendary]:       Checking for game updates
(09:12:46) INFO:    [Legendary]:       Found 0 game(s) to update
(09:12:46) INFO:    [Gog]:             Found 0 game(s) to update
(09:12:47) INFO:    [Backend]:         checking for heroic updates

### Steps to reproduce

new games not added to library
any game install will not work

### Expected behavior

hoping to find a way to resolve the issue or reinstall heroic, I do see the Legendary error in the log, but wouldn't know how to resolve that error...

### System Information

- kubuntu 20.04 LTS
- Heroic Version 2.2.6 (Latest).

**Comment by flavioislima** [comment]
I can see you have an old Legendary version installed on your system and Heroic is using it.
Remove it or upgrade it to latest version (0.20.25).
`Legendary Version: 0.20.6 A Red Letter Day`
