### ISSUE TITLE
Unable to find GE-Proton installations

### ISSUE THREAD

**Issue by vhda** [Heroic-Games-Launcher/HeroicGamesLauncher#1184]
Looks like the pattern matching expects the installation to start with Proton, which is no longer true since it was renamed:

https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/blob/756a1e728800371b799d56cbc62201f70d1e8d40/electron/config.ts#L266

**Comment by flavioislima** [comment]
Hi!
Yes, will be fixed on the next release.

**Comment by vhda** [comment]
Obrigado!

**Comment by flavioislima** [comment]
Fixed upstream
![image](https://user-images.githubusercontent.com/26871415/161987152-3b7be65f-9ebe-40dc-a55d-e719bafa5194.png)
