### ISSUE TITLE
Ziggurat won't launch through HGS, need to launch start.sh from terminal

### ISSUE THREAD

**Issue by TheEpicNoobZilla** [Heroic-Games-Launcher/HeroicGamesLauncher#1189]
### Describe the bug

When i try to launch this game using HGS i get missing libGLU.so error. When i launch this game by typing "./start.sh" in installation directory it launchs without any errors. I've tested also Dungeons 2 and it launched perfectly so i don't know if it's game related problem or something bigger

### Add logs

Error - Command failed: /app/bin/gamemoderun  "/app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl" launch "/home/fedex/Games/Heroic/Ziggurat"  1437564865 --platform=linux  
gamemodeauto: 
dbus[4330]: arguments to dbus_pending_call_block() were incorrect, assertion "pending != NULL" failed in file ../../dbus/dbus-pending-call.c line 765.
This is normally a bug in some application using the D-Bus library.

  D-Bus not built with -rdynamic so unable to print a backtrace
dbus[4334]: arguments to dbus_pending_call_block() were incorrect, assertion "pending != NULL" failed in file ../../dbus/dbus-pending-call.c line 765.
This is normally a bug in some application using the D-Bus library.

  D-Bus not built with -rdynamic so unable to print a backtrace
dbus[4338]: arguments to dbus_pending_call_block() were incorrect, assertion "pending != NULL" failed in file ../../dbus/dbus-pending-call.c line 765.
This is normally a bug in some application using the D-Bus library.

  D-Bus not built with -rdynamic so unable to print a backtrace
./Ziggurat.x86_64: error while loading shared libraries: libGLU.so.1: cannot open shared object file: No such file or directory
dbus[4327]: arguments to dbus_pending_call_block() were incorrect, assertion "pending != NULL" failed in file ../../dbus/dbus-pending-call.c line 765.
This is normally a bug in some application using the D-Bus library.

  D-Bus not built with -rdynamic so unable to print a backtrace

### Steps to reproduce

1. Go to gog libary
2. Click on launch ziggurat
3. Scroll down to ./Ziggurat.x86_64
4. See error log

### Expected behavior

Game launches

### System Information

- OS Fedora 35
- Heroic Version 2.2.6 Flathub:

**Comment by imLinguin** [comment]
Try enabling Steam Runtime in game settings

**Comment by flavioislima** [comment]
@TheEpicNoobZilla have you tried? if it doenst work you can open the issue again.
