### ISSUE TITLE
Unable to open GTA 5 in archcraft

### ISSUE THREAD

**Issue by vignesh1410-tech** [Heroic-Games-Launcher/HeroicGamesLauncher#1191]
### Describe the bug

when i open the gta 5 game in heroic launcher it show me a prompt that internet connection is require
![Screenshot_2022-04-08-05-02-37_1366x768](https://user-images.githubusercontent.com/64078194/162436500-19126e2a-fd37-44e9-8377-8714d2f972dd.png)
d

### Add logs

(17:21:30) INFO:    [Legendary]:       Location: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary
(17:21:30) INFO:    [Gog]:             Location: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl
(17:21:32) INFO:    [Backend]:         
  Heroic Version: 2.2.6 Oden
  Legendary Version:  0.20.25 Our Benefactors
  OS: archcraft KERNEL: 5.17.1-zen1-1-zen ARCH: x64
  CPU: AMD A6-9225 RADEON R4, 5 COMPUTE CORES 2C+3G @1.82 GOVERNOR: schedutil
  RAM: Total: 3.47 GB Available: 2.76 GB
  GRAPHICS: GPU0: Stoney [Radeon R2/R3/R4/R5 Graphics] VRAM: 256MB DRIVER:  
  PROTOCOL: x11
  
(17:21:33) WARNING: [Backend]:         Protocol already registered.
(17:21:35) INFO:    [Frontend]:        Refreshing Library
(17:21:35) INFO:    [Legendary]:       Refreshing library...
(17:21:35) INFO:    [Legendary]:       Refreshing Epic Games...
(17:21:35) INFO:    [Legendary]:       Refreshing Epic Games...
(17:21:37) INFO:    [Legendary]:       [cli] INFO: Logging in...
(17:21:37) INFO:    [Backend]:         launching Grand Theft Auto V 9d2d0eb64d5c44529cece33fe2a46482
(17:21:38) INFO:    [Legendary]:       [Core] INFO: Logging in...
(17:21:42) ERROR:   [Backend]:         TypeError - Cannot destructure property 'stderr' of 'undefined' as it is undefined.
(17:21:42) INFO:    [Legendary]:       [cli] INFO: Getting game list... (this may take a while)
(17:21:42) INFO:    [Legendary]:       Updating game list
(17:21:42) INFO:    [Legendary]:       Game List Updated
(17:21:42) INFO:    [Backend]:         checking for heroic updates
(17:21:45) INFO:    [Legendary]:       Checking for game updates
(17:21:45) INFO:    [Legendary]:       Found 0 game(s) to update
(17:21:45) INFO:    [Gog]:             Found 0 game(s) to update
(17:22:12) INFO:    [Backend]:         launching Grand Theft Auto V 9d2d0eb64d5c44529cece33fe2a46482
(17:22:18) ERROR:   [Backend]:         TypeError - Cannot destructure property 'stderr' of 'undefined' as it is undefined.
(17:24:09) INFO:    [Backend]:         launching Grand Theft Auto V 9d2d0eb64d5c44529cece33fe2a46482
(17:24:17) ERROR:   [Backend]:         TypeError - Cannot destructure property 'stderr' of 'undefined' as it is undefined.
(17:25:17) INFO:    [Backend]:         launching Grand Theft Auto V 9d2d0eb64d5c44529cece33fe2a46482
(17:25:20) ERROR:   [Backend]:         TypeError - Cannot destructure property 'stderr' of 'undefined' as it is undefined.
(17:25:24) WARNING: [DXVKInstaller]:   DXVK cannot be installed on a Proton or a invalid prefix!
(17:25:50) INFO:    [Backend]:         launching Grand Theft Auto V 9d2d0eb64d5c44529cece33fe2a46482
(17:25:52) ERROR:   [Backend]:         TypeError - Cannot destructure property 'stderr' of 'undefined' as it is undefined.
(17:26:17) INFO:    [Backend]:         launching Grand Theft Auto V 9d2d0eb64d5c44529cece33fe2a46482
(17:26:20) ERROR:   [Backend]:         TypeError - Cannot destructure property 'stderr' of 'undefined' as it is undefined.

### Steps to reproduce

1. Go to library 
2. Click on the play button in gta 5

### Expected behavior

-

### System Information

Heroic Version: 2.2.6 Oden
  Legendary Version:  0.20.25 Our Benefactors
  OS: archcraft KERNEL: 5.17.1-zen1-1-zen ARCH: x64
  CPU: AMD A6-9225 RADEON R4, 5 COMPUTE CORES 2C+3G @1.82 GOVERNOR: schedutil
  RAM: Total: 3.47 GB Available: 2.76 GB
  GRAPHICS: GPU0: Stoney [Radeon R2/R3/R4/R5 Graphics] VRAM: 256MB DRIVER:  
  PROTOCOL: x11

**Comment by flavioislima** [comment]
Do you have internet?
Is any proxy blocking Heroic requests?

**Comment by Nocccer** [comment]
That was also my thought. He tried among us and it worked. Does among us need internet ?

**Comment by flavioislima** [comment]
have no idea, but someone else can replicate this?

**Comment by flavioislima** [comment]
Closing this one since no answer for 3 weeks.
