### ISSUE TITLE
"Error - Invalid Path" when attempting to sync with EGS

### ISSUE THREAD

**Issue by ommer15** [Heroic-Games-Launcher/HeroicGamesLauncher#1192]
### Describe the bug

im attempting to sync heroic with epic games (as a part of an attempt of importing gta v from an already installed path), though every time i enter the epic games' installation path it returns an error "invalid path" (image linked below). i entered the path including all of the epic games installation files and it keeps returning that error. am i doing something wrong? am i entering the wrong path? i tried multiple different paths and it returns the same exact error. what path should i be entering anyway?

im using macos monterey 12.3.1 (latest stable release as im writing this)
heroic games launcher (mac installation, installed on the **internal** ssd)
epic games launcher (windows installation, installed on an **external** ssd, along with gta v in a different directory)

in addition to all of this i am also using crossover to run the rockstar games launcher and to (hopefully) run gta v along with it

thanks in advance

### Add logs

(22:45:59) INFO:    [Legendary]:       Location: /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/legendary
(22:45:59) INFO:    [Gog]:             Location: /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/gogdl
(22:46:15) INFO:    [Backend]:         
  Heroic Version: 2.2.6 Oden
  Legendary Version:  0.20.25 Our Benefactors
  OS: macOS KERNEL: 21.4.0 ARCH: x64
  CPU: Intel Core™ i5-8210Y @1.6 
  RAM: Total: 8.59 GB Available: 7.14 GB
  GRAPHICS: GPU0: Intel UHD Graphics 617 VRAM: 1536MB DRIVER:  
  
  
(22:46:16) WARNING: [Backend]:         Protocol already registered.
(22:46:17) INFO:    [Frontend]:        Refreshing Library
(22:46:17) INFO:    [Legendary]:       Refreshing library...
(22:46:17) INFO:    [Legendary]:       Refreshing Epic Games...
(22:46:17) INFO:    [Legendary]:       Refreshing Epic Games...
(22:46:22) INFO:    [Backend]:         checking for heroic updates
(22:46:26) INFO:    [Legendary]:       [cli] INFO: Logging in...
[Core] INFO: Trying to re-use existing login session...
(22:46:27) INFO:    [Legendary]:       [cli] INFO: Getting game list... (this may take a while)
(22:46:47) INFO:    [Legendary]:       Updating game list
(22:46:47) INFO:    [Legendary]:       Game List Updated
(22:47:14) INFO:    [Legendary]:       Checking for game updates
(22:47:14) INFO:    [Legendary]:       Found 0 game(s) to update
(22:47:14) INFO:    [Gog]:             Found 0 game(s) to update
(22:47:16) ERROR:   [Legendary]:       Error: Command failed: legendary egl-sync --enable-sync --egl-wine-prefix /Volumes/Omer 2TB/_Windows/Epic Games -y

### Steps to reproduce

- open heroic
- settings -> general -> sync with installed epic games -> sync
- navigate to the epic games directory (e.g "/Users/user/Application Support/Epic Games/")
- select the folder, then press sync

### Expected behavior

was expecting heroic to recognize the path and sync the installed epic games games

### Screenshots

error message:
<img width="305" alt="image" src="https://user-images.githubusercontent.com/80837492/162516538-69b351b0-11fa-4a52-baf1-d9204247068b.png">

the directory i am attempting to sync (marked in purple, should look similar on other platforms):
<img width="633" alt="image" src="https://user-images.githubusercontent.com/80837492/162517430-0831e554-9a45-42fd-9158-4f9527981be7.png">

### System Information

- OS [macOS Monterey 12.3.1]: 
- Heroic Version [2.2.6 (macOS installation)]:

**Comment by flavioislima** [comment]
You are trying to sync with the native epic store or with one installed with wine/CrossOver?

Also, if it is one game you can import it on the install dialog.

**Comment by ommer15** [comment]
the native one, i got it installed from another windows pc

and thanks so much for letting me know about the option of importing games individually, that could probably serve as a workaround for my issue

**Comment by flavioislima** [comment]
Yes, this doesn't work then.
EGL sync works only on the same platform or the windows version if installed using wine or crossover.
If you just copy the contents of the windows one to the mac, it won't work.
