### ISSUE TITLE
[Minor Feature Request] Show Electron version in General settings

### ISSUE THREAD

**Issue by GitThisBugOff** [Heroic-Games-Launcher/HeroicGamesLauncher#1194]
### Problem description

---
![suggestion](https://user-images.githubusercontent.com/39744079/162584141-e80f10e0-9e84-4f38-9b7d-906ff41f7a4f.png)

### Feature description

Include a simple text line that states the Electron version Heroic is built with. Bonus points if it also says it's running on Wayland or X11.

**Comment by flavioislima** [comment]
You can check all this info about your system opening the log on settings now.
And the heroic version is also on General settings

**Comment by Root-Core** [comment]
@flavioislima I can not find the electron version in the logs. Am I missing something?
I'm using AUR's `heroic-game-launcher-bin` on Manjaro.

**Comment by flavioislima** [comment]
> @flavioislima I can not find the electron version in the logs. Am I missing something?
> I'm using AUR's `heroic-game-launcher-bin` on Manjaro.

That's the issue, we do not have the electron version anywhere. We need to find a way of getting it and out into a global constant on backend that can be accessed on front-end as well.
