### ISSUE TITLE
GoG game saves. Cyberpunk2077 saves but then menu blank when reload game.

### ISSUE THREAD

**Issue by dopeytree** [Heroic-Games-Launcher/HeroicGamesLauncher#1197]
### Describe the bug

Some kind of bug for game sames in GOG. 
I noticed in game it will save but then if you quit & relaunch the game the save/load menu is blank again.

This is using Proton Experiemental on steamdeck.

I haven't yet worked out where to copy my windows game data too (I'm guessing it's one of the compat data folders but which one... (would be much better if they used a naming system) but will also try that and see if that populates the save/load menu.

### Add logs

Launch Command: DXVK_HUD=fps STEAM_COMPAT_CLIENT_INSTALL_PATH=/home/deck/.var/app/com.heroicgameslauncher.hgl/.steam/steam STEAM_COMPAT_DATA_PATH='/home/deck/Games/Heroic/Cyberpunk2077' "/[app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl](http://app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl)" launch "/run/media/mmcblk0p1/Heroic Launcher/Cyberpunk 2077" 1423049311 --no-wine --wrapper "'/home/deck/.steam/steam/steamapps/common/Proton - Experimental/proton' run" --os windows
        System Info:
        
  Heroic Version: 2.2.6 Oden
  Legendary Version:  0.20.25 Our Benefactors
  OS: [Freedesktop.org](http://freedesktop.org/) KERNEL: 5.13.0-valve10.1-1-neptune-02144-g7fffaf925dfb ARCH: x64
  CPU: AMD Custom APU 0405 @2.79 GOVERNOR: schedutil
  RAM: Total: 15.6 GB Available: 8.98 GB
  GRAPHICS: GPU0: Device 163f VRAM: 512MB DRIVER:  
  PROTOCOL: x11
  
        Game Settings: {
"autoInstallDxvk": false,
"autoInstallVkd3d": false,
"maxSharpness": 2,
"nvidiaPrime": false,
"otherOptions": "",
"savesPath": "",
"showFps": true,
"targetExe": "",
"useGameMode": false,
"wineCrossoverBottle": "Heroic",
"winePrefix": "/home/deck/Games/Heroic/Cyberpunk2077",
"wineVersion": {
"bin": "'/home/deck/.steam/steam/steamapps/common/Proton - Experimental/proton'",
"name": "Proton - Proton - Experimental",
"type": "proton"
},
"useSteamRuntime": false
}

        Game Log:
        Proton: Upgrading prefix from GE-Proton7-14 to 7.0-100 (/home/deck/Games/Heroic/Cyberpunk2077/)
Proton: Prefix has an invalid version?! You may want to back up user files and delete this prefix.
fsync: up and running.
wine: RLIMIT_NICE is <= 20, unable to use setpriority safely
WARNING: radv is not a conformant Vulkan implementation, testing use only.
WARNING: radv is not a conformant Vulkan implementation, testing use only.
wine: configuration in L"/home/deck/Games/Heroic/Cyberpunk2077/pfx" has been updated.
WARNING: radv is not a conformant Vulkan implementation, testing use only.
WARNING: radv is not a conformant Vulkan implementation, testing use only.
WARNING: radv is not a conformant Vulkan implementation, testing use only.
WARNING: radv is not a conformant Vulkan implementation, testing use only.
WARNING: radv is not a conformant Vulkan implementation, testing use only.
WARNING: radv is not a conformant Vulkan implementation, testing use only.
WARNING: radv is not a conformant Vulkan implementation, testing use only.
WARNING: radv is not a conformant Vulkan implementation, testing use only.
WARNING: radv is not a conformant Vulkan implementation, testing use only.
WARNING: radv is not a conformant Vulkan implementation, testing use only.
WARNING: radv is not a conformant Vulkan implementation, testing use only.
Unable to read VR Path Registry from C:\users\steamuser\AppData\Local\openvr\openvrpaths.vrpath
Unable to read VR Path Registry from C:\users\steamuser\AppData\Local\openvr\openvrpaths.vrpath
Unable to read VR Path Registry from C:\users\steamuser\AppData\Local\openvr\openvrpaths.vrpath
Unable to read VR Path Registry from C:\users\steamuser\AppData\Local\openvr\openvrpaths.vrpath
Unable to read VR Path Registry from C:\users\steamuser\AppData\Local\openvr\openvrpaths.vrpath
Unable to read VR Path Registry from C:\users\steamuser\AppData\Local\openvr\openvrpaths.vrpath
Unable to read VR Path Registry from C:\users\steamuser\AppData\Local\openvr\openvrpaths.vrpath
Unable to read VR Path Registry from C:\users\steamuser\AppData\Local\openvr\openvrpaths.vrpath
Unable to read VR Path Registry from C:\users\steamuser\AppData\Local\openvr\openvrpaths.vrpath

### Steps to reproduce

Load cyberpunk2077 via heroic launcher with experimental proton. 
Save game. 
Quite gane.
reload game.
try and load a save.
see blank menu.

### Expected behavior

expected save to be there.

### System Information

steamdeck
heroic laucher v 2.2.6

**Comment by imLinguin** [comment]
> Proton: Prefix has an invalid version?! You may want to back up user files and delete this prefix.

This should tell us enough, that prefix is not properly initialized. Please make sure heroic has read and write permissions to that directory and as the log says, backup your saves and delete that prefix.

**Comment by flavioislima** [comment]
This is normal when you change from a GE to the normal proton version.
There is nothing we can do for now.

What you need to do is to backup your saves and start a new prefix with the proton version you want to use.
