### ISSUE TITLE
Unable to run x64 games on Linux

### ISSUE THREAD

**Issue by Bloxxel64** [Heroic-Games-Launcher/HeroicGamesLauncher#1205]
### Describe the bug

Whenever I install a game that requires x64 Windows architecture, Heroic still installs it in an x32 Wineprefix.

### Add logs

Here is the log from trying to run The Escapists from Epic

Launch Command: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary launch Peony --wine '/usr/bin/wine' --wine-prefix '/home/bloxxel64/Games/Heroic/Prefixes/The-Escapists'
        System Info:
        
  Heroic Version: 2.2.6 Oden
  Legendary Version:  0.20.25 Our Benefactors
  OS: Ubuntu KERNEL: 5.13.0-39-generic ARCH: x64
  CPU: Intel Xeon® W3520 @2.67 GOVERNOR: ondemand
  RAM: Total: 16.8 GB Available: 8.69 GB
  GRAPHICS: GPU0: G96C [GeForce 9500 GT]  VRAM: 32MB DRIVER:  
  PROTOCOL: x11
  
        Game Settings: {
	"checkUpdatesInterval": 10,
	"enableUpdates": false,
	"addDesktopShortcuts": true,
	"addStartMenuShortcuts": true,
	"autoInstallDxvk": false,
	"autoInstallVkd3d": false,
	"checkForUpdatesOnStartup": true,
	"customWinePaths": [],
	"defaultInstallPath": "/home/bloxxel64/Games/Heroic",
	"defaultWinePrefix": "/home/bloxxel64/Games/Heroic/Prefixes",
	"language": "en",
	"maxWorkers": 0,
	"minimizeOnLaunch": false,
	"nvidiaPrime": false,
	"otherOptions": "",
	"showUnrealMarket": false,
	"showFps": false,
	"useGameMode": false,
	"userInfo": {
		"epicId": "039b5821ebcc4ab8beb56d932c79e771",
		"name": "bloxxel64"
	},
	"wineCrossoverBottle": "Heroic",
	"winePrefix": "/home/bloxxel64/Games/Heroic/Prefixes/The-Escapists",
	"wineVersion": {
		"bin": "'/usr/bin/wine'",
		"name": "Wine Default - wine-5.0 (Ubuntu 5.0-3ubuntu1)",
		"type": "wine",
		"wineserver": "'/usr/bin/wineserver'",
		"wineboot": "'/usr/bin/wineboot'"
	},
	"altLegendaryBin": "",
	"altGogdlBin": "",
	"darkTrayIcon": true,
	"discordRPC": true,
	"egsLinkedPath": "",
	"maxRecentGames": 5,
	"maxSharpness": 2,
	"savesPath": "",
	"targetExe": "",
	"useSteamRuntime": false
}

        Game Log:
        [cli] INFO: Logging in...
[Core] INFO: Trying to re-use existing login session...
[cli] INFO: Checking for updates...
[Core] INFO: Getting authentication token...
[cli] INFO: Launching Peony...
0012:err:ole:marshal_object couldn't get IPSFactory buffer for interface {00000131-0000-0000-c000-000000000046}
0012:err:ole:marshal_object couldn't get IPSFactory buffer for interface {6d5140c1-7436-11ce-8034-00aa006009fa}
0012:err:ole:StdMarshalImpl_MarshalInterface Failed to create ifstub, hres=0x80004002
0012:err:ole:CoMarshalInterface Failed to marshal the interface {6d5140c1-7436-11ce-8034-00aa006009fa}, 80004002
0012:err:ole:get_local_server_stream Failed: 80004002
0014:err:ole:marshal_object couldn't get IPSFactory buffer for interface {00000131-0000-0000-c000-000000000046}
0014:err:ole:marshal_object couldn't get IPSFactory buffer for interface {6d5140c1-7436-11ce-8034-00aa006009fa}
0014:err:ole:StdMarshalImpl_MarshalInterface Failed to create ifstub, hres=0x80004002
0014:err:ole:CoMarshalInterface Failed to marshal the interface {6d5140c1-7436-11ce-8034-00aa006009fa}, 80004002
0014:err:ole:get_local_server_stream Failed: 80004002
Could not find Wine Gecko. HTML rendering will be disabled.
wine: configuration in L"/home/bloxxel64/Games/Heroic/Prefixes/The-Escapists" has been updated.
0009:err:module:__wine_process_init L"Z:\\home\\bloxxel64\\Games\\Heroic\\TheEscapists\\TheEscapists.exe" 64-bit application not supported in 32-bit prefix

        

### Steps to reproduce

1. Install a modern game from Epic via Heroic on a Debian Based distro like Ubuntu.
2. run the game.
3. see logs.

### Expected behavior

Heroic makes an x64 wineprefix to run the game.

### System Information

  Heroic Version: 2.2.6 Oden
  Legendary Version:  0.20.25 Our Benefactors
  OS: Ubuntu KERNEL: 5.13.0-39-generic ARCH: x64
  CPU: Intel Xeon® W3520 @2.67 GOVERNOR: ondemand
  RAM: Total: 16.8 GB Available: 8.69 GB
  GRAPHICS: GPU0: G96C [GeForce 9500 GT]  VRAM: 32MB DRIVER:  
  PROTOCOL: x11

**Comment by arielj** [comment]
I tried opening The Escapist and I can't reproduce this problem (to the game crashed when it gets to the menu). Is this a problem with Heroic or a problem with wine? have you tried changing which wine you use to run the game? you can try with wine-ge, proton, wine-ge-proton, lutris, you can install them from Heroic's UI using the wine manager.

**Comment by flavioislima** [comment]
This is a wine issue, not an Heroic one.
