### ISSUE TITLE
Account switcher

### ISSUE THREAD

**Issue by dragonDScript** [Heroic-Games-Launcher/HeroicGamesLauncher#1213]
### Problem description

This is a feature EGL expects to have soon. It's always frustrating when you have 2 accounts and have to manually switch.

### Feature description

It should be simple. Store their SID and change them depending on user input

**Comment by flavioislima** [comment]
A thousand times, NO!
😜

**Comment by dragonDScript** [comment]
Why not? Lmao

**Comment by flavioislima** [comment]
This has legal issues. Has ethical problems. 
If we do that we are risking the project. Also, will be a pain feature to maintain.

**Comment by dragonDScript** [comment]
> This has legal issues. Has ethical problems. If we do that we are risking the project. Also, will be a pain feature to maintain.

I understand. What legal issues?
