### ISSUE TITLE
ROCKET LEAGUE crashing 5-6 secs after startup 

### ISSUE THREAD

**Issue by tiklup11** [Heroic-Games-Launcher/HeroicGamesLauncher#1215]
### Describe the bug

Rocket League is crashing on startup. I have seen many people complaining same on youtube video tutorials with title `playing rocket league via heroic `. I have tried on MINT-OS. 
```
Current OS : Endevour OS
```

### Add logs

Launch Command: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary launch Sugar --wine '/usr/bin/wine' --wine-prefix '/home/tiklup/Games/Heroic/Prefixes/Rocket-League®'
        System Info:
        
  Heroic Version: 2.2.6 Oden
  Legendary Version:  0.20.25 Our Benefactors
  OS: EndeavourOS KERNEL: 5.17.3-arch1-1 ARCH: x64
  CPU: Intel Core™ i5-9300H @2.4 GOVERNOR: powersave
  RAM: Total: 8.18 GB Available: 2.83 GB
  GRAPHICS: GPU0: CoffeeLake-H GT2 [UHD Graphics 630]  VRAM: 256MB DRIVER:  GPU1: NVIDIA GeForce GTX 1650 VRAM: 4096MB DRIVER: 510.60.02 
  PROTOCOL: x11
  
        Game Settings: {
	"autoInstallDxvk": false,
	"autoInstallVkd3d": false,
	"maxSharpness": 2,
	"nvidiaPrime": false,
	"otherOptions": "",
	"savesPath": "",
	"showFps": false,
	"targetExe": "",
	"useGameMode": false,
	"wineCrossoverBottle": "Heroic",
	"winePrefix": "/home/tiklup/Games/Heroic/Prefixes/Rocket-League®",
	"wineVersion": {
		"bin": "'/usr/bin/wine'",
		"name": "Wine Default - wine-7.6",
		"type": "wine",
		"wineserver": "'/usr/bin/wineserver'",
		"wineboot": "'/usr/bin/wineboot'"
	},
	"useSteamRuntime": false
}

        Game Log:
        [cli] INFO: Logging in...
[Core] INFO: Trying to re-use existing login session...
[cli] INFO: Checking for updates...
[Core] INFO: Getting authentication token...
[cli] INFO: Launching Sugar...
00f8:fixme:toolhelp:CreateToolhelp32Snapshot Unimplemented: heap list snapshot
00f8:fixme:toolhelp:Heap32ListFirst : stub
00f8:fixme:ntdll:NtQuerySystemInformation info_class SYSTEM_PERFORMANCE_INFORMATION
00f8:err:winediag:ntlm_check_version ntlm_auth was not found or is outdated. Make sure that ntlm_auth >= 3.0.25 is in your path. Usually, you can find it in the winbind package of your distribution.
00f8:err:ntlm:ntlm_LsaApInitializePackage no NTLM support, expect problems
00f8:fixme:heap:RtlSetHeapInformation 0000000000B90000 0 00000000004EEBD0 4 stub
00f8:fixme:dxgi:DXGID3D10CreateDevice Ignoring flags 0x1.
0084:fixme:imm:ImeSetActiveContext (0x273bf0, 0): stub
0084:fixme:imm:ImmReleaseContext (0000000000010020, 0000000000273BF0): stub
00f8:fixme:imm:ImeSetActiveContext (0x572fe0, 1): stub
00f8:fixme:imm:ImmReleaseContext (0000000000020052, 0000000000572FE0): stub

        

### Steps to reproduce

Just launch Rocket league.

### Expected behavior

Game crashing just after startup. 

### Screenshots

![Screenshot from 2022-04-17 20-17-05](https://user-images.githubusercontent.com/57872422/163719714-080d3765-c696-408c-80fb-3e1aae4422ca.png)

Game crashes just after this screen,

### System Information

- OS ["Endevour OS  (also tested on MintOS)"]: 
- Heroic Version [e. g. 2.2.6]:

**Comment by flavioislima** [comment]
This is not an heroic issue.
Open a discussion or go to discord to get help with games.
