### ISSUE TITLE
GOG's `Linux` filter applies to Epic's library

### ISSUE THREAD

**Issue by arielj** [Heroic-Games-Launcher/HeroicGamesLauncher#1219]
### Describe the bug

When filtering games in the GOG library by `Linux` (at the top left), switching to the Epic library shows no games because the filter is applied.

### Add logs

Not relevant

### Steps to reproduce

1. Open the GOG library
2. Click on the linux icon at the top right to filter native linux games
3. Switch to the Epic library
4. It shows no games
5. Go back to the GOG library
6. Select either All or Windows games
7. Go back to the Epic library, all epic games are shown

### Expected behavior

The All/Windows/Linux filter from the GOG library should only apply to the GOG library, it should be ignored when viewing the Epic library (or maybe should be handled separatedly since the Epic store can filter by All/Windows/Mac on a Mac computer).

### System Information

- OS [e. g. "Ubuntu"]: Linux MInt
- Heroic Version [e. g. 2.1.1]: Main branch (currently 2.3.0-beta.1 Caesar Clown)

**Comment by redromnon** [comment]
Yes, I can reproduce this issue.

**Comment by flavioislima** [comment]
Same.
I just sent a fix for it.
