### ISSUE TITLE
[Feature request] Do not use symbols in prefixes

### ISSUE THREAD

**Issue by A-w-x** [Heroic-Games-Launcher/HeroicGamesLauncher#1220]
### Problem description

Help [HeroicBashLauncher](https://github.com/redromnon/HeroicBashLauncher) to create valid launch scripts.

see
https://github.com/redromnon/HeroicBashLauncher/issues/30
https://github.com/redromnon/HeroicBashLauncher/issues/45

### Feature description

Remove, or just do not add, symbols on prefix creation.

**Comment by redromnon** [comment]
This is a Heroic issue and not Bash Launcher's issue. Bash Launcher only handles the launching of games, nothing else.

Plus, I cannot make Bash Launcher edit the user's game folder paths (created by Heroic) which can lead to issues. 
Heroic's upcoming version will be handling this issue as there was a feature request submitted.

**Comment by redromnon** [comment]
The issue has already been fixed in #1183 and the fix will be implemented in the upcoming Heroic's release.

**Comment by A-w-x** [comment]
> The issue has already been fixed in #1183 and the fix will be implemented in the upcoming Heroic's release.

ah, perfect :)
