### ISSUE TITLE
Missing games in library

### ISSUE THREAD

**Issue by CreakinCrank** [Heroic-Games-Launcher/HeroicGamesLauncher#1224]
### Describe the bug

List of games for EGS not updating. The last few free games I have claimed are not showing e.g Demons Tilt, In Sound Mind, Insurmountable & Xcom 2. I have tried refreshing the list, logging out of EGS & logging back in, but still not showing. When I open the store from inside Heroic, the games are listed as "in library".

### Add logs

(13:43:52) INFO:    [Legendary]:       Location: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary
(13:43:52) INFO:    [Gog]:             Location: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl
(13:43:53) INFO:    [Backend]:         
  Heroic Version: 2.2.6 Oden
  Legendary Version:  0.20.6 A Red Letter Day
  OS: ManjaroLinux KERNEL: 5.17.1-3-MANJARO ARCH: x64
  CPU: AMD Ryzen 5 1600X Six-Core Processor @3.6 GOVERNOR: schedutil
  RAM: Total: 16.8 GB Available: 11.3 GB
  GRAPHICS: GPU0: NVIDIA GeForce GTX 1070 Ti VRAM: 8192MB DRIVER: 510.60.02 
  PROTOCOL: x11
  
(13:43:53) INFO:    [Gog]:             Getting data about the user
(13:43:53) WARNING: [Backend]:         Protocol already registered.
(13:43:53) INFO:    [Gog]:             Saved user data to config
(13:43:54) INFO:    [Frontend]:        Refreshing Library
(13:43:54) INFO:    [Gog]:             Getting GOG library
(13:43:55) INFO:    [Gog]:             Number of library pages: 2
(13:43:55) INFO:    [Gog]:             Getting data for page 2
(13:43:55) INFO:    [Gog]:             Saved games data
(13:43:55) INFO:    [Legendary]:       Refreshing library...
(13:43:55) INFO:    [Legendary]:       Refreshing Epic Games...
(13:43:55) INFO:    [Legendary]:       Refreshing Epic Games...
(13:43:56) INFO:    [Legendary]:       usage: legendary [-h] [-v] [-y] [-V]
                 {auth,install,download,update,repair,uninstall,launch,list-games,list-installed,list-files,list-saves,download-saves,sync-saves,verify-game,import-game,egl-sync,status,cleanup}
                 ...
legendary: error: argument subparser_name: invalid choice: 'list' (choose from 'auth', 'install', 'download', 'update', 'repair', 'uninstall', 'launch', 'list-games', 'list-installed', 'list-files', 'list-saves', 'download-saves', 'sync-saves', 'verify-game', 'import-game', 'egl-sync', 'status', 'cleanup')
(13:43:56) INFO:    [Legendary]:       Updating game list
(13:43:56) INFO:    [Legendary]:       Game List Updated
(13:43:57) INFO:    [Legendary]:       Checking for game updates
(13:43:57) INFO:    [Legendary]:       Found 2 game(s) to update
(13:43:58) INFO:    [Gog]:             Found 0 game(s) to update
(13:43:59) INFO:    [Backend]:         checking for heroic updates

### Steps to reproduce

1. Go to 'library-Epic Games'
2. Click on 'search'
3. Type 'xcom 2'
4. See 'no games found'

### Expected behavior

Games would be listed.

### System Information

- OS [e. g. "Ubuntu"]: Manjaro testing
- Heroic Version [e. g. 2.1.1]: 2.2.6-1

**Comment by flavioislima** [comment]
You have an old legendary version installed on your system and Heroic is using it.
Upgrade it or remove it and try again:

`Legendary Version: 0.20.6 A Red Letter Day`

**Comment by CreakinCrank** [comment]
Sorry, sorted now. Idiot me didn't actually read the log until I posted.
