### ISSUE TITLE
Final Fantasy VII suddenly giving me an error

### ISSUE THREAD

**Issue by niklasalkin** [Heroic-Games-Launcher/HeroicGamesLauncher#1225]
### Describe the bug

I try to run the game through Steam, added with heroic bash launcher, and yesterday it started giving me a failed to run message and advising me to check to log file, which I have pasted here.

### Add logs

Launch Command: STEAM_COMPAT_CLIENT_INSTALL_PATH=/home/deck/.var/app/com.heroicgameslauncher.hgl/.steam/steam STEAM_COMPAT_DATA_PATH='/home/deck/Games/Heroic/Prefixes/FINAL-FANTASY-VII-REMAKE-INTERGRADE' /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary launch b25ba0f04dc9434f8a04a062719e7aa7 --no-wine --wrapper "'/home/deck/.steam/steam/steamapps/common/Proton 7.0/proton' run"
        System Info:
        
  Heroic Version: 2.2.6 Oden
  Legendary Version:  0.20.25 Our Benefactors
  OS: Freedesktop.org KERNEL: 5.13.0-valve10.1-1-neptune-02144-g7fffaf925dfb ARCH: x64
  CPU: AMD Custom APU 0405 @1.92 GOVERNOR: schedutil
  RAM: Total: 15.6 GB Available: 13.3 GB
  GRAPHICS: GPU0: Device 163f VRAM: 512MB DRIVER:  
  PROTOCOL: x11
  
        Game Settings: {
	"checkUpdatesInterval": 10,
	"enableUpdates": false,
	"addDesktopShortcuts": false,
	"addStartMenuShortcuts": false,
	"autoInstallDxvk": false,
	"autoInstallVkd3d": false,
	"checkForUpdatesOnStartup": true,
	"customWinePaths": [],
	"defaultInstallPath": "/run/media/mmcblk0p1",
	"defaultWinePrefix": "/home/deck/Games/Heroic/Prefixes",
	"language": "sv",
	"maxWorkers": 0,
	"minimizeOnLaunch": true,
	"nvidiaPrime": false,
	"otherOptions": "",
	"showUnrealMarket": false,
	"showFps": false,
	"useGameMode": false,
	"userInfo": {
		"epicId": "",
		"name": "deck"
	},
	"wineCrossoverBottle": "Heroic",
	"winePrefix": "/home/deck/Games/Heroic/Prefixes/FINAL-FANTASY-VII-REMAKE-INTERGRADE",
	"wineVersion": {
		"bin": "'/home/deck/.steam/steam/steamapps/common/Proton 7.0/proton'",
		"name": "Proton - Proton 7.0",
		"type": "proton"
	},
	"altLegendaryBin": "",
	"altGogdlBin": "",
	"darkTrayIcon": false,
	"egsLinkedPath": "",
	"maxRecentGames": 10,
	"autoSyncSaves": true,
	"maxSharpness": 2,
	"savesPath": "/home/deck/Games/Heroic/Prefixes/FINAL-FANTASY-VII-REMAKE-INTERGRADE/pfx/drive_c/users/steamuser/My Documents/My Games/FINAL FANTASY VII REMAKE/EOS/8ddd64f2fb0d4a6da5065a755afce796/",
	"targetExe": "",
	"useSteamRuntime": false
}

        Game Log:
        [cli] INFO: Logging in...
Traceback (most recent call last):
  File "legendary/cli.py", line 3004, in <module>
  File "legendary/cli.py", line 2919, in main
  File "legendary/cli.py", line 582, in launch_game
  File "legendary/core.py", line 188, in login
ValueError: No saved credentials
[197] Failed to execute script 'cli' due to unhandled exception!

        

### Steps to reproduce

Run the game when added to Steam with heroic bash launcher. Or straight from desktop.

### Expected behavior

I expect the game to run

### System Information

Standard Steam Deck, latest update as of this writing

**Comment by redromnon** [comment]
You need to login again. Just click on your username on the bottom left of the Heroic window -> Manage Accounts -> Log in for Epic Games.

**Comment by niklasalkin** [comment]
> You need to login again. Just click on your username on the bottom left of the Heroic window -> Manage Accounts -> Log in for Epic Games.

Oh ffs.. thanks! Didn’t even have to enter my credentials, just click login. In my defence I hadn’t logged out.

**Comment by redromnon** [comment]
Cool! Can I request you to close this issue?
