### ISSUE TITLE
[Feature Request] Prevent ~/.wine to be assigned as a game's prefix

### ISSUE THREAD

**Issue by redromnon** [Heroic-Games-Launcher/HeroicGamesLauncher#1226]
### Problem description

The following issue #1209 best describes the problem. 

Basically, users might set the game's wine prefix as `~/.wine` which is not recommended at all. The real issue arises when they try to uninstall the game - they check the _delete wine prefix_ option unknowingly and the default wine prefix folder gets deleted.   

### Feature description

Prevent users from using the default `~/.wine` as the game's prefix. Maybe like an alert dialog box?

### Alternatives

None

### Additional information

None

**Comment by flavioislima** [comment]
I don't think we need that. Is too much, people could just read and they will realise that is not a good idea. Heroic already tries everything for the user so not mess up. I don't think we should add one more check for that.
