### ISSUE TITLE
Not showing download progress

### ISSUE THREAD

**Issue by rordi99** [Heroic-Games-Launcher/HeroicGamesLauncher#1230]
### Describe the bug

i installed heroic on my mac m1 its not showing download progress of games but its creating files of games and downloading it 

### Add logs

no logs

### Steps to reproduce

2. Click on '...'
3. Scroll down to '...'

### Expected behavior

it should show the download progress....

### Screenshots

[
![Uploading ss gta 5 bug.png…]()
](url)

### System Information

- macOS Monterey
- version 12.3.1  
- Heroic Version 2.2.6

**Comment by imLinguin** [comment]
Fix is already done, it'll be part of next release

**Comment by wiryfuture** [comment]
fixed
