### ISSUE TITLE
Install button shouldn't work if install path is empty

### ISSUE THREAD

**Issue by arielj** [Heroic-Games-Launcher/HeroicGamesLauncher#1234]
### Describe the bug

When trying to install a game, if the install path is empty, clicking the `Install` button closes the dialog with no information and nothing happens, and there's no indication of an error anywhere.

### Add logs

not relevant

### Steps to reproduce

1. Open the install dialog for a game
2. Make sure the `Select Install Path` field is empty
3. Click the `Install` button
4. Dialog closes, installation never starts, no errors are displayed anywhere (the code simply returns)

### Expected behavior

Clicking the Install button shouldn't close the dialog and it should be clear what's the reason it's not installing.

I can imagine 2 options:
- disable the `Install` button if the input is empty (though we still need to show some indication that it can't be empty)
- leave the button enabled but show a message to the user if the input is empty

### System Information

- OS [e. g. "Ubuntu"]: Linux Mint
- Heroic Version [e. g. 2.1.1]: 2.3.0-beta.1

**Comment by wiryfuture** [comment]
I see what you mean, I'm taking a look.

**Comment by wiryfuture** [comment]
Made a patch on #1239

**Comment by flavioislima** [comment]
fixed.
