### ISSUE TITLE
[Linux] Missing list of games when moving from GOG to Epic with a linux filter

### ISSUE THREAD

**Issue by pktiuk** [Heroic-Games-Launcher/HeroicGamesLauncher#1243]
### Describe the bug

There is only list of recently played games

### Add logs

(16:46:33) INFO:    [Legendary]:       Location: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary
(16:46:33) INFO:    [Gog]:             Location: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl
(16:46:34) INFO:    [Backend]:         
  Heroic Version: 2.2.6 Oden
  Legendary Version:  0.20.22 Anticitizen One (hotfix #3)
  OS: Pop KERNEL: 5.16.19-76051619-generic ARCH: x64
  CPU: Intel Core™ i5-7300HQ @2.5 GOVERNOR: powersave
  RAM: Total: 16.7 GB Available: 11.6 GB
  GRAPHICS: GPU0: HD Graphics 630  VRAM: 256MB DRIVER:  GPU1: NVIDIA GeForce GTX 1050 VRAM: 4096MB DRIVER: 510.54 
  PROTOCOL: x11
  
(16:46:34) WARNING: [Backend]:         Protocol already registered.
(16:46:35) INFO:    [Frontend]:        Refreshing Library
(16:46:35) INFO:    [Legendary]:       Refreshing library...
(16:46:35) INFO:    [Legendary]:       Refreshing Epic Games...
(16:46:35) INFO:    [Legendary]:       Refreshing Epic Games...
(16:46:38) INFO:    [Legendary]:       usage: legendary [-h] [-v] [-y] [-V] [-c <path/name>] [-J]
                 {auth,install,download,update,repair,uninstall,launch,list-games,list-installed,list-files,list-saves,download-saves,clean-saves,sync-saves,verify-game,import-game,egl-sync,status,info,alias,cleanup,activate,get-token}
                 ...
legendary: error: argument subparser_name: invalid choice: 'list' (choose from 'auth', 'install', 'download', 'update', 'repair', 'uninstall', 'launch', 'list-games', 'list-installed', 'list-files', 'list-saves', 'download-saves', 'clean-saves', 'sync-saves', 'verify-game', 'import-game', 'egl-sync', 'status', 'info', 'alias', 'cleanup', 'activate', 'get-token')
(16:46:38) INFO:    [Legendary]:       Updating game list
(16:46:38) INFO:    [Legendary]:       Game List Updated
(16:46:39) INFO:    [Backend]:         checking for heroic updates
(16:46:43) INFO:    [Legendary]:       Checking for game updates
(16:46:43) INFO:    [Legendary]:       Found 1 game(s) to update
(16:46:43) INFO:    [Gog]:             Found 0 game(s) to update

### Steps to reproduce

1. Open Heroic

### Expected behavior

See full list of my games

### Screenshots

![obraz](https://user-images.githubusercontent.com/45544416/165328051-3075b1ca-16d4-4a6f-aa29-05c867573daf.png)

### System Information

- OS: Pop!_OS 20.04
- Heroic Version: `2.2.6` and  `2.3.0 Beta 1 `

### Additional information

It broke after update

**Comment by flavioislima** [comment]
Check your logs.
You have an old version of legendary installed on your system so heroic is having a conflict.
Update it or remove and restart heroic.

Also, are you sure this is happening on the beta as well? Same logs?

**Comment by pktiuk** [comment]
```
(17:56:16) DEBUG:   [Legendary]:       Running Legendary command: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary --version
(17:56:17) INFO:    [Legendary]:       Legendary location: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary
(17:56:17) INFO:    [Gog]:             GOGDL location: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl
(17:56:17) INFO:    [Backend]:         
  Heroic Version: 2.3.0-beta.1 Caesar Clown
  Legendary Version:  0.20.25 Our Benefactors
  OS: Pop KERNEL: 5.16.19-76051619-generic ARCH: x64
  CPU: Intel Core™ i5-7300HQ @2.5 GOVERNOR: powersave
  RAM: Total: 16.7 GB Available: 10.6 GB
  GRAPHICS: GPU0: HD Graphics 630  VRAM: 256MB DRIVER:  GPU1: NVIDIA GeForce GTX 1050 VRAM: 4096MB DRIVER: 510.54 
  PROTOCOL: x11
  
(17:56:17) WARNING: [Backend]:         Protocol already registered.
(17:56:18) INFO:    [Frontend]:        Refreshing Library
(17:56:18) INFO:    [Legendary]:       Refreshing library...
(17:56:18) INFO:    [Legendary]:       Refreshing Epic Games...
(17:56:18) INFO:    [Legendary]:       Refreshing Epic Games...
(17:56:20) DEBUG:   [Legendary]:       Running Legendary command: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary list
(17:56:28) INFO:    [Legendary]:       Updating game list
(17:56:28) INFO:    [Legendary]:       Game List Updated
(17:56:29) INFO:    [Legendary]:       Checking for game updates: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary list-installed --check-updates --tsv
(17:56:29) DEBUG:   [Legendary]:       Running Legendary command: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary list-installed --check-updates --tsv
(17:56:34) INFO:    [Legendary]:       Found 1 game(s) to update
(17:56:34) INFO:    [Gog]:             Found 0 game(s) to update
(17:56:34) INFO:    [Frontend]:        Force Update
(17:56:37) INFO:    [Backend]:         Downloaded Winetricks
```
Different logs same issue

**Comment by flavioislima** [comment]
Ok.
We have a bug that I think wasn't fixed yet.
I don't know if that's the case.
But if you go to GOG then select the the filter to show only Linux games Then go back to Epic. The library will be blank.
Then just go to Gog and select ALL then go to epic.

**Comment by pktiuk** [comment]
Clicking `continue` fixed this issue

![obraz](https://user-images.githubusercontent.com/45544416/165362227-2db81ec1-4569-4956-9e16-9083ad57b6ff.png)

**Comment by flavioislima** [comment]
Good. That's another issue we need to fix.
