### ISSUE TITLE
Wine selection is incorrect

### ISSUE THREAD

**Issue by RickAndTired** [Heroic-Games-Launcher/HeroicGamesLauncher#1250]
### Describe the bug

Game's Wine selection in the UI shows Wine-GE-Proton7-9, but the logs show the launch command is trying to use Wine-GE-Proton7-6

### Add logs

[S&S 499f085e442048aa854d6250b21c42fb-lastPlay.log](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/files/8585016/S.S.499f085e442048aa854d6250b21c42fb-lastPlay.log)

### Steps to reproduce

1. Wine-GE-Proton7-6 installed
2. Installed Wine-GE-Proton7-9
3. Removed Wine-GE-Proton7-6
4. Game settings UI showed it was using Wine-GE-Proton7-9
5. Started game - "Error when launching the game, check the logs!"
6. Logs show the command was still trying to use Wine-GE-Proton7-6

Workaround:
1. Install another version of Wine
2. Select that version of Wine in a game's settings
3. Select Wine-GE-Proton7-9

### Expected behavior

Wine-GE-Proton7-9 shows in the UI and should also be used in the launch command

### System Information

- OS [e. g. "Ubuntu"]: Ubuntu 21.10
- Heroic Version [e. g. 2.1.1]: 2.2.6 Flatpak

**Comment by arielj** [comment]
hey @RickAndTired, can you check if this is still an issue with Heroic 2.3.1?

**Comment by RickAndTired** [comment]
> hey @RickAndTired, can you check if this is still an issue with Heroic 2.3.1?

Yeah it's still happening in 2.3.1

**Comment by CommandMC** [comment]
Since the settings are only saved when *you* edit them, removing an old wine version and installing a new one doesn't update them. So also updating the settings if Wine versions are added/removed via the Wine Manager should fix this

**Comment by flavioislima** [comment]
I believe this was fixed some time ago. 
I cannot reproduce it anymore.
