### ISSUE TITLE
RHEL/EPEL support

### ISSUE THREAD

**Issue by norbertcserpnyak16** [Heroic-Games-Launcher/HeroicGamesLauncher#1257]
I think it is a good idea to integrate RHEL / EPEL into COPR. There must be someone who wants to play on Enterprise Linux. Don't be deprived of the opportunity.

**Comment by flavioislima** [comment]
Sorry, personally we cannot do nothing. You need to talk with the repository maintainers.
All repos that we are today with the exception of Flathub, the initiative came from the maintainers.
