### ISSUE TITLE
Local save data lost

### ISSUE THREAD

**Issue by jimjim527** [Heroic-Games-Launcher/HeroicGamesLauncher#1266]
After selecting the Reset Heroic option in global settings, all saves seem to be gone. Any fix for this? Am I SOL?

**Comment by flavioislima** [comment]
No way this has happened unless you were using the heroic folder as your prefix folder.
On reset heroic deletes the $HOME/.config/heroic folder except for the GOG stores that has your GOG installed game information.

You might have lost your settings for the game, maybe the prefix has changed and thats why you are not finding them.

Also, do not erase the template when opening issues.
We dont even know your Operating system or heroic verison here, is hard to help like this.
Go to our discord if you need more help on that.

**Comment by jimjim527** [comment]
Thank you for the quick response! I will check the settings on my Steam Deck when I get home today. Sorry about not using the right template but I do appreciate the insight and am really enjoying using the software.
