### ISSUE TITLE
PS5 Controller not working 

### ISSUE THREAD

**Issue by Apteryx009** [Heroic-Games-Launcher/HeroicGamesLauncher#1268]
### Describe the bug

When I try to play Rocket League, my PS5 controller does not properly work. My kernel is updated, I tried using different wine and proton versions. I have tried using my controller both wired and wireless. It's like all the buttons are mapped incorrectly, the camera is stuck spinning left for some reason. 

### Add logs

ine: Read access denied for device L"\\??\\Z:\\", FS volume label and serial are not available.
wine: Read access denied for device L"\\??\\Z:\\", FS volume label and serial are not available.
wine: Read access denied for device L"\\??\\Z:\\", FS volume label and serial are not available.
0065:err:d3d:resource_unload Resource 0x2e0ef1a0 is being unloaded while mapped.
0065:err:d3d:resource_unload Resource 0xb16e0c0 is being unloaded while mapped.
0065:err:d3d:resource_unload Resource 0xb16e1d0 is being unloaded while mapped.
0066:err:d3d11:d3d11_immediate_context_ClearDepthStencilView Failed to clear view, hr 0x8876086c.
0066:err:d3d11:d3d11_immediate_context_ClearDepthStencilView Failed to clear view, hr 0x8876086c.
0066:err:d3d11:d3d11_immediate_context_ClearDepthStencilView Failed to clear view, hr 0x8876086c.
0066:err:d3d11:d3d11_immediate_context_ClearDepthStencilView Failed to clear view, hr 0x8876086c.
0066:err:d3d11:d3d11_immediate_context_ClearDepthStencilView Failed to clear view, hr 0x8876086c.
0066:err:d3d11:d3d11_immediate_context_ClearDepthStencilView Failed to clear view, hr 0x8876086c.
0066:err:d3d11:d3d11_immediate_context_ClearDepthStencilView Failed to clear view, hr 0x8876086c.
0066:err:d3d11:d3d11_immediate_context_ClearDepthStencilView Failed to clear view, hr 0x8876086c.
0066:err:d3d11:d3d11_immediate_context_ClearDepthStencilView Failed to clear view, hr 0x8876086c.
0066:err:d3d11:d3d11_immediate_context_ClearDepthStencilView Failed to clear view, hr 0x8876086c.
0065:err:d3d:wined3d_debug_callback 0xb16d080: "GL_INVALID_VALUE error generated. The x-dimension of the subregion fails to meet the alignment constraints of the compressed format.".
0065:err:d3d:wined3d_debug_callback 0xb16d080: "GL_INVALID_VALUE error generated. The x-dimension of the subregion fails to meet the alignment constraints of the compressed format.".
0065:err:d3d:resource_unload Resource 0x4e409f70 is being unloaded while mapped.
0065:err:d3d:resource_unload Resource 0x4a4e4430 is being unloaded while mapped.
0065:err:d3d:resource_unload Resource 0x5628aa30 is being unloaded while mapped.
0065:err:d3d:resource_unload Resource 0x5622bec0 is being unloaded while mapped.
0065:err:d3d:resource_unload Resource 0x2f154c10 is being unloaded while mapped.
0065:err:d3d:resource_unload Resource 0x2e8a7bd0 is being unloaded while mapped.
0065:err:d3d:resource_unload Resource 0x2fb60030 is being unloaded while mapped.
0065:err:d3d:resource_unload Resource 0x2fb60030 is being unloaded while mapped.
0065:err:d3d:resource_unload Resource 0x49dba680 is being unloaded while mapped.
0065:err:d3d:resource_unload Resource 0x2e8a7a50 is being unloaded while mapped.
0065:err:d3d:resource_unload Resource 0x4e5009b0 is being unloaded while mapped.
0065:err:d3d:resource_unload Resource 0x4e5009b0 is being unloaded while mapped.
0035:err:ole:CoUninitialize Mismatched CoUninitialize

### Steps to reproduce

2. Click on '...'
3. Scroll down to '...'

### Expected behavior

The controller should work. 

### System Information

Pop OS. 2070 SUPER gpu.

**Comment by arielj** [comment]
Heroic has nothing to do with the controller support on games, we just tell wine to open a game. Maybe you can ask on the heroic discord if somebody can help, but this is not a Heroic issues.
