### ISSUE TITLE
Save-sync - Force Upload/Force Download don't seem to function properly 

### ISSUE THREAD

**Issue by macneilj** [Heroic-Games-Launcher/HeroicGamesLauncher#1272]
### Describe the bug

When using Force Upload, it seems to ignore this option and download cloud saves if they're "newer". Not sure if I'm misunderstanding the function of this button.

When I use legendary CLI to `force-upload`, it seems to work fine. If I then use "Force Download" in heroic on a secondary device, it still just uploads the "newer" files.

![image](https://user-images.githubusercontent.com/16035351/167017371-095f9922-73b4-4b39-af96-0408cb78b49e.png)

### Add logs

(12:49:23) INFO:    [Legendary]:       Location: C:\Users\User\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\legendary.exe
(12:49:23) INFO:    [Gog]:             Location: C:\Users\User\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\gogdl.exe
(12:49:28) INFO:    [Backend]:         
  Heroic Version: 2.2.6 Oden
  Legendary Version:  0.20.25 Our Benefactors
  OS: Microsoft Windows 10 Education KERNEL: 10.0.19044 ARCH: x64
  CPU: Intel Core™ i7-9700K @3.6 
  RAM: Total: 17.1 GB Available: 10.2 GB
  GRAPHICS: GPU0: NVIDIA GeForce RTX 2070 VRAM: 8192MB DRIVER: 512.59 
  
  
(12:49:28) WARNING: [Backend]:         Protocol already registered.
(12:49:29) INFO:    [Frontend]:        Refreshing Library
(12:49:29) INFO:    [Legendary]:       Refreshing library...
(12:49:29) INFO:    [Legendary]:       Refreshing Epic Games...
(12:49:29) INFO:    [Legendary]:       Refreshing Epic Games...
(12:49:30) INFO:    [Legendary]:       [cli] INFO: Logging in...
(12:49:30) INFO:    [Legendary]:       [Core] INFO: Trying to re-use existing login session...
(12:49:30) INFO:    [Legendary]:       [cli] INFO: Getting game list... (this may take a while)
(12:49:31) INFO:    [Legendary]:       Updating game list
(12:49:31) INFO:    [Legendary]:       Game List Updated
(12:49:32) INFO:    [Legendary]:       Checking for game updates
(12:49:32) INFO:    [Legendary]:       Found 0 game(s) to update
(12:49:32) INFO:    [Gog]:             Found 0 game(s) to update
(12:49:34) INFO:    [Backend]:         checking for heroic updates
(12:53:32) INFO:    [Legendary]:       Installed game list updated
(14:26:59) INFO:    [Legendary]:       Installed game list updated
(15:40:11) INFO:    [Legendary]:       Syncing saves for  d36336f190094951873ed6138ac208d8
(15:40:14) INFO:    [Legendary]:       Installed game list updated
(15:40:14) INFO:    [Legendary]:       Installed game list updated
(15:40:14) INFO:    [Legendary]:       Installed game list updated
(15:40:14) INFO:    [Backend]:         
(15:55:10) INFO:    [Legendary]:       Syncing saves for  d36336f190094951873ed6138ac208d8
(15:55:14) INFO:    [Legendary]:       Installed game list updated
(15:55:14) INFO:    [Legendary]:       Installed game list updated
(15:55:14) INFO:    [Backend]:         
(15:56:44) INFO:    [Legendary]:       Syncing saves for  d36336f190094951873ed6138ac208d8
(15:56:45) INFO:    [Legendary]:       Installed game list updated
(15:56:45) INFO:    [Legendary]:       Installed game list updated
(15:56:45) INFO:    [Backend]:         
(15:57:29) INFO:    [Legendary]:       Syncing saves for  d36336f190094951873ed6138ac208d8
(15:57:30) INFO:    [Legendary]:       Installed game list updated
(15:57:30) INFO:    [Legendary]:       Installed game list updated
(15:57:30) INFO:    [Backend]:         
(15:57:40) INFO:    [Legendary]:       Syncing saves for  d36336f190094951873ed6138ac208d8
(15:57:42) INFO:    [Legendary]:       Installed game list updated
(15:57:42) INFO:    [Legendary]:       Installed game list updated
(15:57:42) INFO:    [Backend]:         
(16:02:29) INFO:    [Legendary]:       Syncing saves for  d36336f190094951873ed6138ac208d8
(16:02:31) INFO:    [Legendary]:       Installed game list updated
(16:02:31) INFO:    [Legendary]:       Installed game list updated
(16:02:31) INFO:    [Backend]:         
(16:02:47) INFO:    [Legendary]:       Syncing saves for  d36336f190094951873ed6138ac208d8
(16:02:49) INFO:    [Legendary]:       Installed game list updated
(16:02:49) INFO:    [Legendary]:       Installed game list updated
(16:02:49) INFO:    [Backend]:         
(16:03:06) INFO:    [Legendary]:       Syncing saves for  d36336f190094951873ed6138ac208d8
(16:03:07) INFO:    [Legendary]:       Installed game list updated
(16:03:07) INFO:    [Legendary]:       Installed game list updated
(16:03:07) INFO:    [Backend]:         

### Steps to reproduce

1. Go to game
2. Click on Force Upload -> Sync
3. "Newer" files get downloaded, erasing existing local save.

### Expected behavior

Local file should get forced uploader, even if it's an older file.

### System Information

- Windows
- Heroic Version 2.2.6

**Comment by flavioislima** [comment]
I remember a bug with Force-Upload/download when using Heroic with the language set other than english, because it was translating the values. I dont remember if we fixed that though.
Are you sure you are using it in English just to be sure that it is not the same bug?

**Comment by macneilj** [comment]
![image](https://user-images.githubusercontent.com/16035351/168104237-32754260-548b-4ab0-b704-203973e5624c.png)
I'm indeed using it in english

**Comment by flavioislima** [comment]
Hmm, so might be a different bug. Will have to investigate that.

**Comment by Nocccer** [comment]
Is it fixed in heroic-2.4.0beta2 ? If so can you close the ticket?
