### ISSUE TITLE
Unreal Engine easy install for Linux

### ISSUE THREAD

**Issue by Mistreaper** [Heroic-Games-Launcher/HeroicGamesLauncher#1273]
### Problem description

Recently, I found this:
https://github.com/AchetaGames/Epic-Asset-Manager/

It's a simple way to install UE on Linux and install UE marketplace assets. Currently, I don't think the project is actively developed anymore.

### Feature description

I think the features of EAM could be implemented here, as it's more "actively developed". Do mind though that you need to authenticate with a GitHub personal access token, as you need to access the UE GitHub repo.that 

### Alternatives

Using EAM.

**Comment by wiryfuture** [comment]
While that looks interesting, imo, Unreal Engine is not entirely relevant to Heroic as a games launcher;
We've also hidden the unreal marketplace by default in the launcher and afaik no one has complained about that so I don't think it's that much of a requested feature

Unless @flavioislima has interest in this, this won't be implemented.

**Comment by flavioislima** [comment]
Yes, it's not the main focus. We already deal with assets and so on but the engine will be too much for our small team to maintain and give support.

**Comment by Sylk** [comment]
Fight the battles you can, it's understandable.
