### ISSUE TITLE
Windows portable binary uses description for background process name 🤦🏻 

### ISSUE THREAD

**Issue by wiryfuture** [Heroic-Games-Launcher/HeroicGamesLauncher#1274]
### Describe the bug

When launching Heroic using the portable windows binary, the background process it creates is using the description instead of just Heroic, which results in this equivocative process name in task manager compared to the foreground process 😆 
![image](https://user-images.githubusercontent.com/50517631/167253572-4f578bbd-1c42-496a-a135-aca9dfcfdbd3.png)

### Add logs

.

### Steps to reproduce

1. Launch portable windows binary of Heroic
2. Look in background processes in task manager

### Expected behavior

The process should be called Heroic/Heroic Games Launcher.

### System Information

- Windows 10 21H2
- Heroic Version 2.2.6 Oden

**Comment by flavioislima** [comment]
This is causing some harm or breaking something? If yes, you can reopen this but I believe its not an issue.
