### ISSUE TITLE
List of Games won't be displayed

### ISSUE THREAD

**Issue by grince** [Heroic-Games-Launcher/HeroicGamesLauncher#1276]
### Describe the bug

even logged in in GOG and Epic, no library gets displayed.

I installed Heroic on my Steamdeck via Discover and logged into GOG and Epic Game Store. I expected that from there the list of owned Games would be retrieved and displayed, but the list of games is empty.

### Add logs

(17:48:39) INFO:    [Legendary]:       Location: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary  
(17:48:39) INFO:    [Gog]:             Location: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl     
(17:48:40) INFO:    [Backend]:
  Heroic Version: 2.2.6 Oden
  Legendary Version:  0.20.25 Our Benefactors
  OS: Freedesktop.org KERNEL: 5.13.0-valve10.3-1-neptune-02176-g5fe416c4acd8 ARCH: x64                                 
  CPU: AMD Custom APU 0405 @1.9 GOVERNOR: schedutil
  RAM: Total: 15.6 GB Available: 13.8 GB
  GRAPHICS: GPU0: Device 163f VRAM: 512MB DRIVER:
  PROTOCOL: x11

(17:48:40) INFO:    [Gog]:             Getting data about the user                                                     
(17:48:40) INFO:    [Gog]:             Refreshing access_token                                                         
(17:48:40) ERROR:   [Backend]:         Failed to register protocol with OS.                                            
(17:48:40) INFO:    [Gog]:             Token refreshed successfully                                                    
(17:48:41) INFO:    [Gog]:             Saved user data to config                                                       
(17:48:41) INFO:    [Frontend]:        Refreshing Library
(17:48:41) INFO:    [Gog]:             Getting GOG library
(17:48:41) INFO:    [Gog]:             Number of library pages: 6                                                      
(17:48:41) INFO:    [Gog]:             Getting data for page 2                                                         
(17:48:42) INFO:    [Gog]:             Getting data for page 3                                                         
(17:48:42) INFO:    [Gog]:             Getting data for page 4                                                         
(17:48:43) INFO:    [Gog]:             Getting data for page 5                                                         
(17:48:43) INFO:    [Gog]:             Getting data for page 6                                                         
(17:48:45) WARNING: [Gog]:             Unable to get covers from gamesdb for Cyberpunk 2077 Goodies Collection. Trying to get it from api.gog.com
(17:48:45) WARNING: [Gog]:             Couldn't get info from api.gog.com, Using fallback vertical image               
(17:48:47) ERROR:   [Frontend]:        Error: Error invoking remote method 'refreshLibrary': TypeError: Cannot read properties of undefined (reading 'url_format')
(17:48:47) INFO:    [Frontend]:        No cache found, getting data from legendary...                                  
(17:48:47) INFO:    [Backend]:         checking for heroic updates                                                     
(17:48:47) INFO:    [Backend]:         skipping heroic updates                                                         
(17:48:47) INFO:    [Legendary]:       Refreshing library...
(17:48:47) INFO:    [Legendary]:       Updating game list
(17:48:47) INFO:    [Legendary]:       Game List Updated
(17:48:48) INFO:    [Legendary]:       Checking for game updates                                                       
(17:48:48) INFO:    [Legendary]:       Found 0 game(s) to update                                                       
(17:48:48) INFO:    [Gog]:             Found 0 game(s) to update                                                       
(18:00:25) INFO:    [Frontend]:        Refreshing Library
(18:00:25) INFO:    [Gog]:             Getting GOG library
(18:00:25) INFO:    [Gog]:             Number of library pages: 6                                                      
(18:00:25) INFO:    [Gog]:             Getting data for page 2                                                         
(18:00:27) INFO:    [Gog]:             Getting data for page 3                                                         
(18:00:27) INFO:    [Gog]:             Getting data for page 4                                                         
(18:00:28) INFO:    [Gog]:             Getting data for page 5                                                         
(18:00:28) INFO:    [Gog]:             Getting data for page 6                                                         
(18:00:30) WARNING: [Gog]:             Unable to get covers from gamesdb for Cyberpunk 2077 Goodies Collection. Trying t
o get it from api.gog.com
(18:00:30) WARNING: [Gog]:             Couldn't get info from api.gog.com, Using fallback vertical image               
(18:00:32) ERROR:   [Frontend]:        Error: Error invoking remote method 'refreshLibrary': TypeError: Cannot read prop
erties of undefined (reading 'url_format')
(18:00:32) INFO:    [Frontend]:        No cache found, getting data from legendary...                                  
(18:00:32) INFO:    [Legendary]:       Refreshing library...                                                           
(18:00:32) INFO:    [Legendary]:       Updating game list
(18:00:32) INFO:    [Legendary]:       Game List Updated
(18:00:35) INFO:    [Legendary]:       Checking for game updates                                                       
(18:00:35) INFO:    [Legendary]:       Found 0 game(s) to update                                                       
(18:00:35) INFO:    [Gog]:             Found 0 game(s) to update                                                       

### Steps to reproduce

Log into Epic Games and GOG and go to the Library.

### Expected behavior

having a list of installable games.

### System Information

- OS SteamDeck KERNEL: 5.13.0-valve10.3-1-neptune-02176-g5fe416c4acd8 ARCH: x64
- Heroic Version 2.2.6 Oden

**Comment by arielj** [comment]
Can you try logging out of GOG? from the logs it seems that the problem is here `(18:00:32) ERROR: [Frontend]: Error: Error invoking remote method 'refreshLibrary': TypeError: Cannot read properties of undefined (reading 'url_format')` and that seems to be code only used in GOG games

**Comment by grince** [comment]
I signed out of GOG with the store-browserpage, stopped Heroic and restarted it. Then I logged back into GOG , but the result (and the error message) is the same.

**Comment by arielj** [comment]
Can you sign out from heroic completely? you should have your user name at the bottom left of the sidebar > manage accounts > log out in the gog block

I sent a PR with a possible fix, but I don't know how you can test it since the steam deck needs a flatpak file

**Comment by grince** [comment]
Thank you. after logging out (thans for the help to completely log out from gog) I see the games from Epic, so it really seems to be in the GOG-Code.
I'll just wait for the next flatpack-version. It is not urgent for me, so I have patience. Thanks for fixing this!
