### ISSUE TITLE
[Linux][GOG] Can't override executable

### ISSUE THREAD

**Issue by gzubsc** [Heroic-Games-Launcher/HeroicGamesLauncher#1280]
### Describe the bug

When I try to override the executable of my game (ie: Dungeon Keeper) the main executable is still launched.

### Add logs

Launch Command: STEAM_COMPAT_CLIENT_INSTALL_PATH=/home/gzu/.steam/steam STEAM_COMPAT_DATA_PATH='/home/gzu/Applications/Heroic/Prefixes/Dungeon-Keeper-Gold' "/opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl" launch "/jeux/Gog/Dungeon Keeper Gold" 1207658934 --no-wine --wrapper "'/home/gzu/.steam/steam/steamapps/common/Proton 7.0/proton' run" --os windows
        System Info:
        
  Heroic Version: 2.2.6 Oden
  Legendary Version:  0.20.25 Our Benefactors
  OS: ManjaroLinux KERNEL: 5.15.32-1-MANJARO ARCH: x64
  CPU: AMD Ryzen 7 3700X 8-Core Processor @3.6 GOVERNOR: schedutil
  RAM: Total: 16.7 GB Available: 11.7 GB
  GRAPHICS: GPU0: NVIDIA GeForce GTX 1660 SUPER VRAM: 6144MB DRIVER: 510.60.02 
  PROTOCOL: x11
  
        Game Settings: {
	"checkUpdatesInterval": 10,
	"enableUpdates": false,
	"addDesktopShortcuts": false,
	"addStartMenuShortcuts": false,
	"autoInstallDxvk": false,
	"autoInstallVkd3d": false,
	"checkForUpdatesOnStartup": true,
	"customWinePaths": [],
	"defaultInstallPath": "/jeux",
	"defaultWinePrefix": "/home/gzu/Applications/Heroic/Prefixes",
	"language": "fr",
	"maxWorkers": 0,
	"minimizeOnLaunch": false,
	"nvidiaPrime": false,
	"otherOptions": "",
	"showUnrealMarket": false,
	"showFps": false,
	"useGameMode": false,
	"userInfo": {
		"epicId": "a1cadcd48a56446d8a42cb03a980ee48",
		"name": "gzu"
	},
	"wineCrossoverBottle": "Heroic",
	"winePrefix": "/home/gzu/Applications/Heroic/Prefixes/Dungeon-Keeper-Gold",
	"wineVersion": {
		"bin": "'/home/gzu/.steam/steam/steamapps/common/Proton 7.0/proton'",
		"name": "Proton - Proton 7.0",
		"type": "proton"
	},
	"altLegendaryBin": "",
	"altGogdlBin": "",
	"darkTrayIcon": false,
	"egsLinkedPath": "",
	"maxRecentGames": 5,
	"maxSharpness": 2,
	"savesPath": "",
	"targetExe": "'/jeux/Gog/Dungeon Keeper Gold/keeperfx.exe'",
	"useSteamRuntime": false
}

        Game Log:
        fsync: up and running.
wine: RLIMIT_NICE is <= 20, unable to use setpriority safely
ALSA lib dlmisc.c:337:(snd_dlobj_cache_get0) Cannot open shared library libasound_module_pcm_pulse.so (libpulse.so.0: Ne peut ouvrir le fichier d'objet partagé: Aucun fichier ou dossier de ce type)
ALSA lib dlmisc.c:337:(snd_dlobj_cache_get0) Cannot open shared library libasound_module_pcm_pulse.so (libpulse.so.0: Ne peut ouvrir le fichier d'objet partagé: Aucun fichier ou dossier de ce type)
ALSA lib pcm.c:8568:(snd_pcm_recover) underrun occurred

### Steps to reproduce

1. Go to 'Game option, then Other tab'
2. Click on the directory icon under "Choose another exe..." and select the new executable (Kepperfx.exe in my case)
3. Launch game as usual

### Expected behavior

The new executable should be launched, but the launcher still start the original one.

### System Information

- OS: Manjaro 21.0
- Heroic Version: 2.2.6-1 (AUR repository)

### Additional information

I tried the 2 gogdl library proposed on this issue (22/03 & 29/03) but the problem still occur: [ [Linux][gog] alternative executable is not being started (starts as usual) #1141 ](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/issues/1141)
I'd reconfigured the new binary on option "Choose an alternative GOGDL..." and the version was recognised "GOGDL version: 0.2"

FYI, I have the same issue on another GOG game: Blood, when I try to override with "nblood.exe"

BTW, thanks for this awesome launcher, I just discovered the HeroicBashLauncher and the steam integration. I'm blasted !

**Comment by imLinguin** [comment]
Maybe try Heroic beta we just released. Looking at the logs it seems `--override-exe` parameter isn't present. You can also take that command and append parameter manually with path to desired executable

**Comment by gzubsc** [comment]
I just tried the last [v2.3.0-beta.2](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/releases/tag/v2.3.0-beta.2) and I can confirm that I have not the problem anymore. 
And a few of the new features are awesome, I stick with it.
Thanks for you answer and your quick workaround !
