### ISSUE TITLE
2.3.0-beta.2: Theme issues

### ISSUE THREAD

**Issue by arshubham** [Heroic-Games-Launcher/HeroicGamesLauncher#1282]
### Describe the bug

Some theme issues I encountered in latest beta.

1. Play button not visible in `Old School Heroic` . No issues in any other theme.
![image](https://user-images.githubusercontent.com/14235191/167311688-22866140-be60-40d8-93c1-5321b30b5bb3.png)

2. Contrast issues in text boxes, select boxes and buttons with background.
`Old School Heroic`
![image](https://user-images.githubusercontent.com/14235191/167311956-c30473f6-7749-4e3a-a041-33809545f93d.png)
![image](https://user-images.githubusercontent.com/14235191/167311896-adad358e-92e3-4c51-a880-f0939aba1e55.png)
![image](https://user-images.githubusercontent.com/14235191/167312123-a8f75fc8-78d9-42f2-911c-81b99d01e28d.png)
`Zombie`
![image](https://user-images.githubusercontent.com/14235191/167311933-bd34f04b-9e9e-4c67-a25a-aea409bd74a3.png)
`Dracula`
![image](https://user-images.githubusercontent.com/14235191/167312076-097b756e-2ed3-4a86-92ad-9563bb0e4114.png)

3, Add folder icon in `Sync with installed Epic Games` is muted in all themes.
![image](https://user-images.githubusercontent.com/14235191/167312018-18c62a20-70cd-4215-ad03-c9bc1813ef36.png)

### Add logs

NA

### Steps to reproduce

NA

### Expected behavior

NA

### System Information

NA

**Comment by flavioislima** [comment]
Yes, saw some of those after releasing. We will fix it for stable. Thanks for reporting it.

**Comment by arielj** [comment]
1) should be already fixed in the beta
3) should be fixed in https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/pull/1281
2) I'll wait until we have the updated figma designs before fixing this, I don't want to go and pick random values

**Comment by arshubham** [comment]
@arielj Thanks for fixing the issues. Can verify Point 1 is fixed.

Found another minor bug. When heroic is loaded the loading page always uses the default theme. 

https://user-images.githubusercontent.com/14235191/167550853-42e2e02c-ce17-48c9-abeb-87186f5fe73b.mp4

**Comment by arielj** [comment]
@arshubham can you confirm if all these issues got fixed in the latest 2.3.1 version? thanks

**Comment by arshubham** [comment]
@arielj Contrast and file icon issues are fixed. 

Still facing the loading issue. Now loading icon is shown on the correct theme however background color from default theme is shown before that.

https://user-images.githubusercontent.com/14235191/168533739-a6742415-2f8f-4b84-8e9e-07a20a364f48.mp4

**Comment by arielj** [comment]
The background issue was fixed in one of the 2.3.x versions and it was the last remaining problem here, closing this.
