### ISSUE TITLE
Uplay support

### ISSUE THREAD

**Issue by lol28** [Heroic-Games-Launcher/HeroicGamesLauncher#1288]
### Problem description

It would be really neat to have uplay support, to not mess with their buggy launcher.

### Feature description

Possibility to download and launch games from uplay

**Comment by Lariaa** [comment]
For future reference:
https://github.com/claabs/ubisoft-demux-node
https://github.com/claabs/ubisoft-dmx-decode
https://github.com/Lariaa/GameLauncherResearch/wiki/Ubisoft-Connect

**Comment by XargonWan** [comment]
I second this, at this time there is some workaround that for me never worked.

**Comment by MrArdillo** [comment]
Plis it will be awesome and origin support too

**Comment by Nocccer** [comment]
We only can implement support, if someone decrypted there API. Closing this for now, because it will not happen soon.
