### ISSUE TITLE
Amazon Games / Twitch support

### ISSUE THREAD

**Issue by nobodywasishere** [Heroic-Games-Launcher/HeroicGamesLauncher#1289]
### Feature description

Add support for games available via amazon/twitch. Login, see/play games, etc.

### Additional information

Potentially useful: https://github.com/imLinguin/nile/

**Comment by Rahabib** [comment]
Yes please!

**Comment by MrM4rc** [comment]
We need that!

**Comment by ronoaldo** [comment]
Adding support for nile backend to do the library/install/update stuff and use the Heroic UI would be awesome!

**Comment by Nocccer** [comment]
> Adding support for nile backend to do the library/install/update stuff and use the Heroic UI would be awesome!

#1616

**Comment by Nocccer** [comment]
> Adding support for nile backend to do the library/install/update stuff and use the Heroic UI would be awesome!

Sure i think imLunguin could need some help to improve it more. If there devs, contribute to nile or get in contact.

**Comment by tripplehelix** [comment]
Would love this

**Comment by Aftonstjarna** [comment]
Bump. Would love to see Nile within Heroics GUI. CLI works but it's not very convenient.

**Comment by Vadatajs** [comment]
bump. excited to see if this could happen

**Comment by H-Tevin** [comment]
bump. This would be amazing. Downloading a whole new launcher for one or two games is ridiculous. This is a perfect problem for Heroic to fix

**Comment by nobodywasishere** [comment]
Would it be possible for people to stop bumping this issue? It creates unnecessary noise and clutters this thread. If you want to watch this issue for news there's a subscribe button on the sidebar. Bumping this isn't going to get this implemented any faster. Thank you.

**Comment by Vadatajs** [comment]
I would think an issue garnering some more attention (bumps) would help prioritize new updates, is that not the case?

**Comment by H-Tevin** [comment]
Linguin is a dev, if they say it shows interest, then I'm inclined to believe them.

Talking about it and showing that there are many people who want this feature can't hurt.

**Comment by imLinguin** [comment]
Please don't start a war here. Not sure why @nobodywasishere hates those comments (I'm not interested in knowing that). However the implementation will be done eventually, at this moment there are some other priorities though.

**Comment by siavashs** [comment]
Lutris added support for [Amazon Games Integration recently](https://github.com/lutris/lutris/releases/tag/v0.5.11), so there is an alternative solution until this feature is implemented in HeroicGamesLauncher.

**Comment by AtFreezingPoint** [comment]
Bumping this one ;)

**Comment by imLinguin** [comment]
Work in progress #2831
