### ISSUE TITLE
[Steamdeck] Cannot install in Game Mode

### ISSUE THREAD

**Issue by Qowy** [Heroic-Games-Launcher/HeroicGamesLauncher#1297]
### Describe the bug

When I try to install a game in GameMode it is stuck on installing... and the whole program freezes (I cannot click on anything).

Installing in Desktop mode works (Maybe a problem with the Notification?)

### Add logs
```
(11:48:02) INFO:    [Legendary]:       Location: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary
(11:48:02) INFO:    [Gog]:             Location: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl
(11:48:03) INFO:    [Backend]:         
  Heroic Version: 2.2.6 Oden
  Legendary Version:  0.20.25 Our Benefactors
  OS: Freedesktop.org KERNEL: 5.13.0-valve10.3-1-neptune-02176-g5fe416c4acd8 ARCH: x64
  CPU: AMD Custom APU 0405 @1.99 GOVERNOR: schedutil
  RAM: Total: 15.6 GB Available: 12.4 GB
  GRAPHICS: GPU0: Device 163f VRAM: 512MB DRIVER:  
  PROTOCOL: wayland
  
(11:48:03) INFO:    [Gog]:             Getting data about the user
(11:48:03) INFO:    [Gog]:             Refreshing access_token
(11:48:03) ERROR:   [Backend]:         Failed to register protocol with OS.
(11:48:03) INFO:    [Gog]:             Token refreshed successfully
(11:48:04) INFO:    [Gog]:             Saved user data to config
(11:48:04) INFO:    [Frontend]:        Refreshing Library
(11:48:04) INFO:    [Gog]:             Getting GOG library
(11:48:05) INFO:    [Gog]:             Number of library pages: 1
(11:48:05) INFO:    [Gog]:             Saved games data
(11:48:05) INFO:    [Legendary]:       Refreshing library...
(11:48:05) INFO:    [Legendary]:       Refreshing Epic Games...
(11:48:05) INFO:    [Legendary]:       Refreshing Epic Games...
(11:48:06) INFO:    [Legendary]:       [Core] WARNING: Could not determine locale, falling back to en-US
(11:48:06) INFO:    [Legendary]:       [cli] INFO: Logging in...
(11:48:07) INFO:    [Legendary]:       [Core] INFO: Logging in...
(11:48:08) INFO:    [Legendary]:       [cli] INFO: Getting game list... (this may take a while)
(11:48:08) INFO:    [Legendary]:       [Core] INFO: Fetching metadata for 2 app(s).
(11:48:09) INFO:    [Legendary]:       Updating game list
(11:48:09) INFO:    [Legendary]:       Game List Updated
(11:48:09) INFO:    [Backend]:         checking for heroic updates
(11:48:09) INFO:    [Backend]:         skipping heroic updates
(11:48:10) INFO:    [Legendary]:       Checking for game updates
(11:48:10) INFO:    [Legendary]:       Found 0 game(s) to update
(11:48:10) INFO:    [Gog]:             Found 0 game(s) to update
(11:48:10) INFO:    [Frontend]:        Force Update
(11:50:18) INFO:    [Gog]:             Installing 1207658890 with: "/app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl" download 1207658890 --platform windows --path="/run/media/mmcblk0p1/Games" --skip-dlcs --lang="fr"  |& tee "/home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/GamesConfig/1207658890.log"

```
```
[API] INFO: Getting info from products endpoint for id: 1207658890
[DOWNLOAD_MANAGER] INFO: Checking compatibility of Neverwinter Nights Diamond with windows
[DOWNLOAD_MANAGER] INFO: Game is compatible
```

### Steps to reproduce

Add as non steam game.
Launch from Game Mode.
Try to install any game.
Freezes
Force exit through steam a short "There are pending operation" pops up

### Expected behavior

Installing Game

### System Information

- OS SteamOS
- Heroic Version 2.2.6 Flatpack:

**Comment by Qowy** [comment]
Yes

**Comment by flavioislima** [comment]
Is this for all games? do you have space left on the device to install?
Whats on `/home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/GamesConfig/1207658890.log` ?

**Comment by uramer** [comment]
Still reproduces with 2.3.9

**Comment by uramer** [comment]
Reproduces on 2.4.0-beta as well, and applies to uninstalling games too

**Comment by arielj** [comment]
@uramer I don't have a steamdeck, do you have any way to run command line tools in Game Mode? might be useful to see what happens if you call the Legendary or GOGdl commands directly without Heroic in the middle

From your logs:

```
/app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary install 03b7b25a77024cc0adf44777f791ffc4 --platform Windows --base-path /run/media/mmcblk0p1/Games --skip-dlcs --skip-sdl -y
```

```
/app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl" download 1207658890 --platform windows --path="/run/media/mmcblk0p1/Games" --skip-dlcs --lang="fr"
```

**Comment by uramer** [comment]
Those are not my logs, but the issue's original author's :)

Here are mine https://pastebin.com/N9xtbrCk

**Comment by uramer** [comment]
I tried running `/app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary install 19927295d6e3467887d4e830d8c85963 --platform Windows --base-path /home/deck/Games/Heroic --skip-dlcs --skip-sdl -y` in game mode through Konsole, and got `/app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary: No such file or directory`. I would assume this is due to the Heroic flatpak not being active at the time?

**Comment by Qowy** [comment]
I usually get the feeling, that it freezes at the exact moment the tray installing notification would pop up in desktop mode.
Maybe the api call fails in game mode. Is there a way to test Heroic without the notification feature.

**Comment by uramer** [comment]
Well just now it froze for me instantly, at 0% downloading progress, and Heroic does show an "installation started" notification, so that's a plausible theory.

**Comment by Nocccer** [comment]
Ah ok yes sounds like a problem. We can see if we are on steam deck game mode and disable all notifications. I can push something today.

**Comment by Nocccer** [comment]
@uramer @Qowy can you test the appimage in gamemode? I will also test it, if i find time.
https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/suites/7749782320/artifacts/325404009

**Comment by Qowy** [comment]
sure, in the evening.
Anything special to get an appimage to run?

**Comment by Nocccer** [comment]
Ok i tested it and it seems to work.

1. download the zip and unpack the appimage
2. make the appiamge executable (file properties > make executable)
3. Add it as none steam game to steam and add start option: `--no-sandbox`

**Comment by uramer** [comment]
Tried it, same freeze at 0% progress

**Comment by Qowy** [comment]
Question remains, does the steamdeck detection work :D Is there anything else that relies on that to verify.

In addition non e of the developers has a steamdeck right?
Can we do something like attach gdb via ssh. to see the hanging function?
Is there a easy debugging method for electron apps?

**Comment by uramer** [comment]
Tried it. Can't even log into my Epic account without freezing. Will try with logging in on Desktop first

**Comment by uramer** [comment]
After logging in on Desktop, installing a game didn't freeze! So while this seems to not be the only cause of freezes, it's one of them

**Comment by Nocccer** [comment]
I tested the appimage. I did not tried to login via gamemode. But installing, playing and removing worked.
I'm pretty sure the detection works. I implemented the quit button again, if we are in gamemode. I tested it on my steamdeck.

I know there is a issue with gog game download progress, not updated in frontend. That happens also on desktop mode.

**Comment by Nocccer** [comment]
> After logging in on Desktop, installing a game didn't freeze! So while this seems to not be the only cause of freezes, it's one of them

Maybe i missed some notifications, so login freezes. Will check again.

**Comment by Nocccer** [comment]
Ok login in worked fine for me aswell. The only problem is that the appimage performance is pretty slow.

**Comment by Nocccer** [comment]
Ok i rewrote the code. Now i don't rely on gamemode. I just check if the system supports notifications via:
https://www.electronjs.org/de/docs/latest/api/notification#notificationissupported

**Comment by uramer** [comment]
Yeah, this AppImage freezes for me again

**Comment by Qowy** [comment]
Thanks for the quick fix, once we correctly guessed the issue :)

I wonder (for the future) if it would be possible to switch to the steam notification api, when run in gamemode. However I have no idea if there even is an API for that. We would probably have to ask valve.

**Comment by Nocccer** [comment]
I don't know if this is possible. If you get any api we can try. I will close for now and you can create a new issue if you have more information.
