### ISSUE TITLE
Flatpak version does not create shortcuts properly (missing folders)

### ISSUE THREAD

**Issue by NelloKudo** [Heroic-Games-Launcher/HeroicGamesLauncher#1300]
I tried creating a shortcut for games by **left clicking on it** > **Tools** > **Add shortcut** but those won't create neither in `~/.local/share/applications` (Flatseal says the app cannot access it apparently) nor in `~/.var/app/com.heroicgameslauncher.hgl/.local/share/applications` as these folder (.local/share/applications) don't exist.

**Example:** (tried with both Rocket League and GTA V)
```
INFO:    [Backend]:         Shortcut saved on /home/nellokudo/Desktop/Rocket League®.desktop
INFO:    [Backend]:         Shortcut saved on /home/nellokudo/.var/app/com.heroicgameslauncher.hgl/.local/share/applications/Rocket League®.desktop
```
But the results are:

![image](https://user-images.githubusercontent.com/98063377/168331416-6908be4c-23d4-48ee-95d9-44aca6e39ce2.png)
![image](https://user-images.githubusercontent.com/98063377/168331835-692937ec-cb50-481c-bd0f-0ee50c885be2.png)

Creating .local/share/applications manually fixes creating the .desktop entry.
Full logs are here:

[heroiclogs.txt](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/files/8689587/heroiclogs.txt)

**Comment by Henry-Hiles** [comment]
You have to give heroic access to system files / those folders using flatseal iirc.

**Comment by flavioislima** [comment]
Yes, we might need to update the Wiki with this informatino.

**Comment by flavioislima** [comment]
This was fixed sometime ago.
