### ISSUE TITLE
[Linux Flatpak] Visual glitches after upgrade to 2.3.0

### ISSUE THREAD

**Issue by syeedahmed** [Heroic-Games-Launcher/HeroicGamesLauncher#1308]
### Describe the bug

i don't know what to write actually. cant even login in epic account. cant go to settings. i share a video on twitter  

### Add logs

flatpak run com.heroicgameslauncher.hgl
Gtk-Message: 15:42:21.397: Failed to load module "canberra-gtk-module"
Gtk-Message: 15:42:21.397: Failed to load module "pk-gtk-module"
Gtk-Message: 15:42:21.397: Failed to load module "canberra-gtk-module"
Gtk-Message: 15:42:21.397: Failed to load module "pk-gtk-module"
[3:0515/154221.409833:ERROR:bus.cc(397)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[3:0515/154221.409941:ERROR:bus.cc(397)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
(15:42:21) DEBUG:   [Legendary]:       Running Legendary command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary --version
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
[43:0515/154221.501735:ERROR:sandbox_linux.cc(377)] InitializeSandbox() called with multiple threads in process gpu-process.
hostname: invalid option -- 'f'
Try 'hostname --help' for more information.
(15:42:22) INFO:    [Legendary]:       Legendary location: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary
(15:42:22) INFO:    [Gog]:             GOGDL location: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl
(15:42:22) INFO:    [Backend]:         
  Heroic Version: 2.3.0 Brook
  Legendary Version:  0.20.25 Our Benefactors
  OS: Freedesktop.org KERNEL: 5.17.6-300.fc36.x86_64 ARCH: x64
  CPU: AMD Ryzen 5 3400G with Radeon Vega Graphics @3.7 GOVERNOR: schedutil
  RAM: Total: 13.64 GiB Available: 11.81 GiB
  GRAPHICS: GPU0: Picasso VRAM: 512MB DRIVER:  
  PROTOCOL: wayland
  
(15:42:22) INFO:    [Backend]:         User Not Found, removing it from Store
APPIMAGE env is not defined, current application is not an AppImage
LaunchProcess: failed to execvp:
xdg-settings
(15:42:22) ERROR:   [Backend]:         Failed to register protocol with OS.
[3:0515/154222.524936:ERROR:browser_main_loop.cc(269)] Gtk: gtk_widget_add_accelerator: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed
[3:0515/154222.525008:ERROR:browser_main_loop.cc(269)] Gtk: gtk_widget_add_accelerator: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed
[3:0515/154222.525087:ERROR:browser_main_loop.cc(269)] Gtk: gtk_widget_add_accelerator: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed
[43:0515/154224.662010:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 1 times!
[43:0515/154225.861245:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 2 times!
[43:0515/154225.869686:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 3 times!
(node:163) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 updateLoginState listeners added to [EventEmitter]. Use emitter.setMaxListeners() to increase limit
(Use `exe --trace-warnings ...` to show where the warning was created)
(15:42:35) INFO:    [Frontend]:        Refreshing wine downloader releases
(15:42:35) INFO:    [WineDownloader]:  Updating wine versions info
(15:42:35) INFO:    [WineDownloader]:  Fetching upstream information...
(15:42:38) INFO:    [WineDownloader]:  wine versions updated

### Steps to reproduce

2. Click on '...'
3. Scroll down to '...'

### Expected behavior

cant open any option

### System Information

OS: Fedora Linux 36 (Workstation Edition) x86_64 
Kernel: 5.17.6-300.fc36.x86_64 
DE: GNOME 42.0 
CPU: AMD Ryzen 5 3400G (8) @ 4.150GHz 
GPU: AMD ATI Radeon Vega Series / Radeon Vega Mobile Series

**Comment by baduhai** [comment]
Exact same problem, nothing works after latest update. Whenever I click on any option, the window flashes for a split second and returns me right to the login screen.

Logs:  
```
tk-Message: 12:13:31.882: Failed to load module "colorreload-gtk-module"
Gtk-Message: 12:13:31.882: Failed to load module "window-decorations-gtk-module"
(12:13:31) DEBUG:   [Legendary]:       Running Legendary command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary --version
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
[42:0515/121331.958215:ERROR:sandbox_linux.cc(377)] InitializeSandbox() called with multiple threads in process gpu-process.
hostname: invalid option -- 'f'
Try 'hostname --help' for more information.
(12:13:32) INFO:    [Legendary]:       Legendary location: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary
(12:13:32) INFO:    [Gog]:             GOGDL location: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl
(12:13:32) INFO:    [Backend]:         
  Heroic Version: 2.3.0 Brook
  Legendary Version:  0.20.25 Our Benefactors
  OS: Freedesktop.org KERNEL: 5.17.7-zen1-1-zen ARCH: x64
  CPU: AMD Ryzen 5 3600 6-Core Processor @3.6 GOVERNOR: schedutil
  RAM: Total: 15.61 GiB Available: 12.15 GiB
  GRAPHICS: GPU0: Device 73df VRAM: 1MB DRIVER:  
  PROTOCOL: wayland
  
(12:13:32) INFO:    [Backend]:         User Not Found, removing it from Store
APPIMAGE env is not defined, current application is not an AppImage
LaunchProcess: failed to execvp:
xdg-settings
(12:13:32) ERROR:   [Backend]:         Failed to register protocol with OS.
[3:0515/121332.331867:ERROR:browser_main_loop.cc(269)] Gtk: gtk_widget_add_accelerator: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed
[3:0515/121332.331936:ERROR:browser_main_loop.cc(269)] Gtk: gtk_widget_add_accelerator: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed
[3:0515/121332.331970:ERROR:browser_main_loop.cc(269)] Gtk: gtk_widget_add_accelerator: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed
[42:0515/121338.370661:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 1 times!
[42:0515/121338.379931:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 2 times!
(12:13:41) INFO:    [Frontend]:        Refreshing wine downloader releases
(12:13:41) INFO:    [WineDownloader]:  Updating wine versions info
(12:13:41) INFO:    [WineDownloader]:  Fetching upstream information...
(12:13:42) INFO:    [WineDownloader]:  wine versions updated
```

**Comment by syeedahmed** [comment]
> Exact same problem, nothing works after latest update. Whenever I click on any option, the window flashes for a split second and returns me right to the login screen.
> 
> Logs:
> 
> ```
> tk-Message: 12:13:31.882: Failed to load module "colorreload-gtk-module"
> Gtk-Message: 12:13:31.882: Failed to load module "window-decorations-gtk-module"
> (12:13:31) DEBUG:   [Legendary]:       Running Legendary command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary --version
> libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
> [42:0515/121331.958215:ERROR:sandbox_linux.cc(377)] InitializeSandbox() called with multiple threads in process gpu-process.
> hostname: invalid option -- 'f'
> Try 'hostname --help' for more information.
> (12:13:32) INFO:    [Legendary]:       Legendary location: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary
> (12:13:32) INFO:    [Gog]:             GOGDL location: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl
> (12:13:32) INFO:    [Backend]:         
>   Heroic Version: 2.3.0 Brook
>   Legendary Version:  0.20.25 Our Benefactors
>   OS: Freedesktop.org KERNEL: 5.17.7-zen1-1-zen ARCH: x64
>   CPU: AMD Ryzen 5 3600 6-Core Processor @3.6 GOVERNOR: schedutil
>   RAM: Total: 15.61 GiB Available: 12.15 GiB
>   GRAPHICS: GPU0: Device 73df VRAM: 1MB DRIVER:  
>   PROTOCOL: wayland
>   
> (12:13:32) INFO:    [Backend]:         User Not Found, removing it from Store
> APPIMAGE env is not defined, current application is not an AppImage
> LaunchProcess: failed to execvp:
> xdg-settings
> (12:13:32) ERROR:   [Backend]:         Failed to register protocol with OS.
> [3:0515/121332.331867:ERROR:browser_main_loop.cc(269)] Gtk: gtk_widget_add_accelerator: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed
> [3:0515/121332.331936:ERROR:browser_main_loop.cc(269)] Gtk: gtk_widget_add_accelerator: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed
> [3:0515/121332.331970:ERROR:browser_main_loop.cc(269)] Gtk: gtk_widget_add_accelerator: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed
> [42:0515/121338.370661:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 1 times!
> [42:0515/121338.379931:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 2 times!
> (12:13:41) INFO:    [Frontend]:        Refreshing wine downloader releases
> (12:13:41) INFO:    [WineDownloader]:  Updating wine versions info
> (12:13:41) INFO:    [WineDownloader]:  Fetching upstream information...
> (12:13:42) INFO:    [WineDownloader]:  wine versions updated
> ```

yes same thing

**Comment by flavioislima** [comment]
This seems like a GPU Driver issue, conflict, hard to know. Or maybe a Wayland issue.
Can you guys try the AppImage?
Also besides Heroic, did you update something else? Kernel, drivers, etc?

@syeedahmed can you attach the video you posted on twitter?

**Comment by flavioislima** [comment]
If the 2.3.0 AppImage has the same issue, try also the previous beta release 2.3.0 beta 3 to see if the same problem happens.

**Comment by flavioislima** [comment]
I can replicate this issue on Wayland with Nvidia, but this happened with other versions as well.
Can you try on X11?

**Comment by syeedahmed** [comment]
> 

https://twitter.com/SyeedAhmed20/status/1525764002583674880?t=4VyboGp_YJ8uAjrbqKEsvw&s=19

**Comment by syeedahmed** [comment]
> I can replicate this issue on Wayland with Nvidia, but this happened with other versions as well. Can you try on X11?

i tried on kde neon with xorg same problem

**Comment by flavioislima** [comment]
@syeedahmed can you try this appImage:
https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/actions/runs/2327134023

**Comment by syeedahmed** [comment]
> @syeedahmed can you try this appImage: https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/actions/runs/2327134023
 naah same prob.. in xorg too... is it ryzen 3400g apu driver issue or something? i mean even appimage is also getting same problem

**Comment by flavioislima** [comment]
@syeedahmed so just to confirm that this issue is on latest version. Can you try the Beta 3 AppImage? and the 2.2.6 Stable AppImage?

What was the last working version?

**Comment by syeedahmed** [comment]
> @syeedahmed so just to confirm that this issue is on latest version. Can you try the Beta 3 AppImage? and the 2.2.6 Stable AppImage?
> 
> What was the last working version?

version 2.2.6 is working fine. i always use flatpak so i didn't tried  beta
version 2.26 appimage log:
./Heroic-2.2.6.AppImage
(19:01:27) INFO:    [Legendary]:       Location: /tmp/.mount_Heroic9TNi6B/resources/app.asar.unpacked/build/bin/linux/legendary
(19:01:27) INFO:    [Gog]:             Location: /tmp/.mount_Heroic9TNi6B/resources/app.asar.unpacked/build/bin/linux/gogdl
[3820:0515/190128.070256:ERROR:sandbox_linux.cc(377)] InitializeSandbox() called with multiple threads in process gpu-process.
(19:01:28) INFO:    [Backend]:         
  Heroic Version: 2.2.6 Oden
  Legendary Version:  0.20.25 Our Benefactors
  OS: Debian GNU/Linux KERNEL: 5.10.0-14-amd64 ARCH: x64
  CPU: AMD Ryzen 5 3400G with Radeon Vega Graphics @3.7 GOVERNOR: schedutil
  RAM: Total: 14.7 GB Available: 12.8 GB
  GRAPHICS: GPU0: Picasso VRAM: 512MB DRIVER:  
  PROTOCOL: x11
  
(19:01:28) INFO:    [Backend]:         User Not Found, removing it from Store
(19:01:29) ERROR:   [Backend]:         Failed to register protocol with OS.
[3788:0515/190129.289375:ERROR:browser_main_loop.cc(267)] Gtk: gtk_widget_add_accelerator: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed
[3788:0515/190129.289621:ERROR:browser_main_loop.cc(267)] Gtk: gtk_widget_add_accelerator: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed
[3788:0515/190129.289825:ERROR:browser_main_loop.cc(267)] Gtk: gtk_widget_add_accelerator: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed
(19:01:32) INFO:    [DXVKInstaller]:   Updating vkd3d to: vkd3d-proton-2.6
(19:01:33) INFO:    [DXVKInstaller]:   downloaded vkd3d
(19:01:33) INFO:    [DXVKInstaller]:   extracting vkd3d
(19:01:33) ERROR:   [DXVKInstaller]:   Extraction of vkd3d failed with: Error: Command failed: tar -I zstd -xvf /home/syeedahmed/.config/heroic/tools/vkd3d/vkd3d-proton-2.6.tar.zst -C /home/syeedahmed/.config/heroic/tools/vkd3d
tar (child): zstd: Cannot exec: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now

(19:01:34) INFO:    [Backend]:         checking for heroic updates

**Comment by flavioislima** [comment]
Ah, we have had flatpak beta actually.
So then try now Beta 1 and 3 to see if you get this error.

**Comment by syeedahmed** [comment]
> Ah, we have had flatpak beta actually. So then try now Beta 1 and 3 to see if you get this error.

beta 1 is working
./Heroic-2.3.0-beta.1.AppImage
(19:11:17) DEBUG:   [Legendary]:       Running Legendary command: /tmp/.mount_HeroicU0eChS/resources/app.asar.unpacked/build/bin/linux/legendary --version
[4843:0515/191117.351086:ERROR:sandbox_linux.cc(377)] InitializeSandbox() called with multiple threads in process gpu-process.
(19:11:17) INFO:    [Legendary]:       Legendary location: /tmp/.mount_HeroicU0eChS/resources/app.asar.unpacked/build/bin/linux/legendary
(19:11:17) INFO:    [Gog]:             GOGDL location: /tmp/.mount_HeroicU0eChS/resources/app.asar.unpacked/build/bin/linux/gogdl
(19:11:17) INFO:    [Backend]:         
  Heroic Version: 2.3.0-beta.1 Caesar Clown
  Legendary Version:  0.20.25 Our Benefactors
  OS: Debian GNU/Linux KERNEL: 5.10.0-14-amd64 ARCH: x64
  CPU: AMD Ryzen 5 3400G with Radeon Vega Graphics @3.7 GOVERNOR: schedutil
  RAM: Total: 14.7 GB Available: 12.7 GB
  GRAPHICS: GPU0: Picasso VRAM: 512MB DRIVER:  
  PROTOCOL: x11
  
(19:11:17) INFO:    [Backend]:         User Not Found, removing it from Store
Checking for update
(19:11:18) ERROR:   [Backend]:         Failed to register protocol with OS.
[4810:0515/191118.491224:ERROR:browser_main_loop.cc(269)] Gtk: gtk_widget_add_accelerator: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed
[4810:0515/191118.491293:ERROR:browser_main_loop.cc(269)] Gtk: gtk_widget_add_accelerator: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed
[4810:0515/191118.491342:ERROR:browser_main_loop.cc(269)] Gtk: gtk_widget_add_accelerator: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed
Found version 2.3.0-beta.3 (url: Heroic-2.3.0-beta.3.AppImage)
(19:11:21) INFO:    [DXVKInstaller]:   Updating vkd3d to: vkd3d-proton-2.6
(19:11:22) INFO:    [DXVKInstaller]:   downloaded vkd3d
(19:11:22) INFO:    [DXVKInstaller]:   extracting vkd3d
(19:11:22) ERROR:   [DXVKInstaller]:   Extraction of vkd3d failed with: Error: Command failed: tar -I zstd -xvf /home/syeedahmed/.config/heroic/tools/vkd3d/vkd3d-proton-2.6.tar.zst -C /home/syeedahmed/.config/heroic/tools/vkd3d
tar (child): zstd: Cannot exec: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now

**Comment by syeedahmed** [comment]
> Ah, we have had flatpak beta actually. So then try now Beta 1 and 3 to see if you get this error.

beta 2 is giving same problems 
./Heroic-2.3.0-beta.2.AppImage
(19:12:55) DEBUG:   [Legendary]:       Running Legendary command: /tmp/.mount_HeroiceaFHSo/resources/app.asar.unpacked/build/bin/linux/legendary --version
[5113:0515/191255.225223:ERROR:sandbox_linux.cc(377)] InitializeSandbox() called with multiple threads in process gpu-process.
(19:12:55) INFO:    [Legendary]:       Legendary location: /tmp/.mount_HeroiceaFHSo/resources/app.asar.unpacked/build/bin/linux/legendary
(19:12:55) INFO:    [Gog]:             GOGDL location: /tmp/.mount_HeroiceaFHSo/resources/app.asar.unpacked/build/bin/linux/gogdl
(19:12:55) INFO:    [Backend]:         
  Heroic Version: 2.3.0-beta.2 Caesar Clown
  Legendary Version:  0.20.25 Our Benefactors
  OS: Debian GNU/Linux KERNEL: 5.10.0-14-amd64 ARCH: x64
  CPU: AMD Ryzen 5 3400G with Radeon Vega Graphics @3.7 GOVERNOR: schedutil
  RAM: Total: 13.65 GiB Available: 11.83 GiB
  GRAPHICS: GPU0: Picasso VRAM: 512MB DRIVER:  
  PROTOCOL: x11
  
(19:12:55) INFO:    [Backend]:         User Not Found, removing it from Store
Checking for update
(19:12:56) ERROR:   [Backend]:         Failed to register protocol with OS.
[5081:0515/191256.477738:ERROR:browser_main_loop.cc(269)] Gtk: gtk_widget_add_accelerator: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed
[5081:0515/191256.477843:ERROR:browser_main_loop.cc(269)] Gtk: gtk_widget_add_accelerator: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed
[5081:0515/191256.477920:ERROR:browser_main_loop.cc(269)] Gtk: gtk_widget_add_accelerator: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed
Found version 2.3.0-beta.3 (url: Heroic-2.3.0-beta.3.AppImage)
(19:12:59) INFO:    [DXVKInstaller]:   Updating vkd3d to: vkd3d-proton-2.6
(19:13:01) INFO:    [DXVKInstaller]:   downloaded vkd3d
(19:13:01) INFO:    [DXVKInstaller]:   extracting vkd3d
(19:13:01) ERROR:   [DXVKInstaller]:   Extraction of vkd3d failed with: Error: Command failed: tar -I zstd -xvf /home/syeedahmed/.config/heroic/tools/vkd3d/vkd3d-proton-2.6.tar.zst -C /home/syeedahmed/.config/heroic/tools/vkd3d
tar (child): zstd: Cannot exec: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now

(19:13:07) INFO:    [Frontend]:        Refreshing wine downloader releases
(19:13:07) INFO:    [WineDownloader]:  Updating wine versions info
(19:13:08) INFO:    [Frontend]:        Refreshing wine downloader releases
(19:13:08) INFO:    [WineDownloader]:  Updating wine versions info
(19:13:10) INFO:    [WineDownloader]:  wine versions updated
(19:13:11) INFO:    [WineDownloader]:  wine versions updated

**Comment by flavioislima** [comment]
this error is normal, it is because you don't have `zstd` installed to extract the VKD3D files.
`(19:13:01) ERROR: [DXVKInstaller]: Extraction of vkd3d failed with: Error: Command failed: tar -I zstd -xvf /home/syeedahmed/.config/heroic/tools/vkd3d/vkd3d-proton-2.6.tar.zst -C /home/syeedahmed/.config/heroic/tools/vkd3d`

But the login is working? library, etc?

**Comment by flavioislima** [comment]
Ah you mean same problems, I read some problems. Sorry
So then the problem started with beta 2. Ok then, thanks for testing that.

**Comment by syeedahmed** [comment]
> Ah you mean same problems, I read some problems. Sorry So then the problem started with beta 2. Ok then, thanks for testing that.

welcome

**Comment by flavioislima** [comment]
I know it is obvious but have you tried restarting your PC? 😅

**Comment by arielj** [comment]
I think this might get fixed in this PR https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/pull/1306, I was working on this refactor yesterday and noticed that, anything you click redirects you to the login (because the SidebarLinks component is always redirecting you `/login` when there's no user)

**Comment by syeedahmed** [comment]
> I know it is obvious but have you tried restarting your PC? sweat_smile

i restated my pc even try with two distro man.. now I am just tired.

**Comment by flavioislima** [comment]
@syeedahmed I see, can you do one last try with @arielj changes then ? so I could make a new release if that fixes it.
https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/actions/runs/2326079265

**Comment by r2rX** [comment]
For what it's worth, I'm running Fedora 36 KDE w/ Mesa 22.2.0-dev & Wayland; this issue occurs with the Flatpak, AppImage and .rpm packages.

**Comment by flavioislima** [comment]
@r2rX can you try the appimage from the build above?

**Comment by r2rX** [comment]
> @r2rX can you try the appimage from the build above?

The above AppImage build seems to be working fine. :)

**Comment by flavioislima** [comment]
Great news! @syeedahmed @baduhai let me know if it fixes for you as well.

**Comment by syeedahmed** [comment]
> Great news! @syeedahmed @baduhai let me know if it fixes for you as well.

I'm outside right now... I will let you know

**Comment by eyoung417** [comment]
Can also verify that the latest release version doesn't work on Garuda (Arch based) and just seems to loop when trying to log in to either of the stores. However the appimage build seems to be working fine.

**Comment by syeedahmed** [comment]
> @syeedahmed I see, can you do one last try with @arielj changes then ? so I could make a new release if that fixes it. https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/actions/runs/2326079265
./Heroic-2.3.0.AppImage
(22:40:48) DEBUG:   [Legendary]:       Running Legendary command: /tmp/.mount_HeroictjCmuE/resources/app.asar.unpacked/build/bin/linux/legendary --version
[2238:0515/224048.335607:ERROR:sandbox_linux.cc(377)] InitializeSandbox() called with multiple threads in process gpu-process.
(22:40:48) INFO:    [Legendary]:       Legendary location: /tmp/.mount_HeroictjCmuE/resources/app.asar.unpacked/build/bin/linux/legendary
(22:40:48) INFO:    [Gog]:             GOGDL location: /tmp/.mount_HeroictjCmuE/resources/app.asar.unpacked/build/bin/linux/gogdl
(22:40:48) INFO:    [Backend]:         
  Heroic Version: 2.3.0 Brook
  Legendary Version:  0.20.25 Our Benefactors
  OS: Debian GNU/Linux KERNEL: 5.10.0-14-amd64 ARCH: x64
  CPU: AMD Ryzen 5 3400G with Radeon Vega Graphics @3.7 GOVERNOR: schedutil
  RAM: Total: 13.65 GiB Available: 11.99 GiB
  GRAPHICS: GPU0: Picasso VRAM: 512MB DRIVER:  
  PROTOCOL: x11
  
(22:40:48) INFO:    [Backend]:         User Not Found, removing it from Store
Checking for update
(22:40:49) ERROR:   [Backend]:         Failed to register protocol with OS.
[2201:0515/224049.495747:ERROR:browser_main_loop.cc(269)] Gtk: gtk_widget_add_accelerator: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed
[2201:0515/224049.495816:ERROR:browser_main_loop.cc(269)] Gtk: gtk_widget_add_accelerator: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed
[2201:0515/224049.495870:ERROR:browser_main_loop.cc(269)] Gtk: gtk_widget_add_accelerator: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed
(22:40:52) INFO:    [DXVKInstaller]:   Updating vkd3d to: vkd3d-proton-2.6
Update for version 2.3.0 is not available (latest version: 2.3.0, downgrade is disallowed).
(22:40:55) INFO:    [DXVKInstaller]:   downloaded vkd3d
(22:40:55) INFO:    [DXVKInstaller]:   extracting vkd3d
(22:40:55) ERROR:   [DXVKInstaller]:   Extraction of vkd3d failed with: Error: Command failed: tar -I zstd -xvf /home/syeedahmed/.config/heroic/tools/vkd3d/vkd3d-proton-2.6.tar.zst -C /home/syeedahmed/.config/heroic/tools/vkd3d
tar (child): zstd: Cannot exec: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now

(22:40:55) INFO:    [Frontend]:        Refreshing wine downloader releases
(22:40:55) INFO:    [WineDownloader]:  Updating wine versions info
(22:40:55) INFO:    [WineDownloader]:  Fetching upstream information...
(22:40:59) INFO:    [WineDownloader]:  wine versions updated


@flavioislima this one is working... yes.. thanx man

**Comment by syeedahmed** [comment]
@flavioislima and one more thing... not that important. but in wine manager can you change the inactive or non-selected sector font color black tor white or something more light color?

**Comment by flavioislima** [comment]
@syeedahmed yes this was an error with the class names aftet relese. Was fixed already

**Comment by flavioislima** [comment]
Ok, just released the new version so we can close this issue.
Will take some time until the update appears on flatpak though.
