### ISSUE TITLE
[Linux] Game that use wine/proton will no longer start under 2.3.0

### ISSUE THREAD

**Issue by deeply-cynical** [Heroic-Games-Launcher/HeroicGamesLauncher#1309]
### Describe the bug

Games that require wine/proton won't run with wine prefixes created with previous Heroic versions.

Have to delete wine prefix and have Heroic recreate it. Annoying if said game requires a bunch of winetricks fixes you can't remember.

### Add logs

Launch Command: STEAM_COMPAT_CLIENT_INSTALL_PATH=/home/tom/.steam/steam STEAM_COMPAT_DATA_PATH=/games/Heroic/++Prefixes++/DEMONS-TILT /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary launch b8b37813c5634dbdac61d88ff411135c --no-wine --wrapper "''/home/tom/.steam/steam/steamapps/common/Proton 7.0/proton'' run"

System Info:

  Heroic Version: 2.3.0 Brook
  Legendary Version:  0.20.25 Our Benefactors
  OS: Arch KERNEL: 5.17.7-arch1-1 ARCH: x64
  CPU: AMD Ryzen 7 5800X 8-Core Processor @3.8 GOVERNOR: schedutil
  RAM: Total: 31.32 GiB Available: 28 GiB
  GRAPHICS: GPU0: Navi 22 [Radeon RX 6700/6700 XT/6750 XT / 6800M] VRAM: 1MB DRIVER:  
  PROTOCOL: x11
  

Game Settings: {
	"checkUpdatesInterval": 10,
	"enableUpdates": false,
	"addDesktopShortcuts": false,
	"addStartMenuShortcuts": false,
	"autoInstallDxvk": true,
	"autoInstallVkd3d": true,
	"checkForUpdatesOnStartup": true,
	"customWinePaths": [],
	"defaultInstallPath": "/games/Heroic",
	"defaultWinePrefix": "/games/Heroic/++Prefixes++",
	"language": "en",
	"maxWorkers": 0,
	"minimizeOnLaunch": false,
	"nvidiaPrime": false,
	"otherOptions": "",
	"showUnrealMarket": false,
	"showFps": false,
	"useGameMode": false,
	"userInfo": {
		"epicId": "77b221f2974d4d1eb55b3d54931c752b",
		"name": "tom"
	},
	"wineCrossoverBottle": "Heroic",
	"winePrefix": "/games/Heroic/++Prefixes++/DEMONS-TILT",
	"wineVersion": {
		"bin": "'/home/tom/.steam/steam/steamapps/common/Proton 7.0/proton'",
		"name": "Proton - Proton 7.0",
		"type": "proton"
	},
	"altLegendaryBin": "",
	"altGogdlBin": "",
	"darkTrayIcon": false,
	"disableController": false,
	"egsLinkedPath": "",
	"maxRecentGames": 5
}

Error Log:
[cli] INFO: Logging in...
[Core] INFO: Trying to re-use existing login session...
[cli] INFO: Checking for updates...
[Core] INFO: Getting authentication token...
[cli] INFO: Launching b8b37813c5634dbdac61d88ff411135c...
Traceback (most recent call last):
  File "legendary/cli.py", line 3004, in <module>
  File "legendary/cli.py", line 2919, in main
  File "legendary/cli.py", line 685, in launch_game
  File "subprocess.py", line 858, in __init__
  File "subprocess.py", line 1704, in _execute_child
FileNotFoundError: [Errno 2] No such file or directory: '/home/tom/.steam/steam/steamapps/common/Proton'
[4645] Failed to execute script 'cli' due to unhandled exception!

### Steps to reproduce

1. Go to 'game'
2. Click on play now'
3. See error

### Expected behavior

Game will start

### System Information

- OS Arch Linux + KDE Plasma, X11 session 
- Heroic Version [e. g. 2.3.0}

**Comment by flavioislima** [comment]
Might be that the settings didnt updated. 
Go to the game settings and select another version of wine/proton and then get back to this one.

**Comment by deeply-cynical** [comment]
That seems to work, a bit annoying do go through my entire library and change them (hope I don't lose any gamesaves)
Rebel Galaxy refuses to start as It says it needs to update when it's already the latest version, a legendary issue possibly. Heroic used to give an option to skip the update, that dialogue box no longer appears.

**Comment by jrDev95** [comment]
Hello all,

it looks like the issue also happends with GOG games. I tried old games and indie like Ignition and Superhexagon with the same message

`Error Log:

Traceback (most recent call last):

  File "gogdl/cli.py", line 44, in <module>

  File "gogdl/cli.py", line 40, in main

File "gogdl/launch.py", line 78, in launch

  File "subprocess.py", line 951, in __init__

  File "subprocess.py", line 1821, in _execute_child

OSError: [Errno 8] Exec format error: '/home/jrd/Games/Heroic/Ignition/DOSBOX/DOSBox.exe'

[655] Failed to execute script 'cli' due to unhandled exception!

Game Log:

Launch command: ['/home/jrd/Games/Heroic/Ignition/DOSBOX/DOSBox.exe', '-conf', '..\\dosbox_igni.conf', '-conf', '..\\dosbox_igni_single.conf', '-noconsole', '-c', 'exit']`

Ask me if you need more details for help

Regards!
