### ISSUE TITLE
Double left mouse click on the Windows system tray icon for opening it

### ISSUE THREAD

**Issue by tkoeck** [Heroic-Games-Launcher/HeroicGamesLauncher#1310]
### Problem description

It's a really nice game launcher.

I was just wondering why I need to left-click on the system tray icon and the press show to show the game launcher window. 

### Feature description

Game launcher default is just double left-click on the game launcher to open it. It is at least for Steam, GoG Galaxy and Epic Game launcher.

Can you please add that feature?

**Comment by arielj** [comment]
This is a duplicate of https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/issues/1036
