### ISSUE TITLE
Flatpak 2.3.0 won't install from Epic

### ISSUE THREAD

**Issue by LiamDawe** [Heroic-Games-Launcher/HeroicGamesLauncher#1312]
### Describe the bug

I'm trying out 2.3.0, logged in with Epic Games and tried to install Rocket League.

It instantly finishes, doing nothing, with no obvious error.

### Add logs

[liam@fedora ~]$ flatpak run com.heroicgameslauncher.hgl
[3:0515/122424.595658:ERROR:bus.cc(397)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[3:0515/122424.595699:ERROR:bus.cc(397)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
(12:24:24) DEBUG:   [Legendary]:       Running Legendary command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary --version
hostname: invalid option -- 'f'
Try 'hostname --help' for more information.
(12:24:24) INFO:    [Legendary]:       Legendary location: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary
(12:24:24) INFO:    [Gog]:             GOGDL location: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl
(12:24:24) INFO:    [Backend]:         
  Heroic Version: 2.3.0 Brook
  Legendary Version:  0.20.25 Our Benefactors
  OS: Freedesktop.org KERNEL: 5.17.6-300.fc36.x86_64 ARCH: x64
  CPU: AMD Ryzen 7 5800X 8-Core Processor @3.8 GOVERNOR: schedutil
  RAM: Total: 31.29 GiB Available: 24.35 GiB
  GRAPHICS: GPU0: TU102 [GeForce RTX 2080 Ti Rev. A]  VRAM: 32MB DRIVER:  
  PROTOCOL: x11
  
APPIMAGE env is not defined, current application is not an AppImage
LaunchProcess: failed to execvp:
xdg-settings
(12:24:24) ERROR:   [Backend]:         Failed to register protocol with OS.
[3:0515/122424.967499:ERROR:browser_main_loop.cc(269)] Gtk: gtk_widget_add_accelerator: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed
[3:0515/122424.967533:ERROR:browser_main_loop.cc(269)] Gtk: gtk_widget_add_accelerator: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed
[3:0515/122424.967557:ERROR:browser_main_loop.cc(269)] Gtk: gtk_widget_add_accelerator: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed
(12:24:25) INFO:    [Frontend]:        Refreshing Library
(12:24:25) INFO:    [Legendary]:       Refreshing library...
(12:24:25) INFO:    [Legendary]:       Refreshing Epic Games...
(12:24:25) INFO:    [Legendary]:       Refreshing Epic Games...
(node:138) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 setGameStatus listeners added to [EventEmitter]. Use emitter.setMaxListeners() to increase limit
(Use `exe --trace-warnings ...` to show where the warning was created)
(12:24:25) DEBUG:   [Legendary]:       Running Legendary command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary list
(12:24:26) INFO:    [Legendary]:       Updating game list
(12:24:26) INFO:    [Legendary]:       Game List Updated
(12:24:26) INFO:    [Legendary]:       Checking for game updates: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary list-installed --check-updates --tsv
(12:24:26) DEBUG:   [Legendary]:       Running Legendary command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary list-installed --check-updates --tsv
(12:24:27) INFO:    [Legendary]:       Found 0 game(s) to update
(12:24:27) INFO:    [Gog]:             Found 0 game(s) to update
(12:24:30) DEBUG:   [Legendary]:       Using cached install info
(12:24:31) DEBUG:   [Legendary]:       Using cached install info
(12:24:31) DEBUG:   [Legendary]:       Using cached install info
(12:24:33) DEBUG:   [Legendary]:       Using cached install info
(12:24:34) DEBUG:   [Legendary]:       Using cached install info
(12:24:34) INFO:    [Legendary]:       Installing Sugar with: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary install Sugar --platform Windows --base-path /home/liam/Games/Heroic --skip-dlcs --skip-sdl -y
(12:24:34) DEBUG:   [Legendary]:       Running Legendary command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary install Sugar --platform Windows --base-path /home/liam/Games/Heroic --skip-dlcs --skip-sdl -y
(12:24:34) DEBUG:   [Legendary]:       Logging to file "/home/liam/.var/app/com.heroicgameslauncher.hgl/config/heroic/GamesConfig/Sugar.log"
(12:24:35) INFO:    [Backend]:         finished installing
(12:24:35) INFO:    [Frontend]:        Refreshing Library
(12:24:35) INFO:    [Legendary]:       Refreshing library...
(12:24:35) INFO:    [Legendary]:       Updating game list
(12:24:35) INFO:    [Legendary]:       Game List Updated
(12:24:35) DEBUG:   [Legendary]:       Using cached install info
(12:24:35) DEBUG:   [Legendary]:       Using cached install info

### Steps to reproduce

Try a fresh Flatpak install, try to download something.

### Expected behavior

It actually downloads

### System Information

Fedora 36
Flatpak

**Comment by flavioislima** [comment]
It was working fine on the beta 3?

**Comment by LiamDawe** [comment]
I was using AppImage previously and that was fine.

Testing the AppImage now of 2.3.0 and seeing the same issue.

**Comment by CommandMC** [comment]
Could you attach the install log (`/home/liam/.var/app/com.heroicgameslauncher.hgl/config/heroic/GamesConfig/Sugar.log`)?

**Comment by flavioislima** [comment]
Ok, so I will try to revert some changes we had on 2.3.0 and I will send you an AppImage to test.

**Comment by LiamDawe** [comment]
[Sugar.log](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/files/8694855/Sugar.log)

**Comment by CommandMC** [comment]
```
Installation requirements check returned the following results:
 ! Failure: Not enough available disk space! 10493.23 MiB < 22789.62 MiB
 ```
Welp, there we go

**Comment by LiamDawe** [comment]
Hrmm, thinks I don't have enough disk space, let me look into that lol

**Comment by LiamDawe** [comment]
Oh wow, this is totally a "me" issue. Had a crap-load of logs that had suddenly built up from other stuff, so it's not actually a Heroic issue.

Still, should I open up a separate feature request to have accurate error on file space left, since you're clearly able to detect it...

**Comment by flavioislima** [comment]
yes, this used to work before so I don't know why is not working.
We have an issue for that already, will reopen it.

**Comment by CommandMC** [comment]
> Since you're clearly able to detect it...

Well, Legendary can detect it, yes. It would be nice if we'd do it as well, but before you even click the Install button.
I believe we had a handler for this before (that displayed an error message if the specific string "Not enough available disk space" was found), but I think ever since the launch refactor we're not calling it anymore

**Comment by flavioislima** [comment]
Ok so we can close this one and I reopened #967 to fix the no spacing issues.
