### ISSUE TITLE
[Mac OS] Auto update fails

### ISSUE THREAD

**Issue by CoolDog22YT** [Heroic-Games-Launcher/HeroicGamesLauncher#1316]
### Describe the bug

The auto update alert pops up but when i click update it fails

### Add logs

(15:51:24) DEBUG:   [Legendary]:       Running Legendary command: /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/legendary --version
(15:51:28) INFO:    [Legendary]:       Legendary location: /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/legendary
(15:51:28) INFO:    [Gog]:             GOGDL location: /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/gogdl
(15:51:28) INFO:    [Backend]:         
  Heroic Version: 2.3.0 Brook
  Legendary Version:  0.20.25 Our Benefactors
  OS: macOS KERNEL: 21.4.0 ARCH: x64
  CPU: Intel Core™ i3-1000NG4 @1.1 
  RAM: Total: 8 GiB Available: 5.69 GiB
  GRAPHICS: GPU0: Intel Iris Plus Graphics VRAM: 1536MB DRIVER:  
  
  
(15:51:28) WARNING: [Backend]:         Protocol already registered.
(15:52:54) ERROR:   [Error: ZIP file not provided: [
  {
    "url": "https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/releases/download/v2.3.1/Heroic-2.3.1.dmg",
    "info": {
      "url": "Heroic-2.3.1.dmg",
      "sha512": "O+c64HxF6lYYkGcO4Oi5pxSwm97UMjfZyvHcfZ2t44fjhyOB5vCoy+35vaHKrf7zIyiKB5C9Wol1aFgDM0cfHw==",
      "size": 140124312
    }
  }
]]: failed to update
(15:52:54) INFO:    [Frontend]:        Refreshing Library
(15:52:54) INFO:    [Legendary]:       Refreshing library...
(15:52:54) INFO:    [Legendary]:       Refreshing Epic Games...
(15:52:54) INFO:    [Legendary]:       Refreshing Epic Games...
(15:52:55) DEBUG:   [Legendary]:       Running Legendary command: /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/legendary list
(15:53:04) INFO:    [Legendary]:       Updating game list
(15:53:04) INFO:    [Legendary]:       Game List Updated
(15:53:04) INFO:    [Legendary]:       Checking for game updates: /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/legendary list-installed --check-updates --tsv
(15:53:04) DEBUG:   [Legendary]:       Running Legendary command: /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/legendary list-installed --check-updates --tsv
(15:53:13) INFO:    [Legendary]:       Found 0 game(s) to update
(15:53:13) INFO:    [Gog]:             Found 0 game(s) to update

### Steps to reproduce

1. Go to 'Heroic and open it'
2. Click on 'the update pop up'
3. Scroll down to 'update'

### Expected behavior

The app should update itself.

### Screenshots

https://user-images.githubusercontent.com/29024047/168491457-41781125-890b-4cc4-8b74-0e2325dc77f3.mov

### System Information

- OS : MacOs 12.3.1
- Heroic Version [2.3.0]:

**Comment by CoolDog22YT** [comment]
here is the log file 
[heroic-2022-05-15T19_51_24.363Z.log](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/files/8695888/heroic-2022-05-15T19_51_24.363Z.log)

**Comment by flavioislima** [comment]
Hmm, the only platform I didn't test this feature.
Should be easy to fix though. We just need to generate a zip instead of dmg package.

**Comment by flavioislima** [comment]
On Electron-Updater docs:
`Note: Your application must be signed for automatic updates on macOS. This is a requirement of Squirrel.Mac.` :(

**Comment by flavioislima** [comment]
So I investigated this deeper and did some tests with a certificate that I generated in Xcode and doesn't work. Only by paying apple, we could get the certificate and unfortunately, we cannot do that. 

So I will just remove the info about auto-update on mac from the website.

**Comment by CoolDog22YT** [comment]
okay

**Comment by Aces-and-Jacks** [comment]
I don't think this is the case still, if I read it right. If this is about MacOS getting updates, I got the recent update automatically just now. So that means auto update on mac is supported?

**Comment by flavioislima** [comment]
> I don't think this is the case still, if I read it right. If this is about MacOS getting updates, I got the recent update automatically just now. So that means auto update on mac is supported?

Yes, we got a certificate from Apple so heroic auto updates now just fine.
