### ISSUE TITLE
Ability to remove games from the list of recently played

### ISSUE THREAD

**Issue by arielj** [Heroic-Games-Launcher/HeroicGamesLauncher#1319]
### Problem description

Recently played games are handled as first in => first out. The problem is that, if you stop playing a game and you don't want it in the list of recently played, the only way to get it out is to start other games until that game is removed from the list.

### Feature description

I imagine an option in the context menu only when right clicking an element in the Recently Played list that allows the user to remove the game from that list.

### Alternatives

Edit the json file that stores this information manually.

**Comment by mattpnolan** [comment]
+1 - Found this ticket via Google when looking for this option in Heroic
