### ISSUE TITLE
[Deb] Unable to update heroic games launcher

### ISSUE THREAD

**Issue by llars0689** [Heroic-Games-Launcher/HeroicGamesLauncher#1322]
I am unable to update the heroic games launcher... I am running Pop_OS 22.04. 

I ran sudo apt update, which prompted there was 1 update for heroic. I tried running sudo apt upgrade, but once its tries to update heroic, it fails... I get the following:

Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following packages will be upgraded:
  heroic
1 to upgrade, 0 to newly install, 0 to remove and 0 not to upgrade.
Need to get 96.3 MB of archives.
After this operation, 173 kB of additional disk space will be used.
Get:1 https://sourceforge.net/projects/madlinux/files/repo core/main amd64 heroic amd64 2.3.1 [96.3 MB]
Err:1 https://sourceforge.net/projects/madlinux/files/repo core/main amd64 heroic amd64 2.3.1
  File has unexpected size (91979776 != 96334160). Mirror sync in progress? [IP: 45.67.159.245 443]
  Hashes of expected file:
   - SHA256:194ec613248c8f09081c6210a59dccf0759c8692878e901bd7af7ec1921a2bac
   - SHA1:7578f047b01c321ecb6541ce20d39e5da23af297 [weak]
   - MD5Sum:bdd361a7387abfae9cd326dfa8fa7a3b [weak]
   - Filesize:96334160 [weak]
E: Failed to fetch https://jztkft.dl.sourceforge.net/project/madlinux/repo/pool/main/h/heroic/heroic_2.3.1_amd64.deb  File has unexpected size (91979776 != 96334160). Mirror sync in progress? [IP: 45.67.159.245 443]
   Hashes of expected file:
    - SHA256:194ec613248c8f09081c6210a59dccf0759c8692878e901bd7af7ec1921a2bac
    - SHA1:7578f047b01c321ecb6541ce20d39e5da23af297 [weak]
    - MD5Sum:bdd361a7387abfae9cd326dfa8fa7a3b [weak]
    - Filesize:96334160 [weak]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?

I tried running it with --fix-missing, but no luck. 

Any ideas why im getting this error?

Thanks,
Luke

**Comment by flavioislima** [comment]
@rauldipeas can you give some light on this one? 🙂

**Comment by rauldipeas** [comment]
This is a temporary issue, take a look at _Mirror sync in progress?_ info.

Just try again later.

**Comment by flavioislima** [comment]
@llars0689 fixed?

**Comment by llars0689** [comment]
@flavioislima Yes its all working now!

Thank you!
