### ISSUE TITLE
[Linux] Missing tray icon

### ISSUE THREAD

**Issue by baduhai** [Heroic-Games-Launcher/HeroicGamesLauncher#1323]
### Describe the bug

Tray icon is empty.

### Add logs

(12:53:39) DEBUG:   [Legendary]:       Running Legendary command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary --version
(12:53:40) INFO:    [Legendary]:       Legendary location: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary
(12:53:40) INFO:    [Gog]:             GOGDL location: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl
(12:53:40) INFO:    [Backend]:         
  Heroic Version: 2.3.1 Brook
  Legendary Version:  0.20.25 Our Benefactors
  OS: Freedesktop.org KERNEL: 5.17.7-zen1-1-zen ARCH: x64
  CPU: AMD Ryzen 5 3600 6-Core Processor @3.6 GOVERNOR: schedutil
  RAM: Total: 15.61 GiB Available: 11.37 GiB
  GRAPHICS: GPU0: Device 73df VRAM: 1MB DRIVER:  
  PROTOCOL: wayland
  
(12:53:40) INFO:    [Gog]:             Getting data about the user
(12:53:40) ERROR:   [Backend]:         Failed to register protocol with OS.
(12:53:40) INFO:    [Gog]:             Saved user data to config
(12:53:41) INFO:    [Frontend]:        Refreshing Library
(12:53:41) INFO:    [Legendary]:       Refreshing library...
(12:53:41) INFO:    [Gog]:             Getting GOG library
(12:53:41) INFO:    [Legendary]:       Refreshing Epic Games...
(12:53:41) INFO:    [Legendary]:       Refreshing Epic Games...
(12:53:41) INFO:    [Gog]:             Number of library pages: 1
(12:53:41) INFO:    [Gog]:             Saved games data
(12:53:41) DEBUG:   [Legendary]:       Running Legendary command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary list
(12:53:42) INFO:    [Legendary]:       Updating game list
(12:53:42) INFO:    [Legendary]:       Game List Updated
(12:53:43) INFO:    [Legendary]:       Checking for game updates: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary list-installed --check-updates --tsv
(12:53:43) DEBUG:   [Legendary]:       Running Legendary command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary list-installed --check-updates --tsv
(12:53:44) INFO:    [Legendary]:       Found 0 game(s) to update
(12:53:44) INFO:    [Gog]:             Found 0 game(s) to update
(12:53:47) ERROR:   [Legendary]:       Error Getting Info from Epic API
(12:53:47) INFO:    [Legendary]:       Getting more details with 'legendary info'
(12:53:48) DEBUG:   [Legendary]:       Running Legendary command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary --pretty-json info Carp --platform Windows --json

### Steps to reproduce

1. Open heroic
2. See that icon is empty

### Expected behavior

Tray icon should be there.

### Screenshots

![Screenshot_20220516_124821](https://user-images.githubusercontent.com/31864305/168576891-f09fcfd1-ca49-414b-99b2-351e421554a8.png)

### System Information

- Arch Linux
- Heroic v2.3.1 from Flathub
- Plasma 5.24.5 (Wayland)

**Comment by flavioislima** [comment]
Can you try going to settings and changing the tray icon color? I cannot reproduce the issue on X11.

**Comment by baduhai** [comment]
Changing tray icon colour has no effect. Neither on Wayland nor on X11.

**Comment by flavioislima** [comment]
@baduhai check if you have DBUS permissions on flatseal, if yes remove them.
Also might be fixed already on the latest release.

reopen the issue in case it doesnt.
