### ISSUE TITLE
The description of the "Installed" icon and the "List View" icon are incorrect.

### ISSUE THREAD

**Issue by pupilo-py** [Heroic-Games-Launcher/HeroicGamesLauncher#1325]
### Describe the bug

![heroic](https://user-images.githubusercontent.com/58078395/168600131-4aed7a12-e1c6-4bdf-8e4a-55fd59d6e837.png)
![heroic2](https://user-images.githubusercontent.com/58078395/168604595-010da467-297a-4faf-96a9-d4f043dd5abc.png)

### Add logs

No need

### Steps to reproduce

No need

### Expected behavior

No need

### System Information

- OS [e. g. "Kubuntu"]: 
- Heroic Version [e. g. 2.3.1]:

**Comment by arielj** [comment]
I imagine the translation is incorrect, you can help following this link https://hosted.weblate.org/languages/ and review the different translations for portuguese.

**Comment by pupilo-py** [comment]
> I imagine the translation is incorrect, you can help following this link https://hosted.weblate.org/languages/ and review the different translations for portuguese.

Thank you!

**Comment by pupilo-py** [comment]
After I signed up it worked

**Comment by pupilo-py** [comment]
Thank you guys. Now that I know how to contribute, I will always do it!

**Comment by flavioislima** [comment]
> Thank you guys. Now that I know how to contribute, I will always do it!

Thanks for fixing that 😁
