### ISSUE TITLE
[Linux] Option to skip game update missing since 2.3.0 update (includes 2.3.1 hotfix)

### ISSUE THREAD

**Issue by deeply-cynical** [Heroic-Games-Launcher/HeroicGamesLauncher#1327]
### Describe the bug

I try to launch Rebel Galaxy, there's a bug where it keeps saying there's an update even though it's on the latest version. 
On the version of Heroic prior to 2.3.0 a dialogue window appeared asking whether I wanted to run the game without updating, that dialogue window no longer appears as of 2.3.0 and 2.3.1hotfix therefore I cannot start the game. nor is there any option in the settings to ignore game updates.

### Add logs

Launch Command: STEAM_COMPAT_CLIENT_INSTALL_PATH=/home/tom/.steam/steam STEAM_COMPAT_DATA_PATH=/games/Heroic/++Prefixes++/Rebel-Galaxy /usr/bin/mangohud --dlsym /usr/bin/gamemoderun /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary launch Weaver --no-wine --wrapper "'/home/tom/.steam/steam/steamapps/common/Proton 7.0/proton' run"

System Info:

  Heroic Version: 2.3.1 Brook
  Legendary Version:  0.20.25 Our Benefactors
  OS: Arch KERNEL: 5.17.7-arch1-1 ARCH: x64
  CPU: AMD Ryzen 7 5800X 8-Core Processor @3.8 GOVERNOR: schedutil
  RAM: Total: 31.32 GiB Available: 28.6 GiB
  GRAPHICS: GPU0: Navi 22 [Radeon RX 6700/6700 XT/6750 XT / 6800M] VRAM: 1MB DRIVER:  
  PROTOCOL: x11
  

Game Settings: {
	"autoInstallDxvk": true,
	"autoInstallVkd3d": false,
	"maxSharpness": 2,
	"launcherArgs": "",
	"nvidiaPrime": false,
	"otherOptions": "",
	"savesPath": "",
	"showFps": false,
	"showMangohud": true,
	"targetExe": "",
	"useGameMode": true,
	"wineCrossoverBottle": "Heroic",
	"winePrefix": "/games/Heroic/++Prefixes++/Rebel-Galaxy",
	"wineVersion": {
		"bin": "/home/tom/.steam/steam/steamapps/common/Proton 7.0/proton",
		"name": "Proton - Proton 7.0",
		"type": "proton"
	},
	"useSteamRuntime": false
}

Error Log:
gamemodeauto:
[cli] INFO: Logging in...
[Core] INFO: Trying to re-use existing login session...
[cli] INFO: Checking for updates...
[cli] ERROR: Game is out of date, please update or launch with update check skipping!

### Steps to reproduce

1. Go to Rebel galaxy - says Update available
2. click update - says update complete
3. then says update available again
4. Click Play Game
5. Game attempts to run but refuses due to game being out of date.

### Expected behavior

Start "Out of Date" game
Window with option to skip update should appear.

### System Information

- OS Arch Linux, KDE, X11 session
- Heroic Version 2.3.1

**Comment by flavioislima** [comment]
can you try:

1. Cleaning Heroic cache and then restarting Heroic?
2. If that doesn't work, run: `/opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary update Weaver` on a terminal to see if it will update the game?

I have a few games that gave updates on my library but could not reproduce this error so its hard to know how to debug it.

can you also check Heroic log?

**Comment by deeply-cynical** [comment]
Thanks for responding so fast.

1.  Cleaning Heroic cache and restarting didn't work.
2. Running the command said the following 

> [:cli] INFO: Download size is 0, the game is either already up to date or has not changed. Exiting...

Results unchanged


Heroic Log :

> (19:15:10) DEBUG:   [Legendary]:       Running Legendary command: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary --version
> (19:15:10) INFO:    [Legendary]:       Legendary location: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary
> (19:15:10) INFO:    [Gog]:             GOGDL location: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl
> (19:15:10) INFO:    [Backend]:         
>   Heroic Version: 2.3.1 Brook
>   Legendary Version:  0.20.25 Our Benefactors
>   OS: Arch KERNEL: 5.17.7-arch1-1 ARCH: x64
>   CPU: AMD Ryzen 7 5800X 8-Core Processor @3.8 GOVERNOR: schedutil
>   RAM: Total: 31.32 GiB Available: 28.13 GiB
>   GRAPHICS: GPU0: Navi 22 [Radeon RX 6700/6700 XT/6750 XT / 6800M] VRAM: 1MB DRIVER:  
>   PROTOCOL: x11
>   
> (19:15:10) INFO:    [Gog]:             Getting data about the user
> (19:15:10) WARNING: [Backend]:         Protocol already registered.
> (19:15:10) INFO:    [Gog]:             Saved user data to config
> (19:15:11) INFO:    [Frontend]:        Refreshing Library
> (19:15:11) INFO:    [Legendary]:       Refreshing library...
> (19:15:11) INFO:    [Gog]:             Getting GOG library
> (19:15:11) INFO:    [Legendary]:       Refreshing Epic Games...
> (19:15:11) INFO:    [Legendary]:       Refreshing Epic Games...
> (19:15:11) INFO:    [Gog]:             Number of library pages: 1
> (19:15:11) INFO:    [Gog]:             Saved games data
> (19:15:11) DEBUG:   [Legendary]:       Running Legendary command: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary list
> (19:15:12) INFO:    [Legendary]:       Updating game list
> (19:15:12) INFO:    [Legendary]:       Game List Updated
> (19:15:12) INFO:    [Legendary]:       Checking for game updates: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary list-installed --check-updates --tsv
> (19:15:12) DEBUG:   [Legendary]:       Running Legendary command: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary list-installed --check-updates --tsv
> (19:15:13) DEBUG:   [Legendary]:       Using cached install info
> (19:15:13) INFO:    [Legendary]:       Found 1 game(s) to update
> (19:15:14) INFO:    [Gog]:             Found 0 game(s) to update
> (19:15:14) DEBUG:   [Legendary]:       Using cached install info
> (19:15:16) DEBUG:   [Legendary]:       Using cached install info
> (19:15:16) INFO:    [Backend]:         Launching Rebel Galaxy (Weaver)
> (19:15:16) DEBUG:   [Legendary]:       Running Wine command: /usr/bin/wine wineboot --init
> (19:15:20) DEBUG:   [Legendary]:       Ran Wine command: /usr/bin/wine wineboot --init
> (19:15:20) INFO:    [DXVKInstaller]:   installing dxvk on... /home/tom/.wine
> (19:15:27) INFO:    [DXVKInstaller]:   dxvk installed on /home/tom/.wine
> (19:15:27) INFO:    [Legendary]:       Launching Rebel Galaxy: WINEPREFIX=/home/tom/.wine /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary launch Weaver --wine /usr/bin/wine --wine-prefix /home/tom/.wine
> (19:15:27) DEBUG:   [Legendary]:       Running Legendary command: WINEPREFIX=/home/tom/.wine /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary launch Weaver --wine /usr/bin/wine --wine-prefix /home/tom/.wine
> (19:15:27) DEBUG:   [Legendary]:       Running Legendary command: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary --version
> (19:15:28) INFO:    [Backend]:         Log was written to /home/tom/.config/heroic/GamesConfig/Weaver-lastPlay.log
> (19:15:28) INFO:    [Frontend]:        Refreshing Library
> (19:15:28) INFO:    [Legendary]:       Refreshing library...
> (19:15:28) INFO:    [Gog]:             Getting GOG library
> (19:15:28) INFO:    [Legendary]:       Updating game list
> (19:15:28) INFO:    [Legendary]:       Game List Updated
> (19:15:28) DEBUG:   [Legendary]:       Using cached install info
> (19:15:28) INFO:    [Gog]:             Number of library pages: 1
> (19:15:28) INFO:    [Gog]:             Saved games data
> (19:15:28) DEBUG:   [Legendary]:       Using cached install info


I assume that the option to skip the update is still showing for your games that aren't up to date?

**Comment by deeply-cynical** [comment]
Fixed for 2.3.2
