### ISSUE TITLE
HeroicAppImage is running (doing nothing) but doesn't show any window

### ISSUE THREAD

**Issue by RafaelLinux** [Heroic-Games-Launcher/HeroicGamesLauncher#1328]
### Describe the bug

I tried to launch from desktop environment, but apparently nothing happened. However, I can see in system monitor there is the Heroic Appimage running and 7 "heroic" threads as childs of "Dolphin" (from I launched Heroic.Appimage)
If I launch the AppImage from terminal, only Heroic AppImage appears running, but not showing any window.

This is the output

```
> ./Heroic.AppImage
(20:43:32) DEBUG:   [Legendary]:       Running Legendary command: /tmp/.mount_HeroicrZpYKf/resources/app.asar.unpacked/build/bin/linux/legendary --version
(node:4923) UnhandledPromiseRejectionWarning: TypeError: Cannot read properties of undefined (reading 'replaceAll')
    at getLegendaryVersion (/tmp/.mount_HeroicrZpYKf/resources/app.asar/build/utils.js:141:9)
    at async getSystemInfo (/tmp/.mount_HeroicrZpYKf/resources/app.asar/build/utils.js:203:30)
    at async /tmp/.mount_HeroicrZpYKf/resources/app.asar/build/main.js:229:28
(Use `heroic --trace-warnings ...` to show where the warning was created)
(node:4923) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
[4958:0516/204333.072082:ERROR:vaapi_wrapper.cc(1136)] vaQuerySurfaceAttributes failed, VA error: invalid parameter
[4958:0516/204333.072218:ERROR:vaapi_wrapper.cc(1083)] FillProfileInfo_Locked failed for va_profile VAProfileH264Main and entrypoint VAEntrypointVLD
[4958:0516/204333.072284:ERROR:vaapi_wrapper.cc(1136)] vaQuerySurfaceAttributes failed, VA error: invalid parameter
[4958:0516/204333.072406:ERROR:vaapi_wrapper.cc(1083)] FillProfileInfo_Locked failed for va_profile VAProfileH264High and entrypoint VAEntrypointVLD
[4958:0516/204333.098085:ERROR:gpu_memory_buffer_support_x11.cc(44)] dri3 extension not supported.

```

### Add logs

No possible, no window available

### Steps to reproduce

1. Launch "Heroic.AppImage"
2. Nothing happens
3. See error (from terminal)

### Expected behavior

Heroic window should appear 

### System Information

Heroic Version: 2.3.1
Operating System: openSUSE Tumbleweed 20220415
KDE Plasma Version: 5.24.4
KDE Frameworks Version: 5.93.0
Qt Version: 5.15.2
Kernel Version: 5.17.2-1-default (64-bit)
Graphics Platform: X11
Processors: 4 × Intel® Core™ i5-6600K CPU @ 3.50GHz
Memory: 31.3 GiB of RAM
Graphics Processor: NVIDIA GeForce GTX 1050 Ti/PCIe/SSE2

### Additional information

I had no issues with many other AppImages I usually use.

**Comment by flavioislima** [comment]
Since this is tumbleweed and we had issues in the past, check this issue here: https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/issues/310

Might be glibc as well. Hard to know.

**Comment by flavioislima** [comment]
Also, try the flatpak, should work better open Suse.

**Comment by RafaelLinux** [comment]
Thank you. Unfortunately, I choose AppImages , cause have a great advantage over Flatpak: I can share in a remote folder ;)

I'll wait some version of Heroic in the future that works "out the box".
Best regards

**Comment by Oaklight** [comment]
> Since this is tumbleweed and we had issues in the past, check this issue here: #310
> 
> Might be glibc as well. Hard to know.

Is there chance to release binary rely on lower level glibc? for instance glibc_2.28? My linux distribution so far only support up to glibc 2.28. And 2.31 will be next year when the underlying move to debian11.

**Comment by Nocccer** [comment]
> > Since this is tumbleweed and we had issues in the past, check this issue here: #310
> > Might be glibc as well. Hard to know.
> 
> Is there chance to release binary rely on lower level glibc? for instance glibc_2.28? My linux distribution so far only support up to glibc 2.28. And 2.31 will be next year when the underlying move to debian11.

No. Your only option would be to fork heroic and build one rely on older glib. Actually having such an old glib is not really good for gaming.

**Comment by Oaklight** [comment]
I see. Then what should I change to leverage the provided commands to compile against glibc 2.28? Which file/config should I change?
```bash
yarn

yarn dist:linux {package to create} (eg: deb, pacman, tar.xz, rpm, AppImage)
```

**Comment by Nocccer** [comment]
@Oaklight i think the glibc comes from electron. I don't know if the electron builder takes your system glibc.
Btw did you tried heroic flatpak? I think flatpak ships there own glibc and dependencies libs.

**Comment by RafaelLinux** [comment]
I can use Flatpak, but unfortunately works "its way", and doesn't show my real home folder, but a "virtual" folder with ".local" and another folder. I think gave up of using Flatpak time ago, preferring AppImage.

**Comment by Oaklight** [comment]
> 

I did a little dig on this and realized that glibc is a dependency of Legendary, not electron. To resolve the legendary issue, I chose to install its pip package: `pip install legendary-gl[webview]`. And specify the legendary path in Heroic settings to that of `which legendary`. Please be aware that there are issues related to versions of python in the Legendary repository. I didn't encounter that because I have a conda env manager running for daily use, which bypasses the python 3 that comes with the OS.

**Comment by Oaklight** [comment]
I installed Heroic using the deb, but the principle of AppImage hacking is the same @RafaelLinux.
Here is what I did:
1. find out the default legendary location by running the heroic binary/AppImage in terminal and check the logging: `/opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary`
2. `sudo mv /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary_original`
3. `which legendary`: `/home/me/mambaforge/bin/legendary`
4. create symbolic link to the default location: `sudo ln -s /home/me/mambaforge/bin/legendary /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary`

You could also do it more elegantly:
1. find out the config file of Heroic: mine is at `.config/heroic/config.json`
2. update this `"altLegendaryBin": "<your legendary location>",`
