### ISSUE TITLE
[Linux] Wine not found error when launching a game

### ISSUE THREAD

**Issue by PS-Professional** [Heroic-Games-Launcher/HeroicGamesLauncher#1329]
### Describe the bug

Hi there.
I'm trying to install and run games I have in my Epic games library but they won't launch.
How can I Fixe them?

### Add logs

Error Log:

[cli] INFO: Logging in...

[Core] INFO: Trying to re-use existing login session...

[cli] INFO: Checking for updates...

[Core] INFO: Getting authentication token...

[cli] INFO: Launching a26f991a5e6c4e9c9572fc200cbea47f...

Traceback (most recent call last):

  File "legendary/cli.py", line 3004, in <module>

  File "legendary/cli.py", line 2919, in main

  File "legendary/cli.py", line 685, in launch_game

  File "subprocess.py", line 858, in __init__

  File "subprocess.py", line 1704, in _execute_child

FileNotFoundError: [Errno 2] No such file or directory: "'/usr/bin/wine'"

[69646] Failed to execute script 'cli' due to unhandled exception!

### Steps to reproduce

1. Go to 'Library'
2. Click on the desired game.
3. Click on 'Play Now'
4. See the error.

### Expected behavior

Launching game after clicking on 'Play Now' button

### System Information

- OS: Ubuntu 22.04.04
- Heroic Version: 2.3.1

**Comment by DmitruMoth** [comment]
Same problem in arch linux, i think the problem is in use " and ': `"'/usr/bin/wine'"`

**Comment by flavioislima** [comment]
Try changing the wine version and getting back to the other one.

**Comment by PS-Professional** [comment]
> Try changing the wine version and getting back to the other one.

It was working before I reinstalled my OS.

**Comment by DmitruMoth** [comment]
There is a bug in new version: i tried appimages of 2 versions: there is no bug in old version. Wine is installed. 

17 мая 2022 г. 07:16:41 GMT+03:00, Parsa Shadab ***@***.***> пишет:

**Comment by PS-Professional** [comment]
> Yes, we are looking into that. We have changed the way we read the config so this workaround is needed for now: Game Settings > Wine > Select another wine version (if doesn't show just install another one using wine manager) > get back to the other one.

I will try that.
I also noticed when I try to modify the prefix given to game, I experience FPS drop.
How can I fix that?

**Comment by flavioislima** [comment]
If you are looking FPS it is because the new prefix doesn't have DXVK or VKD3D installed, or that wine version is not the best for that game. You can have more help on that on our discord.

**Comment by flavioislima** [comment]
Wrote a wiki page with a how to fix the Wine not Found error: https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/wiki/Troubleshooting#wine-not-found-error-when-launching

So I expect this help other.

**Comment by PS-Professional** [comment]
Tnx
