### ISSUE TITLE
Save - Sync menu not showing

### ISSUE THREAD

**Issue by PaaBliiTo** [Heroic-Games-Launcher/HeroicGamesLauncher#1332]
### Describe the bug

I don't have the Save - Sync menu in my games which makes it so that I cannot sync my saves on Epic's cloud, either in upload or download.
Tried this with 5 different games and not working for any of them.

### Steps to reproduce

1. Install Heroic
2. Download game
3. No Save - Sync menu

### Expected behavior

Games should have the Sync - Save menu for the cloud sync to work

### Screenshots

![Screenshot_20220517_203604](https://user-images.githubusercontent.com/23000106/168886791-1f06d7dd-7034-46ff-98bc-6248f9f3b2d1.png)

### System Information

Steam Deck

### Additional information

N/A

**Comment by flavioislima** [comment]
Are you 100% sure those games have Sync Saves support from epic?
Which games are? Send a screenshot of the game page that shows that the game has cloud sync support.
Testing here and game slime Outer Worlds and Control are working fine.
