### ISSUE TITLE
Set LD_LIBRARY_PATH when launching a "portable" wine installation

### ISSUE THREAD

**Issue by aleasto** [Heroic-Games-Launcher/HeroicGamesLauncher#1334]
The launcher looks for user installed wine from, for example, lutris.
These bundle their shared libraries in $runner/lib[64] and they should be preferred over system ones, since some might be missing from the system. This is especially true when using this launcher as a Flatpak.

You could do the same as lutris and add a 'Prefer system libraries' option, off by default, or more simply force the use of the bundled libraries.

**Comment by flavioislima** [comment]
I see. 
That's news to me but maybe because I am using a distro with several libs for gaming already installed. 
Thanks for the tip 👍🏽
