### ISSUE TITLE
Support for gamescope

### ISSUE THREAD

**Issue by wyrthoxir** [Heroic-Games-Launcher/HeroicGamesLauncher#1338]
### Feature description

It would be useful if HGL could have integrated support for the gamescope compositor. There are some gamers who utilize higher resolutions on their Wayland-based desktop environments / window managers in combination with scaling for UI legibility. With Wine currently relying on XWayland, scaling means that games will only detect resolutions based on the results of the scaling. E.g. a 4k display running at native resolution with 2x scaling applied would have a maximum resolution of 1080p.

**Comment by Kirottu** [comment]
I would greatly enjoy gamescope support too.

**Comment by Nocccer** [comment]
You can use gamescope by adding it to the wrapper option of heroic-2.4.0beta2.
Would be good if someone can try that out and report back if it works. Maybe we can implement it in a future release.

**Comment by Doomsdayrs** [comment]
For flatpak, simple append 
`:/app/utils/gamescope/bin` to the PATH deceleration and you can use gamescope.

**Comment by AXL1994** [comment]
@Nocccer I'm sorry to posting this one year later. I tested some games with gamescope wrapper and it works perfectly, as showed by many users on Heroic's Discord. It would be useful to have a GUI to set up easily.
On the "Other" category of the settings there could be a check-box to turn on and off gamescope, and a gear to open up a windows to set up  gamescope easily, like Bottles or Lutris do. It would be so useful for old games and Steam Deck users!

![gamescope](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/assets/49454228/5868422c-55dc-40c7-bb60-f2305f437256)

![lutris](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/assets/49454228/e62ccad4-ce8d-465c-baf0-7ad8342aea76)

**Comment by YaroST12** [comment]
basically, it stopped working as a wrapper. Both flatpak and system (/usr/bin/) versions.

https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/issues/2911
