### ISSUE TITLE
Allow separated folders for GOG or any new launchers that heroic going to support in the future

### ISSUE THREAD

**Issue by bluesaka111** [Heroic-Games-Launcher/HeroicGamesLauncher#1342]
### Feature description

Allow separate between game folders installation and wine-prefixes installation folders similar to Epic games (which Heroic launcher already have).

It is easier to recreate wine-prefix without reinstall or moving game files around (out of wine-prefix folder and move it back in once the prefix is recreated).
Save spaces on devices with SSD + HDD setup.

**Comment by flavioislima** [comment]
You already can have separate folders for installation you just need to select it when installing the game.
I guess adding one option for each store will be confusing, it is better if the user picks up the correct folder/drive.
