### ISSUE TITLE
MangoHud not Working on Heroic (Flatpak).

### ISSUE THREAD

**Issue by paparoxo360** [Heroic-Games-Launcher/HeroicGamesLauncher#1343]
### Describe the bug

When I enable Mangohud on Heroic (flatpak version), the game doesn't launch, I've tried both Mangohud version from the PPA and the github release? Thanks, amazing software btw.

### Add logs

Heroic log:
TypeError - convertToStringArray(...).join is not a function

### Steps to reproduce

1. Go to Settings
2. Go to Other
3. Click on Enable Mangohud
4. Press Play Now

### Expected behavior

MangoHud working on game after press Play Now.

### System Information

- OS : Ubuntu Mate 20.04
- Heroic Version : 2.3.2

**Comment by imLinguin** [comment]
When using Flatpak version of Heroic, you also have to use flatpak version of mangohud.
 `flatpak install org.freedesktop.Platform.VulkanLayer.MangoHud`

**Comment by paparoxo360** [comment]
> When using Flatpak version of Heroic, you also have to use flatpak version of mangohud. `flatpak install org.freedesktop.Platform.VulkanLayer.MangoHud`

Thank you very much, it worked. I was sad that I couldn't see my hardware info on Heroic while gaming, but now everything is ok, thanks again!

**Comment by flavioislima** [comment]
Will add that to the wiki
