### ISSUE TITLE
Library is empty

### ISSUE THREAD

**Issue by reyaz006** [Heroic-Games-Launcher/HeroicGamesLauncher#1348]
### Describe the bug

At some point I'm no longer seeing anything in Library. Only the "Unreal - Everything" section which is also empty.

I can't check with the original EGS launcher at this time due to login issue with their application.

### Add logs

(22:43:33) DEBUG:   [Legendary]:       Running Legendary command: C:\Windows\Temp\29O5ZzBHbig2f4UKMmqWk7jxiV6\resources\app.asar.unpacked\build\bin\win32\legendary --version
(22:43:37) INFO:    [Legendary]:       Legendary location: C:\Windows\Temp\29O5ZzBHbig2f4UKMmqWk7jxiV6\resources\app.asar.unpacked\build\bin\win32\legendary
(22:43:37) INFO:    [Gog]:             GOGDL location: C:\Windows\Temp\29O5ZzBHbig2f4UKMmqWk7jxiV6\resources\app.asar.unpacked\build\bin\win32\gogdl
(22:43:37) INFO:    [Backend]:         
  Heroic Version: 2.3.2 Brook
  Legendary Version:  0.20.25 Our Benefactors
  OS: Windows 8.1  KERNEL: 6.3.9600 ARCH: x64
  CPU: Intel
  RAM: Total: * GiB Available: * GiB
  GRAPHICS: GPU0: *
  
  
(22:43:38) WARNING: [Backend]:         Protocol already registered.
(22:43:39) INFO:    [Frontend]:        Refreshing Library
(22:43:39) INFO:    [Legendary]:       Refreshing library...
(22:43:39) INFO:    [Legendary]:       Refreshing Epic Games...
(22:43:40) DEBUG:   [Legendary]:       Running Legendary command: C:\Windows\Temp\29O5ZzBHbig2f4UKMmqWk7jxiV6\resources\app.asar.unpacked\build\bin\win32\legendary list
(22:43:45) INFO:    [Legendary]:       Updating game list
(22:43:45) INFO:    [Legendary]:       Game List Updated
(22:43:46) INFO:    [Legendary]:       Checking for game updates: C:\Windows\Temp\29O5ZzBHbig2f4UKMmqWk7jxiV6\resources\app.asar.unpacked\build\bin\win32\legendary list-installed --check-updates --tsv
(22:43:46) DEBUG:   [Legendary]:       Running Legendary command: C:\Windows\Temp\29O5ZzBHbig2f4UKMmqWk7jxiV6\resources\app.asar.unpacked\build\bin\win32\legendary list-installed --check-updates --tsv
(22:43:47) INFO:    [Legendary]:       Found 0 game(s) to update
(22:43:47) INFO:    [Gog]:             Found 0 game(s) to update
(22:43:51) DEBUG:   [Legendary]:       Running Legendary command: C:\Windows\Temp\29O5ZzBHbig2f4UKMmqWk7jxiV6\resources\app.asar.unpacked\build\bin\win32\legendary --version
(22:43:51) DEBUG:   [Gog]:             Running GOGDL command: C:\Windows\Temp\29O5ZzBHbig2f4UKMmqWk7jxiV6\resources\app.asar.unpacked\build\bin\win32\gogdl --version

### Steps to reproduce

1. Have a library of games.
2. One day discover the library is empty.

### Expected behavior

The library should not be empty.

### System Information

- OS [e. g. "Ubuntu"]: Windows 8.1 x64
- Heroic Version [e. g. 2.1.1]: 2.3.2

**Comment by flavioislima** [comment]
Check the wiki on the troubleshooting section the list of folders heroic has its config and rename or delete then and try again.
Probability your credentials has expired or the app is stuck in some filter that we removed at some point and heroic can't change it.

**Comment by reyaz006** [comment]
That worked, thanks.

**Comment by bshor** [comment]
I get the same error under Arch Linux. Only "unreal everything" and no games in it or anywhere. I have an Epic Games account. I tried to delete both ~/.config/legendary and ~/.config/heroic but no luck.

**Comment by pooriaPoorsarvi** [comment]
I saw the same problem on the steam deck and no game is being listed from the epic library, is there any solutions?

**Comment by caseyrmcn** [comment]
I believe I found a temporary solution to this issue. For some reason even when told not to show unreal assets in the launcher that's what is being shown by default. I had completely uninstalled Heroic along with deleting config folders to no avail. Unfortuently it's not even giving the user the option to look at the epic library by default. By signing into GOG the library submenu populates and your able to then load your epic library whether or not you own anything on GOG I would assume. 

Testing and found on Steam deck with Flatpak
