### ISSUE TITLE
"Sandbox" user directory

### ISSUE THREAD

**Issue by ChaosMelone9** [Heroic-Games-Launcher/HeroicGamesLauncher#1349]
### Problem description

Currently all wine prefixes map their Documents, Downloads, etc. to the users home directory ones. Depending on the game this can result in unnecessary clutter being piled up in the Documents folder. 

### Feature description

There should be two options.
First, not to link these folders and have them isolated in their respective prefixes.

And second, grant the user the ability to choose a "sanbox"-directory themselves, similarly to the way lutris does this.

### Additional information

Wine does this remapping by using symlinks. Manually changing them for each prefix works and is persistent. It should be fairly easy to just check if these links point to the wanted directory and if not remake them.

**Comment by flavioislima** [comment]
You can use winetricks to make the prefix sandboxed.

**Comment by ChaosMelone9** [comment]
Thank you, I found the option.
