### ISSUE TITLE
Heroic won't launch after forcing to quit with full storage

### ISSUE THREAD

**Issue by ShimonHoranek** [Heroic-Games-Launcher/HeroicGamesLauncher#1350]
### Describe the bug

I was downloading a game and downloading an update of my system at once. The system update had filled my storage completely and all apps including Heroic stopped responding. The game was being downloaded to a different drive. Before I realized that the storage was full, I ran `killall heroic`. I then cleaned the storage and tried to launch Heroic, bu only white is now displayed. I have rebooted the computer multiple times and even reinstalled Heroic, nothing works. 

#### This happens when I launch it now
(14:10:27) DEBUG:   [Legendary]:       Running Legendary command: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary --version
(14:10:29) INFO:    [Legendary]:       Legendary location: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary
(14:10:29) INFO:    [Gog]:             GOGDL location: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl
(14:10:29) INFO:    [Backend]:         
  Heroic Version: 2.3.2 Brook
  Legendary Version:  0.20.25 Our Benefactors
  OS: Arch KERNEL: 5.17.8-arch1-1 ARCH: x64
  CPU: AMD Phenom(tm) II X6 1055T Processor @1.71 GOVERNOR: schedutil
  RAM: Total: 15.62 GiB Available: 14.18 GiB
  GRAPHICS: GPU0: AMD Radeon RX 560 Series VRAM: 4096MB DRIVER:  
  PROTOCOL: x11

  
(14:10:29) INFO:    [Gog]:             Getting data about the user
(14:10:30) INFO:    [Gog]:             Saved user data to config

### Steps to reproduce

1. Fill your disk while downloading a game
2. kill Heroic
3. Clean the disk

### Screenshots

![Screenshot from 2022-05-21 14-22-30](https://user-images.githubusercontent.com/55536438/169651375-9146bfa8-ffa3-4b86-b15e-12d4bca4d39d.png)

### System Information

- OS Archlinux Linux 5.17.8-arch1-1 x86_64
- Heroic v 2.3.0 (I later updated but nothing changed)

**Comment by ShimonHoranek** [comment]
This issue seems to have disappeared with 2.3.4-1

**Comment by flavioislima** [comment]
Great! :)
