### ISSUE TITLE
Add ways to edit start command

### ISSUE THREAD

**Issue by Jark5455** [Heroic-Games-Launcher/HeroicGamesLauncher#1351]
### Problem description

In certain games, there are long cinematics before the game launches, certain games also allow for the cinematic to be skipped by adding an argument to the start command such as "-nostartupmovies" or "-nostartupvideo"

### Feature description

I would like ot be able to edit the command that runs the game and add custom arguments to the command

**Comment by imLinguin** [comment]
You can already do that in Game settings > Other.

![obraz](https://user-images.githubusercontent.com/62100117/169657369-ed9f654f-1eec-4c2c-9a0c-e4037f779591.png)

**Comment by Jark5455** [comment]
oh Im stupid lmao
