### ISSUE TITLE
Check and use .steam path for Steam Linux Runtime

### ISSUE THREAD

**Issue by redromnon** [Heroic-Games-Launcher/HeroicGamesLauncher#1353]
### Describe the bug

By default, Heroic uses the `.local/share/Steam` path for the Steam Linux runtime. But Ubuntu-based distros like Pop_OS don't use symlink to the `.local/share/Steam` directory and may not even have the Steam dir in local. 
This makes the Steam Runtime feature unusable for such users as the Steam runtimes are only included under `.steam` despite enabling Steam Runtime.

### Add logs

```shell
Launch Command: /usr/local/bin/mangohud --dlsym /usr/games/gamemoderun /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl launch /home/redromnon/Games/Heroic/OpenTTD 1293297882 --platform linux
```

### Steps to reproduce

1. Go to any game
2. Click Settings
3. Click Other
4. Enable Steam Runtime

### Expected behavior

Heroic should include the Steam runtime in the launch command.

### Screenshots

None

### System Information

- OS : Pop_OS 22.04 
- Heroic Version : 2.3.3

### Additional information

Implement a check and use the suitable or available path (`.local/share/Steam` or `.steam`) for Steam Runtime.

**Comment by CommandMC** [comment]
I've now created #1359 to change the path to `~/.steam/root/...`.  
I've tested it in a PopOS VM and it seems to work, could you give it a go yourself?

**Comment by redromnon** [comment]
I can confirm that it's working.

**Comment by redromnon** [comment]
Will permanently setting the Steam Rumtime path to `~/steam/root/...` and not `~/.local/share/Steam/...`?

**Comment by CommandMC** [comment]
I think it's the more compatible option, from what I've seen, that's generally what other scripts involving Steam use as well
