### ISSUE TITLE
[Linux] Launching Heroic shows grey background and nothing else happens

### ISSUE THREAD

**Issue by marzeq** [Heroic-Games-Launcher/HeroicGamesLauncher#1354]
### Describe the bug

When I open Heroic, it just shows a grey background.

### Add logs

```log
2503:0522/114829.425825:ERROR:object_proxy.cc(623)] Failed to call method: org.freedesktop.DBus.Properties.Get: object_path= /org/freedesktop/portal/desktop: org.freedesktop.DBus.Error.InvalidArgs: No such interface “org.freedesktop.portal.FileChooser”
[2503:0522/114829.425850:ERROR:select_file_dialog_linux_portal.cc(242)] Failed to read portal version property
(11:48:29) DEBUG:   [Legendary]:       Running Legendary command: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary --version
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
[2532:0522/114829.467937:ERROR:sandbox_linux.cc(377)] InitializeSandbox() called with multiple threads in process gpu-process.
/bin/sh: line 1: hostname: command not found
(11:48:29) INFO:    [Legendary]:       Legendary location: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary
(11:48:29) INFO:    [Gog]:             GOGDL location: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl
(11:48:29) INFO:    [Backend]:
  Heroic Version: 2.3.3 Brook
  Legendary Version:  0.20.25 Our Benefactors
  OS: Arch KERNEL: 5.17.9-arch1-1 ARCH: x64
  CPU: AMD Ryzen 5 5600G with Radeon Graphics @2.86 GOVERNOR: schedutil
  RAM: Total: 27.37 GiB Available: 25.8 GiB
  GRAPHICS: GPU0: Cezanne VRAM: 512MB DRIVER:
  PROTOCOL: wayland

APPIMAGE env is not defined, current application is not an AppImage
(11:48:29) WARNING: [Backend]:         Protocol already registered.
[2503:0522/114829.979205:ERROR:browser_main_loop.cc(269)] Gtk: gtk_widget_add_accelerator: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed
[2503:0522/114829.979247:ERROR:browser_main_loop.cc(269)] Gtk: gtk_widget_add_accelerator: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed
[2503:0522/114829.979274:ERROR:browser_main_loop.cc(269)] Gtk: gtk_widget_add_accelerator: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed
[2532:0522/114834.113318:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 1 times!
[2532:0522/114911.839186:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 2 times!
[2532:0522/114914.080668:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 3 times!
```

### Steps to reproduce

1. Launch Heroic either from the menu system or from the command line
2. The UI does not display

### Expected behavior

The UI would actually display.

### Screenshots

![unknown](https://user-images.githubusercontent.com/58303665/169689552-0b1d1369-9b99-496a-b3ce-b23047000dd5.png)

### System Information

- OS: Arch
- Heroic Version: 2.3.3
- I'm on Wayland

**Comment by thekingoflorda** [comment]
I have the same issue, I am on steamdeck and this problem appeared when I updated to the new version.

**Comment by vicesmilexd** [comment]
I have the same issue :/

**Comment by marzeq** [comment]
Followup: I tried the AUR version and the AppImage and both don't work. Strangely enough, **Flatpak does work**.

**Comment by flavioislima** [comment]
Searching for the error I could find this post on reddit. can you try it?
https://www.reddit.com/r/flatpak/comments/t8wpx3/filechooser_will_not_work/

**Comment by thekingoflorda** [comment]
> Followup: I tried **the AUR version** and the **AppImage** and both **don't work**. Strangely enough, **Flatpak does work**.

I am using the flatpack, it doesn’t work for me.

**Comment by marzeq** [comment]
> Searching for the error I could find this post on reddit. can you try it? [reddit.com/r/flatpak/comments/t8wpx3/filechooser_will_not_work](https://www.reddit.com/r/flatpak/comments/t8wpx3/filechooser_will_not_work/)

I'm pretty sure that error has nothing to do with it. It's gone now that I followed the instructions, but I still get a grey background and nothing else.

**Comment by marzeq** [comment]
{

**Comment by marzeq** [comment]
Accidentally closed, sorry!

**Comment by marzeq** [comment]
If it helps in any way, these are the logs of the Flatpak version that works:

```
[3:0523/131309.611516:ERROR:bus.cc(397)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[3:0523/131309.611563:ERROR:bus.cc(397)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
(13:13:09) DEBUG:   [Legendary]:       Running Legendary command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary --version
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
[41:0523/131309.685588:ERROR:sandbox_linux.cc(377)] InitializeSandbox() called with multiple threads in process gpu-process.
hostname: invalid option -- 'f'
Try 'hostname --help' for more information.
(13:13:09) INFO:    [Legendary]:       Legendary location: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary
(13:13:09) INFO:    [Gog]:             GOGDL location: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl
(13:13:09) INFO:    [Backend]:
  Heroic Version: 2.3.3 Brook
  Legendary Version:  0.20.25 Our Benefactors
  OS: Freedesktop.org KERNEL: 5.17.9-arch1-1 ARCH: x64
  CPU: AMD Ryzen 5 5600G with Radeon Graphics @2.85 GOVERNOR: schedutil
  RAM: Total: 27.37 GiB Available: 25.86 GiB
  GRAPHICS: GPU0: Device 1638 VRAM: 512MB DRIVER:
  PROTOCOL: wayland

APPIMAGE env is not defined, current application is not an AppImage
LaunchProcess: failed to execvp:
xdg-settings
(13:13:10) ERROR:   [Backend]:         Failed to register protocol with OS.
[3:0523/131310.013640:ERROR:browser_main_loop.cc(269)] Gtk: gtk_widget_add_accelerator: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed
[3:0523/131310.013692:ERROR:browser_main_loop.cc(269)] Gtk: gtk_widget_add_accelerator: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed
[3:0523/131310.013729:ERROR:browser_main_loop.cc(269)] Gtk: gtk_widget_add_accelerator: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed
(13:13:10) INFO:    [Frontend]:        Refreshing Library
(13:13:10) INFO:    [Legendary]:       Refreshing library...
(13:13:10) INFO:    [Legendary]:       Refreshing Epic Games...
(node:164) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 setGameStatus listeners added to [EventEmitter]. Use emitter.setMaxListeners() to increase limit
(Use `exe --trace-warnings ...` to show where the warning was created)
(13:13:11) DEBUG:   [Legendary]:       Running Legendary command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary list
(13:13:12) INFO:    [Legendary]:       Updating game list
(13:13:12) INFO:    [Legendary]:       Game List Updated
(13:13:12) INFO:    [Legendary]:       Checking for game updates: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary list-installed --check-updates --tsv
(13:13:12) DEBUG:   [Legendary]:       Running Legendary command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary list-installed --check-updates --tsv
[41:0523/131312.724757:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 1 times!
(13:13:13) INFO:    [Legendary]:       Found 0 game(s) to update
(13:13:13) INFO:    [Gog]:             Found 0 game(s) to update
[41:0523/131314.149913:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 2 times!
```

**Comment by flavioislima** [comment]
> > Searching for the error I could find this post on reddit. can you try it? [reddit.com/r/flatpak/comments/t8wpx3/filechooser_will_not_work](https://www.reddit.com/r/flatpak/comments/t8wpx3/filechooser_will_not_work/)
> 
> I'm pretty sure that error has nothing to do with it. It's gone now that I followed the instructions, but I still get a grey background and nothing else.

OK. Can you see if you have a tray icon, then righ click > debug. See if you get any error on the console.

**Comment by marzeq** [comment]
> > > Searching for the error I could find this post on reddit. can you try it? [reddit.com/r/flatpak/comments/t8wpx3/filechooser_will_not_work](https://www.reddit.com/r/flatpak/comments/t8wpx3/filechooser_will_not_work/)
> > 
> > 
> > I'm pretty sure that error has nothing to do with it. It's gone now that I followed the instructions, but I still get a grey background and nothing else.
> 
> OK. Can you see if you have a tray icon, then righ click > debug. See if you get any error on the console.

![unknown](https://user-images.githubusercontent.com/58303665/169808690-82edc254-bc4e-44fe-a16b-85cb5d6772d3.png)

```log
TypeError: Cannot read properties of null (reading 'is_game')
    at index.tsx:151:48
    at Array.filter (<anonymous>)
    at index.tsx:151:26
    at index.tsx:199:9
    at Object.useMemo (react-dom.production.min.js:172:115)
    at t.useMemo (react.production.min.js:23:113)
    at Pi (index.tsx:190:25)
    at si (react-dom.production.min.js:157:137)
    at $s (react-dom.production.min.js:267:460)
    at Ll (react-dom.production.min.js:250:347)

react-dom.production.min.js:216 TypeError: Cannot read properties of null (reading 'app_name')
    at index.tsx:211:54
    at Array.filter (<anonymous>)
    at index.tsx:210:25
    at Object.useMemo (react-dom.production.min.js:172:115)
    at t.useMemo (react.production.min.js:23:113)
    at Pi (index.tsx:190:25)
    at si (react-dom.production.min.js:157:137)
    at $s (react-dom.production.min.js:267:460)
    at Ll (react-dom.production.min.js:250:347)
    at Pl (react-dom.production.min.js:250:278)
cs @ react-dom.production.min.js:216

scheduler.production.min.js:12 Uncaught TypeError: Cannot read properties of null (reading 'app_name')
    at index.tsx:211:54
    at Array.filter (<anonymous>)
    at index.tsx:210:25
    at Object.useMemo (react-dom.production.min.js:172:115)
    at t.useMemo (react.production.min.js:23:113)
    at Pi (index.tsx:190:25)
    at si (react-dom.production.min.js:157:137)
    at $s (react-dom.production.min.js:267:460)
    at Ll (react-dom.production.min.js:250:347)
    at Pl (react-dom.production.min.js:250:278)
```

**Comment by gazhay** [comment]
Cross-posting as this seems to be the same issue [#1347 ]

**Comment by flavioislima** [comment]
Looking at the logs it seems that the frontend is not getting the game list correctly and its breaking.
I will try to fix that and deal with those errors.

**Comment by flavioislima** [comment]
@marzeq are you already logged in? this happened after a upgrade?
What was the last heroic version working?

**Comment by marzeq** [comment]
> @marzeq are you already logged in? this happened after a upgrade? What was the last heroic version working?

I was logged in, but unfortunately I do not know if this happended after an update, but if it did, it must've been either 2.3.0, 2.3.1 or 2.3.2.

**Comment by flavioislima** [comment]
ok, try this appimage:
https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/actions/runs/2373435028

**Comment by flavioislima** [comment]
@gazhay try this appimage as well to see if it will fix it.

**Comment by marzeq** [comment]
Turns out in my quest to fix this issue myself I tried a clean install of heroic because it kept stuff in `~/.config`, and as it turns out that fixed it, and now even I cannot replicate the issue... That pretty much explains it why Flatpak worked but the AppImage didn't. Well sorry that I kind of messed up your debugging, let's hope @gazhay can still replicate it.

**Comment by flavioislima** [comment]
No problem.
I have two theories:
- The library files or caching were corrupted
- The credentials expired

So I just added an error message in case Heroic cant find any game.
In theory, if no game was found HEroic should redirect to Login, but it seems this is not happening right now.

But good that you fixed the issue then. Lets see if others can test the fix.

**Comment by gazhay** [comment]
I still get the same error, blank screen and errors in the console.

I can wipe out .config to fix it, or I can keep it if you want to debug any further.

**Comment by flavioislima** [comment]
@gazhay so with that appImage you still see the same errors on the console when using the debug? or you mean same errors on the console?

**Comment by flavioislima** [comment]
Ok, try this other one once its finished:
https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/actions/runs/2373757758
