### ISSUE TITLE
Request: ability to launch other than default game executable for running benchmark tool executables inside game folder

### ISSUE THREAD

**Issue by oscarbg** [Heroic-Games-Launcher/HeroicGamesLauncher#136]
Hi,
first thanks for your work.. with Heroic was able to run Crysis Remastered on Linux..
for reference only required setting "winetricks mfc140" for solving a mfc140u.dll error.. at least running on a custom Wine Tkg 6.1 staging build..
Crysis remastered ships with a Benchmark_GPU.bat and Benchmark_CPU.bat in Bin64 but running this can be solved by setting as custom launch arguments:
-DEVMODE +map island +exec benchmark_gpu
for example..
but also Crysis Remastered ships with a simple GUI Benchmark.exe tool that allows selecting resolution, quality and map and then  upon start benchmark button maybe passing custom arguments or writing some cfg file and launches game's executable: "CrysisRemastered.exe"
but running Benchmark.exe tool from command line via wine (not using Heroic Launcher) will fail launching game for same reason as if I launch "CrysisRemastered.exe" outside Heroic Launcher fails..

**Describe the solution you'd like**

I would like, like the addition of the ability to support custom launch program arguments, support for selecting a custom program executable (instead of default) inside games folder for games that ship with a separate Benchmark tool/GUI executable..
Also may be useful for games that ship 32bit and 64 binaries to select which architecture to run..

**Describe alternatives you've considered**
no solution without Heroic launcher assistance..

**Comment by flavioislima** [comment]
Hi!

I'm not sure if this is possible right now. I could make it but it would not use Legendary to run, so if the game needs authentication through the Epic games it wouldn't work. I think this could be a good feature to ask for the Legendary team to implement.

In the future I have plans to add games outside Epic, so it will work like Lutris and other launchers.

**Comment by flavioislima** [comment]
Closing this one since this is something that legendary does not support. If they change this, we can open a new feature request.
