### ISSUE TITLE
heroic not opening m1 mac monterey version 2.3.3

### ISSUE THREAD

**Issue by akilan200** [Heroic-Games-Launcher/HeroicGamesLauncher#1360]
### Describe the bug

heroic not opening m1 mac monterey version 2.3.3

### Add logs

ii

### Steps to reproduce

1. Go to 'app
2. itshows blank blue page

### Expected behavior

showsblank screen

### Screenshots

<img width="1212" alt="Screenshot 2022-05-23 at 1 28 29 PM" src="https://user-images.githubusercontent.com/106062145/169772080-81a06af0-a0d7-4641-891b-09555d5943ee.png">
<img width="1212" alt="Screenshot 2022-05-23 at 1 28 29 PM" src="https://user-images.githubusercontent.com/106062145/169772126-1c53406c-f064-45e5-9f0e-8324617516a3.png">

### System Information

- OS monterey
- Heroic Version :2.3.3

**Comment by flavioislima** [comment]
probably same as #1354 
try this macos build when finished:
https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/actions/runs/2373435025

**Comment by akilan200** [comment]
THANK YOU SO MUCH

**Comment by akilan200** [comment]
CAN YOU PLEASE HELP ME WITH THIS https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/issues/1380#issue-1250565010
