### ISSUE TITLE
Add ability to launch from CLI silently and with Legendary aliases

### ISSUE THREAD

**Issue by rkr87** [Heroic-Games-Launcher/HeroicGamesLauncher#1368]
### Problem description

The Heroic Launcher UI appears when launching games via Steam. 

I need to identify a game's Epic app ID to launch via CLI.

### Feature description

Add a command line argument to launch games silently (IE without invoking the HGL UI).
EG;
flatpak run com.heroicgameslauncher.hgl heroic://launch/CrabEA?**silent=true**

Add the ability to launch via CLI using Legendary aliases rather than the app ID.
EG;
flatpak run com.heroicgameslauncher.hgl heroic://launch/**satisfactory**

instead of;
flatpak run com.heroicgameslauncher.hgl heroic://launch/**CrabEA**

### Additional information

The Epic Games Launcher has the ability to launch silently;
-com.epicgames.launcher://apps/CrabEA?action=launch&**silent=true**

Legendary already has the ability to launch via aliases;
legendary launch satisfactory

**Comment by outphase** [comment]
This is addressed by [Heroic Bash Launcher](https://github.com/redromnon/HeroicBashLauncher).

**Comment by CommandMC** [comment]
Silently launching is already possible with f10051fb4355d75be71d0b242250e516fd84915b
Launching with Aliases instead of AppNames is not something I'd say is necessary

**Comment by flavioislima** [comment]
Yes, this was already implemented.
