### ISSUE TITLE
[SteamDeck] Winecfg/winetricks does not open [v2.3.3]

### ISSUE THREAD

**Issue by Random90** [Heroic-Games-Launcher/HeroicGamesLauncher#1373]
### Describe the bug

If i want to change settings in winecfg, after pushing the button, nothing happens. Seems that there are no logs.
Same with winetricks. Nothing happens. The log says something like: "Check if winetricks available or check (Path to wine-prefix-path). "Ive checked the path.

### Add logs

(14:48:46) DEBUG:   [Legendary]:       Running Legendary command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary --version
(14:48:47) INFO:    [Legendary]:       Legendary location: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary
(14:48:47) INFO:    [Gog]:             GOGDL location: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl
(14:48:47) INFO:    [Backend]:         
  Heroic Version: 2.3.3 Brook
  Legendary Version:  0.20.25 Our Benefactors
  OS: Freedesktop.org KERNEL: 5.13.0-valve14-1-neptune-02195-g5b0f749d00fa ARCH: x64
  CPU: AMD Custom APU 0405 @1.83 GOVERNOR: schedutil
  RAM: Total: 14.49 GiB Available: 12.54 GiB
  GRAPHICS: GPU0: Device 163f VRAM: 512MB DRIVER:  
  PROTOCOL: x11
 
(14:48:47) INFO:    [Backend]:         User Not Found, removing it from Store
(14:48:47) INFO:    [Gog]:             Getting data about the user
(14:48:47) INFO:    [Gog]:             Refreshing access_token
(14:48:47) ERROR:   [Backend]:         Failed to register protocol with OS.
(14:48:48) INFO:    [Gog]:             Token refreshed successfully
(14:48:49) INFO:    [Frontend]:        Refreshing Library
(14:48:49) INFO:    [Legendary]:       Refreshing library...
(14:48:49) INFO:    [Gog]:             Getting GOG library
(14:48:49) INFO:    [Gog]:             Saved user data to config
(14:48:49) INFO:    [Gog]:             Number of library pages: 1
(14:48:49) INFO:    [Gog]:             Saved games data
(14:48:49) INFO:    [Frontend]:        No cache found, getting data from legendary...
(14:48:49) INFO:    [Legendary]:       Refreshing library...
(14:48:50) INFO:    [Gog]:             Found 0 game(s) to update
(14:49:02) INFO:    [Backend]:         trying to run WINEPREFIX='/home/deck/Games/Heroic/Prefixes/Pro Pinball - Big Race USA/pfx' WINE='/home/deck/.steam/steam/steamapps/common/Proton 7.0/dist/bin/wine64' /home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/tools/winetricks -q
(14:49:03) ERROR:   Error: Command failed: WINEPREFIX='/home/deck/Games/Heroic/Prefixes/Pro Pinball - Big Race USA/pfx' WINE='/home/deck/.steam/steam/steamapps/common/Proton 7.0/dist/bin/wine64' /home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/tools/winetricks -q
 
(14:49:03) ERROR:   [Backend]:         Something went wrong! Check if WineTricks is available and /home/deck/.steam/steam/steamapps/common/Proton 7.0/dist/bin/wine64 exists
(14:49:04) INFO:    [Backend]:         trying to run WINEPREFIX='/home/deck/Games/Heroic/Prefixes/Pro Pinball - Big Race USA/pfx' WINE='/home/deck/.steam/steam/steamapps/common/Proton 7.0/dist/bin/wine64' /home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/tools/winetricks -q
(14:49:05) ERROR:   Error: Command failed: WINEPREFIX='/home/deck/Games/Heroic/Prefixes/Pro Pinball - Big Race USA/pfx' WINE='/home/deck/.steam/steam/steamapps/common/Proton 7.0/dist/bin/wine64' /home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/tools/winetricks -q
 
(14:49:05) ERROR:   [Backend]:         Something went wrong! Check if WineTricks is available and /home/deck/.steam/steam/steamapps/common/Proton 7.0/dist/bin/wine64 exists

### Steps to reproduce

1. I've installed Heroic Games Launcher from Discovery on Steam Deck
2. Setup GOG Account
3. Download a Game (Big Race USA Pro Pinball)\
4. Click on the winecfg button

### Expected behavior

Winecfg and winetricks window opens.

### System Information

- Steam Deck
- Heroic Version 2.3.3

**Comment by flavioislima** [comment]
Winetricks is downloaded to `/home/user/.var/app/com.heroicgameslauncher.hgl/config/heroic/tools/winetricks`
can you check if it is in there?

I cannot see on the logs the issue with `winecfg`

**Comment by flavioislima** [comment]
can you try with other proton and wine versions?

That winetricks warning is normal since you are not passing WINEPREFIX and WINE I guess

**Comment by KillerFry** [comment]
I have a similar problem since 2.3.3

No matter the version of Wine that I select (tried Proton 7.0, Proton Experimental, Wine-GE-Proton-7-11, Wine-lutris-wine-7.2, GE-Proton7-15 to 7-18). Clicking the winecfg just highlights the button blue but nothing happens. The winetricks button sometimes works, or sometimes just remains highlighted blue.

(This is on a Steam Deck running on the beta branch).

**Comment by outphase** [comment]
I was only able to get winetricks to work when using a Wine-Proton-GE downloaded from HGL. It didn't appear to work on any Steam-provided Proton or GE-Proton via ProtonUp.

**Comment by XC3N** [comment]
I get the same behaviour on 2.4.0

**Comment by flavioislima** [comment]
It is working just fine on 2.4.3 now, both proton and wine:
![image](https://user-images.githubusercontent.com/26871415/193253487-8f08515c-63d4-4f9b-8d82-768205b2b883.png)
