### ISSUE TITLE
Detect when a game is missing and suggest the user a fix

### ISSUE THREAD

**Issue by arielj** [Heroic-Games-Launcher/HeroicGamesLauncher#1374]
### Problem description

There are cases where Heroic will think a game is installed when it actually isn't:
- you delete the game's folder manually (not sure why would someone do this, but maybe by mistake)
- you delete Epic Games Store and it deletes your games
- an error during installation reports incorrect `installation finished` when it actually didn't install the game
- maybe other cases?

When that happens, trying to run the game will fail saying the directory does not exist, but it shows up as installed and the solution is to either edit the installed games cache file or do some manual work with directories to be able to `uninstall` the game to install it again.

### Feature description

When a user tries to launch a game, if the install directory is missing, we can tell that to the user and suggest to options to execute:
- uninstall (I mean, remove it from the list of installed games and refresh legendary's cache?)
- verify/reinstall

So the user can try a fix by clicking a button without having to ask for help and touching config files manually.

### Alternatives

Do that process manually, that's what has to be done currently.

**Comment by flavioislima** [comment]
I am including this handler on my pr #1363

**Comment by flavioislima** [comment]
I dont know if its more confusing or not, but right now we show the error first:
![image](https://user-images.githubusercontent.com/26871415/170460863-9c7247de-0c0e-45a0-836c-a9b0865c62dc.png)

And then the Dialog to ask if the game should be deleted or not:
![image](https://user-images.githubusercontent.com/26871415/170460947-06ba52b6-67e3-432e-81d0-3a7759204b0b.png)

what do you think? should we show both or only the latest?

**Comment by flavioislima** [comment]
@CommandMC @imLinguin any option on that?

**Comment by CommandMC** [comment]
I think just showing the 2nd one is enough

**Comment by arielj** [comment]
I think it's ok to go with 2 dialogs if it's easier, it's an extra click but it's not a big deal (I would say just 1 dialog if possible, but I don't have a strong opinion)

one comment on the first message, showing the app name might be confusing (like... what is stargazer for the end user? I know it's the app_name for magic arena), maybe it was just a quick test and you are showing the actual game title there, in that case ignore this comment haha

**Comment by flavioislima** [comment]
Yes, I changed it to show only the second dialog with the game name. I also think it's easier to understand.
If possible take a look at my PR.

**Comment by arielj** [comment]
I'll try to look at it later, I've been having a super busy week, but that PR seems like a really good UX improvement, error handling is really important
