### ISSUE TITLE
[macOS] Games don't open/run 2020 Intel macbook pro 

### ISSUE THREAD

**Issue by FredsMedia** [Heroic-Games-Launcher/HeroicGamesLauncher#1377]
### Describe the bug

This is my first post in github so bear with me.
I got Heroic today and was very excited to get a chance to play Rocket League (and trackmania) on my mac. Unfortunately after following an online tutorial (I can add a link if need be) When I go to launch Rocket League (or trackmania) it shows as launching and then stops about 10 seconds after. I have tried to fix this by seeing the the issue that was in the log (sugar for RL, Pigeon for Trackmania) but to no avail. I have also set up crossover with the correct dependancies (is that the correct term?) Any help is appreciated!

### Add logs

(12:40:54) DEBUG:   [Legendary]:       Running Legendary command: "/Users/freddy/Desktop/FredsMedia/Games/Games I Didnt Make/Other/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/legendary" --version
(12:41:04) INFO:    [Legendary]:       Legendary location: /Users/freddy/Desktop/FredsMedia/Games/Games I Didnt Make/Other/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/legendary
(12:41:04) INFO:    [Gog]:             GOGDL location: /Users/freddy/Desktop/FredsMedia/Games/Games I Didnt Make/Other/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/gogdl
(12:41:04) INFO:    [Backend]:         
  Heroic Version: 2.3.3 Brook
  Legendary Version:  0.20.25 Our Benefactors
  OS: macOS KERNEL: 21.5.0 ARCH: x64
  CPU: Intel Core™ i5-8257U @1.4 
  RAM: Total: 8 GiB Available: 5.5 GiB
  GRAPHICS: GPU0: Intel Iris Plus Graphics 645 VRAM: 1536MB DRIVER:  
  
  
(12:41:05) WARNING: [Backend]:         Protocol already registered.
(12:41:06) INFO:    [Frontend]:        Refreshing Library
(12:41:06) INFO:    [Legendary]:       Refreshing library...
(12:41:06) INFO:    [Legendary]:       Refreshing Epic Games...
(12:41:06) DEBUG:   [Legendary]:       Running Legendary command: "/Users/freddy/Desktop/FredsMedia/Games/Games I Didnt Make/Other/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/legendary" list --include-ue
(12:41:13) INFO:    [Legendary]:       Updating game list
(12:41:13) INFO:    [Legendary]:       Game List Updated
(12:41:13) INFO:    [Legendary]:       Checking for game updates: "/Users/freddy/Desktop/FredsMedia/Games/Games I Didnt Make/Other/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/legendary" list-installed --check-updates --tsv
(12:41:13) DEBUG:   [Legendary]:       Running Legendary command: "/Users/freddy/Desktop/FredsMedia/Games/Games I Didnt Make/Other/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/legendary" list-installed --check-updates --tsv
(12:41:20) INFO:    [Legendary]:       Found 0 game(s) to update
(12:41:20) INFO:    [Gog]:             Found 0 game(s) to update
(12:41:58) INFO:    [Backend]:         Launching Rocket League® (Sugar)
(12:41:58) DEBUG:   [Legendary]:       Running Wine command: "/Users/freddy/Desktop/FredsMedia/Games/Games I Didnt Make/Other/CrossOver.app/Contents/SharedSupport/CrossOver/CrossOver-Hosted Application/wine" wineboot --init && "/Users/freddy/Desktop/FredsMedia/Games/Games I Didnt Make/Other/CrossOver.app/Contents/SharedSupport/CrossOver/CrossOver-Hosted Application/wineserver" --wait
(12:42:07) DEBUG:   [Legendary]:       Ran Wine command: "/Users/freddy/Desktop/FredsMedia/Games/Games I Didnt Make/Other/CrossOver.app/Contents/SharedSupport/CrossOver/CrossOver-Hosted Application/wine" wineboot --init && "/Users/freddy/Desktop/FredsMedia/Games/Games I Didnt Make/Other/CrossOver.app/Contents/SharedSupport/CrossOver/CrossOver-Hosted Application/wineserver" --wait
(12:42:07) INFO:    [Legendary]:       Launching Rocket League®: WINEPREFIX=/Users/freddy/.wine "/Users/freddy/Desktop/FredsMedia/Games/Games I Didnt Make/Other/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/legendary" launch Sugar --wine "/Users/freddy/Desktop/FredsMedia/Games/Games I Didnt Make/Other/CrossOver.app/Contents/SharedSupport/CrossOver/CrossOver-Hosted Application/wine" --wine-prefix /Users/freddy/.wine
(12:42:07) DEBUG:   [Legendary]:       Running Legendary command: WINEPREFIX=/Users/freddy/.wine "/Users/freddy/Desktop/FredsMedia/Games/Games I Didnt Make/Other/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/legendary" launch Sugar --wine "/Users/freddy/Desktop/FredsMedia/Games/Games I Didnt Make/Other/CrossOver.app/Contents/SharedSupport/CrossOver/CrossOver-Hosted Application/wine" --wine-prefix /Users/freddy/.wine
(12:42:13) DEBUG:   [Legendary]:       Running Legendary command: "/Users/freddy/Desktop/FredsMedia/Games/Games I Didnt Make/Other/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/legendary" --version
(12:42:17) INFO:    [Backend]:         Log was written to /Users/freddy/Library/Application Support/heroic/GamesConfig/Sugar-lastPlay.log
(12:42:17) INFO:    [Frontend]:        Refreshing Library
(12:42:17) INFO:    [Legendary]:       Refreshing library...
(12:42:17) INFO:    [Legendary]:       Updating game list
(12:42:17) INFO:    [Legendary]:       Game List Updated
(12:43:42) INFO:    [Backend]:         Launching Rocket League® (Sugar)
(12:43:42) DEBUG:   [Legendary]:       Running Wine command: "/Users/freddy/Desktop/FredsMedia/Games/Games I Didnt Make/Other/CrossOver.app/Contents/SharedSupport/CrossOver/CrossOver-Hosted Application/wine" wineboot --init && "/Users/freddy/Desktop/FredsMedia/Games/Games I Didnt Make/Other/CrossOver.app/Contents/SharedSupport/CrossOver/CrossOver-Hosted Application/wineserver" --wait
(12:43:48) DEBUG:   [Legendary]:       Ran Wine command: "/Users/freddy/Desktop/FredsMedia/Games/Games I Didnt Make/Other/CrossOver.app/Contents/SharedSupport/CrossOver/CrossOver-Hosted Application/wine" wineboot --init && "/Users/freddy/Desktop/FredsMedia/Games/Games I Didnt Make/Other/CrossOver.app/Contents/SharedSupport/CrossOver/CrossOver-Hosted Application/wineserver" --wait
(12:43:48) INFO:    [Legendary]:       Launching Rocket League®: WINEPREFIX=/Users/freddy/.wine "/Users/freddy/Desktop/FredsMedia/Games/Games I Didnt Make/Other/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/legendary" launch Sugar --wine "/Users/freddy/Desktop/FredsMedia/Games/Games I Didnt Make/Other/CrossOver.app/Contents/SharedSupport/CrossOver/CrossOver-Hosted Application/wine" --wine-prefix /Users/freddy/.wine
(12:43:48) DEBUG:   [Legendary]:       Running Legendary command: WINEPREFIX=/Users/freddy/.wine "/Users/freddy/Desktop/FredsMedia/Games/Games I Didnt Make/Other/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/legendary" launch Sugar --wine "/Users/freddy/Desktop/FredsMedia/Games/Games I Didnt Make/Other/CrossOver.app/Contents/SharedSupport/CrossOver/CrossOver-Hosted Application/wine" --wine-prefix /Users/freddy/.wine
(12:44:08) DEBUG:   [Legendary]:       Running Legendary command: "/Users/freddy/Desktop/FredsMedia/Games/Games I Didnt Make/Other/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/legendary" --version
(12:44:18) INFO:    [Backend]:         Log was written to /Users/freddy/Library/Application Support/heroic/GamesConfig/Sugar-lastPlay.log
(12:44:18) INFO:    [Frontend]:        Refreshing Library
(12:44:18) INFO:    [Legendary]:       Refreshing library...
(12:44:18) INFO:    [Legendary]:       Updating game list
(12:44:18) INFO:    [Legendary]:       Game List Updated

### Steps to reproduce

1. Go to 'Library'
2. Click on 'Rocket League'
3. Scroll down to 'Logs'

### Expected behavior

I expected the game to open and run

### System Information

- OS: Mac 
- Heroic Version: 2.3.3

**Comment by flavioislima** [comment]
How did you add the `Wine` to Heroic? can you send a screenshot of the Wine Settings?

**Comment by FredsMedia** [comment]
<img width="1264" alt="Screen Shot 2022-05-28 at 12 16 57 pm" src="https://user-images.githubusercontent.com/106362296/170805845-129413bf-6d53-45ee-a15d-701e3c90950b.png">
<img width="863" alt="Screen Shot 2022-05-28 at 12 17 04 pm" src="https://user-images.githubusercontent.com/106362296/170805848-fcf9ad29-f214-4a0a-bc17-0355c3bc2e5b.png">

**Comment by flavioislima** [comment]
Yes, with Crossover you don't need to add wine like custom wine. This was before heroic started supporting crossover.
Now you just need to install crossover and have a bottle named Heroic.
In heroic you can setup the bottle called Heroic or Legendary that has some automated script for a few games.
So you can try both and see which one works.

**Comment by FredsMedia** [comment]
So I just make the bottle in crossover and enable that DX thingo and it works? I tried this and it didn’t sadly, after looking at the log again I noticed the directory at the very end (FredsMedia/games/games) and realised that’s the original directory I tried. I reset heroic but it’s still coming up in both pigeon and sugar. Is there any way to reset that bc that might be the problem.
Ps. Sorry for the late replies it seems like we are in different time zones

**Comment by FredsMedia** [comment]
Is this still being investigated? Do you need more information, screen recordings? anything that will help us figure out the problem?

**Comment by flavioislima** [comment]
@FredsMedia try on the latest release and send a new screenshot like the above.

**Comment by FredsMedia** [comment]
<img width="1264" alt="Screen Shot 2022-06-15 at 3 08 55 pm" src="https://user-images.githubusercontent.com/106362296/173741082-1229d632-db00-4f8d-bee3-07d71e2a8f65.png">
this good?

**Comment by flavioislima** [comment]
Can you try renaming the bottle to `Legendary` ?

**Comment by FredsMedia** [comment]
<img width="768" alt="Screen Shot 2022-06-16 at 9 14 39 am" src="https://user-images.githubusercontent.com/106362296/173957537-bc039929-cc3d-4343-9740-c5b7f2b88216.png">
Both are there
Still doesn't work.
You need any logs?

**Comment by FredsMedia** [comment]
Wait how do I set up the bottle inside of Heroic? I have been making both manually from crossover and I think this might be the problem.

**Comment by FredsMedia** [comment]
has this been abandoned?

**Comment by flavioislima** [comment]
> @flavioislima has this been abandoned? I mean 11 days seems like a while...

Well, you need to understand that we do this on our free time and it's a free project. So there is no deadline we help when we can.

I'm pretty busy these weeks because I'm moving to a new apartment so I am not being able to focus on Heroic and probably won't be for one more week.

Try to go to our discord to get help there if you haven't.

**Comment by FredsMedia** [comment]
omg im so sorry I didn't realise you were doing this in your free time. Again so sorry, I was a bit rude there. Take as much time as you need, I appreciate what you have done so far and I think the app you have created is amazing!

**Comment by FredsMedia** [comment]
@flavioislima How did the move go? Any new ideas because I am stumped...

**Comment by FredsMedia** [comment]
I occasionally use porting kit, would this interfere because they both use wine?

**Comment by flavioislima** [comment]
> I occasionally use porting kit, would this interfere because they both use wine?

I have no idea what this is but might be. Also Heroic won't run games with wine we support Crossover Only. If you are using Wine then that is your problem.

Check the latest commit build in beta to see if it solves your issue:
https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/actions/runs/2813626583

**Comment by Nocccer** [comment]
The only thing i see is the spaces in the game path, but actually that should no be problem in beta. Maybe the games you wanna try to run, just don't work in crossover. Check crossover compatibility database on there side. Also make sure to follow there guide how to setup heroic crossover bottle.

**Comment by FredsMedia** [comment]
sorry for the very late reply! I use crossover but I assumed they both used wine (not an expert!)
I just want to use rocket league and there is lots of proof of it working.

**Comment by FredsMedia** [comment]
Yeah this isn’t going anywhere. Sorry for the waste of time it’s probably my Mac being stubborn as usual. Nice meeting you though Flavioslima.

**Comment by flavioislima** [comment]
> Yeah this isn’t going anywhere. Sorry for the waste of time it’s probably my Mac being stubborn as usual. Nice meeting you though Flavioslima.

Sorry man, could not give attention to this issue.
But tk be honest I'm not sure what is going on yet.
On 2.4.3 the logs are the same?
Have you tried games from both epic and Gog?

**Comment by FredsMedia** [comment]
> > Yeah this isn’t going anywhere. Sorry for the waste of time it’s probably my Mac being stubborn as usual. Nice meeting you though Flavioslima.
> 
> Sorry man, could not give attention to this issue. But tk be honest I'm not sure what is going on yet. On 2.4.3 the logs are the same? Have you tried games from both epic and Gog?

I will check in a bit as I am not home right now. I don’t have any games on gog so what would you reccomend that is free?

**Comment by FredsMedia** [comment]
Well we got further with gog (the game launched) but still not quite there.
<img width="1440" alt="Screen Shot 2022-09-29 at 2 55 29 pm" src="https://user-images.githubusercontent.com/106362296/192942408-ffbc1fde-c210-48b6-806e-ae2b0335632f.png">

**Comment by flavioislima** [comment]
So it launches, the game probably won't run using wine on mac but at least it runs.
Try maybe a native macOS game from both Epic and GOG.

**Comment by FredsMedia** [comment]
Both 64 bit or should we add on a 32 to the mix?

**Comment by FredsMedia** [comment]
ok so both games from epic and got that are native to macOS run perfectly fine. I am going to check Rocket League again to see if it will work.

**Comment by FredsMedia** [comment]
I decided track mania because it took up way less space but these came up. Any ideas?
<img width="241" alt="Screen Shot 2022-09-30 at 8 29 22 am" src="https://user-images.githubusercontent.com/106362296/193153504-4870b2d4-cea2-432f-81c3-e57303299d2a.png">
<img width="243" alt="Screen Shot 2022-09-30 at 8 29 12 am" src="https://user-images.githubusercontent.com/106362296/193153519-9edb94ac-ea31-4d25-9c36-f3082ff78ca6.png">
<img width="248" alt="Screen Shot 2022-09-30 at 8 29 05 am" src="https://user-images.githubusercontent.com/106362296/193153520-2acf05b2-1915-48dc-b670-262f0b6bded6.png">

**Comment by FredsMedia** [comment]
lkwbref;aber;gva;ekrbgvi;haber;igvai;wruhvliawrvliauwbervba;erbfhjaebrgljhbwrljhfga omgggggggggg it's workingggggggggg THIS IS THE BEST DAY OF MY LIFE. thank you for sticking this out for me man
<img width="1440" alt="Screen Shot 2022-09-30 at 8 50 42 am" src="https://user-images.githubusercontent.com/106362296/193155880-9d24d0b2-1632-4ead-a9fa-6fcfccbede65.png">

**Comment by flavioislima** [comment]
> lkwbref;aber;gva;ekrbgvi;haber;igvai;wruhvliawrvliauwbervba;erbfhjaebrgljhbwrljhfga omgggggggggg it's workingggggggggg THIS IS THE BEST DAY OF MY LIFE. thank you for sticking this out for me man
> <img width="1440" alt="Screen Shot 2022-09-30 at 8 50 42 am" src="https://user-images.githubusercontent.com/106362296/193155880-9d24d0b2-1632-4ead-a9fa-6fcfccbede65.png">
> 

That's great, man.
Have fun! 😁
