### ISSUE TITLE
heroic game showing games that are not installed as installed

### ISSUE THREAD

**Issue by akilan200** [Heroic-Games-Launcher/HeroicGamesLauncher#1380]
### Describe the bug

heroic game showing gmaes that are not installed as installed

### Add logs

1

### Steps to reproduce

2. Click on '...'
3. Scroll down to '...'
4. See error22

### Expected behavior

<img width="1552" alt="Screenshot 2022-05-27 at 3 15 33 PM" src="https://user-images.githubusercontent.com/106062145/170675262-8658d28a-39ee-4383-8a72-445d25a9076a.png">

### Screenshots

<img width="1552" alt="Screenshot 2022-05-27 at 3 15 33 PM" src="https://user-images.githubusercontent.com/106062145/170675288-2dfdf2fe-11b5-4633-97a6-d6ebb0b88234.png">

### System Information

- OS : MACOS MONTERY
- Heroic Version :HEROIC VERSION 2.3.3

**Comment by flavioislima** [comment]
How did this happened?
The game was installed before? did you remove the folder? did you click on uninstall and then it still shows as installed?

**Comment by akilan200** [comment]
sorry for the inconvinence i found out how to uninstall
i was only used to old version so iwas confused thank you ansorry again
