### ISSUE TITLE
Update Imported Game

### ISSUE THREAD

**Issue by zihaaad** [Heroic-Games-Launcher/HeroicGamesLauncher#1393]
### Problem description

I have downloaded Massive GTAV from Torrent. It's a games file from last month. However when I launch imported game, It throws me error. 
```
Error Log:
gamemodeauto:
[cli] INFO: Logging in...
[Core] INFO: Trying to re-use existing login session...
[cli] INFO: Checking for updates...
[cli] ERROR: Game is out of date, please update or launch with update check skipping!
```

### Feature description

 I hope you will give us option to update imported game.

**Comment by flavioislima** [comment]
Heroic doesn't support import games from torrent or anywhere else. This feature is to be used after a clean heroic install or to import games installed using epic games store.
