### ISSUE TITLE
Stuck on the default blue screen.

### ISSUE THREAD

**Issue by GoldenAJF** [Heroic-Games-Launcher/HeroicGamesLauncher#1395]
### Describe the bug

When I open the Heroic Games Launcher, it opens the app, and shows me just a blue window. Their isn't anything else, and it doesn't load further. This is installed via AUR.

### Add logs

Can't access.

### Steps to reproduce

Open Heroic Games Launcher.
It won't display much.

### Expected behavior

When I open, it shows me my library, settings, store, ext.

### Screenshots

![Screenshot_20220528_082624](https://user-images.githubusercontent.com/34905857/170827568-2e8e6a95-acb6-4743-a4ed-f4297d759254.png)

### System Information

- OS [e. g. "Ubuntu"]: Manjaro Linux
- Heroic Version [e. g. 2.1.1]: 2.3.3

**Comment by flavioislima** [comment]
I belive this issue was fixed but not released yet.
Can you try the build from the latest commit?
https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/actions/runs/2401432879

**Comment by GoldenAJF** [comment]
The app image appears to work fine, thank you.

**Comment by ahcm** [comment]
Happens with 2.4.0 on archlinux with aur heroic-games-launcher-bin and appimage from github.

**Comment by ahcm** [comment]
Downgrading to 2.3.10-2 fixes it.

**Comment by Nocccer** [comment]
@ahcm run the appimage or aur package from terminal (2.4.0) and provide the ouput here.

**Comment by Thabilis** [comment]
Exact same problem on Arch. Installed from AUR.
Version and kernel version: in logs.
logs: https://pastebin.com/LQgKMfJS
Debug: <noscript>You need to enable JavaScript to run this app.</noscript>
