### ISSUE TITLE
Can't open the browser on SteamDeck to login to Epic

### ISSUE THREAD

**Issue by TeddyDD** [Heroic-Games-Launcher/HeroicGamesLauncher#1397]
### Describe the bug

I can't log-in to Epic because I'm unable to open a browser window by clicking on „Open Epic Store Here” link in the account managment screeen. I'm running Flatpak version of Heroic on beta SteamOS.

### Add logs
```
(19:07:56) DEBUG:   [Legendary]:       Running Legendary command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary --version
(19:07:56) INFO:    [Legendary]:       Legendary location: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary
(19:07:56) INFO:    [Gog]:             GOGDL location: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl
(19:07:56) INFO:    [Backend]:         
  Heroic Version: 2.3.3 Brook
  Legendary Version:  0.20.25 Our Benefactors
  OS: Freedesktop.org KERNEL: 5.13.0-valve15-1-neptune-02197-gf6ec7ad3762a ARCH: x64
  CPU: AMD Custom APU 0405 @1.69 GOVERNOR: schedutil
  RAM: Total: 14.49 GiB Available: 11.6 GiB
  GRAPHICS: GPU0: Device 163f VRAM: 512MB DRIVER:  
  PROTOCOL: x11
  
(19:07:56) INFO:    [Backend]:         User Not Found, removing it from Store
(19:07:56) INFO:    [Gog]:             Getting data about the user
(19:07:56) ERROR:   [Backend]:         Failed to register protocol with OS.
(19:07:57) INFO:    [Gog]:             Saved user data to config
(19:07:58) INFO:    [Frontend]:        Refreshing Library
(19:07:58) INFO:    [Legendary]:       Refreshing library...
(19:07:58) INFO:    [Gog]:             Getting GOG library
(19:07:58) INFO:    [Gog]:             Number of library pages: 2
(19:07:58) INFO:    [Gog]:             Getting data for page 2
(19:07:58) INFO:    [Gog]:             Saved games data
(19:07:58) INFO:    [Frontend]:        No cache found, getting data from legendary...
(19:07:58) INFO:    [Legendary]:       Refreshing library...
(19:07:59) INFO:    [Gog]:             Found 0 game(s) to update
Failed to call portal: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such interface ?org.freedesktop.portal.OpenURI? on object at path /org/freedesktop/portal/desktop
```

### Steps to reproduce

1. Go to Manage Accounts > Epic external login
2. Click „Open Epic store here”

### Expected behavior

Browser window is opened I guess?

### System Information

- OS [e. g. "Ubuntu"]: SteamOS Holo x86_64
- Heroic Version [e. g. 2.1.1]: v2.3.3

**Comment by hartmark** [comment]
I have same behavior on Arch

**Comment by shaunawins** [comment]
I'm having precisely the same issue on Steam Deck. I click the "Epic Store Here" link and nothing happens. It won't even give me a context menu on right click so I can open it in an external browser. This is frustrating, as I've had to resort to other more hacky ways of installing Epic games.

**Comment by flavioislima** [comment]
@shaunawins the normal login doesnt work as well?

**Comment by flavioislima** [comment]
@Nocccer can you check this when you have the time since you have a deck?

**Comment by Nocccer** [comment]
Does this happen in Desktop Mode? Please use heroic in desktop mode only.

**Comment by lyckantropen** [comment]
This happens to me on 2.4.3 in desktop mode. Nothing happens when "Epic Store here" is clicked.

**Comment by flavioislima** [comment]
This is an issue with SteamOS I can confirm that thus happens not only in heroic but other apps as well.
Fortunately is easy to fix.

This came from reddit BTW:

```
For anyone struggling with this annoying bug.

An easy workaround for now is to just paste this into a file

#!/bin/bash
systemctl restart --user xdg-desktop-portal

2. Name it something like "desktop-portal-workaround.sh".

3. Right click it, open properties, then permissions tab and set it as executable.

4. Search "autostart" in the app launcher and open the first thing that pops up.

5. Click the "add" button and choose "add login script" then choose that script you just made.

Then reboot and see if it fixes it.

Works great for me.
```

**Comment by asaji** [comment]
> This is an issue with SteamOS I can confirm that this happens not only in heroic but other apps as well. Fortunately is easy to fix.
> 
> This came from reddit BTW:
> 
> ```
> For anyone struggling with this annoying bug.
> 
> An easy workaround for now is to just paste this into a file
> 
> #!/bin/bash
> systemctl restart --user xdg-desktop-portal
> 
> 2. Name it something like "desktop-portal-workaround.sh".
> 
> 3. Right click it, open properties, then permissions tab and set it as executable.
> 
> 4. Search "autostart" in the app launcher and open the first thing that pops up.
> 
> 5. Click the "add" button and choose "add login script" then choose that script you just made.
> 
> Then reboot and see if it fixes it.
> 
> Works great for me.
> ```

Worked well for me
