### ISSUE TITLE
[SteamDeck] Gamepad navigation not working.

### ISSUE THREAD

**Issue by MathiewMay** [Heroic-Games-Launcher/HeroicGamesLauncher#1400]
### Describe the bug

The gamepad navigation does not work on the steam deck either in gaming or desktop mode

### Add logs

N/A

### Steps to reproduce

1. Install the flatpak version of the heroic games launcher on your steam deck
2. See that the gamepad does not navigate the ui

### Expected behavior

The gamepad input would navigate the ui

### Screenshots

N/A

### System Information

- OS SteamOS
- Heroic Version Flatpak latest

### Additional information

N/A

**Comment by arielj** [comment]
This is a known issue, but seems to be related to flatpak, not heroic, the controller doesn't work in any chrome based application inside a flatpak container (I doesn't even work in Chrome Flatpak on a desktop computer for example)

There's an open issue in the flatpak repo about this https://github.com/flatpak/flatpak/issues/7

**Comment by JDGBOLT** [comment]
Actually, it seems there is one more step that is needed in order to get the gamepad to work on Heroic/Chrome/Edge within flatpak. You need to provide a read only permission to /run/udev, was able to get the heroic launcher Gamepad Input to work by adding /run/udev:ro to the filesystem permissions within flatseal.

**Comment by flavioislima** [comment]
> Actually, it seems there is one more step that is needed in order to get the gamepad to work on Heroic/Chrome/Edge within flatpak. You need to provide a read only permission to /run/udev, was able to get the heroic launcher Gamepad Input to work by adding /run/udev:ro to the filesystem permissions within flatseal.

Interesting. will try that for the next release.
Thanks for the tip.

**Comment by arielj** [comment]
I understand this is currently working, probably some SteamOS update? I know from other issues that the Gamepad navigation is working on Steam Deck now.

**Comment by Nocccer** [comment]
Gamepad navigation was working since 2.3.9. atleast for me on steam deck.
