### ISSUE TITLE
Python Error in all games using either appimage or RPM

### ISSUE THREAD

**Issue by harveyshepherd** [Heroic-Games-Launcher/HeroicGamesLauncher#1401]
### Describe the bug

when I attempt to launch any game the launcher will take a few seconds and no launch occurs. when checking logs I find errors related to python. I am completely unsure how to even start troubleshooting.

note that using previous versions of heroic I have not had this problem. It started with 2.3.3 but I have not used the application in several months so I am not sure when it was introduced

### Add logs

Launch Command: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary launch Kiwi --wine "/home/.../.steam/steam/steamapps/common/Proton - Experimental/proton" --wine-prefix /home/.../Games/Heroic/Prefixes/Tetris®-Effect-Connected 

Heroic Version: 2.3.3 Brook
  Legendary Version:  0.20.25 Our Benefactors
  OS: openSUSE Tumbleweed KERNEL: 5.17.5-1-default ARCH: x64
  CPU: Intel Core™ i7-4770 u/3.4 GOVERNOR: schedutil
  RAM: Total: 31.26 GiB Available: 26.99 GiB
  GRAPHICS: GPU0: NVIDIA GeForce GTX 1070 VRAM: 8192MB DRIVER: 510.68.02 
  PROTOCOL: x11

Game Settings: {
	"altLegendaryBin": "",
	"altGogdlBin": "",
	"addDesktopShortcuts": false,
	"addStartMenuShortcuts": false,
	"audioFix": false,
	"autoInstallDxvk": false,
	"autoInstallVkd3d": false,
	"customWinePaths": [],
	"darkTrayIcon": false,
	"defaultInstallPath": "/home/.../Games/Heroic",
	"defaultWinePrefix": "/home/.../Games/Heroic/Prefixes",
	"disableController": false,
	"discordRPC": false,
	"egsLinkedPath": "",
	"enableEsync": false,
	"enableFsync": false,
	"exitToTray": false,
	"maxRecentGames": 5,
	"maxWorkers": 0,
	"minimizeOnLaunch": false,
	"nvidiaPrime": false,
	"otherOptions": "",
	"showFps": false,
	"showMangohud": false,
	"showUnrealMarket": false,
	"startInTray": false,
	"useGameMode": false,
	"wineCrossoverBottle": "Heroic",
	"winePrefix": "/home/.../Games/Heroic/Prefixes/Tetris®-Effect-Connected",
	"wineVersion": {
		"bin": "'/home/.../.steam/steam/steamapps/common/Proton - Experimental/proton'",
		"name": "Proton - Proton - Experimental"
	},
	"checkUpdatesInterval": 10,
	"enableUpdates": false,
	"checkForUpdatesOnStartup": true,
	"language": "en",
	"userInfo": {
		"epicId": "...",
		"name": "..."
	},
	"offlineMode": false
}

Error Log:
[cli] INFO: Logging in...
[Core] INFO: Trying to re-use existing login session...
[cli] INFO: Checking for updates...
[Core] INFO: Getting authentication token...
[cli] INFO: Launching Kiwi...
Could not find platform independent libraries <prefix>
Could not find platform dependent libraries <exec_prefix>
Consider setting $PYTHONHOME to <prefix>[:<exec_prefix>]
Python path configuration:
  PYTHONHOME = (not set)
  PYTHONPATH = (not set)
  program name = 'python3'
  isolated = 0
  environment = 1
  user site = 1
  import site = 1
  sys._base_executable = '/usr/bin/python3'
  sys.base_prefix = '/usr'
  sys.base_exec_prefix =
'/usr'
  sys.executable = '/usr/bin/python3'
  sys.prefix = '/usr'
  sys.exec_prefix = '/usr'
  sys.path = [
    '/usr/lib/python38.zip',
    '/usr/lib/python3.8',
    '/usr/lib/lib-dynload',
  ]
Fatal Python error: init_fs_encoding: failed to get the Python codec of the filesystem encoding
Python runtime state: core initialized
ModuleNotFoundError: No module named 'encodings'

Current thread 0x00007fe6e0f6b740 (most recent call first):
<no Python frame>

### Steps to reproduce

Attempt to start any game

### Expected behavior

game should launch successfully

### System Information

OpenSUSE Tumbleweed
Heroic 2.3.3 using both RPM and appimage

**Comment by flavioislima** [comment]
Check this issue here:
https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/issues/310
