### ISSUE TITLE
Open Heroic with error "Config file is corrupted"

### ISSUE THREAD

**Issue by Darkatse** [Heroic-Games-Launcher/HeroicGamesLauncher#1406]
### Describe the bug

When you open Heroic, three messages will appear prompting "Config file is corrupted". If you turn it off and keep running, you can log in normally, but the game library cannot be loaded (it shows 0 games in the library)

### Add logs

(00:48:56) DEBUG:   [Legendary]:       Running Legendary command: C:\Users\SomeChineseNameHere\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\legendary --version
(00:49:03) INFO:    [Legendary]:       Legendary location: C:\Users\SomeChineseNameHere\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\legendary
(00:49:03) INFO:    [Gog]:             GOGDL location: C:\Users\SomeChineseNameHere\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\gogdl
(00:49:03) INFO:    [Backend]:         

Heroic Version: 2.3.4 Brook
Legendary Version:  0.20.25 Our Benefactors
OS: Microsoft Windows 11 家庭中文版 KERNEL: 10.0.22000 ARCH: x64
CPU: Intel Core™ i7-8750H @2.2 
RAM: Total: 31.88 GiB Available: 15.07 GiB
GRAPHICS: GPU0: NVIDIA GeForce GTX 1070 with Max-Q Design VRAM: 8192MB DRIVER: 511.79 

(00:49:04) WARNING: [Backend]:         Protocol already registered.
(00:49:04) ERROR:   [Backend]:         Config file is corrupted, please check C:\Users\SomeChineseNameHere\AppData\Roaming\heroic\config.json
(00:49:05) INFO:    [Frontend]:        Refreshing Library
(00:49:05) INFO:    [Legendary]:       Refreshing library...
(00:49:05) INFO:    [Legendary]:       Refreshing Epic Games...
(00:49:05) ERROR:   [Backend]:         Config file is corrupted, please check C:\Users\SomeChineseNameHere\AppData\Roaming\heroic\config.json
(00:49:07) DEBUG:   [Legendary]:       Running Legendary command: C:\Users\SomeChineseNameHere\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\legendary list
(00:49:09) INFO:    [Legendary]:       Updating game list
(00:49:09) INFO:    [Legendary]:       Game List Updated
(00:49:10) INFO:    [Legendary]:       Checking for game updates: C:\Users\SomeChineseNameHere\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\legendary list-installed --check-updates --tsv
(00:49:10) DEBUG:   [Legendary]:       Running Legendary command: C:\Users\SomeChineseNameHere\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\legendary list-installed --check-updates --tsv
(00:49:12) INFO:    [Legendary]:       Found 0 game(s) to update
(00:49:12) INFO:    [Gog]:             Found 0 game(s) to update
(00:49:38) ERROR:   [Error: net::ERR_EMPTY_RESPONSE]: failed to update

### Steps to reproduce

1. open the Heroic
2. error message appears

### Expected behavior

Open normally without errors and display the games in the library normally

### System Information

Heroic Version: 2.3.4 Brook
Legendary Version:  0.20.25 Our Benefactors
OS: Microsoft Windows 11 家庭中文版 KERNEL: 10.0.22000 ARCH: x64
CPU: Intel Core™ i7-8750H @2.2 
RAM: Total: 31.88 GiB Available: 15.07 GiB
GRAPHICS: GPU0: NVIDIA GeForce GTX 1070 with Max-Q Design VRAM: 8192MB DRIVER: 511.79

**Comment by Darkatse** [comment]
And It's my config file
```
{
  "defaultSettings": {
    "altLegendaryBin": "",
    "altGogdlBin": "",
    "addDesktopShortcuts": false,
    "addStartMenuShortcuts": false,
    "autoInstallDxvk": false,
    "autoInstallVkd3d": false,
    "customWinePaths": [],
    "defaultInstallPath": "C:\\Users\\SomeChineseNameHere\\Games\\Heroic",
    "defaultWinePrefix": "C:\\Users\\SomeChineseNameHere\\Games\\Heroic\\Prefixes",
    "disableController": false,
    "egsLinkedPath": "",
    "maxRecentGames": 5,
    "maxWorkers": 0,
    "minimizeOnLaunch": false,
    "nvidiaPrime": false,
    "otherOptions": "",
    "showFps": false,
    "showUnrealMarket": false,
    "useGameMode": false,
    "wineCrossoverBottle": "Heroic",
    "winePrefix": {},
    "wineVersion": {}
  },
  "version": "v0"
}
```

**Comment by flavioislima** [comment]
After the login it still shows the error message?

**Comment by Darkatse** [comment]
> After the login it still shows the error message?

yes, it's still shows error meassge. Maybe it relates to the Chinese username or language environment?

**Comment by flavioislima** [comment]
Good question.
Could be username. 
can you use a json validator online and check if it will show any error?

**Comment by Darkatse** [comment]
> Good question. Could be username. can you use a json validator online and check if it will show any error?

I use jsonlint.com to check and it's shows Valid JSON.

**Comment by Mart994** [comment]
It also happens to me and it isnt the username

**Comment by flavioislima** [comment]
> It also happens to me and it isnt the username

on windows as well?

**Comment by Mart994** [comment]
> > It also happens to me and it isnt the username
> 
> on windows as well?

Yes, Windows 11 pro (spanish)
I uninstalled heroic, wiped all the remaining files, did a clean install of heroic and now I can't log in (no show error on this) plus the same "config file is corrupted" error

**Comment by flavioislima** [comment]
Have you tried to login with SID as well? (external login) Or login on the store first and then click on login on manage accounts.

**Comment by arcadeoni** [comment]
> Have you tried to login with SID as well? (external login) Or login on the store first and then click on login on manage accounts.

Also happening for me on the steam deck. This did not fix it.

**Comment by birqbirq** [comment]
Same for me. Windows 10. Also checked config.json with a json viewer and it shows to be valid.

**Comment by birqbirq** [comment]
Update: I rolled back to 2.3.2 and the error went away.

**Comment by flavioislima** [comment]
Yes, rollback for now while we investigate.

**Comment by Mart994** [comment]
> Have you tried to login with SID as well? (external login) Or login on the store first and then click on login on manage accounts.

Yes, i tried both, but i did rollback to 2.3.2 and now works

**Comment by Darkatse** [comment]
Update: After rolling back to 2.3.2 and re-login, everything now works fine.

**Comment by flavioislima** [comment]
can you guys try this build once its finished:
https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/actions/runs/2408497586
