### ISSUE TITLE
Steam Deck: Command Line Runs Games in Background

### ISSUE THREAD

**Issue by krelltunez** [Heroic-Games-Launcher/HeroicGamesLauncher#1407]
### Describe the bug

When running a game on the Steam Deck via command line (i.e., through "Non-Steam Games"), two behaviors are exhibited:

1.  In Desktop Mode, the game loads normally.  This indicates the link is correct and everything is technically working.
2. In Game Mode, the game seems to load in the background.  The SteamOS loading screen never goes away, but the game audio comes out of the speakers (as if the game is loaded behind the OS load screen).

As far as I know, the Steam Deck does not have an ALT-TAB shortcut to bring the game to the foreground.

### Add logs

N/A

### Steps to reproduce

1. Go to 'Game Mode' on Steam Deck
2. Click on 'Non-Steam Games'
3. Scroll down to game to run (tested with Kena and Outer Wilds)

### Expected behavior

Game should run in the foreground.

### System Information

- SteamOS Beta (v3.2)
- Heroic Version 2.3.4

### Additional information

EDIT:  I am using the "--no-gui" command line argument.

**Comment by X-Caspian-X** [comment]
I have the same issue with Salt and Sacrifice.

I did use the Bash Launcher to add the game to Steam.

In desktop mode, I can run the game out of Heroic and out of Steam.

Once in game mode, the Steam loading screen continues to spin but I can hear the game in the background. 

I don’t have this issue with Rocket League, Yooka Laylee or Inscription.

**Comment by josaco** [comment]
I also have the same bug, borderlands launchs and i can hear the intro sound but stucks in steam loading screen in the steamdeck

**Comment by X-Caspian-X** [comment]
> EDIT:  I heard that Salt and Sacrifice doesn't work on the Steam Deck.  Do you have a different Proton version set for that game, compared to the others that work OK?

I just used GE 7-20 and it worked. I did uninstall and reinstall and it stopped launching though. I did the game to work with Lutris in game mode though.

**Comment by neilchalk** [comment]
I was having this with the game Control, upgraded for v2.3.3 to v2.3.7 and it plays in game mode again on the Steam Deck

**Comment by josaco** [comment]
I can confirm that reinstalling heroic and deleting all the settings files fix the issue. Also noticed that for a strange reason, i had installed heroic 2 times in discover for my steam deck

**Comment by flavioislima** [comment]
> I can confirm that reinstalling heroic and deleting all the settings files fix the issue. Also noticed that for a strange reason, i had installed heroic 2 times in discover for my steam deck

You have probably installed stable and beta, that right now are the same version but soon we will have a beta again.
