### ISSUE TITLE
No games appear in library

### ISSUE THREAD

**Issue by bshor** [Heroic-Games-Launcher/HeroicGamesLauncher#1408]
### Describe the bug

I see no games in my Library. Only a section called "Unreal - Everything", which is itself empty. The store section does work.

I tried deleting ~/.config/legendary and ~/.config/heroic but no luck.

I do see a login screen. I choose external login and pull in the SID. But nothing appears on the library.

### Add logs

(18:12:57) DEBUG:   [Legendary]:       Running Legendary command: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary --version
(18:12:58) INFO:    [Legendary]:       Legendary location: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary
(18:12:58) INFO:    [Gog]:             GOGDL location: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl
(18:12:58) INFO:    [Backend]:         

Heroic Version: 2.3.4 Brook
Legendary Version:  0.20.25 Our Benefactors
OS: Garuda KERNEL: 5.17.8-zen1-1-zen ARCH: x64
CPU: AMD Ryzen 7 3700X 8-Core Processor @3.6 GOVERNOR: performance
RAM: Total: 31.36 GiB Available: 6.79 GiB
GRAPHICS: GPU0: NVIDIA GeForce GTX 1060 6GB VRAM: 6144MB DRIVER: 515.43.04 
PROTOCOL: x11

(18:12:58) INFO:    [Backend]:         User Not Found, removing it from Store
(18:12:58) WARNING: [Backend]:         Protocol already registered.
(18:13:01) INFO:    [Backend]:         Downloaded Winetricks
(18:13:01) INFO:    [DXVKInstaller]:   Updating dxvk to: dxvk-1.10.1
(18:13:01) INFO:    [DXVKInstaller]:   Updating vkd3d to: vkd3d-proton-2.6
(18:13:01) INFO:    [DXVKInstaller]:   downloaded vkd3d
(18:13:01) INFO:    [DXVKInstaller]:   extracting vkd3d
(18:13:01) INFO:    [DXVKInstaller]:   extracting vkd3d updated!
(18:13:02) INFO:    [DXVKInstaller]:   downloaded dxvk
(18:13:02) INFO:    [DXVKInstaller]:   extracting dxvk
(18:13:02) INFO:    [DXVKInstaller]:   extracting dxvk updated!
(18:13:37) INFO:    [Legendary]:       Logging in with Legendary: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary auth --sid <redacted>
(18:13:37) DEBUG:   [Legendary]:       Running Legendary command: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary auth --sid <redacted>
(18:13:38) INFO:    [Frontend]:        Refreshing Library
(18:13:38) INFO:    [Legendary]:       Refreshing library...
(18:13:38) INFO:    [Legendary]:       Refreshing Epic Games...
(18:13:38) INFO:    [Frontend]:        Called Login
(18:13:38) DEBUG:   [Legendary]:       Running Legendary command: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary list
(18:13:39) INFO:    [Legendary]:       Updating game list
(18:13:39) INFO:    [Legendary]:       Game List Updated
(18:13:39) INFO:    [Frontend]:        No cache found, getting data from legendary...
(18:13:39) INFO:    [Legendary]:       Refreshing library...
(18:13:39) INFO:    [Legendary]:       Updating game list
(18:13:39) INFO:    [Legendary]:       Game List Updated
(18:13:39) INFO:    [Frontend]:        Force Update
(18:13:53) INFO:    [Legendary]:       Logging out: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary auth --delete
(18:13:53) DEBUG:   [Legendary]:       Running Legendary command: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary auth --delete
(18:13:54) DEBUG:   [Legendary]:       Running Legendary command: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary cleanup
(18:14:28) INFO:    [Legendary]:       Logging in with Legendary: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary auth --sid <redacted>
(18:14:28) DEBUG:   [Legendary]:       Running Legendary command: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary auth --sid <redacted>
(18:14:29) INFO:    [Frontend]:        Refreshing Library
(18:14:29) INFO:    [Legendary]:       Refreshing library...
(18:14:29) INFO:    [Legendary]:       Refreshing Epic Games...
(18:14:29) INFO:    [Frontend]:        Called Login
(18:14:30) DEBUG:   [Legendary]:       Running Legendary command: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary list
(18:14:31) INFO:    [Legendary]:       Updating game list
(18:14:31) INFO:    [Legendary]:       Game List Updated
(18:14:31) INFO:    [Frontend]:        No cache found, getting data from legendary...
(18:14:31) INFO:    [Legendary]:       Refreshing library...
(18:14:31) INFO:    [Legendary]:       Updating game list
(18:14:31) INFO:    [Legendary]:       Game List Updated
(18:14:31) INFO:    [Frontend]:        Force Update

### Steps to reproduce

1. Load Heroic
2. See no games in "Library"

### Expected behavior

Seeing a list of my games appear

### Screenshots

![image](https://user-images.githubusercontent.com/468070/170895193-169161dd-0a2d-4b2a-8061-dbd063cc8b9a.png)

### System Information

- Garuda Linux (Arch derivative, 5.17 kernel)
- Heroic Version [e. g. 2.1.1]: 2.3.4

**Comment by methane4** [comment]
I have the same issue.

**Comment by pooriaPoorsarvi** [comment]
I can confirm the same issue on the steam deck.

**Comment by Poklonskayaccc** [comment]
Trying going into the configurations and enable the "Show Unreal Marketplace" option.

**Comment by hfalmeida2022** [comment]
> Go to Settings,General and enable the "Show Unreal Marketplace" option.

This fixed it for me

**Comment by fuad00** [comment]
Solution: Install previous release

**Comment by flavioislima** [comment]
Can you guys try this appimage:
https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/actions/runs/2408497584
?

**Comment by methane4** [comment]
Fixed.
