### ISSUE TITLE
Empty library 

### ISSUE THREAD

**Issue by Nino155** [Heroic-Games-Launcher/HeroicGamesLauncher#1410]
### Describe the bug

My library is empty, even if I have a lot of games. 
When I try to find a game I have in the store, it tells me that I have it on the library so I can't try to launch or download it from the store.

### Add logs

(11:15:29) DEBUG:   [Legendary]:       Running Legendary command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary --version
(11:15:30) INFO:    [Legendary]:       Legendary location: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary
(11:15:30) INFO:    [Gog]:             GOGDL location: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl
(11:15:30) INFO:    [Backend]:         

Heroic Version: 2.3.4 Brook
Legendary Version:  0.20.25 Our Benefactors
OS: Freedesktop.org KERNEL: 5.13.0-44-generic ARCH: x64
CPU: Intel Core™ i3-6100H @2.7 GOVERNOR: powersave
RAM: Total: 7.65 GiB Available: 4.51 GiB
GRAPHICS: GPU0: HD Graphics 530  VRAM: 256MB DRIVER:  
PROTOCOL: x11

(11:15:30) WARNING: [Backend]:         Failed to register protocol with OS.
(11:15:31) INFO:    [Frontend]:        Refreshing Library
(11:15:31) INFO:    [Legendary]:       Refreshing library...
(11:15:31) INFO:    [Legendary]:       Refreshing Epic Games...
(11:15:32) DEBUG:   [Legendary]:       Running Legendary command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary list
(11:15:35) INFO:    [Legendary]:       Updating game list
(11:15:35) INFO:    [Legendary]:       Game List Updated
(11:15:37) INFO:    [Backend]:         Downloaded Winetricks
(11:15:37) INFO:    [Legendary]:       Checking for game updates: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary list-installed --check-updates --tsv
(11:15:37) DEBUG:   [Legendary]:       Running Legendary command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary list-installed --check-updates --tsv
(11:15:38) INFO:    [Legendary]:       Found 0 game(s) to update
(11:15:38) INFO:    [Gog]:             Found 0 game(s) to update
(11:18:19) INFO:    [Frontend]:        Refreshing Library
(11:18:19) INFO:    [Gog]:             Found 0 game(s) to update
(11:18:20) INFO:    [Frontend]:        Refreshing Library
(11:18:20) INFO:    [Gog]:             Found 0 game(s) to update
(11:18:20) INFO:    [Frontend]:        Refreshing Library
(11:18:20) INFO:    [Gog]:             Found 0 game(s) to update
(11:18:20) INFO:    [Frontend]:        Refreshing Library
(11:18:21) INFO:    [Gog]:             Found 0 game(s) to update
(11:18:21) INFO:    [Frontend]:        Refreshing Library
(11:18:21) INFO:    [Gog]:             Found 0 game(s) to update
(11:18:21) INFO:    [Frontend]:        Refreshing Library
(11:18:21) INFO:    [Gog]:             Found 0 game(s) to update
(11:18:21) INFO:    [Frontend]:        Refreshing Library
(11:18:21) INFO:    [Gog]:             Found 0 game(s) to update
(11:18:21) INFO:    [Frontend]:        Refreshing Library
(11:18:21) INFO:    [Gog]:             Found 0 game(s) to update
(11:18:21) INFO:    [Frontend]:        Refreshing Library
(11:18:21) INFO:    [Gog]:             Found 0 game(s) to update
(11:34:22) DEBUG:   [Backend]:         Unable to load Steam Libraries, libraryfolders.vdf not found
(11:34:22) DEBUG:   [Backend]:         Unable to load Steam Libraries, libraryfolders.vdf not found
(11:34:38) DEBUG:   [Legendary]:       Running Legendary command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary --version
(11:34:38) DEBUG:   [Gog]:             Running GOGDL command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --version
(11:46:15) INFO:    [Frontend]:        Refreshing Library
(11:46:15) INFO:    [Gog]:             Found 0 game(s) to update

### Steps to reproduce

1.Log in
2.Load the library

### Expected behavior

Showing the game I own when I go in my library

### System Information

Ubuntu 20.04.1 LTS
Heroic Version: 2.3.4 Brook

### Additional information

I tried to go in my config files : .var/app/com.heroicgameslauncher.hgl/config/
and to rm the legendary and heroic folders, then I logged again whith a new SID but it didn't fixed the problem

**Comment by flavioislima** [comment]
try this appimage;
https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/actions/runs/2408497584

**Comment by bradsevy** [comment]
I was having the same issue as OP on the Flatpak build. Switching to this AppImage resolved the issue.
