### ISSUE TITLE
GOG Library tab missing (2.3.5)

### ISSUE THREAD

**Issue by zeekzag** [Heroic-Games-Launcher/HeroicGamesLauncher#1412]
### Describe the bug

Library section for GOG is missing in the new 2.3.5 build.
Section doesn't expand like it used to and defaults to Epic.

Present in Windows and Fedora 36.

### Add logs

Heroic Version: 2.3.5 Brook
Legendary Version:  0.20.25 Our Benefactors
OS: Microsoft Windows 10 Pro KERNEL: 10.0.19043 ARCH: x64
CPU: AMD Ryzen 9 3900X 12-Core Processor @3.8 
RAM: Total: 31.92 GiB Available: 25.82 GiB
GRAPHICS: GPU0: NVIDIA GeForce RTX 3070 VRAM: 8192MB DRIVER: 512.15 

(14:40:12) WARNING: [Backend]:         Protocol already registered.
(14:40:12) INFO:    [Legendary]:       Installed game list updated
(14:40:13) INFO:    [Frontend]:        Refreshing Library
(14:40:13) INFO:    [Legendary]:       Refreshing library...
(14:40:13) INFO:    [Legendary]:       Refreshing Epic Games...
(14:40:13) DEBUG:   [Legendary]:       Running Legendary command: C:\Users\alpot\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\legendary list
(14:40:15) INFO:    [Legendary]:       Updating game list
(14:40:15) INFO:    [Legendary]:       Game List Updated
(14:40:15) INFO:    [Frontend]:        No cache found, getting data from legendary...
(14:40:15) INFO:    [Legendary]:       Refreshing library...
(14:40:15) INFO:    [Legendary]:       Updating game list
(14:40:15) INFO:    [Legendary]:       Game List Updated
(14:40:15) INFO:    [Legendary]:       Checking for game updates: C:\Users\alpot\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\legendary list-installed --check-updates --tsv
(14:40:15) DEBUG:   [Legendary]:       Running Legendary command: C:\Users\alpot\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\legendary list-installed --check-updates --tsv
(14:40:16) INFO:    [Legendary]:       Found 0 game(s) to update
(14:40:16) INFO:    [Gog]:             Found 0 game(s) to update
(14:40:16) INFO:    [Frontend]:        Force Update

### Steps to reproduce

1. Open Heroic
2. Click on Library
3. See that you can't access GOG games anymore

### Expected behavior

After clicking on Library button we should be presented with both Epic and GOG libraries.

### Screenshots

You can see the library highlighted here but there's no way to access GOG games anymore.

![2022-05-30 14_46_07-Heroic Games Launcher](https://user-images.githubusercontent.com/104680414/170995742-5d6110bd-0212-49b1-9826-e0475cd9dd8e.png)

### System Information

Windows 10 Pro
Fedora 36

**Comment by zeekzag** [comment]
After a few  hours of fiddling with this I downgraded to 2.3.3 and then updated to 2.3.5 again and the library seem to be back.

Not sure what might have caused the issue.

**Comment by flavioislima** [comment]
![image](https://user-images.githubusercontent.com/26871415/171005440-08227815-cb17-4396-bc42-d86e8e17c4ba.png)

Yes, was about to say that for me looks fine 👍🏽
