### ISSUE TITLE
Add Scoop (and other windows package manager) package(s)

### ISSUE THREAD

**Issue by TayouVR** [Heroic-Games-Launcher/HeroicGamesLauncher#1413]
### Problem description

I would like to have Heroic installed via a package manager, even on windows. It is just easier to install and update that way.

### Feature description

Scoop is in my eyes the easiest to use and most feature rich package manager for windows.
So I use it for anything, that is available via it.

### Alternatives

So far the package managers I'm aware of are; 
- Scoop (https://scoop.sh/ - community managed)
- Chocolatey (https://chocolatey.org/ - community managed)
- Winget (https://github.com/microsoft/winget-cli - microsoft managed, requires MS account)

Chocolatey and winget both don't really manage packages though, they are more more a registry for installers, winget even requiring a microsoft account to use.

Having a chocolatey package wouldn't be bad either though. 

### Additional information

I sadly don't know about the technicality of deploying builds to any of these package managers, but I would think, that all three of them could be automatically deployed via github actions.

**Comment by flavioislima** [comment]
Heroic is already on `winget`, its not official though.
Unfortunately we have no way of maintaining this windows repos right now.
You can find the winget information on the readme.
