### ISSUE TITLE
Black screen when launching a game

### ISSUE THREAD

**Issue by Nino155** [Heroic-Games-Launcher/HeroicGamesLauncher#1414]
### Describe the bug

I have a black screen when trying to launch Darkest dungeon II on Heroic. I tried different version of wine and enable DXVK but it's still not working.

### Add logs

(15:37:00) DEBUG:   [Legendary]:       Running Legendary command: /tmp/.mount_HeroicAIHx8N/resources/app.asar.unpacked/build/bin/linux/legendary --version
(15:37:01) INFO:    [Legendary]:       Legendary location: /tmp/.mount_HeroicAIHx8N/resources/app.asar.unpacked/build/bin/linux/legendary
(15:37:01) INFO:    [Gog]:             GOGDL location: /tmp/.mount_HeroicAIHx8N/resources/app.asar.unpacked/build/bin/linux/gogdl
(15:37:01) INFO:    [Backend]:         

Heroic Version: 2.3.5 Brook
Legendary Version:  0.20.25 Our Benefactors
OS: Ubuntu KERNEL: 5.13.0-44-generic ARCH: x64
CPU: Intel Core™ i3-6100H @2.7 GOVERNOR: powersave
RAM: Total: 7.65 GiB Available: 3.55 GiB
GRAPHICS: GPU0: HD Graphics 530  VRAM: 256MB DRIVER:  
PROTOCOL: x11

(15:37:01) WARNING: [Backend]:         Failed to register protocol with OS.
(15:37:04) INFO:    [Frontend]:        Refreshing Library
(15:37:04) INFO:    [Legendary]:       Refreshing library...
(15:37:04) INFO:    [Legendary]:       Refreshing Epic Games...
(15:37:04) INFO:    [DXVKInstaller]:   Updating vkd3d to: vkd3d-proton-2.6
(15:37:04) DEBUG:   [Legendary]:       Running Legendary command: /tmp/.mount_HeroicAIHx8N/resources/app.asar.unpacked/build/bin/linux/legendary list
(15:37:05) INFO:    [Backend]:         Downloaded Winetricks
(15:37:05) INFO:    [DXVKInstaller]:   downloaded vkd3d
(15:37:05) INFO:    [DXVKInstaller]:   extracting vkd3d
(15:37:06) ERROR:   [DXVKInstaller]:   Extraction of vkd3d failed with: Error: Command failed: tar -I zstd -xvf /home/nino/.config/heroic/tools/vkd3d/vkd3d-proton-2.6.tar.zst -C /home/nino/.config/heroic/tools/vkd3d
tar (child): zstd: Cannot exec: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now

(15:37:06) INFO:    [Legendary]:       Updating game list
(15:37:06) INFO:    [Legendary]:       Game List Updated
(15:37:07) INFO:    [Legendary]:       Checking for game updates: /tmp/.mount_HeroicAIHx8N/resources/app.asar.unpacked/build/bin/linux/legendary list-installed --check-updates --tsv
(15:37:07) DEBUG:   [Legendary]:       Running Legendary command: /tmp/.mount_HeroicAIHx8N/resources/app.asar.unpacked/build/bin/linux/legendary list-installed --check-updates --tsv
(15:37:09) INFO:    [Legendary]:       Found 0 game(s) to update
(15:37:09) INFO:    [Gog]:             Found 0 game(s) to update
(15:37:37) DEBUG:   [Backend]:         Unable to load Steam Libraries, libraryfolders.vdf not found
(15:37:41) INFO:    [DXVKInstaller]:   Removing vkd3d version information
(15:37:41) ERROR:   [DXVKInstaller]:   error when removing DXVK, please try again Error: Command failed: PATH=/home/nino/.local/share/lutris/runners/wine/lutris-fshack-7.2-x86_64/bin:$PATH WINEPREFIX='/home/nino/Games/Heroic/Prefixes/DarkestDungeonII' bash /home/nino/.config/heroic/tools/vkd3d/vkd3d-proton-2.6/setup*.sh uninstall --symlink
bash: /home/nino/.config/heroic/tools/vkd3d/vkd3d-proton-2.6/setup*.sh: No such file or directory

(15:37:45) INFO:    [Backend]:         Launching Darkest Dungeon II (Suka)
(15:37:45) DEBUG:   [Legendary]:       Running Wine command: "/home/nino/.local/share/lutris/runners/wine/lutris-fshack-7.2-x86_64/bin/wine" wineboot --init
(15:37:50) DEBUG:   [Legendary]:       Ran Wine command: "/home/nino/.local/share/lutris/runners/wine/lutris-fshack-7.2-x86_64/bin/wine" wineboot --init
(15:37:50) INFO:    [Legendary]:       Launching Darkest Dungeon II: WINEPREFIX=/home/nino/Games/Heroic/Prefixes/DarkestDungeonII WINEESYNC=1 /tmp/.mount_HeroicAIHx8N/resources/app.asar.unpacked/build/bin/linux/legendary launch Suka --wine /home/nino/.local/share/lutris/runners/wine/lutris-fshack-7.2-x86_64/bin/wine --wine-prefix /home/nino/Games/Heroic/Prefixes/DarkestDungeonII
(15:37:50) DEBUG:   [Legendary]:       Running Legendary command: WINEPREFIX=/home/nino/Games/Heroic/Prefixes/DarkestDungeonII WINEESYNC=1 /tmp/.mount_HeroicAIHx8N/resources/app.asar.unpacked/build/bin/linux/legendary launch Suka --wine /home/nino/.local/share/lutris/runners/wine/lutris-fshack-7.2-x86_64/bin/wine --wine-prefix /home/nino/Games/Heroic/Prefixes/DarkestDungeonII

### Steps to reproduce

Launch heroic
Log in 
launch darkest dungeon II

### Expected behavior

The game launch and work

### System Information

Ubuntu 20.04.1 LTS
Heroic Version: 2.3.5 Brook

**Comment by flavioislima** [comment]
This is not an issue with Heroic.
For help with games go to the discord  or open a discussion on github.

Also, install the `zstd` package to avoid getting those errors with vkd3d
