### ISSUE TITLE
[SteamDeck] Heroic Games Launcher will not open

### ISSUE THREAD

**Issue by novasheikh** [Heroic-Games-Launcher/HeroicGamesLauncher#1417]
### Describe the bug

I have encountered a bug where heroic games launcher refuses to open. It installs ok and in system monitor I see it running but the actual window for the application never appears. I have Uninstalled and reinstalled it several times. I even went to the github to download it directly but weirdly enough that github installation never officially registered on my device in the menu (it was the app image version and I can't figure out how to uninstall that version). I wonder if it is possible that the github installation remains on my device and is preventing the installation from discover from working correctly.

For what it is worth, things at least launched for me with heroic before I tried installing the github app image. I appreciate any advice or help!

### Add logs

N/A

### Steps to reproduce

1. Go to 'Heroic Games Launcher'
2. Click on 'Heroic Games Launcher'
3. No window opens up but it is running in system monitor

### Expected behavior

I expect a window with the GUI for the Heroic Games Launcher to appear

### System Information

- OS [e. g. "Ubuntu"]: Steam Deck OS 3.2
- Heroic Version [e. g. 2.1.1]: 2.3.4

**Comment by novasheikh** [comment]
https://youtu.be/uItIxJuD1y8

Here is a video of the problem

**Comment by novasheikh** [comment]
(deck@steamdeck ~)$ flatpak run org.heroicgameslauncher.com
error: app/org.heroicgameslauncher.com/x86_64/master not installed
(1)(deck@steamdeck ~)$

**Comment by novasheikh** [comment]
I tried executing the 2.3.5 appimage in konsole but get this error message:

(21:23:53) DEBUG:   [Legendary]:       Running Legendary command: /home/deck/Downloads/legendary.exe --version
(node:6267) UnhandledPromiseRejectionWarning: TypeError: Cannot read properties of undefined (reading 'replaceAll')
    at getLegendaryVersion (/tmp/.mount_HeroicMfbZoi/resources/app.asar/build/utils.js:159:9)
    at async getSystemInfo (/tmp/.mount_HeroicMfbZoi/resources/app.asar/build/utils.js:221:30)
    at async /tmp/.mount_HeroicMfbZoi/resources/app.asar/build/main.js:221:28
(Use `heroic --trace-warnings ...` to show where the warning was created)
(node:6267) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
[6308:0531/212354.042866:ERROR:sandbox_linux.cc(377)] InitializeSandbox() called with multiple threads in process gpu-process.

**Comment by flavioislima** [comment]
This is on the steam deck and it is running the windows version of legendary:
`/home/deck/Downloads/legendary.exe -`
 ???

I think something wrong is not right, send the full log.
It seems like you downloaded a windows version of legendary and selected it on the `alternative legendary binary`

**Comment by flavioislima** [comment]
> (deck@steamdeck ~)$ flatpak run org.heroicgameslauncher.com error: app/org.heroicgameslauncher.com/x86_64/master not installed (1)(deck@steamdeck ~)$

This one its not installed.
You need to go to the Discover store and install Heroic from there.

**Comment by imLinguin** [comment]
A little note: name of heroic in flatpak is actually
`com.heroicgameslauncher.hgl`

**Comment by flavioislima** [comment]
> A little note: name of heroic in flatpak is actually `com.heroicgameslauncher.hgl`

yes, a lot of things are wrong here.

**Comment by novasheikh** [comment]
> This is on the steam deck and it is running the windows version of legendary: `/home/deck/Downloads/legendary.exe -` ???
> 
> I think something wrong is not right, send the full log. It seems like you downloaded a windows version of legendary and selected it on the `alternative legendary binary`

I fixed the issue by simply deleting legendary.exe

Thanks for all the help. I feel like learning Linux is taking me back to the 90s when I had to learn DOS command prompts to be able to play these games lol.

**Comment by Jetsbro** [comment]
Could you possibly explain what to do in the simplest terms lol thanks
