### ISSUE TITLE
Epic games not showing in Library and epic account loging issues(Flatpak)

### ISSUE THREAD

**Issue by syeedahmed** [Heroic-Games-Launcher/HeroicGamesLauncher#1419]
### Describe the bug

Library not showing any epic games and also facing some problem to login in Epic account. like after login is stuck in sid page 5-6 time refresh don't do any thing.
after sometime manage to login in account but Library is empty.

### Add logs

flatpak run com.heroicgameslauncher.hgl
Gtk-Message: 12:54:22.728: Failed to load module "canberra-gtk-module"
Gtk-Message: 12:54:22.728: Failed to load module "pk-gtk-module"
Gtk-Message: 12:54:22.728: Failed to load module "canberra-gtk-module"
Gtk-Message: 12:54:22.728: Failed to load module "pk-gtk-module"
[3:0531/125422.742610:ERROR:bus.cc(397)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[3:0531/125422.742726:ERROR:bus.cc(397)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
(12:54:22) DEBUG:   [Legendary]:       Running Legendary command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary --version
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
[42:0531/125422.828855:ERROR:sandbox_linux.cc(377)] InitializeSandbox() called with multiple threads in process gpu-process.
hostname: invalid option -- 'f'
Try 'hostname --help' for more information.
(12:54:23) INFO:    [Legendary]:       Legendary location: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary
(12:54:23) INFO:    [Gog]:             GOGDL location: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl
(12:54:23) INFO:    [Backend]:         

Heroic Version: 2.3.4 Brook
Legendary Version:  0.20.25 Our Benefactors
OS: Freedesktop.org KERNEL: 5.17.11-300.fc36.x86_64 ARCH: x64
CPU: AMD Ryzen 5 3400G with Radeon Vega Graphics @3.7 GOVERNOR: schedutil
RAM: Total: 13.64 GiB Available: 11.44 GiB
GRAPHICS: GPU0: Picasso VRAM: 512MB DRIVER:  
PROTOCOL: wayland

(12:54:23) INFO:    [Backend]:         User Not Found, removing it from Store
APPIMAGE env is not defined, current application is not an AppImage
LaunchProcess: failed to execvp:
xdg-settings
(12:54:23) WARNING: [Backend]:         Failed to register protocol with OS.
[3:0531/125423.731601:ERROR:browser_main_loop.cc(269)] Gtk: gtk_widget_add_accelerator: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed
[3:0531/125423.731681:ERROR:browser_main_loop.cc(269)] Gtk: gtk_widget_add_accelerator: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed
[3:0531/125423.731760:ERROR:browser_main_loop.cc(269)] Gtk: gtk_widget_add_accelerator: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed
[3:0531/125423.902323:ERROR:browser_main_loop.cc(269)] Gdk: gdk_window_thaw_toplevel_updates: assertion 'window->update_and_descendants_freeze_count > 0' failed
[42:0531/125427.271410:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 1 times!
(12:54:27) INFO:    [Backend]:         Downloaded Winetricks
[42:0531/125431.788278:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 2 times!
[42:0531/125435.892995:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 3 times!
(12:55:51) INFO:    [Frontend]:        Refreshing wine downloader releases
(12:55:51) INFO:    [WineDownloader]:  Updating wine versions info
(12:55:51) INFO:    [WineDownloader]:  Fetching upstream information...
(12:55:55) INFO:    [WineDownloader]:  wine versions updated
(12:56:14) INFO:    [Frontend]:        Refreshing wine downloader releases
(12:56:14) INFO:    [WineDownloader]:  Updating wine versions info
(12:56:14) INFO:    [WineDownloader]:  Fetching upstream information...
(12:56:17) INFO:    [WineDownloader]:  wine versions updated
(12:56:35) INFO:    [Legendary]:       Logging in with Legendary: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary auth --sid <redacted>
(12:56:35) DEBUG:   [Legendary]:       Running Legendary command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary auth --sid <redacted>
(12:56:39) INFO:    [Frontend]:        Refreshing Library
(12:56:39) INFO:    [Legendary]:       Refreshing library...
(12:56:39) INFO:    [Legendary]:       Refreshing Epic Games...
(12:56:40) DEBUG:   [Legendary]:       Running Legendary command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary list
(12:56:45) INFO:    [Legendary]:       Updating game list
(12:56:45) INFO:    [Legendary]:       Game List Updated
(12:56:45) INFO:    [Frontend]:        No cache found, getting data from legendary...
(12:56:45) INFO:    [Legendary]:       Refreshing library...
(12:56:45) INFO:    [Legendary]:       Updating game list
(12:56:45) INFO:    [Legendary]:       Game List Updated
(12:56:45) INFO:    [Frontend]:        Force Update
(12:56:52) INFO:    [Frontend]:        Refreshing Library
(12:56:52) INFO:    [Gog]:             Found 0 game(s) to update

### Steps to reproduce

try to login with Epic account

### Expected behavior

facing some problem to login in Epic account
Library not showing any epic games

### Screenshots

![Screenshot from 2022-05-31 12-55-25](https://user-images.githubusercontent.com/62342624/171112981-79fc0088-8017-41bf-9785-7242370ab8d4.png)
![Screenshot from 2022-05-31 12-54-04](https://user-images.githubusercontent.com/62342624/171113002-0edf1072-dbbc-4dc1-a05e-c8dfd6e64a3c.png)

### System Information

OS: Fedora Linux 36 (Workstation Edition) x86_64
Kernel: 5.17.11-300.fc36.x86_64
CPU: AMD Ryzen 5 3400G (8) @ 4.000GHz
GPU: AMD ATI Radeon Vega Series / Radeon Vega Mobile Series

**Comment by mrbenino** [comment]
I seem to have encountered the same problem on the m1 pro processor. Only the library does not open at all for me, but instead it offers to go to the epic store

Heroic version 2.3.7

**Comment by christianda** [comment]
> I seem to have encountered the same problem on the m1 pro processor. Only the library does not open at all for me, but instead it offers to go to the epic store
> 
> Heroic version 2.3.7

I went to Manage Accounts > Log in > Go to Library and it fixed this issue. I did this in Heroic Games Launcher in desktop mode.
