### ISSUE TITLE
[Linux] Gamescope mouse input gone after update to 2.3.6

### ISSUE THREAD

**Issue by InsaneCake** [Heroic-Games-Launcher/HeroicGamesLauncher#1422]
### Describe the bug

After update from 2.3.2 to 2.3.5 if heroic launched with gamescope - no mouse input to the game, but in heoic itself it works
So now Heroic unusable with gamescope

upd: 2.3.6 still here

### Add logs

(11:01:20) DEBUG:   [Legendary]:       Running Legendary command: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary --version
(11:01:20) INFO:    [Legendary]:       Legendary location: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary
(11:01:20) INFO:    [Gog]:             GOGDL location: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl
(11:01:20) INFO:    [Backend]:         

Heroic Version: 2.3.5 Brook
Legendary Version:  0.20.25 Our Benefactors
OS: ManjaroLinux KERNEL: 5.17.9-1-MANJARO ARCH: x64
CPU: AMD Ryzen 5 3600X 6-Core Processor @3.8 GOVERNOR: schedutil
RAM: Total: 15.55 GiB Available: 12.51 GiB
GRAPHICS: GPU0: Navi 23 [Radeon RX 6600/6600 XT/6600M] VRAM: 1MB DRIVER:  
PROTOCOL: x11

(11:01:20) WARNING: [Backend]:         Failed to register protocol with OS.
(11:01:21) INFO:    [Frontend]:        Refreshing Library
(11:01:21) INFO:    [Legendary]:       Refreshing library...
(11:01:21) INFO:    [Legendary]:       Refreshing Epic Games...
(11:01:22) DEBUG:   [Legendary]:       Running Legendary command: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary list
(11:01:23) INFO:    [Legendary]:       Updating game list
(11:01:23) INFO:    [Legendary]:       Game List Updated
(11:01:23) INFO:    [Backend]:         Downloaded Winetricks
(11:01:24) INFO:    [Legendary]:       Checking for game updates: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary list-installed --check-updates --tsv
(11:01:24) DEBUG:   [Legendary]:       Running Legendary command: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary list-installed --check-updates --tsv
(11:01:26) INFO:    [Legendary]:       Found 3 game(s) to update
(11:01:26) INFO:    [Gog]:             Found 0 game(s) to update

### Steps to reproduce

1. run "gamescope -w 2377 -h 1337 -W 2560 -H 1440 -r 72 -U -f -- heroic"
2. launch game
3. try interact with something by mouse

### Expected behavior

After heroic launched with gamescope and game launched from it mouse input should work in game (and it was in 2.3.2)

### System Information

OS: Manjaro
Heroic 2.3.5-1 installed from [AUR](https://aur.archlinux.org/packages/heroic-games-launcher-bin)

**Comment by flavioislima** [comment]
Can you try adding:
`gamescope -w 2377 -h 1337 -W 2560 -H 1440 -r 72 -U -f `
to the game settings under Environmental Variables?
You can add wrappers there now.

**Comment by InsaneCake** [comment]
In my case - gamescope works, but mouse input still does not works.
I checked different games, resolutions, without mangohud and without fps limiter.
Maybe problem in something outdated in manjaro repos.
In Steam works as intended, in Lutris i dont find out how made it work at all.

**Comment by flavioislima** [comment]
I tested with bioshock infinite and got mouse input and controller working. Using same command as you tried.
I'm on Garuda so should be similar to manjaro I guess. But I'm using gamescope stable and not git.

**Comment by flavioislima** [comment]
The image doesn't work. You can upload in the thread.

**Comment by InsaneCake** [comment]
![UZIdS9G_d](https://user-images.githubusercontent.com/14079980/171790407-8450052a-be90-4430-91d6-fe1cea2c38cd.png)

**Comment by InsaneCake** [comment]
I have found [this gamescope bug](https://github.com/Plagman/gamescope/issues/420)
In steam I actuly add `-e` option, but absolutely forget about it.
In Heroic with `-e` games (or launcher) dont start at all. It enables some kind of steam integration, so i don't know should it work outside steam or not.
