### ISSUE TITLE
Installing a game no longer reports percentage installed

### ISSUE THREAD

**Issue by Etaash-mathamsetty** [Heroic-Games-Launcher/HeroicGamesLauncher#1425]
### Describe the bug

No percentage is being shown when I try installing a game :(

### Add logs

it looks like this now
`(17:31:47) INFO:    [Backend]:         Progress for bc2c95c6ff564a16b26644f1d3ac3c55: 8.93%/1350.35MiB/00:03:42`

### Steps to reproduce

install bioshock i guess?

### Expected behavior

I used to show a percentage last version, something changed in the lengendary backend

### Screenshots

![image](https://user-images.githubusercontent.com/45927311/171505652-4fad8847-25fa-4e9a-bded-97177884b2ab.png)

### System Information

- OS Arch Linux
- Heroic Version Latest:

**Comment by flavioislima** [comment]
That's not on Legendary, that's on me what did change how we get the progress to fix another bug.
Will fix soon.
