### ISSUE TITLE
[Feature Request] Sync play time with epic servers

### ISSUE THREAD

**Issue by JFMugen** [Heroic-Games-Launcher/HeroicGamesLauncher#1429]
### Problem description

Currently, how much I played doesn't saved online. 

### Feature description

I would like to have this feature so I can see how much I played a game, even when I check from my profile (in future probably) or from the official or heroic launcher.

**Comment by flavioislima** [comment]
I am not sure if this is possible but will keep it here to check in the future.

**Comment by JFMugen** [comment]
> I am not sure if this is possible but will keep it here to check in the future.

I remember talking about this in Legendary github, and they were telling a GUI is needed to track the time by running in the background. 

I hope you can work together for this, or maybe you can just write your own code to connect API? Either way, good luck and I hope we can see this feature in a close future ^^

**Comment by flavioislima** [comment]
Forgot that we already have an issue for that and also with a possible solution for it.
#1240
