### ISSUE TITLE
enableResizableBar: Cannot modify VKD3D_CONFIG environment variable

### ISSUE THREAD

**Issue by jhunkeler** [Heroic-Games-Launcher/HeroicGamesLauncher#1431]
### Describe the bug

https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/blob/25fe2ad601b0896650dfb28fcd4fa2c7fcd5b1fb/electron/launcher.ts#L289-L291

When resizable bar is enabled through the interface the user cannot modify `VKD3D_CONFIG` using `Setttings -> Other -> Advanced Options`.

**Current workaround:**
When the resizable bar option is disabled the user can modify the variable (to include adding `upload_hvv` themselves if need be)

### Add logs

```
(10:15:20) INFO:    [Legendary]:       Launching HITMAN 3: PULSE_LATENCY_MSEC=60 VKD3D_CONFIG=upload_hvv RADV_PERFTEST=rt STEAM_COMPAT_CLIENT_INSTALL_PATH=/home/jhunk/.steam/steam STEAM_COMPAT_DATA_PATH=/home/jhunk/Games/Heroic/Prefixes/HITMAN3 WINE_FULLSCREEN_FSR=1 WINE_FULLSCREEN_FSR_STRENGTH=2 STEAM_COMPAT_APP_ID=0 SteamAppId=0 SteamGameId=heroic-HITMAN3 PROTON_LOG_DIR=/home/jhunk /usr/bin/mangohud --dlsym /usr/bin/gamemoderun /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary launch Eider --no-wine --wrapper "'/home/example/.local/share/Steam/compatibilitytools.d/GE-Proton7-20/proton' run"
```

### Steps to reproduce

1. Click Library
2. Click a game
3. Click `Settings`
4. (left-hand tree) Click `Wine`
5. Enable checkbox `Enable Resizable BAR (NVIDIA RTX 30xx only)`
6. (left-hand tree) Click `Other`
7. Under `Advanced Options (Environment Variables)` enter,
```
VKD3D_CONFIG=dxr11 RADV_PERFTEST=rt
```
8. Click `<-` "back" arrow
9. Click `PLAY NOW` button

### Expected behavior

The value `upload_hvv` is appended to `VKD3D_CONFIG` (a comma delimited list). Alternatively the user's input can be appended to `VKD3D_CONFIG`. The order of the options is irrelevant.

```
[...] Launching HITMAN 3: PULSE_LATENCY_MSEC=60 VKD3D_CONFIG=dxr11,upload_hvv RADV_PERFTEST=rt #[...]
```

### System Information

- OS: Manjaro Linux
- Heroic Version: 2.3.7

**Comment by flavioislima** [comment]
@jhunkeler can you check if this was fixed on the new release?

**Comment by jhunkeler** [comment]
Doesn't look like the latest release addresses this.

```
Heroic Version: 2.4.3 Chopper
Legendary Version:  0.20.28 Dark Energy (hotfix #2)
```

- Resizable Bar is enabled.
- `VKD3D_CONFIG` is set to `dxr11`

I launch the game and the result is:
```
(14:10:02) INFO: [Gog]: Launching Cyberpunk 2077: PULSE_LATENCY_MSEC=60 VKD3D_CONFIG=upload_hvv [...]
```

`VKD3D_CONFIG` should have been `upload_hvv,dxr11`, not `upload_hvv`.

**Comment by arielj** [comment]
We are removing the configuration since it seems ResizableBar have been on by default for over a year already https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/pull/1921.

Closing this issue since we won't have the toggle anymore so we won't override env variables
