### ISSUE TITLE
Can't uninstall game from Library

### ISSUE THREAD

**Issue by krablord** [Heroic-Games-Launcher/HeroicGamesLauncher#1433]
### Describe the bug

Can't uninstall game from library

### Add logs

(17:40:32) DEBUG:   [Legendary]:       Running Legendary command: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary --version
(17:40:33) INFO:    [Legendary]:       Legendary location: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary
(17:40:33) INFO:    [Gog]:             GOGDL location: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl
(17:40:33) INFO:    [Backend]:         
  Heroic Version: 2.3.3 Brook
  Legendary Version:  0.20.25 Our Benefactors
  OS: Ubuntu KERNEL: 5.17.0-11.1-liquorix-amd64 ARCH: x64
  CPU: Intel Xeon® E5-2620 v3 @2.4 GOVERNOR: ondemand
  RAM: Total: 15.48 GiB Available: 13.65 GiB
  GRAPHICS: GPU0: NVIDIA GeForce GTX 970 VRAM: 4041MB DRIVER: 470.129.06 
  PROTOCOL: x11
  
(17:40:33) INFO:    [Backend]:         User Not Found, removing it from Store
(17:40:33) INFO:    [Gog]:             Getting data about the user
(17:40:33) INFO:    [Gog]:             Refreshing access_token
(17:40:33) WARNING: [Backend]:         Protocol already registered.
(17:40:33) INFO:    [Gog]:             Token refreshed successfully
(17:40:34) INFO:    [Frontend]:        Refreshing Library
(17:40:34) INFO:    [Legendary]:       Refreshing library...
(17:40:34) INFO:    [Gog]:             Getting GOG library
(17:40:34) INFO:    [Gog]:             Saved user data to config
(17:40:35) INFO:    [Gog]:             Number of library pages: 2
(17:40:35) INFO:    [Gog]:             Getting data for page 2
(17:40:36) INFO:    [Gog]:             Saved games data
(17:40:37) ERROR:   [Frontend]:        Error: Error invoking remote method 'checkGameUpdates': Error: self signed certificate
(17:41:08) INFO:    [Legendary]:       Uninstalling Ginger: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary uninstall Ginger -y
(17:41:08) DEBUG:   [Legendary]:       Running Legendary command: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary uninstall Ginger -y
(17:41:08) INFO:    [Backend]:         finished uninstalling
(17:41:08) INFO:    [Backend]:         Desktop shortcut removed
(17:41:08) INFO:    [Backend]:         Applications shortcut removed
(17:41:08) INFO:    [Frontend]:        Refreshing Library
(17:41:08) INFO:    [Legendary]:       Refreshing library...
(17:41:08) INFO:    [Gog]:             Getting GOG library
(17:41:09) INFO:    [Gog]:             Number of library pages: 2
(17:41:09) INFO:    [Gog]:             Getting data for page 2
(17:41:10) INFO:    [Gog]:             Saved games data

### Steps to reproduce

1. Go to 'Library'
2. Right Click on 'Cyberpunk 2077'
3. Click Uninstall
4. See "Uninstalled" window appear
5. Game is still in Library, though folder is empty and can't start the game

### Expected behavior

Game uninstalls from Library and not showed as installed

### Screenshots

https://user-images.githubusercontent.com/94720169/172008319-93c272cf-c8d0-40d2-a410-e099ad658114.mp4

### System Information

- OS [e. g. "Ubuntu"]: Ubuntu 20.04.04
- Heroic Version [e. g. 2.1.1]: 2.3.3 Brook

**Comment by flavioislima** [comment]
Try on 2.3.7.
If you click play it will show a window saying that the game folder was deleted and will ask if you want to remove from installed. Just click yes.

**Comment by krablord** [comment]
Login to Epic Games expired, but it didn't show that anywhere - so logging in again fixed it
