### ISSUE TITLE
Space in the install folder

### ISSUE THREAD

**Issue by heema** [Heroic-Games-Launcher/HeroicGamesLauncher#1434]
### Describe the bug

If there is a space in the install folder it will give an error game not found
the install game folder is: "/mnt/Win_Y/Games/Epic Games/FFVIIRemakeIntergrade"
the error is: "Games/FFVIIRemakeIntergrade" (No such file or directory)

### Add logs

Launch Command: STEAM_COMPAT_CLIENT_INSTALL_PATH=/home/user/.steam/steam STEAM_COMPAT_DATA_PATH=/mnt/Win_Y/Games/Linux/Heroic/Prefixes/FFVIIRemakeIntergrade STEAM_COMPAT_APP_ID=0 SteamAppId=0 SteamGameId=heroic-FFVIIRemakeIntergrade PROTON_LOG_DIR=/home/user /tmp/.mount_Heroicht5IKI/resources/app.asar.unpacked/build/bin/linux/legendary launch b25ba0f04dc9434f8a04a062719e7aa7 --no-wine --wrapper "/home/user/.local/share/Steam/steamapps/common/SteamLinuxRuntime_soldier/run --filesystem=/mnt/Win_Y/Games/Epic Games/FFVIIRemakeIntergrade -- '/home/user/.local/share/Steam/compatibilitytools.d/GE-Proton7-20/proton' waitforexitandrun"

System Info:
Heroic Version: 2.3.7 Brook
Legendary Version:  0.20.26 Dark Energy
OS: ManjaroLinux KERNEL: 5.18.1-1-MANJARO ARCH: x64
CPU: AMD Ryzen 9 3900X 12-Core Processor @3.8 GOVERNOR: schedutil
RAM: Total: 15.63 GiB Available: 12.99 GiB
GRAPHICS: GPU0: NVIDIA GeForce RTX 3070 Ti VRAM: 8192MB DRIVER: 515.48.07 
PROTOCOL: x11

Game Settings: {
	"autoInstallDxvk": false,
	"autoInstallVkd3d": false,
	"autoSyncSaves": true,
	"maxSharpness": 2,
	"nvidiaPrime": false,
	"otherOptions": "",
	"savesPath": "/mnt/Win_Y/Games/Linux/Heroic/Prefixes/FFVIIRemakeIntergrade/pfx/drive_c/users/steamuser/My Documents/My Games/FINAL FANTASY VII REMAKE/EOS/c29e952e555b4cde9e70451ca65e9bb0/",
	"showFps": false,
	"targetExe": "",
	"useGameMode": false,
	"wineCrossoverBottle": "Heroic",
	"winePrefix": "/mnt/Win_Y/Games/Linux/Heroic/Prefixes/FFVIIRemakeIntergrade",
	"wineVersion": {
		"bin": "/home/user/.local/share/Steam/compatibilitytools.d/GE-Proton7-20/proton",
		"name": "Proton - GE-Proton7-20",
		"type": "proton"
	},
	"useSteamRuntime": true
}

Error Log:
[cli] INFO: Logging in...
[Core] INFO: Trying to re-use existing login session...
[cli] INFO: Checking for updates...
[Core] INFO: Getting authentication token...
[cli] INFO: Launching b25ba0f04dc9434f8a04a062719e7aa7...
pressure-vessel-LOG-0x100: Failed to execute child process "Games/FFVIIRemakeIntergrade" (No such file or directory)

### Steps to reproduce

1. Have a install folder with a space in the folder
2. Click on 'Launch'
3. Scroll down to 'Tools - Latest Log'

### Expected behavior

Have game run in a folder with a space in the name

### System Information

- OS [ManjaroLinux KERNEL: 5.18.1-1-MANJARO ARCH: x64]: 
- Heroic Version [2.3.7]:

**Comment by Ateeq72** [comment]
Still the issue seems to persist in v2.4.3

Installation Path: /run/media/ateeq-ahmed/My Data Two/Games/Epic Games/GTAV

Log:

```
System Info:
Heroic Version: 2.4.3 Chopper
Legendary Version:  0.20.28 Dark Energy (hotfix #2)
OS: ManjaroLinux KERNEL: 5.15.74-3-MANJARO ARCH: x64
CPU: Intel Core™ i5-7200U @2.5 GOVERNOR: powersave
RAM: Total: 15.5 GiB Available: 6.03 GiB
GRAPHICS: GPU0: HD Graphics 620  VRAM: 256MB DRIVER:  GPU1: NVIDIA GeForce 940MX VRAM: 2048MB DRIVER: 520.56.06 
PROTOCOL: x11

Game Settings: {
	"audioFix": false,
	"autoInstallDxvk": true,
	"autoInstallVkd3d": false,
	"preferSystemLibs": false,
	"maxSharpness": 2,
	"language": "",
	"nvidiaPrime": true,
	"enviromentOptions": [],
	"wrapperOptions": [],
	"savesPath": "",
	"showFps": false,
	"showMangohud": false,
	"targetExe": "",
	"useGameMode": false,
	"winePrefix": "/home/ateeq-ahmed/.wine",
	"wineVersion": {
		"bin": "/home/ateeq-ahmed/.config/heroic/tools/wine/Wine-GE-Proton7-32/bin/wine",
		"name": "Wine - Wine-GE-Proton7-32",
		"type": "wine",
		"lib": "/home/ateeq-ahmed/.config/heroic/tools/wine/Wine-GE-Proton7-32/lib64",
		"lib32": "/home/ateeq-ahmed/.config/heroic/tools/wine/Wine-GE-Proton7-32/lib",
		"wineserver": "/home/ateeq-ahmed/.config/heroic/tools/wine/Wine-GE-Proton7-32/bin/wineserver",
		"wineboot": "/home/ateeq-ahmed/.config/heroic/tools/wine/Wine-GE-Proton7-32/bin/wineboot"
	},
	"useSteamRuntime": false,
	"eacRuntime": false,
	"battlEyeRuntime": false,
	"gogSaves": []
}

Game launched at: Wed Oct 26 2022 10:51:20 GMT+0530 (India Standard Time)

Launch Command: DRI_PRIME=1 __NV_PRIME_RENDER_OFFLOAD=1 __GLX_VENDOR_LIBRARY_NAME=nvidia LD_PRELOAD= WINEPREFIX=/home/ateeq-ahmed/.wine LD_LIBRARY_PATH=/home/ateeq-ahmed/.config/heroic/tools/wine/Wine-GE-Proton7-32/lib:/home/ateeq-ahmed/.config/heroic/tools/wine/Wine-GE-Proton7-32/lib64: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary launch 9d2d0eb64d5c44529cece33fe2a46482 --language en  --wine /home/ateeq-ahmed/.config/heroic/tools/wine/Wine-GE-Proton7-32/bin/wine --wine-prefix /home/ateeq-ahmed/.wine

Game Log:
[cli] INFO: Logging in...
[Core] INFO: Trying to re-use existing login session...
[cli] INFO: Checking for updates...
[Core] INFO: Getting authentication token...
[cli] INFO: Launching 9d2d0eb64d5c44529cece33fe2a46482...
Traceback (most recent call last):
  File "legendary/cli.py", line 3054, in <module>
  File "legendary/cli.py", line 2969, in main
  File "legendary/cli.py", line 692, in launch_game
  File "subprocess.py", line 951, in __init__
  File "subprocess.py", line 1821, in _execute_child
FileNotFoundError: [Errno 2] No such file or directory: '/run/media/ateeq-ahmed/My'
[829174] Failed to execute script 'cli' due to unhandled exception!

```

Can I have a fix or workaround for this?. 

Thanks...
