### ISSUE TITLE
Back to top button overlaps install button of last game card

### ISSUE THREAD

**Issue by arielj** [Heroic-Games-Launcher/HeroicGamesLauncher#1436]
### Describe the bug

If the last row of the games grid is full, the Back to Top button overlaps the last card Install icon, making it hard to click

### Add logs

not relvant

### Steps to reproduce

1. Go to the Lbirary
2. resize the screen or do a search to have a full last row of games and scroll down

### Expected behavior

The back to top button should not overlap the last card's install button.

### Screenshots

![image](https://user-images.githubusercontent.com/188464/172064411-c7360da2-3b4a-4717-aebc-415fc97e7016.png)

### System Information

- OS [e. g. "Ubuntu"]: LInux MInt
- Heroic Version [e. g. 2.1.1]: 2.3.6

### Additional information

I can imagine 2 solutions:
- move the `back to top` button to a different place
- add extra padding/margin after the last row to allow scrolling past the back to top button (I think I like this better)

There are probably other possible solutions.

**Comment by arielj** [comment]
Closing since this was fixed in beta and will be in the next release.

**Comment by arielj** [comment]
This is happening again

**Comment by Etaash-mathamsetty** [comment]
> This is happening again

in the beta or in stable?

**Comment by Etaash-mathamsetty** [comment]
Could this be closed again?
