### ISSUE TITLE
No progress displayed whilst updating game

### ISSUE THREAD

**Issue by pwatk** [Heroic-Games-Launcher/HeroicGamesLauncher#1445]
### Describe the bug

Whilst installing the recent update for Borderlands 3 there is no progress displayed.

This is the first game I have updated using Heroic and I believe there is a progress bar above the text  `Updating Game ...` that should be functional.

The log file is filled with the same error which I believe is preventing the progress bar from functioning.

### Add logs

...
(20:09:34) ERROR:   [Backend]:         TypeError: Cannot read properties of null (reading 'download_size')
...

### Steps to reproduce

1. Go to Borderlands 3
2. Click on Update game
3. Scroll down to 'Updating Game ...'
4. See empty progress bar
5. See errors in log

### Expected behavior

Progress bar filling as game update is installed.

### System Information

- OS [e. g. "Ubuntu"]: MacOS 12.4
- Heroic Version [e. g. 2.1.1]: 2.3.7

**Comment by Mark12870** [comment]
I have the same problem with Rocket league, Heroic Version: 2.3.5

**Comment by flavioislima** [comment]
This was fixed on latest stable and also on the beta. 
Reopen if it is not.

**Comment by zer0ring** [comment]
Fallout 3 GOTYE from Epic Games fails to update under HGL 2.5.2, logs indicate download halted while awaiting response from user choice, I am not aware of a means to interact with the process via HGL:

```
cat ~/.config/heroic/GamesConfig/adeae8bbfc94427db57c7dfecce3f1d4.log
[Core] INFO: Trying to re-use existing login session...
You are about to install Fallout 3: Game of the Year Edition, this application supports selective downloads.
The following optional packs are available (tag - name):
 * de - (Additional Languages) Deutsch
 * es - (Additional Languages) español
 * fr - (Additional Languages) français
 * it - (Additional Languages) italiano
Please enter tags of pack(s) to install (space/comma-separated, e.g. "de, es")
Leave blank to use defaults (only required data will be downloaded).
Additional packs [Enter to confirm]:
```

Probably a separate issue but I added here in case others find this via search as I did.
