### ISSUE TITLE
Rocket League and other games not start.. (Archlinux with proton,proton-ge-custom,wine)

### ISSUE THREAD

**Issue by z3r0sTr3sS** [Heroic-Games-Launcher/HeroicGamesLauncher#1454]
### Describe the bug

some issue when trying to open some game with heroic using wine,proton and proton-ge-custom with last version of them;

### Add logs

Launch Command: DRI_PRIME=1 __NV_PRIME_RENDER_OFFLOAD=1 __GLX_VENDOR_LIBRARY_NAME=nvidia STEAM_COMPAT_CLIENT_INSTALL_PATH=/home/lain/.steam/steam STEAM_COMPAT_DATA_PATH=/home/lain/Games/Heroic/rocketleague/Binaries/Win64 DXVK_HUD=fps STEAM_COMPAT_APP_ID=0 SteamAppId=0 SteamGameId=heroic-rocketleague PROTON_LOG_DIR=/home/lain /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary launch Sugar --no-wine --wrapper "'/home/lain/.config/heroic/tools/proton/Proton-GE-Proton7-20/proton' run"

System Info:
Heroic Version: 2.3.7 Brook
Legendary Version:  0.20.26 Dark Energy
OS: Arch KERNEL: 5.18.2-zen1-1-zen ARCH: x64
CPU: Intel Core™ i5-7200U @2.5 GOVERNOR: powersave
RAM: Total: 3.71 GiB Available: 2.32 GiB
GRAPHICS: GPU0: HD Graphics 620  VRAM: 256MB DRIVER:  GPU1: NVIDIA GeForce 930MX VRAM: 2048MB DRIVER: 515.48.07 
PROTOCOL: x11

Game Settings: {
	"autoInstallDxvk": true,
	"autoInstallVkd3d": true,
	"enableEsync": false,
	"enableFsync": false,
	"maxSharpness": 2,
	"enableResizableBar": false,
	"nvidiaPrime": true,
	"offlineMode": false,
	"otherOptions": "",
	"savesPath": "",
	"showFps": true,
	"targetExe": "",
	"useGameMode": false,
	"wineCrossoverBottle": "Heroic",
	"winePrefix": "/home/lain/Games/Heroic/rocketleague/Binaries/Win64",
	"wineVersion": {
		"bin": "/home/lain/.config/heroic/tools/proton/Proton-GE-Proton7-20/proton",
		"name": "Proton - Proton-GE-Proton7-20",
		"type": "proton"
	},
	"useSteamRuntime": true
}

Error Log:
[cli] INFO: Logging in...
[Core] INFO: Trying to re-use existing login session...
[cli] INFO: Checking for updates...
[Core] INFO: Getting authentication token...
[cli] INFO: Launching Sugar...
fsync: up and running.
wine: RLIMIT_NICE is <= 20, unable to use setpriority safely
[S_API] SteamAPI_Init(): SteamAPI_IsSteamRunning() did not locate a running instance of Steam.
[S_API FAIL] SteamAPI_Init() failed

Game Log:
Warning, Failed to compile Material EngineMaterials.FogVolumeMaterial for platform PC-D3D-SM5, Default Material will be used in game.
Warning, Failed to compile Material EngineResources.M_StreamingPause for platform PC-D3D-SM5, Default Material will be used in game.
Warning, Failed to compile Material NodeBuddies.Materials.NodeBuddy_Red1 for platform PC-D3D-SM5, Default Material will be used in game.
Warning, Failed to compile Material NodeBuddies.Materials.NodeBuddy_Target for platform PC-D3D-SM5, Default Material will be used in game.
Warning, Failed to compile Material NodeBuddies.Materials.NodeBuddy_Text1 for platform PC-D3D-SM5, Default Material will be used in game.
Warning, Failed to compile Material NodeBuddies.Materials.NodeBuddy_White1 for platform PC-D3D-SM5, Default Material will be used in game.

### Steps to reproduce

2. Click on '...'
3. Scroll down to '...'

### Expected behavior

launching game and start without crash and logs not help me so much!

### System Information

 [OS: Arch KERNEL: 5.18.2-zen1-1-zen ARCH: x64
Heroic Version: 2.3.7 Brook
Legendary Version:  0.20.26 Dark Energy

### Additional information

the games starting and after crash after few seconds

**Comment by flavioislima** [comment]
Well, the game is being launched, I can only see proton errors.
Check the community on discord or open a discussion to get help with games.
