### ISSUE TITLE
Show progress when moving a game

### ISSUE THREAD

**Issue by flavioislima** [Heroic-Games-Launcher/HeroicGamesLauncher#1456]
### Problem description

Right now when moving games to another folder we don't have any feedback besides a message showing: `Moving...`.
That's because we are using the `mv`.
On Linux and macOS we have the `rsync` utility that has the `--progress` flag that shows a percent with the current progress. So we should change the command to use it instead.

On Windows I never heard of a utility like that that comes natively with powershell, for instance, so I don't know how to proceed there.

### Feature description

Show progress information like we are doing with installs, so a progress bar +  percentage.

**Comment by flavioislima** [comment]
Resources to try on Windows:
https://stackoverflow.com/questions/2434133/progress-during-large-file-copy-copy-item-write-progress

**Comment by JakobDev** [comment]
rsync is not preinstalled on every Linux distro. I would suggest just to loop through the folder and move each file without using a external program.

**Comment by flavioislima** [comment]
Hmm, that makes sense. The problem with counting files is that some files are bigger than others so things wont be really precise. But could work on all platforms.

**Comment by flavioislima** [comment]
@JakobDev for what I did search it is available on the great majority of distros by default.
So I think we should still use `rsync` and if the command is not available, we show a warning and use `mv` instead. I think that's the best approach.

**Comment by arielj** [comment]
just wondering, is there a reason we use move directly and not legendary's `move` command? (haven't tried moving a game with either heroic or legendary to compare though, maybe legendary just uses `mv`)

**Comment by flavioislima** [comment]
Two reasons: won't work for GOG and don't support moving across devices.

**Comment by flavioislima** [comment]
duplicated of #1091
