### ISSUE TITLE
Add on hover description of some settings 

### ISSUE THREAD

**Issue by flavioislima** [Heroic-Games-Launcher/HeroicGamesLauncher#1458]
### Problem description

Since Heroic is becoming popular among non Linux users, those people have no idea what DXVK, VKD3D, Steam runtime, etc are. They don't really know what difference those will make. 

### Feature description

Add a on hover message or an icon that when clicking or putting the mouse on it could give some information on what that setting is about.

**Comment by redromnon** [comment]
Fixed by #1562
