### ISSUE TITLE
Heroric wont launch installed game until restart.

### ISSUE THREAD

**Issue by open-schnick** [Heroic-Games-Launcher/HeroicGamesLauncher#1459]
### Describe the bug

After installing any game heroic shows the game as installed.
It is not possible to start the game tho, because of `TypeError - Cannot read properties of undefined (reading 'bin')` (detailed logs below)
It looks some refresh is failing, because after restart it works as expected.
Spoiler: It does not matter which game it is (i tried 3 different ones, always with the same error)

### Add logs

0:57:32) INFO:    [Backend]:         Progress for *GAME*: 99.56%/940.07MiB/00:00:00
(20:57:33) INFO:    [Backend]:         Progress for *GAME*: 100%/944.21MiB/00:00:00
(20:57:34) INFO:    [Legendary]:       Installed game list updated
(20:57:34) INFO:    [Legendary]:       Installed game list updated
(20:57:35) INFO:    [Backend]:         finished installing
(20:57:35) INFO:    [Backend]:         operation interrupted
(20:57:35) INFO:    [Frontend]:        Refreshing Library
(20:57:35) INFO:    [Legendary]:       Refreshing library...
(20:57:35) INFO:    [Legendary]:       Updating game list
(20:57:35) INFO:    [Legendary]:       Game List Updated
(20:57:35) DEBUG:   [Legendary]:       Using cached install info
(20:57:35) DEBUG:   [Legendary]:       Using cached install info
(20:57:35) DEBUG:   [Legendary]:       Using cached install info
(20:57:58) INFO:    [Backend]:         Launching *GAME*
(20:57:58) DEBUG:   [Legendary]:       Using cached install info
(20:57:58) ERROR:   [Backend]:         TypeError - Cannot read properties of undefined (reading 'bin')
(20:57:58) INFO:    [Backend]:         Log was written to *LOG*
(20:57:58) INFO:    [Frontend]:        Refreshing Library
(20:57:58) INFO:    [Legendary]:       Refreshing library...
(20:57:58) INFO:    [Legendary]:       Updating game list
(20:57:58) INFO:    [Legendary]:       Game List Updated

### Steps to reproduce

1. Install Game
2. Try starting the game -> does not work
3. restart heroic
4. start game -> works

### Expected behavior

I should be able to start a game after installing it without restarting it

### System Information

Heroic Version: 2.3.7 Brook
Legendary Version:  0.20.26 Dark Energy
OS: Arch KERNEL: 5.18.3-arch1-1 ARCH: x64

**Comment by flavioislima** [comment]
Can you test this on the latest beta?

**Comment by open-schnick** [comment]
Same Error with Version: Legendary Version:  0.20.27 Dark Energy (hotfix)

**Comment by open-schnick** [comment]
and in Version:

Heroic Version: 2.4.0 Chopper
Legendary Version:  0.20.27 Dark Energy (hotfix)
OS: Arch KERNEL: 5.18.16-arch1-1 ARCH: x64

**Comment by Nocccer** [comment]
Can you swap the wine version once. I think sometimes the wine information is not updated. So switching wine versions from one to another and then back to the original could fix it.

**Comment by Etaash-mathamsetty** [comment]
I think you just have to click the refresh button in the game library
