### ISSUE TITLE
Can't change language for Bioshock Remastered from Epic Store

### ISSUE THREAD

**Issue by cmalvi** [Heroic-Games-Launcher/HeroicGamesLauncher#1461]
### Describe the bug

I'm trying to play Bioshock Remastered from Epic Store on my Steam Deck, The game ui has Italian language set but on desktop i'm forced to english due to read only filesystem. When i launch the game from game ui, the game detect english launguage an it doen't let the player to change language from game directly.

A language selector like steam in Heroic could be perfect for problem like this

### Add logs

not related

### Steps to reproduce

Launch the game

### Expected behavior

Detect game ui language

### System Information

Steam Deck

**Comment by redromnon** [comment]
Try using `LC_ALL=it_IT.UTF-8` as the environmental variable in the game's settings.

**Comment by cmalvi** [comment]
Already did, I’ve received help on your discord. I’ve missed to close the issue sorry for that

**Comment by cmalvi** [comment]
> Could you please tell where I can set this environmental variable? I'm having the same problem and I don't know how to apply your solution. Ty :)

Game settings > Other > Advanced Options (Environment variable)

**Comment by GiusVir** [comment]
> > Could you please tell where I can set this environmental variable? I'm having the same problem and I don't know how to apply your solution. Ty :)
> 
> Game settings > Other > Advanced Options (Environment variable)

Hi, where i can find game settings?

**Comment by redromnon** [comment]
> Hi, where i can find game settings?

Click on the settings gear icon on the game card.
