### ISSUE TITLE
All Heroic settings are stored as game settings during game installation

### ISSUE THREAD

**Issue by arielj** [Heroic-Games-Launcher/HeroicGamesLauncher#1465]
### Describe the bug

When installing a game, all Heroic settings are stored for the game's settings, even settings that don't apply to games like `maxWorkers` or `darkTrayIcon` for example.

### Add logs

Nothing shows up in logs, I checked the config file for a game after installation.

### Steps to reproduce

1. Install a game that you have never configured before (or remove the config file it it was installed before)
2. Look for its config file in ~/.config/Heroic/GameConfig and open it in a text editor

### Expected behavior

Config file should only include the settings can be applied to games.

### System Information

- Heroic Version [e. g. 2.1.1]: beta branch, but the problem is not new

### Additional information

I'm assigning it to myself, I'm already debugging this, adding this to keep track of it.

**Comment by flavioislima** [comment]
implemented
