### ISSUE TITLE
Not fetching updates

### ISSUE THREAD

**Issue by qube-03** [Heroic-Games-Launcher/HeroicGamesLauncher#1470]
### Describe the bug

ill take rocket league as an example. i launch the game, everything works fine, however i cant play online due to "version mismatch". i look everywhere for a possible "update" optin for rocket league but theres none, although i think there should be

### Add logs

(19:17:52) DEBUG:   [Legendary]:       Running Legendary command: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary --version
(19:17:53) INFO:    [Legendary]:       Legendary location: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary
(19:17:53) INFO:    [Gog]:             GOGDL location: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl
(19:17:53) INFO:    [Backend]:         

Heroic Version: 2.3.7 Brook
Legendary Version:  0.20.26 Dark Energy
OS: Artix KERNEL: 5.18.0-zen1-1-zen ARCH: x64
CPU: AMD Ryzen 5 2600 Six-Core Processor @3.4 GOVERNOR: schedutil
RAM: Total: 15.6 GiB Available: 12.97 GiB
GRAPHICS: GPU0: Ellesmere [Radeon RX 470/480/570/570X/580/580X/590] VRAM: 256MB DRIVER:  
PROTOCOL: x11

(19:17:53) WARNING: [Backend]:         Protocol already registered.
(19:17:54) INFO:    [Frontend]:        Refreshing Library
(19:17:54) INFO:    [Legendary]:       Refreshing library...
(19:17:54) INFO:    [Legendary]:       Refreshing Epic Games...
(19:17:55) DEBUG:   [Legendary]:       Running Legendary command: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary list
(19:17:56) INFO:    [Legendary]:       Updating game list
(19:17:56) INFO:    [Legendary]:       Game List Updated
(19:17:56) INFO:    [Legendary]:       Checking for game updates: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary list-installed --check-updates --tsv
(19:17:56) DEBUG:   [Legendary]:       Running Legendary command: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary list-installed --check-updates --tsv
(19:17:56) INFO:    [Backend]:         Downloaded Winetricks
(19:17:56) INFO:    [Frontend]:        Refreshing wine downloader releases
(19:17:56) INFO:    [WineDownloader]:  Updating wine versions info
(19:17:56) INFO:    [WineDownloader]:  Fetching upstream information...
(19:17:57) INFO:    [Legendary]:       Found 0 game(s) to update
(19:17:57) INFO:    [Gog]:             Found 0 game(s) to update
(19:17:58) INFO:    [WineDownloader]:  wine versions updated
(19:18:12) INFO:    [WineDownloader]:  Start installation of wine version Proton-GE-Proton7-20
(19:19:00) INFO:    [Frontend]:        Refreshing wine downloader releases
(19:19:00) INFO:    [WineDownloader]:  Updating wine versions info
(19:19:00) INFO:    [WineDownloader]:  Fetching upstream information...
(19:19:01) INFO:    [WineDownloader]:  wine versions updated
(19:19:25) INFO:    [WineDownloader]:  Finished installation of wine version Proton-GE-Proton7-20
(19:19:26) INFO:    [Frontend]:        Refreshing wine downloader releases
(19:19:26) INFO:    [WineDownloader]:  Updating wine versions info
(19:19:26) INFO:    [WineDownloader]:  Read local information ...
(19:19:26) INFO:    [WineDownloader]:  wine versions updated
(19:20:25) INFO:    [Backend]:         Changing Language to: ru
(20:23:18) ERROR:   [Legendary]:       Error Getting Info from Epic API
(20:23:18) DEBUG:   [Legendary]:       Using cached install info
(20:25:36) INFO:    [Backend]:         Changing Language to: en
(20:25:40) ERROR:   [Legendary]:       Error Getting Info from Epic API
(20:25:42) DEBUG:   [Legendary]:       Using cached install info
(20:40:41) INFO:    [Frontend]:        Refreshing Library
(20:40:41) INFO:    [Legendary]:       Refreshing library...
(20:40:41) INFO:    [Legendary]:       Refreshing Epic Games...
(20:40:41) DEBUG:   [Legendary]:       Running Legendary command: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary list
(20:40:42) INFO:    [Legendary]:       Updating game list
(20:40:42) INFO:    [Legendary]:       Game List Updated
(20:40:42) INFO:    [Legendary]:       Checking for game updates: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary list-installed --check-updates --tsv
(20:40:42) DEBUG:   [Legendary]:       Running Legendary command: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary list-installed --check-updates --tsv
(20:40:43) INFO:    [Legendary]:       Found 0 game(s) to update
(20:41:49) DEBUG:   [Legendary]:       Using cached install info

### Steps to reproduce

1. Install a game (rocket league here)
2. have an update come out
3. be unable to update the game

### Expected behavior

be able to update the game by clicking the little green button in the bottom left of game covers

### Screenshots

![image](https://user-images.githubusercontent.com/92535344/173425110-bca6faf4-e3c2-43b0-ac32-36d704d502bb.png)

### System Information

- OS: Artix Linux with runit on the zen kernel (5.18)
- Heroic Version: 2.3.7

### Additional information

it seems none of my games are updating, although idk if there is any updates for the others. i also like to run my heroic games through lutris with the help of HeroicBashLauncher.

**Comment by flavioislima** [comment]
Try clearing the cache and click the refresh button.
If that doesn't work, try to verify the game.

**Comment by qube-03** [comment]
oh i should close this, i got it to work with your help, thanks!
