### ISSUE TITLE
Save sync not working

### ISSUE THREAD

**Issue by flowerdealer** [Heroic-Games-Launcher/HeroicGamesLauncher#1474]
### Describe the bug

Can't get Save syncs to work at all (with Epic). Tried Hitman 3, The Messenger, and Ruiner. I play on the SteamDeck, and then I've tried to force upload the saves and resume play on my Windows desktop. I've verified that the paths are similar (except for user an OS specific paths). Epic launcher on PC is fully updated (with Epic Online Services installed, if that makes a difference)
Example paths from Ruiner:
On Windows:
C:\Users\myuser\AppData\Local\Ruiner\Saved\SaveGames\1f7c05e675674856b6a513ded4f445d7
On Steam Deck:
/home/deck/Games/Heroic/Prefixes/RUINER/drive_c/users/deck/Local Settings/Application Data/Ruiner/Saved/SaveGames/1f7c05e675674856b6a513ded4f445d7

Heroic reports uploading the file successfully. Epic shows the game cloud syncing, but no saves from heroic are visible in any directory. 

### Add logs

(09:50:22) DEBUG:   [Legendary]:       Running Legendary command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary --version
(09:50:22) INFO:    [Legendary]:       Legendary location: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary
(09:50:22) INFO:    [Gog]:             GOGDL location: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl
(09:50:22) INFO:    [Backend]:         

Heroic Version: 2.3.8 Brook
Legendary Version:  0.20.26 Dark Energy
OS: Freedesktop.org KERNEL: 5.13.0-valve15-1-neptune-02197-gf6ec7ad3762a ARCH: x64
CPU: AMD Custom APU 0405 @2.69 GOVERNOR: schedutil
RAM: Total: 14.49 GiB Available: 10.65 GiB
GRAPHICS: GPU0: Device 163f VRAM: 512MB DRIVER:  
PROTOCOL: x11

(09:50:22) INFO:    [Gog]:             Getting data about the user
(09:50:22) INFO:    [Gog]:             Refreshing access_token
(09:50:23) WARNING: [Backend]:         Failed to register protocol with OS.
(09:50:23) INFO:    [Gog]:             Token refreshed successfully
(09:50:24) INFO:    [Gog]:             Saved user data to config
(09:50:24) INFO:    [Frontend]:        Refreshing Library
(09:50:24) INFO:    [Legendary]:       Refreshing library...
(09:50:24) INFO:    [Legendary]:       Refreshing Epic Games...
(09:50:24) INFO:    [Gog]:             Getting GOG library
(09:50:24) INFO:    [Gog]:             Number of library pages: 1
(09:50:24) INFO:    [Gog]:             Saved games data
(09:50:24) DEBUG:   [Legendary]:       Running Legendary command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary list
(09:50:26) INFO:    [Backend]:         Downloaded Winetricks
(09:50:26) INFO:    [Legendary]:       Updating game list
(09:50:26) INFO:    [Legendary]:       Game List Updated
(09:50:27) INFO:    [Legendary]:       Checking for game updates: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary list-installed --check-updates --tsv
(09:50:27) DEBUG:   [Legendary]:       Running Legendary command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary list-installed --check-updates --tsv
(09:50:28) INFO:    [Legendary]:       Found 0 game(s) to update
(09:50:29) INFO:    [Gog]:             Found 0 game(s) to update
(09:53:35) DEBUG:   [Legendary]:       Running Legendary command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary --version
(09:53:35) DEBUG:   [Gog]:             Running GOGDL command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --version
(09:57:44) INFO:    [Legendary]:       Syncing saves for Laridae: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary sync-saves --force-upload --save-path "/home/deck/Games/Heroic/Prefixes/RUINER/drive_c/users/deck/Local Settings/Application Data/Ruiner/Saved/SaveGames/1f7c05e675674856b6a513ded4f445d7/" Laridae -y
(09:57:44) DEBUG:   [Legendary]:       Running Legendary command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary sync-saves --force-upload --save-path "/home/deck/Games/Heroic/Prefixes/RUINER/drive_c/users/deck/Local Settings/Application Data/Ruiner/Saved/SaveGames/1f7c05e675674856b6a513ded4f445d7/" Laridae -y
(09:57:47) INFO:    [Legendary]:       Installed game list updated
(09:57:47) ERROR:   [Legendary]:       Corrupted intalled.json file, cannot load installed games SyntaxError: Unexpected end of JSON input
(09:57:47) INFO:    [Legendary]:       Installed game list updated
(09:57:48) INFO:    [Backend]:         
(10:10:42) INFO:    [Legendary]:       Syncing saves for Laridae: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary sync-saves --skip-download --save-path "/home/deck/Games/Heroic/Prefixes/RUINER/drive_c/users/deck/Local Settings/Application Data/Ruiner/Saved/SaveGames/1f7c05e675674856b6a513ded4f445d7/" Laridae -y
(10:10:42) DEBUG:   [Legendary]:       Running Legendary command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary sync-saves --skip-download --save-path "/home/deck/Games/Heroic/Prefixes/RUINER/drive_c/users/deck/Local Settings/Application Data/Ruiner/Saved/SaveGames/1f7c05e675674856b6a513ded4f445d7/" Laridae -y
(10:10:46) INFO:    [Legendary]:       Installed game list updated
(10:10:46) ERROR:   [Legendary]:       Corrupted intalled.json file, cannot load installed games SyntaxError: Unexpected end of JSON input
(10:10:46) INFO:    [Legendary]:       Installed game list updated
(10:10:46) ERROR:   [Legendary]:       Corrupted intalled.json file, cannot load installed games SyntaxError: Unexpected end of JSON input
(10:10:46) INFO:    [Legendary]:       Installed game list updated
(10:10:46) INFO:    [Backend]:         
(10:10:58) INFO:    [Legendary]:       Syncing saves for Laridae: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary sync-saves --force-upload --save-path "/home/deck/Games/Heroic/Prefixes/RUINER/drive_c/users/deck/Local Settings/Application Data/Ruiner/Saved/SaveGames/1f7c05e675674856b6a513ded4f445d7/" Laridae -y
(10:10:58) DEBUG:   [Legendary]:       Running Legendary command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary sync-saves --force-upload --save-path "/home/deck/Games/Heroic/Prefixes/RUINER/drive_c/users/deck/Local Settings/Application Data/Ruiner/Saved/SaveGames/1f7c05e675674856b6a513ded4f445d7/" Laridae -y
(10:11:02) INFO:    [Legendary]:       Installed game list updated
(10:11:02) ERROR:   [Legendary]:       Corrupted intalled.json file, cannot load installed games SyntaxError: Unexpected end of JSON input
(10:11:02) INFO:    [Legendary]:       Installed game list updated
(10:11:02) ERROR:   [Legendary]:       Corrupted intalled.json file, cannot load installed games SyntaxError: Unexpected end of JSON input
(10:11:02) INFO:    [Legendary]:       Installed game list updated
(10:11:04) INFO:    [Backend]:         

### Steps to reproduce

1. Go to game on heroic. Force upload
2. Upload sync successfully. 
3. Launch game on Windows, cloud sync execute successfully. 
4. Save from SteamDeck is not available. Save files do not correspond in directory of game on PC.

### Expected behavior

Save sync working correctly, or getting some sort of an error. 

### System Information

- PC Windows 11 (latest build)
- SteamDeck Beta channel
- Heroic Version 2.3.8
- Epic client fully updated with Epic Online Services.

**Comment by ElGranMachete** [comment]
Dod you find a solution?
