### ISSUE TITLE
[macOS] Import game is not using correct platform

### ISSUE THREAD

**Issue by Moonif** [Heroic-Games-Launcher/HeroicGamesLauncher#1475]
Hello,

Importing a Windows-only game into Heroic on Mac (Example: GtaV), will set the game's platform to default which is Mac in Legendary, which will cause the game to fail to launch, because it will fail to find the game metadata (Trying to find the Mac metadata while the game is only available on Windows), so it will result in an error:

`Metadata for "xxx" does not exist, cannot launch.`

Reported in issue #1198 and #1078 

To fix the problem, the game must be imported with the following argument: --platform Windows
In legendary it's something like this: `import --platform Windows [game name] [game folder]`

Hope that helps.

**Comment by flavioislima** [comment]
fixed
