### ISSUE TITLE
[Linux] Heroic cannot find wine.

### ISSUE THREAD

**Issue by acidicneko** [Heroic-Games-Launcher/HeroicGamesLauncher#1476]
### Describe the bug

I am trying to run Pathways on my Linux machine. I have installed Wine-GE-Proton-7 through Heroic, but when I launch any game it says `FileNotFoundError: [Errno 2] No such file or directory: '/home/ayu/.config/heroic/tools/wine/Wine-GE-Proton7-16/bin/wine'`
I did check the location myself and Wine is present there.

### Add logs

```
Error Log:

[cli] INFO: Logging in...

[Core] INFO: Trying to re-use existing login session...

[cli] INFO: Checking for updates...

[Core] INFO: Getting authentication token...

[cli] INFO: Launching 8fceb562623c430db9bb6abf0549c43e...

Traceback (most recent call last):

  File "legendary/cli.py", line 3016, in <module>

  File "legendary/cli.py", line 2931, in main

  File "legendary/cli.py", line 691, in launch_game

  File "subprocess.py", line 858, in __init__

  File "subprocess.py", line 1704, in _execute_child

FileNotFoundError: [Errno 2] No such file or directory: '/home/ayu/.config/heroic/tools/wine/Wine-GE-Proton7-16/bin/wine'

[32978] Failed to execute script 'cli' due to unhandled exception!

```

### Steps to reproduce

1. Go to library
2. Install Pathways
3. Click on run

### Expected behavior

The game should've run fine as `wine` is installed on the right location.

### System Information

- OS : Linux Mint
- Heroic Version :  2.3.8
- RAM: 4GB
- CPU: intel i3-6006u@2.00GHz

**Comment by flavioislima** [comment]
Can you include the part of the log that has the launch command?

**Comment by acidicneko** [comment]
> Can you include the part of the log that has the launch command?
```
Launch Command: WINEPREFIX=/home/ayu/Games/Heroic/Prefixes/Pathway /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary launch 8fceb562623c430db9bb6abf0549c43e --wine /home/ayu/.config/heroic/tools/wine/Wine-GE-Proton7-16/bin/wine --wine-prefix /home/ayu/Games/Heroic/Prefixes/Pathway
```

**Comment by acidicneko** [comment]
Just checked I cannot manually execute `wine` binary. Also I cannot perform any action on `wine` file but `ls` outputs it.

**Comment by flavioislima** [comment]
Can you try the previous version? 7-15?

**Comment by acidicneko** [comment]
I tried 7-15 but still the same issue.

**Comment by flavioislima** [comment]
don't really know what to do here, man
Send a picture of the terminal with the `ls -l` command.
I believe might be something wrong with your system and not Heroic, since even from the terminal it doesn't work.

**Comment by Nocccer** [comment]
I thought wine-ge needs the normal wine inatalled on the systwm. So running `which wine` in terminal should point to the system wine. But i'm not 100% sure if wine needs to be installed

**Comment by acidicneko** [comment]
@Nocccer its working now thanks.

**Comment by NoelleTGS** [comment]
I'm having this same issue, even though Wine is installed. I'm using the beta version.

**Comment by tripplehelix** [comment]
I am also encountering this issue, although the system wine installation shows up in Heroic, when starting a game it says it can't find it. I'm guessing due to this GE-Proton also won't run.
