### ISSUE TITLE
Recently played games cannot be launched through the tray icon menu on Linux.

### ISSUE THREAD

**Issue by rabidcopy** [Heroic-Games-Launcher/HeroicGamesLauncher#1484]
### Describe the bug

When attempting to launch recently played games listed in the right-click menu of the tray icon, games do not launch. With logging enabled, it puts out "Check failed: chdir(current_directory) == 0". May be related to #968.

### Add logs

Check failed: chdir(current_directory) == 0

### Steps to reproduce

1. Right click the tray icon with a recently played game listed.
2. Left click the game you wish to launch.
3. Nothing happens

### Expected behavior

Expected behavior is for the game to be launched when the menu entry is selected.

### Screenshots

![image](https://user-images.githubusercontent.com/8052832/173976187-2fa3891e-b0c6-4881-9d07-a138b1be9080.png)

### System Information

Heroic Version: 2.3.7 Brook

Legendary Version:  0.20.26 Dark Energy

OS: EndeavourOS KERNEL: 5.18.1-259-tkg-bmq ARCH: x64

CPU: AMD Ryzen 5 2600 Six-Core Processor @3.4 

RAM: Total: 15.64 GiB Available: 11.21 GiB

GRAPHICS: GPU0: Ellesmere [Radeon RX 470/480/570/570X/580/580X/590] VRAM: 256MB DRIVER:  

PROTOCOL: x11

**Comment by arielj** [comment]
How did you install Heroic? flatpak? appimage? repos? I'm wondering if that has something to do and if it works if you try a different installation option.

**Comment by rabidcopy** [comment]
> How did you install Heroic? flatpak? appimage? repos? I'm wondering if that has something to do and if it works if you try a different installation option.
> 
> EDIT: nevermind, I'm able to reproduce the error using the source and I think I have a fix for it

Just to be thorough, I installed Heroic through the AUR repository. I compiled #1493 myself and can confirm games launch from the tray icon menu now. Thank you!
