### ISSUE TITLE
Remove Prefix needs to be explained better

### ISSUE THREAD

**Issue by LiamDawe** [Heroic-Games-Launcher/HeroicGamesLauncher#1486]
### Problem description

When you remove a game, Heroic asks you if you wish to remove the Prefix.

This is technical jargon, that most people won't have any idea what it actually means.

This needs to be explained better for users.

### Feature description

Less tech jargon, more simple text.

### Additional information

In the age of the Steam Deck and tons of people using it, keep it simple.

**Comment by LiamDawe** [comment]
Example: https://www.reddit.com/r/SteamDeck/comments/vd36hy/heroic_launcher_would_you_like_to_remove_the/

**Comment by redromnon** [comment]
Just as a suggestion, apart from the improved Remove Prefix dialog, a **help button** can be implemented right under the Wine Prefix in the game's Wine settings.
This help button will expand on a click and briefly explain what a Prefix is just like how it does for Wine Version, Advanced Options and Game Arguments.
