### ISSUE TITLE
Notify the user about a new Stable or Beta Heroic release

### ISSUE THREAD

**Issue by flavioislima** [Heroic-Games-Launcher/HeroicGamesLauncher#1490]
### Problem description

Right now we are notifying the users that we have a new version available only on Windows (setup) and Linux AppImage.
Before that we used to show a dialog with the new update on all platforms.

So people that are not following the updates are missing them and using old heroic versions, especially on macOS.

### Feature description

I don't think we should bring the old dialog back but would be nice to show that a new version is available, including new betas, somewhere in Heroic. A notification may be or in the settings, header, etc.

### Alternatives

Bring the old dialog back, although I don't think it is ideal.

**Comment by arielj** [comment]
Maybe now that you added the version in the sidebar we can add a `(!)` close to that when there's a new version.

In some applications I've seen an opt-in / opt-out option to check for beta releases, so people can get notifications only for stable releases if they don't care about betas

**Comment by flavioislima** [comment]
Yes, I think we need to add this for the next stable so if we need to send a hotfix people will receive the information.

**Comment by flavioislima** [comment]
Working on this one
