### ISSUE TITLE
uninstalled games still show as installed in played recently

### ISSUE THREAD

**Issue by Etaash-mathamsetty** [Heroic-Games-Launcher/HeroicGamesLauncher#1495]
### Describe the bug

pretty self explanatory, if I download a game and uninstall it, it still shows as installed in played recently for some reason

### Add logs

nothing much in the logs

### Steps to reproduce

1. install game
2. play game
3. uninstall game

### Expected behavior

the game should be grayed out in both played recently and all games

### Screenshots

![image](https://user-images.githubusercontent.com/45927311/174411699-0f9dbbbc-f5d1-488b-b4c9-b1fada0bf2e7.png)

### System Information

- OS: arch linux
- Heroic Version: 2.3.9

**Comment by flavioislima** [comment]
fixed
