### ISSUE TITLE
Trying to install a DLC without the main game installed fails with no error and success message

### ISSUE THREAD

**Issue by arielj** [Heroic-Games-Launcher/HeroicGamesLauncher#1496]
### Describe the bug

When trying to install a DLC for a game, Heroic shows the install dialog, it allows the user to continue with the installation, starts showing some progress, and then finishes with an `Installation finished` notification but the game is not installed and it's not displayed as installed in the list of games.

### Add logs

Heroic's log:
```
(01:22:38) INFO:    [Legendary]:       Installing 6b61b3692dae45be889bf38cb1f9ed84 with: /home/.../legendary install 6b61b3692dae45be889bf38cb1f9ed84 --platform Windows --base-path /home/.../Games/Heroic --skip-dlcs --skip-sdl -y
(01:22:38) DEBUG:   [Legendary]:       Running Legendary command: /home/.../legendary install 6b61b3692dae45be889bf38cb1f9ed84 --platform Windows --base-path /home/.../Games/Heroic --skip-dlcs --skip-sdl -y
(01:22:38) DEBUG:   [Legendary]:       Logging to file "/home/.../.config/heroic/GamesConfig/6b61b3692dae45be889bf38cb1f9ed84.log"
(01:22:40) INFO:    [Backend]:         finished installing
(01:22:40) INFO:    [Backend]:         operation interrupted
```

Game's log:
```
[Core] INFO: Trying to re-use existing login session...
[cli] INFO: Install candidate is DLC
[cli] CRITICAL: Base game "8935bb3e1420443a9789fe01758039a5" is not installed!
```

### Steps to reproduce

Try to install a DLC when the main game is not installed

An example to try is `Alien: Isolation - Last Survivor`, the DLC for `Alien: Isolation` that Epic gave for free at some point.

### Expected behavior

Heroic should warn the user that the game they are trying to install requires another game to be installed first if the game is not installed.

It shouldn't let the user continue without installing the original game or, if we let the user continue, we should show a proper error message explaining that it failed and why.

### System Information

- Heroic Version [e. g. 2.1.1]: main branch, but it happens with any version

**Comment by flavioislima** [comment]
I think we do not have that now that we don't show DLCs on the library, right? At least none of mine are being shown.

**Comment by arielj** [comment]
Yes, now that the DLC does not show up I can't reproduce this anymore, I'll close this
