### ISSUE TITLE
[Linux] Can't install missing DLLs with wine tricks on flatpak

### ISSUE THREAD

**Issue by TheEpicNoobZilla** [Heroic-Games-Launcher/HeroicGamesLauncher#1498]
### Describe the bug

I wanted to play Witcher 2 with wine-ge, but the games requires dlls that i need to install with winetricks, but it does not install

### Add logs

Launch Command: DRI_PRIME=1 __NV_PRIME_RENDER_OFFLOAD=1 __GLX_VENDOR_LIBRARY_NAME=nvidia WINEPREFIX=/home/noobzilla/Games/Heroic/Prefixes/The Witcher 2 DXVK_HUD=fps WINEESYNC=1 WINEFSYNC=1 /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl launch "/home/noobzilla/Games/Heroic/The Witcher 2" 1207658930 --wine /home/noobzilla/.var/app/com.heroicgameslauncher.hgl/config/heroic/tools/wine/Wine-GE-Proton7-16/bin/wine --wine-prefix "/home/noobzilla/Games/Heroic/Prefixes/The Witcher 2" --os windows

System Info:
Heroic Version: 2.3.9 Brook
Legendary Version:  0.20.26 Dark Energy
OS: Freedesktop.org KERNEL: 5.18.5-200.fc36.x86_64 ARCH: x64
CPU: Intel Core™ i7-8750H @2.2 GOVERNOR: performance
RAM: Total: 15.32 GiB Available: 8.33 GiB
GRAPHICS: GPU0: UHD Graphics 630  VRAM: 256MB DRIVER:  GPU1: TU117M [GeForce GTX 1650 Mobile / Max-Q]  VRAM: 32MB DRIVER:  
PROTOCOL: wayland

Game Settings: {
	"autoInstallDxvk": true,
	"autoInstallVkd3d": false,
	"enableEsync": true,
	"enableFsync": true,
	"maxSharpness": 2,
	"nvidiaPrime": true,
	"otherOptions": "",
	"savesPath": "",
	"showFps": true,
	"targetExe": "",
	"useGameMode": false,
	"wineCrossoverBottle": "Heroic",
	"winePrefix": "/home/noobzilla/Games/Heroic/Prefixes/The Witcher 2",
	"wineVersion": {
		"bin": "/home/noobzilla/.var/app/com.heroicgameslauncher.hgl/config/heroic/tools/wine/Wine-GE-Proton7-16/bin/wine",
		"name": "Wine - Wine-GE-Proton7-16",
		"type": "wine",
		"wineserver": "/home/noobzilla/.var/app/com.heroicgameslauncher.hgl/config/heroic/tools/wine/Wine-GE-Proton7-16/bin/wineserver",
		"wineboot": "/home/noobzilla/.var/app/com.heroicgameslauncher.hgl/config/heroic/tools/wine/Wine-GE-Proton7-16/bin/wineboot"
	}
}

Error Log:
fsync: up and running.
wine: RLIMIT_NICE is <= 20, unable to use setpriority safely
002c:fixme:winediag:LdrInitializeThunk wine-staging 7.0 is a testing version containing experimental patches.
002c:fixme:winediag:LdrInitializeThunk Please mention your exact version when filing bug reports on winehq.org.
MESA-INTEL: warning: Performance support disabled, consider sysctl dev.i915.perf_stream_paranoid=0
0054:err:xrandr:xrandr14_get_adapters Failed to get adapters
0024:err:module:import_dll Library mfc100u.dll (which is needed by L"Z:\\home\\noobzilla\\Games\\Heroic\\The Witcher 2\\Launcher.exe") not found
0024:err:module:LdrInitializeThunk Importing dlls for L"Z:\\home\\noobzilla\\Games\\Heroic\\The Witcher 2\\Launcher.exe" failed, status c0000135

Game Log:
Launch command: ['/home/noobzilla/.var/app/com.heroicgameslauncher.hgl/config/heroic/tools/wine/Wine-GE-Proton7-16/bin/wine', '/home/noobzilla/Games/Heroic/The Witcher 2/Launcher.exe']

### Steps to reproduce

1. Go to gog library
2. Click on launch witcher 2 windows version
3. Scroll down to end of the log file

### Expected behavior

Game launcher

### System Information

- OS [e. g. "Ubuntu"]: Fedora 36 (Flatpak version)
- Heroic Version [e. g. 2.1.1]: 2.3.9

### Additional information

I need to launch the game with proton-ge, because i got error with "no file or directory" for wine version (it looks for wine-lutris-ge instead of wine-ge)

**Comment by Nocccer** [comment]
Should be fixed in 2.4.0. Can you try again?

**Comment by TheEpicNoobZilla** [comment]
it does work
