### ISSUE TITLE
Show the anticheat status of a game if in Linux

### ISSUE THREAD

**Issue by arielj** [Heroic-Games-Launcher/HeroicGamesLauncher#1499]
### Problem description

When installing a game that has anticheat, users may not be aware of the game having anticheat or they may not be aware if the anticheat will actually work on linux.

### Feature description

We could use the areweanticheat data from here https://github.com/Starz0r/AreWeAntiCheatYet/blob/master/games.json to know the status of the anticheat for a given name.

Legendary will also try to detect if a game has an anticheat software and show a warning during installation, we could use that information as a fallback maybe?

### Alternatives

Instead of looks for the game to show a badge, we could show a link so the user can go and check areweanticheatyet manually.

### Additional information

The list of games is limited (there are 231 games and many are not even available in the EGS) and probably doesn't change often, so maybe it's simple to keep a mapping of the name in Epic to the json's name (maybe it can even be a feature request to add to are we anti cheat yet?)

**Comment by flavioislima** [comment]
Done
