### ISSUE TITLE
Library UI does not scale well with few languages (Beta version)

### ISSUE THREAD

**Issue by TheEpicNoobZilla** [Heroic-Games-Launcher/HeroicGamesLauncher#1502]
### Describe the bug

I've installed beta version of HGL and when i switched to library i couldn't filter my games to show linux native, because the header (top) UI elements does not move to make sure it scales well with non english languages

### Add logs

[heroic-2022-06-20T16_28_20.968Z.log](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/files/8942283/heroic-2022-06-20T16_28_20.968Z.log)

### Steps to reproduce

1. Go to 'Libarary'
4. Look at top bar UI

### Expected behavior

top UI scales to language

### Screenshots

How it should look:
![unknown](https://user-images.githubusercontent.com/55759769/174644455-08e4a843-fc37-44a3-b091-0400cfe10660.png)
How it looks when switched to my native:
![unknown2](https://user-images.githubusercontent.com/55759769/174644543-1d7ac49b-af2f-4ea0-b1d0-d414718091f9.png)
Another language that is affected by this
![unknown3](https://user-images.githubusercontent.com/55759769/174644463-91c5097d-18c6-403a-bb4e-08b27e6ce366.png)
But some does not)
![unknown4](https://user-images.githubusercontent.com/55759769/174644465-8ea3ceb3-8526-4e8a-9932-be5cd31a5896.png)
As workaround i've added margin to seperate those elements, so maybe adding margin or finding other way to dynamically change the space of those element should be added when releasing this to stable channel
![5](https://user-images.githubusercontent.com/55759769/174644935-cee052c5-70ad-4e0d-91c6-dd9ebc514a08.png)

### System Information

- OS [e. g. "Ubuntu"]: Fedora 36
- Heroic Version [e. g. 2.1.1]: 2.4.0 beta

**Comment by arielj** [comment]
This should have been fixed in the latest beta, closing
