### ISSUE TITLE
Empty "Ok" dialog box every time Heroic starts

### ISSUE THREAD

**Issue by clebercasali** [Heroic-Games-Launcher/HeroicGamesLauncher#1503]
### Describe the bug

Every time I run Heroic I get a dialog box with no text and only an "ok" button.

### Add logs

(17:33:21) DEBUG:   [Legendary]:       Running Legendary command: /tmp/.mount_HeroicXxmcBs/resources/app.asar.unpacked/build/bin/linux/legendary --version
(17:33:21) INFO:    [Legendary]:       Legendary location: /tmp/.mount_HeroicXxmcBs/resources/app.asar.unpacked/build/bin/linux/legendary
(17:33:21) INFO:    [Gog]:             GOGDL location: /tmp/.mount_HeroicXxmcBs/resources/app.asar.unpacked/build/bin/linux/gogdl
(17:33:21) INFO:    [Backend]:         

Heroic Version: 2.3.9 Brook
Legendary Version:  0.20.26 Dark Energy
OS: Ubuntu KERNEL: 5.18.0-5.1-liquorix-amd64 ARCH: x64
CPU: Intel Core™ i7-2600 @3.4 GOVERNOR: ondemand
RAM: Total: 7.75 GiB Available: 5.78 GiB
GRAPHICS: GPU0: NVIDIA GeForce GTX 750 Ti VRAM: 1024MB DRIVER: 515.48.07 
PROTOCOL: x11

(17:33:21) INFO:    [Gog]:             Getting data about the user
(17:33:22) WARNING: [Backend]:         Failed to register protocol with OS.
(17:33:22) INFO:    [Gog]:             Saved user data to config
(17:33:23) INFO:    [Frontend]:        Refreshing Library
(17:33:23) INFO:    [Legendary]:       Refreshing library...
(17:33:23) INFO:    [Legendary]:       Refreshing Epic Games...
(17:33:23) INFO:    [Gog]:             Getting GOG library
(17:33:24) INFO:    [Gog]:             Number of library pages: 1
(17:33:24) INFO:    [Gog]:             Saved games data
(17:33:24) DEBUG:   [Legendary]:       Running Legendary command: /tmp/.mount_HeroicXxmcBs/resources/app.asar.unpacked/build/bin/linux/legendary list
(17:33:24) INFO:    [Backend]:         Downloaded Winetricks
(17:33:24) INFO:    [DXVKInstaller]:   Updating vkd3d to: vkd3d-proton-2.6
(17:33:25) INFO:    [Legendary]:       Updating game list
(17:33:25) INFO:    [Legendary]:       Game List Updated
(17:33:25) INFO:    [DXVKInstaller]:   downloaded vkd3d
(17:33:25) INFO:    [DXVKInstaller]:   extracting vkd3d
(17:33:25) ERROR:   [DXVKInstaller]:   Extraction of vkd3d failed with: Error: Command failed: tar -I zstd -xvf /home/user/.config/heroic/tools/vkd3d/vkd3d-proton-2.6.tar.zst -C /home/user/.config/heroic/tools/vkd3d
tar (child): zstd: Função exec falhou: Arquivo ou diretório inexistente
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now

(17:33:26) INFO:    [Legendary]:       Checking for game updates: /tmp/.mount_HeroicXxmcBs/resources/app.asar.unpacked/build/bin/linux/legendary list-installed --check-updates --tsv
(17:33:26) DEBUG:   [Legendary]:       Running Legendary command: /tmp/.mount_HeroicXxmcBs/resources/app.asar.unpacked/build/bin/linux/legendary list-installed --check-updates --tsv
(17:33:28) INFO:    [Legendary]:       Found 0 game(s) to update
(17:33:28) INFO:    [Gog]:             Found 0 game(s) to update

### Steps to reproduce

Just run Heroic Games Launcher (appimage version).

### Expected behavior

No dialog box at all, or some text describing what is wrong and how to fix it.

### Screenshots

![screen-2022-06-20-17-31-17](https://user-images.githubusercontent.com/13246236/174674343-4d2508e0-e789-4a35-8f4c-627c87d8a4cc.png)

### System Information

- OS [e. g. "Ubuntu"]:  Lubuntu 20.04
- Heroic Version [e. g. 2.1.1]: 2.3.9

**Comment by Nocccer** [comment]
Looks like you don't have tar installed or something is missing like zstd lib. Still a big, because it should report the problem to the frontend into the empty dialog box.

**Comment by clebercasali** [comment]
I do have tar installed. No idea about the zstd lib though.

**Comment by flavioislima** [comment]
> I do have tar installed. No idea about the zstd lib though.

It is ZSTD that you are missing. Search for zstd or libzstd in some distros. 
Probably the dialog has a bug with the translations.

**Comment by flavioislima** [comment]
Yes, we are removing the need for ZSTD on the next releases.

**Comment by flavioislima** [comment]
This is fixed in beta so I am closing it
