### ISSUE TITLE
Ability to add external games not related to EGS or GOG

### ISSUE THREAD

**Issue by Laar3** [Heroic-Games-Launcher/HeroicGamesLauncher#1506]
### Problem description

This day and age its annoying to have to have 5 different launchers for everything.

### Feature description

It would be great if we could add a game, give a title, provide a run command, and supply an image and it would be added to the library.

**Comment by Nocccer** [comment]
This is a idea for long now but takes time to implement.
If you use steam you can try out this feature soon:
https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/pull/1331

In steam you can add external executables.

**Comment by CommandMC** [comment]
Resolved with #1864
