### ISSUE TITLE
[SteamDeck] Non-functional on screen keyboard

### ISSUE THREAD

**Issue by gbdrbob** [Heroic-Games-Launcher/HeroicGamesLauncher#1510]
### Describe the bug

If I open Heroic Games Launcher on my Steam Deck a non functional on screen keyboard (OSK) appears if I navigate to the search box using the gamepad. The keys of this OSK don't work, with no text appearing when they are selected. 

### Add logs

(19:34:40) DEBUG:   [Legendary]:       Running Legendary command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary --version
(19:34:41) INFO:    [Legendary]:       Legendary location: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary
(19:34:41) INFO:    [Gog]:             GOGDL location: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl
(19:34:41) INFO:    [Backend]:         

Heroic Version: 2.3.9 Brook
Legendary Version:  0.20.26 Dark Energy
OS: Freedesktop.org KERNEL: 5.13.0-valve15-1-neptune-02197-gf6ec7ad3762a ARCH: x64
CPU: AMD Custom APU 0405 @1.81 GOVERNOR: schedutil
RAM: Total: 14.49 GiB Available: 11.31 GiB
GRAPHICS: GPU0: Device 163f VRAM: 512MB DRIVER:  
PROTOCOL: x11

(19:34:41) INFO:    [Gog]:             Getting data about the user
(19:34:41) WARNING: [Backend]:         Failed to register protocol with OS.
(19:34:41) INFO:    [Gog]:             Saved user data to config
(19:34:42) INFO:    [Frontend]:        Refreshing Library
(19:34:42) INFO:    [Legendary]:       Refreshing library...
(19:34:42) INFO:    [Legendary]:       Refreshing Epic Games...
(19:34:42) INFO:    [Gog]:             Getting GOG library
(19:34:43) INFO:    [Gog]:             Number of library pages: 2
(19:34:43) INFO:    [Gog]:             Getting data for page 2
(19:34:43) DEBUG:   [Legendary]:       Running Legendary command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary list
(19:34:43) INFO:    [Gog]:             Saved games data
(19:34:44) INFO:    [Backend]:         Downloaded Winetricks
(19:34:45) INFO:    [Legendary]:       Updating game list
(19:34:45) INFO:    [Legendary]:       Game List Updated
(19:34:45) INFO:    [Legendary]:       Checking for game updates: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary list-installed --check-updates --tsv
(19:34:45) DEBUG:   [Legendary]:       Running Legendary command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary list-installed --check-updates --tsv
(19:34:46) INFO:    [Legendary]:       Found 0 game(s) to update
(19:34:46) INFO:    [Gog]:             Found 0 game(s) to update

### Steps to reproduce

1. Open Heroic on a steam deck in game mode
2. Navigate to the search box using the gamepad controls and press gamepad "A" button
3. Observe apperance of non-functional On-screen Keyboard

### Expected behavior

Selecting the search box using the gamepad controls on a Steam Deck should either open the native Steam Deck On Screen Keyboard (usually accessed via "Steam key + X") or do nothing. 

### Screenshots

![20220621184557_1](https://user-images.githubusercontent.com/17690288/174871810-2ac5e6ee-5563-4f2f-8826-482d453579c6.jpg)

### System Information

- OS SteamOS Holo
- Heroic Version 2.3.9 (flatpak)

**Comment by arielj** [comment]
hmmmm this is weird, gamepad navigation never worked in the steam deck, did you do anything special for that to work? I was never able to get it to work in the flatpak version of Heroic (and seems to be a known issue with Flatpak and electron-based appes), I'm really curious about this

**Comment by Nocccer** [comment]
Checked back and can confirm that in game mode the keyboard appears

**Comment by Etaash-mathamsetty** [comment]
pretty sure chromium itself doesn't support this, so I don't thing much can be done about this

**Comment by arielj** [comment]
> > so weird, I don't have a steamdeck and I the gamepad navigation doesn't work on my desktop using the flatpak version (and I developed that feature, so I don't know how to debug it since I can't really use it xD)
> 
> Are you connecting your gamepad before you launch the flatpak? I've read ([1](https://github.com/flatpak/xdg-desktop-portal/issues/536), [2](https://gitlab.steamos.cloud/steamrt/steam-runtime-tools/-/issues/11)) that even when allowing acccess to udev via a permission for /run/udev:ro, hotplug doesn't work, so the pad must be present at launch.

Yes, the gamepad is connected before opening Heroic, maybe the steamdeck's controller is handled different by the system? but my understanding was that the gamepad didn't work at all for steamdeck users, so I don't know what changed if something changed (maybe a steam deck update?)

**Comment by nymb** [comment]
I have the same issue.  On screen keyboard pops up but clicking on the keys with the touch display or mouse or joystick will highlight the key selected but interacting doesn't input the key.  Theres also no way to close the keyboard at this board so closing out of HGL is the only way to remove the on screen keyboard.
Similar issue is when trying install/import a game.  Clicking on the folder to pick a new path or input anything in no longer works.

**Comment by gbdrbob** [comment]
> Theres also no way to close the keyboard at this board so closing out of HGL is the only way to remove the on screen keyboard. 
B key on the gamepad closes the non-functional OSK on my Steam Deck.

**Comment by nymb** [comment]
> > Theres also no way to close the keyboard at this board so closing out of HGL is the only way to remove the on screen keyboard.
> 
> The gamepad "B" button closes the non-functional OSK on my Steam Deck.

Thanks "B" did work.  But sadly still no functional keyboard.  Will patiently wait for updates.

**Comment by arielj** [comment]
sorry I really can't do anything until I have a steam deck to test/debug this (and it's not going to happen anytime soon, I live in argentina, I can't even make a reservation haha)

**Comment by nymb** [comment]
Updated Heroic Launcher a few mins ago and the virtual keyboard in HGL still not responding to any of the steamdeck inputs, except B button will close it.

**Comment by flavioislima** [comment]
> Updated Heroic Launcher a few mins ago and the virtual keyboard in HGL still not responding to any of the steamdeck inputs, except B button will close it.

yes because the new version with the fix was not released yet.
Will be released this week.

**Comment by nymb** [comment]
Gotcha!  I should have checked the version number..  Thanks for the updates.
