### ISSUE TITLE
Can't install games on NTFS partition. Heroic says path might not be writable, but it is.

### ISSUE THREAD

**Issue by clebercasali** [Heroic-Games-Launcher/HeroicGamesLauncher#1512]
### Describe the bug

I can no longer install games in my NTFS partition.
Heroic interface says the path might not be writable, but it is.
The "Install" button is disabled and I can't install.

### Add logs

(18:57:20) DEBUG:   [Legendary]:       Running Legendary command: /tmp/.mount_HeroiceOGugO/resources/app.asar.unpacked/build/bin/linux/legendary --version
(18:57:21) INFO:    [Legendary]:       Legendary location: /tmp/.mount_HeroiceOGugO/resources/app.asar.unpacked/build/bin/linux/legendary
(18:57:21) INFO:    [Gog]:             GOGDL location: /tmp/.mount_HeroiceOGugO/resources/app.asar.unpacked/build/bin/linux/gogdl
(18:57:21) INFO:    [Backend]:         

Heroic Version: 2.3.9 Brook
Legendary Version:  0.20.26 Dark Energy
OS: Ubuntu KERNEL: 5.18.0-5.1-liquorix-amd64 ARCH: x64
CPU: Intel Core™ i7-2600 @3.4 GOVERNOR: ondemand
RAM: Total: 7.75 GiB Available: 6.1 GiB
GRAPHICS: GPU0: NVIDIA GeForce GTX 750 Ti VRAM: 1024MB DRIVER: 515.48.07 
PROTOCOL: x11

(18:57:21) INFO:    [Gog]:             Getting data about the user
(18:57:21) WARNING: [Backend]:         Failed to register protocol with OS.
(18:57:22) INFO:    [Gog]:             Saved user data to config
(18:57:22) INFO:    [Frontend]:        Refreshing Library
(18:57:22) INFO:    [Legendary]:       Refreshing library...
(18:57:22) INFO:    [Legendary]:       Refreshing Epic Games...
(18:57:22) INFO:    [Gog]:             Getting GOG library
(18:57:23) INFO:    [Gog]:             Number of library pages: 1
(18:57:23) INFO:    [Gog]:             Saved games data
(18:57:23) DEBUG:   [Legendary]:       Running Legendary command: /tmp/.mount_HeroiceOGugO/resources/app.asar.unpacked/build/bin/linux/legendary list
(18:57:24) INFO:    [Backend]:         Downloaded Winetricks
(18:57:25) INFO:    [Legendary]:       Updating game list
(18:57:25) INFO:    [Legendary]:       Game List Updated
(18:57:25) INFO:    [Legendary]:       Checking for game updates: /tmp/.mount_HeroiceOGugO/resources/app.asar.unpacked/build/bin/linux/legendary list-installed --check-updates --tsv
(18:57:25) DEBUG:   [Legendary]:       Running Legendary command: /tmp/.mount_HeroiceOGugO/resources/app.asar.unpacked/build/bin/linux/legendary list-installed --check-updates --tsv
(18:57:27) INFO:    [Legendary]:       Found 0 game(s) to update
(18:57:27) INFO:    [Gog]:             Found 0 game(s) to update
(18:57:28) DEBUG:   [Legendary]:       Using cached install info
(18:57:28) DEBUG:   [Legendary]:       Using cached install info
(18:57:28) WARNING: [Backend]:         default is not writable
(18:57:28) WARNING: [Backend]:         '/media/Dados/Jogos/HeroicGamesLauncher/games' is not writable
(18:57:28) WARNING: [Backend]:         '/media/Dados/Jogos/HeroicGamesLauncher/games' is not writable

### Steps to reproduce

Try to install any game in a NTFS partition.

### Expected behavior

Normal install.

### Screenshots

![screen-2022-06-21-18-54-41](https://user-images.githubusercontent.com/13246236/174904206-00410b53-5c51-4288-a4ab-d31cba3edbca.png)
![screen-2022-06-21-18-57-06](https://user-images.githubusercontent.com/13246236/174904209-92910eb4-7bd5-47a5-b55b-f04fe63519c4.png)

### System Information

- OS [e. g. "Ubuntu"]: Lubuntu 20.04
- Heroic Version [e. g. 2.1.1]: 2.3.9

**Comment by Etaash-mathamsetty** [comment]
it should still let you install the game, I had this warning on my windows pc and everything worked fine. 
and also why are you using NTFS? Try using something else like btrfs that has good support on linux and has a windows driver with winbtrfs

**Comment by flavioislima** [comment]
Heroic let you install in this case. It only blocks if there is no space on the device. Can you check if you have space left on it?

**Comment by clebercasali** [comment]
It won't let me install because the "install" button is disabled.
I do have enough space.
The funny thing is that I've created another directory at the same parent, and it installed successfully there.
