### ISSUE TITLE
Make Heroic install Epic Games Overlay

### ISSUE THREAD

**Issue by Etaash-mathamsetty** [Heroic-Games-Launcher/HeroicGamesLauncher#1516]
### Problem description

The Epic games launcher currently does not install this overlay, some games like among us, complain about the missing epic games overlay. 

### Feature description

Add a feature that automatically installs this new overlay in the wine prefixes that you make, a toggle would be preferable.
This feature only needs to be implemented on linux and probably macos. Windows somehow just installs the overlay no questions asked. (if you have epic games installed)

### Alternatives

installing the overlay manually

**Comment by Dryadxon** [comment]
According to [Epic Games' official development portal](https://dev.epicgames.com/docs/services/en-US/EpicGamesStore/TechFeaturesConfig/EOSOverlay/index.html#installation), the EOS overlay is not yet available as a standalone package.  
This issue cannot be resolved in the near future, unless the Epic Games Store is installed in each prefix that requires the overlay.

**Comment by Etaash-mathamsetty** [comment]
> According to [Epic Games' official development portal](https://dev.epicgames.com/docs/services/en-US/EpicGamesStore/TechFeaturesConfig/EOSOverlay/index.html#installation), the EOS overlay is not yet available as a standalone package. This issue cannot be resolved in the near future, unless the Epic Games Store is installed in each prefix that requires the overlay.

we can sync with the installed epic games to locate the overlay and then run it right?

**Comment by derrod** [comment]
Currently the `install` option would not work for a second prefix, you'd have to use the `enable` action for any further prefixes past the first one.

I should probably add an option to not set up the prefix when downloading it, so you can do that manually.  
It was built very Windows-oriented where you only have a single install/registry, whereas on Linux you have a shared install that just gets added to the prefix' registry.

**Comment by Etaash-mathamsetty** [comment]
ok so the overlay seems to open, but nothing is rendered, I guess that will be fixed in a future dxvk update
it would also be future proofing if we add support now, rather than later

**Comment by mrvictory1** [comment]
> I mean the overlay itself don't work using any wine version at the time.

People have managed to get EOS overlay for Fall Guys running. See
https://www.reddit.com/r/linux_gaming/comments/vi54sh/eos_overlay_on_egs_fall_guys/ (this is mine, I use Heroic and bundled EOS overlay installer)
https://www.reddit.com/r/linux_gaming/comments/vi1mjr/how_to_play_fall_guys_using_egs_and_lutris/ (this method uses lutris & EGS, the overlay automatically works if you use EGS)
https://www.reddit.com/r/linux_gaming/comments/vi9dtn/fallguys_on_epic_games/ (this uses legendary to install EOS Overlay)

**Comment by flavioislima** [comment]
@mrvictory1 yes, now it works.
I meant that when legendary implemented the overlay it didn't.
Now we need to add this option in heroic as well.

**Comment by Etaash-mathamsetty** [comment]
![image](https://user-images.githubusercontent.com/45927311/175799281-94654cae-fb48-49b8-80c4-3ad8bfcfeaa1.png)
huh, it wasn't working in among us

**Comment by flavioislima** [comment]
Done! available on beta 2
