### ISSUE TITLE
HGL doesn't even start

### ISSUE THREAD

**Issue by PRinceBhai** [Heroic-Games-Launcher/HeroicGamesLauncher#1521]
### Describe the bug

HGL doesn't even start for me, all I get is three processes running in the background and when I click on the one process that is supposed to have a window with "Bring to Front" with Task manager it just opens the application with Literally no window and all I see is "Temp Window" whilst hovering on the TB Icon. Tried 2.4.0, 2.3.9 with both portable and Installer versions.

Also is Windows 7 supported? Because that's what I'm running it on.

### Add logs

stub

### Steps to reproduce

Just run the application from start menu. :|

### Expected behavior

Open/Show HGL

### Screenshots

![explorer_20220624-01-19-25_8](https://user-images.githubusercontent.com/39632500/175385753-5ec60dbb-1363-48b6-ba50-c1b8fbb827ae.png)

### System Information

- OS [Windows 7]: 
- Heroic Version [e. g. 2.4.0b]:

**Comment by redromnon** [comment]
Maybe Windows 7 is the issue.

**Comment by flavioislima** [comment]
We support windows 10+ only.
