### ISSUE TITLE
I cant install games on windows 10 as every installation point i choose it says path might not be writable

### ISSUE THREAD

**Issue by AshwinKO** [Heroic-Games-Launcher/HeroicGamesLauncher#1524]
### Describe the bug

I cant install games on windows 10 as every installation point i select it says path might not be writable the install button is grayed out windows 10 20h2 heroic stable latest

### Add logs

(11:30:37) DEBUG:   [Legendary]:       Running Legendary command: C:\Users\ASHWIN~1\AppData\Local\Temp\2AcZ4Y505czDX6swpyJoevv50ov\resources\app.asar.unpacked\build\bin\win32\legendary --version
(11:31:06) INFO:    [Legendary]:       Legendary location: C:\Users\ASHWIN~1\AppData\Local\Temp\2AcZ4Y505czDX6swpyJoevv50ov\resources\app.asar.unpacked\build\bin\win32\legendary
(11:31:06) INFO:    [Gog]:             GOGDL location: C:\Users\ASHWIN~1\AppData\Local\Temp\2AcZ4Y505czDX6swpyJoevv50ov\resources\app.asar.unpacked\build\bin\win32\gogdl
(11:31:06) INFO:    [Backend]:         

Heroic Version: 2.3.9 Brook
Legendary Version:  0.20.26 Dark Energy
OS: Microsoft Windows 10 Pro KERNEL: 10.0.19042 ARCH: x64
CPU: Intel Core™ i5-7200U @2.5 
RAM: Total: 11.88 GiB Available: 8.36 GiB
GRAPHICS: GPU0: NVIDIA GeForce 940MX VRAM: 2048MB DRIVER: 516.40 GPU1: Intel(R) HD Graphics 620 VRAM: 1024MB DRIVER:  

(11:31:06) WARNING: [Backend]:         Protocol already registered.
(11:31:07) INFO:    [Frontend]:        Refreshing Library
(11:31:07) INFO:    [Legendary]:       Refreshing library...
(11:31:07) INFO:    [Legendary]:       Refreshing Epic Games...
(11:31:09) DEBUG:   [Legendary]:       Running Legendary command: C:\Users\ASHWIN~1\AppData\Local\Temp\2AcZ4Y505czDX6swpyJoevv50ov\resources\app.asar.unpacked\build\bin\win32\legendary list
(11:31:11) INFO:    [Legendary]:       Updating game list
(11:31:11) INFO:    [Legendary]:       Game List Updated
(11:31:12) INFO:    [Legendary]:       Checking for game updates: C:\Users\ASHWIN~1\AppData\Local\Temp\2AcZ4Y505czDX6swpyJoevv50ov\resources\app.asar.unpacked\build\bin\win32\legendary list-installed --check-updates --tsv
(11:31:12) DEBUG:   [Legendary]:       Running Legendary command: C:\Users\ASHWIN~1\AppData\Local\Temp\2AcZ4Y505czDX6swpyJoevv50ov\resources\app.asar.unpacked\build\bin\win32\legendary list-installed --check-updates --tsv
(11:31:14) INFO:    [Legendary]:       Found 0 game(s) to update
(11:31:14) INFO:    [Gog]:             Found 0 game(s) to update
(11:32:07) DEBUG:   [Legendary]:       Running Legendary command: C:\Users\ASHWIN~1\AppData\Local\Temp\2AcZ4Y505czDX6swpyJoevv50ov\resources\app.asar.unpacked\build\bin\win32\legendary --version
(11:32:07) DEBUG:   [Gog]:             Running GOGDL command: C:\Users\ASHWIN~1\AppData\Local\Temp\2AcZ4Y505czDX6swpyJoevv50ov\resources\app.asar.unpacked\build\bin\win32\gogdl --version

### Steps to reproduce

1. Go to 'library'
2. Click on 'game and then install'
3. See error

### Expected behavior

should let install games

### System Information

windows 10 20h2 ver 2009

**Comment by AshwinKO** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/99164975/175760934-dd81a5df-d8f6-4283-a167-99acd8517dff.png)

**Comment by AshwinKO** [comment]
anyways fixed the issue myself r

**Comment by HoksterC** [comment]
how did you fix it?

**Comment by AshwinKO** [comment]
> how did you fix it?

just create a folder on the disk drive where you wanna  install with this exact same name "HeroicGamesLauncher"

**Comment by flavioislima** [comment]
Fixed on 2.4.3.
Heroic now checks the previous path and do not complain about a folder that doesn't exist.
