### ISSUE TITLE
Make a warning show when using Proton on Heroic for non-Steam games

### ISSUE THREAD

**Issue by orowith2os** [Heroic-Games-Launcher/HeroicGamesLauncher#1525]
### Problem description

Proton and Proton-GE are not made to be ran outside of Steam, and can have issues when ran with that method.
Wine-GE has the features of Proton-GE, but with the Steam-specific portions cut out. 

### Feature description

1. Move away from using Proton as the runner by default if it's the only runner found and instead prompt the user to install Wine-GE or another Wine version.
2. Disable the Proton-GE download menu on the launcher by default, and instead show it when the user specifically decides to enable it, or remove the Proton-GE download menu entirely and redirect users to use ProtonUp-QT if they decide they want to use Proton as a runner. 
3. Show a very visible, but not annoying, warning icon that states that using Proton outside of Steam is not suggested or supported.

### Alternatives

Stated with the numbering in Feature description

**Comment by flavioislima** [comment]
Did you had any issues using Proton with Heroic?

**Comment by orowith2os** [comment]
Having any issues with using Proton with Heroic is not the problem here, the problem is that Proton is not made to run outside of the Steam runtime environment. I understand that some people's games run with Proton and not with Wine, which is why I didn't suggest removing the ability to use Proton as a runner, but instead require the user to specifically enable Proton as a runner.

**Comment by orowith2os** [comment]
I strongly suggest reading this Reddit post made by Glorious Eggroll about Proton-GE and Wine-GE builds;
https://www.reddit.com/r/linux_gaming/comments/uzrz2k/a_thread_about_using_protonge_and_winege_builds/

**Comment by flavioislima** [comment]
We instruct people to use Wine-GE by default and use Proton as the last resource. But on the Steam Deck, only Proton will be available once you launch Heroic the first time and most people won't know how to use the wine manager or even what Wine is.

Unlike other launchers, Heroic uses proton following the way it should be used: Pointing to Steam runtime, using a STEAM APPID and other variables and settings we do in the background, and also using the proton libs provided on the folder.

The only thing that might never work is the proton fixes.

So, if you are on our discord you will see that people have more success when using Proton than Wine most of the time. Adding a warning will bring more people there to ask for support with Wine for a game that would work fine with Proton. Especially people on Ubuntu that install Wine 5.0 by default.

So we prefer to have a warning on the Logs, that we already have, and ask people to now ask for help on GE discord or GH.
