### ISSUE TITLE
How to change the installation path.

### ISSUE THREAD

**Issue by RiemaruKarurosu** [Heroic-Games-Launcher/HeroicGamesLauncher#1530]
I've the flatpak version, I've installed Detroid Become Human, it runs, but when I restarted my paths change suddendly

Now I've got this. 
![Screenshot_20220626_160301](https://user-images.githubusercontent.com/45057400/175833701-16d29ee0-ced6-432a-89da-eb13dbb31080.png)
y

Log:
Launch Command: STEAM_COMPAT_CLIENT_INSTALL_PATH=/home/riemaru/.var/app/com.heroicgameslauncher.hgl/.steam/steam STEAM_COMPAT_DATA_PATH=/home/riemaru/Games/Heroic/Prefixes/DetroitBecomeHuman WINEESYNC=1 WINEFSYNC=1 STEAM_COMPAT_APP_ID=0 SteamAppId=0 SteamGameId=heroic-DetroitBecomeHuman PROTON_LOG_DIR=/home/riemaru/.var/app/com.heroicgameslauncher.hgl /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary launch Columbine --no-wine --wrapper "'/home/riemaru/.var/app/com.heroicgameslauncher.hgl/config/heroic/tools/proton/Proton-GE-Proton7-20/proton' run"

System Info:
Heroic Version: 2.3.9 Brook
Legendary Version:  0.20.26 Dark Energy
OS: Freedesktop.org KERNEL: 5.18.5-1-MANJARO ARCH: x64
CPU: Intel Core™ i5-9400F @2.9 GOVERNOR: powersave
RAM: Total: 15.55 GiB Available: 10.64 GiB
GRAPHICS: GPU0: GP107 [GeForce GTX 1050 Ti]  VRAM: 32MB DRIVER:  
PROTOCOL: x11

Game Settings: {
	"autoInstallDxvk": false,
	"autoInstallVkd3d": false,
	"enableEsync": true,
	"enableFsync": true,
	"maxSharpness": 2,
	"nvidiaPrime": false,
	"otherOptions": "",
	"savesPath": "",
	"showFps": false,
	"showMangohud": true,
	"targetExe": "",
	"useGameMode": false,
	"wineCrossoverBottle": "Heroic",
	"winePrefix": "/home/riemaru/Games/Heroic/Prefixes/DetroitBecomeHuman",
	"wineVersion": {
		"bin": "/home/riemaru/.var/app/com.heroicgameslauncher.hgl/config/heroic/tools/proton/Proton-GE-Proton7-20/proton",
		"name": "Proton - Proton-GE-Proton7-20",
		"type": "proton"
	}
}

Error Log:
[cli] CRITICAL: Install directory "/run/user/1000/doc/422673ea/heoric/DetroitBecomeHuman" appears to be deleted, cannot launch Columbine!

This is not the path, but I don't know where to change it.
bad path:

[cli] CRITICAL: Install directory "/run/user/1000/doc/422673ea/heoric/DetroitBecomeHuman" appears to be deleted, cannot launch Columbine!

good path:
/none/GAMES/heoric/DetroitBecomeHuman/
(Yes, bad typing xD, but I didn't change it)

**Comment by redromnon** [comment]
There's a _Move Game_ option in the _Tools_ section of a game page that will allow you to move the game install folder to a different path. 
Since you didn't use that option, maybe Heroic doesn't know where it is.

As a workaround, you can uninstall the game and then import the game (select the install button again) by choose the correct folder path you mentioned.

**Comment by flavioislima** [comment]
There is also an option on the game page tools to fix the path. It is called Change install path.

**Comment by RiemaruKarurosu** [comment]
Thanks that work
