### ISSUE TITLE
Games I own in Epic Games wont Open

### ISSUE THREAD

**Issue by jcrosby10** [Heroic-Games-Launcher/HeroicGamesLauncher#1532]
### Describe the bug

I can log in fine but when I go to play a game I own, the game wont open. The button turns red for a  few seconds then turns back green. I had this same problem in Lutris so I thought I would try here but I have the same problem so I am guessing it is a config issue.

I also play games on Steam without issue. But I have games in both stores so I would like to be able to play them all.

### Add logs

n/a

### Steps to reproduce

2. Click on '...'
3. Scroll down to '...'

### Expected behavior

I should be able to open my games. They all worked without issue back when I originally had Windows.

### System Information

I am on Linux Mint 20.3 Cinnamon
Linux kernel 5.4.0-121-generic
AMD Athlon(tm) X4 860K Quad Core Processor x 2
NVIDIA Corporation GM107 [GeForce GTX 750 Ti]
16G memory
Heroic 2.3.9

**Comment by imLinguin** [comment]
This is not Heroic issue, most likely it's misconfiguration on your side. If you use Discord consider joining our server, there someone will help and answer your questions.

**Comment by Etaash-mathamsetty** [comment]
try clicking that refresh button

**Comment by Nocccer** [comment]
@jcrosby10 i think we solved it in discord? If so can you close the ticket please.
