### ISSUE TITLE
Multiple Epic Accounts

### ISSUE THREAD

**Issue by mswift98** [Heroic-Games-Launcher/HeroicGamesLauncher#1534]
### Problem description

I have 2 Epic Games accounts and switching between them is a little frustrating.

### Feature description

It would be awesome if Heroic could save multiple Epic Games accounts and you could switch between them just by clicking on them.

**Comment by Nocccer** [comment]
We don't support it in the near future.

**Comment by Ahmed-E-86** [comment]
@mswift98 Try using the AppImage & the Flatpak of Heroic. They use different config folder.

**Comment by mbledkowski** [comment]
> @mswift98 Try using the AppImage & the Flatpak of Heroic. They use different config folder, and will probably work at the same time.

Hi, I am on Windows, are there any options to switch configs?

**Comment by mbledkowski** [comment]
> We don't support it in the near future.

This would be very helpful feature, I have two (or three idk XD) accounts, one for claiming free games, one for buying them.

**Comment by gmankab** [comment]
i need this feature too

**Comment by nick123456789025** [comment]
I also need this feature The majority of my games on one account and there's three others that I like playing on the other. I accidentally signed into the wrong one when getting these games and they cannot be transferred. Tried contacting support and looking through settings. They refused to do anything about it saying that it's not possible even though other platforms like steam have done it.
