### ISSUE TITLE
Record Playing duration

### ISSUE THREAD

**Issue by mswift98** [Heroic-Games-Launcher/HeroicGamesLauncher#1535]
### Problem description

Heroic doesn't show hours spent on each game.

### Feature description

I want to know how much time I've spent playing Rocket League.

**Comment by arielj** [comment]
It should show that in the game's page, above the Play Now button, is this not showing up for you?
![image](https://user-images.githubusercontent.com/188464/177455211-98c23848-b57a-4f62-8b30-3148e55c91a1.png)

**Comment by mswift98** [comment]
![heroic](https://user-images.githubusercontent.com/56540727/177475759-2d2a2489-53c3-4039-982c-b2f3e6de4d83.JPG)

No, it is not showing and has never been. I use Heroic 2.3.9 on Windows 10.

**Comment by arielj** [comment]
hmmm maybe this is only a Windows issue? I don't have Windows to test

**Comment by flavioislima** [comment]
We have no way o tracking time on Windows now since we cannot monitor the game process.

**Comment by Nocccer** [comment]
We could start a timer on game launch and stop the timer on game exit. Still alot of stuff can make the time inaccurate
