### ISSUE TITLE
Process name is too long

### ISSUE THREAD

**Issue by meanindra** [Heroic-Games-Launcher/HeroicGamesLauncher#1536]
### Describe the bug

Heroic process name (String) is too big and it looks like full spam with 'A'

### Add logs

--

### Steps to reproduce

1. Go to 'System Monitor'
2. Click on 'Heroic Process'

### Expected behavior

Name should be simple for better understanding

### Screenshots

![Screenshot from 2022-06-28 23-40-19](https://user-images.githubusercontent.com/36324543/176259816-2add3083-7c3d-49b1-84c6-aa2e02fcb784.png)

### System Information

- OS: Pop OS 22.04 LTS
- Heroic Version: heroic_2.4.0-beta_amd64.deb

**Comment by arielj** [comment]
I don't think we can do much here, this is probably electron's stuff, this happens to me with a lot of other electron based apps

check this zoom process for example
![image](https://user-images.githubusercontent.com/188464/177455958-4b6dc4d1-a4ef-4671-9f5f-513ccec89c14.png)

or slack
![image](https://user-images.githubusercontent.com/188464/177456196-f81e4984-365c-4555-920e-3fb8a0886b31.png)

or discord
![image](https://user-images.githubusercontent.com/188464/177456217-25964221-a641-4285-b7a0-a3d2d145ede9.png)

each of those is one process, and there are multiple process for each of those apps

**Comment by arielj** [comment]
I'm going to close this since I don't think we can do anything about it, it's not Heroic but Electron that creates these processes, it happens for all electron apps (maybe it's a bug/feature request to report in the electron repos)
