### ISSUE TITLE
"Not enough disk space" when there is enough disk space

### ISSUE THREAD

**Issue by mzamayias** [Heroic-Games-Launcher/HeroicGamesLauncher#1540]
### Describe the bug

There is enough disk space on the system, but Heroic sees that there isn't enough disk space.

### Add logs

(12:56:07) DEBUG:   [Legendary]:       Running Legendary command: /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/legendary --version
(12:56:11) INFO:    [Legendary]:       Legendary location: /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/legendary
(12:56:11) INFO:    [Gog]:             GOGDL location: /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/gogdl
(12:56:11) INFO:    [Backend]:         

Heroic Version: 2.3.9 Brook
Legendary Version:  0.20.26 Dark Energy
OS: macOS KERNEL: 21.5.0 ARCH: x64
CPU: Apple M1 @2.4 
RAM: Total: 16 GiB Available: 11.53 GiB
GRAPHICS: GPU0: Apple M1 VRAM: nullMB DRIVER:  

(12:56:11) WARNING: [Backend]:         Protocol already registered.
(12:56:14) INFO:    [Frontend]:        Refreshing Library
(12:56:14) INFO:    [Legendary]:       Refreshing library...
(12:56:14) INFO:    [Legendary]:       Refreshing Epic Games...
(12:56:15) DEBUG:   [Legendary]:       Running Legendary command: /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/legendary list
(12:56:18) DEBUG:   [Backend]:         Unable to load Steam Libraries, libraryfolders.vdf not found
(12:56:18) DEBUG:   [Backend]:         Unable to load Steam Libraries, libraryfolders.vdf not found
(12:56:22) INFO:    [Legendary]:       Updating game list
(12:56:22) INFO:    [Legendary]:       Game List Updated
(12:56:23) INFO:    [Legendary]:       Checking for game updates: /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/legendary list-installed --check-updates --tsv
(12:56:23) DEBUG:   [Legendary]:       Running Legendary command: /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/legendary list-installed --check-updates --tsv
(12:56:25) DEBUG:   [Backend]:         Unable to load Steam Libraries, libraryfolders.vdf not found
(12:56:26) DEBUG:   [Backend]:         Unable to load Steam Libraries, libraryfolders.vdf not found
(12:56:31) INFO:    [Legendary]:       Found 0 game(s) to update
(12:56:31) INFO:    [Gog]:             Found 0 game(s) to update
(12:56:38) DEBUG:   [Legendary]:       Using cached install info
(12:56:38) DEBUG:   [Legendary]:       Using cached install info
(12:56:38) WARNING: [Backend]:         default is not writable
(12:57:07) DEBUG:   [Legendary]:       Running Legendary command: /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/legendary --version
(12:57:07) DEBUG:   [Gog]:             Running GOGDL command: /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/gogdl --version
(12:57:11) DEBUG:   [Backend]:         Unable to load Steam Libraries, libraryfolders.vdf not found
(12:57:11) DEBUG:   [Backend]:         Unable to load Steam Libraries, libraryfolders.vdf not found
(12:57:27) DEBUG:   [Backend]:         Unable to load Steam Libraries, libraryfolders.vdf not found
(12:57:27) INFO:    [Frontend]:        Refreshing Library
(12:57:27) INFO:    [Legendary]:       Refreshing library...
(12:57:27) INFO:    [Legendary]:       Refreshing Epic Games...
(12:57:27) DEBUG:   [Legendary]:       Running Legendary command: /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/legendary list
(12:57:34) INFO:    [Legendary]:       Updating game list
(12:57:34) INFO:    [Legendary]:       Game List Updated
(12:57:35) INFO:    [Legendary]:       Checking for game updates: /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/legendary list-installed --check-updates --tsv
(12:57:35) DEBUG:   [Legendary]:       Running Legendary command: /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/legendary list-installed --check-updates --tsv
(12:57:46) DEBUG:   [Legendary]:       Using cached install info
(12:57:46) INFO:    [Legendary]:       Found 0 game(s) to update
(12:57:46) INFO:    [Gog]:             Found 0 game(s) to update
(12:57:46) DEBUG:   [Legendary]:       Using cached install info
(12:57:47) DEBUG:   [Legendary]:       Using cached install info
(12:57:47) DEBUG:   [Legendary]:       Using cached install info
(12:57:47) WARNING: [Backend]:         default is not writable
(12:57:55) INFO:    [Legendary]:       Importing Sugar: /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/legendary import Sugar /Users/mzamayias/Games/Heroic
(12:57:55) DEBUG:   [Legendary]:       Running Legendary command: /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/legendary import Sugar /Users/mzamayias/Games/Heroic
(12:57:55) DEBUG:   [Legendary]:       Using cached install info
(12:58:02) INFO:    [Backend]:         imported Rocket League®
(12:58:02) INFO:    [Frontend]:        Refreshing Library
(12:58:02) INFO:    [Legendary]:       Refreshing library...
(12:58:02) INFO:    [Legendary]:       Updating game list
(12:58:02) INFO:    [Legendary]:       Game List Updated
(12:58:02) DEBUG:   [Legendary]:       Using cached install info
(12:58:02) DEBUG:   [Legendary]:       Using cached install info
(12:58:02) DEBUG:   [Legendary]:       Using cached install info
(12:58:03) DEBUG:   [Legendary]:       Using cached install info
(12:58:03) DEBUG:   [Legendary]:       Using cached install info
(12:58:03) WARNING: [Backend]:         default is not writable
(12:58:06) DEBUG:   [Legendary]:       Using cached install info
(12:58:06) DEBUG:   [Legendary]:       Using cached install info
(12:58:06) WARNING: [Backend]:         default is not writable
(12:59:46) DEBUG:   [Legendary]:       Using cached install info
(12:59:46) DEBUG:   [Legendary]:       Using cached install info
(12:59:46) WARNING: [Backend]:         default is not writable
(13:00:28) DEBUG:   [Legendary]:       Using cached install info
(13:00:29) DEBUG:   [Legendary]:       Using cached install info
(13:00:29) DEBUG:   [Legendary]:       Using cached install info
(13:00:29) WARNING: [Backend]:         default is not writable
(13:01:04) DEBUG:   [Legendary]:       Using cached install info
(13:01:04) DEBUG:   [Legendary]:       Using cached install info
(13:01:04) WARNING: [Backend]:         default is not writable
(13:01:04) WARNING: [Backend]:         /Users/mzamayias/Games/Heroic is not writable
(13:01:04) WARNING: [Backend]:         /Users/mzamayias/Games/Heroic is not writable
(13:01:13) DEBUG:   [Legendary]:       Using cached install info
(13:01:13) DEBUG:   [Legendary]:       Using cached install info
(13:01:13) WARNING: [Backend]:         default is not writable
(13:01:15) DEBUG:   [Legendary]:       Using cached install info
(13:01:15) DEBUG:   [Legendary]:       Using cached install info
(13:01:15) WARNING: [Backend]:         default is not writable
(13:02:23) DEBUG:   [Legendary]:       Using cached install info
(13:02:23) DEBUG:   [Legendary]:       Using cached install info
(13:02:23) WARNING: [Backend]:         default is not writable

### Steps to reproduce

1. Double click any game that's only Windows native from the Library
2. Click on Install
3. See error

### Expected behavior

Heroic should see the correct amount of available disk space on the system.

### Screenshots

<img width="1680" alt="Screenshot 2022-07-01 at 13 02 54" src="https://user-images.githubusercontent.com/29067825/176873737-456f2a13-6a25-4e8d-8a27-74b30f2c3dd6.png">

### System Information

- OS [e. g. "Ubuntu"]: macOS 12.4 21F79 arm64
- Heroic Version [e. g. 2.1.1]: 2.3.9

### Additional information

I'm using CrossOver 21.2 (21.2.0.33926)

**Comment by Renari** [comment]
I can't confirm this currently but usually applications are downloaded in a compressed format and then extracted. If that is how this works you need roughly double the storage of the application.

**Comment by flavioislima** [comment]
@mzamayias can you download heroic 2.4.0 beta 2 and try again?

**Comment by Nocccer** [comment]
Please check that the partition has enough disk space. I think heroic is pretty celar about that. We had the problems alot now and it was always the users fault. Means the os showed incorrect information or the user did not check the partition space!

**Comment by flavioislima** [comment]
Just tested here on macOS and on Beta 2 it works fine. Tried the same game.

**Comment by jjz1231** [comment]
I'm totally new to this stuff and i have the same issue (with Rocket League)
Can i do something about it?
thx

**Comment by Nocccer** [comment]
You need free disk space. So deinstall stuff you don't need anymore. We can't create free disk space out of nothing ...

**Comment by jjz1231** [comment]
Okay I'm sorry for this question :)
Now it's downloading 
I was completely sure that I have enough space
Anyways Thank you :)

**Comment by ovvldc** [comment]
I see 234.69 GB free in Finder, and 63.69 GiB if I choose the same folder according to Heroic. Definitely on the same file system, and it stays after I reboot.
