### ISSUE TITLE
set windows user agent while browsing epic games store

### ISSUE THREAD

**Issue by Etaash-mathamsetty** [Heroic-Games-Launcher/HeroicGamesLauncher#1542]
### Problem description

It's pretty annoying when I am trying to get a game on the epic games store and it says "this item is not compatible with your device" when 7/10 times it is. 

### Feature description

set the user agent to a windows one (maybe with a toggle or only on the linux build) so that people don't have to keep seeing this message.

**Comment by flavioislima** [comment]
We tried that in the past but broke the login.
We would need to use different user agents depending on the URL for this to work.

**Comment by flavioislima** [comment]
done
