### ISSUE TITLE
SID not working at all

### ISSUE THREAD

**Issue by xbohbo** [Heroic-Games-Launcher/HeroicGamesLauncher#1544]
### Describe the bug

So I just got the Heroic Games Launcher, and I'm using crossover, which works great. Earlier I ran into an issue with the SID, so I thought I just didn't know what I was doing so I shrugged it off and said I'll just fix it later. Now, however when I enter the SID, It only loads and brings me back to the same page where It says; "Epic Games Store, Log In, External Login, etc... I have no idea what could be wrong and I know the SID is something like 13f6b4b09ad84f6080f66638af5e91e8 

### Add logs

(19:31:41) DEBUG:   [Legendary]:       Running Legendary command: /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/legendary --version

(19:31:43) INFO:    [Legendary]:       Legendary location: /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/legendary

(19:31:43) INFO:    [Gog]:             GOGDL location: /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/gogdl

(19:31:43) INFO:    [Backend]:         

Heroic Version: 2.3.9 Brook

Legendary Version:  0.20.26 Dark Energy

OS: Mac OS X KERNEL: 18.7.0 ARCH: x64

CPU: Intel Core™ i7-3520M @2.9 

RAM: Total: 16 GiB Available: 10.68 GiB

GRAPHICS: GPU0: Intel HD Graphics 4000 VRAM: 1536MB DRIVER:  

(19:31:43) INFO:    [Backend]:         User Not Found, removing it from Store

(19:31:43) WARNING: [Backend]:         Protocol already registered.

(19:38:00) DEBUG:   [Backend]:         Unable to load Steam Libraries, libraryfolders.vdf not found

(19:38:00) DEBUG:   [Backend]:         Unable to load Steam Libraries, libraryfolders.vdf not found

(19:39:30) INFO:    [Legendary]:       Logging in with Legendary: /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/legendary auth --sid <redacted>

(19:39:30) DEBUG:   [Legendary]:       Running Legendary command: /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/legendary auth --sid <redacted>

(19:39:31) INFO:    [Legendary]:       Logging in with Legendary: /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/legendary auth --sid <redacted>

(19:39:31) DEBUG:   [Legendary]:       Running Legendary command: /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/legendary auth --sid <redacted>

(19:39:31) INFO:    [Frontend]:        Refreshing Library

(19:39:31) INFO:    [Legendary]:       Refreshing library...

(19:39:31) INFO:    [Frontend]:        Called Login

(19:39:31) INFO:    [Frontend]:        No cache found, getting data from legendary...

(19:39:31) INFO:    [Legendary]:       Refreshing library...

(19:39:32) INFO:    [Frontend]:        Refreshing Library

(19:39:32) INFO:    [Legendary]:       Refreshing library...

(19:39:32) INFO:    [Frontend]:        Called Login

(19:39:32) INFO:    [Frontend]:        No cache found, getting data from legendary...

(19:39:32) INFO:    [Legendary]:       Refreshing library...

(19:39:49) INFO:    [Legendary]:       Logging in with Legendary: /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/legendary auth --sid <redacted>

(19:39:49) DEBUG:   [Legendary]:       Running Legendary command: /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/legendary auth --sid <redacted>

(19:39:50) INFO:    [Frontend]:        Refreshing Library

(19:39:50) INFO:    [Legendary]:       Refreshing library...

(19:39:50) INFO:    [Frontend]:        Called Login

(19:39:50) INFO:    [Frontend]:        No cache found, getting data from legendary...

(19:39:50) INFO:    [Legendary]:       Refreshing library...

(19:40:54) INFO:    [Legendary]:       Logging in with Legendary: /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/legendary auth --sid <redacted>

(19:40:54) DEBUG:   [Legendary]:       Running Legendary command: /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/legendary auth --sid <redacted>

(19:40:55) INFO:    [Frontend]:        Refreshing Library

(19:40:55) INFO:    [Legendary]:       Refreshing library...

(19:40:55) INFO:    [Frontend]:        Called Login

(19:40:55) INFO:    [Frontend]:        No cache found, getting data from legendary...

(19:40:55) INFO:    [Legendary]:       Refreshing library...

(19:42:34) INFO:    [Legendary]:       Logging in with Legendary: /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/legendary auth --sid <redacted>

(19:42:34) DEBUG:   [Legendary]:       Running Legendary command: /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/legendary auth --sid <redacted>

(19:42:36) INFO:    [Frontend]:        Refreshing Library

(19:42:36) INFO:    [Legendary]:       Refreshing library...

(19:42:36) INFO:    [Frontend]:        Called Login

(19:42:36) INFO:    [Frontend]:        No cache found, getting data from legendary...

(19:42:36) INFO:    [Legendary]:       Refreshing library...

(19:42:51) INFO:    [Legendary]:       Logging in with Legendary: /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/legendary auth --sid <redacted>

(19:42:51) DEBUG:   [Legendary]:       Running Legendary command: /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/legendary auth --sid <redacted>

(19:42:51) INFO:    [Legendary]:       Logging in with Legendary: /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/legendary auth --sid <redacted>

(19:42:51) DEBUG:   [Legendary]:       Running Legendary command: /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/legendary auth --sid <redacted>

(19:42:52) INFO:    [Legendary]:       Logging in with Legendary: /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/legendary auth --sid <redacted>

(19:42:52) DEBUG:   [Legendary]:       Running Legendary command: /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/legendary auth --sid <redacted>

(19:42:52) INFO:    [Legendary]:       Logging in with Legendary: /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/legendary auth --sid <redacted>

(19:42:52) DEBUG:   [Legendary]:       Running Legendary command: /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/legendary auth --sid <redacted>

(19:42:55) INFO:    [Frontend]:        Refreshing Library

(19:42:55) INFO:    [Legendary]:       Refreshing library...

(19:42:55) INFO:    [Frontend]:        No cache found, getting data from legendary...

(19:42:56) INFO:    [Legendary]:       Refreshing library...

(19:42:56) INFO:    [Frontend]:        Refreshing Library

(19:42:56) INFO:    [Legendary]:       Refreshing library...

(19:42:56) INFO:    [Frontend]:        No cache found, getting data from legendary...

(19:42:56) INFO:    [Legendary]:       Refreshing library...

(19:42:57) INFO:    [Frontend]:        Refreshing Library

(19:42:57) INFO:    [Legendary]:       Refreshing library...

(19:42:57) INFO:    [Frontend]:        No cache found, getting data from legendary...

(19:42:57) INFO:    [Legendary]:       Refreshing library...

(19:42:57) INFO:    [Frontend]:        Refreshing Library

(19:42:57) INFO:    [Legendary]:       Refreshing library...

(19:42:57) INFO:    [Frontend]:        No cache found, getting data from legendary...

(19:42:57) INFO:    [Legendary]:       Refreshing library...

(19:43:08) INFO:    [Legendary]:       Logging in with Legendary: /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/legendary auth --sid <redacted>

(19:43:08) DEBUG:   [Legendary]:       Running Legendary command: /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/legendary auth --sid <redacted>

(19:43:09) INFO:    [Legendary]:       Logging in with Legendary: /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/legendary auth --sid <redacted>

(19:43:09) DEBUG:   [Legendary]:       Running Legendary command: /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/legendary auth --sid <redacted>

(19:43:11) INFO:    [Legendary]:       Logging in with Legendary: /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/legendary auth --sid <redacted>

(19:43:11) DEBUG:   [Legendary]:       Running Legendary command: /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/legendary auth --sid <redacted>

(19:43:11) INFO:    [Frontend]:        Refreshing Library

(19:43:11) INFO:    [Legendary]:       Refreshing library...

(19:43:11) INFO:    [Frontend]:        Called Login

(19:43:11) INFO:    [Frontend]:        No cache found, getting data from legendary...

(19:43:11) INFO:    [Legendary]:       Refreshing library...

(19:43:14) INFO:    [Frontend]:        Refreshing Library

(19:43:14) INFO:    [Legendary]:       Refreshing library...

(19:43:14) INFO:    [Frontend]:        Called Login

(19:43:14) INFO:    [Frontend]:        No cache found, getting data from legendary...

(19:43:14) INFO:    [Legendary]:       Refreshing library...

(19:43:15) INFO:    [Frontend]:        Refreshing Library

(19:43:15) INFO:    [Legendary]:       Refreshing library...

(19:43:15) INFO:    [Frontend]:        Called Login

(19:43:15) INFO:    [Frontend]:        No cache found, getting data from legendary...

(19:43:15) INFO:    [Legendary]:       Refreshing library...

### Steps to reproduce

2. Click on '...'
3. Scroll down to '...'

### Expected behavior

I know It's supposed to redirect you to a library of some sorts.

### System Information

- OS [e. g. "Ubuntu"]: 
- Heroic Version [e. g. 2.1.1]:

**Comment by flavioislima** [comment]
You forgot to add the Operational System information, but I guess you are using macOS High Sierra or an older version and Heroic supports only 10.15 and up.

Reopen the issue if I am mistaken but add more info so we can help you.
