### ISSUE TITLE
Option to hide/disable storefronts.

### ISSUE THREAD

**Issue by Bitwolfies** [Heroic-Games-Launcher/HeroicGamesLauncher#1546]
### Problem description

I dislike the fact that a store I will never use takes up folders and spots in the launcher.

### Feature description

Let us disable stores entirely, be they Epic or GoG, remove any folders they generate and any options for them in the launcher.

**Comment by flavioislima** [comment]
That makes no sense. Heroic only creates folders and files after you log in to some store. 
I cannot see any value in implementing this neither for the end user or for Heroic itself.

**Comment by madman-asunder** [comment]
Hold up... you see no use in hiding a store that a user doesn't use? What the hell are you smoking? You literally made an app to replace bloated front ends and you see no point in letting the user further customize what services they use?

That might be the craziest thing I've ever read.
