### ISSUE TITLE
Quotation Marks in the Advanced Optons

### ISSUE THREAD

**Issue by Diyou** [Heroic-Games-Launcher/HeroicGamesLauncher#1552]
### Describe the bug

Quotation Marks in the Advanced Optons string do not get properly escapted duing the launch of the game(I'm assuming this also for Game Arguments).

In the log you can see the string is getting cut at the first whitespace after PROTON_EAC_RUNTIME="/mnt/d/Games/steamapps/common/Proton

in the Game Settings json string it gets seemingly properly escaped:
"otherOptions": "PROTON_EAC_RUNTIME=\"/mnt/d/Games/steamapps/common/Proton EasyAntiCheat Runtime/\"",

### Add logs

Launch Command: PROTON_EAC_RUNTIME="/mnt/d/Games/steamapps/common/Proton STEAM_COMPAT_CLIENT_INSTALL_PATH=/home/$USER/.steam/steam STEAM_COMPAT_DATA_PATH=/home/$USER/Games/Heroic/Prefixes/FallGuys WINE_FULLSCREEN_FSR=1 WINE_FULLSCREEN_FSR_STRENGTH=2 WINEFSYNC=1 STEAM_COMPAT_APP_ID=0 SteamAppId=0 SteamGameId=heroic-FallGuys PROTON_LOG_DIR=/home/$USER EasyAntiCheat Runtime/" /usr/bin/mangohud --dlsym /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary launch <token> --no-wine --wrapper "'/home/$USER/.local/share/Steam/compatibilitytools.d/GE-Proton7-24/proton' run"

System Info:

Heroic Version: 2.3.9 Brook

Legendary Version:  0.20.26 Dark Energy

OS: ManjaroLinux KERNEL: 5.17.15-1-MANJARO ARCH: x64

CPU: AMD Ryzen 7 3700X 8-Core Processor @3.6 GOVERNOR: schedutil

RAM: Total: 31.3 GiB Available: 22.69 GiB

GRAPHICS: GPU0: NVIDIA GeForce GTX 1080 VRAM: 8192MB DRIVER: 515.57 

PROTOCOL: x11

Game Settings: {

	"checkUpdatesInterval": 10,

	"enableUpdates": false,

	"addDesktopShortcuts": false,

	"addStartMenuShortcuts": false,

	"autoInstallDxvk": false,

	"autoInstallVkd3d": false,

	"checkForUpdatesOnStartup": true,

	"customWinePaths": [],

	"defaultInstallPath": "/mnt/d/Games",

	"defaultWinePrefix": "/home/$USER/Games/Heroic/Prefixes",

	"language": "en",

	"maxWorkers": 0,

	"minimizeOnLaunch": false,

	"nvidiaPrime": false,

	"otherOptions": "PROTON_EAC_RUNTIME=\"/mnt/d/Games/steamapps/common/Proton EasyAntiCheat Runtime/\"",

	"showUnrealMarket": false,

	"showFps": false,

	"useGameMode": false,

	"userInfo": {

		"epicId": "MY ID",

		"name": "ME"

	},

	"wineCrossoverBottle": "Heroic",

	"winePrefix": "/home/$USER/Games/Heroic/Prefixes/FallGuys",

	"wineVersion": {

		"bin": "/home/$USER/.local/share/Steam/compatibilitytools.d/GE-Proton7-24/proton",

		"name": "Proton - GE-Proton7-24",

		"type": "proton"

	},

	"altLegendaryBin": "",

	"altGogdlBin": "",

	"darkTrayIcon": true,

	"disableController": false,

	"discordRPC": true,

	"egsLinkedPath": "",

	"enableEsync": false,

	"enableFsync": true,

	"maxRecentGames": 5,

	"showMangohud": true,

	"enableFSR": true,

	"maxSharpness": 2,

	"savesPath": "",

	"targetExe": "",

	"useSteamRuntime": false

}

Error Log:

Error: spawn EasyAntiCheat ENOENT

### Steps to reproduce

1. Go to some Game Settings > Other
2. Enter something like PROTON_EAC_RUNTIME="/mnt/d/Games/steamapps/common/Proton EasyAntiCheat Runtime/"
3. See Error: spawn EasyAntiCheat ENOENT

### Expected behavior

Should launch the game with options

### System Information

- OS [e. g. "Ubuntu"]: Manjaro
- Heroic Version [e. g. 2.1.1]: 2.3.9-2

### Additional information

I'm launching the game via Heroic Bash Launcher which works as one would expect.
A workaround would be emitting this options and launch through steam and adding them before %command% in the Launch Options of the non-steam game created with Heroic Bash Launcher.

**Comment by arielj** [comment]
There's currently a PR refactoring how that configuration is managed by heroic https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/pull/1533

Can you try with this appImage https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/actions/runs/2630592676 if the problem still exists? You won't need the `"` when adding the value for an env variable and it should handle white spaces properly (use the new method of adding env variables using the new table, not the `advanced options` field)

**Comment by Diyou** [comment]
With the appimage the Launch Command is created properly but the variable with the whitespace does not take effect when launched through the launcher itself but works when copied into the terminal.

The environment variable without whitespaces works tho. So we are halfway there :D

**Comment by arielj** [comment]
@Nocccer tagging you since you know more about that feature, maybe it's something to check there

**Comment by Nocccer** [comment]
I have no clue? Can you show me the created command?

**Comment by Nocccer** [comment]
I found one small bug i had. Sometimes a extra spaces was added at the end. Now values are trimmed. Can you try again?

**Comment by Nocccer** [comment]
You need to add the env variable again.

**Comment by Diyou** [comment]
`DXVK_FRAME_RATE=120 PROTON_EAC_RUNTIME="/mnt/d/Games/steamapps/common/Proton EasyAntiCheat Runtime/" STEAM_COMPAT_CLIENT_INSTALL_PATH=/home/$user/.steam/steam STEAM_COMPAT_DATA_PATH=/home/$user/Games/Heroic/Prefixes/FallGuys WINE_FULLSCREEN_FSR=1 WINE_FULLSCREEN_FSR_STRENGTH=2 WINEFSYNC=1 STEAM_COMPAT_APP_ID=0 SteamAppId=0 SteamGameId=heroic-FallGuys PROTON_LOG_DIR=/home/$user /usr/bin/mangohud --dlsym /usr/bin/legendary launch <some token> --language en --no-wine --wrapper "'/home/$user/.local/share/Steam/compatibilitytools.d/GE-Proton7-24/proton' run"`

As I said ... the command is created properly with the appimage and the game works just fine running it from the terminal or through steam with the Heroic Bash Launcher script.
DXVK_FRAME_RATE=120 works
PROTON_EAC_RUNTIME="/mnt/d/Games/steamapps/common/Proton EasyAntiCheat Runtime/" does not affect the game when started from the "Heroic Games Launcher" and EAC does not get initialized.
Everything is setup correctly.

**Comment by Nocccer** [comment]
Ok i removed the quotes now. Here is a video of the value we passing to spawn now:
https://user-images.githubusercontent.com/61798668/178147479-83237fde-8f1c-454a-a769-67d022e71707.mp4

Fall Guys crashes for me now before the menu. Maybe it is a sign that somehow eac got in the way ?

**Comment by Diyou** [comment]
For FallGuys you need to copy or create a symlink of FallGuys/EasyAntiCheat/easyanticheat_x64.so to FallGuys/FallGuys_client_game_Data/Plugins/x86_64/easyanticheat_x64.so and change the first line in FallGuys/FallGuys_client.ini to:
`TargetApplicationPath=FallGuys_client_game.exe`

Additionally I get a similar behaviour when adding multiple Game Arguments like
`-NoStartupMovies -notexturestreaming` for Borderlands 3 where adding the second argument makes the Startup Movies play again. Not sure if the notexturestreaming works tho.
Again ... using the Heroic Bash Launcher script through Steam works.
The Borderlands 3 Launch Command with those 2 arguments would look like:

`Launch Command: DXVK_FRAME_RATE=120 ENABLE_VKBASALT=1 STEAM_COMPAT_CLIENT_INSTALL_PATH=/home/$user/.steam/steam STEAM_COMPAT_DATA_PATH=/home/$user/Games/Heroic/Prefixes/Borderlands3 WINE_FULLSCREEN_FSR=1 WINE_FULLSCREEN_FSR_STRENGTH=4 WINEESYNC=1 WINEFSYNC=1 STEAM_COMPAT_APP_ID=0 SteamAppId=0 SteamGameId=heroic-Borderlands3 PROTON_LOG_DIR=/home/$user /usr/bin/mangohud --dlsym /usr/bin/gamemoderun /usr/bin/legendary launch Catnip --language en --no-wine --wrapper "'/home/$user/.local/share/Steam/compatibilitytools.d/GE-Proton7-24/proton' run" "-NoStartupMovies -notexturestreaming"`

Same behaviour in the 2.3.9 and 2.4 beta AppImage

**Comment by Nocccer** [comment]
> For FallGuys you need to copy or create a symlink of FallGuys/EasyAntiCheat/easyanticheat_x64.so to FallGuys/FallGuys_client_game_Data/Plugins/x86_64/easyanticheat_x64.so and change the first line in FallGuys/FallGuys_client.ini to: `TargetApplicationPath=FallGuys_client_game.exe` Taken from : [Reddit](https://www.reddit.com/r/SteamDeck/comments/vht8d1/fall_guys_f2p_epic_version_tutorial_for_steam_deck/?utm_medium=android_app&utm_source=share)
> 
> Additionally I get a similar behaviour when adding multiple Game Arguments like `-NoStartupMovies -notexturestreaming` for Borderlands 3 where adding the second argument makes the Startup Movies play again. Not sure if the notexturestreaming works tho. Again ... using the Heroic Bash Launcher script through Steam works. The Borderlands 3 Launch Command with those 2 arguments would look like:
> 
> `Launch Command: DXVK_FRAME_RATE=120 ENABLE_VKBASALT=1 STEAM_COMPAT_CLIENT_INSTALL_PATH=/home/$user/.steam/steam STEAM_COMPAT_DATA_PATH=/home/$user/Games/Heroic/Prefixes/Borderlands3 WINE_FULLSCREEN_FSR=1 WINE_FULLSCREEN_FSR_STRENGTH=4 WINEESYNC=1 WINEFSYNC=1 STEAM_COMPAT_APP_ID=0 SteamAppId=0 SteamGameId=heroic-Borderlands3 PROTON_LOG_DIR=/home/$user /usr/bin/mangohud --dlsym /usr/bin/gamemoderun /usr/bin/legendary launch Catnip --language en --no-wine --wrapper "'/home/$user/.local/share/Steam/compatibilitytools.d/GE-Proton7-24/proton' run" "-NoStartupMovies -notexturestreaming"`
> 
> Same behaviour in the 2.3.9 and 2.4 beta AppImage

Thanks for the description. I already know that. I also can confirm that enviroment is passed correctly. Now this
```
terminate called after throwing an instance of 'std::logic_error'

  what():  basic_string::_S_construct null not valid
```
occurs and we don't have a clue why. But this is not a problem of quoting. It has something todo with libs not matching. Steam does some magic stuff to solve this. @CommandMC tried to solve this, but i think without success

**Comment by CommandMC** [comment]
Enabling Game Mode will solve that issue. No idea why, no-one I asked had any idea why, but it works

**Comment by Nocccer** [comment]
@Diyou i think i fixed the launch arguments. Can you test it for me? It is in the same PR with the enviroment variable changes.

**Comment by Diyou** [comment]
Looks good ... Fall Guys is playable through the launcher itself and multiple game arguments get applied properly now.
Looking forward to see the 2.4 release.
This issue can be closed now and thank you guys for your work.

**Comment by Nocccer** [comment]
> Configurations of 2.3.9 will break on updating to 2.4 ![2 3 9](https://user-images.githubusercontent.com/21966966/178247042-b3dcffdd-c4c7-4f10-8005-828bc87727b4.png) turns into (the path gets split up and put into the wrapper) ![2 4 0](https://user-images.githubusercontent.com/21966966/178247090-26f6f2d0-b17b-4ee6-aa9a-aaf32fd6ac58.png)
> 
> Additionally you might strip surrounding quotes from the variables if the user enters them accidentally because he copied them inappropriately and validate the configuration file if the user edited it externally. My changes took only effect after I deleted the old ones and added them back in. Making the field editable would be very nice.

It is working. The whole story of my pr was to support spaces in path. Heroic 2.3.9 does not allow spaces in paths.
So setting advanced options with this path, would not work on heroic 2.3.9. 
Paths or args without spaces are passed correctly to the new design.

**Comment by Diyou** [comment]
> Very weird indeed. Maybe the issue relates to the node's spawn since you can launch the game with the bash script just fine.

Correction: It doesn't ... same issue here.

**Comment by Nocccer** [comment]
Ok i googled a little bit was LD_PRELOAD does. For me it sounds like the problem we have here and i will try to fix now.
https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/issues/1334

**Comment by Nocccer** [comment]
> ```js
> process.env.LD_PRELOAD=''
> ```
> 
> or setting LD_PRELOAD to an empty string anywhere fixes the issue. I don't know if this will break something elsewhere tho.

Got it to work. It really fails if LD_PRELOAD is not set by the system. I added a check which defines LD_PRELOAD if undefined.

Thanks alot for this investigation.
