### ISSUE TITLE
Install games into shared folder between Linux and Windows

### ISSUE THREAD

**Issue by 20PercentRendered** [Heroic-Games-Launcher/HeroicGamesLauncher#1553]
### Describe the bug

I use Heroic to install my games into a btrfs drive shared with Windows. I can play games from Linux and Windows just fine. However, when I install a game from Linux and access Heroic's settings for the game on Windows, it shows the "WIne" sub-menu.
If a game has an update available, you cannot update it from Windows as it breaks launching the game and corrupts the executables. 

### Add logs

(23:29:37) DEBUG:   [Legendary]:       Running Legendary command: C:\Users\Onni\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\legendary --version
(23:29:41) INFO:    [Legendary]:       Legendary location: C:\Users\Onni\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\legendary
(23:29:41) INFO:    [Gog]:             GOGDL location: C:\Users\Onni\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\gogdl
(23:29:41) INFO:    [Backend]:         

Heroic Version: 2.3.9 Brook
Legendary Version:  0.20.26 Dark Energy
OS: Microsoft Windows 10 Pro KERNEL: 10.0.19044 ARCH: x64
CPU: Intel Core™ i7-7800X @3.5 
RAM: Total: 47.69 GiB Available: 41.06 GiB
GRAPHICS: GPU0: NVIDIA GeForce RTX 2080 VRAM: 8192MB DRIVER: 512.59 

(23:29:41) WARNING: [Backend]:         Protocol already registered.
(23:29:43) INFO:    [Backend]:         Launching Dead by Daylight (Brill)
(23:29:43) INFO:    [Legendary]:       Launching Dead by Daylight: C:\Users\Onni\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\legendary launch Brill
(23:29:43) DEBUG:   [Legendary]:       Running Legendary command: C:\Users\Onni\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\legendary launch Brill
(23:29:45) DEBUG:   [Legendary]:       Running Legendary command: C:\Users\Onni\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\legendary --version
(23:29:49) INFO:    [Backend]:         Log was written to C:\Users\Onni\AppData\Roaming\heroic\GamesConfig\Brill-lastPlay.log
(23:29:49) INFO:    [Frontend]:        Refreshing Library
(23:29:49) INFO:    [Legendary]:       Refreshing library...
(23:29:49) INFO:    [Legendary]:       Updating game list
(23:29:49) INFO:    [Legendary]:       Game List Updated
(23:29:49) INFO:    [Frontend]:        Force Update
(00:05:54) INFO:    [Backend]:         Launching Fall Guys (0a2d9f6403244d12969e11da6713137b)
(00:05:54) INFO:    [Legendary]:       Launching Fall Guys: C:\Users\Onni\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\legendary launch 0a2d9f6403244d12969e11da6713137b --skip-version-check
(00:05:54) DEBUG:   [Legendary]:       Running Legendary command: C:\Users\Onni\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\legendary launch 0a2d9f6403244d12969e11da6713137b --skip-version-check
(00:05:56) DEBUG:   [Legendary]:       Running Legendary command: C:\Users\Onni\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\legendary --version
(00:06:03) INFO:    [Backend]:         Log was written to C:\Users\Onni\AppData\Roaming\heroic\GamesConfig\0a2d9f6403244d12969e11da6713137b-lastPlay.log
(00:06:03) INFO:    [Frontend]:        Refreshing Library
(00:06:03) INFO:    [Legendary]:       Refreshing library...
(00:06:03) INFO:    [Legendary]:       Updating game list
(00:06:03) INFO:    [Legendary]:       Game List Updated
(00:06:09) DEBUG:   [Backend]:         Unable to load Steam Libraries, libraryfolders.vdf not found
(00:06:36) DEBUG:   [Backend]:         Unable to load Steam Libraries, libraryfolders.vdf not found
(00:06:36) DEBUG:   [Backend]:         Unable to load Steam Libraries, libraryfolders.vdf not found
(00:06:38) ERROR:   [Legendary]:       runWineCommand called on native game!
(00:06:38) ERROR:   [Legendary]:       runWineCommand called on native game!
(00:06:48) DEBUG:   [Backend]:         Unable to load Steam Libraries, libraryfolders.vdf not found
(00:06:55) INFO:    [Backend]:         Launching Fall Guys (0a2d9f6403244d12969e11da6713137b)
(00:06:55) INFO:    [Legendary]:       Launching Fall Guys: C:\Users\Onni\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\legendary launch 0a2d9f6403244d12969e11da6713137b --skip-version-check
(00:06:55) DEBUG:   [Legendary]:       Running Legendary command: C:\Users\Onni\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\legendary launch 0a2d9f6403244d12969e11da6713137b --skip-version-check
(00:06:56) DEBUG:   [Legendary]:       Running Legendary command: C:\Users\Onni\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\legendary --version
(00:07:00) INFO:    [Backend]:         Log was written to C:\Users\Onni\AppData\Roaming\heroic\GamesConfig\0a2d9f6403244d12969e11da6713137b-lastPlay.log
(00:07:00) INFO:    [Frontend]:        Refreshing Library
(00:07:00) INFO:    [Legendary]:       Refreshing library...
(00:07:00) INFO:    [Legendary]:       Updating game list
(00:07:00) INFO:    [Legendary]:       Game List Updated

### Steps to reproduce

1. Install a game on Linux into a shared folder
2. Edit wine settings of game and launch it
3. Close the game and reboot to Windows
4. Wait for a game update to come
5. Update the game
6. Try to launch

### Expected behavior

1. Install game from Linux to shared folder
2. Set whatever settings you please
3. Play on linux
4. Reboot to windows
5. Play on Windows
6. Set whatever settings you want on Windows
7. Update the game on Windows without breaking.

### System Information

- OS [e. g. "Ubuntu"]: Arch
- Heroic Version [e. g. 2.1.1]: 2.3.9

**Comment by Nocccer** [comment]
I don't know if this is even possible. The save folders will be on different places.
- Linux -> mostly in prefix
- Windows -> somewhere in user folder
