### ISSUE TITLE
I would like to be able to choose the language both in general for all the games and specifically

### ISSUE THREAD

**Issue by Sightlyjester** [Heroic-Games-Launcher/HeroicGamesLauncher#1554]
### Problem description

In general I like to use Heroic Game Launcher quite a bit more than the Epic Games Store on my Steam Deck to install game. The problem is that while in the Epic Games Store you can choose to apply the Spanish language generally in the application and also in certain games with launch commands when you want to force the Spanish language because it depends on the game itself...Heroic Games Launcher does not allow either option, and I would like to see it implemented in a future update. As a Spanish user of this app, it is very frustrating not to be able to use it because all the games are in English when I launch them, which forces me to use the Epic Games Store :(

### Feature description

Update with selector of language to the general aplication and also to force on specific games which do not show the game language you selected in general in the application

**Comment by Nocccer** [comment]
Did you tried our Beta. There you can set languages for each games. But not all games support this flag. Some games try to get the language from `locale`.

**Comment by mbarchein** [comment]
> Did you tried our Beta. There you can set languages for each games. But not all games support this flag. Some games try to get the language from `locale`.

I'm using the beta and this setting works, but it doesn't get saved. Each time I run heroic, I must set the language for the game again.

**Comment by Nocccer** [comment]
Ok sounds like a bug. Can you set the language and toggle a checkbox on/off. Does it then store the language?

**Comment by mbarchein** [comment]
Hello, Nocccer. It is fixed on the latest beta (2.4.0 Beta 2). Changing only the language and closing heroic saves this setting for the next restart. Thanks!

**Comment by Nocccer** [comment]
> Hello, Nocccer. It is fixed on the latest beta (2.4.0 Beta 2). Changing only the language and closing heroic saves this setting for the next restart. Thanks!

setting language in general settings only apply for new installed games, else you need to set it per game.
