### ISSUE TITLE
[Steam Deck] heroic:// handler doesn't work with GOG games

### ISSUE THREAD

**Issue by tomsik-radek** [Heroic-Games-Launcher/HeroicGamesLauncher#1556]
### Describe the bug

I use boilR to import Heroic games into Steam. I recently reformatted my Deck and tried to do what I did before, but this time those shortcuts don't work.

It seems like the heroic:// handler doesn't seem to work for GOG games when the launcher isn't running. EGS games launch just fine (they start the launcher and quit the launcher on their own without any issues). Both games are installed on an SD card.  Heroic has full access to the SD card.
If I run the launch command when Heroic is running but minimized, it opens for a second and then the game launches.
Please see linked Youtube video here. Video shows a GOG game (Cyberpunk 2077) and Epic Games Store game (Absolute Drift)
https://www.youtube.com/watch?v=0VGRp1_qDp8

Log isn't from Heroic directly but it is Terminal output when trying to run the command manually. To be exact, it is this command
`"/usr/bin/flatpak" run com.heroicgameslauncher.hgl heroic://launch/AppName --no-gui --no-sandbox`

### Add logs

(deck@steamdeck Downloads)$ "/usr/bin/flatpak" run com.heroicgameslauncher.hgl heroic://launch/1423049311 --no-gui --no-sandbox
Gtk-Message: 16:59:43.601: Failed to load module "canberra-gtk-module"
[3:0709/165943.663082:ERROR:bus.cc(397)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[3:0709/165943.663209:ERROR:bus.cc(397)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
(16:59:43) DEBUG:   [Legendary]:       Running Legendary command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary --version
[37:0709/165943.856176:ERROR:sandbox_linux.cc(377)] InitializeSandbox() called with multiple threads in process gpu-process.
hostname: invalid option -- 'f'
Try 'hostname --help' for more information.
(16:59:44) INFO:    [Legendary]:       Legendary location: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary
(16:59:44) INFO:    [Gog]:             GOGDL location: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl
(16:59:44) INFO:    [Backend]:

Heroic Version: 2.3.9 Brook
Legendary Version:  0.20.26 Dark Energy
OS: Freedesktop.org KERNEL: 5.13.0-valve21-1-neptune-02209-g2a5bdc1102a0 ARCH: x64
CPU: AMD Custom APU 0405 @2.14 GOVERNOR: schedutil
RAM: Total: 14.49 GiB Available: 11.25 GiB
GRAPHICS: GPU0: Device 163f VRAM: 512MB DRIVER:
PROTOCOL: x11

(16:59:44) INFO:    [Gog]:             Getting data about the user
APPIMAGE env is not defined, current application is not an AppImage
LaunchProcess: failed to execvp:
xdg-settings
(16:59:44) WARNING: [Backend]:         Failed to register protocol with OS.
(16:59:44) INFO:    [ProtocolHandler]: received 'heroic://launch/1423049311'
(node:3) UnhandledPromiseRejectionWarning: TypeError: Cannot destructure property 'is_installed' of 'game' as it is null.
    at handleProtocol (/app/bin/heroic/resources/app.asar/build/protocol.js:40:17)
(Use `heroic --trace-warnings ...` to show where the warning was created)
(node:3) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
[3:0709/165944.737678:ERROR:browser_main_loop.cc(269)] Gtk: gtk_widget_add_accelerator: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed
[3:0709/165944.737742:ERROR:browser_main_loop.cc(269)] Gtk: gtk_widget_add_accelerator: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed
[3:0709/165944.737906:ERROR:browser_main_loop.cc(269)] Gtk: gtk_widget_add_accelerator: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed
(16:59:44) INFO:    [Gog]:             Saved user data to config
(16:59:45) INFO:    [Frontend]:        Refreshing Library
(16:59:45) INFO:    [Legendary]:       Refreshing library...
(16:59:45) INFO:    [Legendary]:       Refreshing Epic Games...
(16:59:45) INFO:    [Gog]:             Getting GOG library
(16:59:46) DEBUG:   [Legendary]:       Running Legendary command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary list
(16:59:46) INFO:    [Gog]:             Number of library pages: 2
(16:59:46) INFO:    [Gog]:             Getting data for page 2
(node:158) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 setGameStatus listeners added to [EventEmitter]. Use emitter.setMaxListeners() to increase limit
(Use `exe --trace-warnings ...` to show where the warning was created)
(16:59:46) INFO:    [Gog]:             Saved games data
(16:59:47) INFO:    [Backend]:         Downloaded Winetricks
(16:59:48) INFO:    [Legendary]:       Updating game list
(16:59:48) INFO:    [Legendary]:       Game List Updated
(16:59:48) INFO:    [Legendary]:       Checking for game updates: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary list-installed --check-updates --tsv
(16:59:48) DEBUG:   [Legendary]:       Running Legendary command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary list-installed --check-updates --tsv
(16:59:49) INFO:    [Legendary]:       Found 0 game(s) to update
(16:59:49) INFO:    [Gog]:             Found 0 game(s) to update
(17:00:15) INFO:    [ProtocolHandler]: received 'heroic://launch/1423049311'
(17:00:18) INFO:    [Backend]:         Launching Cyberpunk 2077 (1423049311)
(17:00:18) WARNING: [Backend]:         You are using Proton, this can lead to some bugs. Please do not open issues with bugs related to games
(17:00:18) WARNING: No Steam runtime found
(17:00:18) INFO:    [Gog]:             Launching Cyberpunk 2077: STEAM_COMPAT_CLIENT_INSTALL_PATH=/home/deck/.var/app/com.heroicgameslauncher.hgl/.steam/steam STEAM_COMPAT_DATA_PATH=/home/deck/Games/Heroic/Prefixes/Cyberpunk 2077 STEAM_COMPAT_APP_ID=0 SteamAppId=0 SteamGameId=heroic-Cyberpunk 2077 PROTON_LOG_DIR=/home/deck/.var/app/com.heroicgameslauncher.hgl /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl launch "/run/media/mmcblk0p1/Heroic/Cyberpunk 2077" 1423049311 --no-wine --wrapper "'/home/deck/.local/share/Steam/steamapps/common/Proton 7.0/proton' run" --os windows
(17:00:18) DEBUG:   [Gog]:             Running GOGDL command: STEAM_COMPAT_CLIENT_INSTALL_PATH=/home/deck/.var/app/com.heroicgameslauncher.hgl/.steam/steam STEAM_COMPAT_DATA_PATH=/home/deck/Games/Heroic/Prefixes/Cyberpunk 2077 STEAM_COMPAT_APP_ID=0 SteamAppId=0 SteamGameId=heroic-Cyberpunk 2077 PROTON_LOG_DIR=/home/deck/.var/app/com.heroicgameslauncher.hgl /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl launch "/run/media/mmcblk0p1/Heroic/Cyberpunk 2077" 1423049311 --no-wine --wrapper "'/home/deck/.local/share/Steam/steamapps/common/Proton 7.0/proton' run" --os windows
^C

### Steps to reproduce

1. Install game with Heroic
2. Find its AppName in game settings
3. Close Heroic Launcher
4. Run the game manually with `/usr/bin/flatpak" run com.heroicgameslauncher.hgl heroic://launch/AppName --no-gui --no-sandbox`
5. Observe error

### Expected behavior

Heroic launches in the background, game launches.
When user exits game, Heroic closes.

### System Information

- OS: SteamOS 3.3
- Heroic version: 2.3.9 Flatpak

**Comment by arielj** [comment]
Probably a duplicate of https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/issues/1508 ?

**Comment by tomsik-radek** [comment]
> Probably a duplicate of #1508 ?

Oh yeah, seems like it. I did not notice that issue, I apologize.

**Comment by tomsik-radek** [comment]
Well kinda, #1508 issue says `Could not receive game data for gog - 1486529526!`, mine says `(node:3) UnhandledPromiseRejectionWarning: TypeError: Cannot destructure property 'is_installed' of 'game' as it is null.
at handleProtocol (/app/bin/heroic/resources/app.asar/build/protocol.js:40:17)`

**Comment by Nocccer** [comment]
Test this appimage. It should solve the problem.
https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/suites/7286924811/artifacts/293705094

**Comment by Nocccer** [comment]
> Well kinda, #1508 issue says `Could not receive game data for gog - 1486529526!`, mine says `(node:3) UnhandledPromiseRejectionWarning: TypeError: Cannot destructure property 'is_installed' of 'game' as it is null. at handleProtocol (/app/bin/heroic/resources/app.asar/build/protocol.js:40:17)`

The log there was with a change from my side already. I added the message and compiled heroic again. Thats why you don't see it on your side.

**Comment by tomsik-radek** [comment]
> Test this appimage. It should solve the problem. https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/suites/7286924811/artifacts/293705094

Yes that seems to work perfectly, I used the built in "add to Steam" thing in the Tools menu

`(17:46:36) INFO:    [Legendary]:       Running command : /tmp/.mount_HeroicZWPZiw/resources/app.asar.unpacked/build/bin/linux/legendary --version
(17:46:38) INFO:    [Legendary]:       Legendary location: /tmp/.mount_HeroicZWPZiw/resources/app.asar.unpacked/build/bin/linux/legendary
(17:46:38) INFO:    [Gog]:             GOGDL location: /tmp/.mount_HeroicZWPZiw/resources/app.asar.unpacked/build/bin/linux/gogdl
(17:46:38) INFO:    [Backend]:         

Heroic Version: 2.4.0-beta Caesar Clown
Legendary Version:  0.20.26 Dark Energy
OS: SteamOS KERNEL: 5.13.0-valve21-1-neptune-02209-g2a5bdc1102a0 ARCH: x64
CPU: AMD Custom APU 0405 @1.63 GOVERNOR: schedutil
RAM: Total: 14.49 GiB Available: 11.25 GiB
GRAPHICS: GPU0: VanGogh VRAM: 512MB DRIVER:  
PROTOCOL: x11

(17:46:38) INFO:    [Backend]:         User Not Found, removing it from Store
(17:46:38) INFO:    [Gog]:             Getting data about the user
(17:46:40) WARNING: [Backend]:         Failed to register protocol with OS.
(17:46:40) INFO:    [ProtocolHandler]: received 'heroic://launch/1942942943'
(17:46:40) INFO:    [Gog]:             Saved user data to config
(17:46:41) INFO:    [Frontend]:        Refreshing Library
(17:46:41) INFO:    [Legendary]:       Refreshing library...
(17:46:41) INFO:    [Gog]:             Getting GOG library
(17:46:41) INFO:    [Backend]:         Downloaded Winetricks
(17:46:41) INFO:    [Gog]:             Number of library pages: 2
(17:46:41) INFO:    [Gog]:             Getting data for page 2
(17:46:41) INFO:    [Gog]:             Saved games data
(17:46:41) INFO:    [Frontend]:        No cache found, getting data from legendary...
(17:46:41) INFO:    [Legendary]:       Refreshing library...
(17:46:42) INFO:    [Gog]:             Found 0 game(s) to update
(17:46:43) INFO:    [Backend]:         Launching Bridge Constructor Portal (1942942943)
(17:46:43) WARNING: [Backend]:         You are using Proton, this can lead to some bugs. Please do not open issues with bugs related to games
(17:46:43) WARNING: No Steam runtime found
(17:46:43) INFO:    [Gog]:             Launching Bridge Constructor Portal : STEAM_COMPAT_CLIENT_INSTALL_PATH=/home/deck/.steam/steam STEAM_COMPAT_DATA_PATH=/home/deck/Games/Heroic/Prefixes/Bridge Constructor Portal STEAM_COMPAT_APP_ID=0 SteamGameId=heroic-Bridge Constructor Portal PROTON_LOG_DIR=/home/deck /tmp/.mount_HeroicZWPZiw/resources/app.asar.unpacked/build/bin/linux/gogdl launch "/run/media/mmcblk0p1/HeroicAppImage/Bridge Constructor Portal" 1942942943 --no-wine --wrapper "'/home/deck/.local/share/Steam/steamapps/common/Proton 7.0/proton' run" --os windows
(17:47:27) INFO:    [Legendary]:       Running command : /tmp/.mount_HeroicZWPZiw/resources/app.asar.unpacked/build/bin/linux/legendary --version
(17:47:29) INFO:    [Backend]:         Log was written to /home/deck/.config/heroic/GamesConfig/1942942943-lastPlay.log
`

I'm not a developer, could you please to a TLDR on what was the issue? Thanks!
Also, I know "don't ask ETA" but this will be pushed into the flatpak, right?

**Comment by Nocccer** [comment]
The problem was that we requested game info before we actually load up all game infos into the memory. There was no fallback for gog games, but for legendray. We added a fallback to solve this.

Will hopefully in the next beta release. I'm not 100 % sure if it will work on flatpak, because couldn't not test it yet. But else i will fix it fast.

**Comment by tomsik-radek** [comment]
So it was trying to load the game before the launcher fully loaded? 

Okay, thanks! Btw just tried the Flathub Beta build, and despite being also called 2.4.0-beta it does not feature this fix and doesn't have the built in "add to steam" feature.

**Comment by Nocccer** [comment]
> So it was trying to load the game before the launcher fully loaded?
> 
> Okay, thanks! Btw just tried the Flathub Beta build, and despite being also called 2.4.0-beta it does not feature this fix and doesn't have the built in "add to steam" feature.

As i said above. Will be maybe in the next beta release, not in the current one.

**Comment by tomsik-radek** [comment]
Alright, thanks!

**Comment by alexoughton** [comment]
Hello,

Was this fix included in “2.4.0 Beta 2” and/or “2.3.10 Stable Hotfix”? I am still experiencing this issue with both releases on Steam Deck.

Thanks!

**Comment by Nocccer** [comment]
It is fixed and will be available with next release. We plan a release in the next days.

**Comment by alexoughton** [comment]
Great, thank you!
