### ISSUE TITLE
Heroic player issues with TrackMania

### ISSUE THREAD

**Issue by amwink** [Heroic-Games-Launcher/HeroicGamesLauncher#1561]
Hi - I'm using Heroic version 2.3.9 Brook on a Kubuntu 20.04 system, and I've encountered an issue (with Wine?) whilst starting the TrackMania game.

The technical details that I can see from starting the launcher from the shell are:

During startup there is a message 
`[104300:0710/140438.851499:ERROR:sandbox_linux.cc(377)] InitializeSandbox() called with multiple threads in process gpu-process.`
and repeated messages 
`[104300:0710/140439.089609:ERROR:gbm_wrapper.cc(275)] Failed to export buffer to dma_buf: No such file or directory (2)`
followed by 3 repetitions of this: 
`[104272:0710/140441.280432:ERROR:browser_main_loop.cc(269)] Gtk: gtk_widget_add_accelerator: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed`

But then the launcher does start.

Selecting and downloading TrackMania goes fine and for running it I can select Wine version:
`[Wine Default - wine 5.0 (Ubuntu 5.0-30ubuntu1)]`

When I select [Play Now] then the button is pressed for a few seconds (button showing [Playing(Stop)] )and then returns to its previous state.
Playing from the shell I see this error on the screen: 
`(12:22:43) ERROR:   [Backend]:         TypeError - Cannot read properties of undefined (reading 'bin')`

which also shows in the log file (attached).
[heroic-2022-07-10T10_21_05.226Z.log](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/files/9079040/heroic-2022-07-10T10_21_05.226Z.log)

Does [Backend] mean that it is a problem in Wine? The style of the message suggests that it is a JavaScript error.
Happy to supply more information if it helps.

**Comment by Nocccer** [comment]
Please update your wine to newest. Wine 5.0 is pretty outdated. Then also download newest wine -ge from heroic wine-manager. Select that instead default wine. Report back if it fixed something.

**Comment by Etaash-mathamsetty** [comment]
you might also want to update to ubuntu 22.04, since it's been out for a little while now

**Comment by flavioislima** [comment]
Closing this one since it's not a Heroic issue. OPen a discussion for help with games or go to our discord.
