### ISSUE TITLE
Offline install.

### ISSUE THREAD

**Issue by AireagoirSteam** [Heroic-Games-Launcher/HeroicGamesLauncher#1570]
### Feature description

The gog store both the webpage and the official galaxy app can download offline installers I was hoping this could be added.  As it would be useful for testing a game running through heroic or for reinstalling a game.

**Comment by flavioislima** [comment]
Not planned. You can download them from GOG and import the game to heroic.
We will keep using the galaxy download that is more practical then the offline installer.
