### ISSUE TITLE
Confirm quitting Heroic

### ISSUE THREAD

**Issue by arielj** [Heroic-Games-Launcher/HeroicGamesLauncher#1571]
### Problem description

The `Quit` button in the sidebar to close Heroic closes it immediatelly. If a user clicks it by mistake it closes Heroic without asking.

I know for some people this might be the desired behavior but I can imagine this being a problem for some people (like a gamepad with drift, some disability that could make it harder to click the correct element, a simple mistake, etc).

### Feature description

It would be nice to have a setting to allow users to decide if the Quit button should close Heroic when clicked or if it should ask the user for confirmation.

### Alternatives

Mmmm maybe put the Quit button somewhere else so it's harder to click it by mistake?

**Comment by Nocccer** [comment]
What about showing a dialog on first quit button press with:

Quit?
-------
[yes] [no]
- [ ]  remember

If remember is toggled we store it in the general config file and don't show the dialog again.
