### ISSUE TITLE
[Feature] Sort Played Recently by game's last played time

### ISSUE THREAD

**Issue by redromnon** [Heroic-Games-Launcher/HeroicGamesLauncher#1577]
### Problem description

Currently, the **Played Recently** game list is not sorted by the last played time. This feature should display the last played game first as the header title suggests.

### Feature description

Sort **Played Recently** by a game's last played time.

**Comment by arielj** [comment]
weird, this should be happening already (we prepend games to the list of recently played when a game is launched https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/blob/1bc88715486f0299c588264f3ec7d53c2ca817aa/electron/main.ts#L816)

one thing that I noticed once is that you have to restart heroic for this changes to replicate in the UI, is that the case here? can you confirm that?

**Comment by redromnon** [comment]
I can confirm it doesn't correct the order after restarting Heroic.

To elaborate, the last game I launched is Symphonia (not Fall Guys) but it is being displayed at the end in the Recently Played order.
![Screenshot from 2022-07-19 14-42-55](https://user-images.githubusercontent.com/74495920/179713931-26177631-4929-4c73-89c7-23904c9805b9.png)

**Comment by arielj** [comment]
Closing this since the mentioned PR fixes the issue.
