### ISSUE TITLE
[macos] CrossOver integration doesn't work with CrossOver 22 beta

### ISSUE THREAD

**Issue by kode54** [Heroic-Games-Launcher/HeroicGamesLauncher#1585]
### Describe the bug

Apparently, the CrossOver integration just commands CrossOver's binaries to interact with the Default bottle, and if a default bottle isn't set, it will fail to launch games.

### Add logs

Launch Command: undefined

System Info:
Heroic Version: 2.3.9 Brook
Legendary Version:  0.20.26 Dark Energy
OS: macOS KERNEL: 21.5.0 ARCH: x64
CPU: Apple M1 @2.4 
RAM: Total: 16 GiB Available: 12.32 GiB
GRAPHICS: GPU0: Apple M1 VRAM: nullMB DRIVER:  

Game Settings: {
	"checkUpdatesInterval": 10,
	"enableUpdates": false,
	"addDesktopShortcuts": false,
	"addStartMenuShortcuts": false,
	"autoInstallDxvk": false,
	"autoInstallVkd3d": false,
	"checkForUpdatesOnStartup": true,
	"customWinePaths": [],
	"defaultInstallPath": "/Users/chris/Games/Heroic",
	"defaultWinePrefix": "/Users/chris/Games/Heroic/Prefixes",
	"language": "en",
	"maxWorkers": 0,
	"minimizeOnLaunch": false,
	"nvidiaPrime": false,
	"otherOptions": "",
	"showUnrealMarket": false,
	"showFps": false,
	"useGameMode": false,
	"userInfo": {
		"epicId": "",
		"name": "chris"
	},
	"wineCrossoverBottle": "Heroic",
	"winePrefix": "/Users/chris/.wine",
	"wineVersion": {
		"bin": "",
		"name": "Default Wine - Not Found",
		"type": "wine"
	}
}

Error Log:
Launch aborted: undefined

### Steps to reproduce

1. Go to a game such as Axiom Verge 2
2. Click on Settings
3. Click on winecfg button
5. Nothing happens

### Expected behavior

Launches Winecfg for the configured bottle.

### System Information

- OS: macOS Monterey 12.4
- Heroic Version: 2.3.9

### Additional information

I needed to configure the Heroic bottle to be the default to at least fix this much. But it still attempts to sync the saves to `~/.wine` and not the actual Bottle's home folder, which is under `~/Library/Application Support/CrossOver/Bottles/<bottle name>`.

**Comment by flavioislima** [comment]
Can you check that again on the latest heroic version?
