### ISSUE TITLE
Fortnite Problem

### ISSUE THREAD

**Issue by Nebunaticul69** [Heroic-Games-Launcher/HeroicGamesLauncher#1591]
### Describe the bug

Can't run fortnite with proton + all wine versions.(bruh)

### Add logs

Launch Command: WINEPREFIX=/home/name/Games/Heroic/Prefixes/Fortnite DXVK_HUD=fps /tmp/.mount_HeroicEX2qNp/resources/app.asar.unpacked/build/bin/linux/legendary launch Fortnite --wine /home/name/.local/share/lutris/runners/wine/lutris-7.2-2-x86_64/bin/wine --wine-prefix /home/name/Games/Heroic/Prefixes/Fortnite

System Info:
Heroic Version: 2.3.9 Brook
Legendary Version:  0.20.26 Dark Energy
OS: Fedora Linux KERNEL: 5.18.10-200.fc36.x86_64 ARCH: x64
CPU: AMD Ryzen 5 3500U with Radeon Vega Mobile Gfx @2.1 GOVERNOR: schedutil
RAM: Total: 5.56 GiB Available: 2.46 GiB
GRAPHICS: GPU0: Picasso/Raven 2 [Radeon Vega Series / Radeon Vega Mobile Series] VRAM: 512MB DRIVER:  
PROTOCOL: wayland

Game Settings: {
	"autoInstallDxvk": false,
	"autoInstallVkd3d": false,
	"maxSharpness": 2,
	"nvidiaPrime": false,
	"otherOptions": "",
	"savesPath": "",
	"showFps": true,
	"targetExe": "",
	"useGameMode": false,
	"wineCrossoverBottle": "Heroic",
	"winePrefix": "/home/name/Games/Heroic/Prefixes/Fortnite",
	"wineVersion": {
		"bin": "/home/name/.local/share/lutris/runners/wine/lutris-7.2-2-x86_64/bin/wine",
		"name": "Wine - lutris-7.2-2-x86_64",
		"type": "wine",
		"wineserver": "/home/name/.local/share/lutris/runners/wine/lutris-7.2-2-x86_64/bin/wineserver",
		"wineboot": "/home/name/.local/share/lutris/runners/wine/lutris-7.2-2-x86_64/bin/wineboot"
	}
}

Error Log:
[cli] INFO: Logging in...
[Core] INFO: Trying to re-use existing login session...
[cli] INFO: Checking for updates...
[Core] INFO: Getting authentication token...
[cli] INFO: Launching Fortnite...
wineserver: using server-side synchronization.
002c:fixme:winediag:LdrInitializeThunk Lutris Wine 7.2 is a testing version containing experimental patches.
002c:fixme:winediag:LdrInitializeThunk Please don't report bugs about it on winehq.org and use https://github.com/lutris/wine/issues instead.

Game Log:
Legendary update available!
- New version: 0.20.27 - "Dark Energy (hotfix)"
- Release summary:
 [*] Adds instructions to recover from missing manifest file errors
 [*] Updates "eos-overlay" for more intuitive Linux/macOS usage
 [*] Adds instructions for use on Windows when exe is double-cliecked instead of run from a terminal.
See full changelog for additional details.
- Release URL: https://legendary.gl/release/0.20.27

- Download URL: https://legendary.gl/release/download/0.20.27/legendary
Application could not be started, or no application associated with the specified file.
ShellExecuteEx failed:
File not found.

### Steps to reproduce

2. Click on '...'
3. Scroll down to '...'

### Expected behavior

When clicking play the game should start usual.

### Screenshots

![Screenshot from 2022-07-17 22-10-48](https://user-images.githubusercontent.com/109481700/179421232-65ff70c7-e4da-481b-b156-4505723a207d.png)

### System Information

- OS Fedora Linux 36 (Workstation Edition) 64-bit
- Gnome version 42.2
- Heroic Version 2.3.9

### Additional information

Idk why I have this problem.

**Comment by arielj** [comment]
Fortnite does NOT work on linux, there's no way around it, they refuse to enable the linux support, check here https://areweanticheatyet.com/ https://twitter.com/TimSweeneyEpic/status/1490565925648715781?s=20&t=d7Ya8TH72wrGKXqZIi9gBg

Closing this since even if any problem is fixed, Fornite would be unplayable without the anticheat

**Comment by Etaash-mathamsetty** [comment]
> Fortnite does NOT work on linux, there's no way around it, they refuse to enable the linux support, check here https://areweanticheatyet.com/ https://twitter.com/TimSweeneyEpic/status/1490565925648715781?s=20&t=d7Ya8TH72wrGKXqZIi9gBg
> 
> Closing this since even if any problem is fixed, Fornite would be unplayable without the anticheat

this is correct, but
the game should launch with heroic 2.3.10, but you won't be able to load into it due to an error saying "wine is not supported"
