### ISSUE TITLE
Game appear as not installed on "Recently Played"

### ISSUE THREAD

**Issue by italoghost** [Heroic-Games-Launcher/HeroicGamesLauncher#1598]
### Describe the bug

Hi! I have just installed the latest beta through the AUR beta-bin package and I had already previously installed Fall Guys on my machine, so it appeared as one of my recently played games.

When I installed again, it was still greyed as if not installed, but when I scrolled down to all my games, it was showing as installed. 

It is just a small UI bug, I presume.

### Add logs

I do not know if I need the logs. 

### Steps to reproduce

1. Install a game that is not installed anymore, but is appearing on "Recently Played".
3. After downloading and installing it, it will be still greyed.
4. Scroll down to your games to see that it was installed.

### Expected behavior

It should be showing as installed on "Recently Played" as well.

### Screenshots

[Fall Guys - Recently Played.webm](https://user-images.githubusercontent.com/48540550/179640620-43d06600-bfb3-4097-8fb5-3a193ba490b5.webm)

### System Information

- OS [e. g. "Ubuntu"]: Arch Linux Gnome 42 Wayland 
- Heroic Version [e. g. 2.1.1]: 2.4.0 beta 2

**Comment by italoghost** [comment]
After restarting the application, it appeared as installed on "Recently Played"

**Comment by arielj** [comment]
@italoghost I understand this is fixed, can you check with the latest beta branch? you can download the app image from here https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/actions/runs/2825299593 (it's not released yet)

**Comment by italoghost** [comment]
@arielj I tested it and it is working!
