### ISSUE TITLE
Downloads page

### ISSUE THREAD

**Issue by 20PercentRendered** [Heroic-Games-Launcher/HeroicGamesLauncher#1609]
### Feature description

I think this launcher could benefit from a downloads page like the one in Steam.  The page could show peak download speed, current download speed and could show updates and allow you to queue game downloads and updates.

### Additional information

I could try contributing this myself. I'm no web designer so feedback is appreciated.

**Comment by Nocccer** [comment]
@20PercentRendered feel free to contribute. We can give feedback.
