### ISSUE TITLE
Heroic using Flatpak Steam dir even after uninstalling the Steam Flatpak

### ISSUE THREAD

**Issue by felipecrs** [Heroic-Games-Launcher/HeroicGamesLauncher#1612]
Or perhaps, this is a side-effect of the settings page entry for Steam default path not applying the changes made (have to manually set it in the config.json to make effect).

_Originally posted by @felipecrs in https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/issues/1331#issuecomment-1191733192_

**Comment by Nocccer** [comment]
There is no easy way to detect the paths. What we do is prefer steam flatpak over steam none-flatpak:
https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/blob/beta/electron/constants.ts#L114-L143

**Comment by felipecrs** [comment]
That makes sense. So, the only issue is:

https://user-images.githubusercontent.com/29582865/180283304-5d56ed8c-e05d-4cfc-be31-e2090c5ac0cb.mp4

**Comment by Nocccer** [comment]
> That makes sense. So, the only issue is:
> 
>  Heroic_BI3qEzAgMM.mp4

https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/pull/1611

**Comment by Nocccer** [comment]
I think we should consider using fltapak steam as last resort?
@flavioislima @CommandMC @arielj opinions?

**Comment by flavioislima** [comment]
The problem is thst on flatpak when you uninstall the app it keep the data files, so how would we know?
Maybe rely on flatpak only it heroic is flatpak as well? Still won't work for everyone.

**Comment by Nocccer** [comment]
The question is if we wanna change the order here? So we check for none flatpak first and else for flatpak.
https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/blob/5901dbab8896e1261cfcc9cab6f4b25c69838a02/electron/constants.ts#L135-L143

**Comment by flavioislima** [comment]
I don't think this will make much of a difference. More and more people are using flatpak now and changing the order will give false positives for people that changed the distro steam for the flatpak one.

I thibk we just need a wiki in the page with a troubleshooting for that until we find a way of checking if steam is installed.

Also, another edge case if a person has two steams installed.

**Comment by Nocccer** [comment]
Ok wait a minute. I'm dumb. I added a option to set the steam path. Need to check if this works for every function that relies on steam path, but i think i covered everything.

So in next release people can workaround by setting the steam path in general settings, if needed.

**Comment by felipecrs** [comment]
It should not be too difficult to run a 'flatpak' command to check if Steam is currently installed by flatpak or not.

**Comment by Nocccer** [comment]
Yes we could do that. But we only run it once if we setup the default settings. So if you already installed heroic and install flatpak steam aferwards, maybe it is not picked up.

**Comment by felipecrs** [comment]
So, in that sense, you could add a new checkbox that says:

- [ ] Custom Steam install path

If the user ticks it, the install path field can be customized and so on.

**Comment by Nocccer** [comment]
> So, in that sense, you could add a new checkbox that says:
> 
> * [ ]  Custom Steam install path
> 
> If the user ticks it, the install path field can be customized and so on.

Why a checkbox? Just guess the default path and if it is not correct the user can fix it by itself in settings.
