### ISSUE TITLE
"Install" in game dropdown does not disable

### ISSUE THREAD

**Issue by mrshmllow** [Heroic-Games-Launcher/HeroicGamesLauncher#1614]
### Describe the bug

In its default state, both the "Install" and the icon button are enabled (There is no current download) ![In its default state, both the "Install" and the icon button are enabled (There is no current download)](https://user-images.githubusercontent.com/40532058/180384206-f6b69503-9bf3-43b3-a446-f8cce109ba65.png)

However start installing a game, and the "Install" button will not disable like the others.
![However start installing a game, and the "Install" button will not disable like the others.](https://user-images.githubusercontent.com/40532058/180384278-fca59c71-8d8f-43ee-9ea0-da5d872ad201.png)

### Add logs

(17:01:45) INFO:    [Legendary]:       Running command: C:\Users\marsh\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\legendary --version
(17:01:51) INFO:    [Legendary]:       Legendary location: C:\Users\marsh\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\legendary
(17:01:51) INFO:    [Gog]:             GOGDL location: C:\Users\marsh\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\gogdl
(17:01:51) INFO:    [Backend]:         

Heroic Version: 2.4.0-beta.2 Caesar Clown
Legendary Version:  0.20.27 Dark Energy (hotfix)
OS: Microsoft Windows 10 Pro KERNEL: 10.0.19043 ARCH: x64
CPU: AMD Ryzen 3 3300X 4-Core Processor @3.8 
RAM: Total: 31.95 GiB Available: 21.24 GiB
GRAPHICS: GPU0: Radeon RX 570 Series VRAM: 4096MB DRIVER:  

(17:01:51) INFO:    [Backend]:         User Not Found, removing it from Store
(17:01:51) INFO:    [Backend]:         Registered protocol with OS.
(17:02:03) INFO:    [Backend]:         VCRuntime is installed
(17:02:09) INFO:    [Legendary]:       
(17:02:09) ERROR:   [Legendary]:       [cli] ERROR: Legendary is missing game metadata, please login (if not already) and use the "status" command to fetch necessary information to set-up syncing.

(17:02:33) INFO:    [Backend]:         Writing config for Heroic
(17:02:33) INFO:    [Backend]:         {
  "altLegendaryBin": "",
  "altGogdlBin": "",
  "addDesktopShortcuts": false,
  "addStartMenuShortcuts": false,
  "autoInstallDxvk": false,
  "autoInstallVkd3d": false,
  "preferSystemLibs": false,
  "customWinePaths": [],
  "defaultInstallPath": "D:\\heroic",
  "defaultSteamPath": "C:\\Program Files (x86)\\Steam",
  "defaultWinePrefix": "C:\\Users\\marsh\\Games\\Heroic\\Prefixes",
  "disableController": false,
  "egsLinkedPath": "",
  "maxRecentGames": 5,
  "maxWorkers": 0,
  "minimizeOnLaunch": false,
  "nvidiaPrime": false,
  "enviromentOptions": [],
  "wrapperOptions": [],
  "showFps": false,
  "showUnrealMarket": false,
  "useGameMode": false,
  "wineCrossoverBottle": "Heroic",
  "winePrefix": {},
  "wineVersion": {},
  "eacRuntime": false,
  "battlEyeRuntime": false
}
(17:03:15) INFO:    [Legendary]:       Logging in with Legendary.
(17:03:15) INFO:    [Legendary]:       Running command: C:\Users\marsh\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\legendary auth --sid <redacted>
(17:03:19) INFO:    [Frontend]:        Refreshing Library
(17:03:19) INFO:    [Legendary]:       Refreshing library...
(17:03:19) INFO:    [Legendary]:       Refreshing Epic Games...
(17:03:19) INFO:    [Frontend]:        Called Login
(17:03:20) INFO:    [Legendary]:       Running command: C:\Users\marsh\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\legendary list
(17:03:25) INFO:    [Legendary]:       Updating game list
(17:03:25) INFO:    [Legendary]:       Game List Updated
(17:03:25) INFO:    [Frontend]:        No cache found, getting data from legendary...
(17:03:25) INFO:    [Legendary]:       Refreshing library...
(17:03:25) INFO:    [Legendary]:       Updating game list
(17:03:25) INFO:    [Legendary]:       Game List Updated
(17:03:26) INFO:    [Legendary]:       Checking for game updates.
(17:03:26) INFO:    [Legendary]:       Running command: C:\Users\marsh\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\legendary list-installed --check-updates --tsv
(17:03:29) INFO:    [Legendary]:       Found 0 game(s) to update
(17:03:29) INFO:    [Frontend]:        Force Update
(17:03:38) ERROR:   [Legendary]:       Error Getting Info from Epic API
(17:03:38) INFO:    [Legendary]:       Getting more details with 'legendary info'
(17:03:39) INFO:    [Legendary]:       Running command: C:\Users\marsh\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\legendary --pretty-json info Fortnite --platform Windows --json
(17:03:39) INFO:    [Legendary]:       Getting more details with 'legendary info'
(17:03:39) INFO:    [Legendary]:       Getting more details with 'legendary info'
(17:03:40) INFO:    [Legendary]:       Running command: C:\Users\marsh\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\legendary --pretty-json info Fortnite --platform Windows --json
(17:03:40) INFO:    [Legendary]:       Running command: C:\Users\marsh\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\legendary --pretty-json info Fortnite --platform Windows --json
(17:03:58) INFO:    [Legendary]:       Importing Fortnite.
(17:03:58) INFO:    [Legendary]:       Running command: C:\Users\marsh\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\legendary import Fortnite D:\Fortnite
(17:03:58) DEBUG:   [Legendary]:       Using cached install info
(17:04:01) INFO:    [Backend]:         imported Fortnite
(17:04:01) INFO:    [Frontend]:        Refreshing Library
(17:04:01) INFO:    [Legendary]:       Refreshing library...
(17:04:01) INFO:    [Legendary]:       Updating game list
(17:04:01) INFO:    [Legendary]:       Game List Updated
(17:04:01) DEBUG:   [Legendary]:       Using cached install info
(17:04:01) DEBUG:   [Legendary]:       Using cached install info
(17:04:01) INFO:    [Legendary]:       Checking for game updates.
(17:04:01) INFO:    [Legendary]:       Running command: C:\Users\marsh\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\legendary list-installed --check-updates --tsv
(17:04:03) INFO:    [Legendary]:       Found 0 game(s) to update
(17:04:03) DEBUG:   [Legendary]:       Using cached install info
(17:04:03) DEBUG:   [Legendary]:       Using cached install info
(17:04:03) DEBUG:   [Legendary]:       Using cached install info
(17:04:07) DEBUG:   [Legendary]:       Using cached install info
(17:04:08) DEBUG:   [Legendary]:       Using cached install info
(17:04:08) INFO:    [Legendary]:       Installing Fortnite: C:\Users\marsh\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\legendary install Fortnite --platform Windows --base-path D:\heroic --skip-dlcs --install-tag= --install-tag=chunk0 --install-tag=chunk10 -y
(17:04:08) DEBUG:   [Legendary]:       Logging to file "C:\Users\marsh\AppData\Roaming\heroic\GamesConfig\Fortnite.log"
(17:04:13) INFO:    [Legendary]:       Progress for Fortnite: 37.45%/0.00MiB/00:00:00
(17:07:45) INFO:    [Legendary]:       Running command: C:\Users\marsh\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\legendary --version
(17:07:45) INFO:    [Gog]:             Running command: C:\Users\marsh\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\gogdl --version
(17:07:46) INFO:    [Legendary]:       Progress for Fortnite: 40.38%/1005.35MiB/00:53:50
(17:07:56) INFO:    [Legendary]:       Progress for Fortnite: 40.51%/1051.42MiB/00:54:46
(17:07:56) DEBUG:   [Legendary]:       Using cached install info
(17:07:57) INFO:    [Legendary]:       Progress for Fortnite: 40.53%/1056.22MiB/00:54:51
(17:07:57) DEBUG:   [Legendary]:       Using cached install info
(17:07:58) INFO:    [Legendary]:       Progress for Fortnite: 40.55%/1062.54MiB/00:55:05
(17:08:35) INFO:    [Legendary]:       Progress for Fortnite: 41%/1219.57MiB/00:56:17
(17:08:36) DEBUG:   [Legendary]:       Using cached install info
(17:08:36) INFO:    [Legendary]:       Progress for Fortnite: 41.02%/1224.35MiB/00:56:27
(17:09:19) INFO:    [Legendary]:       Progress for Fortnite: 41.59%/1420.74MiB/00:58:08
(17:09:19) INFO:    [Legendary]:       Getting Info from Epic API
(17:09:19) INFO:    [Legendary]:       Getting more details with 'legendary info'
(17:09:20) INFO:    [Legendary]:       Progress for Fortnite: 41.61%/1427.23MiB/00:58:08
(17:09:20) INFO:    [Legendary]:       Running command: C:\Users\marsh\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\legendary --pretty-json info 0a2d9f6403244d12969e11da6713137b --platform Windows --json
(17:09:21) INFO:    [Legendary]:       Progress for Fortnite: 41.62%/1430.92MiB/00:58:14
(17:10:42) INFO:    [Legendary]:       Progress for Fortnite: 42.7%/1800.72MiB/00:59:59
(17:10:43) INFO:    [Legendary]:       Getting Info from Epic API
(17:10:43) INFO:    [Legendary]:       Getting more details with 'legendary info'
(17:10:43) INFO:    [Legendary]:       Progress for Fortnite: 42.7%/1803.17MiB/01:00:04
(17:10:44) INFO:    [Legendary]:       Running command: C:\Users\marsh\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\legendary --pretty-json info 963137e4c29d4c79a81323b8fab03a40 --platform Windows --json
(17:10:44) INFO:    [Legendary]:       Progress for Fortnite: 42.73%/1810.68MiB/01:00:01
(17:11:35) INFO:    [Legendary]:       Progress for Fortnite: 43.36%/2029.89MiB/01:00:39
(17:11:35) DEBUG:   [Legendary]:       Using cached install info
(17:11:36) INFO:    [Legendary]:       Progress for Fortnite: 43.38%/2034.51MiB/01:00:39
(17:11:39) INFO:    [Legendary]:       Progress for Fortnite: 43.42%/2048.96MiB/01:00:43
(17:11:40) INFO:    [Backend]:         Trying to kill legendary
(17:11:40) INFO:    [Backend]:         Killed legendary
(17:11:40) INFO:    [Legendary]:       Progress for Fortnite: 43.44%/2055.32MiB/01:00:42
(17:11:40) INFO:    [Backend]:         finished installing
(17:11:40) INFO:    [Frontend]:        Refreshing Library
(17:11:40) INFO:    [Legendary]:       Refreshing library...
(17:11:40) INFO:    [Legendary]:       Updating game list
(17:11:40) INFO:    [Legendary]:       Game List Updated
(17:11:40) INFO:    [Backend]:         operation interrupted
(17:11:40) DEBUG:   [Legendary]:       Using cached install info
(17:11:40) DEBUG:   [Legendary]:       Using cached install info
(17:11:40) INFO:    [Legendary]:       Checking for game updates.
(17:11:40) INFO:    [Legendary]:       Running command: C:\Users\marsh\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\legendary list-installed --check-updates --tsv
(17:11:42) INFO:    [Legendary]:       Found 0 game(s) to update
(17:11:47) DEBUG:   [Legendary]:       Using cached install info
(17:12:21) DEBUG:   [Legendary]:       Using cached install info
(17:12:21) DEBUG:   [Legendary]:       Using cached install info
(17:12:22) DEBUG:   [Legendary]:       Using cached install info
(17:12:23) DEBUG:   [Legendary]:       Using cached install info
(17:12:23) DEBUG:   [Legendary]:       Using cached install info
(17:12:25) DEBUG:   [Legendary]:       Using cached install info
(17:12:26) DEBUG:   [Legendary]:       Using cached install info
(17:12:26) INFO:    [Legendary]:       Installing Fortnite: C:\Users\marsh\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\legendary install Fortnite --platform Windows --base-path D:\heroic --skip-dlcs --install-tag= --install-tag=chunk0 --install-tag=chunk10 -y
(17:12:26) DEBUG:   [Legendary]:       Logging to file "C:\Users\marsh\AppData\Roaming\heroic\GamesConfig\Fortnite.log"
(17:12:32) INFO:    [Legendary]:       Progress for Fortnite: 39.18%/0.00MiB/00:00:00
(17:12:33) INFO:    [Legendary]:       Progress for Fortnite: 39.18%/0.79MiB/00:00:00

### Steps to reproduce

1. Start installing a game
2. Right click on a different one

### Expected behavior

The "install" button is consistent with everything else

### System Information

- OS: Windows (ugh)
- Heroic Version: 2.4.0-beta.2 https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/releases/tag/v2.4.0-beta.2

### Additional information

Fortnite progress download logs have been omitted

**Comment by redromnon** [comment]
Closing issue as above PR fixes this.
