### ISSUE TITLE
Add Support for Amazon Games Launcher (with nile)

### ISSUE THREAD

**Issue by Etaash-mathamsetty** [Heroic-Games-Launcher/HeroicGamesLauncher#1616]
### Problem description

Amazon's game launcher doesn't currently work under linux, but there is a project called nile that creates a cli tool to install games that are in amazon's game launcher (it's called nile, https://github.com/imLinguin/nile)

### Feature description

We should implement nile into heroic games launcher to allow installing and playing these games that linux/mac users previously unable able to play.

### Alternatives

wait for amazon games launcher to work under wine?

### Additional information

nile still needs some work before it can be implemented into heroic games launcher

**Comment by imLinguin** [comment]
Duplicate #1289
