### ISSUE TITLE
Availability in Ubuntu Software store

### ISSUE THREAD

**Issue by Hans03430** [Heroic-Games-Launcher/HeroicGamesLauncher#1619]
### Problem description

Since Ubuntu is one of the most widely used distributions that has the most support for applications in the linux world, it would make sense that this game launcher would be available through the Ubuntu Software store. Sadly, it is not, and I suppose that that hurts the discoverability of this great project.

### Feature description

A solution would be to make the already existing deb package available in the Ubuntu Repos, so it's discoverable through the store, like Lutris did. However, i suppose that an easier and more straightforward way would be to publish Heroic game launchers as a snap package with the lzo compression.

### Alternatives

- Snap package for the snap store
- Availability of the deb file in Ubuntu repos

**Comment by Nocccer** [comment]
Not gonna happen. Getting into the deb store is alot of work.
Use alternative instead:
- https://wiki.ubuntuusers.de/Flatpak/ ( flatpak )
- https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher#debian-third-party-apt-repository ( third party deb repo )
