### ISSUE TITLE
"current_dxvk" and "current_vkd3d" files not created inside prefix

### ISSUE THREAD

**Issue by italoghost** [Heroic-Games-Launcher/HeroicGamesLauncher#1624]
### Describe the bug

It is happening with The Witcher 2, from GOG - the other games, from Epic, are working just fine: after installing DXVK, a file named "The" would be created on the parent directory:

https://cdn.discordapp.com/attachments/818939754245652490/1000781046419292210/unknown.png

https://cdn.discordapp.com/attachments/818939754245652490/1000781099607261285/unknown.png

Then, every time that I booted the game, Heroic would try to install/update DXVK and VKD3D, even though it was already installed.

Placing manually the "current_" files inside the prefix prevented this from happening.

On the discord server, CommandMC mentioned the that the problem is related to the fact that you are using the command `echo` to write these files.

### Add logs

There is no log

### Steps to reproduce

1. Install "The Witcher 2" from GOG
2. Mark the options to automatic install/update DXVK and VKD3D.
3. Try to boot the game more than once.
4. See that Heroic is trying to install the extensions again.
5. Go to the game prefix and see that the "current_" files are not there.

### Expected behavior

The "current_" files should be created inside the prefix. 

### System Information

- OS [e. g. "Ubuntu"]: Arch Linux GNOME 42 Wayland
- Heroic Version [e. g. 2.1.1]: 2.4.0-beta-2

**Comment by flavioislima** [comment]
Can you try the AppImage from this PR once the build is done? #1635

**Comment by italoghost** [comment]
@flavioislima I tested the AppImage and it successfully installed DXVK and VKD3D and created the "current_" files!

**Comment by flavioislima** [comment]
Nice, thanks for testing. 👍
