### ISSUE TITLE
make kde inhibit sleep and screen locking when a game is launched

### ISSUE THREAD

**Issue by Etaash-mathamsetty** [Heroic-Games-Launcher/HeroicGamesLauncher#1625]
### Problem description

I'm always annoyed that when I run a game with a controller plugged in, kde always locks the screen after some time. Steam doesn't have this problem because when steam runs a game, steam tells kde to not screen lock/sleep. 

### Feature description

make kde not sleep when playing a game. 

### Alternatives

manually clicking the block screen locking and sleep toggle (I always forget) or gamemode works too

**Comment by flavioislima** [comment]
@Etaash-mathamsetty can you test the PR to see if its working fine now: #1635
