### ISSUE TITLE
Flatpak from flathub has the UI garbled when running on fedora 36

### ISSUE THREAD

**Issue by Hugin0** [Heroic-Games-Launcher/HeroicGamesLauncher#1636]
### Describe the bug

Using the flatpak from flathub, on a fedora 36 under x11 and i3 window manager, the UI is garbled to varying degrees on each run.  

### Add logs

(11:51:24) DEBUG:   [Legendary]:       Running Legendary command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary --version
(11:51:25) INFO:    [Legendary]:       Legendary location: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary
(11:51:25) INFO:    [Gog]:             GOGDL location: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl
(11:51:25) INFO:    [Backend]:         

Heroic Version: 2.3.10 Brook
Legendary Version:  0.20.27 Dark Energy (hotfix)
OS: Freedesktop.org KERNEL: 5.18.11-200.fc36.x86_64 ARCH: x64
CPU: AMD Ryzen 7 2700 Eight-Core Processor @3.2 GOVERNOR: schedutil
RAM: Total: 15.44 GiB Available: 13.37 GiB
GRAPHICS: GPU0: Navi 14 [Radeon RX 5500/5500M / Pro 5500M] VRAM: 512MB DRIVER:  
PROTOCOL: x11

(11:51:25) INFO:    [Backend]:         User Not Found, removing it from Store
(11:51:25) WARNING: [Backend]:         Failed to register protocol with OS.
(11:51:28) INFO:    [Backend]:         Downloaded Winetricks

### Steps to reproduce

1. Install from flathub
2. run from hgl from my rofi launcher 
           - or - 
   with `flatpak run com.heroicgameslauncher.hgl` on the terminal

### Expected behavior

have a UI you can read.

### Screenshots

![2022-07-26-115312_923x998_scrot](https://user-images.githubusercontent.com/131902/181052692-54be150a-8fad-4602-9e32-9f89242bfbf9.png)

### System Information

- OS [e. g. "Ubuntu"]: Fedora 36 i3 spin
- Heroic Version [e. g. 2.1.1]: latest stable - 2.3.10; also tried against the beta on flathub-beta repo.
- Flatpak Version: 1.12.7

### Additional information

The problem can go away if I turn off the devices permission, but i feel like this isn't the appropriate solution.  I did install the Workstation group (to get the normal gnome desktop/UI) and the problem persists.

Tested with AppImage that works as expected.  Probably a permissions issue, but can't nail it down.  

Behavior started happening a while ago, but I've just been fighting through it since I only really use one game on it, I've been able to "see" through the problem to launch it.

**Comment by flavioislima** [comment]
That's unfortunate but we cannot support all distros and window managers. For now, try using the AppImage or install the RPM using the CORP repository.

**Comment by JakobDev** [comment]
If the AppImage works that is maybe a Bug with Flatpak and you should report it there. The Heroic Flatpak just repacks the AppImage.
