### ISSUE TITLE
[Linux] WINECFG & WINETRICKS buttons in Game Settings -> Wine do not work

### ISSUE THREAD

**Issue by Nocifer** [Heroic-Games-Launcher/HeroicGamesLauncher#1642]
### Describe the bug

The WINECFG & WINETRICKS buttons in Game Settings do nothing when clicked.

### Add logs

This is from the terminal output:

```
(11:57:32) ERROR:   [Backend]:         Unable to create Wineprefix:  TypeError: Cannot destructure property 'folder_name' of 'game.getGameInfo(...)' as it is null.
Error occurred in handler for 'callTool': TypeError: Cannot destructure property 'folder_name' of 'game.getGameInfo(...)' as it is null.
    at runWineCommand (/opt/Heroic/resources/app.asar/build/launcher.js:305:26)
```

### Steps to reproduce

1. Go to the Wine section in a game's settings.
2. Click on WINECFG or WINETRICKS buttons at the bottom of the page.
3. See error.

### Expected behavior

The WINECFG & WINETRICKS buttons should work.

### System Information

- OS: Arch Linux
- Heroic Version: 2.4.0-beta2

**Comment by flavioislima** [comment]
Also works fine with me:
![image](https://user-images.githubusercontent.com/26871415/181479758-608d0cd3-cdf9-4298-8f34-643cfceb1911.png)
![image](https://user-images.githubusercontent.com/26871415/181480099-3e1b7833-0804-4251-b936-3bae66c0ec9d.png)

How did you exactly are doing this? Which game? post the game settings here.

**Comment by Nocifer** [comment]
Tested both 2.3.10 and 2.4.0-beta.2 with a fresh install, including a freshly installed (not imported) GOG game and a newly created wine prefix. This works properly in 2.3.10 but is still broken in 2.4.0-beta.2 with the same error reported above, at least for me.

**Comment by Nocifer** [comment]
And here's the debug console output for this one:

```
node:electron/js2c/renderer_init:57 Uncaught (in promise) Error: Error invoking remote method 'callTool': TypeError: Cannot destructure property 'folder_name' of 'game.getGameInfo(...)' as it is null.
    at o.invoke (node:electron/js2c/renderer_init:57:526)
```

**Comment by Nocccer** [comment]
Seems like a pattern here. I think the game info is broken. Your system or Internet is blocking stuff, to read the gameinfo json file or fetching data from gog api.

**Comment by Nocifer** [comment]
How can it be something system- or internet-based when it worked fine five minutes earlier in 2.3.10 though? Especially the latter; I guess system-wise it could prove to be something on my end after all (e.g. a weird incompatibility with some system component or another, this _is_ Arch after all).

**Comment by Nocccer** [comment]
Can you send `~/.config/heroic/gog_store/library.json` and the game name where this happens?

**Comment by Nocifer** [comment]
Thought I'd save you the effort, so here's the info for the game in question (which is Vampire the Masquerade - Bloodlines):

```
		{
			"runner": "gog",
			"store_url": "https://gog.com/en/game/vampire_the_masquerade_bloodlines",
			"developer": "Troika Games",
			"app_name": "1207659240",
			"art_logo": null,
			"art_cover": "https://images-2.gog-statics.com/8bbb356c33d8a97cd6ec70793c81aa29d55680f38e93688d61d69fe3fa831719.jpg",
			"art_square": "https://images.gog.com/d281ccb40ec2ab6c498da7ddfbd7d84135567cefa71846095c71658fce1b6543.jpg?namespace=gamesdb",
			"cloud_save_enabled": false,
			"compatible_apps": [],
			"extra": {
				"about": {
					"description": "A first- and third-person Western RPG based on the Vampire: The Masquerade tabletop RPG with a heavy emphasis on character building and role-playing, in which the player embodies a fledgling vampire under the guidance of vampire prince Sebastian LaCroix. The player must serve the prince while getting to know the various factions of vampires in Los Angeles and forming their own political views.",
					"shortDescription": ""
				},
				"reqs": []
			},
			"folder_name": "VtMB",
			"install": {
				"version": null,
				"executable": "",
				"install_path": "",
				"install_size": "",
				"is_dlc": false,
				"platform": ""
			},
			"is_game": true,
			"is_installed": false,
			"is_ue_asset": false,
			"is_ue_plugin": false,
			"is_ue_project": false,
			"namespace": "vampire_the_masquerade_bloodlines",
			"title": "Vampire®: The Masquerade - Bloodlines™",
			"canRunOffline": true,
			"is_mac_native": false,
			"is_linux_native": false
		},
```

Also, here's the relevant info from `installed.json`:

```
		{
			"platform": "windows",
			"executable": "",
			"install_path": "/home/nocifer/Games/VtMB",
			"install_size": "3.94 GiB",
			"is_dlc": false,
			"version": "1.2 (UP 11.1/11.0/10.2) hotfix",
			"appName": "1207659240",
			"installedWithDLCs": false,
			"language": "en-US",
			"versionEtag": "\"225899965\"",
			"buildId": "55364927195422889"
		},
```

**Comment by Nocccer** [comment]
Thanks. I wonder why there is installed.json but the library.json says it is not installed?

**Comment by Nocifer** [comment]
Also I think I found one more bug. Trying to launch the game for the first time got me this error (this is from the terminal output):

```
(14:39:01) INFO:    [Backend]:         Launching Vampire®: The Masquerade - Bloodlines™ (1207659240)
(14:39:01) INFO:    [Legendary]:       Running command: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary --version
/bin/sh: line 1: hostname: command not found
(14:39:01) ERROR:   [Backend]:         Unable to create Wineprefix:  TypeError: Cannot read properties of undefined (reading 'toString')
(14:39:01) ERROR:   [Backend]:         TypeError: Cannot read properties of undefined (reading 'toString')
    at setupWineEnvVars (/opt/Heroic/resources/app.asar/build/launcher.js:188:70)
    at runWineCommand (/opt/Heroic/resources/app.asar/build/launcher.js:310:12)
```

It seems Heroic has an issue with the wine prefix parent folder being (or its own folder hierarchy containing) a hidden folder, because when I changed `/home/nocifer/Games/.wine/VtMB` to /home/nocifer/Games/VtMB_prefix` as the prefix folder, the game launched without a hitch. But the WINECFG & WINETRICKS buttons still don't work :/

**Comment by Nocccer** [comment]
Can you install a game with the default prefix and conform that all the bugs are gone?
Because this would be else a edge case. We need to make sure that the default behavior works atleast

**Comment by Nocifer** [comment]
I deleted `~/.config/heroic` again, left everything untouched at their default values and installed the same game fresh. On launch, the Wine prefix was successfully created in `/home/nocifer/Games/Heroic/Prefixes`. I then changed the game's prefix path to `/home/nocifer/Games/.wine`, launched the game, and the Wine prefix was again successfully created without any trace of the previous error.

In both cases though, WINECFG & WINETRICKS buttons remain non-functional, producing the error reported in the OP.

I'm kind of baffled to be honest :S But still, I think that getting intermittent errors about stuff that remain virtually unchanged between each attempt (folder structure, internet settings, system configuration) hints more at some buggy edge case within Heroic. But I'd be glad to be proven wrong (because I wanna stop bug hunting and go play my game dammit :P)

**Comment by flavioislima** [comment]
@Nocifer can you try on latest build, I think this bug was the same that we had in the past that you have reported with GOG games:
https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/actions/runs/2825299593

**Comment by Nocifer** [comment]
Yup, problem fixed :)

**Comment by flavioislima** [comment]
Great!
