### ISSUE TITLE
Clicking on a game in the library and then clicking on "Game Settings" in the sidebar does not work

### ISSUE THREAD

**Issue by Nocifer** [Heroic-Games-Launcher/HeroicGamesLauncher#1643]
### Describe the bug

As per title.

### Add logs

No errors are printed.

### Steps to reproduce

1. Click on a game in your library.
2. The sidebar changes into "game details" mode, i.e. "Settings" is replaced by "Game Settings".
3. Click on Game Settings.
4. The main window displays a loading animation ad infinitum.

### Expected behavior

Considering this switch to "game details" mode also happens when clicking on not installed games, I'd guess the functionality is generally not implemented. So one of two things should probably happen:

1. Properly implement this behavior (and also add a check for if a game is installed or not).
2. Disable the behavior altogether (i.e. clicking on a game in the library should not mess around with the sidebar status).

### System Information

- OS: Arch Linux
- Heroic Version: 2.4.0-beta.2

**Comment by flavioislima** [comment]
I cannot reproduce it. For me it goes to the Game settings.

**Comment by flavioislima** [comment]
Click on the Heroic tray icon and then > Debug. On the side will open the DevTools then click on Console and check if some error appears there.
Which game are you trying? Epic or GOG?

**Comment by Nocifer** [comment]
This error is printed on the debug console:

```
index.tsx:288 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'title')
    at index.tsx:288:19
    at f (regeneratorRuntime.js:86:17)
    at Generator._invoke (regeneratorRuntime.js:66:24)
    at Generator.next (regeneratorRuntime.js:117:21)
    at r (asyncToGenerator.js:3:20)
    at s (asyncToGenerator.js:25:9)
```

It's a GOG game, I just checked and Epic games work as expected.

**Comment by Nocifer** [comment]
Hmm, I'm kind of seeing a pattern here; in 2 out of the 3 bugs I just reported, the issue seems to be with the game's title property being apparently null; it's like the game's info is not properly stored or something. As I've also had a couple of other annoying issues since I installed the beta Heroic, I'll try to clear the app settings and cache, install a GOG game fresh and see where that gets me.

**Comment by flavioislima** [comment]
Yes, try that. But which game is that btw?

**Comment by Nocifer** [comment]
Tested with a fresh install, including a freshly installed (not imported) GOG game and a newly created wine prefix, and it's still broken. I'm glad to see you were able to reproduce it!

**Comment by flavioislima** [comment]
@Nocccer thats simple: the Sidebar doesn't have the information about the game, for instance, the runner. So when you click on the game settings button it sends runner as undefined to the settings. Since we are using `legendary` as default runner, it works fine for epic games, but breaks on GOG games.

So we need a way of sending the correct information to the sidebar.

**Comment by Nocccer** [comment]
I think we fixed it already?

**Comment by flavioislima** [comment]
Yes, it is fixed.
