### ISSUE TITLE
Heroic checks if EOS Overlay is installed for uninstalled games

### ISSUE THREAD

**Issue by arielj** [Heroic-Games-Launcher/HeroicGamesLauncher#1654]
### Describe the bug

When opening a game details page, this message appears in the console:

```
(17:19:02) INFO:    [Legendary]:       Checking if EOS Overlay is enabled: /home/..../linux/legendary eos-overlay info --prefix /thedefaultprefixfolder
```

I understand this is a bug because it's checking that for a game that is not installed so it's checking the default prefixes path but when a game is installed then it checks in the specific prefix for the game.

### Add logs

```
(17:21:32) INFO:    [Legendary]:       Checking if EOS Overlay is enabled: /home/ariel/dev/oss/HeroicGamesLauncher/public/bin/linux/legendary eos-overlay info --prefix /home/ariel/.wine
```

### Steps to reproduce

1. Open the details screen of not-installed game
2. Check logs

### Expected behavior

It should do that check only if the game is installed.

### System Information

Irrelevant

### Additional information

I don't really understand the feature of the overlay, haven't used it before or anything so feel free to close this if this behavior is not a bug.

It doesn't really affect in any way, I understand it's just extra work for Heroic.

**Comment by Nocccer** [comment]
This behavior also effects add to steam. Should be easy fix. Just a check if a game is installed in the frontend.
