### ISSUE TITLE
MAD Linux repo is gone, need new Ubuntu repo

### ISSUE THREAD

**Issue by nelsongt** [Heroic-Games-Launcher/HeroicGamesLauncher#1660]
### Problem description

The MAD Linux repo at sourceforge.net cannot be found by any search, and the https://gitlab.com/myawesomedistro/madrepo site returns a 404 error. The myawesomedistro user is gone from gitlab, too. It seems everything was deleted, unless I'm missing something obvious.

The installation guide is out of date now.

### Feature description

A new Ubuntu repository

**Comment by flavioislima** [comment]
Hmm, weird. Let me try to ping the maintainer @rauldipeas

**Comment by rauldipeas** [comment]
> unless I'm missing something obvious

Take a look here.

https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/pull/1604

**Comment by rauldipeas** [comment]
@flavioislima it's outdated, maybe some rollback happened.

**Actual**
![Screenshot_20220802_171009](https://user-images.githubusercontent.com/12108031/182464440-3d3801dc-3be7-41e4-bd58-f5f593400a85.png)

**Fork**
![Screenshot_20220802_171031](https://user-images.githubusercontent.com/12108031/182464444-f796b7c8-d3f9-4d38-b447-14f0ddbe8a79.png)

**Comment by flavioislima** [comment]
Ok, fixed it.

Thanks 👍🏽
