### ISSUE TITLE
[Linux] Can't find Cloud Sync option for imported Cyberpunk 2077 on 2.4.0-beta2

### ISSUE THREAD

**Issue by pierreavizou** [Heroic-Games-Launcher/HeroicGamesLauncher#1665]
### Describe the bug

According to the changelog, 2.4.0-beta2 supports cloud sync for GOG games. However, after importing an existing install of Cyberpunk 2077 into Heroic, I can't seem to find where to enable cloud sync for this game. 
Changelog screenshots seem to indicate that it should appear in the game settings side bar, but I've got nothing. 
l
It might be Heroic failing to detect cloud support, or me being stupid, let me know in either case :smil

### Add logs

(11:48:25) INFO:    [Legendary]:       Running command: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary --version
(11:48:25) INFO:    [Legendary]:       Legendary location: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary
(11:48:25) INFO:    [Gog]:             GOGDL location: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl
(11:48:25) INFO:    [Backend]:         

Heroic Version: 2.4.0-beta.2 Caesar Clown
Legendary Version:  0.20.27 Dark Energy (hotfix)
OS: ManjaroLinux KERNEL: 5.19.0-2-MANJARO ARCH: x64
CPU: AMD Ryzen 7 3700X 8-Core Processor @3.6 GOVERNOR: schedutil
RAM: Total: 31.29 GiB Available: 25.5 GiB
GRAPHICS: GPU0: Navi 10 [Radeon RX 5600 OEM/5600 XT / 5700/5700 XT] VRAM: 512MB DRIVER:  
PROTOCOL: x11

(11:48:25) INFO:    [Gog]:             Getting data about the user
(11:48:25) INFO:    [Gog]:             Refreshing access_token
(11:48:25) WARNING: [Backend]:         Protocol already registered.
(11:48:25) INFO:    [Gog]:             Token refreshed successfully
(11:48:26) INFO:    [Backend]:         AreWeAntiCheatYet data downloaded
(11:48:26) INFO:    [Gog]:             Saved user data to config
(11:48:26) INFO:    [Frontend]:        Refreshing Library
(11:48:26) INFO:    [Legendary]:       Refreshing library...
(11:48:26) INFO:    [Legendary]:       Refreshing Epic Games...
(11:48:26) INFO:    [Gog]:             Getting GOG library
(11:48:26) INFO:    [Gog]:             Number of library pages: 1
(11:48:26) INFO:    [Legendary]:       Running command: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary list
(11:48:26) INFO:    [Gog]:             Saved games data
(11:48:27) INFO:    [Legendary]:       Updating game list
(11:48:27) INFO:    [Legendary]:       Game List Updated
(11:48:27) INFO:    [Legendary]:       Checking for game updates.
(11:48:27) INFO:    [Legendary]:       Running command: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary list-installed --check-updates --tsv
(11:48:28) INFO:    [Backend]:         Downloaded Winetricks
(11:48:28) INFO:    [Legendary]:       Found 0 game(s) to update
(11:48:28) INFO:    [Gog]:             Found 0 game(s) to update
(11:48:31) INFO:    [Gog]:             Getting game metadata.
(11:48:31) INFO:    [Gog]:             Running command: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl info 1423049311 --token <redacted> --lang=en-US --os windows
(11:48:31) INFO:    [Legendary]:       Checking if EOS Overlay is enabled: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary eos-overlay info --prefix "/home/pierre/Games/Heroic/Prefixes/Cyberpunk 2077"
(11:48:39) INFO:    [Frontend]:        Refreshing wine downloader releases
(11:48:39) INFO:    [WineDownloader]:  Updating wine versions info
(11:48:39) INFO:    [WineDownloader]:  Fetching upstream information...
(11:48:41) INFO:    [WineDownloader]:  wine versions updated
(11:50:04) INFO:    [Backend]:         Writing config for 1423049311
(11:50:04) INFO:    [Backend]:         {
  "autoInstallDxvk": true,
  "autoInstallVkd3d": true,
  "preferSystemLibs": false,
  "enableEsync": false,
  "enableFsync": false,
  "maxSharpness": 2,
  "language": "",
  "nvidiaPrime": false,
  "enviromentOptions": [],
  "wrapperOptions": [],
  "savesPath": "",
  "showFps": false,
  "targetExe": "",
  "useGameMode": false,
  "winePrefix": "/home/pierre/Games/Heroic/Prefixes/Cyberpunk 2077",
  "wineVersion": {
    "bin": "/home/pierre/.local/share/lutris/runners/wine/lutris-7.1-x86_64/bin/wine",
    "name": "Wine - lutris-7.1-x86_64",
    "type": "wine",
    "lib": "/home/pierre/.local/share/lutris/runners/wine/lutris-7.1-x86_64/lib64",
    "lib32": "/home/pierre/.local/share/lutris/runners/wine/lutris-7.1-x86_64/lib",
    "wineserver": "/home/pierre/.local/share/lutris/runners/wine/lutris-7.1-x86_64/bin/wineserver",
    "wineboot": "/home/pierre/.local/share/lutris/runners/wine/lutris-7.1-x86_64/bin/wineboot"
  },
  "eacRuntime": false,
  "battlEyeRuntime": false
}
(11:50:07) INFO:    [Backend]:         Launching Cyberpunk 2077 (1423049311)
(11:50:07) INFO:    [Legendary]:       Running command: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary --version
(11:50:08) DEBUG:   [Legendary]:       Running Wine command: "/home/pierre/.local/share/lutris/runners/wine/lutris-7.1-x86_64/bin/wine" wineboot --init
(11:50:16) DEBUG:   [Legendary]:       Ran Wine command: "/home/pierre/.local/share/lutris/runners/wine/lutris-7.1-x86_64/bin/wine" wineboot --init
(11:50:16) INFO:    [Backend]:         Created/Updated Wineprefix at /home/pierre/Games/Heroic/Prefixes/Cyberpunk 2077
(11:50:16) INFO:    [Gog]:             Setup: No instructions
(11:50:16) INFO:    [Gog]:             Launching Cyberpunk 2077: LD_PRELOAD= WINEPREFIX="/home/pierre/Games/Heroic/Prefixes/Cyberpunk 2077" LD_LIBRARY_PATH=/home/pierre/.local/share/lutris/runners/wine/lutris-7.1-x86_64/lib:/home/pierre/.local/share/lutris/runners/wine/lutris-7.1-x86_64/lib64: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl launch "/media/gamedisk/GOG Galaxy/Games/Cyberpunk 2077" 1423049311 --wine /home/pierre/.local/share/lutris/runners/wine/lutris-7.1-x86_64/bin/wine --wine-prefix "/home/pierre/Games/Heroic/Prefixes/Cyberpunk 2077" --os windows
(11:50:38) INFO:    [Gog]:             Getting game metadata.
(11:50:38) INFO:    [Gog]:             Running command: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl info 1423049311 --token <redacted> --lang=en-US --os windows
(11:50:38) INFO:    [Legendary]:       Checking if EOS Overlay is enabled: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary eos-overlay info --prefix "/home/pierre/Games/Heroic/Prefixes/Cyberpunk 2077"
(11:50:39) INFO:    [Frontend]:        Refreshing Library
(11:50:39) INFO:    [Gog]:             Getting GOG library
(11:50:39) INFO:    [Gog]:             Getting game metadata.
(11:50:39) INFO:    [Gog]:             Running command: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl info 1423049311 --token <redacted> --lang=en-US --os windows
(11:50:39) INFO:    [Gog]:             Getting game metadata.
(11:50:39) INFO:    [Gog]:             Running command: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl info 1423049311 --token <redacted> --lang=en-US --os windows
(11:50:39) INFO:    [Gog]:             Number of library pages: 1
(11:50:39) INFO:    [Gog]:             Saved games data
(11:50:40) INFO:    [Gog]:             Found 0 game(s) to update
(11:50:40) INFO:    [Gog]:             Getting game metadata.
(11:50:40) INFO:    [Gog]:             Running command: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl info 1423049311 --token <redacted> --lang=en-US --os windows
(11:50:55) INFO:    [Backend]:         Launching Cyberpunk 2077 (1423049311)
(11:50:55) INFO:    [Legendary]:       Running command: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary --version
(11:50:55) INFO:    [Gog]:             Getting game metadata.
(11:50:55) INFO:    [Gog]:             Running command: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl info 1423049311 --token <redacted> --lang=en-US --os windows
(11:50:56) DEBUG:   [Legendary]:       Running Wine command: "/home/pierre/.local/share/lutris/runners/wine/lutris-7.1-x86_64/bin/wine" wineboot --init
(11:51:00) DEBUG:   [Legendary]:       Ran Wine command: "/home/pierre/.local/share/lutris/runners/wine/lutris-7.1-x86_64/bin/wine" wineboot --init
(11:51:00) INFO:    [Gog]:             Launching Cyberpunk 2077: LD_PRELOAD= WINEPREFIX="/home/pierre/Games/Heroic/Prefixes/Cyberpunk 2077" LD_LIBRARY_PATH=/home/pierre/.local/share/lutris/runners/wine/lutris-7.1-x86_64/lib:/home/pierre/.local/share/lutris/runners/wine/lutris-7.1-x86_64/lib64: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl launch "/media/gamedisk/GOG Galaxy/Games/Cyberpunk 2077" 1423049311 --wine /home/pierre/.local/share/lutris/runners/wine/lutris-7.1-x86_64/bin/wine --wine-prefix "/home/pierre/Games/Heroic/Prefixes/Cyberpunk 2077" --os windows
(11:51:41) INFO:    [Frontend]:        Refreshing Library
(11:51:41) INFO:    [Gog]:             Getting GOG library
(11:51:41) INFO:    [Gog]:             Getting game metadata.
(11:51:41) INFO:    [Gog]:             Running command: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl info 1423049311 --token <redacted> --lang=en-US --os windows
(11:51:41) INFO:    [Gog]:             Getting game metadata.
(11:51:41) INFO:    [Gog]:             Running command: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl info 1423049311 --token <redacted> --lang=en-US --os windows
(11:51:41) INFO:    [Gog]:             Number of library pages: 1
(11:51:41) INFO:    [Gog]:             Saved games data
(11:51:42) INFO:    [Gog]:             Found 0 game(s) to update
(11:51:42) INFO:    [Gog]:             Getting game metadata.
(11:51:42) INFO:    [Gog]:             Running command: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl info 1423049311 --token <redacted> --lang=en-US --os windows
(11:51:47) INFO:    [Backend]:         Exitting to tray instead of quitting
(11:51:49) INFO:    [ProtocolHandler]: received 'heroic://launch/1423049311'
(11:52:13) INFO:    [ProtocolHandler]: received 'heroic://launch/1423049311'
(11:52:47) INFO:    [Legendary]:       Getting Info from Epic API
(11:52:47) INFO:    [Legendary]:       Getting more details with 'legendary info'
(11:52:47) INFO:    [Legendary]:       Checking if EOS Overlay is enabled: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary eos-overlay info --prefix /home/pierre/.wine
(11:52:47) INFO:    [Legendary]:       Running command: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary --pretty-json info b22ce34b4ce0408c97a888554447479b --platform Windows --json
(11:53:36) INFO:    [Backend]:         Exitting to tray instead of quitting

### Steps to reproduce

1. Login to your GOG account
2. Click on Cyberpunk 2077 from you library
3. Click on 'install' then 'import game'
4. Select an existing install and confirm
5. Look for the option to enable cloud sync. 

### Expected behavior

The option to enable cloud sync should appear in game settings

### Screenshots

![image](https://user-images.githubusercontent.com/7101583/183054929-c6dc6910-2e26-4039-94d3-aa2245183bf3.png)

### System Information

- OS [e. g. "Ubuntu"]: Manjaro Gnome
- Heroic Version [e. g. 2.1.1]: 2.4.0-beta2

**Comment by imLinguin** [comment]
Clear heroic cache and refresh the library.

**Comment by pierreavizou** [comment]
Oh well that just worked! Thanks for the blazing fast response :+1:

**Comment by xlBennylx** [comment]
Clearing the cache is not working for me. And if I click on the game then it shows synchronizing unsupported. But I know cyberpunk has my saves in the cloud. I'm on version 2.4.1. on steamdeck

**Comment by imLinguin** [comment]
Clear Cache and then refresh the library

**Comment by xlBennylx** [comment]
Ok after the 3. try it finally worked thanks anyway

**Comment by Istarish** [comment]
In my case creating a new save and syncing it on my windows rig fixed this issue on my Steam Deck.
