### ISSUE TITLE
Steam path doesn't save at all

### ISSUE THREAD

**Issue by Rafii2198** [Heroic-Games-Launcher/HeroicGamesLauncher#1671]
### Describe the bug

Whenever I try to change path of steam installation, it just doesn't save at all and keeps the default value.

### Add logs

(01:20:22) INFO:    [Legendary]:       Running command: C:\Users\Rafii2198\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\legendary --version
(01:20:27) INFO:    [Legendary]:       Legendary location: C:\Users\Rafii2198\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\legendary
(01:20:27) INFO:    [Gog]:             GOGDL location: C:\Users\Rafii2198\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\gogdl
(01:20:27) INFO:    [Backend]:         

Heroic Version: 2.4.0-beta.2 Caesar Clown
Legendary Version:  0.20.27 Dark Energy (hotfix)
OS: Microsoft Windows 10 Home KERNEL: 10.0.19044 ARCH: x64
CPU: AMD Ryzen 5 1600X Six-Core Processor @3.6 
RAM: Total: 31.93 GiB Available: 18.97 GiB
GRAPHICS: GPU0: Radeon RX 580 Series VRAM: 8192MB DRIVER:  

(01:20:27) INFO:    [Gog]:             Getting data about the user
(01:20:27) WARNING: [Backend]:         Protocol already registered.
(01:20:27) INFO:    [Gog]:             Saved user data to config
(01:20:29) INFO:    [Frontend]:        Refreshing Library
(01:20:29) INFO:    [Legendary]:       Refreshing library...
(01:20:29) INFO:    [Legendary]:       Refreshing Epic Games...
(01:20:29) INFO:    [Gog]:             Getting GOG library
(01:20:29) INFO:    [Gog]:             Number of library pages: 1
(01:20:29) INFO:    [Gog]:             Saved games data
(01:20:29) INFO:    [Legendary]:       Running command: C:\Users\Rafii2198\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\legendary list --include-ue
(01:20:32) INFO:    [Legendary]:       Updating game list
(01:20:32) INFO:    [Legendary]:       Game List Updated
(01:20:32) INFO:    [Legendary]:       Checking for game updates.
(01:20:32) INFO:    [Legendary]:       Running command: C:\Users\Rafii2198\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\legendary list-installed --check-updates --tsv
(01:20:34) INFO:    [Legendary]:       Found 0 game(s) to update
(01:20:34) INFO:    [Gog]:             Found 0 game(s) to update
(01:20:34) INFO:    [Frontend]:        Force Update
(01:20:49) INFO:    [Backend]:         VCRuntime is installed
(01:21:29) INFO:    [Backend]:         Launching Unrailed (76233c0af0a441c7bd541e7d7ab3cde1)
(01:21:29) INFO:    [Legendary]:       Running command: C:\Users\Rafii2198\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\legendary --version
(01:21:35) INFO:    [Legendary]:       Launching Unrailed: C:\Users\Rafii2198\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\legendary launch 76233c0af0a441c7bd541e7d7ab3cde1 --language en
(01:21:37) INFO:    [Frontend]:        Refreshing Library
(01:21:37) INFO:    [Legendary]:       Refreshing library...
(01:21:37) INFO:    [Legendary]:       Updating game list
(01:21:37) INFO:    [Legendary]:       Game List Updated
(01:21:38) INFO:    [Legendary]:       Checking for game updates.
(01:21:38) INFO:    [Legendary]:       Running command: C:\Users\Rafii2198\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\legendary list-installed --check-updates --tsv
(01:21:39) INFO:    [Legendary]:       Found 0 game(s) to update
(01:21:40) DEBUG:   [Legendary]:       Using cached install info
(01:22:15) DEBUG:   [Backend]:         Unable to load Steam Libraries, libraryfolders.vdf not found
(01:22:43) INFO:    [Legendary]:       Running command: C:\Users\Rafii2198\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\legendary --version
(01:22:43) INFO:    [Gog]:             Running command: C:\Users\Rafii2198\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\gogdl --version
(01:25:52) INFO:    [Backend]:         Writing config for Heroic
(01:25:52) INFO:    [Backend]:         {
  "altLegendaryBin": "",
  "altGogdlBin": "",
  "addDesktopShortcuts": true,
  "addStartMenuShortcuts": false,
  "autoInstallDxvk": false,
  "autoInstallVkd3d": false,
  "preferSystemLibs": false,
  "customWinePaths": [],
  "darkTrayIcon": true,
  "defaultInstallPath": "E:\\EpicGry",
  "defaultSteamPath": "E:\\Steam",
  "defaultWinePrefix": "C:\\Users\\Rafii2198\\Games\\Heroic\\Prefixes",
  "disableController": true,
  "egsLinkedPath": "windows",
  "exitToTray": true,
  "maxRecentGames": 5,
  "maxWorkers": 11,
  "minimizeOnLaunch": false,
  "nvidiaPrime": false,
  "enviromentOptions": [],
  "wrapperOptions": [],
  "showFps": false,
  "showUnrealMarket": true,
  "startInTray": true,
  "useGameMode": false,
  "wineCrossoverBottle": "Heroic",
  "winePrefix": "",
  "wineVersion": {},
  "eacRuntime": false,
  "battlEyeRuntime": false
}

### Steps to reproduce

Just simply change Steam path installation to anything, you can type by hand or use the explorer window to chose, there is no difference

### Expected behavior

The Steam path would be saved and used instead of default one.

### System Information

- OS: Windows
- Heroic Version: 2.4.0-beta.2

### Additional information

I fixed it by manually changing the config file with the thing that was in the log. There was no Steam entry in my file from the beginning, probably because I upgraded from latest stable version and it is working now after that manual change.

**Comment by Nocccer** [comment]
Fixed in beta branch. Will be in next release.
