### ISSUE TITLE
[GOG] Cant install TES Redguard "Cannot get game info"

### ISSUE THREAD

**Issue by AvnarJakob** [Heroic-Games-Launcher/HeroicGamesLauncher#1672]
### Describe the bug

When I try to install The Elder Scrolls: Adventures Redguard from GOG on Fedora 36 it just opens a small Window with the only option beeing Ok. 
![tryinstall](https://user-images.githubusercontent.com/75129695/183290545-ca647ebb-d28c-4b2d-96b5-ade0a946baa7.png)

When I try to click the game if first shows the normal Game Description but then after ~1s it says "Cannot get game info" Refreshing Library, Clear Heroic chache and Restet Heroic dont do anything.
![GamePage](https://user-images.githubusercontent.com/75129695/183290572-c93c2950-cbc6-4d73-8ff9-39c8c3b1b96c.png)

All that happens with the Flatpack and the RPM.
This only happens with TES Redguard all the other games I own work without problems.

### Add logs

[j@fedora ~]$ flatpak run com.heroicgameslauncher.hgl
[3:0807/143049.807887:ERROR:bus.cc(398)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[3:0807/143049.808001:ERROR:bus.cc(398)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
(14:30:49) DEBUG:   [Legendary]:       Running Legendary command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary --version
hostname: invalid option -- 'f'
Try 'hostname --help' for more information.
(14:30:50) INFO:    [Legendary]:       Legendary location: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary
(14:30:50) INFO:    [Gog]:             GOGDL location: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl
(14:30:50) INFO:    [Backend]:         

Heroic Version: 2.3.10 Brook
Legendary Version:  0.20.27 Dark Energy (hotfix)
OS: Freedesktop.org KERNEL: 5.18.16-200.fc36.x86_64 ARCH: x64
CPU: AMD Ryzen 5 1600 Six-Core Processor @3.2 GOVERNOR: schedutil
RAM: Total: 15.54 GiB Available: 10.24 GiB
GRAPHICS: GPU0: TU116 [GeForce GTX 1660 SUPER]  VRAM: 32MB DRIVER:  
PROTOCOL: x11

(14:30:50) INFO:    [Backend]:         User Not Found, removing it from Store
(14:30:50) INFO:    [Gog]:             Getting data about the user
APPIMAGE env is not defined, current application is not an AppImage
LaunchProcess: failed to execvp:
xdg-settings
(14:30:50) WARNING: [Backend]:         Failed to register protocol with OS.
[3:0807/143050.635686:ERROR:browser_main_loop.cc(271)] Gtk: gtk_widget_add_accelerator: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed
[3:0807/143050.635777:ERROR:browser_main_loop.cc(271)] Gtk: gtk_widget_add_accelerator: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed
[3:0807/143050.635831:ERROR:browser_main_loop.cc(271)] Gtk: gtk_widget_add_accelerator: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed
(14:30:50) INFO:    [Gog]:             Saved user data to config
(14:30:51) INFO:    [Frontend]:        Refreshing Library
(14:30:51) INFO:    [Legendary]:       Refreshing library...
(14:30:51) INFO:    [Gog]:             Getting GOG library
(14:30:51) INFO:    [Gog]:             Number of library pages: 1
(14:30:51) INFO:    [Gog]:             Saved games data
(14:30:51) INFO:    [Frontend]:        No cache found, getting data from legendary...
(14:30:51) INFO:    [Legendary]:       Refreshing library...
(14:30:51) INFO:    [Gog]:             Found 0 game(s) to update
(14:30:53) INFO:    [Backend]:         Downloaded Winetricks
(14:30:58) INFO:    [Gog]:             Getting game metadata: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl info 1435829617 --token <redacted> --lang=en-US --os windows
(14:30:58) DEBUG:   [Gog]:             Running GOGDL command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl info 1435829617 --token <redacted> --lang=en-US --os windows
(14:30:59) ERROR:   [Backend]:         SyntaxError: Unexpected end of JSON input
(14:30:59) ERROR:   [Frontend]:        Cannot get game info

### Steps to reproduce

Click on TES Redguard

### Expected behavior

Install the Game

### System Information

- OS [Fedora]: 
- Heroic Version [v2.3.10]:

**Comment by Nocccer** [comment]
It seems gog can't find you. Try login and out again.
`(14:30:50) INFO: [Backend]: User Not Found, removing it from Store`

**Comment by imLinguin** [comment]
That log is related to Epic.
Try logging out and in from GOG, it looks like token isn't passed at all.

**Comment by AvnarJakob** [comment]
I tryed logging out of both epig and GOG but it doesnt change.

**Comment by imLinguin** [comment]
Any improvement in 2.4.0?

**Comment by AvnarJakob** [comment]
No, still the same behavior. But I tried installing it manually with wine and it runs like dogshit. Not really worth spending to much time on.

**Comment by imLinguin** [comment]
Looks like game uses old V1 depot system. Let's keep this open untill the refactor I'm working on is done, hopefully bringing some improvements.

**Comment by flavioislima** [comment]
Should be fixed now.
