### ISSUE TITLE
"Game removed from Steam" notification for games that were not added to Steam

### ISSUE THREAD

**Issue by arielj** [Heroic-Games-Launcher/HeroicGamesLauncher#1681]
### Describe the bug

When uninstalling a game, a notification saying the game was removed from Steam and that Steam needs to be restarted shows up even if you didn't add the game to Steam.

### Add logs

```
(20:14:04) INFO:    [Legendary]:       Uninstalling 19927295d6e3467887d4e830d8c85963: /home/ariel/dev/oss/HeroicGamesLauncher/public/bin/linux/legendary uninstall 19927295d6e3467887d4e830d8c85963 -y
(20:14:04) INFO:    [Legendary]:       Installed game list updated
(20:14:04) INFO:    [Legendary]:       Installed game list updated
(20:14:04) INFO:    [Backend]:         Desktop shortcut removed
(20:14:04) INFO:    [Backend]:         Applications shortcut removed
(20:14:04) INFO:    [Shortcuts]:       Absolute Drift was successfully removed from Steam.
(20:14:04) INFO:    [Backend]:         Removing prefix /home/ariel/Games/Heroic/Prefixes/AbsoluteDrift
(20:14:04) INFO:    [Backend]:         finished uninstalling
```

### Steps to reproduce

1. Install a game
2. Without adding the game as a non-Steam game on Steam, uninstall it
3. The notifications shows up

### Expected behavior

It should only notify that the game was removed if the game was actually added as a non-Steam game in Steam.

### Screenshots

![image](https://user-images.githubusercontent.com/188464/183530619-b3106b80-803d-4f13-ac1e-d6ab7aed8ad3.png)

After that it shows the `Uninstalled` notification.

### System Information

- OS [e. g. "Ubuntu"]: not relevant
- Heroic Version [e. g. 2.1.1]: latest beta branch

**Comment by flavioislima** [comment]
That should be simple to fix I will add to the 2.4.0 milestone.
