### ISSUE TITLE
Fps overlay always shows even with env variable

### ISSUE THREAD

**Issue by davigamer987** [Heroic-Games-Launcher/HeroicGamesLauncher#1686]
### Describe the bug

In all games the fps overlay is always showing even with it disabled and with DXVK_HUD = 0 set both in heroic launcher and in /etc/environment

### Add logs

(10:53:00) INFO:    [Legendary]:       Running command: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary --version
(10:53:01) INFO:    [Legendary]:       Legendary location: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary
(10:53:01) INFO:    [Gog]:             GOGDL location: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl
(10:53:01) INFO:    [Backend]:         

Heroic Version: 2.4.0-beta.2 Caesar Clown
Legendary Version:  0.20.27 Dark Energy (hotfix)
OS: Arch KERNEL: 5.18.16-zen1-1-zen ARCH: x64
CPU: AMD Ryzen 7 5800X 8-Core Processor @3.8 GOVERNOR: schedutil
RAM: Total: 15.55 GiB Available: 12.23 GiB
GRAPHICS: GPU0: Navi 21 [Radeon RX 6800/6800 XT / 6900 XT] VRAM: 1MB DRIVER:  
PROTOCOL: x11

(10:53:01) WARNING: [Backend]:         Protocol already registered.
(10:53:02) INFO:    [Backend]:         AreWeAntiCheatYet data downloaded
(10:53:02) INFO:    [Frontend]:        Refreshing Library
(10:53:02) INFO:    [Legendary]:       Refreshing library...
(10:53:02) INFO:    [Legendary]:       Refreshing Epic Games...
(10:53:02) INFO:    [Legendary]:       Running command: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary list
(10:53:03) INFO:    [Legendary]:       Updating game list
(10:53:03) INFO:    [Legendary]:       Game List Updated
(10:53:03) INFO:    [Legendary]:       Checking for game updates.
(10:53:03) INFO:    [Legendary]:       Running command: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary list-installed --check-updates --tsv
(10:53:04) INFO:    [Legendary]:       Found 0 game(s) to update
(10:53:04) INFO:    [Gog]:             Found 0 game(s) to update
(10:53:04) INFO:    [Backend]:         Downloaded Winetricks
(10:53:13) INFO:    [Backend]:         Launching Fall Guys (0a2d9f6403244d12969e11da6713137b)
(10:53:13) INFO:    [Legendary]:       Running command: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary --version
(10:53:14) WARNING: [Backend]:         You are using Proton, this can lead to some bugs. Please do not open issues with bugs related to games
(10:53:14) WARNING: [Legendary]:       No Steam runtime found
(10:53:14) INFO:    [Legendary]:       Launching Fall Guys: dxvk=DXVK_HUD=0 LD_PRELOAD= STEAM_COMPAT_CLIENT_INSTALL_PATH=/home/davi/.steam/steam STEAM_COMPAT_DATA_PATH=/home/davi/Games/Heroic/Prefixes/FallGuys PROTON_EAC_RUNTIME=/home/davi/.config/heroic/tools/runtimes/eac_runtime STEAM_COMPAT_APP_ID=0 SteamAppId=0 SteamGameId=heroic-FallGuys PROTON_LOG_DIR=/home/davi /usr/bin/gamemoderun /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary launch 0a2d9f6403244d12969e11da6713137b --language en --no-wine --wrapper "'/home/davi/.config/heroic/tools/proton/GE-Proton7-26/proton' run" DXVK_HUD=0
(10:54:08) INFO:    [Backend]:         Stopped Discord Rich Presence
(10:54:08) INFO:    [Frontend]:        Refreshing Library
(10:54:08) INFO:    [Legendary]:       Refreshing library...
(10:54:08) INFO:    [Legendary]:       Updating game list
(10:54:08) INFO:    [Legendary]:       Game List Updated
(10:54:08) INFO:    [Legendary]:       Checking for game updates.
(10:54:08) INFO:    [Legendary]:       Running command: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary list-installed --check-updates --tsv
(10:54:08) INFO:    [Legendary]:       Found 0 game(s) to update
(10:56:50) INFO:    [Backend]:         Launching Fall Guys (0a2d9f6403244d12969e11da6713137b)
(10:56:50) INFO:    [Legendary]:       Running command: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary --version
(10:56:50) WARNING: [Backend]:         You are using Proton, this can lead to some bugs. Please do not open issues with bugs related to games
(10:56:50) WARNING: [Legendary]:       No Steam runtime found
(10:56:50) INFO:    [Legendary]:       Launching Fall Guys: dxvk=DXVK_HUD=0 LD_PRELOAD= STEAM_COMPAT_CLIENT_INSTALL_PATH=/home/davi/.steam/steam STEAM_COMPAT_DATA_PATH=/home/davi/Games/Heroic/Prefixes/FallGuys PROTON_EAC_RUNTIME=/home/davi/.config/heroic/tools/runtimes/eac_runtime STEAM_COMPAT_APP_ID=0 SteamAppId=0 SteamGameId=heroic-FallGuys PROTON_LOG_DIR=/home/davi /usr/bin/gamemoderun /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary launch 0a2d9f6403244d12969e11da6713137b --language en --no-wine --wrapper "'/home/davi/.config/heroic/tools/proton/GE-Proton7-26/proton' run" DXVK_HUD=0
(10:56:58) INFO:    [Backend]:         Stopped Discord Rich Presence
(10:56:58) INFO:    [Frontend]:        Refreshing Library
(10:56:58) INFO:    [Legendary]:       Refreshing library...
(10:56:58) INFO:    [Legendary]:       Updating game list
(10:56:58) INFO:    [Legendary]:       Game List Updated
(10:56:59) INFO:    [Legendary]:       Checking for game updates.
(10:56:59) INFO:    [Legendary]:       Running command: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary list-installed --check-updates --tsv
(10:56:59) INFO:    [Legendary]:       Found 0 game(s) to update
(10:57:18) INFO:    [Backend]:         Writing config for 0a2d9f6403244d12969e11da6713137b
(10:57:18) INFO:    [Backend]:         {
  "audioFix": false,
  "autoInstallDxvk": false,
  "autoInstallVkd3d": false,
  "preferSystemLibs": false,
  "enableEsync": false,
  "enableFsync": false,
  "maxSharpness": 2,
  "language": "",
  "launcherArgs": "DXVK_HUD=0",
  "nvidiaPrime": false,
  "enviromentOptions": [],
  "wrapperOptions": [],
  "savesPath": "",
  "showFps": false,
  "showMangohud": false,
  "targetExe": "",
  "useGameMode": true,
  "wineCrossoverBottle": "Heroic",
  "winePrefix": "/home/davi/Games/Heroic/Prefixes/FallGuys",
  "wineVersion": {
    "bin": "/home/davi/.config/heroic/tools/proton/GE-Proton7-26/proton",
    "name": "Proton - GE-Proton7-26",
    "type": "proton"
  },
  "eacRuntime": true,
  "battlEyeRuntime": false
}
(10:57:21) INFO:    [Backend]:         Launching Fall Guys (0a2d9f6403244d12969e11da6713137b)
(10:57:21) INFO:    [Legendary]:       Running command: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary --version
(10:57:21) WARNING: [Backend]:         You are using Proton, this can lead to some bugs. Please do not open issues with bugs related to games
(10:57:21) WARNING: [Legendary]:       No Steam runtime found
(10:57:21) INFO:    [Legendary]:       Launching Fall Guys: LD_PRELOAD= STEAM_COMPAT_CLIENT_INSTALL_PATH=/home/davi/.steam/steam STEAM_COMPAT_DATA_PATH=/home/davi/Games/Heroic/Prefixes/FallGuys PROTON_EAC_RUNTIME=/home/davi/.config/heroic/tools/runtimes/eac_runtime STEAM_COMPAT_APP_ID=0 SteamAppId=0 SteamGameId=heroic-FallGuys PROTON_LOG_DIR=/home/davi /usr/bin/gamemoderun /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary launch 0a2d9f6403244d12969e11da6713137b --language en --no-wine --wrapper "'/home/davi/.config/heroic/tools/proton/GE-Proton7-26/proton' run" DXVK_HUD=0
(10:57:26) INFO:    [Backend]:         Stopped Discord Rich Presence
(10:57:26) INFO:    [Frontend]:        Refreshing Library
(10:57:26) INFO:    [Legendary]:       Refreshing library...
(10:57:26) INFO:    [Legendary]:       Updating game list
(10:57:26) INFO:    [Legendary]:       Game List Updated
(10:57:26) INFO:    [Legendary]:       Checking for game updates.
(10:57:26) INFO:    [Legendary]:       Running command: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary list-installed --check-updates --tsv
(10:57:27) INFO:    [Legendary]:       Found 0 game(s) to update
(10:58:50) INFO:    [Legendary]:       Running command: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary --version
(10:58:50) INFO:    [Gog]:             Running command: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --version

### Steps to reproduce

1. 'Find a game'
2. Disable dxvk hud
3. It stays on

### Expected behavior

DXVK hud is disabled when the option in settings is disabled

### Screenshots

![image](https://user-images.githubusercontent.com/68574209/183685417-d12a5121-fcec-4939-bfd8-0a6ef244127b.png)

### System Information

- OS Arch linux
- Heroic Version: 2.4.0-beta.2

### Additional information

env | grep 'DXVK_HUD' reports DXVK_HUD=0

**Comment by Nocccer** [comment]
1. You put the env variable in the wrong setting. It is a "Enviroment Variable" and should be in the Enviroment variable setting. It is not a launch argument for the game!
2. You use proton-ge, our guide suggest wine-ge: https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/wiki/FallGuys
3. The FPS doe snot look like DXVK_HUD. Maybe it comes from GameMode. Please run the game with wine-ge and if it still shows the FPS, i can try to find the issue.

**Comment by davigamer987** [comment]
With wine-ge the hud is gone, but i would like to use proton-ge tho
