### ISSUE TITLE
No Wine-Ge/Proton found leads to wine prefix problems on steam deck.

### ISSUE THREAD

**Issue by Nocccer** [Heroic-Games-Launcher/HeroicGamesLauncher#1687]
### Describe the bug

It is hard to describe, but if the user does not install a single steam game, before using heroic on steam deck, there is never a proton version installed. This leads to the problem where user starting to install games with the factory default settings, which pointing to system wine. System wine is not available on steam deck. We should throw a error if no wine or proton version is found and link instead to our wine-manager to install atleast one version.

### Add logs

No logs

### Steps to reproduce

Install a vm with heroic without any wine/proton version

### Expected behavior

Throw error if no wine/proton version is found. Means also no system wine.

### System Information

- OS [e. g. "Ubuntu"]: SteamDeckOS
- Heroic Version [e. g. 2.1.1]: 2.4.0-beta.2

**Comment by arielj** [comment]
This should be fixed by https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/pull/1912, now we check if either the wine binary is an empty string or if the wine binary actually exists, if the wine config is invalid it shows an error.
