### ISSUE TITLE
Epic Games Overlay is invisible in Fall guys

### ISSUE THREAD

**Issue by davigamer987** [Heroic-Games-Launcher/HeroicGamesLauncher#1689]
### Describe the bug

Epic games overlay in fall guys is invisible, the ui is there but you can't see it, you can still click the button and etc tho

### Add logs

System Info:
Heroic Version: 2.4.0-beta.2 Caesar Clown
Legendary Version:  0.20.27 Dark Energy (hotfix)
OS: Arch KERNEL: 5.18.16-zen1-1-zen ARCH: x64
CPU: AMD Ryzen 7 5800X 8-Core Processor @3.8 GOVERNOR: schedutil
RAM: Total: 15.55 GiB Available: 7.09 GiB
GRAPHICS: GPU0: Navi 21 [Radeon RX 6800/6800 XT / 6900 XT] VRAM: 1MB DRIVER:  
PROTOCOL: x11

Game Settings: {
	"audioFix": false,
	"autoInstallDxvk": false,
	"autoInstallVkd3d": false,
	"preferSystemLibs": false,
	"enableEsync": false,
	"enableFsync": false,
	"maxSharpness": 2,
	"launcherArgs": "DXVK_HUD=0",
	"nvidiaPrime": false,
	"enviromentOptions": [],
	"wrapperOptions": [],
	"savesPath": "",
	"showFps": false,
	"showMangohud": false,
	"targetExe": "",
	"useGameMode": false,
	"language": "",
	"wineVersion": {
		"bin": "/home/davi/.config/heroic/tools/wine/Wine-GE-Proton7-25/bin/wine",
		"name": "Wine - Wine-GE-Proton7-25",
		"type": "wine",
		"lib": "/home/davi/.config/heroic/tools/wine/Wine-GE-Proton7-25/lib64",
		"lib32": "/home/davi/.config/heroic/tools/wine/Wine-GE-Proton7-25/lib",
		"wineserver": "/home/davi/.config/heroic/tools/wine/Wine-GE-Proton7-25/bin/wineserver",
		"wineboot": "/home/davi/.config/heroic/tools/wine/Wine-GE-Proton7-25/bin/wineboot"
	},
	"winePrefix": "/home/davi/Games/Heroic/Prefixes/FallGuys",
	"wineCrossoverBottle": "Heroic",
	"eacRuntime": true,
	"battlEyeRuntime": false
}

Game launched at: Tue Aug 09 2022 23:45:40 GMT-0400 (Eastern Daylight Time)

Launch Command: LD_PRELOAD= WINEPREFIX=/home/davi/Games/Heroic/Prefixes/FallGuys PROTON_EAC_RUNTIME=/home/davi/.config/heroic/tools/runtimes/eac_runtime LD_LIBRARY_PATH=/home/davi/.config/heroic/tools/wine/Wine-GE-Proton7-25/lib:/home/davi/.config/heroic/tools/wine/Wine-GE-Proton7-25/lib64: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary launch 0a2d9f6403244d12969e11da6713137b --language en  --wine /home/davi/.config/heroic/tools/wine/Wine-GE-Proton7-25/bin/wine --wine-prefix /home/davi/Games/Heroic/Prefixes/FallGuys DXVK_HUD=0

Game Log:
[cli] INFO: Logging in...
[Core] INFO: Trying to re-use existing login session...
[cli] INFO: Checking for updates...
[Core] INFO: Getting authentication token...
[cli] INFO: Launching 0a2d9f6403244d12969e11da6713137b...
wineserver: using server-side synchronization.
wine: Using setpriority to control niceness in the [-10,10] range
002c:fixme:winediag:LdrInitializeThunk wine-staging 7.0 is a testing version containing experimental patches.
002c:fixme:winediag:LdrInitializeThunk Please mention your exact version when filing bug reports on winehq.org.
0024:fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (0104FC94 1 C) semi-stub
0024:fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (0104FC7C 1 C) semi-stub
0024:fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (0104FCAC 1 C) semi-stub
0024:fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (0104FD18 1 C) semi-stub
0024:fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (0104FAEC 1 C) semi-stub
0024:fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (0104FA7C 1 C) semi-stub
FGenericBootstrapper::Bootstrap: Started Epic Online Services Bootstrapper 1.0.0++EOSSDK+Release-FGS6-CL-18019720
0024:fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (0104F9AC 1 C) semi-stub
FGenericBootstrapper::Bootstrap: Getting config path
0024:fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (0104F9BC 1 C) semi-stub
0024:fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (0104F948 1 C) semi-stub
FGenericBootstrapper::Bootstrap: Reading config from path: 'Z:\home\davi\fguys\FallGuys\FallGuys_client.ini'
0024:fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (0104F9B4 1 C) semi-stub
0024:fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (0104F708 1 C) semi-stub
0024:fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (0104F5A4 1 C) semi-stub
0024:fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (0104F91C 1 C) semi-stub
0024:fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (0104F91C 1 C) semi-stub
0024:fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (0104F5A4 1 C) semi-stub
0024:fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (0104F708 1 C) semi-stub
0024:fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (0104F708 1 C) semi-stub
0024:fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (0104F708 1 C) semi-stub
0024:fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (0104F700 1 C) semi-stub
0024:fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (0104F708 1 C) semi-stub
0024:fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (0104F708 1 C) semi-stub
0024:fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (0104F708 1 C) semi-stub
0024:fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (0104F708 1 C) semi-stub
0024:fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (0104F708 1 C) semi-stub
0024:fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (0104F700 1 C) semi-stub
0024:fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (0104F708 1 C) semi-stub
0024:fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (0104F708 1 C) semi-stub
0024:fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (0104F708 1 C) semi-stub
0024:fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (0104F700 1 C) semi-stub
0024:fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (0104F710 1 C) semi-stub
FGenericBootstrapper::Bootstrap: Creating session
0024:fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (0104F9BC 1 C) semi-stub
0024:fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (0104F940 1 C) semi-stub
0024:fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (0104E4F4 1 C) semi-stub
0024:fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (0104E474 1 C) semi-stub
0024:fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (0104E454 1 C) semi-stub
0024:fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (0104E4EC 1 C) semi-stub
0024:fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (0104F938 1 C) semi-stub
0024:fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (0104F940 1 C) semi-stub
0024:fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (0104F8B4 1 C) semi-stub
0024:fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (0104F828 1 C) semi-stub
0024:fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (0104F828 1 C) semi-stub
0024:fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (0104F744 1 C) semi-stub
0024:fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (0104F744 1 C) semi-stub
0024:fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (0104F828 1 C) semi-stub
0024:fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (0104F828 1 C) semi-stub
0024:fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (0104F8B4 1 C) semi-stub
FGenericBootstrapper::TryCreateSession: Creating process group
0024:fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (0104F940 1 C) semi-stub
0024:fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (0104F848 1 C) semi-stub
0024:fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (0104F850 1 C) semi-stub
0024:fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (0104F940 1 C) semi-stub
FGenericBootstrapper::Bootstrap: Getting path to User Helper
0024:fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (0104F9BC 1 C) semi-stub
0024:fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (0104F940 1 C) semi-stub
0024:fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (0104F8C0 1 C) semi-stub
FWindowsPlatform::TryGetValueFromRegistry: Failed to get value from registry with SubKeyName 'SOFTWARE\Epic Games\EOS\UserHelper' and ValueName 'Path'
0024:fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (0104F8C0 1 C) semi-stub
FWindowsBootstrapper::TryGetUserHelperPath: Path does not exist in registry
0024:fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (0104F940 1 C) semi-stub
FGenericBootstrapper::Bootstrap: Failed to find path to User Helper
0024:fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (0104F9BC 1 C) semi-stub
0024:fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (0104F974 1 C) semi-stub
FGenericBootstrapper::Bootstrap: Executing target application: 'Z:\home\davi\fguys\FallGuys\FallGuys_client_game.exe'
0024:fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (0104F9B4 1 C) semi-stub
0024:fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (0104F89C 1 C) semi-stub
0024:fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (0104F8A4 1 C) semi-stub
0024:fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (0104F8A4 1 C) semi-stub
0024:fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (0104F89C 1 C) semi-stub
0024:fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (0104F9BC 1 C) semi-stub
FGenericBootstrapper::Bootstrap: Succeeded
0148:fixme:thread:NtSetInformationThread Can't set other thread's platform description
0144:fixme:thread:NtSetInformationThread Can't set other thread's platform description
014c:fixme:thread:NtSetInformationThread Can't set other thread's platform description
0150:fixme:thread:NtSetInformationThread Can't set other thread's platform description
0154:fixme:thread:NtSetInformationThread Can't set other thread's platform description
0158:fixme:thread:NtSetInformationThread Can't set other thread's platform description
015c:fixme:thread:NtSetInformationThread Can't set other thread's platform description
0160:fixme:thread:NtSetInformationThread Can't set other thread's platform description
0164:fixme:thread:NtSetInformationThread Can't set other thread's platform description
0168:fixme:thread:NtSetInformationThread Can't set other thread's platform description
016c:fixme:thread:NtSetInformationThread Can't set other thread's platform description
0170:fixme:thread:NtSetInformationThread Can't set other thread's platform description
0174:fixme:thread:NtSetInformationThread Can't set other thread's platform description
0178:fixme:thread:NtSetInformationThread Can't set other thread's platform description
017c:fixme:thread:NtSetInformationThread Can't set other thread's platform description
0180:fixme:thread:NtSetInformationThread Can't set other thread's platform description
0184:fixme:thread:NtSetInformationThread Can't set other thread's platform description
0188:fixme:thread:NtSetInformationThread Can't set other thread's platform description
018c:fixme:thread:NtSetInformationThread Can't set other thread's platform description
0190:fixme:thread:NtSetInformationThread Can't set other thread's platform description
0194:fixme:thread:NtSetInformationThread Can't set other thread's platform description
0198:fixme:thread:NtSetInformationThread Can't set other thread's platform description
019c:fixme:thread:NtSetInformationThread Can't set other thread's platform description
01a0:fixme:thread:NtSetInformationThread Can't set other thread's platform description
01a4:fixme:thread:NtSetInformationThread Can't set other thread's platform description
01a8:fixme:thread:NtSetInformationThread Can't set other thread's platform description
01ac:fixme:thread:NtSetInformationThread Can't set other thread's platform description
01b0:fixme:thread:NtSetInformationThread Can't set other thread's platform description
010c:fixme:ntdll:NtQuerySystemInformation info_class SYSTEM_PERFORMANCE_INFORMATION
01b4:fixme:thread:NtSetInformationThread Can't set other thread's platform description
01b8:fixme:thread:NtSetInformationThread Can't set other thread's platform description
01bc:fixme:thread:NtSetInformationThread Can't set other thread's platform description
01c0:fixme:thread:NtSetInformationThread Can't set other thread's platform description
01c4:fixme:thread:NtSetInformationThread Can't set other thread's platform description
010c:fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (000000000010F430 1 C) semi-stub
010c:fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (000000000010F4D0 1 C) semi-stub
010c:fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (000000000010F4E0 1 C) semi-stub
010c:err:wldap32:DllMain No libldap support, expect problems
010c:err:kerberos:kerberos_LsaApInitializePackage no Kerberos support, expect problems
010c:fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (000000000010F220 1 C) semi-stub
010c:fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (000000000010F220 1 C) semi-stub
01cc:fixme:cryptasn:CRYPT_GetBuiltinDecoder Unsupported decoder for lpszStructType 1.3.6.1.4.1.311.2.1.4
01cc:fixme:cryptasn:CRYPT_GetBuiltinDecoder Unsupported decoder for lpszStructType 1.3.6.1.4.1.311.2.1.4
010c:fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (000000000010CC40 1 C) semi-stub
010c:fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (000000000010CA10 1 C) semi-stub
010c:fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (000000000010C970 1 C) semi-stub
ATTENTION: default value of option vblank_mode overridden by environment.

### Steps to reproduce

1. Open fall guys with egs enabled
2. Click on the add friends button

### Expected behavior

Ui shows up as normal

### System Information

- OS: Arch Linux 
- Heroic Version: 2.4.0-beta.2

### Additional information

If you press ctrl + a and then ctrl + c and ctrl + v it copies the contents of the overlay which shows it's actually there but just invisible, the cursor also changes from the fall guys one to the system one, EGS is enabled in game settings! using wine-ge

**Comment by davigamer987** [comment]
This seems to be an issue with wine-ge, using proton-ge 7-26 it works but proton ge has an issue where the fps overlay is always showing (#1686)

**Comment by flavioislima** [comment]
The issue is not on Heroic though, I cannot replicate it.
Last time this happened was because of some env var globally set. Check your global environments.

**Comment by Nocccer** [comment]
I linked you the guide yesterday. Did you read it? The fix is to install corefonts on the prefix. Sometimes reading the guide can help!

**Comment by davigamer987** [comment]
> I linked you the guide yesterday. Did you read it? The fix is to install corefonts on the prefix. Sometimes reading the guide can help!

Hi i read the guide and ran the command to install corefonts, nothing changed

**Comment by davigamer987** [comment]
> The issue is not on Heroic though, I cannot replicate it. Last time this happened was because of some env var globally set. Check your global environments.

DXVK_HUD is globally set to 0
