### ISSUE TITLE
Can't disable Esync (With proton runner)

### ISSUE THREAD

**Issue by pixartist** [Heroic-Games-Launcher/HeroicGamesLauncher#1691]
### Describe the bug

When the Esync checkmark for a game is unset, it will still run with esync

### Add logs

```
System Info:

Heroic Version: 2.4.0-beta.2 Caesar Clown

Legendary Version:  0.20.27 Dark Energy (hotfix)

OS: Ubuntu KERNEL: 5.15.0-43-generic ARCH: x64

CPU: AMD Ryzen 9 3900X 12-Core Processor @3.8 GOVERNOR: performance

RAM: Total: 31.26 GiB Available: 26.15 GiB

GRAPHICS: GPU0: NVIDIA GeForce RTX 3080 VRAM: 10240MB DRIVER: 510.85.02 

PROTOCOL: x11

Game Settings: {

	"autoInstallDxvk": false,

	"autoInstallVkd3d": false,

	"preferSystemLibs": false,

	"maxSharpness": 2,

	"language": "",

	"nvidiaPrime": false,

	"enviromentOptions": [],

	"wrapperOptions": [],

	"savesPath": "",

	"showFps": false,

	"targetExe": "",

	"useGameMode": false,

	"wineCrossoverBottle": "Heroic",

	"winePrefix": "/home/finn/Games/Heroic/Prefixes/FallGuys/pfx/",

	"wineVersion": {

		"bin": "/home/finn/.local/share/Steam/compatibilitytools.d/GE-Proton7-14/proton",

		"name": "Proton - GE-Proton7-14",

		"type": "proton"

	},

	"eacRuntime": true,

	"battlEyeRuntime": false

}

Game launched at: Wed Aug 10 2022 09:12:35 GMT+0200 (Central European Summer Time)

Launch Command: LD_PRELOAD= STEAM_COMPAT_CLIENT_INSTALL_PATH=/home/finn/.steam/steam STEAM_COMPAT_DATA_PATH=/home/finn/Games/Heroic/Prefixes/FallGuys/pfx/ PROTON_EAC_RUNTIME=/home/finn/.config/heroic/tools/runtimes/eac_runtime STEAM_COMPAT_APP_ID=0 SteamAppId=0 SteamGameId=heroic-FallGuys PROTON_LOG_DIR=/home/finn /tmp/.mount_HeroicOWTfNE/resources/app.asar.unpacked/build/bin/linux/legendary launch 0a2d9f6403244d12969e11da6713137b --language en  --no-wine --wrapper "'/home/finn/.local/share/Steam/compatibilitytools.d/GE-Proton7-14/proton' run"

Game Log:

[cli] INFO: Logging in...

[Core] INFO: Trying to re-use existing login session...

[cli] INFO: Checking for updates...

[Core] INFO: Getting authentication token...

[cli] INFO: Launching 0a2d9f6403244d12969e11da6713137b...

esync: up and running.

wine: RLIMIT_NICE is <= 20, unable to use setpriority safely

[S_API] SteamAPI_Init(): SteamAPI_IsSteamRunning() did not locate a running instance of Steam.

[S_API FAIL] SteamAPI_Init() failed

FGenericBootstrapper::Bootstrap: Started Epic Online Services Bootstrapper 1.0.0++EOSSDK+Release-FGS6-CL-18019720

FGenericBootstrapper::Bootstrap: Getting config path

FGenericBootstrapper::Bootstrap: Reading config from path: 'Z:\home\finn\Games\Heroic\FallGuys\FallGuys_client.ini'

FGenericBootstrapper::Bootstrap: Creating session

FGenericBootstrapper::TryCreateSession: Creating process group

FGenericBootstrapper::Bootstrap: Getting path to User Helper

FWindowsPlatform::TryGetValueFromRegistry: Failed to get value from registry with SubKeyName 'SOFTWARE\Epic Games\EOS\UserHelper' and ValueName 'Path'

FWindowsBootstrapper::TryGetUserHelperPath: Path does not exist in registry

FGenericBootstrapper::Bootstrap: Failed to find path to User Helper

FGenericBootstrapper::Bootstrap: Executing target application: 'Z:\home\finn\Games\Heroic\FallGuys\FallGuys_client_game.exe'

FGenericBootstrapper::Bootstrap: Succeeded

```

### Steps to reproduce

1. Go to 'Game Settings  -> Wine"
2. Uncheck "Enable Esync"
3. Launch Game
4. See logs

### Expected behavior

Esync is disabled

### System Information

- Laucher 2.4.0-beta.2
- Ubuntu 22.04

**Comment by Nocccer** [comment]
I don't see that esync is enabled. I think it is a problem that you use proton. 

Follow our Fall Guys wine-ge guide:
https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/wiki/FallGuys


If you have still problems with esync under wine-ge, report back.

Note: If you enabled esync in general settings, it will be applied for each game.

**Comment by Etaash-mathamsetty** [comment]
This will be fixed with the next heroic release if you really don't want to use esync

**Comment by pixartist** [comment]
Fall Guys only works with proton and esync disabled

**Comment by pixartist** [comment]
> I don't see that esync is enabled. I think it is a problem that you use proton.
> 
> Follow our Fall Guys wine-ge guide: https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/wiki/FallGuys
> 
> If you have still problems with esync under wine-ge, report back.
> 
> Note: If you enabled esync in general settings, it will be applied for each game.

If you look at the logs you will see ```
esync: up and running.
```

**Comment by imLinguin** [comment]
When using Proton you need to explicitly disable them using env vars
`PROTON_NO_ESYNC=1` and `PROTON_NO_FSYNC=1` they are enabled by default

**Comment by pixartist** [comment]
> When using Proton you need to explicitly disable them using env vars `PROTON_NO_ESYNC=1` and `PROTON_NO_FSYNC=1` they are enabled by default

Yes i did that but that should be automatically passed to proton when explicitly disabled in the settings.

**Comment by imLinguin** [comment]
So, summarizing, for Proton runner, Esync and Fsync checkbox should work the other way they do with wine, thus Esync and Fsync should be enabled by default (for convenience)

**Comment by pixartist** [comment]
> So, summarizing, for Proton runner, Esync and Fsync checkboxes should work the other way they do with wine, thus Esync and Fsync should be enabled by default (for convenience)

hmm or they could also be off but then the proton parameters would need to be set by default (PROTON_NO_ESYNC=1 and PROTON_NO_FSYNC=1)

**Comment by Etaash-mathamsetty** [comment]
> Fall Guys only works with proton and esync disabled

it works fine for me with fsync and esync both enabled

**Comment by pixartist** [comment]
> 

Strange, it crashes after 20-30 seconds gameplay for me with esync and it also said to disable it because of random crashes in multiple guides

**Comment by Etaash-mathamsetty** [comment]
> > 
> 
> Strange, it crashes after 20-30 seconds gameplay for me with esync and it also said to disable it because of random crashes in multiple guides

I would recommend updating your version of proton since it's VERY old, and secondly I have played the game for multiple hours with fsync and esync enabled and it works just fine

**Comment by pixartist** [comment]
> I would recommend updating your version of proton since it's VERY old

I used proton 27 first but it also crashed, then I read some comments that I should not use above proton 21 for fall guys and just stuck to it when it started working (due to disabling esync). I think esync does not work with fall guys in any version of proton.

**Comment by Nocccer** [comment]
In beta branch we fixed esync with proton, will be in next release:
https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/blob/e8729c54b2248c4231959b66052202e25d7f0f8a/electron/launcher.ts#L299-L310

Still if you don't wanna follow our Fall Guys guide with wine-ge, then we can't help with problems. Proton is not developed for games outside of steam, so it can break or act weirdly. That's why we don't help with proton/proton-ge. Wine-ge has all fixes what proton-ge offers!
