### ISSUE TITLE
Add a flatpak nightly build

### ISSUE THREAD

**Issue by Etaash-mathamsetty** [Heroic-Games-Launcher/HeroicGamesLauncher#1694]
### Problem description

I really don't want to keep downloading app images from the latest CI from the beta/main branch.
It would also help catch random bugs that were created as a result of certain PR's

### Feature description

To fix this problem we could introduce a nightly build that one can download from flatpak

### Alternatives

download the app image every day?

**Comment by Nocccer** [comment]
@flavioislima I was also thinking that the beta channel gets updated on each merge. So we have the stable and a up to date dev version. Does flatpak supports a experimental version? It would be really good to have this like proton experimental, but that would be another version. I think it is not possible but having a up to date beta version would be awesome.

**Comment by imLinguin** [comment]
If it wouldn't be possible on flathub, we can always spin up our own repo for highly unstable releases

**Comment by Nocccer** [comment]
https://github.com/flathub/flathub/issues/2975
Flathub seems not to allow nightly.

**Comment by Etaash-mathamsetty** [comment]
> [flathub/flathub#2975](https://github.com/flathub/flathub/issues/2975) Flathub seems not to allow nightly.

I mean they said that it required "prior discussion", so all we have to do is ask them...
and by nightly I mean every day or every 2 days, which is not "every commit"
