### ISSUE TITLE
Getting an exception while launching a GTA 5 game

### ISSUE THREAD

**Issue by deadnight7** [Heroic-Games-Launcher/HeroicGamesLauncher#1701]
### Describe the bug

Getting an exception while launching a GTA 5 Game - TypeError: Cannot read properties of undefined (reading 'charAt')

### Add logs

System Info:
Heroic Version: 2.4.0-beta.2 Caesar Clown
Legendary Version:  0.20.27 Dark Energy (hotfix)
OS: macOS KERNEL: 21.4.0 ARCH: x64
CPU: Apple M1 Pro @2.4 
RAM: Total: 16 GiB Available: 11.86 GiB
GRAPHICS: GPU0: Apple M1 Pro VRAM: nullMB DRIVER:  

Game Settings: {
	"autoInstallDxvk": true,
	"autoInstallVkd3d": false,
	"preferSystemLibs": false,
	"maxSharpness": 2,
	"nvidiaPrime": false,
	"enviromentOptions": [],
	"wrapperOptions": [],
	"savesPath": "",
	"showFps": false,
	"targetExe": "",
	"useGameMode": false,
	"language": "",
	"wineVersion": {
		"bin": "/Applications/CrossOver.app/Contents/SharedSupport/CrossOver/bin/wine",
		"name": "CrossOver - 21.2",
		"type": "crossover",
		"wineserver": "/Applications/CrossOver.app/Contents/SharedSupport/CrossOver/bin/wineserver",
		"wineboot": ""
	},
	"wineCrossoverBottle": "Heroic",
	"eacRuntime": false,
	"battlEyeRuntime": false
}

Game launched at: Thu Aug 11 2022 13:16:12 GMT+0530 (India Standard Time)

An exception occurred when launching the game:
TypeError: Cannot read properties of undefined (reading 'charAt')
    at quoteIfNecessary (/Applications/Heroic.app/Contents/Resources/app.asar/build/utils.js:461:24)
    at Array.map (<anonymous>)
    at getRunnerCallWithoutCredentials (/Applications/Heroic.app/Contents/Resources/app.asar/build/launcher.js:474:29)
    at LegendaryGame.launch (/Applications/Heroic.app/Contents/Resources/app.asar/build/legendary/games.js:503:76)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async node:electron/js2c/browser_init:189:563

### Steps to reproduce

1. Downloaded GTA5
2. Clicked launch app
3. Button changes on "Playing(stop)" for sometime then reverts back to "play now"

### Expected behavior

Should have launched

### Screenshots

<img width="1312" alt="image" src="https://user-images.githubusercontent.com/3257861/184088047-60367f2c-77f6-40a6-a4b0-726ad765ae62.png">

![Uploading image.png…]()

### System Information

- MacOS Monterey 12.3 
- Heroic Version [e. g. 2.4.0-beta2]
- Crossover 21.1

**Comment by Nocccer** [comment]
i think this is the bug where `--wineprefix` value was undefined.
@CommandMC @flavioislima one of you fixed it, if i'm correct?

**Comment by flavioislima** [comment]
Yes, this was fixed.

**Comment by flavioislima** [comment]
@deadnight7 can you try the DMG from this build:
https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/actions/runs/2834176650
?

**Comment by ilisparrow** [comment]
Hello, 

I need to check the logs later, but I have the same behavior on my steam deck when trying to run it. It used to be working perfectly.
Best regards,

**Comment by Nocccer** [comment]
> Hello,
> 
> I need to check the logs later, but I have the same behavior on my steam deck when trying to run it. It used to be working perfectly. Best regards,

No this error only happend on macos. Your problem would be the broken rockstar launcher for all none windows system atm.
So keep an eye on wine to fix this.

**Comment by Nocccer** [comment]
@deadnight7 new release with possible fix for the typeerror. Still GTA 5 is broken imo. See my comment above.

**Comment by cpandit201** [comment]
Thanks team, I cloned the repo locally and built it myself on Marcos with latest main branch. 

This seems to be resolved on the latest commit from main branch. Please release the latest version with this fix

**Comment by Nocccer** [comment]
Already done. Check release in github. We released 2.4.0 today.
