### ISSUE TITLE
[Longshot] Epic Wallet on Linux

### ISSUE THREAD

**Issue by cybik** [Heroic-Games-Launcher/HeroicGamesLauncher#1703]
### Feature description

Following a [discussion on Twitter](https://twitter.com/ImLinguin/status/1557726247232630784), this is very the longest of longshots, but since Heroic is right now the closest thing to an Epic Games Launcher alternative Linux has, _**if**_ Heroic is working with Epic right now, is it possible that Heroic itself would support the Epic Overlay system on Linux?

This would, for example, mean that games launched via Heroic would "flip on" such systems as Epic Wallet. As an example, using EGS to launch Genshin Impact on Windows makes the game use Epic for financial transactions, instead of their normal WorldPay processor.

I'm already assuming a No, but asking on the off chance.

**Comment by Nocccer** [comment]
@cybik is it working?

**Comment by cybik** [comment]
I had issues initially. Retrying right now. Hopefully this run goes smoother.

**Comment by cybik** [comment]
@Nocccer I shall be utterly damned. Opening a money transaction in _**a certain game**_ with the EOS Overlay forced to active, actually made use of Epic Wallet instead of the other processor.
