### ISSUE TITLE
[UI] Add information for Nvidia Prime

### ISSUE THREAD

**Issue by Nocccer** [Heroic-Games-Launcher/HeroicGamesLauncher#1707]
### Problem description

Missing info for nvidia prime switch. we need to add information for that and also call it NVIDIA Prime again!
![image](https://user-images.githubusercontent.com/61798668/184217618-f33a564e-4447-45ba-9bf5-95c630664113.png)

### Feature description

none

**Comment by flavioislima** [comment]
We can maybe add both but this setting works for both Nvidia and AMD.
We changed it exactly because people from AMD didn't know they could use that.
Unless we find a way of checking the Graphic card and then show the correct option, what do you think?

**Comment by Nocccer** [comment]
Atm the option is unclear. We need the info hover, like on other options!

**Comment by Raycert07** [comment]
Here's my idea, something along the lines of

> option uses dedicated graphics card to render game on multi gpu systems. Only needed on gaming laptops, or desktops that use a headless gpu for graphics rendering.
