### ISSUE TITLE
Environment variables table improvements

### ISSUE THREAD

**Issue by arielj** [Heroic-Games-Launcher/HeroicGamesLauncher#1712]
### Problem description

The environment variables table is a great improvement, but there are some things that can be improved to make it more user friendly.

### Feature description

Some ideas:
- add an `(i) Info` block so people can see how it's used with a simple example like "for a variable like MY_VAR=1, put `MY_VAR` as name and `1` as value, then click the `+` button to add it"
- add a `=` character between the fields so users understand better what goes where
- detect if the value of the name includes an `=` sign and automatically split it and put the correct value in each field
- inside a game's setting, show (as readonly) the globally configured env variables so you can see what's happening
- detect when a user puts a variable of a feature we already handle with a toggle and suggest removing it and using the toggle
- detect duplicated variable names
- add a warning next to the fields saying that the variable is NOT saved automatically and the `+` click is required (since we have a comment in the settings saying that settings are saved automatically!)

**Comment by Nocccer** [comment]
- already detect duplicated variable names
- i would prefer the user envs over our toggles. So the user can override the behavior we add, if he wants too.

**Comment by arielj** [comment]
> * already detect duplicated variable names
oops didn't know, does it detect duplications comparing with the global env variables too?

> * i would prefer the user envs over our toggles. So the user can override the behavior we add, if he wants too.
hmmm does this mean our toggles are not correct? not sure I understand the use case

wild idea: make our toggles add env variables to the table directly instead of handling things in the background? or maybe show in the `(i)` tooltip for the toggles what env variable is being added?

**Comment by Nocccer** [comment]
> > * already detect duplicated variable names
> 
> oops didn't know, does it detect duplications comparing with the global env variables too?
> 
> > * i would prefer the user envs over our toggles. So the user can override the behavior we add, if he wants too.
> 
> hmmm does this mean our toggles are not correct? not sure I understand the use case
> 
> wild idea: make our toggles add env variables to the table directly instead of handling things in the background? or maybe show in the `(i)` tooltip for the toggles what env variable is being added?

Between global and game i don't know. I don't even know how global envs are working. From my understanding global settings are the default values passed to a fresh installed game.

Today a user had problems to run Mangohud on a opengl game. We can't detect if the game runs with vulkan or opengl. He solved it by adding a env.

**Comment by arielj** [comment]
> > > * already detect duplicated variable names
> > 
> > 
> > oops didn't know, does it detect duplications comparing with the global env variables too?
> > > * i would prefer the user envs over our toggles. So the user can override the behavior we add, if he wants too.
> > 
> > 
> > hmmm does this mean our toggles are not correct? not sure I understand the use case
> > wild idea: make our toggles add env variables to the table directly instead of handling things in the background? or maybe show in the `(i)` tooltip for the toggles what env variable is being added?
> 
> Between global and game i don't know. I don't even know how global envs are working. From my understanding global settings are the default values passed to a fresh installed game.

maybe, I also don't know how that work, will test later, I though it was a `always apply this env variables` and not a `add this as default settings for a game` but I haven't checked

> Today a user had problems to run Mangohud on a opengl game. We can't detect if the game runs with vulkan or opengl. He solved it by adding a env.

but does this mean our Mongohud toggle is doing something different than what the user did? or that our Mongohud toggle isn't really working?

**Comment by Nocccer** [comment]
> but does this mean our Mongohud toggle is doing something different than what the user did? or that our Mongohud toggle isn't really working?

Mangohud needs to be runned different for vulkan and opengl and i think we do the vulkan way. 
https://github.com/flightlessmango/MangoHud#opengl

**Comment by arielj** [comment]
I think it's worth to add a separate issue about that so we don't forget about it

**Comment by flavioislima** [comment]
I think was done although GH forgot to close this.
