### ISSUE TITLE
error when rendering graphics

### ISSUE THREAD

**Issue by Cris-lml007** [Heroic-Games-Launcher/HeroicGamesLauncher#1713]
### Describe the bug

Opening the multiversus game gives me the following error:  
![image](https://user-images.githubusercontent.com/83845332/184407363-db21279e-354c-49f8-96be-7549330f161c.png)  

### Add logs

System Info:

Heroic Version: 2.4.0 Chopper

Legendary Version:  0.20.27 Dark Energy (hotfix)

OS: Kali GNU/Linux KERNEL: 5.18.0-kali5-amd64 ARCH: x64

CPU: Intel Core™ i7-1065G7 @1.3 GOVERNOR: powersave

RAM: Total: 7.35 GiB Available: 5.08 GiB

GRAPHICS: GPU0: Iris Plus Graphics G7  VRAM: 256MB DRIVER:  

PROTOCOL: x11

Game Settings: {

	"autoInstallDxvk": true,

	"autoInstallVkd3d": false,

	"preferSystemLibs": false,

	"enableEsync": true,

	"maxSharpness": 2,

	"language": "",

	"nvidiaPrime": false,

	"enviromentOptions": [],

	"wrapperOptions": [],

	"savesPath": "",

	"showFps": false,

	"targetExe": "",

	"useGameMode": false,

	"winePrefix": "/home/metallica/Games/Heroic/Prefixes/Multiversus",

	"wineVersion": {

		"bin": "/home/metallica/.config/heroic/tools/proton/Proton-GE-Proton7-21/proton",

		"name": "Proton - Proton-GE-Proton7-21",

		"type": "proton"

	},

	"eacRuntime": false,

	"battlEyeRuntime": false,

	"gogSaves": []

}

Game launched at: Fri Aug 12 2022 12:51:15 GMT-0400 (hora de Bolivia)

Launch Command: LD_PRELOAD= STEAM_COMPAT_CLIENT_INSTALL_PATH=/home/metallica/.steam/steam STEAM_COMPAT_DATA_PATH=/home/metallica/Games/Heroic/Prefixes/Multiversus PROTON_NO_FSYNC=1 STEAM_COMPAT_APP_ID=0 SteamAppId=0 SteamGameId=heroic-Multiversus PROTON_LOG_DIR=/home/metallica /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary launch 711c5e95dc094ca58e5f16bd48e751d6 --language es  --no-wine --wrapper "'/home/metallica/.config/heroic/tools/proton/Proton-GE-Proton7-21/proton' run"

Game Log:

[cli] INFO: Logging in...

[Core] INFO: Trying to re-use existing login session...

[cli] INFO: Checking for updates...

[Core] INFO: Getting authentication token...

[cli] INFO: Launching 711c5e95dc094ca58e5f16bd48e751d6...

esync: up and running.

wine: RLIMIT_NICE is <= 20, unable to use setpriority safely

[S_API] SteamAPI_Init(): SteamAPI_IsSteamRunning() did not locate a running instance of Steam.

[S_API FAIL] SteamAPI_Init() failed

MESA-INTEL: warning: MESA-INTEL: warning: Performance support disabled, consider sysctl dev.i915.perf_stream_paranoid=0

Performance support disabled, consider sysctl dev.i915.perf_stream_paranoid=0

MESA-INTEL: warning: Performance support disabled, consider sysctl dev.i915.perf_stream_paranoid=0

MESA-INTEL: warning: Performance support disabled, consider sysctl dev.i915.perf_stream_paranoid=0

MESA-INTEL: warning: MESA-INTEL: warning: Performance support disabled, consider sysctl dev.i915.perf_stream_paranoid=0

Performance support disabled, consider sysctl dev.i915.perf_stream_paranoid=0

MESA-INTEL: warning: Performance support disabled, consider sysctl dev.i915.perf_stream_paranoid=0

MESA-INTEL: warning: Performance support disabled, consider sysctl dev.i915.perf_stream_paranoid=0

MESA-INTEL: warning: Performance support disabled, consider sysctl dev.i915.perf_stream_paranoid=0

(wine:4031): GStreamer-WARNING **: 12:51:47.150: Failed to load plugin '/home/metallica/.config/heroic/tools/proton/Proton-GE-Proton7-21/files/lib64/gstreamer-1.0/libgsthls.so': libnettle.so.6: no se puede abrir el fichero del objeto compartido: No existe el fichero o el directorio

(wine:4031): GStreamer-WARNING **: 12:51:47.164: Failed to load plugin '/home/metallica/.config/heroic/tools/proton/Proton-GE-Proton7-21/files/lib64/gstreamer-1.0/libgstvpx.so': libvpx.so.5: no se puede abrir el fichero del objeto compartido: No existe el fichero o el directorio

(wine:4031): GStreamer-WARNING **: 12:51:47.181: Failed to load plugin '/home/metallica/.config/heroic/tools/proton/Proton-GE-Proton7-21/files/lib64/gstreamer-1.0/libgstwebp.so': libwebp.so.6: no se puede abrir el fichero del objeto compartido: No existe el fichero o el directorio

(wine:4031): GStreamer-WARNING **: 12:51:47.236: Failed to load plugin '/home/metallica/.config/heroic/tools/proton/Proton-GE-Proton7-21/files/lib/gstreamer-1.0/libgsthls.so': /home/metallica/.config/heroic/tools/proton/Proton-GE-Proton7-21/files/lib/gstreamer-1.0/libgsthls.so: clase ELF errónea: ELFCLASS32

(wine:4031): GStreamer-WARNING **: 12:51:47.243: Failed to load plugin '/home/metallica/.config/heroic/tools/proton/Proton-GE-Proton7-21/files/lib/gstreamer-1.0/libgstvpx.so': /home/metallica/.config/heroic/tools/proton/Proton-GE-Proton7-21/files/lib/gstreamer-1.0/libgstvpx.so: clase ELF errónea: ELFCLASS32

(wine:4031): GStreamer-WARNING **: 12:51:47.249: Failed to load plugin '/home/metallica/.config/heroic/tools/proton/Proton-GE-Proton7-21/files/lib/gstreamer-1.0/libgstwebp.so': /home/metallica/.config/heroic/tools/proton/Proton-GE-Proton7-21/files/lib/gstreamer-1.0/libgstwebp.so: clase ELF errónea: ELFCLASS32

wine: Read access denied for device L"\\??\\Z:\\", FS volume label and serial are not available.

wine: Read access denied for device L"\\??\\Z:\\", FS volume label and serial are not available.

wine: Read access denied for device L"\\??\\Z:\\", FS volume label and serial are not available.

wine: Read access denied for device L"\\??\\Z:\\", FS volume label and serial are not available.

wine: Read access denied for device L"\\??\\Z:\\", FS volume label and serial are not available.

wine: Read access denied for device L"\\??\\Z:\\", FS volume label and serial are not available.

wine: Read access denied for device L"\\??\\Z:\\", FS volume label and serial are not available.

wine: Read access denied for device L"\\??\\Z:\\", FS volume label and serial are not available.

2022-08-12T12:51:43.124[I]                DllMain.cpp:22   Attached GfeSDK.dll

Response: {"EventsInRequest":16,"EventsQueued":16,"EventsWithUnknownSchema":0,"NoErrors":true}

Submission succeeded!

Batch submission success!

### Steps to reproduce

there are flaws in the representation of some pixels, this error only gives me here, since I tested it on the same computer on steam and everything works correctly.

### Expected behavior

because this happens and how can I solve it?

### System Information

- OS: Kali linux 2022.3
- Heroic Version: 2.4.0

**Comment by arielj** [comment]
I don't think this is a heroic issue, if you need help with the game you can ask on discord instead, this tracker should be for issues with heroic. If eventually we find it's heroic causing this we can reopen it.

Go to discord and check the `linux` support channel
