### ISSUE TITLE
[GOG] Cloud sync does not load for Witcher 3 with proton 7.0

### ISSUE THREAD

**Issue by Nocccer** [Heroic-Games-Launcher/HeroicGamesLauncher#1715]
### Describe the bug

The save path for witcher 3 does not show up and the circle is spinning endless without error report in frontend.

### Add logs
```
(22:24:31) ERROR:   [Backend]:         Error running Wine command: Error: Command failed: "/home/deck/.local/share/Steam/steamapps/common/Proton 7.0/proton" runinprefix reg query "HKCU\Software\Microsoft\Windows\CurrentVersion\Explorer\Shell Folders" /v Personal

Traceback (most recent call last):

  File "/home/deck/.local/share/Steam/steamapps/common/Proton 7.0/proton", line 1422, in <module>

    rc = g_session.run_proc([g_proton.wine_bin] + sys.argv[2:])

  File "/home/deck/.local/share/Steam/steamapps/common/Proton 7.0/proton", line 1353, in run_proc

    return subprocess.call(args, env=local_env, stderr=self.log_file, stdout=self.log_file)

  File "/usr/lib/python3.9/subprocess.py", line 349, in call

    with Popen(*popenargs, **kwargs) as p:

  File "/usr/lib/python3.9/subprocess.py", line 951, in __init__

    self._execute_child(args, executable, preexec_fn, close_fds,

  File "/usr/lib/python3.9/subprocess.py", line 1821, in _execute_child

    raise child_exception_type(errno_num, err_msg, err_filename)

FileNotFoundError: [Errno 2] No such file or directory: '/home/deck/.local/share/Steam/steamapps/common/Proton 7.0/dist/bin/wine'
```

### Steps to reproduce

Select proton 7.0 and try to load sync-save settings.

### Expected behavior

It fetches the path correctly or showing an error in the frontend atleast and let the user select the path afterwards, manually.

### Screenshots

https://user-images.githubusercontent.com/61798668/184440473-71163370-58b7-467b-b56e-df76259dff3b.mp4

### System Information

- OS [e. g. "Ubuntu"]: SteamDeckOS
- Heroic Version [e. g. 2.1.1]: 2.4.0

**Comment by imLinguin** [comment]
Why wine in Proton isn't found is another story.

**Comment by Nocccer** [comment]
I would asume the runinprefix is not compatible with proton.

**Comment by Nocccer** [comment]
What about taking this instead and calling the wine executable in proton?
https://wiki.winehq.org/Regedit

**Comment by imLinguin** [comment]
runinprefix does literally that, runs bundled wine executable instead of wrapping it in `steam.exe` like proton would normally do

**Comment by redromnon** [comment]
It's happening to all GOG games in my library apparently, including the ones that don't support save syncing like OpenTTD (Linux).

**Comment by imLinguin** [comment]
Can't reproduce it sadly, Game: `Tomb Raider: Anniversary` save location: `<?DOCUMENTS?>/Eidos/Tomb Raider - Anniversary`

```
(12:29:59) DEBUG:   [Legendary]:       Running Wine command: "/home/linguin/.local/share/Steam/steamapps/common/Proton 7.0/proton" runinprefix reg query "HKCU\Software\Microsoft\Windows\CurrentVersion\Explorer\Shell Folders" /v Personal
(12:30:02) DEBUG:   [Legendary]:       Ran Wine command: "/home/linguin/.local/share/Steam/steamapps/common/Proton 7.0/proton" runinprefix reg query "HKCU\Software\Microsoft\Windows\CurrentVersion\Explorer\Shell Folders" /v Personal
(12:30:02) DEBUG:   [Legendary]:       Running Wine command: "/home/linguin/.local/share/Steam/steamapps/common/Proton 7.0/proton" runinprefix cmd /c winepath "C:\users\steamuser\Documents/Eidos/Tomb Raider - Anniversary"
(12:30:05) DEBUG:   [Legendary]:       Ran Wine command: "/home/linguin/.local/share/Steam/steamapps/common/Proton 7.0/proton" runinprefix cmd /c winepath "C:\users\steamuser\Documents/Eidos/Tomb Raider - Anniversary"
```

**Comment by imLinguin** [comment]
could this be somehow caused by flatpak and it's permissions?

**Comment by redromnon** [comment]
I've created a separate issue #1721 for it instead. Doesn't fit here.

**Comment by Nocccer** [comment]
Not a flatpak porblem. Works on my pc. I need to test on steam deck then.
