### ISSUE TITLE
[Bug] Save Sync option shows up via Game Settings for GOG games that don't support it

### ISSUE THREAD

**Issue by redromnon** [Heroic-Games-Launcher/HeroicGamesLauncher#1721]
### Describe the bug

If _Game Settings_ is directly clicked for GOG games, the _Save Sync_ option gets displayed for games that don't even support cloud save syncing.

However, this is not the case if the green _Settings_ button is clicked on the Game Page.

### Add logs

None that convey this error.

### Steps to reproduce

1. Click on any GOG game
2. Click on Game Settings in the left bar
3. See Save Sync option

### Expected behavior

The Save Sync option should not be present for such games.

### Screenshots

I've uploaded a video instead

https://user-images.githubusercontent.com/74495920/184494702-5e047dbc-27f5-483d-9cc5-0d8b751fbe9b.mp4

.

### System Information

- OS : Pop OS 22.04 LTS 
- Heroic Version : v2.4.0 .deb

### Additional information

None.

**Comment by Nocccer** [comment]
I think this is another issue besides #1715

**Comment by redromnon** [comment]
Yeah, this also means those Wine options too.

**Comment by Nocccer** [comment]
If you want you can fix this. Should be not that hard and only a frontend problem.
