### ISSUE TITLE
[Linux Flatpak] Duplicate AppIndicators on gnome

### ISSUE THREAD

**Issue by jumpers775** [Heroic-Games-Launcher/HeroicGamesLauncher#1722]
### Describe the bug

on gnome when using the flatpak version of this app and the "AppIndicator and KStatusNotifierItem Support" extension there are duplicate icons in the top bar. occasionally only one icon will appear, but it looks very out of place (it is the icon not pressed in my screenshot, however you can observe for yourself)

### Add logs

(21:23:37) INFO:    [Legendary]:       Running command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary --version
(21:23:38) INFO:    [Legendary]:       Legendary location: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary
(21:23:38) INFO:    [Gog]:             GOGDL location: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl
(21:23:38) INFO:    [Backend]:         

Heroic Version: 2.4.0 Chopper
Legendary Version:  0.20.27 Dark Energy (hotfix)
OS: Freedesktop.org KERNEL: 5.18.16-200.fc36.x86_64 ARCH: x64
CPU: AMD Ryzen 9 3900X 12-Core Processor @3.8 GOVERNOR: schedutil
RAM: Total: 31.25 GiB Available: 25.66 GiB
GRAPHICS: GPU0: Device 73bf VRAM: 1MB DRIVER:  
PROTOCOL: wayland

(21:23:38) WARNING: [Backend]:         Failed to register protocol with OS.
(21:23:38) INFO:    [Backend]:         AreWeAntiCheatYet data downloaded
(21:23:38) INFO:    [Frontend]:        Refreshing Library
(21:23:38) INFO:    [Legendary]:       Refreshing library...
(21:23:38) INFO:    [Legendary]:       Refreshing Epic Games...
(21:23:39) INFO:    [Legendary]:       Running command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary list
(21:23:40) INFO:    [Legendary]:       Updating game list
(21:23:40) INFO:    [Legendary]:       Game List Updated
(21:23:40) INFO:    [Legendary]:       Checking for game updates.
(21:23:40) INFO:    [Legendary]:       Running command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary list-installed --check-updates --tsv
(21:23:40) INFO:    [Legendary]:       Found 0 game(s) to update
(21:23:40) INFO:    [Gog]:             Found 0 game(s) to update
(21:23:41) INFO:    [Backend]:         Downloaded Winetricks

### Steps to reproduce

1. install his app via flatpak
2. install gnome
3. install the  "AppIndicator and KStatusNotifierItem Support" extension
4. observe issue

### Expected behavior

there should be one icon

### Screenshots

![image](https://user-images.githubusercontent.com/78500318/184518581-fb623167-eba8-48a0-afa8-2d943f463626.png)

### System Information

- Fedora 36 Linux (this is distro agnostic however)
- 2.4.0

**Comment by Nocccer** [comment]
I don't see a easy way how we could handle that via electron:
https://www.electronjs.org/de/docs/latest/api/tray#new-trayimage-guid

**Comment by ludg1e** [comment]
Fedora Silverblue 36 user, i'm using "Tray Icons: Reloaded" extension, and it works well heroic's tray icon, just one as expected (heroic flatpak 2.4.0)
![image](https://user-images.githubusercontent.com/77110723/186279862-1e5039d2-0f89-43b2-bdf3-b708d1a6aa59.png)

**Comment by flavioislima** [comment]
I also tried a clean install and cannot replicate the issue. gnome by default does not have support for tray icons.
Unfortunately, we cannot support all combinations of Systems, extensions, DEs, etc.
I would try another extension or talk with the developers of this one.

**Comment by Nocccer** [comment]
I can reproduce it, but i don't see a way to hide it. Electron does not over such thing.
