### ISSUE TITLE
Detect and show legendary config

### ISSUE THREAD

**Issue by arielj** [Heroic-Games-Launcher/HeroicGamesLauncher#1724]
### Problem description

Users can configure legendary through the config.ini file https://github.com/derrod/legendary#config-file. When we show game logs (or game settings), we have no visibility if there was any change made on that file (maybe by following an internet guide or any other reason).

Legendary can also configure defaults to be applied to all games for example.

### Feature description

In the logs, we could check if there's any configuration for a given game (or the defaults) and also include it if present.

### Additional information

I know it's not a common case but I think it should be important to consider eventually, certainly not a priority but adding it here so we don't lose track of this.

**Comment by flavioislima** [comment]
Rodney also added the ability to use a custom config. We could create one and use it to avoid conflicts in case someone is using legendary alone as well.

**Comment by flavioislima** [comment]
@arielj 
don't you think adding a button to open legendary config file would be enough? I think adding more settings inside Heroic is an overkill for such an edge case.

**Comment by arielj** [comment]
I don't think adding new settings is needed, I think adding that game's settings in the logs might be useful

I guess adding a button to open legendary's config file is useful but would address this issue.

The concern is that people may follow some guide on the internet that makes them change the legendary config files (we also have suggested that to some users for things we don't yet do in heroic) and if they report an error in Heroic we have no visibility if there's any legendary config for that game that is getting applied at the same time as heroic's, that's why I imagine at least printing those settings in the log for visibility could work.

**Comment by arielj** [comment]
Solved in https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/pull/1918
