### ISSUE TITLE
Trying to update latest version

### ISSUE THREAD

**Issue by lazzer2000** [Heroic-Games-Launcher/HeroicGamesLauncher#1746]
On the steam deck I have an installation of cyberpunk 2077 that heroic says is version 1.52 (which is the latest.) But it says there is an update and won't let me launch. If I try to update the game it never gets past 0%>

**Comment by redromnon** [comment]
Can you check if _Tools->Verify and Repair_ works for you?

**Comment by lazzer2000** [comment]
that did not but I tried letting it "Update" again after the latest update to the application (Heroic) and it now no longer says there is an update.

**Comment by flavioislima** [comment]
Sometimes it is a caching issue, so erasing the Heroic cache should work. It fixes most of the issues especially in between heroic updates where we can add new fields or features so can generate some conflicts.

Maybe we should find a way of automatically cleaning up the cache after an update.

**Comment by Nocccer** [comment]
We could store the version and on each startup we check if the current version is newer than the stored one. Clearing cache and store the current version.

**Comment by flavioislima** [comment]
yes, that would do it.
