### ISSUE TITLE
A uncaught exception occured: TypeError: Cannot read properties of null (reading &#39;download_size&#39;)

### ISSUE THREAD

**Issue by devcycode** [Heroic-Games-Launcher/HeroicGamesLauncher#1748]
### Describe the bug

A uncaught exception occured: TypeError: Cannot read properties of null (reading &#39;download_size&#39;)

![image](https://user-images.githubusercontent.com/105976080/186715525-09cdc4df-05cd-482e-835f-d8a33a5ada84.png)

### Add logs

A uncaught exception occured: TypeError: Cannot read properties of null (reading &#39;download_size&#39;)
![Uploading image.png…]()

### Steps to reproduce

2. Click on '...'
3. Scroll down to '...'

### Expected behavior

A uncaught exception occured: TypeError: Cannot read properties of null (reading &#39;download_size&#39;)

![Uploading image.png…]()

### Screenshots

A uncaught exception occured: TypeError: Cannot read properties of null (reading &#39;download_size&#39;)
![Uploading image.png…]()

### System Information

- OS [e. g. "Ubuntu"]:  MAC
- Heroic Version [e. g. 2.1.1]: 2.4.0

**Comment by Nocccer** [comment]
Somehow this only occurs on mac. To solve this just clear heroic cache via general settings. I think tab advanced or others.
