### ISSUE TITLE
Save sync for GOG Witcher 3 GOTY edition fails to load

### ISSUE THREAD

**Issue by aifreedom** [Heroic-Games-Launcher/HeroicGamesLauncher#1749]
### Describe the bug

When open the save sync tab for Witcher 3 GOTY edition, the page keeps loading and the spinner doesn’t stop. However, for the ordinary GOG Witcher 3 title, the save sync tab works fine. 

I wonder if it’s because these two games share the saves and the heroic game launcher couldn’t handle the special case.

### Add logs

I didn’t get the log before I uninstalled the game. Let me know if you need this for debugging.

### Steps to reproduce

1. Go to Save Sync tab for the Witcher 3 GOTY edition from GOG store
2. See the page shows a loading indicator that doesn’t stop

### Expected behavior

It shows the save sync options correctly

### System Information

- OS [e. g. "Ubuntu"]: Steam OS
- Heroic Version [e. g. 2.1.1]: 2.4.0

**Comment by ElGranMachete** [comment]
I am having the exact same issue! I only have GOTY version installed

**Comment by imLinguin** [comment]
Well, without the log we really can't tell much, share the global Heroic log. Settings > Log.

**Comment by imLinguin** [comment]
Possibly related #1715

**Comment by flavioislima** [comment]
@aifreedom 
are you using Proton? I noticed this behavior sometimes, depending on the game, when using Proton. With Wine-ge it works fine.

**Comment by aifreedom** [comment]
@flavioislima I was. After switching to wine-ge, it works fine for me now.

I'm sorry that I couldn't repro the bug any more and don't have logs that shows the bug.

**Comment by CommandMC** [comment]
This should be fixed with #1887
