### ISSUE TITLE
Can't sync installed with epic games if path includes spaces

### ISSUE THREAD

**Issue by sikora77** [Heroic-Games-Launcher/HeroicGamesLauncher#1750]
### Describe the bug

I can't sync installed with epic games.

### Add logs

(15:37:50) ERROR:   [Legendary]:       Error: Command failed: C:\Users\Name Lastname\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\legendary egl-sync --enable-sync -y
'C:\Users\Name' is not recognized as an internal or external command,

operable program or batch file.

### Steps to reproduce

1. Have Windows username contain a space
2. Try to "sync with installed epic games"

### Expected behavior

Should sync installed games from directory

### System Information

- OS : Windows 10 
- Heroic Version: 2.4.0

### Additional information

Running the command in that errored in a separate terminal with quotation marks around the path worked

**Comment by flavioislima** [comment]
@sikora77 
can you check if it is happening with latest heroic 2.4.3?

**Comment by sikora77** [comment]
Works now
