### ISSUE TITLE
Sync save not working if save path contains single quotation mark

### ISSUE THREAD

**Issue by RikudouSage** [Heroic-Games-Launcher/HeroicGamesLauncher#1765]
### Describe the bug

Basically what the title says. Encountered this on Steam Deck while trying to sync Marvel's Spider-Man Remastered which has a save path of `%USERPROFILE%\Documents\Marvel's Spider-Man Remastered\<user-id>`.

The path gets rewritten without the quotation mark so it becomes `%USERPROFILE%\Documents\Marvels Spider-Man Remastered\<user-id>`.

### Add logs

Not applicable.

### Steps to reproduce

1. Sync a game which has quotation mark in the save path (for example Marvel's Spider-Man Remastered on Epic Games)
2. Observe error
3. A wrong folder (without the quotation mark) with synchronized saves gets created

### Expected behavior

The saves get synced.

### System Information

- OS: SteamOS
- Heroic Version: 2.4.1

**Comment by redromnon** [comment]
Can you please update to the current latest v2.4.3 and check again?

**Comment by RikudouSage** [comment]
Save sync settings don't load at all for me now.

**Comment by CommandMC** [comment]
We've now offloaded Save Path computation to Legendary, which should make it more robust & get rid of, for example, this error.
@RikudouSage Could you check again with 2.5.0?

**Comment by arielj** [comment]
closing this since there's no answer since nov 2022

I'll assume it's working now, it can be reopened if it still fails
