### ISSUE TITLE
debian packages need desktop-file-utils as dependency

### ISSUE THREAD

**Issue by mancausoft** [Heroic-Games-Launcher/HeroicGamesLauncher#1766]
### Describe the bug

when install it i receive the error:
/var/lib/dpkg/info/heroic.postinst: line 10: update-desktop-database: command not found

i had to install package desktop-file-utils

### Add logs

npacking heroic (2.4.1) ...
Setting up gawk (1:5.1.0-1) ...
Setting up curl (7.84.0-2) ...
Setting up heroic (2.4.1) ...
/var/lib/dpkg/info/heroic.postinst: line 10: update-desktop-database: command not found

### Steps to reproduce

1. Run bash <(wget -qO- https://raw.githubusercontent.com/Heroic-Games-Launcher/HeroicGamesLauncher/main/rauldipeas.sh)
in a fresh debian (withouth e desktop-file-utils package installed)

### Expected behavior

install without error

### System Information

- OS: Debian

**Comment by Nocccer** [comment]
Never saw this shell script. Did you install the .deb package from here (https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/releases/tag/v2.4.2)?

Never had problems with the .deb package. I would say your script or link is third party and not our problem. Also we can't provide all dependencies.
