### ISSUE TITLE
Steam Deck - Only Proton 7.0 Works when using Wine Versions associated with Steam for all games

### ISSUE THREAD

**Issue by jamaalsawyerd** [Heroic-Games-Launcher/HeroicGamesLauncher#1767]
### Describe the bug

No version of Proton installed will work besides Proton 7.0 with any variety of settings (use Steam runtime etc) on Steam Deck with latest version of Heroic.

All other versions lead to the following error:
![Screen Shot 2022-09-01 at 5 20 57 PM](https://user-images.githubusercontent.com/1755430/188019350-5f61fba0-4cf4-44a8-9f45-9e8b7736d4e2.jpg)

I know that there is a warning in the logs about using Proton. However, I am raising this because it is global for all games and I remember using GE-Proton7-2x for Ghostrunner with Heroic just fine a month ago.

### Add logs

(17:50:31) INFO:    [Legendary]:       Running command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary --version
(17:50:32) INFO:    [Legendary]:       Legendary location: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary
(17:50:32) INFO:    [Gog]:             GOGDL location: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl
(17:50:32) INFO:    [Backend]:         

Heroic Version: 2.4.2 Chopper
Legendary Version:  0.20.28 Dark Energy (hotfix #2)
OS: Freedesktop.org KERNEL: 5.13.0-valve21.1-1-neptune-02211-gc54cda5a36f3 ARCH: x64
CPU: AMD Custom APU 0405 @2.21 GOVERNOR: schedutil
RAM: Total: 14.49 GiB Available: 12.64 GiB
GRAPHICS: GPU0: Device 163f VRAM: 512MB DRIVER:  
PROTOCOL: x11

(17:50:32) INFO:    [Gog]:             Getting data about the user
(17:50:32) WARNING: [Backend]:         Failed to register protocol with OS.
(17:50:32) INFO:    [Backend]:         AreWeAntiCheatYet data downloaded
(17:50:32) INFO:    [Gog]:             Saved user data to config
(17:50:33) INFO:    [Frontend]:        Refreshing Library
(17:50:33) INFO:    [Legendary]:       Refreshing library...
(17:50:33) INFO:    [Legendary]:       Refreshing Epic Games...
(17:50:33) INFO:    [Gog]:             Getting GOG library
(17:50:33) INFO:    [Legendary]:       Running command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary list
(17:50:34) INFO:    [Gog]:             Number of library pages: 2
(17:50:34) INFO:    [Gog]:             Getting data for page 2
(17:50:35) INFO:    [Legendary]:       Updating game list
(17:50:35) INFO:    [Legendary]:       Game List Updated
(17:50:35) INFO:    [Gog]:             Saved games data
(17:50:35) INFO:    [Backend]:         Downloaded Winetricks
(17:50:35) INFO:    [Legendary]:       Checking for game updates.
(17:50:35) INFO:    [Legendary]:       Running command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary list-installed --check-updates --tsv
(17:50:36) INFO:    [Legendary]:       Found 0 game(s) to update
(17:50:36) INFO:    [Gog]:             Found 0 game(s) to update
(17:50:36) INFO:    [Frontend]:        Force Update
(17:50:39) INFO:    [Backend]:         Launching Absolute Drift (1136126792)
(17:50:39) INFO:    [Backend]:         Preventing display from sleep
(17:50:39) INFO:    [Legendary]:       Running command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary --version
(17:50:40) WARNING: [Backend]:         You are using Proton, this can lead to some bugs. Please do not open issues with bugs related to games
(17:50:40) INFO:    [Gog]:             Launching Absolute Drift: STEAM_COMPAT_CLIENT_INSTALL_PATH=/home/deck/.var/app/com.heroicgameslauncher.hgl/.steam/steam STEAM_COMPAT_DATA_PATH="/home/deck/Games/Heroic/Prefixes/Absolute Drift" PROTON_NO_ESYNC=1 PROTON_NO_FSYNC=1 STEAM_COMPAT_APP_ID=0 SteamAppId=0 SteamGameId="heroic-Absolute Drift" PROTON_LOG_DIR=/home/deck/.var/app/com.heroicgameslauncher.hgl /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl launch "/home/deck/Games/Heroic/Absolute Drift" 1136126792 --no-wine --wrapper "/home/deck/.local/share/Steam/steamapps/common/SteamLinuxRuntime_soldier/run -- '/home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/tools/proton/Proton-GE-Proton7-30/proton' waitforexitandrun" --os windows
(17:50:47) INFO:    [Backend]:         Stopping Display Power Saver Blocker
(17:50:47) INFO:    [Frontend]:        Refreshing Library
(17:50:47) INFO:    [Gog]:             Getting GOG library
(17:50:47) INFO:    [Gog]:             Number of library pages: 2
(17:50:47) INFO:    [Gog]:             Getting data for page 2
(17:50:49) INFO:    [Gog]:             Saved games data
(17:50:49) INFO:    [Gog]:             Found 0 game(s) to update

### Steps to reproduce

**To reproduce:**
(not sure if first step is necessary but I wanted to be super sure)
- Start with Steam Deck desktop and totally remove Heroic flatpak (including all leftover data after uninstall from machine)
- Make sure that you have Proton Experimental or some other variant besides the standard 7.x in Steam by forcing compatibility at least once with any game.
- Install Heroic flatpak from Discover and sign in to Epic or GOG
- (Optional) Install GE-Proton with either ProtonUp-Qt or Wine Manager as further demo
- Note that no version of Proton installed will work besides Proton 7.0 with any variety of settings (use Steam runtime etc)

### Expected behavior

The games should start up and run.

### Screenshots

All other versions lead to the following error:
![Screen Shot 2022-09-01 at 5 20 57 PM](https://user-images.githubusercontent.com/1755430/188019350-5f61fba0-4cf4-44a8-9f45-9e8b7736d4e2.jpg)

### System Information

- **Heroic Version**: 2.4.2
- **Device:** Steam Deck tested on latest Beta/Stable and Stable/Stable as of September 1st

**Comment by Etaash-mathamsetty** [comment]
this is caused by flatpak still using mesa 21 (which only proton 7.0 is able to use) and not mesa 22. This was fixed today with the release of flatpak's platform runtime 22.08 releasing with mesa 22.

**Comment by jamaalsawyerd** [comment]
Ok. So I guess we just have to wait...

@Etaash-mathamsetty I'm curious, why did it work before and now doesn't? Is it a Proton update that now requires mesa 22, presumably?

**Comment by Etaash-mathamsetty** [comment]
> Ok. So I guess we just have to wait...
> 
> @Etaash-mathamsetty I'm curious, why did it work before and now doesn't? Is it a Proton update that now requires mesa 22, presumably?

yes that's right
dvxk and vkd3d (latest from the master branch) both require mesa 22 or higher to work

**Comment by jamaalsawyerd** [comment]
why does everything have to be so complicated? 😄

**Comment by bestlinuxgamers** [comment]
I had the same problem on my laptop with an amd igpu (mesa).
For me, it helped to use GE-Proton-7-26 (generally anything above 26 does not work).
Strangely enough, GE-Proton versions above 26 work on my Pc with an Nvidia GPU.

**Comment by Etaash-mathamsetty** [comment]
> I had the same problem on my laptop with an amd igpu (mesa). For me, it helped to use GE-Proton-7-26 (generally anything above 26 does not work). Strangely enough, GE-Proton versions above 26 work on my Pc with an Nvidia GPU.

that's because nvidia doesn't have this problem and use their own drivers

**Comment by Nocccer** [comment]
This is because heroic does not ship the mesa driver new proton or proton-ge expect.

Also proton and proton-ge is only siggest for steam games only. We suggest wine-ge from our wine-manager with dxvk and vkd3d enabled (gamesettings > wine extensions)

**Comment by jamaalsawyerd** [comment]
This works now with the new flatpak!
