### ISSUE TITLE
Loaded in memory, but no window at all

### ISSUE THREAD

**Issue by RafaelLinux** [Heroic-Games-Launcher/HeroicGamesLauncher#1773]
### Describe the bug

I launch 2.4.2 version. It seems load fine, but nothing happens. I use task monitor to see what's happening. Heroic.AppImage is loaded, and about 6 "heroic" threads are loaded too, but no window of Heroic.

### Add logs

No window, so can't access "log" tab. Terminal output is:

`(22:07:25) INFO:    [Legendary]:       Running command: /tmp/.mount_HeroicT85fv5/resources/app.asar.unpacked/build/bin/linux/legendary --version
(node:21287) UnhandledPromiseRejectionWarning: TypeError: Cannot read properties of undefined (reading 'replaceAll')
    at getLegendaryVersion (/tmp/.mount_HeroicT85fv5/resources/app.asar/build/utils.js:186:9)
    at async getSystemInfo (/tmp/.mount_HeroicT85fv5/resources/app.asar/build/utils.js:247:30)
    at async /tmp/.mount_HeroicT85fv5/resources/app.asar/build/main.js:241:28
(Use `heroic --trace-warnings ...` to show where the warning was created)
(node:21287) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
[21335:0902/220725.702874:ERROR:vaapi_wrapper.cc(1145)] vaQuerySurfaceAttributes failed, VA error: invalid parameter
[21335:0902/220725.703108:ERROR:vaapi_wrapper.cc(1092)] FillProfileInfo_Locked failed for va_profile VAProfileH264Main and entrypoint VAEntrypointVLD
[21335:0902/220725.703263:ERROR:vaapi_wrapper.cc(1145)] vaQuerySurfaceAttributes failed, VA error: invalid parameter
[21335:0902/220725.703375:ERROR:vaapi_wrapper.cc(1092)] FillProfileInfo_Locked failed for va_profile VAProfileH264High and entrypoint VAEntrypointVLD
[21335:0902/220725.743927:ERROR:gpu_memory_buffer_support_x11.cc(44)] dri3 extension not supported.
[21287:0902/220730.852686:ERROR:nss_util.cc(349)] After loading Root Certs, loaded==false: NSS error code: -8018

`

### Steps to reproduce

1. ./Heroic.AppImage

### Expected behavior

To show Heroic window

### System Information

- Operating System: openSUSE Tumbleweed 20220719
- KDE Plasma Version: 5.25.3
- KDE Frameworks Version: 5.96.0
- Qt Version: 5.15.5
- Kernel Version: 5.18.11-1-default (64-bit)
- Graphics Platform: X11
- Processors: 4 × Intel® Core™ i5-6600K CPU @ 3.50GHz
- Memory: 31.3 GiB of RAM
- Graphics Processor: NVIDIA GeForce GTX 1050 Ti/PCIe/SSE2

**Comment by arielj** [comment]
Can you run this `/tmp/.mount_HeroicT85fv5/resources/app.asar.unpacked/build/bin/linux/legendary --version` manually and share the output? the path may change since it's in /tmp, but it's the first part in the log where it says `Running command: ....`

**Comment by RafaelLinux** [comment]
I'm sorry, was not able to found that file till I guessed I must do it while Heroic is loaded. This is the output:
`
/tmp/.mount_HeroicIvxaGU/resources/app.asar.unpacked/build/bin/linux/legendary: error while loading shared libraries: libz.so.1: failed to map segment from shared object

`

**Comment by flavioislima** [comment]
@RafaelLinux this might be related with OpenSuse using latest version of glibc and they are doing that all the time and it always breaks Heroic, this is probably the third or fourth time this happens so thats why we don't officially support openSuse. 
If you are still having this issue I recomend using the flatpak version or going to our discord for help.

**Comment by RafaelLinux** [comment]
That can be true, but only with Tumbleweed version, cause it's a rolling release. I think maybe you can support LTC versions of openSUSE (15.4 is the latest). For Tumbleweed users, I only can tell them that Bottles works, letting install Epic official launcher (but I'm sure it will be slower than using Heroic  ).

thank you
