### ISSUE TITLE
Can't Install games from EPIC

### ISSUE THREAD

**Issue by FrancescoGrazioso** [Heroic-Games-Launcher/HeroicGamesLauncher#1789]
### Describe the bug

After the login on my Epic Games account, trying to download Cyberpunk 2077, the error in the attachment appear twice, one alert over the other, preventing the installation

![image](https://user-images.githubusercontent.com/40018163/189172017-8dfc482d-bf96-4fc7-9e9b-461aeb90b58a.png)

### Add logs

(18:08:39) INFO:    [Legendary]:       Running command: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary --version
(18:08:39) INFO:    [Legendary]:       Legendary location: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary
(18:08:39) INFO:    [Gog]:             GOGDL location: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl
(18:08:39) INFO:    [Backend]:         

Heroic Version: 2.4.2 Chopper
Legendary Version:  0.20.28 Dark Energy (hotfix #2)
OS: Zorin KERNEL: 5.15.0-46-generic ARCH: x64
CPU: AMD Ryzen 7 3700X 8-Core Processor @3.6 GOVERNOR: ondemand
RAM: Total: 31.27 GiB Available: 26.2 GiB
GRAPHICS: GPU0: NVIDIA GeForce RTX 3070 VRAM: 8192MB DRIVER: 510.85.02 
PROTOCOL: x11

(18:08:39) WARNING: [Backend]:         Protocol already registered.
(18:08:40) INFO:    [Backend]:         Checking for new Heroic Updates
(18:08:40) INFO:    [Frontend]:        Refreshing Library
(18:08:40) INFO:    [Legendary]:       Refreshing library...
(18:08:40) INFO:    [Legendary]:       Refreshing Epic Games...
(18:08:40) INFO:    [Backend]:         AreWeAntiCheatYet data downloaded
(18:08:41) INFO:    [Legendary]:       Running command: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary list
(18:08:43) INFO:    [Backend]:         Downloaded Winetricks
(18:08:43) INFO:    [Legendary]:       Updating game list
(18:08:43) INFO:    [Legendary]:       Game List Updated
(18:08:45) INFO:    [Legendary]:       Checking for game updates.
(18:08:45) INFO:    [Legendary]:       Running command: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary list-installed --check-updates --tsv
(18:08:46) INFO:    [Legendary]:       Found 0 game(s) to update
(18:08:46) INFO:    [Gog]:             Found 0 game(s) to update
(18:10:27) INFO:    [Legendary]:       Getting more details with 'legendary info'
(18:10:27) INFO:    [Legendary]:       Getting more details with 'legendary info'
(18:10:27) DEBUG:   [Backend]:         {"free":1606570401792,"diskSize":1967317549056,"message":"1.46 TiB / 1.79 TiB","validPath":true}
(18:10:27) DEBUG:   [Backend]:         {"free":1606569910272,"diskSize":1967317549056,"message":"1.46 TiB / 1.79 TiB","validPath":true}
(18:10:28) INFO:    [Legendary]:       Running command: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary --pretty-json info Ginger --platform Windows --json
(18:10:28) INFO:    [Legendary]:       Running command: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary --pretty-json info Ginger --platform Windows --json
(18:10:33) ERROR:   [Backend]:         SyntaxError: Unexpected end of JSON input
(18:10:36) ERROR:   [Backend]:         SyntaxError: Unexpected end of JSON input

### Steps to reproduce

1. Go to 'Library section'
2. Click on 'Download icon from the library menu'

### Expected behavior

The installation should start and complete

### Screenshots

![image](https://user-images.githubusercontent.com/40018163/189172367-4b36db11-0eaa-40a7-b13f-b8697e7b7766.png)

### System Information

- OS Zorin OS 16.1
- Heroic Version 2.4.2

**Comment by Espionage724** [comment]
Ran into this as well a bit ago. You can use the legendary executable [from this artifact](https://github.com/derrod/legendary/actions/runs/3014652272) for a quick fix

**Comment by flavioislima** [comment]
Or  doing the workaround bellow as well:
open the legendary config file:
`UserHome/.config/legendary/config.ini` (this .config folder is normally hidden)
In the [Legendary] Section add:
`preferred_cdn = http://epicgames-download1.akamaized.net`

That should fix it for now.

**Comment by FrancescoGrazioso** [comment]
Nope, still having the same error, here's the config file as it is right now 

`; Disables the automatic update check
disable_update_check = false
; Disables the notice about an available update on exit
disable_update_notice = false
; Fix to allow game installation
preferred_cdn = http://epicgames-download1.akamaized.net
`

**Comment by derrod** [comment]
Yep, that was my mistake, I thought preferred_cdn applied to that but it's only for the download itself. Alas that means currently the only way with stock legendary is to try over and over again :X

**Comment by flavioislima** [comment]
@FrancescoGrazioso So download the legendary binary from the comment above, and make it executable if you are on Linux.
Go to Heroic > Settings > Advanced > Alternative Legendary binary and select it.

We are accessing the situation to see if a new Heroic hotfix is needed right now. But probably will.

**Comment by Mcfly2340** [comment]
Sorry to be such a pain, but I don't really understand your instructions. Also not that experienced with Linux. What comment are you referring to? And what do you mean with making it executable? (.ini file extension?)

**Comment by paulr24** [comment]
> Sorry to be such a pain, but I don't really understand your instructions. Also not that experienced with Linux. What comment are you referring to? And what do you mean with making it executable? (.ini file extension?)

Took me a moment too but do the following:

- Go here: https://github.com/derrod/legendary/actions/runs/3014652272
- Download the artifact "Linux-package"
- A zip file will download, extract the "legendary" file anywhere you like
- Go to Heroic > Settings > Advanced > Alternative Legendary binary and select the "legendary" file

The first time I selected the file it gave an error, then I tried the same with the other listed artifacts just to see what would happen... Eventually I tried the original file again and it took, and I was just able to install a game.

**Comment by Mcfly2340** [comment]
> 
> 
> 
> > Sorry to be such a pain, but I don't really understand your instructions. Also not that experienced with Linux. What comment are you referring to? And what do you mean with making it executable? (.ini file extension?)
> 
> Took me a moment too but do the following:
> 
> - Go here: https://github.com/derrod/legendary/actions/runs/3014652272
> - Download the artifact "Linux-package"
> - A zip file will download, extract the "legendary" file anywhere you like
> - Go to Heroic > Settings > Advanced > Alternative Legendary binary and select the "legendary" file
> 
> The first time I selected the file it gave an error, then I tried the same with the other listed artifacts just to see what would happen... Eventually I tried the original file again and it took, and I was just able to install a game.

Thanks for this, got it working now!

**Comment by Lubo90** [comment]
> Ran into this as well a bit ago. You can use the legendary executable [from this artifact](https://github.com/derrod/legendary/actions/runs/3014652272) for a quick fix

This workaround made it possible to download games. Thanks a lot!

**Comment by RavenLiquid** [comment]
> > Sorry to be such a pain, but I don't really understand your instructions. Also not that experienced with Linux. What comment are you referring to? And what do you mean with making it executable? (.ini file extension?)
> 
> Took me a moment too but do the following:
> 
> * Go here: https://github.com/derrod/legendary/actions/runs/3014652272
> * Download the artifact "Linux-package"
> * A zip file will download, extract the "legendary" file anywhere you like
> * Go to Heroic > Settings > Advanced > Alternative Legendary binary and select the "legendary" file
> 
> The first time I selected the file it gave an error, then I tried the same with the other listed artifacts just to see what would happen... Eventually I tried the original file again and it took, and I was just able to install a game.

Did you mark the extracted legendary file as executable? You didn't list that step and might be your issue.

For anyone not logged in to github, the artifacts are not click able/download able if your not logged in. Took me a while to notice.

**Comment by Smirlockius** [comment]
This set of fixes (paulr24 & RavenLiquid) worked for me (Linux Mint Flatpak original install, but first updated to hotfix from last week and then followed above). Much appreciated!

**Comment by auras** [comment]
I can't select a different file from the steam deck. What's the format expected in config.json? I wrote the full path to the file:

```
{
  "defaultSettings": {
    "altLegendaryBin": "/home/deck/legendary",
```

But when opening the heroic UI and going to Settings -> Advanced I get this error popup:

`Error running command "home/deck/legendary --version": Error: spawn ./legendary ENOENT`

**Comment by flavioislima** [comment]
We will release a hotfix tomorrow with that and more fixes.

**Comment by Marevilioso** [comment]
> > Sorry to be such a pain, but I don't really understand your instructions. Also not that experienced with Linux. What comment are you referring to? And what do you mean with making it executable? (.ini file extension?)
> 
> Took me a moment too but do the following:
> 
> * Go here: https://github.com/derrod/legendary/actions/runs/3014652272
> * Download the artifact "Linux-package"
> * A zip file will download, extract the "legendary" file anywhere you like
> * Go to Heroic > Settings > Advanced > Alternative Legendary binary and select the "legendary" file
> 
> The first time I selected the file it gave an error, then I tried the same with the other listed artifacts just to see what would happen... Eventually I tried the original file again and it took, and I was just able to install a game.

This doesn't work anymore. The artifacts have expired.

**Comment by flavioislima** [comment]
@Marevilioso just install latest heroic version.

**Comment by Marevilioso** [comment]
> @Marevilioso just install latest heroic version.

I did. Same issue. Nothing working. 😞

**Comment by flavioislima** [comment]
> > @Marevilioso just install latest heroic version.
> 
> I did. Same issue. Nothing working. 😞

then you have another issue, probably your system is not supported or you are missing some library.
If your system is on the list of Supported Operating Systems on Github README then you can open a new issue here attaching all information that is requested on the Issue. 
If it is not supported you can still go try some help on our Discord Community.

**Comment by CauanHenrique** [comment]
I dont know if it helps bu i had a simillar issue with "cannot get game info" 
And to solve it i only had to log out and in from my epic account.

**Comment by RavenMacDaddy** [comment]
> I dont know if it helps bu i had a simillar issue with "cannot get game info" And to solve it i only had to log out and in from my epic account.

Confirmed that this is a temporary workaround, but this needs a long-term fix so that it's not necessary for every single update to the app.

For reference, I personally have this installed through [Scoop](https://scoop.sh/), so it downloads the new version and then symlinks the contents to a folder called 'current' for easy shortcut management (i.e., what's added to the Start menu automatically doesn't have to be updated every time an app is updated) – but that's really it.

No files are persisted or anything, which would risk old configuration data corrupting the app's operation if the functionality is modified with newer versions.
