### ISSUE TITLE
Since the epic games hotfix installation of new games broken

### ISSUE THREAD

**Issue by coke0108** [Heroic-Games-Launcher/HeroicGamesLauncher#1790]
### Describe the bug

Installation of new epic games broken.  Empty popup appears. the main window shows error message "cannot get game info"
Gog installation works flawless.

### Add logs

 
(21:30:35) INFO:    [Legendary]:       Running command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary --version
(21:30:36) INFO:    [Legendary]:       Legendary location: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary
(21:30:36) INFO:    [Gog]:             GOGDL location: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl
(21:30:36) INFO:    [Backend]:

Heroic Version: 2.4.2 Chopper
Legendary Version:  0.20.28 Dark Energy (hotfix #2)
OS: Freedesktop.org KERNEL: 5.13.0-valve21.1-1-neptune-02211-gc54cda5a36f3 ARCH: x64
CPU: AMD Custom APU 0405 @1.82 GOVERNOR: schedutil
RAM: Total: 14.49 GiB Available: 11.83 GiB
GRAPHICS: GPU0: Device 163f VRAM: 512MB DRIVER:
PROTOCOL: x11

(21:30:36) INFO:    [Gog]:             Getting data about the user
(21:30:36) WARNING: [Backend]:         Failed to register protocol with OS.
(21:30:37) INFO:    [Backend]:         AreWeAntiCheatYet data downloaded
(21:30:37) INFO:    [Gog]:             Saved user data to config
(21:30:37) INFO:    [Frontend]:        Refreshing Library
(21:30:37) INFO:    [Legendary]:       Refreshing library...
(21:30:37) INFO:    [Legendary]:       Refreshing Epic Games...
(21:30:37) INFO:    [Gog]:             Getting GOG library
(21:30:38) INFO:    [Gog]:             Number of library pages: 1
(21:30:38) INFO:    [Legendary]:       Running command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary list
(21:30:38) INFO:    [Gog]:             Saved games data
(21:30:39) INFO:    [Backend]:         Downloaded Winetricks
(21:30:40) INFO:    [Legendary]:       Updating game list
(21:30:40) INFO:    [Legendary]:       Game List Updated
(21:30:40) INFO:    [Legendary]:       Checking for game updates.
(21:30:40) INFO:    [Legendary]:       Running command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary list-installed --check-updates --tsv
(21:30:41) INFO:    [Legendary]:       Found 0 game(s) to update
(21:30:41) INFO:    [Gog]:             Found 0 game(s) to update
(21:37:04) INFO:    [Legendary]:       Getting Info from Epic API
(21:37:04) INFO:    [Legendary]:       Getting Info from Epic API
(21:37:04) INFO:    [Legendary]:       Getting more details with 'legendary info'
(21:37:05) INFO:    [Legendary]:       Running command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary --pretty-json info Quail --platform Windows --json
(21:37:06) INFO:    [Legendary]:       Getting more details with 'legendary info'
(21:37:06) INFO:    [Legendary]:       Getting more details with 'legendary info'
(21:37:06) DEBUG:   [Backend]:         {"free":264693055488,"diskSize":492501127168,"message":"246.51 GiB / 458.68 GiB","validPath":true}
(21:37:06) DEBUG:   [Backend]:         {"free":264693055488,"diskSize":492501127168,"message":"246.51 GiB / 458.68 GiB","validPath":true}
(21:37:06) INFO:    [Legendary]:       Running command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary --pretty-json info Quail --platform Windows --json
(21:37:06) INFO:    [Legendary]:       Running command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary --pretty-json info Quail --platform Windows --json
(21:37:08) ERROR:   [Backend]:         SyntaxError: Unexpected end of JSON input
(21:37:08) ERROR:   [Frontend]:        Cannot get game info
(21:37:09) ERROR:   [Backend]:         SyntaxError: Unexpected end of JSON input
(21:37:09) ERROR:   [Backend]:         SyntaxError: Unexpected end of JSON input
(21:40:03) INFO:    [Legendary]:       Getting more details with 'legendary info'
(21:40:04) INFO:    [Legendary]:       Running command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary --pretty-json info Quail --platform Windows --json

### Steps to reproduce

1. Select game you want to install
2. Click on 'install
3. Empty popup appears 2 times
4. The main windows shows the error message

### Expected behavior

Game should be installed

### System Information

- steam OS 
- Heroic Version 2.4.2:

**Comment by flavioislima** [comment]
This is not related with the other hotfix. This is happening because Epic changed another thing on their side. We will fix it again soon.

**Comment by Lubo90** [comment]
I have the same issue - a fresh install on 256GB SteamDeck, when trying to download any game, an empty MessageBox pops up. Ocassionally the app also freezes, making me unable to click "OK", to close it. The OS-dedicated close button also doesn't work.

**Comment by Mcfly2340** [comment]
Also occurs for me. Tried reinstalling, resetting the apps' data, removing the data folder of the app but nothing seemed to fix this. And sometimes it just freezes and stops the whole device which results in me eventually manually rebooting the device

**Comment by flavioislima** [comment]
A workaround for that issue, for now, is to:
open the legendary config file:
`UserHome/.config/legendary/config.ini` (this .config folder is normally hidden)
In the [Legendary] Section add:
`preferred_cdn = http://epicgames-download1.akamaized.net`

That should fix it for now.

**Comment by coke0108** [comment]
tried the workaround with no luck.
found the config.ini not in Home/deck/.config/legendary/ but in /home/deck/.var/app/com.heroicgameslauncher.hgl/config/legendary/.
i entered the string to the config.ini, but the download worked only for the game 20XX(first game in the list). for all other games i tried to install it did not work

**Comment by crazyquark** [comment]
I have this issue as well.

**Comment by alanvww** [comment]
same problem here

**Comment by Mcfly2340** [comment]
> A workaround for that issue, for now, is to: open the legendary config file: `UserHome/.config/legendary/config.ini` (this .config folder is normally hidden) In the [Legendary] Section add: `preferred_cdn = http://epicgames-download1.akamaized.net`
> 
> That should fix it for now.

This sadly didn't do anything for me...

**Comment by flavioislima** [comment]
@Mcfly2340 so maybe try doing what it is pointed at #1789 

Closing this one as duplicated
