### ISSUE TITLE
Download gets stuck if screen of on steam deck

### ISSUE THREAD

**Issue by whise** [Heroic-Games-Launcher/HeroicGamesLauncher#1792]
### Describe the bug

I notice that if I am downloading a game, and the screen turns of, the download gets stuck.

I'm on steam deck

### Add logs

No logs

### Steps to reproduce

2. Click on '...'
3. Scroll down to '...'

### Expected behavior

Should not get stuck

### System Information

- OS [e. g. "Ubuntu"]: steam deck 
- Heroic Version [e. g. 2.1.1]: 2.4.2

**Comment by flavioislima** [comment]
We need more info on that? Is this a GOG game?
There is a current bug for it, the progress gets stuck but the game keeps being downloaded in the background.

**Comment by whise** [comment]
I just realized it keeps downloading, I just like you said. It's GOG. Sorry for the duplicate bug.
