### ISSUE TITLE
"Not enough disk space" when continuing to download is wrong

### ISSUE THREAD

**Issue by whise** [Heroic-Games-Launcher/HeroicGamesLauncher#1793]
### Describe the bug

When continuing to download a game I get "not enough disk space" even though I have enough space to finish downloading what is missing. I guess heroic calculates the space required for the full game, and not for the remainder.

### Add logs

No logs

### Steps to reproduce

2. Click on '...'
3. Scroll down to '...'

### Expected behavior

Should have enough space

### System Information

- OS [e. g. "Ubuntu"]: steam os
- Heroic Version [e. g. 2.1.1]: 2.4.2

**Comment by flavioislima** [comment]
can you send a screenshot?
Heroic looks only for the remaining download size.
The problem is that this value is not exact since depending on the game some chunks need to be redownloaded completely and this is not Heroic's fault.
