### ISSUE TITLE
Epic probably blocks the launcher - Error 403 from download requests and then IP block

### ISSUE THREAD

**Issue by pragma-once** [Heroic-Games-Launcher/HeroicGamesLauncher#1795]
### Describe the bug

Not exactly a bug maybe, but this is how it happens:

- I click on the install button of the game (no matter what game).
- Install.
- "Install started" notification.
- A few seconds later "Install finished" notification but the game's not installed, because of a 403 error.
- Now I can't get the download info of any game (or download) unless I change my IP to only get download info of another game and then again the same story.

I've cleared the cache but that didn't help, could be an API change.

### Add logs

Unfortunately, I'm out of IP addresses, but pasting a mix of logs to show how it went.
I shortened the download URL because I'm not sure what's in there (like keys).

A log file after *first* install attempt with an IP address:

[Core] INFO: Trying to re-use existing login session...
[cli] INFO: Preparing download for "Cities Skylines" (bcbc03d8812a44c18f41cf7d5f849265)...
Traceback (most recent call last):
  File "legendary\cli.py", line 3054, in <module>
  File "legendary\cli.py", line 2971, in main
  File "legendary\cli.py", line 931, in install_game
  File "legendary\core.py", line 1296, in prepare_download
  File "legendary\core.py", line 1221, in get_cdn_manifest
  File "requests\models.py", line 1021, in raise_for_status
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://download.epicgames.com/Builds/Org/<something...>
[9728] Failed to execute script 'cli' due to unhandled exception!

After getting error 403 once, it gets an empty json (a {}, which causes an exception in the .log file too) whenever I try to get the download info of a game.

(18:32:07) INFO:    [Backend]:         VCRuntime is installed
(18:32:21) ERROR:   [Backend]:         SyntaxError: Unexpected end of JSON input
(18:32:21) ERROR:   [Frontend]:        Cannot get game info
(18:32:23) ERROR:   [Backend]:         SyntaxError: Unexpected end of JSON input
(18:32:23) ERROR:   [Frontend]:        Cannot get game info
(18:32:27) ERROR:   [Backend]:         SyntaxError: Unexpected end of JSON input
(18:32:53) DEBUG:   [Legendary]:       Using cached install info
(18:32:53) DEBUG:   [Legendary]:       Using cached install info

### Steps to reproduce

- Install a game
- "Install started" notification.
- A few seconds later "Install finished" notification but the game's not installed, because of a 403 error.
- Now I can't get the download info of any game (or download) unless I change my IP to only get download info of another game and then again the same story.

### Expected behavior

To download the game and not get 403 or empty json.

### System Information

- OS [e. g. "Ubuntu"]: Windows 11
- Heroic Version [e. g. 2.1.1]: 2.4.2

### Additional information

Also, the game info fetch is much faster than before (by before I mean like a month ago maybe). It used to be very slow but now (after changing IP and with cleared cache) it's almost instantaneous.

**Comment by pragma-once** [comment]
Just realized it's related to Legendary Launcher, I'm leaving this open for you to decide whether to close it. It could be open until it's solved for Legendary.

Here's the issue there: https://github.com/derrod/legendary/issues/479

**Comment by flavioislima** [comment]
duplicated from #1789 and #1790
