### ISSUE TITLE
Empty error when pressing install 

### ISSUE THREAD

**Issue by DEAD1SIDE** [Heroic-Games-Launcher/HeroicGamesLauncher#1796]
### Describe the bug

I installed Heroic and wine/proton. When I now try to install Epic games it gives me an empty error.

### Add logs

(21:17:23) INFO:    [Legendary]:       Running command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary --version
(21:17:24) INFO:    [Legendary]:       Legendary location: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary
(21:17:24) INFO:    [Gog]:             GOGDL location: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl
(21:17:24) INFO:    [Backend]:         

Heroic Version: 2.4.2 Chopper
Legendary Version:  0.20.28 Dark Energy (hotfix #2)
OS: Freedesktop SDK KERNEL: 5.13.0-valve21.1-1-neptune-02211-gc54cda5a36f3 ARCH: x64
CPU: AMD Custom APU 0405 @1.78 GOVERNOR: schedutil
RAM: Total: 14.49 GiB Available: 12.03 GiB
GRAPHICS: GPU0: VanGogh [AMD Custom GPU 0405] VRAM: 512MB DRIVER:  
PROTOCOL: x11

(21:17:24) WARNING: [Backend]:         Failed to register protocol with OS.
(21:17:25) INFO:    [Backend]:         AreWeAntiCheatYet data downloaded
(21:17:25) INFO:    [Frontend]:        Refreshing Library
(21:17:25) INFO:    [Legendary]:       Refreshing library...
(21:17:25) INFO:    [Legendary]:       Refreshing Epic Games...
(21:17:26) INFO:    [Legendary]:       Running command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary list
(21:17:27) INFO:    [Backend]:         Downloaded Winetricks
(21:17:28) INFO:    [Legendary]:       Updating game list
(21:17:28) INFO:    [Legendary]:       Game List Updated
(21:17:28) INFO:    [Legendary]:       Checking for game updates.
(21:17:28) INFO:    [Legendary]:       Running command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary list-installed --check-updates --tsv
(21:17:30) INFO:    [Legendary]:       Found 0 game(s) to update
(21:17:30) INFO:    [Gog]:             Found 0 game(s) to update
(21:17:39) INFO:    [Legendary]:       Getting more details with 'legendary info'
(21:17:39) INFO:    [Legendary]:       Getting more details with 'legendary info'
(21:17:39) DEBUG:   [Backend]:         {"free":51630448640,"diskSize":505981009920,"message":"48.08 GiB / 471.23 GiB","validPath":true}
(21:17:39) DEBUG:   [Backend]:         {"free":51630448640,"diskSize":505981009920,"message":"48.08 GiB / 471.23 GiB","validPath":true}
(21:17:39) INFO:    [Legendary]:       Running command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary --pretty-json info Stellula --platform Windows --json
(21:17:39) INFO:    [Legendary]:       Running command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary --pretty-json info Stellula --platform Windows --json
(21:17:43) ERROR:   [Backend]:         SyntaxError: Unexpected end of JSON input
(21:17:43) ERROR:   [Backend]:         SyntaxError: Unexpected end of JSON input

### Steps to reproduce

1. Install via flatpak
2. login with epic
3. try installing a game

### Expected behavior

Install  window should appear

### Screenshots

![Screenshot_20220909_210945](https://user-images.githubusercontent.com/42000678/189429563-d1a0ac20-c8ae-4a17-be48-2008dee72a4d.png)

### System Information

- OS [e. g. "Ubuntu"]: SteamOS 3.3.1 on Steam  deck
- Heroic Version [e. g. 2.1.1]:2.4.2

**Comment by vladfrenkel** [comment]
Same on Nobara Project (Fedora 36 derivative) installed via Flatpak. Version 2,4.2

**Comment by Slymenstra** [comment]
Same on SteamOS 3.3.1

**Comment by A1ic3-g** [comment]
Same of SteamOS however I've done a bit more digging.

It seems there is a 403 forbidden error when trying to download from Epic Games.
I've attached the legendary log from trying to install Overcooked 2 but below is the important bit.

`[Core] INFO: Trying to re-use existing login session...
[cli] INFO: Preparing download for "Overcooked! 2" (Potoo)...
Traceback (most recent call last):
  File "legendary/cli.py", line 3054, in <module>
  File "legendary/cli.py", line 2971, in main
  File "legendary/cli.py", line 931, in install_game
  File "legendary/core.py", line 1296, in prepare_download
  File "legendary/core.py", line 1221, in get_cdn_manifest
  File "requests/models.py", line 953, in raise_for_status
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://download.epicgames.com/Builds/Org/<rest_of_url>`

file:///home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/GamesConfig/Potoo.log

**Comment by A1ic3-g** [comment]
This makes me think Epic has changed something which has broken legendary

**Comment by A1ic3-g** [comment]
https://github.com/derrod/legendary/issues/479

This issue on legendary suggests Legendary has already fixed it, the updated legendary package just hasn't been upstreamed yet

**Comment by DEAD1SIDE** [comment]
I tried to login in lutris to try it there but there the library doesn't load and icon to login still appears. So the probability that it is on epics side is high i would say.

**Comment by CommandMC** [comment]
Resolved in #1791
