### ISSUE TITLE
MAD Linux Repo Not Available

### ISSUE THREAD

**Issue by InklingGirl** [Heroic-Games-Launcher/HeroicGamesLauncher#1799]
The MAD Linux repo I used to install & update Heroic no longer seems to be available. Does anyone know what happened to it? Has it moved? Thank you.

**Comment by flavioislima** [comment]
> The MAD Linux repo I used to install & update Heroic no longer seems to be available. Does anyone know what happened to it? Has it moved? Thank you.

Yes, it changed. Check the heroic readme for updated instructions.
