### ISSUE TITLE
Heroic Flatpak: No Access to Proton from Steam Flathub

### ISSUE THREAD

**Issue by arcDaniel84** [Heroic-Games-Launcher/HeroicGamesLauncher#1805]
### Describe the bug

Since a newer Steam Flatpak update (with the MESA 22.08 runtime), I can't use the Steam Proton version any more. Even custom Proton Version (over ProtonUP-QT) are not loaded into Heroic.

I already made some reinstalls of the Heroic Faltpak (even with deleting the .var files), an resting the permissions. No chance.

### Add logs

(08:57:46) INFO:    [Legendary]:       Running command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary --version
(08:57:46) INFO:    [Legendary]:       Legendary location: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary
(08:57:46) INFO:    [Gog]:             GOGDL location: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl
(08:57:46) INFO:    [Backend]:         

Heroic Version: 2.4.3 Chopper
Legendary Version:  0.20.28 Dark Energy (hotfix #2)
OS: Freedesktop SDK KERNEL: 5.19.7-1-default ARCH: x64
CPU: AMD Ryzen 5 5600X 6-Core Processor @3.7 GOVERNOR: ondemand
RAM: Total: 15.52 GiB Available: 11 GiB
GRAPHICS: GPU0: Navi 21 [Radeon RX 6800/6800 XT / 6900 XT] VRAM: 1MB DRIVER:  
PROTOCOL: x11

(08:57:46) INFO:    [Gog]:             Getting data about the user
(08:57:46) INFO:    [Gog]:             Refreshing access_token
(08:57:46) WARNING: [Backend]:         Failed to register protocol with OS.
(08:57:47) INFO:    [Gog]:             Token refreshed successfully
(08:57:47) INFO:    [Backend]:         AreWeAntiCheatYet data downloaded
(08:57:47) INFO:    [Gog]:             Saved user data to config
(08:57:47) INFO:    [Frontend]:        Refreshing Library
(08:57:47) INFO:    [Legendary]:       Refreshing library...
(08:57:47) INFO:    [Legendary]:       Refreshing Epic Games...
(08:57:47) INFO:    [Gog]:             Getting GOG library
(08:57:47) INFO:    [Gog]:             Number of library pages: 1
(08:57:47) INFO:    [Legendary]:       Running command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary list
(08:57:47) INFO:    [Gog]:             Saved games data
(08:57:49) INFO:    [Legendary]:       Updating game list
(08:57:49) INFO:    [Legendary]:       Game List Updated
(08:57:49) INFO:    [Backend]:         Downloaded Winetricks
(08:57:49) INFO:    [Legendary]:       Checking for game updates.
(08:57:49) INFO:    [Legendary]:       Running command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary list-installed --check-updates --tsv
(08:57:50) INFO:    [Legendary]:       Found 0 game(s) to update
(08:57:50) INFO:    [Gog]:             Found 0 game(s) to update

### Steps to reproduce

...

### Expected behavior

Normally the Proton Steam Versions should be available in Heroic without extra user actions.

### Screenshots

![image](https://user-images.githubusercontent.com/67470462/189592525-1de73911-df9d-4840-adfc-dc9b37cb9d2c.png)
![image](https://user-images.githubusercontent.com/67470462/189592684-7497342b-2d2c-44dd-bd6c-abf493823162.png)

### System Information

-first try Manjaro
-second EndeavourOS 
-now openSuse Tumbleweed

-Heroic 2.4.2 (situation appeared) and not solved with 2.4.3

-Steam latest Flatpak version

**Comment by Nocccer** [comment]
You need to give heroic flatpak access to steam flathub. We can't do that.

**Comment by arcDaniel84** [comment]
But that is the case and what make it so strange
![image](https://user-images.githubusercontent.com/67470462/189600173-14f445a6-5ea0-4e83-b218-2a03563f02ee.png)

**Comment by flavioislima** [comment]
For testing purposes try adding access to all folders for heroic.
Also can you check the path for proton on the steam folder?

**Comment by arcDaniel84** [comment]
checked and tried, no luck

**Comment by arcDaniel84** [comment]
I have found the problem

in the config file
"defaultSteamPath": "/home/daniel/.var/app/com.valvesoftware.Steam/.steam/steam/"

**Comment by arcDaniel84** [comment]
I have found the problem:
in the config.json the entry was
"defaultSteamPath": "/home/daniel/.steam/steam/"
even deleting the file, that a new one would be generated or deleting the entire .var/app/com.heroicgameslauncher.hgl folder didn't help.

So I manually changed it to:
"defaultSteamPath": "/home/daniel/.var/app/com.valvesoftware.Steam/.steam/steam/" 

and now I can chose the steam installed Proton versions.

strange...

**Comment by flavioislima** [comment]
Now there is a input on advanced settings for that.

**Comment by AAlieZZ** [comment]
I changed "Default Steam path" to: `/home/daniel/.var/app/com.valvesoftware.Steam/.steam/steam/`
But it still no "Proton GE"(installed by flatpak) in "Wine version"
