### ISSUE TITLE
I have 252.8gb available. The installer says i have only 75.81 and wont let me install.

### ISSUE THREAD

**Issue by mindingulove** [Heroic-Games-Launcher/HeroicGamesLauncher#1812]
<a href="https://ibb.co/9q5YrSN"><img src="https://i.ibb.co/9q5YrSN/Screenshot-2022-09-13-at-1-34-54-PM.png" alt="Screenshot-2022-09-13-at-1-34-54-PM" border="0"></a>

The picture speaks for itself. 
Tried unisntaling and deleting chaches, configs and temp files, no luck.
Thank you

**Comment by Nocccer** [comment]
Please show a picture that the path you wanna install too has enough space. You just showing the overall space not the partition space

**Comment by flavioislima** [comment]
Closing this one.
