### ISSUE TITLE
Transistor (Epic) not working on heroic launcher

### ISSUE THREAD

**Issue by pratishmerchant** [Heroic-Games-Launcher/HeroicGamesLauncher#1814]
### Describe the bug

Transistor from SuperGaint games installs but is not running on steam deck using heroic launcher.
Keep getting openTk error with any wine version. 

### Add logs

System Info:
Heroic Version: 2.4.3 Chopper
Legendary Version:  0.20.28 Dark Energy (hotfix #2)
OS: Freedesktop SDK KERNEL: 5.13.0-valve21.1-1-neptune-02211-gc54cda5a36f3 ARCH: x64
CPU: AMD Custom APU 0405 @1.68 GOVERNOR: schedutil
RAM: Total: 14.49 GiB Available: 9.86 GiB
GRAPHICS: GPU0: VanGogh [AMD Custom GPU 0405] VRAM: 512MB DRIVER:  
PROTOCOL: x11

Game Settings: {
"audioFix": false,
"autoInstallDxvk": true,
"autoInstallVkd3d": true,
"preferSystemLibs": true,
"enableFSR": false,
"maxSharpness": 5,
"language": "",
"launcherArgs": "",
"nvidiaPrime": false,
"offlineMode": false,
"enviromentOptions": [],
"wrapperOptions": [],
"savesPath": "",
"showFps": false,
"targetExe": "",
"useGameMode": false,
"winePrefix": "/home/deck/Games/Heroic/Prefixes/Transistor",
"wineVersion": {
"bin": "/home/deck/.local/share/Steam/compatibilitytools.d/GE-Proton7-33/proton",
"name": "Proton - GE-Proton7-33",
"type": "proton"
},
"useSteamRuntime": false,
"eacRuntime": false,
"battlEyeRuntime": false,
"gogSaves": []
}

Game launched at: Tue Sep 13 2022 19:21:50 GMT-0400 (Eastern Daylight Time)

Launch Command: STEAM_COMPAT_CLIENT_INSTALL_PATH=/home/deck/.var/app/com.heroicgameslauncher.hgl/.steam/steam STEAM_COMPAT_DATA_PATH=/home/deck/Games/Heroic/Prefixes/Transistor PROTON_NO_ESYNC=1 PROTON_NO_FSYNC=1 STEAM_COMPAT_APP_ID=0 SteamAppId=0 SteamGameId=heroic-Transistor PROTON_LOG_DIR=/home/deck/.var/app/com.heroicgameslauncher.hgl /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary launch Dill --language en  --no-wine --wrapper "'/home/deck/.local/share/Steam/compatibilitytools.d/GE-Proton7-33/proton' run"

Game Log:
[cli] INFO: Logging in...
[Core] INFO: Trying to re-use existing login session...
[cli] INFO: Checking for updates...
[Core] INFO: Getting authentication token...
[cli] INFO: Launching Dill...
wineserver: using server-side synchronization.
wine: RLIMIT_NICE is <= 20, unable to use setpriority safely
[S_API] SteamAPI_Init(): SteamAPI_IsSteamRunning() did not locate a running instance of Steam.
[S_API FAIL] SteamAPI_Init() failed
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.TypeInitializationException: The type initializer for 'OpenTK.Platform.Windows.WinGLContext' threw an exception. ---> OpenTK.Graphics.GraphicsModeException: The requested GraphicsMode is not supported
   at OpenTK.Platform.Windows.WinGraphicsMode.SelectGraphicsMode(ColorFormat color, Int32 depth, Int32 stencil, Int32 samples, ColorFormat accum, Int32 buffers, Boolean stereo)
   at OpenTK.Platform.Windows.WinGLContext.SetGraphicsModePFD(WinGraphicsMode mode_selector, GraphicsMode mode, WinWindowInfo window)
   at OpenTK.Platform.Windows.WinGLContext..cctor()
   --- End of inner exception stack trace ---
   at OpenTK.Platform.Windows.WinGLContext..ctor(GraphicsMode format, WinWindowInfo window, IGraphicsContext sharedContext, Int32 major, Int32 minor, GraphicsContextFlags flags)
   at OpenTK.Platform.Windows.WinFactory.CreateGLContext(GraphicsMode mode, IWindowInfo window, IGraphicsContext shareContext, Boolean directRendering, Int32 major, Int32 minor, GraphicsContextFlags flags)
   at OpenTK.Graphics.GraphicsContext..ctor(GraphicsMode mode, IWindowInfo window, Int32 major, Int32 minor, GraphicsContextFlags flags)
   at OpenTK.GameWindow..ctor(Int32 width, Int32 height, GraphicsMode mode, String title, GameWindowFlags options, DisplayDevice device, Int32 major, Int32 minor, GraphicsContextFlags flags, IGraphicsContext sharedContext)
   at OpenTK.GameWindow..ctor()
   at Microsoft.Xna.Framework.WindowsGameWindow.Initialize()
   at Microsoft.Xna.Framework.WindowsGamePlatform..ctor(Game game)
   at Microsoft.Xna.Framework.Game..ctor()
   at GSGE.App..ctor()
   --- End of inner exception stack trace ---
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache)
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean skipVisibilityChecks, Boolean skipCheckThis, Boolean fillCache)
   at System.Activator.CreateInstance[T]()
   at Game.Windows.Program.Run[T](IBugReporter[] bugReporters)

Unhandled Exception: System.TypeInitializationException: The type initializer for 'OpenTK.Platform.Windows.WinGLContext' threw an exception. ---> OpenTK.Graphics.GraphicsModeException: The requested GraphicsMode is not supported
   at OpenTK.Platform.Windows.WinGraphicsMode.SelectGraphicsMode(ColorFormat color, Int32 depth, Int32 stencil, Int32 samples, ColorFormat accum, Int32 buffers, Boolean stereo)
   at OpenTK.Platform.Windows.WinGLContext.SetGraphicsModePFD(WinGraphicsMode mode_selector, GraphicsMode mode, WinWindowInfo window)
   at OpenTK.Platform.Windows.WinGLContext..cctor()
   --- End of inner exception stack trace ---
   at OpenTK.Platform.Windows.WinGLContext..ctor(GraphicsMode format, WinWindowInfo window, IGraphicsContext sharedContext, Int32 major, Int32 minor, GraphicsContextFlags flags)
   at OpenTK.Platform.Windows.WinFactory.CreateGLContext(GraphicsMode mode, IWindowInfo window, IGraphicsContext shareContext, Boolean directRendering, Int32 major, Int32 minor, GraphicsContextFlags flags)
   at OpenTK.Graphics.GraphicsContext..ctor(GraphicsMode mode, IWindowInfo window, Int32 major, Int32 minor, GraphicsContextFlags flags)
   at OpenTK.GameWindow..ctor(Int32 width, Int32 height, GraphicsMode mode, String title, GameWindowFlags options, DisplayDevice device, Int32 major, Int32 minor, GraphicsContextFlags flags, IGraphicsContext sharedContext)
   at OpenTK.GameWindow..ctor()
   at Microsoft.Xna.Framework.WindowsGameWindow.Initialize()
   at Microsoft.Xna.Framework.WindowsGamePlatform..ctor(Game game)
   at Microsoft.Xna.Framework.Game..ctor()
   at GSGE.ExceptionGame..ctor(Exception e)
   at Game.Windows.Program.Run[T](IBugReporter[] bugReporters)
   at Game.Windows.Program.Main(String[] args)
wine: Unhandled exception 0xe0434352 in thread 138 at address 000000007B0124DE (thread 0138), starting debugger...
Unhandled exception: 0xe0434352 in 64-bit code (0x000000007b0124de).
Register dump:
 rip:000000007b0124de rsp:0000000000419420 rbp:000000000041c670 eflags:00000202 (   - --  I   - - - )
 rax:0000000000419460 rbx:0000000000800050 rcx:0000000000419440 rdx:0000000000000001
 rsi:00000000004195f0 rdi:0000000000419488  r8:0000000000000005  r9:00000000004195c8 r10:0000000000000059
 r11:00000644800121d0 r12:0000000000000005 r13:00000000004195c8 r14:00000000e0434352 r15:00000644807f8b60
Stack dump:
0x0000000000419420:  0000000000419440 0000000200000000
0x0000000000419430:  0000000000000000 0000000000010020
0x0000000000419440:  00000001e0434352 0000000000000000
0x0000000000419450:  000000007b0124de 0000064400000005
0x0000000000419460:  ffffffff80131534 0000000000000000
0x0000000000419470:  0000000000000000 0000000000000000
0x0000000000419480:  000006447f100000 000006447f24e7d7
0x0000000000419490:  0000000000000000 0000000000800050
0x00000000004194a0:  0000000000419698 000001e000000001
0x00000000004194b0:  0000064480012020 000006447f12e7bc
0x00000000004194c0:  0000000000000059 000006447f11edc0
0x00000000004194d0:  fffffffffffffffe 0000000000903658
Backtrace:
=>0 0x000000007b0124de AccessCheckByTypeAndAuditAlarmW+0x114de() in kernelbase (0x000000000041c670)
  1 0x000006447f1e20bd EntryPoint+0x4bc4d() in clr (0x000000000041c670)
  2 0x000006447f1e5c23 EntryPoint+0x4f7b3() in clr (0x000000000041c670)
0x000000007b0124de kernelbase+0x124de: nop
Modules:
Module Address Debug info Name (60 modules)
PE 000000001b460000-000000001b91e000 Deferred        mscorlib
PE 000000001bcb0000-000000001bcba000 Deferred        hostessprotocol
PE 000000001bcd0000-000000001bf3a000 Deferred        engine
PE 000000001bf40000-000000001bfbc000 Deferred        monogame.framework.windows
PE 000000001bfc0000-000000001c03c000 Deferred        monogame.framework.windows
PE 000000001c040000-000000001c04a000 Deferred        hostessprotocol
PE 000000001c0b0000-000000001c118000 Deferred        system.configuration
PE 000000001c160000-000000001c4b6000 Deferred        system
PE 000000001c4c0000-000000001c6de000 Deferred        system.xml
PE 000000001c6e0000-000000001c82c000 Deferred        system.core
PE 000000001c830000-000000001cb4a000 Deferred        opentk
PE 000000001cb50000-000000001ce6a000 Deferred        opentk
PE 000000001ce70000-000000001cf0a000 Deferred        system.drawing
PE 000000001cf70000-000000001d434000 Deferred        system.windows.forms
PE 000000001d440000-000000001d904000 Deferred        system.windows.forms
PE 0000000060c90000-0000000060cf8000 Deferred        system.configuration
PE 0000000060e50000-0000000060f9c000 Deferred        system.core
PE 0000000069720000-000000006993e000 Deferred        system.xml
PE 000000007a820000-000000007ab76000 Deferred        system
PE 000000007b000000-000000007b0da000 Export          kernelbase
PE 000000007b1d0000-000000007b26a000 Deferred        system.drawing
PE 000000007b600000-000000007b812000 Deferred        kernel32
PE 000000007c000000-000000007c4be000 Deferred        mscorlib
PE 0000000140000000-0000000140062000 Deferred        transistor
PE 0000000170000000-00000001700a2000 Deferred        ntdll
PE 0000000180000000-000000018026a000 Deferred        engine
PE 00000001c8b40000-00000001c8b60000 Deferred        msacm32
PE 00000001c8db0000-00000001c8e47000 Deferred        msvcrt
PE 00000001dd3f0000-00000001dd4bd000 Deferred        crypt32
PE 00000001ec2b0000-00000001ec2d6000 Deferred        ws2_32
PE 00000001f51e0000-00000001f51f0000 Deferred        hid
PE 0000000201b20000-0000000201b43000 Deferred        diasymreader
PE 000000021a7e0000-000000021a856000 Deferred        setupapi
PE 0000000231ae0000-0000000231b62000 Deferred        rpcrt4
PE 000000023d820000-000000023da6f000 Deferred        user32
PE 000000026b4c0000-000000026b53a000 Deferred        gdi32
PE 00000002739c0000-0000000273af7000 Deferred        oleaut32
PE 00000002bb750000-00000002bb894000 Deferred        comctl32
PE 00000002d4d40000-00000002d4d57000 Deferred        bcrypt
PE 00000002de970000-00000002de9a2000 Deferred        rsaenh
PE 00000002e3540000-00000002e3591000 Deferred        shlwapi
PE 00000002e8f10000-00000002e902a000 Deferred        ole32
PE 00000002f1fa0000-00000002f1fae000 Deferred        version
PE 0000000308050000-000000030809b000 Deferred        dinput8
PE 00000003126f0000-0000000312709000 Deferred        shcore
PE 0000000327020000-0000000327073000 Deferred        combase
PE 000000032a700000-000000032a72a000 Deferred        sechost
PE 0000000330260000-00000003302a0000 Deferred        advapi32
PE 0000000375610000-0000000375648000 Deferred        win32u
PE 00000003af670000-00000003af730000 Deferred        ucrtbase
PE 00000003afd00000-00000003afd1a000 Deferred        imm32
PE 00000003b8f00000-00000003b8fc1000 Deferred        winmm
PE 000006427ee50000-000006427eebf000 Deferred        mscoree
PE 000006447f100000-000006447fa67000 Export          clr
PE 000006447faf0000-000006447fc67000 Deferred        clrjit
PE 000006447fd00000-000006447fdd1000 Deferred        msvcr100_clr0400
PE 00000644ff540000-00000644ff5d0000 Deferred        mscoreei
PE 00000644ffae0000-00000644ffaf4000 Deferred        nlssorting
PE 00007f7bdbcf0000-00007f7bdbcf4000 Deferred        opengl32
PE 00007f7be0c80000-00007f7be0c84000 Deferred        winex11
Threads:
process  tid      prio (all id:s are in hex)
00000020 steam.exe
["C:\windows\system32\steam.exe" /home/deck/Games/Heroic/Transistor/x64/Transistor.exe /c=.. -AUTH_LOGIN=unused -AUTH_PASSWORD=cffa2a3e2e1046e3bf567e759f630c83 -AUTH_TYPE=exchangecode -epicapp=Dill -epicenv=Prod -EpicPortal -epicusername=Pratzie -epicuserid=77ff8059ea2b49fe965996da3c943588 -epiclocale=en -epicsandboxid=bc81d1e7d1794d3a94e4dbf26e92166d]
00000024    0
000000c4    0
0000013c    0
00000030 services.exe
["C:\windows\system32\services.exe"]
00000034    0
00000038    0
00000044    0
00000048    0
0000005c    0
00000078    0
00000098    0
000000ac    0
000000c0    0
000000f4    0
000000f8    0
000000fc    0
0000003c svchost.exe
[C:\windows\system32\svchost.exe -k LocalServiceNetworkRestricted]
00000040    0
0000004c    0
00000050    0
00000054 winedevice.exe
[C:\windows\system32\winedevice.exe]
00000058    0
00000060    0
00000064    0
00000068    0
000000bc    0
00000070 winedevice.exe
[C:\windows\system32\winedevice.exe]
00000074    0
0000007c    0
00000080    0
00000084    0
00000088    0
0000008c    0
00000094    0
000000a4    0
000000a8    0
0000009c plugplay.exe
[C:\windows\system32\plugplay.exe]
000000a0    0
000000b0    0
000000b4    0
000000b8    0
000000d0 explorer.exe
[C:\windows\system32\explorer.exe /desktop]
000000d4    0
000000d8    0
000000ec    0
000000e4 rpcss.exe
[C:\windows\system32\rpcss.exe]
000000e8    0
00000100    0
00000104    0
00000108    0
0000010c    0
00000114    0
00000120    0
00000124 tabtip.exe
["C:\windows\system32\tabtip.exe"]
00000128    0
00000130    0
00000140    0
00000134 (D) Z:\home\deck\Games\Heroic\Transistor\x64\Transistor.exe
["Z:\home\deck\Games\Heroic\Transistor\x64\Transistor.exe" /c=.. -AUTH_LOGIN=unused -AUTH_PASSWORD=cffa2a3e2e1046e3bf567e759f630c83 -AUTH_TYPE=exchangecode -epicapp=Dill -epicenv=Prod -EpicPortal -epicusername=Pratzie -epicuserid=77ff8059ea2b49fe965996da3c943588 -epiclocale=en -epicsandboxid=bc81d1e7d1794d3a94e4dbf26e92166d]
00000138    0 <==
00000144    0
00000148    2
0000014c    0
00000150    0
0000015c    0
00000160    0
System information:
    Wine build: wine-7.0 (Staging)
    Platform: x86_64
    Version: Windows 10
    Host system: Linux
    Host version: 5.13.0-valve21.1-1-neptune-02211-gc54cda5a36f3

### Steps to reproduce

Install transistor from epic store.
Try to launch game with any wine version

### Expected behavior

Game should run

### System Information

- OS [e. g. "Ubuntu"]: SteamOS
- Heroic Version [e. g. 2.1.1]: 2.4.3

**Comment by arielj** [comment]
Share the log in Heroic's discord in the steam deck channel, the issues tracker in github is for errors in heroic launcher, not for help running games
