### ISSUE TITLE
DLC not showing on Steam Deck. 

### ISSUE THREAD

**Issue by Verberk** [Heroic-Games-Launcher/HeroicGamesLauncher#1816]
### Problem description

For example, I've purchased the DLC pack for Control but on my steam deck it's out of reach.  

### Feature description

Show DLC on the settings of the game

### Alternatives

Show the DLC between all your other games

**Comment by flavioislima** [comment]
What do you mean? show on the list of games or when installing?
can you show a screenshot of the DLC on your account and also the install dialog on the latest heroic release?

If the issue persists reopen the issue.
