### ISSUE TITLE
Error load app

### ISSUE THREAD

**Issue by AgostinoA** [Heroic-Games-Launcher/HeroicGamesLauncher#1818]
### Describe the bug

(23:58:39) INFO:    [Legendary]:       Running command: /tmp/.mount_HeroicdOMzB1/resources/app.asar.unpacked/build/bin/linux/legendary --version                                                                                      
(node:10666) UnhandledPromiseRejectionWarning: TypeError: Cannot read properties of undefined (reading 'replaceAll')                                                                                                                  
    at getLegendaryVersion (/tmp/.mount_HeroicdOMzB1/resources/app.asar/build/utils.js:186:9)                      
    at async getSystemInfo (/tmp/.mount_HeroicdOMzB1/resources/app.asar/build/utils.js:247:30)                     
    at async /tmp/.mount_HeroicdOMzB1/resources/app.asar/build/main.js:241:28                                      
(Use `heroic --trace-warnings ...` to show where the warning was created)                                          
(node:10666) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)  

### Add logs

 (23:58:39) INFO:    [Legendary]:       Running command: /tmp/.mount_HeroicdOMzB1/resources/app.asar.unpacked/build/bin/linux/legendary --version                                                                                      
(node:10666) UnhandledPromiseRejectionWarning: TypeError: Cannot read properties of undefined (reading 'replaceAll')                                                                                                                  
    at getLegendaryVersion (/tmp/.mount_HeroicdOMzB1/resources/app.asar/build/utils.js:186:9)                      
    at async getSystemInfo (/tmp/.mount_HeroicdOMzB1/resources/app.asar/build/utils.js:247:30)                     
    at async /tmp/.mount_HeroicdOMzB1/resources/app.asar/build/main.js:241:28                                      
(Use `heroic --trace-warnings ...` to show where the warning was created)                                          
(node:10666) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)  

### Steps to reproduce

1. Open in terminal
2. Error

### Expected behavior

The appimage must any version and not depend on which OS version is present

### System Information

- OS:  Custom Linux
- Heroic Version : last

**Comment by Javrd** [comment]
Same problem here, Ubuntu 18 and heroic version v2.4.3.
Installing v2.3.10 solved my problem.

**Comment by Javrd** [comment]
... but then I couldn't log in. v2.4.2 seems works both for load the launcher and login.

**Comment by Javrd** [comment]
... but it seems I can't install gloomhaven in that version. Looking at discord someone else had the same problem (Forbiden url in the logs) and the only recommendation is try with last heroic version.
... that it seems I can't lunch at all.

**Comment by flavioislima** [comment]
I don't even understand what is going on. This issue has no description.

**Comment by flavioislima** [comment]
> Same problem here, Ubuntu 18 and heroic version v2.4.3.
> Installing v2.3.10 solved my problem. 

You need to update your ubuntu we cannot support all versions even if it is a lts it is pretty old and we have no way of knowing that it had everything to run heroic.

And please check the supported OS list before opening issues.

If you need help with other distros than that then open a discussion on github or go to discord.

**Comment by Javrd** [comment]
Just for adding a bit more info about it, following some advice in discord I tried to run directly 
`/opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary --version`
and I got
`[26411] Error loading Python lib '/tmp/_MEI0vSTeH/libpython3.9.so.1.0': dlopen: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /tmp/_MEI0vSTeH/libpython3.9.so.1.0)`
So it seems related with python version on Ubuntu 18 and yes, the easier solution is to upgrade to newer ubuntu to solve that.

Thanks!

**Comment by Nocccer** [comment]
The problem with url was a flatpak only steam deck problem, where we found a workaround till steam fix this upstream to steamos
