### ISSUE TITLE
Add a setting to play GTA 5 with LSPDFR

### ISSUE THREAD

**Issue by Lolothepro** [Heroic-Games-Launcher/HeroicGamesLauncher#1820]
### Problem description

I'm frustrated that I can't play GTA 5 with the LSPDFR mod.

### Feature description

Add a system to play with GTA 5 with LSPDFR

**Comment by Etaash-mathamsetty** [comment]
Heroic games launcher isin't a mod manager, and probably never will be, you will have to install this mod by yourself

**Comment by Lolothepro** [comment]
To start GTA 5 with LSPDFR, Heroic needs to start RAGEPluginHook.exe, but there are no options for starting GTA 5 with RAGEPluginHook.exe.
The LSPFR mod is not just a file to be added or modified in GTA 5.

**Comment by Etaash-mathamsetty** [comment]
> To start GTA 5 with LSPDFR, Heroic needs to start RAGEPluginHook.exe, but there are no options for starting GTA 5 with RAGEPluginHook.exe. LSPFR mod is not just a file to be added or modified in GTA 5.

you can just set an alternative exe in heroic...

**Comment by Lolothepro** [comment]
Just run RAGEPluginHook.exe, but that means that every time I want to run GTA 5 without LSPDFR, I'll have to delete it, then put it back every time I want to use LSPDFR.

**Comment by flavioislima** [comment]
You can use now the option to Add game, that's the best we can do.
