### ISSUE TITLE
[GoG] REDlauncher and REDmod are nowhere to found in Cyberpunk 2077 

### ISSUE THREAD

**Issue by HenrikDK2** [Heroic-Games-Launcher/HeroicGamesLauncher#1828]
### Describe the bug

Cyberpunk 2077 recently released update 1.6, and the game launches and runs the new update perfectly fine. The problem is that in the update CD Project Red includes a new free DLC REDmod for mod support, and I'm unable to install and enable it.

Most new mods are going to be built on REDmod like [Bike Overhaul](https://www.nexusmods.com/cyberpunk2077/mods/5167?tab=description). 

However, that is not the only issue, REDmod when installed is required to be enabled through the launcher. For some reason, on my install of Cyberpunk 2077 it doesn't exist. When installed through any other launcher, it will boot straight into the launcher, where you can start the game. But through Heroic Games Launcher it launches the game directly without the launcher, but by doing that I can't enable mod support. 

I've tried looking for the REDprelauncher.exe file with the find command, but it doesn't exist in the games folder or the prefix. I tried to uninstall the game, and deleting the prefix. However, it still installs the game without the REDprelauncher.exe file, and I'm unable to install the REDmod DLC. 

I just tried to install the game through GOG Galaxy via. Lutris, and the file is included. I just tried to copy over the launcher setup file, and the offline REDmod installer over to my Heroic installation. Howerver, the REDmod installer said it couldn't detect the base game and wouldn't install, and the REDlauncher didn't work after the installation. 

For now, the only way for to get mod support is installing the game through Lutris.

```
henrik@arch ~ (master)> find /mnt/sshd/Heroic/ -name "*RED*.exe"
/mnt/sshd/Heroic/Cyberpunk 2077/bin/x64/REDEngineErrorReporter.exe
henrik@arch ~ (master)> find /mnt/sshd/Heroic/ -name "Cyber*.exe"
/mnt/sshd/Heroic/Cyberpunk 2077/bin/x64/Cyberpunk2077.exe
henrik@arch ~ (master)> 
```
```
henrik@arch ~ (master)> find /mnt/sshd/Heroic/ -name "*launcher*.exe"
/mnt/sshd/Heroic/Prefixes/FallGuys/pfx/drive_c/windows/system32/belauncher.exe
/mnt/sshd/Heroic/Prefixes/FallGuys/pfx/drive_c/windows/syswow64/belauncher.exe
/mnt/sshd/Heroic/Prefixes/Cyberpunk 2077/pfx/drive_c/windows/system32/belauncher.exe
/mnt/sshd/Heroic/Prefixes/Cyberpunk 2077/pfx/drive_c/windows/syswow64/belauncher.exe
```

### Add logs
```
System Info:

Heroic Version: 2.4.3 Chopper

Legendary Version:  0.20.28 Dark Energy (hotfix #2)

OS: Arch KERNEL: 5.19.9-zen1-1-zen ARCH: x64

CPU: AMD Ryzen 5 3600 6-Core Processor @3.6 GOVERNOR: ondemand

RAM: Total: 31.27 GiB Available: 25.49 GiB

GRAPHICS: GPU0: Navi 10 [Radeon RX 5600 OEM/5600 XT / 5700/5700 XT] VRAM: 512MB DRIVER:  

PROTOCOL: wayland

Game Settings: {

	"autoInstallDxvk": false,

	"autoInstallVkd3d": false,

	"preferSystemLibs": false,

	"autoSyncSaves": true,

	"enableEsync": false,

	"enableFsync": true,

	"maxSharpness": 2,

	"enableResizableBar": true,

	"launcherArgs": "",

	"nvidiaPrime": false,

	"enviromentOptions": [],

	"wrapperOptions": [],

	"savesPath": "",

	"showFps": false,

	"showMangohud": true,

	"targetExe": "",

	"useGameMode": true,

	"useSteamRuntime": true,

	"language": "",

	"wineVersion": {

		"bin": "/mnt/sshd/SteamLibrary/steamapps/common/Proton - Experimental/proton",

		"name": "Proton - Proton - Experimental",

		"type": "proton"

	},

	"winePrefix": "/mnt/sshd/Heroic/Prefixes/Cyberpunk 2077",

	"eacRuntime": false,

	"battlEyeRuntime": false,

	"gogSaves": [

		{

			"name": "saves",

			"location": "/mnt/sshd/Heroic/Prefixes/Cyberpunk 2077/pfx/drive_c/users/steamuser/Saved Games/CD Projekt Red/Cyberpunk 2077"

		}

	]

}

Game launched at: Wed Sep 21 2022 08:28:56 GMT+0200 (Centraleuropæisk sommertid)

Launch Command: LD_PRELOAD= STEAM_COMPAT_CLIENT_INSTALL_PATH=/home/henrik/.steam/steam STEAM_COMPAT_DATA_PATH="/mnt/sshd/Heroic/Prefixes/Cyberpunk 2077" PROTON_NO_ESYNC=1 VKD3D_CONFIG=upload_hvv STEAM_COMPAT_APP_ID=0 SteamAppId=0 SteamGameId="heroic-Cyberpunk 2077" PROTON_LOG_DIR=/home/henrik /usr/bin/mangohud --dlsym /usr/bin/gamemoderun /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl launch "/mnt/sshd/Heroic/Cyberpunk 2077" 1423049311 --no-wine --wrapper "'/mnt/sshd/SteamLibrary/steamapps/common/Proton - Experimental/proton' run" --os windows

Game Log:

gamemodeauto: 

gamemodeauto: 

gamemodeauto: 

fsync: up and running.

wine: Using setpriority to control niceness in the [-19,19] range

```

### Steps to reproduce

1. Install the game
2. Try to install REDmod through Heroic Games Launcher
3. Fail miserably

### Expected behavior

To be able to install the DLC, and enable it with the launcher that doesn't exist in my game files.

### Screenshots

![20220921-075814](https://user-images.githubusercontent.com/30632653/191426105-ebb03d51-dce0-4fea-87dd-086ee8dc3870.jpg)
![20220921-075748](https://user-images.githubusercontent.com/30632653/191426109-cd3f3068-429a-4439-b713-ac535a1401a6.jpg)

### System Information

- OS [Arch Linux]: 
- Heroic Version [2.4.3]:

**Comment by imLinguin** [comment]
Related issue #1119
