### ISSUE TITLE
[macOS] Cannot update GTAV

### ISSUE THREAD

**Issue by Dvdspr** [Heroic-Games-Launcher/HeroicGamesLauncher#1830]
### Describe the bug

When I try to launch gta v, Heroic asks me if I want to update it, but when I click on "yes" the progress bar stays at 0% and basically the update doesn't start at all. If I try to open the game without updating it, it won't start, showing an infinite loading screen

### Add logs

(16:25:50) INFO:    [Legendary]:       Running command: /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/legendary --version
(16:25:55) INFO:    [Legendary]:       Legendary location: /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/legendary
(16:25:55) INFO:    [Gog]:             GOGDL location: /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/gogdl
(16:25:55) INFO:    [Backend]:         

Heroic Version: 2.4.3 Chopper
Legendary Version:  0.20.28 Dark Energy (hotfix #2)
OS: macOS KERNEL: 21.5.0 ARCH: x64
CPU: Apple M1 @2.4 
RAM: Total: 8 GiB Available: 5.86 GiB
GRAPHICS: GPU0: Apple M1 VRAM: nullMB DRIVER:  

(16:25:55) WARNING: [Backend]:         Protocol already registered.
(16:25:59) INFO:    [Backend]:         Checking for new Heroic Updates
(16:25:59) INFO:    [Frontend]:        Refreshing Library
(16:25:59) INFO:    [Legendary]:       Refreshing library...
(16:25:59) INFO:    [Legendary]:       Refreshing Epic Games...
(16:26:00) INFO:    [Legendary]:       Running command: /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/legendary list
(16:26:08) INFO:    [Legendary]:       Updating game list
(16:26:08) INFO:    [Legendary]:       Game List Updated
(16:26:09) INFO:    [Legendary]:       Checking for game updates.
(16:26:09) INFO:    [Legendary]:       Running command: /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/legendary list-installed --check-updates --tsv
(16:26:19) INFO:    [Legendary]:       Found 1 game(s) to update
(16:26:19) INFO:    [Gog]:             Found 0 game(s) to update
(16:26:33) DEBUG:   [Legendary]:       Using cached install info
(16:26:33) ERROR:   [Backend]:         Shortcuts haven't been implemented in the current platform.
(16:26:33) INFO:    [Legendary]:       Checking if EOS Overlay is enabled: /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/legendary eos-overlay info
(16:26:38) DEBUG:   [Legendary]:       Using cached install info
(16:26:38) INFO:    [Legendary]:       Updating 9d2d0eb64d5c44529cece33fe2a46482: /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/legendary update 9d2d0eb64d5c44529cece33fe2a46482 -y
(16:26:38) DEBUG:   [Legendary]:       Logging to file "/Users/davidesparvoli/Library/Application Support/heroic/GamesConfig/9d2d0eb64d5c44529cece33fe2a46482.log"
(16:26:39) INFO:    [Backend]:         Preventing machine to sleep
(16:26:39) DEBUG:   [Legendary]:       Using cached install info

### Steps to reproduce

1. Go to 'Library'
2. Click on 'Play'
3. Click 'Yes' on the update popup
4. The game is not being updated

### Expected behavior

I expect the game to get updated 

### Screenshots

<img width="1440" alt="Schermata 2022-09-21 alle 16 33 55" src="https://user-images.githubusercontent.com/114039711/191533055-81538da3-19f5-458d-9229-757bfcf6372f.png">

### System Information

- OS: MacOS 12.4
- Heroic Version: 2.4.3

**Comment by flavioislima** [comment]
Try to click on Verify And Repair on the Tools Tab.
It will check the files and then will fix if needed and update the game afterwards.
Might take sometime though since GTA is a big game.
