### ISSUE TITLE
[Linux] Unhanded exception breaking game launch and other methods

### ISSUE THREAD

**Issue by dav-garcia** [Heroic-Games-Launcher/HeroicGamesLauncher#1831]
### Describe the bug

Any game installed (at least the Epic ones) fail to start very early, before running Wine.

When Heroic is launched from the command line, the following log is shown:
```
(13:44:53) INFO:    [Backend]:         Launching Horizon Chase Turbo (bb406082b69a47208489d3616b22b5c2)
(13:44:53) INFO:    [Backend]:         Preventing display from sleep
(13:44:53) INFO:    [Legendary]:       Running command: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary --version
(13:44:54) ERROR:   [Backend]:         Unable to create Wineprefix:  TypeError: Cannot read properties of undefined (reading 'toString')
(13:44:54) ERROR:   [Backend]:         TypeError: Cannot read properties of undefined (reading 'toString')
    at setupWineEnvVars (/opt/Heroic/resources/app.asar/build/launcher.js:184:70)
    at runWineCommand (/opt/Heroic/resources/app.asar/build/launcher.js:312:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
(13:44:54) INFO:    [Backend]:         Stopping Display Power Saver Blocker
```

The problem seems to be this value conversion: https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/blob/v2.4.3/electron/launcher.ts#L297
All my games' config are missing the `maxSharpness` setting, for example Horizon Chase Turbo:
```json
{
  "bb406082b69a47208489d3616b22b5c2": {
    "autoInstallDxvk": true,
    "autoInstallVkd3d": true,
    "preferSystemLibs": false,
    "enableEsync": true,
    "enableFSR": true,
    "enableFsync": true,
    "nvidiaPrime": false,
    "enviromentOptions": [],
    "wrapperOptions": [],
    "showFps": false,
    "useGameMode": false,
    "language": "",
    "wineVersion": {
      "bin": "/home/david/.config/heroic/tools/wine/Wine-GE-Proton7-25/bin/wine",
      "name": "Wine - Wine-GE-Proton7-25",
      "type": "wine",
      "lib": "/home/david/.config/heroic/tools/wine/Wine-GE-Proton7-25/lib64",
      "lib32": "/home/david/.config/heroic/tools/wine/Wine-GE-Proton7-25/lib",
      "wineserver": "/home/david/.config/heroic/tools/wine/Wine-GE-Proton7-25/bin/wineserver",
      "wineboot": "/home/david/.config/heroic/tools/wine/Wine-GE-Proton7-25/bin/wineboot"
    },
    "winePrefix": "/home/david/Games/Wine/HorizonChaseTurbo"
  },
  "version": "v0",
  "explicit": true
}
```
However, the UI settings for the game show the value "2" (see attached screenshot).
If I manually add the property to the JSON file or change the value from the UI, the game will start correctly.

### Add logs

```
System Info:
Heroic Version: 2.4.3 Chopper
Legendary Version:  0.20.28 Dark Energy (hotfix #2)
OS: Ubuntu KERNEL: 5.15.0-47-generic ARCH: x64
CPU: Intel Core™ i7-8565U @1.8 GOVERNOR: powersave
RAM: Total: 31.21 GiB Available: 22.66 GiB
GRAPHICS: GPU0: WhiskeyLake-U GT2 [UHD Graphics 620]  VRAM: 256MB DRIVER:  GPU1: GP108M [GeForce MX250]  VRAM: 32MB DRIVER:  
PROTOCOL: wayland

Game Settings: {
	"autoInstallDxvk": true,
	"autoInstallVkd3d": true,
	"preferSystemLibs": false,
	"enableEsync": true,
	"enableFSR": true,
	"enableFsync": true,
	"nvidiaPrime": false,
	"enviromentOptions": [],
	"wrapperOptions": [],
	"showFps": false,
	"useGameMode": false,
	"language": "",
	"wineVersion": {
		"bin": "/home/david/.config/heroic/tools/wine/Wine-GE-Proton7-25/bin/wine",
		"name": "Wine - Wine-GE-Proton7-25",
		"type": "wine",
		"lib": "/home/david/.config/heroic/tools/wine/Wine-GE-Proton7-25/lib64",
		"lib32": "/home/david/.config/heroic/tools/wine/Wine-GE-Proton7-25/lib",
		"wineserver": "/home/david/.config/heroic/tools/wine/Wine-GE-Proton7-25/bin/wineserver",
		"wineboot": "/home/david/.config/heroic/tools/wine/Wine-GE-Proton7-25/bin/wineboot"
	},
	"winePrefix": "/home/david/Games/Wine/HorizonChaseTurbo"
}

Game launched at: Thu Sep 22 2022 12:10:45 GMT+0200 (hora de verano de Europa central)

An exception occurred when launching the game:
TypeError: Cannot read properties of undefined (reading 'toString')
    at setupWineEnvVars (/opt/Heroic/resources/app.asar/build/launcher.js:184:70)
    at runWineCommand (/opt/Heroic/resources/app.asar/build/launcher.js:312:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
```

### Steps to reproduce

1. Go to any game.
2. Click on the "PLAY NOW" button.
3. Game won't start.
4. The error is shown in game settings -> logs.

### Expected behavior

The game starts.

### Screenshots

![image](https://user-images.githubusercontent.com/17596200/191739934-679c2cca-2018-47b4-9d36-3fcc473933e7.png)

### System Information

- OS [e. g. "Ubuntu"]: Ubuntu 22.04
- Heroic Version [e. g. 2.1.1]: 2.4.3

### Additional information

Maybe related: #1777

**Comment by flavioislima** [comment]
Nice that you found this issue, makes sense that this Wine call is breaking some other things around, we should stop doing like this:
`ret.WINE_FULLSCREEN_FSR_STRENGTH = gameSettings.maxSharpness.toString()
`

And add always a backup value like this:
` ret.WINE_FULLSCREEN_FSR_STRENGTH = (gameSettings?.maxSharpness && gameSettings?.maxSharpness?.toString()) || 2
`

Will add a label to be fixed asap and also look for other things like this that could break.

**Comment by flavioislima** [comment]
I tried to reproduce the error now:
- Went to my CP2077 config file
- removed the maxSharpening config
- Launched the game, and it worked fine
- looked at the config it was still without the maxSharpening
- Went to Save sync, removed the folder that was there
- left the settings screen
- confirmed that the setting was still missing in my config file
- went to save sync config and it worked fine.

So it is hard to know if that is really the issue here 🤔

**Comment by syphr42** [comment]
I just installed HGL on Ubuntu 22.04 using Flatpak (HGL version 2.4.3) and I seem to be running into this bug. 

After installing HGL, I did the following:
* Logged into both EGL and GOG
* Downloaded a single game from EGL
* Downloaded the latest Wine GE using the Wine Manager in HGL (Wine-GE-Proton7-34)
* Edited settings by enabling:
  * FSR hack
  * esync
  * fsync
  * DXVK
  * VKD3D
  * EAC runtime
  * BattleEye runtime
  * GameMode

When I attempt to launch the game, it immediately fails.

Logs show this:
```
(17:46:22) ERROR:   [Backend]:         Unable to create Wineprefix:  TypeError: Cannot read properties of undefined (reading 'toString')
(17:46:22) ERROR:   [Backend]:         TypeError: Cannot read properties of undefined (reading 'toString')
    at setupWineEnvVars (/app/bin/heroic/resources/app.asar/build/launcher.js:184:70)
    at runWineCommand (/app/bin/heroic/resources/app.asar/build/launcher.js:312:12)
```

I went back and undid all my configuration changes, but it made no difference.

**Comment by arielj** [comment]
@syphr42 can you try with Heroic 2.5.0-beta.2? to check if this is still an issue

**Comment by syphr42** [comment]
@arielj 

I tried re-enabling FSR and changing the sharpness value. Result is the same on 2.4.3 with the game failing to launch and the same error. The sharpness value also seems to revert. Doesn't look like it's saving to the config file which may have been part of the problem.

It is possible to install the beta via flatpak? I don't see it on Flathub.

**Comment by arielj** [comment]
> @arielj
> 
> I tried re-enabling FSR and changing the sharpness value. Result is the same on 2.4.3 with the game failing to launch and the same error. The sharpness value also seems to revert. Doesn't look like it's saving to the config file which may have been part of the problem.
> 
> It is possible to install the beta via flatpak? I don't see it on Flathub.

you have to add the flathub-beta repo https://twitter.com/HeroicLauncher/status/1518629474081849344 (you may also need this other command)

then it should show up to install

**Comment by syphr42** [comment]
I can confirm that the beta does fix this error.

However, now there is a new error. It fails to install DXVK because it appears to be looking in the wrong place for the setup script.

The error says it cannot be found here:

`~/.var/app/com.heroicgameslauncher.hgl/config/heroic/tools/vkd3d/vkd3d-proton-2.7.tar.xz/setup*.sh`

However, I did find a setup script here:

`~/.var/app/com.heroicgameslauncher.hgl/config/heroic/tools/vkd3d/vkd3d-proton-2.7/setup_vkd3d_proton.sh`

This problem does not seem to be related to the original issue here though.

**Comment by tete1700pro** [comment]
acabo de instalar heroic games launcher y me aparece este error que no me perimite inciar juegos no se como solucionarlo
![captura error eroic](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/assets/150873547/32280c4c-15ce-4285-9bd5-4aa60367e827)

**Comment by flavioislima** [comment]
> acabo de instalar heroic games launcher y me aparece este error que no me perimite inciar juegos no se como solucionarlo
> ![captura error eroic](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/assets/150873547/32280c4c-15ce-4285-9bd5-4aa60367e827)
> 

This seems to be a different issue than above. Please open a new issue.

Fill as many information as possible and make sure your system is supported. You can read the list of supported distros on our Readme here on github.

If that is not the case try to open an issue on our discord support channel.
