### ISSUE TITLE
[Feature request] Allow customized native Linux executables in GOG

### ISSUE THREAD

**Issue by hfc2x** [Heroic-Games-Launcher/HeroicGamesLauncher#1833]
### Problem description

The GOG Galaxy executable in Windows allows games to have custom executables, which is useful for when games have community-made engines, which are more feature-rich than what is provided in the store, due to the games being open sourced (for example [Doom](https://github.com/chocolate-doom/chocolate-doom)), or reverse-engineered (like [Diablo](https://github.com/diasurgical/devilutionX)). In the case of DOS-only games, they can still run in the native Linux version of [DOSBox](https://sourceforge.net/projects/dosbox/).

Heroic Games Launcher does allow custom executables, but only Windows ones. Games that are listed as Windows-only don't allow Linux executables to be specified, since they're forced to run through Wine.

### Feature description

Allow the addition of a custom executable (possibly with a warning to let the user know if they break something, it's on them), and let the user choose if it's a native Linux application or a Windows one. For Linux, let the user either browse for an executable, or allow them to type the command they want to execute. For Windows, present them with the options already implemented, where they specify a Wine version and Wineprefix.

For example, in GOG's application settings, you see something like this:
![GOG application settings](https://user-images.githubusercontent.com/8249996/191829223-9cf23336-0d61-492b-b73c-464ae08dc517.png)

In the example, DUSK has a default executable, which is what launches when you press the Play button, but it also has other executables, and at the bottom, there's an option to add your own personalized executable parameters.

### Alternatives

Running the native executables through GOG Galaxy in Wine with `wine cmd /c [executable]`, but it doesn't work.

**Comment by flavioislima** [comment]
If you mean running a different binary/executable when launching a game (to skip a launcher for instance) this is already possible in Heroic:

![image](https://user-images.githubusercontent.com/26871415/192100826-0dba4a59-8622-44bf-98d8-eb6d7b40156a.png)

Maybe the naming means like you need to select a EXE from windows but it is actually any type of file, can be a shell script for instance.

**Comment by hfc2x** [comment]
So, if launching a shell script or a native Linux application, does it mean that Heroic is not going to use Wine to run it?

**Comment by imLinguin** [comment]
It just overwrites the executable. Wine and other wrappers are still used.

**Comment by flavioislima** [comment]
> So, if launching a shell script or a native Linux application, does it mean that Heroic is not going to use Wine to run it?

Yes.
If it is a native Linux game it needs to be a Linux binary as well that you select there.

**Comment by hfc2x** [comment]
Yes, but I mean this suggestion for Windows games that do have community-made Linux executables, which aren't natively supported by GOG, such as [Unreal Tournament](https://github.com/OldUnreal/UnrealTournamentPatches), for example.

**Comment by flavioislima** [comment]
That's pretty complicated to achieve because then we would need to run a native executable to run a windows game if I understood it correctly.
So this is a pretty edge case and do not worth the effort imo.

Maybe when we add the possibility to add and run any game outside Epic/GOG this can be achieved but not as a independent feature.

**Comment by hfc2x** [comment]
> That's pretty complicated to achieve because then we would need to run a native executable to run a windows game if I understood it correctly.

No, that was not it. What I was talking about is something like the feature Lutris has to allow the user to either select a native Linux application (which runs directly), or a Windows EXE application (which runs through Wine):

![2022-10-02_20-17](https://user-images.githubusercontent.com/8249996/193480655-015d80b9-ee99-4e1f-9c9e-908bc6571299.png)

The example I gave about Unreal Tournament was because that particular fan-made patch creates both a Windows executable (UnrealTournament.exe) and a Linux executable (ut-bin) in the game's install directory, and what you run depends on what you need, since both get installed regardless of your operating system.

There's nothing complicated about running a native Linux executable other than Wine (which is also a native Linux executable), in my opinion.

**Comment by flavioislima** [comment]
Ah, this is what I'm working on right now and will be available on next beta release.

**Comment by hfc2x** [comment]
Oh, that's nice! Great to know :D

**Comment by poyo86** [comment]
> Ah, this is what I'm working on right now and will be available on next beta release.

@flavioislima hey, sorry to bump this since this was closed so long ago. Was this ever properly implemented?

I stumbled across this problem yesterday when I tried to play GOG's Morrowind (a Windows game) using OpenMW's Linux build. I was looking for a way to change the game's platform from Windows to Linux but didn't find any. Another notable game would be DOOM, which on GOG is a Windows game but has countless native source ports.

Thanks to https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/issues/1833#issuecomment-1256970307 I learned that I could set the Linux executable and it would work. And it does work. However, Heroic still uses Proton to launch the custom Linux executable which can cause issues and is a waste of resources. Ideally Proton wouldn't be used when the custom binary is not a Windows one, or the user would have the choice to disable Proton altogether. Should this issue be reopened?

**Comment by arielj** [comment]
> > Ah, this is what I'm working on right now and will be available on next beta release.
> 
> [@flavioislima](https://github.com/flavioislima) hey, sorry to bump this since this was closed so long ago. Was this ever properly implemented?
> 
> I stumbled across this problem yesterday when I tried to play GOG's Morrowind (a Windows game) using OpenMW's Linux build. I was looking for a way to change the game's platform from Windows to Linux but didn't find any. Another notable game would be DOOM, which on GOG is a Windows game but has countless native source ports.
> 
> Thanks to [#1833 (comment)](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/issues/1833#issuecomment-1256970307) I learned that I could set the Linux executable and it would work. And it does work. However, Heroic still uses Proton to launch the custom Linux executable which can cause issues and is a waste of resources. Ideally Proton wouldn't be used when the custom binary is not a Windows one, or the user would have the choice to disable Proton altogether. Should this issue be reopened?

what you want is this feature https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/pull/4608 but it was not merged yet
