### ISSUE TITLE
User Categories for EGS

### ISSUE THREAD

**Issue by dtantono** [Heroic-Games-Launcher/HeroicGamesLauncher#1838]
### Problem description

With big libraries, especially with the free games from Epic, it can be really hard to browse the library.

### Feature description

Ability to create categories and manage categories categories, something like Steams collections.

### Alternatives

EGS already shipped Favorites and Collections (https://trello.com/c/Oqw02CJf/453-favorites-collections) Heroic can do the same .

### Additional information

I know you already close this before (https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/issues/1275) because it is not implemented yet at that time. But, since this feature already implemented now. it will be good and beneficial

**Comment by flavioislima** [comment]
You can already use Favorites and Hide games on Heroic to organize your collection.
We can also add a feature of creating Labels so you could organize and filter the games using it. That should do the trick?

To use the EGS specific collections we would need to get the info from their API, we would need to check if that's available.

**Comment by dtantono** [comment]
yeah create label is nice temporary workaround because if our library grows larger, that will be quite messy to manage also Create favorites and hide games is not enough. By the way, it will be great if we have nice EGS specific collections.

**Comment by flavioislima** [comment]
> EGS specific collections.

What do you mean and how that would work?

**Comment by dtantono** [comment]
I saw EGS native Windows client use tabs horizontally to organise collections (max 11 collections atm). it looks good to mirror it. But, if you want to create collections feature like Steam with flashy icons or separate grid in List view. that also great. it's your call.

**Comment by flavioislima** [comment]
Yes, we try to keep Heroic as independent as possible from EGS and use only the necessary features because HEroic is not only an Epic games launcher and we will add more stores in the future so ideally, the collections inside Heroic should be it's own thing.

**Comment by arielj** [comment]
Closing, we have this feature of creating custom categories since 2.11.0
