### ISSUE TITLE
[Feature request] Steam like multi-library

### ISSUE THREAD

**Issue by Sporesirius** [Heroic-Games-Launcher/HeroicGamesLauncher#1840]
### Problem description

Currently, it is relatively more difficult to manage different games on different storage media than on Steam.

### Feature description

A multi-library, like Steam has implemented.

**Comment by arielj** [comment]
what is a `multi library`? can you define what features that would mean? I'm not familiar with the idea

**Comment by flavioislima** [comment]
I think the idea is to have Folders with games in different partitions like steam does, I believe we already have a feature request for that with examples #1673 

Will mark this one as duplicate.
