### ISSUE TITLE
[Epic Games] 404 error "store page" from Games' Tools tab for some games

### ISSUE THREAD

**Issue by Oaklight** [Heroic-Games-Launcher/HeroicGamesLauncher#1842]
### Describe the bug

Some of my Epic games have 404 error when I click the "Store Page" on their Tools tab.
![截图_选择区域_20220924053421](https://user-images.githubusercontent.com/13076552/192093376-ed101bbe-33de-44d8-b401-79ae2411c537.png)
However, I can view these games' pages without issue when I search directly in Epic game store.
For instance, here are some I tested:
Hundred Days - Winemaking Simulator
The Lion's Song
Brothers - A Tale of Two Sons
Ghostwire: Tokyo - Prelude

### Add logs

(05:03:51) INFO:    [Legendary]:       Running command: /home/me/mambaforge/bin/legendary --version
(05:03:52) INFO:    [Legendary]:       Legendary location: /home/me/mambaforge/bin/legendary
(05:03:52) INFO:    [Gog]:             GOGDL location: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl
(05:03:52) INFO:    [Backend]:         

Heroic Version: 2.4.3 Chopper
Legendary Version:  0.20.29 Dark Energy (hotfix #3)
OS: Deepin KERNEL: 5.18.4-amd64-desktop-hwe ARCH: x64
CPU: AMD Ryzen 5 3600 6-Core Processor @3.6 GOVERNOR: powersave
RAM: Total: 31.28 GiB Available: 18.81 GiB
GRAPHICS: GPU0: TU106 [GeForce RTX 2060 Rev. A]  VRAM: 32MB DRIVER:  
PROTOCOL: x11

(05:03:52) INFO:    [Gog]:             Getting data about the user
(05:03:52) WARNING: [Backend]:         Failed to register protocol with OS.
(05:03:52) INFO:    [Backend]:         AreWeAntiCheatYet data downloaded
(05:03:52) INFO:    [Gog]:             Saved user data to config
(05:03:53) INFO:    [Backend]:         Checking for new Heroic Updates
(05:03:53) INFO:    [Frontend]:        Refreshing Library
(05:03:53) INFO:    [Legendary]:       Refreshing library...
(05:03:53) INFO:    [Legendary]:       Refreshing Epic Games...
(05:03:53) INFO:    [Gog]:             Getting GOG library
(05:03:54) INFO:    [Gog]:             Number of library pages: 1
(05:03:54) INFO:    [Legendary]:       Running command: /home/me/mambaforge/bin/legendary list
(05:03:54) INFO:    [Legendary]:       Updating game list
(05:03:54) INFO:    [Legendary]:       Game List Updated
(05:03:54) INFO:    [Gog]:             Saved games data
(05:03:55) INFO:    [Backend]:         Downloaded Winetricks
(05:03:55) INFO:    [Legendary]:       Checking for game updates.
(05:03:55) INFO:    [Legendary]:       Running command: /home/me/mambaforge/bin/legendary list-installed --check-updates --tsv
(05:03:55) INFO:    [Legendary]:       Found 0 game(s) to update
(05:03:55) INFO:    [Gog]:             Found 0 game(s) to update
(05:04:35) INFO:    [Legendary]:       Getting Info from Epic API
(05:04:35) INFO:    [Legendary]:       Getting Info from Epic API
(05:04:35) INFO:    [Legendary]:       Getting more details with 'legendary info'
(05:04:36) INFO:    [Legendary]:       Running command: /home/me/mambaforge/bin/legendary --pretty-json info ac8f20a7931e4d63a1db4dc1267ec3d1 --platform Windows --json
(05:05:09) DEBUG:   [Legendary]:       Using cached install info
(05:05:16) INFO:    [Legendary]:       Getting Info from Epic API
(05:05:16) INFO:    [Legendary]:       Getting Info from Epic API
(05:05:16) INFO:    [Legendary]:       Getting more details with 'legendary info'
(05:05:17) INFO:    [Legendary]:       Running command: /home/me/mambaforge/bin/legendary --pretty-json info 90185b9fc481480097f52d86921dc08c --platform Windows --json
(05:05:21) DEBUG:   [Legendary]:       Using cached install info
(05:33:32) INFO:    [Legendary]:       Running command: /home/me/mambaforge/bin/legendary --version
(05:33:32) INFO:    [Gog]:             Running command: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --version
(05:33:50) INFO:    [Backend]:         Changing Language to: en
(05:33:55) INFO:    [Legendary]:       Getting Info from Epic API
(05:33:55) INFO:    [Legendary]:       Getting Info from Epic API
(05:33:55) DEBUG:   [Legendary]:       Using cached install info
(05:33:55) INFO:    [Legendary]:       Checking if EOS Overlay is enabled: /home/me/mambaforge/bin/legendary eos-overlay info --prefix /media/me/Vault/HeroicLibrary/Prefixes/TheLionsSong/pfx
(05:34:06) DEBUG:   [Legendary]:       Using cached install info
(05:34:06) INFO:    [Legendary]:       Checking if EOS Overlay is enabled: /home/me/mambaforge/bin/legendary eos-overlay info --prefix /media/me/Vault/HeroicLibrary/Prefixes/TheLionsSong/pfx

### Steps to reproduce

1. Go to one of these games listed above (there might be others)
2. Click on "Tools" 
3. Scroll down to "Store Page" and click
4. See 404 error

### Expected behavior

The webpage should display without error from "Store Page" on the "Tools" tab

### Screenshots

![截图_heroic_20220924054135](https://user-images.githubusercontent.com/13076552/192093667-b99878f6-1fb1-45dd-ae1f-02ce2c70e532.png)

![截图_heroic_20220924054151](https://user-images.githubusercontent.com/13076552/192094036-d53b4513-5d2c-4a73-b2a2-c56a1ac55812.png)

### System Information

- OS [e. g. "Ubuntu"]: Deepin 20.7
- Heroic Version [e. g. 2.1.1]: 2.4.3
- Legendary Version: `"0.20.29", codename "Dark Energy (hotfix #3)"` (installed by `pip install legendary-gl[webview]`)

**Comment by flavioislima** [comment]
Yes, that is a known issue with some games.
Epic doesn't follow a convention to their links on store page so sometimes the name of the game won't match.

A solution for that would be to check the info we are getting on their graphiql API and check if we can get a URL and use it instead of appending the game name.

**Comment by flavioislima** [comment]
Noticed that this is duplicated of #1160 
we have more info there so will close this one.
