### ISSUE TITLE
Not working on Windows 7

### ISSUE THREAD

**Issue by MechanosG** [Heroic-Games-Launcher/HeroicGamesLauncher#1844]
### Describe the bug

When trying to use Heroic Games Launcher 2.4.3 for the first time on a Windows 7 install, both the portable version and the install version, do not pop up visible windows.  For example, with the portable version I can open task manager and see that 3 instances of Heroic.exe are running, with 0 CPU usage.  It would appear everything was created properly in the Temp folder, but no GUI is visible.

### Add logs

Unable to get a log since the program doesn't become visible, and I don't see a log file.

### Steps to reproduce

1. Download HGL 2.4.3, portable or installer, save to D:\HGL
2. Run the exe
3. Open task manager to confirm that the processes have opened
4. Wait 10 minutes, just in case something's happening in the back ground - nuffin.

### Expected behavior

I would expect some kind of window/GUI to open.

### Screenshots

Not really applicable.

### System Information

- OS [e. g. "Ubuntu"]: Windows 7 Ultimate 64bit
- Heroic Version [e. g. 2.1.1]: 2.4.3, both Portable and Setup variants tried

### Additional information

I'm really hoping I can get this working.  For some reason, GOG has decided to drop Windows 7 support in GOG Galaxy (they're doing the same with Cyberpunk 2077 as well).  Some people posting in the forums, claim it's because CD Projekt Red wants to use some telemetry services only in Win8/10/11.  Like many people however, Windows 7 will be my last Microsoft OS.  I'll be eventually moving to linux Mint.  In the mean time, HGL is probably my best bet to access GOG.

**Comment by flavioislima** [comment]
Windows 7 is not supported. Please check the list of supported operating system on the readme.

**Comment by MechanosG** [comment]
The website has no readme.  The documentation button goes to the wiki, which has no section for supported OS.  But okay.  Dangit.

**Comment by flavioislima** [comment]
> The website has no readme.  The documentation button goes to the wiki, which has no section for supported OS.  But okay.  Dangit.

It is on the github readme but you are right. Will add it to the website and wiki as well. 👍

**Comment by Patraskon** [comment]
Could it be a good alternative to Steam in 2024?
