### ISSUE TITLE
After last Kena bridge of spirits update, Kena does not start any more

### ISSUE THREAD

**Issue by anaselli** [Heroic-Games-Launcher/HeroicGamesLauncher#1849]
### Describe the bug

I'm using Heroic Launcher from flatpack on linux mageia 8.

Last Kena bridge of spirits update needs UE4 installed.

![immagine](https://user-images.githubusercontent.com/1303486/193006378-756c886c-5917-47e1-bea7-7d9b47072552.png)

All seems to go but during installation:
![immagine](https://user-images.githubusercontent.com/1303486/193007030-67efb193-f802-478d-919a-8508ddf87094.png)

I tried on lutris with Epic launcher and even if gave an error at last game started.

I tried to run UE4 installer from prefix with the same final effect.

### Add logs

System Info:
Heroic Version: 2.4.3 Chopper
Legendary Version:  0.20.28 Dark Energy (hotfix #2)
OS: Freedesktop SDK KERNEL: 5.15.65-desktop-1.mga8 ARCH: x64
CPU: AMD Ryzen 9 3900X 12-Core Processor @3.8 GOVERNOR: schedutil
RAM: Total: 31.27 GiB Available: 27.69 GiB
GRAPHICS: GPU0: TU106 [GeForce RTX 2060 Rev. A]  VRAM: 32MB DRIVER:  
PROTOCOL: x11

Game Settings: {
	"autoInstallDxvk": true,
	"autoInstallVkd3d": true,
	"preferSystemLibs": false,
	"enableEsync": true,
	"enableFsync": true,
	"maxSharpness": 2,
	"nvidiaPrime": false,
	"enviromentOptions": [],
	"wrapperOptions": [],
	"savesPath": "",
	"showFps": false,
	"targetExe": "",
	"useGameMode": false,
	"language": "",
	"wineVersion": {
		"bin": "/home/angelo/.var/app/com.heroicgameslauncher.hgl/config/heroic/tools/wine/Wine-GE-Proton7-29/bin/wine",
		"name": "Wine - Wine-GE-Proton7-29",
		"type": "wine",
		"lib": "/home/angelo/.var/app/com.heroicgameslauncher.hgl/config/heroic/tools/wine/Wine-GE-Proton7-29/lib64",
		"lib32": "/home/angelo/.var/app/com.heroicgameslauncher.hgl/config/heroic/tools/wine/Wine-GE-Proton7-29/lib",
		"wineserver": "/home/angelo/.var/app/com.heroicgameslauncher.hgl/config/heroic/tools/wine/Wine-GE-Proton7-29/bin/wineserver",
		"wineboot": "/home/angelo/.var/app/com.heroicgameslauncher.hgl/config/heroic/tools/wine/Wine-GE-Proton7-29/bin/wineboot"
	},
	"winePrefix": "/run/user/1001/doc/7432b0f6/Prefixes/KenaBridgeOfSpirits",
	"wineCrossoverBottle": "Heroic",
	"eacRuntime": false,
	"battlEyeRuntime": false,
	"gogSaves": []
}

Game launched at: Thu Sep 29 2022 12:18:45 GMT+0200 (Ora legale dell’Europa centrale)

Launch Command: LD_LIBRARY_PATH=/home/angelo/.var/app/com.heroicgameslauncher.hgl/config/heroic/tools/wine/Wine-GE-Proton7-29/lib:/home/angelo/.var/app/com.heroicgameslauncher.hgl/config/heroic/tools/wine/Wine-GE-Proton7-29/lib64: WINEPREFIX=/run/user/1001/doc/7432b0f6/Prefixes/KenaBridgeOfSpirits WINEESYNC=1 WINEFSYNC=1 /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary launch 70b920b3d9b145d682ecaacae52fc4cb --language it  --wine /home/angelo/.var/app/com.heroicgameslauncher.hgl/config/heroic/tools/wine/Wine-GE-Proton7-29/bin/wine --wine-prefix /run/user/1001/doc/7432b0f6/Prefixes/KenaBridgeOfSpirits

Game Log:
[cli] INFO: Logging in...
[Core] INFO: Trying to re-use existing login session...
[cli] INFO: Checking for updates...
[Core] INFO: Getting authentication token...
[cli] INFO: Launching 70b920b3d9b145d682ecaacae52fc4cb...
esync: up and running.
wine: RLIMIT_NICE is <= 20, unable to use setpriority safely

Legendary update available!
- New version: 0.20.29 - "Dark Energy (hotfix #3)"
- Release summary:
 [!] Adds workaround for Epic CDN issue (403 when downloading manifest)
 [!] Fixes potential zero division error when verifying large files on fast SSDs
See full changelog for additional details.
- Release URL: https://legendary.gl/release/0.20.29
! This update is recommended as it fixes major issues.

- Download URL: https://legendary.gl/release/download/0.20.29/legendary
002c:fixme:winediag:LdrInitializeThunk wine-staging 7.0 is a testing version containing experimental patches.
002c:fixme:winediag:LdrInitializeThunk Please mention your exact version when filing bug reports on winehq.org.
011c:fixme:imm:ImeSetActiveContext (0xe60210, 1): stub
011c:fixme:imm:ImmReleaseContext (0000000000010066, 0000000000E60210): stub
0058:fixme:imm:ImeSetActiveContext (0x4803d0, 0): stub
0058:fixme:imm:ImmReleaseContext (0000000000010020, 00000000004803D0): stub
0114:fixme:oleacc:find_class_data unhandled window class: L"Static"
0114:fixme:oleacc:find_class_data unhandled window class: L"Button"
0114:fixme:oleacc:find_class_data unhandled window class: L"Button"
0114:fixme:oleacc:find_class_data unhandled window class: L"Static"
0114:fixme:oleacc:find_class_data unhandled window class: L"#32770"
0114:fixme:oleacc:find_class_data unhandled window class: L"Button"
0114:fixme:oleacc:find_class_data unhandled window class: L"#32769"
0114:fixme:oleacc:find_class_data unhandled window class: L"Button"
0114:fixme:oleacc:find_class_data unhandled window class: L"#32769"
0114:fixme:oleacc:find_class_data unhandled window class: L"Button"
0128:fixme:heap:RtlSetHeapInformation unimplemented HeapEnableTerminationOnCorruption
0134:fixme:heap:RtlSetHeapInformation unimplemented HeapEnableTerminationOnCorruption
0134:fixme:advapi:DecryptFileW (L"C:\\users\\anaselli\\Temp\\{0d995f46-317b-4b5f-bf3e-9f98bae9d339}\\", 00000000): stub
013c:fixme:imm:ImeSetActiveContext (0x2370030, 1): stub
013c:fixme:imm:ImmReleaseContext (0003006E, 02370030): stub
0140:fixme:imm:ImeSetActiveContext (0x2370030, 1): stub
0140:fixme:imm:ImmReleaseContext (0001007C, 02370030): stub
0128:fixme:ole:CoInitializeSecurity 006AF664, -1, 00000000, 00000000, 6, 2, 00000000, 12288, 00000000 stub
0148:fixme:shell:SHAutoComplete stub
0148:err:richedit:ReadStyleSheet missing style number
0114:fixme:oleacc:find_class_data unhandled window class: L"Button"
0114:fixme:oleacc:find_class_data unhandled window class: L"Button"
0114:fixme:oleacc:find_class_data unhandled window class: L"Static"
0114:fixme:oleacc:find_class_data unhandled window class: L"Static"
0114:fixme:oleacc:find_class_data unhandled window class: L"Static"
0114:fixme:oleacc:find_class_data unhandled window class: L"Static"
0114:fixme:oleacc:find_class_data unhandled window class: L"Button"
0114:fixme:oleacc:find_class_data unhandled window class: L"Button"
0114:fixme:oleacc:find_class_data unhandled window class: L"Static"
0114:fixme:oleacc:find_class_data unhandled window class: L"Button"
0114:fixme:oleacc:find_class_data unhandled window class: L"Static"
0114:fixme:oleacc:find_class_data unhandled window class: L"Static"
0114:fixme:oleacc:find_class_data unhandled window class: L"Static"
0114:fixme:oleacc:find_class_data unhandled window class: L"Button"
0114:fixme:oleacc:find_class_data unhandled window class: L"Button"
0114:fixme:oleacc:find_class_data unhandled window class: L"Static"
0114:fixme:oleacc:find_class_data unhandled window class: L"Static"
0114:fixme:oleacc:find_class_data unhandled window class: L"Static"
0114:fixme:oleacc:find_class_data unhandled window class: L"Button"
0114:fixme:oleacc:find_class_data unhandled window class: L"msctls_progress32"
0114:fixme:oleacc:find_class_data unhandled window class: L"Static"
0114:fixme:oleacc:find_class_data unhandled window class: L"Static"
0114:fixme:oleacc:find_class_data unhandled window class: L"Static"
0114:fixme:oleacc:find_class_data unhandled window class: L"Static"
0114:fixme:oleacc:find_class_data unhandled window class: L"Static"
0114:fixme:oleacc:find_class_data unhandled window class: L"Button"
0114:fixme:oleacc:find_class_data unhandled window class: L"Button"
0114:fixme:oleacc:find_class_data unhandled window class: L"Button"
0114:fixme:oleacc:find_class_data unhandled window class: L"Static"
0114:fixme:oleacc:find_class_data unhandled window class: L"Static"
0114:fixme:oleacc:find_class_data unhandled window class: L"Static"
0114:fixme:oleacc:find_class_data unhandled window class: L"Static"
0114:fixme:oleacc:find_class_data unhandled window class: L"Button"
0114:fixme:oleacc:find_class_data unhandled window class: L"Button"
0114:fixme:oleacc:find_class_data unhandled window class: L"Button"
0114:fixme:oleacc:find_class_data unhandled window class: L"Static"
0114:fixme:oleacc:find_class_data unhandled window class: L"RichEdit20W"
0114:fixme:oleacc:find_class_data unhandled window class: L"Static"
0114:fixme:oleacc:find_class_data unhandled window class: L"Static"
0114:fixme:oleacc:find_class_data unhandled window class: L"Static"
0114:fixme:oleacc:find_class_data unhandled window class: L"Button"
0114:fixme:oleacc:find_class_data unhandled window class: L"Static"
0114:fixme:oleacc:find_class_data unhandled window class: L"Static"
0114:fixme:oleacc:find_class_data unhandled window class: L"Static"
0114:fixme:oleacc:find_class_data unhandled window class: L"Static"
0114:fixme:oleacc:find_class_data unhandled window class: L"RichEdit20W"
0114:fixme:oleacc:find_class_data unhandled window class: L"Button"
0114:fixme:oleacc:find_class_data unhandled window class: L"Button"
0114:fixme:oleacc:find_class_data unhandled window class: L"Button"
0114:fixme:oleacc:find_class_data unhandled window class: L"Button"
0134:fixme:advapi:DecryptFileW (L"C:\\users\\anaselli\\Temp\\{0d995f46-317b-4b5f-bf3e-9f98bae9d339}\\", 00000000): stub
0114:fixme:oleacc:find_class_data unhandled window class: L"Button"
0128:fixme:wuapi:automatic_updates_Pause 
0128:fixme:sfc:SRSetRestorePointW 006AF538 006AF748
0150:fixme:wininet:InternetSetOptionW INTERNET_OPTION_SEND/RECEIVE_TIMEOUT/DATA_SEND_TIMEOUT 120000
0150:fixme:wininet:InternetSetOptionW INTERNET_OPTION_SEND/RECEIVE_TIMEOUT/DATA_SEND_TIMEOUT 120000
0150:err:kerberos:kerberos_LsaApInitializePackage no Kerberos support, expect problems
0150:err:ntlm:ntlm_LsaApInitializePackage no NTLM support, expect problems
0144:fixme:cryptasn:CRYPT_GetBuiltinDecoder Unsupported decoder for lpszStructType 1.3.6.1.4.1.311.2.1.4
0144:fixme:cryptasn:CRYPT_GetBuiltinDecoder Unsupported decoder for lpszStructType 1.3.6.1.4.1.311.2.1.4
0144:fixme:cryptasn:CRYPT_GetBuiltinDecoder Unsupported decoder for lpszStructType 1.3.6.1.4.1.311.2.1.4
0144:fixme:cryptasn:CRYPT_GetBuiltinDecoder Unsupported decoder for lpszStructType 1.3.6.1.4.1.311.2.1.4
0144:fixme:cryptasn:CRYPT_GetBuiltinDecoder Unsupported decoder for lpszStructType 1.3.6.1.4.1.311.2.1.4
0144:fixme:cryptasn:CRYPT_GetBuiltinDecoder Unsupported decoder for lpszStructType 1.3.6.1.4.1.311.2.1.4
0144:fixme:file:NtLockFile I/O completion on lock not implemented yet
wineserver: file_set_error() can't map error: Function not implemented
0144:fixme:storage:get_lock_error no mapping for error 31
wineserver: file_set_error() can't map error: Function not implemented
0144:fixme:storage:get_lock_error no mapping for error 31
wineserver: file_set_error() can't map error: Function not implemented
0144:fixme:storage:get_lock_error no mapping for error 31
wineserver: file_set_error() can't map error: Function not implemented
0144:fixme:storage:get_lock_error no mapping for error 31
wineserver: file_set_error() can't map error: Function not implemented
0144:fixme:storage:get_lock_error no mapping for error 31
wineserver: file_set_error() can't map error: Function not implemented
0144:fixme:storage:get_lock_error no mapping for error 31
0114:fixme:oleacc:find_class_data unhandled window class: L"Button"
0114:fixme:oleacc:find_class_data unhandled window class: L"#32769"
0114:fixme:oleacc:find_class_data unhandled window class: L"#32769"
0114:fixme:oleacc:find_class_data unhandled window class: L"Button"
0128:fixme:wuapi:automatic_updates_Resume 
011c:fixme:kernelbase:AppPolicyGetProcessTerminationMethod FFFFFFFFFFFFFFFA, 0000000000B9FEB0

### Steps to reproduce

1. Go to run game
2. Click on yes
3. Install UE4

### Expected behavior

After installing UE4 game should start as before

### System Information

- OS Linux Mageia 8
- Heroic Version 2.4.3

**Comment by flavioislima** [comment]
The game is being launched, you are getting an error from wine, not heroic.
Open a discussion or try to get help on discord
