### ISSUE TITLE
Updates too big

### ISSUE THREAD

**Issue by gabriele2000** [Heroic-Games-Launcher/HeroicGamesLauncher#1858]
### Describe the bug

Game: The Cycle - Frontier

Basically everyone says "oh my download size was 200MB" or something like that, then the log says "Oh I need to download 2GB of data".

Either it's something missing from Legendary, or something's horribly wrong.

### Add logs

[Core] INFO: Trying to re-use existing login session...
[cli] INFO: Preparing download for "The Cycle: Frontier" (AzaleaAlpha)...
[Core] INFO: Parsing game manifest...
[Core] INFO: Install path: /mnt/SOS/TheCycleEarlyAccess
[Core] INFO: Selected CDN: epicgames-download1.akamaized.net (https)
[cli] INFO: Install size: 37000.17 MiB
[cli] INFO: **Download size: 2050.17 MiB (Compression savings: 51.1%)**
[cli] INFO: Reusable size: 31843.29 MiB (chunks) / 974.47 MiB (unchanged / skipped)
[cli] INFO: Downloads are resumable, you can interrupt the download with CTRL-C and resume it using the same command later on.

### Steps to reproduce

1: Update The Cycle: Frontier using Linux
2: Boom, everyone will tell you that they downloaded way less than you.

### Expected behavior

Small updates, not huge redownloads.

### System Information

- OS: Pop!_Os 22.04
- Heroic Version: 2.4.3

### Additional information

The game is downloading the Windows version, of course.
I shouldn't have to download more than everyone else.

**Comment by arielj** [comment]
If you think it's an issue in Legendary you should report this to the Legendary github, not here

**Comment by gabriele2000** [comment]
> If you think it's an issue in Legendary you should report this to the Legendary github, not here

Sorry, I was thinking the same thing but maybe someone else had that problem too...
