### ISSUE TITLE
Unreal Engine support

### ISSUE THREAD

**Issue by DavidRLTG** [Heroic-Games-Launcher/HeroicGamesLauncher#1859]
### Problem description

I really, really wanna switch to HGL, but I simply cannot because it does not have a way to install and launch Unreal Engine, and it does not have Unreal Marketplace, or the Unreal Library. Help!

### Feature description

Please, add Unreal Engine installing and launching, Unreal Marketplace, and Unreal Library, and a UE project manager. Like EGL!

### Alternatives

I just use EGL for now, haha

### Additional information

please help c:

**Comment by arielj** [comment]
We used to have support for the Unreal Marketplace but it was broken an unmaintained and it was removed. We don't plan to support Unreal Engine in the near future since there are better alternatives.

Can't you use the market place from Unreal Engine itself?

**Comment by arielj** [comment]
Unreal Engine can be downloaded directly from their website https://www.unrealengine.com/en-US/linux

**Comment by DavidRLTG** [comment]
Well, I can only use UE and not any alternatives because of my bought assets, megascans and metahumans, and since it's easier to use, and has the Blueprints system. Plus, No you cannot use the marketplace from within Unreal Engine (as far as I know!) and well, many other things. In general, I'd just really like UE support. But if that's not possible, it's fine-

**Comment by arielj** [comment]
Sorry I didn't mean alternatives to Unreal Engine itself, I meant alternatives to managing Unreal Engine that are way better than what we could add to Heroic.

**Comment by DavidRLTG** [comment]
Ah. Could you list some, please? Thank you.

**Comment by arielj** [comment]
Sorry the only one I know is using Epic Games Launcher, I'm not an Unreal Engine user so I haven't done any research (I thought the market place was available inside UE but I got confused with the integration of the megascans that is now included in the editor, not the complete marketplace).

**Comment by arielj** [comment]
It's really confusing to me that Epic provides native linux installer for Unreal Engine but then it doesn't provide a native app to manage the assets/projects/etc, it makes no sense, that also why I thought the market place was included in the editor now.

**Comment by DavidRLTG** [comment]
Oh.. yeah, that's why I asked for support in the first place, haha- since using Epic Games Launcher on Linux is **TRUE PAIN** xd

**Comment by arielj** [comment]
You can check this alternative app for assets management https://flathub.org/apps/details/io.github.achetagames.epic_asset_manager

**Comment by DavidRLTG** [comment]
Damn! thanks a lot, man! I appreciate your help, I guess I can close the issue now. Have a good day!
