### ISSUE TITLE
Easier to run multiple executables

### ISSUE THREAD

**Issue by Sadasad1** [Heroic-Games-Launcher/HeroicGamesLauncher#1861]
### Problem description

Some games have multiple executables both for map editor and other things like in Heroes V. Right now the only way to pick one is to replace executable in launch options. Not to mention adding games as shortcut to Steam. This makes it really tedious to swap between those in launcher, especially in Steam Deck where you have to go to Desktop Mode to do that. 

### Feature description

One of the possible solution i find is to allow to specify all executables in form of a list and where is more than one you just show those options at launch.

### Alternatives

Another solution would be to allow to create copy of the existing game configuration pointing to the same game. In that way you could have multiple configs to test and run.

**Comment by arielj** [comment]
Next beta will allow you to add arbitrary exe files to Heroic's library and set their config individually, would that work for this issue? I understand you will be able to add the alternative exe you want, assign wine/prefix/image/etc and it will show up in the library as another game

**Comment by Sadasad1** [comment]
Aside from potentially unnecessary copying of manual prefix path and manually setting the same config for multiple exe files when the only thing you want is to have another exe this looks like a decent solution. But I still suggest as an upgrade making it a little more user-friendly and less of a time waster in the future
