### ISSUE TITLE
The "Add to Steam" functionality on Windows has problems if your Steam folder is not "C:\Program Files (x86)\Steam"

### ISSUE THREAD

**Issue by KingKrouch** [Heroic-Games-Launcher/HeroicGamesLauncher#1863]
### Describe the bug

The "Add to Steam" functionality on Windows has problems if your Steam folder is not "C:\Program Files (x86)\Steam". 

I personally have my Steam folder set to "C:\Steam" as that's way more convenient to navigate to, and it matches the folders on my other drives that I use for games, but Heroic doesn't seem to pick up on this.

### Add logs

(13:33:59) INFO:    [Legendary]:       Running command: C:\Users\Bryce\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\legendary --version
(13:34:14) INFO:    [Legendary]:       Legendary location: C:\Users\Bryce\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\legendary
(13:34:14) INFO:    [Gog]:             GOGDL location: C:\Users\Bryce\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\gogdl
(13:34:14) INFO:    [Backend]:         

Heroic Version: 2.4.3 Chopper
Legendary Version:  0.20.28 Dark Energy (hotfix #2)
OS: Microsoft Windows 11 Pro KERNEL: 10.0.22621 ARCH: x64
CPU: AMD Ryzen 5 5600X 6-Core Processor @3.7 
RAM: Total: 31.91 GiB Available: 19.28 GiB
GRAPHICS: GPU0:  VRAM: 0MB DRIVER:  GPU1:  VRAM: 0MB DRIVER:  GPU2: AMD Radeon RX 6700 XT VRAM: 12272MB DRIVER:  

(13:34:14) INFO:    [Gog]:             Getting data about the user
(13:34:14) WARNING: [Backend]:         Protocol already registered.
(13:34:15) INFO:    [Backend]:         Checking for new Heroic Updates
(13:34:15) INFO:    [Frontend]:        Refreshing Library
(13:34:15) INFO:    [Legendary]:       Refreshing library...
(13:34:15) INFO:    [Legendary]:       Refreshing Epic Games...
(13:34:15) INFO:    [Gog]:             Getting GOG library
(13:34:15) INFO:    [Gog]:             Saved user data to config
(13:34:16) INFO:    [Legendary]:       Running command: C:\Users\Bryce\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\legendary list
(13:34:16) INFO:    [Gog]:             Number of library pages: 1
(13:34:16) INFO:    [Gog]:             Saved games data
(13:34:18) INFO:    [Backend]:         VCRuntime is installed
(13:34:20) INFO:    [Legendary]:       Updating game list
(13:34:20) INFO:    [Legendary]:       Game List Updated
(13:34:21) INFO:    [Legendary]:       Checking for game updates.
(13:34:21) INFO:    [Legendary]:       Running command: C:\Users\Bryce\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\legendary list-installed --check-updates --tsv
(13:34:25) INFO:    [Legendary]:       Found 0 game(s) to update
(13:34:25) INFO:    [Gog]:             Found 0 game(s) to update
(13:35:02) DEBUG:   [Legendary]:       Using cached install info
(13:35:04) ERROR:   [Shortcuts]:       C:\Program Files (x86)\Steam\userdata does not exist. Can't add/remove game to/from Steam!

### Steps to reproduce

1. Go to the 'Tools' section when you are in the summary view for an installed game (Either Epic or GOG).
2. Click on 'Add to Steam' when your Steam install is in an alternate directory that isn't 'C:\Program Files (x86)\Steam'

### Expected behavior

Heroic should be able to detect alternate Steam install directories. Perhaps there's a way to read this from the Windows registry or through some other means.

### Screenshots

https://imgur.com/0wEFEKb

### System Information

- OS [e. g. "Ubuntu"]: Windows 11 (x64)
- Heroic Version [e. g. 2.1.1]: 2.4.3

**Comment by Nocccer** [comment]
We can't guess where the steam path is. We added a option to change this path:
![image](https://user-images.githubusercontent.com/61798668/193643254-8ecca4bc-da66-4c60-bbc0-21ccc96fec2b.png)

Close the ticket if it works after you changed this path to the correct one.

**Comment by KingKrouch** [comment]
Apologies. Didn't realize that option was there (Probably wasn't looking carefully enough). I will now close the ticket.

**Comment by Nocccer** [comment]
No problem. This option is pretty hidden.
