### ISSUE TITLE
Can't login into Epic Games store on Steam Deck

### ISSUE THREAD

**Issue by ximian** [Heroic-Games-Launcher/HeroicGamesLauncher#1869]
### Describe the bug

I'm unable to login into Epic Games Store on Steam Deck.
When I'm trying to log in using an Epic Games account there is no clickable login button (only a moving circle instead).
It might have something in common with [#1853](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/issues/1853) but I'm not sure.

### Add logs

(21:26:06) INFO:    [Legendary]:       Running command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary --version
(21:26:07) INFO:    [Legendary]:       Legendary location: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary
(21:26:07) INFO:    [Gog]:             GOGDL location: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl
(21:26:07) INFO:    [Backend]:         

Heroic Version: 2.4.3 Chopper
Legendary Version:  0.20.28 Dark Energy (hotfix #2)
OS: Freedesktop SDK KERNEL: 5.13.0-valve21.2-1-neptune ARCH: x64
CPU: AMD Custom APU 0405 @1.92 GOVERNOR: schedutil
RAM: Total: 14.49 GiB Available: 11.94 GiB
GRAPHICS: GPU0: VanGogh [AMD Custom GPU 0405] VRAM: 512MB DRIVER:  
PROTOCOL: x11

(21:26:07) INFO:    [Backend]:         User Not Found, removing it from Store
(21:26:07) INFO:    [Gog]:             Getting data about the user
(21:26:07) INFO:    [Gog]:             Refreshing access_token
(21:26:07) WARNING: [Backend]:         Failed to register protocol with OS.
(21:26:08) INFO:    [Gog]:             Token refreshed successfully
(21:26:08) INFO:    [Backend]:         AreWeAntiCheatYet data downloaded
(21:26:08) INFO:    [Frontend]:        Refreshing Library
(21:26:08) INFO:    [Legendary]:       Refreshing library...
(21:26:08) INFO:    [Gog]:             Getting GOG library
(21:26:09) INFO:    [Gog]:             Saved user data to config
(21:26:09) INFO:    [Gog]:             Number of library pages: 2
(21:26:09) INFO:    [Gog]:             Getting data for page 2
(21:26:10) INFO:    [Gog]:             Saved games data
(21:26:10) INFO:    [Frontend]:        No cache found, getting data from legendary...
(21:26:10) INFO:    [Legendary]:       Refreshing library...
(21:26:10) INFO:    [Gog]:             Found 0 game(s) to update
(21:26:10) INFO:    [Backend]:         Downloaded Winetricks

### Steps to reproduce

1. Go to Epic Shop
2. Click on Login using the Epic Games account
3. Enter login and password
4. There is no way to click on a login button 

### Expected behavior

1. Go to Epic Shop
2. Click on Login using the Epic Games account
3. Enter login and password
4. Login button should be clickable

### Screenshots

![Screenshot_20220930_233951](https://user-images.githubusercontent.com/4366946/194014892-abc9b9b1-e865-475a-806b-e5b24603fb9a.png)

### System Information

- OS: SteamOS 3.3.2
- Heroic Version: 2.4.3

**Comment by ximian** [comment]
I'm not entirely sure if that might be the case but, after several tries, it finally worked when a keyboard and mouse were attached to a Steam Deck.

My previous attempts were without any accessories connected to a Steam Deck.

Also when I tried to log in using the Account Management tab without a keyboard then it wanted to use the Epic Games authorization code which was unfortunate because clicking on any of the links did nothing (so I was unable to retrieve the code).

With a keyboard connected to a SD I've had a normal selection of login options and I was able to log in using Epic user credentials.

**Comment by arielj** [comment]
The Epic Store login is not intended to be used (I actually added a feature request to prevent this from happening https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/issues/1870).

Is this still an issue using the Account Manager tab? make sure you click in `Login` and not in `External login` when testing.
