### ISSUE TITLE
A `copy link to clipboard` action to share logs

### ISSUE THREAD

**Issue by arielj** [Heroic-Games-Launcher/HeroicGamesLauncher#1872]
### Problem description

Almost every time we need to provide support, we ask for logs and many users are not sure how to do it. We have to describe the steps and it's not completely clear to people that are not tech-savvy.

### Feature description

Have a button in the log screen that will:
- let the user know that we'll upload the log at some site (patebin, hastebin, gist)
- upload log
- copy the link to the clipboard
- instruct the user that the link is copied and they should paste it in discord

### Alternatives

Display the instructions for doing that manually inside heroic maybe? not great UX though

**Comment by flavioislima** [comment]
Does the current copy to clipboard and show log on folder works already? this seems to much IMO. We would need to use the pastebin API as well.

**Comment by arielj** [comment]
The current options are enough, I just added this as an idea for some improvements but I admit I won't we working on this anytime soon (there are other things more useful and interesting). Closing this so it doesn't add noise.
