### ISSUE TITLE
Skyrim Special Edition GOG launcher not showing Options menu

### ISSUE THREAD

**Issue by romanovzky** [Heroic-Games-Launcher/HeroicGamesLauncher#1874]
### Describe the bug

Skyrim Special Edition GOG installer doesn't show `Options` in game launcher. This prevents setting the graphical options, etc.

Also, the `Play` button does not launch the game.

### Add logs

System Info:
Heroic Version: 2.4.3 Chopper
Legendary Version:  0.20.28 Dark Energy (hotfix #2)
OS: EndeavourOS KERNEL: 5.19.13-arch1-1 ARCH: x64
CPU: AMD Ryzen 9 5900HX with Radeon Graphics @3.43 GOVERNOR: schedutil
RAM: Total: 15.04 GiB Available: 12.06 GiB
GRAPHICS: GPU0: NVIDIA GeForce RTX 3080 Laptop GPU VRAM: 8192MB DRIVER: 515.76 GPU1: Cezanne VRAM: 512MB DRIVER:  
PROTOCOL: x11

Game Settings: {
	"audioFix": false,
	"autoInstallDxvk": true,
	"autoInstallVkd3d": true,
	"preferSystemLibs": true,
	"enableEsync": false,
	"enableFSR": false,
	"enableFsync": false,
	"maxSharpness": 2,
	"enableResizableBar": true,
	"language": "",
	"nvidiaPrime": false,
	"offlineMode": false,
	"enviromentOptions": [],
	"wrapperOptions": [],
	"savesPath": "",
	"showFps": false,
	"showMangohud": false,
	"targetExe": "",
	"useGameMode": false,
	"winePrefix": "/home/mcromao/Games/Heroic/Prefixes/Skyrim Anniversary Edition",
	"wineVersion": {
		"bin": "/home/mcromao/.config/heroic/tools/proton/Proton-GE-Proton7-37/proton",
		"name": "Proton - Proton-GE-Proton7-37",
		"type": "proton"
	},
	"useSteamRuntime": false,
	"eacRuntime": false,
	"battlEyeRuntime": false,
	"gogSaves": [
		{
			"name": "saves",
			"location": "/home/mcromao/Games/Heroic/Prefixes/Skyrim Anniversary Edition/pfx/drive_c/users/steamuser/Documents/My Games"
		}
	]
}

Game launched at: Thu Oct 06 2022 13:52:22 GMT+0100 (British Summer Time)

Launch Command: LD_PRELOAD= STEAM_COMPAT_CLIENT_INSTALL_PATH=/home/mcromao/.steam/steam STEAM_COMPAT_DATA_PATH="/home/mcromao/Games/Heroic/Prefixes/Skyrim Anniversary Edition" PROTON_NO_ESYNC=1 PROTON_NO_FSYNC=1 VKD3D_CONFIG=upload_hvv STEAM_COMPAT_APP_ID=0 SteamAppId=0 SteamGameId="heroic-Skyrim Anniversary Edition" PROTON_LOG_DIR=/home/mcromao /opt/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl launch "/home/mcromao/Games/Heroic/Skyrim Anniversary Edition" 1711230643 --no-wine --wrapper "'/home/mcromao/.config/heroic/tools/proton/Proton-GE-Proton7-37/proton' run" --os windows

Game Log:
wineserver: using server-side synchronization.
wine: RLIMIT_NICE is <= 20, unable to use setpriority safely
[S_API] SteamAPI_Init(): SteamAPI_IsSteamRunning() did not locate a running instance of Steam.
[S_API FAIL] SteamAPI_Init() failed
Language:english
Launch command: ['/home/mcromao/.config/heroic/tools/proton/Proton-GE-Proton7-37/proton', 'run', '/home/mcromao/Games/Heroic/Skyrim Anniversary Edition/SkyrimSELauncher.exe']

### Steps to reproduce

1. Install GOG Skyrim
2. Run game
3. Observer that `Options` are missing in the launcher

### Expected behavior

The launcher should have an `Options` menu

### Screenshots

![Screenshot from 2022-10-06 13-52-30](https://user-images.githubusercontent.com/7794475/194317852-9614dcc9-3d9c-4a3c-9ac6-adc9506c0703.png)

### System Information

- OS [e. g. "Ubuntu"]:  EndeavourOS
- Heroic Version [e. g. 2.1.1]: 2.4.3

### Additional information

- Pointing Heroic to the Skyrim game executable (instead of launcher executable) launches the game, but using default options.
- The same Skyrim Special Edition GOG distribution works as intended when the game is installed using the GOG installer in Lutris, Bottles, etc.
- This was tested in two different computers (both running EndeavourOS), so it's unlikely to be a hardware problem.
- This has been observed by more than one use (see Discord Linux channel), where a workaround is to start a prefix with the GOG installer and then point Heroic to use that prefix.
- Tested using Wine staging, Proton Experimental, Proton GE 7.x, Proton GE 6.x

**Comment by flavioislima** [comment]
We cannot help you with that, it is not a Heroic issue but a Wine/proton issue since the game is being launched.
You can get support on our discord community, check ProtonDB, check communities on Reddit, etc. 
Or open a discussion here on Github,

**Comment by flavioislima** [comment]
Well, the game is being launched so unless the other Apps have some config that Heroic doesn't, I don't see why it would have the issue.
It is basically impossible to debug something like this unless you get exactly what the other Apps are doing differently for them to work.
Still, not Lutris nor Bottles Nor Heroic will work the same way and there will be games that will work in one of them and not on the other, that's the reason we have options ;)

**Comment by romanovzky** [comment]
Well, SSE doesn't have an installation recipe in Lutris for GOG, so it just runs the GOG installer verbosely (explicitly). Heroic hides the GOG installer. I raised this issue because my first intuition was that this abstraction might be doing something opinionated for the installation that is breaking the game.

If this is happening to SSE GOG, it will eventually happen to other GOG games. For the time being I'll use Lutris simple out-of-the-box installation as I don't need any of the Heroic extra features for this title (I use it a lot to make use of GOG cloud save games, which I don't need for this game).

Cheers

**Comment by romanovzky** [comment]
It seems that the default GOG configuration in Lutris is itself quite opinionated, I'll see if I can "mimic" this within Heroic

**Comment by imLinguin** [comment]
Can you attach `.script` file found in game directory?

The issue might happen because Heroic doesn't use installers, instead it acts more like GOG Galaxy. We are still trying to improve and add more features to make that experience less painful.

**Comment by romanovzky** [comment]
> Can you attach `.script` file found in game directory?
> 
> The issue might happen because Heroic doesn't use installers, instead it acts more like GOG Galaxy. We are still trying to improve and add more features to make that experience less painful.

I can't find a `.script` in the game directory or the prefix directory

**Comment by romanovzky** [comment]
> Heroic uses the GOG Galaxy way of installing a game instead of using the offline installer. We had issues in the past but with native games, because some Linux titles does not have the right config, or have outdated libs so it is more complicated to support. But for Windows games I cannot remember having an issue with it. Maybe check if the Lutris script install something on the prefix that might be missing on your config, like some VCrun files or something like this.

I see, so you do more like one of those extraction installations?

**Comment by imLinguin** [comment]
> I can't find a `.script` in the game directory or the prefix directory
Just looked at manifest. There is no .script file, which means settings are accessed different way. Put the `.info` file then, it contains launch options. Might help

**Comment by romanovzky** [comment]
> > I can't find a `.script` in the game directory or the prefix directory
> 
> Just looked at manifest. There is no .script file, which means settings are accessed different way. Put the `.info` file then, it contains launch options. Might help

Sorry again, in which folder should I find this file?

**Comment by imLinguin** [comment]
Game directory, it's exactly `goggame-1711230643.info`

**Comment by romanovzky** [comment]
Stupid me, I thought you mean a file `.info`, I didn't understand it was an extension. I found two, as I've been trying different settings
[goggame-1.zip](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/files/9727258/goggame-1.zip)

**Comment by imLinguin** [comment]
So it still doesn't tell us much. It's interesting given the fact Skyrim manifest doesn't have any information to set it up.

**Comment by romanovzky** [comment]
Is this unique to Skyrim installer? I wonder if the same happens to other Bethesda titles, like Fallout New Vegas, Fallout 3, Oblivion, etc

**Comment by sluedecke** [comment]
Same problem here.  My workaround is:

* set game exe to `SkyrimSE.exe`
* start game once
* then open `drive_c/users/steamuser/Documents/My Games/Skyrim Special Edition GOG/SkyrimPrefs.ini` and set display resolution in section `[Display]` to something like:
```
  bBorderless=0
  bFull Screen=1
  iSize H=1600
  iSize W=2560
```
This way it is at least playable for me.

**Comment by hallinbirch** [comment]
i have a work around for this at (https://github.com/hallinbirch/Pythonic-Incantations)
you just need LinuxToWinePath and LinuxBethesdaInstalationFixer from the repo

python3 ./LinuxBethesdaInstalationFixer.py 'Game-Install-Directory' 'Wine-Prefix-Folder-Path'

what i found out is the game is weirdly linked to a gog.com registry entry  instead of a Bethesda one

**Comment by imLinguin** [comment]
Oh, this dependence on registry is actually good to know. Thanks for mentioning it.

**Comment by ispanos** [comment]
Hello. I installed Skyrim SE on my desktop pc (amd cpu & dgpu) a few weeks ago and it worked fine. I'm try to install it on my laptop (intel+nvidia) now that I'm on holidays and I have the same issue. "Options" are not present in the menu and "Play" just crashes. Both computers use Fedora (Workstation 38 on the desktop, Silverblue 40 - [Bluefin](https://projectbluefin.io/) on the laptop). 
 
 What should I use to play skyrim for now?

> bBorderless=0
>   bFull Screen=1
>   iSize H=1600
>   iSize W=2560

The above did not work.

> i have a work around for this at (https://github.com/hallinbirch/Pythonic-Incantations) you just need LinuxToWinePath and LinuxBethesdaInstalationFixer from the repo
> 
> python3 ./LinuxBethesdaInstalationFixer.py 'Game-Install-Directory' 'Wine-Prefix-Folder-Path'

The scripts are not longer there.
