### ISSUE TITLE
Anno 1800 Fails to launch

### ISSUE THREAD

**Issue by Slyfox88** [Heroic-Games-Launcher/HeroicGamesLauncher#1875]
### Describe the bug

Anno 1800 fails to launch on linux os.

### Add logs

__________________________________Proton-GE-7-37_________________________
System Info:
Heroic Version: 2.4.3 Chopper
Legendary Version:  0.20.28 Dark Energy (hotfix #2)
OS: Garuda KERNEL: 5.19.13-zen1-1-zen ARCH: x64
CPU: AMD Ryzen 7 5700G with Radeon Graphics @3.89 GOVERNOR: performance
RAM: Total: 27.3 GiB Available: 20.5 GiB
GRAPHICS: GPU0: Navi 21 [Radeon RX 6800/6800 XT / 6900 XT] VRAM: 1MB DRIVER:  GPU1: Cezanne VRAM: 512MB DRIVER:  
PROTOCOL: x11

Game Settings: {
	"autoInstallDxvk": false,
	"autoInstallVkd3d": false,
	"preferSystemLibs": false,
	"maxSharpness": 2,
	"language": "",
	"nvidiaPrime": false,
	"enviromentOptions": [],
	"wrapperOptions": [],
	"savesPath": "",
	"showFps": false,
	"targetExe": "",
	"useGameMode": false,
	"winePrefix": "/home/slyfox/Games/Heroic/Prefixes/ANNO1800",
	"wineVersion": {
		"bin": "/home/slyfox/.config/heroic/tools/proton/Proton-GE-Proton7-37/proton",
		"name": "Proton - Proton-GE-Proton7-37",
		"type": "proton"
	},
	"eacRuntime": false,
	"battlEyeRuntime": false,
	"gogSaves": []
}

Game launched at: Thu Oct 06 2022 15:16:52 GMT-0400 (Eastern Daylight Time)

Launch Command: LD_PRELOAD= STEAM_COMPAT_CLIENT_INSTALL_PATH=/home/slyfox/.steam/steam STEAM_COMPAT_DATA_PATH=/home/slyfox/Games/Heroic/Prefixes/ANNO1800 PROTON_NO_ESYNC=1 PROTON_NO_FSYNC=1 STEAM_COMPAT_APP_ID=0 SteamAppId=0 SteamGameId=heroic-ANNO1800 PROTON_LOG_DIR=/home/slyfox /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary launch Oregano --language en  --no-wine --wrapper "'/home/slyfox/.config/heroic/tools/proton/Proton-GE-Proton7-37/proton' run"

Game Log:
[cli] INFO: Logging in...
[Core] INFO: Trying to re-use existing login session...
[cli] INFO: Checking for updates...
[Core] INFO: Getting authentication token...
[cli] INFO: Launching Oregano...

Legendary update available!
- New version: 0.20.29 - "Dark Energy (hotfix #3)"
- Release summary:
 [!] Adds workaround for Epic CDN issue (403 when downloading manifest)
 [!] Fixes potential zero division error when verifying large files on fast SSDs
See full changelog for additional details.
- Release URL: https://legendary.gl/release/0.20.29
! This update is recommended as it fixes major issues.

- Download URL: https://legendary.gl/release/download/0.20.29/legendary
wineserver: using server-side synchronization.
wine: Using setpriority to control niceness in the [-11,11] range
[S_API] SteamAPI_Init(): SteamAPI_IsSteamRunning() did not locate a running instance of Steam.
[S_API FAIL] SteamAPI_Init() failed

__________________________________Wine Staging________________
System Info:
Heroic Version: 2.4.3 Chopper
Legendary Version:  0.20.28 Dark Energy (hotfix #2)
OS: Garuda KERNEL: 5.19.13-zen1-1-zen ARCH: x64
CPU: AMD Ryzen 7 5700G with Radeon Graphics @3.89 GOVERNOR: performance
RAM: Total: 27.3 GiB Available: 20.47 GiB
GRAPHICS: GPU0: Navi 21 [Radeon RX 6800/6800 XT / 6900 XT] VRAM: 1MB DRIVER:  GPU1: Cezanne VRAM: 512MB DRIVER:  
PROTOCOL: x11

Game Settings: {
	"autoInstallDxvk": false,
	"autoInstallVkd3d": false,
	"preferSystemLibs": false,
	"maxSharpness": 2,
	"language": "",
	"nvidiaPrime": false,
	"enviromentOptions": [],
	"wrapperOptions": [],
	"savesPath": "",
	"showFps": false,
	"targetExe": "",
	"useGameMode": false,
	"winePrefix": "/home/slyfox/Games/Heroic/Prefixes/ANNO1800",
	"wineVersion": {
		"bin": "/usr/bin/wine",
		"name": "Wine Default - wine-7.18 (Staging)",
		"type": "wine",
		"wineserver": "/usr/bin/wineserver",
		"wineboot": "/usr/bin/wineboot"
	},
	"eacRuntime": false,
	"battlEyeRuntime": false,
	"gogSaves": []
}

Game launched at: Thu Oct 06 2022 14:52:24 GMT-0400 (Eastern Daylight Time)

Launch Command: LD_PRELOAD= WINEPREFIX=/home/slyfox/Games/Heroic/Prefixes/ANNO1800 /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary launch Oregano --language en  --wine /usr/bin/wine --wine-prefix /home/slyfox/Games/Heroic/Prefixes/ANNO1800

Game Log:
[cli] INFO: Logging in...
[Core] INFO: Trying to re-use existing login session...
[cli] INFO: Checking for updates...
[Core] INFO: Getting authentication token...
[cli] INFO: Launching Oregano...

Legendary update available!
- New version: 0.20.29 - "Dark Energy (hotfix #3)"
- Release summary:
 [!] Adds workaround for Epic CDN issue (403 when downloading manifest)
 [!] Fixes potential zero division error when verifying large files on fast SSDs
See full changelog for additional details.
- Release URL: https://legendary.gl/release/0.20.29
! This update is recommended as it fixes major issues.

- Download URL: https://legendary.gl/release/download/0.20.29/legendary
002c:fixme:winediag:LdrInitializeThunk wine-staging 7.18 is a testing version containing experimental patches.
002c:fixme:winediag:LdrInitializeThunk Please mention your exact version when filing bug reports on winehq.org.
007c:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
007c:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
007c:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
007c:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
00fc:fixme:kernelbase:AppPolicyGetProcessTerminationMethod FFFFFFFA, 0076FEAC

### Steps to reproduce

1. Click play now
2. Game doesn't launch
3. Click report a problem running this game to view log

### Expected behavior

Expect the game to launch

### System Information

- OS: Garuda Linux x86_64 KDE
- Heroic Version: 2.4.3

**Comment by arielj** [comment]
Use discord to ask for help running games, the issue tracker is for issue with Heroic itself, not with specific games.

Try using Wine-GE-Proton (not Wine Staging nor Proton-GE). If it still fails share a new log in Heroic's discord in the `linux` channel.
