### ISSUE TITLE
Discrepancy in game count between All games and sum of epic and gog

### ISSUE THREAD

**Issue by NoeDeMontard** [Heroic-Games-Launcher/HeroicGamesLauncher#1877]
### Describe the bug

In the library, all games show 294 while epic + gog is 262+31 = 293. All Games therefore count one more than the sum of its part.

While filtering, I find a more precise  with a cont of 3 shown in all Games, only 2 games presents in the list and a count of 2 in Epic, 0 in Gog.

When I try to check my epic purchase history I find only the two games displayed. (The method I found to check independently the number of games.) I didn't find a way to check all the DLCs I own (see speculation in additional info).

I am on the flatpak version 2.4.3.

### Add logs

```
(01:34:40) INFO:    [Legendary]:       Running command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary --version
(01:34:41) INFO:    [Legendary]:       Legendary location: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary
(01:34:41) INFO:    [Gog]:             GOGDL location: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl
(01:34:41) INFO:    [Backend]:         

Heroic Version: 2.4.3 Chopper
Legendary Version:  0.20.28 Dark Energy (hotfix #2)
OS: Freedesktop SDK KERNEL: 5.19.13-200.fc36.x86_64 ARCH: x64
CPU: Intel Core™ i7-1065G7 @1.3 GOVERNOR: powersave
RAM: Total: 15.4 GiB Available: 12.23 GiB
GRAPHICS: GPU0: Iris Plus Graphics G7  VRAM: 256MB DRIVER:  
PROTOCOL: wayland

(01:34:41) INFO:    [Gog]:             Getting data about the user
(01:34:41) WARNING: [Backend]:         Failed to register protocol with OS.
(01:34:41) INFO:    [Backend]:         AreWeAntiCheatYet data downloaded
(01:34:41) INFO:    [Gog]:             Saved user data to config
(01:34:42) INFO:    [Frontend]:        Refreshing Library
(01:34:42) INFO:    [Legendary]:       Refreshing library...
(01:34:42) INFO:    [Legendary]:       Refreshing Epic Games...
(01:34:42) INFO:    [Gog]:             Getting GOG library
(01:34:42) INFO:    [Gog]:             Number of library pages: 1
(01:34:42) INFO:    [Legendary]:       Running command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary list
(01:34:43) INFO:    [Gog]:             Saved games data
(01:34:44) INFO:    [Legendary]:       Updating game list
(01:34:44) INFO:    [Legendary]:       Game List Updated
(01:34:44) INFO:    [Backend]:         Downloaded Winetricks
(01:34:44) INFO:    [Legendary]:       Checking for game updates.
(01:34:44) INFO:    [Legendary]:       Running command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary list-installed --check-updates --tsv
(01:34:45) INFO:    [Legendary]:       Found 0 game(s) to update
(01:34:45) INFO:    [Gog]:             Found 0 game(s) to update
(01:36:05) INFO:    [Frontend]:        Refreshing Library
(01:36:05) INFO:    [Legendary]:       Refreshing library...
(01:36:05) INFO:    [Legendary]:       Refreshing Epic Games...
(01:36:05) INFO:    [Gog]:             Getting GOG library
(01:36:05) INFO:    [Legendary]:       Running command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary list
(01:36:05) INFO:    [Gog]:             Number of library pages: 1
(01:36:06) INFO:    [Gog]:             Saved games data
(01:36:07) INFO:    [Legendary]:       Updating game list
(01:36:07) INFO:    [Legendary]:       Game List Updated
(01:36:07) INFO:    [Legendary]:       Checking for game updates.
(01:36:07) INFO:    [Legendary]:       Running command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary list-installed --check-updates --tsv
(01:36:08) INFO:    [Legendary]:       Found 0 game(s) to update
(01:36:08) INFO:    [Gog]:             Found 0 game(s) to update
(01:52:27) INFO:    [Legendary]:       Getting Info from Epic API
(01:52:27) INFO:    [Legendary]:       Getting Info from Epic API
(01:52:27) INFO:    [Legendary]:       Getting more details with 'legendary info'
(01:52:28) INFO:    [Legendary]:       Running command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary --pretty-json info Grunt --platform Windows --json
(01:52:36) INFO:    [Legendary]:       Getting Info from Epic API
(01:52:36) INFO:    [Legendary]:       Getting Info from Epic API
(01:52:36) INFO:    [Legendary]:       Getting more details with 'legendary info'
(01:52:36) INFO:    [Legendary]:       Running command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary --pretty-json info 1fe19232c0f7476a8e99fd8752e800c2 --platform Windows --json
(01:52:40) DEBUG:   [Legendary]:       Using cached install info

```

### Steps to reproduce

1. Go to 'Library'
2. Click on 'All Games'
3. Not the number displayed
4. Click on 'Epic'
5. Not the number displayed
6. 2. Click on 'Gog'
7. Not the number displayed
8. The number on all games might not match the sum of the numbers on the sub categories

### Expected behavior

The number on all games match the sum of the sub categories, eventually excluding duplicates, but in any case be either equal or less.

### Screenshots

All Games with filter :

![image](https://user-images.githubusercontent.com/75419554/194441358-be681826-f941-459f-8df1-44e4ceb61ea4.png)

Epic with filter :

![image](https://user-images.githubusercontent.com/75419554/194441395-fef260d6-d36f-426f-b8e7-20ad812260d8.png)

Gog with filter :
![image](https://user-images.githubusercontent.com/75419554/194441480-c7c0829d-e7ce-4a16-bc2d-02219c618cbb.png)

### System Information

- OS [e. g. "Ubuntu"]: fedora 36
- Heroic Version [e. g. 2.1.1]: V2.4.3 flatpak

#### Speculation - first analysis

I made a quick look at the code (I never looked at it before) and I saw that in the count there seems to be a filter in what I interpret as the Epic case that exclude DLCs. I didn't quite understood the mechanism used to filter and show the game list, so I'm not sure what it include. I also couldn't check the number of DLCs I might own on the Epic Game Store.

My hypothesis is the following : this discrepancy might be something going on with the filter, maybe not filtering in all necessary cases.

#### Other

This bug seems low priority to me but might be a quick fix for someone familiar with the codebase and the language if I identified the good reason.

I remain available for further informations or testing, even in the future.

**Comment by arielj** [comment]
Hmmm I can't reproduce this. From your comment I understand you can help debugging this testing things with the code?

If so, clone the repo and go to this line https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/blob/main/src/frontend/screens/Library/components/LibraryHeader/index.tsx#L34 and before that line do `console.log(list)`, then search `az` and you should see the list of games printed in the dev tools console. You can expand the games and see if there's something weird or share the output here.
