### ISSUE TITLE
Colors in Library config are inconsistent

### ISSUE THREAD

**Issue by arielj** [Heroic-Games-Launcher/HeroicGamesLauncher#1878]
### Describe the bug

![image](https://user-images.githubusercontent.com/188464/194448141-e683fa8d-f39c-4b83-b16e-0f6480b29cda.png)

Some buttons have an accentuated color in one state and white in the other, but the accentuated color make it look like an on/off thing when it is not an on/off:
- the layout type is accentuated in grid and white in list
- the alphabetical order is accentuated in descending and white in ascending
- the sort by installed is accentuated if installed first and white if installed last
- show hidden is accentuated if active and white if inactive

All these icons actually change to another icon already to indicate the status. The icon change should be enough indication, since the color seems to suggest a meaning that is not really there.

The color of the favorites icon changes, which seems ok to indicate an on/off status of the filter so it can make sense in this one.

It also mixes sorting with filtering with the refresh icon, but the top left `all / epic / gog` buttons also do filtering and work completely different.

Also icons have light blue hover effect when the text is white but no hover effect when is accentuated.

### Add logs

not relevant

### Steps to reproduce

1. Go to the Library
2. Change the list filter/sorting/layout

### Expected behavior

Icons shouldn't change color if the color is not relevant to the status of the icon.

### System Information

- Heroic Version [e. g. 2.1.1]: main branch

**Comment by flavioislima** [comment]
Still relevant?

**Comment by arielj** [comment]
Yes, the problem is still present. I'll see if I can fix that today, it's actually a good first issue too, it's pretty simple.

**Comment by arielj** [comment]
fixed in the main branch
