### ISSUE TITLE
Some games requires manual uplay installation before game will launch

### ISSUE THREAD

**Issue by Slyfox88** [Heroic-Games-Launcher/HeroicGamesLauncher#1879]
### Describe the bug

After installing a game that require uplay to launch the game won't start. To solve the issue I had to go in the setting of the game, click on 'Run EXE on Prefix' and then navigate to Uplay/UplayInstaller.exe in the game folder. That will install uplay and the game will show up as already downloaded. The game lauches as normal after that step. Not sure why this program doesn't install uplay automatically on games that require it like Anno 1800 because most people probably won't think to do the step I just described and think your app is broken. After installation this app should prompt for uplay installation if game requires it.

### Add logs

Not a wine/proton issue

### Steps to reproduce

1. Download game the requires uplay to lauch like Anno 1800
2. Try launching the game

### Expected behavior

Expect this app to prompt for installation of uplay so that the manual steps listed above are not necessary and that the process is seamless to the end user.

### System Information

- OS: Linux
- Heroic Version: 2.4.3

**Comment by redromnon** [comment]
Uplay and Origin games aren't supported as of now. You will have to do it manually just like you described or using Legendary's `activate` command, although I haven't tried the latter.

Refer to - [Heroic Wiki](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/wiki#which-games-are-not-supported-by-heroic)

**Comment by flavioislima** [comment]
Those are not supported but you can still try to install uplay on the prefix to make it run.
