### ISSUE TITLE
Remember scroll position when leaving the Library and restore when back

### ISSUE THREAD

**Issue by arielj** [Heroic-Games-Launcher/HeroicGamesLauncher#1911]
### Problem description

Currently, if you are navigating the Library and open a game page to read more about it, if you go back you are back at the top and you have to scroll back again to where you were.

### Feature description

Would be convenient to remember the scroll position of the Library and restore that scroll position when showing the Library again.

Not sure if it's useful in all cases, maybe do this only when "going back" from other screens, but keep the scroll at the top when clicking the `Library` item in the sidebar?

### Alternatives

Keep the current behavior, it's a minor inconvenience only.

**Comment by flavioislima** [comment]
done
