### ISSUE TITLE
"ImportError: libffi.so.6: cannot open shared object file: No such file or directory" when running a game using Proton

### ISSUE THREAD

**Issue by nl28** [Heroic-Games-Launcher/HeroicGamesLauncher#1914]
### Describe the bug

See the steps to reproduce section. After selecting any Proton version (Proton 7.0, Proton 6.3, Proton Experimental), I get the error message (see logs). Please also check the "Additional information" section below.

### Add logs

```
(13:57:43) INFO:    [Legendary]:       Running command: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary --version
(13:57:43) INFO:    [Legendary]:       Legendary location: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary
(13:57:43) INFO:    [Gog]:             GOGDL location: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl
(13:57:43) INFO:    [Backend]:         

Heroic Version: 2.4.3 Chopper
Legendary Version:  0.20.28 Dark Energy (hotfix #2)
OS: Fedora Linux KERNEL: 5.19.15-201.fc36.x86_64 ARCH: x64
CPU: Intel Core™ i5-4570 @3.2 GOVERNOR: schedutil
RAM: Total: 7.65 GiB Available: 5.05 GiB
GRAPHICS: GPU0: Xeon E3-1200 v3/4th Gen Core Processor Integrated Graphics Controller  VRAM: 256MB DRIVER:  GPU1: NVIDIA GeForce GTX 660 VRAM: 1999MB DRIVER: 470.141.03 
PROTOCOL: x11

(13:57:44) WARNING: [Backend]:         Protocol already registered.
(13:57:44) INFO:    [Backend]:         AreWeAntiCheatYet data downloaded
(13:57:44) INFO:    [Backend]:         Checking for new Heroic Updates
(13:57:45) INFO:    [Frontend]:        Refreshing Library
(13:57:45) INFO:    [Legendary]:       Refreshing library...
(13:57:45) INFO:    [Legendary]:       Refreshing Epic Games...
(13:57:46) INFO:    [Legendary]:       Running command: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary list
(13:57:46) DEBUG:   [Legendary]:       Using cached install info
(13:57:46) INFO:    [Legendary]:       Checking if EOS Overlay is enabled: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary eos-overlay info --prefix /home/dv/Games/Heroic/Prefixes/rocketleague/pfx
(13:57:47) INFO:    [Backend]:         Downloaded Winetricks
(13:57:47) INFO:    [Legendary]:       Updating game list
(13:57:47) INFO:    [Legendary]:       Game List Updated
(13:57:48) INFO:    [Legendary]:       Checking for game updates.
(13:57:48) INFO:    [Legendary]:       Running command: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary list-installed --check-updates --tsv
(13:57:50) INFO:    [Legendary]:       Found 0 game(s) to update
(13:57:50) INFO:    [Gog]:             Found 0 game(s) to update
(13:57:50) DEBUG:   [Legendary]:       Using cached install info
(13:57:50) INFO:    [Backend]:         Launching Rocket League® (Sugar)
(13:57:50) INFO:    [Backend]:         Preventing display from sleep
(13:57:50) INFO:    [Legendary]:       Running command: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary --version
(13:57:50) DEBUG:   [Legendary]:       Using cached install info
(13:57:51) WARNING: [Backend]:         You are using Proton, this can lead to some bugs. Please do not open issues with bugs related to games
(13:57:51) DEBUG:   [Legendary]:       Running Wine command: "/home/dv/.local/share/Steam/steamapps/common/Proton 7.0/proton" waitforexitandrun wineboot --init
(13:57:51) ERROR:   [Backend]:         Error running Wine command: Error: Command failed: "/home/dv/.local/share/Steam/steamapps/common/Proton 7.0/proton" waitforexitandrun wineboot --init
Traceback (most recent call last):
  File "/home/dv/.local/share/Steam/steamapps/common/Proton 7.0/proton", line 20, in <module>
    from ctypes import CDLL
  File "/home/dv/.pyenv/versions/3.8.12/lib/python3.8/ctypes/__init__.py", line 7, in <module>
    from _ctypes import Union, Structure, Array
ImportError: libffi.so.6: cannot open shared object file: No such file or directory

(13:57:51) ERROR:   [Backend]:         Unable to create Wineprefix:  Error: Command failed: "/home/dv/.local/share/Steam/steamapps/common/Proton 7.0/proton" waitforexitandrun wineboot --init
Traceback (most recent call last):
  File "/home/dv/.local/share/Steam/steamapps/common/Proton 7.0/proton", line 20, in <module>
    from ctypes import CDLL
  File "/home/dv/.pyenv/versions/3.8.12/lib/python3.8/ctypes/__init__.py", line 7, in <module>
    from _ctypes import Union, Structure, Array
ImportError: libffi.so.6: cannot open shared object file: No such file or directory

(13:57:51) ERROR:   [Backend]:         Error: Command failed: "/home/dv/.local/share/Steam/steamapps/common/Proton 7.0/proton" waitforexitandrun wineboot --init
Traceback (most recent call last):
  File "/home/dv/.local/share/Steam/steamapps/common/Proton 7.0/proton", line 20, in <module>
    from ctypes import CDLL
  File "/home/dv/.pyenv/versions/3.8.12/lib/python3.8/ctypes/__init__.py", line 7, in <module>
    from _ctypes import Union, Structure, Array
ImportError: libffi.so.6: cannot open shared object file: No such file or directory

    at ChildProcess.exithandler (node:child_process:407:12)
    at ChildProcess.emit (node:events:527:28)
    at maybeClose (node:internal/child_process:1092:16)
    at Socket.<anonymous> (node:internal/child_process:451:11)
    at Socket.emit (node:events:527:28)
    at Pipe.<anonymous> (node:net:709:12)
(13:57:51) INFO:    [Backend]:         Stopping Display Power Saver Blocker
(13:57:51) INFO:    [Frontend]:        Refreshing Library
(13:57:51) INFO:    [Legendary]:       Refreshing library...
(13:57:51) INFO:    [Legendary]:       Updating game list
(13:57:52) INFO:    [Legendary]:       Game List Updated
(13:57:52) DEBUG:   [Legendary]:       Using cached install info
(13:57:52) DEBUG:   [Legendary]:       Using cached install info
(13:57:53) INFO:    [Legendary]:       Checking for game updates.
(13:57:53) INFO:    [Legendary]:       Running command: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary list-installed --check-updates --tsv
(13:57:54) INFO:    [Legendary]:       Found 0 game(s) to update
(13:57:54) DEBUG:   [Legendary]:       Using cached install info
```

### Steps to reproduce

1. Select "Rocket League" from library.
2. Click on "Settings" next to "Play Now".
3. Select "Proton - Proton 7.0" under the "Wine Version" field.
4. Click the back icon at the top left corner.
5. Click on "Play Now".

### Expected behavior

Game should run.

### System Information

```
System Info:
Heroic Version: 2.4.3 Chopper
Legendary Version:  0.20.28 Dark Energy (hotfix #2)
OS: Fedora Linux KERNEL: 5.19.15-201.fc36.x86_64 ARCH: x64
CPU: Intel Core™ i5-4570 @3.2 GOVERNOR: schedutil
RAM: Total: 7.65 GiB Available: 5 GiB
GRAPHICS: GPU0: Xeon E3-1200 v3/4th Gen Core Processor Integrated Graphics Controller  VRAM: 256MB DRIVER:  GPU1: NVIDIA GeForce GTX 660 VRAM: 1999MB DRIVER: 470.141.03 
PROTOCOL: x11
```

### Additional information

The game runs under the following Wine versions, but lags a lot:

1. Wine-GE-Proton7-31
2. Wine-Lutris-Wine-7.2-2

The game does not run under the following Wine versions:

1. Proton-GE-Proton7-37
2. Proton - Proton 7.0
3. Proton - Proton 6.3
4. Proton - Proton - Experimental

Other things I have tried:
1. Moving the Proton directory from another partition to `.local/share/Steam/steamapps/common/Proton 7.0/proton`.
2. Enabling "Use Steam Runtime".
3. Running "Verify and Repair".
4. Running "CLEAR HEROIC CACHE".
5. Running "RESET HEROIC".
6. Reinstalled Heroic.

This issue started when I upgraded my system from Fedora 35 to Fedora 36 using [DNF system upgrade](https://docs.fedoraproject.org/en-US/quick-docs/dnf-system-upgrade/#sect-performing-system-upgrade).

**Comment by arielj** [comment]
The log shows this message `(13:57:51) WARNING: [Backend]:         You are using Proton, this can lead to some bugs. Please do not open issues with bugs related to games`

Try using the latest Wine-GE-Proton instead of Proton / Proton-GE / Proton Experimental. Wine-GE-Proton is intended to be used for games outside Steam.

**Comment by arielj** [comment]
Check https://stackoverflow.com/questions/61875869/ubuntu-20-04-upgrade-python-missing-libffi-so-6, this seems to be an issue in your system's packages, not in Heroic, make sure you have that library installed.

**Comment by nl28** [comment]
@arielj Thanks a lot. Doing the following solved the issue:

1. `pyenv install 3.7.4`
2. `pyenv global 3.7.4`

I have one question. Why does Heroic depend on the system's Python version? Shouldn't the correct Python version be bundled with it?

**Comment by arielj** [comment]
> I have one question. Why does Heroic depend on the system's Python version? Shouldn't the correct Python version be bundled with it?

Heroic is not the one failing here, it's Proton: ` File "/home/dv/.local/share/Steam/steamapps/common/Proton 7.0/proton", line 20, in <module>`

**Comment by Nocccer** [comment]
Proton is also developed for steam games only. Better use wine-ge from our wine-manager. This doe snot need python at all.

**Comment by nl28** [comment]
@arielj Thanks for the clarification.

@Nocccer The game works really well when I use Proton. There is a huge performance improvement over Wine-GE-Proton7-31 and Wine-Lutris-Wine-7.2-2. Any reason why this happens?

**Comment by arielj** [comment]
Are you enabling DXVK and VKD3D? proton has those turned on by default, while Wine-GE don't, go to the game's settings > Wine Extensions

**Comment by arielj** [comment]
> @arielj But the game works when I open it through Steam (using the same Proton version).

Proton is intended to work with Steam, probably steam is telling proton to use some built-in version of Python or dependencies provided by Steam. The thing is, Proton is NOT intended to be used for non-steam games, anything extra (either good or bad) is a result of proton or steam expecting things from each other.

Wine-GE is intended to be use for non-steam games.

**Comment by nl28** [comment]
> Are you enabling DXVK and VKD3D? proton has those turned on by default, while Wine-GE don't, go to the game's settings > Wine Extensions

Tried this. Now the performance is much better with Wine-GE-Proton7-31, but "Proton - Proton 7.0" performance is still slightly better. Why should these be turned on manually?

> Proton is intended to work with Steam, probably steam is telling proton to use some built-in version of Python or dependencies provided by Steam (something we don't include in Heroic since we don't need to for Wine-GE, the one we recommend). The thing is, Proton is NOT intended to be used for non-steam games, anything extra (either good or bad) is a result of proton or steam expecting things from each other.

Thanks for the clarification.

**Comment by arielj** [comment]
> Tried this. Now the performance is much better with Wine-GE-Proton7-31, but "Proton - Proton 7.0" performance is still slightly better.

Proton could be doing something else, I don't know.

> Why should these be turned on manually?

It is going to be on by default since the next version of Heroic for new Heroic installations. You can always go to the general heroic settings > wine extensions and toggle them on so it's on by default for every new game you install (keep in mind this is the default, it won't change the config for games currently installed).

For this not being a default since now, DXVK and VKD3D are not part of Wine-GE, Heroic downloads and adds them, but in order to use them you need a GPU that supports Vulkan (while the defaults from Wine do not have that requirement) so the safe default was to not turn them on by default, but we decided to change the default and then if somebody has issues using an older GPU they can disable them anyway.
