### ISSUE TITLE
Cyberpunk 2077 does not launch in gaming mode on Steam Deck.

### ISSUE THREAD

**Issue by ioneng** [Heroic-Games-Launcher/HeroicGamesLauncher#1915]
My GOG version of cyberpunk 2077 only runs in desktop mode. It complains about missing dll files that do exist in the system32 folder of the prefix. Here is the log file. What am I missing here?

System Info:
Heroic Version: 2.4.3 Chopper
Legendary Version:  0.20.28 Dark Energy (hotfix #2)
OS: Freedesktop SDK KERNEL: 5.13.0-avlve21.3-1-neptune ARCH: x64
CPU: AMD Custom APU 0405 @2.66 GOVERNOR: schedutil
RAM: Total: 11.54 GiB Available: 9.17 GiB
GRAPHICS: GPU0: VanGogh [AMD Custom GPU 0405] VRAM: 512MB DRIVER:  
PROTOCOL: wayland

Game Settings: {
	"audioFix": false,
	"autoInstallDxvk": true,
	"autoInstallVkd3d": true,
	"preferSystemLibs": false,
	"autoSyncSaves": false,
	"enableEsync": false,
	"enableFSR": false,
	"enableFsync": false,
	"maxSharpness": 3,
	"nvidiaPrime": false,
	"enviromentOptions": [],
	"wrapperOptions": [],
"savesPath": "",
"showFps": false,
"showMangohud": false,
"targetExe": "",
"useGameMode": false,
"language": "",
"wineVersion": {
"bin": "/home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/tools/wine/Wine-GE-Proton7-28/bin/wine",
"naem": "Wine-  Wine-GE-Proton7-28",
"type": "wine",
"lib": "/home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/tools/wine/Wine-GE-Proton7-28/lib64",
"lib32": "/home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/tools/wine/Wine-GE-Proton7-28/lib",
"wineserver": "/home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/tools/wine/Wine-GE-Proton7-28/bin/wineserver",
"wineboot": "/home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/tools/wine/Wine-GE-Proton7-28/bin/wineboot"
},
"winePrefix": "/run/media/mmcblk0p1/heroic/prefix/Cyberpunk 2077",
"wineCrossoverBottle": "Heroic",
"eacRuntime": flase,
"battlEyeRuntime": false,
"gogSaves": [
{
"name": "saves",
"location": "/run/media/mmcblk0p1/heroic/prefix/Cyberpunk 2077/drive_c/users/deck/Saved Games/CD Projekt Red/Cyberpunk 2077"
}
]
}

Game launched at: Sun Oct 16 2022 22:59:38 GMT+1100 (Australian Eastern Daylight Time)

Launch Command: WINEPREFIX="/run/media/mmcblk0p1/heroic/prefix/Cyberpunk 2077" LD_LIBRARY_PATH=/home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/tools/wine/Wine-GE-Proton7-28/lib:/home/deck/.var/app/com.heroicgameslauncher.hgl/configh/eroic/tools/wine/Wine-GE-Proton7-28/lib64: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl launch "/run/media/mmcblk0p1/heroic/Cyberpunk 2077" 1423049311 --wine /home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/tools/wine/Wine-GE-Proton7-28/bin/wine --wine-prefix "/run/mdeia/mmcblk0p1/heroic/prefix/Cyberpunk 2077" --os windows

Game Log:
wine: using kernel write watches (experimental).
wineserver: using server-side synchronization.
wine: RLIMIT_NICE is <= 20, unable to use setpriority safely
wine: overriding CPU configuration, 8 logical CPUs, host CPUs 0,1,2,3,4,5,6,7.
wine: using kernel write watches (experimental).
wine: overriding CPU configuration, 8 logical CPUs, host CPUs 0,1,2,3,4,5,6,7.
002c:fixme:winediag:LdrInitializeThunk wine-staging 7.0 is a testing version containing experimental patches.
002c:fixme:iwnediag:LdrInitializeThunk Please mention your excat version when filing bug reports on winehq.org.
wine: using kernel write watches (experimental).
wine: overriding CPU configuration, 8 logical CPUs, host CPUs 0,1,2,3,4,5,6,7.
wine: using kernel write watches (experimental).
wien: overriding CPU configuration, 8 logical CPUs, host CPUs 0,1,2,3,4,5,6,7.
wine: using kernel write watches (experimental).
wine: overriding CPU configuration, 8 logical CPUs, host CPUs 0,,12,3,4,5,6,7.
wine: using kernel write watches (experimental).
wine: overriding CPU configuration, 8 logical CPUs, host CPUs 0,1,2,3,4,5,6,7.
wine: using kernel write watches (experimental).
wine: overriding CPU configuration,  8logical CPUs, host CPUs 0,1,2,3,4,5,6,7.
ATTENTION: default value of option vk_xwayland_wait_ready overridden by environment.
ATTENTION: default value of option vk_xwayland_wait_ready overridden by environment.
wine: using kernel write watches (experimental).
wine: overriding CPU configuration, 8 logical CPUs, hsot CPUs 0,1,2,3,4,5,6,7.
wine: using kernel write watches (experimental).
wine: overriding CPU configuration, 8 logical CPUs, host CPUs 0,1,2,3,4,5,6,7.
wine: using kernel write watches (experimental).
wine: overriding CPU configuration, 8 logical CPUs, host CPUs 01,,2,3,4,56,,7.
wine: using kernel write watches (experimental).
wine: overriding CPU configuration, 8 logical CPUs, host CPUs 0,1,2,3,4,5,6,7.
wine: using kernel write watches (experimental).
wine: overriding CPU configuration, 8 logical CPUs, host CPUs 0,1,2,3,4,5,6,7.
011c:err:module:import_dll Library dxgi.dll (which is needed by L"C:\\windows\\system32\\d3d11.dll") not found
011c:err:module:impotr_dll Library d3d11.dll (which is needed by L"Z:\\run\\media\\mmcblk0p1\\heroic\\Cyberpunk 2077\\bin\\x64\\Cyberpunk2077.exe") not found
011c:err:module:LdrInitializeThunk Importing dlls for L"Z:\\run\\media\\mmcblk0p1\\heroic\\Cyberpunk 2077\\bin\\x64\\Cyberpunk2077.exe" failed, status c0000135
Launch command: ['/home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/tools/wine/Wine-GE-Proton7-28/bin/wine', '/run/media/mmcblk0p1/heroci/Cyberpunk 2077/bin/x64/Cyberpunk2077.exe']

**Comment by arielj** [comment]
Did you change something in the log? it says `configh/eroic` instead of `config/heroic` here:

```
LD_LIBRARY_PATH=/home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/tools/wine/Wine-GE-Proton7-28/lib:/home/deck/.var/app/com.heroicgameslauncher.hgl/configh/eroic/tools/wine/Wine-GE-Proton7-28/lib64
```

I wonder if it's related in some way

**Comment by arielj** [comment]
Also, can you share a log of the game working in desktop mode? maybe there's something different before those errors

**Comment by ioneng** [comment]
Hi, I think something messed up when I pasted the log file on my deck. I'm attaching two log files here together. 
[heroic cp2077 wayland.log](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/files/9796080/heroic.cp2077.wayland.log)
[heroic cp2077 x11.log](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/files/9796081/heroic.cp2077.x11.log)

**Comment by arielj** [comment]
Hmmm the first difference I see is one is running on X11 and the other one on Wayland. This seems to be an issue with the steam deck doing something weird in game mode, doesn't seem to be an issue in Heroic itself (since it does work on the steam deck in desktop mode).

You should ask on Heroic's discord about this, more people will be able to help you there and it's specific support for a game (personally, I was able to play Cyberpunk 2077 on the steam deck in both desktop and game mode out of the box :S). Check the `#steam-deck` channel in discord and share these logs there.

I'm closing this issue since.
