### ISSUE TITLE
GOG throwing erros when trying to launch Witcher 1

### ISSUE THREAD

**Issue by rKsanu2MMYvypWePtQWM** [Heroic-Games-Launcher/HeroicGamesLauncher#1917]
### Describe the bug

Seems like a GOG component is having trouble before the Witcher gets to launch. gogdl perhaps? Tried with appimage as well as flatpak - same exact error

### Add logs

System Info:
Heroic Version: 2.4.3 Chopper
Legendary Version:  0.20.28 Dark Energy (hotfix #2)
OS: Freedesktop SDK KERNEL: 6.0.1-1-default ARCH: x64
CPU: AMD Ryzen 5 1600 Six-Core Processor @3.2 GOVERNOR: schedutil
RAM: Total: 15.55 GiB Available: 9.95 GiB
GRAPHICS: GPU0: Tonga PRO [Radeon R9 285/380] VRAM: 256MB DRIVER:  
PROTOCOL: x11

Game Settings: {
	"autoInstallDxvk": true,
	"autoInstallVkd3d": false,
	"preferSystemLibs": false,
	"maxSharpness": 2,
	"language": "",
	"nvidiaPrime": false,
	"enviromentOptions": [],
	"wrapperOptions": [],
	"savesPath": "",
	"showFps": false,
	"targetExe": "",
	"useGameMode": false,
	"winePrefix": "/home/redacted/Games/Heroic/Prefixes/The Witcher Enhanced Edition",
	"wineVersion": {
		"bin": "/home/redacted/.var/app/com.heroicgameslauncher.hgl/config/heroic/tools/wine/Wine-GE-Proton7-31/bin/wine",
		"name": "Wine - Wine-GE-Proton7-31",
		"type": "wine",
		"lib": "/home/redacted/.var/app/com.heroicgameslauncher.hgl/config/heroic/tools/wine/Wine-GE-Proton7-31/lib64",
		"lib32": "/home/redacted/.var/app/com.heroicgameslauncher.hgl/config/heroic/tools/wine/Wine-GE-Proton7-31/lib",
		"wineserver": "/home/redacted/.var/app/com.heroicgameslauncher.hgl/config/heroic/tools/wine/Wine-GE-Proton7-31/bin/wineserver",
		"wineboot": "/home/redacted/.var/app/com.heroicgameslauncher.hgl/config/heroic/tools/wine/Wine-GE-Proton7-31/bin/wineboot"
	},
	"eacRuntime": false,
	"battlEyeRuntime": false,
	"gogSaves": []
}

Game launched at: Mon Oct 17 2022 00:13:42 GMT+0300 (Eastern European Summer Time)

An exception occurred when launching the game:
TypeError: Cannot read properties of undefined (reading 'replace')
    at setup (/app/bin/heroic/resources/app.asar/build/gog/setup.js:118:82)
    at async prepareWineLaunch (/app/bin/heroic/resources/app.asar/build/launcher.js:112:9)
    at async GOGGame.launch (/app/bin/heroic/resources/app.asar/build/gog/games.js:243:119)
    at async node:electron/js2c/browser_init:189:563

### Steps to reproduce

Install Witcher
Launch Witcher

### Expected behavior

Game runs

### System Information

- OS [e. g. "Ubuntu"]: OpenSUSE Tumbleweed 20221015
- Heroic Version [e. g. 2.1.1]: 2.4.3

**Comment by arielj** [comment]
Ask about this in Heroic's Discord server, you'll get more help there (I even think it was already discussed, search for witcher 1 in the discord server and there are different things to try). The issues tracker here is for issues in the Heroic app, not for support running games.

This issues tracker is for issues in the Heroic app, not for support running games.

**Comment by sluedecke** [comment]
I kindly request reopening this one.

On my steam deck I get the same error message with heroic version "2.5.2 HOTFIX #2".  I tried searching the heroic discord for a solution, but I could not find any.

The main reason for my request is that the error message originates from heroic code, so it might be worth having a closer look.

**Comment by sluedecke** [comment]
in 2.5.2, `src/backeng/gog/setup.ts`, line 163 the workingDir value for actionArguments is not set so the replace fails.

**Comment by rKsanu2MMYvypWePtQWM** [comment]
Can confirm the game still doesn't run on the latest version. The exception in the log is the same.

The game works fine without any custom configuration when installed into Bottles from the official installer downloaded manually from GOG, so it does seem to be a Heroic launcher issue.

Also, Discord is a chat, not a place to search for information. If search engines can't see it, then it's as good as not existing in the first place.

**Comment by imLinguin** [comment]
It's definitely error on Heroic side here. I'll look into it

**Comment by sluedecke** [comment]
Thanks for looking into this once more!

regarding the missing `workingDir` value: this is taken from the .script file heroic finds in the game install folder (`backend/gog/setup.ts::obtainSetupInstructions`), but for me this file does not set one.  It's contents are:

goggame-1207658924.script:
```json
{
    "actions": [
        {
            "install": {
                "action": "Execute", 
                "arguments": {
                    "executable": "galaxy_the_witcher_enhanced_edition_2.1.0.15.exe", 
                    "runAsAdmin": true
                }
            }, 
            "name": "Install the game"
        }
    ], 
    "productId": "1207658924"
}
```

**Comment by sluedecke** [comment]
I have installed this game outside of heroic with wine and the offline installer:

* This installation can be started just fine with wine.
* This installation does not start with proton.
* This installation does not start when imported into heroic.  Instead heroic tries to run the `goggame-1207658924.script` and fails as above at the missing `workingDir`.

**Comment by sluedecke** [comment]
Ignoring the replace issue, I compared the wine prefixes for a heroic and a fresh wine install.  The game files are the same (except some missing, but probably not important files, see below).

### system.reg makes the difference

I cannot start the game using the heroic created wine prefix, BUT I can start the game with the normal wine prefix.  If I copy the system.reg from my wine prefix to the heroic wine prefix, I can start the game with the heroic wine prefix, too.

#### Missing files

I also compared the installation folders for a heroic based install versus a wine command line install.  These are the files missing from a heroic install but they do not seem to make any actual difference:

```shell
rhash --skip-ok -c ../non-heroic.rhash 

--( Verifying ../non-heroic.rhash )---------------------------------------------
The Witcher Enhanced Edition/Launch The Witcher Enhanced Edition Director's Cut.lnk No such file or directory
The Witcher Enhanced Edition/EULA.txt               No such file or directory
The Witcher Enhanced Edition/unins000.msg           No such file or directory
The Witcher Enhanced Edition/gog.ico                No such file or directory
The Witcher Enhanced Edition/unins000.dat           No such file or directory
The Witcher Enhanced Edition/goglog.ini             No such file or directory
The Witcher Enhanced Edition/GameuxInstallHelper.dll No such file or directory
The Witcher Enhanced Edition/unins000.exe           No such file or directory
The Witcher Enhanced Edition/Support.ico            No such file or directory
--------------------------------------------------------------------------------
Errors Occurred: Errors:0   Miss:9   Success:2666 Total:2675

```

**Comment by imLinguin** [comment]
The key part is the .exe that's provided in setup instructions. Keep in mind heroic does things exactly like GOG Galaxy, so it may differ a bit from the offline setup

**Comment by sluedecke** [comment]
Understood.  Still I wonder why it fails at the .script file ... how can we best investigate that part? I don't know where to look.

Heroic wants to execute `galaxy_the_witcher_enhanced_edition_2.1.0.15.exe` which I cannot find anywhere on my system.  Also it does not handle the case where `workingDir` is missing from the install script.

Also this game is around 1,19 € at the moment on gog.com, I can gift it to you or the team behind heroic if that helps getting to the root cause of this issue.

**Comment by sluedecke** [comment]
I am able to get it to run!  The Witcher: Enhanced Edition seems to use a .script which is not handled well by heroics `gog/setup.ts`.  This is the included `goggame-1207658924.script` file:

```json
{
    "actions": [
        {
            "install": {
                "action": "Execute", 
                "arguments": {
                    "executable": "galaxy_the_witcher_enhanced_edition_2.1.0.15.exe", 
                    "runAsAdmin": true
                }
            }, 
            "name": "Install the game"
        }
    ], 
    "productId": "1207658924"
}
```

The Witcher starts fine if this file is modified to be:

```json
{
    "actions": [
        {
            "install": {
                "action": "Execute", 
                "arguments": {
                    "executable": "support/1207658924/galaxy_the_witcher_enhanced_edition_2.1.0.15.exe", 
                    "runAsAdmin": true,
                    "workingDir": "{app}"
                }
            }, 
            "name": "Install the game"
        }
    ], 
    "productId": "1207658924"
}

```

Versions: Heroic 2.5.2
Wine: Wine-GE-Proton7-34
System: Arch Linux, Kernel 6.0.12-arch1-1

**Comment by imLinguin** [comment]
Yes, I'm currently checking out alternatives, and working in refactor of some of GOG integration parts

**Comment by sluedecke** [comment]
The workaround works on the steam deck, too. Whether one wants to play it on the deck is a different question - it still is a mouse/keyboard based game.

**Comment by imLinguin** [comment]
You no longer need the workaround after version 2.6.0. Just make sure you updated the heroic. 

You may need to delete wine prefix to force Heroic to re run the setup

**Comment by bartekjot** [comment]
My heroic is 2.6.2. I couldn't get Witcher to launch for the life of mine. It just save synced and went off. I've deleted prefix and re downloading now.

Will try to run on proton 7, will let you know soon.

**Comment by bartekjot** [comment]
> My heroic is 2.6.2. I couldn't get Witcher to launch for the life of mine. It just save synced and went off. I've deleted prefix and re downloading now.
> 
> Will try to run on proton 7, will let you know soon.

Not launching, fresh install, no launch using proton GE or wine

**Comment by imLinguin** [comment]
Have you tried deleting wine prefix as I suggested?  
Try doing that, launch the game and send Heroic logs

**Comment by bartekjot** [comment]
I have. Can you guide me on heroic log? Is it the one from Settings?

**Comment by imLinguin** [comment]
Yes

**Comment by bartekjot** [comment]
And as by miracle the game ran after xth attempt. Thank you for your assistance.

**Comment by sluedecke** [comment]
Happy to see it running for you and sorry for being not so fast with a response!

AFAIR the process should be:

* install game with heroic
* edit above mentioned .script file
* start witcher

But since I had to RMA my deck, this is from memory.

**Comment by imLinguin** [comment]
Now this process is just install and run, like I said above, issue is solved in Heroic 2.6.0

**Comment by kopach** [comment]
Fresh install, latest Heroic - can't launch the game (tried modifying `goggame-1207658924.script`, tried different versions of Proton)

**Comment by bartekjot** [comment]
Concur. Not able to launch.

**Comment by kopach** [comment]
@imLinguin, could you reopen this ticket?
