### ISSUE TITLE
Game won't launch after switching accounts.

### ISSUE THREAD

**Issue by BpPanic** [Heroic-Games-Launcher/HeroicGamesLauncher#1920]
I'm using a Steam Deck. After installing a game on one epic account. The game wont launch when I switch to my alternate account. The play button goes away like it's launching but, then comes back and the game doesn't launch.

**Comment by arielj** [comment]
You are changing the steam account or the heroic account? you should share some logs from heroic when you try to run the game.

**Comment by arielj** [comment]
If you are changing epic accounts, do you own the game on both accounts?

**Comment by BpPanic** [comment]
I'm dumb, didn't have it on new account

**Comment by arielj** [comment]
I'm closing this issue then. If you still have issues open a new one with more details, logs from heroic, etc.
