### ISSUE TITLE
Save-sync points to the wrong directory causing failure in syncing

### ISSUE THREAD

**Issue by Yasand123** [Heroic-Games-Launcher/HeroicGamesLauncher#1924]
### Describe the bug

Prey (2017) downloaded from Epic store; in the Save-sync section it points to the wrong directory by default.

This is the default value:
`/home/yand/.local/share/heroic/prefixes/PREY/drive_c/users/yand/Saved Games/Arkane Studios`

Changing the value to this fixed the syncing errors:
`/home/yand/.local/share/heroic/prefixes/PREY/drive_c/users/yand/Saved Games/Arkane Studios/Prey_Epic/b42d8f8782444208abb5a26fb642c819`

Yes, I changed where the games are downloaded and the prefixes are stored, but it does point to the current prefix, just not deep enough to reach the ID(?) directory.

Not sure about other games.

### Add logs

Current log doesn't show the issue as I've ran the game once after fixing it. It just shows the typical wine fixme warnings:

```
0174:fixme:d3dcompiler:skip_u32_unknown Skipping 4 unknown u32s:
0174:fixme:d3dcompiler:skip_u32_unknown 	0xffffffff
0174:fixme:d3dcompiler:skip_u32_unknown 	0x00000000
0174:fixme:d3dcompiler:skip_u32_unknown 	0xffffffff
0174:fixme:d3dcompiler:skip_u32_unknown 	0x00000000
0174:fixme:d3dcompiler:skip_u32_unknown Skipping 4 unknown u32s:
0174:fixme:d3dcompiler:skip_u32_unknown 	0xffffffff
0174:fixme:d3dcompiler:skip_u32_unknown 	0x00000000
0174:fixme:d3dcompiler:skip_u32_unknown 	0xffffffff
0174:fixme:d3dcompiler:skip_u32_unknown 	0x00000000
```

However previously it would say that the data on the cloud is N/A after uploading or force uploading.

### Steps to reproduce

1. Download an Epic game
2. Play and make sure to create a save file
3. Syncing will fail

### Expected behavior

For syncing to work out of the box, or at least to get a descriptive/helpful error message (although that I suppose is on Legendary).

### System Information

- ArchLinux 6.0.1
- Heroic 2.4.3 (`heroic-games-launcher-bin` from AUR)

**Comment by Yasand123** [comment]
Update: Tried another Epic game, A Plague Tale Innocence and it works fine out of the box. So it seems only some games are affected.

**Comment by Nocccer** [comment]
We can't detect all save paths. There are so many places where developer can put them. We might fix this is we have a game db where we store workarounds and settings. For now you need to check them by yourselfs.

**Comment by Yasand123** [comment]
> 

That is very true. Why not create a github issue where people can post these locations for games they have to help out. I'm not sure how practical that is but it's something, even if it won't help the developers it can help people set their paths manually.
