### ISSUE TITLE
Parental Controls / Family View

### ISSUE THREAD

**Issue by sketchbook22** [Heroic-Games-Launcher/HeroicGamesLauncher#1927]
### Problem description

My Epic Games account has a mixture of games.  Some that I would let my kids play and some that I would not.  Also I would not let my kids browse the Epic Games store page.  So far this has meant that I only give them access to my steam games.  Steam allows me to configure Family View to only show the games I want them to play, and to block the store page.  

### Feature description

- If "Family View" is configured, Heroic Launcher starts with "Family View" active.
- When "Family View" is active block all Left Menu tabs except the Library Tab.
- Clicking the eye icon in the Library Tab to show/hide games, also toggles "Family View" inactive/active & requires a pin to exit Family View / show hidden games
- Some way to reset "Family View" pin via email.

(Epic games actually already has a pin feature, if you have a way to auth against that pin, you wouldn't need to implement "pin reset" for this feature)

optional feature:
If "Family View" is configured, games that are new to the library will default to hidden = true.  

About optional feature:
That way "Family View" acts as a white list.  NOTE: If you activate a game in steam while in Family View it does show a popup "This game is not available in family view".  If you worry this would confuse users, then don't do this feature;  black-list behavior is enough for me.

### Alternatives

I have contacted Epic Games, and they told me to start a separate account and re-buy the kids games on that account, which still wouldn't completely solve the problem.

I have gone as far as to manually configure specific Epic Games to launch using Legendary and added those one by one to the steam launcher.  And realized I would have to do that again for each PC, and controller support was lacking, and I occasionally needed to repair my legendary configurations...  
You have solved many of these headaches with Heroic Games Launcher, very impressive.  I tried many other ways to get controller support working for Totally Reliable Delivery Service, and with Heroic Games Launcher... It just works!  A basic "Family View" type feature would help me greatly.

**Comment by sketchbook22** [comment]
While I still think the above request is nice to have...
The Add To Steam feature can be used to achieve my goal of sharing specific games with my kids.
If others are interested: the Add To Steam button is located in the Front End interface under Game page > Tools.

**Comment by arielj** [comment]
I like the idea of this feature, but we can't rely on one store's pin feature for example since we aim to support multiple stored, we would have to implement this feature on some servers we own and that's a complete different feature we would need first (and I don't think we want to deal with that, a lot of complexity and privacy concerns). I like the idea, maybe if it can be implemented securely locally it could work but we would also have to start encrypting files I think to not allow kids to change configuration files manually either which is also complicated.

**Comment by sketchbook22** [comment]
@arielj Understandable.  I have a **wild idea** that probably has more problems than it's worth;  I'll share it anyway...   Could you store stuff on epic like games do?  If needed, could parental controls be a "game", and then result in local files that Heroic uses locally?  Could this also help with sharing settings between machines?  https://dev.epicgames.com/docs/game-services/player-data-storage  I realize (even if it somehow worked) that would make heroic oddly dependent on epic, while that is not the only store it works for.

**Comment by arielj** [comment]
We would be depending on the epic store, and we would be storing user info on epic servers. I don't think it's good for privacy (is somebody doesn't like epic they wouldn't want their data there either) or if epic servers change anything we have no control over that.

Handling data from users is really complicated and has some legal stuff to consider depending on where in the world your user lives, like you have to be GDPR compliant for example if you collect information from users in Europe and that means a lot of things. It would have to become a full time paid job hahah. I don't think it's worth to try any online solution. If we want to add these features it's probably good to start with just local stuff and users manually copying files from one place to the other, it's not that user friendly of a `sync config` button on the cloud but it's orders of magnitude simpler less complex.
