### ISSUE TITLE
Option to ignore disk space requirement

### ISSUE THREAD

**Issue by Espionage724** [Heroic-Games-Launcher/HeroicGamesLauncher#1928]
### Problem description

![Disk space error](https://i.imgur.com/HHid5q0.png)

On Windows I disabled performance counters and other stuff for a test, and it seems something causes Heroic to not be able to detect free disk space, and thus causes it to gray-out the Install option for games.

I have plenty of free space and would like Heroic to not check it.

### Feature description

Add advanced option in Heroic to ignore disk space checks.

### Additional information

I suspect it's either the pla Windows Service, or the service that controls WMI.

**Comment by flavioislima** [comment]
Yes, we are doing that from the next release.
Will be an option to continue anyway.

**Comment by Nocccer** [comment]
It sounds like that powershell or wmi is failing. What does the logs say? There should be a error, telling you what failed.

**Comment by arielj** [comment]
Closing since from Flavios' comment this was implemented at some point.
