### ISSUE TITLE
GTA V: Entering Story Mode Stuck

### ISSUE THREAD

**Issue by canyesilyurt** [Heroic-Games-Launcher/HeroicGamesLauncher#1929]
### Describe the bug

GTA V: When logging in, it freezes in the logging into story mode area and stays on the loading screen for hours. I did some research and read that the problem will be solved by setting the vsync value to 2 if it is 1 and 1 if it is 2 on the Documents > Rockstar Games > GTA V > settings.xml file. I tried these solutions but my problem still persists. I repaired and even deleted the game and reinstalled it but my problem still persists. Please help me.

### Add logs

(16:25:03) INFO:    [Legendary]:       Running command: /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/legendary --version
(16:25:12) INFO:    [Legendary]:       Legendary location: /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/legendary
(16:25:12) INFO:    [Gog]:             GOGDL location: /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/gogdl
(16:25:12) INFO:    [Backend]:         

Heroic Version: 2.4.3 Chopper
Legendary Version:  0.20.28 Dark Energy (hotfix #2)
OS: macOS KERNEL: 21.6.0 ARCH: x64
CPU: Apple M1 @2.4 
RAM: Total: 16 GiB Available: 12.4 GiB
GRAPHICS: GPU0: Apple M1 VRAM: nullMB DRIVER:  

(16:25:12) WARNING: [Backend]:         Protocol already registered.
(16:25:15) INFO:    [Backend]:         Checking for new Heroic Updates
(16:25:15) INFO:    [Frontend]:        Refreshing Library
(16:25:15) INFO:    [Legendary]:       Refreshing library...
(16:25:15) INFO:    [Legendary]:       Refreshing Epic Games...
(16:25:16) INFO:    [Legendary]:       Running command: /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/legendary list
(16:25:24) INFO:    [Legendary]:       Updating game list
(16:25:24) INFO:    [Legendary]:       Game List Updated
(16:25:24) INFO:    [Legendary]:       Checking for game updates.
(16:25:24) INFO:    [Legendary]:       Running command: /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/legendary list-installed --check-updates --tsv

### Steps to reproduce

2. Click on '...'
3. Scroll down to '...'

### Expected behavior

GTA V: When logging in, it freezes in the logging into story mode area and stays on the loading screen for hours. I did some research and read that the problem will be solved by setting the vsync value to 2 if it is 1 and 1 if it is 2 on the Documents > Rockstar Games > GTA V > settings.xml file. I tried these solutions but my problem still persists. I repaired and even deleted the game and reinstalled it but my problem still persists. Please help me.

### System Information

- OS [e. g. "Ubuntu"]: Mac Mini
- Heroic Version [e. g. 2.1.1]: 2.4.3

**Comment by Nocccer** [comment]
Please head over to our discord server. People can help there. This issue tracker is only for heroic issues not for game issues. As soon as you see wine is running, it is not a problem of heroic anymore.
