### ISSUE TITLE
Dialogs are closed when clicking the `buttons` area

### ISSUE THREAD

**Issue by arielj** [Heroic-Games-Launcher/HeroicGamesLauncher#1931]
### Describe the bug

When clicking on the empty space at the left of the dialog's buttons, the dialog gets closed. The area marked in red here:
![image](https://user-images.githubusercontent.com/188464/197318228-f187d8ee-2da9-402a-8b87-681de02e8d96.png)

This shouldn't happen since the user is clicking inside the dialog.

### Add logs

Nothing relevant

### Steps to reproduce

1. Do any action that triggers a Dialog component
2. Click the empty space at the left of the buttons
3. The dialog is closed

### Expected behavior

The dialog should not be closed clicking that area.

### System Information

- Heroic Version [e. g. 2.1.1]: happens in main and in beta

**Comment by wbrtm** [comment]
Looks like this issue can be closed.
