### ISSUE TITLE
`(i)` icon in alternative login method for Epic links to a `SID` PR

### ISSUE THREAD

**Issue by arielj** [Heroic-Games-Launcher/HeroicGamesLauncher#1934]
### Describe the bug

When using the Alternative/External login for Epic, there's a `(i)` icon that would explain what's the `autorhization code information number` step, but it link to https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/issues/42 which explains the SID number.

I mean this icon at the end of step 1:
![image](https://user-images.githubusercontent.com/188464/197350973-4572fa43-6751-4f49-b77e-0a0ec3df8be9.png)

### Add logs

Nothing relevant

### Steps to reproduce

1. Go to Manage Account
2. Click the External login / Alternative login option for Epic
3. Click the `(i)` icon

### Expected behavior

It should link to a page explaining what's the Authorization Code instead of the SID.

Nice to have: Link to a WIKI page explaining that and maybe the complete alt login flow (with screenshots, examples, caveats, etc), that page does not exist currently.

### System Information

- Heroic Version [e. g. 2.1.1]: Since 2.4.3 that we had to change from SID to auth code

**Comment by flavioislima** [comment]
fixed
