### ISSUE TITLE
Winetricks needs --force option

### ISSUE THREAD

**Issue by LiamDawe** [Heroic-Games-Launcher/HeroicGamesLauncher#1935]
### Problem description

Testing the unreleased AppImage -> https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/actions/runs/3296557369

If you try to install dotnet in Winetricks, it gives an error about it needing a new version of Wine to run otherwise it doesn't work. It tells you to run it with "--force" to allow it but Heroic doesn't seem to have the option.

Reason being: it seems to detect various Wine installs as old.

Additionally: only seems to be an issue on Wine GE which is what reports an old version. Latest Lutris Wine is fine.

### Feature description

Add a way to use "--force" in Winetricks.

**Comment by flavioislima** [comment]
Although this makes sense, the root issue here is that Wine-GE does not report the correct Wine version, should this not be something that GE should fix?

**Comment by flavioislima** [comment]
Implemented on #2108
