### ISSUE TITLE
Processing files, please wait. Looks like it is not doing anything. 

### ISSUE THREAD

**Issue by fatihG** [Heroic-Games-Launcher/HeroicGamesLauncher#1942]
### Problem description

I have tried multiple times today to get Cyberpunk to install via Heroic with GOG. 

Multiple times I had to relaunch the app to get the download to continue and all that, but that is beside the scope of this request. 

At the end of the download, when it did finally reach 100% the message 'Processing files, please wait' showed up. 
And while that is fine and dandy, it appear as if nothing happens. It is a static message. (did the app freeze? is it actually doing anything?)
Checking the logs isnt really helpfull either as it just keep posting the same message every second. 

### Feature description

I think it would be useful to have some visual, non static element to the final part of the install. 

Something simple as 3 periods that appear and disappear. Even better to show read/write speeds, of Herioc, that update every second, to show that the app is doing actually writing data.

### Alternatives

More descriptive text for each step. 

'downloading X%' and when it done downloading, have a checkmark appear. At least we will know that step is done and the user knows not to worry about the download failing. 
'Installing X%' 
'Processing files 32mb/s'

Etc.

**Comment by flavioislima** [comment]
Now you can see the disk activity on the downloads screen
