### ISSUE TITLE
Actions can be performed in games while they are being uninstalled

### ISSUE THREAD

**Issue by arielj** [Heroic-Games-Launcher/HeroicGamesLauncher#1951]
### Describe the bug

When uninstalling a game, all the actions that you can do on installed games are available (force update, add shortcuts, verify and repair, even uninstall while uninstalling).

This can lead to a lot of unexpected problems of conflicting actions happening at the same time.

### Add logs

Nothing relevant.

### Steps to reproduce

1. Install a game
2. Right click the card
3. Click Uninstall
4. Confirm
5. While the game is uninstalling you can try any option like play, right click > uninstall again, etc

Same thing can be done in the game page with even more options to click (move, repair, uninstall again, etc)

### Expected behavior

When uninstalling a game is confirmed, since it is an irreversible action we should disable all other actions that are related to the game installation status (we can still show things like hide/favorites/store link/check compatibility)

### System Information

- Heroic Version [e. g. 2.1.1]: 2.4.3 and beta

### Additional information

I addressed a bit of this here https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/pull/1950 disabling the play buttons, but there are many more actions that should be handled better.

**Comment by flavioislima** [comment]
I think what you did on your PR will cover 99% of the cases and I believe this is not something common to do, ask to uninstall and then try to do something. Only if the person has the intention to break the app. It think we can close this one since most cases are covered.
