### ISSUE TITLE
Native wayland

### ISSUE THREAD

**Issue by jumpers775** [Heroic-Games-Launcher/HeroicGamesLauncher#1963]
### Problem description

running this requires X11 to be installed, even on a wayland system as it uses X11. 

### Feature description

Allowing this to run on wayland would be nice. 

### Additional information

Running it with `--enable-features=UseOzonePlatform --ozone-platform=wayland` works great, although it lacks a titlebar.

**Comment by Etaash-mathamsetty** [comment]
> ### Problem description
> 
> running this requires X11 to be installed, even on a wayland system as it uses X11.
> ### Feature description
> 
> Allowing this to run on wayland would be nice.
> ### Alternatives
> 
> _No response_
> ### Additional information
> 
> Running it with `--enable-features=UseOzonePlatform --ozone-platform=wayland` works great, although it lacks a titlebar.

it works fine with wayland for me, titlebar is there and everything, works perfectly (I haven't daily driven it tho) + the electron version in the latest stable is electron 20, the I updated the beta to 21, so that's not the problem

**Comment by flavioislima** [comment]
It is being a long time since heroic works in Wayland now.
Maybe you have an issue with your OS install.

**Comment by flavioislima** [comment]
I think I understand what you mean now, probably related with this new feature in electron:
https://github.com/electron/electron/pull/34937
