### ISSUE TITLE
After logout, settings are reseted

### ISSUE THREAD

**Issue by arielj** [Heroic-Games-Launcher/HeroicGamesLauncher#1965]
### Describe the bug

When you log out from a store, some settings are deleted (I didn't check exactly which ones, but at least the theme is reseted). This is an issue because you are still logged in with an account.

### Add logs

Nothing relevant.

### Steps to reproduce

1. Login with both epic and gog
2. Change your theme
3. Log out from one of the stores
4. The theme (along with other settings most likely) are reseted as the initial default values

### Expected behavior

It should not reset the settings.

### System Information

- Heroic Version [e. g. 2.1.1]: main and beta

**Comment by CommandMC** [comment]
Resolved with #2054
