### ISSUE TITLE
When logging out from an account, there's no feedback to the user that something is happening

### ISSUE THREAD

**Issue by arielj** [Heroic-Games-Launcher/HeroicGamesLauncher#1966]
### Describe the bug

When a user clicks `Log out`, nothing happens until the user is finally logged out. If the system is slow for any reason, it may look like nothing is happening.

### Add logs

Nothing relevant, just the logout command.

### Steps to reproduce

1. Login to an account
2. Click 'log out'

### Expected behavior

There should be some indication that something is happening, like changing the text to `logging out`, disabling the button, etc (any other ideas that might be more clear are welcomed)

### System Information

- Heroic Version [e. g. 2.1.1]: main and beta

**Comment by Flexicon** [comment]
@arielj  This can be closed since #2175 was merged, right?

**Comment by arielj** [comment]
yes, it looks like it's done
