### ISSUE TITLE
Steam Deck - Unable to createio-slave. Unknown protocol 'heroic'.

### ISSUE THREAD

**Issue by skunkworxdark** [Heroic-Games-Launcher/HeroicGamesLauncher#1970]
### Describe the bug

When I try and run any installed game from my steam deck desktop shortcut that was created from the heroic launcher I get the following error :

![image](https://user-images.githubusercontent.com/21961335/199035313-dee67ba6-d300-40ba-8c07-d24154fb3dc1.png)

I have looked at the issues #577 #689 #1350 and followed the advice there but I don't seem to get any further.  When I add the game to steam and run it from there it doesn't run either I suspect it is for the same reason but I don't see any error when I do that. 

my minmeapps.list has the following line:
x-scheme-handler/heroic=com.heroicgameslauncher.hgl.desktop

### Add logs

(14:35:23) INFO:    [Legendary]:       Running command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary --version
(14:35:24) INFO:    [Legendary]:       Legendary location: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary
(14:35:24) INFO:    [Gog]:             GOGDL location: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl
(14:35:24) INFO:    [Backend]:         

Heroic Version: 2.4.3 Chopper
Legendary Version:  0.20.28 Dark Energy (hotfix #2)
OS: Freedesktop SDK KERNEL: 5.13.0-valve21.3-1-neptune ARCH: x64
CPU: AMD Custom APU 0405 @1.78 GOVERNOR: schedutil
RAM: Total: 14.49 GiB Available: 11.86 GiB
GRAPHICS: GPU0: VanGogh [AMD Custom GPU 0405] VRAM: 512MB DRIVER:  
PROTOCOL: x11

(14:35:24) INFO:    [Gog]:             Getting data about the user
(14:35:24) INFO:    [Gog]:             Refreshing access_token
(14:35:24) WARNING: [Backend]:         Failed to register protocol with OS.
(14:35:24) INFO:    [Backend]:         AreWeAntiCheatYet data downloaded
(14:35:24) INFO:    [Gog]:             Token refreshed successfully
(14:35:25) INFO:    [Gog]:             Saved user data to config
(14:35:25) INFO:    [Frontend]:        Refreshing Library
(14:35:25) INFO:    [Legendary]:       Refreshing library...
(14:35:25) INFO:    [Legendary]:       Refreshing Epic Games...
(14:35:25) INFO:    [Gog]:             Getting GOG library
(14:35:25) INFO:    [Gog]:             Number of library pages: 1
(14:35:26) INFO:    [Legendary]:       Running command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary list
(14:35:26) INFO:    [Gog]:             Saved games data
(14:35:27) INFO:    [Backend]:         Downloaded Winetricks
(14:35:27) INFO:    [Legendary]:       Updating game list
(14:35:27) INFO:    [Legendary]:       Game List Updated
(14:35:27) INFO:    [Legendary]:       Checking for game updates.
(14:35:27) INFO:    [Legendary]:       Running command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary list-installed --check-updates --tsv
(14:35:28) INFO:    [Legendary]:       Found 0 game(s) to update
(14:35:29) INFO:    [Gog]:             Found 0 game(s) to update

### Steps to reproduce

1. Install a Game
2. Create a Desktop Shortcut
3. Double click on the desktop shortcut

### Expected behavior

I would expect it to run the game. 

### Screenshots

![image](https://user-images.githubusercontent.com/21961335/199033248-c816c737-3d32-4920-b8cc-d8798e6599d1.png)

### System Information

- OS: SteamOS 3.3.2 
- Heroic Version: 2.4.3

**Comment by flavioislima** [comment]
This won't work probably because the protocol is not working with flatpak, you will need to add the games to steam instead of using desktop shortcuts
