### ISSUE TITLE
Shortcuts do not work under 2.5.0 beta 1

### ISSUE THREAD

**Issue by johndoe9867** [Heroic-Games-Launcher/HeroicGamesLauncher#1972]
### Describe the bug

When ever using a shortcut under the 2.5.0 beta 1, the shortcut will not work saying "undefined Currently not installed." Launching through Heroic directly works as expected. It worked just fine under the latest stable. Also tested in virtual machine with clean install and same issue happens

### Add logs

(17:01:25) INFO:    [Connection]:       Connectivity: check-online
(17:01:25) INFO:    [Connection]:       Pinging external endpoints
(17:01:25) INFO:    [Legendary]:        Running command: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary --version
(17:01:25) INFO:    [Legendary]:        Legendary location: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary
(17:01:25) INFO:    [Gog]:              GOGDL location: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl
(17:01:25) WARNING: [Backend]:          Protocol already registered.
(17:01:26) INFO:    [Gog]:              Running command: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --version
(17:01:26) INFO:    [Connection]:       Connectivity: online
(17:01:26) INFO:    [Backend]:          User Not Found, removing it from Store
(17:01:26) INFO:    [Gog]:              Getting data about the user
(17:01:26) INFO:    [Gog]:              Refreshing access_token
(17:01:26) INFO:    [Backend]:          AreWeAntiCheatYet data downloaded
(17:01:26) INFO:    [Backend]:          

Heroic Version: 2.5.0-beta.1 Caesar Clown
Legendary Version:  0.20.30 Dark Energy (hotfix #4)
GOGdl Version: 0.5
OS: Arch KERNEL: 6.0.6-arch1-1 ARCH: x64
CPU: AMD Ryzen 5 5600 6-Core Processor @3.93 GOVERNOR: schedutil
RAM: Total: 15.53 GiB Available: 12.83 GiB
GRAPHICS: GPU0: NVIDIA GeForce RTX 3060 VRAM: 12288MB DRIVER: 520.56.06 
PROTOCOL: wayland

(17:01:26) INFO:    [Gog]:              Token refreshed successfully
(17:01:26) INFO:    [Backend]:          Checking for new Heroic Updates
(17:01:26) INFO:    [Frontend]:         Refreshing Library
(17:01:26) INFO:    [Legendary]:        Refreshing library...
(17:01:26) INFO:    [Gog]:              Getting GOG library
(17:01:26) INFO:    [Gog]:              Saved user data to config
(17:01:27) INFO:    [Gog]:              Number of library pages: 1
(17:01:27) INFO:    [Gog]:              Saved games data
(17:01:27) INFO:    [Frontend]:         No cache found, getting data from legendary...
(17:01:27) INFO:    [Legendary]:        Refreshing library...
(17:01:28) INFO:    [DXVKInstaller]:    Updating vkd3d to: vkd3d-proton-2.7.tar.xz
(17:01:28) INFO:    [Winetricks]:       Downloaded Winetricks
(17:01:29) INFO:    [Gog]:              Getting game metadata: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl info 1881970704 --token <redacted> --lang=en-US --os windows
(17:01:29) INFO:    [DXVKInstaller]:    downloaded vkd3d
(17:01:29) INFO:    [DXVKInstaller]:    extracting vkd3d
(17:01:29) INFO:    [DXVKInstaller]:    extracting vkd3d updated!
(17:01:33) INFO:    [Backend]:          Shortcut saved on /home/user/Desktop/Batman™: Arkham Knight.desktop
(17:01:33) INFO:    [Backend]:          Shortcut saved on /home/user/.local/share/applications/Batman™: Arkham Knight.desktop
(17:01:37) INFO:    [ProtocolHandler]:  received 'heroic://launch/1881970704'
(17:01:37) WARNING: [Legendary]:        Requested game 1881970704 was not found in library
(17:01:37) ERROR:   [Legendary]:        Could not get game info for 1881970704, returning empty object. Something is probably gonna go wrong soon
(17:01:37) INFO:    [ProtocolHandler]:  "1881970704" not installed.
(17:04:21) INFO:    [ProtocolHandler]:  Not installing game

### Steps to reproduce

1. Go to game and create shortcut
2. Launch game from desktop or steam shortcut
3.  Popup will show up

### Expected behavior

Shortcut should just launch the game.

### Screenshots

![bug](https://user-images.githubusercontent.com/117124748/199119624-8149bb62-b311-4102-a5e9-2bcb5c64cf6c.png)

### System Information

- OS: Arch
- Heroic Version 2.5.0 beta 1

**Comment by arielj** [comment]
is it a GOG game? if so it's a known issue and should probably be fixed by this https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/pull/1969

**Comment by flavioislima** [comment]
It is also broken on Windows in a different way, the shortcut files are empty.
And the Issue with GOG games happens on both Windows and Linux.
