### ISSUE TITLE
Games not opening

### ISSUE THREAD

**Issue by jamesx0416** [Heroic-Games-Launcher/HeroicGamesLauncher#1974]
### Describe the bug

When I try to open a game(Fortnite), it starts to load but then it stops without the game or a error popping up.
Chromebook(Version 106.0.5249.112 (Official Build) (64-bit)) Linux

### Add logs

(20:47:32) INFO:    [Connection]:       Connectivity: check-online
(20:47:32) INFO:    [Connection]:       Pinging external endpoints
(20:47:32) INFO:    [Legendary]:        Running command: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary --version
(20:47:32) INFO:    [Legendary]:        Legendary location: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary
(20:47:32) INFO:    [Gog]:              GOGDL location: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl
(20:47:33) WARNING: [Backend]:          Protocol already registered.
(20:47:33) INFO:    [Gog]:              Running command: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --version
(20:47:34) INFO:    [Connection]:       All ping requests failed:
(20:47:34) INFO:    [Connection]:       AggregateError: All promises were rejected
(20:47:35) INFO:    [Backend]:          

Heroic Version: 2.5.0-beta.1 Caesar Clown
Legendary Version:  0.20.30 Dark Energy (hotfix #4)
GOGdl Version: 0.5
OS: Debian GNU/Linux KERNEL: 5.10.136-19393-g8d1faf8b57d7 ARCH: x64
CPU: AMD 3015Ce with Radeon Graphics @1.2 
RAM: Total: 2.77 GiB Available: 2.48 GiB
GRAPHICS: 
PROTOCOL: 

(20:47:35) WARNING: [DXVKInstaller]:    App offline, skipping possible DXVK update.
(20:47:36) INFO:    [Backend]:          Checking for new Heroic Updates
(20:47:36) INFO:    [Frontend]:         Refreshing Library
(20:47:36) INFO:    [Legendary]:        Refreshing library...
(20:47:36) INFO:    [Legendary]:        Refreshing Epic Games...
(20:47:37) INFO:    [Legendary]:        Game list updated, got 2 games & DLCs
(20:47:37) INFO:    [Legendary]:        Running command: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary list
(20:47:40) INFO:    [Connection]:       Pinging external endpoints
(20:47:40) INFO:    [Connection]:       Connectivity: online
(20:47:41) INFO:    [Backend]:          AreWeAntiCheatYet data downloaded
(20:49:11) DEBUG:   [Legendary]:        Using cached install info
(20:49:11) DEBUG:   [Backend]:          Unable to load Steam Libraries, libraryfolders.vdf not found
(20:49:11) DEBUG:   [Backend]:          {"free":20067975168,"diskSize":61849174016,"message":"18.69 GiB / 57.6 GiB","validPath":true}
(20:49:11) DEBUG:   [Backend]:          {"free":20067975168,"diskSize":61849174016,"message":"18.69 GiB / 57.6 GiB","validPath":true}
(20:49:11) DEBUG:   [Backend]:          {"free":20067975168,"diskSize":61849174016,"message":"18.69 GiB / 57.6 GiB","validPath":true}
(20:50:54) INFO:    [Backend]:          Launching Clash of Clans (6uzZqoxLAg1StTtxVKg4PA)
(20:50:54) INFO:    [Backend]:          Preventing display from sleep
(20:50:56) INFO:    [Backend]:          launching non-native sideloaded: /home/xijam/com.supercell.clashofclans_1.0.12067.123.exe}
(20:50:56) ERROR:   [Backend]:          Couldn't find all library folders of Custom Wine - /mnt/chromeos/removable/James Lexar/wine-lutris-GE-Proton7-33-x86_64.tar.xz!
Missing undefined and/or undefined!
Falling back to system libraries!
(20:50:56) DEBUG:   [Backend]:          Running Wine command: /home/xijam/com.supercell.clashofclans_1.0.12067.123.exe
(20:50:56) DEBUG:   [Backend]:          Logging to file "/home/xijam/.config/heroic/GamesConfig/6uzZqoxLAg1StTtxVKg4PA-lastPlay.log"
(20:50:56) INFO:    [Backend]:          Stopping Display Power Saver Blocker
(20:50:56) INFO:    [Frontend]:         Refreshing Library
(20:50:56) INFO:    [Legendary]:        Refreshing library...
(20:50:56) INFO:    [Legendary]:        Game list updated, got 2 games & DLCs
(20:51:07) INFO:    [Backend]:          Writing config for Heroic
(20:51:07) INFO:    [Backend]:          {
  "checkUpdatesInterval": 10,
  "enableUpdates": false,
  "addDesktopShortcuts": false,
  "addStartMenuShortcuts": false,
  "autoInstallDxvk": false,
  "autoInstallVkd3d": false,
  "addSteamShortcuts": false,
  "preferSystemLibs": false,
  "checkForUpdatesOnStartup": true,
  "customWinePaths": [
    "/mnt/chromeos/removable/James Lexar/wine-lutris-GE-Proton7-33-x86_64.tar.xz"
  ],
  "defaultInstallPath": "/mnt/chromeos/removable/James Lexar",
  "defaultSteamPath": "/home/xijam/.steam/steam",
  "defaultWinePrefix": "/home/xijam/Games/Heroic/Prefixes",
  "language": "en",
  "maxWorkers": 0,
  "minimizeOnLaunch": false,
  "nvidiaPrime": false,
  "enviromentOptions": [],
  "wrapperOptions": [],
  "showFps": true,
  "useGameMode": false,
  "userInfo": {
    "epicId": "c9306703314e4ade8d8c01ee7de3e879",
    "name": "xijam"
  },
  "wineCrossoverBottle": "Heroic",
  "winePrefix": "/home/xijam/.wine",
  "wineVersion": {
    "bin": "/home/xijam/.config/heroic/tools/wine/Wine-GE-Proton7-33/bin/wine",
    "name": "Wine - Wine-GE-Proton7-33",
    "type": "wine",
    "lib": "/home/xijam/.config/heroic/tools/wine/Wine-GE-Proton7-33/lib64",
    "lib32": "/home/xijam/.config/heroic/tools/wine/Wine-GE-Proton7-33/lib",
    "wineserver": "/home/xijam/.config/heroic/tools/wine/Wine-GE-Proton7-33/bin/wineserver",
    "wineboot": "/home/xijam/.config/heroic/tools/wine/Wine-GE-Proton7-33/bin/wineboot"
  },
  "altLegendaryBin": "",
  "altGogdlBin": "",
  "disableController": false,
  "egsLinkedPath": "",
  "maxRecentGames": 5,
  "showUnrealMarket": false,
  "eacRuntime": false,
  "battlEyeRuntime": false
}
(20:51:15) INFO:    [Backend]:          Writing config for Heroic
(20:51:15) INFO:    [Backend]:          {
  "checkUpdatesInterval": 10,
  "enableUpdates": false,
  "addDesktopShortcuts": false,
  "addStartMenuShortcuts": false,
  "autoInstallDxvk": false,
  "autoInstallVkd3d": false,
  "addSteamShortcuts": true,
  "preferSystemLibs": false,
  "checkForUpdatesOnStartup": true,
  "customWinePaths": [
    "/mnt/chromeos/removable/James Lexar/wine-lutris-GE-Proton7-33-x86_64.tar.xz"
  ],
  "defaultInstallPath": "/mnt/chromeos/removable/James Lexar",
  "defaultSteamPath": "/home/xijam/.steam/steam",
  "defaultWinePrefix": "/home/xijam/Games/Heroic/Prefixes",
  "language": "en",
  "maxWorkers": 0,
  "minimizeOnLaunch": false,
  "nvidiaPrime": false,
  "enviromentOptions": [],
  "wrapperOptions": [],
  "showFps": true,
  "useGameMode": false,
  "userInfo": {
    "epicId": "c9306703314e4ade8d8c01ee7de3e879",
    "name": "xijam"
  },
  "wineCrossoverBottle": "Heroic",
  "winePrefix": "/home/xijam/.wine",
  "wineVersion": {
    "bin": "/home/xijam/.config/heroic/tools/wine/Wine-GE-Proton7-33/bin/wine",
    "name": "Wine - Wine-GE-Proton7-33",
    "type": "wine",
    "lib": "/home/xijam/.config/heroic/tools/wine/Wine-GE-Proton7-33/lib64",
    "lib32": "/home/xijam/.config/heroic/tools/wine/Wine-GE-Proton7-33/lib",
    "wineserver": "/home/xijam/.config/heroic/tools/wine/Wine-GE-Proton7-33/bin/wineserver",
    "wineboot": "/home/xijam/.config/heroic/tools/wine/Wine-GE-Proton7-33/bin/wineboot"
  },
  "altLegendaryBin": "",
  "altGogdlBin": "",
  "disableController": false,
  "egsLinkedPath": "",
  "maxRecentGames": 5,
  "showUnrealMarket": false,
  "eacRuntime": false,
  "battlEyeRuntime": false
}
(20:51:17) INFO:    [Backend]:          Writing config for Heroic
(20:51:17) INFO:    [Backend]:          {
  "checkUpdatesInterval": 10,
  "enableUpdates": false,
  "addDesktopShortcuts": false,
  "addStartMenuShortcuts": true,
  "autoInstallDxvk": false,
  "autoInstallVkd3d": false,
  "addSteamShortcuts": true,
  "preferSystemLibs": false,
  "checkForUpdatesOnStartup": true,
  "customWinePaths": [
    "/mnt/chromeos/removable/James Lexar/wine-lutris-GE-Proton7-33-x86_64.tar.xz"
  ],
  "defaultInstallPath": "/mnt/chromeos/removable/James Lexar",
  "defaultSteamPath": "/home/xijam/.steam/steam",
  "defaultWinePrefix": "/home/xijam/Games/Heroic/Prefixes",
  "language": "en",
  "maxWorkers": 0,
  "minimizeOnLaunch": false,
  "nvidiaPrime": false,
  "enviromentOptions": [],
  "wrapperOptions": [],
  "showFps": true,
  "useGameMode": false,
  "userInfo": {
    "epicId": "c9306703314e4ade8d8c01ee7de3e879",
    "name": "xijam"
  },
  "wineCrossoverBottle": "Heroic",
  "winePrefix": "/home/xijam/.wine",
  "wineVersion": {
    "bin": "/home/xijam/.config/heroic/tools/wine/Wine-GE-Proton7-33/bin/wine",
    "name": "Wine - Wine-GE-Proton7-33",
    "type": "wine",
    "lib": "/home/xijam/.config/heroic/tools/wine/Wine-GE-Proton7-33/lib64",
    "lib32": "/home/xijam/.config/heroic/tools/wine/Wine-GE-Proton7-33/lib",
    "wineserver": "/home/xijam/.config/heroic/tools/wine/Wine-GE-Proton7-33/bin/wineserver",
    "wineboot": "/home/xijam/.config/heroic/tools/wine/Wine-GE-Proton7-33/bin/wineboot"
  },
  "altLegendaryBin": "",
  "altGogdlBin": "",
  "disableController": false,
  "egsLinkedPath": "",
  "maxRecentGames": 5,
  "showUnrealMarket": false,
  "eacRuntime": false,
  "battlEyeRuntime": false
}
(20:51:20) INFO:    [Backend]:          Writing config for Heroic
(20:51:20) INFO:    [Backend]:          {
  "checkUpdatesInterval": 10,
  "enableUpdates": false,
  "addDesktopShortcuts": true,
  "addStartMenuShortcuts": true,
  "autoInstallDxvk": false,
  "autoInstallVkd3d": false,
  "addSteamShortcuts": true,
  "preferSystemLibs": false,
  "checkForUpdatesOnStartup": true,
  "customWinePaths": [
    "/mnt/chromeos/removable/James Lexar/wine-lutris-GE-Proton7-33-x86_64.tar.xz"
  ],
  "defaultInstallPath": "/mnt/chromeos/removable/James Lexar",
  "defaultSteamPath": "/home/xijam/.steam/steam",
  "defaultWinePrefix": "/home/xijam/Games/Heroic/Prefixes",
  "language": "en",
  "maxWorkers": 0,
  "minimizeOnLaunch": false,
  "nvidiaPrime": false,
  "enviromentOptions": [],
  "wrapperOptions": [],
  "showFps": true,
  "useGameMode": false,
  "userInfo": {
    "epicId": "c9306703314e4ade8d8c01ee7de3e879",
    "name": "xijam"
  },
  "wineCrossoverBottle": "Heroic",
  "winePrefix": "/home/xijam/.wine",
  "wineVersion": {
    "bin": "/home/xijam/.config/heroic/tools/wine/Wine-GE-Proton7-33/bin/wine",
    "name": "Wine - Wine-GE-Proton7-33",
    "type": "wine",
    "lib": "/home/xijam/.config/heroic/tools/wine/Wine-GE-Proton7-33/lib64",
    "lib32": "/home/xijam/.config/heroic/tools/wine/Wine-GE-Proton7-33/lib",
    "wineserver": "/home/xijam/.config/heroic/tools/wine/Wine-GE-Proton7-33/bin/wineserver",
    "wineboot": "/home/xijam/.config/heroic/tools/wine/Wine-GE-Proton7-33/bin/wineboot"
  },
  "altLegendaryBin": "",
  "altGogdlBin": "",
  "disableController": false,
  "egsLinkedPath": "",
  "maxRecentGames": 5,
  "showUnrealMarket": false,
  "eacRuntime": false,
  "battlEyeRuntime": false
}
(20:51:27) INFO:    [Backend]:          Writing config for Heroic
(20:51:27) INFO:    [Backend]:          {
  "checkUpdatesInterval": 10,
  "enableUpdates": false,
  "addDesktopShortcuts": true,
  "addStartMenuShortcuts": true,
  "autoInstallDxvk": false,
  "autoInstallVkd3d": false,
  "addSteamShortcuts": true,
  "preferSystemLibs": false,
  "checkForUpdatesOnStartup": true,
  "customWinePaths": [
    "/mnt/chromeos/removable/James Lexar/wine-lutris-GE-Proton7-33-x86_64.tar.xz"
  ],
  "defaultInstallPath": "/mnt/chromeos/removable/James Lexar",
  "defaultSteamPath": "/home/xijam/.steam/steam",
  "defaultWinePrefix": "/home/xijam/Games/Heroic/Prefixes",
  "language": "en",
  "maxWorkers": 0,
  "minimizeOnLaunch": false,
  "nvidiaPrime": false,
  "enviromentOptions": [],
  "wrapperOptions": [],
  "showFps": true,
  "useGameMode": false,
  "userInfo": {
    "epicId": "c9306703314e4ade8d8c01ee7de3e879",
    "name": "xijam"
  },
  "wineCrossoverBottle": "Heroic",
  "winePrefix": "/home/xijam/.wine",
  "wineVersion": {
    "bin": "/home/xijam/.config/heroic/tools/wine/Wine-GE-Proton7-33/bin/wine",
    "name": "Wine - Wine-GE-Proton7-33",
    "type": "wine",
    "lib": "/home/xijam/.config/heroic/tools/wine/Wine-GE-Proton7-33/lib64",
    "lib32": "/home/xijam/.config/heroic/tools/wine/Wine-GE-Proton7-33/lib",
    "wineserver": "/home/xijam/.config/heroic/tools/wine/Wine-GE-Proton7-33/bin/wineserver",
    "wineboot": "/home/xijam/.config/heroic/tools/wine/Wine-GE-Proton7-33/bin/wineboot"
  },
  "altLegendaryBin": "",
  "altGogdlBin": "",
  "disableController": false,
  "egsLinkedPath": "",
  "maxRecentGames": 10,
  "showUnrealMarket": false,
  "eacRuntime": false,
  "battlEyeRuntime": false
}
(20:51:48) INFO:    [Frontend]:         Refreshing Library
(20:51:48) INFO:    [Legendary]:        Refreshing library...
(20:51:48) INFO:    [Legendary]:        Refreshing Epic Games...
(20:51:48) INFO:    [Legendary]:        Game list updated, got 2 games & DLCs
(20:51:49) INFO:    [Legendary]:        Running command: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary list
(20:51:52) INFO:    [Backend]:          Launching Fortnite (Fortnite)
(20:51:52) INFO:    [Backend]:          Preventing display from sleep
(20:51:54) DEBUG:   [Backend]:          Running Wine command: wineboot --init
(20:51:54) INFO:    [Legendary]:        Running command: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary launch Fortnite --json --offline
(20:51:54) INFO:    [Legendary]:        Launching Fortnite: LD_PRELOAD= WINEPREFIX=/home/xijam/Games/Heroic/Prefixes/Fortnite PROTON_BATTLEYE_RUNTIME=/home/xijam/.config/heroic/tools/runtimes/battleye_runtime ORIG_LD_LIBRARY_PATH= LD_LIBRARY_PATH=/home/xijam/.config/heroic/tools/wine/Wine-GE-Proton7-33/lib64:/home/xijam/.config/heroic/tools/wine/Wine-GE-Proton7-33/lib GST_PLUGIN_SYSTEM_PATH_1_0=/home/xijam/.config/heroic/tools/wine/Wine-GE-Proton7-33/lib64/gstreamer-1.0:/home/xijam/.config/heroic/tools/wine/Wine-GE-Proton7-33/lib/gstreamer-1.0 WINEDLLPATH=/home/xijam/.config/heroic/tools/wine/Wine-GE-Proton7-33/lib64/wine:/home/xijam/.config/heroic/tools/wine/Wine-GE-Proton7-33/lib/wine /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary launch Fortnite --language en --wine /home/xijam/.config/heroic/tools/wine/Wine-GE-Proton7-33/bin/wine
(20:51:58) INFO:    [Backend]:          Stopping Display Power Saver Blocker
(20:51:58) INFO:    [Frontend]:         Refreshing Library
(20:51:58) INFO:    [Legendary]:        Refreshing library...
(20:51:58) INFO:    [Legendary]:        Game list updated, got 2 games & DLCs
(20:52:00) DEBUG:   [Backend]:          Unable to load Steam Libraries, libraryfolders.vdf not found
(20:52:03) INFO:    [Backend]:          Writing config for 6uzZqoxLAg1StTtxVKg4PA
(20:52:03) INFO:    [Backend]:          {
  "autoInstallDxvk": false,
  "autoInstallVkd3d": false,
  "preferSystemLibs": false,
  "nvidiaPrime": false,
  "enviromentOptions": [],
  "wrapperOptions": [],
  "showFps": false,
  "useGameMode": false,
  "language": "",
  "wineVersion": {
    "bin": "/home/xijam/.config/heroic/tools/wine/Wine-GE-Proton7-33/bin/wine",
    "name": "Wine - Wine-GE-Proton7-33",
    "type": "wine",
    "lib": "/home/xijam/.config/heroic/tools/wine/Wine-GE-Proton7-33/lib64",
    "lib32": "/home/xijam/.config/heroic/tools/wine/Wine-GE-Proton7-33/lib",
    "wineserver": "/home/xijam/.config/heroic/tools/wine/Wine-GE-Proton7-33/bin/wineserver",
    "wineboot": "/home/xijam/.config/heroic/tools/wine/Wine-GE-Proton7-33/bin/wineboot"
  },
  "winePrefix": "/home/xijam/Games/Heroic/Prefixes/Clash of Clans"
}
(20:52:06) INFO:    [Backend]:          Writing config for 6uzZqoxLAg1StTtxVKg4PA
(20:52:06) INFO:    [Backend]:          {
  "autoInstallDxvk": false,
  "autoInstallVkd3d": false,
  "preferSystemLibs": false,
  "enableEsync": true,
  "nvidiaPrime": false,
  "enviromentOptions": [],
  "wrapperOptions": [],
  "showFps": false,
  "useGameMode": false,
  "language": "",
  "wineVersion": {
    "bin": "/home/xijam/.config/heroic/tools/wine/Wine-GE-Proton7-33/bin/wine",
    "name": "Wine - Wine-GE-Proton7-33",
    "type": "wine",
    "lib": "/home/xijam/.config/heroic/tools/wine/Wine-GE-Proton7-33/lib64",
    "lib32": "/home/xijam/.config/heroic/tools/wine/Wine-GE-Proton7-33/lib",
    "wineserver": "/home/xijam/.config/heroic/tools/wine/Wine-GE-Proton7-33/bin/wineserver",
    "wineboot": "/home/xijam/.config/heroic/tools/wine/Wine-GE-Proton7-33/bin/wineboot"
  },
  "winePrefix": "/home/xijam/Games/Heroic/Prefixes/Clash of Clans"
}
(20:52:07) INFO:    [Backend]:          Writing config for 6uzZqoxLAg1StTtxVKg4PA
(20:52:07) INFO:    [Backend]:          {
  "autoInstallDxvk": false,
  "autoInstallVkd3d": false,
  "preferSystemLibs": false,
  "enableEsync": true,
  "enableFsync": true,
  "nvidiaPrime": false,
  "enviromentOptions": [],
  "wrapperOptions": [],
  "showFps": false,
  "useGameMode": false,
  "language": "",
  "wineVersion": {
    "bin": "/home/xijam/.config/heroic/tools/wine/Wine-GE-Proton7-33/bin/wine",
    "name": "Wine - Wine-GE-Proton7-33",
    "type": "wine",
    "lib": "/home/xijam/.config/heroic/tools/wine/Wine-GE-Proton7-33/lib64",
    "lib32": "/home/xijam/.config/heroic/tools/wine/Wine-GE-Proton7-33/lib",
    "wineserver": "/home/xijam/.config/heroic/tools/wine/Wine-GE-Proton7-33/bin/wineserver",
    "wineboot": "/home/xijam/.config/heroic/tools/wine/Wine-GE-Proton7-33/bin/wineboot"
  },
  "winePrefix": "/home/xijam/Games/Heroic/Prefixes/Clash of Clans"
}
(20:52:13) INFO:    [Backend]:          Launching Clash of Clans (6uzZqoxLAg1StTtxVKg4PA)
(20:52:16) INFO:    [Backend]:          launching non-native sideloaded: /home/xijam/com.supercell.clashofclans_1.0.12067.123.exe}
(20:52:16) DEBUG:   [Backend]:          Running Wine command: /home/xijam/com.supercell.clashofclans_1.0.12067.123.exe
(20:52:16) DEBUG:   [Backend]:          Logging to file "/home/xijam/.config/heroic/GamesConfig/6uzZqoxLAg1StTtxVKg4PA-lastPlay.log"
(20:52:16) INFO:    [Backend]:          Stopping Display Power Saver Blocker
(20:52:16) INFO:    [Frontend]:         Refreshing Library
(20:52:16) INFO:    [Legendary]:        Refreshing library...
(20:52:16) INFO:    [Legendary]:        Game list updated, got 2 games & DLCs
(20:52:17) DEBUG:   [Backend]:          Unable to load Steam Libraries, libraryfolders.vdf not found
(21:21:55) INFO:    [Frontend]:         Refreshing Library
(21:21:55) INFO:    [Legendary]:        Refreshing library...
(21:21:55) INFO:    [Legendary]:        Refreshing Epic Games...
(21:21:55) INFO:    [Legendary]:        Game list updated, got 2 games & DLCs
(21:21:56) INFO:    [Legendary]:        Running command: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary list
(21:22:01) DEBUG:   [Backend]:          Unable to load Steam Libraries, libraryfolders.vdf not found
(21:22:21) INFO:    [Frontend]:         Refreshing Library
(21:22:21) INFO:    [Legendary]:        Refreshing library...
(21:22:21) INFO:    [Legendary]:        Refreshing Epic Games...
(21:22:21) INFO:    [Legendary]:        Game list updated, got 2 games & DLCs
(21:22:23) INFO:    [Backend]:          Launching Fortnite (Fortnite)
(21:22:23) INFO:    [Legendary]:        Running command: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary list
(21:22:23) DEBUG:   [Backend]:          Running Wine command: wineboot --init
(21:22:23) INFO:    [Legendary]:        Running command: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary launch Fortnite --json --offline
(21:22:24) INFO:    [Legendary]:        Launching Fortnite: LD_PRELOAD= WINEPREFIX=/home/xijam/Games/Heroic/Prefixes/Fortnite PROTON_BATTLEYE_RUNTIME=/home/xijam/.config/heroic/tools/runtimes/battleye_runtime ORIG_LD_LIBRARY_PATH= LD_LIBRARY_PATH=/home/xijam/.config/heroic/tools/wine/Wine-GE-Proton7-33/lib64:/home/xijam/.config/heroic/tools/wine/Wine-GE-Proton7-33/lib GST_PLUGIN_SYSTEM_PATH_1_0=/home/xijam/.config/heroic/tools/wine/Wine-GE-Proton7-33/lib64/gstreamer-1.0:/home/xijam/.config/heroic/tools/wine/Wine-GE-Proton7-33/lib/gstreamer-1.0 WINEDLLPATH=/home/xijam/.config/heroic/tools/wine/Wine-GE-Proton7-33/lib64/wine:/home/xijam/.config/heroic/tools/wine/Wine-GE-Proton7-33/lib/wine /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary launch Fortnite --language en --wine /home/xijam/.config/heroic/tools/wine/Wine-GE-Proton7-33/bin/wine
(21:22:27) INFO:    [Backend]:          Stopping Display Power Saver Blocker
(21:22:27) INFO:    [Frontend]:         Refreshing Library
(21:22:27) INFO:    [Legendary]:        Refreshing library...
(21:22:27) INFO:    [Legendary]:        Game list updated, got 2 games & DLCs

### Steps to reproduce

2. Click on '...'
3. Scroll down to '...'

### Expected behavior

Game opening.

### Screenshots

![Screenshot 2022-11-01 21 22 16](https://user-images.githubusercontent.com/105842516/199213583-f798c045-f221-46a3-866f-52b87e8e4f59.png)
![Screenshot 2022-11-01 21 22 27](https://user-images.githubusercontent.com/105842516/199213592-a15ed29f-0e00-438a-8f4b-05887bd20a64.png)
![Screenshot 2022-11-01 21 22 56](https://user-images.githubusercontent.com/105842516/199213601-b009697a-88cc-4ebc-a632-34fc05471019.png)

### System Information

- OS: Chrome OS (Linux)
- Heroic Version: 2.5.0-beta.1

**Comment by flavioislima** [comment]
FORTNITE does not work on Linux.
HEROIC is NOT supported on Chrome OS.

**Comment by jamesx0416** [comment]
oh
