### ISSUE TITLE
Install dialog not closing when select menu is focused using gamepad

### ISSUE THREAD

**Issue by wbrtm** [Heroic-Games-Launcher/HeroicGamesLauncher#1975]
### Describe the bug

While using a gamepad to navigate Heroic, the install dialog does not close when a select menu inside the dialog is focused and the B button is pressed on the gamepad.

### Add logs

nothing relevant

### Steps to reproduce

1. Go to the game page of an uninstalled game
3. Click the install button
4. Use the gamepad to navigate the dialog
5. Press B when one of the select menus is in focus and press B when another element is in focus

### Expected behavior

Expected behaviour would be that the install dialog closes upon pressing B, no matter where the cursor in the dialog is currently at.

### Screenshots

![installdialogue](https://user-images.githubusercontent.com/19275468/199227830-a3a1f58a-2d0f-4195-962c-921c6cbb4aa6.jpg)

### System Information

- OS: Tested on Manjaro and Steam Deck (SteamOS)
- Heroic Version: 2.4.3 and 2.5.0-beta.1

### Additional information

Select menus are handled as a special case, as you'd like an opened select menu to close when pressing the back button, this works as intended. But there is no detection of whether the select menu is currently open or not, so pressing back always (tries to) close the select menu and never closes the dialog.

**Comment by flavioislima** [comment]
Is this still an issue?
