### ISSUE TITLE
RocketLeage does not update in 2.5.0 beta1

### ISSUE THREAD

**Issue by killerdevildog11** [Heroic-Games-Launcher/HeroicGamesLauncher#1982]
### Describe the bug

Does not update game, in my case rocket league has an update and wont run on the 2.5.0 launcher but will when running the 2.4.3 launcher

### Add logs

no logs to show

### Steps to reproduce

2. Click on '...'
3. Scroll down to '...'

### Expected behavior

should detect and notify of update

### Screenshots

na

### System Information

- Heroic Version [e. g. 2.4.3 and 2.5.0]:
Ubuntu 22.04
MSI GE76 gaming laptop 

### Additional information

thats it folks let me know how i can help

**Comment by arielj** [comment]
is there anything in the logs? the issue description says `no logs to show` but it's not clear if you don't have any log of if the logs show nothing related to an available update

**Comment by killerdevildog11** [comment]
I'm just a gamer, how do I find the logs?

**Comment by arielj** [comment]
in heroic, go to settings > log

**Comment by killerdevildog11** [comment]
attached is the logs from yesterday when it was happening

let me know how i can help after the update occurred on the 2.4.3 launcher
the 2.5.0 beta version booted just fine.

**Comment by arielj** [comment]
I think you replied to an email to answer in the thread, but email attachments are not uploaded to the github issue so we can't see the attachment
