### ISSUE TITLE
GOG games download stuck on Linux and Windows 10

### ISSUE THREAD

**Issue by dtantono** [Heroic-Games-Launcher/HeroicGamesLauncher#1985]
### Describe the bug

I use Heroic [2.5.0 Beta 1] because it features download manager. But, when I tried to download certain games. it stuck and when I close the app and start the app again I need to start the download again from the scratch. That's not good

### Add logs

[Log.zip](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/files/9927126/Log.zip)

### Steps to reproduce

1. Go to Library
2. Click on GOG
3. Choose the game
4. After few minutes. the download stuck

### Expected behavior

it should download the game properly and when I tried to close and open the app. it should resume the process

### Screenshots

![2022-11-03_18-39](https://user-images.githubusercontent.com/29157187/199688831-7392f93d-dc3b-4fda-b746-c9121fc31a90.png)

<img width="268" alt="Snipaste_2022-11-05_22-01-29" src="https://user-images.githubusercontent.com/29157187/200121216-784840fb-ba68-4c33-a345-0d361c259948.png">

### System Information

- OS Ubuntu 22.04
- Heroic Version 2.5.0 Beta 1

### Additional information

Sorry the Log is too long and I have to make it to zip file instead and this affect Windows 10 as well

**Comment by flavioislima** [comment]
Still happening on stable?

**Comment by dtantono** [comment]
that uncaught exception popup is gone. But, the download manager is still unstable

**Comment by flavioislima** [comment]
Yes, we are fixing the other issues.

**Comment by dtantono** [comment]
on Windows 10, especially for 1.6.0 hotfix 2. when, I closed the app, the Uncaught exception popup happens again. But, it is not often.

**Comment by flavioislima** [comment]
Yes, thats because we force to close everything if you close the app. So some process might thrown an exception if they are in the middle of something.
