### ISSUE TITLE
Filling in Empty Space & Themes

### ISSUE THREAD

**Issue by QVGK** [Heroic-Games-Launcher/HeroicGamesLauncher#1992]
### Feature description

When you click a game in the library, it opens the following page.

![image](https://user-images.githubusercontent.com/45526481/200105148-e75f5886-01d2-4349-be1d-251d89069d26.png)

Now as you may see, there's a lot of empty space here that could be filled in. One thing that could be added is the "How Long to Beat" info. A cool NPM Package that could be used to add this is [HowLongToBeat](https://www.npmjs.com/package/howlongtobeat) by ckatzorke.

Another thing that would be cool is themes.

![image](https://user-images.githubusercontent.com/45526481/200105197-c9f4254c-c1fe-49db-adf6-ebdc83ed143a.png)

I don't really like this yellow theme and the blue-ish background color. It would be nice if we could use CSS to change the colors of some things and add cool CSS transition effects.

**Comment by flavioislima** [comment]
Heroic has themes already, go to accessibility screen. On the beta you can even add your own themes.
About the HowLingToBeat we already have a open feature request for that.
