### ISSUE TITLE
Determine Language when Install the game

### ISSUE THREAD

**Issue by dtantono** [Heroic-Games-Launcher/HeroicGamesLauncher#1999]
### Problem description

there is no language selection when install the game and when the game is installed. we cannot change the language setting. 

### Feature description

on GOG Galaxy for Windows there is an option to choose language for install the game and I hope heroic took same approach as well.

### Alternatives

GOG Galaxy for Windows

**Comment by flavioislima** [comment]
Heroic already does that. But not all games has this option.
Do you have an example of a game that gives the option on galaxy but not on heroic?
Games like cyberpunk and the witcher on heroic shows the language selection. Other doesn't because they do not have this feature.

**Comment by dtantono** [comment]
there are lot of games. But, let me mention few examples like: Chaos; child and Splinter cell.
<img width="732" alt="Snipaste_2022-11-07_00-37-40" src="https://user-images.githubusercontent.com/29157187/200180095-6db05cc8-0088-4254-af4c-a984d5d68635.png">
<img width="758" alt="Snipaste_2022-11-07_00-37-12" src="https://user-images.githubusercontent.com/29157187/200180096-b4652ec9-c0af-4324-b2be-6cacde0fe0db.png">
<img width="371" alt="Snipaste_2022-11-07_00-35-34" src="https://user-images.githubusercontent.com/29157187/200180097-d913cb12-a1fc-4821-96fd-753cc0ef099d.png">


<img width="436" alt="Snipaste_2022-11-07_00-38-33" src="https://user-images.githubusercontent.com/29157187/200180090-889f549b-6d1a-48b9-b224-fe098599a8a8.png">

**Comment by flavioislima** [comment]
@imLinguin what do you think? Maybe we are missing some info from the api? Or because those are v1 games?

**Comment by imLinguin** [comment]
@dtantono did you wait untill it calculates the size and shows you more options?

**Comment by imLinguin** [comment]
![obraz](https://user-images.githubusercontent.com/62100117/200184879-3147e5d1-84f2-4011-aeb3-2a36ee9813bb.png)
![obraz](https://user-images.githubusercontent.com/62100117/200184928-8218e7bb-e6bf-4f8f-ac0a-c3d1176d2aaa.png)

Even native games as long as it's supported:  
![obraz](https://user-images.githubusercontent.com/62100117/200184979-e0b2b194-1299-4106-89ec-b35ea1f74f0d.png)

**Comment by dtantono** [comment]
yeah you are right, I need to wait for at least a minute or longer before the full detailed information shows up because it seems reading my remaining file storage capacity. Like steam, Is it possible to make the file reading faster?

**Comment by redromnon** [comment]
If I'm not Heroic doesn't store any of the info as a cache, so it takes some time to load the details every time.

**Comment by imLinguin** [comment]
I'll try to make the process faster in gogdl refactor
