### ISSUE TITLE
Game is uninstalled even when the uninstall pop-up is closed by the user

### ISSUE THREAD

**Issue by 34v5n90** [Heroic-Games-Launcher/HeroicGamesLauncher#2000]
### Describe the bug

When user tries to uninstall a game, but closes the uninstall pop-up, the game is still uninstalled.

### Add logs

n/a

### Steps to reproduce

1. Right click library game and press Uninstall
2. Close the uninstall window

### Expected behavior

The game should not have been uninstalled

### System Information

- OS : Fedora 36 KDE
- Heroic Version : 2.4.3 (Flatpak)

**Comment by arielj** [comment]
hmmmm I can't reproduce this, can you share a video of the issue?

**Comment by 34v5n90** [comment]
Here you go
https://user-images.githubusercontent.com/114310621/200181621-c7338290-cc2a-4e2a-b66e-6fc2cc8d54a3.mp4

While trying to record the issue I couldn't reproduce it with the language set to English, but as soon as I switched to Polish the issue was still present. Pretty weird.

**Comment by arielj** [comment]
can you try with the latest beta 2.5.0-beta.2? we reimplemented many of the dialogs (including the uninstall dialog) and it might be fixed already

**Comment by 34v5n90** [comment]
Seems to be fixed in the latest beta. Closing
