### ISSUE TITLE
Automatic update for game

### ISSUE THREAD

**Issue by dtantono** [Heroic-Games-Launcher/HeroicGamesLauncher#2009]
### Problem description

Some game can be outdated on certain time and incompatible with updated OS and it is quite hassle if we update the game version manually. 

### Feature description

It is really wonderful if there is a feature for update the game automatically like steam. 

### Alternatives

Steam and GOG Galaxy. 

### Additional information

also it will be great if we have scheduled updates as well So, it will not hamper our gaming activity.

**Comment by arielj** [comment]
closing since this feature was implemented a while ago

![image](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/assets/188464/dac31006-9e99-4fcd-8848-02420769b1cc)
