### ISSUE TITLE
Can't access Epic games Library

### ISSUE THREAD

**Issue by Darian-A** [Heroic-Games-Launcher/HeroicGamesLauncher#2013]
### Describe the bug

Hi there,
I tried to log in to Epic ,but after I tried signing in ,the page went blank

I could still view Epic from the store tab, but I'm unable to get past the login page or access my Library, how do I fix this?

### Add logs

..

### Steps to reproduce

1. Go to 'Log in
2. Click on 'Sign in with Epic Games'
3. Enter login credentials 
4. Login incorrect response, please refresh page
5. Log in page blank

### Expected behavior

I wanted to access my  Library 

### System Information

- Windows 10
- Heroic v2.3.10

**Comment by flavioislima** [comment]
Please update Heroic, this old version you are using do not work anymore.
