### ISSUE TITLE
A setting to pick the DXVK version to be installed by heroic

### ISSUE THREAD

**Issue by arielj** [Heroic-Games-Launcher/HeroicGamesLauncher#2020]
### Problem description

DXVK 2 has been released a few days ago and it seems to cause some issues for users with GPUs that do NOT support Vulkan 1.3.

Currently, users have to disable heroic's automatic dxvk handling and manually install DXVK 1.10.3 that works with Vulkan 1.2 (the latest version before DXVK 2).

It's not user friendly.

### Feature description

When the `auto update/install DXVK` feature is enabled, we can show a selector to specify DXVK 1 or 2, that way a user can do a global default setting for it instead of dealing with this for every game

### Alternatives

manual setup, adding more docs to point the users to how to do it

**Comment by imLinguin** [comment]
We could base our whole components management off components repository maintained by Bottles team and community.
 https://github.com/bottlesdevs/components

available on https://repo.usebottles.com/components

**Comment by arielj** [comment]
Closing this since we have a feature to automatically install compatible DXVK/VKD3D versions which is more user friendly and simpler than having a way to select different versions. https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/blob/main/src/backend/tools/index.ts#L676-L680

Users can still use Winetricks to installs specific versions for edge cases.

**Comment by GrabbenD** [comment]
I've switched from Lutris to Bottles due to greater level of customization. However, Bottles isn't designed to build your own gaming library and I was hoping Heroic Games Launcher would be the one.

The lack of easily being able to select different versions of DXVK and VKD3D is a real shame for advanced users who like to have latest and greatest or custom builds like DXVK-GPLASYNC

For example, with Lutris you can just build your own DXVK/VKD3D and drop it into `~/.local/share/lutris/runtime/dxvk/name-here` and it will show up in the application as a selectable option.

**Comment by Applewubs** [comment]
> I've switched from Lutris to Bottles due to greater level of customization. However, Bottles isn't designed to build your own gaming library and I was hoping Heroic Games Launcher would be the one.
> 
> The lack of easily being able to select different versions of DXVK and VKD3D is a real shame for advanced users who like to have latest and greatest or custom builds like DXVK-GPLASYNC
> 
> For example, with Lutris you can just build your own DXVK/VKD3D and drop it into `~/.local/share/lutris/runtime/dxvk/name-here` and it will show up in the application as a selectable option.

Yeah.. it might be user friendly but not game friendly, if a new DXVK version screws your portable game then you're pretty much forced back to Bottles

**Comment by iWisp360** [comment]
On heroic, I'm forced to pass the x64 and x32 folders of dxvk to the dxvk heroic downloads to then remove the prefix, and then heroic will regenerate the prefix using that dxvk
