### ISSUE TITLE
Cant launch Fall Guys

### ISSUE THREAD

**Issue by FirephoenixX02** [Heroic-Games-Launcher/HeroicGamesLauncher#2023]
### Describe the bug

The game doesnt start, when clicking the play button the button changes for 1-2 seconds to the stop game button, but then changes back.

### Add logs

(14:41:20) INFO:    [Connection]:       Connectivity: check-online
(14:41:20) INFO:    [Connection]:       Pinging external endpoints
(14:41:20) INFO:    [Legendary]:        Running command: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary --version
(14:41:20) INFO:    [Legendary]:        Legendary location: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary
(14:41:20) INFO:    [Gog]:              GOGDL location: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl
(14:41:20) WARNING: [Backend]:          Protocol already registered.
(14:41:20) INFO:    [Gog]:              Running command: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --version
(14:41:21) INFO:    [Connection]:       Connectivity: online
(14:41:21) INFO:    [Backend]:          AreWeAntiCheatYet data downloaded
(14:41:21) INFO:    [Backend]:          

Heroic Version: 2.5.0-beta.2 Caesar Clown
Legendary Version:  0.20.30 Dark Energy (hotfix #4)
GOGdl Version: 0.5
OS: Ubuntu KERNEL: 5.15.0-52-generic ARCH: x64
CPU: Intel Xeon® X5560 @2.8 GOVERNOR: schedutil
RAM: Total: 15.63 GiB Available: 9.59 GiB
GRAPHICS: GPU0: NVIDIA GeForce GTX 1050 Ti VRAM: 4096MB DRIVER: 515.65.01 
PROTOCOL: x11

(14:41:22) INFO:    [Backend]:          Checking for new Heroic Updates
(14:41:22) INFO:    [Frontend]:         Refreshing Library
(14:41:22) INFO:    [Legendary]:        Refreshing library...
(14:41:22) INFO:    [Legendary]:        Refreshing Epic Games...
(14:41:22) INFO:    [Legendary]:        Game list updated, got 2 games & DLCs
(14:41:22) INFO:    [Legendary]:        Running command: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary list
(14:41:23) INFO:    [DXVKInstaller]:    Updating vkd3d to: vkd3d-proton-2.7.tar.xz
(14:41:24) INFO:    [Winetricks]:       Downloaded Winetricks
(14:41:24) INFO:    [DXVKInstaller]:    downloaded vkd3d
(14:41:24) INFO:    [DXVKInstaller]:    extracting vkd3d
(14:41:24) INFO:    [DXVKInstaller]:    extracting vkd3d updated!
(14:41:26) INFO:    [Backend]:          Launching Fall Guys (0a2d9f6403244d12969e11da6713137b)
(14:41:26) INFO:    [Backend]:          Preventing display from sleep
(14:41:26) WARNING: [Backend]:          You are using Proton, this can lead to some bugs. Please do not open issues with bugs related to games
(14:41:26) INFO:    [Legendary]:        Running command: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary launch 0a2d9f6403244d12969e11da6713137b --json --offline
(14:41:27) INFO:    [Legendary]:        Launching Fall Guys: PULSE_LATENCY_MSEC=60 LD_PRELOAD= STEAM_COMPAT_CLIENT_INSTALL_PATH=/home/user/.steam/steam STEAM_COMPAT_DATA_PATH=/home/user/Games/Heroic/Prefixes/FallGuys PROTON_NO_ESYNC=1 PROTON_NO_FSYNC=1 PROTON_EAC_RUNTIME=/home/user/.config/heroic/tools/runtimes/eac_runtime PROTON_BATTLEYE_RUNTIME=/home/user/.config/heroic/tools/runtimes/battleye_runtime STEAM_COMPAT_APP_ID=0 SteamAppId=0 SteamGameId=heroic-FallGuys PROTON_LOG_DIR=/home/user /home/user/.local/share/Steam/steamapps/common/SteamLinuxRuntime_soldier/run -- --filesystem=/home/user/Games/Heroic/FallGuys /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary launch 0a2d9f6403244d12969e11da6713137b --language en --no-wine --wrapper "'/home/user/.local/share/Steam/steamapps/common/Proton - Experimental/proton' run"
(14:41:28) INFO:    [Backend]:          Stopping Display Power Saver Blocker
(14:41:29) INFO:    [Frontend]:         Refreshing Library
(14:41:29) INFO:    [Legendary]:        Refreshing library...
(14:41:29) INFO:    [Legendary]:        Game list updated, got 2 games & DLCs

### Steps to reproduce

1. Go to Library
2. Click on Start Game
3. See that it doesnt open

### Expected behavior

game should start

### System Information

- OS [e. g. "Ubuntu"]:  Ubuntu 22.04
- Heroic Version [e. g. 2.1.1]: Heroic 2.5.0-beta2

### Additional information

Tried with Heroic 2.3.9, 2.4.3 and 2.5 beta2
Wine version doesnt matter
proton version doesnt matter
using steam runtime doesnt matter

**Comment by arielj** [comment]
From that log, it looks like you didn't follow our official guide (you are using proton experimental) https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/wiki/Fall-Guys

Github issues are not for help running games, try the guide and if you are still having issue ask in our discord in the `#-linux` channel.

**Comment by FirephoenixX02** [comment]
> From that log, it looks like you didn't follow our official guide (you are using proton experimental) https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/wiki/Fall-Guys
> 
> Github issues are not for help running games, try the guide and if you are still having issue ask in our discord in the `#-linux` channel.

As I already said the Wine version doesn't matter, I tried to follow the official guide but it won't launch. I tried every wine version from 4.0-latest and every custom wine, that*s not the issue. Easy AntiCheat is also not the problem, i think, because the game doesnt even start. From that i concluded that it must be another issue, possibly a launcher issue idk.

**Comment by flavioislima** [comment]
Any specific reason you are using the offline flag for this game?

**Comment by FirephoenixX02** [comment]
> Any specific reason you are using the offline flag for this game? 

I didnt but it didnt updated the game or gave me a notification. Had to force check for an update 3x until it finally updated

**Comment by arielj** [comment]
> Any specific reason you are using the offline flag for this game?

This line:
(14:41:26) INFO: [Legendary]: Running command: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary launch 0a2d9f6403244d12969e11da6713137b --json --offline

is not for actually running the game, it is only to get legendary's config of the game for the logs. it just gets the configuration without checking anything online to make it faster, but should not affect the real launch command
