### ISSUE TITLE
Heroic games Launcher / Sifu / Steamdeck 

### ISSUE THREAD

**Issue by ch40s-1** [Heroic-Games-Launcher/HeroicGamesLauncher#2026]
I looked forward to playing Sifu over the Heroic games launcher on my steamdeck. Unfortunately every 20 minutes or so the following message pops up:

"If you continue without signing in,  progress will not be saved"

Progress IS saved but after the popup comes up, it renders my game unplayable as if the controller is disconnected. Only thing that helps is to exit the game via SteamOS and restarting it. Then it takes 15-20 mins to happen again. Quite a few people report similar issues on Reddit.

Everything is up to date, tried messing with the auto/cloud-save feature and offline mode in HGL, but it won't disappear. It's driving me insane...

Any ideas/leads/workarounds?

Best, Chris

**Comment by arielj** [comment]
you should ask for help with specific games in our discord, github issues are more for errors of the launcher, not errors in games

I'm closing this, you can as in our discord in the `#-Support` channel
