### ISSUE TITLE
Update built in legendary binary to 0.20.31 cannot add it manually.

### ISSUE THREAD

**Issue by bhask4r** [Heroic-Games-Launcher/HeroicGamesLauncher#2028]
### Describe the bug

Tried playing GTA 5 using heroic and Crossover 22.1 worked fine until GTA Online started crashing after 5-10 minutes of gameplay checked everything possible until I saw heroic logs which said new legendary update fixes lot of problems but cannot seem to add new update manually gives me an error below.

### Add logs

Legendary update available!
- New version: 0.20.31 - "Dark Energy (hotfix #5)"
- Release summary:
 [!] Fixed cloud-syncing accidentally deleting game or save data in some cases
 [*] Updated API URL for Uplay activiation
See full changelog for additional details.
- Release URL: https://legendary.gl/release/0.20.31
! This update is recommended as it fixes major issues.
- Download URL: https://legendary.gl/release/download/0.20.31/legendary_macOS.zip
preloader: Warning: failed to reserve range 0000000000010000-0000000000110000
preloader: Warning: failed to reserve range 0000000000010000-0000000000110000
preloader: Warning: failed to reserve range 0000000000010000-0000000000110000
preloader: Warning: failed to reserve range 0000000000010000-0000000000110000
preloader: Warning: failed to reserve range 0000000000010000-0000000000110000

WHEN TRY TO UPDATE LEGENDARY BINARY MANUALLY ERROR SAYS:
Error running command "/Users/bhaskar/Downloads/legendary-6 --version": Error: spawn ./legendary-6 EACCES
at ChildProcess._handle.onexit (node:internal/child_process:283:19)
at onErrorNT (node:internal/child_process:478:16)
at process.processTicksAndRejections (node:internal/process/task_queues:83:21)

### Steps to reproduce

1. Go to Launch Game
2. Click on Show logs after word
3. Try to manually update legendary binary from advanced settings

### Expected behavior

Being able to use custom legendary version or add the binary built in.

### Screenshots

<img width="255" alt="image" src="https://user-images.githubusercontent.com/20121493/202386770-55611410-d543-48f7-b0ee-588b66b9c338.png">
<img width="661" alt="image" src="https://user-images.githubusercontent.com/20121493/202387081-73a5cd36-5114-454a-bd86-a8347cea4f0e.png">

### System Information

- OS [e. g. "MACOS 13.1"]: 
- Heroic Version [e. g. 2.4.3 and 2.5.0 beta 2 and several other versions]:

### Additional information

The problem discussion resides here as well 
https://www.codeweavers.com/compatibility/crossover/forum/grand-theft-auto-v?msg=270528

**Comment by flavioislima** [comment]
The game crashing has nothing to do with Legendary or Heroic.
This is probably more related with Crossover since the game is being launched.

Heroic and legendary just calls crossover to launch the game and after that they don't control what happens.

Try to get help on our discord or on a MacOS gaming community. Maybe you need to do some configuration on your crossover bottle or try a different version. 

Also, Heroic beta 2 already have the latest Legendary.
The fixes New version of legendary has are not related with launching games as you can see on changelog, but cloud sync and others.
