### ISSUE TITLE
epic games returns null SID

### ISSUE THREAD

**Issue by lever1209** [Heroic-Games-Launcher/HeroicGamesLauncher#2033]
### Describe the bug

after a few attempts to log into epic games, it has started to return a null SID

### Add logs

(02:29:48) INFO:    [Legendary]:       Running command: /usr/lib/heroic-games-launcher/resources/app.asar.unpacked/build/bin/linux/legendary --version
(02:29:48) INFO:    [Legendary]:       Legendary location: /usr/lib/heroic-games-launcher/resources/app.asar.unpacked/build/bin/linux/legendary
(02:29:48) INFO:    [Gog]:             GOGDL location: /usr/lib/heroic-games-launcher/resources/app.asar.unpacked/build/bin/linux/gogdl
(02:29:48) INFO:    [Backend]:         

Heroic Version: 2.4.3 Chopper
Legendary Version:  0.20.27 Dark Energy (hotfix)
OS: Arch KERNEL: 6.0.7-arch1-1 ARCH: x64
CPU: Intel Core™ i7-3770 @3.4 GOVERNOR: schedutil
RAM: Total: 17.53 GiB Available: 13.23 GiB
GRAPHICS: GPU0: NVIDIA GeForce GTX 1650 VRAM: 4096MB DRIVER: 520.56.06 
PROTOCOL: tty

(02:29:48) INFO:    [Backend]:         User Not Found, removing it from Store
(02:29:49) INFO:    [Gog]:             Getting data about the user
(02:29:49) WARNING: [Backend]:         Failed to register protocol with OS.
(02:29:50) INFO:    [Gog]:             Saved user data to config
(02:29:50) INFO:    [Backend]:         AreWeAntiCheatYet data downloaded
(02:29:50) INFO:    [Backend]:         Checking for new Heroic Updates
(02:29:50) INFO:    [Frontend]:        Refreshing Library
(02:29:50) INFO:    [Legendary]:       Refreshing library...
(02:29:50) INFO:    [Gog]:             Getting GOG library
(02:29:51) INFO:    [Gog]:             Number of library pages: 1
(02:29:52) INFO:    [Gog]:             Saved games data
(02:29:52) INFO:    [DXVKInstaller]:   Updating vkd3d to: vkd3d-proton-2.7.tar.xz
(02:29:54) INFO:    [Backend]:         Downloaded Winetricks
(02:29:54) INFO:    [Gog]:             Found 0 game(s) to update
(02:29:57) INFO:    [DXVKInstaller]:   downloaded vkd3d
(02:29:57) INFO:    [DXVKInstaller]:   extracting vkd3d
(02:29:57) INFO:    [DXVKInstaller]:   extracting vkd3d updated!
(02:32:05) INFO:    [Legendary]:       Logging in with Legendary.
(02:32:05) INFO:    [Legendary]:       Running command: /usr/lib/heroic-games-launcher/resources/app.asar.unpacked/build/bin/linux/legendary auth --code <redacted>
(02:32:06) INFO:    [Frontend]:        Refreshing Library
(02:32:06) INFO:    [Legendary]:       Refreshing library...
(02:32:06) INFO:    [Frontend]:        Called Login
(02:32:06) INFO:    [Frontend]:        No cache found, getting data from legendary...
(02:32:06) INFO:    [Legendary]:       Refreshing library...

### Steps to reproduce

i have no clue what caused it in specific, my only guess is several failed attempts to login causes it

### Expected behavior

the returned SID should not be null

### System Information

os: archlinux
heroic 2.4.3

**Comment by UniversalStyle** [comment]
You can use value of "authorizationCode" field to log in. It works for me

**Comment by arielj** [comment]
this is not a Heroic issue, epic changed their login a few months ago and heroic 2.4.3 got out of date with that info

you have to use `authorizationCode`, check the updated wiki here https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/wiki/How-To:-Epic-Alternative-Login (heroic 2.5.0 will have the correct info too)

**Comment by lever1209** [comment]
the authorization code does not work to login, I've already tried it, and I verified it again just now

**Comment by UniversalStyle** [comment]
> the authorization code does not work to login, I've already tried it, and I verified it again just now
What mistake? I tried it about 3 hours ago and it worked

**Comment by lever1209** [comment]
ive updated to the beta and its working now, but the latest stable build does not work
