### ISSUE TITLE
Offline mode isnot working in beta

### ISSUE THREAD

**Issue by haytham-med** [Heroic-Games-Launcher/HeroicGamesLauncher#2035]
### Describe the bug

I select offline mode per game , but game wont launch, in discord,i was told offline has spaces in it.

### Add logs

Rise of tomb raider log: https://pastebin.com/NzmtLTqL

Heroic launcher 2.5.0 beta2 log: https://pastebin.com/EGFgPrU4

### Steps to reproduce

1. Go to '...'Game settings
2. Click on '...'offline mode, then launch game
3. Scroll down to '...'

### Expected behavior

Game should launch offline

### System Information

- OS [e. g. "Ubuntu"]: kde neon 5.26
- Heroic Version [e. g. 2.1.1]: 2.5.0 beta2 appimage

**Comment by haytham-med** [comment]
I downloaded the stable 2.4.3 version, and game worked offline

**Comment by Nocccer** [comment]
Can confirm the bug.

**Comment by CommandMC** [comment]
Resolved in #2037
