### ISSUE TITLE
Creating shortcuts for additional .exe added manually to the prefix (not installed via Heroic), so that we can run them within the prefix

### ISSUE THREAD

**Issue by mscipio** [Heroic-Games-Launcher/HeroicGamesLauncher#2039]
### Problem description

Hi,

I have spent most of the afternoon trying to figure out if this was possible with the tools I had at my disposal (bash scripting, manually creating a "wine prefix" equivalent to the Proton prefix, even adapting manually a bash script generated by heroic bash launcher) but to no avail.

CONTEXT
- I tried to install Rayman Legend that I have on Epic.
- The installation was successful, but the game wouldn't start, as it needed the Ubisoft Connect launcher.
- I downloaded the exe to install the Ubisoft launcher, ran it using the "run with this prefix" functionality provided by Heroic Launcher, and successfully installed the Ubi Launcher.
- Rayman works like a charm with the Ubidoft Launcher in the same prefix.

Then I wanted to push it further ...
- I opened the launcher and install a Ubisoft game that I only have on Ubisoft (Child of Light, but I guess any would work ..)
- The game installed within the same prefix folder, it shows up in the Ubisoft launcher, it launches and plays perfectly

### Feature description

Now, as soon as I close the Ubisoft launcher, I will have almost no way to reopen it, and to access the game I installed using it. That's a pity, as Heroic seems to have all the tools to run "technically unsupported" games, if only it was possible to create a custom shortcut that says"
- use this heroic prefix
- launch this executable using this prefix

I have honestly a hard time thinking this is something hard to put together.
Do you have any suggestion of things I can try to achieve this goal? I would be happy to share if I happen to get good results

**Comment by Leopard1907** [comment]
> I have been using the version of heroic I can download from flatpak. What is the best (i.e. non destructive for what's already installed) way to upgrade to the beta version?

https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/releases/tag/v2.5.0-beta.2

Grab Appimage one from here, right click to it and mark it as executable. Your system one will still stay at whichever version you've installed, you can use appimage one any time you want.

**Comment by mscipio** [comment]
Thank you, that sort of worked, buy with the app image for the beta I don't see any of the games I installed with the system version. Is there a way I can permanently switch to the beta version, or it's just a trial image and I should just wait for the beta to be released on flatpack?
