### ISSUE TITLE
Add per-game option to suppress "Game Needs Update" popup

### ISSUE THREAD

**Issue by trueNightRomantic** [Heroic-Games-Launcher/HeroicGamesLauncher#2040]
### Problem description

It's useful (for me) to play some games without updating them to latest version. Having to press "Not now" in "Game Needs Update" popup on every game start feels... suboptimal :-)

### Feature description

It would be useful to add per-game option "Don't show Game Needs Update popup on game launch" -- most likely in [Game Settings -> Other] and disabled by default.

I'm personally ok even with hidden option for this, if you don't want to clutter UI.

**Comment by trueNightRomantic** [comment]
I've got one more idea. Heroic can check for `skip_update_check = true` in legendary's `config.ini` and not show update request if this option is present. Not as accessible and easy to find as a setting in UI -- but still usable, sort of compromise.

**Comment by arielj** [comment]
I understand this is implemented in the new 2.6 version of Heroic based on https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/pull/2308 

I'm closing this
