### ISSUE TITLE
Launching games on Windows isn't properly tracked.

### ISSUE THREAD

**Issue by Zarklord** [Heroic-Games-Launcher/HeroicGamesLauncher#2046]
### Describe the bug

When launching a game on Linux
It will go from `Play Now` to `Stop (Playing)`
And it will stay that way until you close the game.
But on windows it does this:
It will go from `Play Now` to `Stop (Playing)` back to `Play Now`

I don't know what the difference is, but on windows Heroic fails to track the game and this causes several issues.

- If you have cloud saves enabled, the sync won't occur when you close the game, potentially causing you to lose lots of progress in game.
- It fails to track time played which is a big bummer.
- You can't actually close the game from the launcher

**Comment by flavioislima** [comment]
Unfortunately it is a normal behavior on Linux. Somehow some processes launch and then die and then start the second process that is the game itself.
I tried to fix that in the past but it is just how Windows works.
You will see that for some games this works and for others it doesn't.

**Comment by Zarklord** [comment]
> Unfortunately it is a normal behavior on Linux. Somehow some processes launch and then die and then start the second process that is the game itself. I tried to fix that in the past but it is just how Windows works. You will see that for some games this works and for others it doesn't.

Even if its standard behavior, it doesn't mean that this isn't a critical thing to solve, I would love to use heroic over EGS right now, but because cloud saving is darn near completely broken, I can't... when I go to play on my steam deck from my PC or vice versa, I don't want to be thinking "have I done the 5 steps needed to ensure my save data has been properly uploaded/downloaded", instead I'm gonna use lutris and EGS since the cloud syncing is seamless on my end.

**Comment by flavioislima** [comment]
Hmm, but can you sync save the games on EGS/lutris by launching the game from steam and without the gui?
I belive you always need to open the Egs launcher for that, so that's not different from opening Heroic in gaming mode and launching the game.

Anyway, after merging your PR the sync saves might work on no-gui. 👍

**Comment by Zarklord** [comment]
> Hmm, but can you sync save the games on EGS/lutris by launching the game from steam and without the gui? I belive you always need to open the Egs launcher for that, so that's not different from opening Heroic in gaming mode and launching the game.

Yes, yes you can.

**Comment by flavioislima** [comment]
What I meant is that I could not find a way to solve this.

right now when a game is launched, Heroic watch the process initiated by Legendary or GogDL.
Because Heroic is just a frontend for these CLI apps.
So if Legendary and GogDL gets back to Heroic and says that they are done, Heroic sends the information to the frontend that the game process was stopped.

So Heroic calls Legendary/GogDL that calls the game exe. 
Different from Linux and macOS, after launching the game Legendary and GogDL gets terminated after the game is launched.

I have no idea how to solve that on our Side.

**Comment by Zarklord** [comment]
I took a look and also couldn't figure out how to solve this easily, that said this is a major issue, almost to the point that I think advertising `Sync saves with cloud` as a feature is lying.
If Epic or Steam were to offer cloud saves but they didn't re-sync when you closed the game, people would be attacking them left right and center, because while it technically would support cloud saves, its arguably not useful since your still gonna have to manually trigger a sync after you stop playing, as it currently stands Heroic has the cloud saves implemented as far as an API standpoint, but there are/were several issues relating to cloud saves that currently make them not a usable feature.

**Comment by flavioislima** [comment]
Ok, take a look if you have the time.
But saying Sync Saves with cloud is NOT a lie since it does that, what is not working is `AUTO SYNC SAVES WITH THE CLOUD`, and that is not advertized. The button to sync is there and it works just fine.

**Comment by flavioislima** [comment]
Testing here on windows and GOG games works perfectly fine as you can see on this screenshot, so the issue might be with legendary only.
![image](https://user-images.githubusercontent.com/26871415/203975589-1216b94a-2b86-4771-b166-f9b7a9a3dbe8.png)

**Comment by verypurple** [comment]
Hi, I just wanted to add - because of this Time Played is also not recorded. It is always "Time Played: Never".

**Comment by vvirtues** [comment]
> Hi, I just wanted to add - because of this Time Played is also not recorded. It is always "Time Played: Never".

I either get this or it shows a few minutes because sometimes games take a few seconds to load and that builds up playtime (not heroic/legendary's fault)
