### ISSUE TITLE
Download multiple games not always works 

### ISSUE THREAD

**Issue by UniversalStyle** [Heroic-Games-Launcher/HeroicGamesLauncher#2047]
### Describe the bug

It worked good, but after the last restart app multiple download was borked: UI button for download is disabled, when Any game is downloading. In log, it not visible because UI is disabled and on click event not work

### Add logs

https://pastebin.com/hKmjPVTM

### Steps to reproduce

1. Start download any game
2. Click on download button to download another game

### Expected behavior

I expect download button has active status, but it's not happening

### Screenshots

![image](https://user-images.githubusercontent.com/82130739/203183900-27f7295e-a34a-4de8-907e-9b4bd771f1c1.png)

### System Information

- OS [e. g. "Ubuntu"]: elementary OS 6.1 Jólnir, Linux kernel 6.0.7
- Heroic Version [e. g. 2.1.1]: 2.4.3

**Comment by flavioislima** [comment]
Multiple downloads is only possible on the beta release. I can see you are using the stable one.
Change to beta or wait for next stable on next month.
