### ISSUE TITLE
Idea: Debian Repository

### ISSUE THREAD

**Issue by Razuuu** [Heroic-Games-Launcher/HeroicGamesLauncher#205]
Hello,

As a Debian user, I don't think it's great to always download the .deb file and have a question about whether it would be possible to create a Debian repository.

With best regards
Razuuu

**Comment by flavioislima** [comment]
Would be good but is not that simple. I tried to create a launchpad repository for ubuntu but without success.
You can follow the packages discussion here on #78.

**Comment by rauldipeas** [comment]
I have Heroic and Legendary on [**MAD Linux**](https://madlinux.now.sh) repository.
https://gitlab.com/myawesomedistro/madrepo/-/blob/master/scripts/getpkg/heroic.sh

**Comment by flavioislima** [comment]
> I have Heroic and Legendary on [**MAD Linux**](https://madlinux.now.sh) repository.
> https://gitlab.com/myawesomedistro/madrepo/-/blob/master/scripts/getpkg/heroic.sh

Nice, man!
And can we use it on other Debian based distros?

**Comment by rauldipeas** [comment]
> > I have Heroic and Legendary on [**MAD Linux**](https://madlinux.now.sh) repository.
> > https://gitlab.com/myawesomedistro/madrepo/-/blob/master/scripts/getpkg/heroic.sh
> 
> Nice, man!
> And can we use it on other Debian based distros?

Probably it will work well, but i can't assure this.
There's a lot of good popular software on this repository.

**Comment by Razuuu** [comment]
Hey @flavioislima,

i just added the latest .deb file to my debian repo.
To use my Debian repo you would have to do this:

`curl -sS http://deb.arrow-systems.de/arrow-systems.de.gpg | apt-key add -
echo "deb [arch=amd64] http://deb.arrow-systems.de/razuuu stable main" > /etc/apt/sources.list.d/deb.arrow-systems.de.list
apt update`

and then lastly `apt install heroic` ;)

With best regards
Razuuu

**Comment by rauldipeas** [comment]
> Hey @flavioislima,
> 
> i just added the latest .deb file to my debian repo.
> To use my Debian repo you would have to do this:
> 
> `curl -sS http://deb.arrow-systems.de/arrow-systems.de.gpg | apt-key add -`
> `echo "deb [arch=amd64] http://deb.arrow-systems.de/razuuu stable main" > /etc/apt/sources.list.d/deb.arrow-systems.de.list`
> `apt update`
> 
> and then lastly `apt install heroic` ;)
> 
> With best regards
> Razuuu

There are no description for this repository content?

**Comment by Razuuu** [comment]
> > Hey @flavioislima,
> > i just added the latest .deb file to my debian repo.
> > To use my Debian repo you would have to do this:
> > `curl -sS http://deb.arrow-systems.de/arrow-systems.de.gpg | apt-key add -`
> > `echo "deb [arch=amd64] http://deb.arrow-systems.de/razuuu stable main" > /etc/apt/sources.list.d/deb.arrow-systems.de.list`
> > `apt update`
> > and then lastly `apt install heroic` ;)
> > With best regards
> > Razuuu
> 
> There are no description for this repository content?

Wym

**Comment by rauldipeas** [comment]
I'm talking about what packages do you have on Your repository, it's a risk to add a repository without know what's in it.

My repository description is [here](https://gitlab.com/myawesomedistro/madrepo).

**Comment by BiRo96** [comment]
> Would be good but is not that simple. I tried to create a launchpad repository for ubuntu but without success.
> You can follow the packages discussion here on #78.

I have found this :)
https://askubuntu.com/a/71516/1171094

**Comment by dragonDScript** [comment]
The simplest way to upload .debs to Ubuntu/Debian is snapcraft.

**Comment by Razuuu** [comment]
Its me again, got debian repository working in github actions, pulls the latest .deb file
https://github.com/ArrowSystemsDE/heroic-apt
