### ISSUE TITLE
Easier navigation of library

### ISSUE THREAD

**Issue by texdade** [Heroic-Games-Launcher/HeroicGamesLauncher#2051]
### Problem description

On Steam Deck right now navigating the library is not otpimal when using the analogs/directional buttons: moving between adiacent games left to right and viceversa only requires on button press. Moving up and down requires instead between 2 to 3 button presses: two if the both titles' images are fully displayed into the screen, three if the title's image we moved to is partially cut. This makes for an unpleasant experience when quickly moving up and down the library.

### Feature description

Moving up and down should be a one press action, regardless of the direction. The selection of the download button, when using steam deck's controller, could be skipped.

**Comment by flavioislima** [comment]
These improvements were already made and will be available on next release.
Heroic will follow the same guidelines as the deck. 👍

**Comment by asb** [comment]
I'm using the latest Heroic Games Launcher release and seeing this same issue when moving down using the d-pad or analogue stick.

**Comment by arielj** [comment]
> I'm using the latest Heroic Games Launcher release and seeing this same issue when moving down using the d-pad or analogue stick.

are you on steam deck?

**Comment by asb** [comment]
> > I'm using the latest Heroic Games Launcher release and seeing this same issue when moving down using the d-pad or analogue stick.
> 
> are you on steam deck?

Yes. If a title is selected on the bottom row but the bottom row isn't fully in view, I need to press down twice. This then moves the next row into view (but not 100%) meaning going down another row requires another two presses, and so on.

**Comment by arielj** [comment]
we currently rely and the browser's native spatial navigation and don't have too much control on how much it scrolls when moving, I'm not sure if we can fix that completely, I'll do some tests (I'll reopen this issue since that part of the original problem is not addressed)

**Comment by arielj** [comment]
This should be fixed by https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/pull/3354

**Comment by arielj** [comment]
Closing because that PR got merged today. This will be included in the next release
