### ISSUE TITLE
Check installed games list is correct on library refresh/startup

### ISSUE THREAD

**Issue by snoozysoft** [Heroic-Games-Launcher/HeroicGamesLauncher#2058]
Description: By default, Heroic has a set folder location that it assumes games are installed to. If the games were installed via Heroic itself but then removed/uninstalled outside of Heroic such as by deleting the folder, Heroic does not appear to acknowledge that as a fact. To put it another way..

Reproduce:
1. Install any game using Heroic
2. Once installed, delete it via your file manager of choice.

Expected Behaviour: Heroic realizes the folder is no longer there and removes the "installed" status automatically and places it back in the suitable place on the library list.

Actual Behaviour: Heroic continues to assume it is still installed. Refreshing the library or closing and re-opening Heroic does not fix this. The only way to get Heroic to realize is to either right click on the game in question and then uninstall or to attempt to launch it to make it realize the folder is not there.

This problem also extends into the "default install folder" setting which also just assumes the given folder is always there, even when it isn't.

**Comment by snoozysoft** [comment]
Found new problem behaviour after posting. If a given game was initially installed via Heroic, deleted outside of it, then re-installed through the official app, Heroic still assumes it's in its original install location. This presents a rather unique problem when a game has had an update during the interval between deletion and re-installation as Heroic will persistently think that a new update is available even when an alternative executable has been specified in the settings. 

Being able to specify the actual and new install path rather than an alternative executable would perhaps resolve this issue as it would then be able to actually check all the files are at the current version.

**Comment by arielj** [comment]
I understand this will be addressed in the next beta. If heroic can't find the game folder it will show the game as uninstalled.

**Comment by flavioislima** [comment]
this was already implemented and will be available on next beta like Ariel said.
