### ISSUE TITLE
Epic Game Store: Missing game(s?) in Heroic Game Launcher 2.4.3

### ISSUE THREAD

**Issue by ScrambleTheRamble** [Heroic-Games-Launcher/HeroicGamesLauncher#2060]
### Describe the bug

I added STAR WARS: Squadrons to my EGS account but am unable to see the game in Heroic Games Launcher 2.4.3 (flatpak) on both my Steam Deck and my Fedora 36 desktop. Also confirmed by other people on /r/linux_gaming

Logging out and in into EGS does not resolve the issue.

### Add logs

(10:50:29) INFO:    [Legendary]:       Running command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary --version
(10:50:30) INFO:    [Legendary]:       Legendary location: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary
(10:50:30) INFO:    [Gog]:             GOGDL location: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl
(10:50:30) INFO:    [Backend]:         

Heroic Version: 2.4.3 Chopper
Legendary Version:  0.20.28 Dark Energy (hotfix #2)
OS: Freedesktop SDK KERNEL: 6.0.8-200.fc36.x86_64 ARCH: x64
CPU: AMD Ryzen 9 3900X 12-Core Processor @3.8 GOVERNOR: schedutil
RAM: Total: 94.22 GiB Available: 86.88 GiB
GRAPHICS: GPU0: Navi 22 [Radeon RX 6700/6700 XT/6750 XT / 6800M] VRAM: 1MB DRIVER:  
PROTOCOL: wayland

(10:50:30) INFO:    [Gog]:             Getting data about the user
(10:50:30) INFO:    [Gog]:             Refreshing access_token
(10:50:30) WARNING: [Backend]:         Failed to register protocol with OS.
(10:50:30) INFO:    [Backend]:         AreWeAntiCheatYet data downloaded
(10:50:30) INFO:    [Frontend]:        Refreshing Library
(10:50:30) INFO:    [Legendary]:       Refreshing library...
(10:50:30) INFO:    [Gog]:             Refreshing access_token
(10:50:30) INFO:    [Legendary]:       Refreshing Epic Games...
(10:50:31) INFO:    [Gog]:             Token refreshed successfully
(10:50:31) INFO:    [Gog]:             Getting GOG library
(10:50:31) INFO:    [Legendary]:       Running command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary list
(10:50:31) INFO:    [Gog]:             Token refreshed successfully
(10:50:31) INFO:    [Gog]:             Saved user data to config
(10:50:31) INFO:    [Gog]:             Number of library pages: 1
(10:50:32) INFO:    [Gog]:             Saved games data
(10:50:33) INFO:    [Backend]:         Downloaded Winetricks
(10:50:37) INFO:    [Legendary]:       Updating game list
(10:50:37) INFO:    [Legendary]:       Game List Updated
(10:50:37) INFO:    [Legendary]:       Checking for game updates.
(10:50:37) INFO:    [Legendary]:       Running command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary list-installed --check-updates --tsv
(10:50:38) INFO:    [Legendary]:       Found 0 game(s) to update
(10:50:38) INFO:    [Gog]:             Found 0 game(s) to update
(10:50:45) INFO:    [Frontend]:        Refreshing wine downloader releases
(10:50:45) INFO:    [WineDownloader]:  Updating wine versions info
(10:50:45) INFO:    [WineDownloader]:  Fetching upstream information...
(10:50:47) INFO:    [WineDownloader]:  wine versions updated

### Steps to reproduce

1. Go to EGS and add the game
2. Click on "Refresh library" in Heoic
3. Type Star Wars in Search bar or scroll through game list

### Expected behavior

Find the game

### System Information

- OS: Fedora 36 & Steam Deck 3.3.2
- Heroic Version: 2.4.3

**Comment by flavioislima** [comment]
Please check the documentation, games that uses third party launchers, like origin in this case, are not supported by Heroic YET.

**Comment by ScrambleTheRamble** [comment]
@flavioislima might be a good idea to make this specific issue more visible on the Game screen itself rather than hide it from the games list itself. Because based on this issue ticket I should be able to download the game through Heroic Games Launcher: https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/issues/1879

**Comment by ScrambleTheRamble** [comment]
Did some more digging and it's related to legendary, by default it doesn't list this game (and some others I've forgotten I owned) but they can be listed with

`legendary list -T`

So these games aren't downloaded from Epic at all, but go through Origin, not quite sure what the best way is to handle these kinds of things, maybe an FAQ on the documentation page? Eg:

Q - Why can't I find my game on Epic?
A - Heroic Games Launcher will not list games that can not be directly installed by Legendary.  You can confirm this with legendary; legendary list -T will show you the game and instructions on how to install it.

**Comment by MrP-Sr** [comment]
put in console ./legendary launch --origin bobcat and it will appear in your list of games.. with ./legendary launch --origin MtMassive it will appear STAR WARS™ Battlefront™ II: Celebration Edition
