### ISSUE TITLE
[Beta 3] Current Found bugs

### ISSUE THREAD

**Issue by flavioislima** [Heroic-Games-Launcher/HeroicGamesLauncher#2061]
### Describe the bug

A list of current found bugs to be fixed before stable:

- Not available games still being ordered along with installed games (maybe we should create a new status for it and show a message that is installed on a nonavailable drive, also give the option to uninstall or change install path.
- Importing games from GameCard does not change the status to installed (shows as not available, probably the `useEffect` is not being triggered to check availability after importing)
- Not available games still shows the update icon (not sure if should be remove though, maybe just add the new status said above)
- How long to beat data is causing a layout shift after returning the results (perhaps move it to a different place or show a placeholder instead.)
- HowLongToBeat date does not return anything if the game title has some characters like for trademark or copyrights, 

### Add logs

None

### Steps to reproduce

2. Click on '...'
3. Scroll down to '...'

### Expected behavior

Should fix them before stable.

### System Information

- OS [e. g. "Ubuntu"]: All
- Heroic Version [e. g. 2.1.1]: 2.5.0 beta 3

**Comment by dtantono** [comment]
and also I found played recently bar is gone on the library. what do you think?

**Comment by flavioislima** [comment]
> and also I found played recently bar is gone on the library. what do you think?

Have you enabled it on general settings?

**Comment by dtantono** [comment]
there is nothing here
![2022-11-26_22-05](https://user-images.githubusercontent.com/29157187/204090533-87c5aec6-9b95-4e0b-921f-90411e49d847.png)

**Comment by flavioislima** [comment]
> there is nothing here
> ![2022-11-26_22-05](https://user-images.githubusercontent.com/29157187/204090533-87c5aec6-9b95-4e0b-921f-90411e49d847.png)
> 

It is the option just below on your screenshot.
Called library top section.

**Comment by dtantono** [comment]
yeah, I saw it but, it will be great if both Favourites & Recently Played Games can be viewed easily as well. 
![2022-11-26_22-42](https://user-images.githubusercontent.com/29157187/204091963-de457b70-f00a-4738-b1fa-6ab2da45bdc6.png)
