### ISSUE TITLE
Cannot install "Star Wars Squadrons"

### ISSUE THREAD

**Issue by csutcliff** [Heroic-Games-Launcher/HeroicGamesLauncher#2063]
### Describe the bug

Attempting to install "Star Wars Squadrons" from the EGS (currently free) results in a crash on stable and an error message on beta 3.

`Error:
tr('box.error.generic.message', 'Something Went Wrong!')

TypeError: Cannot use 'in' operator to search for 'languages' in null`

### Add logs

(14:24:59) INFO:    [Connection]:       Connectivity: check-online
(14:24:59) INFO:    [Connection]:       Pinging external endpoints
(14:24:59) INFO:    [Legendary]:        Running command: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary --version
(14:24:59) INFO:    [Legendary]:        Legendary location: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary
(14:24:59) INFO:    [Gog]:              GOGDL location: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl
(14:24:59) WARNING: [Backend]:          Protocol already registered.
(14:25:00) INFO:    [Connection]:       Connectivity: online
(14:25:00) INFO:    [Gog]:              Getting data about the user
(14:25:00) INFO:    [Backend]:          AreWeAntiCheatYet data downloaded
(14:25:00) INFO:    [Gog]:              Running command: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --version
(14:25:00) INFO:    [Backend]:          

Heroic Version: 2.5.0-beta.3 Caesar Clown
Legendary Version:  0.20.31 Dark Energy (hotfix #5)
GOGdl Version: 0.5
OS: Arch KERNEL: 6.1.0-rc6-1-mainline ARCH: x64
CPU: AMD Ryzen 9 5950X 16-Core Processor @3.4 GOVERNOR: schedutil
RAM: Total: 31.26 GiB Available: 21.29 GiB
GRAPHICS: GPU0: Navi 21 [Radeon RX 6800/6800 XT / 6900 XT] VRAM: 1MB DRIVER:  
PROTOCOL: wayland

(14:25:00) INFO:    [Backend]:          Checking for new Heroic Updates
(14:25:00) INFO:    [Frontend]:         Refreshing Library
(14:25:00) INFO:    [Legendary]:        Refreshing library...
(14:25:00) INFO:    [Legendary]:        Refreshing Epic Games...
(14:25:00) INFO:    [Legendary]:        Game list updated, got 63 games & DLCs
(14:25:00) INFO:    [Gog]:              Getting GOG library
(14:25:00) INFO:    [Gog]:              Saved user data to config
(14:25:00) INFO:    [Legendary]:        Running command: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary list
(14:25:00) INFO:    [Gog]:              Number of library pages: 1
(14:25:00) INFO:    [Gog]:              Saved games data
(14:25:02) INFO:    [Winetricks]:       Downloaded Winetricks
(14:25:02) DEBUG:   [Legendary]:        Using cached install info
(14:25:02) DEBUG:   [Legendary]:        Using cached install info
(14:25:02) DEBUG:   [Backend]:          {"free":672515084288,"diskSize":1959595606016,"message":"626.33 GiB / 1.78 TiB","validPath":true}
(14:25:03) INFO:    [Frontend]:         Refreshing Library
(14:25:03) INFO:    [Legendary]:        Refreshing library...
(14:25:03) INFO:    [Legendary]:        Refreshing Epic Games...
(14:25:03) INFO:    [Legendary]:        Game list updated, got 63 games & DLCs
(14:25:03) INFO:    [Gog]:              Getting GOG library
(14:25:03) INFO:    [Gog]:              Number of library pages: 1
(14:25:03) INFO:    [Legendary]:        Running command: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary list
(14:25:03) INFO:    [Gog]:              Saved games data

### Steps to reproduce

1. Go to 'Library'
2. Click install on 'Star Wars Squadrons'
3. See error

### Expected behavior

The game should install

### Screenshots

![Screenshot_20221125_142829](https://user-images.githubusercontent.com/188845/204005578-5dc30c50-fa98-4748-80fc-064aa53e51fc.png)

### System Information

- OS Arch Linux
- Heroic Version: 2.5.0 Beta 3 / 2.4.3

**Comment by flavioislima** [comment]
This game should not even appear on the library because it uses a third party launcher and heroic does not support it. This information is on the Heroic documentation.

**Comment by csutcliff** [comment]
Thank you for the response, I wasn't aware this game relied on a TP launcher, especially as it does show up in Heroic.

**Comment by nightblade9** [comment]
Can someone provide official instructions on how to make this work with Epic?

I installed `legendary` and messed around with installing and executing games via the CLI. At some point, they started showing up in the Heroic UI.
