### ISSUE TITLE
Beta 3 Wine Manager issues

### ISSUE THREAD

**Issue by syeedahmed** [Heroic-Games-Launcher/HeroicGamesLauncher#2066]
### Describe the bug

wine manager can't fetch wine or proton? is it a bug or known issues of beta 3

### Add logs

Heroic Version: 2.5.0-beta.3 Caesar Clown
Legendary Version:  0.20.31 Dark Energy (hotfix #5)
GOGdl Version: 0.5
OS: Fedora Linux KERNEL: 6.0.9-300.fc37.x86_64 ARCH: x64
CPU: AMD Ryzen 5 3400G with Radeon Vega Graphics @3.7 GOVERNOR: schedutil
RAM: Total: 13.57 GiB Available: 10.48 GiB
GRAPHICS: GPU0: Picasso/Raven 2 [Radeon Vega Series / Radeon Vega Mobile Series] VRAM: 512MB DRIVER:  
PROTOCOL: wayland

(11:19:25) INFO:    [Connection]:       Connectivity: online
(11:19:25) INFO:    [Backend]:          Checking for new Heroic Updates
(11:19:25) INFO:    [Frontend]:         Refreshing Library
(11:19:25) INFO:    [Legendary]:        Refreshing library...
(11:19:25) INFO:    [Legendary]:        Refreshing Epic Games...
(11:19:26) INFO:    [Legendary]:        Game list updated, got 142 games & DLCs
(11:19:26) INFO:    [Backend]:          AreWeAntiCheatYet data downloaded
(11:19:27) INFO:    [Legendary]:        Running command: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary list
(11:19:28) INFO:    [Winetricks]:       Downloaded Winetricks
[13453:1126/111929.355508:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 1 times!
(11:19:33) INFO:    [Frontend]:         Refreshing wine downloader releases
(11:19:33) INFO:    [WineDownloader]:   Updating wine versions info
(11:19:33) INFO:    [WineDownloader]:   Read local information ...
(11:19:33) INFO:    [WineDownloader]:   wine versions updated
[13453:1126/111936.065150:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 2 times!

### Steps to reproduce

1. Go to the wine manager
that's is

### Expected behavior

can't fetch wine or proton

### Screenshots

![Screenshot from 2022-11-26 11-19-53](https://user-images.githubusercontent.com/62342624/204073700-2fbdcd55-c894-457b-a36d-8aec2480650e.png)

### System Information

OS: Fedora Linux
Heroic Version: 2.5.0-beta.3 Caesar Clown

**Comment by flavioislima** [comment]
Hmm, a refresh button should be available there and that's might be the reason.

Will fix that before stable.
