### ISSUE TITLE
Origin(?) games are unavailable in the library

### ISSUE THREAD

**Issue by lever1209** [Heroic-Games-Launcher/HeroicGamesLauncher#2067]
### Describe the bug

Star wars battlefront two and star wars squadrons are not listed at all in the library

### Add logs

(04:09:40) INFO:    [Connection]:       Connectivity: check-online
(04:09:40) INFO:    [Connection]:       Pinging external endpoints
(04:09:40) INFO:    [Legendary]:        Running command: /tmp/.mount_HeroicGMtIWs/resources/app.asar.unpacked/build/bin/linux/legendary --version
(04:09:40) INFO:    [Legendary]:        Legendary location: /tmp/.mount_HeroicGMtIWs/resources/app.asar.unpacked/build/bin/linux/legendary
(04:09:40) INFO:    [Gog]:              GOGDL location: /tmp/.mount_HeroicGMtIWs/resources/app.asar.unpacked/build/bin/linux/gogdl
(04:09:41) WARNING: [Backend]:          Failed to register protocol with OS.
(04:09:41) INFO:    [Connection]:       Connectivity: online
(04:09:41) INFO:    [Gog]:              Getting data about the user
(04:09:41) INFO:    [Gog]:              Running command: /tmp/.mount_HeroicGMtIWs/resources/app.asar.unpacked/build/bin/linux/gogdl --version
(04:09:41) INFO:    [Backend]:          AreWeAntiCheatYet data downloaded
(04:09:41) INFO:    [Backend]:          

Heroic Version: 2.5.0-beta.3 Caesar Clown
Legendary Version:  0.20.31 Dark Energy (hotfix #5)
GOGdl Version: 0.5
OS: Arch KERNEL: 6.0.8-arch1-1 ARCH: x64
CPU: Intel Core™ i7-3770 @3.4 GOVERNOR: schedutil
RAM: Total: 17.53 GiB Available: 12.84 GiB
GRAPHICS: GPU0: NVIDIA GeForce GTX 1650 VRAM: 4096MB DRIVER: 520.56.06 
PROTOCOL: tty

(04:09:41) INFO:    [Gog]:              Saved user data to config
(04:09:42) INFO:    [Backend]:          Checking for new Heroic Updates
(04:09:42) INFO:    [Frontend]:         Refreshing Library
(04:09:42) INFO:    [Legendary]:        Refreshing library...
(04:09:42) INFO:    [Legendary]:        Refreshing Epic Games...
(04:09:42) INFO:    [Legendary]:        Game list updated, got 206 games & DLCs
(04:09:42) INFO:    [Gog]:              Getting GOG library
(04:09:42) INFO:    [Legendary]:        Running command: /tmp/.mount_HeroicGMtIWs/resources/app.asar.unpacked/build/bin/linux/legendary list
(04:09:42) INFO:    [Gog]:              Number of library pages: 1
(04:09:43) INFO:    [Gog]:              Saved games data
(04:09:44) INFO:    [DXVKInstaller]:    Updating vkd3d to: vkd3d-proton-2.7
(04:09:44) INFO:    [Winetricks]:       Downloaded Winetricks
(04:09:44) INFO:    [DXVKInstaller]:    downloaded vkd3d
(04:09:44) INFO:    [DXVKInstaller]:    extracting vkd3d
(04:09:44) INFO:    [DXVKInstaller]:    vkd3d updated!

### Steps to reproduce

add star wars squadrons to your library [its free at the moment](https://store.epicgames.com/en-US/p/star-wars-squadrons)

refresh your library

search for it or scroll manually through

### Expected behavior

it should show up

### System Information

arch linux
2.5.0-beta.3

### Additional information

the only connection between these two games is that they use the origin launcher, which may be a reason why its broken

my guess:
either manually disabled by the heroic devs (a one time warning message would be nice) or caused by some strange epic games api behavior about origin launcher games

**Comment by lever1209** [comment]
i feel like i should mention that it was also broken in 2.5.0-beta.2 and 2.4.3

**Comment by flavioislima** [comment]
This is on the documentation and we had several issues saying the same.
EA games are not supported since they are launched by origin and not Epic launcher.

**Comment by lever1209** [comment]
could you make a one time warning message about it if origin games are detected?

maybe you can list them anyway and put the message on an info icon replacing the install button

**Comment by codingthat** [comment]
> maybe you can list them anyway and put the message on an info icon replacing the install button

I love this idea!  To me this is much better than a one-time warning or docs, since it gives you the info you need exactly when you need it.  ✔

**Comment by flavioislima** [comment]
I will add something like this on my current PR with the other fixes.

**Comment by flavioislima** [comment]
That should do it for now:
![image](https://user-images.githubusercontent.com/26871415/204144607-bd075ac7-f831-459f-8d4b-d4a19b4185a7.png)

**Comment by flavioislima** [comment]
For the game page:
![image](https://user-images.githubusercontent.com/26871415/204145097-45dc96b8-f26a-4c46-979c-74c530022e83.png)

**Comment by lever1209** [comment]
holy crap that was fast, thank you
