### ISSUE TITLE
Disable Epic login if the OS is incompatible with Legendary

### ISSUE THREAD

**Issue by arielj** [Heroic-Games-Launcher/HeroicGamesLauncher#2071]
### Problem description

It is really common on Discord to have users using old version of MacOS (High Sierra) and sometimes Windows 7 asking about issues during login.

The problem is that Legendary requires Windows 8.1+ and MacOS 12.0+ but we don't show that anywhere and we show no error when the login fails either. https://github.com/derrod/legendary#requirements

### Feature description

In the login screen, if we detect the OS is incompatible, the Epic login options should be disabled with a message explaining that we use Legendary and Legendary is not compatible with the OS version.

### Alternatives

No idea.

**Comment by flavioislima** [comment]
Actually, we need to show a message that Heroic is not compatible with those systems, MS does not support windows 7 anymore so why should we?

So we can show a dialog if we detect one of those systems instead of disabling Epic and this dialog should not be able to close and after clicking OK Heroic would quit.

**Comment by dylanmtaylor** [comment]
> Actually, we need to show a message that Heroic is not compatible with those systems, MS does not support windows 7 anymore so why should we?
> 
> So we can show a dialog if we detect one of those systems instead of disabling Epic and this dialog should not be able to close and after clicking OK Heroic would quit.

Windows 8.1 will reach end of support on January 10, 2023, so it might make sense to only support Windows 10+
