### ISSUE TITLE
Sort by purchase order (gog)

### ISSUE THREAD

**Issue by Bubu** [Heroic-Games-Launcher/HeroicGamesLauncher#2091]
### Feature description

I'd like to see the most recently purchased games on top of my list of games, so I can more easily install them on the deck. Otherwise I need to know the name of the game (which when getting a free game offer by gog, I often don't really remember) and use the search function to get to the game. Or scroll through the alphabetical library 

Gog provides this sort order in their online library view, it might be a bit hard to get the purchase date of a game via the api though? Gog galaxy doesn't have this as an option but they do expose a purchase history site.

![image](https://user-images.githubusercontent.com/105185/204364986-98e5cfa1-7e5d-4318-a5c9-84923de49b6b.png)

**Comment by flavioislima** [comment]
I'm not sure if that is possible since we don't have any account information. All we have from the user is the username. Heroic does not access any other information about your buyings or anything else.
