### ISSUE TITLE
With 2.5.0 "Game Needs Update" popup is invisible when Heroic window is closed

### ISSUE THREAD

**Issue by trueNightRomantic** [Heroic-Games-Launcher/HeroicGamesLauncher#2101]
### Describe the bug

Title basically says it all. Scenario to recreate the behaviour is in steps to reproduce.

### Add logs

```text
I'm quite sure logs aren't useful with this bugreport.
```

### Steps to reproduce

1. Close Heroic window leaving tray icon;
2. Right-click tray icon and try to launch a game that has update available;

Nothing happens. Nothing at all :-(

3. Open Heroic window and see the "Game Needs Update" notification.

### Expected behavior

I can think of three ways to solve this:

1. Show a system notification so that user could see the reason for game not launching.
2. Open the Heroic window with new popup in it -  this one maybe a little heavy-handed.
3. Show old style popup. Not pretty, but it works.

Consider also #2040 , it will help with games user don't want to update.

### System Information

- Heroic Version 2.5.0

### Additional information

Connected to #2040

**Comment by flavioislima** [comment]
Hmm. We actually fixed that partially when launching games from Steam or when using a no-gui flag, but that's true, there are edge cases that were not covered.

**Comment by trueNightRomantic** [comment]
Additional detail: it happens when launching game through tray icon regardless of window state, i.e. for open window:
- Heroic window is open.
- Click tray icon to launch a game.
- Heroic window closes (normal/expected behaviour).
- Nothing happens, game doesn't start (unexpected behaviour).
- Reopen Heroic window, new style "Game needs update" window is there.
