### ISSUE TITLE
Support Steam Deck as a PC controller for another PC

### ISSUE THREAD

**Issue by dtantono** [Heroic-Games-Launcher/HeroicGamesLauncher#2116]
### Problem description

Hi
I know Heroic support Steam Deck and it will be wonderful if Steam Deck can become a controller to other PC

### Feature description

Steam deck can become controller to other PC

### Alternatives

Steam Link

**Comment by arielj** [comment]
Sorry, I don't understand how is this related to Heroic, sounds like a feature you want on the Steam Deck, independently of Heroic Games Launcher.

**Comment by dtantono** [comment]
it is like heroic detect steam deck as a controller on another PC

**Comment by arielj** [comment]
sorry I still don't quiet understand, you mean you want to have Heroic installed on your PC and use the steam deck to control Heroic on your PC?

you first need to get your PC to detect steam deck as a controller, Heroic can't detect a controller unless your PC lists that as a controller

you have to find a way to tell your PC that you have a steam deck that you want to use as a controller, then Heroic will probably see it, but we can't bypass what the Operating System detects

**Comment by flavioislima** [comment]
Also, totally out of scope.
