### ISSUE TITLE
[UI] Adjust the UI to Right-to-left Languages.

### ISSUE THREAD

**Issue by Ali-x98** [Heroic-Games-Launcher/HeroicGamesLauncher#2117]
### Describe the bug

When using right-to-left languages (e.g., Arabic, Persian, Hebrew), the UI should be mirrored to the right side of the screen, along with all texts and UI elements.

There was an attempt to fix this in #868, but the UI is still not completely mirorred.

Comparing English and Persian (since Arabic is still not in the selection even though it's 100% complete):
![image](https://user-images.githubusercontent.com/25479373/205084994-84950969-ab5e-4d3e-84ca-4689c2627272.png)
![image](https://user-images.githubusercontent.com/25479373/205084304-69b25aed-d69c-425a-b2da-cc1fbf6ff16f.png)

The side bar should be on the right, and the text inside should be written right-to-left.

This image from [Apple](https://developer.apple.com/library/archive/documentation/MacOSX/Conceptual/BPInternational/SupportingRight-To-LeftLanguages/SupportingRight-To-LeftLanguages.html) demonstrates this well:
![image](https://user-images.githubusercontent.com/25479373/205087969-55a3b61d-fd99-43e8-86cd-86829bfdb2fb.png)

### Add logs

```text
-
```

### Steps to reproduce

1. Go to Setting
2. Click on the 'Choose App Language' box
3. Select any RTL language (I think Persian is currently the only one available).

### Expected behavior

UI should be mirrored to the right side.

### System Information

- OS [Fedora 37]: 
- Heroic Version [2.5.0]:

**Comment by flavioislima** [comment]
Good, we will look into it. And also add Arabic to the list.
