### ISSUE TITLE
[macOS] crossover setting doesn't do anything 

### ISSUE THREAD

**Issue by ai-h24** [Heroic-Games-Launcher/HeroicGamesLauncher#2118]
### Describe the bug

crossover version button in setttings doesn't do anything, it clicks but no menu or options show up on Heroic (2.5.0 or older)  i tried reinstalling crossover and heroic fully and that didn't fix it, tried other version of heroic still nothing. 

crossover version is 22.0.1
herioc 2.5.0

### Add logs

```text
(13:26:48) INFO:    [Connection]:       Connectivity: check-online
(13:26:48) INFO:    [Connection]:       Pinging external endpoints
(13:26:48) INFO:    [Legendary]:        Running command: /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/legendary --version
(13:26:48) INFO:    [Legendary]:        Legendary location: /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/legendary
(13:26:48) INFO:    [Gog]:              GOGDL location: /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/gogdl
(13:26:48) WARNING: [Backend]:          Protocol already registered.
(13:26:49) INFO:    [Connection]:       Connectivity: online
(13:26:49) INFO:    [Gog]:              Running command: /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/gogdl --version
(13:26:51) INFO:    [Backend]:          

Heroic Version: 2.5.0 Yamato
Legendary Version:  0.20.31 Dark Energy (hotfix #5)
GOGdl Version: 0.5
OS: macOS Ventura 13.1 KERNEL: 22.2.0 ARCH: x64
CPU: Apple M1 @2.4 
RAM: Total: 8 GiB Available: 5.87 GiB
GRAPHICS: GPU0: Apple M1   


(13:26:53) INFO:    [Backend]:          Checking for new Heroic Updates
(13:26:53) INFO:    [Frontend]:         Refreshing Library
(13:26:53) INFO:    [Legendary]:        Refreshing library...
(13:26:53) INFO:    [Legendary]:        Refreshing Epic Games...
(13:26:53) INFO:    [Legendary]:        Game list updated, got 81 games & DLCs
(13:26:53) INFO:    [Backend]:          Checking for current version changelog
(13:26:53) INFO:    [Frontend]:         Force Update
(13:26:54) INFO:    [Legendary]:        Running command: /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/legendary list --third-party
(13:26:55) INFO:    [Frontend]:         Refreshing Library
(13:26:55) INFO:    [Legendary]:        Refreshing library...
(13:26:55) INFO:    [Legendary]:        Refreshing Epic Games...
(13:26:55) INFO:    [Legendary]:        Game list updated, got 81 games & DLCs
(13:26:56) INFO:    [Legendary]:        Running command: /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/legendary list --third-party
(13:26:57) INFO:    [Frontend]:         Refreshing Library
(13:26:57) INFO:    [Legendary]:        Refreshing library...
(13:26:57) INFO:    [Legendary]:        Refreshing Epic Games...
(13:26:57) INFO:    [Legendary]:        Game list updated, got 81 games & DLCs
(13:26:58) DEBUG:   [Legendary]:        Using cached install info
(13:26:58) INFO:    [Legendary]:        Running command: /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/legendary list --third-party
(13:33:59) DEBUG:   [Legendary]:        Using cached install info
```

### Steps to reproduce

1. Go to settings
2. Click on game defaults 
3. Scroll down to crossover version
4. See error nothing happens when clicking on it

### Expected behavior

open a menu to choose wine/crossover versions. 

### Screenshots

![no](https://user-images.githubusercontent.com/117847131/205132590-4e0d8157-ec7c-4dc7-9979-557139a10f3f.png)

### System Information

Heroic Version: 2.5.0 Yamato
OS: macOS Ventura 13.1 KERNEL: 22.2.0 ARCH: x64
CPU: Apple M1 @2.4 
RAM: Total: 8 GiB Available: 5.87 GiB
GRAPHICS: GPU0: Apple M1

**Comment by ai-h24** [comment]
also clicking on play on any downloaded game shows this: 

![wine](https://user-images.githubusercontent.com/117847131/205134829-6d57c978-90ac-4f62-946b-bbc744fca8b2.png)

**Comment by flavioislima** [comment]
What is the ouput of this comand on the terminal:
`'mdfind kMDItemCFBundleIdentifier = "com.codeweavers.CrossOver"'
`
For me it is working fine, if you want check this version here that I am working and I am adding support for Wine and Wineskin, although it is still in testing:
https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/actions/runs/3593528352

**Comment by ai-h24** [comment]
no output. 
![1](https://user-images.githubusercontent.com/117847131/205146836-40798700-9bb8-4087-9384-0aad65974288.png)

**Comment by flavioislima** [comment]
This is related with where your app is. If the command does not show anything is because it is not registered. How exactly did you install it? can you move the crossover.app to the /applications folder?

**Comment by ai-h24** [comment]
> This is related with where your app is. If the command does not show anything is because it is not registered. How exactly did you install it? can you move the crossover.app to the /applications folder?

oh that makes more sense why i keep getting "move to application follder" each time i open crossover. but the thing is its already in the application folder. so i’m not sure what is missing but let me re-install it once more maybe i missed something or irdk ill try and report back

**Comment by ai-h24** [comment]
well re-installing crossover stopped giving the "move to application folder" screen. but still i cant click or do anything in Heroic (crossover version) option. and the command still dose not show anything. what should i do? right now i’m using the trial version of crossover. idk if thats related to this or not.

**Comment by ai-h24** [comment]
never mind i just found this [someone with the same issue](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/issues/821#issuecomment-1001697908) and, yeah i have spotlight disabled too. well ill re-enable it and see if that works. thanks for ur time and help!

**Comment by flavioislima** [comment]
> never mind i just found this [someone with the same issue](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/issues/821#issuecomment-1001697908) and, yeah i have spotlight disabled too. well ill re-enable it and see if that works. thanks for ur time and help!

cool, I totally forgot about that, yes Spotlight needs to be installed for the search to work.
We should add this info somewhere in the troubleshooting section of the wiki.

**Comment by ai-h24** [comment]
yup! thank you very much! it didn't show at first after re-enabling spotlight. but re-installing Heroic did the trick!

**Comment by duckyy1992** [comment]
So I’m having the exact same issue but my spotlight is turned on with no locations excluded from search, not sure what else to try

**Comment by ai-h24** [comment]
> So I’m having the exact same issue but my spotlight is turned on with no locations excluded from search, not sure what else to try

yeah same here after updating to the new Heroic version 1.5.1 the issue is back. 
and, yes. spotlight is working and the older 1.5.0 version of Heroic can find crossover like it normally does and lunch games normally. @flavioislima thanks in advance.

**Comment by flavioislima** [comment]
I will try to fix that in the next few days.
Not sure why this is happening to some people because for me I can see crossover just fine.
But since I added the method to check for other wine versions as well, maybe it's not working if you have crossover only.

Maybe try to install wine skin and create a wrapper called heroic.

Or install wine crossover on the home apications folder.

**Comment by ai-h24** [comment]
> OP- is it possible to reopen this issue?

i dont think so, but no need anyway.

> I will try to fix that in the next few days. Not sure why this is happening to some people because for me I can see crossover just fine. But since I added the method to check for other wine versions as well, maybe it's not working if you have crossover only.
> 
> Maybe try to install wine skin and create a wrapper called heroic.
> 
> Or install wine crossover on the home apications folder.

will try right now.......well funny thing while typing that i went to check on it and i just saw crossover being there in Heroic options. its working again.
 ive done nothing my mac been up for days didn't restart or download anything or change a thing (related to crossover or wine or heroic). not sure how it worked. but it does now. 

also huge thanks for adding native arm support!!!! i’m not sure why no one talking about it (or i just live under a rock) and i’m 88% sure this is the first release of an ARM Heroic luncher. so again thank you! because its so so fast. i dont need to use the browser anymore for epic games store.

**Comment by flavioislima** [comment]
@ai-h24 yes, I added a native ARM pkg now on the releases page, will need to update the website as well to add both options there once I have the time.

**Comment by flavioislima** [comment]
You guys that are having issues can use this version here with a fix:
[mac-dmg](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/suites/9768574223/artifacts/469384025)

**Comment by duckyy1992** [comment]
So the original issue is now resolved with the DMG shared earlier,

however I’m now having a secondary issue 

I’m updating from version 2.2.1 and had the choice of selecting a Crossover bottle and then entering my custom wine path which then loaded the game, I’ve entered the same paths in the new version and it says there’s no Wine version selected 
![BED7B966-697E-4B78-972B-97A3B8773DE6](https://user-images.githubusercontent.com/93503766/206796227-22804175-8b5f-4074-a60a-29a829538b8d.jpeg)
![5DF2DE12-9650-469A-A23A-97A64EA8125F](https://user-images.githubusercontent.com/93503766/206796232-ce4fedca-964c-411f-835f-f486bd51dd1d.jpeg)
