### ISSUE TITLE
Cannot launch any Epic game on Mint 19.3 / Ubuntu 18.04

### ISSUE THREAD

**Issue by orbitalchicken** [Heroic-Games-Launcher/HeroicGamesLauncher#2124]
### Describe the bug

I tested with the flatpak version AND with the .deb version and I have the same problem:
In HGL, I can install a game.
When I click the button to play the game, nothing happens.
There is an error in the log. (see logs section below)
(To obtain the log, I had to start HGL from the terminal, because in the Settings, the log is incomplete)

### Add logs

```text
Heroic Version: 2.5.0 Yamato
Legendary Version:  0.20.31 Dark Energy (hotfix #5)
GOGdl Version: 
OS: LinuxMint KERNEL: 5.4.0-97-generic ARCH: x64
CPU: Intel Core™ i5-4590 @3.3 GOVERNOR: powersave
RAM: Total: 31.25 GiB Available: 28.32 GiB
GRAPHICS: GPU0: Xeon E3-1200 v3/4th Gen Core Processor Integrated Graphics Controller  VRAM: 256MB  GPU1: NVIDIA GeForce GTX 950 VRAM: 2000MB DRIVER: 470.161.03 
PROTOCOL: x11

(23:51:27) INFO:    [Backend]:          Checking for new Heroic Updates
(23:51:27) INFO:    [Backend]:          Checking for current version changelog
(23:51:27) INFO:    [Frontend]:         Refreshing Library
(23:51:27) INFO:    [Legendary]:        Refreshing library...
(23:51:27) INFO:    [Legendary]:        Refreshing Epic Games...
(23:51:27) INFO:    [Legendary]:        Game list updated, got 231 games & DLCs
(23:51:27) INFO:    [Legendary]:        Running command: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary list --third-party
(23:51:29) INFO:    [Winetricks]:       Downloading Winetricks
Error occurred in handler for 'syncSaves': TypeError: Cannot read properties of undefined (reading 'replaceAll')
    at T.syncSaves (/opt/Heroic/resources/app.asar/build/electron/main.70993683.js:34:21592)
    at /opt/Heroic/resources/app.asar/build/electron/main.70993683.js:114:6227
    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async node:electron/js2c/browser_init:193:551
```

### Steps to reproduce

Install Heroic Games Launcher in Linux Mint 19.3 (Thus, I assume the same problem on Ubuntu 18.04) 
(Login)
Install a game.
Click the green arrow to launch a game.
Nothing happen.

### Expected behavior

The game should start.

### System Information

- OS: Linux Mint 19.3 (based on Ubuntu 18.04)
- Heroic Version: 2.5.0 (the previous version did not have this problem)

**Comment by flavioislima** [comment]
CAn you try this appimage?
https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/actions/runs/3614395247

**Comment by orbitalchicken** [comment]
Justr tried: With this AppImage, HGL starts and I can install games. But 
when I run game, the game doesn't start. On the other hand please note 
that I had the same problem with the version 2.4.3 AppImage and .deb. So 
version 2.4.3 only worked in flatpak format. All this on Mint 19.3 
(Ubuntu 18.04).

Le 2022-12-04 à 16 h 19, Flávio F Lima a écrit :
