### ISSUE TITLE
Add a pause button into the download manager

### ISSUE THREAD

**Issue by BenTowali** [Heroic-Games-Launcher/HeroicGamesLauncher#2126]
### Problem description

I want to be able to pause downloads whenever, instead of cancelling (all) the download(s).

### Feature description

This feature would add a pause button in the download manager.

Example:
![pausebutton](https://user-images.githubusercontent.com/108379869/205426789-8aaed4ab-61d9-4999-97ba-15ba8e5522a0.png)

**Comment by lever1209** [comment]
i see the utility of a dedicated pause button, but there is a way to do this already

click the X, and in this menu hit the button labeled "YES"
![image](https://user-images.githubusercontent.com/34011519/205472632-bb8ce85d-4fed-4857-8611-611efe6728be.png)

then you can hit install on the game later like so (it will be grouped with games not installed)
![image](https://user-images.githubusercontent.com/34011519/205472658-060de789-caea-46dd-b1bb-084366b5d89f.png)

**Comment by GenocideStomper** [comment]
Continuing the download doesn't pick up the changed WinePrefix path that was previously setup.

**Comment by lever1209** [comment]
@GenocideStomper this issue has already been marked as resolved, and your problem is unrelated to the original reason this issue was created, please go create a new issue

**Comment by GenocideStomper** [comment]
The original issue was a suggestion to add a pause button to the download manager. Your suggestion was to cancel the download and then start it again. My comment was that that's not without issue, and doesn't adequately cover the initial request for a pause button.

If you want I can create a new issue with the exact same content as @BenTowali initial post, but it'll probably be marked as a duplicate of this issue. Perhaps a mod can re-open this issue.
