### ISSUE TITLE
Accessibility Font Page is Too Large Compared to the Rest of the Interface

### ISSUE THREAD

**Issue by cachandlerdev** [Heroic-Games-Launcher/HeroicGamesLauncher#2127]
### Describe the bug

The text on the Accessibility page uses a much larger font size than the text used throughout the rest of the application.

### Add logs

```text
(21:55:09) INFO:    [Connection]:       Connectivity: check-online
(21:55:09) INFO:    [Connection]:       Pinging external endpoints
(21:55:09) INFO:    [Legendary]:        Running command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary --version
(21:55:09) INFO:    [Legendary]:        Legendary location: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary
(21:55:09) INFO:    [Gog]:              GOGDL location: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl
(21:55:09) WARNING: [Backend]:          Failed to register protocol with OS.
(21:55:09) INFO:    [Gog]:              Running command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --version
(21:55:09) INFO:    [Connection]:       Connectivity: online
(21:55:09) INFO:    [Gog]:              Getting data about the user
(21:55:09) INFO:    [Backend]:          AreWeAntiCheatYet data downloaded
(21:55:09) INFO:    [Backend]:          

Heroic Version: 2.5.0 Yamato
Legendary Version:  0.20.31 Dark Energy (hotfix #5)
GOGdl Version: 0.5
OS: Freedesktop SDK KERNEL: 6.0.5-200.fc36.x86_64 ARCH: x64
CPU: AMD Ryzen 7 7700X 8-Core Processor @3.83 GOVERNOR: schedutil
RAM: Total: 30.5 GiB Available: 25.14 GiB
GRAPHICS: GPU0: TU104 [GeForce RTX 2070 SUPER]  VRAM: 32MB  GPU1: Device 164e VRAM: 512MB  
PROTOCOL: x11

(21:55:10) INFO:    [Backend]:          Checking for current version changelog
(21:55:10) INFO:    [Frontend]:         Refreshing Library
(21:55:10) INFO:    [Legendary]:        Refreshing library...
(21:55:10) INFO:    [Legendary]:        Refreshing Epic Games...
(21:55:10) INFO:    [Legendary]:        Game list updated, got 286 games & DLCs
(21:55:10) INFO:    [Gog]:              Getting GOG library
(21:55:11) INFO:    [Gog]:              Saved user data to config
(21:55:11) INFO:    [Legendary]:        Running command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary list --third-party
(21:55:11) INFO:    [Gog]:              Number of library pages: 1
(21:55:11) INFO:    [Gog]:              Saved games data
(21:55:12) INFO:    [Winetricks]:       Downloading Winetricks
```

### Steps to reproduce

1. Open the application.
2. Go to the Accessibility panel.

### Expected behavior

I would expect the Accessibility page to follow the same style guidelines used throughout the rest of the application, such as the font size found in the Settings pages.

### Screenshots

Regular interface size:
![image](https://user-images.githubusercontent.com/70250943/205426673-de81701f-1b93-4e6a-81cb-437abf8b5f2e.png)

Accessibility page size:
![image](https://user-images.githubusercontent.com/70250943/205426697-b910bb68-a44c-495b-a187-e0b560f39b1b.png)

### System Information

- OS: Fedora Linux
- Heroic Version: 2.5.0

**Comment by flavioislima** [comment]
I think that's intentional since the person that goes there might have issues with the default font size.

**Comment by cachandlerdev** [comment]
I suppose that might make sense, but it just seems a little jarring to have the app jump from roughly size 13 to size 18 whenever the user wants to change the style theme (since that option is placed in the accessibility page).

**Comment by flavioislima** [comment]
Yes, we need to re-think if we want to keep that setting on the accessibility page or move it to general settings.

**Comment by arielj** [comment]
Yes, the font size is intentional.

At some point the settings for the theme was both in the accessibility page and in general, I think it belongs to both places. I'd prefer to have those settings duplicated so we are covered for users with accessibility needs and also for users that may expect the theme setting to be in the general settings.

**Comment by flavioislima** [comment]
Yes, maybe makes sense to have it in both.

**Comment by flavioislima** [comment]
Anyway, closing this one since we won't change the accessibility page font size.
