### ISSUE TITLE
(Steam Deck Game mode) Launching games from Steam is erratic

### ISSUE THREAD

**Issue by brechtm** [Heroic-Games-Launcher/HeroicGamesLauncher#2130]
### Describe the bug

Launching Heroic games from Steam in gaming mode is buggy since upgrading to 2.5.0 (from 2.4.?). Sometimes it works fine as before, but often it starts the game several times (typically 3 or 4). I'm not sure, but I think games also take longer to launch compared to 2.4.? (also reported in #2115).

This happens for all games I tried. I haven't yet verified whether the same happens in Desktop mode.

P.S. Thanks for this wonderful piece of software! It makes the Steam Deck even better, adding user-friendly support for GOG and EGS games.

### Add logs

```text
NA
```

### Steps to reproduce

1. Install game in Heroic
2. 'Add to Steam'
3. Launch game in Steam
4. See the game starting up several times

### Expected behavior

Launch game only once.

### System Information

Steam Deck

**Comment by flavioislima** [comment]
I cankot replicate that.
The issue introduced on 2.5 is that if the game has an update, it will hang on the loading screen forever. This I fixed already.

On thing it have in mind is that if the game is set to auto sync saves, the startup will take longer than normal.

**Comment by edt-xx** [comment]
I am in PC with beta2 and have had this Happen with cyberpunk a few times.  I've not been able to figure out how to trigger it on demand though.

**Comment by arielj** [comment]
@brechtm is this still happening with heroic 2.5.1?

**Comment by brechtm** [comment]
I upgraded to 2.5.1 yesterday and haven't seen it happen again. But since on 2.5.0 it didn't _always_ happen, I'll need to give it some more time before I can say it is fixed with relative certainty.

In any case, it still takes longer for games to start. Seems to be around 15 seconds, the save path detection timeout mentioned in the release notes. I tried manually syncing (download) saves on Celeste, which failed, so that may be related?

**Comment by arielj** [comment]
> In any case, it still takes longer for games to start. Seems to be around 15 seconds, the save path detection timeout mentioned in the release notes. I tried manually syncing (download) saves on Celeste, which failed, so that may be related?

yes, it's probably related, if you disable auto sync saves for Celeste, does it start the game immediately?

**Comment by flavioislima** [comment]
should be fixed now

**Comment by brechtm** [comment]
I haven't seen this issue anymore! 👍
Starting games still takes quite long, even though auto sync saves is disabled.
