### ISSUE TITLE
Heroic Games Launcher won’t open 

### ISSUE THREAD

**Issue by Jetsbro** [Heroic-Games-Launcher/HeroicGamesLauncher#2146]
### Describe the bug

Downloaded Heroic Games Launcher on steam deck I have read previously on here that I need to remove legendary.exe file can someone explain to me step by step please on how to locate this file and remove it thanks

### Add logs

```text
H
```

### Steps to reproduce

2. Click on '...'
3. Scroll down to '...'

### Expected behavior

Heroic Games Launcher to open

### System Information

- OS [e. g. "Ubuntu"]: 
- Heroic Version [e. g. 2.1.1]:

**Comment by flavioislima** [comment]
What?

**Comment by flavioislima** [comment]
Please fill all the needed information.
Have you tried running from the terminal to see the output?check the logs and reopen the issue once you add all the information. Its hard to help like this.

**Comment by Jetsbro** [comment]
Why is it closed

**Comment by arielj** [comment]
> Why is it closed

The description is not clear, why do you want to remove the legendary exe? where did you read that? legendary.exe is a windows file so it has nothing to do with heroic on the steam deck. what happens when you try to pen heroic? how are you installing heroic? you have to provide more information when reporting a problem, it's impossible to help with so little information

**Comment by Jetsbro** [comment]
On steam deck installed Heroic Games Launcher I click on it and nothing happens. There was a person on here who had the same problem and they said all they did was remove the legendary.exe file and it solved it

**Comment by arielj** [comment]
how did you install heroic? using discover? or did you download some binary?

have you tried running heroic from the command line to see if there's any error?

ignore that about deleting the legendary.exe file

apart from these questions, github issues are for heroic errors, not for support, you should use our discord, there's a support channel/forum to get help on this kind of problems

**Comment by Jetsbro** [comment]
Yeah I downloaded it from Discover I click on it nothing happens it shows up as loading in the bottom bar then disappears… how do I run it from a command line

**Comment by arielj** [comment]
please use heroic's discord to get support, there are more users there that can help
