### ISSUE TITLE
Flatpak fails to start on new version.

### ISSUE THREAD

**Issue by aleksasiriski** [Heroic-Games-Launcher/HeroicGamesLauncher#2149]
### Describe the bug

Flatpak fails to start on new version.

### Add logs

```text
[3:1206/191623.142635:ERROR:ozone_platform_x11.cc(240)] Missing X server or $DISPLAY
[3:1206/191623.142660:ERROR:env.cc(255)] The platform failed to initialize.  Exiting.
/app/bin/heroic-run: line 2:     3 Segmentation fault      (core dumped) zypak-wrapper /app/bin/heroic/heroic "$@"
```

### Steps to reproduce

1. flatpak run com.heroicgameslauncher.hgl

### Expected behavior

Work

### System Information

- OS [e. g. "Ubuntu"]: Fedora Silverblue
- Heroic Version [e. g. 2.1.1]: 2.5.0

**Comment by rei-nert** [comment]
Same error occurring in Debian Testing and Heroic version 2.5.1

**Comment by flavioislima** [comment]
Steam flatpak works under wayland?

one thing I noticed that I changed on the flatpak package was that:
removed this:
--socket=x11

added this:
--socket=fallback-x11

**Comment by flavioislima** [comment]
Changed that because the documentation says that there is no x11:
https://docs.flatpak.org/en/latest/sandbox-permissions.html

**Comment by flavioislima** [comment]
I will update the file with both sockets to see, seems I misunderstood this.

**Comment by joedank** [comment]
Same issue with flatpack I'm instead using COPR repo which is still on previous version

**Comment by flavioislima** [comment]
@joedank if not flatpak then it is another issue, you will need to open a new issue and attach the logs there

**Comment by flavioislima** [comment]
@aleksasiriski try this build:
`flatpak install --user https://dl.flathub.org/build-repo/122582/com.heroicgameslauncher.hgl.flatpakref`

**Comment by flavioislima** [comment]
thats news to me

**Comment by rei-nert** [comment]
Here on Debian Testing is now working

**Comment by flavioislima** [comment]
ok, let me update flathub, maybe installing from there might fix your issue @aleksasiriski

**Comment by aleksasiriski** [comment]
Manaully disabling --socket=fallback-x11 fixed it, the stable version from Flathub.

**Comment by joedank** [comment]
> @joedank if not flatpak then it is another issue, you will need to open a new issue and attach the logs there

You should re-read my sentence

**Comment by flavioislima** [comment]
> > @joedank if not flatpak then it is another issue, you will need to open a new issue and attach the logs there
> 
> You should re-read my sentence. Ill try fix and update thanks

yes, read too fast and saw only the COPR part 🤦🏽 
Need to turn off the computer for the day
