### ISSUE TITLE
No wine version selected

### ISSUE THREAD

**Issue by BenTowali** [Heroic-Games-Launcher/HeroicGamesLauncher#2151]
### Describe the bug

When I try to launch a game for the first time it says "no wine version selected" even though it is. To fix it I have to select another option then the wine option again.

### Add logs

```text
(23:34:47) INFO:    [Connection]:       Connectivity: check-online
(23:34:47) INFO:    [Connection]:       Pinging external endpoints
(23:34:47) INFO:    [Legendary]:        Running command: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary --version
(23:34:47) INFO:    [Legendary]:        Legendary location: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary
(23:34:47) INFO:    [Gog]:              GOGDL location: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl
(23:34:47) WARNING: [Backend]:          Protocol already registered.
(23:34:47) INFO:    [Connection]:       Connectivity: online
(23:34:47) INFO:    [Gog]:              Running command: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --version
(23:34:47) INFO:    [Backend]:          AreWeAntiCheatYet data downloaded
(23:34:47) INFO:    [Backend]:          

Heroic Version: 2.5.1 Yamato
Legendary Version:  0.20.31 Dark Energy (hotfix #5)
GOGdl Version: 0.5
OS: Arch KERNEL: 6.0.9-arch1-1 ARCH: x64
CPU: Intel Core™ i7-7700 @3.6 GOVERNOR: powersave
RAM: Total: 15.59 GiB Available: 11.01 GiB
GRAPHICS: GPU0: GP104 [GeForce GTX 1070 Ti]  VRAM: 32MB  
PROTOCOL: x11

(23:34:48) INFO:    [Backend]:          Checking for new Heroic Updates
(23:34:48) INFO:    [Backend]:          Checking for current version changelog
(23:34:48) INFO:    [Frontend]:         Refreshing Library
(23:34:48) INFO:    [Legendary]:        Refreshing library...
(23:34:48) INFO:    [Legendary]:        Refreshing Epic Games...
(23:34:48) INFO:    [Legendary]:        Game list updated, got 58 games & DLCs
(23:34:48) INFO:    [Backend]:          Frontend Ready
(23:34:48) INFO:    [Legendary]:        Running command: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary list --third-party
(23:34:49) INFO:    [Winetricks]:       Downloading Winetricks
(23:34:51) INFO:    [Backend]:          Launching Hue (Herring)
(23:34:51) INFO:    [Backend]:          Preventing display from sleep
(23:34:51) INFO:    [Backend]:          Stopping Display Power Saver Blocker
(23:34:52) INFO:    [Frontend]:         Refreshing Library
(23:34:52) INFO:    [Legendary]:        Refreshing library...
(23:34:52) INFO:    [Legendary]:        Game list updated, got 58 games & DLCs
(23:34:53) INFO:    [Backend]:          Starting the Download Queue
```

### Steps to reproduce

1. Click the play button
2. See error

### Expected behavior

The game would just launch without having to go to the game settings and selecting another option and then the wine version again.

### Screenshots

![image](https://user-images.githubusercontent.com/108379869/206027659-75e0ad69-f455-41fb-804a-20bc3eeed33b.png)
![image](https://user-images.githubusercontent.com/108379869/206027707-66f88ae7-f879-42f7-9696-a8113be2ba90.png)

### System Information

- OS [e. g. "Ubuntu"]: Arch Linux
- Heroic Version [e. g. 2.1.1]: 2.5.1

**Comment by BenTowali** [comment]
Still doesn't work OOTB, but it's not a huge deal honestly it's just weird.

**Comment by nolt** [comment]
I have same error, just installed from Epic TombRaider and as default wine I have default wine version: Wine-GE-Proton-31 same prefix for installed game. After install folder in Prefix dir has been created but it was empty; winecfg button in game settings doesn't work. I installed Wine-GE-Proton-34 and set it in game settings then winecfg and prefix has been created and game runs. :confused:

**Comment by KawaiiDinosaur** [comment]
The same is happening to me. Heroic seems hardcoded to look for for Wine-GE-Proton7-20 despite Wine-GE-Proton7-35 being the one installed. 

![Screenshot_20221220_202002](https://user-images.githubusercontent.com/36821201/208784993-5f082bd6-7579-445c-a5ae-40326cff9dba.png)
![Screenshot_20221220_202025](https://user-images.githubusercontent.com/36821201/208785020-5cb84464-d5d9-4d3d-a93f-ab319b1c7482.png)
![Screenshot_20221220_201932](https://user-images.githubusercontent.com/36821201/208785030-d137a1e1-c96a-4d3d-a0e7-6a60e196051d.png)

**Comment by Bananaman** [comment]
@arielj I just installed Heroic via Flatpak, and I think your suspicion is correct.

Here was my process:

- Install fresh Flatpak. No old settings exist.
- Go to Wine Manager, download newest GE-Wine.
- Go to Settings: Game Defaults, and noticed that this "Wine-GE-Proton7-35" is already selected, so I did nothing else.
- Went and downloaded the Windows version of a GOG game.
- The game refused to run, with the warning "No Wine Version Selected. Check Game Settings!"
- I went into the GAME CONFIGURATION, set the Wine Version to Proton and then immediately back to Wine-GE-Proton7-35.
- Now the game runs.

I then guessed that your comment about the global default dropdown NOT ACTUALLY having a setting was the true error here.

So I uninstalled the game and told it to delete the prefix.

Then I went to the global GAME DEFAULTS, did the "set as Proton then set as Wine-GE" dance.

When I installed the game again, this time it runs perfectly with the correct runner without having to change anything.

So yes, Heroic Games Launcher doesn't have any list selection by default. It's a false selection, simply by being the topmost entry in the list.

Easy fix: Add a default "(No Runner)" option at the top of the list or something like that, which shows up UNTIL the user has set an actual value in that list.

**Comment by nolt** [comment]
Well I had two different versions set up. Older as default and I pointed newer for new install and issue occurs as empty prefix dir in new installation. Both versions has been downloaded (default - after heroic install, new one before game was downloaded).

**Comment by arielj** [comment]
Can anyone confirm if this issue is still present? We made some changes on what happens when Heroic cannot find the selected wine

**Comment by nolt** [comment]
I've installed few games from Epic and didn't noticed any further issues. Prefixes was created as they should - all games works just fine.

**Comment by flavioislima** [comment]
Yes this was fixed on the latest release.
Closing...

**Comment by V7rgil** [comment]
Como puedo agregar la version wine-staging 10.7 a Heroic games laucher?. Solo veo que aparecen las verisiones que proporciona Heroic en su administrador de descarga de wine. Todas son Wine-Ge y no veo Wine-Staging :C . alguien me ayuda?
