### ISSUE TITLE
Heroic 2.5.1 does not show ARK Survival DLC's anymore

### ISSUE THREAD

**Issue by pzlingo** [Heroic-Games-Launcher/HeroicGamesLauncher#2162]
I tried "legendary list-games", DLC are showing up, but not if I open Heroic Games Launcher.
DLC's showed up until version 2.4.3.
![legendary](https://user-images.githubusercontent.com/3507181/206594904-a027bdff-b638-436d-a65f-e172e7d08c9c.png)

Some DLC's are obtained, but not installed yet.

Opensuse 15.3

Heroic 
![243](https://user-images.githubusercontent.com/3507181/206928331-8a7ccf01-0b3a-48d8-aeb3-12a871884215.png)
2.43

and 2.51
![251](https://user-images.githubusercontent.com/3507181/206928339-cf463290-038b-4ed7-b0ca-e83cb9a1a458.png)

**Comment by arielj** [comment]
Closing since heroic 2.8.0 has the new DLC manager, if this is still an issue we can reopen
