### ISSUE TITLE
When bulk adding games to steam, adding too many (while steam isnt running?) will cause steam to stop updating its index of games

### ISSUE THREAD

**Issue by lever1209** [Heroic-Games-Launcher/HeroicGamesLauncher#2164]
### Describe the bug

while i was adding my gog and epic games libraries to steam via the in app button, i added all of the installed games at once while steam was not running, and when i opened it, steam had only loaded a quarter of the games added, and after that point would never load any changes to the steam game index, non steam game or not, i had to delete my `~/.local/share/Steam` folder and try again buffering with 5-10 games per group, where i would open steam, add 5-10 games, close steam, reopen it, verify the games were added properly, add 5-10 more games, close steam and re open it, verify, etc etc

### Add logs

```text
https://cdn.discordapp.com/attachments/975775648050188368/1050633564179415130/heroic-2022-12-09T02_10_44.674Z.log

apologies for the file link via discord, but the log file made this post too big for github
```

### Steps to reproduce

1. close steam
2. add about 50 games to steam
3. open it
5. observe as steams game index gets borked

### Expected behavior

it should not be borked

### System Information

- arch linux
- heroic 2.5.1

### Additional information

apologies if thats the wrong log, i lost the original while i was testing it

also, there is probably not enough actual useful information here to make an accurate re creation of the bug, so its really just for my hopes that a dev here may have a hunch to what may be causing it

if more information is needed i can dive deeper into it

**Comment by lever1209** [comment]
maybe also add an option to back up the files that will be modified before any bulk actions take place?

**Comment by arielj** [comment]
I'm not sure there's any limitation. We just modify a file and append data, it's not that any application is running to limit what we add.

I'm going to close this for now. If this is still a problem we can reopen it.
