### ISSUE TITLE
Add customization options for discord rpc

### ISSUE THREAD

**Issue by lever1209** [Heroic-Games-Launcher/HeroicGamesLauncher#2177]
### Problem description

its kinda annoying that this is the only option for discord rpc
![image](https://user-images.githubusercontent.com/34011519/206884049-e64bca42-21c2-476e-8623-dae46cb3fad3.png)

### Feature description

the ability to customize it would be nice

### Alternatives

if not a fully featured in app customizer, then what about a user exposed js file that contains the code used for discord rpc

**Comment by lever1209** [comment]
if js/ts has anything like java reflection and interfaces it should be easy to do the alternative

**Comment by flavioislima** [comment]
Sorry but I don't see much value on that, I mean, it does not bring value to the launcher itself imo.

The discord api is too limited on our end so we cannot do much about it without putting  a lot of effort on that.
