### ISSUE TITLE
Managing installed.json

### ISSUE THREAD

**Issue by pragma-once** [Heroic-Games-Launcher/HeroicGamesLauncher#2186]
### Describe the bug

Checking out auto-save setting seems to interrupt installed.json (\<user\>/.config/legendary/installed.json) and even corrupt it sometimes (write an empty installed.json, losing all installed games' data). Also when importing the games back, I have to wait for the current import to be done, then do the next one. I guess queueing could help with all these, for importing games, installing/downloading, and auto-save checking seems to interrupt both.

### Add logs

```text
Lost them, but it said installed.json is corrupt because it was an empty file.
```

### Steps to reproduce

1. Install/Import a game.
2. check auto-save or import another game meanwhile.
3. installed.json is either empty now or something didn't install or import.

### Expected behavior

To import all the items and not to lost all installed games' data.

### System Information

- OS [e. g. "Ubuntu"]: Windows 11
- Heroic Version [e. g. 2.1.1]: 2.5.1

**Comment by pragma-once** [comment]
Apparently, stopping a download and choosing 'keep files' on its own without any other action may cause problems in installed.json causing all installed games to disappear. Keeping a backup of installed.json is handy for now (what I'm doing since last time it happened, helped get back all installed games without the hassle of importing them one by one).

**Comment by flavioislima** [comment]
I never experienced this for the last 2 years I am working on Heroic. It is possible? probably, but would need to be some race condition where heroic would cause different processes to write to installed.json.

Maybe if you import a game at the same time as a installation finishes. Still I could not reproduce this.

But you are right, perhaps we should add imports to the Queue as well.
