### ISSUE TITLE
Update issue | Wine / Proton can't be fetched

### ISSUE THREAD

**Issue by nPHYN1T3** [Heroic-Games-Launcher/HeroicGamesLauncher#2190]
### Describe the bug

Grabbed the appImage for my roommate and launched. Immediately given a pop up for a new version and an "update and restart" option. So Update and Restart...blam same pop up...cue never ending loop.

OK well ignore that since it's not working and just see if a game can be installed. UI is confusing with the run installer first bit. Kinda like having two buttons "Install" "Other Install" Why is there a differentiation here? However it complains the version of Wine selected is not installed. So go to the Wine/Proton bit and "Could not fetch Wine/Proton version this time."

### Add logs

```text
(22:44:50) INFO:    [Connection]:       Connectivity: check-online

(22:44:50) INFO:    [Connection]:       Pinging external endpoints

(22:44:50) INFO:    [Legendary]:        Running command: /tmp/.mount_Heroick7BzjN/resources/app.asar.unpacked/build/bin/linux/legendary --version

(22:44:50) INFO:    [Legendary]:        Legendary location: /tmp/.mount_Heroick7BzjN/resources/app.asar.unpacked/build/bin/linux/legendary

(22:44:50) INFO:    [Gog]:              GOGDL location: /tmp/.mount_Heroick7BzjN/resources/app.asar.unpacked/build/bin/linux/gogdl

(22:44:50) WARNING: [Backend]:          Failed to register protocol with OS.

(22:44:51) INFO:    [Gog]:              Running command: /tmp/.mount_Heroick7BzjN/resources/app.asar.unpacked/build/bin/linux/gogdl --version

(22:44:51) INFO:    [Connection]:       Connectivity: online

(22:44:51) INFO:    [Backend]:          User Not Found, removing it from Store

(22:44:51) INFO:    [Backend]:          AreWeAntiCheatYet data downloaded

(22:44:51) INFO:    [Backend]:          Checking for new Heroic Updates

(22:44:51) ERROR:   [Gog]:              Could not get game info for oyE9g8nsG9qxLYhwKKZFZ2, returning empty object. Something is probably gonna go wrong soon

(22:44:51) INFO:    [Backend]:          

Heroic Version: 2.5.0-beta.3 Caesar Clown

Legendary Version:  0.20.31 Dark Energy (hotfix #5)

GOGdl Version: 0.5

OS: Garuda KERNEL: 6.0.12-arch1-1 ARCH: x64

CPU: AMD Ryzen 7 5700G with Radeon Graphics @4.1 GOVERNOR: performance

RAM: Total: 31.24 GiB Available: 21.68 GiB

GRAPHICS: GPU0: NVIDIA GeForce GTX 1060 6GB VRAM: 6144MB DRIVER: 525.60.11 

PROTOCOL: x11]
```

### Steps to reproduce

1. Download appImage, mark executable and run
2. Note popup about update (at least at the time of this writing, cue why isn't the appImage the update version?)
3. Click on the Wine/Proton side menu
4. See message that basically says you can't do anything.

### Expected behavior

You'd expect the update to update and the Wine/Proton menu to list things to install, or what I really expected was a Lutris like install the best version of Wine for the game being installed rather than expecting the user to "just know" what version to install. At the very least you should be able to select and install things here but you can't.

### System Information

- Garuda Soaring
- Heroic Version 2.5.0-beta.3

**Comment by arielj** [comment]
@nPHYN1T3  Is this still an issue with Heroic 2.6.2?

**Comment by nPHYN1T3** [comment]
No clue, uninstalled...moved on.

**Comment by arielj** [comment]
ok, closing this then
