### ISSUE TITLE
Allow specifying custom executable in heroic's arguments when launching a game directly.

### ISSUE THREAD

**Issue by Kevadroz** [Heroic-Games-Launcher/HeroicGamesLauncher#2192]
### Problem description

Some games have multiple executables (a launcher and the game itself, multiple games in the case of a collection) and one may want to launch a different binary each time (specially with shortcuts).

While possible having to change the settings each time is annoying.

### Feature description

With a command of the likes of `<heroic-binary> heroic://launch/<game-id> --executable "/home/user/Games/Heroic/Game/tool.exe"` or whatever a game can be started using a specific executable for that one launch.

### Alternatives

#2039 offers a pretty good solution for the frontend.

**Comment by flavioislima** [comment]
You can use the option to Add Game to launch any exe, will work for several games. Or use the alternative exe option on the game settings.

**Comment by flavioislima** [comment]
So your need is too specific, it is really an edge case and we cannot support every possibility, would be crazy for us to make heroic launch basically anything on every configuration. I expect you understand.
