### ISSUE TITLE
a little "fix" for (app is damaged and can't be opened) on ARM macs.

### ISSUE THREAD

**Issue by ai-h24** [Heroic-Games-Launcher/HeroicGamesLauncher#2199]
the command provided in the release notes didn't work for me. 

but this command did:
`xattr -d com.apple.quarantine /Applications/Heroic.app`

and did try to install Heroic again to check which command did the job, or simply if both were needed. and turns out only the one above is needed. 
after using it once in terminal everything works as expected.

**Comment by flavioislima** [comment]
Thanks for the info, which OS version are you on?
It seems the command might be different and the one from the website is for an old version.

**Comment by ai-h24** [comment]
> Thanks for the info, which OS version are you on?
> It seems the command might be different and the one from the website is for an old version. 

tested it on both MacOS Ventura 13.1 and the new beta 13.2 both worked with that command above.

**Comment by flavioislima** [comment]
Cool. So no `sudo`  as well?

**Comment by ai-h24** [comment]
> Cool. So no `sudo` as well?

yes. no need for `sudo`. 
and the command works from MacOS Big Sur to the latest one Ventura (which are the only OS's that support ARM macs)

**Comment by flavioislima** [comment]
Thanks for the info, I updated the website and also the instructions on the release notes 👍🏽

**Comment by ai-h24** [comment]
> Thanks for the info, I updated the website and also the instructions on the release notes 👍🏽

thank you, but the website and the release notes both still show the old command.

**Comment by ai-h24** [comment]
hey again, that command didn't work either. so i was thinking ill find a way to fix for everyone. but after spending an hour or so trying to figure it out (look how many tries it took)

> ![oops](https://user-images.githubusercontent.com/117847131/208047393-1a413d90-c206-4ccb-a55f-9db72529c0b3.png)


well i just couldn't find a way. till after all these hours i was like you know let me try to just take the Original DMG file out of quarantine. by simply doing:

`xattr -d com.apple.quarantine /Downloads/Heroic-2.5.2-macOS-arm64.dmg` or you know wherever the dmg is located. 

and it worked perfectly. you can do it from ur side then upload it on here and everything will work fine without having the user to do any additional steps. 
its funny how simple it was to fix it. not funny how much time it took to find out tho.

**Comment by gummipunkt** [comment]
Hi,

when I try 
`xattr -d com.apple.quarantine /Downloads/Heroic-2.5.2-macOS-arm64.dmg`

the response is

`xattr: /Downloads/Heroic-2.5.2-macOS-arm64.dmg: No such xattr: com.apple.quarantine
`

**Comment by gummipunkt** [comment]
Ok solution was

Open DMG, move App to Applications and then

`xattr -d com.apple.quarantine /Applications/Heroic.app`

**Comment by ai-h24** [comment]
> Hi,
> 
> when I try `xattr -d com.apple.quarantine /Downloads/Heroic-2.5.2-macOS-arm64.dmg`
> 
> the response is
> 
> `xattr: /Downloads/Heroic-2.5.2-macOS-arm64.dmg: No such xattr: com.apple.quarantine `

i think you have to add the full path where the dmg file located. 
not just using **/Downloads/example.dmg** but something like /Users/**(your mac user)**/Downloads/example.dmg

or just type `xattr -d com.apple.quarantine` in terminal then drag and drop the dmg file wherever its located to the terminal window.

**Comment by ai-h24** [comment]
> `xattr -d com.apple.quarantine /Downloads/Heroic-2.5.2-macOS-arm64.dmg` or you know wherever the dmg is located.


@flavioislima hey, can this be implemented in Heroic dmg before it being uploaded to GitHub?
