### ISSUE TITLE
Cannot open "select executable" file chooser in "add game" dialog

### ISSUE THREAD

**Issue by jaragunde** [Heroic-Games-Launcher/HeroicGamesLauncher#2205]
### Describe the bug

Certain file chooser dialogs in the "add game" feature don't work. In particular, the "select executable" and "run installer first" ones.

### Add logs

```text
(16:55:40) INFO:    [Connection]:       Connectivity: check-online
(16:55:40) INFO:    [Connection]:       Pinging external endpoints
(16:55:40) INFO:    [Legendary]:        Running command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary --version
(16:55:40) INFO:    [Legendary]:        Legendary location: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary
(16:55:40) INFO:    [Gog]:              GOGDL location: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl
(16:55:40) WARNING: [Backend]:          Failed to register protocol with OS.
(16:55:40) INFO:    [Connection]:       Connectivity: online
(16:55:40) INFO:    [Gog]:              Getting data about the user
(16:55:40) INFO:    [Gog]:              Running command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --version
(16:55:41) INFO:    [Backend]:          AreWeAntiCheatYet data downloaded
(16:55:41) INFO:    [Backend]:          

Heroic Version: 2.5.2 Yamato
Legendary Version:  0.20.31 Dark Energy (hotfix #5)
GOGdl Version: 0.5
OS: Freedesktop SDK KERNEL: 5.13.0-valve21.3-1-neptune ARCH: x64
CPU: AMD Custom APU 0405 @2.27 GOVERNOR: schedutil
RAM: Total: 14.49 GiB Available: 12.67 GiB
GRAPHICS: GPU0: VanGogh [AMD Custom GPU 0405] VRAM: 512MB  
PROTOCOL: x11

(16:55:41) INFO:    [Gog]:              Saved user data to config
(16:55:41) INFO:    [Backend]:          Checking for current version changelog
(16:55:41) INFO:    [Frontend]:         Refreshing Library
(16:55:41) INFO:    [Legendary]:        Refreshing library...
(16:55:41) INFO:    [Legendary]:        Refreshing Epic Games...
(16:55:41) INFO:    [Legendary]:        Game list updated, got 50 games & DLCs
(16:55:41) INFO:    [Gog]:              Getting GOG library
(16:55:41) INFO:    [Backend]:          Frontend Ready
(16:55:42) INFO:    [Gog]:              Number of library pages: 1
(16:55:42) INFO:    [Legendary]:        Running command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary list --third-party
(16:55:42) INFO:    [Gog]:              Saved games data
(16:55:43) INFO:    [Winetricks]:       Downloading Winetricks
(16:55:46) INFO:    [Backend]:          Starting the Download Queue
(16:56:38) INFO:    [Connection]:       Connectivity: offline
(16:56:39) INFO:    [Connection]:       Connectivity: check-online
(16:56:39) INFO:    [Connection]:       Pinging external endpoints
(16:56:39) INFO:    [Connection]:       Connectivity: online
(16:57:25) INFO:    [Connection]:       Connectivity: offline
(16:57:26) INFO:    [Connection]:       Connectivity: check-online
(16:57:26) INFO:    [Connection]:       Pinging external endpoints
(16:57:27) INFO:    [Connection]:       Connectivity: online
(16:57:39) INFO:    [Connection]:       Connectivity: offline
(16:57:41) INFO:    [Connection]:       Connectivity: check-online
(16:57:41) INFO:    [Connection]:       Pinging external endpoints
(16:57:41) INFO:    [Connection]:       Connectivity: online
(16:58:50) INFO:    [Connection]:       Connectivity: offline
(16:58:51) INFO:    [Connection]:       Connectivity: check-online
(16:58:51) INFO:    [Connection]:       Pinging external endpoints
(16:59:02) INFO:    [Connection]:       All ping requests failed:
(16:59:02) INFO:    [Connection]:       AggregateError: All promises were rejected
(16:59:02) INFO:    [Connection]:       Connectivity: offline
(16:59:03) INFO:    [Connection]:       Connectivity: check-online
(16:59:03) INFO:    [Connection]:       Pinging external endpoints
(16:59:13) INFO:    [Connection]:       All ping requests failed:
(16:59:13) INFO:    [Connection]:       AggregateError: All promises were rejected
(16:59:18) INFO:    [Connection]:       Pinging external endpoints
(16:59:18) INFO:    [Connection]:       Connectivity: online
(16:59:24) INFO:    [Connection]:       Connectivity: offline
(16:59:25) INFO:    [Connection]:       Connectivity: check-online
(16:59:25) INFO:    [Connection]:       Pinging external endpoints
(16:59:31) INFO:    [Connection]:       Connectivity: online
(17:00:01) INFO:    [Connection]:       Connectivity: offline
(17:00:02) INFO:    [Connection]:       Connectivity: check-online
(17:00:02) INFO:    [Connection]:       Pinging external endpoints
(17:00:06) INFO:    [Connection]:       Connectivity: offline
(17:00:06) INFO:    [Connection]:       All ping requests failed:
(17:00:06) INFO:    [Connection]:       AggregateError: All promises were rejected
(17:00:08) INFO:    [Connection]:       Connectivity: check-online
(17:00:08) INFO:    [Connection]:       Pinging external endpoints
(17:00:11) INFO:    [Connection]:       Pinging external endpoints
(17:00:13) INFO:    [Connection]:       Connectivity: online
(17:00:18) INFO:    [Connection]:       All ping requests failed:
(17:00:18) INFO:    [Connection]:       AggregateError: All promises were rejected
(17:00:23) INFO:    [Connection]:       Pinging external endpoints
(17:00:23) INFO:    [Connection]:       Connectivity: online
```

### Steps to reproduce

1. Click "Add game"
2. On Select executable -> click the folder icon
2. Alternatively, clicking "run installer first" has the same effect.

### Expected behavior

A file chooser dialog appears.

### System Information

- OS [e. g. "Ubuntu"]: Steam OS (beta channel) on Steam Deck
- Heroic Version [e. g. 2.1.1]: 2.5.2

### Additional information

* If ran from the command line, the following error message appears when clicking on the folder icon: 
```
[3:1215/165615.887202:ERROR:browser_main_loop.cc(269)] Gtk: gtk_file_chooser_widget_set_current_name: assertion 'priv->action == GTK_FILE_CHOOSER_ACTION_SAVE || priv->action == GTK_FILE_CHOOSER_ACTION_CREATE_FOLDER' failed
 
(heroic:3): Gtk-WARNING **: 16:56:15.891: Can't open portal file chooser: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such interface “org.freedesktop.portal.FileChooser” on object at path /org/freedesktop/portal/desktop
```
* Other dialogs do work, for example, the "WinePrefix" dialog.
* I've seen videos of the feature running, and I noticed they produce *KDE* dialogs, while my install produces GTK dialogs. I did not customize my Steam OS install other than installing a few Flatpaks :shru

**Comment by flavioislima** [comment]
Works fine here:
![image](https://user-images.githubusercontent.com/26871415/207932961-e453c204-6d11-4da6-b67c-0eb46e6a145f.png)


SteamOS as well, are you on desktop or gaming mode? it will only work on desktop mode.

**Comment by danielpragai** [comment]
Having the same issue on desktop mode, basic install, with stable steamos branch.

**Comment by danielpragai** [comment]
Just found a solution for myself!

The steam gaming mode language was not english. After changing it back the window appears as it should

**Comment by jaragunde** [comment]
Thanks for writing back! I forgot to mention this happens in desktop mode.

To find out if there's something wrong when running on GTK/GNOME, I ran Heroic on my Fedora 37 laptop with GNOME 43.2 desktop. I don't have the same error there, the dialog opens and it's a GTK dialog, although one of the error messages still shows up in the command line:
```
[3:1216/093229.593843:ERROR:browser_main_loop.cc(269)] Gtk: gtk_file_chooser_widget_set_current_name: assertion 'priv->action == GTK_FILE_CHOOSER_ACTION_SAVE || priv->action == GTK_FILE_CHOOSER_ACTION_CREATE_FOLDER' failed
```

I still wonder why I'm getting GTK dialogs on the Deck, I'll look into it.

@danielpragai did changing the language in gaming mode affect Heroic running on desktop mode? I have a mismatch there, gaming mode is in Spanish but desktop mode is in English down to the keyboard layout. I didn't bother to fix it... :innocent:

**Comment by flavioislima** [comment]
@jaragunde @danielpragai I had issues with Steam deck on another language than English as well, not only with heroic, but even the terminal complains about it.

Heroic does not use GTK or KDE on flatpak, it uses the freedesktop runtime so should have no issues with any DE. It is probably some misconfiguration on the deck side.

**Comment by varpness** [comment]
I'm running English language and have the same issue in Desktop mode.

**Comment by jaragunde** [comment]
I cannot reproduce this problem any more, I think this could have been fixed with the SteamOS 3.4 update. Thanks for taking a look!

**Comment by Cappellohack** [comment]
I have the same problem.

OS: Endeavour OS - Kernel: 6.7.5
Flatpak v2.13.0

**Comment by Milor123** [comment]
I have the same problem, I am in  manjaro and it only open 1 instance, cant open other instance while a game is running, how can i run pararellel instances in the same wineprefix?

**Comment by arielj** [comment]
> I have the same problem, I am in manjaro and it only open 1 instance, cant open other instance while a game is running, how can i run pararellel instances in the same wineprefix?

your issue seems unrelated to what was reported here

because if how wineserver works you can't run another application in a prefix when one is already running

what you can do is write a small bash script to launch 2 applications in parallel, something similar to what's explained in this discord thread https://discord.com/channels/812703221789097985/1210747284086849578/1210747284086849578

**Comment by Milor123** [comment]
> > I have the same problem, I am in manjaro and it only open 1 instance, cant open other instance while a game is running, how can i run pararellel instances in the same wineprefix?
> 
> your issue seems unrelated to what was reported here
> 
> because if how wineserver works you can't run another application in a prefix when one is already running
> 
> what you can do is write a small bash script to launch 2 applications in parallel, something similar to what's explained in this discord thread https://discord.com/channels/812703221789097985/1210747284086849578/1210747284086849578

A solution with little accessibility for the normal user, I will try it, but why so complicated? In most other launchers I can easily run another file without being locked. Is it really important to keep that lock?

**Comment by arielj** [comment]
> A solution with little accessibility for the normal user, I will try it, but why so complicated? In most other launchers I can easily run another file without being locked. Is it really important to keep that lock?

I honestly don't know, it's been like that since before I joined the project, currently the only way I know to run 2 processes in the same wineprefix in parallel is that

**Comment by Milor123** [comment]
> > A solution with little accessibility for the normal user, I will try it, but why so complicated? In most other launchers I can easily run another file without being locked. Is it really important to keep that lock?
> 
> I honestly don't know, it's been like that since before I joined the project, currently the only way I know to run 2 processes in the same wineprefix in parallel is that

In Heroic this function does not work correctly, in theory, the second process will stay waiting for the first process to close, which works for the installers, but it does not work correctly as a parallel, something prevents two processes to run at the same time, for this reason it is an incomplete function, because for many games we need to open several processes, either to modify them, connect them online or other functions, I tried many ways using the GUI that were easy to allow me to run the two processes in parallel, but I did not get it, I had to go to use another launcher because it gave me despair.

And the idea of a GUI, is to make complicated technical things easier for the user, especially nowadays that more and more new users are coming to linux who have very basic knowledge.
