### ISSUE TITLE
mangohud is enabled, but `mangohud` executable could not be found on $path

### ISSUE THREAD

**Issue by kentgr** [Heroic-Games-Launcher/HeroicGamesLauncher#2218]
### Describe the bug

After ticking the mangohud box i cant run any game on Linux and get the error (I am in Arch Linux using Flatpak version of 
HeroicGamesLauncher)
mangohud is enabled, but `mangohud` executable could not be found on $path

### Add logs

```text
mangohud is enabled, but `mangohud` executable could not be found on $path
```

### Steps to reproduce

1. Go to Game
2. Click on Preferences 
3. Scroll down to mangohud

### Expected behavior

It should launch 

### System Information

- OS Arch Linux 
- Heroic Version 2.5.2

### Additional information

mangohud works with Steam and Lutris

**Comment by arpan20032009** [comment]
i think your mangohud is not added to the path variable

**Comment by kentgr** [comment]
Ok, it's strange because I can just write mangohud in Bash terminal, and it comes up. Am I missing something here?

**Comment by kentgr** [comment]
Also it works with no issue in Lutris and Steam

**Comment by Nocccer** [comment]
On heroic flatpak only mangohud flatpak should work ootb. For all other mangohuds you need to set the correct flatpak permissions. Maybe someone can tell you what permissions are needed

**Comment by flavioislima** [comment]
This is documented on our wiki:
https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/wiki/SteamDeck---Flatpak#mangohud-doesnt-work

**Comment by LiamDawe** [comment]
Sorry to dig this back up, but I believe I have everything set but Heroic still claims the same.

![Screenshot_20230712_171820](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/assets/83223/083005a8-6066-4397-82a0-72d5a112d056)

MangoHUD flatpak is installed as well, but still get the same error when ticking the MangoHud box.

**Comment by M4st0d0n** [comment]
> Sorry to dig this back up, but I believe I have everything set but Heroic still claims the same.
> 
> MangoHUD flatpak is installed as well, but still get the same error when ticking the MangoHud box.

Had the issue recently and found Flatpak (with the command shown on MangoHUD's Github) had installed the files in :

~/.local/share/flatpak/runtime/flatpak/runtime/org.freedesktop.Platform.VulkanLayer.MangoHud

Which I then added as additionnal path for Heroic via FlatSeal, and then MangoHUD shows ingame.

**Comment by NickyMeuleman** [comment]
> Flatpak (with the command shown on MangoHUD's Github) had installed the files in :
> 
> ~/.local/share/flatpak/runtime/org.freedesktop.Platform.VulkanLayer.MangoHud

Thanks for this, it didn't work for me but pointed me in the right direction.

I added to the PATH for the flatpak of the Heroic Games Launcher
I added the directory to the binary for the flatpak of Mangohud directly.
In my case that was `/var/lib/flatpak/runtime/org.freedesktop.Platform.VulkanLayer.MangoHud/x86_64/21.08/active/files/bin`, newer version (22, or 23) did not seem to work for me. No idea why, but it works and I'm not bothered to find out why.

Then ticking the box within Heroic Games > specific game > settings > other > use Mangohud
worked and used my modified mangohud settings correctly

**Comment by Nocccer** [comment]
This problem is not yet in thr stable version for detecting mangohud under steam.
Steam throws an error and in the current stable version we expect that mangohud does not work if a error is thrown. This will be fixed with the next release version

**Comment by THEGAMER16** [comment]
> > Flatpak (with the command shown on MangoHUD's Github) had installed the files in :
> > ~/.local/share/flatpak/runtime/org.freedesktop.Platform.VulkanLayer.MangoHud
> 
> Thanks for this, it didn't work for me but pointed me in the right direction.
> 
> I added to the PATH for the flatpak of the Heroic Games Launcher
> 
> I added the directory to the binary for the flatpak of Mangohud directly. In my case that was `/var/lib/flatpak/runtime/org.freedesktop.Platform.VulkanLayer.MangoHud/x86_64/21.08/active/files/bin`, newer version (22, or 23) did not seem to work for me. No idea why, but it works and I'm not bothered to find out why.
> 
> Then ticking the box within Heroic Games > specific game > settings > other > use Mangohud worked and used my modified mangohud settings correctly

How do I add the PATH?

**Comment by regs01** [comment]
You don't need to. You need to to install MangoHud from Flathub by running:
```
flatpak install mangohud
```

For current Heroic Launcher install version org.freedesktop.Platform.VulkanLayer.MangoHud 23.08

To customize make `MangoHud` folder in `~/.config` and place `MangoHud.conf` there.

Then run once
```
flatpak override --user --filesystem=xdg-config/MangoHud:ro
```

And tick checkbox in game settings in Heroic Launcher.

**Comment by THEGAMER16** [comment]
> You don't need to. You need to to install MangoHud from Flathub by running:
> 
> ```
> flatpak install mangohud
> ```
> 
> For current Heroic Launcher install version org.freedesktop.Platform.VulkanLayer.MangoHud 23.08
> 
> To customize make `MangoHud` folder in `~/.config` and place `MangoHud.conf` there.
> 
> Then run once
> 
> ```
> flatpak override --user --filesystem=xdg-config/MangoHud:ro
> ```
> 
> And tick checkbox in game settings in Heroic Launcher.

Yes, I found this on Reddit a while ago. Thank you for reply though.

**Comment by CavaleriOmar** [comment]
I'm in this situation, but I can't get heroic launcher to “see” mangohud at all.

I have already tried the above, but nothing

**Comment by regs01** [comment]
> I'm in this situation, but I can't get heroic launcher to “see” mangohud at all.
> 
> I have already tried the above, but nothing

You need `org.freedesktop.Platform.VulkanLayer.MangoHud 24.08` nowadays

**Comment by frecio231** [comment]
I've downloaded Mangohud, this is my `$PATH` on the flatpak 
`PATH=/app/bin:/app/utils/bin:/usr/bin:/usr/lib/extensions/vulkan/MangoHud/bin:/usr/lib/extensions/vulkan/gamescope/bin:/usr/lib/extensions/vulkan/OBSVkCapture/bin:/app/bin/heroic/resources/app.asar.unpacked/build/bin/linux:/var/lib/flatpak/runtime/org.freedesktop.Platform.VulkanLayer.MangoHud/x86_64/24.08/active/files/bin`

And this is my `flatpak list` result  showing the version I installed is 24.08
`MangoHud org.freedesktop.Platform.VulkanLayer.MangoHud 0.7.2 24.08 system` and still get the error 
`Mangohud is enabled, but mangohud executable could not be found on $PATH`

**Comment by yuwon6881** [comment]
> I'm in this situation, but I can't get heroic launcher to “see” mangohud at all.
> 
> I have already tried the above, but nothing

I am facing this issue as well, my solution is to use lutris instead of heroic launcher, the mangohud just works in lutris

**Comment by NickyMeuleman** [comment]
Ran into this again today.
Is the required version documented somewhere?
I had the flatpak installed like [the docs suggest](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/wiki/Steam-Deck#mangohud-does-not-work) but it did not work.

I had version 24 installed.
After I downgraded to version 23 it started working.

**Comment by Suero152** [comment]
> Ran into this again today. Is the required version documented somewhere? I had the flatpak installed like [the docs suggest](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/wiki/Steam-Deck#mangohud-does-not-work) but it did not work.
> 
> I had version 24 installed. After I downgraded to version 23 it started working.

Downgrading to version 23 is the key.

**Comment by kwiniarski97** [comment]
Is there some solution to not do it? I am using also bottles which in turn require Mangohud 24

**Comment by Lukasxtrix88** [comment]
MangoHUD version 23 is the key 🚬

**Comment by AttiZK** [comment]
> the url changed https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/wiki/Steam-Deck#mangohud-does-not-work

Thanks, I was able to initialize mangohud inside a game shortly after I posted, I just simply forgot to relaunch Heroic after installing mangohud 24.
