### ISSUE TITLE
Visible url and/or `copy to clipoard` for the Alternative Login url

### ISSUE THREAD

**Issue by arielj** [Heroic-Games-Launcher/HeroicGamesLauncher#2245]
### Problem description

For the alternative login, we have a button to open the login page in an external browser, if, for any reason, that opening fails, users have no way of knowing which url they have to use.

### Feature description

A footnote in the alt login dialog that shows the url that should be opened in a browser and a button to `copy to clipboard` so users can click and paste in a browser.

**Comment by kshitijsubedi** [comment]
Would love to work on this.

**Comment by arielj** [comment]
There's no UI reference, you can try something and share it here and receive feedback
