### ISSUE TITLE
UI Consistency on Library between Windows/Linux 

### ISSUE THREAD

**Issue by dtantono** [Heroic-Games-Launcher/HeroicGamesLauncher#2250]
### Problem description

When I turn on the recently played games on the settings tab, I noticed stark differences between Windows/Linux versions. While, the Linux version is much sleeker and cleaner. But, the Windows version is messier. 

### Feature description

I think there should be UI consistency between those Windows/Linux version. 

### Additional information

Windows 10 22h2 Heroic 2.5.2 hotfix 2 exe file looks messy to find recently played games

[2022-12-24 10-04-00.mp4.zip](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/files/10297822/2022-12-24.10-04-00.mp4.zip)

Ubuntu 22.04 Heroic 2.5.2 .deb looks cleaner and sleeker
https://user-images.githubusercontent.com/29157187/209416870-0383a81f-c678-46a5-96b7-0e2bcbfbcd8d.mp4

**Comment by arielj** [comment]
hmmmm looks like the windows version is not respecting the limit of recently played games there

**Comment by flavioislima** [comment]
@dtantono perhaps try to change the limit of recent games on windows, then get back. This is a known bug that was fixed and will be on the next release.

**Comment by dtantono** [comment]
![image](https://user-images.githubusercontent.com/29157187/209453365-6d81869c-4143-4db6-b390-328d0aa35c0a.png)

that workaround works for windows atm. But, it will be great if we don't have to tamper this setting when our playtime grows.
