### ISSUE TITLE
Game shows up as installed when uninstalling while another game is being installed

### ISSUE THREAD

**Issue by arielj** [Heroic-Games-Launcher/HeroicGamesLauncher#2258]
### Describe the bug

When a game is uninstalled while another game is being installed, when the game finishes installing the game that was just uninstalled is back again in the list as installed.

### Add logs

```text
There's nothing relevant in the logs BUT I was checking `~/.config/legendary/installed.json` and I can see the first game gets removed from the list of installed games and then it's added again when the second game finishes.
```

### Steps to reproduce

1. Start installing 2 games (one will be in the queue)
2. After the first game finishes installing, wait for the next to start
3. Uninstall the first game
4. After the second game finishes installing, the first game (that was just uninstalled) is back in the list as installed

### Expected behavior

The game I just uninstalled should not reappear as installed (it is not really installed)

### Heroic Version

Latest Stable

### System Information

- OS [e. g. "Ubuntu"]: Not relevant

### Additional information

I think this might be a bug in Legendary and not in Heroic.

**Comment by flavioislima** [comment]
I think we need to add the uninstall method to the queue as well. So we could avoid that.

This is happening only with epic games, right?

Or we could also handle the installed games internally and sync with legendary when the refreshing the library.

**Comment by arielj** [comment]
Closing this, I did the same steps just with legendary directly and the issue is still present, so I added a bug report in legendary's repo instead https://github.com/derrod/legendary/issues/544
