### ISSUE TITLE
Option to disable(or hide) HowLongToBeat info.

### ISSUE THREAD

**Issue by paparoxo360** [Heroic-Games-Launcher/HeroicGamesLauncher#2259]
**Problem description**

I really enjoy the option to see the game's length, it's indeed a good option to have. But it's not everyone that like to know how long a game will last, I really enjoy the surprise to play a game, without knowing anything about it, like how long it will take to finish it, 

**Feature description**

I think would be nice an option to disable this feature or hide it behind a button on the game page, and thanks for the amazing work.

**Comment by vijfhoek** [comment]
Or perhaps hide it behind a button on the game page, kind of like a spoiler alert

**Comment by paparoxo360** [comment]
> Or perhaps hide it behind a button on the game page, kind of like a spoiler alert

I agree, this is even better.( I even updated my post, with what your suggestion).

**Comment by arielj** [comment]
this was done in the latest releases (the option is under the Extra info option in the game page menu and also hidden inside that dialog)
