### ISSUE TITLE
Download speed limit option

### ISSUE THREAD

**Issue by Furrior** [Heroic-Games-Launcher/HeroicGamesLauncher#2263]
### Problem description

Both Epic Store and GOG have an option to cap maximum download speed. I guess Heroic should have it too.

### Feature description

A thing in options to cap download speed and to choose how high it is.

**Comment by arielj** [comment]
We need Legendary and GOGdl to support download speed limit, we don't handle the actual download of the files in Heroic (we call those tools to download games).

**Comment by DocBretti** [comment]
So this is up to gog...okay over there should be a request for this, will look it up.

**Comment by imLinguin** [comment]
It's up to us, what arielj meant was it's up to tools we use under the hood 
Please don't bother GOG about unofficial software
https://github.com/derrod/legendary  
https://github.com/Heroic-Games-Launcher/heroic-gogdl

**Comment by arielj** [comment]
I said `GOGdl`, not `GOG`

**Comment by DocBretti** [comment]
Ah ok, sorry, my fault. :-)

**Comment by tripplehelix** [comment]
> it's still not a thing right

Doesn't look like it, I would also love this.
