### ISSUE TITLE
GOG games shows up as not available after installation

### ISSUE THREAD

**Issue by arielj** [Heroic-Games-Launcher/HeroicGamesLauncher#2283]
### Describe the bug

Sometimes, after a GOG game is installed, it shows up in the list as not available even though it was just installed.

For example, I just installed these 3 games:
![image](https://user-images.githubusercontent.com/188464/210012131-ad4926b4-db93-4181-b775-d25046506711.png)

Both GOG games show up as not available, the Epic one is fine.

### Add logs

```text
Nothing relevant on logs, just the normal installation logs (progress, shortcuts, etc)
```

### Steps to reproduce

1. Put a few GOG games in the queue
2. Stay in the Library screen while the games are being installed
3. At some point, a game that was just installed will show up as not available
4. Go to another screen and back to Library and the status is correct

### Expected behavior

A game that was just installed should not show up as not available. And I shouldn't have to change screens to get the status updated.

### Heroic Version

Latest Stable

### System Information

Not relevant

**Comment by Ulugbeg** [comment]
I'm experiencing this too. 

Fresh install on arch linux, using the latest pre-compiled binary (hotfix 2)

For me the behavior is that the download seems to succeed, after which I do _not_ find the game in the expected directory - the ~/Games/Heroic folder does not contain the expected directory containing the game.

For me, this was the case with both Stardew Valley and Another World 20th anniversary edition. 

I tried these 2 GOG games, have not tried any others. 

I did try 1 Epic Store game, which worked just fine.

I did not try any games besides those.

The only option to remove them from the list of installed games was to remove them from the `.config/heroic/gog_store/installed.json` file. 

Trying to install them again after doing that results in no visual download, but the game does get moved from 'download' to 'completed'  (without downloading anything), but stil without a game showing up in ~/Games/Heroic (but with a non-working entry in the list of 'installed' games.

**Comment by SleepyCyb** [comment]
Also got that on my Steam Deck. However, for me, GoG games were working and it would download to the proper location.

But, just today, the folder I created at the root of my sd card for my GoG games just... vanished. The folder was nowhere to be found and so my game would not launch or uninstall. (Tried to find the config file like mentionned above, could not find it)

I can see two things that could have caused that : 

1- I logged-out of my GoG account and then re-logged (same account) I don't know if logging out can mess the library up somehow

2- I installed a system update for my Steam Deck

I ended up uninstalling and reinstalling Heroic to get rid of the "Game not available" games.

**Comment by arielj** [comment]
I think this got fixed in the latest releases

@Ulugbeg can you confirm this with Heroic 2.6.2?

**Comment by arielj** [comment]
I haven't since this problem since the 2.6.2 release, I'm closing this

**Comment by CheeseBiscuits** [comment]
With no solution in sight, I nuked heroic altogether. 

Uninstalling games would remove them from library but would not free up storage. Now I have over 50gb of "other" crap that's nowhere to be found even with useless diak analyzer.

From  now on I'm only getting games on steam.

**Comment by Subtly-Dismiss** [comment]
> With no solution in sight, I nuked heroic altogether.
> 
> Uninstalling games would remove them from library but would not free up storage. Now I have over 50gb of "other" crap that's nowhere to be found even with useless diak analyzer.
> 
> From now on I'm only getting games on steam.


I've just stumbled across this whilst searching for a related issue. To anybody else who is reading this comment, please don't pay any attention to it. The benefit of games from GOG or similar is that they are yours, forever, whereas on Steam you are legally a subscriber to your own games. Don't get me wrong, Steam offers some good functionality, but in the age of nothing-is-yours and the subscription model, we need to take a stand. 

You can effortlessly find where large data is stored on Linux, Windows, and macOS. There are tools built into the OS and there are a thousand off-the-shelf apps to do just this.

**Comment by PVautour** [comment]
Left clicking the game to have the single game view and using the `verify and repair` option in the three dot menu seems to fix the game for me :)
