### ISSUE TITLE
[Documentation] Incorrect winget installation command for windows 

### ISSUE THREAD

**Issue by Cem-Kaya** [Heroic-Games-Launcher/HeroicGamesLauncher#2289]
### Describe the bug

The given installation command for winget does not work. 
The working one is :   winget install Heroic

### Add logs

```text
Na
```

### Steps to reproduce

1. Open terminal on windows 
2. type "winget install HeroicGamesLauncher.HeroicGamesLauncher"

### Expected behavior

the commend should install the package 

### Screenshots

![image](https://user-images.githubusercontent.com/48164025/210068851-8a4d63fd-c3c9-4247-9078-7d422a2bcabb.png)

correct commend:
![image](https://user-images.githubusercontent.com/48164025/210068817-4e3a9fde-e3a7-4d2e-99b1-92b4ac87f42c.png)

### Heroic Version

Latest Stable

### System Information

- OS windows 11 2022h2

**Comment by flavioislima** [comment]
Hmm, not sure how we come to that, will fix.
