### ISSUE TITLE
Mac default wine settings are broken

### ISSUE THREAD

**Issue by nonoche2** [Heroic-Games-Launcher/HeroicGamesLauncher#2296]
### Describe the bug

the last update (2.5.2) has changed the default wine settings on Mac : while it still shows Crossover as selected, it asks for a wine prefix file path (which should be replaced by the crossover prefix which is a string and not a file path), and shows an error alert when trying to launch a game

Switching the "Crossover version" to Wine 7 stable (which I had installed) and back to crossover fixes the issue and replaces the wine prefix field with the crossover prefix (with its previous correct setting) and allowed me to play games again

### Add logs

```text
no log available sorry once I fixed the issue I couldn't reproduce it
```

### Steps to reproduce

1. on macOS, install a windows game from EGS and launch it
2. error, game won't launch
3. look in default game settings and notice that the default Crossover prefix has been replaced by Wine prefix

### Expected behavior

default crossover prefix shouldn't be switched to wine prefix

### Heroic Version

Latest Stable

### System Information

- macOS Ventura 13.1

**Comment by flavioislima** [comment]
Yes, since we have added support for Wine on the latest releases, you might need to go to the game settings and select and deselect crossover. Maybe there is a way to make crossover default again, will check.

**Comment by nonoche2** [comment]
maybe make Heroic default to Crossover if there's a stored prefix that doesn't contain a slash character?

**Comment by nonoche2** [comment]
actually crossover is still default, it's the prefix setting that isn't restored properly
