### ISSUE TITLE
on Mac use Codeweaver's compatibility database to display game compatibility

### ISSUE THREAD

**Issue by nonoche2** [Heroic-Games-Launcher/HeroicGamesLauncher#2297]
### Problem description

on Mac the "check compatibility" option opens a page to ProtonDB which isn't very useful for Mac users, could you switch to Codeweaver's database for Mac users please?

### Feature description

ideally showing the compatibility stars right on the game thumbnail in the library, and replace the link to ProtonDB with a link to Codeweaver's compatibility page

### Alternatives

letting us add notes for each game (such as preferred settings to make them work) would also be a nice plus

**Comment by Nocccer** [comment]
Does codeweaver have a api that works with steam app ids or do they have redirects with steam app ids ?

**Comment by nonoche2** [comment]
that's a good question, I'll ask around and will let you know

**Comment by flavioislima** [comment]
I was thinking in actually using AppleGamingWiki for that.
@Nocccer they use the same API as PCGamingWiki, I think it is the from the same guy, so maybe we could query the compatibility from there or at least open the game page there:
https://www.applegamingwiki.com/wiki/Home

**Comment by Nocccer** [comment]
Yes has same Api, but i can't search for gog ids. Only for titles.
I started a new branch where i already added the backend. I want to combine howlongtobeat, pcgamingwiki and applewiki into one ipc call and also export only one type.

**Comment by flavioislima** [comment]
> Yes has same Api, but i can't search for gog ids. Only for titles.
> I started a new branch where i already added the backend. I want to combine howlongtobeat, pcgamingwiki and applewiki into one ipc call and also export only one type.

Cool. Let me know when you need some testing.
