### ISSUE TITLE
Translations cannot be synced from Hosted Weblate

### ISSUE THREAD

**Issue by totoroot** [Heroic-Games-Launcher/HeroicGamesLauncher#2302]
### Describe the bug

Four days ago the translations from https://hosted.weblate.org/projects/heroic-games-launcher stopped being synced, apparently due to issues with the project's Git history. I cannot tell what caused this, but thought I'd let you know in case you didn't notice.

### Add logs

```text
N/A
```

### Steps to reproduce

1. Open the [project's translation page on Hosted Weblate](https://hosted.weblate.org/projects/heroic-games-launcher).
2. Try adding translations for the project.
3. Check header

![image](https://user-images.githubusercontent.com/39650930/210330132-b0b0f21a-12a9-425c-b89d-c08a1feac9bf.png)

4. Click on [Could not push the repository.](https://hosted.weblate.org/projects/heroic-games-launcher/gamepage/#alerts) to get to alert description.

### Expected behavior

N/A

### Screenshots

![image](https://user-images.githubusercontent.com/39650930/210329226-dd6c7942-91bc-4bda-9391-7a3cebf599c0.png)

### Heroic Version

main branch from GitHub

### System Information

N/A

**Comment by flavioislima** [comment]
Yes, this happens from time to time due to conflicts. I will fix it during the week.

**Comment by arielj** [comment]
hey @flavioislima , was this fixed? not sure how to check

**Comment by flavioislima** [comment]
Yes, fixed.
