### ISSUE TITLE
Heroic fails to uninstall a game that is not available

### ISSUE THREAD

**Issue by arielj** [Heroic-Games-Launcher/HeroicGamesLauncher#2303]
### Describe the bug

If you have a game that is not available, if you try to uninstall it heroic fails and the game is not removed from the list.

This is a problem, because if, for any reason, you have a game on an SD card and it stops working, you can't remove the game from the list.

### Add logs

```text
(10:34:48) INFO:    [Gog]:              Removing /home/ariel/Games/Heroic/Wasteland 2 Director's Cut
(10:34:48) ERROR:   [Backend]:          Error: ENOENT: no such file or directory, stat '/home/ariel/Games/Heroic/Wasteland 2 Director's Cut'
    at statSync (node:fs:1551:3)
    at e.statSync (node:electron/js2c/asar_bundle:5:4535)
    at __node_internal_ (node:internal/fs/utils:799:8)
    at Object.rmSync (node:fs:1226:13)
    at _GOGGame.uninstall (/home/ariel/dev/oss/HeroicGamesLauncher/build/electron/main.1f638763.js:4333:18)
    at /home/ariel/dev/oss/HeroicGamesLauncher/build/electron/main.1f638763.js:13483:18
    at node:electron/js2c/browser_init:193:567
    at EventEmitter.<anonymous> (node:electron/js2c/browser_init:165:11606)
    at EventEmitter.emit (node:events:527:28)
```

### Steps to reproduce

1. Install a game
2. Delete the game from the disk manually
3. Make sure Heroic shows the game as not available
4. Try to uninstall the game

### Expected behavior

The game should be removed from the library.

### Heroic Version

Latest Stable

### System Information

- OS [e. g. "Ubuntu"]: Mint

### Additional information

If you try to play the game, it asks you if you want to remove it from the list so there's a workaround, but it's not obvious for users.

**Comment by flavioislima** [comment]
For me it works fine for epic games, is this gog only maybe?
