### ISSUE TITLE
In Flatpak version of Heroic Games Launcher, some games may not work if file system access is blocked

### ISSUE THREAD

**Issue by dariox86** [Heroic-Games-Launcher/HeroicGamesLauncher#2307]
### Describe the bug

The only proprietary class of applications I run on my system are video games and I want them to run in a confined environment. While Heroic Games Launcher is packaged for my operating system, the rationale for using the Flatpak version boils down to the sandboxing capabilities offered by Bubblewrap. Upon installing the application through Flathub, I issue the following command to block file system access:
`flatpak --user override --nofilesystem=host:reset com.heroicgameslauncher.hgl`
_The Vanishing of Ethan Carter_ is one such game affected by this command. This game saves progress and settings in _%USERPROFILE%\Documents\My Games\The Vanishing of Ethan Carter_, but _%USERPROFILE%\Documents_ points to the actual _Documents_ folder on the host system outside the sandboxed environment. If file system access is blocked, all progress and settings are lost upon closing Heroic Games Launcher. This issue only happens with prefixes created with Wine-GE. When using Proton-GE, _%USERPROFILE%\Documents_ is not a symlink to the _Documents_ folder, it is just a regular folder confined to the sandbox.
Please note that this is just one occurrence of an actual issue I had upon restricting access to the sanboxed application. I have seen other folders in the prefixes symlinked to actual folders on the host system that will cause issues with enforced file system permissions.

### Add logs

```text
I think this is not needed as the issue is pretty well explained.
```

### Steps to reproduce

1. Install Flatpak on the host system.
2. $ flatpak --user remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
3. $ flatpak --user install flathub com.heroicgameslauncher.hgl
4. $ flatpak --user override --nofilesystem=host:reset com.heroicgameslauncher.hgl
5. Launch Heroic Games Launcher.
6. Launch _The Vanishing of Ethan Carter_ with Wine-GE.
7. Customize some settings in the game.
8. Close the game.
9. Close Heroic Games Launcher.
10. Open Heroic Games Launcher.
11. Launch _The Vanishing of Ethan Carter_ with Wine-GE.
12. Every setting customization in game is gone.

### Expected behavior

I expect files created in _%USERPROFILE%\Documents_ or every other folder that is currently symlinked to the host file system in the Wine prefix to be retained in the sandboxed environment with external file system access blocked.

### Heroic Version

Latest Stable

### System Information

- OS: Parabola GNU/Linux-libre

### Additional information

Both Steam and Bottles work with external file system access blocked in Flatpak. In Bottles, sandboxing is one of the [stated goals](https://docs.usebottles.com/getting-started/installation) of the project. I have also used Lutris in the past with file system access blocked in Flatpak with no issues. For some users, the whole point for using Flatpak is sandboxing. In the specific case, I do not want Windows software to mess with $HOME.

**Comment by Etaash-mathamsetty** [comment]
This is a known issue and should be fixed with https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/pull/2298
you can compile this PR by yourself and test if it works for you

**Comment by flavioislima** [comment]
Even though this might be fixed like @Etaash-mathamsetty said. We cannot official support you changing permissions like this.


Imagine if by using 10 other commands heroic would break as well? Would we need to support all of them? 

Heroic flatpak will work as it is with the default permissions it asks. If doesn't then you can open an issue about it. 👍

**Comment by dariox86** [comment]
Obviously, issues are bound to happen if something like network access is disabled because some games may need it, but generally speaking games do not require access to user data the like of other class of application software. Games require sound, video, network and few more things like screensaver control. Bottles works with no file system access by default, Steam can access Pictures and Music for some optional features and Lutris can (optionally) work with no file system access as well. I think a Flatpak application should work on a principle of least privilege. Of course, the decision is up to you.

**Comment by flavioislima** [comment]
@dariox86 i see your point, the thing is that you are confusing two things in this case. Heroic is an interface that will call the runners and wine or proton eventually. Heroic itself does not need access to anywhere but the place you will download the games.

But the games itself, because of how wine works, needs access to those folders.

Bottles has a different philosophy than heroic. It will sandbox everything by default and if this behavior is desired, than bottles is more indicated in this case.

In the past we changed wine to sandbox prefixes by default because one person asked for and the majority of the community did not like it and we have reversed.

If you want to have this behavior just use wine tricks for that it is pretty simple to sandbox a prefix.

So it is good to have other softwares like bottles and lutris besides heroic, but on our end we won't change this behavior. Maybe an option in the future but we also do not want to clutter heroic with so many settings because it is confusing for new users.

**Comment by dariox86** [comment]
I know Bottles and Heroic Games Launcher serve a different purpose. If the community objected to the sandboxing of Wine prefixes, then I get your point. @Etaash-mathamsetty said I would need to run Winetricks every time I launch the application. That would be a bit unpractical. I will see if replacing the symlinks with actual folders with a script turns out to be a more convenient solution. Thank you for taking your time.

**Comment by bartek990** [comment]
I don't know if this is the same case, but...
When I click install, mentioned error occurs:

![2024-12-19-184301_hyprshot](https://github.com/user-attachments/assets/6cf47d0a-a307-4f64-a245-3dc6e5b6d9bc)

This path suppose to be "/home/.../Games/Heroic" and when I type correct path everything is back to normal - I can install a game and run it.

I use flatpak on Arch.
