### ISSUE TITLE
save-sync creates savedata into wrong directory [Windows]

### ISSUE THREAD

**Issue by rakiyoshi** [Heroic-Games-Launcher/HeroicGamesLauncher#2310]
### Describe the bug

Save-Sync creates savedata into wrong directory. The last character of the directory name is trimmed.

My configuration is the below and this creates `C:\Users\<user>\AppData\LocalLow\KojimaProductions\DeathStranding\ee8d2ed2a13e4b91a4121802229fff6`.
![スクリーンショット 2023-01-04 230647](https://user-images.githubusercontent.com/15209577/210572874-0b139faf-3574-418f-b82d-7ea47a54bd70.png)

The directory name is trimmed when calling legendary command. (see logs below for more detail.) 

This seems to be cause by the following code.
https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/blob/280c5c9a7f911b6d97e28238d0dc9628ad7e8fd4/src/backend/legendary/games.ts#L730

This was introduced from the first commit to `game.ts` (#349) but I couldn't know why.

### Add logs

```text
## The logs of Save-Sync

[Core] INFO: Trying to re-use existing login session...
[cli] INFO: Got 3 remote save game(s)
[cli] INFO: Checking "Death Stranding" (Boga)
[cli] INFO: Overriding save path with "C:\Users\<user>\AppData\LocalLow\KojimaProductions\DeathStranding\ee8d2ed2a13e4b91a4121802229fff6"...
[cli] INFO: Cloud save for "Death Stranding" is newer:
[cli] INFO: - Cloud save date: 2023-01-04 10:04:44
[cli] INFO: - Local save date: N/A
[cli] INFO: Downloading remote savegame...
[Core] INFO: Deleting old save files...
[Core] INFO: Downloading "Boga/manifests/2023.01.04-10.04.44.manifest"...
[Core] INFO: Successfully completed savegame download.

## Legendary log in `C:\Users\<user>\AppData\Roaming\heroic\logs\legendary-2023-01-04T12_00_26.264Z.log`

[2023/1/4 22:59:10] C:\Users\<user>\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\legendary sync-saves --skip-upload --save-path C:\Users\<user>\AppData\LocalLow\KojimaProductions\DeathStranding\ee8d2ed2a13e4b91a4121802229fff6 Boga -y
[Core] INFO: Trying to re-use existing login session...
[cli] INFO: Got 3 remote save game(s)
[cli] INFO: Checking "Death Stranding" (Boga)
[cli] INFO: Overriding save path with "C:\Users\<user>\AppData\LocalLow\KojimaProductions\DeathStranding\ee8d2ed2a13e4b91a4121802229fff6"...
[cli] INFO: Cloud save for "Death Stranding" is newer:
[cli] INFO: - Cloud save date: 2023-01-04 10:04:44
[cli] INFO: - Local save date: N/A
[cli] INFO: Downloading remote savegame...
[Core] INFO: Deleting old save files...
[Core] INFO: Downloading "Boga/manifests/2023.01.04-10.04.44.manifest"...
[Core] INFO: Successfully completed savegame download.
```

### Steps to reproduce

1. Set the filepath into `Please check twice if the path is correct` textbox.
2. Run `Download`

### Expected behavior

Filepath should not to be trimmed.

### Heroic Version

Latest Stable

### System Information

- OS [e. g. "Ubuntu"]: Windows

**Comment by Nocccer** [comment]
We always try to guess the save path but we can't get it write everytime. Checkout https://www.pcgamingwiki.com/wiki/Home for the correct paths. Closing this.
