### ISSUE TITLE
Automatically install game redistributables

### ISSUE THREAD

**Issue by imLinguin** [Heroic-Games-Launcher/HeroicGamesLauncher#2313]
### Problem description

Some games come with bundled redistributables (prerequisites) like `vcrun2017`, `nGlide`, `DirectX` etc..

Some especially older ones may not work due to missing implementations of those in wine.

### Feature description

Automatically install redistributable, when setting up wine prefix (Mac, Linux) or when installing the game (Windows). To provide as good as possible out of the box experience.

### Alternatives

Prompt user to select what redistributables to install.

### Additional information

Legendary currently lists prerequisites in `info` command.

gogdl will be able to list required redistributables when the refactor is done (that will allow for Steam like redistributable management, and reuse binaries across all games that need them)

**Comment by flavioislima** [comment]
I think I wanted to have something like this almost one year ago:
https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/issues/1381

**Comment by imLinguin** [comment]
Right, we do. Closing this since it's a duplicate
