### ISSUE TITLE
Ask to login again after credentials has expired

### ISSUE THREAD

**Issue by flavioislima** [Heroic-Games-Launcher/HeroicGamesLauncher#232]
Noticed today after trying to launch any game, that my credentials were expired, but heroic doesn't show any message about it.
Even when trying to logout no message was being shown (I think the Logout dialog is broken), but it worked.
So I needed to click on logout, close heroic and open it again to be able to log in again with the epic account.

So Would be good to have a dialog when launching heroic or a game, that the credentials were expired and then logout and ask for login again.

**Comment by adityaruplaha** [comment]
Well we were considering overhauling the login system entirely weren't we?

**Comment by flavioislima** [comment]
> Well we were considering overhauling the login system entirely weren't we?

Yeah, this must be done along with the new login screen. :)

**Comment by adityaruplaha** [comment]
Superseded by #306.
@flavioislima I think closing this issue would be nice.
