### ISSUE TITLE
Please rebuild a new version with mesa 22.3 to fix a bug of playing Death Stranding.

### ISSUE THREAD

**Issue by qwIvan** [Heroic-Games-Launcher/HeroicGamesLauncher#2326]
### Describe the bug

Death Stranding Crashing when opening the Map.

### Add logs

```text
{
  "checkUpdatesInterval": 10,
  "enableUpdates": false,
  "addDesktopShortcuts": false,
  "addStartMenuShortcuts": false,
  "autoInstallDxvk": true,
  "autoInstallVkd3d": true,
  "addSteamShortcuts": false,
  "preferSystemLibs": false,
  "checkForUpdatesOnStartup": false,
  "customWinePaths": [],
  "defaultInstallPath": "/run/media/mmcblk0p1/Heroic",
  "libraryTopSection": "recently_played_installed",
  "defaultSteamPath": "/home/deck/.steam/steam",
  "defaultWinePrefix": "/run/media/mmcblk0p1/Heroic/Prefixes",
  "hideChangelogsOnStartup": false,
  "language": "en",
  "maxWorkers": 0,
  "minimizeOnLaunch": false,
  "nvidiaPrime": false,
  "enviromentOptions": [],
  "wrapperOptions": [],
  "showFps": false,
  "useGameMode": false,
  "userInfo": {
    "name": "deck"
  },
  "wineCrossoverBottle": "Heroic",
  "winePrefix": "/home/deck/.wine",
  "wineVersion": {
    "bin": "",
    "name": "Default Wine - Not Found",
    "type": "wine"
  }
}
```

### Steps to reproduce

Open the Map in the game Death Stranding.

### Expected behavior

Upgrade the mesa library with 22.3 and rebuild the flatpak and appimage version to fix the bug.

### Heroic Version

Latest Stable

### System Information

steam deck with steam os.

### Additional information

This is the explain: https://www.reddit.com/r/SteamDeck/comments/zvt1ug/death_stranding_on_epic_games_is_broken_on_the/
This is the issue of mesa.
https://gitlab.freedesktop.org/mesa/mesa/-/issues/7735

**Comment by mike3e** [comment]
Mesa is not part of either of those packages. Flatpak uses whatever flatpak devs provide, and appimage should already use the system version of mesa

**Comment by Nocccer** [comment]
We only can fix flatpak if flatpak devs provide a new "runtime" package

**Comment by flavioislima** [comment]
exactly, this does not depends on heroic
