### ISSUE TITLE
User Interface: Update game process unclear

### ISSUE THREAD

**Issue by tmajibon** [Heroic-Games-Launcher/HeroicGamesLauncher#233]
While Heroic says there's an update available, it's not made clear that clicking "Play Game" will prompt for the update.

I feel there's a variety of ways to approach this that are all relatively equal:

* Add to the update message a small bit of text indicating to "click Play to update"
* Update the Play button to Play/Update when there's an update available
* Add a separate Update button (possibly under the gear menu?)

----

Maintainer's Edit:
Should be fixed by #236

**Comment by flavioislima** [comment]
> While Heroic says there's an update available, it's not made clear that clicking "Play Game" will prompt for the update.
> 
> I feel there's a variety of ways to approach this that are all relatively equal:
> 
>     * Add to the update message a small bit of text indicating to "click Play to update"
> 
>     * Update the Play button to Play/Update when there's an update available
> 
>     * Add a separate Update button (possibly under the gear menu?)

yeah, for sure. We'll have something on next update.

**Comment by adityaruplaha** [comment]
I think moving Update to a seperate button is a good idea. Also I'm looking at how game page buttons are handled currently and I think it might need a rework with the next update.

**Comment by flavioislima** [comment]
Added an option on the game menu to Update the game for now.

**Comment by adityaruplaha** [comment]
Will be fixed by #236
