### ISSUE TITLE
Show a short explanation of what Sync Saves: Unsupported means

### ISSUE THREAD

**Issue by arielj** [Heroic-Games-Launcher/HeroicGamesLauncher#2330]
### Problem description

Currently it's not clear for users where do we get that information and if there's anything that can be done for it to be supported.

### Feature description

When sync saves are unsupported we can show an `(i)` icon with a message like `This games does not support Epic's cloud saves. This information is provided by the game developers. Some games do implement their own cloud save system`

Changing `Epic's` for `GOG's` depending on the game.

(any suggestion for how to make this message more clear is welcomed)

### Alternatives

Another option is to still enable the `Sync Saves` section in the settings and display that message there, there's more space to put more text.

**Comment by flavioislima** [comment]
Some games on GOG also does not support so maybe lets make the message less specific.

**Comment by enzoIto** [comment]
Is still open? I would like to pick this issue

**Comment by Nocccer** [comment]
> Is still open? I would like to pick this issue

I think it is still open. Feel free to pick it :)
