### ISSUE TITLE
Moving or setting a non default path makes games unavailable

### ISSUE THREAD

**Issue by msdobrescu** [Heroic-Games-Launcher/HeroicGamesLauncher#2341]
### Describe the bug

Using the flatpak version, I try to avoid using the home directory for games installation.
I've tried to manually set the paths, to move the games, move the wine prefixes - by using the built-in features, leads to losing access to the games new paths. Even setting a default path to install will lose the games track after a short while.
Installing to a specific path also loses the games track. The error is "Game is unavailable" eventually.
Note, when selecting a path like /mnt/Games/Heroic/Games (/mnt/Games is related to the partition label), will set a /home/user/.var/... path, actually.

The only way I could have the large binaries on other path was to actually link the desired storage to /home/Games/ path, which is acceptable, but all the options discussed above are hopeless for this purpose.

### Add logs

```text
Can't find anything relevant, no error or clear log related to a path issue was present in my tests.
```

### Steps to reproduce

2. Click on '...'
3. Scroll down to '...'

### Expected behavior

Ideally, built-in move/import features should work.
If not, detect flatpak and disable features that do not work due to this technology.

### Heroic Version

Latest Stable

### System Information

- OS: MocaccinoOS - a Gentoo based distribution

### Additional information

Can't get a clear reason of it, like access issues or any specific error.
It may fallback to default paths or does not mount in the same way the game when moved..?

**Comment by imLinguin** [comment]
You just encountered flatpak feature - sandboxing, if you don't use the default paths such as `~/Games/Heroic` or `/media` you need to manually provide the access, you can use great tool called Flatseal to do that easily.

**Comment by msdobrescu** [comment]
Indeed.

If I have installed a game that played once, then could not be found anywhere after, where were the binaries installed in the first place?
