### ISSUE TITLE
heroic as low-level session-manager-gui (through gamescope: app-starter / steam-/kodi-alternative, f.e. for the steamdeck)

### ISSUE THREAD

**Issue by slynobody** [Heroic-Games-Launcher/HeroicGamesLauncher#2351]
### Problem description

your term 'launcher' has implications. you could use heroic not only as a game-launcher but as a simple gui to start applications on a linux-machine.

i am using heroic through gamescope as a low-level-session-manager (before a console could start). This enables me to use a simple gui with controller-input without using to much resources of the machine. (controlling sound and display brightness through keyboard are dealed with by using a simple rc.xml through openbox)

Though this already is a great solution in its current form, there are some features missing to supplement f.e. some steam- or kodi-functionalities at this low-level.

### Feature description

please integrate:

- simple app-kill-switch-option (kill a wine-session or even better: kill running topmost foreground-app, if you f.e. started a game / kodi / a browser; currently to my knowledge killing is only possibly by using an icon)
- simple option to start/stop services through keystroke (f.e. networking / bluetooth)
- simple overlay displaying on/off-state of networking and / or bluetooth
- simple overlay displaying changes in media (brightness, sound up or down; by using gamescope, this simple overlay should be displayed topmost already relatively easy by design).
- nice to have: option for using controller as complete mouse-replacement
- science-fiction: integrate touch-functionality

### Alternatives

none (please give me hints to implement functionality through other means)

### Additional information

none

**Comment by arielj** [comment]
I feel like this is way out of the scope of what Heroic aims to be. There's already a lot of complexity just with what we are currently doing and we expect to implement new stores too.

**Comment by flavioislima** [comment]
The idea is good but like Ariel commented, it is out of Heroic scope to work like this.
