### ISSUE TITLE
[Windows] Silent failure at moving game due to underlying script trying to use linux bash command

### ISSUE THREAD

**Issue by rodrigovda** [Heroic-Games-Launcher/HeroicGamesLauncher#2361]
### Describe the bug

When trying to move a game's installation in Windows it fails because the underlying code tries to execute:
```
mv -f 'D:\Games\Epic\FallGuys' 'D:\Games\Heroic\FallGuys'
```
And of course `mv` is a linux command incompatible with Windows CMD, the log shows:
```
'mv' is not recognized as an internal or external command,

operable program or batch file.
```

I suggest changing the code so it uses the equivalent `move` or `robocopy` commands in the windows version:
```
move /Y "D:\Path\to\source" "D:\Path\to\destination"
```
```
robocopy "D:\Path\to\source" "D:\Path\to\destination" /MOVE /e /im /is /it
OR
robocopy "D:\Path\to\source" "D:\Path\to\destination" /MOVE /mir
```
What's worse, HGL doesn't notify you of the failure, it simply says "Finished Moving", but the Install Path doesn't change, you can only see the error by reading the log.

### Add logs

```text
(14:18:34) INFO:    [Legendary]:        Moving 0a2d9f6403244d12969e11da6713137b to D:\Games\Heroic\FallGuys with mv -f 'D:\Games\Epic\FallGuys' 'D:\Games\Heroic\FallGuys'

(14:18:34) INFO:    [Backend]:          Preventing machine to sleep

(14:18:34) DEBUG:   [Legendary]:        Using cached install info

(14:18:34) DEBUG:   [Legendary]:        Using cached install info

(14:18:34) ERROR:   [Legendary]:        Failed to move 0a2d9f6403244d12969e11da6713137b: Error: Command failed: mv -f 'D:\Games\Epic\FallGuys' 'D:\Games\Heroic\FallGuys'

'mv' is not recognized as an internal or external command,

operable program or batch file.

    at ChildProcess.exithandler (node:child_process:407:12)

    at ChildProcess.emit (node:events:527:28)

    at maybeClose (node:internal/child_process:1092:16)

    at Socket.<anonymous> (node:internal/child_process:451:11)

    at Socket.emit (node:events:527:28)

    at Pipe.<anonymous> (node:net:709:12)

(14:18:34) INFO:    [Backend]:          Finished moving 0a2d9f6403244d12969e11da6713137b to D:\Games\Heroic\FallGuys.
```

### Steps to reproduce

1. Open Heroic Games Launcher in windows
2. Go to a game's Library page and select "Move Game"
3. Pick a destination
4. The process SILENTLY fails

### Expected behavior

The game moves succesfully to the destination folder, and if it fails for some reason, the user gets notified.

### Heroic Version

Latest Stable

### System Information

- OS [e. g. "Ubuntu"]: Windows 10

**Comment by rodrigovda** [comment]
> `mv` works fine on powershell on windows 10 and 11. are you using normal windows install or a debloated one?

Regular Windows 10, and yes, I have Powershell (both core and 7). but the error comes as if "mv" was executed in CMD (not powershell).

Besides, if your plan is to use Pwershell then the "force" argument should be `-Force`, not` -f`

**Comment by rodrigovda** [comment]
Here you can see in the attached image how Windows Powershell, Command Prompt and PowerShell 7 react to:
`mv -f C:\test D:\test`

As you can see, it fails in all 3 of them: CMD doesn't know `mv`, and Powershell doesn't recognize `-f`. And the error of my logs look exactly as the one given by CMD.

![image](https://user-images.githubusercontent.com/15835304/213211849-b58de389-141c-4b30-8a9d-33dcfa0fcd78.png)

**Comment by flavioislima** [comment]
> > `mv` works fine on powershell on windows 10 and 11. are you using normal windows install or a debloated one?
> 
> Regular Windows 10, and yes, I have Powershell (both core and 7). but the error comes as if "mv" was executed in CMD (not powershell).
> 
> Just in case: Windows 10 Pro 22H2 (19045.2486 build)
> 
> Besides, if your plan is to use Pwershell then the "force" argument should be `-Force`, not` -f`

Heroic runs all commands inside powershell.

I will investigate and test with robocopy when I have the time.
