### ISSUE TITLE
GOG downloads fail after fifteen minutes

### ISSUE THREAD

**Issue by JKingweb** [Heroic-Games-Launcher/HeroicGamesLauncher#2368]
### Describe the bug

If a GOG download takes longer than fifteen minutes, gogdl will start to report checksum mismatches and fail to make further progress. This always happens at or very near (± 1s) the 15:00 mark, irrespective of game. 

Attached here are compressed logs for three large games, all of which exhibited the behaviour at the 15-minute mark during download.

[1431426311.log.gz](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/files/10459375/1431426311.log.gz)
[1584823040.log.gz](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/files/10459376/1584823040.log.gz)
[1707860700.log.gz](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/files/10459377/1707860700.log.gz)

### Add logs

```text
See above.
```

### Steps to reproduce

1. Start downloading a large game from GOG
2. Wait fifteen minutes
3. Note the download has stalled

### Expected behavior

The download should continue to completion.

### Heroic Version

Latest Stable

### System Information

- OS: Manjaro

### Additional information

gogdl commit b95cc8e779798f735ff0c14b9a88ebe13a9c4c64.

**Comment by arielj** [comment]
will be fixed in the next release, the fix is already in the main branch of gogdl

can you try the binary from https://github.com/Heroic-Games-Launcher/heroic-gogdl/actions/runs/3949730533 ?

**Comment by arielj** [comment]
closing, this was fixed and we had no new reports
