### ISSUE TITLE
Does not open on steam deck

### ISSUE THREAD

**Issue by 2Redd4** [Heroic-Games-Launcher/HeroicGamesLauncher#2370]
### Describe the bug

Title, installed on steamdeck via flatpak

### Add logs

```text
Steam deck doesn't allow you to view logs :/
```

### Steps to reproduce

1. Go to desktop
2. Click on heroic launcher
3. wait for it to load
4. doesn't open

### Expected behavior

heroic launcher should open

### Heroic Version

Latest Stable

### System Information

- OS: Steam OS

**Comment by redromnon** [comment]
Open up the terminal app Konsole and run this command - `flatpak run com.heroicgameslauncher.hgl`

You can now post whatever you see as the log here.

**Comment by arielj** [comment]
Closing as this is stale, please comment again if this is still an issue
