### ISSUE TITLE
Xbox gamepass

### ISSUE THREAD

**Issue by FerLuisxd** [Heroic-Games-Launcher/HeroicGamesLauncher#2381]
### Problem description

Currently there is no way to play xbox game pass games on the steam deck using steamos

### Feature description

Would be amazing to see xbox game pass games here

**Comment by Poopooracoocoo** [comment]
Are there any tools than can emulate MSIX packaged apps? If not, I don't think this is in the scope of Heroic.

**Comment by scyto** [comment]
> Are there any tools than can emulate MSIX packaged apps on Linux? If not, I don't think this is in the scope of Heroic as it's a big ask.

and its even more complicated than MSIX apps as the games come packaged in xbox disk format that needs to be mounted by a custom device driver / filter driver which also includes copy protection, so yeah this is utterly impossible
