### ISSUE TITLE
WWZ Vulkan Black Screen but audio & input works

### ISSUE THREAD

**Issue by FerLuisxd** [Heroic-Games-Launcher/HeroicGamesLauncher#2383]
### Describe the bug

WWZ works with DX11 but when I change it to Vulkan and try to open it again I can only see a blank screen, the audio & input still works tho

I've tried with Proton experimental, Proton GE -47 , Proton 7.0
Same issue
Also deleting the wine prefix and changing it to other versions didn't help either

### Add logs

```text
https://pastebin.com/FxYQ5HzR
```

### Steps to reproduce

1. Open WWZ (default is DX11)
2. Go to settings and then Change it to Vulkan. 
3. Restart the game

### Expected behavior

The game should be visible when changing renderer

### Heroic Version

Latest Stable

### System Information

- OS: Steam OS 3.4
- Using steam deck

**Comment by flavioislima** [comment]
GAming issue not heroic issue, if the game launches the issue is not with Heroic. Go to our discord or open a GH discussion.
