### ISSUE TITLE
Ability to disable/control verbosity of wine logging

### ISSUE THREAD

**Issue by imLinguin** [Heroic-Games-Launcher/HeroicGamesLauncher#2388]
### Problem description

Currently there is no built in way to control how logging behaves

### Feature description

Add ability to control how verbose are wine, dxvk and vkd3d logs.

Default verbosity is good for basic debugging, but when everything works fine it's best to avoid unnecessary IO traffic. Leaving more resources for a game

### Alternatives

Instruct users in obvious way what environment variables allow to do things I described here.

### Additional information

https://wiki.winehq.org/Debug_Channels  
https://github.com/jp7677/dxvk#debugging  
https://github.com/HansKristian-Work/vkd3d-proton#environment-variables

**Comment by imLinguin** [comment]
I have these options in mind:
- On and off checkbox (Default/Disable)
- Drop down to choose level of verbosity (FULL(with masive slowdown warning)/Default/OFF)

Checkbox seems like the best option, in most cases you probably don't need FULL logging nevertheless

**Comment by Etaash-mathamsetty** [comment]
yeah most users won't need a full option, and those who need full can just set the WINEDEBUG env variable themselves (just make sure that this setting doesn't override it)

**Comment by arielj** [comment]
@imLinguin can we close this issue? We currently have a toggle to disable logs, and for cases where something extra is needed we can instruct users to set the WINEDBUG env variable as Etaash mentions

**Comment by imLinguin** [comment]
I believe we can, yes
