### ISSUE TITLE
Replace first ping url for better experience in China.

### ISSUE THREAD

**Issue by eebssk1** [Heroic-Games-Launcher/HeroicGamesLauncher#2389]
### Feature description

`const ping1 = ping('https://github.com', abortController.signal)`
The first ping uses github as target, which is heavily blocked in China.
It also add 3-5s offline status for us when launching.
Replace it with widely deployed url to avoid this.
I personally use 'https://cloudflare-dns.com' in my fork, works better.

**Comment by arielj** [comment]
hmmm weird, we do the pings in parallel and resolve as soon as any of the urls responds so one being slow shouldn't cause that problem, can it be that all 3 urls are blocked?

**Comment by eebssk1** [comment]
I'm now using system proxy on windows and test does go through proxy so this is no longer a big issue for me.
However for normal uses who does not use proxy or use proxy that does only route game traffic this change maybe important.

**Comment by arielj** [comment]
we could add a new url instead of replacing, since they are done in parallel it should be fine, and we are aborting the rest once one finishes successfully

**Comment by eebssk1** [comment]
well, I think this should do the job then.
