### ISSUE TITLE
won't auto-update to 2.6.0 (windows) +  2.6.2 (windows)

### ISSUE THREAD

**Issue by McBen** [Heroic-Games-Launcher/HeroicGamesLauncher#2400]
### Describe the bug

won't update because it tries to load `Heroic-2.6.0-Setup.exe`

but release files are named 
```
Heroic-2.6.0-Setup-arm64.exe
Heroic-2.6.0-Setup-x64.exe
Heroic-2.6.0-Setup.exe.blockmap 
```

### Add logs

```text
(18:26:32) ERROR:   [Backend]:          failed to update Error: Cannot download "https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/releases/download/v2.6.0/Heroic-2.6.0-Setup.exe", status 404:
```

### Steps to reproduce

start app, click on "update" in "new update available" dialog

### Expected behavior

download and install update

### Screenshots

`Something went wrong with the update, please check the logs or try again later!`

### Heroic Version

Latest Stable

### System Information

OS: Microsoft Windows 11 Home KERNEL: 10.0.22621 ARCH: x64
Heroic Version: 2.5.2 Yamato
Legendary Version:  0.20.31 Dark Energy (hotfix #5)
GOGdl Version: 0.5

**Comment by flavioislima** [comment]
Yes, forgot to rename the files before doing the release since now I added the ARM64 version as well.
Check if it will work now for the 2.6.1. Otherwise I will need to change the scripts to rename the files during build so they can have their own latest.yml and buildmaps.

**Comment by McBen** [comment]
2.6.1 looks good, thx

**Comment by McBen** [comment]
same with 2.6.2

**Comment by flavioislima** [comment]
hmm, does not make sense, it complains about anything? because I think the latest.yml and the files in it have the correct name and structure.

**Comment by McBen** [comment]
`(15:31:12) ERROR:   [Backend]:          failed to update Error: Cannot download "https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/releases/download/v2.6.2/Heroic-2.6.2-Setup.exe", status 404: 
`

**Comment by McBen** [comment]
fixed
