### ISSUE TITLE
Save-Sync not showing for Windows versions of GOG Games of which Linux versions are available

### ISSUE THREAD

**Issue by cst152** [Heroic-Games-Launcher/HeroicGamesLauncher#2402]
### Describe the bug

Windows Versions of games like Hollow Knight of Beneath a Steel Sky don't show the Cloud Saves Sync option in the Settings modal in Version 2.6.0 and 2.6.1. Both games have a Linux and a Windows Version.

I had Hollow Knight configured before the update to 2.6, so Saves Sync still works. There is just no settings category in the modal.

I'll test whether the Linux version of the respective games still work once #2401 is resolved.

### Add logs

```text
No logs relating to the problem found
```

### Steps to reproduce

1. Install Hollow Knight, Windows version from GOG
2. Click the settings button
3. Scroll down in the settings modal

### Expected behavior

I'd expect the Cloud Saves Sync option category to show up.

### Heroic Version

Latest Stable

### System Information

- OS [e. g. "Ubuntu"]: Arch Linux

**Comment by italoghost** [comment]
Can confirm the same thing. I have the Windows version of the "The Witcher 2" installed and the save sync option is gone.
