### ISSUE TITLE
Install dialog does not pre-select the default Wine

### ISSUE THREAD

**Issue by arielj** [Heroic-Games-Launcher/HeroicGamesLauncher#2406]
### Describe the bug

I installed Wine-GE-Proton7-36, then changed it in Settings > Games Defaults.

When I open the install dialog for any game, it pre-selects the first option (Wine-Staging in my case) and not the correct default.

The change is applied I can see that in the logs and if I go back to default settings

### Add logs

```text
(19:41:18) INFO:    [Backend]:          Heroic: Setting wineVersion to {"bin":"/home/ariel/.config/heroic/tools/wine/Wine-GE-Proton7-36/bin/wine","name":"Wine - Wine-GE-Proton7-36","type":"wine","lib":"/home/ariel/.config/heroic/tools/wine/Wine-GE-Proton7-36/lib64","lib32":"/home/ariel/.config/heroic/tools/wine/Wine-GE-Proton7-36/lib","wineserver":"/home/ariel/.config/heroic/tools/wine/Wine-GE-Proton7-36/bin/wineserver","wineboot":"/home/ariel/.config/heroic/tools/wine/Wine-GE-Proton7-36/bin/wineboot"}
```

### Steps to reproduce

1. Change the Wine version in the Default Settings
2. Open the install dialog for a game

### Expected behavior

The pre-selected wine version option should be the one defined as default

### Heroic Version

Latest Stable

### System Information

- OS [e. g. "Ubuntu"]: Mint

**Comment by flavioislima** [comment]
Noticed that as well. Should be an easy fix though.
