### ISSUE TITLE
Themes issues

### ISSUE THREAD

**Issue by arielj** [Heroic-Games-Launcher/HeroicGamesLauncher#2410]
### Describe the bug

There are elements in the interface that are always showing the color from the new default instead of the expected color from the there.

Game title in Zombie theme uses the mirage text color
![image](https://user-images.githubusercontent.com/188464/216496934-20aa34ad-168a-45cd-8bea-81c88e01409e.png)

(this light blue text color is leaking to a lot of places in many themes)

Same for the search bar
![image](https://user-images.githubusercontent.com/188464/216497006-15c85f6f-5858-4f33-ba20-77dd6db2bb36.png)

Also for Dracula
![image](https://user-images.githubusercontent.com/188464/216497070-9ad8fed0-db11-44b8-a049-c6ca0a0459d4.png)

Game Defaults info message is too light in Nord Light:
![image](https://user-images.githubusercontent.com/188464/216497189-f325bdbd-dfa6-4cbc-a0a3-05f94e625592.png)

Also Nord Light, current vs not current setting screen is too similar:
![image](https://user-images.githubusercontent.com/188464/216497288-3f0e32ad-7b76-46ae-bcbf-7503669bc159.png)

Dracula settings text color is the one from mirage
![image](https://user-images.githubusercontent.com/188464/216497398-1214ba17-f47f-4d88-8e93-cbcc6191b593.png)

Same for some of the text in Zombie
![image](https://user-images.githubusercontent.com/188464/216497496-08e46f4d-b294-493b-9fba-9e68d089a3d3.png)

Sweet accent color is too dark for the sidebar
![image](https://user-images.githubusercontent.com/188464/216497635-b8cd32b8-d0b2-45e0-a187-54a1c7ba79f7.png)

Contrast of yellow button in Mirage is below standards:
![image](https://user-images.githubusercontent.com/188464/216498252-aea5ad8a-87e5-4c24-872d-e41cd6747a8f.png)

Sync button in high contrast theme has bad contrast
![image](https://user-images.githubusercontent.com/188464/216498615-e532a43c-564e-4033-ba6b-bb292868111d.png)

These red buttons in high contrast theme have bad contrast when hovered
![image](https://user-images.githubusercontent.com/188464/216498731-1194ddb9-6984-4094-8631-43aa3b3c68d1.png)

Same for Nord Light
![image](https://user-images.githubusercontent.com/188464/216499170-8f209e1f-4cff-4f79-b9b8-ae920d083d61.png)

### Add logs

```text
nothing relevant
```

### Steps to reproduce

Just try different themes

### Expected behavior

Themes should have a consistent color palette. Elements should have at least AA contrast.

### Heroic Version

Latest Stable

### System Information

Not relevant

### Additional information

I don't know if this is the best place to report these issues, there are a lot of really small things.

**Comment by flavioislima** [comment]
I have defined some default variables for themes that does not have those, because before we were reusing some colors from the cyber theme.

I am checking this now.
