### ISSUE TITLE
Heroic v2.6.1 MacOS ARM64 "damaged"

### ISSUE THREAD

**Issue by scottjl** [Heroic-Games-Launcher/HeroicGamesLauncher#2411]
### Describe the bug

Try to launch application after copying to Applications folder (no errors in download or copy), receiving dialog box stating:

“Heroic.app” is damaged and can’t be opened. You should move it to the Trash."

### Add logs

```text
No log available
```

### Steps to reproduce

1. download  Heroic-2.6.1-macOS-arm64.dmg https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/releases/download/v2.6.1/Heroic-2.6.1-macOS-arm64.dmg
2. mount image
3. copy application to /Applications
4. Double click Heroic.app

### Expected behavior

Heroic launches

### Heroic Version

Latest Stable

### System Information

- MacOS 13.2
- PowerBook M1 Pro

**Comment by r-j-w** [comment]
The app isn't signed by apple so this is normal. The only solution right now is to manually delete the quarantine attribute:
```xattr -d com.apple.quarantine /Applications/Heroic.app```

**Comment by scottjl** [comment]
Maybe you could include a README file on the image stating this or something obvious? Most Mac users are just going to download the .dmg, drag and drop, and expect it to work.

Are there any plans to get a developer account with Apple?

**Comment by MichaelGDev48** [comment]
The team can get a free apple developer account and fix this with the codesign command there are guides out there i wish them luck :) 
Github workflow might also be able to do it i could see if i could make a pr and before distribution it codesigns

**Comment by MichaelGDev48** [comment]
Heres the syntax
codesign --force --sign "Developer ID Application: <identityIdentifier>" <pathToApp>

**Comment by flavioislima** [comment]
> The team can get a free apple developer account and fix this with the codesign command there are guides out there i wish them luck :) Github workflow might also be able to do it i could see if i could make a pr and before distribution it codesigns

How to get a free apple developer account?
Afaik we would need to pay apple 99USD per year to have one, no?

**Comment by MichaelGDev48** [comment]
> > The team can get a free apple developer account and fix this with the codesign command there are guides out there i wish them luck :) Github workflow might also be able to do it i could see if i could make a pr and before distribution it codesigns
> 
> How to get a free apple developer account? Afaik we would need to pay apple 99USD per year to have one, no?

Not you dont . Thats for more features but you can codesign with a free account. All you have to do is create an apple id

**Comment by tosziro** [comment]
2.6.2 have same problem

**Comment by flavioislima** [comment]
> 2.6.2 have same problem

All versions will have this issue until we buy a developer certificate from Apple.

It might happen

**Comment by scottjl** [comment]
> > 2.6.2 have same problem
> 
> All versions will have this issue until we buy a developer certificate from Apple.
> 
> It might happen

did you look at MichaleGDev48's comment? You can get a code signing account for free.

https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/issues/2411#issuecomment-1416801169

**Comment by flavioislima** [comment]
> > > 2.6.2 have same problem
> > 
> > All versions will have this issue until we buy a developer certificate from Apple.
> > 
> > It might happen
> 
> did you look at MichaleGDev48's comment? You can get a code signing account for free.
> 
> https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/issues/2411#issuecomment-1416801169

Yes, looked at it hut when I try to enroll the developer program it asks me to pay the bill. There is no option to do it for free.

**Comment by MichaelGDev48** [comment]
No just create an apple id and use that to codesign it

**Comment by MichaelGDev48** [comment]
You only need an apple id to notarize an app which is different

**Comment by arielj** [comment]
I think we are now signing the apps for mac so this shouldn't be an issue anymore?

can anyone confirm this using heroic 2.7?

**Comment by MichaelGDev48** [comment]
> I think we are now signing the apps for mac so this shouldn't be an issue anymore?
> 
> can anyone confirm this using heroic 2.7?

Yes can confirm, this can be closed now thank you team :D
