### ISSUE TITLE
discord rich presence broken

### ISSUE THREAD

**Issue by brudi123** [Heroic-Games-Launcher/HeroicGamesLauncher#2418]
### Describe the bug

discord rich presence isnt working on the deb version of heroic. please fix this !

### Add logs

```text
.............
```

### Steps to reproduce

1. Go to 'settings'
2. Click on 'settings for games
3. Scroll down to 'discord rich presence'
4. no error there it seems applied but is not

### Expected behavior

that the rich presence works in discord

### Heroic Version

main branch from GitHub

### System Information

- OS kubuntu 22.10

**Comment by Etaash-mathamsetty** [comment]
seems like it broke with the new version? It's no longer working on my side too

**Comment by flavioislima** [comment]
I think it wont work for custom games, probably we are not calling the method for that. But should work fine for gog and epic games. I just tested on macOS and works fine. Flatpak never worked. Deb should work just fine. But without logs is complicated to know what happened.

**Comment by Etaash-mathamsetty** [comment]
> I think it wont work for custom games, probably we are not calling the method for that. But should work fine for gog and epic games. I just tested on macOS and works fine. Flatpak never worked. Deb should work just fine. But without logs is complicated to know what happened.

I remember it was working last release lol

**Comment by flavioislima** [comment]
Yeah, looking at the code, sideload games should work just fine and we did not changed anything related with the discord RPC so I am not sure what happened, we will need to test more on other distros like Arch and fedora.
