### ISSUE TITLE
login to EGS fails on windows 7 

### ISSUE THREAD

**Issue by woeisme** [Heroic-Games-Launcher/HeroicGamesLauncher#2419]
### Describe the bug

attempts to login to epic game store fail silently to user, both normal and alternative methods (Heroic Version 2.6.1)

A message in the logs complains about missing python modules

### Add logs

```
LoadLibrary: The specified module could not be found.
    at ChildProcess.exithandler (node:child_process:409:12)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1093:16)
    at ChildProcess._handle.onexit (node:internal/child_process:302:5)
(20:39:05) DEBUG:   [Backend]:          Unable to load Steam Libraries, libraryfolders.vdf not found
```

### Steps to reproduce

1. Go to 'Manage Accounts' put in credentials
2. Click on 'Epic Games Login'
3. nothing happens

### Expected behavior

login and add Epic games to Heroic Launcher

### Heroic Version

main branch from GitHub

### System Information

Windows 7 Professional 64bit

**Comment by flavioislima** [comment]
Windows 7 is not supported. Only 10 and up. This is at the Readme and on our website.

**Comment by woeisme** [comment]
I guess you suck then.
