### ISSUE TITLE
[Feature Request] Add toggle for OBS vkcatpture

### ISSUE THREAD

**Issue by Etaash-mathamsetty** [Heroic-Games-Launcher/HeroicGamesLauncher#2429]
### Problem description

I don't want to keep adding in the same env (OBS_VKCAPTURE=1) variable for all my games in heroic, so why not make this a toogle, it's a simple env variable after all. 

### Feature description

add a toggle that sets this env variable when the game is launched. 

### Alternatives

set the env variable manually

**Comment by arielj** [comment]
you can add that once in the Game Defaults setting and it will be added by default for every new game you install instead of doing it for each game

**Comment by arielj** [comment]
you could also set that for your system too

it sounds like a really specific use case though, I don't know if it makes sense to add that to the UI (it's just more code to maintain, strings to translate, providing support, etc)

**Comment by Etaash-mathamsetty** [comment]
> you could also set that for your system too
> 
> it sounds like a really specific use case though, I don't know if it makes sense to add that to the UI (it's just more code to maintain, strings to translate, providing support, etc)

yeah I just discovered you can set an env variable for all games globally lol, I guess I will be use that
I also agree that it's kind of specific, but it also is a very nice QoL feature that more people would use if they knew about it.
