### ISSUE TITLE
Can you add the ability to add existing libraries?

### ISSUE THREAD

**Issue by amogusussy** [Heroic-Games-Launcher/HeroicGamesLauncher#2445]
### Problem description

All my games are stored on a different hard drive to my main HDD, but when I changed my Linux distro (arch to void), all my games weren't set as downloaded.

### Feature description

Could you an option to import preexisting libraries (like what steam has, where you open settings, click downloads, click steam library folders, click the plus icon, and import your library)?

### Alternatives

There aren't any alternatives to my knowledge.

**Comment by Lariaa** [comment]
This is highly dependant on the original launchers.
You already can hit install for a specific game and then say "import".
Reading the Data from installs done by the proprietary launcher might come at a later time.
If the upstream launcher doesn't support mass import from folder itself, this will become difficult to do.
So depending on the platform you are talking about, it might be necessary to get this implemented by the vendor first so we can copy.
