### ISSUE TITLE
Steam shortcut image looks "wierd" when the game has a separate logo file

### ISSUE THREAD

**Issue by arielj** [Heroic-Games-Launcher/HeroicGamesLauncher#2463]
### Describe the bug

From a report on Discord:

![image](https://user-images.githubusercontent.com/188464/219868403-c474cced-becd-4bd2-8e8d-17f6f7a093e5.png)

This is because some games have a separate image for the logo, so the cover art is actually kinda empty.

### Add logs

```text
Nothing relevant
```

### Steps to reproduce

1. Install a game that has a logo file (celeste, the batman arkham, faster than life, there are many)
2. Add the game to steam

### Expected behavior

The shortcut should have an image made out of the cover art + the logo when available.

We already have a method to use the frontend's canvas to generate images so it shouldn't be THAT hard maybe?

### Heroic Version

Latest Stable

### System Information

Not relevant

**Comment by Nocccer** [comment]
I know for the hero image steam already does that if a logo is provided.
