### ISSUE TITLE
GamePage image is missing logo when available

### ISSUE THREAD

**Issue by arielj** [Heroic-Games-Launcher/HeroicGamesLauncher#2466]
### Describe the bug

For games that have a separate asset for the logo, we are not showing the logo in the game page:

![image](https://user-images.githubusercontent.com/188464/219874647-d4551845-283b-4432-bbdc-6e3033fbd724.png)

![image](https://user-images.githubusercontent.com/188464/219874804-611ac6df-935c-490b-bb93-274d617fb60d.png)

### Add logs

```text
Nothing relevant
```

### Steps to reproduce

1. Open the game page for any game that has a logo asset (rayman legends, alan wake's, batman arkham, faster than light, celeste, and many more)

### Expected behavior

The logo should be placed over the image like it's done in the library

### Heroic Version

Latest Stable

### System Information

Not relevant

**Comment by thiyagarajan17** [comment]
please assign the issue.. would love to work on it!

**Comment by flavioislima** [comment]
> 
> please assign the issue.. would love to work on it!

No need to assign. Just let us know that you want to work on that. And also if you are stuck go to our discord for help. 👍
