### ISSUE TITLE
Ubisoft Connect games not starting

### ISSUE THREAD

**Issue by davegorst** [Heroic-Games-Launcher/HeroicGamesLauncher#2479]
### Describe the bug

Cannot start Ubisoft Connect games purchased via EGS.

Installs OK, but hit play results in a few seconds of "Playing" then reverts to "Installed <size>".

Using Proton Experimental doesn't seem to help.

### Add logs

```text
(08:00:15) INFO:    [Backend]:          Launching Assassin's Creed: Valhalla (965ccf8b2eba4f9381ef43183c08e205)
(08:00:15) INFO:    [Backend]:          Preventing display from sleep
(08:00:15) INFO:    [Backend]:          Checking if wine version exists: Proton - Proton 7.0
(08:00:15) INFO:    [Backend]:          Checking if wine version exists: Proton - Proton 7.0
(08:00:15) WARNING: [Backend]:          You are using Proton, this can lead to some bugs. Please do not open issues with bugs related to games
(08:00:15) INFO:    [Backend]:          Checking if wine version exists: Proton - Proton 7.0
(08:00:15) INFO:    [Backend]:          Checking if wine version exists: Proton - Proton 7.0
(08:00:15) DEBUG:   [Backend]:          Running Wine command: run wineboot --init
(08:00:17) INFO:    [Legendary]:        Running command: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary launch 965ccf8b2eba4f9381ef43183c08e205 --json --offline
(08:00:17) INFO:    [Legendary]:        Launching Assassin's Creed: Valhalla: LD_PRELOAD= STEAM_COMPAT_CLIENT_INSTALL_PATH=/home/dgorst/.steam/steam STEAM_COMPAT_DATA_PATH="/home/dgorst/Games/Heroic/Prefixes/Assassins Creed Valhalla" PROTON_NO_ESYNC=1 PROTON_NO_FSYNC=1 STEAM_COMPAT_APP_ID=0 SteamAppId=0 SteamGameId=heroic-AssassinsCreedValhalla PROTON_LOG_DIR=/home/dgorst /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary launch 965ccf8b2eba4f9381ef43183c08e205 --language en --no-wine --wrapper "'/mnt/media2/SteamLibrary/steamapps/common/Proton 7.0/proton' run"
(08:00:20) INFO:    [Backend]:          Stopping Display Power Saver Blocker
(08:00:20) INFO:    [Frontend]:         Refreshing Library
(08:00:20) INFO:    [Legendary]:        Refreshing library...
(08:00:20) INFO:    [Legendary]:        Game list updated, got 21 games & DLCs
```

### Steps to reproduce

1. Open Heroic and select an Ubisoft game.
2. Click on Play
3. Wait
4. Status reverts to installed.

### Expected behavior

1. Open Heroic and select an Ubisoft game.
2. Click on Play
3. Wait
4. Game starts

### Heroic Version

Latest Stable

### System Information

Ubuntu 22.04
CPU : 5950X
GPU : Radeon 6800XT

### Additional information

Previously ran OK under Lutris.

**Comment by davegorst** [comment]
EGS and GOG non-Ubisoft games run fine.

**Comment by arielj** [comment]
You have to install Ubisoft connect in the game prefix (and for some games like Watch Dogs 2 you have to install them through Ubisoft Connect). Check our guide here https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/wiki/How-to-install-Ubisoft-Connect-on-Linux-and-Mac

In the next version of Heroic, it will install Ubisoft Connect in the background so you won't have to do it manually, but for now that is the process.

**Comment by davegorst** [comment]
Many thanks - that worked.
