### ISSUE TITLE
Heroic failing to detect pre-installed games.

### ISSUE THREAD

**Issue by jarrard** [Heroic-Games-Launcher/HeroicGamesLauncher#248]
As title says, screenshot says 1000 words.  Everything has been refreshed, restarted, etc...

![rage fail](https://user-images.githubusercontent.com/17428910/111369114-98421600-86e6-11eb-9b2e-fac9f0e1f530.jpg)

**Comment by jarrard** [comment]
It seems legendary is downloading all the files and failing to see it as installed.. 

I'm at a loss.

**Comment by jarrard** [comment]
What could be useful is if the app either auto detects that the folder and files exists and imports them automatically, then gives you a yellow exclamation mark to run the verify files option.  Or have a option in the menu somewhere to import pre-existing folder.

Currently it seems possible for legendary to download and not import games, and when this happens you must import and verify the folder yourself.

I download via legendary because heroic launcher always fails on downloading files for some reason (single threaded? unstable threads?)...

**Comment by adityaruplaha** [comment]
> Importing the folder and then running a repair on it may work.  It just seems the app doesn't care if the files exist already which is unfortunate.

You will have to edit the installed.json file manually. There's not a way for Heroic to know what files are stored inside ~/Games/Heroic. So it keeps its own installation database seperate from legendary.

It might be possible to check for new installs and update the database automatically using legendary, I will have to look into it.

**Comment by adityaruplaha** [comment]
> I download via legendary because heroic launcher always fails on downloading files for some reason (single threaded? unstable threads?)...

Interesting. That shouldn't happen. Can you post a log?

**Comment by flavioislima** [comment]
I could not understand what happened. You have downloaded a game using legendary but using the option to download only and not install? Because heroic uses the legendary config files to read the installed games so if you install a game using legendary, without the option to download only, it works because this is how heroic works.

But if you used the option to only download the game, that game won't be on the installed.json file on the legendary config folder so heroic won't see it.

About the game not downloading when using heroic, have you tried using the max option on the max workers settings?

**Comment by flavioislima** [comment]
So if you're downloading a game using legendary, use only the install option and the path option if you need. This way, doing `legendary list-installed` will list your installed games that will be the same games that will show on heroic.

**Comment by jarrard** [comment]
> Interesting. That shouldn't happen. Can you post a log?

There is already a issue report about this.

**Comment by flavioislima** [comment]
> > Interesting. That shouldn't happen. Can you post a log?
> 
> There is already a issue report about this.
> 
> Yeah legendary only downloaded files then it seems I need to manually install it myself afterwards. Odd, don't remember it being that way in past.

this is really odd and not how legendary works. Try to get support on their discord or open an issue on their GH since this is happening outside heroic. Check your legendary config file as well, maybe something is wrong there.

**Comment by jarrard** [comment]
The only thing I have in my profile is below, perhaps its not enough. But if I download a game it will put the files into the correct folder but fails to actually install the app, so nothing see's it until I do that. 

/home/theriddick/.config/legendary/config.ini
[Legendary]
install_dir = /mnt/GamesNVMe/EpicGamesStore/

**Comment by flavioislima** [comment]
> The only thing I have in my profile is below, perhaps its not enough. But if I download a game it will put the files into the correct folder but fails to actually install the app, so nothing see's it until I do that. 
> 
> 
> ```
> /home/theriddick/.config/legendary/config.ini
> [Legendary]
> install_dir = /mnt/GamesNVMe/EpicGamesStore/
> ```
> 
> **Still I think Heroic could just detect if folder exists already and do some basic prompts to the user if they want to add it to games and verify the contents. Rather simple and would solve this problem if anyone gets it.** 
> 

I'll close the issue since is not heroic related! 👍
