### ISSUE TITLE
The tooltip for a Completed (Cancelled) games' action says to "Remove from Downloads", but goes to the game's Install page.

### ISSUE THREAD

**Issue by Alzarath** [Heroic-Games-Launcher/HeroicGamesLauncher#2485]
### Describe the bug

After cancelling a game (untested when a game has completed downloading), the Action shows a down arrow, but the tooltip says "Remove from Downloads". The behavior, on the other hand, is to navigate to the game's Install page.

### Add logs

```text
N/A
```

### Steps to reproduce

1. Go to the Library page
2. Click on any game's Install button
3. Click the Install button
4. Click the Install button
5. Go to the Downloads page
6. Click the Pause/Cancel action button for the installing game
7. Hover over the action button for the cancelled game under the Completed category

### Expected behavior

Display a tooltip that describes its actual function.

OR

Remove the game from the Completed category and use a more appropriate icon.

### Heroic Version

Latest Stable

### System Information

- Arch Linux x86_64

**Comment by flegald** [comment]
May I please have this assigned to me? I have a fix ready to go

**Comment by arielj** [comment]
Fixed in 2.10.0
