### ISSUE TITLE
app-support / app-ui-levels / antimicrox-option / 'play' / appl.-exit-key

### ISSUE THREAD

**Issue by slynobody** [Heroic-Games-Launcher/HeroicGamesLauncher#2486]
### Problem description

compatibility / usability / launch-support / keyboard-shortcuts

### Feature description

- [linux] please support possibilities to use local apps in the following forms: *.appimg; *.desktop (should make it easier to use for the ui-guys installing via app-stores etc.; *.desktop-support should also include import of icon mentioned there)
- [all] please give options to 'lock-down' given ui-options on two (or three levels): easy, (medium), full ('easy' at least should give you a completly stripped-down view: trigger icon = start, trigger icon again = stop, no other changes possible; s.f.e. kodi on such a solution)
- [all] in games-option, please give the opportunity to launch 'antimicrox'
- [all] please rename word 'play' to a word with wider context, f.e. 'start' (or give possibility to alter it in 'full mode')
- [all] please give possibilty for assinging a global keystroke quiting current running application without ui being v isible (no ctrl-q-equivalent but adaptive to application started)

**Comment by Nocccer** [comment]
Please format this as markdown in the issue and not as a code field. Also make the issue title more clear
