### ISSUE TITLE
Parse gog .info files to list addtional executables.  

### ISSUE THREAD

**Issue by Bitwolfies** [Heroic-Games-Launcher/HeroicGamesLauncher#2488]
### Problem description

GOG games tend to come with several exe's used to configure the game, or outright other parts of a game, and manually dragging them to the run in prefix button is slow and cumbersome.

### Feature description

GOG Galaxy has a solution to this problem, with the additional executables section.  
![Screenshot_20230223_020959](https://user-images.githubusercontent.com/65789901/220877741-fd982b42-2f9a-4298-936e-22b27b7cd96a.png)

Thankfully, these options are all listed with the games .info file, no external db required.
![Screenshot_20230223_020903](https://user-images.githubusercontent.com/65789901/220877546-fc653855-4214-4e20-b0b5-3349b0d28a3d.png)
It would be great if Heroic could list these options within its gui.

**Comment by imLinguin** [comment]
That's something I was planning to do. Probably in form of popup window, play task select on game page, or option in settings to also allow for this feature when running from shortcut or protocol
