### ISSUE TITLE
Best way to run something before and after e.g. changing keyboard layout

### ISSUE THREAD

**Issue by alexheretic** [Heroic-Games-Launcher/HeroicGamesLauncher#2507]
### Problem description

I often want to set my keyboard layout to qwerty for games, rather than my default of colemak.

In steam I can do this with launch settings `setxkbmap gb; %command%; setxkbmap gb colemak`.

For some games I've used a similar way to set mouse sensitivity before & after the game launch.

I can't see an equivalent way to do so in heroic. Is there a good way to achieve this?

### Feature description

Configure commands to run before & after the game.

**Comment by Anuskuss** [comment]
Until this is done properly, you can use this as your wrapper script:

```bash
#!/bin/bash

setxkbmap gb
"$@"
setxkbmap colemak
```
