### ISSUE TITLE
Heroic recognizes Steam Proton but will not run... 

### ISSUE THREAD

**Issue by lineber** [Heroic-Games-Launcher/HeroicGamesLauncher#251]
Hello, 
I think Heroic-Game-Launcher is great. In settings, I get the current wine on my system, some lutris wine prefixes, and the Protons installed in Steam. The only one that works is the system prefix (~/.wine). I am not sure if it has to do with this being a flatpak version of Steam, as I see that all those issues have already been closed. And the Launcher recognizes the Proton prefixes.

I get popup message: `"key 'box.error (en)' returned an object instead of string. Error when launching the game, check the logs!"`
The logs are as followed:
```

Traceback (most recent call last):
  File "/home/linuxuser/.var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/common/Proton 5.13/proton", line 959, in <module>
    g_session.run()
  File "/home/linuxuser/.var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/common/Proton 5.13/proton", line 932, in run
    self.run_proc([g_proton.wine_bin, "steam"] + sys.argv[2:] + self.cmdlineappend)
  File "/home/linuxuser/.var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/common/Proton 5.13/proton", line 924, in run_proc
    subprocess.call(args, env=local_env, stderr=self.log_file, stdout=self.log_file)
  File "/usr/lib64/python3.9/subprocess.py", line 349, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/lib64/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib64/python3.9/subprocess.py", line 1823, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/home/linuxuser/.var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/common/Proton 5.13/dist/bin/wine'
```

By the way, there is a file called wine in that directory. Also, the Lutris versions of wine also don't work. If this is because I have flatpak, is there a way I can install Proton without going through Steam?

**Comment by flavioislima** [comment]
So you're using Wine and Steam Flatpak?
I never tried proton with steam flatpak but the path to its proton was added a long time ago and it should recognize it.

No games are running or this is a specific one?

Another way of using proton is by downloading (or adding a symlink) it and putting inside the `.confg/heroic/tools/proton` folder.
You could try downloading Proton-GE for instance and extracting it inside this folder.

On the next version, 1.5.6, Heroic will have a new setting where you can select a proton or wine binary yourself anywhere on your system to run your games and this will make life easier to a lot of people at least we are expecting this.

**Comment by lineber** [comment]
Thanks, I was able to install Proton-GE directly, but still, get the error as mentioned. I imagine this has something to do with my personal settings. I use Fedora 33 (Silverblue), hence why I prefer to use Flatpaks. Proton works very well within Steam but I must be missing some dependency. The Wine-6.3 (staging) works decently on Subnautica Below Zero, but of course, I'd prefer to try it with Proton as there are some visual oddities (not many). So far I've tried 4 games and this is the only one I can get to work. Despite that, heroic is great as my problems are likely with Wine.

Feel free to close this issue as I cannot say it is related to heroic.

Thank you again for your assistance.

**Comment by flavioislima** [comment]
Yeah, unfortunately Flatpak is something that I'm still getting familiar with. I'm trying to have a Heroic flatpak since version 1.0 and could not do it yet, but I'm close.

But even with a  flatpak version, heroic won't be able to do much since most of the things lives in their own containers on a a flatpak so it is a challenge.

But keep looking at our releases here and you will see a flatpak version eventually 👍

**Comment by CleoMenezes** [comment]
> So you're using Wine and Steam Flatpak?
> I never tried proton with steam flatpak but the path to its proton was added a long time ago and it should recognize it.
> 
> No games are running or this is a specific one?
> 
> Another way of using proton is by downloading (or adding a symlink) it and putting inside the `.confg/heroic/tools/proton` folder.
> You could try downloading Proton-GE for instance and extracting it inside this folder.
> 
> On the next version, 1.5.6, Heroic will have a new setting where you can select a proton or wine binary yourself anywhere on your system to run your games and this will make life easier to a lot of people at least we are expecting this.

Works for me
