### ISSUE TITLE
[Feature request] Heroic should spit out sub-process errors too on Linux

### ISSUE THREAD

**Issue by otuva** [Heroic-Games-Launcher/HeroicGamesLauncher#2510]
### Problem description

It's a problem when things don't go as expected and there's no error to work on.
Games fail to launch without any errors, for example, if wine couldn't find a binary or couldn't create a display socket
I intentionally broke a couple of things and there were no errors from heroic. I had to dive into other logs 

### Feature description

Heroic should not just log itself, but it should log every process under it. 

### Alternatives

n/a

### Additional information

n/a

**Comment by Nocccer** [comment]
Already exist for a long time. Was just moved to a not good place and we already consider making it clear again.
![image](https://user-images.githubusercontent.com/61798668/222479710-fdf1f775-812d-43cc-84fb-5683145bd6c4.png)

**Comment by otuva** [comment]
@Nocccer Yeah, I see it now, my bad. I thought it was a bug report for community scripts type of thing like on Lutris
