### ISSUE TITLE
Stranger Things Save-Sync does not work

### ISSUE THREAD

**Issue by longusnickus** [Heroic-Games-Launcher/HeroicGamesLauncher#252]
the title says it al

i played on geforce now and downloaded the save files. this works.
but if i upload my local save files it messes it up

~/.wine/pfx/drive_c/users/steamuser/AppData/LocalLow/BonusXP/ST3TG/
in this folder is a Savegames folder, which seems not to be uploaded, but some files from ST3TG folder

not really important, but maybe it affects other games too

https://www.epicgames.com/store/p/stranger-things-3-the-game

**Comment by flavioislima** [comment]
Hi!

This save sync stuff is a bit complex to be honest.
I guess that in 80% of the cases heroic will find the right path but on other cases you will need to select the folder manually.

This is probably one these cases. Just use the option to override the folder and you're good to go,
