### ISSUE TITLE
Can't login in either method for epic games

### ISSUE THREAD

**Issue by nekolifestyle** [Heroic-Games-Launcher/HeroicGamesLauncher#2529]

**Comment by a-cristi** [comment]
I had the same problem, but I managed to log in without any issues using the alternative log in method, as described [here](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/wiki/How-To:-Epic-Alternative-Login).

**Comment by Erz3** [comment]
I can't either, not even with the alternative method.

I am running 2.7.0 appimage version on Manjaro.

**Comment by flavioislima** [comment]
> I can't either, not even with the alternative method.
> 
> I am running 2.7.0 appimage version on Manjaro.

Can you try the flatpak?

**Comment by Erz3** [comment]
> Can you try the flatpak? 

Yes, work fine with flatpak version.
