### ISSUE TITLE
games won't download, it says installing but over one day it installed 0 % please help

### ISSUE THREAD

**Issue by DAvethegoat** [Heroic-Games-Launcher/HeroicGamesLauncher#253]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Ubuntu]
-  Game:
-  Wine/Proton version:

**Additional context**

**Comment by flavioislima** [comment]
Can you add the required information for the bug report? Is hard to help like this.
