### ISSUE TITLE
Same as the guy below. Can't login Epic Games using launcher.

### ISSUE THREAD

**Issue by rickrock1** [Heroic-Games-Launcher/HeroicGamesLauncher#2530]
### Describe the bug

Can't login Epic Games account on Heroic Launcher. After capture says refresh and try again. Been trying for hours. Please hurry up and fix it. I paid good money to use this system and Crossover to play Rocket League on a mac. Also, what's with the 10 step account sign up to post an issue. What is this a bank? wtf. Jesus fucking christ is all I've got to say. 

Was working fine yesterday. I notice someone else has the same issue and is yet unanswered. 

### Add logs

```text
mhvbj,vkhgch
```

### Steps to reproduce

2. Click on '...'
3. Scroll down to '...'

### Expected behavior

hvjhvgjh

### Screenshots

<img width="1303" alt="Screen Shot 2023-03-09 at 6 12 22 PM" src="https://user-images.githubusercontent.com/127466388/224219441-54b3edf0-161a-4997-a224-7070e483cf74.png">

### Heroic Version

Latest Stable

### System Information

- OS [e. g. "Ubuntu"]:

### Additional information

ngvjngv

**Comment by Dandraghas** [comment]
there is temporary [solution](https://discord.com/channels/812703221789097985/1083464134428999722/1083544455199596695) for this issue, try alternative login
