### ISSUE TITLE
Login issue

### ISSUE THREAD

**Issue by TheAbstractDev** [Heroic-Games-Launcher/HeroicGamesLauncher#2531]
### Describe the bug

Hello,

After installing Heroic (macOS) 3 days ago, it was working fine but today, when trying to launch a game, I had an error message from Heroic telling me to logout and re-login.

Now, I can unfortunately confirm that the login doesn't work now, either with the SID.

I'm currently using the 2.6.2 (Hotfix).

### Add logs

```text
No logs shown for the login
```

### Steps to reproduce

Heroic in-app Login:
1. Go to 'Log in'
2. Click on 'EPIC GAMES LOGIN'
3. Try to login with your credentials
5. See error: "Incorrect Response. Please refresh the page"

SID Login:
Error: "{"redirectUrl":"https://localhost/launcher/authorized?code=MYCODE","authorizationCode":"CODE","sid":null}"

### Expected behavior

Log in

### Screenshots

<img width="481" alt="Screenshot 2023-03-10 at 10 55 53" src="https://user-images.githubusercontent.com/11737352/224285363-fa6e0cd9-e67e-4bb2-b318-a33908a1cdf7.png">
<img width="1275" alt="Screenshot 2023-03-10 at 10 56 24" src="https://user-images.githubusercontent.com/11737352/224285721-4d6be46a-14f7-4c76-9291-c791acdc8997.png">

### Heroic Version

Latest Stable

### System Information

- OS: macOS

**Comment by Dandraghas** [comment]
as explained many times try [alternative login](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/wiki/How-To:-Epic-Alternative-Login)

**Comment by TheAbstractDev** [comment]
It's working great (for now) with the alternative login !
Thanks !

**Comment by Stooovie** [comment]
Not for me, the AuthorizationCode is accepted but I get returned to the Stores logins screen.

**Comment by TheAbstractDev** [comment]
@Stooovie 
I had to re-connect today and I can confirm that the alternative login is still working for me

**Comment by mmbossoni** [comment]
I have this same problem, no matter which authentication method I use
After a day or so, I receive the login failed.
Have to close heroic, open it again and trigger re-login

**Comment by rpstreef** [comment]
This is still happening on v2.7.1, just a minute ago after updating I tried to login via email with captcha afterwards. It still gives you the response as shown in the image of the OP.

**Comment by Mon-ius** [comment]
same problem for 3 weeks, tried to reset passwd, not works

**Comment by arielj** [comment]
Can you try with Heroic 2.10.0?

**Comment by arielj** [comment]
Closing this since there's no answer after my comment since november
