### ISSUE TITLE
[Feature Request] Downloading a native version of the game

### ISSUE THREAD

**Issue by atapfedora** [Heroic-Games-Launcher/HeroicGamesLauncher#255]
Greetings my friend! it always makes me sad downloading the windows version of the game on HGL because it always makes the performance worse on my computer than the native version. However, since I don't always have the money to buy games from Steam, Epic's free games are my hope for a little relaxation from my work. I just want to ask, are there any plans to add features to download the native version of the game?

**Comment by Flonky** [comment]
Epic currently only supplies the windows versions of the games

**Comment by flavioislima** [comment]
Exactly, so it is impossible for heroic to download the native version unfortunately 😕
