### ISSUE TITLE
[Bug] Starts but unable to open a window

### ISSUE THREAD

**Issue by Flonky** [Heroic-Games-Launcher/HeroicGamesLauncher#256]
**Describe the bug**
Heroic starts, spawns a process but doesnt open a window.

**To Reproduce**
1. Download the deb or appimage from the release section
2. chmod it, (install), run it
3. Nothing except the process spawning happens

**Expected behavior**
The heroic launcher window opens

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu 20,04 & Kubuntu 20.04
 - Version 1.5.6 & 1.5.5 (didnt test the others)
-  Game: - 
-  Wine/Proton version: -

**Additional context**
Tried it on an clean install of kubuntu and my main ubuntu. When starting via cli it starts but immediately end itself after.

**Image of the process but no window:**
![image](https://user-images.githubusercontent.com/64008721/111876098-3ab50e80-89f1-11eb-997d-2d5b66a1845a.png)

**Image of it starting and ending immediately on my main system**
(ignore the gtk errors, that just my system theme that shouldnt impact it)
![image](https://user-images.githubusercontent.com/64008721/111876177-ac8d5800-89f1-11eb-823b-d702859eae68.png)

**Comment by CronyAkatsuki** [comment]
I'm also having same problems.

**Comment by flavioislima** [comment]
Looking at it. Will release a fix soon.

**Comment by flavioislima** [comment]
After some time debugging I noticed that the issue is only with 1.5.6.
On Ubuntu 20.04 I can run both 1.5.4 and 1.5.5 deb and AppImage. Also cloning the repo and running locally it works.
So I'm checking which commit was responsible for the bug.

**Comment by flavioislima** [comment]
So this affects only new installs, but on any distros, no only ubuntu. Found a fix already.

**Comment by dlogvin** [comment]
Hey! Reopening the issue here. I got the same bug with the latest version, unfortunately. MACOS
