### ISSUE TITLE
Heroic detect only one GPU

### ISSUE THREAD

**Issue by Francehelder** [Heroic-Games-Launcher/HeroicGamesLauncher#2560]
### Describe the bug

I have two gpus on my laptop, but Heroic shows that it has one.

![image](https://user-images.githubusercontent.com/14970431/226232270-d3edc3ee-8905-4e33-81db-b4a7673f5d60.png)

### Add logs

```text
System Info:
Heroic Version: 2.6.2 Trafalgar Law
Legendary Version:  0.20.32 Dark Energy (hotfix #6)
GOGdl Version: 0.6

Electron Version: 22.2.0
Chrome Version: 108.0.5359.215
NodeJS Version: 16.17.1

OS: EndeavourOS KERNEL: 6.1.20-1-lts ARCH: x64
CPU: AMD Ryzen 5 3500U with Radeon Vega Mobile Gfx @2.1 GOVERNOR: schedutil
RAM: Total: 13.59 GiB Available: 4.1 GiB
GRAPHICS: GPU0: Picasso/Raven 2 [Radeon Vega Series / Radeon Vega Mobile Series] VRAM: 512MB  
PROTOCOL: x11

Game Settings: {
	"autoInstallDxvk": false,
	"autoInstallVkd3d": false,
	"preferSystemLibs": false,
	"maxSharpness": 2,
	"nvidiaPrime": false,
	"enviromentOptions": [],
	"wrapperOptions": [],
	"savesPath": "",
	"showFps": false,
	"showMangohud": false,
	"targetExe": "",
	"useGameMode": false,
	"language": "",
	"wineVersion": {
		"bin": "/home/francehelder/.local/share/Steam/steamapps/common/Proton - Experimental/proton",
		"name": "Proton - Proton - Experimental",
		"type": "proton"
	},
	"winePrefix": "/home/francehelder/Games/Heroic/Prefixes/AmongUs",
	"eacRuntime": false,
	"battlEyeRuntime": false,
	"gogSaves": []
}

Game launched at: Mon Mar 20 2023 00:05:25 GMT-0300 (Horário Padrão de Brasília)

Legendary's config from config.ini (before Heroic's settings):
{
  "game_parameters": [],
  "game_executable": "Among Us.exe",
  "game_directory": "/home/francehelder/Games/Heroic/AmongUs",
  "launch_command": [
    "wine"
  ],
  "working_directory": "/home/francehelder/Games/Heroic/AmongUs",
  "user_parameters": [],
  "environment": {},
  "pre_launch_command": "",
  "pre_launch_wait": false
}

Launch Command: LD_PRELOAD= STEAM_COMPAT_CLIENT_INSTALL_PATH=/home/francehelder/.steam/steam STEAM_COMPAT_DATA_PATH=/home/francehelder/Games/Heroic/Prefixes/AmongUs PROTON_NO_ESYNC=1 PROTON_NO_FSYNC=1 STEAM_COMPAT_APP_ID=0 SteamAppId=0 SteamGameId=heroic-AmongUs PROTON_LOG_DIR=/home/francehelder /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary launch 963137e4c29d4c79a81323b8fab03a40 --language pt_BR --no-wine --wrapper "'/home/francehelder/.local/share/Steam/steamapps/common/Proton - Experimental/proton' run" 

Game Log:
[cli] INFO: Logging in...
[Core] INFO: Trying to re-use existing login session...
[cli] INFO: Checking for updates...
[Core] INFO: Getting authentication token...
[cli] INFO: Launching 963137e4c29d4c79a81323b8fab03a40...
wineserver: using server-side synchronization.
wine: RLIMIT_NICE is <= 20, unable to use setpriority safely
[S_API] SteamAPI_Init(): SteamAPI_IsSteamRunning() did not locate a running instance of Steam.
[S_API FAIL] SteamAPI_Init() failed
```

### Steps to reproduce

2. Click on '...'
3. Scroll down to '...'

### Expected behavior

Detect two gpus 

### Heroic Version

Latest Stable

### System Information

Mesa version is 22.3.6
![image](https://user-images.githubusercontent.com/14970431/226236529-b5e2d015-29c0-48b9-9056-ed5f642c746b.png)

**Comment by arielj** [comment]
Can you try with something like Mongohud to see what games detect? if heroic can't see 2 GPUs but gems do then you don't have any issue, we use what the system reports to us but that has no effect on games from the heroic side

**Comment by Francehelder** [comment]
Tomb Raider Setup detect both GPUs

![image](https://user-images.githubusercontent.com/14970431/226239918-b5564afe-236e-4bac-9b94-3e0e8cf301e1.png)

I runned the benchmark with each of it

AMD Radeon 540X:
![image](https://user-images.githubusercontent.com/14970431/226240487-8682d9ea-00fc-4880-a5b9-80fdb82f1493.png)

AMD Radeon Vega 8:
![image](https://user-images.githubusercontent.com/14970431/226240551-f91675d5-3e71-4348-a5a6-f8e6ca0dc78d.png)

But, the choose does nor persists on setup:

https://user-images.githubusercontent.com/14970431/226241473-f7b80ba6-c612-4217-8d98-5c3e135550b5.mp4

**Comment by arielj** [comment]
heroic not detecting the GPU is no a problem then (we use https://github.com/sebhildebrandt/systeminformation, so maybe it's a bug to report in that project)

the game not preserving that information is unrelated to this, I'd recommend asking for help about that in our discord (github issues are only for issues with heroic itself, not for support with games). join our discord and create a thread with the game issue in `#-support` and you'll get more answers
