### ISSUE TITLE
Library header overlaps search suggestions

### ISSUE THREAD

**Issue by arielj** [Heroic-Games-Launcher/HeroicGamesLauncher#2561]
### Describe the bug

![image](https://user-images.githubusercontent.com/188464/226465926-4945b1a3-ff28-4e62-9a2d-31028be6b336.png)

### Add logs

```text
not relevant
```

### Steps to reproduce

1. Start searching something

### Expected behavior

The suggestions should be OVER the header, not below.

### Heroic Version

main branch from GitHub

### System Information

not relefant

### Additional information

this is a regression in the main branch, not present in stable

**Comment by Etaash-mathamsetty** [comment]
when did this happen??
