### ISSUE TITLE
Scroll bars scroll down continuously when controller support enabled

### ISSUE THREAD

**Issue by Richard-Payne** [Heroic-Games-Launcher/HeroicGamesLauncher#2568]
### Describe the bug

Whenever a scrollbar is visible in the app, it scroll down with no input from me.  Inputting scroll up commands with my mouse scroll wheel can force it to scroll up but as soon as I stop inputs, it starts going down again.  

I found, on a hunch, that turning off the controller support fixed the issue. 

I have a Steam Controller and a Logitech G29 Wheel plugged in.   Both work perfectly in games.  Neither seem to operate the Heroic UI as far as I can tell.  Something in the controller support code is reading a continuous down input from somewhere, but I'm not sure where.

### Add logs

```text
(18:59:06) INFO:    [Connection]:       Connectivity: check-online
(18:59:06) INFO:    [Connection]:       Pinging external endpoints
(18:59:06) INFO:    [Legendary]:        Running command: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary --version
(18:59:06) INFO:    [Legendary]:        Legendary location: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary
(18:59:06) INFO:    [Gog]:              GOGDL location: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl
(18:59:06) INFO:    [Gog]:              GOGDL location: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl
(18:59:06) WARNING: [Backend]:          Protocol already registered.
(18:59:06) INFO:    [Connection]:       Connectivity: online
(18:59:06) INFO:    [Backend]:          User Not Found, removing it from Store
(18:59:06) INFO:    [Gog]:              Running command: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --version
(18:59:06) INFO:    [Backend]:          AreWeAntiCheatYet data downloaded
(18:59:06) INFO:    [Backend]:          Loading Screen Ready
(18:59:06) INFO:    [Backend]:          Frontend Ready
(18:59:06) INFO:    [Backend]:          Checking for new Heroic Updates
(18:59:06) INFO:    [Backend]:          Checking for current version changelog
(18:59:06) INFO:    [Backend]:          

Heroic Version: 2.6.2 Trafalgar Law
Legendary Version:  0.20.32 Dark Energy (hotfix #6)
GOGdl Version: 0.6

Electron Version: 22.2.0
Chrome Version: 108.0.5359.215
NodeJS Version: 16.17.1

OS: ManjaroLinux KERNEL: 6.1.19-1-MANJARO ARCH: x64
CPU: AMD Ryzen 7 5800X 8-Core Processor @3.8 GOVERNOR: schedutil
RAM: Total: 62.73 GiB Available: 39.17 GiB
GRAPHICS: GPU0: NVIDIA GeForce RTX 3060 VRAM: 12288MB DRIVER: 525.89.02 
PROTOCOL: x11

(18:59:08) INFO:    [Winetricks]:       Downloading Winetricks
(18:59:11) INFO:    [Backend]:          Starting the Download Queue
(18:59:19) INFO:    [Backend]:          Heroic: Setting disableController to true
(19:00:02) INFO:    [Backend]:          Heroic: Setting defaultSteamPath to "/home/richard/Games/Steam"
(19:00:18) INFO:    [Legendary]:        Logging in: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary auth --code <redacted>
(19:00:19) INFO:    [Frontend]:         Refreshing Library
(19:00:19) INFO:    [Legendary]:        Refreshing library...
(19:00:19) INFO:    [Legendary]:        Refreshing Epic Games...
(19:00:19) INFO:    [Legendary]:        Game list updated, got 9 games & DLCs
(19:00:19) INFO:    [Frontend]:         No cache found, getting data from legendary...
(19:00:19) INFO:    [Legendary]:        Refreshing library...
(19:00:19) INFO:    [Legendary]:        Game list updated, got 9 games & DLCs
(19:00:19) INFO:    [Frontend]:         Force Update
(19:00:19) INFO:    [Legendary]:        Running command: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary list --third-party
```

### Steps to reproduce

1. Go to settings
2. Enable Controller support

### Expected behavior

Scrollbars should need input from me to move.

### Heroic Version

Latest Stable

### System Information

Electron Version: 22.2.0
Chrome Version: 108.0.5359.215
NodeJS Version: 16.17.1

OS: ManjaroLinux KERNEL: 6.1.19-1-MANJARO ARCH: x64
CPU: AMD Ryzen 7 5800X 8-Core Processor @3.8 GOVERNOR: schedutil
RAM: Total: 62.73 GiB Available: 39.17 GiB
GRAPHICS: GPU0: NVIDIA GeForce RTX 3060 VRAM: 12288MB DRIVER: 525.89.02 
PROTOCOL: x11

**Comment by arielj** [comment]
can you test your controller in https://gamepad-tester.com and share what you see there?

**Comment by Richard-Payne** [comment]
Interesting.  It detects both devices.  

1) Steam Controller: no button pushes or axis changes picked up at all.
2) G29: Buttons are detected.  Wheel movement is not.  Pedal movement is, and being pedals are biased to 1.000 at rest, moving to -1.000 fully depressed.

The odd thing is, I did consider the pedals when testing and they did not appear to affect the scroll behaviour.

**Comment by Richard-Payne** [comment]
ok, now the issue is seeming to track with the wheel being set as the active controller in the Manjaro Game Controller settings window.

However, pressing the pedals does not seem to stop or reverse the scrolling behaviour.

**Comment by arielj** [comment]
what we can do is ignore the G29 completely when processing gamepad input, it won't work to control heroic but I doubt anyone would want a wheel to control a UI

can you share a screenshot of the G29 test? I would need some numbers/ids from that page to detect that controller properly

**Comment by Richard-Payne** [comment]
![image](https://user-images.githubusercontent.com/6730730/227748365-648ab6f0-8a14-41d0-8805-ddc46fc03be4.png)

**Comment by arielj** [comment]
hey @Richard-Payne, can you try the AppImage build from here https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/actions/runs/4522412576?pr=2570 ? it should allow you to use the xbox controller and should ignore the wheel

**Comment by Richard-Payne** [comment]
Tried the linked appimage.  It did does indeed seem to ignore the G29.  The Steam Controller is not working.

**Comment by arielj** [comment]
can you try one more thing? when you open the appImage, right click the tray icon > debug, that should open devtools

go to the `console` tab and then move the steam controller, is there any message in the console?

**Comment by Richard-Payne** [comment]
There are no messages in the console.

**Comment by arielj** [comment]
> There are no messages in the console.
hmmm weird, I'll try to make a new build later today with more logs and ping you back

**Comment by arielj** [comment]
hi @Richard-Payne can you try the AppImage from this link? https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/actions/runs/4559999182

and do the same, right click tray > debug > then move your controllers, I hope it should log at least something now
