### ISSUE TITLE
Search suggestions/autocomplete shows DLCs but then picking them shows no results

### ISSUE THREAD

**Issue by arielj** [Heroic-Games-Launcher/HeroicGamesLauncher#2575]
### Describe the bug

When using the search, a dropdown with suggestions/autocomplete appears. The results include DLCs. When selecting a DLC, since DLCs are not actually displayed in the library, the library shows no results.

![image](https://user-images.githubusercontent.com/188464/227811318-fdaca678-3b67-4872-ada0-92e5f5e599e0.png)

![image](https://user-images.githubusercontent.com/188464/227811332-eca29bfe-728c-4bd2-8cfb-1fe5483af18d.png)

### Add logs

```text
Nothing relevant
```

### Steps to reproduce

1. Search for something that could be part of a DLC name
2. Select the DLC in the suggestions

### Expected behavior

DLCs should not show up as suggestions.

### Heroic Version

Latest Stable

### System Information

Not relevant

**Comment by amanx123** [comment]
Would like to work on this. Assign me please

**Comment by arielj** [comment]
hey @amanx123, any update on this? if you can't work on this I can unassign you in case somebody else wants to take this

**Comment by arielj** [comment]
@amanx123 I included a fix for this in a PR with other fixes too, so no need to work on it anymore

**Comment by arielj** [comment]
This got fixed in 2.9.1, DLCs don't show up as suggestions
