### ISSUE TITLE
Heroic doesn't recognize that game supports cloud saves

### ISSUE THREAD

**Issue by RikudouSage** [Heroic-Games-Launcher/HeroicGamesLauncher#2589]
### Describe the bug

Heroic doesn't recognize that a game (*Heroes of Might & Magic V: Tribes of the East*) supports cloud saves even though it does - it's listed on the [store page](https://www.gog.com/en/game/heroes_of_might_and_magic_5_bundle) and it does synchronize saves in GOG Galaxy.

My gut feeling is this happens because the game is only accessible as part of a bundle and not separately.

### Add logs

```text
(18:58:23) INFO:    [Backend]:          Launching Heroes of Might and Magic V - Tribes of the East (1207661193)
(18:58:23) INFO:    [Backend]:          Checking if wine version exists: Proton - Proton-GE-Proton7-53
(18:58:24) INFO:    [Backend]:          Checking if wine version exists: Proton - Proton-GE-Proton7-53
(18:58:24) WARNING: [Backend]:          You are using Proton, this can lead to some bugs. Please do not open issues with bugs related to games
(18:58:24) INFO:    [Backend]:          Checking if wine version exists: Proton - Proton-GE-Proton7-53
(18:58:24) INFO:    [Backend]:          Checking if wine version exists: Proton - Proton-GE-Proton7-53
(18:58:24) DEBUG:   [Backend]:          Running Wine command: run wineboot --init
(18:58:25) INFO:    [Gog]:              Launching Heroes of Might and Magic V - Tribes of the East: STEAM_COMPAT_CLIENT_INSTALL_PATH=/home/username/.var/app/com.heroicgameslauncher.hgl/.steam/steam STEAM_COMPAT_DATA_PATH="/home/username/Games/Heroic/Prefixes/Heroes of Might and Magic V - Tribes of the East" PROTON_NO_ESYNC=1 PROTON_NO_FSYNC=1 STEAM_COMPAT_APP_ID=0 SteamAppId=0 SteamGameId="heroic-Heroes of Might and Magic V - Tribes of the East" PROTON_LOG_DIR=/home/username/.var/app/com.heroicgameslauncher.hgl /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl launch "/home/username/Games/Heroic/Heroes of Might and Magic V - Tribes of the East" 1207661193 --no-wine --wrapper "'/home/username/.var/app/com.heroicgameslauncher.hgl/config/heroic/tools/proton/Proton-GE-Proton7-53/proton' run" --platform windows
(18:58:34) INFO:    [Backend]:          Stopping Display Power Saver Blocker
(18:58:34) INFO:    [Frontend]:         Refreshing Library
(18:58:34) INFO:    [Gog]:              Getting GOG library
(18:58:35) INFO:    [Gog]:              Number of library pages: 2
(18:58:35) INFO:    [Gog]:              Getting data for page 2
(18:58:36) INFO:    [Gog]:              Getting data for page 2
(18:58:36) INFO:    [Gog]:              Saved games data
```

### Steps to reproduce

1. Open Heroic
2. Install `Heroes of Might & Magic V: Tribes of the East`
3. The game reports sync saves is unsupported

### Expected behavior

Sync save works

### Screenshots

![Screenshot from 2023-04-01 19-01-58](https://user-images.githubusercontent.com/13106547/229304627-40434924-96eb-4ab4-9631-07d6ea164384.png)

### Heroic Version

Latest Stable

### System Information

- OS: Linux Mint 21.1 (installed through Flatpak)

**Comment by imLinguin** [comment]
Try clearing Heroic cache and restart Heroic

**Comment by RikudouSage** [comment]
Just did, didn't help.

**Comment by imLinguin** [comment]
Then you can try to manually remove `/home/username/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/library.json`

**Comment by RikudouSage** [comment]
Still the same.

**Comment by imLinguin** [comment]
Could you try the build from main branch to verify that this wasn't fixed already?  
https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/actions/runs/4583737548

**Comment by RikudouSage** [comment]
It seems to work in that build.

**Comment by imLinguin** [comment]
Great, it will be released in a few days as stable
