### ISSUE TITLE
Discord Rich Presence information

### ISSUE THREAD

**Issue by LukeVader-IV** [Heroic-Games-Launcher/HeroicGamesLauncher#259]
**Is your feature request related to a problem? Please describe.**
Rich presence is a cool feature in discord but it doesn't work natively under wine as it's proprietary software 

**Describe the solution you'd like**
using a solution like https://github.com/0e4ef622/wine-discord-ipc-bridge would make the gaming experience just a little closer to native windows, showing your friends more information about what you're playing, maybe using a toggle that needs to be enabled as Discord is proprietary software and shouldn't be enabled by default

**Additional context**
what RL shows under windows:
![Screenshot from 2021-03-21 17-05-47](https://user-images.githubusercontent.com/15455108/111911937-6373ed00-8a5f-11eb-9f64-82a53e7e1c77.png)

What RL show under wine:
![Screenshot from 2021-03-21 17-00-40](https://user-images.githubusercontent.com/15455108/111911939-640c8380-8a5f-11eb-9b35-a6db2134e8c7.png)

**Comment by ElJdP** [comment]
u do be gay

**Comment by adityaruplaha** [comment]
@EIJdP don't do that again.

**Comment by flavioislima** [comment]
Hi! I don't really know how to solve this. this should be done on Heroic? on Discord? I have no clue. I'm not that familiar with Discord shinanigans tbh, don't even know how to activate this on my profile to show the game I'm playing. So maybe try to post this on our Discord and we can have a better clue on how to solve this.

**Comment by LukeVader-IV** [comment]
As it specifies on the GitHub README:

> # Usage
>
>Just run this program first, wait for it to start listening to the pipe, and then launch your program/game. The two programs need to be running under the same wineprefix. If you're using Steam Play/Proton, download and follow the instructions in **winediscordipcbridge-steam.sh.**

I know this wouldn't be hard to do under wine where you could just launch the .exe and wait for a specific output to run the main game within the same wineprefix but not 100% sure how you would go about doing this with Legendary, as i know Heroic at the moment just runs **"Legendary Launch {Game}"** to run a game

If everything runs within the same wineprefix you could simply use wine (or any modified version of wine) to run the .exe, and then following with **"Legendary Launch {Game}"**, once the desired output was recorded

**Comment by LukeVader-IV** [comment]
Update: I tested it and it really is as simple as running the provided .exe first and then running wine, it also works with the current implementation in heroic, you can run the .exe in wine and then just run a game from heroic with the same wine version.

One little issue, it doesn't show any information for me but that might be because there's no official support for my distro and i had to build and install a community .rpm package

**Comment by LukeVader-IV** [comment]
maybe have an option where it runs "wine ~/path/to/file/winediscordipcbridge.exe" and listens for "Pipe Server: Main thread awaiting client connection on \\.\pipe\discord-ipc-0" before continuing with what it does now. and the equivalent for wine versions like proton. (again, this should be an option that is disabled by default in my opinion)

maybe an idea would be to have an advanced options page where a user can modify this command and what it listens for

PS: I was thinking of making a Github project to enable rich presence on unsupported games, so that you can see things like, for example, what game mode someone is in in rocket league even though it's not natively supported, or on what level you are in overcooked

**Comment by flavioislima** [comment]
If we need to modify the wine conmand, then it is not possible to do it on heroic since legendary is responsible for launching the games and to call wine.

**Comment by LukeVader-IV** [comment]
as i already said, you would simply run the same command but if the option is active it would run the .exe first (in wine or proton) and then do just the same thing, no changes to the actual game and how it launches.

**Comment by flavioislima** [comment]
So then, if we need to touch the exe, then we cannot do anything, because heroic doesn't run wine exe, like lutris does for instance. We run `legendary launch 'game'`, because we use Legendary to launch the games and Legendary is the one that call wine with the exe.

Otherwise, you can test yourself.
Run Heroic from the terminal, run a game, copy the launch command. With the launch command, add the wrapper around it, and check if discord shows the right information. If it works, then we can do it in Heroic, otherwise, this should be a feature request on Legendary.

**Comment by flavioislima** [comment]
I think if this PR is merged on Legendary, it would work.
I just don't know if we would need to do something on our side though.

**Comment by TabulateJarl8** [comment]
I don't believe you guys would need to change anything. Except one thing that comes to mind that did change when I created the rich presence is that the legendary process is now blocking, as opposed to before when it wasn't blocking. Not sure if that would break anything with your app

**Comment by adityaruplaha** [comment]
@TabulateJarl8 yeah thanks for the heads up, some parts will need fixing I guess.

**Comment by TabulateJarl8** [comment]
As you may have seen, they closed my Pull Request so it won't be added to legendary itself

**Comment by adityaruplaha** [comment]
@TabulateJarl8 mind joining us over on Discord? I'll try to design an implementation in Heroic based on yours.

https://yarnpkg.com/package/discord-rpc

I'm looking at this, it shouldn't be too much work to make it work.

**Comment by flavioislima** [comment]
@LukeVader-IV 
Have you checked this tutorial here?
https://github.com/ValveSoftware/Proton/wiki/Enabling-Discord-Rich-Presence

This is for Proton, but if we need all of this, I don't really know how could Heroic or Legendary deal with it.

**Comment by TabulateJarl8** [comment]
I believe I've added support for discord RPC in #429

**Comment by dragonDScript** [comment]
This is easy to implement. When a game is started, start the rich presence. When legendary stops, stop it.

I can work on this in the future

**Comment by adityaruplaha** [comment]
One problem. Legendary is non-blocking.

**Comment by pktiuk** [comment]
![image](https://user-images.githubusercontent.com/45544416/200136867-eee1f248-bbd2-4124-a290-0e211f43da83.png)

Is it how DIscord rich presence is supposed to work?   
I would expect game title instead of just `Heroic Games Launcher`  

I play Disco Elysium from GOG.

**Comment by imLinguin** [comment]
You would need to forward the presence from wine prefix with tool like https://github.com/0e4ef622/wine-discord-ipc-bridge

**Comment by pktiuk** [comment]
I thought the point of implementing this feature is to automate this process.    
______________
Oh I see it now.

![image](https://user-images.githubusercontent.com/45544416/200137223-b89c4d37-835b-4a90-929c-29d60ee872ac.png)

Game title is placed in description of activity.
