### ISSUE TITLE
Remove focus after game ends

### ISSUE THREAD

**Issue by JakubFojtik** [Heroic-Games-Launcher/HeroicGamesLauncher#2594]
### Feature description

Can you please remove the launcher window focus after closing a game? Or tell me where in source i could toggle it myself?
Is it intentional or a side effect?

**Comment by theli-ua** [comment]
It is indeed annoying for heroic to pop up from tray after you close the game

**Comment by Zorrototo** [comment]
Please an update on that, is it intended? Can you add a setting to disable that behavior if it is intended?

**Comment by arielj** [comment]
A fix for this will be included in the next release
