### ISSUE TITLE
Manual cloud save download fails - Read-only file system

### ISSUE THREAD

**Issue by esmorun** [Heroic-Games-Launcher/HeroicGamesLauncher#2597]
### Describe the bug

When attempting to do a cloud sync to download saved games I'm getting an error saying that {UserSavedGames} is a read only file system.

I tried giving the Flatpak full filesystem access (filesystem=host) via the Seal app, but it didn't solve the issue.

Here's the permissions I see on the save folder:

```
# owner: myuser
# group: mygroup
user::rwx
group::r-x
other::r-x
```

I tried to add write permissions to other, but it didn't solve the problem:
`chmod o+w -R ~/Games/Heroic/Prefixes/PREY/pfx/drive_c/users/steamuser/Saved\ Games/Arkane\ Studios/Prey_Epic/1286def5317b49a683cf5cb418dda73d/`

### Add logs

```text
[Core] INFO: Trying to re-use existing login session...
[cli] INFO: Got 4 remote save game(s)
[cli] INFO: Checking "PREY" (52d88e9a6df248da913c8e99f1e4c526)
[cli] INFO: Overriding save path with "{UserSavedGames}/Arkane Studios/Prey_Epic/{EpicID}/"...
[cli] INFO: Cloud save for "PREY" is newer:
[cli] INFO: - Cloud save date: 2023-02-12 22:50:42
[cli] INFO: - Local save date: N/A
[cli] INFO: Downloading remote savegame...
[Core] INFO: Deleting old save files...
[Core] INFO: Downloading "52d88e9a6df248da913c8e99f1e4c526/manifests/2023.02.12-22.50.42.manifest"...
Traceback (most recent call last):
  File "legendary/cli.py", line 3061, in <module>
  File "legendary/cli.py", line 2988, in main
  File "legendary/cli.py", line 537, in sync_saves
  File "legendary/core.py", line 1065, in download_saves
  File "os.py", line 215, in makedirs
  File "os.py", line 215, in makedirs
  File "os.py", line 215, in makedirs
  [Previous line repeated 2 more times]
  File "os.py", line 225, in makedirs
OSError: [Errno 30] Read-only file system: '{UserSavedGames}'
[214] Failed to execute script 'cli' due to unhandled exception!
```

### Steps to reproduce

1. Click the settings button on an Epic game.
2. Expand "Cloud Saves Sync"
3. Hit the Sync button (with Download selected in the combobox)

### Expected behavior

I expect Heroic to have write access so that it can save the downloaded files in my ~/Games/Heroic folder.

### Heroic Version

Latest Stable

### System Information

- OS: Ubuntu 22.10

**Comment by esmorun** [comment]
> Does, this issue exist on 2.7.0? i having this issue on 2.6.3 but after updating to 2.7.0 issue no longer exists, update heroic or just write path to game save folder mannualy.

Just got the update to 2.7.0, the issue still exists. What do you mean by write the path manually? I see no option to modify the save folder path :)

**Comment by Dandraghas** [comment]
> 
> What do you mean by write the path manually? I see no option to modify the save folder path :)

there is small button with '⌫' symbol, click on it:
![image](https://user-images.githubusercontent.com/91272905/230287122-276381e1-7aa4-48e9-b45f-78d2d1036140.png)

after clicking that, there will be '🗀' button press on it:
![image](https://user-images.githubusercontent.com/91272905/230287429-c5f133f6-f48e-40ae-bf94-1766bc86f6fb.png)
and then select path to save game folder, in your situation it: `/Games/Heroic/Prefixes/PREY/pfx/drive_c/users/steamuser/Saved\ Games/Arkane\ Studios/Prey_Epic/`
