### ISSUE TITLE
Make changelog header static

### ISSUE THREAD

**Issue by JordanPlayz158** [Heroic-Games-Launcher/HeroicGamesLauncher#2609]
### Problem description

When I scroll through the changelog, once I scroll to the bottom (reach the end), I would like to be able to close it without needing to scroll to the top again. I think this makes sense as that is the flow that feels natural (opinionated but I think this is present in many applications).

### Feature description

Make it so the header (which has the X button) does not scroll up with the main body (the changelog itself) so it can be exited out at any point.

### Alternatives

If not already present, allow clicking outside of the changelog box to also close the box as the X button would.

**Comment by flavioislima** [comment]
In case you don't know you can just click outside the modal and it will close. All modals can be closed like this on Heroic.

**Comment by JordanPlayz158** [comment]
Yeah, I did notice this by accident, I think the reason it was not obvious to me is because when I see an X button, I assume the reason it is there as that is the way to close it, perhaps if we remove the X or make the header static it could be better or maybe I'm just not the normal user and these trends of having an X button but also being able to close by clicking the unfocused/overlay area is just a known thing now but if we do have the X, I do ultimately feel the expected behavior is for the header to stay always at the top

**Comment by arielj** [comment]
I think the X should be static, I think it makes it easier to get there when using a controller
