### ISSUE TITLE
Please add support for .desktop executables downloaded from the Discover app store

### ISSUE THREAD

**Issue by bric0096** [Heroic-Games-Launcher/HeroicGamesLauncher#2616]
### Problem description

As a user i would like to have support for Steam OS apps downloaded from the Discover app store with the .desktop extension. Currently Heroic only support the .AppImage extension for adding Linux apps

### Feature description

Please add support for executables with the .desktop extension in Steam OS

**Comment by Nocccer** [comment]
I don't understand the problem. On steam os you make sure the game runs on desktop mode. If so you click on the game to get to the game page and click the three dots. There should be add to steam. Switch to game mode and your game is added there

**Comment by bric0096** [comment]
![image](https://user-images.githubusercontent.com/106574762/230779207-8c3e6c40-1340-4356-9094-01567dc94f76.png)

this window when the platform selected is Linux, the Select Executable only works with .AppImage files, was hoping it will also work with a .desktop extension

add to steam definitely works but heroic has steamgriddb integration for the posters

**Comment by atomic1fire** [comment]
There is a decky plugin for Steamgriddb, if you're willing to install decky.

**Comment by bric0096** [comment]
ill try the decky plugin, thanks for your replies
