### ISSUE TITLE
GTA V Stuck at "Entering Story Mode"

### ISSUE THREAD

**Issue by eggsy** [Heroic-Games-Launcher/HeroicGamesLauncher#2618]
### Describe the bug

I have downloaded GTA V over the launcher and everything went perfect. I logged into my Rockstar Games account and game showed up, I was really excited to see it working. But for some reason, on initial load where it forces you to play the first campaign, it stucks in the loading screen.

I have been searching for almost 3 hours, I've tried installing Rockstar Games Launcher in a CrossOver bottle, which didn't even let me open the launcher, it was just stuck like that in "Application Not Responding", I couldn't even see the game launching when I used a CrossOver bottle.

I tried verifying, setting a key called `ServicesPipeTimeout` in somewhere in the registry editor, basically, I've tried everything I could possibly find online. I just couldn't get it working. I left it for 30+ minutes and it still didn't load anything. Idk if it's RSG Launcher or HG Launcher related but I just want to see if anyone else is experiencing the same issue?

### Add logs

```text
https://pastebin.com/raw/tSFHZneC
```

### Steps to reproduce

1. Download GTA V
2. Try to play it
3. See if you're able to pass the "entering story mode" loading screen

### Expected behavior

It should load and let me play the first campaign.

### Screenshots

<img width="802" alt="image" src="https://user-images.githubusercontent.com/13917975/230923217-fe4987ba-0011-4f18-8c4d-c737a2053ee8.png">

### Heroic Version

Latest Stable

### System Information

- OS macOS Ventura 13.1.1

**Comment by eggsy** [comment]
Just saw another issue closed since it wasn't related to the launcher itself, closing this as well and heading to Discord server instead.

**Comment by donnchawp** [comment]
I had this problem too, but I think enabling esync in the Heroic bottle in Crossover fixed it. When I started GTA V I saw the microphone permission dialogue and giving it permission, the game started correctly. :)

**Comment by Naozumi520** [comment]
@donnchawp's method works, and I found out the permission dialogue will appear only your SIP is enabled.
