### ISSUE TITLE
Games still in the download section and showing download percentage after being installed

### ISSUE THREAD

**Issue by cronyakatsuki** [Heroic-Games-Launcher/HeroicGamesLauncher#262]
**Describe the bug**
After a game has downloaded and getting the notification they are still in the downloading section.

**To Reproduce**
1. Install any game.
2. Check the downloading section.

**Expected behavior**
After a game has installed it shouldn't be showing in the downloading section and not have download percentage showing.

**Screenshots**
![Imgur](https://i.imgur.com/Q2xvSC8.png)

**Desktop (please complete the following information):**
 - OS: Manjaro
 - Version: Testing Repos
-  Game:
-  Wine/Proton version:

**Additional context**
After restarting the launcher it shows everything corectly.

**Comment by flavioislima** [comment]
I saw this happening a few times as well. The same thing happens when uninstalling sometimes. I think we need to improve the way we handle the game status on it.

**Comment by flavioislima** [comment]
@adityaruplaha I think this might have been fixed after your merge, right?

**Comment by adityaruplaha** [comment]
This was an existing issue?! I spent 4 hours thinking it was a bug on my branch! Oh well it should be fixed somewhat now.

**Comment by cronyakatsuki** [comment]
This problem seems to have stopped being a thing since the last release. But will test it out a bit more.

**Comment by flavioislima** [comment]
Confirmed it is fixed.
