### ISSUE TITLE
 Add Option to sort games by GameScore

### ISSUE THREAD

**Issue by Asharax** [Heroic-Games-Launcher/HeroicGamesLauncher#2623]
### Feature description

Add sorting buttons by game score. Game score can be sorted by OpenCritic/MetaCritic score by default.

### Alternatives

Could be sort by option that we can choose from list, which has: Rating/HowLongToBeat/Name/Status/etc... When one option is selected, the games are sorted by that option.

Another alternative: Maybe in the table layout, add sorting for the columns, instead of adding sort buttons for everything.

### Additional information

I would like to sort my games by scores so I can easily see the valuable games on my libraries. It's hard to navigate library of 300+ games. 
This feature could be more valuable after adding other stores to the heroic game launcher. 
Also having option to sort by how long to beat could be nice too.

**Comment by arielj** [comment]
the problem is that we don't have this information for all games, we have to query that info 1 game at a time and keep updating it over time if scores change

we currently just fetch the one game it's requested, fetching all the information for all games from the different sites would be overkill for performance

we could eventually do this if we have a service that can give us all this information in one request, but until that I would say this is feasible but not worth it for the bad impact in performance

maybe this can be reopened if somebody finds a way to fetch this information in only a few requests

**Comment by kmturley** [comment]
Looks like there is no official API. All the solutions I found work by scraping the html page:

For a single game such as:
https://www.metacritic.com/game/no-mans-sky/

Then run this in your JavaScript console to get the score:
`document.querySelector('.c-productScoreInfo_scoreNumber').querySelectorAll('span')[0].innerText`

Or for a browse page:
https://www.metacritic.com/browse/game/?releaseYearMin=1958&releaseYearMax=2024&page=1

You can run:
```
const items = document.querySelectorAll('.c-finderProductCard-game');
items.forEach(item => {
  const title = item.querySelector('.c-finderProductCard_title').getAttribute('data-title');
  const date = item.querySelector('.c-finderProductCard_meta').querySelectorAll('span')[0].innerText.replace(/\n/g, '').trim();
  const score = item.querySelector('.c-finderProductCard_score').querySelectorAll('span')[0].innerText;
  console.log(title, date, score);
});
```

Reasons why this is not a good solution:
- Requires knowing the url path to the game, which Heroic would not know upfront
- Requires loading the entire page content, just to grab a value
- When page content changes, it will break until someone updates the html selectors
- There is no way to return just the scores for a specific subset of games

**Comment by kmturley** [comment]
A better solution would be to precompute all the data required in a registry/database.

This would abstract all the complexity away from Heroic runtime, and move it to a separate process for indexing game data.

You could implement it like this:
- Create a separate GitHub repo e.g. `heroic-registry`
- Add a list of identifiers/mappings (steam ID, metacritic url, epic games id)
- Run in GitHub actions pipeline on a weekly basis
- For each identifier/mapping, load and collect data needed form API or site
- Store combine fields into json files and publish to `gh-pages` branch = GitHub site.

For example the script could generate:
/metacritic/no-mans-sky.json -> `{ "rating": 71 }`
/steam/275850.json -> `{ "rating": 6 }`

Or could combine data into a single file:
/games/no-mans-sky.json -> `{ "metacritic": 71 , steam: 6 ''}`

Just make sure that the naming and file/folder structure is deterministic for Heroic launcher to look up that data easily.

I did something similar for audio plugins here:
https://github.com/studiorack/studiorack-registry

If you're interested I could help prototype something!

**Comment by kmturley** [comment]
@Asharax Here is a quick prototype of my idea:
https://github.com/kmturley/games-database

Which generates:

- https://kmturley.github.io/games-database
- https://kmturley.github.io/games-database/red-dead-redemption.json

**Comment by kmturley** [comment]
Yes an API and database would allow combining of requests e.g:
`game-database.com/games?id=game-one&id=game-two&id=game-three`

but would have some downsides:

- Dedicated server/compute/hosting
- Bandwidth concerns/costs
- Security and protection against Ddos and abuse by other apps/services

My suggestion would avoid all that, and by pre-computing as static files, in theory the load times would be faster than an API for a 1:1 request.

When you load Heroic after logging into Stores, the library loads for awhile (presumably syncing each store and creating a local cache)
<img width="224" alt="Screenshot 2024-09-10 at 8 17 48 PM" src="https://github.com/user-attachments/assets/35dc5079-53f7-4884-9bd1-41a2aabbda34">

If at this step it made a request for a static file for each game, and stored the combined result locally, it would not add much to the load time of the library.

You could start by only showing ratings for games in view:
<img width="1181" alt="Screenshot 2024-09-10 at 8 27 31 PM" src="https://github.com/user-attachments/assets/dd49791e-2b40-47f9-87c9-3ebf3baa447c">

Then as the user scrolls, and Heroic loads cover images, also load ratings information.

**Comment by arielj** [comment]
but if you want to order by score you can't know which games are at the top when you sort by it if you don't have their scores, the library would keep moving around while you scroll down as new scores are fetch (or that sorting option would need to be disabled until you have all the scores for all games?)

there's users with libraries of over a thousand games, we can't trigger requests for each of those games using a github repo, github rate limiting will hit for sure (and we had users already expressing concerns about the amount of requests heroic does at boot, this fetching would have to be an opt-in feature too)

**Comment by kmturley** [comment]
I agree the sorting feature would not work well with the GitHub pages json approach.

Regarding Github limits. They have different usage limits for:
- [APIs](https://docs.github.com/en/rest/using-the-rest-api/rate-limits-for-the-rest-api)
- [Releases](https://docs.github.com/en/pages/getting-started-with-github-pages/about-github-pages#usage-limits)
- [Pages](https://docs.github.com/en/pages/getting-started-with-github-pages/about-github-pages#usage-limits)

My prototype is served from GitHub Pages:
"GitHub Pages sites have a soft bandwidth limit of 100 GB per month."

**Comment by Asharax** [comment]
@kmturley I previously forgot about this, on Keggle there are huge datasets that can provide us all of the required information, so we wouldn't have to crawl data for days. 

Applicable for Steam review and Metacritic scores. I'd assume the first dataset would suffice for this feature, what do you think?


https://www.kaggle.com/datasets/jummyegg/rawg-game-dataset/data

https://www.kaggle.com/datasets/antonkozyriev/game-recommendations-on-steam

**Comment by kmturley** [comment]
Interesting, i'm not sure how Kaggle works, but appears to be hosting datasets for data analysis, rather than live APIs for websites/apps. So likely the data would need to be loaded into a database somewhere and hosted.

The first dataset: https://www.kaggle.com/datasets/jummyegg/rawg-game-dataset/data
Hasn't been updated for awhile, but the Github page for it https://github.com/trung-hn/video-game-encyclopedia links to the API they used: https://rawg.io/apidocs RAWG could be a GREAT option as it says they have 500,000+ games and data including Metacritic ratings. It says free for non-commercial projects, so would have to check if Heroic would fall under that use-case?

The second dataset: https://www.kaggle.com/datasets/antonkozyriev/game-recommendations-on-steam
Is regularly updated. It has 50k games with their steam id and ratings. Wonder if this covers all the games heroic would need or not? I personally think metacritic ratings are more useful than Steam, so the RAWG option looks better.
