### ISSUE TITLE
Missing library 'libmspack' for 'cabextract' for winetricks in flatpak app

### ISSUE THREAD

**Issue by nickname76** [Heroic-Games-Launcher/HeroicGamesLauncher#2625]
### Describe the bug

Winetricks is not able to install dll components that require use of cabextract during install

### Add logs

```text
Executing load_xact 

grep: warning: stray \ before /

Executing cabextract -q -d /var/home/user/Games/Heroic/Prefixes/The Elder Scrolls V - Skyrim/pfx/dosdevices/c:/windows/temp -L -F *_xact_*x86* /var/home/user/.var/app/com.heroicgameslauncher.hgl/cache/winetricks/directx9/directx_Jun2010_redist.exe

cabextract: error while loading shared libraries: libmspack.so.0: cannot open shared object file: No such file or directory

------------------------------------------------------
warning: Note: command cabextract -q -d /var/home/user/Games/Heroic/Prefixes/The Elder Scrolls V - Skyrim/pfx/dosdevices/c:/windows/temp -L -F *_xact_*x86* /var/home/user/.var/app/com.heroicgameslauncher.hgl/cache/winetricks/directx9/directx_Jun2010_redist.exe returned status 127. Aborting.
------------------------------------------------------
```

### Steps to reproduce

1. Create prefix using proton-ge-proton
2. Run winetricks
3. Install xact dll

### Expected behavior

Winetricks installing xact

### Heroic Version

Latest Stable

### System Information

- OS: Linux Fedora 37 Workstation (Silverblue)

**Comment by Nocccer** [comment]
Cabeextract is in the flatpak included

**Comment by nickname76** [comment]
I want to add, that this issue only exists WHEN USING PROTON-GE-PROTON

**Comment by Xirious** [comment]
Hi all,

I get the same error when I try and install d3dx9. 

I have this issue with GoG Neverwinter Nights 2 and it is via Proton-GE-Proton7-53. 

I think it's a version error with Cabextract (i.e. try bumping the flatpak version to 1.11).

**Comment by flavioislima** [comment]
Fixing that for the latest release:
https://github.com/flathub/com.heroicgameslauncher.hgl/pull/75

**Comment by SuddenPineapple** [comment]
This is a problem again. Trying to get Gog Batman: Arkham Asylum to work but I get the same error when trying to install DXVK or D3Dx9
