### ISSUE TITLE
Error while upload the saves to the cloud (epic)

### ISSUE THREAD

**Issue by masterzion** [Heroic-Games-Launcher/HeroicGamesLauncher#2631]
### Describe the bug

It's not possible to sync Epic games saves to the cloud

### Add logs

```text
[Core] INFO: Trying to re-use existing login session...
[cli] INFO: Got 1 remote save game(s)
[cli] INFO: Checking "Control" (Calluna)
[cli] INFO: Overriding save path with "/home/deck/Games/Heroic"...
[cli] INFO: Local save for "Control" is newer
[cli] INFO: - Cloud save date: N/A
[cli] INFO: - Local save date: 2023-04-16 10:27:15
[cli] INFO: Uploading local savegame...
[SGH] INFO: Packing savegame for "Calluna", input folder: /home/deck/Games/Heroic
Traceback (most recent call last):
  File "legendary/cli.py", line 3061, in <module>
  File "legendary/cli.py", line 2988, in main
  File "legendary/cli.py", line 557, in sync_saves
  File "legendary/core.py", line 964, in upload_save
  File "legendary/utils/savegame_helper.py", line 118, in package_savegame
PermissionError: [Errno 13] Permission denied: '/home/deck/Games/Heroic/Control/dosdevices/com1'
[215] Failed to execute script 'cli' due to unhandled exception!
```

### Steps to reproduce

1. Go to 'Main menu'
2. Click on 'Settings of the Control game (Epic)'
3. Scroll down to 'Cloud Saves Sync'
4. Select upload
5. Click "Sync"
6. See error

### Expected behavior

it should upload the saves to the cloud

### Heroic Version

Latest Stable

### System Information

NAME="SteamOS"
PRETTY_NAME="SteamOS"
VERSION_CODENAME=holo
ID=steamos
ID_LIKE=arch
ANSI_COLOR="1;35"
HOME_URL="https://www.steampowered.com/"
DOCUMENTATION_URL="https://support.steampowered.com/"
SUPPORT_URL="https://support.steampowered.com/"
BUG_REPORT_URL="https://support.steampowered.com/"
LOGO=steamos
VARIANT_ID=steamdeck
BUILD_ID=20230313.1
VERSION_ID=3.4.6

### Additional information

Deck user is not assigned to the uucp group...
It will return a permission deny. 

(127)(deck@steamdeck ~)$ ls -lah /home/deck/Games/Heroic/Control/dosdevices/com1
lrwxrwxrwx 1 deck deck 10 Feb 23 16:30 /home/deck/Games/Heroic/Control/dosdevices/com1 -> /dev/ttyS0
(deck@steamdeck ~)$ ls -lah /dev/ttyS0
crw-rw---- 1 root uucp 4, 64 Apr 16 12:27 /dev/ttyS0
(deck@steamdeck ~)$

**Comment by Nocccer** [comment]
The save path looks wrong. Change it manually to the save path that is reported by pcgamingwiki for epic

**Comment by masterzion** [comment]
changed path to 
/home/deck/Games/Heroic/Control/drive_c/users/deck/AppData/Local/Remedy/Control/Default-Epic-User/

Seems working now
