### ISSUE TITLE
Cannot download saves from Epic Cloud save

### ISSUE THREAD

**Issue by merajmasuk** [Heroic-Games-Launcher/HeroicGamesLauncher#2634]
### Describe the bug

The save download progress seems stuck. 

The log says, "No chunks were available".

Tried finding the location of "legendary" on my PC but no result.

```
$ whereis legendary
legendary:
```

### Add logs

```text
[Core] INFO: Trying to re-use existing login session...
[cli] INFO: Got 12 remote save game(s)
[cli] INFO: Checking "Filament" (14a38161ad3c45adab18425415b5df3d)
[cli] INFO: Overriding save path with "/home/meraj/.wine-10/drive_c/users/meraj/Local Settings/Application Data/Filament/Saved/SavedGames"...
[cli] INFO: Cloud save for "Filament" is newer:
[cli] INFO: - Cloud save date: 2023-03-15 10:16:01
[cli] INFO: - Local save date: N/A

[cli] INFO: Downloading remote savegame...

[Core] INFO: Deleting old save files...
[Core] INFO: Downloading "14a38161ad3c45adab18425415b5df3d/manifests/2023.03.15-10.16.01.manifest"...
[Core] CRITICAL: No chunks were available, aborting. Try running "legendary clean-saves 14a38161ad3c45adab18425415b5df3d" and try again.
```

### Steps to reproduce

1. Go to a game that supports save sync.
2. Click on the option to the left of the 'Play' button under the game thumbnail.
3. Scroll down to 'Cloud Saves Sync' and expand.
4. Choose a directory as a save location.
5. Select sync option as 'Download'.
6. See error.

### Expected behavior

The save download should finish successfully.

### Screenshots

![image](https://user-images.githubusercontent.com/34513961/232538409-98a7fb11-8f04-43de-a4b6-26a90d26b677.png)

### Heroic Version

Latest Stable

### System Information

- OS: Pop!_OS 22.04 LTS
- Heroic version:  2.7.0

**Comment by arielj** [comment]
you can find the location of the legendary binary at the beginning of the logs in Settings > Logs

**Comment by merajmasuk** [comment]
> you can find the location of the legendary binary at the beginning of the logs in Settings > Logs

Thanks, I'll check an let you know

**Comment by merajmasuk** [comment]
> I do think this is not an issue of Heroic but of Legendary if you still have issues running it directly https://github.com/derrod/legendary

Confirmed this is not an issue with Heroic. Closing this issue. Thanks for your help.

**Comment by mertzi** [comment]
Hi! Did you ever manage to solve this? Because I can't find anything useful through google, reddit etc. I tried downloading Legendary but it is way above my pay grade to understand how to use it without a GUI such as Heroic. I really really don't want to install EGL, but I need to access cloud saves for a game (Maneater). I get a similar error message but not exactly the same, but I believe it is also a legendary and not a heroic issue.

**Comment by merajmasuk** [comment]
No, not really. I haven't got time to check out. I'll let you know when I do.

**Comment by kopach** [comment]
I've tried to run proposed `legendary clean-saves` command from within heroic flatpak and got steam credentials error
running `legendary auth` and  `legendary clean-saves` command again fixed the issue. Here are commands I had to run

``bash
flatpak run --command=bash com.heroicgameslauncher.hgl
legendary clean-saves <number-from-logs>
```
got `ValueError: No saved credentials` at this point

```bash
legendary auth
```

you have to follow instructions here and copy auth code/paste auth code as instructed

then run same `clean-saves` command again and exit
```bash
legendary clean-saves <number-from-logs>
exit
```

At this point - saves show no errors
