### ISSUE TITLE
Cannot add any games to steam

### ISSUE THREAD

**Issue by Durus-R** [Heroic-Games-Launcher/HeroicGamesLauncher#2637]
### Describe the bug

I just cannot add any games to my steam. 

Steam and HGL are both installed by flatpak.

### Add logs

```text
ERROR:   [Shortcuts]:        /home/rene/.steam/steam/userdata does not contain a valid user directory!
```

### Steps to reproduce

1. Go to 'Game Page'
2. Click on '...'
3. Click on "Add to steam"

### Expected behavior

It adds the game to steam.

### Screenshots

![grafik](https://user-images.githubusercontent.com/68396806/232600599-619aa146-6278-4d98-8ac7-09fe03d329b6.png)

### Heroic Version

Latest Stable

### System Information

- OS [e. g. "Ubuntu"]: Vanilla OS (based on Ubuntu)

**Comment by Nocccer** [comment]
Check that this folder exist. If so change the permission once to root and back to user. This fixed it for someone on steamdeck

**Comment by Durus-R** [comment]
no, works not.

**Comment by Durus-R** [comment]
Should I maybe change the steam runtime?

**Comment by Durus-R** [comment]
And what about this? https://github.com/redromnon/HeroicBashLauncher

**Comment by Nocccer** [comment]
Probably i would recommend steam as deb and everything should work. For steam flatpak you need to set the correct path to the steam flatpak folder. I can post some example path tomorrow.

You also need to probably set permission via flatseal so heroic and steam can interact with each other

**Comment by Durus-R** [comment]
It worked now, after creating a folder with my user ID in .steam/steam/userdata .
But, steam did not recognized them until I dropped these files in ~/.var/app/com.valvesoftware.Steam/data/Steam/userdata/USERID/config

**Comment by Durus-R** [comment]
Editing the steam path worked for me, although, it did not set the correct logo. But i will create a new issue for that.

**Comment by tristann21** [comment]
Getting the same issue on Fedora Kinoite (another immutable distro as OP was using Vanilla I believe)

Would be nice if Heroic automatically saw and detected the flatpak version of Steam so it would work better, cheers!

**Comment by miguelcouteirorodrigues** [comment]
> Editing the steam path worked for me, although, it did not set the correct logo. But i will create a new issue for that.

I managed to fix that by using Flatseal to add the flatpak Heroic's path to the list of directories flatpak Steam has access to:

![imagem](https://github.com/user-attachments/assets/b8d9fe9d-906d-46e1-bde2-d20eb5cc2605)

**Comment by xfechx** [comment]
I have also this problem. Heroic does not add games to steam, when adding them, the spinner keeps moving and they are not added to Steam.

**Comment by VinterSolen** [comment]
I get the same error, just now when i installed epic Borderlands 3

/home/stefan/.steam/steam/userdata does not contain a valid user directory!

**Comment by arafath45-dev** [comment]
It is fixed for me. I have set the Default steam path in Heroic launcher to `/var/home/USERID/.var/app/com.valvesoftware.Steam/.steam/steam/`

The flatpak keeps steam data files here.
