### ISSUE TITLE
Quit on Ctrl+Q

### ISSUE THREAD

**Issue by kra-mo** [Heroic-Games-Launcher/HeroicGamesLauncher#2640]
### Problem description

Ctrl+Q has become the de facto standard for quitting graphical Linux applications. Heroic does not support this.

### Feature description

The application should quit upon pressing Ctrl+Q.

**Comment by 2022H1030042G** [comment]
Hi, I would like to work on it. Is it available?

**Comment by flavioislima** [comment]
> Hi, I would like to work on it. Is it available?

Yes

**Comment by 2022H1030042G** [comment]
@flavioislima  Can you give some details like where the changes are required and how can I implement it?

**Comment by flavioislima** [comment]
> @flavioislima  Can you give some details like where the changes are required and how can I implement it?

I think that you first need to look where we are defining the tray menu items. Then register an accelerator (shortcut) for the quit item.

You can learn more on the electron docs.

**Comment by CharlExMachina** [comment]
Isn't that already declared, though? I was browsing through the code looking at the part you're mentioning, and found this on `tray_icon.ts`, line 126 onwards:

```
    {
      click: function () {
        handleExit()
      },
      label: i18next.t('tray.quit', 'Quit'),
      accelerator: platform === 'darwin' ? 'Cmd+Q' : 'Ctrl+Q'
    }
```

It seems to me the accelerator is already mapped to exit the app on pressing `Ctrl+Q` on non-Darwin platforms. Although pressing the shorcut, at least on my packaged version, does nothing :thinking: . Tried doing it both with the tray menu opened, and with the app focused

**Comment by flavioislima** [comment]
@CharlExMachina yes, we did that a long time ago but it did not work, so maybe something is missing or it is declared in a wrong way.

**Comment by flavioislima** [comment]
I found a solution for that, I will open a PR

**Comment by NuxarianCookie** [comment]
you should add in a way to either stop this or make it only happen when in the window, as whenever im playing i often press ctrl+q and end up accidentally closing the launcher, or opening the dialogue

**Comment by sedikitaja** [comment]
I have to agree with @NuxarianCookie, this needs to be limited to when the Launcher is the focussed application. It should not be listening for Ctrl+Q globally, as this pulls you out of a game.
