### ISSUE TITLE
Elite Dangerous, stuck at 100% download, processing files ...

### ISSUE THREAD

**Issue by PadTrick** [Heroic-Games-Launcher/HeroicGamesLauncher#2641]
### Describe the bug

Heroic Launcher 2.7.0 seems to not recognize Elite Dangerois DLC Odyssey (it wont show the download size of it).
It will download the ~20GB for the main game, completes it and is stuck forever in precessing files ...
No disc or network activity can be seen. if i pause the download, close heroic and reopen it, the install finishes.

but if i start the oddysey dlc in the ed launcher, the game loads and crashs.
legacy game works fine.

i currently try to verify gamefiles with the ed launcher, hope this will work.

*edit* i finished verifing files and i'm now able to play.

### Add logs

```text
cant provide log, because this PAGE doesnt allows it to be posted. to much characters in it lol
```

### Steps to reproduce

Check inside your Library the game Elite Dangerous.
Normaly it would show the Game Size + the Size of the DLC.
Now it only shows the Base Game size.

### Expected behavior

Install the Base Game + DLC (if i select the option) and not to hold without finishing.
Showing the correct download size.

### Heroic Version

Latest Stable

### System Information

Archlinux Kernel 6.2.12-zen1-1-zen
using the AUR package.

**Comment by flavioislima** [comment]
Check again on the latest heroic version, if it is not fixed, reopen the issue.

**Comment by PadTrick** [comment]
latest version doesnt recognize epic login. but all was working as expected in 2.8.0 release, if made 2 changes https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/issues/2674#issuecomment-1570458185
