### ISSUE TITLE
Open Epic and GOG webview in different sandboxes to prevent tracking

### ISSUE THREAD

**Issue by Elendil211** [Heroic-Games-Launcher/HeroicGamesLauncher#2650]
### Problem description

Currently, both are using the same sandbox. When I go to the GOG page and click through some links I can get to the Epic website where I'm automatically logged in.

From what I understand, this allows cross site tracking, for example via third-party cookies.

### Feature description

Open the webview for Epic and GOG in different sandboxes with different context. The behavior should be as if they were using different browsers. Ideally there should be no way for Epic or GOG to know that a particular user also has an account on the other platform.

**Comment by arielj** [comment]
do you know if that is actually happening? do you know if there's a third-party cookie allowing one service to track the other? browsers already do things to prevent sites from knowing your activity in other sites, I don't think epic.com can know you are logged in gog.com for example

**Comment by Elendil211** [comment]
I don't know whether or not this happens, but (at least as far as I understand) it would be possible. Third-party-cookies are also not the only way for tracking, as described here: https://www.cookiebot.com/en/google-third-party-cookies/

**Comment by imLinguin** [comment]
Its achievable with partition parameter to <webview> with `persist:` prefix.

Not sure if we really want to be that strict. Cookies are generally bound per domain and JS code can't read them unless allowed by domain explicitly.
