### ISSUE TITLE
Heroic frozen when launching and refreshing on big GOG libraries (Implement Setting to disable update on startup)

### ISSUE THREAD

**Issue by Bob837217** [Heroic-Games-Launcher/HeroicGamesLauncher#2655]
### Overview

When I launch Heroic, first thing on a given day, it seems to want to re-download my metadata for my GoG library.
But with over 700 games on GoG, this takes an indeterminate amount of time.  

### Actual Behavior

Today I left it going and Heroic would be frozen completely with only a black box as the UI.  The CPU was 25% overall on my 4 core system which means that 1 was at 100%.  I left it in this state for about 1 hour before closing it off.  After a restart, launch was almost immediate and no problem.

### Extra Points

Given that the GoG API is pretty chunky and slow especially for large game libraries, it really should be up to the user to issue a refresh on GoG.  The cached GoG API info should never be allowed to expire.  Perhaps a notification can ask user if they want to refresh GoG if it's detected as "stale" by Heroic.   The problem is GoG API, really it should support: a) get a list of game names + identifiers only (like Legendary does), then for each of these, request a URL to the game cover and cache these forever.  But since that is not how GoG API operates and is slow + full fat - we need to control the refresh as end users and the cache should be allowed to persist forever ideally and not expire.

### Add logs

```text
(these logs do not show that the instance was up for 1 hour at high CPU before I closed it off)

(09:05:39) INFO:    [Connection]:       Connectivity: check-online
(09:05:39) INFO:    [Connection]:       Pinging external endpoints
(09:05:39) INFO:    [Legendary]:        Running command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary --version
(09:05:40) INFO:    [Legendary]:        Legendary location: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary
(09:05:40) INFO:    [Gog]:              GOGDL location: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl
(09:05:40) INFO:    [Gog]:              GOGDL location: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl
(09:05:40) WARNING: [Backend]:          Failed to register protocol with OS.
(09:05:40) INFO:    [Connection]:       Connectivity: online
(09:05:40) INFO:    [Gog]:              Getting data about the user
(09:05:40) INFO:    [Gog]:              Running command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/bob/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth
(09:05:40) INFO:    [Gog]:              Running command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/bob/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json --version
(09:05:40) INFO:    [Backend]:          AreWeAntiCheatYet data downloaded
(09:05:40) INFO:    [Backend]:          

Heroic Version: 2.7.0 Eustass Kid
Legendary Version:  0.20.32 Dark Energy (hotfix #6)
GOGdl Version: 0.7.1

Electron Version: 23.1.4
Chrome Version: 110.0.5481.192
NodeJS Version: 18.12.1

OS: Freedesktop SDK KERNEL: 6.2.6-76060206-generic ARCH: x64
CPU: Intel Coreâ„¢ i5-2500K @3.3 GOVERNOR: schedutil
RAM: Total: 15.59 GiB Available: 10.54 GiB
GRAPHICS: GPU0: GP104 [GeForce GTX 1070 Ti]  VRAM: 32MB 
PROTOCOL: x11

(09:05:40) INFO:    [Backend]:          Loading Screen Ready
(09:05:41) INFO:    [Frontend]:         Refreshing Library
(09:05:41) INFO:    [Legendary]:        Refreshing library...
(09:05:41) INFO:    [Legendary]:        Refreshing Epic Games...
(09:05:41) INFO:    [Legendary]:        Found 0 games to update
(09:05:41) INFO:    [Legendary]:        Game list updated, got 279 games & DLCs
(09:05:41) INFO:    [Gog]:              Running command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/bob/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth
(09:05:41) INFO:    [Backend]:          Frontend Ready
(09:05:41) ERROR:   [Frontend]:         Error: F is not iterable
(09:05:41) INFO:    [Backend]:          Checking for current version changelog
(09:05:41) INFO:    [Legendary]:        Running command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary list --third-party
(09:05:41) INFO:    [Gog]:              Saved user data to config
(09:05:41) INFO:    [Gog]:              Found 0 game(s) to update
(09:05:41) INFO:    [Frontend]:         No cache found, getting data from legendary...
(09:05:41) INFO:    [Legendary]:        Refreshing library...
(09:05:41) INFO:    [Legendary]:        Game list updated, got 279 games & DLCs
(09:05:41) INFO:    [Gog]:              Getting GOG library
(09:05:41) INFO:    [Frontend]:         Force Update
(09:05:42) INFO:    [Gog]:              Number of library pages: 7
(09:05:42) INFO:    [Gog]:              Getting data for page 2
(09:05:42) INFO:    [Winetricks]:       Downloading Winetricks
(09:05:42) INFO:    [Gog]:              Getting data for page 3
(09:05:43) INFO:    [Gog]:              Getting data for page 4
(09:05:43) INFO:    [Gog]:              Getting data for page 5
(09:05:44) INFO:    [Gog]:              Getting data for page 6
(09:05:45) INFO:    [Gog]:              Getting data for page 7
(09:05:45) INFO:    [Gog]:              Running command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/bob/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth
(09:05:46) INFO:    [Backend]:          Starting the Download Queue
(09:05:46) INFO:    [Gog]:              Getting data for page 2
(09:05:46) INFO:    [Gog]:              Getting data for page 3
(09:05:47) INFO:    [Gog]:              Saved games data
(09:06:25) ERROR:   [ExtraGameInfo]:    Was not able to get GamesDB data for 1486144755
(09:06:33) ERROR:   [ExtraGameInfo]:    Was not able to get GamesDB data for 2015545325
(09:06:38) ERROR:   [ExtraGameInfo]:    Was not able to get GamesDB data for 1426071866
(09:08:04) ERROR:   [ExtraGameInfo]:    Was not able to get GamesDB data for 1739637082
(09:08:54) ERROR:   [ExtraGameInfo]:    Was not able to get GamesDB data for 1289070799
(09:09:05) ERROR:   [ExtraGameInfo]:    Was not able to get GamesDB data for 1980301910
```

### Steps to reproduce

1. Wait one day since last launch.  
2. Launch Heroic. 
3. High CPU + Frozen UI happens with black box for Heroic window.

### Expected behavior

Heroic should just launch

### Heroic Version

Latest Beta

### System Information

OS: Pop!_OS 22.04 LTS x86_64 
Kernel: 6.2.6-76060206-generic 
DE: GNOME 
WM: Mutter 
CPU: Intel i5-2500K (4) @ 5.900GHz 
GPU: NVIDIA GeForce GTX 1070 Ti 
Memory: 6337MiB / 15961MiB

**Comment by marcbres** [comment]
I've noticed the same behavior after updating from 2.6.2, now on 2.7.0 it takes some minutes to start on the first start of each day, I'm thinking on revert to 2.7.0 in the meantime

**Comment by flavioislima** [comment]
So you mean that Heroic should not search for changes in the library on startup and do it only when the refresh button was clicked?

I think the problem is that in your case @Bob837217 your CPU is a bit old and then Heroic cannot really do any multithreading when updating the list. 

But I think we could add a setting to refresh or not the library on startup, that should improve Heroic launch.

**Comment by Bob837217** [comment]
@flavioislima the age of the CPU is irrelevant for multithreading.  All we are interested in is the core count.  My core count is 4.  I hope you are not suggesting that I need something like AMD ThreadRipper to update my library metadata?

The Epic/Legendary side seems 100% fine when updating.  But I know that when I need to use lgogdownloader (just another client for GoG) that it takes about 30 minutes to just get my metadata before it begins downloading game updates and new games for me.  This is constant everytime.  So really, it is the GoG API which is slow.

So Heroic should not update GoG library metadata upon start or when cache is old.  Perhaps it can do so if it times it's own update and finds its < 10 seconds right?  But anything over this should mean the user needs to hit refresh.

Which means that Epic side of Heroic and Gog side of Heroic will have different behaviours for updating the library meta data.  It is an inconsistency.  But for me it's the difference between having my games "instant on" (which is a huge thing) and having to restart/kill Heroic many times until it gives up on updating GoG metadata and just lets me play the damn latest game I am on at the moment.

**Comment by arielj** [comment]
@Bob837217 just wondering, do you think you can try to debug some of the slowness?

Because from your log I see the different pages of results for the games are fetched pretty fast:
```
(09:05:41) INFO:    [Gog]:              Getting GOG library
(09:05:41) INFO:    [Frontend]:         Force Update
(09:05:42) INFO:    [Gog]:              Number of library pages: 7
(09:05:42) INFO:    [Gog]:              Getting data for page 2
(09:05:42) INFO:    [Gog]:              Getting data for page 3
(09:05:43) INFO:    [Gog]:              Getting data for page 4
(09:05:43) INFO:    [Gog]:              Getting data for page 5
(09:05:44) INFO:    [Gog]:              Getting data for page 6
(09:05:45) INFO:    [Gog]:              Getting data for page 7
```

it's like 4 seconds

Then what I think it's taking too long is the download of the images we need for heroic. GOG's API returns landscape images but we need portrait images, so we have to fetch the info from gamesdb and we do that in chunks of 20 games at a time, but we should only run that for games which we don't already have an image for, since it shouldn't need to re-download all of them every day.

Would be interesting to know that's the length of the gamesWithNoImage variable for example https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/blob/main/src/backend/storeManagers/gog/library.ts#L286

Maybe one issue is that we have (I think) 6hs for the cache store invalidation by default and maybe that's too little for the libraries? https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/blob/main/src/backend/cache.ts#L13, would be interesting if you can try increasing that number to a few days (`60 * 24 * 3` for example)

**Comment by arielj** [comment]
@Bob837217 can you confirm if this still happens in 2.8.0 of if it was fixed?

**Comment by Bob837217** [comment]
@arielj Strangely, in my runs after this with the old version it really didn't seem to happen anymore.  And after upgrading to 2.8.0 I don't see any issue there either. I'll close this off, cheers.

**Comment by pelupessy** [comment]
The original issue is solved for the op, but the suggested feature (Implement Setting to disable update on startup) has not been implemented. Should one open a new issue if one still wanted this feature?

At the moment the library still takes about half a minute to refresh on my system (around 250 games). Admittedly, it is a minor annoyance, but this feature would prevent it from happening.
