### ISSUE TITLE
HL 2.5.0.beta1 -> 2.8.0 Unable to Login to Epic: Captcha answers always wrong.

### ISSUE THREAD

**Issue by PadTrick** [Heroic-Games-Launcher/HeroicGamesLauncher#2674]
### Describe the bug

i try to login into my epic account, but regardless what i do, the given answers are always wrong.

### Add logs

```text
no log
```

### Steps to reproduce

try to login

### Expected behavior

to login

### Heroic Version

Latest Stable

### System Information

Arch

**Comment by arielj** [comment]
that sometimes happens to me but even on my browser, I have to try a few times until it changes the prompt of the captcha and then it works fine

can you confirm if after trying 3 or 4 times it changes the prompt and then it works?

**Comment by PadTrick** [comment]
tried it over 20 times on heroic launcher. in browser it works flawless

**Comment by flavioislima** [comment]
This is my experience and it is working just fine. the problem is that those captchas are becoming more and more difficult now:

![2023-05-05_09-52-47 (1)](https://user-images.githubusercontent.com/26871415/236404505-f947bf86-ccda-43d6-bc2c-38703679edf0.gif)

Closing since we can't reproduce the issue.

**Comment by PadTrick** [comment]
strange, for me the only way to get it was to login into browser and solve the captcha there.
i even had the exact same captcha and i solved it, where HL told me that it was wrong.

i'm currently using 2nd login method which doesnt login, but the games in my lib are atleast working.

maybe it's a strange behavior of the captcha idk

**Comment by flavioislima** [comment]
Yes, the problem is not the captcha. Looking further into it, I can see it return status 400, bad request, after the login.

So my theory is that epic found a way of blocking heroic.

Tried several things and could not fix it so far.

I'm reopening this issue.

**Comment by PadTrick** [comment]
Ok, now i cant even play any game anymore.
I'm loggin into epic, using 2nd method, because normal method doesnt work.

An error has occurred! Try to Logout and Login on your Epic account.
gamemodeauto:[cli] INFO: Logging in...
Traceback (most recent call last):
File "legendary/cli.py", line 3061, in <module>File "legendary/cli.py", line 2976, in main
File "legendary/cli.py", line 592, in launch_game
File "legendary/core.py", line 187, in login
ValueError: No saved credentials
[9048] Failed to execute script 'cli' due to unhandled exception!

**Comment by arielj** [comment]
I can't reproduce this, I tried with a clean config and I was able to login first try with the captcha, maybe it was a temporary thing?

**Comment by PadTrick** [comment]
have this issue sine 1 week. trying daily to login, but always the same.
idk what it is, i also have this on 2 other machines, with other distros.
tried flatpak, arch aur package, binary ...
clueless and confused

**Comment by mumbleskates** [comment]
it does indeed look like epic is killing these sign-in attempts based on user-agent or something. my login token expired and i can't get it back by logging in inside heroic. i could probably import my browser's login cookies to .config/heroic/Partitions/epicstore/Cookies but that's so much effort

**Comment by mumbleskates** [comment]
i was able to get the launcher, but not the store page, to be logged in via the alternate login path where you paste the login token from legend. although this did produce the error below, it does function and launch games afterwards:

```
An error has occurred! Try to Logout and Login on your Epic account.
[cli] INFO: Logging in...[Core] INFO: Trying to re-use existing login session...[cli] INFO: Getting game list... (this may take a while)Traceback (most recent call last):
File "legendary/cli.py", line 3061, in <module>
File "legendary/cli.py", line 2972, in main
File "legendary/cli.py", line 206, in list_games
File "legendary/core.py", line 511, in get_non_asset_library_items
File "legendary/api/egs.py", line 229, in get_library_items
File "requests/models.py", line 1021, in raise_for_status
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://library-service.live.use1a.on.epicgames.com/library/api/public/items?includeMetadata=True
[111871] Failed to execute script 'cli' due to unhandled exception!
```

**Comment by flavioislima** [comment]
Guys, I think I found the issue, can you guys test the build from this PR to confirm:
https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/actions/runs/4906572797?pr=2688

**Comment by PadTrick** [comment]
> Guys, I think I found the issue, can you guys test the build from this PR to confirm: https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/actions/runs/4906572797?pr=2688

doesnt work for me. but i check on another machine

**Comment by p3ak** [comment]
> > Guys, I think I found the issue, can you guys test the build from this PR to confirm: https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/actions/runs/4906572797?pr=2688
> 
> doesnt work for me. but i check on another machine. tested on another machine, where Hl wasnt installed. no luck. i'm on arch on both systems, can this be a source for the problem ?

Nope, same issue, WIn 11

**Comment by p3ak** [comment]
> Guys, I think I found the issue, can you guys test the build from this PR to confirm: https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/actions/runs/4906572797?pr=2688

Any chance this update can be pushed really soon?

**Comment by PadTrick** [comment]
> > Guys, I think I found the issue, can you guys test the build from this PR to confirm: https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/actions/runs/4906572797?pr=2688
> 
> Any chance this update can be pushed really soon?

doesnt work for me on all my systems. i even tested very old versions. to me it seems like epic changed something on their end, which needs to be implemented/changed

**Comment by p3ak** [comment]
> 

Funny enough: It now works for me again.. also had other captchas than yesterday... lol

**Comment by Erz3** [comment]
> I don't know if it's of any use, but when I tried the alternate login method, the captcha would not solve when I blocked HTML canvassing, but I could solve and the site allowed me to grab the authentication # when I allowed HTML canvassing.

I don't understand you. I have got the same issue, could you explain it better?

**Comment by mumbleskates** [comment]
this doesn't say much; captcha rejections are arbitrary, and you are just as likely to be getting blocked based on IP address (VPNs are also extremely likely to be caught in blanket IP bans for this kind of thing)

**Comment by Arcitec** [comment]
@mumbleskates No. I am successful via my phone (exact same IP address).

Here is what I get on my Linux Brave browser where I am still logged in from a months-old login session. I can add games to the cart but if I try to buy them, the captcha fails and says:

![image](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/assets/38923130/88a7ea82-0c5e-4bce-96a7-8b3cf83e66ac)

Then I use my phone (Google Chrome, Android, same IP) and buy the game no problem.

**Comment by Arcitec** [comment]
@mumbleskates 

I decided to try my Windows 11 virtual machine, with Microsoft Edge browser, and the exact same IP address.

- Login: Works. In fact they didn't even ask me to solve any captcha.
- Finishing cart purchase (same cart as failed on Linux above): Works. And again they didn't ask me to solve captcha.

SAME. IP.

Epic hates Linux. Confirmed.

**Comment by Arcitec** [comment]
If I had to guess, Epic has raised their "threat level" threshold.

- Epic uses Cloudflare to test user browser legitimacy.
- Epic uses hCaptcha to test if user is a human or a bot.
- The captcha service is serving harder captchas to Linux users, fact.
- The captcha service is responding that the Linux user completed the captcha.
- The combined score from Cloudflare + hCaptcha are used to reject users.
- Linux users probably have a higher "threat score" than Windows. Therefore the blocking may not be intentional. If anyone has a communication line to Epic, please use it, because they most likely aren't aware. But of course, Tim Sweeney famously hates Linux (he rants against it on Twitter).

**Comment by mumbleskates** [comment]
normal epic login works completely fine from my linux browser, and has never even served me a captcha. it is arbitrary, and no data point necessarily generalizes this way. unless you can find a specific browser feature that makes or breaks the process (which it sounds like you haven't) this is just another data point.

these kinds of login filters put all the data they have access to into some heuristic, and yes linux user-agents generally do have a higher threat score.

**Comment by Arcitec** [comment]
@mumbleskates What browser are you using? I can test it too. I have most likely received a higher IP-based score in general, which together with being a Linux user puts me into the trash-can @ Epic.

**Comment by Arcitec** [comment]
Ultimate hilarity. I used my still-logged-in-since-months-ago Linux browser session to try to make a ticket. The ticket process asks for a captcha which of course fails. :D

Time to submit the ticket via Windows. I suggest that EVERYONE affected starts contacting Epic's support (via your account page: Need Help: Contact us (at the bottom)). And explain that the issue needs to be relayed to the engineering team because this is a clear issue on their end, not ours.

![image](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/assets/38923130/a2696529-af0d-4f8f-8993-c89db4cbd07b)

**Comment by PadTrick** [comment]
I'm on Arch and with Opera i also dont get any Captchas to solve.
But i get Captchas on Firefox and can successful solve these, the same with Chrome.
Just the Heroic Launcher refuses somehow to accept the correct answers and goes karen mode ^^

**Comment by Erz3** [comment]
Me too… I can log in with Firefox on Linux. The problem is with Heroic, I think.

**Comment by Nocccer** [comment]
For me it sounds like it depends on the webdriver version. Electron uses chrome driver with a specific version. It might only happens with a old or to new version?

**Comment by flavioislima** [comment]
@Arcitec I don't think the issue is with Linux because I have the same problems on macOS. I believe that it's something blocking our IP on their end.

Because for me sometimes I can log in fine on Heroic, sometimes I cannot log in even on the browser. Looking at the dev tools, I see a bad request error 400 but could not find more info on what could be wrong.

**Comment by Nocccer** [comment]
Can the method to login make a different? I log in via google and i have no captcha prompt and login works fine.

**Comment by flavioislima** [comment]
> Can the method to login make a different? I log in via google and i have no captcha prompt and login works fine.

yes, only Epic logins are being affects, if you use google or any other it will be fine.

**Comment by tazihad** [comment]
Guys, I have found a way to bypass the failed captcha inside heroic launcher. Make sure you connect your epic games with your google account from any browser. Than try login with google account with inside heroic. After giving google login details it takes me directly to Epic games 2fa screen. And the login happens without any issue.

**Comment by PadTrick** [comment]
> Guys, I have found a way to bypass the failed captcha inside heroic launcher. Make sure you connect your epic games with your google account from any browser. Than try login with google account with inside heroic. After giving google login details it takes me directly to Epic games 2fa screen. And the login happens without any issue.

nice workaround, but in the end, the issue with the captchas for epic account login needs to be fixed.

**Comment by flavioislima** [comment]
@Arcitec buy on heroic we already pass the user agent as chrome on windows to avoid this type of thing.

**Comment by Arcitec** [comment]
@flavioislima Yeah, I even saw the patch you're using to update the user agent to try to avoid the new captcha.

It's clear to me that Epic has tuned their "untrusted user agents" check way too sensitive. I've contacted their support twice by the way, with an explanation and a request to forward it to engineering. Both times, support personnel just clicked their control panel's auto-suggested auto-reply template and closed the tickets. They sent me links to helpful tips such as "How to clear your browser cache to see if that works".

Time to submit the 3rd ticket. Tickets will continue until morale improves.

**Comment by Arcitec** [comment]
Third time was the charm. Finally a support agent who forwarded the info to Epic's engineering. The bold part is the non-template/auto-response part of their message. I am 99% sure that everything non-bold is a standard template for "passing along info to engineers" but the bold part is human-written and suggests that the info is being passed along.

Now we just need to pray that they actually revise their login thresholds to allow the rarer Linux web browsers (non-Firefox users) back into the store.

> Hello there!
> 
> Thank you for reaching out to us.
> My name is ... and I'll be your Epic Games Support Agent.
>  
> **I'm sorry to hear about your experience with logging into Epic on Linux.**
> **Thank you for letting us know of a potential fix that would stop this from happening to other players as well.**
> **Not many people go the extra mile like you did!**
>  
> I'll pass your feedback along, yet since we get a lot of feedback, I can't guarantee that any action or response will come from this. Don't forget to keep an eye on our News page for the latest information on updates and changes.
>  
> If there's anything else I could do for you, please let me know!
> I wish you a great rest of your day!
>  
> Kind regards,
> ...

**Comment by karlisk** [comment]
Came here after looking for solutions from here: [Login issue #2531](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/issues/2531)

Seems to be one and the same cause in both issues. As noted in the other issue, I was able to log in using Firefox on Linux, any other browser failed with incorrect captchas or "incorrect response".

**Comment by Arcitec** [comment]
> Seems to be one and the same cause in both issues. As noted in the other issue, I was able to log in using Firefox on Linux, any other browser failed with incorrect captchas or "incorrect response".

@karlisk Yeah, this is not fixable by us. Epic must do it.

Please **start contacting Epic's support (via your account page: Need Help: Contact us (at the bottom)).** And begin the message by explaining that the issue is affecting TONS of users on Mac and Linux and that it needs to be relayed to the engineering team because this is a clear issue on their end, not ours.

Then go on to list the working and non-working platforms and browsers.

In my case, all browsers are stock (no extensions) and are all on the same IP. Private mode doesn't fix it either.

- Works: Windows (Chrome, Brave, Edge), Android (Chrome), Linux (Firefox)
- Blocked by Epic: Linux (Chrome, Brave, Electron/Chromium).

Those are the ones I have tested.

**Comment by Erz3** [comment]
It seems work now on Linux.

I logged in with the first option and passed captcha challenge.

**Comment by Arcitec** [comment]
As an extra data point:

- Epic Games Launcher (the OFFICIAL app) inside of Bottles, emulated via Wine, logs in properly.
- That app is basically just a web browser. The login process is the exact same. But when using that app, the login is accepted immediately without even being asked for a captcha.

@flavioislima Any ideas for figuring out which User-Agent the official app uses? Maybe we can emulate it perfectly.

**Comment by 404b** [comment]
If anyone still having issue with hCaptcha
try noCaptcha Ai solving. There's a Free plan of 6K req/month

**hCaptcha Solving Variations**
- Image (Normal/Enterprise) Grid, Multiple Select, Click on Canvas
- Normal Token

Chrome Extension:
https://github.com/noCaptchaAi/chrome-extension


**Selenium Packages** :

https://github.com/Hammad69275/NoCaptchaSolver
https://github.com/claudiofepereira/nocaptchaai-selenium
https://raw.githubusercontent.com/the-captcha-ai/captcha-solver/main/usage_examples/example-selenium.py

Software Library: https://nocaptchaai.com/software

`npm install nocaptchasolver`

```
const {HCaptchaSolver} = require("nocaptchasolver")

const config = {
    apiKey,
    userAgent,
    siteKey,
    siteURL,
    enableLogger,
    loggerFunction,
    delay // in milliseconds (default is 7000ms)
}

const Solver = new HCaptchaSolver(config)


```

**Comment by PadTrick** [comment]
> If anyone still having issue with hCaptcha try noCaptcha Ai solving. There's a Free plan of 6K req/month
> 
> **hCaptcha Solving Variations**
> 
> * Image (Normal/Enterprise) Grid, Multiple Select, Click on Canvas
> * Normal Token
> 
> Chrome Extension: https://github.com/noCaptchaAi/chrome-extension
> 
> **Selenium Packages** :
> 
> https://github.com/Hammad69275/NoCaptchaSolver https://github.com/claudiofepereira/nocaptchaai-selenium https://raw.githubusercontent.com/the-captcha-ai/captcha-solver/main/usage_examples/example-selenium.py
> 
> Software Library: https://nocaptchaai.com/software
> 
> `npm install nocaptchasolver`
> 
> ```
> const {HCaptchaSolver} = require("nocaptchasolver")
> 
> const config = {
>     apiKey,
>     userAgent,
>     siteKey,
>     siteURL,
>     enableLogger,
>     loggerFunction,
>     delay // in milliseconds (default is 7000ms)
> }
> 
> const Solver = new HCaptchaSolver(config)
> ```

can someone plz delete this AD ?!

1. it's an AD
2. it has nothing todo with the problem

**Comment by 404b** [comment]
> can someone plz delete this AD from 404b ?!
> 
> 1. it's an AD

I've deleted it, It was a plug for noCapcthaAi Captcha Solver I admit. But it's not the only one, there're more mention for other captcha solver sevice (eg. on replies of [Arcitec](https://github.com/Arcitec)). 

No provider has free hobby/personal plan like noCapcthaAi (6000 req each month).

> 2. it has nothing todo with the problem

noCapcthaAi bypasses hCaptcha pretty well and daily updated, as much i can read here issue is about hCaptcha bypass failing which can be solved by getting a passed hCaptcha Token (entirely request based https://docs.nocaptchaai.com/en/token/hCaptcha.html). 

Because third party projects always get's blocked by firewall/Captcha. Lot of software/clients already implemented our api on their side to bypass HCaptcha, [HeroicGamesLauncher ](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/) can too as an optional feature.

Alternatively, I could mention free projects here on github but there will same failed to bypass issue as they are not updated as much as noCapcthaAi

I didn't mean to upset you with a hcapctha solution (on your Issue about the same) thousand of people daily use. Have a good day.

**Comment by flavioislima** [comment]
I opened a PR where I just changed the user agent on the login screen to Firefox on Linux since some people had success with it. 
It worked for me as well.

But need more testers:
https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/pull/2726

**Comment by MxD-Sans** [comment]
I found that, in browser, changing the User Agent from Developer Options -> Network Conditions to Chrome on Windows, said capcha will just not bother me anymore. If it stays default (Chrome on Linux), it would always fail. So maybe there's something specifically on linux that triggers that capcha? Since Epic is only officially supported on Windows, they only test Windows browsers?

The emulated User Agent, in Chrome, is
`Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36`

**Comment by flavioislima** [comment]
> I found that, in browser, changing the User Agent from Developer Options -> Network Conditions to Chrome on Windows, said capcha will just not bother me anymore. If it stays default (Chrome on Linux), it would always fail. So maybe there's something specifically on linux that triggers that capcha? Since Epic is only officially supported on Windows, they only test Windows browsers?
> 
> The emulated User Agent, in Chrome, is `Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36`

no, on the current Heroic stable we use chrome on windows, we always used chrome on windows so its something else. 
Some people even using a browser gets the error so it is more complicated than we think, might even be something on Epic side.

**Comment by sleeplessKomodo** [comment]
I'm on Fedora. Heroic v2.7.1

Can successfully login via Firefox browser, and can login within legendary using the alternative method to access my library, but can't use the built-in browser to log in and access the store. The regular login still fails

**Comment by Arcitec** [comment]
# The issue has been found: It's a bug in hCaptcha. Everyone please start contacting them, complaining about their broken captchas.

Contact them here:

- [support@hcaptcha.com](mailto:support@hcaptcha.com)
- [sales@hcaptcha.com](mailto:sales@hcaptcha.com)

The short summary: hCaptcha is detecting and permanently blocking the Linux/Mac versions of Chrome-based browsers (Brave, Chrome, Electron, etc) REGARDLESS OF USER AGENT (spoofing the exact same agent as the Windows version doesn't matter; it still hates your browser if you're on Mac/Linux), and hCaptcha blocks them permanently when attempting the hardest security challenge ([Enterprise Grade, which is what Epic uses](https://nopecha.com/demo/hcaptcha)). In a few rare cases you might succeed an Enterprise challenge, but you will be blocked on your next tries after that. Their "bot detection" engine is simply COMPLETELY broken and is detecting non-Windows Chromium browsers as bots.

Full details here: https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/pull/2726#issuecomment-1563634439

**Comment by mks-h** [comment]
You jump to conclusions. I have no problem solving captchas in neither Firefox nor Chrome on Linux, using this website https://nopecha.com/demo/hcaptcha. Yet, it's broken in Heroic. Maybe the problem is that you are trying to spoof user-agent, and getting caught doing that, and therefore rejected.

**Comment by flavioislima** [comment]
> 

yes, I also suspect that. I will remove the useragent change on my PR so we can test it again.

The issue with that is that, when retrieving games on the epic store, free games, or buying games, we will get a warning saying that the platform is not supported.
Same for windows only games on macOS. But that is not an issue, only one more button to click.

**Comment by arielj** [comment]
> The issue with that is that, when retrieving games on the epic store, free games, or buying games, we will get a warning saying that the platform is not supported.

I think they removed that, for the last few weeks, using my browser to "buy" the free games didn't trigger that `it's not supported` message

**Comment by PadTrick** [comment]
@Arcitec

i also dont see any reason why hcaptcha is at fault here.
i'm able to solve captchas in any browser i try (Chrome, Mozilla, Opera), regardless if its the demo page, epic store or somewhere else.
Only Heroic Launcher refuses to accept the correct choices, even if i had the identical captcha in a browser and solved it correctly, HL still says its wrong.

so yeah, we still need to wait for a fix inside of HL.

**Comment by devipasigner** [comment]
> @Arcitec
> 
> 
> 
> i also dont see any reason why hcaptcha is at fault here.
> 
> i'm able to solve captchas in any browser i try (Chrome, Mozilla, Opera), regardless if its the demo page, epic store or somewhere else.
> 
> Only Heroic Launcher refuses to accept the correct choices, even if i had the identical captcha in a browser and solved it correctly, HL still says its wrong.
> 
> 
> 
> so yeah, we still need to wait for a fix inside of HL.

I believe there are different security levels for hcaptcha. Sometimes it's a very easy & quick process, other times it's an infuriating process to solve it. Though I do believe that heroic is causing it to trigger the "maximum" difficulty.

**Comment by PadTrick** [comment]
>As for why you in particular can log in using Chrome on Linux, while many other people can't: That's because they use multiple metrics.

that completly doesnt explains, why i have 0 issues with login on every browser and never had.
but HL refuses to login.

if that was the case, than i never had the ability to login, regardless of browser.
so yeah, i still see the issue on the HL side and way the login method works in HL

**Comment by mumbleskates** [comment]
observation: captchas are little-understood, their behaviors are arbitrary and people often think their anecdotal experience generalizes, and this thread keeps attracting shills

**Comment by PadTrick** [comment]
contacted hCaptcha support. exchanged several mails with them.
result is, 

and as i already stated several times, the issue is only with HL/legendary. nothing else is affected.
they arent able to help in any sort, if a 3rd party launcher doesnt work correctly.
that is not a hcaptcha issue.

fact is. i'm able to login and solve the captchas with any browser. i can login and solve the captcha with epic games store running through wine.

just HL/legendary refuses.

**Comment by arielj** [comment]
I think the problem is a weird combination of things (like cookies, ip, browser agent, movement patterns -the request to verify the captcha sends all the mouse movements too to verify they look "human-ish"- and maybe more), I don't think it's as simple as to say `hcaptcha is doing this wrong on linux` or `it's heroic's issue`. If those were the problems then nobody would be able to login and we have users with no issues (I'm one of those).

What's difficult to solve this is that none of the developers seem to be able to reproduce this problem consistently to try to find a solution. At least for me it just works every time, with any browser on linux and with heroic for example (like I just tried logging in with chrome on linux in incognito and it doesn't even show the captcha, and I had times in the past where the captcha is never accepted when buying a free game but it's totally fine on login).

**Comment by NeoFoxxo** [comment]
hey i found that i had this same issue in my browser (brave on windows) but once i disabled my ad blocker and all the tracker blockers it worked perfectly idk if that can help

**Comment by slynobody** [comment]
(temporary?) solution: change webview-browser-agent as well as main heroic browser-agent to 'Mozilla/5.0 (Windows NT 10.0; WOW64; rv:70.0) Gecko/20100101 Firefox/70.0'

to test without compiling: ctrl-shift-i, see current main agent (console): navigator.userAgent, change: network conditions; webview: elements / body / app / webview / Webview__webview: simply change to above)

**Comment by PadTrick** [comment]
Can u plz share more detailed howto change it ?
For me my user agent is "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) heroic/2.7.1 Chrome/110.0.5481.192 Electron/23.1.4 Safari/537.36' "

i thought it should be the windows wone ?!?!

**Comment by flavioislima** [comment]
> (temporary?) solution: change webview-browser-agent as well as main heroic browser-agent to 'Mozilla/5.0 (Windows NT 10.0; WOW64; rv:70.0) Gecko/20100101 Firefox/70.0'
> 
> to test without compiling: ctrl-shift-i, see current main agent (console): navigator.userAgent, change: network conditions; webview: elements / body / app / webview / Webview__webview: simply change to above)

I just pushed the change to my PR if you guys want to try @PadTrick 
Just wait for the build to finish

**Comment by flavioislima** [comment]
Not much luck on my end though, I imagine that this was what you meant @slynobody 
<img width="1321" alt="image" src="https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/assets/26871415/d564a636-9036-417e-8948-dbccae16e7a9">

**Comment by PadTrick** [comment]
its also not working for me, but somehow i dont see any activity in console etc.
as if nothing really done ...

**Comment by flavioislima** [comment]
I really think this is something random not sure, perhaps let's try old heroic versions, from 2.4 I believe. Older than that I think the login won't work.

**Comment by PadTrick** [comment]
uhm, which dir do i need to nuke to get rid of all settings etc. ? ^^

**Comment by PadTrick** [comment]
v 2.4.1 doesnt even asks for a captcha o_O

**Comment by flavioislima** [comment]
> uhm, which dir do i need to nuke to get rid of all settings etc. ? ^^ nvm found it
> 
> v 2.4.1 doesnt even asks for a captcha o_O, but it only logs into the page, not into the account. cant access my library v 2.4.2 seems to work fine, can access my library etc. but cant install games ^^ v 2.4.3 seems to work perfect. login works (captcha wasnt needed), can install games

interesting. Yeah, ignore what happens after the login because the rest is probably broken. Can you try 2.6? and then 2.5?

**Comment by flavioislima** [comment]
> v 2.5.0 & v 2.6.0 asking for captcha, which arent solveable. also tested v2.5.0 beta 1 -> 3 all the same.
> 
> the only working version for me is 2.4.3, where login works (doesnt asks for captcha), i see my library and can play games.

cool, thanks for testing, we can check what was the difference now between these version and see if we broke something on our end

**Comment by flavioislima** [comment]
Tested here and yes, it asks for captcha on 2.4.3 but it works just fine afterward and I can log in normally. Tried more than once and was fine.

the problem is that 2.5.0 had several structural changes and might be difficult to find which one has caused it, but I believe its a problem on the Heroic side.

**Comment by PadTrick** [comment]
uhm ok. it didnt asked for captcha for me.
maybe it has something todo with default browser? i'm on arch and using latest opera.

**Comment by arielj** [comment]
> uhm ok. it didnt asked for captcha for me. maybe it has something todo with default browser? i'm on arch and using latest opera.

I use Opera as my default browser on Linux Mint and I had no issues with logins so I don't think it's relate to that.


@flavioislima, @PadTrick, I understand you can reproduce the problem consistently? in 2.4.3 you can login and in 2.5 you can't?

**Comment by PadTrick** [comment]
> > uhm ok. it didnt asked for captcha for me. maybe it has something todo with default browser? i'm on arch and using latest opera.
> 
> I use Opera as my default browser on Linux Mint and I had no issues with logins so I don't think it's relate to that.
> 
> @flavioislima, @PadTrick, I understand you can reproduce the problem consistently? in 2.4.3 you can login and in 2.5 you can't?

yes, 2.4.3 works like intended. all newer version, including 2.5.0 beta 1-3 having the captcha issue

**Comment by arielj** [comment]
hmmm I'm checking the diff between 2.4.3 and 2.5.0beta1 https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/compare/v2.4.3...v2.5.0-beta.1

One thing I see that might be related: we upgraded electron from 20 to 21

I wonder if we can rollback the version of Electron and make a test build

**Comment by arielj** [comment]
@PadTrick, when you have some time, can you try the build from this PR? https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/pull/2743

it downgrades electron from version 23 to version 20

**Comment by arielj** [comment]
Also please try this one https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/pull/2744

it uses electron 23 but has no hardcoded useragent

**Comment by arielj** [comment]
last one: this one has no user agent and electron 20, like it was in 2.4.3 https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/pull/2745

**Comment by PadTrick** [comment]
tested https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/pull/2743
during login captcha was shown and i was able to solve it

**Comment by arielj** [comment]
thanks for testing! looks like for you the problem is the version of Electron then, because it works in both cases with electron 20 with and without a hardcoded useragent, and the cases where it fails for you are electron 21 and 23

let's wait for more people to test this

@Arcitec can you try the test builds I created? would be interesting to see how that works for you too

**Comment by flavioislima** [comment]
> thanks for testing! looks like for you the problem is the version of Electron then, because it works in both cases with electron 20 with and without a hardcoded useragent, and the cases where it fails for you are electron 21 and 23
> 
> let's wait for more people to test this
> 
> @Arcitec can you try the test builds I created? would be interesting to see how that works for you too

Its not the electron version. I saw the diff and tried reverting electron version, reverted to old webview code, with and without user agent and also reverted the settings for the main window to be the same as 2.4.3 that, like I said above, also works for me.

If this was caused by the refactor of the IPC calls somehow that would be impossible to revert. There was like more than 100 commits in between these versions so would be impossible to find the exact issue.

**Comment by arielj** [comment]
Sorry I don't follow, you said you reverted those things and it works for you? I don't follow why that wouldn't be the fix if it works

One thing I was thinking is that maybe it's actually different root causes for different issues? looks like for PanTrick the electron downgrade actually does fixes the problem for example, maybe we are trying to find one single solution when maybe there are more than 1 thing that need to change for different users?

I thought about the IPC calls, but I don't think those have an impact in the webview, it's not that the `window.api` thing is added to the webviews, it's only added to the main windows.

**Comment by flavioislima** [comment]
Continuing what I said above.

In my case my ad-blocker that is installed on my router called Diversion that was blocking Epic.

tried 4 times now and I could login just fine on all of them.

After enabling the ad-blocker it didn't work again.

So might be some router configuration, even if not an ad-blocker, but some settings that might be interfering with the login. I will keep testing it though.

**Comment by arielj** [comment]
but there must be something else in the Heroic side, or it wouldn't work with any version of Heroic for you, but it does with 2.4.3 even with that ad-blocker running

there's something else, something that sounds like we could change in heroic

**Comment by PadTrick** [comment]
tested v2.8.0, wasnt able to solve captchas.
removed the user agent , like in https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/pull/2745
no captcha was shown and was able to login

**Comment by Jofagi** [comment]
I'm using Heroic on Arch and I had problems with 2.7.1 as well. Went back to the 2.4.3 version of the AUR package and then it worked. Today I updated to 2.8.0 and that works as well for me. I had to solve about 13 captchas until I got to the TOTP screen and it let me log in.
I logged out and in again, had to solve >10 captchas but it finally let me in a second time.

**Comment by PadTrick** [comment]
tinkered a bit. i now have v2.8.0 working.
- removed the user-agent (result = Epic wont ask for Captchas in most cases)
- downgraded electron (result = i'm able to solve captchas)

looked @ https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/pull/2745 
but only edited src/frontend/screens/WebView/index.tsx & package.json (havent touched yarn.lock)

**Comment by 24Freddy24** [comment]
when you make a new account there is no issue for 2 days and after that the seam issue

**Comment by mini-bomba** [comment]
I was just tinkering a bit with the webview myself to test some of the theories listed in this thread, which didn't result in any great success, but thought I'd drop some of my debugging observations here.

> Support Mail from hCaptcha. Wanted to share those infos with them.
> but somehow console & har are empty

Main thing I've noticed is that logs and network requests happening inside the webview won't show up inside the devtools window of heoric. If you want to see them or otherwise debug the webview, you need to open the devtools of the webview, which can be done by running `document.querySelector("webview").openDevTools()` in the devtools of heroic.

**Comment by PadTrick** [comment]
> I was just tinkering a bit with the webview myself to test some of the theories listed in this thread, which didn't result in any great success, but thought I'd drop some of my debugging observations here.
> 
> > Support Mail from hCaptcha. Wanted to share those infos with them.
> > but somehow console & har are empty
> 
> Main thing I've noticed is that logs and network requests happening inside the webview won't show up inside the devtools window of heoric. If you want to see them or otherwise debug the webview, you need to open the devtools of the webview, which can be done by running `document.querySelector("webview").openDevTools()` in the devtools of heroic.

yeah i was able to get the infos, but since this is not an issue caused by hcaptcha, there is no point in contacting the support there.

i'm currently testing the changes made in the last few days, if this resolves the issues i had with random appearing error msgs and tomorrow i can see if can grab the freegame at epic.

so far, 2.8.0 with the changes i made here https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/issues/2674#issuecomment-1571287438 works.

**Comment by arielj** [comment]
Is this still happening with heroic 2.11?

**Comment by arielj** [comment]
Closing since there's no comments since June apart from mine and we haven't seen reports like this in a long time.

**Comment by oldgithubman** [comment]
Problem not solved
