### ISSUE TITLE
Hotkeys are captured globally on macOS.

### ISSUE THREAD

**Issue by astrochili** [Heroic-Games-Launcher/HeroicGamesLauncher#2676]
### Describe the bug

It looks like [these hotkeys](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/pull/2659) are captured globally on macOS.

Being in the Internet browser, for example, Cmd+R or Cmd+Q affect Heroic, but not the browser. It's absolutely not okay.

### Steps to reproduce

Press Cmd+Q (or other hotkey) when Heroic's window isn't active.

### Expected behavior

Shortcuts works in the current context and nothing happens in Heroic.

### Heroic Version

Version 2.7.1 (2.7.1)

### System Information

- macOS Ventura

**Comment by astrochili** [comment]
A pull request by @Etaash-mathamsetty already exists: https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/pull/2672

**Comment by Etaash-mathamsetty** [comment]
> A [pull request](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/pull/2672) by @Etaash-mathamsetty already exists, but looks like it just disables the new functionality.

It doesn't it retains some of the shortcuts while removing some of the heroic specific ones. While it's possible to add them back, let's fix the bug first
