### ISSUE TITLE
AppImage: Loop in first window after pasting SID and click "Enter"

### ISSUE THREAD

**Issue by RafaelLinux** [Heroic-Games-Launcher/HeroicGamesLauncher#268]
AppImage version (latest) 
I put my SID in initial window, click "Enter" and again ask for SID

**To Reproduce**
1. Launch  ./heroic-1.5.7.AppImage auth
2. Click on 'Open Store Here' link
3. Copy SID from webpage (each time I click on previous link, SID is distinct 
4. Paste SID in HGL window
5. Click on "Login"
6. Some text appears quickly and then again asking for SID.

**Expected behavior**
No idea, first time I launch HGL, but I think it will show another window, not the login window

**Desktop (please complete the following information):**
Operating System: openSUSE Leap 15.2
KDE Plasma Version: 5.21.3
KDE Frameworks Version: 5.80.0
Qt Version: 5.15.2
Kernel Version: 5.3.18-lp152.66-preempt
OS Type: 64-bit
Graphics Platform: X11
Graphics Processor: GeForce GTX 1050 Ti/PCIe/SSE2
Wine 5.0 (staging)

**Additional context**
Each time I try to login:
`Error: Command failed: /tmp/.mount_heroicMasAjG/resources/app.asar.unpacked/build/bin/legendary list-games
/tmp/.mount_heroicMasAjG/resources/app.asar.unpacked/build/bin/legendary: error while loading shared libraries: libz.so.1: failed to map segment from shared object

    at ChildProcess.exithandler (child_process.js:312:12)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Socket.<anonymous> (internal/child_process.js:443:11)
    at Socket.emit (events.js:315:20)
    at Pipe.<anonymous> (net.js:674:12) {
  killed: false,
  code: 127,
  signal: null,
  cmd: '/tmp/.mount_heroicMasAjG/resources/app.asar.unpacked/build/bin/legendary list-games',
  stdout: '',
  stderr: '/tmp/.mount_heroicMasAjG/resources/app.asar.unpacked/build/bin/legendary: error while loading shared libraries: libz.so.1: failed to map segment from shared object\n'`

**Comment by flavioislima** [comment]
Unfortunately it's not possible to run heroic on OpenSuse leap since it uses an old version of python. At least version 3.8 is needed for it to work. Check if that's the issue, if it is, please close the issue.

👍

**Comment by RafaelLinux** [comment]
Yes, that's. Leap 15.2 brings Python 2.7
Is not supossed precisely that AppImage are "selfproviding" their libraries?  I always choose AppImage to avoid version conflicts or not installed libreries, and this is first time I see this kind of issue. :(

**Comment by flavioislima** [comment]
Yeah, that's true. But this is a special case because heroic uses Legendary to handle the login, install and launch of games. And legendary runs on python 3.8.
As you can see, heroic opens since it does not depends on python for it. 👍

**Comment by RafaelLinux** [comment]
Woooops, so I'll can't try HGL ....  :(

Thank you for explaining it
