### ISSUE TITLE
Error on Epic library refresh

### ISSUE THREAD

**Issue by matteozel** [Heroic-Games-Launcher/HeroicGamesLauncher#2700]
### Describe the bug

Everytime the Epic library is refreshed I got this error:

Legendary (Epic Games)
Error:
An error has occurred! Try to Logout and Login on your Epic account.
Available games:
* 20XX (App name: Quail | Version: 1.42.13rc1)
* 3 out of 10, EP 1: "Welcome To Shovelworks" (App name: Flounder | Version: R01_S01_E05_V007_CL16693)
* 3 out of 10: Season Two (App name: 9a1aae61129247fb971ce96ab6a959da | Version: S02_Release_V002_CL16694)
* >observer_ (App name: Tumeric | Version: 1.0.0d)
* A Plague Tale: Innocence (App name: e0fa47ae79514345823bff209ae29451 | Version: EGS_1.08.4)
* A Short Hike (App name: d6407c9e6fd54cb492b8c6635480d792 | Version: 1.9_v3_Windows)
* A Total War Saga: TROY (App name: 11e598b192324994abce05bad4f81b50 | Version: 16581.2782747)
* Absolute Drift (App name: 19927295d6e3467887d4e830d8c85963 | Version: Win_202305111447)
* ABZU (App name: Curry | Version: 1.0)
* AER Memories of Old (App name: 26b63c46de9e4dcc856b3c6b106b6777 | Version: 1.0.4.1)
* Airborne Kingdom (App name: Macaw | Version: 1.10.1-Win64)
* Airborne Kingdom Community Test Environment (App name: 01335258501c4e65a36e3bf2c1887c5c | Version: 00)
* Alan Wake's American Nightmare (App name: Condor | Version: 01.03)
* Alba - A Wildlife Adventure (App name: 8a0173bbe3ac48ac903f5bc7277e7b4e | Version: 1.2.4)
* Alien: Isolation (App name: 8935bb3e1420443a9789fe01758039a5 | Version: 1.0RC5.284847.51533)
* Amnesia: The Dark Descent (App name: ece4c58603d04bcb97454be9a7492fa6 | Version: 1.5)
* Amnesia: A Machine for Pigs (App name: d7db33dfe7634d6b8a188c708f2caa3c | Version: 1.2)
* Amnesia: Rebirth (App name: f59de18db4dc445f88ffeff24d081234 | Version: 1.42)
* Among the Sleep - Enhanced Edition (App name: aa78f7be2ee64193b6b6444c5fc50157 | Version: Windows.3.1.0.41_Win64_DLL_Fix)
* Ancient Enemy (App name: a96de508ac71471fa05e7c1c695e3b5d | Version: 1.03fix)
* Anodyne 2: Return to Dust (App name: Tanzanite | Version: Win_1.32)
* ARK: Survival Evolved (App name: aafc587fbf654758802c8e41e4fb3255 | Version: 357.9.win)
* Ashen (App name: Wren | Version: 1.0.17.0)
* Assassins Creed Syndicate (App name: Albacore | Version: 1.54)
- This game can be activated directly on your Ubisoft account and does not require legendary to install/run. Use "legendary activate --uplay" and follow the instructions.
* Aven Colony (App name: dc07b9ead8214591b8df6d2546d2a0e3 | Version: 15)
* Axiom Verge (App name: Puffin | Version: 1.53)
* Axiom Verge Randomizer Beta (App name: 3017c57256b640519e6b84b44a4ac940 | Version: 1.58)
* Barony (App name: c98c4cd6d83a4524b4b22f13af95a104 | Version: v3.3.7-010920)
* Barony (Beta) (App name: 24349b736ad74d9db72e6cab21933877 | Version: v3.9.0-qodbeta110323)[cli] INFO: Logging in...[Core] INFO: Trying to re-use existing login session...[cli] INFO: Getting game list... (this may take a while)Traceback (most recent call last):
File "legendary/cli.py", line 3061, in <module>
File "legendary/cli.py", line 2972, in main
File "legendary/cli.py", line 239, in list_games
UnicodeEncodeError: 'ascii' codec can't encode character '\u2122' in position 9: ordinal not in range(128)
[292] Failed to execute script 'cli' due to unhandled exception!

### Add logs

```text
(08:33:13) INFO:    [Legendary]:        Refreshing library...
(08:33:13) INFO:    [Legendary]:        Refreshing Epic Games...
(08:33:13) INFO:    [Connection]:       Connectivity: check-online
(08:33:13) INFO:    [Connection]:       Pinging external endpoints
(08:33:13) INFO:    [Legendary]:        Running command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary --version
(08:33:13) INFO:    [Legendary]:        Legendary location: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary
(08:33:13) INFO:    [Gog]:              GOGDL location: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl
(08:33:13) INFO:    [Gog]:              GOGDL location: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl
(08:33:13) INFO:    [Legendary]:        Game list updated, got 234 games & DLCs
(08:33:13) WARNING: [Backend]:          Failed to register protocol with OS.
(08:33:13) INFO:    [Connection]:       Connectivity: online
(08:33:13) INFO:    [Gog]:              Checking if login is valid
(08:33:13) INFO:    [Gog]:              Running command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth
(08:33:13) INFO:    [Gog]:              Running command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json --version
(08:33:13) INFO:    [Legendary]:        Running command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary list --third-party
(08:33:14) INFO:    [Backend]:          Loading Screen Ready
(08:33:14) INFO:    [Frontend]:         Refreshing Library
(08:33:14) WARNING: [Backend]:          listUpdateableGames not implemented on Sideload Library Manager
(08:33:14) INFO:    [Gog]:              Found 0 game(s) to update
(08:33:14) INFO:    [Backend]:          Frontend Ready
(08:33:14) INFO:    [Backend]:          AreWeAntiCheatYet data downloaded
(08:33:14) INFO:    [Backend]:          

Heroic Version: 2.7.1 Eustass Kid
Legendary Version:  0.20.32 Dark Energy (hotfix #6)
GOGdl Version: 0.7.1

Electron Version: 23.1.4
Chrome Version: 110.0.5481.192
NodeJS Version: 18.12.1

OS: Freedesktop SDK KERNEL: 5.13.0-valve36-1-neptune ARCH: x64
CPU: AMD Custom APU 0405 @2.49 GOVERNOR: schedutil
RAM: Total: 14.47 GiB Available: 8.49 GiB
GRAPHICS: GPU0: VanGogh [AMD Custom GPU 0405] VRAM: 512MB 
PROTOCOL: x11

(08:33:14) INFO:    [Backend]:          Checking for current version changelog
(08:33:14) INFO:    [Gog]:              Saved username to config file
(08:33:14) INFO:    [Legendary]:        Checking for game updates: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary list --third-party
(08:33:15) INFO:    [Winetricks]:       Downloading Winetricks
(08:33:16) DEBUG:   [Legendary]:        Update is available for Min: 38291-x64 != 38294-x64
(08:33:16) INFO:    [Legendary]:        Found 1 game to update
(08:33:19) INFO:    [Backend]:          Starting the Download Queue
(08:37:02) INFO:    [Legendary]:        Getting more details with 'legendary info'
(08:37:03) INFO:    [Backend]:          Preventing machine to sleep
(08:37:04) INFO:    [Legendary]:        Running command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary info Min --platform Windows --json
(08:37:09) INFO:    [DownloadManager]:  Hades  was added to the download queue.
(08:37:09) DEBUG:   [Legendary]:        Using cached install info
(08:37:09) INFO:    [Legendary]:        Updating Min: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary update Min -y
(08:37:09) DEBUG:   [Legendary]:        Logging to file "/home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/GamesConfig/Min.log"
(08:37:17) INFO:    [Legendary]:        installed.json updated, refreshing library
(08:37:17) INFO:    [Legendary]:        installed.json updated, refreshing library
(08:37:17) INFO:    [DownloadManager]:  Finished Update of Min
(08:37:17) INFO:    [DownloadManager]:  Min added to download manager finished.
(08:37:17) INFO:    [DownloadManager]:  Min removed from download manager.
(08:37:17) INFO:    [Frontend]:         Refreshing Library
(08:37:17) WARNING: [Backend]:          listUpdateableGames not implemented on Sideload Library Manager
(08:37:17) INFO:    [Gog]:              Found 0 game(s) to update
(08:37:17) INFO:    [Legendary]:        Checking for game updates: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary list --third-party
(08:37:20) INFO:    [Legendary]:        Found 0 games to update
(08:37:40) INFO:    [Frontend]:         Refreshing Library
(08:37:40) WARNING: [Backend]:          listUpdateableGames not implemented on Sideload Library Manager
(08:37:40) INFO:    [Gog]:              Found 0 game(s) to update
(08:37:41) INFO:    [Legendary]:        Checking for game updates: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary list --third-party
(08:37:45) INFO:    [Legendary]:        Found 0 games to update
(08:39:40) INFO:    [Frontend]:         Refreshing Library
(08:39:40) WARNING: [Backend]:          listUpdateableGames not implemented on Sideload Library Manager
(08:39:40) INFO:    [Gog]:              Found 0 game(s) to update
(08:39:41) INFO:    [Legendary]:        Checking for game updates: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary list --third-party
(08:39:44) INFO:    [Legendary]:        Found 0 games to update
```

### Steps to reproduce

1. Open Epic Launcher or refresh the library
2. See error

### Expected behavior

To not see the error

### Heroic Version

Latest Stable

### System Information

Steam Deck. SteamOS is updated.

**Comment by arielj** [comment]
Can you try with heroic 2.10.0? we updated the legendary binary

**Comment by matteozel** [comment]
with the 2.10 the error is not appearing anymore!

**Comment by matteozel** [comment]
uops, I didn't realize that I'm able to close the issue :) Closing because it's solve!
