### ISSUE TITLE
Update Links to SignPath

### ISSUE THREAD

**Issue by SabotageAndi** [Heroic-Games-Launcher/HeroicGamesLauncher#2708]
### Describe the bug

Hi!

Sorry if I am using the wrong issue template. This was the best match I found for my request.
I am the Developer Evangelist of SignPath.

Could you change the links to signpath.io to https://signpath.io/?utm_source=foundation&utm_medium=github&utm_campaign=heroicgameslauncher in your Readme.md?

If you want, I can submit a PR for this.
Thanks!

### Add logs

```text
-
```

### Steps to reproduce

-

### Expected behavior

-

### Heroic Version

Latest Stable

### System Information

-

**Comment by flavioislima** [comment]
@SabotageAndi sure, open a PR if you have the time.
Thanks

**Comment by SabotageAndi** [comment]
@flavioislima done: https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/pull/2711
