### ISSUE TITLE
Game (Death Stranding Director's Cut) duplicating 4 times

### ISSUE THREAD

**Issue by chikachit69** [Heroic-Games-Launcher/HeroicGamesLauncher#2720]
### Describe the bug

I own the Base Death Stranding and the Director's Cut Upgrade which should show up as either a one game or a single game with dlc, instead i now have 4 seperate heroic entries 

### Add logs
[legendary-2023-05-20T20_00_42.696Z.log](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/files/11523118/legendary-2023-05-20T20_00_42.696Z.log)
[heroic-2023-05-20T20_00_42.696Z.log](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/files/11523119/heroic-2023-05-20T20_00_42.696Z.log)

### Steps to reproduce

1. Own Base Death Stranding + the Director's Cut Upgrade
2. Go to '.Library'

### Expected behavior

One single Heroic entry shows up with a prompt to download the extra content that appears when i click install, similar to when installing dlc from GOG games

### Screenshots
![8](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/assets/129736109/1c61a8a8-c74f-47a9-8fd4-b493937ecb3d)
![7](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/assets/129736109/c20737cb-3d59-4f28-8180-0be601d03582)
![6](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/assets/129736109/66f9c2cd-0802-446d-87a8-0e2d16247466)
![5](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/assets/129736109/4467d221-0637-487b-9a6b-d470c61c47c7)
![4](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/assets/129736109/ab19cbc1-2e41-4283-8908-7b699155354c)
![3](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/assets/129736109/34e067c5-4a79-4b78-b4b8-e43deccdf067)
![2](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/assets/129736109/d8024b7f-36a1-450d-ae40-c0c3c00752be)
![1](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/assets/129736109/5db01c5a-e3c5-415a-9cd4-51ef8a9cf75a)

### Heroic Version

Latest Stable

### System Information

Pop!Os 22.04
FlatHub Heroic 2.7.1 Hotfix #1

**Comment by flavioislima** [comment]
That's because internally epic treat them as different "games". You can hide the ones you don't want to see by right clicking on the card and then Hide Game.
