### ISSUE TITLE
Cannot play most / any games. Epic service unavailable. And asks to download other launcher when trying to add games to library.

### ISSUE THREAD

**Issue by ScarletMcLearn** [Heroic-Games-Launcher/HeroicGamesLauncher#2722]
### Describe the bug

Cannot play most / any games. Epic service unavailable. And asks to download other launcher when trying to add games to library.

### Add logs

```text
Unavailable service
```

### Steps to reproduce

2. Click on '...'
3. Scroll down to '...'

### Expected behavior

Should install and play.

### Heroic Version

Latest Stable

### System Information

Linux Mint XFCE

**Comment by flavioislima** [comment]
Please update the issue with more information otherwise we will close it.

We don't even know how did you install heroic or what your system is. It's complicated to help like this.

**Comment by arielj** [comment]
closing since there little to no info and no answer after 2 weeks
