### ISSUE TITLE
Fortnite DirectX 12 shaders not available

### ISSUE THREAD

**Issue by LuisMayo** [Heroic-Games-Launcher/HeroicGamesLauncher#2724]
### Describe the bug

Currently Fortnite needs an additional "DX12 shaders" component to be installed in order to be able to enable Direct X12.  However, this isn't shown in the components list while installiing

### Add logs

```text
N/A?
```

### Steps to reproduce

1. Go to 'Library/Fortinte'
2. Click on 'Install'
3. Look for the Shaders component
4. You won't find it

### Expected behavior

I guess it should appear? To be fair I don't really use the Epic Games Store at all so I don't know if it shows there. I just know Fortnite asks me to install them "In the launcher" and In my launcher the option just isn't there

### Heroic Version

Latest Stable

### System Information

- OS: Windows 10

### Additional information

This will be better if #2694 gets implemented

**Comment by arielj** [comment]
closing, this is fixed in the new 2.8.0 release

![image](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/assets/188464/a6e7f134-38a3-4bdd-9375-08ca032c7034)

**Comment by Romz24** [comment]
@arielj 
I already have the game installed, how can I call up this menu to add a new component?

**Comment by arielj** [comment]
currently there's no way to trigger this changes from heroic for an installed game, that only appears during installation of the whole game

check this discord thread for a workaround https://discord.com/channels/812703221789097985/1186523980237127820/1186523980237127820

**Comment by ArchOwlen** [comment]
Discord Thread link seems to not exist, but I found another one saying launch with "-d3d11" in launch arguments

**Comment by bigc0** [comment]
Any updated workarounds to install DirectX 12 shaders after installing the game?

**Comment by auvio323** [comment]
> Discord Thread link seems to not exist, but I found another one saying launch with "-d3d11" in launch arguments

The discord thread does exist; make sure to join their discord at invite `rHJ2uqdquK` or whatever invite is listed on their discord and that link should work.

Basically, the Discord thread says to open CMD and type these commands:
`SET "LEGENDARY_CONFIG_PATH=%APPDATA%\heroic\legendaryConfig\legendary"
` (this is the first command you need to run, and it makes sure legendary is set to the config that heroic games launcher uses)
`"%LOCALAPPDATA%\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\legendary" repair Fortnite --reset-sdl` (This is the second command you need to run, and it uses the legendary binary bundled with herioc games launcher to command a repair to fortnite, and you should get an output in cmd. After it is done verifying Fortnite, you should see a prompt in the CLI to select select optional packs. Make sure you type 'dx12' or whatever other optional packs you want. After this it will download the DX12 pack into Fortnite and it should work.

In case you still experience issues, someone in the Discord thread said the following helped them: try cd into "%LOCALAPPDATA%\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\" directory and then run `legendary.exe auth`. For me when I tried running that (not the person in the discord thread), the built in webview froze, so I had to run the command with `legendary auth --disable-webview` to work. If legendary tells you that you are already authenticated then you are good to go. Runing the commands in the directory "%LOCALAPPDATA%\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\" could also fix issues if your thing still isnt working. 

Hope this helped!
