### ISSUE TITLE
When logging in through the browser, it doesn't return response to the app

### ISSUE THREAD

**Issue by mks-h** [Heroic-Games-Launcher/HeroicGamesLauncher#2731]
### Describe the bug

I couldn't login to Epic through the embedded browser due to captcha, so I tried the "open in browser" button. I'm logged in in my browser, so it immediately returned me a JSON. I assume it had to send this JSON back to Heroic, but it didn't — the app still thinks I'm not logged in, and I'm staring at JSON in my browser's window.

The JSON has `redirectUrl` property with a value starting with `https://localhost/launcher/authorized?code=`, `authorizationCode` that is the same as the one after `code=`, and `sid` property equal to `null`

### Add logs

```text
(12:22:42) INFO:    [Legendary]:        Refreshing library...
(12:22:42) INFO:    [Connection]:       Connectivity: check-online
(12:22:42) INFO:    [Connection]:       Pinging external endpoints
(12:22:42) INFO:    [Legendary]:        Running command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary --version
(12:22:42) INFO:    [Legendary]:        Legendary location: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary
(12:22:42) INFO:    [Gog]:              GOGDL location: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl
(12:22:42) INFO:    [Gog]:              GOGDL location: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl
(12:22:42) WARNING: [Backend]:          Failed to register protocol with OS.
(12:22:42) INFO:    [Connection]:       Connectivity: online
(12:22:42) INFO:    [Backend]:          User Not Found, removing it from Store
(12:22:42) INFO:    [Gog]:              Running command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/mks/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json --version
(12:22:42) INFO:    [Backend]:          AreWeAntiCheatYet data downloaded
(12:22:43) INFO:    [Backend]:          Loading Screen Ready
(12:22:43) INFO:    [Backend]:          Frontend Ready
(12:22:43) INFO:    [Backend]:          

Heroic Version: 2.7.1 Eustass Kid
Legendary Version:  0.20.32 Dark Energy (hotfix #6)
GOGdl Version: 0.7.1

Electron Version: 23.1.4
Chrome Version: 110.0.5481.192
NodeJS Version: 18.12.1

OS: Freedesktop SDK KERNEL: 6.2.15-300.fc38.x86_64 ARCH: x64
CPU: Intel Core™ i5-6200U @2.3 GOVERNOR: powersave
RAM: Total: 7.63 GiB Available: 3.24 GiB
GRAPHICS: GPU0: Skylake GT2 [HD Graphics 520]  VRAM: 256MB GPU1: GM108M [GeForce 940MX]  VRAM: 32MB 
PROTOCOL: wayland

(12:22:43) INFO:    [Backend]:          Checking for current version changelog
(12:22:44) INFO:    [Winetricks]:       Downloading Winetricks
(12:22:48) INFO:    [Backend]:          Starting the Download Queue
```

### Steps to reproduce

1. Go to 'Log in'
2. Click on 'EPIC GAMES LOGIN'
3. Click on 'Open in browser' (top-tight corner)
4. Login in necessary
5. You will see JSON in the browser's window
6. You still will not be logged in in Heroic

### Expected behavior

Log me in

### Heroic Version

Latest Stable

### System Information

- OS Fedora
- Packaging Flathub
- Browser Firefox (Flathub)
- Heroic Version 2.7.1

**Comment by imLinguin** [comment]
![obraz](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/assets/62100117/e0ade42c-9436-4ec0-9ad8-0737ed6c1c32)

This is expected behaviour at this moment, like the attached instruction states

**Comment by mks-h** [comment]
Oh. I didn't even read past the first option. Sorry. Although I'd suggest combining the two options
