### ISSUE TITLE
Allow settings Custom User Agent for Web Sideloads

### ISSUE THREAD

**Issue by JakobDev** [Heroic-Games-Launcher/HeroicGamesLauncher#2757]
### Problem description

Some Webapps e.g. [YouTube TV](https://www.youtube.com/tv), which has a better Interface for the Steam Deck than normal YouTube, requires a custom User Agent to work. 

### Feature description

Allow settings a User Agent. That could be a Dropbox with a list of Popular User Agents e.g. Smart TVs together with a Textfield in which the User can add a own User Agent that is not in the List.

**Comment by flavioislima** [comment]
That is useful and should be simple to implement:

- On the Sideload Dialog add a new Select component with a list of user agents and a 'Custom' one. (maybe default to chrome on Windows)
- When selecting custom, show an input to write the UA.
- Save it inside the sideloaded store with the game information.
- When creating the BrowserWindow with the URL, pass the user-agent as an argument.

**Comment by Massakera** [comment]
Hii @flavioislima, where I can locate the Sideload Dialog?

**Comment by Doc-4** [comment]
You may need to do more to have total functionality on relevant web apps. Nvidia GeForce Now has started using UA client hints, which a dedicated project ran into and fixed last month here: https://github.com/hmlendea/gfn-electron/pull/184

**Comment by flavioislima** [comment]
> You may need to do more than just UAstring spoofing to have total functionality on relevant web apps. Nvidia GeForce Now has started using UA client hints, which a dedicated project ran into and fixed last month here: https://github.com/hmlendea/gfn-electron/pull/184
> Without this, important settings and some games (notably Genshin Impact) are missing.

Interesting, I think we should add these changed here as well.

**Comment by Doc-4** [comment]
Any update on the status of this feature? The project I mentioned in a prior post has given up on making their app able to truly obfuscate every linux identifier as methods change, unfortunately something that is somewhat needed for a number of web apps and sites that try to serve a lesser site to linux users.

**Comment by flavioislima** [comment]
Implemented here: https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/pull/3191
