### ISSUE TITLE
Can't build as descriped

### ISSUE THREAD

**Issue by Nocccer** [Heroic-Games-Launcher/HeroicGamesLauncher#276]
Hello,

Maybe i'm dumb.

I checked out the repostiroy and followed the Readme to build the project with yarn.
Im not familiar with yarn at all but with npm and electron.

If i type yarn install it tells me:
00h00m00s 0/0: : ERROR: [Errno 2] No such file or directory: 'install'

I really like this project and wan't to write some test's via mocha.
(If the test's are worth, i will do a pull-request)

What i missing here ? NodeJs and Yarn are installed. I using Pop os.

Regards
Niklas

**Comment by Flonky** [comment]
From my knowledge you can just run "yarn" and dont have to run "yarn install".
I recommend you to take a look at my pull request with the updated readme, i discrbed the manual installation there how it was explained to me in the discord.

**Comment by Nocccer** [comment]
I checked your branch and tried that as well...
Errror: 00h00m00s 0/0: : ERROR: There are no scenarios; must have at least one.

I think i missing something here. Im the only one trying this on pop os (Ubuntu)?
If this is not a fault of my dumbness, maybe we need to update the build porcess and readme?

**Comment by flavioislima** [comment]
Are you on the or are next project folder?

**Comment by Nocccer** [comment]
I think so.

My steps:

`
git clone https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher heroic
cd heroic
yarn
00h00m00s 0/0: : ERROR: There are no scenarios; must have at least one.
`

**Comment by Nocccer** [comment]
Ok i found my issue.
I expected that yarn is already in the common debian repositorys.
So i typed `sudo apt install yarn` which installed somehow cmdtest which has a scenario testing tool called "yarn" included.

Now everything works fine, with the correct yarn installed.

Anyway thanks alot for the help.

**Comment by flavioislima** [comment]
Nice. Yeah, always use npm to install yarn. Also, don't install node using apt, install nvm or asdf and install node from there to avoid using sudo to install global packages. It is a great security risk for your system using sudo for npm packages.

Last but no least, before start working in some feature or anything for heroic, go to the development channel on our discord to discuss your ideas and get help there. The link is on the read me. 😁
