### ISSUE TITLE
Heroic Launcher stuck in loading animation after logging in 

### ISSUE THREAD

**Issue by Slayr** [Heroic-Games-Launcher/HeroicGamesLauncher#278]
After many failed attempts at logging in, I got one right, and then The launcher enters its loading screen, and has been there for multiple hours, and has persisted after quitting the app and opening it again, and restarts.
I expected to get to the games list, but i never got there. 

![image](https://user-images.githubusercontent.com/77377160/112746130-a63b4500-8fca-11eb-8b72-461f5b80e8f6.png)

- OS: Pop_OS
- Version 20.10
- Game:
- Wine/Proton version:

**Comment by Kjell291** [comment]
Try deleting the content of ~/.config/legendary/metadata
This worked for me

**Comment by flavioislima** [comment]
Might be some corrupted file. Try first to delete or rename the `.config/heroic` folder.
If this doesn't work. try to do the same with `.config/legendary`.

**Comment by flavioislima** [comment]
@Slayr do you still have this issue? I'll close it and if you need, reopen it.
