### ISSUE TITLE
[Feature Request] [macOS] Detect installed Apple's Game Porting Toolkit

### ISSUE THREAD

**Issue by mavethee** [Heroic-Games-Launcher/HeroicGamesLauncher#2786]
### Feature description

This would allow to run more games especially the DX12 ones and wouldn't limit people to Wine-CrossOver / Wine / CrossOver.

### Alternatives

Currently there's a [method](https://www.applegamingwiki.com/wiki/Game_Porting_Toolkit#Epic_and_GOG.com_support) with replacing files but Heroic doesn't seem to like replacing files as it doesn't work for me and have to use Terminal to launch installed games.

Some games even freak out and you have to be in game directory to execute it correctly without missing files, eg. Control.

**Comment by flavioislima** [comment]
@mavethee just opened a PR with support for it. Need testers!

#2787
