### ISSUE TITLE
Choose beta channel for GOG

### ISSUE THREAD

**Issue by RikudouSage** [Heroic-Games-Launcher/HeroicGamesLauncher#2791]
### Problem description

Some games (Timberborn in this case) autoselect a beta channel and I can't disable it to get the stable version.

### Feature description

Option to select if and which beta channel to use.

**Comment by imLinguin** [comment]
Latest version of Heroic should choose stable branch instead. Try reinstalling the game on 2.8.0 Heroic version

**Comment by RikudouSage** [comment]
Can confirm it works now, though the ability to select a beta channel would still be nice.

**Comment by imLinguin** [comment]
This is the part of upcoming refactor. Will keep posting on this issue
