### ISSUE TITLE
Gog disappearing 

### ISSUE THREAD

**Issue by Zanomi** [Heroic-Games-Launcher/HeroicGamesLauncher#2797]
### Describe the bug

Whenever I download middle earth shadow of war on gog all the gog games disappear but I am still logged into gog on the store. I can sign in and out but nothing happens. I have to delete the app every time and if I download shadow of war again the same thing happens.

### Add logs

```text
Unavailable (had to delete)
```

### Steps to reproduce

1. Download shadow of war on gog
2. Wait for download to finish
3. Gog gone

### Expected behavior

My gog games are still available 

### Heroic Version

Latest Stable

### System Information

- OS Ubuntu

**Comment by somebody1121** [comment]
It happend to me today, but downloading the silver case. It wouldn't start so i uninstalled it. After that, all the games installed on the default location were mark as unavilable. I look into the installation folder and it was empty. The games i selected to install outside function as always. Also redownloading didn't work, every game has missing files and veryfing them didn't help. Appears to be something wrong with gog.

**Comment by arielj** [comment]
Closing this since the last comment from June mentions it's not happening anymore.

We can reopen if the problem reappears (or if it's not really gone at all)
