### ISSUE TITLE
Launcher freezes when try to download big games like Fortnite or Watch Dogs 2

### ISSUE THREAD

**Issue by mrbean457** [Heroic-Games-Launcher/HeroicGamesLauncher#280]
the Launcher complety freezes (you can not cancel the download without closing the whole launcher) and is stuck at (i think) getting the size of the game or preparing the download. i find this out by running herotic via the terminal. Probably same issue as https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/issues/277

Operating System Pop OS 20.04

Fortnite
![Bildschirmfoto von 2021-03-28 19-56-35](https://user-images.githubusercontent.com/44673644/112762663-27153380-9001-11eb-8775-5b99657b0d07.png)

Watch Dogs 2
![Bildschirmfoto von 2021-03-28 20-09-35](https://user-images.githubusercontent.com/44673644/112762743-a99df300-9001-11eb-866e-290fba47774c.png)

**Comment by adityaruplaha** [comment]
Hi, please repost this on the original thread, this is the same as #277.
