### ISSUE TITLE
Please can you tell me how to uninstall this.

### ISSUE THREAD

**Issue by nick123456789025** [Heroic-Games-Launcher/HeroicGamesLauncher#2813]
### Problem description

There is no documentation now to uninstall this software. When you do the normal pacman command to uninstall it does not remove everything. Add documentation, add a script. I am fed up with developers for getting about this. There needs to be a way to completely remove it, not the games the launcher.

### Feature description

Add uninstall option

### Alternatives

Provide an uninstall script

### Additional information

There needs to be documentation on this. PS. I don't care if this is formatted properly. I just care that you see it. I am way too tired and way too pissed off for this.

**Comment by outphase** [comment]
Delete `~/.config/heroic/`

When your goal is to remove configs for any app, you can always start looking in `~/.local/share/` or `~/.config/`. These folders are not created by `pacman` nor should they be removed by `pacman`.

**Comment by nick123456789025** [comment]
Thanks. I was a little ticked off because I couldn't find where they were
located. I'm fairly new to Arch and I'm trying to daily drive it and I had
to restore from a timeshift back up breaking everything when it comes to
wine and steam proton so now I'm trying to fix that whole mess.

**Comment by JakobDev** [comment]
You may want to try the Heroic Flatpak. The Data of the Flatpak are completely separated from the Rest of the System.

**Comment by arielj** [comment]
Added a Wiki page with the things to delete depending on the OS and installation method: https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/wiki/Removing-Uninstalling-Heroic-Games-Launcher
