### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Minzimixx** [Heroic-Games-Launcher/HeroicGamesLauncher#2820]
### Describe the bug

When I log in it gives me an error saying "legendary epic account" It has promted me to log out and back in.

I have done so multiple times I have reinstalled the launcher nothing seems to be working.

if anyone could help me that would be amazing!

### Add logs

```text
nothing
```

### Steps to reproduce

2. Click on '...'
3. Scroll down to '...'

### Expected behavior

lets me play

### Screenshots

none i have atm

### Heroic Version

Latest Stable

### System Information

- OS [e. g. "Ubuntu"]:

**Comment by arielj** [comment]
please fill in all the information, what's your OS? add a screenshot, you say you don't have logs but that there's a message in the screen, it's impossible to help with no details

**Comment by Minzimixx** [comment]
ok
