### ISSUE TITLE
[UI] Heroic always comes to the foreground after a game exits

### ISSUE THREAD

**Issue by Slater91** [Heroic-Games-Launcher/HeroicGamesLauncher#2825]
### Describe the bug

Heroic automatically restores its window and brings it to the fore after a game exits. The application shouldn't activate itself unless selected by the user.

### Add logs

```text
.
```

### Steps to reproduce

1. Open a game
2. Minimise Heroic
3. Exit the game

### Expected behavior

Nothing happens and Heroic stays in the state the user left it in (e.g. minimised, or behind another window).

### Heroic Version

Latest Stable

### System Information

- OS [e. g. "Ubuntu"]: KDE Neon (based on Ubuntu 22.04)

### Additional information

"Minimise Heroic after game launch" is deselected. 

This was marked as "fixed" in bug #727 and then again for #2478, but the bug is present again.

**Comment by imLinguin** [comment]
This is fixed upstream by #2502 , and will be available in next release. You can try it out using builds from main branch
