### ISSUE TITLE
Unable to login to epic game store using google

### ISSUE THREAD

**Issue by GM-Script-Writer-62850** [Heroic-Games-Launcher/HeroicGamesLauncher#283]
**Describe the bug**
https://imgur.com/khrme3p.png

**To Reproduce**

1. Click on Store (top left)
2. Click on google
3. enter user name
4. get rejected by google

**Comment by flavioislima** [comment]
Hi!

Unfortunately this won't work because google does not recognize heroic as a safe App. 
this is a global issue with, no only electron, but other types of web engine as well.
For now, use your epic credentials

**Comment by GM-Script-Writer-62850** [comment]
Would it be possible to have it open a link in the default web browser, perhaps a setting to decide what the store button/link does (internal vs external)

to me that sounds like more a anti-competitive move disguised as a security move from google

**Comment by adityaruplaha** [comment]
It won't work. Then you won't be authenticated. That's why even if you login into Epic Games on Chrome, you need to login again on Heroic. Since each electron app behaves like a seperate browser.

**Comment by dragonDScript** [comment]
This could be fixed by setting a different userAgent.
