### ISSUE TITLE
client side decorations

### ISSUE THREAD

**Issue by ghost** [Heroic-Games-Launcher/HeroicGamesLauncher#2833]
### Problem description

usually when you run electron applications in wayland natively and they don't have their own CSD, there won't be any window decorations by default

of course there is also a flag `--enable-features=WaylandWindowDecorations` but generally the compositor's/wm's window decorations don't really fit the app

### Feature description

HGL could have it's own window decorations, with an option to disable that and use native window decor/titllebar
that way you could have a consistent look across all systems even and have decorations for wayland

### Additional information

additionally, if possible, the CSD should respect system preferences and hide minimize and maximize buttons and also move the buttons to the left if requested (e.g. in GNOME you can hide each button and move them, by default only close button shows)

the CSDs would be styled with themes, possibly include css for macOS spotlights?

**Comment by nvkomimi** [comment]
made some mockups to show what I meant by this:

1st: (pretty standard)
![mockup1](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/assets/76652465/79bf1602-f21b-448a-a195-85ee33fd744f)
2nd: (mac, though the spotlights should probably be at the position like in the 3rd mockup below)
![mockup2](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/assets/76652465/1042afe3-5410-41c2-bf5a-869b648d9dc9)
3rd: (min & max buttons are disabled and buttons are moved to the left, suggesting that it respects os preferences)
![mockup3](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/assets/76652465/00d54dde-92fb-411e-a903-47d9d43ea524)

**Comment by arielj** [comment]
Closing this, this has been a feature for a few versions already (Settings > Use Frameless Window)
