### ISSUE TITLE
Red Dead Redemption 2 won't boot

### ISSUE THREAD

**Issue by Furaihai** [Heroic-Games-Launcher/HeroicGamesLauncher#284]
**Describe the bug**
Red Dead Redemption 2 doesn't boot through the launcher. To be fair I can't get RDR2 working through any launcher but it doesn't work here either.

**To Reproduce**

1. Open Heroic
2. Click launch RDR2
3. See the rockstar logo infinitely loading and ultimately timed out.

**Expected behavior**
For the game to load.

**Desktop (please complete the following information):**

- OS: Manjaro Cinnamon
- Version: Kernel 5.10.23
- CPU: AMD Ryzen 3900X
- GPU: AMD Radeon 6900 XT
- Driver: Mesa 20.3
- Game: Red Dead Redemption 2
- Wine/Proton version: proton-5.0-rdr2-4

**Comment by flavioislima** [comment]
Hi! if you need game support, go to our discord. GH is for issues with the launcher, not games. 👍🏽
