### ISSUE TITLE
[Feature Request] Ability to import/export hidden games

### ISSUE THREAD

**Issue by ScrambleTheRamble** [Heroic-Games-Launcher/HeroicGamesLauncher#2844]
### Problem description

I have multiple devices and multiple game stores,  these stores sometimes have duplicate games, eg Absolute Drift on GOG & EPIC. Heroic has the option to hide games from specific stores allowing you to hide these duplicates. However, you currently need to maintain this manually on every system running Heroic, eg Linux Desktop & Steam Deck or rebuild this if you reinstall Heroic.

### Feature description

Make it possible for exporting/importing the hidden games.

**Comment by arielj** [comment]
We currently have this other feature request to export/import all your settings (including the hidden games) https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/issues/1896

closing this issue in favor of that other one that is more complete
