### ISSUE TITLE
Winecfg and winetricks not using game specifig wineprefix

### ISSUE THREAD

**Issue by VortexAcherontic** [Heroic-Games-Launcher/HeroicGamesLauncher#285]
**Describe the bug**
Hey there if I launch winetricks of winecfg from the game settings tab it will not run those in the specified wine prefix but instead defaults to "~/.wine"

**To Reproduce**
1. Specifiy a dedicated wineprefix for a game
2. run winecfg or winetricks form the settings page
3. winetricks will list the current wineprefix in the window title

**Expected behavior**
- Using the right prefix

**Screenshots**

![Game settings](https://user-images.githubusercontent.com/11244092/113523978-dd51bd80-95ab-11eb-8df8-5683db007c84.png)

![Winetricks](https://user-images.githubusercontent.com/11244092/113099817-dbc67500-91fa-11eb-9c4a-a381f2a5aa04.png)

**Desktop (please complete the following information):**
- OS: openSUSE Tumbleweed
- Version: 1.5.7 (RPM)
- Game: Any
- Wine/Proton version: Lutris Wine 6.0

**Additional context**
I launched heroic via cli and noticed this output:

````
{
  command: "WINE='/home/vortex/.local/share/lutris/runners/wine/lutris-6.0-x86_64/bin/wine64' WINEPREFIX=/z004/sdd1/user/vortex/Spiele/Heroic/Rage2/.wine \n" +
    '    winetricks'
}
{
  command: "WINE='/home/vortex/.local/share/lutris/runners/wine/lutris-6.0-x86_64/bin/wine64' WINEPREFIX=/z004/sdd1/user/vortex/Spiele/Heroic/Rage2/.wine \n" +
    "    '/home/vortex/.local/share/lutris/runners/wine/lutris-6.0-x86_64/bin/wine64' winecfg"
}
````

I suspect it will not get the right prefix because the brackets ' are missing at WINEPREFIX=

**Comment by flavioislima** [comment]
Fixed in #335
