### ISSUE TITLE
Apple Game Porting Toolkit Support

### ISSUE THREAD

**Issue by blackxfiied** [Heroic-Games-Launcher/HeroicGamesLauncher#2857]
### Problem description

Now, I'm aware there's a pull request for this open, however, it's actually nonfuctional (#2832) 
The purpose of this post is just to act as a friendly reminder.

### Feature description

Apple's game porting toolkit is a development kit intended for use by game developers in order to simplify the process of game porting from the Windows operating system.

### Alternatives

CrossOver, but currently not as good at game porting toolkit, even though they are based on the same technology.

**Comment by flavioislima** [comment]
This was already implemented and will be available on the next release.

**Comment by pakkographic** [comment]
> This was already implemented and will be available on the next release.

Read the problem description.
