### ISSUE TITLE
[Feature Request] EA App support using new CrossOver 23 beta

### ISSUE THREAD

**Issue by mavethee** [Heroic-Games-Launcher/HeroicGamesLauncher#2859]
### Problem description

Until CrossOver 23, it wasn't possible to run games requiring EA app client, now once CX23 reached beta, there should be no issues with running EA app games.

~~Yes I'm aware The Sims 4 runs fine with Origin, this is just a quick example of Heroic blocking downloads~~
![CleanShot 2023-07-13 at 19 12 06@2x](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/assets/47083527/72fd17ab-b77e-46f4-9a82-8d5eb4d50ae5)

### Feature description

Allow to download, install and run games that require EA app as third party launcher.
Possibly implement check if at least CX23 is selected to reduce user's confusion?

**Comment by arielj** [comment]
The `Unsupported` state is not related to the version of Crossover (or Wine, or any of that). It's Unsupported because Heroic cannot install them to begin with.

Closing this since there's nothing to fix and we already have other feature request to support origin/ea app games
