### ISSUE TITLE
Better Discord RPC design

### ISSUE THREAD

**Issue by ghost** [Heroic-Games-Launcher/HeroicGamesLauncher#2869]
### Problem description

current RPC just blasts heroic as the main thing, overshadowing the game you are playing

### Feature description

it would be better to use the game's poster image/icon for the big icon and have Heroic's icon as a small icon

also instead of the Playing/main title being "Heroic Games Launcher" it could be the game's title, while Heroic Games Launcher being on the second line under it

I'm positive this can be done and shouldn't be too much effort, also I believe it's just a better design overall that actually showcases what you are playing immediately, while there's still Heroic mentioned

alternatively instead of "via Heroic on Linux" it could be 2 lines
"Heroic Games Launcher"
"on Linux"

same way you grab poster images for games for the library, you could probably get an icon

the current RPC design should be used when there isn't an icon to be found

### Alternatives

#2177

### Additional information

Current rich presence:

![Screenshot from 2023-07-19 12-29-02](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/assets/76652465/55836020-6181-43f7-9822-ab21e048bb49)

Example presence with the feature mentioned:

![Screenshot from 2023-07-19 12-29-28](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/assets/76652465/84f95971-a4a7-4eaa-bada-c061c020c55c)

Proposed rich presence design:

![Screenshot from 2023-07-19 12-37-12](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/assets/76652465/e10cded3-4429-4552-834a-b40c26c77592)

**Comment by imLinguin** [comment]
It's not possible for us to provide image for each game, the RPC is constructed in a way which only allows limited subset of  pre uploaded images that can be set by key.

We can only upload a few images to developer portal, when constructing the RPC request to the client we provide key of the image to display.
