### ISSUE TITLE
Couldn't find all library folders of Wine Default - wine-8.12!

### ISSUE THREAD

**Issue by LittFlower** [Heroic-Games-Launcher/HeroicGamesLauncher#2875]
### Describe the bug

Hello everyone!

I use the Hero Game installer on my Arch Linux and KDE wayland. Before I installed the Hero Game installer, I had already installed Wine, and then I installed the Autumn Guy. However, when I run Fall Guys in the game library, I am unable to successfully run it.

I tried fixing this error myself: I tried installing Wine GE Latest and modifying the wine version to 'Wine Wine GE Latest'. However, when I ran the game again, I failed again and the error was still `(19:09:56) Error: [Backend]: Unable to find all library folders for Wine Default - Wine 8.12!` in the log. This is strange, it seems that my settings have not worked. I have set up automatic save configuration and have tried restarting.

I am using the latest version of AppImage.

### Add logs

```text
(19:09:56) INFO:    [DXVKInstaller]:    installing dxvk on... /home/flower/Games/Heroic/Prefixes/default

(19:09:56) INFO:    [DXVKInstaller]:    dxvk already installed!

(19:09:56) INFO:    [DXVKInstaller]:    installing vkd3d on... /home/flower/Games/Heroic/Prefixes/default

(19:09:56) INFO:    [DXVKInstaller]:    vkd3d already installed!

(19:09:56) ERROR:   [Backend]:          Couldn't find all library folders of Wine Default - wine-8.12!

Missing undefined and/or undefined!

Falling back to system libraries!

(19:09:56) INFO:    [Legendary]:        Running command: /tmp/.mount_HeroicBx3J9J/resources/app.asar.unpacked/build/bin/linux/legendary launch 0a2d9f6403244d12969e11da6713137b --json --offline

(19:09:56) INFO:    [Legendary]:        Launching Fall Guys: LD_PRELOAD= WINEPREFIX=/home/flower/Games/Heroic/Prefixes/default WINEDLLOVERRIDES=winemenubuilder.exe=d ORIG_LD_LIBRARY_PATH=/tmp/.mount_HeroicBx3J9J/usr/lib: /tmp/.mount_HeroicBx3J9J/resources/app.asar.unpacked/build/bin/linux/legendary launch 0a2d9f6403244d12969e11da6713137b --language zh_Hans --wine /usr/bin/wine

(19:10:12) INFO:    [Backend]:          Stopping Display Power Saver Blocker

(19:10:12) INFO:    [Frontend]:         Refreshing legendary Library

(19:10:12) INFO:    [Legendary]:        Refreshing library...

(19:10:12) INFO:    [Legendary]:        Refreshing Epic Games...

(19:10:12) INFO:    [Legendary]:        Game list updated, got 1 games & DLCs

(19:10:14) INFO:    [Legendary]:        Running command: /tmp/.mount_HeroicBx3J9J/resources/app.asar.unpacked/build/bin/linux/legendary list --third-party
```

### Steps to reproduce

1. Go to the library which have had the Fall Guys;
2. Click on 'run';
3. Wait just a minute;
4. See error in the log.

### Expected behavior

I can run the game sucessfully.

### Screenshots

![image](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/assets/75172736/04e36df1-1e09-4d9c-8126-7b0698d0a20a)

### Heroic Version

Latest Stable

### System Information

```
                   -`                    
                  .o+`                   ----------------- 
                 `ooo/                   OS: Arch Linux x86_64 
                `+oooo:                  Host: ASUS TUF Gaming F15 FX507VV_FX507VV 1.0 
               `+oooooo:                 Kernel: 6.4.4-arch1-1 
               -+oooooo+:                Uptime: 1 hour, 28 mins 
             `/:-:++oooo+:               Packages: 1744 (pacman) 
            `/++++/+++++++:              Shell: zsh 5.9 
           `/++++++++++++++:             Resolution: 1920x1080 
          `/+++ooooooooooooo/`           DE: Plasma 5.27.6 
         ./ooosssso++osssssso+`          WM: KWin 
        .oossssso-````/ossssss+`         WM Theme: Layan 
       -osssssso.      :ssssssso.        Theme: [Plasma], Breeze [GTK2/3] 
      :osssssss/        osssso+++.       Icons: Tela [Plasma], Tela [GTK2/3] 
     /ossssssss/        +ssssooo/-       Terminal: konsole 
   `/ossssso+/:-        -:/+osssso+-     CPU: 13th Gen Intel i7-13700H (20) @ 4.800GHz 
  `+sso+:-`                 `.-/+oso:    GPU: Intel Raptor Lake-P [Iris Xe Graphics] 
 `++:.                           `-/+/   GPU: NVIDIA GeForce RTX 4060 Max-Q / Mobile 
 .`                                 `/   Memory: 6908MiB / 15613MiB 
```

### Additional information

Sincerely hope to receive everyone's help, thank you all.

**Comment by Ganther3301** [comment]
> ### Describe the bug
> 
> Hello everyone!
> 
> I use the Hero Game installer on my Arch Linux and KDE wayland. Before I installed the Hero Game installer, I had already installed Wine, and then I installed the Autumn Guy. However, when I run Fall Guys in the game library, I am unable to successfully run it.
> 
> I tried fixing this error myself: I tried installing Wine GE Latest and modifying the wine version to 'Wine Wine GE Latest'. However, when I ran the game again, I failed again and the error was still `(19:09:56) Error: [Backend]: Unable to find all library folders for Wine Default - Wine 8.12!` in the log. This is strange, it seems that my settings have not worked. I have set up automatic save configuration and have tried restarting.
> 
> I am using the latest version of AppImage.
> ### Add logs
> 
> ```
> (19:09:56) INFO:    [DXVKInstaller]:    installing dxvk on... /home/flower/Games/Heroic/Prefixes/default
> 
> (19:09:56) INFO:    [DXVKInstaller]:    dxvk already installed!
> 
> (19:09:56) INFO:    [DXVKInstaller]:    installing vkd3d on... /home/flower/Games/Heroic/Prefixes/default
> 
> (19:09:56) INFO:    [DXVKInstaller]:    vkd3d already installed!
> 
> (19:09:56) ERROR:   [Backend]:          Couldn't find all library folders of Wine Default - wine-8.12!
> 
> Missing undefined and/or undefined!
> 
> Falling back to system libraries!
> 
> (19:09:56) INFO:    [Legendary]:        Running command: /tmp/.mount_HeroicBx3J9J/resources/app.asar.unpacked/build/bin/linux/legendary launch 0a2d9f6403244d12969e11da6713137b --json --offline
> 
> (19:09:56) INFO:    [Legendary]:        Launching Fall Guys: LD_PRELOAD= WINEPREFIX=/home/flower/Games/Heroic/Prefixes/default WINEDLLOVERRIDES=winemenubuilder.exe=d ORIG_LD_LIBRARY_PATH=/tmp/.mount_HeroicBx3J9J/usr/lib: /tmp/.mount_HeroicBx3J9J/resources/app.asar.unpacked/build/bin/linux/legendary launch 0a2d9f6403244d12969e11da6713137b --language zh_Hans --wine /usr/bin/wine
> 
> (19:10:12) INFO:    [Backend]:          Stopping Display Power Saver Blocker
> 
> (19:10:12) INFO:    [Frontend]:         Refreshing legendary Library
> 
> (19:10:12) INFO:    [Legendary]:        Refreshing library...
> 
> (19:10:12) INFO:    [Legendary]:        Refreshing Epic Games...
> 
> (19:10:12) INFO:    [Legendary]:        Game list updated, got 1 games & DLCs
> 
> (19:10:14) INFO:    [Legendary]:        Running command: /tmp/.mount_HeroicBx3J9J/resources/app.asar.unpacked/build/bin/linux/legendary list --third-party
> ```
> 
> ### Steps to reproduce
> 
>     1. Go to the library which have had the Fall Guys;
> 
>     2. Click on 'run';
> 
>     3. Wait just a minute;
> 
>     4. See error in the log.
> 
> 
> ### Expected behavior
> 
> I can run the game sucessfully.
> ### Screenshots
> 
> ![image](https://user-images.githubusercontent.com/75172736/254868682-04e36df1-1e09-4d9c-8126-7b0698d0a20a.png)
> ### Heroic Version
> 
> Latest Stable
> ### System Information
> 
> ```
>                    -`                    
>                   .o+`                   ----------------- 
>                  `ooo/                   OS: Arch Linux x86_64 
>                 `+oooo:                  Host: ASUS TUF Gaming F15 FX507VV_FX507VV 1.0 
>                `+oooooo:                 Kernel: 6.4.4-arch1-1 
>                -+oooooo+:                Uptime: 1 hour, 28 mins 
>              `/:-:++oooo+:               Packages: 1744 (pacman) 
>             `/++++/+++++++:              Shell: zsh 5.9 
>            `/++++++++++++++:             Resolution: 1920x1080 
>           `/+++ooooooooooooo/`           DE: Plasma 5.27.6 
>          ./ooosssso++osssssso+`          WM: KWin 
>         .oossssso-````/ossssss+`         WM Theme: Layan 
>        -osssssso.      :ssssssso.        Theme: [Plasma], Breeze [GTK2/3] 
>       :osssssss/        osssso+++.       Icons: Tela [Plasma], Tela [GTK2/3] 
>      /ossssssss/        +ssssooo/-       Terminal: konsole 
>    `/ossssso+/:-        -:/+osssso+-     CPU: 13th Gen Intel i7-13700H (20) @ 4.800GHz 
>   `+sso+:-`                 `.-/+oso:    GPU: Intel Raptor Lake-P [Iris Xe Graphics] 
>  `++:.                           `-/+/   GPU: NVIDIA GeForce RTX 4060 Max-Q / Mobile 
>  .`                                 `/   Memory: 6908MiB / 15613MiB 
> ```
> 
> ### Additional information
> 
> Sincerely hope to receive everyone's help, thank you all.

Hey. I'm facing the same issue. how did you solve it?

**Comment by LittFlower** [comment]
...Anyway, I don't use Heroic anymore. I think you can play it via steam rather than Heroic.

**Comment by Mubelotix** [comment]
Still an issue. Happens on latest version (deb), still with fall guys. Using an amd gpu, as it works fine on another of my machines
