### ISSUE TITLE
Files are not removed after canceling an installation with the button on the gamecard

### ISSUE THREAD

**Issue by Kjell291** [Heroic-Games-Launcher/HeroicGamesLauncher#288]
**Describe the bug**
When canceling a installation with the button on the Gamecard and selecting to remove the files, the files are not removed. This does not happen if the installation is canceled with the button on the Gamepage.

**To Reproduce**

1. Start an installation
2. Cancel the installation with the button on the gamecard
3. Select to not keep the files
4. The files are still there

**Expected behavior**
The files are deleted

**Desktop**
- OS: Arch Linux

**Comment by flavioislima** [comment]
Probably something wrong on the frontend. I'll try to replicate the issue.

**Comment by adityaruplaha** [comment]
@Kjell291 can you recheck if this issue still happens?

**Comment by Kjell291** [comment]
It still happens with 1.7.0

**Comment by flavioislima** [comment]
Yeah, I can reproduce the issue!
Probably the stop installation function is not calling the function to remove the folder after hitting cancel.
