### ISSUE TITLE
New Heroic Update was detected as a trojan by Windows Defender

### ISSUE THREAD

**Issue by Pointing8422** [Heroic-Games-Launcher/HeroicGamesLauncher#2896]
### Describe the bug

I installed the new version of Heroic 2.9.0 on my Windows 11 machine with this file: "Heroic-2.9.0-Setup-x64.exe", and after start the app and try to login to epic every folder, file and process of Heroic was detected as a Troyan
<img width="756" alt="Captura de pantalla 2023-07-25 001721" src="https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/assets/66259936/7329833e-ddee-4da8-9f92-ed7c67c06908">

### Add logs

```text
The app was automatically deleted.
```

### Steps to reproduce

1. Install the new update
2. Execute Heroic
3. Try to login to epic
4. After that Windows Defender detect a trojan on every folder and process of Heroic, including Heroid.exe

### Expected behavior

Not have this problem.

### Heroic Version

Latest Stable

### System Information

Windows 11

**Comment by TonyTwoShanks** [comment]
This happened on my end as well. Same detected trojan as shown in your screenshot. The only difference was that it was detected and immediately quarantined before I could launch anything.

**Comment by flavioislima** [comment]
Hmm, maybe the signing didn't work then.
I will try to investigate the issue
