### ISSUE TITLE
Bug Report: "Flatpak Command Not Found" Error [SteamDeck][AMAZON GAMES]

### ISSUE THREAD

**Issue by eguren12** [Heroic-Games-Launcher/HeroicGamesLauncher#2899]
### Describe the bug

Description:

I encountered an issue while trying to launch the game "8Doors Arum's Afterlife Adventure" using Heroic on Arch Linux on AMAZON GAMES STORE. Every time I attempt to launch the game, I receive an error stating "FileNotFoundError: [Errno 2] No such file or directory: 'flatpak'".

Steps to Reproduce:

Launch Heroic on Arch Linux.
Attempt to launch the game "8Doors Arum's Afterlife Adventure" using the provided game settings.
Observe the error message mentioned above.
Expected Behavior:

I expected the game to launch successfully without any errors related to "flatpak".

Actual Behavior:

The game fails to launch, and I receive a "FileNotFoundError: [Errno 2] No such file or directory: 'flatpak'" error in the log.

System Information:

Operating System: Arch Linux
Heroic Version: 2.9.0 Boa Hancock
Wine Version: Proton - GE-Proton7-55
CPU: AMD Custom APU 0405 @3.33 GHz
RAM: Total: 14.47 GiB Available: 11.64 GiB
GPU: VanGogh [AMD Custom GPU 0405] VRAM: 512MB
Graphics Protocol: x11
Additional Notes:

I have already verified that Flatpak is installed on my system, and I can access it from the terminal. Additionally, I have added the Flatpak location to the PATH environment variable, but the issue persists.

### Add logs

```text
Game Settings: {
	"autoInstallDxvk": true,
	"autoInstallVkd3d": true,
	"preferSystemLibs": false,
	"enableEsync": true,
	"enableFsync": true,
	"nvidiaPrime": false,
	"offlineMode": true,
	"enviromentOptions": [],
	"wrapperOptions": [],
	"showFps": false,
	"useGameMode": false,
	"language": "",
	"wineVersion": {
		"bin": "/home/deck/.local/share/Steam/compatibilitytools.d/GE-Proton7-55/proton",
		"name": "Proton - GE-Proton7-55",
		"type": "proton"
	},
	"winePrefix": "/home/deck/Games/Heroic/Prefixes/default/8Doors Arums Afterlife Adventure",
	"wineCrossoverBottle": "",
	"eacRuntime": false
}

Game launched at: Tue Jul 25 2023 13:16:47 GMT+0200 (hora de verano de Europa central)

System Info:
Heroic Version: 2.9.0 Boa Hancock
Legendary Version:  0.20.32 Dark Energy (hotfix #6)
GOGdl Version: 0.7.3
Nile Version: 1.0.0 Jonathan Joestar

Electron Version: 24.4.1
Chrome Version: 112.0.5615.204
NodeJS Version: 18.14.0

OS: Freedesktop SDK KERNEL: 5.13.0-valve36-1-neptune ARCH: x64
CPU: AMD Custom APU 0405 @3.33 GOVERNOR: schedutil
RAM: Total: 14.47 GiB Available: 11.64 GiB
GRAPHICS: GPU0: VanGogh [AMD Custom GPU 0405] VRAM: 512MB 
PROTOCOL: x11

Launch Command: STEAM_COMPAT_CLIENT_INSTALL_PATH=/home/deck/.var/app/com.heroicgameslauncher.hgl/.steam/steam STEAM_COMPAT_DATA_PATH="/home/deck/Games/Heroic/Prefixes/default/8Doors Arums Afterlife Adventure" STEAM_COMPAT_INSTALL_PATH="/home/deck/Games/Heroic/8Doors Arum's Afterlife Adventure" WINE_FULLSCREEN_FSR=0 STEAM_COMPAT_APP_ID=0 SteamAppId=0 SteamGameId="heroic-8Doors: Arum's Afterlife Adventure" PROTON_LOG_DIR=/home/deck/.var/app/com.heroicgameslauncher.hgl /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/nile launch --no-wine --wrapper " '/home/deck/.local/share/Steam/compatibilitytools.d/GE-Proton7-55/proton' run" --wine-prefix "/home/deck/Games/Heroic/Prefixes/default/8Doors Arums Afterlife Adventure" amzn1.adg.product.c82d2124-433c-4d90-beba-e1ea3f57ffd9

Game Log:
INFO [CLI]:	 Searching for amzn1.adg.product.c82d2124-433c-4d90-beba-e1ea3f57ffd9
Traceback (most recent call last):
  File "nile/cli.py", line 343, in <module>
  File "nile/cli.py", line 328, in main
  File "nile/cli.py", line 241, in handle_launch
  File "nile/utils/launch.py", line 143, in start
  File "nile/utils/launch.py", line 81, in get_scummvm_command
  File "subprocess.py", line 505, in run
  File "subprocess.py", line 951, in __init__
  File "subprocess.py", line 1837, in _execute_child
FileNotFoundError: [Errno 2] No such file or directory: 'flatpak'
[317] Failed to execute script 'cli' due to unhandled exception!
```

### Steps to reproduce

2. Click on '...'
3. Scroll down to '...'

### Expected behavior

Verified Flatpak installation and PATH inclusion.
Restarted Heroic after making changes to PATH. ?????????

### Heroic Version

Latest Stable

### System Information

- OS SteamOS

**Comment by matheusfaustino** [comment]
I think this is happening because nile did consideres that could be running inside a flatpak runtime (which does not exist the flatpak binary, only spawn). Either we find another way of checking some binaries or we handle the exception and try first with flatpak and secondly with flatpak-spawn
