### ISSUE TITLE
Games still tell as playable after uninstall

### ISSUE THREAD

**Issue by Maldevich** [Heroic-Games-Launcher/HeroicGamesLauncher#290]
**Describe the bug**

**To Reproduce**

1. Go to 'heroic games library'
2. Click on 'one of the games that call as playable when it shouldn't'

**Expected behavior**
The game is not call as playable and need to be install again if I want to play it.

**Screenshots**
-

**Desktop (please complete the following information):**

- OS: Garuda Linux
- Version KDE Plasma 5.21.3
- Game: Shadowrun Returns, Shadowrun : Dragonfall, & Shadowrun Hongkong
- Wine/Proton version: 5.13

**Additional context**

**Comment by flavioislima** [comment]
Try refreshing the library.

**Comment by adityaruplaha** [comment]
Should be fixed by my refactor (#294). Can you test and confirm?

**Comment by Maldevich** [comment]
Confirmed. It's clear now. Thanks :D
