### ISSUE TITLE
opt out of playtime tracking 

### ISSUE THREAD

**Issue by MB90it** [Heroic-Games-Launcher/HeroicGamesLauncher#2906]
### Feature description

I know playtime tracking is a heavily requested feature but I would really like a way to disable it. Either within Heroic or some kind of workaround.

Appreciate all the hard work. Thanks!

**Comment by Rathmox** [comment]
GOG should allow it as they say playtime tracking only works through GOG Galaxy so the game cal be launched without being tracked
