### ISSUE TITLE
Flatpak version cannot find installed gamescope

### ISSUE THREAD

**Issue by Shished** [Heroic-Games-Launcher/HeroicGamesLauncher#2911]
### Describe the bug

Gamescope used to work fine but since Flathub maintainers have switched refs from `com.valvesoftware.Steam.Utility.gamescope` to `org.freedesktop.Platform.VulkanLayer.gamescope` the flatpak version of HGL can no longer find and run it.
If the gamescope package is installed from the old ref, it will work fine as before but it should not be used because it is marked end-of-life.

```
Info: (pinned) runtime com.valvesoftware.Steam.Utility.gamescope branch stable is end-of-life, with reason:
   The gamescope Flatpak has been migrated to org.freedesktop.Platform.VulkanLayer.gamescope.
```

### Add logs

```text
[cli] INFO: Logging in...[Core] INFO: Trying to re-use existing login session...[cli] INFO: Checking for updates...[Core] INFO: Getting authentication token...[Core] INFO: Getting ownership token.[cli] INFO: Launching c38f51843fdf4db0b24fc907b8d78221...Traceback (most recent call last):
File "legendary/cli.py", line 3061, in <module>
File "legendary/cli.py", line 2976, in mainFile "legendary/cli.py", line 697, in launch_game
File "subprocess.py", line 951, in __init__
File "subprocess.py", line 1821, in _execute_child
FileNotFoundError: [Errno 2] No such file or directory: 'gamescope'
[735] Failed to execute script 'cli' due to unhandled exception!
```

### Steps to reproduce

1. Click on a game in the library
2. Click on settings button 
3. Scroll down to "Other" section, click to open it
4. Scroll down to "Wrapper command" section
5. Enter "gamescope" into "New Wrapper" field, " -f -h 2160 --" into "Wrapper Arguments" field
6. Close the settings widow, click "Play now" button
7. Wait a little and reopen the HGL window if it got minimized, observe the error log.

### Expected behavior

Game would start without errors inside of the gamescope window.

### Heroic Version

Latest Stable (Flatpak)

### System Information

Arch Linux with all updates installed, Flatpak stuff was also updated. PC rebooted.

**Comment by warderkeeju** [comment]
Yeah -- can duplicate this problem here on my own SteamDeck.

gamescope ran from a stand alone cmd prompt works fine.  not sure if it's hardcoded to grab it from somewhere else and crapping out or what.

**Comment by flavioislima** [comment]
Shoud be fixed already, just update Heroic from Discover. I have updated the manisfest last week with the gamescope path on flatpak
