### ISSUE TITLE
Add Library Top Section selection to show only games that are installed

### ISSUE THREAD

**Issue by hikarutilmitt** [Heroic-Games-Launcher/HeroicGamesLauncher#2914]
### Problem description

Sometimes the game card being full color when it's installed doesn't look much different or just "blends in" with the rest of the cards on some screens. The current dropdown allows for favorites, recently played and recently played but only for installed games. Being able to just see, at a glance what's installed, would be helpful.

### Feature description

Add an option to have the top section only show what is installed.

### Alternatives

A quick filter button to only show what is installed (which may actually be a better option in some cases).

**Comment by hikarutilmitt** [comment]
I have and mentioned why it's not a great solution. This is basically to allow a separated section for just installed gsmes so it's easier to see what you've got installed.

**Comment by arielj** [comment]
We currently have a filter to show only installed games which covers the alternative option in this request, closing this
