### ISSUE TITLE
`EOS Overlay` won't install on Linux in `Flatpak` version `2.9.1` of the `Heroic Games Launcher`

### ISSUE THREAD

**Issue by MeteorKLINT** [Heroic-Games-Launcher/HeroicGamesLauncher#2916]
### Describe the bug

Made a fresh installation of the `Flatpak` version `2.9.1` of `Heroic`. I tried to install the `EOS Overlay`. After I hit the button to install the EOS Overlay, I got the message `The EOS Overlay is being installed...`. The log tells me that the process is aborted close after, but heroic stays in its state forever, and I have to forcefully kill heroic to cancel the not working installation.

### Add logs

```text
(00:46:12) INFO:    [Legendary]:        Running command: XDG_CONFIG_HOME=/home/rieso/.var/app/com.heroicgameslauncher.hgl/config/heroic/legendaryConfig /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary --version
(00:46:12) INFO:    [Legendary]:        Legendary location: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary
(00:46:12) INFO:    [Gog]:              GOGDL location: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl
(00:46:12) INFO:    [Connection]:       Connectivity: check-online
(00:46:12) INFO:    [Connection]:       Pinging external endpoints
(00:46:12) INFO:    [Connection]:       Connectivity: online
(00:46:12) INFO:    [Gog]:              Running command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/rieso/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json --version
(00:46:13) INFO:    [Nile]:             Running command: XDG_CONFIG_HOME=/home/rieso/.var/app/com.heroicgameslauncher.hgl/config/heroic/nile_config /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/nile --version
(00:46:13) INFO:    [Backend]:          

Heroic Version: 2.9.1 Boa Hancock
Legendary Version:  0.20.32 Dark Energy (hotfix #6)
GOGdl Version: 0.7.3
Nile Version: 1.0.0 Jonathan Joestar

Electron Version: 24.4.1
Chrome Version: 112.0.5615.204
NodeJS Version: 18.14.0

OS: Freedesktop SDK KERNEL: 6.2.6-76060206-generic ARCH: x64
CPU: AMD Ryzen 5 3600 6-Core Processor @3.6 GOVERNOR: ondemand
RAM: Total: 31.25 GiB Available: 21.16 GiB
GRAPHICS: GPU0: Navi 10 [Radeon RX 5600 OEM/5600 XT / 5700/5700 XT] VRAM: 512MB 
PROTOCOL: x11

(00:46:13) INFO:    [Backend]:          DRM module staus {
  "oimompecagnajdejgnnjijobebaeigek": {
    "name": "Widevine Content Decryption Module",
    "status": "updated",
    "version": "4.10.2557.0"
  }
}
(00:46:13) INFO:    [Backend]:          User Not Found, removing it from Store
(00:46:13) ERROR:   [Gog]:              Unable to syncQueued playtime, userData not present
(00:46:13) WARNING: [Backend]:          Failed to register protocol with OS.
(00:46:13) INFO:    [Backend]:          AreWeAntiCheatYet data downloaded
(00:46:14) INFO:    [Backend]:          Loading Screen Ready
(00:46:14) INFO:    [Backend]:          Frontend Ready
(00:46:14) INFO:    [Backend]:          Checking for current version changelog
(00:46:14) INFO:    [Frontend]:         Updated to a new version, cleaaning up the cache.
(00:46:14) INFO:    [Legendary]:        Running command: XDG_CONFIG_HOME=/home/rieso/.var/app/com.heroicgameslauncher.hgl/config/heroic/legendaryConfig /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary cleanup
(00:46:14) INFO:    [Frontend]:         Refreshing undefined Library
(00:46:14) WARNING: [Backend]:          refresh not implemented on Sideload Library Manager
(00:46:14) INFO:    [Legendary]:        Refreshing library...
(00:46:16) INFO:    [Winetricks]:       Downloading Winetricks
(00:46:16) INFO:    [DXVKInstaller]:    Updating dxvk to: dxvk-2.2
(00:46:16) INFO:    [DXVKInstaller]:    Updating vkd3d to: vkd3d-proton-2.9
(00:46:16) INFO:    [DXVKInstaller]:    downloaded vkd3d
(00:46:16) INFO:    [DXVKInstaller]:    extracting vkd3d
(00:46:17) INFO:    [DXVKInstaller]:    vkd3d updated!
(00:46:17) INFO:    [DXVKInstaller]:    downloaded dxvk
(00:46:17) INFO:    [DXVKInstaller]:    extracting dxvk
(00:46:17) INFO:    [DXVKInstaller]:    dxvk updated!
(00:46:19) INFO:    [Backend]:          Starting the Download Queue
(00:46:43) INFO:    [Legendary]:        Logging in: XDG_CONFIG_HOME=/home/rieso/.var/app/com.heroicgameslauncher.hgl/config/heroic/legendaryConfig /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary auth --code <redacted>
(00:46:44) INFO:    [Frontend]:         Refreshing legendary Library
(00:46:44) INFO:    [Legendary]:        Refreshing library...
(00:46:44) INFO:    [Legendary]:        Refreshing Epic Games...
(00:46:44) INFO:    [Legendary]:        Game list updated, got 0 games & DLCs
(00:46:44) INFO:    [Frontend]:         No cache found, getting data from legendary...
(00:46:44) INFO:    [Legendary]:        Refreshing library...
(00:46:44) INFO:    [Legendary]:        Refreshing Epic Games...
(00:46:44) INFO:    [Legendary]:        Game list updated, got 0 games & DLCs
(00:46:44) INFO:    [Legendary]:        Running command: XDG_CONFIG_HOME=/home/rieso/.var/app/com.heroicgameslauncher.hgl/config/heroic/legendaryConfig /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary list --third-party
(00:46:44) INFO:    [Legendary]:        Running command: XDG_CONFIG_HOME=/home/rieso/.var/app/com.heroicgameslauncher.hgl/config/heroic/legendaryConfig /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary list --third-party
(00:46:48) INFO:    [Legendary]:        Running command: XDG_CONFIG_HOME=/home/rieso/.var/app/com.heroicgameslauncher.hgl/config/heroic/legendaryConfig /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary --version
(00:46:48) INFO:    [Gog]:              Running command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/rieso/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json --version
(00:46:48) INFO:    [Nile]:             Running command: XDG_CONFIG_HOME=/home/rieso/.var/app/com.heroicgameslauncher.hgl/config/heroic/nile_config /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/nile --version
(00:46:50) INFO:    [Legendary]:        Getting EOS Overlay install size: XDG_CONFIG_HOME=/home/rieso/.var/app/com.heroicgameslauncher.hgl/config/heroic/legendaryConfig /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary eos-overlay install --path /home/rieso/.var/app/com.heroicgameslauncher.hgl/config/heroic/tools/eos_overlay
(00:46:50) INFO:    [Backend]:          Preventing machine to sleep
(00:46:51) INFO:    [Legendary]:        Abort command "XDG_CONFIG_HOME=/home/rieso/.var/app/com.heroicgameslauncher.hgl/config/heroic/legendaryConfig /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary eos-overlay install --path /home/rieso/.var/app/com.heroicgameslauncher.hgl/config/heroic/tools/eos_overlay"
(00:48:30) ERROR:   [Backend]:          Aborting not possible. Could not find a matching abort controller for 98bc04bc842e4906993fd6d6644ffb8d
```

### Steps to reproduce

1. Go to `Settings`
2. Click on `Advance`
3. Scroll down to `EOS Overlay`
4. Click on `Install`
5. Wait, as long as I want
6. Click on `Cancel`
7. Cannot be canceled.

### Expected behavior

`EOS Overlay` should be installed, or the process should be at least abortable.

### Heroic Version

Latest Stable (Flatpak)

### System Information

- Pop!_OS 22.04 LTS x86_64 
- Kernel: 6.2.6-76060206-generic 
- CPU: AMD Ryzen 5 3600 (12) @ 3.600GHz 
- GPU: AMD ATI Radeon RX 5600 OEM/5600 XT / 5700/5700 XT 
- Memory: 31998MiB 

### Additional information

Seems to be related to https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/issues/2905

**Comment by arielj** [comment]
I pushed a fix for this, until it's released you can workaround this issue by running this in a terminal `XDG_CONFIG_HOME=/home/rieso/.var/app/com.heroicgameslauncher.hgl/config/heroic/legendaryConfig /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary eos-overlay install --path /home/rieso/.var/app/com.heroicgameslauncher.hgl/config/heroic/tools/eos_overlay` (from your log there), then restart heroic and it should work

**Comment by MeteorKLINT** [comment]
Thank you, @arielj, for the pushing and the idea how to work around this issue. 

First, I got this message from my terminal: 
```zsh
zsh: no such file or directory: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary
```
I suggest, the response is related to the flatpak environment, so I tried this.
```zsh
$ flatpak run --command=bash com.heroicgameslauncher.hgl
$ XDG_CONFIG_HOME=/home/rieso/.var/app/com.heroicgameslauncher.hgl/config/heroic/legendaryConfig /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary eos-overlay install --path /home/rieso/.var/app/com.heroicgameslauncher.hgl/config/heroic/tools/eos_overlay
```
After restarting `Heroic`, the `EOS Overlay` seems to be installed.
![image](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/assets/75277768/fa6d55f5-9c29-4bc4-ae77-92d28292dfc4)

**Comment by Roccoriu** [comment]
This does not work for me. I ran the command in the flatpak environment as outlined by @MeteorKLINT.
I double checked if it's installed through the cli and it tells me that it's installed. 

this is the output when I run it again. 
[📦 com.heroicgameslauncher.hgl ~]$ XDG_CONFIG_HOME=/home/rieso/.var/app/com.heroicgameslauncher.hgl/config/heroic/legendaryConfig /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary eos-overlay install --path /home/rieso/.var/app/com.heroicgameslauncher.hgl/config/heroic/tools/eos_overlay
[cli] INFO: Preparing to start overlay install...
[Core] WARNING: Unable to download manifest from "download.epicgames.com" (status: 403), trying next URL...
[Core] WARNING: Unable to download manifest from "download2.epicgames.com" (status: 403), trying next URL...
[Core] WARNING: Unable to download manifest from "download3.epicgames.com" (status: 403), trying next URL...
[Core] WARNING: Unable to download manifest from "download4.epicgames.com" (status: 403), trying next URL...
[cli] INFO: Installed version is up to date, nothing to do.

Yet even after rebooting my pc it still does not show up as installed in the ui. 
![Screenshot from 2023-07-30 16-42-33](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/assets/25778176/454a6bfc-67ed-4ba2-a7a1-e86ae1493c21)

**Comment by arielj** [comment]
can you share heroic's logs when you click that Install button from the UI? maybe the path is different?

**Comment by MeteorKLINT** [comment]
@Roccoriu the command 
```bash
$ XDG_CONFIG_HOME=/home/rieso/.var/app/com.heroicgameslauncher.hgl/config/heroic/legendaryConfig /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary eos-overlay install --path /home/rieso/.var/app/com.heroicgameslauncher.hgl/config/heroic/tools/eos_overlay
```
contains my user `rieso` you should replace it with your username. I will edit the workaround to make this work regarding any username.

**Comment by gaberilde** [comment]
> 

$USER should do it  if you replace your username you can also replace /home and the username to just ~ this points to your home folder no matter what

**Comment by gaberilde** [comment]
`$ XDG_CONFIG_HOME=~/.var/app/com.heroicgameslauncher.hgl/config/heroic/legendaryConfig /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary eos-overlay install --path ~/.var/app/com.heroicgameslauncher.hgl/config/heroic/tools/eos_overlay`

this should hopefully work

**Comment by ThomasHineXYZ** [comment]
What would the adapted fix be for this on Windows? I'm experiencing this same issue on Windows 10.

**Comment by arielj** [comment]
> What would the adapted fix be for this on Windows? I'm experiencing this same issue on Windows 10.

check my answer in the windows issue https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/issues/2905

**Comment by kereko** [comment]
Thanks @MeteorKLINT it worked perfectly on SteamDeck using Windows 11

**Comment by ileeds** [comment]
When I follow these instructions, upon reopening Heroic Games Launcher and selecting a game (apologies for typos, I can't copy/paste):

An error has occurred! Try to Logout and Login on your Epic account.
[cli] INFO: Using prefix "/home/deck/Games/Heroic/Prefixes/default/Fall Guys"
[cli] INFO: Installed version: 1.2.7...
[cli] INFO: Installed path: /home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/tools/eos_overlay
Traceback (most recent call last):
...
ValueError: No user.reg file, invalid path
...

Any ideas?

**Comment by MeteorKLINT** [comment]
Hey @ileeds, it appears that you started _Fall Guys_. Is that true? Did you try different games?

**Comment by ileeds** [comment]
Hey @MeteorKLINT, thanks for the reply. That's correct. And sorry for the confusion, it seems this error was due to my use of the `legendary eos-overlay` command as I was trying to debug the original issue, which is what I'm back to now after a fresh install.

I'm seeing this same behavior for multiple games. When I click "Enable EOS Overlay" it seems to succeed (the prompt changes to "Disable EOS Overlay") but if I leave the game page and come back, it's always back to "Enable EOS Overlay".

**Comment by Corben78** [comment]
Just hit this issue as well, as it hasn't been release yet, as copy-paste solution for debian package users:
`XDG_CONFIG_HOME=$HOME/.config/heroic/legendaryConfig /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary eos-overlay install --path $HOME/.config/heroic/tools/eos_overlay`

**Comment by Etuldan** [comment]
I have a similar issue on Windows 10 OS.
The workaround above is inapplicable on a such OS.

Here is the errorlog

```
Une erreur est survenue ! Essayez de vous déconnecter et de vous reconnecter à votre compte Epic.
Do you want to install the overlay? [Y/n]:[cli] INFO: Preparing to start overlay install...[Core] WARNING: Unable to download manifest from "download.epicgames.com" (status: 403), trying next URL...[Core] WARNING: Unable to download manifest from "download2.epicgames.com" (status: 403), trying next URL...[Core] WARNING: Unable to download manifest from "download3.epicgames.com" (status: 403), trying next URL...[Core] WARNING: Unable to download manifest from "download4.epicgames.com" (status: 403), trying next URL...[cli] INFO: Install directory: C:\Users\Etuldan\AppData\Roaming\heroic\tools\eos_overlay
[cli] INFO: Install size: 330.82 MiB
[cli] INFO: Download size: 141.52 MiB
Traceback (most recent call last):
File "legendary\cli.py", line 3069, in <module>
File "legendary\cli.py", line 3018, in main
File "legendary\cli.py", line 2268, in manage_eos_overlay
File "legendary\utils\cli.py", line 4, in get_boolean_choice
EOFError: EOF when reading a line
[19304] Failed to execute script 'cli' due to unhandled exception!
```

Heroic : 2.9.1
Legendary : 0.20.32 Dark Energy (hotfix #6)
GOGDL : 0.7.3
Nile : 1.0.0 Jonathan Joestar
HTTPS enabled (checkbox is unchecked)

**Comment by ThomasHineXYZ** [comment]
@Etuldan there is a [separate issue](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/issues/2905) for this on Windows. 

Looks like [it is set to be fixed in the next update](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/pull/2930).
