### ISSUE TITLE
Amazon games don't launch on macOS

### ISSUE THREAD

**Issue by nonoche2** [Heroic-Games-Launcher/HeroicGamesLauncher#2921]
### Describe the bug

Amazon Games install but do not launch with Heroic (log error says "WARNING: [Backend] could not determine system info" (tried with a dozen titles)
Launching amazon games installed with Heroic from Crossover works fine.

### Add logs

```text
WARNING: [Backend] could not determine system info
```

### Steps to reproduce

1. install an Amazon game
2. attempt to launch the game

### Expected behavior

the games should launch

### Heroic Version

Latest Stable

### System Information

- macOS Ventura 13.4.1
- MacBook Air M1, 16 GB RAM

**Comment by nonoche2** [comment]
update: Just realized I have exactly the same issue with GOG games. Epic games launch fine.

**Comment by Etaash-mathamsetty** [comment]
which version of heroic?

**Comment by nonoche2** [comment]
issue is still here with 2.9.2

**Comment by nonoche2** [comment]
I am not getting the "WARNING: [Backend] could not determine system info" error in the log anymore though, the games just fail silently (button goes from "game running (stop)" back to "play now")

**Comment by Alex0007** [comment]
I can confirm this bug as well. And i can confirm solution: https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/issues/3118#issuecomment-1752389371

**Comment by arielj** [comment]
@Alex0007 I understand that Heroic 2.12.0 works fine then from your comment, right?

I want to close this issue if that's the case

**Comment by Alex0007** [comment]
@arielj 
Yes, correct! Can be closed
