### ISSUE TITLE
Epic Store Integration

### ISSUE THREAD

**Issue by siltentassasin** [Heroic-Games-Launcher/HeroicGamesLauncher#293]
Is it possible to make the epic store not in an extern window? I think it would be very nice, if its direct in the launcher :)

**Comment by flavioislima** [comment]
> 
> 
> Is it possible to make the epic store not in an extern window? I think it would be very nice, if its direct in the launcher :)

I tried to do it once and have some issues. I don't know if we will be implementing this anytime soon.
