### ISSUE TITLE
 Issues with Launching and Uninstalling Epic Games Game on Windows

### ISSUE THREAD

**Issue by The-Ducktor** [Heroic-Games-Launcher/HeroicGamesLauncher#2936]
### Describe the bug

When attempting to launch an Epic Games game on Windows, users encounter an error. This error does not occur on macOS, where the game runs smoothly. Additionally, when trying to uninstall the game on Windows, the same error appears, while the installation process is error-free. Moreover, logging in and out does not trigger any action or result in expected behavior.

### Add logs

```text
An error has occurred! Try to Logout and Login on your Epic account.
[Core] INFO: Synced app "7179f095efcc4f92a950a6d9dbd9c602" is no longer in the EGL manifest list.[Core] INFO: Game files exist, assuming game is still installed, re-exporting to EGL...Traceback (most recent call last):
File "legendary\cli.py", line 3069, in <module>File "legendary\cli.py", line 2984, in main
File "legendary\cli.py", line 578, in launch_game
File "legendary\core.py", line 566, in get_installed_game
File "legendary\core.py", line 1861, in egl_sync
File "legendary\core.py", line 1847, in egl_restore_or_uninstall
File "legendary\core.py", line 1824, in egl_exportFile "legendary\lfs\egl.py", line 85, in set_manifest
ValueError: EGS ProgramData path does not exist
[13764] Failed to execute script 'cli' due to unhandled exception!
```

### Steps to reproduce

1. Launch the Epic Games game on a Windows PC.
2. Observe the error preventing the game from starting.
3. Attempt to uninstall the game from the Windows PC.
4. Observe the same error appearing during the uninstallation process.
5. Log in and out of the Epic Games account.
6. Notice that nothing happens, and there is no expected behavior upon login or logout.

### Expected behavior

1. The game should launch successfully on Windows, just like it does on macOS.
2. Uninstalling the game on Windows should not trigger any errors and should be completed without issues.
3. Logging in and out of the Epic Games account should result in appropriate actions, such as account status changes, synchronization, or displaying user-related information.

### Heroic Version

Latest Stable

### System Information

1. Windows version: 11 64-bit
2. macOS version: Sonoma Developer Beta 4
3. Epic Games game title: Severed Steel and Genshin Impact launcher
4. Game version: Latest

- Hardware specifications: 
    - CPU: Ryzen 5 3500
    - Ram 16GB
    - AMD Radeon RX 5700

**Comment by arielj** [comment]
Did you have the Epic Games Launcher installed and the uninstalled it?

**Comment by arielj** [comment]
you can run `c:\path\to\\legendary.exe egl-sync --disable-sync` and should fix this

you can get the path to legendary checking heroic's general logs, at the beginning

**Comment by An-Eagle** [comment]
I've also had this bug on Linux, with the heroic flatpak

**Comment by arielj** [comment]
Closing this since the `ValueError: EGS ProgramData path does not exist` is fixed by disabling the egl-sync.

I added this other feature request to detect the error and automatically disable that legendary feature https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/issues/2985
