### ISSUE TITLE
Can't see Amazon Games games

### ISSUE THREAD

**Issue by Zanomi** [Heroic-Games-Launcher/HeroicGamesLauncher#2947]
### Describe the bug

After logging in to the Amazon games store they do not appear even after logging out and in.

### Add logs

```text
.
```

### Steps to reproduce

1. Log into Amazon games store
2. Click on library

### Expected behavior

See games

### Heroic Version

Latest Stable

### System Information

Steam deck

**Comment by Henry-Hiles** [comment]
> ### Describe the bug
> After logging in to the Amazon games store they do not appear even after logging out and in.
> 
> ### Add logs
> ```
> .
> ```
> 
> ### Steps to reproduce
> 1. Log into Amazon games store
> 2. Click on library
> 3. See error
> 
> ### Expected behavior
> See games
> 
> ### Screenshots
> _No response_
> 
> ### Heroic Version
> Latest Stable
> 
> ### System Information
> Steam deck
> 
> ### Additional information
> _No response_

If you want support, logs are needed. Open a new issue with the correct information.
