### ISSUE TITLE
be able to install packages or dll to be able to run some games as in lutris, and its script

### ISSUE THREAD

**Issue by tridoxx** [Heroic-Games-Launcher/HeroicGamesLauncher#295]
I am trying to run a game "batman arkham city", but it cannot be executed because it does not detect the dotnet (.net), in the wine profile in the game, a section should be created, where the user can preconfigure the requirements of this game and pre-install them in the game's wine profile. an example as I mentioned before is to use a script pre-installer like lutris uses. 
since each game has different requirements.  
lutris example  from a another game:
![image](https://user-images.githubusercontent.com/22879539/114226857-ce676400-9939-11eb-94ab-e03bc4b9d5f9.png)
the error: but I can't install the .net since it doesn't allow it to run directly, but with winetricks it could be added to the game's wine room
![imagen_2021-04-09_134340](https://user-images.githubusercontent.com/22879539/114226743-97914e00-9939-11eb-88c3-4e73615706f8.png)

**Comment by flavioislima** [comment]
Answered on Discord server:
_You can use the run exe on the wine settings to install the files that comes with the instalation, normally at a redist folder. Or you can click on winetricks and install those dependencies. But it is not on our plan to implement this feature that lutris has, not sooner, maybe never. Sounds really complex logic to do that kind of integration._
