### ISSUE TITLE
Steam Deck cannot open the downloading game from Epic

### ISSUE THREAD

**Issue by zhangjack7502** [Heroic-Games-Launcher/HeroicGamesLauncher#2952]
### Describe the bug

When i use the Heroic Game Launch to download and install Epic‘s games， i find that i can't open these game on steam deck. This is the atmosphere：
Steam Deck（Steam OS/Linux），Proton GE 8，WD SN740 2TB

Issue Detail：Use Heroic Download the game-Add games to the steam-use steam os（desktop mode & game mode）to run
these game- running about just 5-8s-the game will be closed

Which process i have the mistake or issue，Could you help me to solve that problem？ Thanks for your supporting.

### Add logs

```text
Null， No Logs
```

### Steps to reproduce

2. Click on '...'
3. Scroll down to '...'

### Expected behavior

Null

### Screenshots

Null

### Heroic Version

Latest Stable

### System Information

- Steam OS
- The Lastest Version

### Additional information

I am Chinese player, so my English perhaps is not very good. If you have some question about that, you can use the trans application to communicate with me on Chinese.

**Comment by arielj** [comment]
Please open a thread in the `#support` channel in our discord, this kind of issue fits better there
