### ISSUE TITLE
Error code while launching Epic games on Steam deck

### ISSUE THREAD

**Issue by ioneng** [Heroic-Games-Launcher/HeroicGamesLauncher#2957]
### Describe the bug

Epic games don't launch any more . Error dialog comes up every time. Gog games are not affected.

### Add logs

```text
[cli] INFO: Logging in...[Core] INFO: Trying to re-use existing login session...[cli] INFO: Getting game list... (this may take a while)Traceback (most recent call last):
File "legendary/cli.py", line 3061, in <module>
File "legendary/cli.py", line 2972, in main
File "legendary/cli.py", line 239, in list_games
UnicodeEncodeError: 'ascii' codec can't encode character '\xae' in position 13: ordinal not in range(128)
[232]Failed to execute script 'cli' due to unhandled exception!
```

### Steps to reproduce

try to launch any epic game.
game not lauching
See error

### Expected behavior

games runs normally.

### Heroic Version

Latest Stable (Flatpak)

### System Information

- OS [e. g. "Ubuntu"]:SteamOS 3.5

### Additional information
log:
(13:38:05) INFO:    [Legendary]:        Running command: XDG_CONFIG_HOME=/home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/legendaryConfig /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary --version
(13:38:05) INFO:    [Legendary]:        Legendary location: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary
(13:38:05) INFO:    [Gog]:              GOGDL location: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl
(13:38:05) INFO:    [Connection]:       Connectivity: check-online
(13:38:05) INFO:    [Connection]:       Pinging external endpoints
(13:38:05) INFO:    [Nile]:             Refreshing library...
(13:38:05) INFO:    [Nile]:             Refreshing Amazon Games...
(13:38:05) INFO:    [Nile]:             Running command: XDG_CONFIG_HOME=/home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/nile_config /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/nile library sync
(13:38:05) INFO:    [Nile]:             Game list updated, got 135 games
(13:38:05) INFO:    [Backend]:          DRM module staus {
  "oimompecagnajdejgnnjijobebaeigek": {
    "name": "Widevine Content Decryption Module",
    "status": "new",
    "version": "4.10.2557.0"
  }
}
(13:38:05) WARNING: [Backend]:          Failed to register protocol with OS.
(13:38:05) INFO:    [Connection]:       Connectivity: online
(13:38:05) INFO:    [Gog]:              Checking if login is valid
(13:38:05) INFO:    [Gog]:              Running command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth
(13:38:05) INFO:    [Gog]:              Running command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json --version
(13:38:05) INFO:    [Backend]:          AreWeAntiCheatYet data downloaded
(13:38:06) INFO:    [Nile]:             Running command: XDG_CONFIG_HOME=/home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/nile_config /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/nile --version
(13:38:06) INFO:    [Backend]:          Loading Screen Ready
(13:38:06) INFO:    [Nile]:             Saved user data to config file
(13:38:06) INFO:    [Frontend]:         Refreshing undefined Library
(13:38:06) WARNING: [Backend]:          refresh not implemented on Sideload Library Manager
(13:38:06) INFO:    [Gog]:              Running command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth
(13:38:06) INFO:    [Legendary]:        Refreshing library...
(13:38:06) INFO:    [Legendary]:        Refreshing Epic Games...
(13:38:06) INFO:    [Nile]:             Refreshing library...
(13:38:06) INFO:    [Nile]:             Refreshing Amazon Games...
(13:38:06) INFO:    [Nile]:             Running command: XDG_CONFIG_HOME=/home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/nile_config /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/nile library sync
(13:38:06) INFO:    [Nile]:             Game list updated, got 135 games
(13:38:06) INFO:    [Legendary]:        Game list updated, got 136 games & DLCs
(13:38:06) INFO:    [Backend]:          Frontend Ready
(13:38:06) INFO:    [Gog]:              Saved username to config file
(13:38:06) INFO:    [Backend]:          Checking for current version changelog
(13:38:06) INFO:    [Gog]:              Getting GOG library
(13:38:06) INFO:    [Gog]:              Running command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth
(13:38:06) INFO:    [Backend]:          

Heroic Version: 2.9.1 Boa Hancock
Legendary Version:  0.20.32 Dark Energy (hotfix #6)
GOGdl Version: 0.7.3
Nile Version: 1.0.0 Jonathan Joestar

Electron Version: 24.4.1
Chrome Version: 112.0.5615.204
NodeJS Version: 18.14.0

OS: Freedesktop SDK KERNEL: 6.1.29-valve8-2-neptune-61 ARCH: x64
CPU: AMD Custom APU 0405 @3.09 GOVERNOR: schedutil
RAM: Total: 11.52 GiB Available: 7.33 GiB
GRAPHICS: GPU0: VanGogh [AMD Custom GPU 0405] VRAM: 512MB 
PROTOCOL: x11

(13:38:07) INFO:    [Legendary]:        Running command: XDG_CONFIG_HOME=/home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/legendaryConfig /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary list --third-party
(13:38:08) INFO:    [Winetricks]:       Downloading Winetricks
(13:38:08) WARNING: [Backend]:          No clientId in goggame-2.info file. Cannot resolve save path
(13:38:08) INFO:    [Gog]:              Saved games data
(13:38:09) WARNING: [Backend]:          listUpdateableGames not implemented on Sideload Library Manager
(13:38:11) INFO:    [Backend]:          Starting the Download Queue
(13:38:18) INFO:    [Gog]:              Found 2 game(s) to update
(13:38:19) INFO:    [Legendary]:        Checking for game updates: XDG_CONFIG_HOME=/home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/legendaryConfig /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary list --third-party
(13:38:22) DEBUG:   [Legendary]:        Update is available for a1e2ce30defe4a9187ebc14fc9d2bd8b: KSP.1.12.5.en-us != KSP.1.12.5.win64.full
(13:38:22) DEBUG:   [Legendary]:        Update is available for bc2c95c6ff564a16b26644f1d3ac3c55: 1.0.0_BN-180_CL-17677 != 1.0.0_BN-187_CL-17677
(13:38:22) INFO:    [Legendary]:        Found 2 games to update
(13:38:22) INFO:    [Nile]:             Looking for updates...
(13:38:22) INFO:    [Nile]:             Running command: XDG_CONFIG_HOME=/home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/nile_config /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/nile list-updates --json
(13:47:34) INFO:    [Backend]:          Launching Haven Park (1906330252)
(13:47:34) INFO:    [Backend]:          Preventing display from sleep
(13:47:34) INFO:    [Backend]:          Preventing machine to sleep
(13:47:35) INFO:    [Backend]:          Stopping Power Saver Blocker
(13:47:35) INFO:    [Gog]:              Launching Haven Park: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json launch "/home/deck/Games/Heroic/Haven Park" 1906330252 --wrapper /app/bin/gamemoderun --platform linux
(13:47:49) INFO:    [Backend]:          Stopping Display Power Saver Blocker
(13:47:49) INFO:    [Frontend]:         Refreshing gog Library
(13:47:49) INFO:    [Gog]:              Running command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth
(13:47:50) INFO:    [Gog]:              Getting GOG library
(13:47:50) INFO:    [Gog]:              Running command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth
(13:47:51) WARNING: [Backend]:          No clientId in goggame-2.info file. Cannot resolve save path
(13:47:52) INFO:    [Gog]:              Saved games data

_No response_

**Comment by arielj** [comment]
Is this still an issue with Heroic 2.11.0?

**Comment by arielj** [comment]
closing since there's been no answer in over a month, if this still happens it can be reopened
