### ISSUE TITLE
Feature Request to Add Collections

### ISSUE THREAD

**Issue by Nicholas705M** [Heroic-Games-Launcher/HeroicGamesLauncher#2967]
### Feature description

Feature request to add collections, like in Steam. One game can be in multiple collections and some collections can auto update based off of platform, installed or not, etc.

**Comment by arielj** [comment]
There's a PR in progress for this https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/pull/3115

Not the autoupdate part, but adding custom categories and filtering

**Comment by arielj** [comment]
Closing this since we have custom categories support and filtering by categories now.
