### ISSUE TITLE
Heroic Games Launcher GUI problem

### ISSUE THREAD

**Issue by Brennock** [Heroic-Games-Launcher/HeroicGamesLauncher#299]
**Describe the bug**
Heroic Games Launcher graphical interface will not show up.

**To Reproduce**
(I'm describing what happens in my case)
1. Open heroic games launcher
2. Note absent GUI
3. Open xfce-task-manager
4. See the process running with no problems

**Expected behavior**
Clicking on the program will prompt it to open and display my library

**Screenshots**
https://imgur.com/a/yGXGJpQ

**Desktop (please complete the following information):**

- OS: Manjaro Arch Linux

**Additional context**
It has happened before, i reformated the computer and it worked again. A few weeks back i noticed the launcher had stopped getting updated by the package manager even tough the AUR was up to date, but the problem showed up when i did a full system update.

**Comment by flavioislima** [comment]
Try removing `.config/heroic` folder. If this doesn't work. Try removing the`.config/legendary` folder as well.
Probably some config file got corrupted for some reason.

**Comment by Brennock** [comment]
Damn, it worked like a charm! Thanks!
