### ISSUE TITLE
Cloud synchronization reports an error

### ISSUE THREAD

**Issue by QingXuan2000** [Heroic-Games-Launcher/HeroicGamesLauncher#3000]
### Describe the bug

When the game is synced in the cloud the bug ：

[Core] INFO: Trying to re-use existing login session...

[cli] INFO: Got 1 remote save game(s)

[cli] INFO: Checking "Death Stranding" (Boga)

[cli] INFO: Overriding save path with "/home/fircug/Games/Heroic/Prefixes/default/Death Stranding/pfx/drive_c/users/steamuser/AppData/LocalLow/KojimaProductions/DeathStranding/cb27fcec8d0345b9893ec940c1f60c1a"...

[cli] INFO: Save game for "Death Stranding" is up to date, skipping...

Legendary update available!

- New version: 0.20.33 - "Undue Alarm"

- Release summary:

 [*] Improved handling of SDL changes

 [*] Added safeguards to prevent two simultaneous instances from corrupting the database

 [*] Added support for running uninstallers

 [*] More gracefully handles account errors

See full changelog for additional details.

- Release URL: https://legendary.gl/release/0.20.33

- Download URL: https://legendary.gl/release/download/0.20.33/legendary

### Add logs

```text
[Core] INFO: Trying to re-use existing login session...

[cli] INFO: Got 1 remote save game(s)

[cli] INFO: Checking "Death Stranding" (Boga)

[cli] INFO: Overriding save path with "/home/fircug/Games/Heroic/Prefixes/default/Death Stranding/pfx/drive_c/users/steamuser/AppData/LocalLow/KojimaProductions/DeathStranding/cb27fcec8d0345b9893ec940c1f60c1a"...

[cli] INFO: Save game for "Death Stranding" is up to date, skipping...

Legendary update available!

- New version: 0.20.33 - "Undue Alarm"

- Release summary:

 [*] Improved handling of SDL changes

 [*] Added safeguards to prevent two simultaneous instances from corrupting the database

 [*] Added support for running uninstallers

 [*] More gracefully handles account errors

See full changelog for additional details.

- Release URL: https://legendary.gl/release/0.20.33

- Download URL: https://legendary.gl/release/download/0.20.33/legendary
```

### Steps to reproduce

When the game is synced in the cloud

### Expected behavior

OS: Manjaro Linux
CPU: Intel® Xeon® E5-2680 0 × 16
RAM: 16.0 GiB
GPU: AMD Radeon™ RX 580 Series

### Screenshots

![截图 2023-08-20 22-24-58](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/assets/140320507/6ba0cd2b-e0d3-4249-81d5-a79e0cd54772)

### Heroic Version

Latest Stable

### System Information

OS: Manjaro Linux
CPU: Intel® Xeon® E5-2680 0 × 16
RAM: 16.0 GiB
GPU: AMD Radeon™ RX 580 Series

**Comment by arielj** [comment]
I don't see an error, I see logs with information, but not an error

it even says that the saves are up to date

**Comment by CaptainFrosty** [comment]
> I don't see an error, I see logs with information, but not an error
> 
> it even says that the saves are up to date

May not be the same bug but mine [#3003](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/issues/3003) is failing to transfer most of the data despite reporting successful. First version this has happened.
