### ISSUE TITLE
Is it possible to seperate the game process and launcher process?

### ISSUE THREAD

**Issue by ghost** [Heroic-Games-Launcher/HeroicGamesLauncher#3005]
### Problem description

when I want to alt+tab into my game window, it looks the same as heroic launcher
usually tabbing into it just puts focus on the launcher window and not the game window

### Feature description

seperate the process, maybe use a different icon for the game window or it's intended game icon (to immediately distinguish it from the launcher)
is doing that possible?

### Alternatives

of course, i can just rebind my alt+tab to instead browse through individual windows instead of apps/window groups but that seems inconvenient

### Additional information

to me, the desired behavior of game window being seperate from the window group of HGL seems the most obvious one and one the end user would expect

**Comment by arielj** [comment]
If this is a gnome think, should we close this issue?

**Comment by arielj** [comment]
Closing since it's a gnome issue and we can't really fix that.
