### ISSUE TITLE
All file picker dialogs are not working in flatpak

### ISSUE THREAD

**Issue by RikudouSage** [Heroic-Games-Launcher/HeroicGamesLauncher#3023]
### Describe the bug

Whenever I click any action that should open a file picker, nothing happens.

That includes:

- folder icon in "Select Executable"
- button "Run installer first"
- folder icon in "Select an alternative EXE to run"
- button "Run exe on prefix"

The folder icons have a workaround of manually inputting the path, but the buttons have no workaround and I cannot do any of that

### Add logs

```text
There are no relevant logs.
```

### Steps to reproduce

Click any of the buttons mentioned. Though on my previous system this didn't happen, so I don't know the exact steps to reproduce.

### Expected behavior

The buttons work

### Heroic Version

Latest Stable (Flatpak)

### System Information

- OS: NixOS

**Comment by RikudouSage** [comment]
I found this when running the flatpak from command line:

`Can't open portal file chooser: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such interface “org.freedesktop.portal.FileChooser” on object at path /org/freedesktop/portal/desktop`

**Comment by imLinguin** [comment]
Do you have any flatpak xdg portal installed?

**Comment by imLinguin** [comment]
I'm not that familiar with NixOS, in distros like Arch it is usually a packages `xdg-desktop-portal` and `xdg-desktop-portal-gnome` or `xdg-desktop-portal-kde`

**Comment by RikudouSage** [comment]
Just found out as well, will let you know how it goes.

**Comment by RikudouSage** [comment]
Solved it! Had to add this to the `configuration.nix` file:

```nix
  xdg.portal.extraPortals = [
    pkgs.xdg-desktop-portal-gtk
  ];
```
