### ISSUE TITLE
Downloading games on separate hard drive does not work

### ISSUE THREAD

**Issue by Noxellar** [Heroic-Games-Launcher/HeroicGamesLauncher#304]
**Describe the bug**
When trying to install games on a separate hard drive (but I would assume the same thing would happen in another partition as well), Heroic Games will give me a notification that it has finished importing the game instead of downloading/installing it. Installing in my home directory will start a proper download (with the notification corresponding to "downloading") and symbolic links work too (technically I only tried with symlinks but should be same result without). Looking on the second hard drive, I can see that two different games, one downloading through the symlink I made and one directly selecting the installation path, only one is installed.

**To Reproduce**

1. Install a game like you normally would
2. When met with the "select installation path" dialogue box, select a folder on a different hard drive
3. Start download
4. A notification will pop up and say that the game has imported successfully instead of showing the percentage finished downloading

**Expected behavior**
That the game started to download, making a new folder for itself in the second hard drive.

**Desktop (please complete the following information):**

- OS: Linux Mint Mate
- Version 20.1
- Game: Tried to install Night in the Woods and Oddworld: New 'n' Tasty
- Wine/Proton version: N/A

**Comment by flavioislima** [comment]
Run from terminal and check the launch command. Maybe its something with the name of the folder.

**Comment by Noxellar** [comment]
I get these messages when I try to download these games:

```
Installing 7c566548d24343e48151125ced4b494c with: /tmp/.mount_heroicQCjADM/resources/app.asar.unpacked/build/bin/legendary install 7c566548d24343e48151125ced4b494c --base-path '/media/user/secondHDD/My Folder/Game Files/Heroic Games/Game Files'  -y &> /home/user/.config/heroic/GamesConfig/7c566548d24343e48151125ced4b494c.log
operation interrupted
-------------------- I tried to download again here --------------------
Progress: 7c566548d24343e48151125ced4b494c /MiB/undefined
Progress: 7c566548d24343e48151125ced4b494c /MiB/undefined
Installing 7c566548d24343e48151125ced4b494c with: /tmp/.mount_heroicQCjADM/resources/app.asar.unpacked/build/bin/legendary install 7c566548d24343e48151125ced4b494c --base-path '/media/user/secondHDD/My Folder/Game Files/Heroic Games/Game Files'  -y &> /home/user/.config/heroic/GamesConfig/7c566548d24343e48151125ced4b494c.log
operation interrupted
Progress: 7c566548d24343e48151125ced4b494c /MiB/undefined
Progress: 7c566548d24343e48151125ced4b494c /MiB/undefined
```

I also installed the Legendary CLI tool and tried to use the same command (without the last bit that makes a log file) and it worked, so it probably isn't an upstream error.

Judging from the error message, it could possibly be related to issue #195. I forgot to mention that when it shows the notification that the game has "finished importing" that Heroic Games reloads my library. I think this where the "operation interrupted" message comes from.


The thing I find most funny is the fact that symlinks to the hard drive works. Maybe the problem has something to do with the "Sync with Installed Epic Games" feature as well? This is just a very vague idea, I have no idea what this actually does but I assume this is to access game files in a Windows partition. Sorry if I'm wrong.

**Comment by kajlando** [comment]
Create a symlink to an external drive and problem solved!

**Comment by flavioislima** [comment]
@Noxellar can you try on the latest version? I tried to replicate the issue but I could install games on a second HDD and also on a second SSD without issues.

**Comment by Izz21** [comment]
I'm facing this same issue but instead of completing the download. It freezes in the process.

**Comment by flavioislima** [comment]
> I'm facing this same issue but instead of completing the download. It freezes in the process.

Send the logs for when you launch heroic from terminal.

**Comment by Izz21** [comment]
> > I'm facing this same issue but instead of completing the download. It freezes in the process.
> 
> Send the logs for when you launch heroic from terminal.

What is the command to launch heroic from terminal

**Comment by flavioislima** [comment]
> > > I'm facing this same issue but instead of completing the download. It freezes in the process.
> > 
> > 
> > Send the logs for when you launch heroic from terminal.
> 
> What is the command to launch heroic from terminal

just: `heroic`

**Comment by Izz21** [comment]
> > > > I'm facing this same issue but instead of completing the download. It freezes in the process.
> > > 
> > > 
> > > Send the logs for when you launch heroic from terminal.
> > 
> > 
> > What is the command to launch heroic from terminal
> 
> just: `heroic`

It simply stops at this and doesnt continue
Progress: Sugar 3.03%/1082.20
MiB/00:55:35

Progress: Sugar 3.03%/1082.20
MiB/00:55:35

**Comment by flavioislima** [comment]
@Izz21 could not replicate it.
I have 3 drives with BTRFS partitions: A SSD NVME, a SSD SATA and a HDD. I can install any game on any of those drives without an issue.

You're using Debian, right?
This is the stable or the testing branch?
Because since it focuses a lot on stability, might be that some lib is missing or have an old version installed.

Can you try another distro? Like Ubuntu or Pop_os! ?

**Comment by Izz21** [comment]
Yes, I'm using Debian 10 stable. I can't try another distro but I think it may be a lib error because this started popping up

libva error: va_getDriverName() failed with unknown libva error,driver_name=(null)

**Comment by Izz21** [comment]
Yes, this error pops up everytime I open heroic. How can I fix it?

**Comment by flavioislima** [comment]
> Yes, this error pops up everytime I open heroic. How can I fix it?

Changing distro maybe? Nothing against Debian it's not just indicated for gaming since everything on Linux gaming needs more recent packages and libraries.

Other thing is using legendary directly, maybe you will have more luck. But on heroic we cannot support every distro, would be impossible.

So we support ubuntu and derivatives and also manjaro and other arch based distros.

**Comment by Izz21** [comment]
Okay, I'll try using legendary then try to change to ubuntu. Thanks for the advice
