### ISSUE TITLE
Add "--ozone-platform-hint=auto" to the desktop launch options by default.

### ISSUE THREAD

**Issue by Bitwolfies** [Heroic-Games-Launcher/HeroicGamesLauncher#3040]
### Problem description

Wayland is not enabled by default, id like it to be.

### Feature description

This change allows wayland clients to use heroic in wayland mode, without effecting X11 users. Works perfectly on my Nvidia card which usually tends to be the worst with wayland, so presumably there wont be any issues.

### Alternatives

I can add it manually, but it being default is nicer.

**Comment by flavioislima** [comment]
I don't see this line switch on the electron docs, I know it is a chromium flag but might not be supported.
Using it here I don't see any difference. how to test if the flag worked?

https://www.electronjs.org/docs/latest/api/command-line-switches

**Comment by flavioislima** [comment]
Cool, I will try it out!

**Comment by Etaash-mathamsetty** [comment]
I have been using the flag for a while, and it's pretty stable, so it's something that we could use
