### ISSUE TITLE
Less default filesystem access for flatpak

### ISSUE THREAD

**Issue by AtFreezingPoint** [Heroic-Games-Launcher/HeroicGamesLauncher#3042]
### Problem description

I believe that the Heroic desktop application uses too much filesystem access when installed normally.

### Feature description

I believe that less filesystem access should be given to the application

### Additional information

Bottles, another application that kind-of does the same thing as Heroic only has permission to the downloads folder on install. I get that Heroic uses Steam's own proton versions and a few other things but i believe that the current number of files it normally can access is unnecessarily over the top.

**Comment by imLinguin** [comment]
Every permission is added for some reason, mostly just to give as much out of the box experience for new Linux and Steam Deck users

**Comment by AtFreezingPoint** [comment]
> Every permission is added for some reason, mostly just to give as much out of the box experience for new Linux and Steam Deck users

Hey, is it not possible to like maybe go like "Would you like to use this feature?" when called for and possibly add that permission later, possibly using sudo?

**Comment by imLinguin** [comment]
This is not how flatpak permissions work...

As far as I know there is no flatpak portal that would allow apps to obtain persistent permissions. Also apps being able to modify their permissions defeats the purpose of the container

**Comment by AtFreezingPoint** [comment]
> This is not how flatpak permissions work...
> 
> As far as I know there is no flatpak portal that would allow apps to obtain persistent permissions. Also apps being able to modify their permissions defeats the purpose of the container

Well yeah i guess, though i believe keeping perms to a minimum whenever possible probably would be the best way to continue.

**Comment by AtFreezingPoint** [comment]
Will mark closed

**Comment by imLinguin** [comment]
I understand the concern but we need to keep in mind that some users don't know how flatpak works and we want to deliver user friendly experience for them too
