### ISSUE TITLE
Games added to Steam are not launching through Steam when MangoHud toggle is activated

### ISSUE THREAD

**Issue by italoghost** [Heroic-Games-Launcher/HeroicGamesLauncher#3046]
### Describe the bug

Since the last version (and latest commits), the games added to Steam are not launching there when the MangoHud toggle is activated, but launching fine on Heroic:

`Launch aborted: Mangohud is enabled, but `mangohud` executable could not be found on $PATH`

If I add `mangohud` to the Wrapper, it launches and the mangohud overlay works, but it doesn't read my MangoHud.conf file.

I have tested with both the AppImage and the latest git (I am using the [heroic-games-launcher-git](https://aur.archlinux.org/packages/heroic-games-launcher-git) package).

### Add logs

```text
System Info:
CPU: 16x AMD Ryzen 7 2700 Eight-Core Processor
Memory: 16.69 GB (used: 6.01 GB)
GPUs:
  GPU 0:
    Name: Advanced Micro Devices, Inc. [AMD/ATI] Ellesmere [Radeon RX 470/480/570/570X/580/580X/590]
    IDs: D=67df V=1002 SD=2310 SV=1458
    Driver: amdgpu
OS: Arch Linux 6.5.3-273-tkg-bore-eevdf (linux)

The current system is not a Steam Deck
We are not running inside a Flatpak container

Software Versions:
  Heroic: 2.9.2 Boa Hancock
  Legendary: 0.20.32 Dark Energy (hotfix #6)
  gogdl: 0.7.3
  Nile: 1.0.0 Jonathan Joestar

Game Settings: {
	"autoInstallDxvk": true,
	"autoInstallVkd3d": true,
	"preferSystemLibs": true,
	"enableEsync": true,
	"enableFsync": true,
	"nvidiaPrime": false,
	"enviromentOptions": [],
	"wrapperOptions": [],
	"showFps": false,
	"showMangohud": true,
	"useGameMode": false,
	"useSteamRuntime": true,
	"language": "br",
	"wineVersion": {
		"bin": "/home/ghost/ssd-games/SteamLibrary/steamapps/common/Proton - Experimental/proton",
		"name": "Proton - Proton - Experimental",
		"type": "proton"
	},
	"winePrefix": "/home/ghost/ssd-games/Heroic/prefix/Rocket League",
	"wineCrossoverBottle": "",
	"autoInstallDxvkNvapi": true
}

Game launched at: Wed Sep 13 2023 13:09:04 GMT-0300 (Brasilia Standard Time)

Launch aborted: Mangohud is enabled, but `mangohud` executable could not be found on $PATH
```

### Steps to reproduce

1. Go to the game Settings
2. Click on "Enable MangoHud"
3. Try to launch a game added to Steam
4. See the error on the logs.

### Expected behavior

The game should launch just fine on Steam with the MangoHud option enabled.

### Heroic Version

main branch from GitHub

### System Information

CPU: 16x AMD Ryzen 7 2700 Eight-Core Processor
Memory: 4.29 GB (used: 1.16 GB)
GPUs:
  GPU 0:
    Name: Advanced Micro Devices, Inc. [AMD/ATI] Ellesmere [Radeon RX 470/480/570/570X/580/580X/590]
    IDs: D=67df V=1002 SD=2310 SV=1458
    Driver: amdgpu
OS: Arch Linux 6.5.3-273-tkg-bore-eevdf (linux)

The current system is not a Steam Deck
We are not running inside a Flatpak container

Software Versions:
  Heroic: 2.9.2 Boa Hancock
  Legendary: 0.20.32 Dark Energy (hotfix #6)
  gogdl: 0.7.3
  Nile: 1.0.0 Jonathan Joestar

**Comment by cncz42** [comment]
Also seems to affect gamemode being enabled

**Comment by Vitorvlv** [comment]
For me no games are launching anymore through steam, doesn't matter if mangohud or gamemode is on or off

**Comment by bruno-fs** [comment]
I can confirm I'm experiencing the same with gamemode and/or mangohud enabled (and I have them installed and working oO)

**Comment by Etaash-mathamsetty** [comment]
Could this be caused by us overriding XDG_CONFIG_HOME? Do gog games work?

**Comment by bruno-fs** [comment]
> Could this be caused by us overriding XDG_CONFIG_HOME? Do gog games work?

Just tested here: the issue affects epic, amazon and gog as well. Enabling mangohud and or mangohud causes the game to not open through steam. Disabling does the trick to make them open.

**Comment by Etaash-mathamsetty** [comment]
> > Could this be caused by us overriding XDG_CONFIG_HOME? Do gog games work?
> 
> Just tested here: the issue affects epic, amazon and gog as well. Enabling mangohud and or mangohud causes the game to not open through steam. Disabling does the trick to make them open.

ok so it's something else

**Comment by Nocccer** [comment]
Probably the Path to mangohud executable is not appended. Will check tomorrow

**Comment by Nocccer** [comment]
OK found the error:
calling `which mangohud` inside steam throws an error:
`ERROR: ld.so: object '/home/niklas/.steam/debian-installation/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.`

**Comment by Nocccer** [comment]
Feel free to test the AppImage from the actions. For me it solved the problem.
