### ISSUE TITLE
Show the free game of the week.

### ISSUE THREAD

**Issue by adityaruplaha** [Heroic-Games-Launcher/HeroicGamesLauncher#305]
A simple `openUrlOrFile` should suffice I feel.

**Comment by dragonDScript** [comment]
We should show it in a separate window, like steam does

**Comment by dragonDScript** [comment]
> A simple openUrlOrFile should suffice I feel.

What about a link to the launch protocol? If it's installed, it will be played. If not, it will prompt to install it.

**Comment by flegald** [comment]
I would like to take this please.

**Comment by flegald** [comment]
PR has been opened for this feature.

I did try and see if there was any way I could get the free games' info without scraping the page's HTML so we could have better integration into Heroic.

But I did not see anything exposed for this in legendary.

This means that we have to use Epic's own storefront for this popup unfortunately.

**Comment by dragonDScript** [comment]
It's okay. At least they can get the free games.

**Comment by wiryfuture** [comment]
@flavioislima I think this can be closed w/ the store page.

**Comment by flavioislima** [comment]
Yes! 👍🏽
