### ISSUE TITLE
GOG games aren’t connected to GOG account and the GOG cloud 

### ISSUE THREAD

**Issue by itslexii** [Heroic-Games-Launcher/HeroicGamesLauncher#3052]
### Describe the bug

So currently I’m trying to play Cyberpunk 2077 on heroic on MacOS with GPTK, and I used to play through GeForce now, where all my saves are on the GOG cloud. When trying Cyberpunk through heroic launcher, opening the game shows none of my cloud saves there, and also says I must launch Cyberpunk 2077 through GOG account to receive my ingame rewards, which I assume to mean that I am not logged in. Is there any way to fix this so I can access my cloud saves ?

### Add logs

```text
no logs
```

### Steps to reproduce

1. Go to GOG games like Cyberpunk
2. Click on launch game
3. Look for online or connected to GOG account
4. Is not connected to GOG accoung

### Expected behavior

Expected should be that GOG account is linked to the game and the game acknowledges that you are connected to GOG account and allows access to the GOG cloud

### Heroic Version

Latest Stable

### System Information

- OS [e. g. "MacOS"]:
- Using GPTK 1.0.4

**Comment by Kajot-dev** [comment]
That is true, but it should be a feature-request as it is in the planned features (https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher#planned-features) "Play GOG games online"

**Comment by Lariaa** [comment]
This requires the integration of https://github.com/imLinguin/comet into heroic which is currently being worked on.
Some games use the Galaxy Integration SDK, which Heroic currently doesn't provide a replacement for.

**Comment by imLinguin** [comment]
in terms of cloud saves, you can just download them in the game settings, other features like online or cross platform sync are planned like @Lariaa and @Kajot-dev mentioned. Cloud saves are supported already though

**Comment by karaushu** [comment]
Hello, any news here?
Have similar issues with Witcher 3. I want to use [cross progression](https://support.cdprojektred.com/en/witcher-3/nintendo-switch/sp-technical/issue/2431/how-to-use-cross-progression-2) for switch/PC. When enter My rewards, there is a banner - "Open GOG Galaxy 2.0 and start the game".

**Comment by imLinguin** [comment]
Latest versions of Cyberpunk 2077 and Witcher 3 use REDLauncher (a separate CDPR account) for cross progression and in-game rewards. Other than that new comet experimental support provides this functionality for older versions of those games.

**Comment by MattSturgeon** [comment]
> Latest versions of Cyberpunk 2077 and Witcher 3 use REDLauncher (a separate CDPR account) for cross progression and in-game rewards.

Does REDLauncher work with Heroic and if not are there any plans to add support? Would it need a project similar to comet?

> Other than that new comet experimental support provides this functionality for older versions of those games.

Amazing, thanks for all your work on this!

**Comment by imLinguin** [comment]
REDLauncher doesn't have any dependencies on GOG Galaxy (or at least they are optional). It only requires additional login to CDPR account. 
Once setup, using `--launcher-skip` launch parameter will prevent its GUI from appearing, while still working in the background.

Comet is still needed to provide achievements and such...

**Comment by diffusi-on** [comment]
I’m having trouble getting this to work on macOS using the Heroic Launcher, GOG account, and Cyberpunk 2077. There’s no option to sign in with my CDPR account — no RED launcher appears at all. The game just starts directly and displays a warning that it must be launched from GOG to enable cross-progression. Does anyone know how to fix this?

**Comment by MattSturgeon** [comment]
> no RED launcher appears at all. The game just starts directly

Do you have the `--launcher-skip` CLI argument configured? You'll need to temporarily remove that to get the launcher to show up.

**Comment by diffusi-on** [comment]
@MattSturgeon No. Just tried clean install from Heroic/GOG account. Same result: game starts directly from Heroic

**Comment by imLinguin** [comment]
@diffusi-on are you on Mac by any chance? I remember that there, the red launcher fails to show the UI so it falls back to simply launching the game. 
If on Linux, you should make sure you run Proton-GE and try running the installer of the launcher (found in the game directory) using Heroic's run in prefix feature (found in Heroics game settings). 

If none of that helps you should seek help on our subreddit or Discord

**Comment by diffusi-on** [comment]
@imLinguin  Exactly! I’m on an arm Mac M4 Max. I also checked the Heroic game logs and found that it tries to launch RedLauncher, then catches an error and follows by dirct game launch (as you said). There is no exact reson why, even with verbose logs enabled. Missing .dll or somthing. Sad.

`2025-03-29 17:35:54.366 [Information][ (0)] [TID 36][red-launcher]: Scheduling problem report gui_failed_to_load (type post_mortem).
2025-03-29 17:35:54.367 [Error][ (0)] [TID 36][red-launcher]: The GUI failed to load. Launching the initial game's fallback edition.
2025-03-29 17:35:54.367 [Information][ (0)] [TID 36][red-launcher]: Requested to launch the game.
2025-03-29 17:35:54.420 [Information][ (0)] [TID 36][red-launcher]: The game was launched under PID 564.
2025-03-29 17:35:54.420 [Information][ (0)] [TID 36][red-launcher]: No user ID in the settings file.`

**Comment by Blintmester** [comment]
this problem is still present in 2026, I'm using M4 Max, and Redlauncher still can't open, and I can't login, is there a known workaround?

<img width="504" height="249" alt="Image" src="https://github.com/user-attachments/assets/fe50aef1-3ae9-4c70-920b-f41ced7e4501" />
