### ISSUE TITLE
Better credential management.

### ISSUE THREAD

**Issue by adityaruplaha** [Heroic-Games-Launcher/HeroicGamesLauncher#306]
- [ ] Change login to use the Epic Login instead of SID
- [x] Ask to login again after credentials has expired

Supersedes #232.

**Comment by dragonDScript** [comment]
For storing secrets, there are libraries like node-keytar.

**Comment by dragonDScript** [comment]
See https://api.epic.foundation/docs/oauth2

**Comment by arielj** [comment]
I think this can be closed, right? @flavioislima

**Comment by flavioislima** [comment]
Yes, thanks 👍🏽
