### ISSUE TITLE
GE-Proton8-15 update failed

### ISSUE THREAD

**Issue by Gamertech** [Heroic-Games-Launcher/HeroicGamesLauncher#3067]
### Describe the bug

Using the 'latest' install option for both Wine-GE and GE-Proton.

When clicking update on Wine-GE8-15 it downloads and completes successfully. When downloading GE-Proton8-15 however it fully downloads then fails to extract with a permission denied error on 'files/lib64/wine/nvapi/version'.

### Add logs

```text
System Information:

CPU: 24x AMD Ryzen 9 5900X 12-Core Processor

Memory: 33.56 GB (used: 4.39 GB)

GPUs:

  GPU 0:

    Name: Advanced Micro Devices, Inc. [AMD/ATI] Navi 31 [Radeon RX 7900 XT/7900 XTX]

    IDs: D=744c V=1002 SD=2423 SV=148c

    Driver: amdgpu

OS: Freedesktop SDK 22.08 (Flatpak runtime) (linux)

The current system is not a Steam Deck

We are running inside a Flatpak container

Software Versions:

  Heroic: 2.9.2 Boa Hancock

  Legendary: 0.20.32 Dark Energy (hotfix #6)

  gogdl: 0.7.3

  Nile: 1.0.0 Jonathan Joestar

(09:32:21) INFO:    [Backend]:          Starting the Download Queue

(09:32:23) INFO:    [Gog]:              Saved games data

(09:32:23) WARNING: [Backend]:          listUpdateableGames not implemented on Sideload Library Manager

(09:32:24) INFO:    [Gog]:              Found 0 game(s) to update

(09:32:25) INFO:    [Legendary]:        Checking for game updates: XDG_CONFIG_HOME=/home/gamertech/.var/app/com.heroicgameslauncher.hgl/config/heroic/legendaryConfig /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary list --third-party

(09:32:28) INFO:    [Legendary]:        Found 0 games to update

(09:32:37) INFO:    [Frontend]:         Refreshing wine downloader releases

(09:32:37) INFO:    [WineDownloader]:   Updating wine versions info

(09:32:37) INFO:    [WineDownloader]:   Fetching upstream information...

(09:32:39) INFO:    [WineDownloader]:   wine versions updated

(09:32:47) INFO:    [WineDownloader]:   Start update of wine version Wine-GE-latest

(09:33:01) INFO:    [WineDownloader]:   Finished update of wine version Wine-GE-latest

(09:33:10) INFO:    [WineDownloader]:   Start update of wine version Proton-GE-latest

(09:33:50) ERROR:   [WineDownloader]:   Error: Unzip of GE-Proton8-15.tar.gz failed with:

 Unzip of /home/gamertech/.var/app/com.heroicgameslauncher.hgl/config/heroic/tools/proton/GE-Proton8-15.tar.gz failed with:

 tar: files/lib64/wine/nvapi/version: Cannot open: Permission denied

!

    at /app/bin/heroic/resources/app.asar/build/electron/main.eeeeb87e.js:118:195

    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

    at async installVersion (/app/bin/heroic/resources/app.asar/build/electron/main.eeeeb87e.js:118:16)

    at async installWineVersion (/app/bin/heroic/resources/app.asar/build/electron/main.eeeeb87e.js:119:1796)

    at async /app/bin/heroic/resources/app.asar/build/electron/main.eeeeb87e.js:190:17455

    at async node:electron/js2c/browser_init:2:98394

(09:33:57) INFO:    [WineDownloader]:   Start update of wine version Proton-GE-latest

(09:34:36) ERROR:   [WineDownloader]:   Error: Unzip of GE-Proton8-15.tar.gz failed with:

 Unzip of /home/gamertech/.var/app/com.heroicgameslauncher.hgl/config/heroic/tools/proton/GE-Proton8-15.tar.gz failed with:

 tar: files/lib64/wine/nvapi/version: Cannot open: Permission denied

!

    at /app/bin/heroic/resources/app.asar/build/electron/main.eeeeb87e.js:118:195

    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

    at async installVersion (/app/bin/heroic/resources/app.asar/build/electron/main.eeeeb87e.js:118:16)

    at async installWineVersion (/app/bin/heroic/resources/app.asar/build/electron/main.eeeeb87e.js:119:1796)

    at async /app/bin/heroic/resources/app.asar/build/electron/main.eeeeb87e.js:190:17455

    at async node:electron/js2c/browser_init:2:98394
```

### Steps to reproduce

1. Go to Wine Manager with Proton-GE-Latest selected and on a previous version to 8-15
2. Click on PROTON-GE
3. Click on the update icon
4. Update proceeds then fails to extract and cancels.

### Expected behavior

Heroic successfully downloads and extracts GE-Proton 8-15

### Heroic Version

Latest Stable

### System Information

- OS [e. g. "Ubuntu"]: Fedora KDE 38
- Heroic Flatpak

**Comment by Gamertech** [comment]
Happening with 8-16 too, Proton-GE-Latest fails to install every time, however specifically installing Proton-GE-Proton8-16 below it works fine.

In Wine Manager 8-16 shows a filesize of 1.19 GiB whereas -Latest shows 1.18 GiB.
In Distro properties 8-16 shows 1,274,644,168 whereas Latest shows 1,525,806,315.

Log for 8-16-Latest install process is identical to above.

Wine-GE-Latest works fine still with 8-17.

After a Heroic restart and waiting ~10 minutes, the Wine Manager will remove the Update icon from the Proton-GE-Latest line as if it's installed but looking at the Proton files themselves, it looks like the files in the Latest directory have only partially been updated.

Uninstalling -Latest via Wine Manager (and ensuring the directory was gone) and reinstalling -Latest completed successfully and filesize in Heroic matches 8-16 at 1.19GiB.

In Dolphin 8-16 now shows 1,274,633,702 and -Latest shows 1,274,644,168.

**Comment by Nocccer** [comment]
Atm i just unzip the files into the folder with overwrite. This does not delete files that do not exist in the new version. Thats why the size increase. 

About the permission. Somehow GE changes file permissions from release to release.

I will add a fix that removes the existing files completly before unzipping the new version

**Comment by Gamertech** [comment]
Quick work! Thanks Nocccer
