### ISSUE TITLE
Implement a registered Heroic protocol.

### ISSUE THREAD

**Issue by adityaruplaha** [Heroic-Games-Launcher/HeroicGamesLauncher#307]
For integration purposes, we need to implement a standardised protocol for communicating with Heroic from other applications. The simplest way to achieve this is using Electron's [protocol](https://www.electronjs.org/docs/api/protocol). 

Candidates:
- `heroic://` (going with this one.)
- `heroicgl://`

I'm not sure which kind of protocol we should register, but I'm thinking string.

Usecases:
- Desktop Shortcuts
- Integration into other services like Discord Rich Presence. (I'm thinking: Open Game button to the Rich Presence so that anybody can play along.)

**Comment by adityaruplaha** [comment]
This is a rather high priority project as some important things depend upon it. I'll try to get an initial implementation worked out.

**Comment by Flonky** [comment]
I'd prefer the `heroic://` url, it just looks better than `heroicgl://` and i dont know of any other projects which would use it as theirs

**Comment by adityaruplaha** [comment]
Initial implementation ready, but can't test since there's no .desktop file corresponsding to the executable.

**Comment by flavioislima** [comment]
100% heroic://
