### ISSUE TITLE
Can't install Kerbal Space Program. "String must contain at least 1 character(s)"

### ISSUE THREAD

**Issue by salihmarangoz** [Heroic-Games-Launcher/HeroicGamesLauncher#3114]
### Describe the bug

Can't install Kerbal Space Program.

### Add logs

```text
(04:09:22) ERROR:   [DownloadManager]:  Installation of a1e2ce30defe4a9187ebc14fc9d2bd8b failed with: [

  {

    "code": "too_small",

    "minimum": 1,

    "type": "string",

    "inclusive": true,

    "exact": false,

    "message": "String must contain at least 1 character(s)",

    "path": []

  }

]
```

### Steps to reproduce

1. Go to the library
2. Click on Kernal Space Program
3. Install the game
4. Nothing happens. See the error in the log.

### Expected behavior

Install the game.

### Heroic Version

Latest Stable

### System Information

- OS [e. g. "Ubuntu"]: Ubuntu 20.04
- App version 2.9.2

### Additional information

From Epic Games library.

**Comment by teunzwart** [comment]
Investigating a bit further, this seems to be a regression as 2.9.1 does allow for KSP to install, and the install still works on 2.9.2. A workaround is to use [https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/releases/download/v2.9.1/Heroic-2.9.1-macOS-arm64.dmg](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/releases/download/v2.9.1/Heroic-2.9.1-macOS-arm64.dmg)

**Comment by arielj** [comment]
Can you try with Heroic 2.10.0? we upgraded legendary so maybe that fixes this?

**Comment by teunzwart** [comment]
2.10.0 does indeed fix this. Thank you!

**Comment by salihmarangoz** [comment]
2.10.0 fixes this problem. Thank you!
