### ISSUE TITLE
Cannot start GOG game in CrossOver 23.5

### ISSUE THREAD

**Issue by CyrosX** [Heroic-Games-Launcher/HeroicGamesLauncher#3118]
### Describe the bug

I've had Heroic on my system already installed and updated.
Trying to start Witcher 3 (my first and only - downloaded and installed Heroic game) is not working.
The "Heroic" bottle exists in CrossOver. D3DMetal is enabled and ESync. But changing these (to e.g. DXVK) does not change the outcome.
It seems as it does not use the CrossOver Wine instance.
My custom wine/proton path is empty.
Game defaults shows CrossOver 23.5 and bottle name Heroic.
Heroic is also the default bottle in CrossOver. (Nothing is installed in it)

The game launches when using CrossOver directly.

### Add logs

```text
System Info:
CPU: 10x Apple M1 Pro
Memory: 34.36 GB (used: 16.44 GB)
GPUs:

OS:  14.0.0 (darwin)

The current system is not a Steam Deck
We are not running inside a Flatpak container

Software Versions:
  Heroic: 2.9.2 Boa Hancock
  Legendary: 0.20.32 Dark Energy (hotfix #6)
  gogdl: 0.7.3
  Nile: 1.0.0 Jonathan Joestar

Game Settings: {
	"autoInstallDxvk": true,
	"autoInstallVkd3d": true,
	"preferSystemLibs": false,
	"enableEsync": true,
	"enableFsync": true,
	"nvidiaPrime": false,
	"enviromentOptions": [],
	"wrapperOptions": [],
	"showFps": false,
	"targetExe": "",
	"useGameMode": false,
	"language": "de",
	"wineVersion": {
		"bin": "/Applications/CrossOver.app/Contents/SharedSupport/CrossOver/bin/wine",
		"name": "CrossOver - 23.5",
		"type": "crossover",
		"wineserver": "/Applications/CrossOver.app/Contents/SharedSupport/CrossOver/bin/wineserver"
	},
	"wineCrossoverBottle": "Heroic",
	"winePrefix": "/Users/cyrosx/.wine",
	"gogSaves": [
		{
			"name": "saves",
			"location": "/Users/cyrosx/Library/Application Support/CrossOver/Bottles/Heroic/dosdevices/c:/users/crossover/Documents/The Witcher 3"
		}
	]
}

Game launched at: Fri Oct 06 2023 13:23:54 GMT+0200 (Central European Summer Time)

Launch Command: HEROIC_APP_NAME=1495134320 HEROIC_APP_RUNNER=gog HEROIC_APP_SOURCE=gog LD_PRELOAD= DOTNET_BUNDLE_EXTRACT_BASE_DIR= CX_BOTTLE=Heroic WINE_FULLSCREEN_FSR=0 WINEESYNC=1 WINEFSYNC=1 /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/gogdl launch "/Users/cyrosx/Games/Heroic/The Witcher 3 Wild Hunt GOTY" 1495134320 --platform windows --prefer-task 2

Game Log:
Traceback (most recent call last):
  File "gogdl/cli.py", line 51, in <module>
  File "gogdl/cli.py", line 47, in main
  File "gogdl/launch.py", line 173, in launch
  File "subprocess.py", line 951, in __init__
  File "subprocess.py", line 1837, in _execute_child
OSError: [Errno 8] Exec format error: '/Users/cyrosx/Games/Heroic/The Witcher 3 Wild Hunt GOTY/bin/x64/witcher3.exe'
[83360] Failed to execute script 'cli' due to unhandled exception!
Launch command: ['/Users/cyrosx/Games/Heroic/The Witcher 3 Wild Hunt GOTY/bin/x64/witcher3.exe']
```

### Steps to reproduce

1. Go to 'Library'
2. Click on 'Witcher 3 - Play'
// Choosing one of the launch options from the details page, does not change this behavior.
(Options: The Witcher 3 - Wild Hunt, The Witcher 3 - Wild Hunt (DX11)
3. Wait. Button says "Stop" but after some time it is back to "Play"
4. See error in logs

### Expected behavior

Game launches.

### Heroic Version

Latest Stable

### System Information

- OS [e. g. "Ubuntu"]: macOS 14.0
- Crossover 23.5

**Comment by cptryd** [comment]
I'm having the same issue with GoG games starting from version 2.9.0. It seems that the launch command is missing the --wine parameter. Without it it tries to execute the windows executable directly which leads the above error "Exec format error".

**Comment by nonoche2** [comment]
same for me (on macOS), I can only launch games from EGS with Heroic. Games from Amazon and GoG install but do not launch. I can launch these games from CrossOver. This has been happening for the past couple versions of Heroic

**Comment by thysanoptera** [comment]
I just spend the whole day trying to figure this out. Same situation on MacOS, Exec format error when launching any GOG game.

**Comment by cptryd** [comment]
It works if I explicitly add game arguments which Heroic should do automatically when it runs a windows command on MacOS.
<img width="783" alt="game_arguments" src="https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/assets/9074096/8e1ab734-e35f-4c49-8bd2-e91a3344cf7b">

**Comment by nonoche2** [comment]
confirmed, this solves the issue for me, both for GOG and Amazon games

**Comment by Alex0007** [comment]
I can confirm @cptryd solution. This is definitely a bug. 

Also it's unclear to me: Esync is turned off in bottle configuration, but it turned on in logged game settings. What will be a result of this?

```
Software Versions:
  Heroic: 2.11.0 Kumachi
  Legendary: 0.20.33 Undue Alarm
  gogdl: 0.7.3
  Nile: 1.0.0 Jonathan Joestar

Game Settings: {
	"autoInstallDxvk": true,
	"autoInstallVkd3d": false,
	"preferSystemLibs": false,
	"enableEsync": true,
	"enableFsync": false,

```

**Comment by flavioislima** [comment]
Can you guys test the build from this PR #3308 ?
you can download from the macOS build and then run `xattr -d -r com.apple.quarantine Heroic.app` if it says its corrupted.

We only need to confirm it's working so we can merge and add it on the next release.

@Alex0007 @CyrosX @cptryd @nonoche2

**Comment by Alex0007** [comment]
@flavioislima I have tested released version and it works
