### ISSUE TITLE
two options of "unistall/install dxvk in the prefix" in spanish version of heroic 

### ISSUE THREAD

**Issue by 00pandora00** [Heroic-Games-Launcher/HeroicGamesLauncher#3123]
### Describe the bug

two options of "unistall/install dxvk in the prefix" in spanish version of heroic:

![Captura desde 2023-10-09 00-10-44](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/assets/143676512/19bda052-5d75-413a-8409-2265db3a749d)

### Add logs

```text
(none)
```

### Steps to reproduce

2. Click on '...'
3. Scroll down to '...'

### Expected behavior

just one option of "unistall/install dxvk in the prefix" in spanish version of heroic  (but maeby this is just a traduction error. sooo correct the line?)

### Heroic Version

Latest Stable

### System Information

Fedora 38

### Additional information

if is needed more information i will provide it, in principle.

**Comment by arielj** [comment]
This is currently fixed in Weblate and should be included in a next release.

One of them is actually for NVAPI and not for DXVK but the translation is wrong.

I'll leave this open until that's released.

**Comment by arielj** [comment]
Should be fixed now in 2.10.0

**Comment by 00pandora00** [comment]
> Should be fixed now in 2.10.0

yea is fix
