### ISSUE TITLE
Impossible to start when ~/.local/share/flatpak is a symlink (bwrap)

### ISSUE THREAD

**Issue by Zykino** [Heroic-Games-Launcher/HeroicGamesLauncher#3134]
### Describe the bug

Heroic does not start at all.
```sh
❯ flatpak run com.heroicgameslauncher.hgl
bwrap: Can't make symlink at /home/zykino/.local/share/flatpak: File exists

~
❌1 ❯
```

### Add logs

```text
Can I get the logs another way? I do not have a GUI that open so can’t go to the Settings panel…
```

### Steps to reproduce

1. Go to another HD where you have more space than your home one.
2. `mv ~/.local/share/flatpak/ .`
3. `rm ~/.local/share/flatpak/ -r` (there was still some files in the repo subfolder, including a lock one)
4. `ln -s </new/path/to/share>/flatpak/ ~/.local/share/flatpak`
5. (reboot)
6. Try to start heroic, it don’t try with the cli, see the bug description.

### Expected behavior

Heroic does not care that the flatpak folder is a symbolic link to an other Hard Drive (it start slower, like Discord, Thunderbird, and others flatpak apps but still start).

### Heroic Version

Latest Stable (Flatpak)

### System Information

- OS [PopOS]: Linux zykino-pop-os 6.5.4-76060504-generic #202309191142~1695998943~22.04~070916d SMP PREEMPT_DYNAMIC Fri S x86_64 x86_64 x86_64 GNU/Linux

### Additional information

I already moved the game folder on the same hard drive (and steam games but Heroic isn’t connected to steam, right?) So I added "Another folders" in Flatseals that points to "</other/path/to/hard/drive>/Games/Heroic" but that was done before and worked well.

I already did `flatpak  install com.heroicgameslauncher.hgl --reinstall` found in another issue, without success.

**Comment by Etaash-mathamsetty** [comment]
this is the wrong way to move a flatpak to another drive, follow this guide https://docs.flatpak.org/en/latest/tips-and-tricks.html#adding-a-custom-installation

**Comment by Zykino** [comment]
I think I like your idea to bind mount better. Maybe it needs `fstab` to have it at startup isn’t it?

I tried to configure a custom flatpak installation but I don’t find a way to move the application from my user folder to this one. Nor a way to have the pop-shop use that install folder. I don’t really know flatpak, I kinda only use it from the pop-shop :sweat_smile:

**Comment by Zykino** [comment]
Thanks again both of you, I believe Etash’s solution should work, but since I don’t really know flatpak I went with wsdfhjxc’s one.

I added that in my `/etc/fstab` file so the mount is persistent now and I don’t have issue anymore with heroic (and did not lost all I had downloaded before):
```/etc/fstab
# Move flatpak folders to save /home space
/mnt/Data/Flatpak/appdata  /home/zykino/.var/app  none  defaults,bind  0  0
/mnt/Data/Flatpak/installation  /home/zykino/.local/share/flatpak  none  defaults,bind  0  0
```

**Comment by Zykino** [comment]
I closed the issue, but if you want to support the simple symlink way I tried to do, feel free to re-open it. Other flatpak are not disturbed by it so it could still be good to also not crash on it.
