### ISSUE TITLE
List steam games also to launch

### ISSUE THREAD

**Issue by niksingh710** [Heroic-Games-Launcher/HeroicGamesLauncher#3138]
### Problem description

I love heroic launcher and I like to have all my ganes at one place
It would be nice if I can launch my steam games using heroic 

### Feature description

Steams games listed in heroic library and launched

**Comment by arielj** [comment]
Closing as a duplicate of https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/issues/2872
