### ISSUE TITLE
Running a game from a desktop shortcut or from steam shouldn't start downloads

### ISSUE THREAD

**Issue by arielj** [Heroic-Games-Launcher/HeroicGamesLauncher#3155]
### Describe the bug

I have things on the download queue and stopped everything. I closed Heroic and then I launched a game from a desktop shortcut.

After closing the game, Heroic was still running so I opened it. A download was in progress.

Apart form the problem that the download is happening in the background and I don't know that, this creates a problem on the steam deck in gaming mode: when closing a game, steam can't close heroic cause there's a download in progress, so we end up in a black screen and we have to press B to abort the game.

### Add logs

```text
Nothing relevant.
```

### Steps to reproduce

1. Add some game to the queue
2. Pause the download
3. Close Heroic
4. Launch a game from a shortcut (desktop or steam)
5. Close the game

In desktop mode you can open the Heroic UI to see the game is being downloaded. In gaming mode the game won't fully close and needs to be aborted.

### Expected behavior

When launching a game from any shortcut, heroic should NOT start downloads.

### Heroic Version

Latest Stable

### System Information

Not relevant

### Additional information

This can probably be solved by waiting some time to start the downloads when start heroic to have time to process if the start is triggered by the protocol, and only start downloads if not started by the protocol.

**Comment by flavioislima** [comment]
Makes sense, adding a check if it is using no-gui here should solve this issue:
https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/blob/876da593cd5eabab0e60f24fa33446db65e28cc0/src/backend/main.ts#L454

I can open a quick PR to fix that.
