### ISSUE TITLE
Heroic doesn't refresh properly installation infos after changing the path

### ISSUE THREAD

**Issue by Giovix92** [Heroic-Games-Launcher/HeroicGamesLauncher#316]
**Describe the bug**
The title is self-explanatory

**To Reproduce**
1. Open Heroic, click on Rocket League
2. Select "Import game" and select the path for it
3. Wait till it loads the version etc.
4. Now change installation path (eg. in my case the default installation folder (/home/user/Games/Heroic)
5. You'll notice it'll be stuck on previous installation infos, with no possibility of uninstalling.

**Expected behavior**
It should refresh the status from "Installed" to "Non-installed"

**Screenshots**
Old folder (installed thru EGS previously):
![image](https://user-images.githubusercontent.com/19226770/115155238-42fb7a80-a07f-11eb-8027-4be5c9d152c3.png)
New folder (empty):
![image](https://user-images.githubusercontent.com/19226770/115155216-2e1ee700-a07f-11eb-95e2-624004e49d86.png)
Heroic with new path:
![image](https://user-images.githubusercontent.com/19226770/115155127-c8caf600-a07e-11eb-9415-4d0ac365252f.png)

**Desktop (please complete the following information):**

- OS: Arch Linux
- Version: latest
- Game: Rocket League
- Wine/Proton version: 6.6, as per wine options.

**Additional context**
Strangely it keeps every info from the previous installation. The uninstall button makes the page just refresh, nothing much. Also the old path will stay there where it was, with every file inside it (and it should be like that tbf, since the path was changed).

**Comment by adityaruplaha** [comment]
Not a Heroic issue. Change Installation Path is an unsafe option and will not verify that game files actually exist there. We should warn about that tbh. 

For the record, "Change Installation Path" does not:
1. Move your game.
2. Verify files are actually present there.
3. Repair a possibly broken installation.

It literally just updates where Legendary thinks the installation files are located.

I suggest renaming the option as its pretty confusing.
