### ISSUE TITLE
Repairing Epic games currently does not work

### ISSUE THREAD

**Issue by CommandMC** [Heroic-Games-Launcher/HeroicGamesLauncher#3163]
### Describe the bug

Repairing Epic games will quit instantly, without actually repairing. This is caused by this switch case:

https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/blob/75f79d16dd1b50cb4f1f008de0db139881c02f47/src/backend/storeManagers/legendary/library.ts#L810-L813

missing the "repair" case

### Add logs

```text
Reported by a user on Discord
Relevant part of <AppName.log>:

usage: legendary install <App Name> [options]
legendary install: error: the following arguments are required: <App Name>
```

### Steps to reproduce

1. Go to a game's page
2. Try to repair it
3. See error

### Expected behavior

Well, repairing should work

### Heroic Version

Latest Stable

### System Information

N/A

**Comment by arielj** [comment]
fixed by https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/pull/3165
