### ISSUE TITLE
It doesn't start with Heroic Crossover.

### ISSUE THREAD

**Issue by canyesilyurt** [Heroic-Games-Launcher/HeroicGamesLauncher#3176]
### Describe the bug

I want to play The Evil Within 2. I have a Windows 10 x64 bottle called Heroic on Crossover. It won't open the game on Crossover.

![image](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/assets/36952967/04db264a-6f7d-4059-98cd-bc9faa08fcfa)
![image](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/assets/36952967/8a79e803-d974-4873-a266-ff8eb93dda1a)

### Add logs

```text
(16:11:06) INFO:    [Backend]:          Launching The Evil Within 2 (74977fee80de4e5e9f663e62560a0f2f)
(16:11:06) INFO:    [Backend]:          Checking if wine version exists: CrossOver - 23.6
(16:11:06) INFO:    [Backend]:          Stopping Power Saver Blocker
(16:11:06) DEBUG:   [Legendary]:        Using cached install info
(16:11:06) DEBUG:   [Legendary]:        Using cached install info
(16:11:06) DEBUG:   [Legendary]:        Using cached install info
(16:11:06) DEBUG:   [Legendary]:        Using cached install info
(16:11:06) INFO:    [Backend]:          Checking if wine version exists: CrossOver - 23.6
(16:11:06) INFO:    [Backend]:          Checking if wine version exists: CrossOver - 23.6
(16:11:06) INFO:    [Legendary]:        Launching The Evil Within 2: HEROIC_APP_NAME=74977fee80de4e5e9f663e62560a0f2f HEROIC_APP_RUNNER=legendary HEROIC_APP_SOURCE=epic LD_PRELOAD= DOTNET_BUNDLE_EXTRACT_BASE_DIR= CX_BOTTLE=Heroic WINE_FULLSCREEN_FSR=0 WINEESYNC=1 WINEFSYNC=1 XDG_CONFIG_HOME="/Users/cy/Library/Application Support/heroic/legendaryConfig" /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/legendary launch 74977fee80de4e5e9f663e62560a0f2f --language tr
(16:11:29) INFO:    [Backend]:          Stopping Display Power Saver Blocker
(16:11:29) INFO:    [Frontend]:         Refreshing legendary Library
(16:11:29) INFO:    [Legendary]:        Refreshing library...
(16:11:29) INFO:    [Legendary]:        Refreshing Epic Games...
(16:11:29) ERROR:   [Legendary]:        Failed to parse 261f8e875a0e45f98e517946deca4dc8.json
(16:11:29) ERROR:   [Legendary]:        Failed to parse AzaleaAlpha.json
(16:11:29) ERROR:   [Legendary]:        Failed to parse b6c8e6f5a6a14c88bfec3af60f0a4a72.json
(16:11:29) INFO:    [Legendary]:        Game list updated, got 146 games & DLCs
(16:11:29) INFO:    [Legendary]:        Running command: XDG_CONFIG_HOME="/Users/cy/Library/Application Support/heroic/legendaryConfig" /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/legendary list --third-party
```

### Steps to reproduce

2. Click on '...'
3. Scroll down to '...'

### Expected behavior

I want the game to start on crossover

### Heroic Version

Latest Stable

### System Information

MacOs

**Comment by arielj** [comment]
For support running specific games, please use our Discord server and start a new thread in the `#-support` channel.

This issues tracker is for issues in Heroic itself.

**Comment by Alex0007** [comment]
@arielj @canyesilyurt  it's a common bug with heroic-crossover integration

Solution is to manually provide `--wine` argument

https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/issues/3118#issuecomment-1752389371

**Comment by Coulin9** [comment]
> @arielj @canyesilyurt it's a common bug with heroic-crossover integration
> 
> Solution is to manually provide `--wine` argument
> 
> [#3118 (comment)](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/issues/3118#issuecomment-1752389371)

I have the same problem and the solution doesn't work for me
