### ISSUE TITLE
Core Bugs on Installing and Launching

### ISSUE THREAD

**Issue by Rapta-08** [Heroic-Games-Launcher/HeroicGamesLauncher#319]
Describe the bug:
I tried to install Core (an early access game)
I got stuck on "Installing (Screenshot 1)"
I killed the progress and after I relaunched Heroic it told me it was installed.
After I launched it, got stuck at the second secreenshot.

**To Reproduce**

First Error:
1. Go to 'Core'
2. Click on 'Install Game'
3. Wait until it is downloaded

Second Error:
1. Kill the progress
2. Launch the game
3. See error

**Screenshots**
1. https://drive.google.com/file/d/1fi82YEapsT--WnJuYxh2qJvTrvLJfQw-/view?usp=sharing
2. https://i.imgur.com/FWN7MQs.png

**Desktop:

- OS: Manjaro
- Version: 21.0.2
- Game: Core (Early Access)
- Wine/Proton version: Wine 6.6 Staging

Additional Information:
I discuased with the Reddit community in [r/linux_gaming](https://www.reddit.com/r/linux_gaming/), specificly [here].(https://www.reddit.com/r/linux_gaming/comments/mul1mc/installing_core_via_heroic_games_launcher_leaves/) 
[InterestingAddendum](https://www.reddit.com/user/InterestingAddendum/) told to provide you this log file:
~/.config/heroic/GamesConfig/a99769d95d8f400baad1f67ab5dfe508-lastPlay.log

**Comment by adityaruplaha** [comment]
Yeah we're going to need the logfile.

**Comment by adityaruplaha** [comment]
Also try using Verify and Repair.

The installation bar is very finicky, so give it a few minutes extra after it gets stuck just in case.

**Comment by flavioislima** [comment]
I'm wondering that this game might have selective download that is something that heroic does not support yet and if thats the case, you will need to install the game from the Legendary CLi and then you can launch from HEroic. Because this game is like a selection of several games so might be the case. I dont have it to test so I can be of much help.

So, if possible, try to install legendary (it's on AUR), and run `legendary list-installed` to check if the game is properly installed.

**Comment by Rapta-08** [comment]
I tried it, says that it is, but the game still crashs and doesn't work..

**Comment by Rapta-08** [comment]
Also the log file is [here](https://drive.google.com/file/d/1qJkTftY6enF7IRHWIQbUVhdXonE4x2cF/view?usp=sharing)

**Comment by flavioislima** [comment]
Hi! for the logs, this doesnt looks like a Heroic Issue. The game is being launched correctly. 
Please use our discord to get help for launching games.
