### ISSUE TITLE
When opening a store, if the saved url is external to the store we can't go back to the store

### ISSUE THREAD

**Issue by arielj** [Heroic-Games-Launcher/HeroicGamesLauncher#3200]
### Describe the bug

In 2.10.0 I implemented a feature to store the last visited url for each store.

If the user navigated to a url that is external to the current store, it's saved and then there's no way to go back to the store without clearing the local storage manually of finding a way to navigate back to the store following links.

### Add logs

```text
Nothing relevant
```

### Steps to reproduce

1. Open a store
2. Click links around until you are in an external url
3. go to the library
4. click the same store again
5. We are in a page that is not the actual store

### Expected behavior

We should either not store the url, or we should ignore the stored url if the url does not belong to the store.

### Heroic Version

Latest Stable

### System Information

Not relevant

**Comment by Liametekudasai** [comment]
same bug,  can't go back to the original store

**Comment by jp438-2** [comment]
All three of my store links (Epic, GOG and Prime Gaming) all lead to the Epic Game store now (and the GOG one leads to the EGS Turnip Boy Commits Tax Evasion page). I have no idea how it happened and I can't do anything about it. This really needs to be fixed!

**Comment by nenadandric** [comment]
I'm facing the same issue. Quick workround is to go to library page, select game from GOG store, then go to dot menu and select store page

**Comment by kn-f** [comment]
Same issue here on Heroic 2.10.0.
Even rebooting my PC or clearing Heroic cache is not working, now I'm stuck to a page in Prime gaming no matter what store I choose.
In 2.9 this wasn't happening

**Comment by arielj** [comment]
This will be fixed in the next release, until now the workarounds are:

Option 1)
Ctrl/Cmd+shit+I to open devtools
look for the application tab in devtools
search for local storage in the sidebar
delete the entries that start with `last-url-...`

Option 2)
Open the `store page` of a game from the 3 dots menu in the game's page

**Comment by Zykino** [comment]
Thanks for the workaround. Option 2 did not work for me (it opened the GoG shop, but in the general shop bar, not fixing the "shop gog" item.

The option 1 did work… but I managed to open the dev tools only once, and I’m not sure how/why. Do I need to select the shop, or the application? I tried both but did not have a consistent setup.

Can I stress a point in my issue that: I don’t care which is the last url visited for each shop? I like to have heroic remember if I was on EGS or GoG, but I don’t really want to have it remember if I was visiting game A, B or C (at least, not after a reboot of the application).

Also having a "right click, go to home page" on the "shop gog" item would be nicer to fix this. And/or home button on the line, so I can press that and others can "just" press the label and go to the last visited url.

**Comment by arielj** [comment]
there should be a `last-store` entry in the local storage and then `last-url-gog` `last-url-epic` and `last-url-amazon`, clearing all those things should revert all stores

heroic will set those again though while navigating the store


the current fix (that will be included in the next release) is only storing the pages you navigate inside the store (so you can always go back to the home) and it's only stored during a session, so closing heroic and opening again resets that info too

the requested feature why this was implemented was to store the last url and not just the last store, it's clearly not something everybody needs but the next version will have an easy way to get back to the home (since the stored urls will only be the ones in the specific store, the store home link will always be accessible, so that works as an alternative to right click > go to home)
