### ISSUE TITLE
Can't uninstall amazon games since 2.10.0 version

### ISSUE THREAD

**Issue by MontblancKupo** [Heroic-Games-Launcher/HeroicGamesLauncher#3201]
### Describe the bug

Can't uninstall games from heroic launcher that have been installed from amazon.

### Add logs

```text
Traceback (most recent call last):
  File "nile\cli.py", line 343, in <module>
  File "nile\cli.py", line 330, in main
  File "nile\cli.py", line 245, in handle_uninstall
  File "nile\utils\uninstall.py", line 32, in uninstall
FileNotFoundError: [WinError 2] The system cannot find the file specified: 'D:\\Heroic Launcher Games\\10 Second Ninja X\\directX/JUN2008_d3dx9_38_x86.cab'
[5936] Failed to execute script 'cli' due to unhandled exception!
```

### Steps to reproduce

1. Choose to uninstall a game via context menu of game cover art or "..." menu from within game details page.
2. choose "yes"
3. heroic says "uninstalling"
4. game not uninstalled.

### Expected behavior

Game should uninstall... it does not.

### Heroic Version

Latest Stable

### System Information

windows 10, latest available system update done.
heroic launcher updated to version 2.10.0 via prompt when launching app.

**Comment by MontblancKupo** [comment]
Bug still present after 2.12.0 update.

**Comment by LZeugirdor** [comment]
Can confirm this is an issue.

**Comment by Francehelder** [comment]
Same here. Version 2.12.0

**Comment by arielj** [comment]
closing, heroic 2.15.0 includes the latest `nile` that I understand fixes this issue

feel free to comment if this is still a problem and we can reopen

**Comment by goremykin** [comment]
Not sure if it is related. Tried to uninstall an amazon game on 2.14 - see result on screenshots below. Tried one more time but on 2.15 - the same. 

![image](https://github.com/user-attachments/assets/a893fc6a-bb67-4c55-a74a-3ea313019c19)
![image](https://github.com/user-attachments/assets/abc1b0b9-f156-4f9a-858d-191c3ccab34d)

**Comment by kjack9** [comment]
> Not sure if it is related. Tried to uninstall an amazon game on 2.14 - see result on screenshots below. Tried one more time but on 2.15 - the same.

I'm running into this same issue. A quick fix I found is to start a repair on the game. That will create the install directory. Then uninstall the game (even before the repair is done) and it works as expected.

**Comment by ZipperXT** [comment]
My workaround is to change the install path of the game to a new temporary folder that can be deleted.  Then uninstall the game.  The game will be uninstalled and the folder you chose will be deleted.
