### ISSUE TITLE
Crashing while Downloading Wine in MacOs

### ISSUE THREAD

**Issue by iammohan01** [Heroic-Games-Launcher/HeroicGamesLauncher#3202]
I tried to download wine from wine manager , when the download completes Launcher getting crash 
Downloaded through Brew
OS : MacOs
version : Sonoma

### Add logs

```text
(10:53:02) INFO:    [WineDownloader]:   Removed wine version Wine-Crossover-latest succesfully.
(10:53:04) INFO:    [WineDownloader]:   Start installation of wine version Wine-Crossover-latest
(10:53:08) INFO:    [Backend]:          Downloaded: 11.41 MB / 175.5 MB  @4.56 MB/s (6.50%)
(10:53:10) INFO:    [Backend]:          Downloaded: 28.66 MB / 175.5 MB  @8.92 MB/s (16.33%)
(10:53:13) INFO:    [Backend]:          Downloaded: 53.9 MB / 175.5 MB  @8.48 MB/s (30.71%)
(10:53:15) INFO:    [Backend]:          Downloaded: 68.49 MB / 175.5 MB  @9.28 MB/s (39.03%)
(10:53:17) INFO:    [Backend]:          Downloaded: 85.39 MB / 175.5 MB  @8.77 MB/s (48.66%)
(10:53:19) INFO:    [Backend]:          Downloaded: 108.02 MB / 175.5 MB  @8.61 MB/s (61.55%)
(10:53:20) INFO:    [Backend]:          Downloaded: 118.87 MB / 175.5 MB  @8.96 MB/s (67.73%)
(10:53:21) INFO:    [Backend]:          Downloaded: 127.8 MB / 175.5 MB  @8.5 MB/s (72.82%)
(10:53:24) INFO:    [Backend]:          Downloaded: 148.97 MB / 175.5 MB  @8.46 MB/s (84.89%)
(10:53:25) INFO:    [Backend]:          Downloaded: 157.73 MB / 175.5 MB  @7.37 MB/s (89.88%)
(10:53:27) INFO:    [Backend]:          Downloaded: 172.59 MB / 175.5 MB  @8.85 MB/s (98.35%)
(10:53:28) INFO:    [DownloadManager]:  Downloader: Finished downloading https://github.com/Gcenx/winecx/releases/download/crossover-wine-23.0.1/wine-crossover-23.0.1-osx64.tar.xz
(10:53:28) INFO:    [DownloadManager]:  Downloader: Finished downloading https://github.com/Gcenx/winecx/releases/download/crossover-wine-23.0.1/wine-crossover-23.0.1-osx64.tar.xz
(10:53:28) WARNING: [WineDownloader]:   No checksum provided. Download of Wine-Crossover-latest could be invalid!
```

### Steps to reproduce

1. Just Download wine from Wine Manager.
2. Wait until downloads 100%.
3. That's it launcher gets crashed.

### Expected behavior

A way to install wine in Mac Os

### Heroic Version

Latest Stable

### System Information

- OS : MacOs
- Version : Sonoma
- Model : Macbook Pro M1 16"

**Comment by kokosowy** [comment]
Same here, I'm going back to older version.

**Comment by arielj** [comment]
When you say it crashed, what exactly happens? heroic closes itself? the ui breaks? an error appears? crashing can mean different things

**Comment by vaivars** [comment]
When starting the installation for any of the wine releases, it successfully gets to 100% and then the launcher immediately exits and the report to mac pops up (content attached). 
Restarting the launcher, the wine release shows up as "downloaded" with 0 bytes. 

[heroic-report.json](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/files/13260328/heroic-report.json)

**Comment by arielj** [comment]
Can you all confirm if you are using an M1/2 chip? I can't reproduce this on an Intel Mac, so maybe it's something only on the arm architecture

**Comment by vaivars** [comment]
> Can you all confirm if you are using an M1/2 chip? I can't reproduce this on an Intel Mac, so maybe it's something only on the arm architecture

Yes, M1/Sonoma

**Comment by Nocccer** [comment]
I have the feeling it has something todo with the unzip package we use.

**Comment by urdanetahd** [comment]
Same here. The app crashes when starting the download of any version of Wine. MBP M1 Pro. Sonoma 14.2 (Beta)

**Comment by alokdhir** [comment]
Me too -- M2 Ultra Studio, Sonoma 14.1

**Comment by flavioislima** [comment]
Probably related with the decompress package. Although it was compiled to ARM so should work.
So will need to investigate and maybe get back to the old methods on macOS.

**Comment by MikeyTheHobo** [comment]
Still not working on 14.2 Beta 2 on M1

**Comment by flavioislima** [comment]
> Still not working on 14.2 Beta 2 on M1

On my branch?

**Comment by markraub** [comment]
Looks like you can work around this atm:
- reopen heroic after it crashes
- go into wine manager, re-download the version that crashed before
- it should now show the folder/X options, open the folder
- one folder up is the tar file for the wine version you need. Untar it, and move it into the folder for the version you want! 


This issue is also causing heroic to not download a default wine version when you install it the first time. It thinks it grabbed 8.18 automatically, but it's just making the folder and leaving it empty. 


I'm on an M3 Pro MBP.

**Comment by zaubara** [comment]
> > Still not working on 14.2 Beta 2 on M1
> 
> On my branch?

I just built your branch locally, can confirm your fix works :)

**Comment by madr7d** [comment]
Can somebody explain me how to fix it ? I don't understand how to get the fix lmao (I'm on GitHub since recently). I have the exact same issue. Thanks !
