### ISSUE TITLE
New update introduced problems with right-to-left languages.

### ISSUE THREAD

**Issue by Doods0** [Heroic-Games-Launcher/HeroicGamesLauncher#3204]
### Describe the bug

There are visual bugs on the upper left corner of the game view screen.

1- Two buttons sticking too close to each other.
2- The menu going in the wrong direction.
3- A button's texture is overlapping another's.
4- a weird horizontal scroll bar appears below the 'Play Now' button whenever I tough that hamburger menu

### Add logs

```text
(10:29:54) INFO:    [Legendary]:        Legendary location: /tmp/.mount_HGL.Ap7rgQAu/resources/app.asar.unpacked/build/bin/linux/legendary
(10:29:54) INFO:    [Gog]:              GOGDL location: /tmp/.mount_HGL.Ap7rgQAu/resources/app.asar.unpacked/build/bin/linux/gogdl
(10:29:54) INFO:    [Connection]:       Connectivity: check-online
(10:29:54) INFO:    [Connection]:       Pinging external endpoints
(10:29:54) INFO:    [Backend]:          DRM module staus {
  "oimompecagnajdejgnnjijobebaeigek": {
    "name": "Widevine Content Decryption Module",
    "status": "new",
    "version": "4.10.2710.0"
  }
}
(10:29:55) WARNING: [Backend]:          Failed to register protocol with OS.
(10:29:55) INFO:    [Connection]:       Connectivity: online
(10:29:55) ERROR:   [Gog]:              Unable to syncQueued playtime, userData not present
(10:29:55) INFO:    [Backend]:          AreWeAntiCheatYet data downloaded
(10:29:56) INFO:    [Backend]:          Loading Screen Ready
(10:29:56) INFO:    [Frontend]:         Refreshing undefined Library
(10:29:56) WARNING: [Backend]:          refresh not implemented on Sideload Library Manager
(10:29:56) INFO:    [Legendary]:        Refreshing library...
(10:29:56) INFO:    [Legendary]:        Refreshing Epic Games...
(10:29:56) INFO:    [Legendary]:        Game list updated, got 45 games & DLCs
(10:29:56) INFO:    [Backend]:          Frontend Ready
(10:29:56) WARNING: [Backend]:          listUpdateableGames not implemented on Sideload Library Manager
(10:29:56) INFO:    [Gog]:              Found 0 game(s) to update
(10:29:56) INFO:    [Backend]:          Checking for new Heroic Updates
(10:29:56) INFO:    [Backend]:          Checking for current version changelog
(10:29:56) INFO:    [Legendary]:        Running command: LEGENDARY_CONFIG_PATH=/home/doods/.config/heroic/legendaryConfig/legendary /tmp/.mount_HGL.Ap7rgQAu/resources/app.asar.unpacked/build/bin/linux/legendary --version
(10:29:56) INFO:    [Gog]:              Running command: /tmp/.mount_HGL.Ap7rgQAu/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/doods/.config/heroic/gog_store/auth.json --version
(10:29:56) INFO:    [Nile]:             Running command: NILE_CONFIG_PATH=/home/doods/.config/heroic/nile_config /tmp/.mount_HGL.Ap7rgQAu/resources/app.asar.unpacked/build/bin/linux/nile --version
(10:29:56) INFO:    [Legendary]:        Checking for game updates: LEGENDARY_CONFIG_PATH=/home/doods/.config/heroic/legendaryConfig/legendary /tmp/.mount_HGL.Ap7rgQAu/resources/app.asar.unpacked/build/bin/linux/legendary list --third-party
(10:29:56) INFO:    [Legendary]:        Running command: LEGENDARY_CONFIG_PATH=/home/doods/.config/heroic/legendaryConfig/legendary /tmp/.mount_HGL.Ap7rgQAu/resources/app.asar.unpacked/build/bin/linux/legendary list --third-party
(10:29:57) INFO:    [Backend]:          
System Information:
CPU: 4x Intel(R) Core(TM) i5-7500 CPU @ 3.40GHz
Memory: 8.19 GB (used: 1.76 GB)
GPUs:
  GPU 0:
    Name: Intel Corporation HD Graphics 630
    IDs: D=5912 V=8086 SD=829d SV=103c
    Driver: i915
OS: Pop!_OS 22.04 LTS (linux)

The current system is not a Steam Deck
We are not running inside a Flatpak container

Software Versions:
  Heroic: 2.10.0 Jewelry Bonney
  Legendary: 0.20.33 Undue Alarm
  gogdl: 0.7.3
  Nile: 1.0.0 Jonathan Joestar

(10:29:57) INFO:    [Winetricks]:       Downloading Winetricks
(10:29:59) DEBUG:   [Legendary]:        Update is available for 4f272a49a39742b795d63e1f483a7c7d: 1.4.98.5144.39.win64 != 1.7.101.win64
(10:29:59) INFO:    [Legendary]:        Found 1 game to update
(10:30:00) INFO:    [WineDownloader]:   Updating wine versions info
(10:30:00) INFO:    [WineDownloader]:   Fetching upstream information...
(10:30:01) INFO:    [Backend]:          Starting the Download Queue
(10:30:01) INFO:    [WineDownloader]:   wine versions updated
```

### Steps to reproduce

Open any game in your library while using a right-to-left language.

### Expected behavior

Exactly what happens in older versions.

### Screenshots

![Screenshot from 2023-11-05 10-22-04](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/assets/80251531/4506f71b-566b-4637-b94e-68eddb2f9f40)

### Heroic Version

Latest Stable

### System Information

Pop!_OS 22.04 running on the gnome-session package on Wayland.
1366x768 resolution.
Using the self updating Appimage, version '2.10.0'.

: 4x Intel(R) Core(TM) i5-7500 CPU @ 3.40GHz
Memory: 8.19 GB (used: 2.21 GB)
GPUs:
  GPU 0:
    Name: Intel Corporation HD Graphics 630
    IDs: D=5912 V=8086 SD=829d SV=103c
    Driver: i915
OS: Pop!_OS 22.04 LTS (linux)

The current system is not a Steam Deck
We are not running inside a Flatpak container

Software Versions:
  Heroic: 2.10.0 Jewelry Bonney
  Legendary: 0.20.33 Undue Alarm
  gogdl: 0.7.3
  Nile: 1.0.0 Jonathan Joestar

### Additional information

Unrelated, but I already opened an issue to why not:

* The bug report menu on Github still claims the latest version is '2.9.2'.

* The shrinking of the screen in which you choose the prefix and installation path when downloading a game are - Intentionally - too small to show full paths - for installation and prefix choosing.![Screenshot from 2023-11-05 10-23-02](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/assets/80251531/9f025799-ca9c-4018-9104-fe3e8c8f2cde)

* Something seems to be wrong the the log menu in the setting in all languages, cutting the names of games with average sized named and awkwardly placing the log box next to them, in addition to the weird white box on the bottom left corner of the log box.![Screenshot from 2023-11-05 10-52-32](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/assets/80251531/49d947bc-0c09-4a78-960a-23fec6acef0a)

* The game configure menu - while highly improved - has became too small to  be easily legible ![Screenshot from 2023-11-05 10-51-18](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/assets/80251531/6a498f69-863e-4996-9f09-c39b86d7a9b0)

**Comment by flavioislima** [comment]
Probably more electron 27 issues @arielj

**Comment by arielj** [comment]
> Probably more electron 27 issues @arielj

I think most are not caused by the electron:
- install dialog too narrow (we could make it wider by default)
- settings dialog to short (we could make it taller by default)
- the ones about the log screen are kinda intentional (we have to put some limit to the length of the titles, the layout is like that intentionally)
- the github bug template is related to the automatic PR after a release (I can't merge it)
- the buttons and scroll in the game page sounds more like an issue with the refactor for the redesign

I'll check most of this today probably
