### ISSUE TITLE
Legendary Error running command

### ISSUE THREAD

**Issue by CundC** [Heroic-Games-Launcher/HeroicGamesLauncher#3205]
### Describe the bug

I start my Heroic Game Launcher and suddenly a error Message pops up with the following:

Error running command "LEGENDARY_CONFIG_PATH=C:\Users\CundC\AppData\Roaming\heroic\legendaryConfig\legendary C:\Users\CundC\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\legendary --version": Error: spawn legendary ENOENT
at Process.onexit (node:internal/child_process:283:19)
at onErrorNT (node:internal/child_process:476:16)
at process.processTicksAndRejections (node:internal/process/task_queues:82:21)

Also this error is always coming and when i try to login in my Epic Account throught the App, i get the same error again.

### Add logs

```text
(13:49:58) INFO:    [Legendary]:        Legendary location: C:\Users\CundC\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\legendary
(13:49:58) INFO:    [Gog]:              GOGDL location: C:\Users\CundC\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\gogdl
(13:49:58) INFO:    [Connection]:       Connectivity: check-online
(13:49:58) INFO:    [Connection]:       Pinging external endpoints
(13:49:58) INFO:    [Backend]:          DRM module staus {
  "neifaoindggfcjicffkgpmnlppeffabd": {
    "name": "Google Widevine Windows CDM",
    "status": "new",
    "version": "1.0.2738.0"
  },
  "oimompecagnajdejgnnjijobebaeigek": {
    "name": "Widevine Content Decryption Module",
    "status": "new",
    "version": "4.10.2710.0"
  }
}
(13:49:58) WARNING: [Backend]:          Protocol already registered.
(13:49:58) INFO:    [Connection]:       Connectivity: online
(13:49:58) INFO:    [Backend]:          User Not Found, removing it from Store
(13:49:58) ERROR:   [Gog]:              Unable to syncQueued playtime, userData not present
(13:49:59) INFO:    [Backend]:          Loading Screen Ready
(13:49:59) INFO:    [Backend]:          Frontend Ready
(13:49:59) INFO:    [Backend]:          Checking for new Heroic Updates
(13:49:59) INFO:    [Backend]:          Checking for current version changelog
(13:49:59) INFO:    [Backend]:          VCRuntime is installed
(13:50:04) INFO:    [Backend]:          Starting the Download Queue
(13:50:13) INFO:    [Legendary]:        Running command: LEGENDARY_CONFIG_PATH=C:\Users\CundC\AppData\Roaming\heroic\legendaryConfig\legendary C:\Users\CundC\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\legendary --version
(13:50:13) INFO:    [Gog]:              Running command: C:\Users\CundC\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\gogdl --auth-config-path C:\Users\CundC\AppData\Roaming\heroic\gog_store\auth.json --version
(13:50:13) INFO:    [Nile]:             Running command: NILE_CONFIG_PATH=C:\Users\CundC\AppData\Roaming\heroic\nile_config C:\Users\CundC\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\nile --version
(13:50:13) ERROR:   [Legendary]:        Error running command "LEGENDARY_CONFIG_PATH=C:\Users\CundC\AppData\Roaming\heroic\legendaryConfig\legendary C:\Users\CundC\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\legendary --version": Error: spawn legendary ENOENT
    at Process.onexit (node:internal/child_process:283:19)
    at onErrorNT (node:internal/child_process:476:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
(13:50:14) INFO:    [Backend]:          
System Information:
CPU: 16x AMD Ryzen 7 3700X 8-Core Processor             
Memory: 34.28 GB (used: 15.75 GB)
GPUs:
  GPU 0:
    Name: Advanced Micro Devices, Inc. [AMD/ATI] Navi 21 [Radeon RX 6800/6800 XT / 6900 XT]
    IDs: D=73bf V=1002 SD=232a SV=1458
    Driver: 31.0.22017.3004
OS: Microsoft Windows 11 Pro 10.0.22621 (win32)

The current system is not a Steam Deck
We are not running inside a Flatpak container

Software Versions:
  Heroic: 2.10.0 Jewelry Bonney
  Legendary: invalid
  gogdl: 0.7.3
  Nile: 1.0.0 Jonathan Joestar
```

### Steps to reproduce

1. Go to "Login"
2. Click on 'Epic Game Login'
3. Login

### Expected behavior

That i login in my Epic Account and install my games.

### Screenshots

![grafik](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/assets/53524208/07885dc3-df1b-4dd6-8719-88fa364746af)

### Heroic Version

Latest Stable

### System Information

CPU: 16x AMD Ryzen 7 3700X 8-Core Processor             
Memory: 34.28 GB (used: 15.69 GB)
GPUs:
  GPU 0:
    Name: Advanced Micro Devices, Inc. [AMD/ATI] Navi 21 [Radeon RX 6800/6800 XT / 6900 XT]
    IDs: D=73bf V=1002 SD=232a SV=1458
    Driver: 31.0.22017.3004
OS: Microsoft Windows 11 Pro 10.0.22621 (win32)

The current system is not a Steam Deck
We are not running inside a Flatpak container

Software Versions:
  Heroic: 2.10.0 Jewelry Bonney
  Legendary: invalid
  gogdl: 0.7.3
  Nile: 1.0.0 Jonathan Joestar

**Comment by Kisty** [comment]
Same issue here

**Comment by HazardousBackup** [comment]
I got the same error message and reverting back to 2.9.2 fixed it.
However, I now think that may be because it (re)installed the old version of Legendary.

I noticed that Windows Defender seems to have quarantined Legendary presumably before I first got the error. I can't be certain it was before because it didn't tell me when it happened and I found out later.

**Comment by user0753** [comment]
> I noticed that Windows Defender seems to have quarantined Legendary presumably before I first got the error. I can't be certain it was before because it didn't tell me when it happened and I found out later.

This may be the root of the problem, got a notification from Defender saying it quarantined legendary.exe as soon as I tried launching an Epic Games based title. The detection was "Trojan:Win32/Wacatac.B!ml" which I've seen before when it's falsely flagged files. I'm sure it's the same situation here, but some additional confirmation would be nice. Only started happening after I updated from 2.9.2 to 2.10.0.

**Comment by CundC** [comment]
Yes it was my Antivirus Program, dont know why it was removing it while using it. I didnt got any notification about it but now its working after i select the folder as a exeption of the scan.

**Comment by user0753** [comment]
I've submitted it to Microsoft for false positive analysis. Somehow I'm getting a detection locally while Microsoft's portal shows none even though I've got the same security intel version they do. Either way, hopefully they can resolve this.

**Comment by AyoungDukie** [comment]
Just in case the additional info helps, this is how Windows Defender flagged it for me (installed via scoop package manager):
![image](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/assets/5449443/7547bebe-85d7-425d-a78d-f8d3bb47ef99)

**Comment by user0753** [comment]
> I've submitted it to Microsoft for false positive analysis. Hopefully they can resolve this.

They've responded surprisingly fast. They've determined it to indeed be a false positive and removed it from detection. No more detection on my end after running protection/security intelligence updates within Windows Defender.

```
At this time, the submitted files do not meet our criteria for malware or potentially unwanted applications. The detection has been removed. Please follow the steps below to clear cached detections and obtain the latest malware definitions.

     1. Open command prompt as administrator and change directory to c:\Program Files\Windows Defender 
     2. Run “MpCmdRun.exe -removedefinitions -dynamicsignatures”
     3. Run "MpCmdRun.exe -SignatureUpdate"

Alternatively, the latest definition is available for download here: https://docs.microsoft.com/microsoft-365/security/defender-endpoint/manage-updates-baselines-microsoft-defender-antivirus
```

**Comment by HazardousBackup** [comment]
I let Heroic update to the latest version after giving Windows Defender a few days and it hasn't had any more issues.
This probably can be closed as just a false positive from WD killing Legendary.

**Comment by Kisty** [comment]
Likewise. It's fixed now after reinstalling Heroic here.

**Comment by arielj** [comment]
I'm closing this since the issue was Windows Defender flagging legendary.exe with a false positive.

Updating Windows Defender prevents that from happening, then Heroic can be reinstalled to restore that file ir can be downloaded from https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/tree/v2.10.0/public/bin/win32
