### ISSUE TITLE
Ability to download normal Proton versions

### ISSUE THREAD

**Issue by AtFreezingPoint** [Heroic-Games-Launcher/HeroicGamesLauncher#3211]
### Feature description

I believe being able to download normal Proton versions and non-GE variants would be pretty nice.

### Alternatives

Explain why not possible

**Comment by Nocccer** [comment]
You can download proton via steam. Proton is only made for steam games and not for no-steam games. So Wine-ge is always the best option. We just made proton-ge available because it can be download from github and should be prefered over proton.

Proton is not really available via github.

**Comment by AtFreezingPoint** [comment]
> You can download proton via steam. Proton is only made for steam games and not for no-steam games. So Wine-ge is always the best option. We just made proton-ge available because it can be download from github and should be prefered over proton.
> 
> Proton is not really available via github.

What diffs would you say Proton & Wine-GE have? Never tried Wine-GE...
