### ISSUE TITLE
Error Trying To Run Epic Game (Stumble Guys)

### ISSUE THREAD

**Issue by BaileyIsUp** [Heroic-Games-Launcher/HeroicGamesLauncher#3214]
### Describe the bug

The bug stops running of the the game fall guys

### Add logs

```text
An error has occurred! Try to Logout and Login on your Epic account.
[cli] INFO: Logging in...
[Core] INFO: Trying to re-use existing login session...[cli] INFO: Checking for updates...[Core] INFO: Getting authentication token...[cli] INFO: Launching 0a2d9f6403244d12969e11da6713137b...Traceback (most recent call last):
File "legendary/cli.py", line 3148, in <module>
File "legendary/cli.py", line 3063, in main
File "legendary/cli.py", line 706, in launch_gameFile "subprocess.py", line 951, in __init__
File "subprocess.py", line 1837, in _execute_child
FileNotFoundError: [Errno 2] No such file or directory: '/home/bailey/.config/heroic/tools/wine/Wine-GE-latest/bin/wine'
[2884] Failed to execute script 'cli' due to unhandled exception!
```

### Steps to reproduce

1. Go to 'Library'
2. Click on 'fall guys'
3. See error

### Expected behavior

I expected the game to run

### Screenshots

![Screenshot 2023-11-06 11 21 28 PM](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/assets/150053772/e7d6cdbf-4d80-4e1d-b6d8-e136af97f937)

### Heroic Version

Latest Stable

### System Information

- OS Linux (debian 11)

**Comment by arielj** [comment]
Go to our discord, go to the `#-support` channel. Read the pinned `Read me first` message and follow all the instructions (specially the one about installing wine dependencies)

if you still have problems, create a thread there (the github issues are for errors in heroic itself)
