### ISSUE TITLE
Missing files in game: The Witcher 3 (GOG)

### ISSUE THREAD

**Issue by aidalgol** [Heroic-Games-Launcher/HeroicGamesLauncher#3226]
### Describe the bug

The Witcher 3 installed via Heroic is missing many textures.

### Add logs

(Too large to paste.)
[1495134320-lastPlay.log](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/files/13306249/1495134320-lastPlay.log)
[1495134320.log](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/files/13315596/1495134320.log)

### Steps to reproduce

1. Install Witcher 3 from GOG through Heroic
   (This may stall until Heroic is restarted, multiple times.)
2. Launch game
3. The starting area will have missing textures.

### Expected behavior

All game files to be in the installed game directory.

### Screenshots

![screenshot](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/assets/2313201/656d57f1-2602-404b-9412-2b9d6d2105f9)

### Heroic Version

Latest Stable

### System Information

CPU: 32x AMD Ryzen 9 3950X 16-Core Processor
Memory: 33.6 GB (used: 23.19 GB)
GPUs:
  GPU 0:
    Name: NVIDIA Corporation GA102 [GeForce RTX 3080]
    IDs: D=2206 V=10de SD=87b0 SV=1043
    Driver: nvidia
OS: NixOS 23.11 (Tapir) (linux)

The current system is not a Steam Deck
We are not running inside a Flatpak container

Software Versions:
  Heroic: 2.10.0 Jewelry Bonney
  Legendary: 0.20.33 Undue Alarm
  gogdl: 0.7.3
  Nile: 1.0.0 Jonathan Joestar

## Directory listings
Output from `tree` command on the game folder installed via Heroic vs the unpacked GOG offline installer.
- [Via Heroic](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/files/13315602/tw3-heroic-tree.txt)
- [From GOG installer](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/files/13306202/tw3-goginst-tree.txt)

The missing texture are `.dds` files, and the only `.dds` file in the game folder installed via Heroic is `content/content0/hdr/hdr_calibration_screen.dds`.

The textures in-game look fine when running from the GOG installer unpack.

**Comment by lapastillaroja** [comment]
I'm having exactly the same visual problem since Heroic 2.9.2

**Comment by italoghost** [comment]
I am having the same issue: the download stops at 88% and never finishes. I paused and let it begin again. It now stops at 71%. Then it sudenly finishes the installation, but you it has the missing textures.

Trying to repair doesn't do anything.

**Comment by italoghost** [comment]
I downloaded the game through [this PR](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/pull/3020) and now it worked flawlessly!

**Comment by arielj** [comment]
This is fixed in the latest 2.13.0 release, closing
