### ISSUE TITLE
CRITICAL: Heroic deletes the wrong folder while removing partially downloaded games.

### ISSUE THREAD

**Issue by Zebouski** [Heroic-Games-Launcher/HeroicGamesLauncher#323]
**Describe the bug**
Folders with similar folder names as the selected installation folder, alongside said folder, are being deleted.

**To Reproduce**

1.
[zeb@zebArchDesktop ~]$ mkdir Games
[zeb@zebArchDesktop ~]$ touch Games/testing
[zeb@zebArchDesktop ~]$ ls Games
testing
[zeb@zebArchDesktop ~]$ mkdir "Games - Epic"
[zeb@zebArchDesktop ~]$ Heroic

2. Click on Settings
3. Set default installation path to '/home/youruser/Games - Epic'
4. Go to Library
5. Click a game that isn't installed
6. Make sure it says Install on /home/youruser/Games - Epic
7. Click Cancel, and then No on the keep data popup
8.
[zeb@zebArchDesktop ~]$ ls Games
ls: cannot access 'Games': No such file or directory
<Exit Status: 2>
[zeb@zebArchDesktop ~]$ 

9. Try not to cry over your deleted Games folder and all its stuff in it

**Screenshots**

**Desktop (please complete the following information):**

- OS: Arch Linux
- Version: Latest. aur/heroic-games-launcher-bin 1.5.7-1
- Game: Tony Hawk's Pro Skater 1+2
- Wine/Proton version:

**Additional context**
I replicated this bug on both NTFS and EXT4 filesystems

I named folders like this because I have a Games - Emulation and a Games - Steam right beside these two. those two folders were not harmed by this bug. Feels to me like this bug is due to a missing pair of "s somewhere.

**Comment by adityaruplaha** [comment]
I'm so sorry. This issue has been identified and fixed by #294. And you are right, it was due to improper escaping.

Just to be sure, can you build latest main and test?

**Comment by Zebouski** [comment]
Thanks for the quick response. I built from source and indeed the bug is fixed.

I didn't lose much, only a few games i didn't have backed up but nothing irreplaceable.

Hope y'all can get this released to distros asap so i'm the only one who gets hit by this :)

**Comment by adityaruplaha** [comment]
Yep we'll probably have to release a new version pretty soon.

**Comment by adityaruplaha** [comment]
1.5.8 should no longer have this issue.
