### ISSUE TITLE
Tiny cursor on my HiDPI display on GNOME Wayland with Flatpak Heroic Games Launcher

### ISSUE THREAD

**Issue by dariox86** [Heroic-Games-Launcher/HeroicGamesLauncher#3236]
### Describe the bug

On my HiDPI display set at 200% scaling, the cursor shrinks when hovering on Flatpak Heroic Games Launcher in GNOME Wayland. Heroic Games Launcher is started in Wayland mode using the parameters to avoid XWayland.

### Add logs

```text
I think no logs are necessary. The issue can be easily reproduced.
```

### Steps to reproduce

On GNOME Wayland with scaling set at 200% on a HiDPI display, launch Flatpak Heroic Games Launcher with the following command:
`
$ flatpak run --branch=stable --arch=x86_64 --command=heroic-run --file-forwarding com.heroicgameslauncher.hgl --ozone-platform-hint=auto --disable-features=WaylandFractionalScaleV1`

The cursor becomes tiny when hovering Heroic Games Launcher.

### Expected behavior

The cursor should stay the same size as when it is not hovering Heroic Games Launcher.

### Heroic Version

Latest Stable

### System Information

Parabola GNU/Linux-libre.

### Additional information

The problem goes away after issuing the following command:

`$ flatpak --user override --env=XCURSOR_PATH=/run/host/user-share/icons:/run/host/share/icons com.heroicgameslauncher.hgl`

I think [this bug report](https://github.com/flathub/com.mojang.Minecraft/pull/103) and the [related commit](https://github.com/flathub/com.mojang.Minecraft/pull/103/commits/d78eed1a38ada27c5b9c88b9c2ae6bba2ea20cd8) are relevant.

Steam has the same permission mentioned in the bug report.

**Comment by Kajot-dev** [comment]
I think this is not Heroic related but an upstream Chromium bug introduced in 116 and ported to Electron: https://bugs.chromium.org/p/chromium/issues/detail?id=1477948&q=cursor%20wayland&can=2

**Comment by arielj** [comment]
I imagine we have to close this since we can't really do anything. Eventually chromium will fix that, then electron, then we'll update the electron version, but we have no control over when the fix will actually happen.

**Comment by regs01** [comment]
For those who are looking for solution for X11 as well.
`ocs-url` (Pling, i.e. Gnome Look, Xfce Look, KDE Store etc) installs cursors into `~/.icons`, but `Flatpak` is looking for them in `~/.local/share/icons`. So just move or copy folders from `~/.icons` to `~/.local/share/icons`.
