### ISSUE TITLE
Rocket League no longer works after Arch updates

### ISSUE THREAD

**Issue by LiamDawe** [Heroic-Games-Launcher/HeroicGamesLauncher#324]
**Describe the bug**
Up until a day or so ago, Rocket League launched from Heroic worked perfectly. Now it tries launching, gives a black screen in some sort of almost-fullscreen window and just stays black.

**To Reproduce**
Try latest Arch with latest NVIDIA driver.

**Expected behavior**
It works?

**Screenshots**
![IMG_20210425_110827](https://user-images.githubusercontent.com/83223/115989532-bbe65f00-a5b6-11eb-8977-097eea1e1c16.jpg)

**Desktop (please complete the following information):**

- OS: Arch
- Wine/Proton version: tried it across Wine Lutris versions 6.4, 6.0, 5.7 and normal Wine 6.6 staging. All do exactly the same thing.

**Additional context**
Running Heroic in terminal gives very little useful output:

> [liam@liam-pc ~]$ '/home/liam/Downloads/heroic-1.5.7.AppImage'
> launching Sugar
> 
>  Launch Command:      /usr/bin/gamemoderun /tmp/.mount_heroic7FR5RL/resources/app.asar.unpacked/build/bin/legendary launch  Sugar  --wine '/home/liam/.local/share/lutris/runners/wine/lutris-6.4-x86_64/bin/wine64' --wine-prefix '/home/liam/.wine' 

[Sugar-lastPlay.log](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/files/6371887/Sugar-lastPlay.log)
Log seems confused too, states an old DXVK and then later the latest - which is it? Why is it saying multiple?

How can I track down the real cause? 

Have not tried reinstalling the game, in case there's an error we can find to fix that may be lost during reinstall.

**Comment by LiamDawe** [comment]
Okay I found the issue, it was DXVK and Heroic's handling of it.

My understanding is that it's supposed to update it for us right? That's what the "Auto Install/Update DXVK on Prefix" option is for right? But it seem genuinely like it gave me an old version, repeatedly. I just did a manual DXVK install into my main Staging 6.7 prefix - and now it boots as expected.

**Comment by flavioislima** [comment]
@LiamDawe I checked this and the Lutris DXVK, the one we use, was still at 1.4, so there is no issue about that. 
Heroic will always use the DXVK that is marked as Latest Release on the Lutris Repository.

**Comment by LiamDawe** [comment]
Uh, no. Lutris has lots of DXVK versions available, including much newer versions.

**Comment by flavioislima** [comment]
> Uh, no. Lutris has lots of DXVK versions available, including much newer versions.

Yeah, but Heroic will always use the Latest release that is the one they consider stable.
But ofc you can manually install new versions with winetricks or manually.

**Comment by LiamDawe** [comment]
You're right, spoke to Lutris dev, seems it's supposed to be a newer version.
