### ISSUE TITLE
Download progress in the taskbar [Windows]

### ISSUE THREAD

**Issue by revanmj** [Heroic-Games-Launcher/HeroicGamesLauncher#3250]
### Feature description

Display current download progress on Heroic icon in Windows taskbar (supported since Windows 7 up to 11).

Sample documentation:
C# Winforms: https://stackoverflow.com/questions/63383067/winforms-c-sharp-taskbar-progress-indicator-windows-10
Electron: https://www.electronjs.org/docs/latest/tutorial/progress-bar

**Comment by arielj** [comment]
There's actually a PR already implementing this https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/pull/3086

it needs some more testing (I tried it but some features only work on windows/mac) and resolve conflicts

**Comment by arielj** [comment]
Closing since the PR implementing this was merged. Will be included in the next release.
