### ISSUE TITLE
Games don't launch a second time

### ISSUE THREAD

**Issue by Gaemfreak** [Heroic-Games-Launcher/HeroicGamesLauncher#3289]
### Describe the bug

The first time I open Heroic and launch a game it works fine. The second time I try to relaunch the game during that first instance of Heroic being open, say I closed the game and came back later to play again, the game will not launch unless I restart Heroic.

This happens every time. When I open Heroic and go to my library, I get a "Cannot get game info" error. Refresh library does nothing. Restarting Heroic fixes it once until it breaks when trying to launch the game a second time.

### Add logs

```text
Heroic: (20:18:39) INFO:    [Backend]:          Heroic is already running, quitting this instance

Fortnite: 

System Info:
CPU: 16x AMD Ryzen 7 3700X 8-Core Processor             
Memory: 34.29 GB (used: 11.01 GB)
GPUs:
  GPU 0:
    Name: NVIDIA Corporation GA102 [GeForce RTX 3080]
    IDs: D=2206 V=10de SD=3885 SV=3842
    Driver: 546.01
OS: Microsoft Windows 11 Pro 10.0.22621 (win32)

The current system is not a Steam Deck
We are not running inside a Flatpak container

Software Versions:
  Heroic: 2.11.0 Kumachi
  Legendary: 0.20.33 Undue Alarm
  gogdl: 0.7.3
  Nile: 1.0.0 Jonathan Joestar

Game Settings: {
	"autoInstallDxvk": true,
	"autoInstallVkd3d": true,
	"preferSystemLibs": false,
	"enableEsync": true,
	"enableFsync": true,
	"nvidiaPrime": false,
	"enviromentOptions": [],
	"wrapperOptions": [],
	"showFps": false,
	"useGameMode": false,
	"language": ""
}

Game launched at: Sun Dec 03 2023 20:24:38 GMT-0800 (Pacific Standard Time)

Launch Command: HEROIC_APP_NAME=Fortnite HEROIC_APP_RUNNER=legendary HEROIC_APP_SOURCE=epic C:\Users\UserPC\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\legendary launch Fortnite --language en

Game Log:
An exception occurred when launching the game:
Error: EPERM: operation not permitted, open 'C:\Users\UserPC\AppData\Roaming\heroic\logs\2023-12-04T02_16_16-legendary.log'
    at Object.openSync (node:fs:603:3)
    at Object.func [as openSync] (node:electron/js2c/asar_bundle:2:2170)
    at Object.writeFileSync (node:fs:2324:35)
    at Object.appendFileSync (node:fs:2386:6)
    at callRunner (C:\Users\UserPC\AppData\Local\Programs\heroic\resources\app.asar\build\electron\main.52801ae1.js:95:913)
    at runRunnerCommand (C:\Users\UserPC\AppData\Local\Programs\heroic\resources\app.asar\build\electron\main.52801ae1.js:98:8771)
    at Module.launch$1 [as launch] (C:\Users\UserPC\AppData\Local\Programs\heroic\resources\app.asar\build\electron\main.52801ae1.js:81:25)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async C:\Users\UserPC\AppData\Local\Programs\heroic\resources\app.asar\build\electron\main.52801ae1.js:202:450
    at async WebContents.<anonymous> (node:electron/js2c/browser_init:2:90734)
```

### Steps to reproduce

1. Open Heroic
2. Launch Fortnite
3. Close Fortnite after playing for an hour
4. Try to open Fortnite again a little later
5. Fortnite doesn't launch.

### Expected behavior

1. Open Heroic.
2. Launch Fortnite.
3. Close Fortnite after playing for an hour.
4. Try to open Fortnite again a little later.
5. Fortnite does launch.

### Heroic Version

Latest Stable

### System Information

**Windows Info:** 

Edition	Windows 11 Pro
Version	22H2
Installed on	‎10/‎6/‎2022
OS build	22621.2715
Experience	Windows Feature Experience Pack 1000.22677.1000.0

**Hardware Info:**
Processor	AMD Ryzen 7 3700X 8-Core Processor                3.60 GHz
Installed RAM	32.0 GB
System type	64-bit operating system, x64-based processor
Pen and touch	No pen or touch input is available for this display

**Comment by vvirtues** [comment]
+1, can confirm. Going to the fortnite page gives heroic failed to load, clicking reset heroic works

**Comment by Gaemfreak** [comment]
> +1, can confirm. Going to the fortnite page gives heroic failed to load, clicking reset heroic works

I wish the reset heroic option worked for me :/ I press it and the UI elements for it flicker real quick and nothing happens.

**Comment by Tommy2678** [comment]
+1

**Comment by vvirtues** [comment]
sometimes clicking reset would close it but since I have exit to tray it just sits in tray
I have to either click quit and it reopens itself or quit from tray and open it manually

**Comment by arielj** [comment]
curious, are you all windows users? trying to understand if there's a pattern to debug the issue

**Comment by vvirtues** [comment]
> curious, are you all windows users? trying to understand if there's a pattern to debug the issue

Yes, OP and I am, judging from the logs

**Comment by arielj** [comment]
I see this there in the logs

```
Error: EPERM: operation not permitted, open 'C:\Users\UserPC\AppData\Roaming\heroic\logs\2023-12-04T02_16_16-legendary.log'
```

does the file mentioned in the log exists?

I just installed windows in a virtual machine and I can run a game twice, seems to be a permissions issue?

**Comment by arielj** [comment]
some questions:
- is it always the same game? or happens with any game?
- when the error happens, does the file mentioned in the error exist?
- if you go to that folder before running the game, do you see any change in the files before and after the first run?

**Comment by Gaemfreak** [comment]
> I see this there in the logs
> 
> ```
> Error: EPERM: operation not permitted, open 'C:\Users\UserPC\AppData\Roaming\heroic\logs\2023-12-04T02_16_16-legendary.log'
> ```
> 
> does the file mentioned in the log exists?
> 
> I just installed windows in a virtual machine and I can run a game twice, seems to be a permissions issue?

I don't have that exact log but I have others with the same "legendary.log" name.

**Comment by vvirtues** [comment]
I dont get this all the time, sometimes it works  flawlessly, other times even launching other games doesnt work

**Comment by vvirtues** [comment]
I'll post logs once I get it again

**Comment by dplynx** [comment]
I also have this problem, also a Windows user. Launching games from Steam will apparently do nothing, then I launch a Heroic and click clear cache and restart and it will work for one more launch.
