### ISSUE TITLE
SID registration window doesn't appear on 1.5.8 fresh installs.

### ISSUE THREAD

**Issue by dubigrasu** [Heroic-Games-Launcher/HeroicGamesLauncher#329]
On new 1.5.8 installations (with _.config/heroic_ & _.config/legendary_ deleted) the initial SID window doesn't appear. I can see briefly the spinning wheel and then the GUI remains blank.
The terminal displays:
```
Protocol already registered.
Updating DXVK to: dxvk-1.4.6
downloaded DXVK
extracting DXVK
DXVK updated!
```
Tested the deb package and the appimage.

The previous version 1.5.7 behaves normally, and if I add the SID number and _only then_ update to 1.5.8, then the GUI starts working.

Ubuntu 18.04
Gnome

**Comment by adityaruplaha** [comment]
Oh come on I thought I fixed this bug.

Anything on the log?

**Comment by dubigrasu** [comment]
Can't seem to find any kind of logs, except what it says in the terminal mentioned above,

**Comment by iWeaker4you** [comment]
Yep, i confirm that problem. 
![image](https://user-images.githubusercontent.com/49424816/116127181-61afd180-a67c-11eb-892f-43389b192f5e.png)

**Comment by mrmcsalad** [comment]
Yeah I have the same issue:
Protocol already registered.

I just installed it from source on Arch Linux (since the AUR is down at the moment).

**Comment by adityaruplaha** [comment]
We're looking into the issue, hang tight. 

Also you can login with legendary and this should work.

**Comment by adityaruplaha** [comment]
I've been unable to reproduce this issue when only the legendary config has been deleted. So it's probably something to do with the config refactor. I'm looking into it.

**Comment by adityaruplaha** [comment]
> "Failed to register protocol with OS"

Nah that should be fine.
