### ISSUE TITLE
Add link to Discord in the logs window

### ISSUE THREAD

**Issue by pawamoy** [Heroic-Games-Launcher/HeroicGamesLauncher#3296]
### Describe the bug

When I click on "Report a problem running this game", the logs window tells me to "Join our Discord", though it doesn't give me a link to the server, so I typed "heroic discord" on duckduckgo and ended up on the e-sports Heroic Discord server, not the Heroic Games Launcher one. It was a bit confusing. Maybe you could add such a link in the message above the logs?

### Add logs

```text
N/A
```

### Steps to reproduce

Click on the "Report a problem running this game" button.

### Expected behavior

A link to the Discord server.

### Heroic Version

Latest Stable

### System Information

- OS: Arch

**Comment by pawamoy** [comment]
Sorry for marking this as a bug. Feature request could have been better? Not sure. Not sure either where this would have fit on the Discord server. Feel free to close and track elsewhere :slightly_smiling_face:

**Comment by hashkar123** [comment]
It sounds like a bug I could fix.
I'll try to look into it.
