### ISSUE TITLE
Broken link in the FAQ: https://heroicgameslauncher.com/faq

### ISSUE THREAD

**Issue by pawamoy** [Heroic-Games-Launcher/HeroicGamesLauncher#3297]
### Describe the bug

> My game is not working with Heroic. What should I do?
If you are having trouble running a game with Heroic, you can: Check the general documentation for troubleshooting and workarounds at this link: https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/wiki. This resource may contain information that can help you resolve your issue. 

That wiki link gives a 404, because the dot at the end is part of the URL.

### Add logs

```text
N/A
```

### Steps to reproduce

- Go to https://heroicgameslauncher.com/faq
- Click on the wiki link in the `My game is not working with Heroic. What should I do?` section

### Expected behavior

Working link.

### Heroic Version

Latest Stable

### System Information

- OS: Arch

**Comment by Sasikuttan2163** [comment]
I've submitted a [pull request](https://github.com/Heroic-Games-Launcher/heroic-website/pull/15) in the heroic-website repo to fix this issue.

**Comment by Sasikuttan2163** [comment]
The changes were merged, you can close this issue now

**Comment by pawamoy** [comment]
Thanks a lot!
