### ISSUE TITLE
Black screen on Linux Mint 21.2 (.deb)

### ISSUE THREAD

**Issue by pekumbe** [Heroic-Games-Launcher/HeroicGamesLauncher#3298]
### Describe the bug

Hello!
The last two versions of Heroic are giving a **black screen** when starting the application. It appears that the layout is not rendering correctly. It is still possible to navigate through the Heroic menus, but nothing appears correctly.
In the previous version this had happened once and then returned normally. I suspect this happened after I messed with the theme options, but I switched back to the default theme after the first time it happened.
Below is a screenshot of Heroic 2.11.0 opened, .deb version.

### Add logs

```text
Nothing to add
```

### Steps to reproduce

2. Click on '...'
3. Scroll down to '...'

### Expected behavior

It appears that the layout is not rendering correctly. It is still possible to navigate through the Heroic menus, but nothing appears correctly.

### Screenshots

![Captura de tela de 2023-12-06 23-29-33](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/assets/128752518/2d0cb0fa-ec16-4d72-97ea-5a602f664f5a)

### Heroic Version

Latest Stable

### System Information

![Captura de tela de 2023-12-06 23-28-52](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/assets/128752518/51f78149-80ce-4cc0-b360-e690875753dc)

**Comment by arielj** [comment]
check this issue, especially the comment about clearing the gpu cache https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/issues/3284#issuecomment-1837483667

**Comment by pekumbe** [comment]
Thanks, I'll delete it. I searched for "black screen" and that didn't appear.
