### ISSUE TITLE
Refresh library hangs

### ISSUE THREAD

**Issue by warriormaster12** [Heroic-Games-Launcher/HeroicGamesLauncher#330]
**Describe the bug**
Basically when I click to "refresh library" the application hangs in the this loop. I've tried to fix the issue by deleting .config/heroic folder but that only made the situation worse. The solution to this issue was to downgrade to 1.5.7.

**To Reproduce**

1. Go to games library page
2. Click on drop-down menu and select "refresh library"
3. See error

**Expected behavior**
Update games' library without hanging.

**Screenshots**
![image](https://user-images.githubusercontent.com/33091666/116210681-c1c17900-a74b-11eb-8b50-9b285a1e3e5e.png)

**Desktop (please complete the following information):**

- OS: KDE Neon 20.04lts
- Application packaging: Appimage

**Comment by adityaruplaha** [comment]
Unable to reproduce. It takes a minute or two, but it works for me.

**Comment by warriormaster12** [comment]
I tried 1.5.9 and still it hangs. I just tried to delete .config/heroic folder to see if the application will throw me into the login screen but even fails to do that. In 1.5.7 I get to the login screen instantly.

**Comment by flavioislima** [comment]
@warriormaster12 try this version please: https://drive.google.com/file/d/1JL5Sln81-Ae2FJVBwnZcaNFYQus7C3Z0/view?usp=sharing
