### ISSUE TITLE
"Error: spawn free EACCES"

### ISSUE THREAD

**Issue by axdvgnj1234** [Heroic-Games-Launcher/HeroicGamesLauncher#3313]
### Describe the bug

IDK

### Add logs

```text
Uncaught Exception occured!
Error:
A uncaught exception occured:
Error: spawn free EACCES
Report the exception on our Github repository.
```

### Steps to reproduce

2. Click on '...'
3. Scroll down to '...'

### Expected behavior

NON

### Screenshots

NON

### Heroic Version

Latest Stable

### System Information

- OS [e. g. "Ubuntu"]:

**Comment by CommandMC** [comment]
I'm pretty sure this is an issue with the Snap package

**Comment by hakuario** [comment]
Hello. Maybe it adds my particular experience when installing. When installing from "Ubuntu software" I had the error when opening the application. Then uninstall and download installer from github and install from terminal. When I opened the application the problem no longer occurred.

**Comment by bwstandard** [comment]
I get this as well. I used the Snap package. Will try installer from GH

**Comment by Finn090** [comment]
I currently have the same problem.
I installed from Ubuntu "Apps" and when I click on "Log in" I get the same error message.

I am running Ubuntu 24.04

**Comment by arielj** [comment]
Don't use the snap package from the ubuntu store, it's broken and outdated (we want to remove it from the app store)

use flatpak, or deb, or appimage instead

**Comment by Finn090** [comment]
Thank you for your comment. I am currently testing the deb package.

**Comment by arielj** [comment]
Closing this. It's an issue with the snap package and should not be used.
