### ISSUE TITLE
[macOS]Considering adding msync support for mac users

### ISSUE THREAD

**Issue by Coulin9** [Heroic-Games-Launcher/HeroicGamesLauncher#3315]
### Feature description

I noticed that Wine-9.0-rc1 has added msync support,so is it possible to open msync in the game settings like opening esync?
Msync can greatly improve the game experience.

**Comment by Coulin9** [comment]
> > I noticed that Wine-9.0-rc1 has added msync support
> 
> That’s inaccurate, I’ve only applied msync patchset to wine-staging (since 8.18), the patchset is _not_ applied to wine-devel packages.

Yeah,my mistake.I mean the latest staging packages.
I can only turn on msync by setting environment variables. I think adding a switch is more user-friendly than configuring environment variables.
The switch can be shown when the user selects the wine-staging packages.This can also remind users that this is a package which support msync.

**Comment by theaspirational** [comment]
how to turn on msync by setting environment variables? I am using whisky bottle prefix and msync is checked in whisky settings. but i don't know if it works when i run gta v through heroic. Thx

**Comment by Coulin9** [comment]
> how to turn on msync by setting environment variables? I am using whisky bottle prefix and msync is checked in whisky settings. but i don't know if it works when i run gta v through heroic. Thx

Maybe you can check the game boot log to see if msync is enabled

**Comment by LeaveNhA** [comment]
I wanna get some log with WINEDEBUG="+msync" but, where is the log going I don't get it.

**Comment by flavioislima** [comment]
Per https://github.com/marzent/wine-msync we would just need to copy/paste the ESYNC setting that we have today and use the `WINEMSYNC=1` environmental variable when it's enabled.

**Comment by flavioislima** [comment]
> > Per https://github.com/marzent/wine-msync we would just need to copy/paste the ESYNC setting that we have today and use the `WINEMSYNC=1` environmental variable when it's enabled.
> 
> Actually need to set `WINEEYSNC=1` & `WINEMSYNC=1` due to a D3DMetal bug

Perfect, did not know that. Thanks for the info!

**Comment by flavioislima** [comment]
Closing this one since it was implemented by #3630
