### ISSUE TITLE
Add support for GoG Rollback feature

### ISSUE THREAD

**Issue by Alex0007** [Heroic-Games-Launcher/HeroicGamesLauncher#3318]
### Feature description

GoG rollback feature description: https://docs.gog.com/gc-rollback/

I'm not sure if it's possible to implement in side client, but it is a nice feature to have. 

For example some games [are only working](https://www.gog.com/forum/wreckfest/solve_problem_multiplayer_inaccessible_different_version_than_steam/page1) on previous versions, which are unavailable for download in Heroic Launcher

**Comment by imLinguin** [comment]
Supported by #3020

**Comment by arielj** [comment]
Closing, latest 2.13.0 release includes this feature
