### ISSUE TITLE
Heroic just lauches up blank

### ISSUE THREAD

**Issue by Brotatochip0919** [Heroic-Games-Launcher/HeroicGamesLauncher#3319]
### Describe the bug

So when heroic launches up the entire UI is just blank. All the elements on the start page seem to work but obviously I can't see them and they are kinda glitchy as the UI on the thing I'm hovering on will pop in for a seck and then just go away. I can still launch games through the taskbar but otherwise I have not been able to fix this. I have tried to reinstall but that didn't work and as the start screen is blank I can't paste my logs so if someone knows a alternative way to paste logs or just have a solution in general.

### Add logs

```text
Can't pase logs right now,, help would be appreciated :)
```

### Steps to reproduce

1. Launch Heroic

(sorry if this is not helpful but it is what I know)

### Expected behavior

I expected the game launcher to boot up normaly into the home page where all my games are.

### Screenshots

![image](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/assets/129114975/b1068f30-2531-4cb4-a3dc-5c5059bb4437)

### Heroic Version

Latest Stable

### System Information

- OS Ubuntu 21.04
- Cpu: Intel i7 3770
- Gpu: Radeon 590

**Comment by EPOCHvoyager** [comment]
Same here on an fully updated Nobara 38(RPM version):

![image](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/assets/39300993/64ffa431-ce1c-450c-8140-7406014ac532)

**Comment by arielj** [comment]
you seem to be having this issue https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/issues/3284#issuecomment-1837483667

do what I suggest in that commend (delete the GPUCache folder) and restart heroic

**Comment by Brotatochip0919** [comment]
Thank you @arielj that worked
