### ISSUE TITLE
Gamescope is installed but not found

### ISSUE THREAD

**Issue by tclemens** [Heroic-Games-Launcher/HeroicGamesLauncher#3323]
### Describe the bug

The gamescope tab of the game-defaults and game-specific settings display an error "We could not found gamescope on the PATH. Install it or add it to the PATH." when an instance of gamescope is installed and available in `$PATH`.

### Add logs

```text
(16:53:13) INFO:    [Legendary]:        Legendary location: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary
(16:53:13) INFO:    [Gog]:              GOGDL location: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl
(16:53:13) INFO:    [Connection]:       Connectivity: check-online
(16:53:13) INFO:    [Connection]:       Pinging external endpoints
(16:53:13) INFO:    [Backend]:          DRM module staus {
  "oimompecagnajdejgnnjijobebaeigek": {
    "name": "Widevine Content Decryption Module",
    "status": "new",
    "version": "4.10.2710.0"
  }
}
(16:53:13) WARNING: [Backend]:          Failed to register protocol with OS.
(16:53:13) INFO:    [Legendary]:        Running command: LEGENDARY_CONFIG_PATH=/home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/legendaryConfig/legendary /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary --version
(16:53:13) INFO:    [Gog]:              Running command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json --version
(16:53:14) INFO:    [Nile]:             Running command: NILE_CONFIG_PATH=/home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/nile_config /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/nile --version
(16:53:14) INFO:    [Connection]:       Connectivity: online
(16:53:14) ERROR:   [Gog]:              Unable to syncQueued playtime, userData not present
(16:53:14) INFO:    [Backend]:          AreWeAntiCheatYet data downloaded
(16:53:14) INFO:    [Backend]:
System Information:
CPU: 8x AMD Custom APU 0405
Memory: 15.53 GB (used: 2.43 GB)
GPUs:
  GPU 0:
    Name: Advanced Micro Devices, Inc. [AMD/ATI] undefined
    IDs: D=1435 V=1002 SD=0123 SV=1002
    Driver: amdgpu
OS: SteamOS 3.5.7 holo (linux)

The current system is a Steam Deck (model: OLED)
We are running inside a Flatpak container

Software Versions:
  Heroic: 2.11.0 Kumachi
  Legendary: 0.20.33 Undue Alarm
  gogdl: 0.7.3
  Nile: 1.0.0 Jonathan Joestar

(16:53:14) INFO:    [Backend]:          Loading Screen Ready
(16:53:14) INFO:    [Frontend]:         Refreshing undefined Library
(16:53:14) WARNING: [Backend]:          refresh not implemented on Sideload Library Manager
(16:53:14) INFO:    [Legendary]:        Refreshing library...
(16:53:14) INFO:    [Legendary]:        Refreshing Epic Games...
(16:53:14) INFO:    [Legendary]:        Game list updated, got 9 games & DLCs
(16:53:14) INFO:    [Backend]:          Frontend Ready
(16:53:14) WARNING: [Backend]:          listUpdateableGames not implemented on Sideload Library Manager
(16:53:14) INFO:    [Gog]:              Found 0 game(s) to update
(16:53:14) INFO:    [Backend]:          Checking for current version changelog
(16:53:14) INFO:    [Legendary]:        Running command: LEGENDARY_CONFIG_PATH=/home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/legendaryConfig/legendary /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary list --third-party
(16:53:14) INFO:    [Legendary]:        Checking for game updates: LEGENDARY_CONFIG_PATH=/home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/legendaryConfig/legendary /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary list --third-party
(16:53:15) INFO:    [Legendary]:        Found 0 games to update
(16:53:16) INFO:    [Winetricks]:       Downloading Winetricks
(16:53:16) INFO:    [DXVKInstaller]:    Updating dxvk-nvapi to: dxvk-nvapi-v0.6.4
(16:53:17) INFO:    [DownloadManager]:  Downloader: Finished downloading https://github.com/jp7677/dxvk-nvapi/releases/download/v0.6.4/dxvk-nvapi-v0.6.4.tar.gz
(16:53:17) INFO:    [DownloadManager]:  Downloader: Finished downloading https://github.com/jp7677/dxvk-nvapi/releases/download/v0.6.4/dxvk-nvapi-v0.6.4.tar.gz
(16:53:17) INFO:    [DXVKInstaller]:    downloaded dxvk-nvapi
(16:53:17) INFO:    [DXVKInstaller]:    extracting dxvk-nvapi
(16:53:17) INFO:    [Backend]:          Extracting /home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/tools/dxvk-nvapi/dxvk-nvapi-v0.6.4.tar.gz to /home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/tools/dxvk-nvapi/dxvk-nvapi-v0.6.4 using native tar
(16:53:17) ERROR:   [Backend]:          Extracting Error: tar: /home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/tools/dxvk-nvapi/dxvk-nvapi-v0.6.4: Cannot open: No such file or directory
tar: Error is not recoverable: exiting now

(16:53:17) INFO:    [DXVKInstaller]:    dxvk-nvapi updated!
(16:53:18) INFO:    [WineDownloader]:   Updating wine versions info
(16:53:18) INFO:    [WineDownloader]:   Fetching upstream information...
(16:53:19) INFO:    [WineDownloader]:   wine versions updated
(16:53:19) INFO:    [Backend]:          Starting the Download Queue
```

### Steps to reproduce

1. Go to 'Settings > Game Defaults' or the settings for any game in 'Library'
2. Click on the 'GAMESCOPE' tab
3. See the error message "We could not found gamescope on the PATH. Install it or add it to the PATH."

### Expected behavior

The 'gamescope not found" error should not be displayed when an instance of gamescope is available in `$PATH`

### Screenshots

![Screenshot_20231215_165536](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/assets/9720410/51f2ae62-84d5-47c7-a862-ef38837f6072)

### Heroic Version

Latest Stable (Flatpak)

### System Information

- Steam Deck OLED
- SteamOS Holo
  - Variant: steamdeck
  - Version: 3.5.7
  - Build: 20231122.1

### Additional information

After digging through the code a bit I suspect that this bit of the `Gamescope` component may be the culprit:

https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/blob/8be4727c2609ad23686f7d0580592699358561bc/src/frontend/screens/Settings/components/Gamescope.tsx#L33-L45

In particular, I think the `hasExecutable('gamescope')` async call may not return a result by the time the component is done rendering. Since `useEffect(() => {...}, [])` only runs once after the first time the component is rendered, the error message will be displayed indefinitely even if `hasExecutable` would have eventually returned `true`.

I think something like `useEffect(() => {...}, [fetching])` could achieve the intended result without displaying the error message.

**Comment by arielj** [comment]
> I think something like `useEffect(() => {...}, [fetching])` could achieve the intended result without displaying the error message.

This would produce an infinite loop re-triggering the effect constantly. The current code for the useEffect is correct, for some reason heroic cannot find the executable.

how did you install gamescope?

**Comment by arielj** [comment]
@flavioislima I see this issue closed that says this should work https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/issues/2911, do you know how to debug this?

I tried installing gamescope with discover and heroic cannot find it

**Comment by tclemens** [comment]
> how did you install gamescope?

I tried using version that comes installed with steamos and the latest version distributed by flatpak

**Comment by flavioislima** [comment]
I cannot reproduce the issue. Are you on game mode or desktop mode? @tclemens 

I never needed to install Gamescope on the deck, heroic was able to find the version that come installed.

**Comment by arielj** [comment]
for me, I tested in desktop mode

I also tried going inside the flatpak with a bash with `flatpak run --command=bash com.heroicgameslauncher.hgl` and inside that I ran `which gamescope` (like the backend runs) and it says there's no gamescope command

**Comment by tclemens** [comment]
> Are you on game mode or desktop mode?

I made attempts in both desktop mode and game mode (by adding heroic launcher as a non-steam game)

**Comment by arielj** [comment]
I just tried this and it seems to work.

First, do NOT install gamescope with discover, if it's installed like that, uninstall it (it didn't work for me)
Then, on a konsole run `flatpak install gamescope` and pick the option that installs `runtime/com.valvesoftware.Steam.Utility.gamescope/x86_64/stable`

After that it does work, Heroic can see it and I can confirm it's working for me

**Comment by xenrohachi** [comment]
The above worked for me as well! Thank you!

**Comment by StarsetKnight** [comment]
So, quick rundown is a system installation of gamescope will not work, you have to install the flatpak version of gamescope for it to work with the flatpak version of Heroic.

**Comment by imLinguin** [comment]
As mentioned above, since it's a flatpak you need to install `org.freedesktop.Platform.VulkanLayer.gamescope` flatpak. Otherwise Heroic isn't able to access gamescope binaries and libraries within the container

**Comment by kopach** [comment]
Installing `gamescope` with `flatpak install gamescope` didn't work for me either. What did work was installing it with command:
```bash
flatpak install org.freedesktop.Platform.VulkanLayer.gamescope
```
this prompted me with versions of `gamescope` - I selected latest available and everything started finally to work for me

**Comment by BlueEyedCrow** [comment]
Is there a way to add a PATH of gamescope bin to a Flatpak version of Heroic, by using flatseal?

**Comment by imLinguin** [comment]
no, you need to install the correct gamescope flatpak, see message above yours

**Comment by Kirihi147** [comment]
> What if I have installed correct gamescope flatpak, but still have got this message: "We could not found gamescope on the PATH. Install it or add it to the PATH". How can I solve the problem? (I am using Arch linux)

Same issue. Kubuntu 24.04

**Comment by CleoMenezesJr** [comment]
> What if I have installed correct gamescope flatpak, but still have got this message: "We could not found gamescope on the PATH. Install it or add it to the PATH".


Same here

![image](https://github.com/user-attachments/assets/f02329e1-1638-486c-bac7-48d62fcf5821)
![image](https://github.com/user-attachments/assets/490fa4dd-d090-4eff-9692-eb408c6dc519)
![image](https://github.com/user-attachments/assets/4629365b-b5e3-4db3-bde0-781150f98dc1)

**Comment by imLinguin** [comment]
At the moment Heroic uses `23.08` flatpak runtime, thus the same gamescope needs to be provided

**Comment by CleoMenezesJr** [comment]
> At the moment Heroic uses `23.08` flatpak runtime, thus the same gamescope needs to be provided

Thanks, I didn't realize that Heroic hadn't updated the runtime. Sorry for the noise around here.

**Comment by Sunspark-007** [comment]
Came here to confirm the install string kopach provided is the answer plus the further guidance to match the runtime from the choices.

Heroic 2.17 is using the 24.08 runtime, so pick that version from the list of choices.

Would be good if down the road this could be done by the launcher.
