### ISSUE TITLE
some games dont show up in the library

### ISSUE THREAD

**Issue by 00pandora00** [Heroic-Games-Launcher/HeroicGamesLauncher#3337]
### Describe the bug

hi some of the games don't show up  in the library (Rocket Racing (epic games), and other that i can't remember (epic games)). 

i think this problem is with the "update library" feature because "the game that i can't remeber' pop up after a day or two. 
but i can't guaranty that, because the Rocket Racing game is older in my library that  "the game that i can't remember' and still don't show up today.

### Add logs

```text
(none)
```

### Steps to reproduce

check library 

### Expected behavior

all games, even unsupported ones, in the library.

### Heroic Version

Latest Stable

### System Information

(i really need to do this?)

**Comment by 00pandora00** [comment]
**update**: the "the game that i can't remeber' is destiny 2, and is older in my library  that rocket racing (my bad). the reason why i believed it was newer is that epic made an offer this christmas with destiny 2 (my bad again)

**Comment by arielj** [comment]
go to settings > logs > legendary/epic

it should list all the games in your library, are the games listed there?

**Comment by 00pandora00** [comment]
> go to settings > logs > legendary/epic
> 
> it should list all the games in your library, are the games listed there?

yes is there, but don't show up in the library.

question: i have to share that part of the logs?

**Comment by 00pandora00** [comment]
Note: the game is free... maybe you can test that yourself? (note: this is just a option. i'm here if any help is needed)

**Comment by arielj** [comment]
I see it's part of forntine

```
![image](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/assets/188464/e55f20db-bdf9-4523-81e9-5e9b25524630)
```

that is not displayed in the library (and I understand heroic cannot handle that yet either)

**Comment by arielj** [comment]
I understand this https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/pull/3317 will solve that if I'm not mistaken

**Comment by 00pandora00** [comment]
> I see it's part of forntine
> 
> ![image](https://private-user-images.githubusercontent.com/188464/292048604-e55f20db-bdf9-4523-81e9-5e9b25524630.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMxMTYxNTksIm5iZiI6MTcwMzExNTg1OSwicGF0aCI6Ii8xODg0NjQvMjkyMDQ4NjA0LWU1NWYyMGRiLWJkZjktNDUyMy04MWU5LTVlOWIyNTUyNDYzMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyMFQyMzQ0MTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jNjQyNmMwNmNiMzY1OTYyZDlhNjI4MzVmMWM1MWQ5OGYxOGM0YWIwZjUwMjk3MDZjMGNiNGYwZjc2NzQ1NmI1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.mdiJqzZONpjmMD0lq5SWTZqXqWsq7OBmGQmcawAsEus)
> 
> that is not displayed in the library (and I understand heroic cannot handle that yet either)

soo this game is a rare  case? a game that passes as a dlc? (o something like that)


> I understand this #3317 will solve that if I'm not mistaken

i will check that

**Comment by 00pandora00** [comment]
yea is seen that https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/pull/3317 is exactly the solution. so I guess this issue will remain open until https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/pull/3317 is merged

**Comment by arielj** [comment]
would be great if you can test the build from that PR to confirm if it works, you can download the windows portable exe from here https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/actions/runs/7252882767?pr=3317

**Comment by 00pandora00** [comment]
> would be great if you can test the build from that PR to confirm if it works, you can download the windows portable exe from here https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/actions/runs/7252882767?pr=3317

i can try but.. i'm in linux (flatpak) anyway to try that in linux? (please don't say: running the .exe XD)

**Comment by arielj** [comment]
> > would be great if you can test the build from that PR to confirm if it works, you can download the windows portable exe from here https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/actions/runs/7252882767?pr=3317
> 
> i can try but.. i'm in linux (flatpak) anyway to try that in linux? (please don't say: running the .exe XD)

the appImage is a linux portable executable

the github actions also build a flatpak binary https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/actions/runs/7252882736?pr=3317 (though it would override your current flatpak I guess)

**Comment by 00pandora00** [comment]
> > > would be great if you can test the build from that PR to confirm if it works, you can download the windows portable exe from here https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/actions/runs/7252882767?pr=3317
> > 
> > 
> > i can try but.. i'm in linux (flatpak) anyway to try that in linux? (please don't say: running the .exe XD)
> 
> the appImage is a linux portable executable
> 
> the github actions also build a flatpak binary https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/actions/runs/7252882736?pr=3317 (though it would override your current flatpak I guess)

Well that's unfortunate... I think I'll pass on trying that "solution". since I prefer to avoid modifying my flatpak. (still the appimage is an option. maybe try that)



> I assumed you are on windows because fortnite does not work outside windows (no idea if those fortnite extras work)

no problem. The truth is that I didn't know that game was part of Fortnite. (for me it was just a new epic game)

**Comment by arielj** [comment]
Closing this since Rocket Racing will show up as `Launch options` for Fortnite when that's implemented, it's expected that it doesn't show up in the library.

**Comment by 00pandora00** [comment]
> Closing this since Rocket Racing will show up as `Launch options` for Fortnite when that's implemented, it's expected that it doesn't show up in the library.

i guess that is fine. but is possible that some people get confused by that.

**Comment by bgiesing** [comment]
> Closing this since Rocket Racing will show up as `Launch options` for Fortnite when that's implemented, it's expected that it doesn't show up in the library.

Any chance this could be changed in the future or as an optional setting? I would love to have a direct tile in my library and the ability to make unique Steam shortcuts for each of these separate game modes. With how it's setup currently, you can only add the main Fortnite option using Heroic's Add Shortcuts function.

It also means the games don't show up when searching your library either which might confuse some people. Maybe it could be a filter "Show Epic Experiences" or something?
