### ISSUE TITLE
Uninstalling Gamescope can restrict access to games through GUI

### ISSUE THREAD

**Issue by Alzarath** [Heroic-Games-Launcher/HeroicGamesLauncher#3341]
### Describe the bug

After enabling Gamescope on a game, if you uninstall Gamescope, the menu gives the information "We could not found gamescope on the PATH. Install it or add it to the PATH." and hides Gamescope options. However, the options are still there and the game will attempt to play with gamescope, but it can't because it's not installed.

### Add logs

```text
N/A
```

### Steps to reproduce

1. Enable any Gamescope options with Gamescope installed
2. Uninstall Gamescope
3. Attempt to launch the game

### Expected behavior

When Gamescope is uninstalled, either the game will ignore the Gamescope options entirely, or the options will be visible for the user to make corrections.

### Heroic Version

Latest Stable

### System Information

Arch Linux x86_64

### Additional information

Workarounds involve, of course, re-installing Gamescope, or deleting the gamescope block from the game's config file.

**Comment by arielj** [comment]
For reference if anyone wants to work on fixing this, I reported this possibility during the development of the feature, pointing to the problematic code https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/pull/3089/files#r1349736177
