### ISSUE TITLE
Epic games not logged in when launched...

### ISSUE THREAD

**Issue by Arkm20** [Heroic-Games-Launcher/HeroicGamesLauncher#3349]
### Describe the bug

When I launch an epic game, such as Fortnite, it won't sign in automatically. I am on Mac...

### Add logs

```text
None Available
```

### Steps to reproduce

1. Launch Fortnite, on an m1 macbook, using an epic account on heroic
2. Wait for game to load in to sign in screen
3. then gives error to retry the launch of the game

### Expected behavior

Supposed to automatically sign in...

### Heroic Version

Latest Stable

### System Information

- OS [e. g. "MacOS"]:

**Comment by Arkm20** [comment]
My bad...

**Comment by xlegends** [comment]
happens to me too, tried it just rn
