### ISSUE TITLE
How to debug/resolve game launch issues?

### ISSUE THREAD

**Issue by cookiEoverdose** [Heroic-Games-Launcher/HeroicGamesLauncher#3351]
### Describe the bug

**Game**: Returnal (Epic Games Store)
**Issue**: After pressing play now, it turns back to "play now" after a few seconds, nothing else happens.
Other Epic Game Store games work with HGL. Already tried changing wine/proton selection and using "--enable-logging". I do not see any warnings or error messages just one info with the launch command.    
Launching the game without HGL but for example with Bottles / in a bottle with Epic Games Store installed, works fine. The game launches.

**Question**: So in general, how to get more information why launching with Heroic Games Launcher fails with a specific game?

### Add logs

```text
INFO:    [Backend]:          Launching Returnal
INFO:    [Backend]:          Checking if wine version exists: Wine - Wine-GE-Proton8-25
INFO:    [Backend]:          Stopping Power Saver Blocker
INFO:    [Backend]:          Checking if wine version exists: Wine - Wine-GE-Proton8-25
INFO:    [Backend]:          Checking if wine version exists: Wine - Wine-GE-Proton8-25
INFO:    [Backend]:          Checking if wine version exists: Wine - Wine-GE-Proton8-25
DEBUG:   [Backend]:          Running Wine command: wineboot --init
INFO:    [DXVKInstaller]:    installing dxvk on... [..]
INFO:    [DXVKInstaller]:    dxvk already installed!
INFO:    [DXVKInstaller]:    installing vkd3d on... [..]
INFO:    [DXVKInstaller]:    vkd3d already installed!
INFO:    [Legendary]:        Launching Returnal [..]
INFO:    [Backend]:          Stopping Display Power Saver Blocker
INFO:    [Frontend]:         Refreshing legendary Library
INFO:    [Legendary]:        Refreshing library...
INFO:    [Legendary]:        Refreshing Epic Games...
INFO:    [Legendary]:        Game list updated, got [..]
```

### Steps to reproduce

2. Click on '...'
3. Scroll down to '...'

### Expected behavior

* game launches

### Heroic Version

Latest Stable (Flatpak)

### System Information

- OS [e. g. "Ubuntu"]: Fedora 39 / AMD GPU

**Comment by arielj** [comment]
there's a button `Report an problem running this game` right below the `play` button (or you can do right click the card > logs)

that's the first place to look

please use the `#-support` area on our discord server for help debugging game issues, github issues are meant for errors of heroic itself
