### ISSUE TITLE
Transfer games to hard disk

### ISSUE THREAD

**Issue by niksingh710** [Heroic-Games-Launcher/HeroicGamesLauncher#3361]
### Feature description

transfer games to another disk easily. like the option available in steam

**Comment by imLinguin** [comment]
I believe this is already supported 
![obraz](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/assets/62100117/b7840421-1cbb-49fc-b8db-5c57a4dc514a)

**Comment by niksingh710** [comment]
ins't there any way to move all the games at once?
i mean like how steam does it in a way where it can scan and move all of it's games at once.
