### ISSUE TITLE
Make a prompt to update the legendary binary as sometimes the one that is bundled is sometimes outdated

### ISSUE THREAD

**Issue by sjp760** [Heroic-Games-Launcher/HeroicGamesLauncher#3365]
### Problem description

It could be useful to check for updates to the legendary executable since the one that is bundled might be outdated. For example, in the latest release of Heroic as of this writing (2.11.0), the legendary version included is 0.20.33 Undue Alarm but the latest release of legendary as of this writing is 0.20.34 Direct Intervention. This helps users get the latest bugfixes that might be included in legendary as they do not have to wait for a heroic update.

### Feature description

It could detect the latest version of legendary then prompt the user to download it. Heroic could use the custom legendary binary setting to point towards the executable.. If there happens to be an issue with a breaking change in legendary, there could be a setting to quickly switch to the included one in Heroic as a solution.

**Comment by flavioislima** [comment]
The problem is that if Legendary brings some change that might break some heroic feature so the update could break Heroic.

Although Legendary and Heroic are projects that work together we are still separate projects.

**Comment by arielj** [comment]
Maybe we can detect when there's a new version in the logs and put a link to a wiki page explaining how users can do it manually also in the logs?

So we don't do anything automatic but also educate users to do it themselves if they want to

**Comment by flavioislima** [comment]
Nothing against that.
