### ISSUE TITLE
Update crossover WINE versions?

### ISSUE THREAD

**Issue by asmaloney** [Heroic-Games-Launcher/HeroicGamesLauncher#3372]
### Problem description

The "Wine Manager" shows the latest crossover WINE as 23.0.1 from 1 November 2023.

Any possibility of adding [23.5.0, 23.6.0, 23.7.0, and 23.7.1](https://www.codeweavers.com/crossover/changelog)?

### Feature description

It would be useful to keep the crossover WINE versions up-to-date.

I have  bunch of games which don't work and it would be great to be able to try different, more recent versions of Crossover WINE.

**Comment by arielj** [comment]
We use this repository to get the versions https://github.com/Gcenx/winecx. Looks like they have tags for those versions but not releases, maybe we need to change the logic to download them based on tags instead of releases

**Comment by flavioislima** [comment]
@Gcenx sorry for the ping.
How does the publishing works on your repo when codeweavers releases an update?
How could we get the latest version from them?

Thanks!

**Comment by flavioislima** [comment]
Closing this one since it is not Heroic-related directly like stated above.

Thanks for making it clear @Gcenx .

**Comment by robigan** [comment]
> Before it comes up.
> 
> 
> 
> <br>
> 
> 
> 
> I won’t be providing a wine-crossover-24.x package anytime soon.
> 
> 
> 
> <br>
> 
> 
> 
> The wine-crossover-23.7.1 package unlike CrossOver-23.7.1 does not support:
> 
> - Battle.Net
> 
> - D3DMetal
> 
> - GStreamer
> 
> - Ubisoft Connect
> 
> - VKD3D (Limited DirectX 12 support via MoltenVK)

Then what would it take to get D3DMetal (Game Porting Toolkit in it's entirety) to run? It is my understanding that compiling the game porting toolkit with Apple's homebrew compiler provide a wine version with crossover modifications and the gptk modifications baked in right? Although I checked out the script and I found that it compiles with crossover 21. Is it possible to compile with crossover 23 or are there issues in compiling with this version as you'd mentioned above?

Trying to get Elite Dangerous to run smoothly but it's my understanding that Apple's contribution to the gptk are the improved graphics performance and support for d3d12 right?

**Comment by robigan** [comment]
> > Then what would it take to get D3DMetal (Game Porting Toolkit in its entirety) to run? It is my understanding that compiling the game porting toolkit with Apple's homebrew compiler provide a wine version with crossover modifications and the gptk modifications baked in right? Although I checked out the script and I found that it compiles with crossover 21. Is it possible to compile with crossover 23 or are there issues in compiling with this version as you'd mentioned above?
> 
> 
> D3DMetal: Apples Direct3D to Metal translation layer.
> 
> Game Porting Toolkit: Apple developer utility to help investigate the feasibility of porting Windows games to macOS without the upfront work.
> 
> > Is it possible to compile with crossover 23
> 
> No as Game Porting Toolkit is it’s own thing, CrossOver-23.5.0 and later supports D3DMetal you can purchase a license
> 
> > or are there issues in compiling with this version as you'd mentioned above?
> 
> There’s no compilation issues, it was packing issues but I’m also no going to provide an easy to use package of the latest version of wine-crossover + builtin D3DMetal support.

I see your point of view. Alright thanks!
