### ISSUE TITLE
Offline Mode Not Appearing for Some Epic Games

### ISSUE THREAD

**Issue by Ponjen** [Heroic-Games-Launcher/HeroicGamesLauncher#3383]
### Describe the bug

Games that support Offline Mode or are DRM free don't have an Offline Mode toggle in Heroic. Three games as examples are Soulstice, DNF Duel, and 20 Minutes Till Dawn. Heroic says these games require an online connection, but this is wrong. DNF Duel and Soulstice work 100% offline on Epic's launcher and supports Offline Mode. 20 Minutes Till Dawn is DRM free. However, because Heroic doesn't offer the Offline Mode toggle for these games, an arbitrary online connection is forced in order to boot them.

### Add logs

```text
System Info:

CPU: 8x AMD Custom APU 0405

Memory: 12.36 GB (used: 7.32 GB)

GPUs:

  GPU 0:

    Name: Advanced Micro Devices, Inc. [AMD/ATI] VanGogh [AMD Custom GPU 0405]

    IDs: D=163f V=1002 SD=0123 SV=1002

    Driver: amdgpu

OS: SteamOS 3.5.7 holo (linux)

The current system is a Steam Deck (model: LCD)

We are running inside a Flatpak container

Software Versions:

  Heroic: 2.11.0 Kumachi

  Legendary: 0.20.33 Undue Alarm

  gogdl: 0.7.3

  Nile: 1.0.0 Jonathan Joestar

Game Settings: {

	"autoInstallDxvk": true,

	"autoInstallVkd3d": true,

	"preferSystemLibs": false,

	"enableEsync": true,

	"enableFsync": true,

	"nvidiaPrime": false,

	"enviromentOptions": [],

	"wrapperOptions": [],

	"showFps": false,

	"useGameMode": false,

	"language": "",

	"wineVersion": {

		"bin": "/home/deck/.local/share/Steam/compatibilitytools.d/GE-Proton8-25/proton",

		"name": "Proton - GE-Proton8-25",

		"type": "proton"

	},

	"winePrefix": "/home/deck/Games/Heroic/Prefixes/Baldurs Gate 3",

	"wineCrossoverBottle": ""

}

Game launched at: Wed Jan 03 2024 19:41:45 GMT-0500 (Eastern Standard Time)

Launch aborted: Offline mode not supported
```

### Steps to reproduce

1. Disable internet connection
2. Launch a DRM free EGS game
3. See Error "offline mode is not supported"

### Expected behavior

The game should launch offline with no issues, as it has no DRM and even supports Offline Mode on the actual Epic launcher.

### Heroic Version

Latest Stable

### System Information

System Info:

CPU: 8x AMD Custom APU 0405

Memory: 12.36 GB (used: 7.32 GB)

GPUs:

  GPU 0:

    Name: Advanced Micro Devices, Inc. [AMD/ATI] VanGogh [AMD Custom GPU 0405]

    IDs: D=163f V=1002 SD=0123 SV=1002

    Driver: amdgpu

OS: SteamOS 3.5.7 holo (linux)

### Additional information

I first noticed this issue with Soulstice, but didn't think much of it. I assumed it was just Epic being scum. Had an inkling this was a Heroic issue when I saw DNF Duel didn't have an Offline Mode toggle either, and Reddit users telling me it works offline on the actual Epic launcher. Now here's 20  Minutes Till Dawn, a game confirmed to be DRM free (I can launch the exe itself as a Non-Steam game), and it also has this issue. Clearly something isn't right. Also, ignore the prefix name in the log. I just use my Baldur's Gate 3 prefix as my default, shared prefix.

**Comment by arielj** [comment]
We use the information that is present in the game's metadata to know if the game can run offline:

```
      "CanRunOffline": {
        "type": "STRING",
        "value": "true"
      },
```

Those games don't have that information in the metadata so we don't show the option.

This would be an issue with the data we get and not something we can control (means the developers didn't flag the game as supporting offline mode)

**Comment by arielj** [comment]
Maybe one thing we can do is to always show the option to turn on the Offline mode but for the cases the game metadata doesn't have the info we show a warning saying the game does not explicitly support Offline mode turning the option on is the user's responsibility and there's a change the game won't start.

**Comment by Ponjen** [comment]
I'm wondering if devs don't realize Offline Mode is an opt-in option on Epic, and not launcher-wide like Steam. Just tested DNF Duel just to be sure, and it definitely runs offline, even though Epic says it doesn't support Offline Mode.
