### ISSUE TITLE
Game "installs" instantly but does not appear as installed in heroic library

### ISSUE THREAD

**Issue by Zanomi** [Heroic-Games-Launcher/HeroicGamesLauncher#3386]
### Describe the bug

Whilst downloading guardians of the galaxy on heroic I switched to desktop mode which cancelled it. I then accidentally deleted its prefix folder in files. After trying to redownload it it instantly says it has been installed and added to steam. It is still grayed out in heroic library and has added to steam but when clicking play from steam it says it has not installed and asks if I want to install it which i do but that does the same instant download thing.

### Add logs

```text
(19:52:55) INFO:    [Backend]:          Heroic is already running, quitting this instance
```

### Steps to reproduce

Start game download in game mode
Switch to desktop
Delete prefix folder 
Reattempt download 

### Expected behavior

Game downloads properly (I expect it to take a while)

### Heroic Version

Latest Stable

### System Information

Steam OS

**Comment by arielj** [comment]
you shouldn't download games in gaming mode, it's a bad idea

look for the game install directory and delete it and download it again (looks like something got corrupted)

**Comment by Zanomi** [comment]
Ok thanks where would this be?

**Comment by arielj** [comment]
when you open the install dialog it tells you where it's going to install the game

**Comment by arielj** [comment]
Closing this since last message was from january, I imagine the game installs now.
