### ISSUE TITLE
Strange behaviour of Heroic GUI

### ISSUE THREAD

**Issue by RafaelLinux** [Heroic-Games-Launcher/HeroicGamesLauncher#3391]
### Describe the bug

Despite having the latest version of Heroic, something happens and I don't know why. I've even restarted the computer, but it's nothing to do with it.

### Add logs

```text
Can't access "Setting" or anything in the GUI
```

### Steps to reproduce

1. Launch Heroic

### Expected behavior

Show all GUI as always

### Heroic Version

Latest Stable

### System Information

Operating System: openSUSE Tumbleweed 20231226
KDE Plasma Version: 5.27.10
KDE Frameworks Version: 5.113.0
Qt Version: 5.15.11
Kernel Version: 6.6.7-1-default (64-bit)
Graphics Platform: Wayland
Processors: 24 × AMD Ryzen 9 3900X 12-Core Processor
Memory: 31.3 GiB of RAM

Graphics Processor: AMD Radeon RX 7600
Product Name: B550M Phantom Gaming 4

### Additional information

Was running without issues 2 months ago.
I attached screen record of Heroic GUI
[Heroic Games_VP9.webm](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/assets/13048959/f3aea615-04be-4642-b91e-27c951fecf85)

**Comment by arielj** [comment]
check this https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/issues/3284#issuecomment-1837483667

**Comment by arielj** [comment]
if it still shows those visual glitches, try passing `--disable-gpu` to the command (or add that to the shortcut)

**Comment by RafaelLinux** [comment]
No changes at all. I tried bot (rmdir that folder and add those parameters to launch Heroic) but really nothing changed. Same behaviour  :(

**Comment by arielj** [comment]
how did you install heroic? how are you running it?

**Comment by RafaelLinux** [comment]
Is AppImage version. I always download it, make it executable and launch from access in desktop.

**Comment by arielj** [comment]
Have you tried opening a terminal where the app image is and running `./Heroics...appImage --disable-gpu`?

you can try an appimage from https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/pull/3305 (https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/actions/runs/7153690921) that disables the gpu acceleration

but the `--disable-gpu` flag I understand it should work

**Comment by RafaelLinux** [comment]
You have reason. When I put "--disable-gpu" parameter in launcher, it was ignoring them. When I launched from console, it worked, so I put correctly now that parameter in launcher.

![imagen](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/assets/13048959/be6a095d-b2d2-4f8c-8815-7aa8995b0ea3)


Thanks

**Comment by RafaelLinux** [comment]
Yes, I'm sorry, I thought I closed it. Now I do it.

**Comment by RafaelLinux** [comment]
I can confirm that with release [2.12.1 HOTFIX #1](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/releases/tag/v2.12.1), there is not necessary yet the `--disable-gpu` argument that suddenly I needed to put in previous version.
