### ISSUE TITLE
Very bad FR Translation for NVAPI parameter.

### ISSUE THREAD

**Issue by sigzegv** [Heroic-Games-Launcher/HeroicGamesLauncher#3396]
### Describe the bug

Translation is wrong at https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/blob/16bb04f670eb048587bf5c4e79789af7496b5e3e/public/locales/fr/translation.json#L654 and can lead to misinterpretation. As example I wanted to set PROTON_ENABLE_NVAPI=0 but that checkbox forces this value to 1, and with this bad translation I wasn't enable to quickly guess that the checkbox was refering to NVAPI...

### Add logs

```text
no logs needed.
```

### Steps to reproduce

open the game parameters.

### Expected behavior

The english text is `Auto Install/Update DXVK-NVAPI on Prefix`, so the FR translation should refer to dxvk-nvapi instead of only dxvk/vkd3d that is a non sense, and should be this : `Installation/Mise à jour automatique de DXVK-NVAPI sur le prefixe`

### Heroic Version

Latest Stable

### System Information

- OS: Any

**Comment by imLinguin** [comment]
Thanks for catching that. You can fix translations on our weblate, the change will be available in next release. If you want you can make a change there
 https://hosted.weblate.org/projects/heroic-games-launcher

**Comment by sigzegv** [comment]
I didn't created an account but I sent a suggestion for that key, is that enough ?

**Comment by arielj** [comment]
weblate automatically makes a PR against our repo with updated strings periodically, so the fix should appear eventually

**Comment by arielj** [comment]
Closing this. Weblate already made a PR with this change https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/pull/3395/files#diff-db68874ec38c82339488bf71b2c6986967df85e8920b9dc9755e603a6ec7c4b0R654 and it will be included in the next release
