### ISSUE TITLE
There's no easy way to go back to the game details page after opening the `Store Page`

### ISSUE THREAD

**Issue by arielj** [Heroic-Games-Launcher/HeroicGamesLauncher#3399]
### Describe the bug

In the game details page we have the option to open the store page of that game. This open in the `Stores` screen (the webview) but there's no element to go back to the game page of Heroic.

This is a problem because you are looking at a game, you open the store to check more details and then if you want to install the game you have to go Library > scroll to the game > open it.

### Add logs

```text
Nothing relevant.
```

### Steps to reproduce

1. Go to the library
2. Click on any game card to open the game details
3. Click the 3 dots menu > Store Page
4. There's no way to go back to the game details

Note that we DO have a way to go back pressing B when using a controller, this issue is a problem only if using mouse navigation of the interface.

### Expected behavior

I imagine 2 options:
- we open the store page in a popup window instead of the stores page (I think it was like this before but then replaced with the current behavior though)
- we implement some action to go back (we already have the `<` arrow in that screen, it could be used for this)

### Heroic Version

Latest Stable

### System Information

Not relevant

**Comment by CommandMC** [comment]
> we implement some action to go back (we already have the `<` arrow in that screen, it could be used for this)

This is probably the easiest to implement: I have a mouse with physical back/forward buttons and using it to go back to the details page already works, so having that button with a [`History.back`](https://developer.mozilla.org/en-US/docs/Web/API/History/back) callback should be all that's needed here
