### ISSUE TITLE
Use upstream winetricks on macOS

### ISSUE THREAD

**Issue by Gcenx** [Heroic-Games-Launcher/HeroicGamesLauncher#3413]
### Feature description

Upstream winetricks now works without modification.

### Additional information

When originally proposed upstream winetricks didn’t work correctly with CX nor upstreams WoW64 system, that’s no longer the case.

**Comment by flavioislima** [comment]
Cool, will work on removing it and using the upstream WineTricks.

Thanks!

**Comment by flavioislima** [comment]
> @flavioislima it would be a good idea to change to upstream winetricks now as I've removed the fork and GitHub now gives a 404 for the old url.

True, will do that before the next release.
