### ISSUE TITLE
Launching problem

### ISSUE THREAD

**Issue by VoidedKN0X** [Heroic-Games-Launcher/HeroicGamesLauncher#342]
**Describe the bug**
Some games don't launch via the Heroic Launcher but can launch via Legendary in terminal, i've tried all the different installed win versions but none of theme make a difference

**Expected behavior**
The games launch via Heroic Launcher like they would via Legendary

**Desktop (please complete the following information):**

- OS: Manjaro Gnome
- Version Latest
- Game:SUPERHOT (just an example)
- Wine/Proton version:Proton 6.3, Wine 6.7, Proton GE 6.5

**Comment by flavioislima** [comment]
Hi! can you post the Heroic Launch command? you can see it when using heroic from terminal and launch the game. then send the Legendary command you're using and other games that we can try to launch. I was never able to play superhot on legendary or heroic.

**Comment by VoidedKN0X** [comment]
> Hi! can you post the Heroic Launch command? you can see it when using heroic from terminal and launch the game. then send the Legendary command you're using and other games that we can try to launch. I was never able to play superhot on legendary or heroic.

This is what i get:
Launch Command: PULSE_LATENCY_MSEC=60    MANGOHUD=1 /usr/bin/gamemoderun /opt/heroic/resources/app.asar.unpacked/build/bin/linux/legendary launch Dory  --wine /usr/bin/wine --wine-prefix '/home/axel/.wine'

**Comment by flavioislima** [comment]
And how do you do to launch using legendary? Does this same command work?

**Comment by VoidedKN0X** [comment]
> And how do you do to launch using legendary? Does this same command work?

it does work with the same command but when i use legendary i just use this: legendary launch Dory (or whatever the name of the game is)

**Comment by flavioislima** [comment]
On the game settings, in Heroic, turn off all options like `mangohud`, `gamemode`, etc.
The command then should be only `legendary launch game` and the wine and prefix options.
I had issues with Mangohud and gamemode before with a few games and this might be what is happening in your case.

**Comment by VoidedKN0X** [comment]
> On the game settings, in Heroic, turn off all options like `mangohud`, `gamemode`, etc.
> The command then should be only `legendary launch game` and the wine and prefix options.
> I had issues with Mangohud and gamemode before with a few games and this might be what is happening in your case.

I've already tried that before, i've tried it again just now and it still didn't work... This is my terminal window:
heroic                                                           ✔ 
Protocol already registered.
launching Dory

 Launch Command:       /opt/heroic/resources/app.asar.unpacked/build/bin/linux/legendary launch Dory  --wine /usr/bin/wine --wine-prefix '/home/axel/.wine'

**Comment by Gyilkos91** [comment]
I have exactly the same problem. Trying to launch the launch command directly leads to this error:
`/opt/heroic/resources/app.asar.unpacked/build/bin/linux/legendary: error while loading shared libraries: libz.so.1: failed to map segment from shared object`

**Comment by flavioislima** [comment]
> I have exactly the same problem. Trying to launch the launch command directly leads to this error:
> `/opt/heroic/resources/app.asar.unpacked/build/bin/linux/legendary: error while loading shared libraries: libz.so.1: failed to map segment from shared object`
> 
> Edit: I tried it now by renaming the bundled version of legendary and linking the newest release of legendary that I have installed and it works immediately. So it seems to be a problem with the bundled version. At least for me.

Hmm, yeah, I cannot reproduce it but I'll download and add another legendary binary even though we are using the latest and then you can try again. @VoidedKN0X can you try that as well?

**Comment by VoidedKN0X** [comment]
> > I have exactly the same problem. Trying to launch the launch command directly leads to this error:
> > `/opt/heroic/resources/app.asar.unpacked/build/bin/linux/legendary: error while loading shared libraries: libz.so.1: failed to map segment from shared object`
> > Edit: I tried it now by renaming the bundled version of legendary and linking the newest release of legendary that I have installed and it works immediately. So it seems to be a problem with the bundled version. At least for me.
> 
> Hmm, yeah, I cannot reproduce it but I'll download and add another legendary binary even though we are using the latest and then you can try again. @VoidedKN0X can you try that as well?

If i could get a tutorial on how to do that i can try it... I'm not very familiar with those things

**Comment by flavioislima** [comment]
I dont think thats the issue. I just confirmed that we are using the latest version and on the screenshot below you can see that the md5 checksum of both binaries, the one I downloaded from their repo just now and the one that comes with Heroic, is the same:
![image](https://user-images.githubusercontent.com/26871415/118393154-e23f6d80-b63d-11eb-93ca-2c61a397f3f8.png)

@VoidedKN0X you would need to replace the legendary binary that comes with heroic with the one downloaded from their repository or create a symbolic link to it.

Also, you said that some games work and some others doesn't, right?
When I asked above if the same command that heroic shows works with legendary, you should have tested copying the heroic command shown on the terminal and replace the legendary part like this:

`PULSE_LATENCY_MSEC=60 MANGOHUD=1 /usr/bin/gamemoderun legendary launch Dory --wine /usr/bin/wine --wine-prefix '/home/axel/.wine'`

**Comment by VoidedKN0X** [comment]
> I dont think thats the issue. I just confirmed that we are using the latest version and on the screenshot below you can see that the md5 checksum of both binaries, the one I downloaded from their repo just now and the one that comes with Heroic, is the same:
> ![image](https://user-images.githubusercontent.com/26871415/118393154-e23f6d80-b63d-11eb-93ca-2c61a397f3f8.png)
> 
> @VoidedKN0X you would need to replace the legendary binary that comes with heroic with the one downloaded from their repository or create a symbolic link to it.
> 
> Also, you said that some games work and some others doesn't, right?
> When I asked above if the same command that heroic shows works with legendary, you should have tested copying the heroic command shown on the terminal and replace the legendary part like this:
> 
> `PULSE_LATENCY_MSEC=60 MANGOHUD=1 /usr/bin/gamemoderun legendary launch Dory --wine /usr/bin/wine --wine-prefix '/home/axel/.wine'`

That's literally what i did and it launches fine unless i use heroic launcher then it doesn't for some reason

**Comment by VoidedKN0X** [comment]
Please put this on open agai  as this still isn't answered, the issue still persists

**Comment by flavioislima** [comment]
> Please put this on open again as this still isn't answered, the issue still persists

This is opened. But i don't know what to do. The error is quite generic and I cannot replicate it here. And I'm using a arch based distro as well. I'll also try on popos when I have time.

**Comment by Gyilkos91** [comment]
I just checked the checksum and I realized that the legendary binary doesn't work for me either, same problems with the library, but I had python3-legendary-gl_0.20.6-1_all.deb installed, which doesn't need any libraries linked. So it doesn't seem to be the same issue.

**Comment by flavioislima** [comment]
> I just checked the checksum and I realized that the legendary binary doesn't work for me either, same problems with the library, but I had python3-legendary-gl_0.20.6-1_all.deb installed, which doesn't need any libraries linked. So it doesn't seem to be the same issue.

So it might be a legendary issue. Heroic is just the gui that calls legendary with the parameters like wine, prefix, etc. So I don't see how this can be on the Heroic side. But, I'll keep this open for now.

**Comment by Gyilkos91** [comment]
> > I just checked the checksum and I realized that the legendary binary doesn't work for me either, same problems with the library, but I had python3-legendary-gl_0.20.6-1_all.deb installed, which doesn't need any libraries linked. So it doesn't seem to be the same issue.
> 
> So it might be a legendary issue. Heroic is just the gui that calls legendary with the parameters like wine, prefix, etc. So I don't see how this can be on the Heroic side. But, I'll keep this open for now.

Yes, at least my problem is not caused by heroic.

**Comment by adityaruplaha** [comment]
@VoidedKN0X does issue still persist?

**Comment by VoidedKN0X** [comment]
> @VoidedKN0X does issue still persist?

I will check this evening, in in about 13 hours since i'm not home right now

**Comment by VoidedKN0X** [comment]
> @VoidedKN0X does issue still persist?

Issue still persists

**Comment by toalex77** [comment]
Ok, I managed to solve this issue on my system, openSUSE Tumbleweed, in two alternatives ways:
- Installing "legendary" from [openSUSE Community Repositories](https://software.opensuse.org/package/legendary?search_term=legendary) and replacing the legendary binary in /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary with a symbolic link to /usr/bin/legendary (the executable from the Community Package)
- By settings PYTHONHOME=/usr and PYTHONPATH=/usr/lib64/python3.8/lib-dynload:/usr/lib64/python3.8 environment variables

So it's an issue with the binary from Legendary launcher.

What Heroic Games Launcher can do?
I think, it can use the system-wide "legendary" executable file, if it's installed (it can use the output of command `which legendary`), or at least alert the user when PYTHONHOME and/or PYTHONPATH are not setted (and suggest how to set these two environment variables).

**Comment by VoidedKN0X** [comment]
> Ok, I managed to solve this issue on my system, openSUSE Tumbleweed, in two alternatives ways:
> 
> * Installing "legendary" from [openSUSE Community Repositories](https://software.opensuse.org/package/legendary?search_term=legendary) and replacing the legendary binary in /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary with a symbolic link to /usr/bin/legendary (the executable from the Community Package)
> * By settings PYTHONHOME=/usr and PYTHONPATH=/usr/lib64/python3.8/lib-dynload:/usr/lib64/python3.8 environment variables
> 
> So it's an issue with the binary from Legendary launcher.
> 
> What Heroic Games Launcher can do? I think, it can use the system-wide "legendary" executable file, if it's installed (it can use the output of command `which legendary`), or at least alert the user when PYTHONHOME and/or PYTHONPATH are not setted (and suggest how to set these two environment variables).

So i just now tried those 2 fixes with no success (i know i'm very late) and the first one didn't work and the second one i don't really understand how to excecute properly, so a little extra explanation would be welcome

**Comment by flavioislima** [comment]
Try the latest version. Also, try Flatpak if possible.
