### ISSUE TITLE
Gamepad navigation stutter when navigating the menu

### ISSUE THREAD

**Issue by mdeguzis** [Heroic-Games-Launcher/HeroicGamesLauncher#3421]
### Describe the bug

I have an official Playstation 4 controller. When I navigate with the directional pad / left stick, the movement skips, so instead of going up 1 selection it goes up 2. The back button also doesn't seem to work (what amounts to pressing B). When I checked https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/wiki/Gamepad-Navigation, it seems PS4 controllers fall under the PS3 controller section.

I noticed when I hit O / circle on the controller, the glyph change to XBXY, so I suspect it's fighting with what Steam Input / SteamOS is providing.

I haven't yet tested the controller with https://gamepad-tester.com, but I can. Is this a consequence of playing on SteamOS/ChimeraOS with gamescope? Maybe the overlay is messing with how it's implementing on Heroic.

Any ideas? Willing to test/debug and put in some time on it.

### Add logs

```text
I can't at the moment, as it' runs on my living room PC with controller. Is there a CLI command / log location? I have SSH access. I can also try to record a video.
```

### Steps to reproduce

1. Connect a PS4 controller in game mode / gamescope (Steam)
2. Ensure controller support enabled
3. Try to move around the UI

### Expected behavior

Navigation moves as if the arrow keys are being used

### Heroic Version

Latest Stable

### System Information

ChimeraOS

**Comment by ColeCarithers** [comment]
Looks like this may be related to or duplicated from issue #989

**Comment by mdeguzis** [comment]
It is the same , yea. Resolving.
