### ISSUE TITLE
Dark text on dark background is very difficult to read

### ISSUE THREAD

**Issue by asmaloney** [Heroic-Games-Launcher/HeroicGamesLauncher#3430]
### Describe the bug

When looking at the library and a game is downloading an update, the text showing the progress is dark text on a dark background which is difficult to read.

### Add logs

```text
(no logs)
```

### Steps to reproduce

1. Update a game
2. Go to the library

### Expected behavior

Readable text.

### Screenshots

<img width="189" alt="Screen Shot 2024-01-11 at 17 28 10 PM" src="https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/assets/391371/b797c841-a16d-4e2a-9aac-ec431f6bc6eb">

### Heroic Version

Latest Stable

### System Information

macOS

**Comment by arielj** [comment]
I imagine this is a theme issue, which theme are you using? looks like nord-light

**Comment by asmaloney** [comment]
Yep - Nord Light!
