### ISSUE TITLE
New UI - Game Settings Placement

### ISSUE THREAD

**Issue by BVengo** [Heroic-Games-Launcher/HeroicGamesLauncher#3437]
### Problem description

Hi! I've just tested out the new UI and pretty quickly ran into my first 'problem' (if you can call it that). I noticed that, in the game info screen, settings are in the top centre whereas extra information is on the top right which feels unintuitive when comparing to other applications. 

![image](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/assets/43019560/8a2b4a0d-a67a-4fe5-a49a-a773a59938ab)

The settings buttons also feel a little out of place since they're not perfectly centered. I assume this is probably because they share a container with the frame beneath them, which makes sense but still looks a bit out of place.

### Feature description

I believe they should probably be swapped around, so that they are consistent with a lot of other UIs. My own software exposure says to look at the top right corner for extra settings, so it took that extra couple of seconds looking around for what I was after when I realised it had shifted.

This issue could be closed due to it being personal preference (and I fully understand if that happens), however I thought it worth mentioning :)

### Alternatives

Have all of the buttons on the top right, with the settings being furthest to the right. A small, gray/white vertical separator line could be placed between the info buttons and the settings buttons to clearly indicate separate behaviours. 

### Additional information

Love HL, and thanks to everyone who works on it!

**Comment by arielj** [comment]
This was changed already for the next release, closing
