### ISSUE TITLE
[UI/UX] Idea: Transparent/Blur NavBar

### ISSUE THREAD

**Issue by DavidoTek** [Heroic-Games-Launcher/HeroicGamesLauncher#344]
**Is your feature request related to a problem? Please describe.**
More transparency/blur effects could be added for a more "modern" look.

**Describe the solution you'd like**
- Make the NavBar transparent and add a blur effect
- Show blurred game image in the background on the Game page
- Maybe add the option to disable the blur effect (not sure if it consumes too much system resources)

**Describe alternatives you've considered**
Not adding the effect for a simpler look and lower resource usage.

**Additional context**
Changes (NavBar): https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/compare/main...DavidoTek:blur-ui
![heroic2](https://user-images.githubusercontent.com/54072917/117438750-407b9a80-af32-11eb-8014-d856959c763a.png)
Mockup (Game page):
![heroic1](https://user-images.githubusercontent.com/54072917/117438754-41acc780-af32-11eb-8a6a-418fd290cd15.png)

**Comment by adityaruplaha** [comment]
Fixed by #345.
