### ISSUE TITLE
Arm64 linux

### ISSUE THREAD

**Issue by franklinprakash1090** [Heroic-Games-Launcher/HeroicGamesLauncher#3443]
### Problem description

Heroic games need port for Linux arm64&risc-v

### Feature description

Windows going to full scale risc instruction by 
Qualcomm and other chipset manufacturers with introduction of windows 12 arm64 and native arm64 windows games and apps the windows x86 needs box86 to emulate

**Comment by CommandMC** [comment]
[`castlabs/electron-releases`](https://github.com/castlabs/electron-releases), the specific version of Electron we're using, does not have an arm64 build for Linux (or Windows), and has no RISC-V versions at all. This may change in the future, and at that point we might look into creating a version of Heroic for those platforms, but for now we can't do anything about this.
