### ISSUE TITLE
Language: čeština got undefined country flag

### ISSUE THREAD

**Issue by Razuuu** [Heroic-Games-Launcher/HeroicGamesLauncher#346]
Hello,
I have just installed Heroic, I am German myself but saw that "čeština" has no country flag.

kind regards

Razuuu

![Heroic](https://user-images.githubusercontent.com/40471551/117486428-eb5b7b00-af69-11eb-9396-7e06270b843e.png)

**Comment by adityaruplaha** [comment]
Already fixed on latest branch, thanks for reporting though!
