### ISSUE TITLE
Can't log in to GOG

### ISSUE THREAD

**Issue by 1BrentEdward** [Heroic-Games-Launcher/HeroicGamesLauncher#3466]
### Describe the bug

just downloaded the heroic launcher on M1 Mac Sonoma.

when trying to log in to GOG, it tells me the user is not found, but if I log in through a regular webpage, it works fine.

### Add logs

```text
none
```

### Steps to reproduce

2. Click on '...'
3. Scroll down to '...'

### Expected behavior

epect4d behavior is to log in correctly

### Heroic Version

Latest Stable

### System Information

macos sonoma

**Comment by imLinguin** [comment]
GOG is having server issues now, try again later

**Comment by 1BrentEdward** [comment]
If that was the case, then I wouldn’t have been able to log in via the web or their client.

**Comment by imLinguin** [comment]
That was the case, most services should be back online now.
