### ISSUE TITLE
Support Blizzard/Activision as source

### ISSUE THREAD

**Issue by yoshimo** [Heroic-Games-Launcher/HeroicGamesLauncher#347]
**Is your feature request related to a problem? Please describe.**
Having multiple launchers fighting for download bandwith and systray space isn't the best user experience
Same is true for the social features

**Describe the solution you'd like**
Heroic being able to download/install&update from Battle.net, read game news and talk to friends as well as buy games/dlcs/services. Be Notified about deals for your wishlist  and free games

**Describe alternatives you've considered**
GoG  Galaxy launcher.

**Additional context**
Some more infos from others around file formats and protocols

https://github.com/barncastle/Battle.Net-Installer
https://github.com/bartok765/galaxy_blizzard_plugin
https://wowdev.wiki/TACT
https://wowdev.wiki/Ribbit
https://github.com/ladislav-zezula/StormLib/
https://github.com/WoW-Tools/CASCExplorer/
https://github.com/beemdevelopment/Aegis/issues/483

The official launcher uses oauth for authentification.

**Comment by flavioislima** [comment]
Sorry but supporting this is not planned in the near or long future. 
The only Stores that we will support besides Epic are GOG and perhaps Itch.io. 
This would be a lot of work.
Unless some dev wants to try to implement this by themselves since Heroic is open to contributions.
