### ISSUE TITLE
ULWGL support?

### ISSUE THREAD

**Issue by bayazidbh** [Heroic-Games-Launcher/HeroicGamesLauncher#3479]
### Problem description

It seems that GE has made [ULWGL](https://github.com/Open-Wine-Components/ULWGL) which, if I'm reading it right, would allow automatic application of [protonfixes](https://github.com/Open-Wine-Components/ULWGL-protonfixes) if you provide the game ID.

### Feature description

Not entirely sure, but it's supported in [Proton-GE-8-28](https://github.com/GloriousEggroll/proton-ge-custom/releases/tag/GE-Proton8-28). According to the [ULWGL-launcher](https://github.com/Open-Wine-Components/ULWGL-launcher) page, it seems you just need to supply the game ID?

I suppose people would need to build the EGS/GOG/Amazon IDs to [ULWGL IDs](https://github.com/Open-Wine-Components/ULWGL-database) first?

### Alternatives

It might be worth waiting until ULWGL is more mature. I'm just opening this Issue to ask the question if there's any plan to implement it and, if so, how.

**Comment by imLinguin** [comment]
We are directly involved with the project. So this is already planned.

**Comment by shelterx** [comment]
How's the progress going? I haven't seen any updates since the PR was created and it got conflics now with current heroic release.

**Comment by imLinguin** [comment]
Closed by #3724
