### ISSUE TITLE
Allow games to open the browser in Steam Deck Game Mode (Required to play certain games)

### ISSUE THREAD

**Issue by puddydoo** [Heroic-Games-Launcher/HeroicGamesLauncher#3509]
### Problem description

The Atari Recharged series on Epic Games opens a browser on launch to log in to Epic Games. But on Steam Deck, this only works in desktop mode. If playing in game mode, no browser window will open up and the game will appear to be stuck on a "loading" screen, so practically these games are unplayable. Even logging in on desktop and rebooting into game mode doesn't work.

### Feature description

Heroic should be able to open some kind of browser window when prompted by the game while in SteamOS's game mode.

**Comment by arielj** [comment]
We can't do anything there, it's a limitation of steamos in gaming mode.

We just launch the game, everything else is between wine and steamos and we don't have any way to change that.

This is actually a problem of the games asking to authenticate every time, the game's developer should fix that on their side.

**Comment by arielj** [comment]
Closing since we can't control if a browser can open in gaming mode. That's something the steamdeck has to change. We can't do anything about it.
