### ISSUE TITLE
UbiConnect as Source

### ISSUE THREAD

**Issue by yoshimo** [Heroic-Games-Launcher/HeroicGamesLauncher#351]
Is your feature request related to a problem? Please describe.
Having multiple launchers fighting for download bandwith and systray space isn't the best user experience
Same is true for the social features

Describe the solution you'd like
Heroic being able to download/install&update from UbiConnect, read news  and talk to friends as well as buy games/dlcs/services. Be Notified about deals for your wishlist  and free games

Describe alternatives you've considered
GoG Galaxy launcher.

**Comment by flavioislima** [comment]
Same as I answered for the Blizzard issue. #347
