### ISSUE TITLE
Can't download Watch Dogs 2

### ISSUE THREAD

**Issue by nonoche2** [Heroic-Games-Launcher/HeroicGamesLauncher#3513]
### Describe the bug

I'm getting this error when I try to download Watch Dogs 2 :

"(12:25:44) ERROR:   [DownloadManager]:  Downloader: Failed to get headers for https://raw.githubusercontent.com/Heroic-Games-Launcher/known-fixes/main/Angelonia-epic.json. 

Error: Error: Request failed with status code 404"

### Add logs

```text
(12:25:44) ERROR:   [DownloadManager]:  Downloader: Failed to get headers for https://raw.githubusercontent.com/Heroic-Games-Launcher/known-fixes/main/Angelonia-epic.json. 

Error: Error: Request failed with status code 404
```

### Steps to reproduce

1. download Watch Dogs 2

### Expected behavior

it should download the game

### Heroic Version

Latest Stable

### System Information

macOS 14.2.1

**Comment by imLinguin** [comment]
This error alone doesn't prevent download from completing. Please share whole log

**Comment by arielj** [comment]
That error can be ignored.

Watch Dogs 2 cannot be installed by Legendary (which we use to install epic games), it's one special case for the Ubisoft games.

You have to install through UbisoftConnect https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/wiki/How-to-install-Ubisoft-Connect-on-Linux-and-Mac#installing-option-1-standalone-launcher

Though I think UbisoftConnect does not works on MacOS, it needs some fixes from proton that I don't think are available in any wine/crossover on mac.

**Comment by nonoche2** [comment]
in that case it should be reported as "non-available" by Heroic

**Comment by nonoche2** [comment]
> This error alone doesn't prevent download from completing. Please share whole log

(12:25:44) INFO:    [Legendary]:        Installing Angelonia: LEGENDARY_CONFIG_PATH="/Users/nonoche/Library/Application Support/heroic/legendaryConfig/legendary" /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/legendary install Angelonia --platform Windows --base-path /Volumes/Transcend/Heroic --skip-dlcs -y --max-workers 5 --skip-sdl

(12:25:44) DEBUG:   [Legendary]:        Logging to file "/Users/nonoche/Library/Application Support/heroic/GamesConfig/Angelonia.log"

(12:25:44) DEBUG:   [Legendary]:        Using cached install info

(12:25:44) DEBUG:   [Legendary]:        Using cached install info

(12:25:44) ERROR:   [DownloadManager]:  Downloader: Failed to get headers for https://raw.githubusercontent.com/Heroic-Games-Launcher/known-fixes/main/Angelonia-epic.json. 

Error: Error: Request failed with status code 404

(12:25:54) INFO:    [Backend]:          Adding shortcuts for Watch Dogs 2

(12:25:54) INFO:    [DownloadManager]:  Finished Installation of Angelonia

(12:25:55) INFO:    [DownloadManager]:  Angelonia added to download manager finished.

(12:25:55) INFO:    [DownloadManager]:  Angelonia removed from download manager.

(12:25:55) INFO:    [Frontend]:         Refreshing legendary Library

(12:25:55) INFO:    [Legendary]:        Refreshing library...

(12:25:55) INFO:    [Legendary]:        Refreshing Epic Games...

(12:25:55) INFO:    [Legendary]:        Game list updated, got 449 games & DLCs

(12:25:55) INFO:    [Legendary]:        Running command: LEGENDARY_CONFIG_PATH="/Users/nonoche/Library/Application Support/heroic/legendaryConfig/legendary" /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/legendary list --third-party

**Comment by arielj** [comment]
> in that case it should be reported as "non-available" by Heroic

well... yeah, but it's... complicated, I know that's the case for that game because I tested it, but it's not something that comes with the game metadata to detect that programmaticaly and we don't want to hardcode that information in the code in case things change over time

it's a weird edge case (I know only of that game and I think it happens for Far Cry Primal from other reports but I don't own that game)

**Comment by arielj** [comment]
Closing since there's not much to do in this case.

#2432 would solve the underlaying problem and show instructions to the user
