### ISSUE TITLE
Heroic AppImage don't work

### ISSUE THREAD

**Issue by alexbespik** [Heroic-Games-Launcher/HeroicGamesLauncher#3529]
### Describe the bug

After last update heroic AppImage not starting 

### Add logs

```text
Something went wrong trying to read the squashfs image.
ERROR: appimage_shall_not_be_integrated : sqfs_open_image error: /home/alexbespik/Applications/Heroic-2.12.1_4df0e945923d5d86ef62ba85fbb7d5fa.AppImage
AppImageLauncher error: appimage_shall_not_be_integrated() failed (returned -1)
Something went wrong trying to read the squashfs image.
ERROR: appimage_is_terminal_app : sqfs_open_image error: /home/alexbespik/Applications/Heroic-2.12.1_4df0e945923d5d86ef62ba85fbb7d5fa.AppImage
AppImageLauncher error: appimage_is_terminal_app() failed (returned -1)
Something went wrong trying to read the squashfs image.

Cannot mount AppImage, please check your FUSE setup.
You might still be able to extract the contents of this AppImage 
if you run it with the --appimage-extract option. 
See https://github.com/AppImage/AppImageKit/wiki/FUSE 
for more information
open dir error: No such file or directory
    ~/Applications  AppImageLauncher Heroic-2.12.1_4df0e945923d5d86ef62ba85fbb7d5fa.AppImage --appimage-extract                                                                                                                 127 ✘ 
Something went wrong trying to read the squashfs image.
Failed to open squashfs image
```

### Steps to reproduce

Open heroic games launcher

### Expected behavior

Normal work 

### Screenshots

![image](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/assets/122635924/8b46ffd5-3e05-46ae-a68b-35661509ec84)
![image](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/assets/122635924/873397bb-b599-4e0c-a39b-c4a6e5ad9499)

### Heroic Version

Latest Stable

### System Information

- OS Manjaro linux btrfs kde

### Additional information

2.12.1

**Comment by arielj** [comment]
@alexbespik have you followed this link? https://github.com/AppImage/AppImageKit/wiki/FUSE

From that link, the issue is an issue with the version of FUSE in your system and how app images work.

I just tested the latest AppImage and it works fine. Try following the steps listed in that link and it should fix it.
