### ISSUE TITLE
Support Steam as source

### ISSUE THREAD

**Issue by yoshimo** [Heroic-Games-Launcher/HeroicGamesLauncher#353]
Is your feature request related to a problem? Please describe.
Having multiple launchers fighting for download bandwith and systray space isn't the best user experience
Same is true for the social features

Describe the solution you'd like

Heroic being able to download/install&update from Steam, read game news and talk to friends as well as buy games/dlcs/services. Be Notified about deals for your wishlist and free games. Sync Cloud Games.
Download/Install/Update Workshop Items.
Chat with friends.

Describe alternatives you've considered
GoG Galaxy launcher. Official Steam Client.

Notes:
https://github.com/X2CommunityCore/xcom2-launcher as a community attempt of an additional interface is a nice thing that could be merged, but so far requires steam running. 
Probably a complex research task to see what is and what isn't possible with CEG and DRM of some games.

**Comment by flavioislima** [comment]
Would be nice to have but Steam is closed source and the best we could have would be to launch the games from Heroic, but would work like Lutris. It would open the Steam Launcher and then launch the game.
98% of Steam games have DRM so it is not possible to launch them without opening the Steam Launcher which I consider not pratical.
