### ISSUE TITLE
Heroic on Pop!_OS doesn't recognize proton experimental. 

### ISSUE THREAD

**Issue by LukasHaefele** [Heroic-Games-Launcher/HeroicGamesLauncher#354]
I got the launcher to boot GTA V on Linux since the Lutris launcher seems broken for the time being. The guide said to use proton experimental (and all other wine versions don't seem to work anyhow) but the launcher doesn't see Proton Experimental in the /.wine Folder as a prefix.

1. Installed steam and Proton Experimental through it
2. installed heroic
3. started heroic searched for proton couldn't find it in the prefixes

**Expected behavior**
I thought Proton should show in the wine dropdown as in all the tutorials I saw

- OS: Pop!_OS 
- Version: 20.10
- Game: GTA V
- Wine/Proton version: Proton Experimental (But I can't see any Proton for that matter)

My guess would be I'd have to select a different prefix folder but I can't seem to get the hang of how to do that

**Comment by adityaruplaha** [comment]
Ubuntu and Pop!_OS have Proton in noon standard directories. They're not supported.

**Comment by flavioislima** [comment]
> Ubuntu and Pop!_OS have Proton in noon standard directories. They're not supported. 

It's is not that they are not supported. Is that we didn't have time to add their directories to the search.
Maybe let's keep this opened and try to implement on next release.

**Comment by LukasHaefele** [comment]
Alright thanks, can I add it as a custom prefix?

**Comment by flavioislima** [comment]
> Alright thanks, can I add it as a custom prefix?

Yes, for now you can just add as custom. Make sure to select the proton binary, not the wine one.

**Comment by LukasHaefele** [comment]
Yeah that's my problem, I don't know what filetype that is, I think I know where about it would be located

**Comment by flavioislima** [comment]
Fixed on #359
