### ISSUE TITLE
Configuration not changed when i place a new proton

### ISSUE THREAD

**Issue by Aisyk** [Heroic-Games-Launcher/HeroicGamesLauncher#355]
**Describe the bug**
Games not launching

**To Reproduce**
Steps to reproduce the behavior :

1. Install game (Example : Pine)
2. Copy Proton 6.5 GE-2 in "./config/heroic/tools'
3. Launch
4. Play game

### Changing Proton version deleting ancient 6.5 GE-2

1. Go to '/.config/heroic/tools/'
2. Copy your Proton folder (from your Steam directory), named Proton 6.8 GE-1 (for example)
3. Change your Proton option for listed Proton 6.8 GE-1
4. Launch game
5. See error file

**Log with error**
[cli] INFO: Logging in...
[Core] INFO: Trying to re-use existing login session...
[cli] INFO: Checking for updates...
[Core] INFO: Getting authentication token...
[cli] INFO: Launching 03b7b25a77024cc0adf44777f791ffc4...
Traceback (most recent call last):
  File "legendary/cli.py", line 1375, in <module>
  File "legendary/cli.py", line 1341, in main
  File "legendary/cli.py", line 512, in launch_game
  File "subprocess.py", line 854, in init
  File "subprocess.py", line 1702, in _execute_child
FileNotFoundError: [Errno 2] No such file or directory: '/home/aisyk/.config/heroic/tools/proton/Proton-6.5-GE-2/proton'
[370963] Failed to execute script cli

### Replace the ancient Proton 6.5 GE-2 in the directory without changing options.

[cli] INFO: Logging in...
[Core] INFO: Trying to re-use existing login session...
[cli] INFO: Checking for updates...
[Core] INFO: Getting authentication token...
[cli] INFO: Launching 6d564ff21f9c45b7b782b7113ad60be8...
gamemodeauto: 
wineserver: using server-side synchronization.
002c:fixme:winediag:LdrInitializeThunk Wine TkG (staging) 6.0-rc1 is a testing version containing experimental patches.
002c:fixme:winediag:LdrInitializeThunk Please don't report bugs about it on winehq.org and use https://github.com/Frogging-Family/wine-tkg-git/issues instead.
skipping config: /home/aisyk/.config/MangoHud/wine-explorer.conf [ not found ]
skipping config: /home/aisyk/.local/share/lutris/runners/wine/lutris-6.0-rc1-x86_64/bin/MangoHud.conf [ not found ]
skipping config: /home/aisyk/.config/MangoHud/wine64-preloader.conf [ not found ]
parsing config: /home/aisyk/.config/MangoHud/MangoHud.conf [ ok ]

Game with default Wine launched

### Game with Proton 6.5 GE-2 in options

[cli] INFO: Logging in...
[Core] INFO: Trying to re-use existing login session...
[cli] INFO: Checking for updates...
[Core] INFO: Getting authentication token...
[cli] INFO: Launching 6d564ff21f9c45b7b782b7113ad60be8...
gamemodeauto: 
ERROR: ld.so: object '/usr/$LIB/libgamemodeauto.so.0' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object '/usr/$LIB/libgamemodeauto.so.0' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
wineserver: using server-side synchronization.
skipping config: /home/aisyk/.config/MangoHud/wine-explorer.conf [ not found ]
skipping config: /home/aisyk/.config/heroic/tools/proton/Proton-6.5-GE-2/dist/bin/MangoHud.conf [ not found ]
skipping config: /home/aisyk/.config/MangoHud/wine64-preloader.conf [ not found ]
parsing config: /home/aisyk/.config/MangoHud/MangoHud.conf [ ok ]
gamemodeauto: 

**Expected behavior**
Launching game :)

**Desktop (please complete the following information):**

- OS: [PopOS]
- Version [ 20.10]
- Game: Pine, Absolut Drift
- Wine/Proton version: 6.8 (system), 6.0-rc1 (heroic), proton 6.5-ge-2, proton 6.8-ge-1

**Additional context**

**Comment by flavioislima** [comment]
Hi!

I didn't get it. The settings are not being updated when you change them? Or do you want heroic to discover that the old proton was deleted and update the config with the new one on the folder?

**Comment by Aisyk** [comment]
Sorry if I misspoke,

For example,

When i select a Proton version 6.5-GE-2 (installed in /.config/heroic/tools/ ) in the options of my game, the game is not launched and this is the message i have in the error log : 
```
[cli] INFO: Logging in...
[Core] INFO: Trying to re-use existing login session...
[cli] INFO: Checking for updates...
[Core] INFO: Getting authentication token...
[cli] INFO: Launching 6d564ff21f9c45b7b782b7113ad60be8...
gamemodeauto: 
ERROR: ld.so: object '/usr/$LIB/libgamemodeauto.so.0' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object '/usr/$LIB/libgamemodeauto.so.0' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
wineserver: using server-side synchronization.
skipping config: /home/aisyk/.config/MangoHud/wine-explorer.conf [ not found ]
skipping config: /home/aisyk/.config/heroic/tools/proton/Proton-6.5-GE-2/dist/bin/MangoHud.conf [ not found ]
skipping config: /home/aisyk/.config/MangoHud/wine64-preloader.conf [ not found ]
parsing config: /home/aisyk/.config/MangoHud/MangoHud.conf [ ok ]
gamemodeauto: 
```

Ok, so i delete this version of Proton, because the game don't launch with it. If i try to launch the game, with Proton deleted (and don't change anything to my configuration), game don't launch with error of non existent Proton version.

If i change Proton version with a new one (6.8-GE-1) in .config/heroic/tools/
And change it in the options, game not launched too.

[proton-bug.txt](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/files/6468792/proton-bug.txt)

So none of theses Proton versions functions with Absolut Drift, Pine, Deponia (games i tested).

I go through the options in the game, select Wine, the game launched with wine, ok.
And i don't have mangohud, gamemode activated (they are installed, in launch them with my steam games), they are activated in the heroic options.

**Comment by flavioislima** [comment]
Are you putting the proton under the tools folder or under the tools/proton/ folder?nshouod be the second one. I mean, extract the proton you downloaded inside the proton folder in the tools folder. 
On the wiki, you can find more info about how to use wine and proton with heroic.

Also, run heroic from the terminal and post here the launch command when you launch a game. So we can see if it is using the right binary.

**Comment by Aisyk** [comment]
Sorry, it is the /tools/proton folder : 
![Capture d’écran du 2021-05-13 01-04-15](https://user-images.githubusercontent.com/5584650/118054776-2a813600-b387-11eb-9cb2-e4fa55aeab5e.png)

When i launch a game (Pine) with wine :
```
aisyk@pop-os:~$ heroic
Protocol already registered.
launching 6d564ff21f9c45b7b782b7113ad60be8

 Launch Command: PULSE_LATENCY_MSEC=60    MANGOHUD=1 /usr/bin/gamemoderun /opt/heroic/resources/app.asar.unpacked/build/bin/linux/legendary launch 6d564ff21f9c45b7b782b7113ad60be8  --wine '/home/aisyk/.local/share/lutris/runners/wine/lutris-6.0-rc1-x86_64/bin/wine64' --wine-prefix '/home/aisyk/.wine' 
```

Launching Pine with proton (game not launched)
```
launching 6d564ff21f9c45b7b782b7113ad60be8

 You are using Proton, this can lead to some bugs, 
              please do not open issues with bugs related with games Proton - Proton-6.5-GE-2

 Launch Command: PULSE_LATENCY_MSEC=60   STEAM_COMPAT_DATA_PATH='/home/aisyk/.wine' MANGOHUD=1 /usr/bin/gamemoderun /opt/heroic/resources/app.asar.unpacked/build/bin/linux/legendary launch 6d564ff21f9c45b7b782b7113ad60be8  --no-wine --wrapper "'/home/aisyk/.config/heroic/tools/proton/Proton-6.5-GE-2/proton' run" 
```
And the error log for the game :
```
[cli] INFO: Logging in...
[Core] INFO: Trying to re-use existing login session...
[cli] INFO: Checking for updates...
[Core] INFO: Getting authentication token...
[cli] INFO: Launching 6d564ff21f9c45b7b782b7113ad60be8...
gamemodeauto: 
ERROR: ld.so: object '/usr/$LIB/libgamemodeauto.so.0' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object '/usr/$LIB/libgamemodeauto.so.0' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
wineserver: using server-side synchronization.
skipping config: /home/aisyk/.config/MangoHud/wine-explorer.conf [ not found ]
skipping config: /home/aisyk/.config/heroic/tools/proton/Proton-6.5-GE-2/dist/bin/MangoHud.conf [ not found ]
skipping config: /home/aisyk/.config/MangoHud/wine64-preloader.conf [ not found ]
parsing config: /home/aisyk/.config/MangoHud/MangoHud.conf [ ok ]
gamemodeauto: 
```

**Comment by flavioislima** [comment]
@Aisyk Looks correct.

About the game, I downloaded it here and it doesn't work with Proton-GE for me as well but worked with Proton Experimental.
So I think this is not and Heroic issue but a Proton/Wine one.

Try again with Proton Experimental.
Since you're using Pop_OS I guess Heroic won't find Steam installed Proton, we are working to fix this issue.
So you have two options: create a symbolic link from the Proton Experimental to the heroic proton folder or add it as a custom Proton on the Heroic General Settings. Just make sure to select the proton binary and not the wine one. So it will appear as `Custom Proton` on your wine settings.

**Comment by Aisyk** [comment]
Ok, 

I've tryed with another game : Absolute Drift, and with a copied Proton - Experimental in heroic proton folder, it works ! (Pine too)
(same error with Absolute Drift and Proton 6.5-GE-2)

Seems to be two buggued versions of Proton 6.5-GE-2 and Proton 6.8-GE-1...

Thanks for your responses !

**Comment by adityaruplaha** [comment]
Closing since this is not a Heroic issue and has been resolved.
