### ISSUE TITLE
Problem with games

### ISSUE THREAD

**Issue by TheRealDarkn3ss** [Heroic-Games-Launcher/HeroicGamesLauncher#356]
_**Bug**_
The launcher cancels its installation by itself, it cancels between 70-75%.

_**Game tested**_
Rocket League, I just tested like Roller Coaster Tycoon 3 and happens the same thing, I used Lutris once a time, but it lags terrible and I want to try this launcher.

_**System used**_
Linux Mint

Help is appreciated

**Comment by flavioislima** [comment]
Duplicate of #195
