### ISSUE TITLE
Cannot open a store page after logging in.

### ISSUE THREAD

**Issue by Giger22** [Heroic-Games-Launcher/HeroicGamesLauncher#3569]
### Describe the bug

After I logged in to GOG I cannot refresh and I cannot see its store page.

### Add logs

```text
No logs.
```

### Steps to reproduce

1. Logint to GOG.
2. Click on Stores->GOG Store
3. Blank screen

### Expected behavior

Normal store page.

### Screenshots

[Screenshot](https://imgur.com/DkRFFs4)

### Heroic Version

Latest Stable

### System Information

- OS [e. g. "Ubuntu"]: Artix Linux OpenRC

**Comment by Giger22** [comment]
[Amazon](https://imgur.com/a6MNB26)

**Comment by imLinguin** [comment]
Heroic redirects the store page through our partner link starting 2.13.0. As it's handled by `adtraction` this is what happens when the adtraction domain is blocked. We'll provide a option to disable partner links in the future

**Comment by Giger22** [comment]
Yeah, you are right. I just checked and Portmaster blocked track.adtraction.com when attempting to connect.

**Comment by imLinguin** [comment]
The partner link we got from GOG works that way. This is their way to detect what purchases were made after being redirected through such link.

**Comment by 8BitCerberus** [comment]
Ahhh! I've been wondering why all of the sudden GOG hasn't been working. I guess it's been my Pi-hole. Do you get any benefit from the partner link, or is it only for GOG's tracking/metrics? If you are getting any percentage of sales made with the partner link I'd be happy to whitelist adtraction, but if not I'll keep it blocked and wait for the fallback workaround.

**Comment by arielj** [comment]
> Ahhh! I've been wondering why all of the sudden GOG hasn't been working. I guess it's been my Pi-hole. Do you get any benefit from the partner link, or is it only for GOG's tracking/metrics? If you are getting any percentage of sales made with the partner link I'd be happy to whitelist adtraction, but if not I'll keep it blocked and wait for the fallback workaround.

we get a % of the games purchased if that link is followed

**Comment by bnthn** [comment]
It could be beneficial to provide the specific partner link e.g. inside the readme so people can add an exception to their adblockers

**Comment by imLinguin** [comment]
I think the modal that is shown when adtraction fails to load is clear enough about the domain.  
![obraz](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/assets/62100117/9b7ff7fb-a368-4c9f-a2a1-f088c0de55a9)
