### ISSUE TITLE
Infinite Loading games list

### ISSUE THREAD

**Issue by ciolast** [Heroic-Games-Launcher/HeroicGamesLauncher#357]
Hi all. I have a problem with Heroic, I tried to install it with the AUR package, and it runs fine.
But when I paste my SID, and then click Enter, nothing happens, there is only an infinite loading games list.
When I launch Heroic on the terminal, there is an error.

[<a href="https://ibb.co/1Jr7N1S"><img src="https://i.ibb.co/S7t5gbL/Screenshot-20210512-164006.png" alt="Screenshot-20210512-164006" border="0"></a><br />](url)

Someone knows how I can fix it?

**Comment by flavioislima** [comment]
For some reason your credentials are messed up. Hard to know the reason. Have you tried again, generating a new Sid? 
Try to Delete the folder `.config/legendary` to start completely fresh as well.

**Comment by ciolast** [comment]
Thank you, the solution was found quickly, I deleted the folder, then clicked on the epic link, and there it worked. 
Thank you again for your help.

**Comment by flavioislima** [comment]
> Thank you, the solution was found quickly, I deleted the folder, then clicked on the epic link, and there it worked. 
> Thank you again for your help.

Nice! You're welcome!
