### ISSUE TITLE
High temperatures on Steam Deck when downloading games from GOG, and a few more problems

### ISSUE THREAD

**Issue by Terefere85** [Heroic-Games-Launcher/HeroicGamesLauncher#3579]
### Describe the bug

After last update (2.13), there are a few problems with GOG integration. 
First of all, when downloading or updating a game, GOGDL process heats up Steam Deck (thermal_zone0 - acpitz) from 47*C (idle) to 75*C (when downloading GOG games). When using Heroic to download from Epic, there is no problem, and temp is max 52*C
Second one - updating GOG games don't work - they are installing from scratch. Example - Cyberpunk 2077 patch is 3.5GB... and heroic downloads whole 90GB game... and when paused, whole progress is lost. 
Third one - many games stopped working. Cyberpunk 2077 gets error, or black screen when trying to launch. RDR2 is loading extremely slow, and after that it gets black screen. 
In my case, launching GOG on my Steam Deck OLED is not possible with latest Heroic Launcher version. 

### Add logs

```text
No
```

### Steps to reproduce

Just try to download any game. 

### Expected behavior

Fix temperature and download issues... or get back to older GOGDL file. 

### Heroic Version

Latest Stable

### System Information

Steam OS - Steam Deck OLED

**Comment by imLinguin** [comment]
Solution is to limit max number of download threads in Heroic settings

**Comment by Emurikku** [comment]
Hello,
I can confirm that I also had to download the whole game in order to install version 2.11 of “Cyberpunk 2077”. Can’t say for the temperatures, but noticed downloading from GOG is also significantly faster than from Epic.

**Comment by imLinguin** [comment]
> Example - Cyberpunk 2077 patch is 3.5GB... and heroic downloads whole 90GB game... and when paused, whole progress is lost.

Progress is never lost, it's just always counted from 0%, it's always picked up where it's been left off. If you are referring to the number in the download queue below the game title, it always shows full game size at the moment (also for Epic games)

**Comment by Terefere85** [comment]
> > Example - Cyberpunk 2077 patch is 3.5GB... and heroic downloads whole 90GB game... and when paused, whole progress is lost.
> 
> Progress is never lost, it's just always counted from 0%, it's always picked up where it's been left off. If you are referring to the number in the download queue below the game title, it always shows full game size at the moment (also for Epic games)

Unfortunately it is lost in my case. Like I said Cyberpunk patch is ~3.5gb - it takes ~20min to download with my PC. Using Steam Deck after 4 hours, progress bar showed about 40% complete (at full speed) and looking by Steam Deck storage, there were clearly 30-40gb less storage than before installation (installed that game a few times, and checked it almost every time). When I pause installation disk space is "free" again, and whole process starts from the beginning. 
There is no problem with Epic games - RDR2 patch was about ~200mb and it downloaded just that. I have tested "pause" on other game when installing it and on Epic, it just continued the installation as it should.


> Solution is to limit max number of download threads in Heroic settings

Where can I find this setting?

**Comment by imLinguin** [comment]
The setting is at the bottom of general heroic settings

**Comment by Terefere85** [comment]
> The setting is at the bottom of general heroic settings

Already have it on "1", and still it heats my Steam Deck like crazy. 
Before 2.13 update there were no problems, and games were working great.

**Comment by imLinguin** [comment]
All right, tracked down the issue. This build should solve it https://github.com/Heroic-Games-Launcher/heroic-gogdl/actions/runs/7964724004

Test instructions:
1. Get gogdl-Linux file from link above
2. Extract the zip
3. Move gogdl file to ~/Games/Heroic
4. In file properties under permissions make sure that gogdl is executable
5. In Heroic settings > advanced, select just extracted gogdl as alternative executable

Enjoy

**Comment by Terefere85** [comment]
> All right, tracked down the issue. This build should solve it https://github.com/Heroic-Games-Launcher/heroic-gogdl/actions/runs/7964724004
> 
> Test instructions:
> 
>     1. Get gogdl-Linux file from link above
> 
>     2. Extract the zip
> 
>     3. Move gogdl file to ~/Games/Heroic
> 
>     4. In file properties under permissions make sure that gogdl is executable
> 
>     5. In Heroic settings > advanced, select just extracted gogdl as alternative executable
> 
> 
> Enjoy

It seems it worked. Games are updating as before, some of them (Cyberpunk) are finally able to run without problems, and temperatures are not that high... but they are still over 60*C, when Epic Games download temperatures are 10*C lower

**Comment by tarasis** [comment]
Wondering if your third issue is what I'm running into with Tomb Raider Remastered. Installed fine, runs via Heroic directly (but for Keyboard), but doesn't launch from Steam, just shows the spinning Steam Logo and FPS it jittery 24-25fps.
