### ISSUE TITLE
Discord link invalid

### ISSUE THREAD

**Issue by manschwetus** [Heroic-Games-Launcher/HeroicGamesLauncher#3582]
### Describe the bug

The discord invitation behind the discord links is invalid

### Add logs

```text
Not needed
```

### Steps to reproduce

1. Go to new bug
2. Click on "open" next to "Have a issue with running a game? Please ask on our Discord instead"
3. See error

### Expected behavior

Discord channel opens

### Heroic Version

Latest Stable

### System Information

- OS [e. g. "Ubuntu"]: ANY

**Comment by imLinguin** [comment]
Hmm, it worked just fine.  
The link is https://discord.com/invite/rHJ2uqdquK

Can anyone else reproduce the issue?

**Comment by arielj** [comment]
I clicked the button in Heroic and it opened the Discord server for me

**Comment by imLinguin** [comment]
I just confirmed in Discord server settings, the link is and will be valid forever. Not sure what error you were presented with. Closing this as the link is in fact valid

**Comment by manschwetus** [comment]
Ok I rechecked, it looks like the invite can only be used when having a discord account or you have to create one

**Comment by manschwetus** [comment]
@imLinguin is it intended, that I need to have a discord account, to use the invite?

**Comment by imLinguin** [comment]
This is how discord operates, it's nothing we control in any way
