### ISSUE TITLE
HGL showing offline banner, even though I'm definitely online

### ISSUE THREAD

**Issue by JonAbrams** [Heroic-Games-Launcher/HeroicGamesLauncher#3603]
### Describe the bug

HGL was working fine for me for a while until suddenly one day I had these issues:

1. In Heroic Games Launcher, there's a purple banner at the top that says "Offline (ignore)". Clicking ignore does nothing. I'm definitely online!
2. Launching games from Steam's Gaming Mode just shows the Steam loading spinner forever. Doesn't matter which game, as long as it was added to Steam by Heroic. Launching games from within HGL still works ok.

### Add logs

```text
(00:25:14) INFO:    [Legendary]:        Legendary location: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary
(00:25:14) INFO:    [Gog]:              GOGDL location: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl
(00:25:14) INFO:    [Connection]:       Connectivity: check-online
(00:25:14) INFO:    [Connection]:       Pinging external endpoints
(00:25:14) INFO:    [Gog]:              Checking for existing gog manifests
(00:25:14) INFO:    [Nile]:             Refreshing library...
(00:25:14) INFO:    [Nile]:             Refreshing Amazon Games...
(00:25:14) INFO:    [Nile]:             Running command: NILE_CONFIG_PATH=/home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/nile_config /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/nile library sync
(00:25:14) INFO:    [Nile]:             Game list updated, got 424 games
(00:25:14) INFO:    [Backend]:          DRM module staus {
  "oimompecagnajdejgnnjijobebaeigek": {
    "name": "Widevine Content Decryption Module",
    "status": "new",
    "version": "4.10.2710.0"
  }
}
(00:25:14) WARNING: [Backend]:          Failed to register protocol with OS.
(00:25:14) INFO:    [Legendary]:        Running command: LEGENDARY_CONFIG_PATH=/home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/legendaryConfig/legendary /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary --version
(00:25:14) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH=/home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/gogdlConfig /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json --version
(00:25:14) INFO:    [Nile]:             Running command: NILE_CONFIG_PATH=/home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/nile_config /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/nile --version
(00:25:14) INFO:    [Connection]:       Connectivity: online
(00:25:14) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH=/home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/gogdlConfig /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth
(00:25:14) INFO:    [Gog]:              Checking if login is valid
(00:25:14) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH=/home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/gogdlConfig /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth
(00:25:14) INFO:    [Backend]:          AreWeAntiCheatYet data downloaded
(00:25:15) INFO:    [Backend]:
System Information:
CPU: 8x AMD Custom APU 0405
Memory: 15.53 GB (used: 2.99 GB)
GPUs:
  GPU 0:
    Name: Advanced Micro Devices, Inc. [AMD/ATI] Sephiroth [AMD Custom GPU 0405]
    IDs: D=1435 V=1002 SD=0123 SV=1002
    Driver: amdgpu
OS: SteamOS 3.5.7 holo (linux)

The current system is a Steam Deck (model: OLED) in desktop mode
We are running inside a Flatpak container

Software Versions:
  Heroic: 2.13.0 Dorry & Broggy
  Legendary: 0.20.34 Direct Intervention
  gogdl: 1.0.0
  Nile: 1.0.1 Jonathan Joestar

(00:25:15) INFO:    [Backend]:          Checking for current version changelog
(00:25:15) INFO:    [Gog]:              Saved username to config file
(00:25:17) INFO:    [Winetricks]:       Downloading Winetricks
(00:25:19) INFO:    [WineDownloader]:   Updating wine versions info
(00:25:19) INFO:    [WineDownloader]:   Fetching upstream information...
(00:25:20) INFO:    [WineDownloader]:   wine versions updated
```

### Steps to reproduce

1. Download a game from any source in Heroic Game Launcher
2. Click "Add to Steam" in the game's 3-dot menu
3. In Steam's Gaming Mode, launch the game.

### Expected behavior

I expect launching games (added via HGL) in Gaming Mode to load, and not be stuck on a spinner.

### Heroic Version

Latest Stable

### System Information

- OS [e. g. "Ubuntu"]: SteamOS 3.5.7 holo (linux)
 

### Additional information

I've tried:
- Uninstalling and re-installing HGL via Discover. 
- Resetting HGL via the Settings -> Advanced -> Reset Heroic.

**Comment by JonAbrams** [comment]
Fixed it by signing out of Amazon Games. When I try to sign in again, I just see a spinner. Games now start when launched from Steam of the `flatpak run …` command.

**Comment by chronohart** [comment]
I've been experiencing what seems to be the same issue. I don't launch any HGL games in Steam, but HGL has been showing me the Offline banner constantly for weeks now and I haven't been able to install any Amazon games. After finding this issue, finally, I tried logging out of Amazon and the banner immediately went away. When I try logging in to Amazon again, it simply spins forever with "Preparing Login..."

**Comment by arielj** [comment]
Closing as the issue seems to have been related to the amazon integration.

`nile` was updated in the latest release so login should work fine now

we can reopen if the issue persists

**Comment by moorejon** [comment]
I just experienced what appears to be the same issue. Version 2.18.0. logging out of Amazon account resolved games not starting. Attempting to log back in results in the same spinning animation and login page never loads.

This seems like either the error message is inaccurate or the logic is faulty given it stops all games from working.

Great tool thanks for your hard work.

**Comment by GMMan** [comment]
I'm getting the same thing currently with 2.20.1. Logging out of Amazon also stopped the banner. With the app thinking it's offline, games do not launch at all directly from Steam. One dependent library breaking should not affect the overall online status (especially one that doesn't provide in-game services at all), and shouldn't affect the ability to launch games not associated with that service either. Launch from Steam should also not stay stuck if the launcher thinks it's not online, instead prompting like it does when launching from within Heroic. Personally, I don't think being offline should affect the ability to launch at all. If there's an error caused by that, display the error, otherwise do a best effort to launch. Launching should not be preempted by (erroneous) determinations of being offline.
