### ISSUE TITLE
Add "XCURSOR_PATH" environment variable to the Flatpak manifest by default

### ISSUE THREAD

**Issue by severtheskyline** [Heroic-Games-Launcher/HeroicGamesLauncher#3624]
### Problem description

When running Heroic natively in Wayland using the Flatpak version, the cursor looks completely different than your desktop/theme's cursor, this doesn't happen when the app runs natively on Wayland in a native environment (like installed via the AUR on Arch) or when running on Xwayland both on the flatpak and native versions. It looks something like this:

https://youtu.be/33kftEOxXbQ
(I wanted to upload on github directly, but I guess they can't fathom the idea of a 19 mb video file. And don't worry, the 2007 xbox 360 gameplay quality goes away in a couple of seconds.)

### Feature description

However, when adding "XCURSOR_PATH=/run/host/user-share/icons:/run/host/share/icons" as an environment variable in the flatpak manifest, now it can properly see the cursor your desktop/theme uses. This is also used in [Vesktop](https://github.com/flathub/dev.vencord.Vesktop/blob/master/dev.vencord.Vesktop.yml#L26) which fixes the same issue, and should fix #3236 since it seems to fix the issue when overriding it in the command line. It should look something like this:

https://youtu.be/nPGYLBirwIk
(Same story as before)

### Alternatives

In the mentioned #3236, it was mentioned that this was a Chromium specific issue and that Heroic couldn't really fix it, so I'm not sure if this counts as a hacky fix and if a proper Chromium fix is needed/wanted, however, it seemed that this fixes the same issue on Vesktop, so I'm not sure how "hacky" this could be.

### Additional information

Not much other than technical details I may or may not fully understand about the flatpak sandbox (?

**Comment by severtheskyline** [comment]
>  This Wayland protocol [is supported by every major compositor except Gnome](https://wayland.app/protocols/cursor-shape-v1#compositor-support)

So tipical ain't it

Anyway, is Heroic stuck in a specific electron/chromium version?

**Comment by severtheskyline** [comment]
If I attempt for markdown more my computer will explode- Yeah, sorry about that first comment.

And for that second one, I guess it could be added for the time being, if anything for compositors that doesn't implement it when it is generally adopted by Electron apps and other compositors.

**Comment by dariox86** [comment]
This is fixed for me in the latest version. I am on GNOME Wayland. I have «ELECTRON_OZONE_PLATFORM_HINT=wayland» environment variable.

**Comment by Etaash-mathamsetty** [comment]
Closing, since we use Electron 31 now
