### ISSUE TITLE
many random GOG games listed as "not installable"

### ISSUE THREAD

**Issue by twiztedtbone** [Heroic-Games-Launcher/HeroicGamesLauncher#3636]
### Describe the bug

GOG account (and only that, no Epic/Amazon) successfully linked, have two games currently installed that I play frequently. Upon opening Heroic, on the Library tab, many games are listed as not installable with the message: "This game doesn't appear to be installable. Check downloadable content on https://gog.com/account". Checking my GOG account shows the games are all perfectly available for download.

I have played many of these games previously via Lutris/Bottles, so I know they're both a) available and b) work on Linux.

### Add logs

```text
(18:04:49) INFO:    [Legendary]:        Legendary location: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary
(18:04:49) INFO:    [Gog]:              GOGDL location: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl
(18:04:49) INFO:    [Connection]:       Connectivity: check-online
(18:04:49) INFO:    [Connection]:       Pinging external endpoints
(18:04:49) INFO:    [Gog]:              Checking for existing gog manifests
(18:04:49) INFO:    [Backend]:          DRM module staus {
  "oimompecagnajdejgnnjijobebaeigek": {
    "name": "Widevine Content Decryption Module",
    "status": "new",
    "version": "4.10.2710.0"
  }
}
(18:04:49) WARNING: [Backend]:          Protocol already registered.
(18:04:49) INFO:    [Legendary]:        Running command: LEGENDARY_CONFIG_PATH=/home/username/.config/heroic/legendaryConfig/legendary /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary --version
(18:04:49) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH=/home/username/.config/heroic/gogdlConfig /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/username/.config/heroic/gog_store/auth.json --version
(18:04:49) INFO:    [Nile]:             Running command: NILE_CONFIG_PATH=/home/username/.config/heroic/nile_config /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/nile --version
(18:04:49) INFO:    [Connection]:       Connectivity: online
(18:04:49) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH=/home/username/.config/heroic/gogdlConfig /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/username/.config/heroic/gog_store/auth.json auth
(18:04:49) INFO:    [Backend]:          User Not Found, removing it from Store
(18:04:49) INFO:    [Gog]:              Checking if login is valid
(18:04:49) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH=/home/username/.config/heroic/gogdlConfig /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/username/.config/heroic/gog_store/auth.json auth
(18:04:49) INFO:    [Backend]:          
System Information:
CPU: 16x 11th Gen Intel(R) Core(TM) i7-11700F @ 2.50GHz
Memory: 33.52 GB (used: 9.01 GB)
GPUs:
  GPU 0:
    Name: NVIDIA Corporation GA102 [GeForce RTX 3080 Ti]
    IDs: D=2208 V=10de SD=3955 SV=3842
    Driver: nvidia
OS: Arch Linux 6.8.1-arch1-1 (linux)

The current system is not a Steam Deck
We are not running inside a Flatpak container

Software Versions:
  Heroic: 2.13.0 Dorry & Broggy
  Legendary: 0.20.34 Direct Intervention
  gogdl: 1.0.0
  Nile: 1.0.1 Jonathan Joestar

(18:04:49) INFO:    [Frontend]:         Refreshing undefined Library
(18:04:49) WARNING: [Backend]:          refresh not implemented on Sideload Library Manager
(18:04:49) INFO:    [Legendary]:        Refreshing library...
(18:04:49) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH=/home/username/.config/heroic/gogdlConfig /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/username/.config/heroic/gog_store/auth.json auth
(18:04:49) INFO:    [Backend]:          Frontend Ready
(18:04:49) INFO:    [Gog]:              Getting GOG library
(18:04:49) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH=/home/username/.config/heroic/gogdlConfig /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/username/.config/heroic/gog_store/auth.json auth
(18:04:49) INFO:    [Backend]:          Checking for new Heroic Updates
(18:04:49) INFO:    [Backend]:          AreWeAntiCheatYet data downloaded
(18:04:49) INFO:    [Backend]:          Checking for current version changelog
(18:04:50) INFO:    [Gog]:              Saved username to config file
(18:04:51) INFO:    [Winetricks]:       Downloading Winetricks
(18:04:54) INFO:    [WineDownloader]:   Updating wine versions info
(18:04:54) INFO:    [WineDownloader]:   Fetching upstream information...
(18:04:54) INFO:    [Backend]:          Starting the Download Queue
(18:04:58) INFO:    [WineDownloader]:   wine versions updated
```

### Steps to reproduce

1. Open Heroic, navigate to Library tab
1.5. See that many games are uninstallable
2. Click on an uninstallable game
2.5. See the aforementioned message in full

### Expected behavior

For the uninstallable games to be installable

### Screenshots

![heroic_gog_issue_1](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/assets/65798752/085a482c-a2da-4bbf-bba3-a54f4e0d4e09)
![heroic_gog_issue_2](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/assets/65798752/cd99d639-00a8-4df7-8825-7bd0d5c6a6d4)

### Heroic Version

Latest Stable

### System Information

- Arch (up to date)
  - Heroic installed via AUR (heroic-games-launcher-bin)
  - GNOME/X11
- 11700F
- 3080Ti
- 32G RAM

**Comment by Lariaa** [comment]
Have a look if there is a second entry for those games.
We right now don't collapse demos, dlcs, packages and bonus material into one entry and if you are looking at let's say a soundtrack entry, the "not installable" label is correct.

**Comment by Periyte** [comment]
It happens randomly in my library too, with games from GOG (not goodies or else).

**Comment by twiztedtbone** [comment]
> Have a look if there is a second entry for those games. We right now don't collapse demos, dlcs, packages and bonus material into one entry and if you are looking at let's say a soundtrack entry, the "not installable" label is correct.

I don't believe this to be the case, certainly not with over 33% (I'm lowballing in lieu of actually counting, but it's a lot, approaching half) of my GOG games.

Here is, for example, Plague Tale's entry on gog.com; no second entry, no DLC, no soundtrack, etc.:
![heroic_gog_issue_3](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/assets/65798752/271de707-64d9-4bc9-afdf-504b77a6c859)

**Comment by arielj** [comment]
This seems to happen when, for some reason, heroic can't fetch the content information from GOG's API https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/pull/2759/files#diff-14645ea20292edb3fd5d19b27f1551d877765ccf5bd6f49e252aa657a564696eR644

then `installable` is undefined or false and it ends up showing that message

I'm not sure why it's failing to connect though, we probably should add some logs when that happens. here for example https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/pull/2950/files#diff-14645ea20292edb3fd5d19b27f1551d877765ccf5bd6f49e252aa657a564696eR200

any thoughts on this @imLinguin ?

**Comment by imLinguin** [comment]
I guess this issue should be reduced by axios connection re-use. However we can also consider completely removing this check and check for this while getting install info

**Comment by hardpenguin** [comment]
Also affected by this, closing the app and starting it up again only caused different group of games to be affected than the first time.

**Comment by cortu01** [comment]
> Also affected by this, closing the app and starting it up again only caused different group of games to be affected than the first time.

Same issue here. I would add that I see the same few games having installation enabled/disabled each time I reload the app. Vast majority of games remains uninstallable. Alternate software does not exhibit this problem.

**Comment by SkalCore** [comment]
same behaviour here,,,it is a littlebit annoying

**Comment by arielj** [comment]
can anyone try the build from this PR https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/pull/3700 ?

**Comment by Periyte** [comment]
> can anyone try the build from this PR #3700 ?

I tested it with a clean install on Windows and I didn't notice any game marked as "Not Installable" this time. I wonder if it didn't improve library fetching process speed too.

**Comment by shakeyourbunny** [comment]
> can anyone try the build from this PR #3700 ?

I downloaded the AppImage artifact from https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/actions/runs/8696093997, as I have the same problem and wiped the configuration.

Currently I have about 2779 games in my library.

![image](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/assets/5352403/80ca4bcc-45fc-4dde-8600-55ce2bd4b9d6)

Heroic Games Launcher, after fresh start, it says that I have 2070 games and most of then are still blocked.
![image](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/assets/5352403/6885d226-4f22-4b3b-96ce-907db38ceacf)

There is something really broken in the API with the Python fork of GOGDL, why not just using lgogdownloader which has had never problems getting and managing GOG games? It seems that GOGDL does not really can throttle its API calls properly for getting the data reliably.

Main cause is that the log file is full of 
```
(11:52:34) ERROR:   [Gog]:              Failed to fetch product data for 1207666513, retrying
(11:52:34) ERROR:   [Gog]:              Failed to fetch product data for 1430742927, retrying
(11:52:34) ERROR:   [Gog]:              Failed to fetch product data for 1207666513, retrying
(11:52:34) ERROR:   [Gog]:              Failed to fetch product data for 1207666513, retrying
(11:52:34) ERROR:   [Gog]:              Failed to fetch product data for 1430742927, retrying
(11:52:34) ERROR:   [Gog]:              Failed to fetch product data for 1430742927, retrying
(11:52:35) ERROR:   [Gog]:              Failed to fetch product data for 1207667173, retrying
(11:52:35) ERROR:   [Gog]:              Failed to fetch product data for 1207667173, retrying
(11:52:35) ERROR:   [Gog]:              Failed to fetch product data for 1207667173, retrying
```

**Comment by shakeyourbunny** [comment]
Clicking once on the refresh symbol seems to load some more games, it is 2770, my guess is that gogdl fails to load the last library page.
![image](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/assets/5352403/d76d2aed-4f55-4ef6-92c4-089071eec8a1)

Clicking a third time (and waiting until it finishes) seems not to add the missing 9 games. Seems to be another bug.

**Comment by eemmmmg** [comment]
This issue still seems to occur on 2.15.2. I keep having random games in my library duplicate, and one is "not installable".
