### ISSUE TITLE
Long loading times

### ISSUE THREAD

**Issue by MatusModder** [Heroic-Games-Launcher/HeroicGamesLauncher#366]
Hi there 

I have a issue when I paste my SID and I hit Enter it's loading like a half day, and no, I'm not running Kubuntu on a HDD. I'm running Kubuntu on a 500GB Samsung 850 Evo with AMD Ryzen 5 3600 with GeForce GTX 1660 super. **Can you fix it please, because I want to try just cause 4 and I don't want to wait half day to load my epic game list**

**Comment by flavioislima** [comment]
Try this:
https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/wiki/Troubleshooting#heroic-doesnt-open-never-load-games-after-login-or-shows-a-blank-window

**Comment by debiangamer** [comment]
Just Cause 4 crashes on startup with winehq-staging and winehq-devel and dxvk, not worth to try.

**Comment by flavioislima** [comment]
Closing here since we got not updates for more than two weeks.
Try latest version with a clean install @MatusModder , like it is stated on the Wiki.
