### ISSUE TITLE
Unreal Marketplace tab is hidden even though I have marketplace items in my account.

### ISSUE THREAD

**Issue by warriormaster12** [Heroic-Games-Launcher/HeroicGamesLauncher#367]
**Describe the bug**
When I launch the application I should see Unreal Marketplace tab since I do have items in there but instead I don't see it because application assumes that I don't have them.

**To Reproduce**

1. Open application 
2. log into your account
3. See error

**Expected behavior**
Unreal marketplace tab should be visible

**Screenshots**
![image](https://user-images.githubusercontent.com/33091666/118790752-bc64d380-b89e-11eb-8ec5-06b727e00cf8.png)

**Desktop (please complete the following information):**

- OS: KDE Neon and Arch Linux

**Comment by flavioislima** [comment]
We will try to fix it on next version, for now, try to downgrade to 1.6.0, download some asset and then upgrade to 1.6.1 again. You could use the AppImage for testing purposes.

**Comment by warriormaster12** [comment]
I use appimage by default :D

Anyways, I've noticed a trend with new releases. I think you could have release candidates before releasing a stable version. This way you can ensure that when you release a stable version, it won't have application breaking bugs.

**Comment by flavioislima** [comment]
> I use appimage by default :D
> 
> Anyways, I've noticed a trend with new releases. I think you could have release candidates before releasing a stable version. This way you can ensure that when you release a stable version, it won't have application breaking bugs.

That's true, I think most of the issues we have today are related to testing. We need to start thinking about how to have people to help with specific testing. Or maybe have RC and Betas, like you said, wait for some people to test and give feedback, and then fix the errors or release it as a major version.

I'll think about this for the next version, we tried once but I got no feedback then I didn't try again.

**Comment by flavioislima** [comment]
@warriormaster12 can you try this AppImage: https://drive.google.com/file/d/1zMxWMuxnI7jChXZAEC8Gt5JOPQeuudkC/view?usp=sharing

?

**Comment by warriormaster12** [comment]
@flavioislima unfortunately no, Unreal marketplace is still hidden.
![image](https://user-images.githubusercontent.com/33091666/119226437-c0e4f280-bb11-11eb-809a-909334fdebf3.png)

**Comment by flavioislima** [comment]
> @flavioislima unfortunately no, Unreal marketplace is still hidden.
> ![image](https://user-images.githubusercontent.com/33091666/119226437-c0e4f280-bb11-11eb-809a-909334fdebf3.png)
>   

Ok, but on 1.6.0 was working, right? Because then I can revert my changes from 1 6.1.

**Comment by flavioislima** [comment]
@warriormaster12 check this other version now:
https://drive.google.com/file/d/1tfyVw4ytzHCjlC3fuOaQrt_V8ak-y4cr/view?usp=sharing

**Comment by warriormaster12** [comment]
@flavioislima the link doesn't work anymore. Its in your Gdrives trash bin

**Comment by flavioislima** [comment]
> @flavioislima the link doesn't work anymore. Its in your Gdrives trash bin

Yeah because I updated it since I was testing other issues as well:
https://drive.google.com/drive/folders/1OaxxUQENLwQ-XgQVFrEuyjtmAIvBJ0jl?usp=sharing

But I reverted my changes so Unreal Marketplace will be shown always for now so should work. I'm just waiting for other things to finish to release a new version.

**Comment by warriormaster12** [comment]
![image](https://user-images.githubusercontent.com/33091666/119328240-8f446680-bc8c-11eb-996b-67ca31ba8a8d.png)

Yup, now it works

**Comment by flavioislima** [comment]
> ![image](https://user-images.githubusercontent.com/33091666/119328240-8f446680-bc8c-11eb-996b-67ca31ba8a8d.png)
> 
> Yup, now it works

But they are shown as duplicated, right? Or just the images are duplicated and they are different assets?

**Comment by warriormaster12** [comment]
I bet duplicate assets. I don't 742 assets in my library XD.
