### ISSUE TITLE
How do I execute an .exe file as sudo from heroic's gui?

### ISSUE THREAD

**Issue by Twig6943** [Heroic-Games-Launcher/HeroicGamesLauncher#3679]
### Describe the bug

I need to run this through heroic
sudo wine 123.exe

### Add logs

```text
I need to run this through heroic
sudo wine 123.exe
```

### Steps to reproduce

2. Click on '...'
3. Scroll down to '...'

### Expected behavior

I need to run this through heroic
sudo wine 123.exe

### Screenshots

I need to run this through heroic
sudo wine 123.exe

### Heroic Version

Latest Stable

### System Information

- OS [e. g. "Ubuntu"]:
- Mint

### Additional information

I need to run this through heroic
sudo wine 123.exe

**Comment by arielj** [comment]
what are you trying to achieve? if you try to run that command in any way the process will get stuck waiting for you to enter de password for the sudo

maybe what you are trying to do can be done in a different way

**Comment by Twig6943** [comment]
I need to run an exe with sudo for it to work (seems to not work without it) thing is I want everything inside a prefix (Im too much of a dumbass to understand how prefixes work so heroic is what I use for all of that stuff)

**Comment by imLinguin** [comment]
You should never under any circumstances run wine as root. This was and always will be a bad idea.

What are you trying to do in the first place

**Comment by Twig6943** [comment]
nvm I found an alternative.
