### ISSUE TITLE
Only using XWayland on Flatpak?

### ISSUE THREAD

**Issue by marcelohdez** [Heroic-Games-Launcher/HeroicGamesLauncher#3696]
### Describe the bug

Using the Heroic Games Launcher (`com.heroicgameslauncher.hgl`) flatpak, the launcher only runs under XWayland, which is very noticeable on my laptop which uses 1.5x scaling on Sway making HGL blurry. I have tried disabling the X11 socket, keeping only the Wayland one enabled but it fails with the following output:
```
[13:0413/230557.633016:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[13:0413/230558.451603:ERROR:ozone_platform_x11.cc(244)] Missing X server or $DISPLAY
[13:0413/230558.451625:ERROR:env.cc(257)] The platform failed to initialize.  Exiting.
/app/bin/heroic-run: line 6:    13 Segmentation fault      (core dumped) zypak-wrapper /app/bin/heroic/heroic "$@"
```
For the log when HGL is run with default permissions (and therefore on XWayland) see logs attached.

### Add logs

```text
(22:58:08) INFO:    [Legendary]:        Legendary location: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary
(22:58:08) INFO:    [Gog]:              GOGDL location: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl
(22:58:08) INFO:    [Connection]:       Connectivity: check-online
(22:58:08) INFO:    [Connection]:       Pinging external endpoints
(22:58:08) INFO:    [Gog]:              Checking for existing gog manifests
(22:58:08) INFO:    [Backend]:          DRM module staus {
  "oimompecagnajdejgnnjijobebaeigek": {
    "status": "new",
    "title": "Widevine Content Decryption Module",
    "version": "4.10.2710.0"
  }
}
(22:58:08) WARNING: [Backend]:          Failed to register protocol with OS.
(22:58:08) INFO:    [Legendary]:        Running command: LEGENDARY_CONFIG_PATH=/home/mhdez/.var/app/com.heroicgameslauncher.hgl/config/heroic/legendaryConfig/legendary /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary --version
(22:58:08) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH=/home/mhdez/.var/app/com.heroicgameslauncher.hgl/config/heroic/gogdlConfig /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/mhdez/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json --version
(22:58:08) INFO:    [Nile]:             Running command: NILE_CONFIG_PATH=/home/mhdez/.var/app/com.heroicgameslauncher.hgl/config/heroic/nile_config /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/nile --version
(22:58:08) INFO:    [Connection]:       Connectivity: online
(22:58:08) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH=/home/mhdez/.var/app/com.heroicgameslauncher.hgl/config/heroic/gogdlConfig /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/mhdez/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth
(22:58:08) INFO:    [Backend]:          User Not Found, removing it from Store
(22:58:08) INFO:    [Gog]:              Checking if login is valid
(22:58:08) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH=/home/mhdez/.var/app/com.heroicgameslauncher.hgl/config/heroic/gogdlConfig /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/mhdez/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth
(22:58:08) INFO:    [Backend]:          AreWeAntiCheatYet data downloaded
(22:58:09) INFO:    [Frontend]:         Refreshing undefined Library
(22:58:09) WARNING: [Backend]:          refresh not implemented on Sideload Library Manager
(22:58:09) INFO:    [Legendary]:        Refreshing library...
(22:58:09) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH=/home/mhdez/.var/app/com.heroicgameslauncher.hgl/config/heroic/gogdlConfig /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/mhdez/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth
(22:58:09) INFO:    [Backend]:          Frontend Ready
(22:58:09) INFO:    [Gog]:              Getting GOG library
(22:58:09) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH=/home/mhdez/.var/app/com.heroicgameslauncher.hgl/config/heroic/gogdlConfig /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/mhdez/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth
(22:58:09) INFO:    [Backend]:          
System Information:
CPU: 16x AMD Ryzen 7 7840U w/ Radeon  780M Graphics
Memory: 29.22 GB (used: 4.66 GB)
GPUs:
  GPU 0:
    Name: Advanced Micro Devices, Inc. [AMD/ATI] Phoenix1
    IDs: D=15bf V=1002 SD=0006 SV=f111
    Driver: amdgpu
OS: Fedora Linux 40 (Forty) (linux)

The current system is not a Steam Deck
We are running inside a Flatpak container

Software Versions:
  Heroic: 2.14.1 Flame Emperor Sabo
  Legendary: 0.20.34 Direct Intervention
  gogdl: 1.0.1
  Nile: 1.0.2 Jonathan Joestar

(22:58:09) INFO:    [Backend]:          Checking for current version changelog
(22:58:09) INFO:    [Gog]:              Saved username to config file
(22:58:10) INFO:    [Gog]:              Saved games data
(22:58:10) WARNING: [Backend]:          listUpdateableGames not implemented on Sideload Library Manager
(22:58:10) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH=/home/mhdez/.var/app/com.heroicgameslauncher.hgl/config/heroic/gogdlConfig /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/mhdez/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth
(22:58:10) INFO:    [Gog]:              Found 0 game(s) to update
(22:58:10) DEBUG:   [Backend]:          Unable to load Steam Libraries, libraryfolders.vdf not found
(22:58:10) INFO:    [Winetricks]:       Downloading Winetricks
(22:58:13) INFO:    [WineDownloader]:   Updating wine versions info
(22:58:13) INFO:    [WineDownloader]:   Fetching upstream information...
(22:58:14) INFO:    [Backend]:          Starting the Download Queue
(22:58:15) INFO:    [WineDownloader]:   wine versions updated
```

### Steps to reproduce

1. Open HGL
2. Get window stats, e.g. for Sway: `swaymsg -t get_tree | jq '.. | select(.type?) | select(.focused)'`
3. See that it is running on XWayland.
4. Attempt to remove X11 socket from permissions in Flatseal
5. Heroic fails to open

### Expected behavior

For HGL to support running under Wayland, as noted in https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/issues/1963#issuecomment-1297787677

### Heroic Version

Latest Stable (Flatpak)

### System Information

- OS [e. g. "Ubuntu"]: Fedora 40 Beta
- WM: Sway 1.9

**Comment by Tallis-Larsen** [comment]
same problem but on arch with hyprland

**Comment by Anseryde** [comment]
Same problem on Fedora KDE Wayland.

**Comment by Twig6943** [comment]
Same issue here!
![image](https://github.com/user-attachments/assets/e2198ee0-f934-42f0-bba3-ba3fe77f4fdc)

**Comment by Etaash-mathamsetty** [comment]
just pass in `--ozone-platform-hint=auto`

**Comment by Twig6943** [comment]
(Works with the AppImage package)
![image](https://github.com/user-attachments/assets/11471128-d1a5-4461-af76-e4a70c28430a)

**Comment by Twig6943** [comment]
> Same issue here! ![image](https://private-user-images.githubusercontent.com/119701717/364066479-e2198ee0-f934-42f0-bba3-ba3fe77f4fdc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc2MDIyMDgsIm5iZiI6MTcyNzYwMTkwOCwicGF0aCI6Ii8xMTk3MDE3MTcvMzY0MDY2NDc5LWUyMTk4ZWUwLWY5MzQtNDJmMC1iYmEzLWJhM2ZlNzdmNGZkYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyOVQwOTI1MDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02N2M3ZTRkZjcxYzc4OGYyMzJiYjgzNTIyYmRlZDA3M2YwNmNhMDA4ZjA3M2Y1N2Y5MjliOTkwMDBlZjAxOGYxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.A6ln6sSfePqSFq0HVvLCBTWxAsCvK2sUXBisv8Pu0VU)

>flatpak run com.heroicgameslauncher.hgl --ozone-platform-hint=auto
The flatpak package seems to use wayland too with said flag (even has the icon unlike the AppImage)

**Comment by Etaash-mathamsetty** [comment]
> > just pass in `--ozone-platform-hint=auto`
> 
> (Works with the AppImage package) (The icon is missing but yeah pretty minor issue) (Going to test with the flatpak package soon) ![image](https://private-user-images.githubusercontent.com/119701717/371842064-11471128-d1a5-4461-af76-e4a70c28430a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc2Mjk2NzcsIm5iZiI6MTcyNzYyOTM3NywicGF0aCI6Ii8xMTk3MDE3MTcvMzcxODQyMDY0LTExNDcxMTI4LWQxYTUtNDQ2MS1hZjc2LWU0YTcwYzI4NDMwYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyOVQxNzAyNTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xM2M3YzcxZjMzYjE5ODhjYmQ4YzY0ZTFlZWZlNWJhZTRhNWRiYWYzNGI1NGUzZTA1MjEwNmRlOGQxNzlkYTQ3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.-nVcT5b1LorMYEPsuJp8xwgOyKQuYhD3OBWC2abmEDs)

this will be fixed in the future with the xdg_toplevel_icon protocol, anyway closing as this is not an issue

**Comment by Twig6943** [comment]
@Etaash-mathamsetty  "xdg_toplevel_icon" seems to be merged tho https://gitlab.freedesktop.org/wayland/wayland-protocols/-/merge_requests/269

**Comment by Twig6943** [comment]
@Etaash-mathamsetty could you re-open this issue? This issue is still present (I don't really care about the icon I want the app to auto use the wayland backend without the need of flags)

**Comment by Twig6943** [comment]
I'll create a separate issue in case your notifications are turned off

**Comment by Junzz0** [comment]
Looking forward to HeroicGamesLauncher supporting pure Wayland launch.
