### ISSUE TITLE
Make it possible to add linux native games to library

### ISSUE THREAD

**Issue by PigeonCoding** [Heroic-Games-Launcher/HeroicGamesLauncher#3704]
### Problem description

so i wanted to add a Linux native game i had but i wasn't able to find a way or any reference to being to

### Feature description

allowing the user to add a linux executable as a library entry

**Comment by imLinguin** [comment]
Do you mean using `Add Game` feature?

It's already possible
![image](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/assets/62100117/8ef0a285-b6b8-4f66-a14b-81de4c7ba4cf)

**Comment by PigeonCoding** [comment]
The option was not there for some reason I rebooted and found it now maybe it was not updated for some reason? But anyway the issue is fixed thank you
