### ISSUE TITLE
Importing installed games do not work

### ISSUE THREAD

**Issue by debiangamer** [Heroic-Games-Launcher/HeroicGamesLauncher#371]
Importing installed games do not work. Heroic version:  1.6.1 Magelan

1. Go to Settings
2. Click on Sync with Installed Epic Games
3. Browse to the Epic Games folder and click Sync

Heroic should sync the chosen folder.

**Screenshots**
![image](https://user-images.githubusercontent.com/15704414/119184803-8716dc00-ba7e-11eb-8e36-73fd438c5d20.png)

- OS: Debian Sid Xfce
- Version: rolling
- Wine/Proton version: winehq-devel 6.8/DXVK 1.8.1

**Comment by flavioislima** [comment]
We need more info.
Are you syncing with a epic games installed on windows or Linux?
For Linux you need to select the prefix, not the instalation folder.

**Comment by debiangamer** [comment]
Using the wineprefix ~/.wine works. This must be documented to the UI. The pretyped text in the text box is misleading.

**Comment by flavioislima** [comment]
> Using the wineprefix ~/.wine works. This must be documented to the UI. The pretyped text in the text box is misleading. 

Yeah, I'll write a guide on the wiki 👍
