### ISSUE TITLE
Resume download

### ISSUE THREAD

**Issue by JakobDev** [Heroic-Games-Launcher/HeroicGamesLauncher#372]
It would be nice if Heroic allows to resume a download after closing the store or if the internet connection is lost for a short time. Some Games are very big and for people with bad Internet it takes some time and you may want to resume a big download instead of restarting it. Steam allows this. It always resumes a download is something happen like closing steam instead if restarting it.

**Comment by flavioislima** [comment]
Hi. 

All interrupted downloads get continued after starting again. What we were missing was the feedback to the user, like continuing the percentage instead of getting back to zero.

But this was fixed on the main branch and will be also on next release.

**Comment by debiangamer** [comment]
I did try Download NBA2k21 (80GB )with Heroic and it failed to 3% always. Legendary has downloaded 21.5% now and seems to work better. Download:
https://github.com/derrod/legendary/releases/tag/0.20.6

**Comment by adityaruplaha** [comment]
> I did try Download NBA2k21 (80GB )with Heroic and it failed to 3% always. Legendary has downloaded 21.5% now and seems to work better. Download:
> https://github.com/derrod/legendary/releases/tag/0.20.6

We know about this issue. We haven't figured out a fix yet. That's why we advise using Legendary to install large games.

**Comment by flavioislima** [comment]
> I did try Download NBA2k21 (80GB )with Heroic and it failed to 3% always. Legendary has downloaded 21.5% now and seems to work better. Download:
> https://github.com/derrod/legendary/releases/tag/0.20.6

can you try to replicate the issue again but this time running Heroic from the terminal?
Check if you can you see the progress on the terminal after Heroic "cancels" the download. Or if we can see any other error message.

Thanks

**Comment by debiangamer** [comment]
I did try download The Cycle game and it failed with these messages in 5.81%:
```
Progress: AzaleaAlpha 5.81%/898.62
MiB/13:17:13

Progress: AzaleaAlpha 5.81%/898.62
MiB/13:17:13


(heroic:154288): libnotify-WARNING **: 18:22:03.901: Failed to connect to proxy

(heroic:154288): libnotify-WARNING **: 18:22:03.903: Failed to connect to proxy

(heroic:154288): libnotify-WARNING **: 18:22:03.904: Failed to connect to proxy

(heroic:154288): libnotify-WARNING **: 18:22:10.477: Failed to connect to proxy

(heroic:154288): libnotify-WARNING **: 18:22:10.477: Failed to connect to proxy

(heroic:154288): libnotify-WARNING **: 18:22:10.478: Failed to connect to proxy
```

![image](https://user-images.githubusercontent.com/15704414/119231912-c64f3680-bb2b-11eb-9fa6-15c27facd167.png)

**Comment by flavioislima** [comment]
@debiangamer thanks for the info.
Can you try this version:
https://drive.google.com/file/d/1tfyVw4ytzHCjlC3fuOaQrt_V8ak-y4cr/view?usp=sharing
?

**Comment by debiangamer** [comment]
127MB is really slow to download with 10KB/sec speed.

**Comment by flavioislima** [comment]
> 127MB is really slow to download with 10KB/sec speed.

No rush. Thanks for trying. 
This bug is quite old and I think I got the issue but it doenst happen to me so it's hard to replicate.

**Comment by debiangamer** [comment]
> > 127MB is really slow to download with 10KB/sec speed.
> 
> No rush. Thanks for trying.
> This bug is quite old and I think I got the issue but it doenst happen to me so it's hard to replicate.

Can you create a Debian package and put it MediaFire or here?

**Comment by flavioislima** [comment]
> > > 127MB is really slow to download with 10KB/sec speed.
> > 
> > No rush. Thanks for trying.
> > This bug is quite old and I think I got the issue but it doenst happen to me so it's hard to replicate.
> 
> Can you create a Debian package and put it to MediaFire or here?

It's quite late here. Tomorrow I'll create a pre-release with all packages for testing.

**Comment by debiangamer** [comment]
I left my computer running for a night to download the NBA2k21 game and closed the Heroic UI. My system had downloaded the Cycle game fully at the background with the legendary processes. The game does not run anymore because of a anti-cheat software. I managed to download the heroic-fix.AppImage and it does not fix the issue. I did try to install the Close to the Sun game and Heroic shows The game is not installed at 16.84% with same terminal messages:

```
Progress: Silene 16.84%/3872.71
MiB/04:01:59

Progress: Silene 16.84%/3872.71
MiB/04:01:59


(heroic:222664): libnotify-WARNING **: 06:33:22.599: Failed to connect to proxy

(heroic:222664): libnotify-WARNING **: 06:33:22.601: Failed to connect to proxy

(heroic:222664): libnotify-WARNING **: 06:33:22.603: Failed to connect to proxy

(heroic:222664): libnotify-WARNING **: 06:33:25.772: Failed to connect to proxy

(heroic:222664): libnotify-WARNING **: 06:33:25.773: Failed to connect to proxy

(heroic:222664): libnotify-WARNING **: 06:33:25.774: Failed to connect to proxy
```
Legendary processes are running and they are downloading the game maybe.

**Comment by adityaruplaha** [comment]
> I left my computer running for a night to download the NBA2k21 game and closed the Heroic UI. My system had downloaded the Cycle game fully at the background with the legendary processes. The game does not run anymore because of a anti-cheat software. I managed to download the heroic-fix.AppImage and it does not fix the issue. I did try to install the Close to the Sun game and Heroic shows The game is not installed at 16.84% with same terminal messages:

Thanks for the info. We'll see what we can do. The issue doesn't happen on all systems, so it's difficult to diagnose and fix.

**Comment by adityaruplaha** [comment]
Also, this is the same issue as #195, so please continue discussion there.
