### ISSUE TITLE
i cant sign in

### ISSUE THREAD

**Issue by boxthevip** [Heroic-Games-Launcher/HeroicGamesLauncher#374]
hello,

i used my sid information and clicked login it doesn't seem to be logging in

**Comment by flavioislima** [comment]
> hello,
> 
> i used my sid information and clicked login it doesn't seem to be logging in

Please check our wiki for some troubleshooting guides

**Comment by boxthevip** [comment]
hello again,

is there a link for the wiki?

**Comment by boxthevip** [comment]
nvm im new to github

**Comment by boxthevip** [comment]
there's no answer for my issue

**Comment by adityaruplaha** [comment]
Screenshots please. Also launch Heroic from terminal and send us the log.

**Comment by flavioislima** [comment]
> there's no answer for my issue

The latest subject.
You can try deleting those folders and generating a new SID.
After using the SID once, if it doesnt work, you will need to generate a new one because the other gets invalidated.

**Comment by m0rphtail** [comment]
can't seem to login, tried the steps suggested by @flavioislima 
getting this in the terminal
![image](https://user-images.githubusercontent.com/47940274/121011620-71125680-c7b4-11eb-89ab-a4adae168d10.png)

**Comment by flavioislima** [comment]
> can't seem to login, tried the steps suggested by @flavioislima 
> getting this in the terminal
> ![image](https://user-images.githubusercontent.com/47940274/121011620-71125680-c7b4-11eb-89ab-a4adae168d10.png)
> 

Everything looks good. Tried another Sid?

**Comment by m0rphtail** [comment]
> Tried another Sid?

yes, still nothing,
its just says logging in, but nothing happens

**Comment by flavioislima** [comment]
> > Tried another Sid?
> 
> yes, still nothing,
> its just says logging in, but nothing happens

Probably you have an old python version and legendary cant work
So we need more info, like your Distro, and check the python version with:
`python --version`
on the terminal

**Comment by m0rphtail** [comment]
> > > Tried another Sid?
> > 
> > 
> > yes, still nothing,
> > its just says logging in, but nothing happens
> 
> Probably you have an old python version and legendary cant work
> So we need more info, like your Distro, and check the python version with:
> `python --version`
> on the terminal

Python version is 3.9.5
i'm on Arch linux
and i installed heroic launcher from the AUR

**Comment by adityaruplaha** [comment]
That's weird, should work perfectly fine.

**Comment by flavioislima** [comment]
> > > > Tried another Sid?
> > > 
> > > 
> > > yes, still nothing,
> > > its just says logging in, but nothing happens
> > 
> > 
> > Probably you have an old python version and legendary cant work
> > So we need more info, like your Distro, and check the python version with:
> > `python --version`
> > on the terminal
> 
> Python version is 3.9.5
> i'm on Arch linux
> and i installed heroic launcher from the AUR

So maybe install legendary from AUR and try to login with it.
Using:
`legendary auth`

**Comment by m0rphtail** [comment]
okay, so looks like its an issue with legendary
nothings happening after i enter the sid

**Comment by flavioislima** [comment]
> okay, so looks like its an issue with legendary
> nothings happening after i enter the sid

So maybe open an issue there because here we can do nothing.
