### ISSUE TITLE
Amazon Library only half populating, games listed as "???"

### ISSUE THREAD

**Issue by MistarBeanz** [Heroic-Games-Launcher/HeroicGamesLauncher#3745]
### Describe the bug

Heroic Launcher on a Steam Deck OLED is not pulling down my complete Amazon Games library.  Heroic appears to log into my Amazon account fine, and it shows the proper number of games in my library.  However, it only is pulling down information for about half my game library.  This problem appears to be unique to Amazon, as GOG and Epic do not have this issue.  I can guarantee that half my library is missing as I was looking to install The Banner Saga from my Amazon library, and while I can find the graphic for it in the grid view, it is listed as "???" and cannot be installed.

As far as troubleshooting goes, I have even gone so far as to completely wipe my Steam Deck by reinstalling the Steam Deck OS via USB to ensure there was no misconfiguration or previously tweaks I may have done that might cause an issue.

As you see in the following screenshot, when in list view, I have the proper count of games.  However as noted by the scroll bar indicator on the right, it's around the halfway mark that games start to populate appropriately.
![List View](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/assets/132597339/282a02dc-0c61-44d3-88e3-64872108df81)

When switching to Grid View, you see that the first correctly populated game does have the game title listed correctly when you mouse over it.
![Grid View - Good Game](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/assets/132597339/8ea28eff-b5f2-42b7-afb3-3f330aa3e224)

However, then game directly before it that was listed as "???" in list view, does have the proper game graphics downloaded, but still it does not appear to have any further information like the game title.
![Grid View - Bad Game](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/assets/132597339/81e1a4d5-8e83-4c8c-afcd-a98e4a62efe7)

When I click on this game (or any game) marked as "???".  For a brief split second, I get an option to install, however the game title is still marked as "???"
![Screenshot_20240510_093425](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/assets/132597339/1c76ba49-72b1-44fd-9ec8-949b72b2b361)

However, the screen quickly changes to this one in which clearing the Heroic cache or fully resetting does not help.
![Screenshot_20240510_093637](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/assets/132597339/97f8e86c-9e99-4a25-a498-777979f64b47)

### Add logs

```text
(09:47:48) INFO:    [Legendary]:        Legendary location: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary
(09:47:48) INFO:    [Gog]:              GOGDL location: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl
(09:47:48) INFO:    [Connection]:       Connectivity: check-online
(09:47:48) INFO:    [Connection]:       Pinging external endpoints
(09:47:48) INFO:    [Gog]:              Checking for existing gog manifests
(09:47:48) INFO:    [Nile]:             Refreshing library...
(09:47:48) INFO:    [Nile]:             Refreshing Amazon Games...
(09:47:48) INFO:    [Nile]:             Running command: NILE_CONFIG_PATH=/home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/nile_config /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/nile library sync
(09:47:48) INFO:    [Nile]:             Game list updated, got 481 games
(09:47:48) INFO:    [Backend]:          DRM module staus {
  "oimompecagnajdejgnnjijobebaeigek": {
    "status": "new",
    "title": "Widevine Content Decryption Module",
    "version": "4.10.2710.0"
  }
}
(09:47:49) WARNING: [Backend]:          Failed to register protocol with OS.
(09:47:49) INFO:    [Legendary]:        Running command: LEGENDARY_CONFIG_PATH=/home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/legendaryConfig/legendary /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary --version
(09:47:49) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH=/home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/gogdlConfig /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json --version
(09:47:49) INFO:    [Nile]:             Running command: NILE_CONFIG_PATH=/home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/nile_config /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/nile --version
(09:47:49) INFO:    [Connection]:       Connectivity: online
(09:47:49) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH=/home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/gogdlConfig /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth
(09:47:49) INFO:    [Backend]:          User Not Found, removing it from Store
(09:47:49) ERROR:   [Gog]:              Unable to syncQueued playtime, userData not present
(09:47:49) INFO:    [Backend]:          AreWeAntiCheatYet data downloaded
(09:47:49) INFO:    [Backend]:          
System Information:
CPU: 8x AMD Custom APU 0932
Memory: 15.53 GB (used: 5.17 GB)
GPUs:
  GPU 0:
    Name: Advanced Micro Devices, Inc. [AMD/ATI] Sephiroth [AMD Custom GPU 0405]
    IDs: D=1435 V=1002 SD=0123 SV=1002
    Driver: amdgpu
OS: SteamOS 3.5.19 holo (linux)

The current system is a Steam Deck (model: OLED) in desktop mode
We are running inside a Flatpak container

Software Versions:
  Heroic: 2.14.1 Flame Emperor Sabo
  Legendary: 0.20.34 Direct Intervention
  gogdl: 1.0.1
  Nile: 1.0.2 Jonathan Joestar

(09:47:49) INFO:    [Nile]:             Saved user data to config file
(09:47:49) INFO:    [Frontend]:         Refreshing undefined Library
(09:47:49) WARNING: [Backend]:          refresh not implemented on Sideload Library Manager
(09:47:49) INFO:    [Legendary]:        Refreshing library...
(09:47:49) INFO:    [Nile]:             Refreshing library...
(09:47:49) INFO:    [Nile]:             Refreshing Amazon Games...
(09:47:49) INFO:    [Nile]:             Running command: NILE_CONFIG_PATH=/home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/nile_config /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/nile library sync
(09:47:49) INFO:    [Nile]:             Game list updated, got 481 games
(09:47:49) INFO:    [Backend]:          Frontend Ready
(09:47:49) WARNING: [Backend]:          listUpdateableGames not implemented on Sideload Library Manager
(09:47:49) INFO:    [Nile]:             Looking for updates...
(09:47:49) INFO:    [Nile]:             Running command: NILE_CONFIG_PATH=/home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/nile_config /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/nile list-updates --json
(09:47:50) INFO:    [Backend]:          Checking for current version changelog
(09:47:51) INFO:    [Winetricks]:       Downloading Winetricks
(09:47:53) INFO:    [WineDownloader]:   Updating wine versions info
(09:47:53) INFO:    [WineDownloader]:   Fetching upstream information...
(09:47:54) INFO:    [Backend]:          Starting the Download Queue
(09:47:55) INFO:    [WineDownloader]:   wine versions updated
```

### Steps to reproduce

Log in to Amazon account.
Only half of games library populates appropriately.
Reproducible every single time.  After experiencing the issue, I performed a Steam Deck factory reset via the Steam Deck menu.  Then after continuing to experience the issue, I performed a full Steam Deck OS re installation via USB and still experiencing the issue on a clean Steam Deck.

### Expected behavior

Full list of Amazon games with titles populated appropriately with the ability to install and run.

### Heroic Version

Latest Stable

### System Information

- OS [e. g. "Ubuntu"]:Latest Stable version of Steam Deck OS.  Not using Beta or Preview builds.

**Comment by MistarBeanz** [comment]
One additional note, if I simply click the Install button when in grid or list view for a game marked as "???", it will never let me install.  These games are truly broken in Heroic.

**Comment by imLinguin** [comment]
It's an amazon issue for not providing title in metadata for those titles for some reason

**Comment by MistarBeanz** [comment]
> It's an amazon issue for not providing title in metadata for those titles for some reason

One thing that is interesting though is that I installed Heroic Launcher on my older Steam Deck LCD just a couple days prior and that device was able to download my entire Amazon games library information just fine.  After success on that device, I then decided to install Heroic on my Steam Deck OLED, and I've run into this issue consistently.

Is it possible that something changed on the Amazon side over the last couple days that broke something for Heroic that could be fixed?

**Comment by imLinguin** [comment]
Just to be clear, this affects their official launcher as well, although it seems their client doesn't rely on titles as much as Heroic does. Heroic needs a game title to create a easily accessible name for the created directory. 

I can fairly easily workaround the issue. The problem is that we'd have to use a game id as a directory name instead. Which may be weird from end-user's standpoint.

**Comment by MistarBeanz** [comment]
While my vote may not count for much, I'd vote for the workaround you described.  I'd rather have a Game ID as the directory name and be able to actually install and play the game vs the current state which completely prevents installation of half the library (for me at least).

**Comment by imLinguin** [comment]
Amazon seems to have fixed the issue. I will merge the workaround for the future nevertheless

**Comment by MistarBeanz** [comment]
> Amazon seems to have fixed the issue. I will merge the workaround for the future nevertheless

I can verify on my end that this appears to be fixed as well. Thanks so much for the responsiveness!
