### ISSUE TITLE
Game (GTA V Using Wine GE Latest) says launching but it won't launch?

### ISSUE THREAD

**Issue by tidal0001oncord** [Heroic-Games-Launcher/HeroicGamesLauncher#3759]
### Describe the bug

I've tried launching GTA V on the launcher but the game refuses to run for some reason, even after changing the Wine version.
It's giving this exact error:
> An error has occurred! Try to Logout and Login on your Epic account.
> [Core] WARNING: Could not determine locale, falling back to en-US[cli] INFO: Logging in...[Core] INFO: Trying to re-use existing login session...[cli] INFO: Checking for updates...[Core] INFO: Getting authentication token...[cli] INFO: Launching 9d2d0eb64d5c44529cece33fe2a46482...Traceback (most recent call last):
> File "legendary/cli.py", line 3161, in <module>File "legendary/cli.py", line 3076, in mainFile "legendary/cli.py", line 716, in launch_gameFile "subprocess.py", line 951, in __init__File "subprocess.py", line 1837, in _execute_childPermissionError: [Errno 13] Permission denied: '/home/paul/.steam/root/compatibilitytools.d/GE-Proton9-5/proton'
> [91523]Failed to execute script 'cli' due to unhandled exception!

### Add logs

```text
(14:30:49) INFO:    [Legendary]:        Legendary location: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary
(14:30:49) INFO:    [Gog]:              GOGDL location: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl
(14:30:49) INFO:    [Connection]:       Connectivity: check-online
(14:30:49) INFO:    [Connection]:       Pinging external endpoints
(14:30:49) INFO:    [Gog]:              Checking for existing gog manifests
(14:30:49) INFO:    [Backend]:          DRM module staus {
  "oimompecagnajdejgnnjijobebaeigek": {
    "status": "new",
    "title": "Widevine Content Decryption Module",
    "version": "4.10.2710.0"
  }
}
(14:30:49) WARNING: [Backend]:          Protocol already registered.
(14:30:50) INFO:    [Legendary]:        Running command: LEGENDARY_CONFIG_PATH=/home/paul/.config/heroic/legendaryConfig/legendary /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary --version
(14:30:50) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH=/home/paul/.config/heroic/gogdlConfig /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/paul/.config/heroic/gog_store/auth.json --version
(14:30:50) INFO:    [Nile]:             Running command: NILE_CONFIG_PATH=/home/paul/.config/heroic/nile_config /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/nile --version
(14:30:50) INFO:    [Connection]:       Connectivity: online
(14:30:50) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH=/home/paul/.config/heroic/gogdlConfig /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --auth-config-path /home/paul/.config/heroic/gog_store/auth.json auth
(14:30:50) ERROR:   [Gog]:              Unable to syncQueued playtime, userData not present
(14:30:50) INFO:    [Backend]:          
System Information:
CPU: 12x AMD Ryzen 5 2600X Six-Core Processor
Memory: 16.68 GB (used: 3.66 GB)
GPUs:
  GPU 0:
    Name: Advanced Micro Devices, Inc. [AMD/ATI] RX 6600 MECH 2X
    IDs: D=73ff V=1002 SD=5022 SV=1462
    Driver: amdgpu
OS: Arch Linux 6.8.9-zen1-2-zen (linux)

The current system is not a Steam Deck
We are not running inside a Flatpak container

Software Versions:
  Heroic: 2.14.1 Flame Emperor Sabo
  Legendary: 0.20.34 Direct Intervention
  gogdl: 1.0.1
  Nile: 1.0.2 Jonathan Joestar

(14:30:50) INFO:    [Frontend]:         Refreshing undefined Library
(14:30:50) WARNING: [Backend]:          refresh not implemented on Sideload Library Manager
(14:30:50) INFO:    [Legendary]:        Refreshing library...
(14:30:50) INFO:    [Legendary]:        Refreshing Epic Games...
(14:30:50) INFO:    [Backend]:          Frontend Ready
(14:30:50) INFO:    [Backend]:          AreWeAntiCheatYet data downloaded
(14:30:50) INFO:    [Backend]:          Checking for new Heroic Updates
(14:30:50) INFO:    [Backend]:          Checking for current version changelog
(14:30:50) INFO:    [Legendary]:        Running command: LEGENDARY_CONFIG_PATH=/home/paul/.config/heroic/legendaryConfig/legendary /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary list --third-party
(14:30:52) INFO:    [Legendary]:        Game list updated, got 49 games & DLCs
(14:30:52) INFO:    [Backend]:          Launching Grand Theft Auto V (9d2d0eb64d5c44529cece33fe2a46482)
(14:30:52) INFO:    [Backend]:          Preventing display from sleep
(14:30:52) INFO:    [Backend]:          Checking if wine version exists: Wine - Wine-GE-latest
(14:30:52) WARNING: [Backend]:          listUpdateableGames not implemented on Sideload Library Manager
(14:30:52) INFO:    [Backend]:          Checking if wine version exists: Wine - Wine-GE-latest
(14:30:52) INFO:    [Backend]:          Checking if wine version exists: Wine - Wine-GE-latest
(14:30:52) INFO:    [Backend]:          Checking if wine version exists: Wine - Wine-GE-latest
(14:30:52) DEBUG:   [Backend]:          Running Wine command: wineboot --init
(14:30:52) INFO:    [Backend]:          Preventing machine to sleep
(14:30:52) INFO:    [Legendary]:        Checking for game updates: LEGENDARY_CONFIG_PATH=/home/paul/.config/heroic/legendaryConfig/legendary /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary list --third-party
(14:30:52) INFO:    [Winetricks]:       Downloading Winetricks
(14:30:53) INFO:    [DXVKInstaller]:    installing dxvk on... /home/paul/Games/Heroic/Prefixes/default
(14:30:53) INFO:    [DXVKInstaller]:    dxvk already installed!
(14:30:53) INFO:    [DXVKInstaller]:    installing vkd3d on... /home/paul/Games/Heroic/Prefixes/default
(14:30:53) INFO:    [DXVKInstaller]:    vkd3d already installed!
(14:30:53) INFO:    [Legendary]:        Launching Grand Theft Auto V: HEROIC_APP_NAME=9d2d0eb64d5c44529cece33fe2a46482 HEROIC_APP_RUNNER=legendary HEROIC_APP_SOURCE=epic STEAM_COMPAT_INSTALL_PATH=/run/media/paul/games/games2/GTAV LD_PRELOAD= DOTNET_BUNDLE_EXTRACT_BASE_DIR= DOTNET_ROOT= WINEPREFIX=/home/paul/Games/Heroic/Prefixes/default WINEDLLOVERRIDES=winemenubuilder.exe=d WINE_FULLSCREEN_FSR=0 WINEESYNC=1 WINEFSYNC=1 PROTON_EAC_RUNTIME=/home/paul/.config/heroic/tools/runtimes/eac_runtime PROTON_BATTLEYE_RUNTIME=/home/paul/.config/heroic/tools/runtimes/battleye_runtime ORIG_LD_LIBRARY_PATH= LD_LIBRARY_PATH=/home/paul/.config/heroic/tools/wine/Wine-GE-latest/lib64:/home/paul/.config/heroic/tools/wine/Wine-GE-latest/lib GST_PLUGIN_SYSTEM_PATH_1_0=/home/paul/.config/heroic/tools/wine/Wine-GE-latest/lib64/gstreamer-1.0:/home/paul/.config/heroic/tools/wine/Wine-GE-latest/lib/gstreamer-1.0 WINEDLLPATH=/home/paul/.config/heroic/tools/wine/Wine-GE-latest/lib64/wine:/home/paul/.config/heroic/tools/wine/Wine-GE-latest/lib/wine LEGENDARY_CONFIG_PATH=/home/paul/.config/heroic/legendaryConfig/legendary /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary launch 9d2d0eb64d5c44529cece33fe2a46482 --wine /home/paul/.config/heroic/tools/wine/Wine-GE-latest/bin/wine --language en
(14:30:53) INFO:    [Backend]:          Stopping Power Saver Blocker
(14:30:54) INFO:    [Legendary]:        Found 0 games to update
(14:30:54) INFO:    [Backend]:          Stopping Display Power Saver Blocker
(14:30:54) INFO:    [Frontend]:         Refreshing legendary Library
(14:30:54) INFO:    [Legendary]:        Refreshing library...
(14:30:54) INFO:    [Legendary]:        Refreshing Epic Games...
(14:30:54) INFO:    [Legendary]:        Running command: LEGENDARY_CONFIG_PATH=/home/paul/.config/heroic/legendaryConfig/legendary /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary list --third-party
(14:30:54) INFO:    [WineDownloader]:   Updating wine versions info
(14:30:54) INFO:    [WineDownloader]:   Fetching upstream information...
(14:30:55) INFO:    [Backend]:          Starting the Download Queue
(14:30:55) INFO:    [Legendary]:        Game list updated, got 49 games & DLCs
(14:30:56) INFO:    [WineDownloader]:   wine versions updated
```

### Steps to reproduce

1. Go to 'Grand Theft Auto V Settings'
2. Click on 'Wine Version'
3. Select 'Wine - Wine-GE-latest'
5. Launch Game

### Expected behavior

For the game to launch normally using Proton or Wine.

### Heroic Version

Latest Stable

### System Information

OS: Arch Linux x86_64 
Kernel: 6.8.9-zen1-2-zen

**Comment by MizxGaming** [comment]
Try using normal wine instead of wine-ge. Better, install protonup-qt and install both wine and proton for heroic and try running the game with both of them.

**Comment by tidal0001oncord** [comment]
Hi, i just tried and it's giving me the same exact error:

> An error has occurred! Try to Logout and Login on your Epic account.
> [Core] WARNING: Could not determine locale, falling back to en-US[cli] INFO: Logging in...[Core] INFO: Trying to re-use existing login session...[cli] INFO: Checking for updates...[Core] INFO: Getting authentication token...[cli] INFO: Launching 9d2d0eb64d5c44529cece33fe2a46482...Traceback (most recent call last):
> File "legendary/cli.py", line 3161, in <module>File "legendary/cli.py", line 3076, in main
> File "legendary/cli.py", line 716, in launch_game
> File "subprocess.py", line 951, in __init__File "subprocess.py", line 1837, in _execute_child
> PermissionError: [Errno 13] Permission denied: '/home/paul/.steam/root/compatibilitytools.d/GE-Proton9-5/proton'
> [22158] Failed to execute script 'cli' due to unhandled exception!

**Comment by arielj** [comment]
Have you checked if you have a zombie proton process running in the background or something?

also, check inside `/home/paul/.config/heroic/legendaryConfig/legendary`, somewhere inside there there should be a `config.ini` file, check if there's any reference to proton inside that file

**Comment by MizxGaming** [comment]
Do you have ethernet connected? If you're using wifi then try using ethernet or USB tethering from your phone and give it a try. I get a similar error everytime I'm on wifi cuz my adapter sucks. But as soon as I use ethernet, it's all fine and running. I don't know if this will help, but it's worth giving a shot.

**Comment by tidal0001oncord** [comment]
> Have you checked if you have a zombie proton process running in the background or something?
> 
> also, check inside `/home/paul/.config/heroic/legendaryConfig/legendary`, somewhere inside there there should be a `config.ini` file, check if there's any reference to proton inside that file

Theres no other proton process running in the background, wine either.
The only thing that mentions "proton" is this:
`wrapper = "/home/paul/.steam/root/compatibilitytools.d/GE-Proton9-5/proton" run`
and
`STEAM_COMPAT_DATA_PATH = /home/paul/.proton`
I checked my `/home/paul/` folder to see if i can find anything about .proton but couldn't find anything; could this be it?

**Comment by tidal0001oncord** [comment]
> Do you have ethernet connected? If you're using wifi then try using ethernet or USB tethering from your phone and give it a try. I get a similar error everytime I'm on wifi cuz my adapter sucks. But as soon as I use ethernet, it's all fine and running. I don't know if this will help, but it's worth giving a shot.

Tried this too; nothing.

**Comment by tidal0001oncord** [comment]
So.. is there no fix to it?

**Comment by arielj** [comment]
have you checked if there's a `config.ini` somewhere inside `/home/paul/.config/heroic/legendaryConfig/legendary` ?

**Comment by MizxGaming** [comment]
> So.. is there no fix to it?

There might be, but it's not something I can help with. I'm not that experienced to solve this issue. I recommend you seek help in Heroic Games Discord server. I got a lot of help from there and pretty fast too.  There are much more knowledgeable people there who can actually help you

**Comment by MizxGaming** [comment]
And yeah, can you try running it again and provide the logs?

**Comment by arielj** [comment]
> Had the same problem, the only way to make GTA V launch is using Crossover (the paid one), create bottle in there and name it "Heroic", in Heroic launcher settings select Crossover instead of Wine-Crossover or others, and type the bottle name (you may find it by default preselected), and then reinstall the GTA 5 into that bottle, you'll manage to run the rockstar games launcher once but you'll see that it shows that you can launch the game. Then you have to do that thing with fix.bat. If It launches the rockstar games launcher but shows that you don't have the game owned - increase in fix.bat the number from 20 to 60. You'll get it working, but lagging. I made all of that stuff but have no idea right now how to get smooth fps, since now it drops from normal to 0 for 10 seconds.

just to clarify, this is a different issue and it's unrelated to Mac and unrelated to the `fix.bat` problem

**Comment by tidal0001oncord** [comment]
> have you checked if there's a `config.ini` somewhere inside `/home/paul/.config/heroic/legendaryConfig/legendary` ?
> 
> something is telling legendary to use proton, but it's not in the heroic's logs, so I imagine it's some change in the config.ini

Hi, sorry for the long delay I had some issues with my computer therefore i couldn't reply in time.

only thing that may relate to proton are these:
"STEAM_COMPAT_DATA_PATH = /home/paul/.proton"

and this one.

wrapper = "/home/paul/.steam/root/compatibilitytools.d/GE-Proton9-5/proton" run
no_wine = true

also i got GTA V from Epic games store and in the config it says : 
egl_sync = False

should i turn it on?

**Comment by arielj** [comment]
you should remove those `wrapper` and `no_wine` configuration, those are overriding what you set in heroic and that's creating this problem

you don't need to set `egl_sync`, that's when you want to keep the official Epic Games Launcher in sync with heroic if you have both installed, but if you want that there's a setting in Heroic to do that, you shouldn't configure things in legendary's config.ini that we have inside the heroic config folder

**Comment by arielj** [comment]
Closing this since it's not an issue with heroic but some issue with configuration files. If you still have issues after removing that config, please create a thread in the `#-Support` section in our discord since github issues are meant for bugs in heroic itself.
