### ISSUE TITLE
Systemwide performance drop when launching game via HGL without having EGS launched via Lutris beforehand

### ISSUE THREAD

**Issue by fridge-art** [Heroic-Games-Launcher/HeroicGamesLauncher#377]
This is a weird one but I have tested and verified this numerous time now with just one game, FM2020. I assume the issue is some kind of memory/cpu leak and its probable that other games should be effected too even if i cant verify it personally at this stage.

If i perform a clean system boot, start HGL, Launch Football Manager 2020, it does start the game as expected but with heavy performance issues. FPS maybe 5-10. At this stage it is systemwide, in and outside of the game. Moving the cursor is like dragging it through syrup. In web browser and OS browsing. If i exit the game, the system returns back to normal performance. 

Looking at "top" via terminal gives me cpu usage at 90-100% on FM2020.exe. 

However, if i first launch Lutris, then launch EGS, then open HGL and launch Football Manager 2020, the issue is nowhere to be seen and performance is good in and outside of the game.

Sounds to me like some kind of cpu leakage or check that doesnt get the result it wants and are caught in some kind of infinite loop.

**Desktop (please complete the following information):**

- OS: Manjaro
- Kernel: 5.10.36-2-MANJARO 
- Game: Football Manager 2020
- Wine/Proton version: Wine 6.8 

If any logs are needed to clarify the issue i will try to provide on request

**Comment by adityaruplaha** [comment]
Can you check using Legendary? This shouldn't be something Heroic can even cause accidentally.

**Comment by fridge-art** [comment]
> Can you check using Legendary? This shouldn't be something Heroic can even cause accidentally.

I just tried. Reboot, launch via legendary, same system wide performance issue. 93% cpu used by fm.exe but only 7% mem. Close game, launch lutris, launch EGS, launch game via legendary, performance issue gone. 

So in short, using Legendary produced the exact same issue

**Comment by adityaruplaha** [comment]
Well please report it on the Legendary GitHub then, there's nothing we can do about it. Sorry.

**Comment by adityaruplaha** [comment]
My best guess: the game is trying to constantly call something from the EGS internal API that Legendary doesn't implement. Hence when that fails, the game probably does something weird, perhaps intentionally to enforce DRM.
