### ISSUE TITLE
Launch DOS games using native system DOSBox

### ISSUE THREAD

**Issue by hfc2x** [Heroic-Games-Launcher/HeroicGamesLauncher#3793]
### Problem description

GOG games usually offer a Linux installer, but some of them only come with the Windows version of DOSBox (such as Warcraft), which Heroic tries to run through WINE. This is pretty inconvenient.

### Feature description

DOS games should be able to run natively, since DOSBox is available as a package for most distros. GOG DOS games usually come with the required configuration ready for this.

### Additional information

This can be done on Steam by installing Boxtron. Instead of running Windows DOSBox through Proton, Boxtron allows Steam to launch the native version of DOSBox.

**Comment by Lariaa** [comment]
https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/pull/3797 should help with this
