### ISSUE TITLE
umu-launcher support

### ISSUE THREAD

**Issue by esanscoopsers** [Heroic-Games-Launcher/HeroicGamesLauncher#3801]
### Problem description

wine-GE is no longer being updated to the latest version of proton/wine

### Feature description

support for selecting umu-launcher as the wine version https://github.com/Open-Wine-Components/umu-launcher

**Comment by arielj** [comment]
it's in progress https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/pull/3724

it would be useful if you can test that

**Comment by dancaer69** [comment]
I'd like to test that(I already use umu manually and on lutris recently), but I don't know how in heroic. I have the latest version 2.14.1 and I also tried to build it by git clone(I ended up with the same version), but it doesn't seems to work. When I select ge-proton from wine version I get the error "The wine path isn't valid...". I have umu-launcher installed.

**Comment by Lalarian** [comment]
How do you buls this from a branch please?
I did git clone, git switch umu, and pnpm dist:linux
But the resulting build seems to be the normal one.

**Comment by dancaer69** [comment]
I did it like this:
git clone -b umu https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher.git --single-branch  --recurse-submodules

**Comment by slagiewka** [comment]
For anyone interested in testing the experimental feature in HGL 2.15:

1. Install latest version (2.15.1 as of today)
2. Go to Settings -> Advanced -> Experimental Features -> Use UMU as Proton runtime
3. Change game settings to run via some Proton version
4. Run the game

**Warning:** I see that running under UMU/Proton prefix makes the game lose track of previous saves. They are back when I switch back to Wine, though.

**Comment by imLinguin** [comment]
There is one more step - ensure `Use Steam runtime` is enabled per game. UMU symlinks wine and proton paths together so no data loss should occur

**Comment by arielj** [comment]
Closing this since heroic already integrates UMU. Experimental feature in the latest release and will be on by default starting in the next release.
