### ISSUE TITLE
Xinput works in menu but not in games?

### ISSUE THREAD

**Issue by ParanoIIa91** [Heroic-Games-Launcher/HeroicGamesLauncher#3803]
### Describe the bug

My alpakka controller works fine with steam even with mixed inputs, but for some reason its not recognised in games launched via heroic games launcher even tho controller works in heroic games launcher menu?

### Add logs

```text
Nothing to paste.
```

### Steps to reproduce

Not needed.

### Expected behavior

Self explanatory.

### Heroic Version

Latest Stable

### System Information

Pop Os, Ryzen 3600x, 6600XT.

**Comment by arielj** [comment]
Heroic has no control on how games detect the controllers (that's something between the games and wine).

You can try something from here https://github.com/CommandMC/EpicLinux/wiki/Potential-controller-issue-fixes but there's nothing that heroic can do there.

If you still have issues you'll have more help asking in the `#-support` section in our discord.
