### ISSUE TITLE
My M2 Air dosn't run FS22

### ISSUE THREAD

**Issue by CukursTV** [Heroic-Games-Launcher/HeroicGamesLauncher#3813]
### Describe the bug

Hello ! I download heroic app to play FS22. After downloading app and game I try to launch but I see eror. How to fix that or something to I can play FS22

### Add logs

```text
(21:57:46) INFO:    [Legendary]:        Launching Farming Simulator 22: HEROIC_APP_NAME=f452ea20ae1b43698209998b56c2cc1c HEROIC_APP_RUNNER=legendary HEROIC_APP_SOURCE=epic LD_PRELOAD= DOTNET_BUNDLE_EXTRACT_BASE_DIR= DOTNET_ROOT= WINEPREFIX="/Users/ingars/Games/Heroic/Prefixes/default/Farming Simulator 22" WINEDLLOVERRIDES=winemenubuilder.exe=d WINE_FULLSCREEN_FSR=0 WINEESYNC=1 WINEMSYNC=1 ORIG_LD_LIBRARY_PATH= LD_LIBRARY_PATH="/Users/ingars/Library/Application Support/heroic/tools/wine/Wine-Crossover-latest/Contents/Resources/wine/lib:/Users/ingars/Library/Application Support/heroic/tools/wine/Wine-Crossover-latest/Contents/Resources/wine/lib" WINEDLLPATH="/Users/ingars/Library/Application Support/heroic/tools/wine/Wine-Crossover-latest/Contents/Resources/wine/lib/wine:/Users/ingars/Library/Application Support/heroic/tools/wine/Wine-Crossover-latest/Contents/Resources/wine/lib/wine" LEGENDARY_CONFIG_PATH="/Users/ingars/Library/Application Support/heroic/legendaryConfig/legendary" /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/legendary launch f452ea20ae1b43698209998b56c2cc1c --wine "/Users/ingars/Library/Application Support/heroic/tools/wine/Wine-Crossover-latest/Contents/Resources/wine/bin/wine64" --language en
```

### Steps to reproduce

1. Go to library 
2. Click START button to FS22
3. see eror

### Expected behavior

Game down't start

### Screenshots

![FarmingSimulator2022](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/assets/110425999/23b1369f-ad74-415f-9436-642ef060e6af)

### Heroic Version

Latest Stable

### System Information

Sanoma 14.4.1 - OS

**Comment by CommandMC** [comment]
This issue tracker is *only* for bugs in Heroic itself. Resolving game issues usually requires a more direct means of communication, which GitHub is not suited for. Please join our Discord server and create a post in the support forum instead, adding your game log (which is also missing here, so we couldn't help you even if we'd want to)
