### ISSUE TITLE
Amazon Games Manifest Unreachable

### ISSUE THREAD

**Issue by DumbAsFuck** [Heroic-Games-Launcher/HeroicGamesLauncher#3825]
### Describe the bug

Amazon games manifest says it;s unreachable in the logs. Amazon games info will load for a split second then disappear. Can't install games by hovering over the picture and pressing y on gamepad. It just goes ti the download page and fails to load install size and download size.

I can however play games by amazon I have installed by hovering over and pressing y. Can't get those games info same as above.

Nothing has changed on my end this seems to of jjust become an issue. Guessing Amazon changed something.

I tried relogging into amazon and clearing heroic cache and restarting heroic. steam deck multiple times.

Logs seem useless since all it mentions is a failure to reach app manifest.

on steam deck heroic version 2.14.1

### Add logs

```text
cant seem to copy/paste the logs. all they say thats useful is failed to get manifest and failed to get versions.

by that i mean those are the only things shown as errors.

if you really need it ill figure out a way to copy/paste it.
```

### Steps to reproduce

1. Go to any games provided by amazon
2. Click on show game
3. See error

### Expected behavior

to load normally

### Heroic Version

Latest Stable

### System Information

steam latest. heroic latest

**Comment by arielj** [comment]
I think you are having this issue https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/issues/3816 ? if so that explains a workaround and this could be closed

**Comment by DumbAsFuck** [comment]
yes that worked ty
