### ISSUE TITLE
Add anti cheat runtime update checks

### ISSUE THREAD

**Issue by games647** [Heroic-Games-Launcher/HeroicGamesLauncher#3837]
### Problem description

I wondered why `XDefiant` always crashes, even in menu. In the end, updating the files from `/heroic/tools/runtimes/battleye_runtime` fixed this issue. Turns out the old files were years older.

### Feature description

Currently, Heroic seems to only checks if the runtime is installed ([ref](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/blob/45358ad722d7f6f9c09fb75dd4d97efaeb968564/src/backend/launcher.ts#L392)). Therefore, we need to implement some kind of version checking. Lutris' API currently exposes a `created_at` key. Maybe that could be useful ([ref](https://lutris.net/api/runtimes)).

**Comment by CommandMC** [comment]
#3799 implemented this. The feature will thus be available in the next Heroic release
