### ISSUE TITLE
Icon slight redesign.

### ISSUE THREAD

**Issue by DuttaAB-dev** [Heroic-Games-Launcher/HeroicGamesLauncher#384]
The icon looks too boxy. Maybe make the edges a bit rounded to better suite desktop environments like GNOME?

**Comment by dragonDScript** [comment]
Why not simplify the logo? I think that it has too many gradients. I will be uploading my proposal soon.

**Comment by flavioislima** [comment]
Yeah, we will never find a logo that will make everyone happy.
I think we need to improve the ones that stay on the tray icon, that should be the priority in my opinion.

**Comment by flavioislima** [comment]
Converting to a discussion.
