### ISSUE TITLE
Allow online play with GOG

### ISSUE THREAD

**Issue by Rathmox** [Heroic-Games-Launcher/HeroicGamesLauncher#3852]
### Problem description

I tried playing online a GOG game (Quake II Enhanced), but the game said my account failed to register.
I needed to use the GOG Galaxy launcher to play online and register my account properly (as normally needed by any online game on GOG)

### Feature description

Launching the game with the parameters used by GOG Galaxy to play online and allow multiplayer

### Alternatives

Installing the GOG Galaxy launcher and using game shortcuts made by it as "Play Online"

### Additional information

It would be interesting to allow choosing to start the game online or offline

**Comment by imLinguin** [comment]
I'm currently developing a module for it. It's known as [comet](https://github.com/imLinguin/comet). It's almost ready, now it's a matter of more testing. Any feedback is greatly appreciated.

**Comment by Harmonia2Side** [comment]
Very glad to know this feature is in the works. Will see if I can do some testing, as well as adding some games I own that use this feature to the compatibility list
