### ISSUE TITLE
Missing Image for JayDLC / The messenger picnic panic

### ISSUE THREAD

**Issue by StefanLobbenmeier** [Heroic-Games-Launcher/HeroicGamesLauncher#386]
**Describe the bug**
#81 was closed because there was no image data available. In this case the image data is available but Heroic still says "Image not found":

![image](https://user-images.githubusercontent.com/36509607/119569351-ee020100-bdae-11eb-9c3b-da5f7b6ab938.png)

**To Reproduce**

1. Login to an account that has "The messenger Picnic Panic"
2. View the image in Library

**Expected behavior**
The background loads, one of 

```json
    "keyImages": [
      {
        "height": 1440,
        "md5": "0466026af367640bd29a5052f326b1e7",
        "size": 541703,
        "type": "DieselGameBox",
        "uploadedDate": "2019-11-13T18:34:35.337Z",
        "url": "https://cdn1.epicgames.com/752368fdba244e9386023cfb2b9d6ceb/item/Sabotage_PicnicPanic-2560x1440-0466026af367640bd29a5052f326b1e7.jpg",
        "width": 2560
      },
      {
        "height": 420,
        "md5": "6b715bcdcd8d7ace25ec786ec82dda6a",
        "size": 75843,
        "type": "DieselGameBoxLogo",
        "uploadedDate": "2019-11-13T18:35:03.531Z",
        "url": "https://cdn1.epicgames.com/752368fdba244e9386023cfb2b9d6ceb/item/ColorPicnicPanicLogo-986x420-6b715bcdcd8d7ace25ec786ec82dda6a.png",
        "width": 986
      },
      {
        "height": 1440,
        "md5": "f1232fd3929b62f0f6e0eecce04120c4",
        "size": 268204,
        "type": "DieselStoreFrontTall",
        "uploadedDate": "2019-11-13T18:35:12.463Z",
        "url": "https://cdn1.epicgames.com/752368fdba244e9386023cfb2b9d6ceb/item/PicnicPanic_Portrait-1280x1440-f1232fd3929b62f0f6e0eecce04120c4.jpg",
        "width": 1280
      }
    ],
```

**Screenshots**
If you look closely, you can see that the custom text has actually loaded:
![image](https://user-images.githubusercontent.com/36509607/119568941-64eaca00-bdae-11eb-84c7-21b66c92f014.png)

**Desktop (please complete the following information):**

- OS: Manjaro, 
- Version: Heroic 1.7.0-1
- Game: 
 -  "app_name": "JayDLC1",
 -  "app_title": "The Messenger Picnic Panic",
- Wine/Proton version: 6.8

**Additional context**

**Comment by StefanLobbenmeier** [comment]
So I am guessing this is because the type "DieselGameBoxTall" is missing?

**Comment by StefanLobbenmeier** [comment]
Relevant Code: https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/blob/b23487674ed3cbb744759c5302f2c894001b6f63/electron/legendary_utils/library.ts#L273

**Comment by flavioislima** [comment]
> So I am guessing this is because the type "DieselGameBoxTall" is missing?

Hmm. No, we have this type. Might be something on the URL. I'll take a look when I have some time.
