### ISSUE TITLE
Rimworld Heroic games problem on linux 

### ISSUE THREAD

**Issue by asdbasma** [Heroic-Games-Launcher/HeroicGamesLauncher#3862]
### Describe the bug

i try to use rimworld on heroic games but than start the game its just craching i tryed it use not fullscrean but not worked than i 
tryed to use proton and some versions on wine and proton and its not worked too and i tryed start setting this -popupscrean 
-w 1920 -h1080 

### Add logs

```text
its doesnt make the log too
```

### Steps to reproduce

1.i open the rimworld
2.directly crashed 

### Expected behavior

directly crashed 

### Heroic Version

Latest Stable

### System Information

Dualboot
Arch linux 
Windows
Rimworld 1.5 4136

**Comment by arielj** [comment]
Github issues are for issues with heroic itself, for help running specific games use the `#-support` channel in our discord
