### ISSUE TITLE
Cannot retrieve data from Amazon Games

### ISSUE THREAD

**Issue by RibhuNoodleBoodle** [Heroic-Games-Launcher/HeroicGamesLauncher#3876]
### Describe the bug

Heroic cannot seem to retrieve data from Amazon Games/Nile. 

### Add logs

```text
07:12:38) INFO:    [Nile]:             Running command: NILE_CONFIG_PATH=/home/user/.config/heroic/nile_config /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/nile list-updates --json
(07:14:10) INFO:    [ExtraGameInfo]:    Using cached ExtraGameInfo data for The Forgotten City
(07:14:10) INFO:    [ExtraGameInfo]:    Using cached ExtraGameInfo data for The Forgotten City
(07:14:10) INFO:    [Nile]:             Getting more details
(07:14:10) INFO:    [Nile]:             Running command: NILE_CONFIG_PATH=/home/user/.config/heroic/nile_config /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/nile install --info --json amzn1.adg.product.e31e4571-b8d9-444e-852f-93846749eb40
(07:14:11) INFO:    [Nile]:             Getting more details
(07:14:11) INFO:    [Nile]:             Running command: NILE_CONFIG_PATH=/home/user/.config/heroic/nile_config /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/nile install --info --json amzn1.adg.product.e31e4571-b8d9-444e-852f-93846749eb40
(07:14:12) ERROR:   [Gog]:              SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at Module.getInstallInfo$2 [as getInstallInfo] (/opt/Heroic/resources/app.asar/build/electron/main.159a68a5.js:95:5537)
    at async /opt/Heroic/resources/app.asar/build/electron/main.159a68a5.js:235:5349
    at async WebContents.<anonymous> (node:electron/js2c/browser_init:2:79404)
(07:14:12) ERROR:   [Gog]:              SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at Module.getInstallInfo$2 [as getInstallInfo] (/opt/Heroic/resources/app.asar/build/electron/main.159a68a5.js:95:5537)
    at async /opt/Heroic/resources/app.asar/build/electron/main.159a68a5.js:235:5349
    at async WebContents.<anonymous> (node:electron/js2c/browser_init:2:79404)
(07:14:12) ERROR:   [Frontend]:         Cannot get game info
(07:14:12) ERROR:   [Frontend]:         Cannot get game info
(07:14:12) ERROR:   [Frontend]:         Cannot get game info
```

### Steps to reproduce

Go to any game any game, says "Cannot get game info". Even cannot start downloads/ installation because it cannot seem to retrieve data.

### Expected behavior

Expected the data to retrieve and downloads to happen.

### Screenshots

![Screenshot_20240724_071436](https://github.com/user-attachments/assets/38dd03d7-e582-40b0-a03d-bc98ea9eaf7c)

### Heroic Version

Latest Stable

### System Information

- OS [e. g. "Ubuntu"]: 22.04

**Comment by FeedTheChunk** [comment]
Same here for me.   Kubuntu noble 24.04 x86_64  v 2.14.1 installed via Flatpak

**Comment by crosscoder1** [comment]
I can also confirm this is happening with v2.14.1 AppImage.  But seems to be an API change as Lutris throws a similar error for Amazon Games.

**Comment by promarcel** [comment]
This is related with https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/issues/3850.

You can solve the issue by installing and using the latest [nile client](https://github.com/imLinguin/nile), as described in this comment: https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/issues/3850#issuecomment-2208433405.

I recommend you to using the latest released binary build instead of the nightly version: https://github.com/imLinguin/nile/releases/latest

**Comment by RibhuNoodleBoodle** [comment]
Downloading and installing the latest nile client did the trick thank you! @promarcel
