### ISSUE TITLE
Location of 'Application Data' folder?

### ISSUE THREAD

**Issue by Shotweb** [Heroic-Games-Launcher/HeroicGamesLauncher#388]
Hello, I have downloaded Killing Floor 2 but my progress is saved locally on my previous Lutris installation, in LutrisGames/epic-games-store/drive_c/users/shotweb/Application Data/KF2

I need to copy this folder over to Heroic Games Launcher's KF2 instance, but where is that folder?

**Comment by adityaruplaha** [comment]
Just put in the corresponding location on the wineprefix you're using with that game.

**Comment by Shotweb** [comment]
In Settings for the game that is set to be "/home/shotweb/.wine" but copying my KF2 folder to "/home/shotweb/.wine/drive_c/users/victor/Application Data" doesn't work.

**Comment by flavioislima** [comment]
> In Settings for the game that is set to be "/home/shotweb/.wine" but copying my KF2 folder to "/home/shotweb/.wine/drive_c/users/shotweb/Application Data" doesn't work.

Why don't you keep using the same prefix with heroic? Go the the game settings and on prefix select the same that lutris was using. I think its the easier way.

Just notice it that if you use proton to launch the game, the prefix will be different since it will create a folder called pfx inside the prefix.

**Comment by Shotweb** [comment]
My old install is on a slow HDD, I have bought a new SDD where I have a completely fresh Debian installation and I want my games on there. Can I just transfer my old Lutris prefix? Is it just a question of copying the whole folder over and pointing Heroic to it?

**Comment by flavioislima** [comment]
> My old install is on a slow HDD, I have bought a new SDD where I have a completely fresh Debian installation and I want my games on there. Can I just transfer my old Lutris prefix? Is it just a question of copying the whole folder over and pointing Heroic to it?

I think I'm getting confused 😅
Do you want to move the game folder, with the install files or only the wine prefix? Wine prefix should not be that big.

If you want to move the folder where the game is installed you can move it whenever you want then you go to the game o heroic, open the game page clicking on the card, then on the install part you select import. Then select the folder where the game is installed.

If you're talking only about the saves, then they are on your wine prefix, that you also can move. And then on heroic, under the game setting, wine setting, select the folder with the prefix that have your save games.

**Comment by Shotweb** [comment]
I don't really mind how it is done, I have already re-downloaded the game on my SSD. The other times I had to do this, when still using Epic Games Store, I just had to copy the KF2 folder over and it would work.

I don't understand about re-using my old wine prefix, since it is on the old HDD and I want everything on the SSD.

**Comment by flavioislima** [comment]
> I don't really mind how it is done, I have already re-downloaded the game on my SSD. The other times I had to do this, when still using Epic Games Store, I just had to copy the KF2 folder over and it would work.
> 
> I don't understand about re-using my old wine prefix, since it is on the old HDD and I want everything on the SSD.

So you just need to copy the wine prefix from the hdd to the ssd like I said above. Then on heroic you will point it to your new SSD. Copy from hdd, paste on ssd, change config on heroic.
Maybe on our discord you will get faster and better help than here on github.

**Comment by Shotweb** [comment]
But the old wine prefix is using the Epic Games Store? How will that work through Heroic Games Store?

**Comment by adityaruplaha** [comment]
It just will. The details aren't really relevant. Heroic doesn't touch your wineprefix directly, the game does. So it'll just find everything in its normal place and be happy.

**Comment by flavioislima** [comment]
Yeah, prefixes are not something unique to a game or application. You can use the same prefix for several different stuff. You can imagine the prefix as a really really tiny windows installation, where you have basic stuff to make the games and apps work.

For gaming, sometimes is good to have different prefixes because they might need different configurations, but most of the time having only one is ok.

So you can keep using the same prefix you were before with lutris, with the egs installed there. And also you can come back and forth from heroic and egs anytime, should not be an issue.

**Comment by Shotweb** [comment]
I must admit I've always been confused about the concept of wine prefixes. I understand that Heroic has created the wine prefix /home/shotweb/.wine/ but the actual game is installed in /home/shotweb/Games/Heroic/KillingFloor2. That means that if I copy my old Lutris prefix into .wine/, I will have two duplicate KF2 installations taking up disc space.

But never mind, I figured it out. The correct path for my KF2 savegame folder was not /home/shotweb/.wine/drive_c/users/victor/Application Data but /home/shotweb/.wine/pfx/drive_c/users/steamuser/Application Data. I am highly confused why it is suddenly a "steamuser" but I guess that's because I'm using Steam's proton wine.
