### ISSUE TITLE
Add total size of the game that needs to be downloaded next to amount downloaded

### ISSUE THREAD

**Issue by Emerald-glitch** [Heroic-Games-Launcher/HeroicGamesLauncher#389]
It will be really helpful if you could add total size of the game that needs to be downloaded as in
00MB/700MB

**Comment by adityaruplaha** [comment]
Unfortunately Legendary doesn't provide the total download size in the log. But I'll see if it's possible to extract the information.

**Comment by Emerald-glitch** [comment]
Apart from that i noticed that the continue function continues downloading after the latest completed file i.e. if i pause/cancel the download when only half of a file is downloaded then on resume it downloads that file again, Is it also due to legendary?

**Comment by flavioislima** [comment]
> Apart from that i noticed that the continue function continues downloading after the latest completed file i.e. if i pause/cancel the download when only half of a file is downloaded then on resume it downloads that file again, Is it also due to legendary?

Yeah, this is how Legendary works and I think sounds safe, not always is possible to continue the download of the same file, something could get corrupted.

**Comment by adityaruplaha** [comment]
> > Apart from that i noticed that the continue function continues downloading after the latest completed file i.e. if i pause/cancel the download when only half of a file is downloaded then on resume it downloads that file again, Is it also due to legendary?
> 
> Yeah, this is how Legendary works and I think sounds safe, not always is possible to continue the download of the same file, something could get corrupted.

Yeah had that happen with pacman once.

**Comment by dragonDScript** [comment]
Is someone already working on this?

**Comment by flavioislima** [comment]
> Is someone already working on this?

I don't think so. You can grab it.
Can you assign the issue to yourself?

**Comment by adityaruplaha** [comment]
@dragonDScript I'll advise waiting for a while, I'm currently in the middle of redoing how we interact with Legendary. Your implementation will be completely incompatible with that. Once I'm done this should be much easier to tackle cuz stdout listeners.

**Comment by flavioislima** [comment]
> @dragonDScript I'll advise waiting for a while, I'm currently in the middle of redoing how we interact with Legendary. Your implementation will be completely incompatible with that. Once I'm done this should be much easier to tackle cuz stdout listeners.

@adityaruplaha since you're refactoring things again, what do you suggest would be good for @dragonDScript start with?

**Comment by adityaruplaha** [comment]
> > @dragonDScript I'll advise waiting for a while, I'm currently in the middle of redoing how we interact with Legendary. Your implementation will be completely incompatible with that. Once I'm done this should be much easier to tackle cuz stdout listeners.
> 
> @adityaruplaha since you're refactoring things again, what do you suggest would be good for @dragonDScript start with?

Honestly I've no idea. I just wanna spare him the trouble of wayy too many conflicts. Anything not interacting with Legendary should be unaffected by GSR Part 2.

**Comment by dragonDScript** [comment]
> @dragonDScript I'll advise waiting for a while, I'm currently in the middle of redoing how we interact with Legendary. Your implementation will be completely incompatible with that. Once I'm done this should be much easier to tackle cuz stdout listeners.

Yeah, I know. Please notify me when you're done refactoring.

**Comment by flavioislima** [comment]
Well, I'll add more issues based on our current list of bugs and feature requests.
Stay tunned @dragonDScript

**Comment by dragonDScript** [comment]
I'll move this to 1.8.1

**Comment by wiryfuture** [comment]
@flavioislima I know this isn't really the fraction that was asked for but does this count as implemented?
You can see download size and how much has been downloaded.
![image](https://user-images.githubusercontent.com/50517631/149017564-440f1ba5-7475-422b-8f61-61260d0838f8.png)

**Comment by flavioislima** [comment]
Now that we have the total size, we could add it there. The problem is that this will be confusing when continuing download. We can actually check if legendary shows this on the CLI and add it to the progress method.

**Comment by adityaruplaha** [comment]
@flavioislima Ideally I think we ought to have an interface somewhat like qBittorrent. Total download size, downloaded overall, and downloaded in this session.

**Comment by flavioislima** [comment]
I think this is not necessary anymore since we have the total download on top. It will be just the same info in another place.
