### ISSUE TITLE
Support GOG DLC on Linux

### ISSUE THREAD

**Issue by ToxicFrog** [Heroic-Games-Launcher/HeroicGamesLauncher#3894]
### Problem description

Heroic 2.13 added support for GOG DLC, but, as far as I can tell, only on Windows. On Linux I can still install DLC-having games, like AI War 2, but the DLC is not installed and there's no option to install it.

### Feature description

DLC should be supported on Linux as it is on Windows and Mac.

### Alternatives

Manually downloading the DLC installers, running them, and telling them to install to the directory Heroic installed AIW2 to works fine, but is awkward: each DLC installer needs you to click through an EULA for the installer framework itself, then tell it where to find the installed game.

**Comment by imLinguin** [comment]
As far as I remember it's possible to have DLCs installed together with the game. It's not possible to modify them later (Modify Installation option on game page) though.

Can you confirm that the DLCs are at least shown on the install dialog?

**Comment by ToxicFrog** [comment]
Checked and yes, they show up in the install dialog if the game is not already installed -- so the only part that doesn't work is installing DLCs post hoc.

In the case of AIW2, I already had it installed, then bought the DLCs and wanted to add them, but couldn't find any DLC management interface, nor did "check for updates" or "repair install" install them.

This does at least offer a workaround -- uninstall and reinstall the game -- but that's awkward if the game is large.
