### ISSUE TITLE
[Translation] "Manage Categories" not translated in any language

### ISSUE THREAD

**Issue by Bahasnyldz** [Heroic-Games-Launcher/HeroicGamesLauncher#3898]
### Describe the bug

Manage Categories string not translated in any language even if there is a translated text.

### Add logs

```text
.
```

### Steps to reproduce

1. Choose non english language
1. Go to Library
2. Click on Categories
3. Manage Categories is not translated

### Expected behavior

Display the translation of the "Manage categories".

### Screenshots

![resim](https://github.com/user-attachments/assets/a935e20c-2d44-4b6b-a2a0-f150bfdd4dc4)

### Heroic Version

Latest Stable (Flatpak)

### System Information

Operating System: Bazzite 40
KDE Plasma Version: 6.1.3
KDE Frameworks Version: 6.4.0
Qt Version: 6.7.2
Kernel Version: 6.9.12-203.fsync.fc40.x86_64 (64-bit)
Graphics Platform: Wayland
Processors: 8 × AMD Ryzen 3 5300U with Radeon Graphics
Memory: 6,6 GiB of RAM
Graphics Processor: AMD Radeon Graphics
Manufacturer: LENOVO
Product Name: 82KD
System Version: Lenovo V15 G2 ALC

### Additional information

2.14.1

**Comment by arielj** [comment]
I can't reproduce this, what do you see if you pick spanish?

![image](https://github.com/user-attachments/assets/8c24cf26-376a-41b5-8abc-eb70bc0a9166)

**Comment by arielj** [comment]
This is when I use Turkish

![image](https://github.com/user-attachments/assets/a57fb17b-f319-49c1-ba9b-66746935d88e)

**Comment by Bahasnyldz** [comment]
> I can't reproduce this, what do you see if you pick spanish?
> 
> ![image](https://private-user-images.githubusercontent.com/188464/354849710-8c24cf26-376a-41b5-8abc-eb70bc0a9166.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI3MzMwODUsIm5iZiI6MTcyMjczMjc4NSwicGF0aCI6Ii8xODg0NjQvMzU0ODQ5NzEwLThjMjRjZjI2LTM3NmEtNDFiNS04YWJjLWViNzBiYzBhOTE2Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwNFQwMDUzMDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03MGM1OGRkNTRmNTk3MzE2Y2RmMmNlY2UzMDI0NmM3ZGFhOTQ0ZTc1ZDk5ZGUyNDE4YWM2YTdlMjVmMWZjNjFmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.pXTsIhqcFU1Y2QfS1vKbukY3G666bpnhF6L2Z2e2sQU)

Same, this is on windows 11 same issue.
![image](https://github.com/user-attachments/assets/d6045e4c-3cbb-4370-a96e-30b37d775a0c)

**Comment by arielj** [comment]
try opening the dev tools (right click the tray icon > debug) and see if there's any error message in the Console tab related to translations

**Comment by Bahasnyldz** [comment]
> try opening the dev tools (right click the tray icon > debug) and see if there's any error message in the Console tab related to translations

Sadly there is no error message related to translations.

**Comment by arielj** [comment]
I think that the latest release was released before the translations were complete so that's why you see that (I can reproduce the issue with the latest release, before I was using the main branch from github which doesn't have the issue)

so in that case it will be fixed in the next release because those translations are already present in the development branch

**Comment by Bahasnyldz** [comment]
> I think that the latest release was released before the translations were complete so that's why you see that (I can reproduce the issue with the latest release, before I was using the main branch from github which doesn't have the issue)
> 
> so in that case it will be fixed in the next release because those translations are already present in the development branch

Okay, thank you for your help.
