### ISSUE TITLE
Heroic v2.15.0 - GOG signing error on Linux.

### ISSUE THREAD

**Issue by Dunard** [Heroic-Games-Launcher/HeroicGamesLauncher#3900]
### Describe the bug

First bug: Having a problem loading on fresh loading. Close it and then reopen the Heroic. Error went away.

Second bug: GOG can't be log in. Crash.

Older released works fine. No issue.

### Add logs

```text
These issues not from a game.
```

### Steps to reproduce

2. Click on '...'
3. Scroll down to '...'

### Expected behavior

GOG can't sign in.

### Screenshots

![Screenshot_20240805_093119](https://github.com/user-attachments/assets/f2d6b535-4b5e-493d-9b2d-e1af440add58)
![Screenshot_20240805_093226](https://github.com/user-attachments/assets/1e27c80b-9859-4b1b-abd0-ee93afb0181b)

### Heroic Version

Latest Stable

### System Information

Nobara 40 OS.

**Comment by imLinguin** [comment]
2.15.0 isn't out yet, how did you build the package?

**Comment by Etaash-mathamsetty** [comment]
You built it wrong, you need to download the helper binaries using pnpm

**Comment by Dunard** [comment]
pnpm install helper

Same errors.

**Comment by imLinguin** [comment]
It's `pnpm run download-helper-binaries`

**Comment by Dunard** [comment]
mitchell@nobara-pc:~/HeroicGamesLauncher$ pnpm run download-helper-binaries

> heroic@2.15.0 download-helper-binaries /home/mitchell/HeroicGamesLauncher
> esbuild --bundle --platform=node --target=node21 meta/downloadHelperBinaries.ts | node

sh: line 1: esbuild: command not found
mitchell@nobara-pc:~/HeroicGamesLauncher$

**Comment by Dunard** [comment]
Now it working. After pnpm install then this pnpm run download-helper-binaries

**Comment by Dunard** [comment]
Thank you. No errors now.
![Screenshot_20240807_071739](https://github.com/user-attachments/assets/f31bcb58-c76a-4181-b00f-063ddb0d7b2a)

**Comment by imLinguin** [comment]
awesome
