### ISSUE TITLE
Heroic won't open 

### ISSUE THREAD

**Issue by Izz21** [Heroic-Games-Launcher/HeroicGamesLauncher#392]
### Open here only issues with Heroic like: Heroic doesn't open, some button is out of place, Heroic closes unexpectedly, installs got interrupted, etc.

Heroic games won't open when I launch it.

**To Reproduce**

After installing the deb file and try to launch heroic, it gets stuck loading on my sidebar and will not open.

**Expected behavior**

**Desktop (please complete the following information):**

- OS: Debian
- Version 10 "Buster"
- Game: Heroic Launcher
- Wine/Proton version: Wine 6
- Hardware specs (RAM, CPU, GPU): 32-bit, 64-bit
![Screenshot 2021-05-28 6 38 51 AM](https://user-images.githubusercontent.com/84967690/119971837-7b944b00-bf7f-11eb-97cb-84885060ca9f.png)

**Additional context**

**Comment by flavioislima** [comment]
Since you're using Debian. Can you check your python 3 version? Should be at least 3.8 to work with heroic.

**Comment by flavioislima** [comment]
Would be good to launch it from terminal and check the output as well. You might have some clue

**Comment by Izz21** [comment]
What is the command to launch from terminal?

**Comment by flavioislima** [comment]
heroic
If you installed using the deb that should work

**Comment by debiangamer** [comment]
You can upgrade to Debian Sid where everything works fine and you have latest bug fixes and features faster. Heroic 1.7.0 works fine with Debian Sid.

**Comment by RDKRACZ** [comment]
I have the same issue, after running from a terminal I only got this
```
Protocol already registered.
launching 9d2d0eb64d5c44529cece33fe2a46482

 Launch Command:        /opt/heroic/resources/app.asar.unpacked/build/bin/linux/legendary launch 9d2d0eb64d5c44529cece33fe2a46482  --wine '/home/k0rr/.local/share/lutris/runners/wine/lutris-6.1-3-x86_64/bin/wine64' --wine-prefix '/home/k0rr/.wine' 
launching 9d2d0eb64d5c44529cece33fe2a46482
```

And then the button turns from "Playing" to "Play now", nothing more happens. The game is GTA V.

**Comment by flavioislima** [comment]
> I have the same issue, after running from a terminal I only got this
> ```
> Protocol already registered.
> launching 9d2d0eb64d5c44529cece33fe2a46482
> 
>  Launch Command:        /opt/heroic/resources/app.asar.unpacked/build/bin/linux/legendary launch 9d2d0eb64d5c44529cece33fe2a46482  --wine '/home/k0rr/.local/share/lutris/runners/wine/lutris-6.1-3-x86_64/bin/wine64' --wine-prefix '/home/k0rr/.wine' 
> launching 9d2d0eb64d5c44529cece33fe2a46482
> ```
> 
> And then the button turns from "Playing" to "Play now", nothing more happens. The game is GTA V. 
> Ah yes I tried with non-lutris wine (6.0) before.

In your case is different, it's probably a wine config. Get help on our discord.

**Comment by Izz21** [comment]
It had worked shortly after downloading python but I am trying to open it again after closing it and I'm facing the problem again

**Comment by flavioislima** [comment]
> It had worked shortly after downloading python but I am trying to open it again after closing it and I'm facing the problem again
> 

I think it's like debiangamer said above, this Debian version is probably incompatible. The same thing happened to OpenSuse Leap, heroic also doesn't work there.

Unfortunately there is nothing we can do on our side. 😕
