### ISSUE TITLE
Use `--mangoapp` when `gamescope` and `MangoHud` is enabled

### ISSUE THREAD

**Issue by zastrixarundell** [Heroic-Games-Launcher/HeroicGamesLauncher#3930]
### Problem description

When you use mangohud and gamescope, rather than running mangohud on the gamescope window or the game window, `--mangoapp` should be passed to gamescope.

### Feature description

Automatically add `--mangoapp` option to the generated gamescope command when `MangoHud` is enabled and any option under `GAMESCOPE` is present.

**Comment by Etaash-mathamsetty** [comment]
this has already been fixed
