### ISSUE TITLE
2.15.0: refreshing games library never finishes

### ISSUE THREAD

**Issue by tgurr** [Heroic-Games-Launcher/HeroicGamesLauncher#3932]
### Describe the bug

The spinners keep endlessly spinning and refreshing the games library never finishes. I've configured accounts for Epic, GOG and Amazon.

### Add logs

```text
[...]
(19:51:18) ERROR:   [Frontend]:         Error: Error invoking remote method 'refreshLibrary': TypeError: Cannot read properties of undefined (reading 'url_format')
[...]
```
Log: [2024-08-11T17_48_54-heroic.log](https://github.com/user-attachments/files/16575730/2024-08-11T17_48_54-heroic.log)

### Steps to reproduce

1. Click on 'refresh library'
2. See error

### Expected behavior

Finish refreshing library like with the previous version 2.14.1

### Screenshots

![image](https://github.com/user-attachments/assets/9e72617d-c5b2-4374-b3cc-aeb793d5cc4a)

### Heroic Version

Latest Stable

### System Information

- OS [e. g. "Ubuntu"]: Exherbo Linux

### Additional information
For testing I've also cleared `~/.config/heroic/` and logged back in to all services which didn't make any difference.

**Comment by Wargzax** [comment]
I'm having the same problem. Library never finishes loading. At first my Gog library  was missing. I tried to reset all settings, clear the cache, re login to the Epic/ Gog/ Amazon accounts, but now Epic library is missing too.

**Heroic Version**

Latest Stable

**System Information**

    OS [e. g. "Ubuntu"]: SteamOS Stable

**Comment by arielj** [comment]
looks like some element in the library is missing the square_icon, please use 2.14 until the next release or a build from this PR https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/pull/3933

**Comment by arielj** [comment]
also, can you share a bit more of the log? maybe there's information about the GOG entry that's causing that

**Comment by tgurr** [comment]
> also, can you share a bit more of the log? maybe there's information about the GOG entry that's causing that

I've updated my initial report with the complete log attached. Reading it I also found a minor spelling issue:
(19:48:55) INFO:    [Frontend]:         Updated to a new version, **cleaaning** up the cache.

(Small timely hotfix release would be nice.)

**Comment by arielj** [comment]
> (Small timely hotfix release would be nice.)

you can use the build from https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/pull/3933 temporarily

we want to see if other small issues like this appear and we'll make a hotfix release, but in a couple of days probably

**Comment by arielj** [comment]
@tgurr can you share the `gogdl` log from settings > logs after the error?

the current log doesn't seem to show the correct id that's causing the issue, the gogdl log should show it I think

**Comment by arielj** [comment]
reopening, I didn't mean to close this

**Comment by arielj** [comment]
2.15.1 was released, should show up for update soon to everyone, closing this
