### ISSUE TITLE
Heroic not recognizing Flatpak Steam's Proton nor bottled Wine

### ISSUE THREAD

**Issue by not-a-dev-stein** [Heroic-Games-Launcher/HeroicGamesLauncher#395]
As stated in the title, Heroic doesn't recognize Flatpak Steam's Proton versions nor does it recognize wineprefixes created from [Bottles](https://github.com/bottlesdevs/Bottles).

- OS: Arch Linux
- DE: GNOME 40.1
- Heroic: heroic-games-launcher-bin installed from the chaotic-AUR repo

**Screenshots**
![Captura de tela de 2021-05-29 14-14-27](https://user-images.githubusercontent.com/63420929/120078963-3c9dec80-c088-11eb-87d1-45fcd2846136.png)
~/.local/share/bottles/bottles:
![Captura de tela de 2021-05-29 14-25-04](https://user-images.githubusercontent.com/63420929/120079330-b2568800-c089-11eb-85e3-1591adc208a9.png)
~/.var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/common:
![Captura de tela de 2021-05-29 14-21-53](https://user-images.githubusercontent.com/63420929/120079221-4f64f100-c089-11eb-8997-4073031dfe3a.png)

**Comment by flavioislima** [comment]
Hi!
It's really hard for us to support all kind of configuration, even some distros can't run heroic due to the many different options we have today.

So, for bottles I don't known what this is, but if it creates wine prefixes, should follow then default configuration for wine otherwise won't work.

For steam flatpak, you will need to adapt to the supported paths we have on our wiki.
I know there states that we support flatpak but I never tried myself and in the future we might get back to it, also with a flatpak version of Heroic. But, for now, try using symlink to the other places stated on the wiki like .steam/steam/common/steamapps.

Thanks

**Comment by not-a-dev-stein** [comment]
> So, for bottles I don't known what this is, but if it creates wine prefixes, should follow then default configuration for wine otherwise won't work.

In a nutshell, it creates sandboxed wineprefixes, but I get it's not the usual use for WINE, so I'm not even expecting it to be supported, but, about:
> For steam flatpak, you will need to adapt to the supported paths we have on our wiki.

That's where my issues are coming from. I installed Proton in the regular, supported folder for flatpak (inside `~/.var/app/com.valvesoftware.Steam`) and it isn't showing up, that's why I created the issue. I'll try creating a `~/.local/share/Steam/steamapps/common` and see if that helps.

**Comment by flavioislima** [comment]
> > So, for bottles I don't known what this is, but if it creates wine prefixes, should follow then default configuration for wine otherwise won't work.
> 
> In a nutshell, it creates sandboxed wineprefixes, but I get it's not the usual use for WINE, so I'm not even expecting it to be supported, but, about:
> > For steam flatpak, you will need to adapt to the supported paths we have on our wiki.
> 
> That's where my issues are coming from. I installed Proton in the regular, supported folder for flatpak (inside `~/.var/app/com.valvesoftware.Steam`) and it isn't showing up, that's why I created the issue. I'll try creating a `~/.local/share/Steam/steamapps/common` for the symlink and see if that helps.

I see.
But that's on me then, I forgot to update the wiki with the new path. Check the help box on the wine settings, there I remember I updated with the correct path.

**Comment by adityaruplaha** [comment]
I personally, don't have a problem with supporting Bottles, but supporting every possible path where a prefix might exist is a pain.
