### ISSUE TITLE
[GOG, maybe others?] Certain games use illegal characters for NTFS filenames

### ISSUE THREAD

**Issue by LoneFenris** [Heroic-Games-Launcher/HeroicGamesLauncher#3966]
### Describe the bug

I'm uncertain if there's anything Heroic can do about this, necessarily, as it may be coming from the game package itself, but I thought I'd at least document it.

When trying to install the Linux version DLC for Darkest Dungeon from GOG, I noticed that most of the DLC will refuse to install. This seems to be the result of colons being in the folders/filenames the install tries to create (i.e. "Darkest Dungeon: The Shieldbreaker"), but that being an illegal character for NTFS, which was the target filesystem.

This issue would presumably impact any Linux game using illegal NTFS characters in filenames targeting an NTFS filesystem.

### Add logs

```text
Relevant GOG log:

[8/17/2024, 10:56:52 PM] GOGDL_CONFIG_PATH=/home/lonefenris/.var/app/com.heroicgameslauncher.hgl/config/heroic/gogdlConfig /app/bin/heroic/resources/app.asar.unpacked/build/bin/x64/linux/gogdl --auth-config-path /home/lonefenris/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json update 1450711444 --platform linux --path "/mnt/wally/GOGLinux/Darkest Dungeon" --support /home/lonefenris/.var/app/com.heroicgameslauncher.hgl/config/heroic/gogdlConfig/heroic_gogdl/gog-support/1450711444 --with-dlcs --lang en --dlcs 1128594953,1405492047

[GENERIC DOWNLOAD_MANAGER] INFO: Platform is Linux, redirecting download to Linux Native installer manager

[LINUX] INFO: Initialized Linux Download Manager

[API] INFO: Getting info from products endpoint for id: 1450711444

New/changed files 355

Deleted 0

Total files 8489

(28.575852394104004, 'MB') 29963953

(38.261837005615234, 'MB') 40120444

[PROGRESS] INFO: = Progress: 0.00 0/33526323, Running for: 00:00:00, ETA: 00:00:00

[PROGRESS] INFO: = Downloaded: 0.00 MiB, Written: 0.00 MiB

[PROGRESS] INFO:  + Download	- 0.00 MiB/s (raw) / 0.00 MiB/s (decompressed)

[PROGRESS] INFO:  + Disk	- 0.00 MiB/s (write) / 0.00 MiB/s (read)

Process Writer-18:

Traceback (most recent call last):

  File "multiprocessing/process.py", line 315, in _bootstrap

  File "gogdl/dl/workers/task_executor.py", line 261, in run

  File "gogdl/dl/dl_utils.py", line 41, in prepare_location

  File "os.py", line 225, in makedirs

OSError: [Errno 22] Invalid argument: '/mnt/wally/GOGLinux/Darkest Dungeon/docs/Darkest Dungeon: The Shieldbreaker'
```

### Steps to reproduce

1. Install Darkest Dungeon with no DLC to an NTFS partition
2. Modify the installation and select The Shieldbreaker DLC for install
3. Download/Install will hang and error will show in the GOG log.

Alternatively, a similar effect can be seen when just trying to install all DLC with the base game, except the download will hang with no apparent error about the point it tries to fetch the DLCs

### Expected behavior

The DLC installs

### Heroic Version

Latest Stable (Flatpak)

### System Information

- Arch Linux
- NTFS target filesystem

### Additional information

Workaround would be installing to a non-NTFS partition where the filenames are not illegal. Seems to be able to install to BTRFS and work fine, for example.

**Comment by imLinguin** [comment]
Since this is the way those games are packaged there is nothing we can do. I think it's reasonable to not expect Linux games to install and work fine on a Windows file system, especially when symlinks are a common occurrence

**Comment by imLinguin** [comment]
It's not just about the folder, there is no guarantee that game files are using only Windows fs compatible characters. 

Additionally the Linux NTFS driver has very limited support for symbolic links.

So unless the game checks those two boxes..
- The game doesn't have illegal characters 
- The game doesn't have symlinks

Refrain from using NTFS for Linux native games.

**Comment by LoneFenris** [comment]
@imLinguin I might suggest at least some better error handling of the situation, then. As I mentioned, it's not very obvious to a user what went wrong (or even *that* something went wrong) unless they are watching the logs. Install hangs, rather than fails when this happens, and continues printing out download progress to the log that never actually progresses which also hides the error for someone not actively watching it.
