### ISSUE TITLE
Heroic doesn't need 2 icons on the bar

### ISSUE THREAD

**Issue by Sunspark-007** [Heroic-Games-Launcher/HeroicGamesLauncher#3969]
### Describe the bug

In KDE, Heroic displays 2 icons. 1 in full colour and a second smaller one next to the status icons like wifi, etc.

1) Two icons are not necessary. It is clutter.
2) Weirdly, right-clicking on the smaller icon lists entries for a game that has never been installed in Heroic or Steam and only within a virtual machine. 

### Add logs

```text
No logs because this is UI.
```

### Steps to reproduce

1. Observe bar while Heroic is running. 2 icons.
2. Right-click on smaller icon, see multiple entries from a 86Box VM.

### Expected behavior

1. Single icon only (or the option to do such.)
2. Don't list items that have nothing to do with Heroic.

### Heroic Version

Latest Stable (Flatpak)

### System Information

SteamOS 3.4

**Comment by CommandMC** [comment]
The smaller icon you're seeing is a tray icon. It gives you quick access to Heroic's features, even if you have it minimized. Other game launchers (Steam, Epic, EA App, etc.) do this as well.

If you really do not want the tray icon, you can configure your desktop environment to hide it. For KDE: Right-click the "Show hidden icons" button, click "Configure System Tray". Find Heroic in the list (it might display as just the icon, with no title), set it to "Always hidden".

I'm not sure how those games got into the tray icon though. It is populated based on games you recently launched in Heroic, games outside of Heroic cannot appear there.
You might want to upload the following file: `~/.var/app/com.heroicgameslauncher.hgl/config/heroic/store/config.json` (it stores the recently played games the menu is based on)

**Comment by Sunspark-007** [comment]
![image](https://github.com/user-attachments/assets/68b560fe-6dcc-4513-8a58-51431d4c950a)
[config.json.txt](https://github.com/user-attachments/files/16681875/config.json.txt)

Here is the file, thanks for the tip on hiding it. 

Now that I think about it, I do have a CD.. I wonder if I tried installing it through Heroic, completely forgot about it, and this is why.. that it left remnants of the failed attempts (I ended up installing and updating it myself in a DOS virtual machine, though the CD also had a Windows version as well which I didn't go with because it was missing the audio tracks).. strange that the appName is different for each entry, unless it is supposed to be?

I don't hold it against Heroic if it failed to install the Windows version because it's very old.

It is for sure the game was never launched.. but the installer probably was.

PS. What does "Show" in the menu do? Clicking on it doesn't do anything.

**Comment by CommandMC** [comment]
> Now that I think about it, I do have a CD.. I wonder if I tried installing it through Heroic, completely forgot about it, and this is why

Well, Heroic certainly has them in your recently played list

> strange that the appName is different for each entry, unless it is supposed to be?

That is how Heroic differentiates different games. I assume you've tried adding the game multiple times (at least that's the only way sideloaded games, and subsequently their `appName`s, are generated)

> It is for sure the game was never launched.. but the installer probably was.

Without knowing more about those sideloaded games, I can't say much for certain. But assuming you selected the installer as the game executable, launching the installer = launching the game, as far as Heroic knows

> PS. What does "Show" in the menu do? Clicking on it doesn't do anything.

It shows (brings to front) & focuses the Heroic window. Assuming you already have Heroic open, it'll not look like anything's happening

**Comment by Sunspark-007** [comment]
Thanks for the info. I am closing it because I don't think there's anything to be done here now.
