### ISSUE TITLE
Use Legendary to launch games with Heroic Settings

### ISSUE THREAD

**Issue by redromnon** [Heroic-Games-Launcher/HeroicGamesLauncher#397]
As Heroic Games Launchers uses Legendary and Legendary is command line based, **is there a way to launch a game using Legendary but with additional settings applied in Heroic settings?**

For example, if I enable the MangoHUD and Game-mode options for a game in Heroic Launcher these settings should also be applied if I run ` legendary launch (game) `

I tried to launch a game using legendary but the game runs without the above enabled options.

**Comment by flavioislima** [comment]
Yeah. Simple:
launch heroic from the terminal and then launch the game with the settings you have set.
On the terminal, you will see something like:
Launching game with the following command:
`legendary launch game .. ... ` with all the options heroic added.

Then you can copy this command and use it whenever you want without heroic, like in a bash script to call on lutris or from steam, for instance. 👍🏽

**Comment by redromnon** [comment]
Thanks @flavioislima!
