### ISSUE TITLE
Cant open games from epic

### ISSUE THREAD

**Issue by Ahmey1400** [Heroic-Games-Launcher/HeroicGamesLauncher#3971]
### Describe the bug

when i try to install and play the game it cant opens i tried 2 games and same error

### Add logs

```text
An error has occurred! Try to Logout and Login on your Epic account.
[DLManager] INFO: = Progress: 93.93% (2028/2159), Running for 00:09:55, ETA: 00:00:38
[DLManager] INFO: - Downloaded: 1806.68 MiB, Written: 1899.95 MiB
[DLManager] INFO: - Cache usage: 37.00 MiB, active tasks: 32
[DLManager] INFO: + Download - 1.87 MiB/s (raw) / 1.98 MiB/s (decompressed)
[DLManager] INFO: + Disk - 0.86 MiB/s (write) / 0.00 MiB/s (read)[DLManager] INFO: = Progress: 94.26% (2035/2159), Running for 00:09:56, ETA: 00:00:36[DLManager] INFO: - Downloaded: 1811.61 MiB, Written: 1906.12 MiB
[DLManager] INFO: - Cache usage: 36.00 MiB, active tasks: 32
[DLManager] INFO: + Download - 4.90 MiB/s (raw) / 4.96 MiB/s (decompressed)
[DLManager] INFO: + Disk - 6.13 MiB/s (write) / 0.00 MiB/s (read)[DLManager] INFO: = Progress: 94.44% (2039/2159), Running for 00:09:57, ETA: 00:00:35
[DLManager] INFO: - Downloaded: 1815.58 MiB, Written: 1910.12 MiB
[DLManager] INFO: - Cache usage: 36.00 MiB, active tasks: 32
[DLManager] INFO: + Download - 3.93 MiB/s (raw) / 3.96 MiB/s (decompressed)
[DLManager] INFO: + Disk - 3.96 MiB/s (write) / 0.00 MiB/s (read)[DLManager] INFO: = Progress: 94.49% (2040/2159), Running for 00:09:58, ETA: 00:00:34
[DLManager] INFO: - Downloaded: 1816.58 MiB, Written: 1911.12 MiB
[DLManager] INFO: - Cache usage: 36.00 MiB, active tasks: 32[DLManager] INFO: + Download - 0.99 MiB/s (raw) / 0.99 MiB/s (decompressed)
[DLManager] INFO: + Disk - 0.99 MiB/s (write) / 0.00 MiB/s (read)[DLManager] INFO: = Progress: 94.63% (2043/2159), Running for 00:09:59, ETA: 00:00:34[DLManager] INFO: - Downloaded: 1819.56 MiB, Written: 1914.12 MiB
[DLManager] INFO: - Cache usage: 36.00 MiB, active tasks: 32
[DLManager] INFO: + Download - 2.95 MiB/s (raw) / 2.96 MiB/s (decompressed)[DLManager] INFO: + Disk - 2.96 MiB/s (write) / 0.00 MiB/s (read)[DLManager] INFO: = Progress: 94.72% (2045/2159), Running for 00:10:00, ETA: 00:00:33
[DLManager] INFO: - Downloaded: 1821.54 MiB, Written: 1916.12 MiB
[DLManager] INFO: - Cache usage: 36.00 MiB, active tasks: 32
[DLManager] INFO: + Download - 1.96 MiB/s (raw) / 1.98 MiB/s (decompressed)
[DLManager] INFO: + Disk - 1.98 MiB/s (write) / 0.00 MiB/s (read)[DLManager] INFO: = Progress: 94.91% (2049/2159), Running for 00:10:01, ETA: 00:00:32
[DLManager] INFO: - Downloaded: 1826.51 MiB, Written: 1920.12 MiB
[DLManager] INFO: - Cache usage: 37.00 MiB, active tasks: 32
[DLManager] INFO: + Download - 4.90 MiB/s (raw) / 4.93 MiB/s (decompressed)
[DLManager] INFO: + Disk - 3.95 MiB/s (write) / 0.00 MiB/s (read)[DLManager] INFO: = Progress: 95.09% (2053/2159), Running for 00:10:02, ETA: 00:00:31
[DLManager] INFO: - Downloaded: 1830.15 MiB, Written: 1924.12 MiB
[DLManager] INFO: - Cache usage: 37.00 MiB, active tasks: 32
[DLManager] INFO: + Download - 3.61 MiB/s (raw) / 3.97 MiB/s (decompressed)
[DLManager] INFO: + Disk - 3.97 MiB/s (write) / 0.00 MiB/s (read)[DLManager] INFO: = Progress: 95.09% (2053/2159), Running for 00:10:03, ETA: 00:00:31
[DLManager] INFO: - Downloaded: 1831.14 MiB, Written: 1924.12 MiB
[DLManager] INFO: - Cache usage: 38.00 MiB, active tasks: 32
[DLManager] INFO: + Download - 0.98 MiB/s (raw) / 0.99 MiB/s (decompressed)
[DLManager] INFO: + Disk - 0.00 MiB/s (write) / 0.00 MiB/s (read)[DLManager] INFO: = Progress: 95.09% (2053/2159), Running for 00:10:04, ETA: 00:00:31
[DLManager] INFO: - Downloaded: 1833.26 MiB, Written: 1924.12 MiB
[DLManager] INFO: - Cache usage: 41.00 MiB, active tasks: 32[DLManager] INFO: + Download - 2.10 MiB/s (raw) / 2.97 MiB/s (decompressed)
[DLManager] INFO: + Disk - 0.00 MiB/s (write) / 0.00 MiB/s (read)[DLManager] INFO: = Progress: 95.79% (2068/2159), Running for 00:10:05, ETA: 00:00:26
[DLManager] INFO: - Downloaded: 1838.51 MiB, Written: 1936.18 MiB
[DLManager] INFO: - Cache usage: 35.00 MiB, active tasks: 32[DLManager] INFO: + Download - 5.20 MiB/s (raw) / 5.94 MiB/s (decompressed)
[DLManager] INFO: + Disk - 11.95 MiB/s (write) / 0.00 MiB/s (read)[DLManager] INFO: = Progress: 95.79% (2068/2159), Running for 00:10:06, ETA: 00:00:26
[DLManager] INFO: - Downloaded: 1840.25 MiB, Written: 1936.18 MiB[DLManager] INFO: - Cache usage: 37.00 MiB, active tasks: 32
[DLManager] INFO: + Download - 1.73 MiB/s (raw) / 1.99 MiB/s (decompressed)
[DLManager] INFO: + Disk - 0.00 MiB/s (write) / 0.00 MiB/s (read)[DLManager] INFO: = Progress: 95.97% (2072/2159), Running for 00:10:07, ETA: 00:00:25
[DLManager] INFO: - Downloaded: 1842.82 MiB, Written: 1939.33 MiB
[DLManager] INFO: - Cache usage: 37.00 MiB, active tasks: 32
[DLManager] INFO: + Download - 2.56 MiB/s (raw) / 2.98 MiB/s (decompressed)[DLManager] INFO: + Disk - 3.13 MiB/s (write) / 0.00 MiB/s (read)[DLManager] INFO: = Progress: 96.25% (2078/2159), Running for 00:10:08, ETA: 00:00:23
[DLManager] INFO: - Downloaded: 1846.08 MiB, Written: 1945.33 MiB
[DLManager] INFO: - Cache usage: 35.00 MiB, active tasks: 32
[DLManager] INFO: + Download - 3.23 MiB/s (raw) / 3.96 MiB/s (decompressed)
[DLManager] INFO: + Disk - 5.95 MiB/s (write) / 0.00 MiB/s (read)[DLManager] INFO: = Progress: 96.29% (2079/2159), Running for 00:10:09, ETA: 00:00:23
[DLManager] INFO: - Downloaded: 1849.26 MiB, Written: 1946.33 MiB
[DLManager] INFO: - Cache usage: 38.00 MiB, active tasks: 32
[DLManager] INFO: + Download - 3.16 MiB/s (raw) / 3.97 MiB/s (decompressed)
[DLManager] INFO: + Disk - 0.99 MiB/s (write) / 0.00 MiB/s (read)[DLManager] INFO: = Progress: 96.29% (2079/2159), Running for 00:10:10, ETA: 00:00:23
[DLManager] INFO: - Downloaded: 1851.47 MiB, Written: 1946.33 MiB
[DLManager] INFO: - Cache usage: 41.00 MiB, active tasks: 32[DLManager] INFO: + Download - 2.17 MiB/s (raw) / 2.96 MiB/s (decompressed)
[DLManager] INFO: + Disk - 0.00 MiB/s (write) / 0.00 MiB/s (read)[DLManager] INFO: = Progress: 96.29% (2079/2159), Running for 00:10:11, ETA: 00:00:23
[DLManager] INFO: - Downloaded: 1851.47 MiB, Written: 1946.33 MiB
[DLManager] INFO: - Cache usage: 41.00 MiB, active tasks: 32[DLManager] INFO: + Download - 0.00 MiB/s (raw) / 0.00 MiB/s (decompressed)
[DLManager] INFO: + Disk - 0.00 MiB/s (write) / 0.00 MiB/s (read)[DLManager] INFO: = Progress: 96.67% (2087/2159), Running for 00:10:12, ETA: 00:00:21
[DLManager] INFO: - Downloaded: 1854.57 MiB, Written: 1954.33 MiB
[DLManager] INFO: - Cache usage: 37.00 MiB, active tasks: 32
[DLManager] INFO: + Download - 3.07 MiB/s (raw) / 3.97 MiB/s (decompressed)
[DLManager] INFO: + Disk - 7.93 MiB/s (write) / 0.00 MiB/s (read)[DLManager] INFO: = Progress: 96.76% (2089/2159), Running for 00:10:13, ETA: 00:00:20
[DLManager] INFO: - Downloaded: 1859.07 MiB, Written: 1956.33 MiB[DLManager] INFO: - Cache usage: 41.00 MiB, active tasks: 32
[DLManager] INFO: + Download - 4.47 MiB/s (raw) / 5.96 MiB/s (decompressed)
[DLManager] INFO: + Disk - 1.99 MiB/s (write) / 0.00 MiB/s (read)[DLManager] INFO: = Progress: 97.41% (2103/2159), Running for 00:10:14, ETA: 00:00:16[DLManager] INFO: - Downloaded: 1865.11 MiB, Written: 1969.60 MiB
[DLManager] INFO: - Cache usage: 45.00 MiB, active tasks: 31
[DLManager] INFO: + Download - 5.97 MiB/s (raw) / 17.79 MiB/s (decompressed)
[DLManager] INFO: + Disk - 13.11 MiB/s (write) / 0.00 MiB/s (read)[DLManager] INFO: = Progress: 97.45% (2104/2159), Running for 00:10:15, ETA: 00:00:16
[DLManager] INFO: - Downloaded: 1866.77 MiB, Written: 1970.60 MiB
[DLManager] INFO: - Cache usage: 44.00 MiB, active tasks: 20
[DLManager] INFO: + Download - 1.64 MiB/s (raw) / 10.89 MiB/s (decompressed)
[DLManager] INFO: + Disk - 0.99 MiB/s (write) / 0.00 MiB/s (read)[DLManager] INFO: = Progress: 97.50% (2105/2159), Running for 00:10:16, ETA: 00:00:15
[DLManager] INFO: - Downloaded: 1869.31 MiB, Written: 1971.60 MiB[DLManager] INFO: - Cache usage: 43.00 MiB, active tasks: 13
[DLManager] INFO: + Download - 2.51 MiB/s (raw) / 6.91 MiB/s (decompressed)
[DLManager] INFO: + Disk - 0.99 MiB/s (write) / 0.00 MiB/s (read)[DLManager] INFO: = Progress: 97.50% (2105/2159), Running for 00:10:17, ETA: 00:00:15
[DLManager] INFO: - Downloaded: 1871.41 MiB, Written: 1971.60 MiB
[DLManager] INFO: - Cache usage: 43.00 MiB, active tasks: 9
[DLManager] INFO: + Download - 2.08 MiB/s (raw) / 3.97 MiB/s (decompressed)[DLManager] INFO: + Disk - 0.00 MiB/s (write) / 0.00 MiB/s (read)[DLManager] INFO: = Progress: 99.17% (2141/2159), Running for 00:10:18, ETA: 00:00:05
[DLManager] INFO: - Downloaded: 1877.17 MiB, Written: 2003.14 MiB
[DLManager] INFO: - Cache usage: 11.00 MiB, active tasks: 1
[DLManager] INFO: + Download - 5.71 MiB/s (raw) / 7.92 MiB/s (decompressed)
[DLManager] INFO: + Disk - 31.21 MiB/s (write) / 0.00 MiB/s (read)[DLManager] INFO: = Progress: 100.00% (2159/2159), Running for 00:10:19, ETA: 00:00:00
[DLManager] INFO: - Downloaded: 1878.11 MiB, Written: 2012.67 MiB
[DLManager] INFO: - Cache usage: 0.00 MiB, active tasks: 0
[DLManager] INFO: + Download - 0.92 MiB/s (raw) / 0.99 MiB/s (decompressed)[DLManager] INFO: + Disk - 9.40 MiB/s (write) / 0.00 MiB/s (read)[DLManager] INFO: Waiting for installation to finish...[DLManager] INFO: All done! Download manager quitting...Traceback (most recent call last):
File "legendary\cli.py", line 3161, in <module>File "legendary\cli.py", line 3078, in mainFile "legendary\cli.py", line 1072, in install_gameFile "legendary\core.py", line 1642, in install_gameFile "legendary\core.py", line 1870, in egl_export
File "legendary\lfs\egl.py", line 85, in set_manifestValueError: EGS ProgramData path does not exist[28176] Failed to execute script 'cli' due to unhandled exception!
```

### Steps to reproduce

1. Go to any epic game
2. wait to finish the download
3. try to open the game
4. error..

### Expected behavior

It needs to open

### Heroic Version

Latest Stable

### System Information

- OS [ windows 11]:

### Additional information

also i cant uninstall

**Comment by rairay91** [comment]
Same here

**Comment by CommandMC** [comment]
> `ValueError: EGS ProgramData path does not exist`

You've enabled EGL sync and have now uninstalled the EGL. Untick EGL sync in Heroic's settings

**Comment by Ahmey1400** [comment]
i disabled it and it gave me this error when i try to download:

An error has occurred! Try to Logout and Login on your Epic account.
[DLManager] INFO: = Progress: 85.64% (1849/2159), Running for 00:02:33, ETA: 00:00:25
[DLManager] INFO: - Downloaded: 1649.99 MiB, Written: 1741.91 MiB
[DLManager] INFO: - Cache usage: 36.00 MiB, active tasks: 32
[DLManager] INFO: + Download - 8.85 MiB/s (raw) / 8.92 MiB/s (decompressed)[DLManager] INFO: + Disk - 9.40 MiB/s (write) / 0.00 MiB/s (read)[DLManager] INFO: = Progress: 86.34% (1864/2159), Running for 00:02:34, ETA: 00:00:24
[DLManager] INFO: - Downloaded: 1661.89 MiB, Written: 1754.90 MiB[DLManager] INFO: - Cache usage: 35.00 MiB, active tasks: 32
[DLManager] INFO: + Download - 11.81 MiB/s (raw) / 11.91 MiB/s (decompressed)
[DLManager] INFO: + Disk - 12.89 MiB/s (write) / 0.00 MiB/s (read)[DLManager] INFO: = Progress: 87.12% (1881/2159), Running for 00:02:35, ETA: 00:00:22[DLManager] INFO: - Downloaded: 1676.77 MiB, Written: 1769.07 MiB
[DLManager] INFO: - Cache usage: 35.00 MiB, active tasks: 32
[DLManager] INFO: + Download - 14.77 MiB/s (raw) / 14.89 MiB/s (decompressed)
[DLManager] INFO: + Disk - 14.06 MiB/s (write) / 0.00 MiB/s (read)[DLManager] INFO: = Progress: 87.77% (1895/2159), Running for 00:02:36, ETA: 00:00:21
[DLManager] INFO: - Downloaded: 1687.25 MiB, Written: 1781.08 MiB
[DLManager] INFO: - Cache usage: 33.00 MiB, active tasks: 32
[DLManager] INFO: + Download - 10.36 MiB/s (raw) / 10.88 MiB/s (decompressed)
[DLManager] INFO: + Disk - 11.88 MiB/s (write) / 0.00 MiB/s (read)[DLManager] INFO: = Progress: 88.24% (1905/2159), Running for 00:02:37, ETA: 00:00:20[DLManager] INFO: - Downloaded: 1696.85 MiB, Written: 1790.09 MiB
[DLManager] INFO: - Cache usage: 34.00 MiB, active tasks: 32
[DLManager] INFO: + Download - 9.52 MiB/s (raw) / 9.92 MiB/s (decompressed)
[DLManager] INFO: + Disk - 8.93 MiB/s (write) / 0.00 MiB/s (read)[DLManager] INFO: = Progress: 88.70% (1915/2159), Running for 00:02:38, ETA: 00:00:20[DLManager] INFO: - Downloaded: 1710.66 MiB, Written: 1799.81 MiB
[DLManager] INFO: - Cache usage: 39.00 MiB, active tasks: 32
[DLManager] INFO: + Download - 13.69 MiB/s (raw) / 13.89 MiB/s (decompressed)
[DLManager] INFO: + Disk - 9.64 MiB/s (write) / 0.00 MiB/s (read)[DLManager] INFO: = Progress: 89.39% (1930/2159), Running for 00:02:39, ETA: 00:00:18
[DLManager] INFO: - Downloaded: 1721.38 MiB, Written: 1813.15 MiB[DLManager] INFO: - Cache usage: 37.00 MiB, active tasks: 32
[DLManager] INFO: + Download - 10.66 MiB/s (raw) / 10.94 MiB/s (decompressed)
[DLManager] INFO: + Disk - 13.27 MiB/s (write) / 0.00 MiB/s (read)[DLManager] INFO: = Progress: 90.04% (1944/2159), Running for 00:02:40, ETA: 00:00:17[DLManager] INFO: - Downloaded: 1734.09 MiB, Written: 1827.15 MiB
[DLManager] INFO: - Cache usage: 36.00 MiB, active tasks: 32
[DLManager] INFO: + Download - 12.59 MiB/s (raw) / 12.87 MiB/s (decompressed)
[DLManager] INFO: + Disk - 13.86 MiB/s (write) / 0.00 MiB/s (read)[DLManager] INFO: = Progress: 90.78% (1960/2159), Running for 00:02:41, ETA: 00:00:16
[DLManager] INFO: - Downloaded: 1745.03 MiB, Written: 1840.04 MiB[DLManager] INFO: - Cache usage: 34.00 MiB, active tasks: 32
[DLManager] INFO: + Download - 10.88 MiB/s (raw) / 10.94 MiB/s (decompressed)
[DLManager] INFO: + Disk - 12.82 MiB/s (write) / 0.00 MiB/s (read)[DLManager] INFO: = Progress: 91.15% (1968/2159), Running for 00:02:42, ETA: 00:00:15
[DLManager] INFO: - Downloaded: 1756.90 MiB, Written: 1845.21 MiB
[DLManager] INFO: - Cache usage: 41.00 MiB, active tasks: 32[DLManager] INFO: + Download - 11.77 MiB/s (raw) / 11.90 MiB/s (decompressed)
[DLManager] INFO: + Disk - 5.13 MiB/s (write) / 0.00 MiB/s (read)[DLManager] INFO: = Progress: 91.80% (1982/2159), Running for 00:02:43, ETA: 00:00:14
[DLManager] INFO: - Downloaded: 1765.66 MiB, Written: 1858.19 MiB[DLManager] INFO: - Cache usage: 37.00 MiB, active tasks: 32
[DLManager] INFO: + Download - 8.71 MiB/s (raw) / 8.94 MiB/s (decompressed)
[DLManager] INFO: + Disk - 12.89 MiB/s (write) / 0.00 MiB/s (read)[DLManager] INFO: = Progress: 92.26% (1992/2159), Running for 00:02:44, ETA: 00:00:13
[DLManager] INFO: - Downloaded: 1778.40 MiB, Written: 1868.19 MiB
[DLManager] INFO: - Cache usage: 40.00 MiB, active tasks: 32[DLManager] INFO: + Download - 12.65 MiB/s (raw) / 12.91 MiB/s (decompressed)
[DLManager] INFO: + Disk - 9.93 MiB/s (write) / 0.00 MiB/s (read)[DLManager] INFO: = Progress: 93.10% (2010/2159), Running for 00:02:45, ETA: 00:00:12
[DLManager] INFO: - Downloaded: 1790.96 MiB, Written: 1886.01 MiB[DLManager] INFO: - Cache usage: 36.00 MiB, active tasks: 32
[DLManager] INFO: + Download - 12.46 MiB/s (raw) / 12.90 MiB/s (decompressed)
[DLManager] INFO: + Disk - 17.67 MiB/s (write) / 0.00 MiB/s (read)[DLManager] INFO: = Progress: 93.61% (2021/2159), Running for 00:02:46, ETA: 00:00:11[DLManager] INFO: - Downloaded: 1800.84 MiB, Written: 1896.02 MiB
[DLManager] INFO: - Cache usage: 36.00 MiB, active tasks: 32
[DLManager] INFO: + Download - 9.78 MiB/s (raw) / 9.90 MiB/s (decompressed)
[DLManager] INFO: + Disk - 9.91 MiB/s (write) / 0.00 MiB/s (read)[DLManager] INFO: = Progress: 94.40% (2038/2159), Running for 00:02:47, ETA: 00:00:09
[DLManager] INFO: - Downloaded: 1815.59 MiB, Written: 1909.12 MiB[DLManager] INFO: - Cache usage: 37.00 MiB, active tasks: 32
[DLManager] INFO: + Download - 14.59 MiB/s (raw) / 14.84 MiB/s (decompressed)
[DLManager] INFO: + Disk - 12.96 MiB/s (write) / 0.00 MiB/s (read)[DLManager] INFO: = Progress: 94.67% (2044/2159), Running for 00:02:48, ETA: 00:00:09
[DLManager] INFO: - Downloaded: 1823.19 MiB, Written: 1915.12 MiB[DLManager] INFO: - Cache usage: 39.00 MiB, active tasks: 32
[DLManager] INFO: + Download - 7.55 MiB/s (raw) / 7.95 MiB/s (decompressed)
[DLManager] INFO: + Disk - 5.96 MiB/s (write) / 0.00 MiB/s (read)[DLManager] INFO: = Progress: 95.79% (2068/2159), Running for 00:02:49, ETA: 00:00:07
[DLManager] INFO: - Downloaded: 1838.51 MiB, Written: 1936.18 MiB[DLManager] INFO: - Cache usage: 35.00 MiB, active tasks: 32
[DLManager] INFO: + Download - 15.17 MiB/s (raw) / 16.83 MiB/s (decompressed)
[DLManager] INFO: + Disk - 20.85 MiB/s (write) / 0.00 MiB/s (read)[DLManager] INFO: = Progress: 96.29% (2079/2159), Running for 00:02:50, ETA: 00:00:06[DLManager] INFO: - Downloaded: 1850.05 MiB, Written: 1946.33 MiB
[DLManager] INFO: - Cache usage: 39.00 MiB, active tasks: 32
[DLManager] INFO: + Download - 11.44 MiB/s (raw) / 13.89 MiB/s (decompressed)
[DLManager] INFO: + Disk - 10.07 MiB/s (write) / 0.00 MiB/s (read)[DLManager] INFO: = Progress: 97.04% (2095/2159), Running for 00:02:51, ETA: 00:00:05
[DLManager] INFO: - Downloaded: 1862.11 MiB, Written: 1962.33 MiB
[DLManager] INFO: - Cache usage: 43.00 MiB, active tasks: 32
[DLManager] INFO: + Download - 11.96 MiB/s (raw) / 19.83 MiB/s (decompressed)[DLManager] INFO: + Disk - 15.86 MiB/s (write) / 0.00 MiB/s (read)[DLManager] INFO: = Progress: 99.03% (2138/2159), Running for 00:02:52, ETA: 00:00:01
[DLManager] INFO: - Downloaded: 1873.66 MiB, Written: 2000.96 MiB
[DLManager] INFO: - Cache usage: 13.00 MiB, active tasks: 5[DLManager] INFO: + Download - 11.43 MiB/s (raw) / 35.63 MiB/s (decompressed)
[DLManager] INFO: + Disk - 38.24 MiB/s (write) / 0.00 MiB/s (read)[DLManager] INFO: = Progress: 100.00% (2159/2159), Running for 00:02:53, ETA: 00:00:00[DLManager] INFO: - Downloaded: 1878.11 MiB, Written: 2012.67 MiB
[DLManager] INFO: - Cache usage: 0.00 MiB, active tasks: 0
[DLManager] INFO: + Download - 4.41 MiB/s (raw) / 4.96 MiB/s (decompressed)
[DLManager] INFO: + Disk - 11.61 MiB/s (write) / 0.00 MiB/s (read)[DLManager] INFO: Waiting for installation to finish...[DLManager] INFO: All done! Download manager quitting...Traceback (most recent call last):
File "legendary\cli.py", line 3161, in <module>File "legendary\cli.py", line 3078, in mainFile "legendary\cli.py", line 1072, in install_game
File "legendary\core.py", line 1642, in install_gameFile "legendary\core.py", line 1870, in egl_exportFile "legendary\lfs\egl.py", line 85, in set_manifestValueError: EGS ProgramData path does not exist
[17064]Failed to execute script 'cli' due to unhandled exception!

**Comment by Ahmey1400** [comment]
also when i try to uninstall it ti gave me this:

An error has occurred! Try to Logout and Login on your Epic account.
[Core] INFO: Synced app "ca0e1d19d3b640b39d8d20e966067872" is no longer in the EGL manifest list.[Core] INFO: Game files exist, assuming game is still installed, re-exporting to EGL...Traceback (most recent call last):
File "legendary\cli.py", line 3161, in <module>File "legendary\cli.py", line 3080, in main
File "legendary\cli.py", line 1165, in uninstall_gameFile "legendary\core.py", line 585, in get_installed_game
File "legendary\core.py", line 1911, in egl_syncFile "legendary\core.py", line 1893, in egl_restore_or_uninstallFile "legendary\core.py", line 1870, in egl_exportFile "legendary\lfs\egl.py", line 85, in set_manifest
ValueError: EGS ProgramData path does not exist
[26204]Failed to execute script 'cli' due to unhandled exception!

**Comment by CommandMC** [comment]
Doesn't seem like it's disabled there.

You could also try manually disabling it. Open up a command prompt and run the following:
```
SET "LEGENDARY_CONFIG_PATH=%APPDATA%\heroic\legendaryConfig\legendary"
"%LOCALAPPDATA%\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\legendary" egl-sync --disable-sync
```

**Comment by Ahmey1400** [comment]
it says this: The system cannot find the path specified.

**Comment by CommandMC** [comment]
Oh right, hang on, the path changed

```cmd
SET "LEGENDARY_CONFIG_PATH=%APPDATA%\heroic\legendaryConfig\legendary"
"%LOCALAPPDATA%\Programs\heroic\resources\app.asar.unpacked\build\bin\x64\win32\legendary" egl-sync --disable-sync
```

**Comment by Ahmey1400** [comment]
its fixed,thanks a lot mate
