### ISSUE TITLE
Reducing left panel to just icons.

### ISSUE THREAD

**Issue by roland-5** [Heroic-Games-Launcher/HeroicGamesLauncher#3990]
### Problem description

![ps_20240901211535](https://github.com/user-attachments/assets/dbcda3a9-a456-412f-b945-089b9b5569c1)

### Feature description

I'm little blind and to feel comfortably I significantly enlarged the game covers. Problem is, not only game covers are bigger, but left panel too. Could be there option to minimize it to just icons? For 170% zoom in, a 5th title game cover could appear in the row.

**Comment by imLinguin** [comment]
You can easily control the width of the sidebar already just drag the edge of it

**Comment by roland-5** [comment]
Och, my, god... Sorry for trouble. you are right.
