### ISSUE TITLE
DXVK options for Whisky wine

### ISSUE THREAD

**Issue by Dark-Schneider-666** [Heroic-Games-Launcher/HeroicGamesLauncher#4034]
### Problem description

Cannot choose to use DXVK when launching games from Heroic using Whisky, it always uses GTPK. Noticed that for DX11 games in some cases DXVK performs better than D3DMetal.

### Feature description

We'd need both Whisky options for DXVK, which are using it instead GPTK, and with or without Async, as present in the own Whisky app bottle options.

**Comment by mix3d** [comment]
I've tried the WineTricks feature to enable DXVK as well, but it did not appear to work, at least for the game I have separately setup and working directly in Whisky with DXVK settings enabled. 

Alternatively, would it be possible to connect Heroic to an existing/preconfigured Bottle? That might also solve this problem.

**Comment by flavioislima** [comment]
Yeah, that is intentional because GPTK already users DXVK and the normal DXVK will break the prefix.
Maybe something changed on 2.0 but up to 1.1 it was like this.
So the option is disabled for those.

**Comment by flavioislima** [comment]
If you need to use DXVK go to Wine Manager and Download Wine-Crossover, then DXVK will be available.
For DX9 and DX10 games this is the best option.

**Comment by Dark-Schneider-666** [comment]
Unfortunately cannot make most games to work with the Wine-Crossover option, games that works with Whisky or CrossOver.
