### ISSUE TITLE
"Browse files" option

### ISSUE THREAD

**Issue by hfc2x** [Heroic-Games-Launcher/HeroicGamesLauncher#4037]
### Problem description

I needed to change some text configuration for a game, and I needed to go into the install folder. I realized Heroic has no such option, so I had to go to the install folder manually.

### Feature description

This should be a simple option like Lutris has when wanting to open the install folder of a game.

### Additional information

I'm on Fedora 40. Heroic is installed via the COPR repository.

**Comment by redromnon** [comment]
Hi, I believe you can open the game's install folder from a game page: click on _Installed Information_ -> _Install Path_ and Heroic will open the install folder using your native file manager.

**Comment by arielj** [comment]
Yes, clicking the install path in the game page information opens the file explorer in the installation folder. Also clicking the wine prefix path opens the file explorer in the wine prefix folder.

Closing, feel free tor reply and we can reopen if this is not what you meant.

**Comment by Coolumin** [comment]
> Yes, clicking the install path in the game page information opens the file explorer in the installation folder. Also clicking the wine prefix path opens the file explorer in the wine prefix folder.
> 
> Closing, feel free tor reply and we can reopen if this is not what you meant.

This isn't really what OP is looking for (and frankly not what I'm looking for either). Clicking the game's option for the changing the install path is for changing where it's installed from, and thus opens an in-app pop-up window rather than a normal file explorer window. 

What's desired here is just a shortcut button that takes you directly inside the game's folder by opening a new window of the file explorer used by the system, just like on Steam or Lutris.

**Comment by arielj** [comment]
> > Yes, clicking the install path in the game page information opens the file explorer in the installation folder. Also clicking the wine prefix path opens the file explorer in the wine prefix folder.
> > Closing, feel free tor reply and we can reopen if this is not what you meant.
> 
> This isn't really what OP is looking for (and frankly not what I'm looking for either). Clicking the game's option for the changing the install path is for changing where it's installed from, and thus opens an in-app pop-up window rather than a normal file explorer window.
> 
> What's desired here is just a shortcut button that takes you directly inside the game's folder by opening a new window of the file explorer used by the system, just like on Steam or Lutris.

I wasn't talking about the option to change the installation path, I was talking about the install path and prefix path displayed under `Installed Information`:

![Image](https://github.com/user-attachments/assets/3055b171-ae2b-4589-992f-6f4408927d9a)

those 2 paths open those 2 paths in the file explorer

**Comment by hfc2x** [comment]
I think I could probably do a pull request next week to add the option (without removing the already existing one) to a more standard location like the three dots option sub menu.

**Comment by arielj** [comment]
> I think I could probably do a pull request next week to add the option (without removing the already existing one) to a more standard location like the three dots option sub menu.

there is one already https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/pull/4285
