### ISSUE TITLE
UMU launcher does not function in the flatpak version of heroic 2.15.2

### ISSUE THREAD

**Issue by Anseryde** [Heroic-Games-Launcher/HeroicGamesLauncher#4048]
### Describe the bug

When umu-launcher is enabled within heroic via the advanced settings, games using proton will not launch. The games using proton will launch when umu-launcher is disabled.

### Add logs

```text
Launching "Control Ultimate Edition" (gog)

Native? No

Installed in: /home/ryann/Games/Heroic/Control

System Info:

CPU: 16x 13th Gen Intel(R) Core(TM) i7-13620H

Memory: 16.45 GB (used: 9.09 GB)

GPUs:

  GPU 0:

    Name: NVIDIA Corporation AD107M [GeForce RTX 4060 Max-Q / Mobile]

    IDs: D=28a0 V=10de SD=13c7 SV=1462

    Driver: nvidia

  GPU 1:

    Name: Intel Corporation Raptor Lake-P [UHD Graphics]

    IDs: D=a7a8 V=8086 SD=13c7 SV=1462

    Driver: i915

OS: Fedora Linux 40 (KDE Plasma) (linux)

The current system is not a Steam Deck

We are running inside a Flatpak container

Software Versions:

  Heroic: 2.15.2 Emeth

  Legendary: 0.20.36 Urban Flight (Heroic)

  gogdl: 1.1.2

  comet: comet 0.1.2

  Nile: 1.1.2 Will A. Zeppeli

Game Settings: {

	"autoInstallDxvk": true,

	"autoInstallDxvkNvapi": true,

	"autoInstallVkd3d": true,

	"preferSystemLibs": false,

	"enableEsync": true,

	"enableMsync": false,

	"enableFsync": true,

	"launcherArgs": "",

	"nvidiaPrime": true,

	"enviromentOptions": [],

	"wrapperOptions": [],

	"showFps": false,

	"useGameMode": false,

	"battlEyeRuntime": false,

	"eacRuntime": false,

	"language": "",

	"beforeLaunchScriptPath": "",

	"afterLaunchScriptPath": "",

	"wineVersion": {

		"bin": "/home/ryann/.var/app/com.valvesoftware.Steam/.local/share/Steam/compatibilitytools.d/GE-Proton9-15/proton",

		"name": "Proton - GE-Proton9-15",

		"type": "proton"

	},

	"winePrefix": "/home/ryann/Games/Heroic/Prefixes/default/Control Ultimate Edition",

	"wineCrossoverBottle": ""

}

Game launched at: Wed Oct 09 2024 14:13:03 GMT+0800 (Singapore Standard Time)

Winetricks packages: 

Launch Command: HEROIC_APP_NAME=2049187585 HEROIC_APP_RUNNER=gog GAMEID=umu-0 HEROIC_APP_SOURCE=gog STORE=gog DRI_PRIME=1 __NV_PRIME_RENDER_OFFLOAD=1 __GLX_VENDOR_LIBRARY_NAME=nvidia STEAM_COMPAT_INSTALL_PATH=/home/ryann/Games/Heroic/Control LD_PRELOAD= STEAM_COMPAT_CLIENT_INSTALL_PATH=/home/ryann/.var/app/com.heroicgameslauncher.hgl/.steam/steam WINEPREFIX="/home/ryann/Games/Heroic/Prefixes/default/Control Ultimate Edition" STEAM_COMPAT_DATA_PATH="/home/ryann/Games/Heroic/Prefixes/default/Control Ultimate Edition" PROTONPATH=/home/ryann/.var/app/com.valvesoftware.Steam/.local/share/Steam/compatibilitytools.d/GE-Proton9-15 WINE_FULLSCREEN_FSR=0 PROTON_ENABLE_NVAPI=1 DXVK_NVAPI_ALLOW_OTHER_DRIVERS=1 STEAM_COMPAT_APP_ID=0 SteamAppId=0 SteamGameId=heroic-Control PROTON_LOG_DIR=/home/ryann/.var/app/com.heroicgameslauncher.hgl /app/bin/heroic/resources/app.asar.unpacked/build/bin/x64/linux/gogdl launch /home/ryann/Games/Heroic/Control 2049187585 --no-wine --wrapper "/home/ryann/.var/app/com.heroicgameslauncher.hgl/config/heroic/tools/runtimes/umu/umu_run.py" --platform windows

Game Log:

[1msteamrt is up to date[0m

/home/ryann/.var/app/org.openwinecomponents.umu.umu-launcher/data/umu/run: line 22: /home/ryann/.var/app/org.openwinecomponents.umu.umu-launcher/data/umu/pressure-vessel/bin/pressure-vessel-unruntime: No such file or directory

Launch command: ['/home/ryann/.var/app/com.heroicgameslauncher.hgl/config/heroic/tools/runtimes/umu/umu_run.py', '/home/ryann/Games/Heroic/Control/Control.exe']

All processes exited

============= End of log =============
```

### Steps to reproduce

1. Under Advanced Settings tab of Heroic Games launcher tick the box for umu
2. Launch a game using any proton version

### Expected behavior

The game launches without any issues using proton and umu-launcher.

### Heroic Version

Latest Stable (Flatpak)

### System Information

             .',;::::;,'.                
         .';:cccccccccccc:;,.            -------------------- 
      .;cccccccccccccccccccccc;.         OS: Fedora Linux 40 (KDE Plasma) x86_64 
    .:cccccccccccccccccccccccccc:.       Host: Katana 15 B13VFK REV:1.0 
  .;ccccccccccccc;.:dddl:.;ccccccc;.     Kernel: 6.10.12-200.fc40.x86_64 
 .:ccccccccccccc;OWMKOOXMWd;ccccccc:.    Uptime: 1 day, 1 hour, 11 mins 
.:ccccccccccccc;KMMc;cc;xMMc;ccccccc:.   Packages: 3267 (dnf), 15 (steam), 82 (flatpak-system) 
,cccccccccccccc;MMM.;cc;;WW:;cccccccc,   Shell: fish 3.7.0 
:cccccccccccccc;MMM.;cccccccccccccccc:   Editor: GNU nano 7.2 
:ccccccc;oxOOOo;MMM0OOk.;cccccccccccc:   Resolution: 2560x1440 
cccccc;0MMKxdd:;MMMkddc.;cccccccccccc;   DE: Plasma 6.1.5 [KF5 ] [Qt ] (wayland) 
ccccc;XM0';cccc;MMM.;cccccccccccccccc'   WM: kwin_wayland_wr 
ccccc;MMo;ccccc;MMW.;ccccccccccccccc;    Theme: Breeze-Dark [GTK2/3] 
ccccc;0MNc.ccc.xMMd;ccccccccccccccc;     Icons: Tela [GTK2/3] 
cccccc;dNMWXXXWM0:;cccccccccccccc:,      Cursor: breeze_cursors [GTK2/3] 
cccccccc;.:odl:.;cccccccccccccc:,.       Terminal: yakuake 
:cccccccccccccccccccccccccccc:'.         CPU: 13th Gen Intel i7-13620H (16) @ 4.7GHz 
.:cccccccccccccccccccccc:;,..            GPU: NVIDIA GeForce RTX 4060 Max-Q / Mobile 
  '::cccccccccccccc::;,.                 GPU: Intel Raptor Lake-P [UHD Graphics] 
                                         Memory: 8.40 GiB / 15.31 GiB (54%) 
                                         Network: Wifi6 
                                         Bluetooth: Intel Corp. AX211 
                                         BIOS: American Megatrends International, LLC. 1.22 (07/11/2024)

**Comment by Gamertech** [comment]
Posted on Discord, but I have this too as does another.

Lutris now has the same issue so seems like there was a runtime update and now Heroic's been told to look for umu-launcher in the location where the flatpak install would exist if umu had one.

`/home/gamertech/.var/app/org.openwinecomponents.umu.umu-launcher/data/umu/run: line 22: /home/gamertech/.var/app/org.openwinecomponents.umu.umu-launcher/data/umu/pressure-vessel/bin/pressure-vessel-unruntime: No such file or directory`

**Comment by R1kaB3rN** [comment]
Hi, the `No such file or directory` error has already been fixed since https://github.com/Open-Wine-Components/umu-launcher/pull/207 and merged in the main branch of umu-launcher.

For now, until the next hotfix is released, users will need to build the user install umu-launcher from source and replace the umu-run executable in Heroic's runtime directory. Afterwards, delete `$HOME/.var/app/org.openwinecomponents.umu.umu-launcher/data/umu` then relaunch your game. To make it simple for you, so you don't have to build it, I'll attach the executable below but be sure to decompress it.

[umu-run.gz](https://github.com/user-attachments/files/17334546/umu-run.gz)

**Comment by Gamertech** [comment]
After today's 1.1.3 update, it's finally working in Heroic flatpak again thank you.

One issue, the umu-run.py isn't set as executable, so wouldn't launch until flagged manually.

**Comment by Arcitec** [comment]
Works for me in latest Heroic. Can close this ticket.
