### ISSUE TITLE
Game specific WINE

### ISSUE THREAD

**Issue by Doomsdayrs** [Heroic-Games-Launcher/HeroicGamesLauncher#405]
**Is your feature request related to a problem? Please describe.**
One issue I have is that when setting up wine for certain games, one must modify the environment to fit said game. But these modifications can conflict with out games, leading to headache and time wasted.

**Describe the solution you'd like**
Instead of using the global wine folder, have each game be equipped with its own wine prefix. This allows a more in depth and configurable environment for games

**Comment by kcthrn** [comment]
You can already assign a separate wine prefix and wine version in each game's settings.

Look for the _WinePrefix folder_ input field and _Wine Version_ dropdown box under _Wine_ in the game's settings in Heroic.
