### ISSUE TITLE
macOS? Heroic does not load games when in a folder with spaces

### ISSUE THREAD

**Issue by StefanLobbenmeier** [Heroic-Games-Launcher/HeroicGamesLauncher#406]
**Describe the bug**
I just built this for macOS and installed it to the Applications folder. I opened it and it was stuck loading the games list.
I then started the binary via the terminal to see the logs:

```
➜  MacOS pwd                       
/Applications/Heroic Games Launcher.app/Contents/MacOS
➜  MacOS ./Heroic\ Games\ Launcher 
Default Wine not installed
Default Wine not installed
Protocol already registered.
Error occurred in handler for 'checkGameUpdates': Error: Command failed: /Applications/Heroic Games Launcher.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/legendary list-installed --check-updates --tsv
/bin/sh: /Applications/Heroic: No such file or directory

    at ChildProcess.exithandler (child_process.js:317:12)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1048:16)
    at Socket.<anonymous> (internal/child_process.js:439:11)
    at Socket.emit (events.js:315:20)
    at Pipe.<anonymous> (net.js:673:12) {
  killed: false,
  code: 127,
  signal: null,
  cmd: '/Applications/Heroic Games Launcher.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/legendary list-installed --check-updates --tsv',
  stdout: '',
  stderr: '/bin/sh: /Applications/Heroic: No such file or directory\n'
}
^C% 
```

**To Reproduce**

1. Launch Heroic from a folder with spaces (e.g. default installation on macOS)

**Expected behavior**
The game list is shown

**Screenshots**
Screenshot of Heroic when stuck loading:
![image](https://user-images.githubusercontent.com/36509607/120900449-1ef6f700-c635-11eb-941e-2ec765f34a03.png)

**Desktop (please complete the following information):**

- OS: macOS Big Sur
- Version 521620abae366b7d3725b07b94e100b275da25f9  (Actually on my fork: https://github.com/StefanLobbenmeier/HeroicGamesLauncher/commit/521620abae366b7d3725b07b94e100b275da25f9)
- Game: -
- Wine/Proton version: -
- Hardware specs (RAM, CPU, GPU): x86

**Additional context**

**Comment by StefanLobbenmeier** [comment]
By the way, feel free to reproduce on other platforms and comment if this is only macOS. I guess the same behaviour could occur on other platforms as well, but it is installed differently there. Or there is a bug specific to the macOS implementation of resolving that path that forgot to insert quotes.

**Comment by StefanLobbenmeier** [comment]
Looking at the source code the issue probably occurs in that line: https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/blob/6a35318e8047253060734d3ac9b94273b82662fd/electron/legendary_utils/library.ts#L147 (I could be wrong, haven't run it with debugger)

Which means that this line should be fixed? https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/blob/6a35318e8047253060734d3ac9b94273b82662fd/electron/constants.ts#L24

**Comment by flavioislima** [comment]
> By the way, feel free to reproduce on other platforms and comment if this is only macOS. I guess the same behaviour could occur on other platforms as well, but it is installed differently there. Or there is a bug specific to the macOS implementation of resolving that path that forgot to insert quotes.

No, this doesn't happens on Linux or Windows.
Might be just the name of the folder when building because it's trying to find the legendary binary.
So maybe we just need to change the build config of macos to call the app just heroic instead of the full name.

@entaromia created the mac version, so he probably knows best.

**Comment by StefanLobbenmeier** [comment]
I think it should also work in a folder with blanks in it. The recommended fix is to wrap the executable in quotes: https://github.com/nodejs/node/issues/6803

**Comment by Nocccer** [comment]
Maybe this happens because i removed alot of stuff which was wrapped like this:
`${filePahts[0]}`
and i changed it to:
filePaths[0]

**Comment by flavioislima** [comment]
Should be fixed on the main branch now @StefanLobbenmeier

**Comment by StefanLobbenmeier** [comment]
Actually master has a different issue now, does not start at all:

```
(node:35701) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'replace' of undefined
    at /Applications/Heroic Games Launcher.app/Contents/Resources/app.asar/build/main.js:171:66
    at Generator.next (<anonymous>)
    at fulfilled (/Applications/Heroic Games Launcher.app/Contents/Resources/app.asar/build/main.js:24:58)
(Use `Heroic Games Launcher --trace-warnings ...` to show where the warning was created)
(node:35701) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:35701) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

**Comment by adityaruplaha** [comment]
Crap, something must've broken pretty bad.

**Comment by flavioislima** [comment]
> Crap, something must've broken pretty bad.

That would be new 😅

**Comment by Linux4Good** [comment]
Thats my fault. 
I forgot to limit the python version check to linux.
So its trying to read the python version on mac and its getting undefined. Simple fix.
I'll do it on my branch but if you want to fix it yourself @StefanLobbenmeier, remove the python check on lines 195 and 255 of main.js.

**Comment by flavioislima** [comment]
Fixed on main branch
