### ISSUE TITLE
Merge multiple entries for games owned on multiple platforms

### ISSUE THREAD

**Issue by eggmanstudio** [Heroic-Games-Launcher/HeroicGamesLauncher#4098]
### Problem description

I opwn several games on more than one platform across GOG, Amazon and Epic. These games appear more than once in my library, as separate games.

### Feature description

For multiple entries for the same game to be merged into a single entry, ideally with the option of choosing which service you want to download it from.

**Comment by arielj** [comment]
closing as duplicate of https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/issues/3010
