### ISSUE TITLE
Uncought exception occured

### ISSUE THREAD

**Issue by ScatterAdd** [Heroic-Games-Launcher/HeroicGamesLauncher#4100]
### Describe the bug

Message of the window:
A uncaught exception occured:
Error: Render frame was disposed before WebFrameMain could be accessed
Report the exception on our Github repository.

### Add logs

```text
It's a problem with the launcher, not with a game.
There are no logs
```

### Steps to reproduce

open Heroic
change to GOG
push GOG.com Button or Store
The window dissapears when I click twice the store or anywhere to the Gog screen.

### Expected behavior

Change to Store View at GOG without error Window

### Screenshots

I hope this works:
https://imgur.com/2S1DAYb

### Heroic Version

Latest Stable

### System Information

Linux Mint 22

### Additional information

20 minutes later it seems the GOG side was the trouble maker.
I only did what the error windows sayed, report to github :o)

PLS close the ticket.

**Comment by thatLeaflet** [comment]
Could you reopen this? This is still an issue.

I can reliably trigger this issue by by clicking on a Winter Calendar Sale box.

![image](https://github.com/user-attachments/assets/8c97d79e-ffe6-49fd-bdf2-e82b5e6ad323)
