### ISSUE TITLE
Heroic does not install owned DLC

### ISSUE THREAD

**Issue by CzernyJ** [Heroic-Games-Launcher/HeroicGamesLauncher#4103]
### Describe the bug

I installed Age of Wonders 4 from GOG using Heroic Game Launcher. 

Although I own the most up to date DLC, it is not installed by Heroic Game Launcher. The game still claims it does not have the DLC. Double checked, that GOG lists the DLC under my Games. Force Update does not activate the DLC.

### Add logs

```text
Heroic Log
https://0x0.st/XDW6.log

GOG Log
https://0x0.st/XDWJ.log

Game Starter Log
https://0x0.st/XDWU.log
```

### Steps to reproduce

Sorry do not really know how to reproduce this case.

### Expected behavior

I would expect to either see the DLC or have a outstandnig Update.

### Heroic Version

Latest Stable

### System Information

PopOS 22.04 LTS

**Comment by imLinguin** [comment]
Did you check 
![obraz](https://github.com/user-attachments/assets/355c48dc-fe6d-417a-8c74-cd5af66fd546)

Heroic doesn't do many things automatically, though in the case of DLCs maybe it's something to consider...

**Comment by flavioislima** [comment]
I think makes sense to install them automatically since this is the behavior other launchers like Steam does. 
And then we will always have the option to remove using the Modify button.

**Comment by CzernyJ** [comment]
Looks like I did not check that one :facepalm: 

It did result in the correct behavior.

**Comment by lmReef** [comment]
The DLCs still did not show in the `modify installation` section for me.
For anyone else looking for a workaround I went to https://www.gog.com/en/account where I could manually download and install each DLC by running the `.exe` with heroic's `RUN EXE ON PREFIX` option
