### ISSUE TITLE
Steam Deck Built In Controller not working in game

### ISSUE THREAD

**Issue by antonlinux123** [Heroic-Games-Launcher/HeroicGamesLauncher#4108]
### Describe the bug

When I launched a gog game from the default steam deck ui, the game would launch but the built in steam controller was not working, this is also the case in desktop mode.

### Add logs

```text
(21:01:02) INFO:    [Legendary]:        Legendary location: /app/bin/heroic/resources/app.asar.unpacked/build/bin/x64/linux/legendary
(21:01:02) INFO:    [Gog]:              GOGDL location: /app/bin/heroic/resources/app.asar.unpacked/build/bin/x64/linux/gogdl
(21:01:02) INFO:    [Connection]:       Connectivity: check-online
(21:01:02) INFO:    [Connection]:       Pinging external endpoints
(21:01:02) INFO:    [Gog]:              Checking for existing gog manifests
(21:01:02) WARNING: [Backend]:          Failed to register protocol with OS.
(21:01:02) INFO:    [Legendary]:        Running command: LEGENDARY_CONFIG_PATH=/home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/legendaryConfig/legendary /app/bin/heroic/resources/app.asar.unpacked/build/bin/x64/linux/legendary --version
(21:01:02) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH=/home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/gogdlConfig /app/bin/heroic/resources/app.asar.unpacked/build/bin/x64/linux/gogdl --auth-config-path /home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json --version
(21:01:02) INFO:    [Nile]:             Running command: NILE_CONFIG_PATH=/home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/nile_config /app/bin/heroic/resources/app.asar.unpacked/build/bin/x64/linux/nile --version
(21:01:02) INFO:    [Connection]:       Connectivity: online
(21:01:02) INFO:    [Backend]:          User Not Found, removing it from Store
(21:01:02) INFO:    [Gog]:              Checking if login is valid
(21:01:02) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH=/home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/gogdlConfig /app/bin/heroic/resources/app.asar.unpacked/build/bin/x64/linux/gogdl --auth-config-path /home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth
(21:01:02) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH=/home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/gogdlConfig /app/bin/heroic/resources/app.asar.unpacked/build/bin/x64/linux/gogdl --auth-config-path /home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth
(21:01:02) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH=/home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/gogdlConfig /app/bin/heroic/resources/app.asar.unpacked/build/bin/x64/linux/gogdl --auth-config-path /home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth
(21:01:03) INFO:    [Backend]:          AreWeAntiCheatYet data downloaded
(21:01:03) INFO:    [Frontend]:         Refreshing undefined Library
(21:01:03) WARNING: [Backend]:          refresh not implemented on Sideload Library Manager
(21:01:03) INFO:    [Legendary]:        Refreshing library...
(21:01:03) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH=/home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/gogdlConfig /app/bin/heroic/resources/app.asar.unpacked/build/bin/x64/linux/gogdl --auth-config-path /home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth
(21:01:03) INFO:    [Backend]:          Frontend Ready
(21:01:03) INFO:    [Backend]:          
System Information:
CPU: 8x AMD Custom APU 0405
Memory: 15.53 GB (used: 4.54 GB)
GPUs:
  GPU 0:
    Name: Advanced Micro Devices, Inc. [AMD/ATI] VanGogh [AMD Custom GPU 0405]
    IDs: D=163f V=1002 SD=0123 SV=1002
    Driver: amdgpu
OS: SteamOS 3.6.20 holo (linux)

The current system is a Steam Deck (model: LCD) in desktop mode
We are running inside a Flatpak container

Software Versions:
  Heroic: 2.15.2 Emeth
  Legendary: 0.20.36 Urban Flight (Heroic)
  gogdl: 1.1.2
  comet: comet 0.1.2

  Nile: 1.1.2 Will A. Zeppeli

(21:01:03) INFO:    [Backend]:          Checking for current version changelog
(21:01:03) INFO:    [Gog]:              Getting GOG library
(21:01:03) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH=/home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/gogdlConfig /app/bin/heroic/resources/app.asar.unpacked/build/bin/x64/linux/gogdl --auth-config-path /home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth
(21:01:03) INFO:    [Gog]:              GOG presence set
(21:01:04) INFO:    [Gog]:              Saved username to config file
(21:01:04) INFO:    [Gog]:              Saved games data
(21:01:04) WARNING: [Backend]:          listUpdateableGames not implemented on Sideload Library Manager
(21:01:04) INFO:    [Gog]:              Running command: GOGDL_CONFIG_PATH=/home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/gogdlConfig /app/bin/heroic/resources/app.asar.unpacked/build/bin/x64/linux/gogdl --auth-config-path /home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/gog_store/auth.json auth
(21:01:05) INFO:    [Gog]:              Found 0 game(s) to update
(21:01:05) INFO:    [Winetricks]:       Downloading Winetricks
(21:01:07) INFO:    [WineDownloader]:   Updating wine versions info
(21:01:07) INFO:    [WineDownloader]:   Fetching upstream information...
(21:01:08) INFO:    [Backend]:          Starting the Download Queue
(21:01:08) INFO:    [WineDownloader]:   wine versions updated
```

### Steps to reproduce

1. Launch a game from the heroic games launcher on your steam deck
2. Notice controller inputs not working 

### Expected behavior

Pressing buttons on the steam deck should cause things to happen on the screen in game.

### Screenshots

https://github.com/user-attachments/assets/bdda62dc-42de-4c25-bdef-ff407195adae

### Heroic Version

Latest Stable (Flatpak)

### System Information

Steam Deck LCD 256GB
Running the stock image, Stable channel 

### Additional information

This was not an issue yesterday but since then I updated my system.  Also likely effects all games, I tried Control and Dead Cells.

**Comment by Valox26** [comment]
same things happen to me, i update the heroic launcher an every games that usually start added to steam,stop recognizing controller. Tried on startup and on desktop mode, They just works directly from Heroic.

**Comment by trinukso** [comment]
Confirm this bug. The same thing happens to me.

**Comment by antonlinux123** [comment]
I was wrong it is not an issue in desktop mode exept for the game Control for some reason.

**Comment by antonlinux123** [comment]
I found a temperary solution, you have to downgrade the flatpak with the following 

sudo flatpak update --commit=1e19d3aaabef44c15e87f09a1a720e592d0bd2e841e498ce6e9e7fb2d0126823 com.heroicgameslauncher.hgl

**Comment by GOBsNotOnBoard** [comment]
> I found a temperary solution, you have to downgrade the flatpak with the following
> 
> sudo flatpak update --commit=1e19d3aaabef44c15e87f09a1a720e592d0bd2e841e498ce6e9e7fb2d0126823 com.heroicgameslauncher.hgl

This fixed the bug for me. Thank you!

**Comment by Saigaiii** [comment]
Damn just when I was gonna play some dishonored and now my steam deck controls don’t work😭😭

**Comment by Valox26** [comment]
> I found a temperary solution, you have to downgrade the flatpak with the following
> 
> sudo flatpak update --commit=1e19d3aaabef44c15e87f09a1a720e592d0bd2e841e498ce6e9e7fb2d0126823 com.heroicgameslauncher.hgl

Works for me, never love to downgrade but it's ok and works.

**Comment by Valox26** [comment]
> Damn just when I was gonna play some dishonored and now my steam deck controls don’t work😭😭

If you start the deck in desktop mode and launch from heroic it works, eventually you can do the downgrade solution in this thread. 
I find that games from heroic launcher not passing through steam have some calibration problem for the two sticks but they works.

**Comment by victorjoia** [comment]
> I found a temperary solution, you have to downgrade the flatpak with the following
> 
> sudo flatpak update --commit=1e19d3aaabef44c15e87f09a1a720e592d0bd2e841e498ce6e9e7fb2d0126823 com.heroicgameslauncher.hgl

works for me! Thanks

**Comment by arielj** [comment]
the flatpak runtime update was reverted, a new heroic update should show up soon in the steam deck, can you confirm if that solves the problem?

**Comment by Valox26** [comment]
> the flatpak runtime update was reverted, a new heroic update should show up soon in the steam deck, can you confirm if that solves the problem?

Thank you, 
in any case do you think it is better for future to install game with Proton-GE instead of default Wine-GE?

**Comment by arielj** [comment]
wine-ge stopped getting updates, so new wine updates only get to proton-ge

the idea is that it should be used along with UMU (but there are still some issues with it)

so I'd recommend:
- try proton-ge+UMU first, if everything works, good
- then try proton-ge
- if none of those work try wine-ge

Just to be clear, the games are installed independently of the wine/proton selected, that only affects the prefix creation and not the game installation, so if you want to change wine/proton versions you don't need to reinstall, just delete the prefix (backup saves if any)

**Comment by arielj** [comment]
closing the issue as it was resolved by the flatpak runtime downgrade
