### ISSUE TITLE
Discord RPC support when using Heroic Flatpak + Discord Native

### ISSUE THREAD

**Issue by Arcitec** [Heroic-Games-Launcher/HeroicGamesLauncher#4115]
### Describe the bug

I have been investigating why Heroic's "Discord Rich Presence" doesn't work when you have a native Discord + a flatpak Heroic.

The issue is that the typescript library which wraps the `discord-rpc` library automatically picks IPC sockets as the transport stream instead of websocket here:

https://github.com/devsamuelv/discord-rich-presence/blob/master/index.js

This means that it always looks at `/run/user/1000/discord-ipc-0` inside the Flatpak environment. It does not attempt to connect to the Discord RPC websocket port (which is open on localhost port 6463 [as seen here](https://github.com/discordjs/RPC/blob/9e7de2a6d917591f10a66389e62e1dc053c04fec/src/transports/websocket.js#L21)).

Because we are limited to the socket-file based method of connecting to Discord RPC, we run into issues with needing to give the Flatpak access to the host's native `/run/user/1000/discord-ipc-0` file.

Adding permission to `--filesystem=xdg-run/discord-ipc-0` is **extremely unreliable** and requires the following steps:

- Give all Flatpaks permission to the Discord IPC socket file: `flatpak override --user --filesystem=xdg-run/discord-ipc-0`
- Alternatively, just give Heroic access: `flatpak override --user --filesystem=xdg-run/discord-ipc-0 com.heroicgameslauncher.hgl`
- Now we must fix a problem inside Heroic:
- `flatpak run --command=bash com.heroicgameslauncher.hgl`
- On the Bash prompt inside the Heroic Flatpak, run the following command to delete the Symlink that Heroic creates on startup:
- `rm -fv /run/user/1000/discord-ipc-0`
- Type `exit` to close the Flatpak session so that the `xdg-run/discord-ipc-0` permission you gave it can take effect.
- Run the native Discord or arRPC-based app (such as Vesktop), to create the `xdg-run/discord-ipc-0` socket.
- Run Heroic after that. Now Discord RPC works.
- The socket file inside Heroic Flatpak's `xdg-run/discord-ipc-0` path will remain as a socket-file until the last instance of Heroic is closed (that includes any command-line `flatpak run` bash connection).
- If the `xdg-run/discord-ipc-0` socket vanishes on the HOST (which happens if you close Discord/Vesktop/arRPC), then it becomes a 0-byte normal file inside the Heroic Flatpak.
- If you start Discord/Vesktop/arRPC again, and then start the Heroic Flatpak, the file will be mapped as a socket-file again.
- If you EVER start Heroic when Discord/Vesktop/arRPC isn't running, meaning that the `xdg-run/discord-ipc-0` is seen as a normal 0-byte file, then the [heroic-run script](https://github.com/flathub/com.heroicgameslauncher.hgl/blob/master/com.heroicgameslauncher.hgl.yml#L200) will do a `test -S`, see that it's not a socket, and replace it with a symlink to `/run/user/1000/discord-ipc-0 -> /run/user/1000/app/com.discordapp.Discord/discord-ipc-0` on startup.
- In other words, you can NEVER start Heroic when Discord/Vesktop/arRPC isn't running, because the Heroic startup script will rewrite the IPC file into a symlink, which in turn prevents Flatpak from mapping the real host socket into Heroic.
- Note: The `test -S` recommendation is a bit misguided, leads to always overwriting the targets and creating new symlinks on every startup anyway. This [bad code](https://github.com/flathub/com.discordapp.Discord/wiki/Rich-Precense-(discord-rpc)) comes from the Discord Flatpak wiki and is widely in use by various Flatpaks.

What can be done? I can see a few solutions and non-solutions:

### 1. Rewrite Heroic's startup script to leave the discord IPC files alone.

- Even if Heroic's startup scripts were improved to always leave the file alone too (for example by changing `test -S` to `test -e` to ensure that it leaves all sockets/files alone too)...
- ...the other issue remains, which is that Discord/Vesktop/arRPC must always be started BEFORE starting Heroic, otherwise Flatpak will not map the host-socket-file into the Heroic Flatpak, because the file doesn't exist during Heroic startup, so it gets mapped as a normal 0-byte file and will NOT change into a socket when Discord is started on the host.
- That is a downside of mapping files instead of directories. Mapped files must exist on the host when Flatpaks are started, as they will not be mapped if they appear later after the Flatpak is already running.
- Therefore, I am not a fan of mapping host-files directly.
- It would also interfere with Heroic's ability to map to the Discord Flatpak's RPC, because if we add `--filesystem=xdg-run/discord-ipc-0` as a Heroic permission by default, then that file would always exist as either a 0-byte file or a socket file (if mapped), which means the "improved" startup script would NEVER symlink it to the Discord Flatpak. So that would just break something else instead!
- However, we *could* still change the startup scripts to use `test -e` but NOT add `--filesystem=xdg-run/discord-ipc-0` by default. Then Heroic would still auto-create the Discord Flatpak RPC links on every startup. The users could then CHOOSE to delete the symlink themselves and add the permission, which would create a permanent link to the host's Discord. Then, the only remaining downside is that Discord/Vesktop/arRPC MUST be started BEFORE Heroic to establish a link.

### 2. Use Websocket RPC

- We could switch the Discord RPC library to something better. Heroic currently uses a lazy wrapper around the `discord-rpc` library, which always auto-selects "IPC" mode.
- If we [clone the wrapper's code](https://github.com/devsamuelv/discord-rich-presence/) (which has not been changed in 4+ years), we could add a parameter to specify the transport mode.
- Then we could change the way Heroic connects, to try Websocket first and then fall back to IPC if all the Websocket ports are closed.
- Upsides: It would work with all Discord apps and variants and require no filesystem permissions. It would never have any problems with socket-files disappearing during runtime, meaning we can open and close Discord as much as we want while Heroic is open.
- Downsides: Maybe it's slow to attempt to connect to and fail to connect to localhost port connections, maybe? Has to be tried.

### 3. Standardize Linux around a special path for Discord RPC

- We could modify arRPC/Vesktop to place the socket in a subdirectory of `xdg-run`, such as `xdg-run/app/com.discordapp.Discord` which is already in use by the Discord Flatpak.
- Then we can map that directory into the Flatpak, which means that files are able to come and go (appear/disappear) during runtime, which means there's no more need to start Discord before Heroic.
- Upsides: It's the Discord Flatpak solution, so we already know that it works, and many Flatpaks are already written to get permissions to this host-path.
- Downsides: Requires upstream changes in the official native Discord app, the Vesktop app, and the arRPC library. Those apps would also need to be changed to still export the legacy location for backwards compatibility, meaning they'd have to also create `xdg-run/discord-ipc-0 -> xdg-run/app/com.discordapp.Discord/discord-ipc-0` symlinks for every socket file.
- Other Issues: All apps would write to the same socket file locations which was reserved by the Discord Flatpak. But in practice, this is no problem, because the same issue already exists with `xdg-run/discord-ipc-0` being a single, clashing location anyway. The bigger issue is really that I doubt we'd ever get Discord to respond to such a change, since they don't care about Linux and have no active developers. So if such a change happens, I think it'd happen only in Vesktop and arRPC.

### 4. Figure out another way of linking to the host's IPC sockets

- I may have missed some idea. Perhaps there is some way we can non-invasively create `xdg-run/app/com.discordapp.Discord/discord-ipc-0` on the host and link to the `xdg-run/discord-ipc-0` path, so that Flatpaks can continue mapping the `xdg-run/app/com.discordapp.Discord` without needing any changes in the native Discord/Vesktop/arRPC.
- But I can't think of any way to do that, because we'd just map a folder of symlinks, and would not have permission to access the real socket files that are the targets of the links. Furthermore, it would just lead to a cyclic link inside the Flatpak, where `xdg-run/discord-ipc-0 -> xdg-run/app/com.discordapp.Discord/discord-ipc-0` and `xdg-run/app/com.discordapp.Discord/discord-ipc-0 -> xdg-run/discord-ipc-0`.
- So I really can't think of any way to give the Flatpak nice access to the host's true socket location.
- And no, we cannot give permission to `--filesystem=xdg-run`, because Flatpaks are not allowed to map the entire host's xdg runtime directory. Would just give us `error: Unknown filesystem location xdg-run, valid locations are: host, host-os, host-etc, home, xdg-*[/…], ~/dir, /dir`.

### 5. Socat on the host

- Just as I was finishing this up, I discovered that the Discord Flatpak literally uses `socat` to create two sockets and stream data via a link between Discord's own socket and its own custom `/app/` socket, seen [here](https://github.com/flathub/com.discordapp.Discord/blob/master/discord.sh).
- It may be possible to write a small script on the host which bridges `xdg-run/app/com.discordapp.Discord/discord-ipc-0` to `xdg-run/discord-ipc-0` via the exact same technique. Then the Flatpaks such as Heroic should work automatically, as they'll believe they are connecting to the Discord Flatpak RPC location.
- When apps such as Discord, Vesktop and arRPC run natively, they'd be connecting themselves as listeners to the `xdg-run/discord-ipc-0` socket, which would already exist and be in communication with `xdg-run/app/com.discordapp.Discord/discord-ipc-0`.
- So unless there's a problem with "file already exists, I'll create discord-ipc-1 instead" in the code of Discord/arRPC, then this should work...
- It may even be possible to write it as a systemd user-service which bridges those two socket locations automatically, maybe even natively without needing socat, since I know that systemd has a lot of socket-related features, maybe even a bridge feature.

### Most appealing solutions

- Forking the RPC library and adding websocket support. This would require zero upstream changes anywhere, and zero user-scripts (no socat etc).
- Modifying arRPC to use the `xdg-run/app/com.discordapp.Discord/discord-ipc-0` as its true path on the host, and placing symlinks in `xdg-run/discord-ipc-0`. This would fix all third-party Discord clients that use arRPC (which all good ones do). Kind of a nice solution, but may be hard to get arRPC to accept it in case he wants to act exactly like upstream Discord.
- Writing a systemd user-service which bridges the sockets, so that native apps can place the required socket in the "Discord Flatpak RPC location".

### Heroic Version

Latest Stable (Flatpak)

### System Information

- OS: Fedora Workstation 40

**Comment by Arcitec** [comment]
Since I discovered the `socket <----> socket` link method now, I am tempted to start investigating how to do that on the host and whether it will work (it won't work if it causes arRPC to think the socket is already in-use due to the file existing and then pick a different socket number).

But if it works, we could end up with a small systemd unit that users can enable to get working links between native Discord/Vesktop/arRPC and Flatpak apps such as Heroic.

**Comment by Arcitec** [comment]
Alright, early tests were a success. I use `socat` right now but would prefer to use [systemd-socket-proxyd](https://www.freedesktop.org/software/systemd/man/latest/systemd-socket-proxyd.html).

I will be working on this when I have time, so no estimates.

**Comment by Arcitec** [comment]
After an afternoon of hard work and testing, it's ready. People can now use Heroic and other Flatpak apps with native Discord clients.

# [discord-flatpak-rpc-bridge](https://github.com/Arcitec/discord-flatpak-rpc-bridge)

The **Heroic wiki** has also been updated:

### https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/wiki/How-To:-Discord-Rich-Presence-RPC-Support

Closing ticket. Enjoy! :)

**Comment by yodus67edus98** [comment]
flatpak override --user --filesystem=xdg-run/app/com.discordapp.Discord:create --filesystem=xdg-run/discord-ipc-0 --device=all org.vinegarhq.Sober
