### ISSUE TITLE
Can't start Heroic, because wrong python version is detected

### ISSUE THREAD

**Issue by JoeJoeTV** [Heroic-Games-Launcher/HeroicGamesLauncher#414]
**Describe the bug**
Heroic won't start, because python 3.8 is supposedly not installed, even though python 3.8 and 3.9 are installed.

**To Reproduce**
1. Install Heroic 1.8.0
2. Try to start it

**Expected behavior**
Heroic shoud start normally and detect python version correctly

**Desktop (please complete the following information):**

- OS: Linux Mint Cinnamon 20.1
- Version: 1.8.0
- Game: /
- Wine/Proton version: /
- Hardware specs (RAM, CPU, GPU):
  - AMD Ryzen 1600
  - 16GB RAM
  - NVIDIA GTX 1060 6G

**Additional context**
Python 3.8.5 is installed already and I tried installing Python 3.9 as well, which did nothing.

This is the output when started in terminal:
```Failed to register protocol with OS.
Python Version incompatible. Python needed: >= 3.8, Python found: null
No credentials. Missing Login?
Error occurred in handler for 'checkGameUpdates': Error: Command failed: /opt/Heroic Games Launcher/resources/app.asar.unpacked/build/bin/linux/legendary list-installed --check-updates --tsv
/bin/sh: 1: /opt/Heroic: not found

    at ChildProcess.exithandler (child_process.js:317:12)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1048:16)
    at Socket.<anonymous> (internal/child_process.js:439:11)
    at Socket.emit (events.js:315:20)
    at Pipe.<anonymous> (net.js:673:12) {
  killed: false,
  code: 127,
  signal: null,
  cmd: '/opt/Heroic Games Launcher/resources/app.asar.unpacked/build/bin/linux/legendary list-installed --check-updates --tsv',
  stdout: '',
  stderr: '/bin/sh: 1: /opt/Heroic: not found\n'
}
```

**Comment by flavioislima** [comment]
Yeah, this is another issue. For some reason the game of the folder have spaces in it and heroic won't start, probably no Linux version will.
But can you try appimage?

**Comment by JoeJoeTV** [comment]
For clarity, I used the .deb file to install it first.

The AppImage also will not start because it detects `null` as the python version.

**Comment by JoeJoeTV** [comment]
But it will then load the library and does not show the error related to the directory.

**Comment by flavioislima** [comment]
I discovered the issue, I'll update the packages on the release page soon.

Thanks for opening the issue!

**Comment by JoeJoeTV** [comment]
Yeah, now the deb version also shows the library and doesn't throw the directory related error, but the python version check is still wrong.
Thank you for responding so fast!

**Comment by flavioislima** [comment]
> Yeah, now the deb version also shows the library and doesn't throw the directory related error, but the python version check is still wrong.
> Thank you for responding so fast!

so it still complain about python version?
maybe run `python --version` on terminal.
Might be that your default python is version 2.

**Comment by flavioislima** [comment]
it might be null because this command `python --version` returns nothing. but I'll change it to check for `python3 --version` in the future.
Just tested here and in my case it returns 3.9.

**Comment by JoeJoeTV** [comment]
The command `python --version` does return the Python 2 version (`Python 2.7.18`)

**Comment by flavioislima** [comment]
updated the packages again this time checking python3. can you try it?

**Comment by Nocccer** [comment]
Maybe we try several calls ?
`python --version`
`python3 --version`

**Comment by JoeJoeTV** [comment]
> updated the packages again this time checking python3. can you try it?

Yeah it works now!

> Maybe we try several calls ?
> `python --version`
> `python3 --version`

That would have also been my suggestion.

**Comment by flavioislima** [comment]
> Maybe we try several calls ?
> `python --version`
> `python3 --version`

I think python3 should be enough. I thought that python 2 was EOL and no distro would use it as default.
Well, one more lesson learned :P



> > updated the packages again this time checking python3. can you try it?
> 
> Yeah it works now!
> 
> > Maybe we try several calls ?
> > `python --version`
> > `python3 --version`
> 
> That would have also been my suggestion.

Nice, thanks for trying!

**Comment by JoeJoeTV** [comment]
I'll close the issue now, since this problem has been resolved
