### ISSUE TITLE
Apply protonfixes to all proton types

### ISSUE THREAD

**Issue by LucasSnatiago** [Heroic-Games-Launcher/HeroicGamesLauncher#4140]
### Problem description

I tried to open Thief game yesterday and it gave me some errors:  [Thief crashing on startup after 5 seconds of black screen](https://github.com/HansKristian-Work/vkd3d-proton/issues/2224). I opened an issue on VKD3D thinking that was a problem on their implementation of the d3dcompiler, but actually it was just missing one dependency.

### Feature description

I would like to ask if it is possible to auto download and install all necessary dependencies automatically for all proton or wine versions (ex.: proton-ge, wine-ge, wine and steam proton). Heroic has already a repo containing [Know-Fixes](https://github.com/Heroic-Games-Launcher/known-fixes) and it is just a matter of installing [this fix](https://github.com/Heroic-Games-Launcher/known-fixes/blob/main/epic/4123bcce398b4b1d8b9ef878f81055d1-epic.json) even when not using wine-ge and it should fix this game for everyone. Applying the winetricks that is already available would help everyone that does not know how to install dependencies on heroic games launcher.

### Additional information

I saw more people lost on how to solve this issue on [protondb](https://www.protondb.com/app/239160) as well. The two most recent comments for example:
![image](https://github.com/user-attachments/assets/069d20b4-c847-4a42-a51c-f136e19a67ad)

**Comment by imLinguin** [comment]
Hi, just make sure you have this option checked on 
![obraz](https://github.com/user-attachments/assets/b8d2ab74-4b7b-4126-a0c8-5ce535f38c66)

It should work with that. A game reinstall or deletion of the prefix may be needed

**Comment by arielj** [comment]
I think UMU still breaks the winetricks commands, right?

**Comment by imLinguin** [comment]
hmm.. I'm able to run winetricks just fine from the settings tab

**Comment by LucasSnatiago** [comment]
@imLinguin interesting, that button is actually already pressed and it is still not working. I ran the winetricks manually and then it worked on proton bleeding edge.

**Comment by LucasSnatiago** [comment]
I tried again reinstalling the game and the problem disappeared. I downloaded the game twice and it worked flawlessly. I have no idea what have happened to this game the first two times I downloaded it and I couldn't get it to work. I think this is an issue on my end hahaha. Thanks for all the help anyways!
