### ISSUE TITLE
Protocol handler not working

### ISSUE THREAD

**Issue by JoeJoeTV** [Heroic-Games-Launcher/HeroicGamesLauncher#415]
**Describe the bug**
The protocol handler added in 1.8.0 seems to not be working, because when I try to launch a geme in heroic using e.g. `heroic://launch/Subnautica`, it throws following error in the log output:
```(node:162912) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'split' of undefined
    at Object.<anonymous> (/opt/Heroic/resources/app.asar/build/protocol.js:22:21)
    at Generator.next (<anonymous>)
    at /opt/Heroic/resources/app.asar/build/protocol.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/opt/Heroic/resources/app.asar/build/protocol.js:4:12)
    at Object.handleProtocol (/opt/Heroic/resources/app.asar/build/protocol.js:15:12)
    at App.<anonymous> (/opt/Heroic/resources/app.asar/build/main.js:163:24)
    at App.emit (events.js:315:20)
(node:162912) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4)
```

When using `heroic://launch?appName=Subnautica`, following exception is thrown in the log output:
```ProtocolHandler: received 'heroic://launch?appName=Subanutica'
(node:162912) UnhandledPromiseRejectionWarning: TypeError: Cannot destructure property 'is_installed' of '(intermediate value)' as it is null.
    at Object.<anonymous> (/opt/Heroic/resources/app.asar/build/protocol.js:33:21)
    at Generator.next (<anonymous>)
    at fulfilled (/opt/Heroic/resources/app.asar/build/protocol.js:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:162912) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 5)
```

**To Reproduce**
1. Lauch a game in heroic using the `heroic://` protocol handler
2. See excaption in console

**Expected behavior**
The game should be launched in heroic and no error should be thrown

**Desktop (please complete the following information):**

- OS: Linux Mint Cinnamon 20.1
- Version: 1.8.0(Heroic)
- Game: e.g. Subnautica
- Wine/Proton version: /
- Hardware specs (RAM, CPU, GPU):
  - CPU: AMD Ryzen 1600
  - RAM: 16GB
  - GPU: NVIDIA GeForce GTX 1060 6G

**Additional context**
After looking into the code, i founf, that there is a `ping` command, so I tried that (`heroic://ping`), but I threw the first error again, which seems like a problem with splitting the ?-parameters from the url string, if I'm correct.
Following this, I tried it with `heroic://ping?test=test`, and that worked:
```ProtocolHandler: received 'heroic://ping?test=test'
Received ping! Map(1) { 'test' => 'test' }
```

**Comment by flavioislima** [comment]
I'll remove that part from the release note

**Comment by JoeJoeTV** [comment]
Ah, ok, I tried the first one (`heroic://launch/{appName}`) with the app_Name from the library.json, but forgot to test that with the second one, thanks!

**Comment by adityaruplaha** [comment]
Yeah protocol handler is still very unstable, wouldn't recommend using it.
