### ISSUE TITLE
Can't run Marvel Rivals

### ISSUE THREAD

**Issue by Mr-Blondie** [Heroic-Games-Launcher/HeroicGamesLauncher#4172]
### Describe the bug

Can't run MarvelRivals_Launcher.exe. I think it need to run as admin

### Add logs

```text
Start-Process : This command cannot be run due to the error: Istenen islem i�in y�kseltme gerekiyor.
At line:1 char:1
+ Start-Process "`"C:\Games\Steam\steamapps\common\MarvelRivals\MarvelR ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
============= End of log =============    + CategoryInfo          : InvalidOperation: (:) [Start-Process], InvalidOperationException
    + FullyQualifiedErrorId : InvalidOperationException,Microsoft.PowerShell.Commands.StartProcessCommand
```

### Steps to reproduce

1. add MarvelRivals_Launcher.exe in launcer
2. click and run
3. nothing happened

### Expected behavior

game should be run

### Heroic Version

Latest Stable

### System Information

windows 11

**Comment by arielj** [comment]
Github issues are for issues with heroic itself, for help with games use the `#-support` section of our discord.
