### ISSUE TITLE
Nosferatu: Wrath of Malachi from GOG is choosing the wrong .exe to run

### ISSUE THREAD

**Issue by Relbron** [Heroic-Games-Launcher/HeroicGamesLauncher#4183]
### Describe the bug

After you install the game Nosferatu: Wrath of Malachi on Heroic or on Lutris it (for some bizarre reason) defaults to a .exe named Nosshell.exe instead of Nosferatu.exe not allowing you to properly play the game out of the box.

### Add logs

```text
Launching "Nosferatu: Wrath of Malachi" (gog)

Native? No

Installed in: /media/sebastian/Games/Nosferatu - Wrath of Malachi

System Info:

CPU: 12x AMD Ryzen 5 4500 6-Core Processor

Memory: 16.54 GB (used: 4.92 GB)

GPUs:

  GPU 0:

    Name: NVIDIA Corporation TU116 [GeForce GTX 1660]

    IDs: D=2184 V=10de SD=1067 SV=3842

    Driver: nvidia

OS: Linux Mint 22 (Wilma) (linux)

The current system is not a Steam Deck

We are running inside a Flatpak container

Software Versions:

  Heroic: 2.15.2 Emeth

  Legendary: 0.20.36 Urban Flight (Heroic)

  gogdl: 1.1.2

  comet: comet 0.1.2

  Nile: 1.1.2 Will A. Zeppeli

Game Settings: {

    "autoInstallDxvk": true,

    "autoInstallDxvkNvapi": false,

    "autoInstallVkd3d": true,

    "preferSystemLibs": false,

    "enableEsync": true,

    "enableMsync": false,

    "enableFsync": true,

    "nvidiaPrime": false,

    "enviromentOptions": [],

    "wrapperOptions": [],

    "showFps": false,

    "useGameMode": true,

    "battlEyeRuntime": true,

    "eacRuntime": true,

    "language": "",

    "beforeLaunchScriptPath": "",

    "afterLaunchScriptPath": "",

    "wineVersion": {

        "bin": "/home/sebastian/.steam/debian-installation/steamapps/common/Proton 5.0/proton",

        "name": "Proton - Proton 5.0",

        "type": "proton"

    },

    "winePrefix": "/home/sebastian/Games/Heroic/Prefixes/default/Nosferatu Wrath of Malachi",

    "wineCrossoverBottle": ""

}

Game launched at: Sat Dec 14 2024 12:51:54 GMT-0500 (Colombia Standard Time)

Winetricks packages: 

Launch Command: HEROIC_APP_NAME=1207666093 HEROIC_APP_RUNNER=gog GAMEID=umu-0 HEROIC_APP_SOURCE=gog STORE=gog STEAM_COMPAT_INSTALL_PATH="/media/sebastian/Games/Nosferatu - Wrath of Malachi" LD_PRELOAD= STEAM_COMPAT_CLIENT_INSTALL_PATH=/home/sebastian/.var/app/com.heroicgameslauncher.hgl/.steam/steam WINEPREFIX="/home/sebastian/Games/Heroic/Prefixes/default/Nosferatu Wrath of Malachi" STEAM_COMPAT_DATA_PATH="/home/sebastian/Games/Heroic/Prefixes/default/Nosferatu Wrath of Malachi" PROTONPATH="/home/sebastian/.steam/debian-installation/steamapps/common/Proton 5.0" WINE_FULLSCREEN_FSR=0 PROTON_DISABLE_NVAPI=1 PROTON_EAC_RUNTIME=/home/sebastian/.var/app/com.heroicgameslauncher.hgl/config/heroic/tools/runtimes/eac_runtime PROTON_BATTLEYE_RUNTIME=/home/sebastian/.var/app/com.heroicgameslauncher.hgl/config/heroic/tools/runtimes/battleye_runtime STEAM_COMPAT_APP_ID=0 SteamAppId=0 SteamGameId="heroic-Nosferatu - Wrath of Malachi" PROTON_LOG_DIR=/home/sebastian/.var/app/com.heroicgameslauncher.hgl /app/bin/heroic/resources/app.asar.unpacked/build/bin/x64/linux/gogdl launch "/media/sebastian/Games/Nosferatu - Wrath of Malachi" 1207666093 --no-wine --wrapper "/app/bin/gamemoderun "/home/sebastian/.steam/debian-installation/steamapps/common/Proton 5.0/proton" waitforexitandrun" --platform windows

Game Log:

gamemodeauto: 

gamemodeauto: 

gamemodeauto: 

esync: up and running.

[S_API] SteamAPI_Init(): SteamAPI_IsSteamRunning() did not locate a running instance of Steam.

[S_API FAIL] SteamAPI_Init() failed

gamemodeauto: 

Launch command: ['/app/bin/gamemoderun', '/home/sebastian/.steam/debian-installation/steamapps/common/Proton 5.0/proton', 'waitforexitandrun', '/media/sebastian/Games/Nosferatu - Wrath of Malachi/nosshell.exe']

All processes exited

============= End of log =============
```

### Steps to reproduce

1. Go to 'Heroic Games Launcher'
2. Click on 'Nosferatu: Wrath of Malachi'
3. Run the game with any compatibility layer
4. See the message of "Playing" and then nothing happens.

### Expected behavior

Click the play button and the game should open right away.

### Screenshots

![image](https://github.com/user-attachments/assets/1fadf6a7-bb8d-4b68-936b-47d38e44ca4f)
![image](https://github.com/user-attachments/assets/9b062d9d-8f74-4a2b-8d76-4d6513096981)

### Heroic Version

Latest Stable

### System Information

System:
  Kernel: 6.8.0-50-generic arch: x86_64 bits: 64 compiler: gcc v: 13.3.0 clocksource: tsc
  Desktop: Cinnamon v: 6.2.9 tk: GTK v: 3.24.41 wm: Muffin v: 6.2.0 vt: 7 dm: LightDM v: 1.30.0
    Distro: Linux Mint 22 Wilma base: Ubuntu 24.04 noble
Machine:
  Type: Desktop Mobo: ASUSTeK model: PRIME A320M-K v: Rev X.0x serial: <superuser required>
    part-nu: SKU uuid: <superuser required> UEFI: American Megatrends v: 6042 date: 04/28/2022
CPU:
  Info: 6-core model: AMD Ryzen 5 4500 bits: 64 type: MT MCP smt: enabled arch: Zen 2 rev: 1 cache:
    L1: 384 KiB L2: 3 MiB L3: 8 MiB
  Speed (MHz): avg: 2662 high: 4198 min/max: 400/4208 cores: 1: 3603 2: 2800 3: 400 4: 2999
    5: 2953 6: 2965 7: 4001 8: 400 9: 3375 10: 4198 11: 400 12: 3850 bogomips: 86406
  Flags: avx avx2 ht lm nx pae sse sse2 sse3 sse4_1 sse4_2 sse4a ssse3
Graphics:
  Device-1: NVIDIA TU116 [GeForce GTX 1660] vendor: eVga.com. driver: nvidia v: 535.183.01
    arch: Turing pcie: speed: 5 GT/s lanes: 2 ports: active: none off: HDMI-A-1 empty: DP-1,DVI-D-1
    bus-ID: 01:00.0 chip-ID: 10de:2184 class-ID: 0300
  Display: x11 server: X.Org v: 21.1.11 with: Xwayland v: 23.2.6 driver: X: loaded: nouveau
    unloaded: fbdev,modesetting,vesa failed: nvidia gpu: nvidia,nvidia-nvswitch display-ID: :0
    screens: 1
  Screen-1: 0 s-res: 1920x1080 s-dpi: 101 s-size: 483x261mm (19.02x10.28") s-diag: 549mm (21.61")
  Monitor-1: HDMI-0 res: 1920x1080 hz: 75 dpi: 102 size: 480x260mm (18.9x10.24")
    diag: 546mm (21.49") modes: N/A
  API: EGL v: 1.5 hw: drv: nvidia platforms: device: 0 drv: nvidia device: 2 drv: swrast gbm:
    drv: kms_swrast surfaceless: drv: nvidia x11: drv: nvidia inactive: wayland,device-1
  API: OpenGL v: 4.6.0 compat-v: 4.5 vendor: nvidia mesa v: 535.183.01 glx-v: 1.4
    direct-render: yes renderer: NVIDIA GeForce GTX 1660/PCIe/SSE2
Audio:
  Device-1: NVIDIA TU116 High Definition Audio vendor: eVga.com. driver: snd_hda_intel v: kernel
    pcie: speed: 8 GT/s lanes: 2 bus-ID: 01:00.1 chip-ID: 10de:1aeb class-ID: 0403
  Device-2: AMD Renoir Radeon High Definition Audio vendor: ASUSTeK driver: snd_hda_intel
    v: kernel pcie: speed: 8 GT/s lanes: 16 bus-ID: 09:00.1 chip-ID: 1002:1637 class-ID: 0403
  Device-3: AMD Family 17h/19h HD Audio vendor: ASUSTeK PRIME B450M-A driver: snd_hda_intel
    v: kernel pcie: speed: 8 GT/s lanes: 16 bus-ID: 09:00.6 chip-ID: 1022:15e3 class-ID: 0403
  API: ALSA v: k6.8.0-50-generic status: kernel-api
  Server-1: PipeWire v: 1.0.5 status: active with: 1: pipewire-pulse status: active
    2: wireplumber status: active
  Server-2: PulseAudio v: 16.1 status: off (using pipewire-pulse)
Network:
  Device-1: Realtek RTL8111/8168/8211/8411 PCI Express Gigabit Ethernet vendor: ASUSTeK RTL8111H
    driver: r8169 v: kernel pcie: speed: 2.5 GT/s lanes: 1 port: e000 bus-ID: 06:00.0
    chip-ID: 10ec:8168 class-ID: 0200
  IF: enp6s0 state: up speed: 1000 Mbps duplex: full mac: <filter>
  Device-2: Ralink MT7601U Wireless Adapter driver: mt7601u type: USB rev: 2.0 speed: 480 Mb/s
    lanes: 1 bus-ID: 3-3:2 chip-ID: 148f:7601 class-ID: 0000 serial: <filter>
  IF: wlx000c430bad09 state: up mac: <filter>
Drives:
  Local Storage: total: 1.15 TiB used: 431.64 GiB (36.7%)
  ID-1: /dev/nvme0n1 vendor: TeamGroup model: TM8FP6512G size: 476.94 GiB speed: 31.6 Gb/s
    lanes: 4 tech: SSD serial: <filter> fw-rev: EDFME0.1 temp: 38.9 C scheme: GPT
  ID-2: /dev/sda vendor: TeamGroup model: T253512GB size: 476.94 GiB speed: 6.0 Gb/s tech: SSD
    serial: <filter> fw-rev: 61.5 scheme: GPT
  ID-3: /dev/sdb vendor: Patriot model: Burst Elite 240GB size: 223.57 GiB speed: 6.0 Gb/s
    tech: SSD serial: <filter> fw-rev: 3B0 scheme: GPT
Partition:
  ID-1: / size: 218.51 GiB used: 156.33 GiB (71.5%) fs: ext4 dev: /dev/sdb2
  ID-2: /boot/efi size: 96 MiB used: 31.4 MiB (32.7%) fs: vfat dev: /dev/sda1
Swap:
  ID-1: swap-1 type: file size: 2 GiB used: 0 KiB (0.0%) priority: -2 file: /swapfile
USB:
  Hub-1: 1-0:1 info: hi-speed hub with single TT ports: 2 rev: 2.0 speed: 480 Mb/s lanes: 1
    chip-ID: 1d6b:0002 class-ID: 0900
  Hub-2: 2-0:1 info: super-speed hub ports: 4 rev: 3.1 speed: 10 Gb/s lanes: 1 chip-ID: 1d6b:0003
    class-ID: 0900
  Hub-3: 3-0:1 info: hi-speed hub with single TT ports: 9 rev: 2.0 speed: 480 Mb/s lanes: 1
    chip-ID: 1d6b:0002 class-ID: 0900
  Device-1: 3-3:2 info: Ralink MT7601U Wireless Adapter type: Network driver: mt7601u
    interfaces: 1 rev: 2.0 speed: 480 Mb/s lanes: 1 power: 160mA chip-ID: 148f:7601 class-ID: 0000
    serial: <filter>
  Device-2: 3-6:3 info: Evision RGB Keyboard type: keyboard,mouse driver: hid-generic,usbhid
    interfaces: 2 rev: 2.0 speed: 12 Mb/s lanes: 1 power: 400mA chip-ID: 320f:505b class-ID: 0301
  Hub-4: 4-0:1 info: super-speed hub ports: 3 rev: 3.1 speed: 10 Gb/s lanes: 1 chip-ID: 1d6b:0003
    class-ID: 0900
  Hub-5: 5-0:1 info: hi-speed hub with single TT ports: 4 rev: 2.0 speed: 480 Mb/s lanes: 1
    chip-ID: 1d6b:0002 class-ID: 0900
  Hub-6: 6-0:1 info: super-speed hub ports: 2 rev: 3.1 speed: 10 Gb/s lanes: 1 chip-ID: 1d6b:0003
    class-ID: 0900
  Hub-7: 7-0:1 info: hi-speed hub with single TT ports: 4 rev: 2.0 speed: 480 Mb/s lanes: 1
    chip-ID: 1d6b:0002 class-ID: 0900
  Device-1: 7-1:2 info: Nordic ASA 1K NRF Receiver type: mouse,HID driver: hid-generic,usbhid
    interfaces: 4 rev: 2.0 speed: 12 Mb/s lanes: 1 power: 98mA chip-ID: 1915:0723 class-ID: 0300
  Hub-8: 8-0:1 info: super-speed hub ports: 2 rev: 3.1 speed: 10 Gb/s lanes: 1 chip-ID: 1d6b:0003
    class-ID: 0900
Sensors:
  System Temperatures: cpu: 47.0 C mobo: N/A gpu: nvidia temp: 40 C
  Fan Speeds (rpm): N/A gpu: nvidia fan: 0%
Repos:
  Packages: 2678 pm: dpkg pkgs: 2620 pm: flatpak pkgs: 58
  No active apt repos in: /etc/apt/sources.list
  Active apt repos in: /etc/apt/sources.list.d/official-package-repositories.list
    1: deb http: //packages.linuxmint.com wilma main upstream import backport
    2: deb http: //archive.ubuntu.com/ubuntu noble main restricted universe multiverse
    3: deb http: //archive.ubuntu.com/ubuntu noble-updates main restricted universe multiverse
    4: deb http: //archive.ubuntu.com/ubuntu noble-backports main restricted universe multiverse
    5: deb http: //security.ubuntu.com/ubuntu/ noble-security main restricted universe multiverse
Info:
  Memory: total: 16 GiB note: est. available: 15.41 GiB used: 4.38 GiB (28.4%)
  Processes: 399 Power: uptime: 32m states: freeze,mem,disk suspend: deep wakeups: 0
    hibernate: platform Init: systemd v: 255 target: graphical (5) default: graphical
  Compilers: gcc: 13.3.0 alt: 11/12 Client: Cinnamon v: 6.2.9 inxi: 3.3.34

**Comment by imLinguin** [comment]
Based on the log it looks like you are using a really old Proton 5.0. 
Based on the .info file you've shared on Discord it seems the `nosshell.exe` is the expected executable. If anything, its a wine issue.
