### ISSUE TITLE
Controller switching between Wireless or Wired(for charging a dead controller) not picked up properly

### ISSUE THREAD

**Issue by Shadow-Hunt3r** [Heroic-Games-Launcher/HeroicGamesLauncher#4201]
### Describe the bug

While playing God of War from GOG I have run into the issue where whenever a controller dies and I need to connect it to power, which I usually use a data USB cable from my desktop to charge, then Bluetooth connection gets terminated by the controller and the game doesn't realise this.

### Add logs

```text
Unsure if I should post Log content from Heroic Launcher, GOG or God of War
```

### Steps to reproduce

1. Play a game starting off with a controller connected, this can be wired connection or wireless
2. During the game disconnect or connect the appropriate data USB cable to charge the controller using the desktop/laptop you are playing on
3. Bug will occur not detecting the new controller and failing to switch to it even though the previous connection doesn't exist

### Expected behavior

Would expect client to accordingly detect that the controller has been switched from wired(USB) or wireless(Bluetooth) connection to the other

### Heroic Version

Latest Stable

### System Information

OS: Linux Mint 22
CPU: AMD Ryzen Threadripper 1950x
GPU: AMD Radeon RX 7800 XT
Memory: 64GB DDR4

**Comment by arielj** [comment]
This is out of the control of Heroic. We just tell wine/proton to launch the game and how the controllers work there is not managed by Heroic in any way.

It sounds like a wine/proton bug, we can't fix that from Heroic's side.
