### ISSUE TITLE
gamescope is always active

### ISSUE THREAD

**Issue by MrRulf** [Heroic-Games-Launcher/HeroicGamesLauncher#4207]
### Describe the bug

Gamescope is always active, even when it is not supposed to. I've got a 3:2 screen and there this leads to black bars because its not always handled in the best way. Seeing this behavior suggests that 32:9 or setups with different screen sizes could also have trouble with gamescope being ALWAYS active. 

### Add logs

```text
Launching "Stardew Valley" (gog)

Native? Yes

Installed in: /home/myuser/Games/Heroic/Stardew Valley

System Info:

CPU: 16x AMD Ryzen 7 7840U w/ Radeon  780M Graphics

Memory: 46.08 GB (used: 2.3 GB)

GPUs:

  GPU 0:

    Name: Advanced Micro Devices, Inc. [AMD/ATI] Phoenix1

    IDs: D=15bf V=1002 SD=0006 SV=f111

    Driver: amdgpu

OS: Arch Linux 6.12.6-arch1-1 (linux)

The current system is not a Steam Deck

We are not running inside a Flatpak container

Software Versions:

  Heroic: 2.15.2 Emeth

  Legendary: 0.20.36 Urban Flight (Heroic)

  gogdl: 1.1.2

  comet: comet 0.1.2

  Nile: 1.1.2 Will A. Zeppeli

Game Settings: {

	"autoInstallDxvk": true,

	"autoInstallDxvkNvapi": false,

	"autoInstallVkd3d": true,

	"preferSystemLibs": false,

	"enableEsync": true,

	"enableMsync": false,

	"enableFSR": false,

	"enableFsync": true,

	"nvidiaPrime": false,

	"enviromentOptions": [],

	"wrapperOptions": [],

	"showFps": false,

	"useGameMode": true,

	"useSteamRuntime": true,

	"battlEyeRuntime": true,

	"eacRuntime": true,

	"language": "",

	"beforeLaunchScriptPath": "",

	"afterLaunchScriptPath": "",

	"gamescope": {

		"enableUpscaling": false,

		"enableLimiter": false,

		"windowType": "fullscreen",

		"gameWidth": "2256",

		"gameHeight": "1504",

		"upscaleHeight": "1504",

		"upscaleWidth": "2256",

		"upscaleMethod": "fsr",

		"fpsLimiter": "60",

		"fpsLimiterNoFocus": "30",

		"additionalOptions": ""

	},

	"wineVersion": {

		"bin": "/home/myuser/.local/share/Steam/steamapps/common/Proton - Experimental/proton",

		"name": "Proton - Proton - Experimental",

		"type": "proton"

	},

	"winePrefix": "/home/myuser/Games/Heroic/Prefixes/default"

}

Game launched at: Thu Dec 26 2024 14:31:05 GMT+0100 (Central European Standard Time)

Launch Command: HEROIC_APP_NAME=1453375253 HEROIC_APP_RUNNER=gog GAMEID=umu-0 HEROIC_APP_SOURCE=gog STORE=gog STEAM_COMPAT_INSTALL_PATH="/home/myuser/Games/Heroic/Stardew Valley" LD_PRELOAD= /opt/Heroic/resources/app.asar.unpacked/build/bin/x64/linux/gogdl launch "/home/myuser/Games/Heroic/Stardew Valley" 1453375253 --wrapper "/usr/bin/gamemoderun /home/myuser/.local/share/Steam/ubuntu12_32/steam-runtime/run.sh" --platform linux

Game Log:

gamemodeauto: 

gamemodeauto: 

gamemodeauto: 

gamemodeauto: 

gamemodeauto: 

gamemodeauto: 

gamemodeauto: 

gamemodeauto: 

Running Stardew Valley

./StardewValley: line 7: sw_vers: command not found

gamemodeauto: 

./StardewValley: line 27:  8869 Killed                  ./"Stardew Valley" $@

Launch command: ['/usr/bin/gamemoderun', '/home/myuser/.local/share/Steam/ubuntu12_32/steam-runtime/run.sh', '/home/myuser/Games/Heroic/Stardew Valley/start.sh']

All processes exited

============= End of log =============
```

### Steps to reproduce

1. Take a 3:2 monitor
2. Open a game set to 16:9 on it
3. Stretched picture/black bars...

### Expected behavior

Gamescope should only be active when it is set to be active, similar to gamemode

### Heroic Version

Latest Stable

### System Information

- OS: Arch 6.12.6 linux
- Ryzen 7840U w 780m

**Comment by arielj** [comment]
if you check the log of a game, is heroic setting the `gamescope` wrapper in the `Launch Command` line?

because if it's not in the launch command then it's not heroic doing that

can you share one game log here?

**Comment by MrRulf** [comment]
I've added logs, I still see gamescope in there, however when I launched the title today it actually was in my screen resolution, there were no black bars and the games resolution seemed to adapt to other resolutions when it wasn't in fullscreen mode (tiling window manager with the game only on half the screen)
I did not really change anything from yesterday to today, maybe the reboot after I tried to change the resolution for gamescope yesterday did something. 
If i got other settings I shouldn't have set please tell me, didn't want to provoke a bug that isn't there

**Comment by arielj** [comment]
It looks like your system had some hiccup and it kept applying gamescope as a wrapper, because I see the gamescope settings are disabled and it's not passed as a wrapper in the `Launch Command` line, it was not Heroic doing that.

If it's fixed after a restart I don't think it's a Heroic issue.

**Comment by MrRulf** [comment]
Never had an issue with gamescope before, I only used it trough steam, but I also wasn't able to replicate the bug, so I'm gonna close the issue now. 
Thanks for the help anyway ^^
