### ISSUE TITLE
I would like to be able to launch games in 32 bit wine

### ISSUE THREAD

**Issue by F3arM3** [Heroic-Games-Launcher/HeroicGamesLauncher#4215]
### Problem description

Games like Classic Rebirth for resident evil 1&3 refuse to launch outside of 32 bit wine so I have to use lutris.

### Feature description

Just as it says in the title, the ability to select a 32 bit wine ex: wine-ge-8-26-x86_64

**Comment by arielj** [comment]
There is a setting to add custom paths for wines you want for heroic to show it in the wine selector:
![image](https://github.com/user-attachments/assets/deb220f5-73be-41c0-ae75-070d47d6c978)

**Comment by GloriousEggroll** [comment]
what is the purpose?
64 bit wine is able to run 32 bit applications. there is no need for 32 bit wine or 32 bit prefixes.

**Comment by GloriousEggroll** [comment]
Ive just verified the gog copy of the game runs fine without rebirth. It's a problem with the rebirth ddraw.dll

**Comment by GloriousEggroll** [comment]
I went back through all the steps to verify everything was setup correctly. It works fine with proton/umu. Does not need wine32.

Works with GOG version without needing japanese version if you use it alongside the unofficial nexusmod 1.01 patch:

https://www.nexusmods.com/residentevil1996/mods/25?tab=files&file_id=61
