### ISSUE TITLE
Ability to scan folders for previous instalations

### ISSUE THREAD

**Issue by F3arM3** [Heroic-Games-Launcher/HeroicGamesLauncher#4217]
### Problem description

I just switched from the flatpak to the appimage and even after setting the same install folder heroic doesn't recognize that my games have been installed

### Feature description

maybe some kind of already installed option so I can restore the directory

**Comment by F3arM3** [comment]
Oh, wait, there is an input option when downloading, that should probably be visible with a right click or something like that

**Comment by arielj** [comment]
> Oh, wait, there is an import option when downloading, that should probably be visible with a right click or something like that

yes, for the record, there's an issue about this not being easily visible https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/issues/1116
