### ISSUE TITLE
Add a logger

### ISSUE THREAD

**Issue by dragonDScript** [Heroic-Games-Launcher/HeroicGamesLauncher#422]
**Is your feature request related to a problem? Please describe.**
When a bug occurs, usually we have to re-start Heroic in the terminal. If we added a logger and then saved the logs in a file, e.g. %appdata%/heroic/logs/2020-02-02-23:00.txt or .config/heroic/... it'd be much easier to report bugs.

**Describe the solution you'd like**
In the main process, listen for changes in stdout and save them in an array. Then, when the program is exiting, array.join("\n") and save it to a file with the local time.

It is important to log everything important, e.g. config changed, started game X, ... and the time that it occurs.

(I'm free to work on this tomorrow or so, so I will submit a PR soon!)

**Comment by adityaruplaha** [comment]
We're already working on this. See #337. Thanks for the interest though!

**Comment by flavioislima** [comment]
@dragonDScript enter our discord if you havent. We have a development channel there to discuss features, etc.

**Comment by dragonDScript** [comment]
Please review #423 again!

I've added log levels.
