### ISSUE TITLE
Update GamePage Design with new one

### ISSUE THREAD

**Issue by flavioislima** [Heroic-Games-Launcher/HeroicGamesLauncher#431]
**Is your feature request related to a problem? Please describe.**
As part of the new design initiative, we should start updating the current design with a new one.

**Describe the solution you'd like**

- [ ] Just follow the design spec we have on this Figma Project: https://www.figma.com/file/Zv89aBtLJ8yN4BwFS0AwNb/Heroic-Games?node-id=0%3A1
- [ ] Use current CSS or SASS.

**Comment by opllama2** [comment]
Hello, i would like to be a part of this if possible

**Comment by flavioislima** [comment]
> Hello, i would like to be a part of this if possible

Sure, be my guest and send us a PR. Join our discord server on the development and design channel if you emuage any questions or troubles during development.
