### ISSUE TITLE
Blank window on windows 10

### ISSUE THREAD

**Issue by currall** [Heroic-Games-Launcher/HeroicGamesLauncher#435]
![Heroic_Games_Launcher_K39tAMDs0L](https://user-images.githubusercontent.com/29579820/121783691-01331000-cba8-11eb-9913-a7d430bf170b.png)

**Comment by flavioislima** [comment]
Weird. Do you have powershell installed? That is the only thing I can think about.
Is your Windows customized or its the default?

**Comment by currall** [comment]
> 
> 
> Weird. Do you have powershell installed? That is the only thing I can think about.
> Is your Windows customized or its the default?

powershell is installed, is by default afaik. Windows is pretty vanilla

**Comment by flavioislima** [comment]
And you um have downloaded or built the exe from source ?

**Comment by currall** [comment]
downloaded latest release

**Comment by flavioislima** [comment]
Can you try to remove the folder
.config on your user folder?
And open heroic again?

**Comment by currall** [comment]
yeah, deleting .config worked. Thanks for the help

**Comment by flavioislima** [comment]
No worries. Probably some config got corrupted.
