### ISSUE TITLE
wineVersion never set if there is only one version installed

### ISSUE THREAD

**Issue by FireMasterK** [Heroic-Games-Launcher/HeroicGamesLauncher#440]
**Describe the bug**
When there is only one Wine version installed, the `wineVersion` is never set.

**To Reproduce**

1. Start off with no installed wine
2. Install wine.
3. See that the wine version is selected correctly.
4. Check `.config/heroic/` to see that no changes are made,

**Expected behavior**
The wine version is set correctly.

**Desktop (please complete the following information):**

- OS: EndaevorOS
- Version Rolling/Arch
- Game: N/A
- Wine/Proton version: latest from arch repo - 6.10
- Hardware specs (RAM, CPU, GPU): N/A

**Additional context**
Discussed on Discord.

**Comment by flavioislima** [comment]
Fixed on main branch
