### ISSUE TITLE
I can't start ANY game

### ISSUE THREAD

**Issue by dragonDScript** [Heroic-Games-Launcher/HeroicGamesLauncher#444]
**Describe the bug**
Installing games works correctly. But when I try to start a game, ANY of them, the button changes to PLAYING (STOP) and then to start again. When I launch things from Wine directly that doesn't happen. I haven't tried with Legendary directly.

**To Reproduce**

1. Install Heroic
2. Login
3. Start a game (neither rayman nor rocket league worked)

**Expected behavior**
I install the game, I start it, and I can play it.

**Desktop (please complete the following information):**

- OS: Ubuntu 21.04
- Version 1.7.0 moria
- Game: Rayman Legends/Rocket league
- Wine/Proton version:
- Wine 6.0.1, Proton Experimental
- Hardware specs (RAM, CPU, GPU): ryzen 7 cpu 64 bits, amd rx 5500 xt gpu. 16gb ram

**Comment by flavioislima** [comment]
On version you should put heroic version.

**Comment by dragonDScript** [comment]
Done

**Comment by flavioislima** [comment]
On our wiki, there are a few troubleshooting guides. Also, how to get logs about a game not working. You can start from there.
We also have our discord that would be good for you to join since you also want to contribute with code. 🙂

**Comment by dragonDScript** [comment]
> On our wiki, there are a few troubleshooting guides. Also, how to get logs about a game not working. You can start from there.
> We also have our discord that would be good for you to join since you also want to contribute with code.

I've already joined the Discord server.

Sorry for not sharing the logs. Here they are:
```
mesa: for the --simplifycfg-sink-common option: may only occur zero or one times!
mesa: for the --global-isel-abort option: may only occur zero or one times!
mesa: for the --amdgpu-atomic-optimizations option: may only occur zero or one times!
mesa: for the --structurizecfg-skip-uniform-regions option: may only occur zero or one times!
Protocol already registered.
launching Anchovy

 Launch Command:        /opt/heroic/resources/app.asar.unpacked/build/bin/linux/legendary launch Anchovy  --wine  --wine-prefix '/home/dragon/.wine' 
```

**Comment by flavioislima** [comment]
Yes earlier on discord. I sent the fix as a PR on #441.
Compile a deb from the updated main branch that should work 🙂

**Comment by dragonDScript** [comment]
Now it only says 'stop' and never shows the game's window.

**Comment by flavioislima** [comment]
No, the python info is misleading.
Now check the game logs.
Are you on X11 or wayland?

**Comment by dragonDScript** [comment]
> No, the python info is misleading.
> Now check the game logs.
> Are you on X11 or wayland?

I'm on X11.

The game logs are:
```
Error - Command failed:        /tmp/.mount_Heroic8WGYsw/resources/app.asar.unpacked/build/bin/linux/legendary launch Anchovy  --wine  --wine-prefix '/home/dragon/.wine' 
usage: legendary launch <App Name> [options]
legendary launch: error: argument --wine: expected one argument
```

**Comment by flavioislima** [comment]
> > No, the python info is misleading.
> > Now check the game logs.
> > Are you on X11 or wayland?
> 
> I'm on X11.
> 
> The game logs are:
> ```
> Error - Command failed:        /tmp/.mount_Heroic8WGYsw/resources/app.asar.unpacked/build/bin/linux/legendary launch Anchovy  --wine  --wine-prefix '/home/dragon/.wine' 
> usage: legendary launch <App Name> [options]
> legendary launch: error: argument --wine: expected one argument
> ```
> Which is fake, if you look at the launch command it is passing wine as an argument

Yeah but this doesn't look like the fixed version I sent. Use that one and go to the settings and change anything like the dxvk setting. Check if the json config file for that game had updated.
It should not be wine should be the whole path.

**Comment by dragonDScript** [comment]
> > > No, the python info is misleading.
> > > Now check the game logs.
> > > Are you on X11 or wayland?
> > 
> > I'm on X11.
> > 
> > The game logs are:
> > ```
> > Error - Command failed:        /tmp/.mount_Heroic8WGYsw/resources/app.asar.unpacked/build/bin/linux/legendary launch Anchovy  --wine  --wine-prefix '/home/dragon/.wine' 
> > usage: legendary launch <App Name> [options]
> > legendary launch: error: argument --wine: expected one argument
> > ```
> > Which is fake, if you look at the launch command it is passing wine as an argument
> 
> Yeah but this doesn't look like the fixed version I sent. Use that one and go to the settings and change anything like the dxvk setting. Check if the json config file for that game had updated.
> It should not be wine should be the whole path. 

It is the version I compiled from the main branch. I am checking It tomorrow.

**Comment by flavioislima** [comment]
@dragonDScript have you tried again?

**Comment by dragonDScript** [comment]
It hasn't worked.

**Comment by flavioislima** [comment]
Have you tried the troubleshooting guides?

**Comment by flavioislima** [comment]
But what happens when you change the game config in heroic and checks if the Json file with the config changes?
It gets updated somehow?
Also, can you try downloading some other wine version, like the ones from Lutris?
Or proton from steam?
And check if it works

**Comment by dragonDScript** [comment]
> But what happens when you change the game config in heroic and checks if the Json file with the config changes?
> It gets updated somehow?
> Also, can you try downloading some other wine version, like the ones from Lutris?
> Or proton from steam?
> And check if it works

I have a version from Lutris. I'll try it later (I'm not in my work PC). I also tried proton in the past, and it didn't work.

**Comment by dragonDScript** [comment]
From Lutris it doesn't work either.
