### ISSUE TITLE
Implement Button to create Desktop Shortcut

### ISSUE THREAD

**Issue by flavioislima** [Heroic-Games-Launcher/HeroicGamesLauncher#447]
**Is your feature request related to a problem? Please describe.**
The implementation is already done on the backend, so just need to add some way to call it from the frontend.
Also we need an option under settings to create or not Desktop Shortcuts automatically, since now this is always true.

**Describe the solution you'd like**
- [ ] A button on the game page to create a Desktop Shortcut to launch the game
- [ ] A Setting to enable/disabled create Desktop shortcuts automatically when installing.

**Comment by dragonDScript** [comment]
The second thing is already done. But it needs to be added to the UI.

**Comment by dragonDScript** [comment]
The second, we should split the code into a new function and call it from install if the setting is enabled. Easy!
I'm going to work on it

**Comment by flavioislima** [comment]
Yes, like I said, the Electron part is done, but needs to have something on the UI to the user.
for now we can add it to the dropdown menu we have on the game page.
