### ISSUE TITLE
Implement Install dialog when not installed game is launched from protocol

### ISSUE THREAD

**Issue by flavioislima** [Heroic-Games-Launcher/HeroicGamesLauncher#448]
**Is your feature request related to a problem? Please describe.**
The Backend part is done but there is no listener on the frontend for that.

**Describe the solution you'd like**
So now if the game is launcher from protocol and its not installed, a dialog appears but confirming the installation does nothing.
The installation should be triggered with the default install, the same way as when installing a game from the library.

**Comment by dragonDScript** [comment]
Already implemented (see https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/blob/5d94ef72854bedeed1748162f3d86e287ba0dd78/electron/protocol.ts#L32) but it could be improved.

**Comment by dragonDScript** [comment]
So should we convert this issue to a discussion? (to discuss the aspect of it, etc..)

**Comment by flavioislima** [comment]
Yeah I know, this ticket is a follow up from the current implementation. Clicking on the YES button doesn't do anything now.
We need to receive the call on the frontend and call the install function.
The electron part is done, but now needs the React part.
I explained how it needs to be done on you PR.

**Comment by flavioislima** [comment]
> So should we convert this issue to a discussion? (to discuss the aspect of it, etc..)

Nah, I don't there is much to be discussed about it. Its just a few lines of code for that to work.

**Comment by dragonDScript** [comment]
> Yeah I know, this ticket is a follow up from the current implementation. Clicking on the YES button doesn't do anything now.
> We need to receive the call on the frontend and call the install function.
> The electron part is done, but now needs the React part.
> I explained how it needs to be done on you PR.

that's not expected.

**Comment by flavioislima** [comment]
> > Yeah I know, this ticket is a follow up from the current implementation. Clicking on the YES button doesn't do anything now.
> > We need to receive the call on the frontend and call the install function.
> > The electron part is done, but now needs the React part.
> > I explained how it needs to be done on you PR.
> 
> that's not expected. i coded it to do something

And it is, its launching the game. 😛
