### ISSUE TITLE
Add a Queue system for download and updates. 

### ISSUE THREAD

**Issue by flavioislima** [Heroic-Games-Launcher/HeroicGamesLauncher#457]
**Is your feature request related to a problem? Please describe.**
Today Heroic uses parallel downloads what can take a lot of resources from the machine and also bug the installation of games that might show as not installed. 

**Describe the solution you'd like**
A queue  system implemented on the Global State. If a game is installing and the user asks to install another one, the last should go to the queue. 
After the installation finishes, on the ComponentDidUpdate function a helper function could check if any games are installing, if not, checks the queue and starts to install the new one if have some.

**Comment by dragonDScript** [comment]
```js
var queue = []

// when the user requests to install a game
queue.append(app_name)
if (queue[0] === undefined) return;
Game.get(queue[0]).install() // when completes, repeat (recursion)
```
This helps hopefully?

**Comment by ExperiBass** [comment]
has there been any progress on this? currently i have to wait till a game finishes downloading to download the next one.

**Comment by wiryfuture** [comment]
Summary to date of features wanted for this issue?
- Queue downloads + updates
- Ability to modify order of queue 
- Throttle/limit download rate

**Comment by dragonDScript** [comment]
I don't think parallel downloads should be a thing

**Comment by wiryfuture** [comment]
> I don't think parallel downloads should be a thing

Tbf some people have ridiculously fast internet so might want it, but it's kinda unecessary because if it's that fast then it'll be fine downloading everything synchronously.

**Comment by ExperiBass** [comment]
Either way, parallel downloads does make it a bit faster, whether you have slow or fast internet

**Comment by dragonDScript** [comment]
> Either way, parallel downloads does make it a bit faster, whether you have slow or fast internet.

I disagree. They should be opt-in because synchronously at least you can play 1 game while the other downloads

**Comment by ExperiBass** [comment]
> > Either way, parallel downloads does make it a bit faster, whether you have slow or fast internet.
> 
> 
> 
> I disagree. They should be opt-in because synchronously at least you can play 1 game while the other downloads

Oh for sure, it does need to be opt-in. But parallel downloads would bring a decrease in time spent waiting, especially if you're downloading a larger game with smaller games, as the smaller games will finish while the larger game is doing its thing, instead of the smaller games delaying the larger game or vice versa.

**Comment by wiryfuture** [comment]
> > > Either way, parallel downloads does make it a bit faster, whether you have slow or fast internet.
> > 
> > 
> > I disagree. They should be opt-in because synchronously at least you can play 1 game while the other downloads
> 
> Oh for sure, it does need to be opt-in. But parallel downloads would bring a decrease in time spent waiting, especially if you're downloading a larger game with smaller games, as the smaller games will finish while the larger game is doing its thing, instead of the smaller games delaying the larger game or vice versa.

You could just queue the small games first and the large one last and it solves that issue.

**Comment by ExperiBass** [comment]
> > > > Either way, parallel downloads does make it a bit faster, whether you have slow or fast internet.
> 
> > > 
> 
> > > 
> 
> > > I disagree. They should be opt-in because synchronously at least you can play 1 game while the other downloads
> 
> > 
> 
> > Oh for sure, it does need to be opt-in. But parallel downloads would bring a decrease in time spent waiting, especially if you're downloading a larger game with smaller games, as the smaller games will finish while the larger game is doing its thing, instead of the smaller games delaying the larger game or vice versa.
> 
> 
> 
> You could just queue the small games first and the large one last and it solves that issue.

That's what I touched upon in my reply. In a synchronous queue, the small games would delay the large game, instead of letting it download in the background at the same time.

**Comment by wiryfuture** [comment]
> > > > > Either way, parallel downloads does make it a bit faster, whether you have slow or fast internet.
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > I disagree. They should be opt-in because synchronously at least you can play 1 game while the other downloads
> > 
> > 
> > > 
> > 
> > 
> > > Oh for sure, it does need to be opt-in. But parallel downloads would bring a decrease in time spent waiting, especially if you're downloading a larger game with smaller games, as the smaller games will finish while the larger game is doing its thing, instead of the smaller games delaying the larger game or vice versa.
> > 
> > 
> > You could just queue the small games first and the large one last and it solves that issue.
> 
> That's what I touched upon in my reply. In a synchronous queue, the small games would delay the large game, instead of letting it download in the background at the same time.

The small games would finish downloading faster because they have the whole bandwidth 😆 so they'd be done faster and wouldn't do that 😅

**Comment by dragonDScript** [comment]
> Hey guys, you know that Legendary doesn't support parallel downloads right now, right? So it's not possible to have this in Heroic. 
> as another question, do you guys know any game launcher that supports that?
> Out of my mind: neither Steam, Uplay, EGL or GOG galaxy has it. And that's for a reason: parallel downloads has drawbacks for the system since its pretty intensive on some cases.
> 
> About the Queue. We can go for a simple Queue at first, that's means:
> - A Page/place to see the queue
> - Ability to add or remove an item from it.
> 
> In the future we can improve that to support:
> - Changing the order of queued items
> - Change the order of items even for started downloads. 
> 
> ⚔️ 
> 

You can launch multiple legendary processes tho.

**Comment by flavioislima** [comment]
@dragonDScript that doesn't solve the issue. Legendary will override the `installed.json` file and erase the games that were installed first.

**Comment by wiryfuture** [comment]
Probably the same with stuff like steam that's why they dont do it lol, or your package manager.

**Comment by arielj** [comment]
I agree that parallel downloads can be tricky and maybe too complex for the actual benefit to make it a priority for this feature. A queue solves the main problem of trying to download multiple things without waiting for one to finish, parallelization is some optimization for a specific case that could be treated as a separated feature.

I'm not sure how many users really NEED it (like I imagine people requesting it because they want it, but not as a need), I'd say that parallelization is something that shouldn't block the development of a queue system, maybe something that can be added in the future if found possible.

**Comment by wiryfuture** [comment]
> Chrome supports parallel downloads. And they're fine. That's why people demand this people.

chrome parallel downloads are completely different because it isn't indexing versions in one file

**Comment by dragonDScript** [comment]
> > Chrome supports parallel downloads. And they're fine. That's why people demand this people.
> 
> chrome parallel downloads are completely different because it isn't indexing versions in one file

If this is the main reason then lock files exist for a reason

**Comment by Etaash-mathamsetty** [comment]
any updates on this?

**Comment by ekianjo** [comment]
I was about to post a feature request on this, but noticed that this existed. This is a problem not to have a queue system for large downloads that take time. You don't want to lose several hours of download just because you were not around to "click install" for the next game.

**Comment by QUASARFREAK** [comment]
+1

**Comment by oleghind** [comment]
+1

**Comment by Etaash-mathamsetty** [comment]
I found an interesting "bug", I was updating one game, and another game had an update available, so clicked update and both games started updating (at the same time), and finished successfully

**Comment by arielj** [comment]
Can we close this? :D

**Comment by flavioislima** [comment]
Yes, closing...

**Comment by N-R-K** [comment]
> > Can we close this? :D
>
> Yes, closing...

I don't think queue ordering part has been implemented. I'm trying to put the currently downloading game (a large one) and start downloading a smaller game from the queue but I'm not seeing any obvious way to do this in the UI.
