### ISSUE TITLE
No Audio While Playing Among Us

### ISSUE THREAD

**Issue by cow-killer** [Heroic-Games-Launcher/HeroicGamesLauncher#463]
I can't find a Discord link anywhere...so I hope nobody minds if I post here.

**Describe the bug**
No audio while playing Among Us. Running Arch Linux. From what I understand I need some type of `lib32` audio library, but I'm not sure which.

**Desktop:**

- OS: Garuda
- Game: Among Us
- Wine/Proton version: 6.3
- Hardware specs: i5-8400, GTX 1660, 24 GB RAM

**Comment by flavioislima** [comment]
The discord link is on the github main page.
There is a button in the top.
Also on heroic itself, if you out the mouse on your username will appear a menu and there we have a discord link as well.
