### ISSUE TITLE
Request: An update button directly visible instead of being in sub-menu

### ISSUE THREAD

**Issue by ekianjo** [Heroic-Games-Launcher/HeroicGamesLauncher#464]
**Is your feature request related to a problem? Please describe.**
Even though HL clearly displays games that need updates, there is no way from that view to actually update the game(s) with one click. You need to go in the game details and the side menu to update the game. 

**Describe the solution you'd like**
A "Update game" button next to "Play Now" and "Uninstall" in the game details screen, and also a mini-icon in the overall game list to do the same thing.

**Comment by dragonDScript** [comment]
I will work on it myself

**Comment by dragonDScript** [comment]
Fixed, it is text instead of a button as per @flavioislima
