### ISSUE TITLE
Linux assets in the Releases page are shipped with unused macOS binary

### ISSUE THREAD

**Issue by guihkx** [Heroic-Games-Launcher/HeroicGamesLauncher#467]
**Describe the bug**
A 7 MB macOS binary is being shipped with Linux releases.

**To Reproduce**
Go to the [Releases](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/releases) page, download any asset, notice that they have a macOS binary under `/opt/heroic/resources/app.asar.unpacked/build/bin/darwin`

**Expected behavior**
No macOS binary.

**Screenshots**
N/A

**Desktop (please complete the following information):**
N/A

**Comment by Nocccer** [comment]
Can confirm. Same for .deb package.

**Comment by Nocccer** [comment]
Solution: asarUnpack per os entry
https://www.electron.build/configuration/configuration#overridable-per-platform-options
