### ISSUE TITLE
Add catalan to the language selector.

### ISSUE THREAD

**Issue by dragonDScript** [Heroic-Games-Launcher/HeroicGamesLauncher#473]
**Is your feature request related to a problem? Please describe.**
Is it clear enough?

**Describe the solution you'd like**
Add it.

**Describe alternatives you've considered**
No

**Additional context**
I've added translations for the catalan language. But it doesn't appear in the app. We should add it

**Comment by Nocccer** [comment]
Maybe you need to add it to the languageSelector in 'src/components/UI/LanguageSelector/index.tsx'

**Comment by flavioislima** [comment]
It needs to be added in several places, also on the backend on the main.js file on the list of supported languages.
Also on `index.tsx` file on src and on the language selector.

**Comment by flavioislima** [comment]
I saw that the translation is not finished on weblate, is at 56%. so don't forget to finish it first before adding on the app. :)
