### ISSUE TITLE
Make fortnite compatible with Heroic

### ISSUE THREAD

**Issue by dragonDScript** [Heroic-Games-Launcher/HeroicGamesLauncher#475]

**Comment by Nocccer** [comment]
Ask Epic or EAC to do it :D 
Actually a issue we can't fix

**Comment by 616b2f** [comment]
It's this still valid?
 https://www.gamingonlinux.com/2021/09/epic-games-announce-full-easy-anti-cheat-for-linux-including-wine-a-proton/

Epic announced Linux Support und also for Proton (see link above)

Bright future for Linux community :)

**Comment by flavioislima** [comment]
Yes, fortnite still doesn't work on Linux. Perhaps this might change when steam deck s launched.

**Comment by dragonDScript** [comment]
Perhaps make it downloadable for when it works. Same for 2077

**Comment by flavioislima** [comment]
But you can download them

**Comment by dragonDScript** [comment]
I can't. Let's go to discord #linux channel

**Comment by thebigsmileXD** [comment]
I am on windows and just noticed fortnite is the only game i got that won't start from heroic. GOG Galaxy does it though, and i can even have heroic running whilst launching fortnite, so i don't really see the issue?
