### ISSUE TITLE
wine tracked_files missing. What are they?

### ISSUE THREAD

**Issue by Mangus78** [Heroic-Games-Launcher/HeroicGamesLauncher#484]
Hi, just installed heroic but I have a problem using proton.
I have steam with the latest 4 versions of proton installed. With steam and proton games are running flawlessly.
But on heroic, with every game I try, if I select any version of proton, I always receive the following message in the log file:

FileNotFoundError: [Errno 2] No such file or directory: '/home/myhome/.wine/tracked_files'

I've tried with stable and staging wine, installed dxvk and any other prerequisites.
If I select standard wine, the games start but with proton they don't.

II know that probably is not a problem related directly to heroic but searching on the web I can't find anything about these "tracked_files", other than that proton doesn't generate them and I have to put them there manually but I don't even know what they are and where I can found/how to generate them!

Thanks in advance for any help.

I'm on intel+nvidia combination with ubuntu 21.04

**Comment by flavioislima** [comment]
Proton outside steam is complicated.
Try using Lutris wine or look for Wine-GE.

Check our Wiki to understand how to use Proton and custom wine on Heroic.

Also, when using Proton, is good to make a new prefix instead of using the default one. Try this and it might fix your issue

**Comment by Mangus78** [comment]
> Proton outside steam is complicated.
> Try using Lutris wine or look for Wine-GE.
> 
> Check our Wiki to understand how to use Proton and custom wine on Heroic.
> 
> Also, when using Proton, is good to make a new prefix instead of using the default one. Try this and it might fix your issue

Shouldn't Proton be more optimized for games than plain wine or lutris?
I hadn't any wine installed before, so It shouldn't be a "prefix" problem.
The error it seems to speak for itself I suppose but searching on google gives very little results.
one is this page: https://github.com/Fincer/steamproton-systemwine/blob/master/files_proton/proton

Where, in the code, you can read this line:
#proton 3.7 did not generate tracked_files, so copy it into place first

But wtf is tracked_files? LOL

Anyway, I didn't know wine-ge, what is it exactly? I see there are different "flavours" of it.

I'm a beginner with this kind of things and sorry if I'm asking stupid or rhetoric questions. But I must say that the info and documentation online are a little bit "blurry" and it's difficult to find a "straight" and "official" way to install and configure.
For example, I followed precisely some guide but at the end they can play games with proton and I'm not. 
Thanks a lot.

**Comment by flavioislima** [comment]
> > Proton outside steam is complicated.
> > Try using Lutris wine or look for Wine-GE.
> > Check our Wiki to understand how to use Proton and custom wine on Heroic.
> > Also, when using Proton, is good to make a new prefix instead of using the default one. Try this and it might fix your issue
> 
> Shouldn't Proton be more optimized for games than plain wine or lutris?
> I hadn't any wine installed before, so It shouldn't be a "prefix" problem.
> The error it seems to speak for itself I suppose but searching on google gives very little results.
> one is this page: https://github.com/Fincer/steamproton-systemwine/blob/master/files_proton/proton
> 
> Where, in the code, you can read this line:
> #proton 3.7 did not generate tracked_files, so copy it into place first
> 
> But wtf is tracked_files? LOL
> 
> Anyway, I didn't know wine-ge, what is it exactly? I see there are different "flavours" of it.
> 
> I'm a beginner with this kind of things and sorry if I'm asking stupid or rhetoric questions. But I must say that the info and documentation online are a little bit "blurry" and it's difficult to find a "straight" and "official" way to install and configure.
> For example, I followed precisely some guide but at the end they can play games with proton and I'm not.
> Thanks a lot.

Proton, yes, will be better than wine for most things. But at the same time Proton was created for Steam, uses several files and libraries from it, and Steam know how to handle them.
Outside of steam is recommended to use Wine since other apps might not handle Proton libraries correctly, so its a hit or miss that depends on several other factors.

Even if you havent used wine before, just create a new prefix and try other wine versions like latest Wine Lutris or Wine-GE, the compatibility should be close to Proton's.

**Comment by flavioislima** [comment]
Closing this since its not an heroic issue.
