### ISSUE TITLE
Store game information on app storage to increase loading times. 

### ISSUE THREAD

**Issue by flavioislima** [Heroic-Games-Launcher/HeroicGamesLauncher#488]
**Is your feature request related to a problem? Please describe.**

Right now, every time we open the game page we make a api request to the epics servers to get the game info. So would be nice to not to have this since might be slow depending on the hardware and connection. 

**Describe the solution you'd like**

Instead of making several requests, store the information on the first request in the browser storage and get the from there after it. That would improve a lot the time to open the game page.

**Comment by dragonDScript** [comment]
What if the user adds a new game from the web store (e.g. the free game of the week)?

**Comment by flavioislima** [comment]
> What if the user adds a new game from the web store (e.g. the free game of the week)?

We just need to check if we have some info on the storage, if not, we get it from the API and store it.
So we will always need to fetch the info at least once. 
After that, we will fetch from storage.
