### ISSUE TITLE
Create .desktop launcher files for installed games on Linux

### ISSUE THREAD

**Issue by neffo** [Heroic-Games-Launcher/HeroicGamesLauncher#489]
**Is your feature request related to a problem? Please describe.**
Create .desktop files when games are installed.

**Describe the solution you'd like**
Launching games and adding Heroic games through Steam (as a non-steam game) would be easier if .desktop files could be created on install and added to "$HOME/.local/share/applications". Steam on Linux works does this, and under GNOME this means that opening these games directly outside of Steam is easily achieved from the desktop (even if Steam isn't currently open).

(This would allow broader support for controllers and also Steam in-home streaming support.)

Unsure exactly how games are launched through Heroic, but this may require the launcher to be "wrapped" by the Steam to ensure that video can be captured and controller support provided.

**Describe alternatives you've considered**
Not sure of another way to enable this, I don't think an alternative exists to expose game launchers.

**Additional context**

Example file created by Steam (Firewatch.desktop):
```
[Desktop Entry]
Name=Firewatch
Comment=Play this game on Steam
Exec=steam steam://rungameid/383870
Icon=steam_icon_383870
Terminal=false
Type=Application
Categories=Game;
```

**Comment by B34rly** [comment]
Yes, this is a feature that will be added in the next version. It has already been added, but requires more testing.

**Comment by flavioislima** [comment]
Exactly. This feature is implemented and will be on next release.

**Comment by neffo** [comment]
Thanks all, I didn't see it in the feature list. I couldn't build the git version, so or else I'd have liked to check it out.
