### ISSUE TITLE
Heroic shows blank screen when clicking "Proton - Proton"

### ISSUE THREAD

**Issue by SpeedyGamer32** [Heroic-Games-Launcher/HeroicGamesLauncher#491]
**Describe the bug**
For some reason heroic becomes a blank window when click "Proton - Proton" under wine section. You can resolve this by just restarting heroic as changed arent saved

**To Reproduce**
1. Launch Heroic
2. Go to Settings
3. Go to Wine
4. Under wine version select "Proton - Proton"
5. Observe how the screen goes blank

**Expected behavior**
Screen is not supposed to go blank, it is supposed to select Proton and work fine

**Screenshots**

This is neofetch
https://imgur.com/HV7QPZ6

This is proton version
https://imgur.com/gu9sOzZ

This is the blank screen with terminal output 
https://imgur.com/Ynfm1Jr

**Desktop:**

- OS: Arch Linux
- Heroic Version: https://aur.archlinux.org/heroic-games-launcher-bin.git
- Wine/Proton version: Proton Experimental, Wine 6.11 
- Hardware specs (RAM, CPU, GPU): See neofetch screenshot please.

**Additional context**
No additional context.

**Comment by Nocccer** [comment]
@flavioislima @dragonDScript really strange problem here.
I looked over the frontend, but didn't see any problem.
Do you have any idea ?

**Comment by flavioislima** [comment]
Can you try to run from terminal and check if you have someberror message? Because I never got any error like that. Don't really know how to reproduce it. And I have 10 different wine and proton versions right now.

**Comment by Nocccer** [comment]
@flavioislima see last picture. Terminal is showing nothing. Maxbe something todo with "proton - proton". Can a version parsed as "proton" break something ?

**Comment by flavioislima** [comment]
> @flavioislima see last picture. Terminal is showing nothing. Maxbe something todo with "proton - proton". Can a version parsed as "proton" break something ?

We parse a Proton if the binary is called proton so I don't see anything there. Anyway. Might be that he have no read access to this proton file, folder, etc. Might be some permission issue. I dont think this is a heroic one if it's working normally for everyone else.

**Comment by Nocccer** [comment]
But it sounds like heroic issues. Because it doesn't rerender the winesettings package if a wineversion is selected.

**Comment by flavioislima** [comment]
> But it sounds like heroic issues. Because it doesn't rerender the winesettings package if a wineversion is selected. And for me sounds like some paths/checks to find installed proton/wine versions is broken.

Then we need more information. Did you reproduce it?

@SpeedyGamer32 where are your proton versions installed?
Can you try to remove the folder .config/heroic and try again?
Which proton version is that?

**Comment by Nocccer** [comment]
@flavioislima it is proton experimental installed via steam. See the attached pictures

**Comment by flavioislima** [comment]
> @flavioislima it is proton experimental installed via steam. See the attached pictures

Ah OK. But still, try removing that folder @SpeedyGamer32 it won't remove games or anything, just heroic settings. You can just rename it if you want as well.

**Comment by flavioislima** [comment]
Also try to reproduce it on version 1.8.0-rc1, you can download the appimage or the pacman file.

**Comment by SpeedyGamer32** [comment]
ok i have reinstalled proton but choose v.6.3 instead of experimental and it seems to be fine, so if there is any other issues ill reopen the this issue thank you
