### ISSUE TITLE
Game page for 'The Spectrum Retreat' does not open

### ISSUE THREAD

**Issue by Goggo66** [Heroic-Games-Launcher/HeroicGamesLauncher#500]
**Describe the bug**
The game page for the latest free game, "The Spectrum Retreat", does not open.

**To Reproduce**

1. Add game to library.
2. Click on game icon to open the game page.
3. For a brief moment, the rotating icon appears, then the window goes black. There is no way to return. Heroic has to be closed and restarted.

**Expected behavior**
Game page should open.

**Desktop (please complete the following information):**

- OS: Kubuntu
- Version 21.04
- Game: The Spectrum Retreat
- Wine/Proton version: n/a
- Hardware specs AMD Ryzen 3700X, 16 GByte, AMD RX580

**Comment by flavioislima** [comment]
Interesting. This game might be missing some info we use there and that's why is broken.

**Comment by flavioislima** [comment]
Fixed on #501 
for now install it on default path and to access the settings use the settings button on the card.
Next release will contain the fix.
Thanks for pointing the issue.

**Comment by debiangamer** [comment]
Can you run the game? When I open it with the small play button on the right of the Heroic launcher the game will display an opening screen then the following access error immediately. Using winehq-devel 6.11 and dxvk 1.9.1.
![image](https://user-images.githubusercontent.com/15704414/124246529-ae56d380-db29-11eb-83bc-170d45739f71.png)

**Comment by flavioislima** [comment]
Yes, same here. I have no idea why. I'll try on windows if I have time.
Maybe the game runs offline but the offline toggle in Heroic is not working, need to be fixed.
Try running the exe directly with wine.

**Comment by Goggo66** [comment]
Same here with Proton 6.3.
Maybe a misconfiguration on Epic side?

**Comment by Goggo66** [comment]
Update: In my case, the message above is opened in a browser window. The game itself has been started, and is minimised to the taskbar. Clicking on the taskbar icon will open the game in fullscreen mode. It seems to be running just fine.

**Comment by flavioislima** [comment]
> Can you run the game? When I open it with the small play button on the right of the Heroic launcher the game will display an opening screen then the following access error immediately. Using winehq-devel 6.11 and dxvk 1.9.1.
> ![image](https://user-images.githubusercontent.com/15704414/124246529-ae56d380-db29-11eb-83bc-170d45739f71.png)

To avoid this. On the game settings, under launch arguments, pass the flag: `--offline` since heroic offline options is not working.
