### ISSUE TITLE
Cannot install any games on v1.8.1 

### ISSUE THREAD

**Issue by Ruthenic** [Heroic-Games-Launcher/HeroicGamesLauncher#511]
### Open here only issues with Heroic like: Heroic doesn't open, some button is out of place, Heroic closes unexpectedly, installs got interrupted, etc.

**Describe the bug**
Whenever clicking on the install button, the application reloads, and the game is never installed. Using the command present in the console logs, however, it works and installs properly (see [1] for details), and after installing them, launching works fine.

**To Reproduce**

1. Attempt to install any game.
2. The application flickers for a moment (presumably reloading?).
3. After reloading, no change in the status of installation on the GUI occurs, and [1] appears in the console logs

**Expected behavior**
For the game to properly install into `~/Games/Heroic`

**Screenshots**
N/A

**Desktop (please complete the following information):**

- OS: Void Linux
- Version: Not Applicable
- Game: Any (although I mainly tried with Among Us and World of Goo)
- Wine/Proton version: Wine 6.9
- Hardware specs (RAM, CPU, GPU): 
     - CPU: AMD Ryzen 5 3500
     - GPU: NVIDIA GeForce GTX 1650 SUPER
     - RAM: 7930MiB

**Additional context**
I am using a manually compiled version, as there are no official packages for Void Linux as of now.
[1]: 
`INFO: Installing 963137e4c29d4c79a81323b8fab03a40 with: /usr/lib/heroic-games-launcher/resources/app.asar.unpacked/build/bin/linux/legendary install 963137e4c29d4c79a81323b8fab03a40 --base-path /home/ruthenic/Games/Heroic --max-workers 2 -y |& tee "/home/ruthenic/.config/heroic/GamesConfig/963137e4c29d4c79a81323b8fab03a40.log"`
`INFO: finished installing`
`INFO: operation interrupted`

**Comment by Nocccer** [comment]
Which game you try to install. Origin games and also fortine and cyberbunk can't be installed straight away. If it is none of them switch to 1.7.2 and we will investigate this bug.

**Comment by Ruthenic** [comment]
> Which game you try to install.  

As I mentioned in the `Desktop` section, I've tried World of Goo and Among Us (why does the template put that in the desktop section anyways?).
> What package manager use void Linux ?  

`xbps`, however it should have no effect in this case as I am not using any package managment at the moment for this package
> Did you tried tried the downloadable appimage for 1.8.1 ?  

Yes, it has the same issue

**Comment by flavioislima** [comment]
Sorry. For now we can't support compiled packages since every machine and installation will have its peculiarities.

As for distros right now we support Ubuntu and derivatives and partially Arch and derivatives.

So we won't be able to help you on that.
If you want, join our discord server and maybe someone else there has tried heroic on void Linux. 👍

**Comment by WhiteCzar** [comment]
I have the same issue on 1.9 on PopOS, which is a Ubuntu derivative. I choose install or import and it flickers for a moment and says "game is imported" but nothing actually happens.

**Comment by Ruthenic** [comment]
What shell are you using, @WhiteCzar (also you may want to make a new issue, as this one has already been closed)

**Comment by flavioislima** [comment]
The fish issue was fixed on 1.8.2.
@WhiteCzar check the troubleshooting guide on our wiki and if nothing works start a new issue here. But add proper logs and informations.

**Comment by WhiteCzar** [comment]
It downloaded after a few clicks. I can't recreate this bug so I guess it was just a network bug or something. Sorry!

**Comment by Verberk** [comment]
> It downloaded after a few clicks. I can't recreate this bug so I guess it was just a network bug or something. Sorry!

Looks like this worked for me too, just click a couple of times, but had the same issue as you described.
