### ISSUE TITLE
Issues with Game installations on 1.8.1 due to $SHELL Variable being SH or Fish

### ISSUE THREAD

**Issue by BlackJim313** [Heroic-Games-Launcher/HeroicGamesLauncher#516]
After switching from version 1.7.2 to 1.8.1, it was impossible for me to install my games, I tried several and each time the installation launched and closed. So I reinstalled version 1.7.2 and there the installations are going very well. I am under Kubuntu 21.04 up to date, Linux 5.11.0-22-generic, I got 12GO RAM, CPU : AMD FX8350 8 cores.

**Comment by flavioislima** [comment]
> After switching from version 1.7.2 to 1.8.1, it was impossible for me to install my games, I tried several and each time the installation launched and closed. So I reinstalled version 1.7.2 and there the installations are going very well. I am under Kubuntu 21.04 up to date, Linux 5.11.0-22-generic, I got 12GO RAM, CPU : AMD FX8350 8 cores.

Use the template to report bugs and attach logs and info from terminal.

**Comment by Ruthenic** [comment]
I seem to have had a similar problem in #511, although it was closed because I was using an unsupported distribution

**Comment by Ruthenic** [comment]
Are you using a shell incompatible with `|&` or `tee` (I.E. `fish` and `sh`)? That was my problem, so it might be a similar problem in your case.

**Comment by flavioislima** [comment]
Yes. On 1.8 we are running the install command and others using the shell found on the shell environment variable. I'll revert this change and put back to run always on bash.

**Comment by flavioislima** [comment]
I'm closing this one since was fixed in 1.8.2.
If the issue persists we can reopen it.
