### ISSUE TITLE
Wrong button label displayed on GamePage

### ISSUE THREAD

**Issue by nettnikl** [Heroic-Games-Launcher/HeroicGamesLauncher#523]
**Describe the bug**
The game is fully and successfully installed, and can be started. However besides the "play now" button, the "continue download" is displayed instead of "uninstall game".

**To Reproduce**
Sadly i cannot reproduce, other games work as expected.

**Expected behavior**
A "uninstall game" button, as the game is fully installed.

**Desktop (please complete the following information):**

- OS: Ubuntu 20.04 based
- Version: 1.8.1 Arlong
- Game: GTA V

**Additional context**
I did install and uninstall the game multiple times, and switched the installation path - probably too rapidly, and may ended up in messing up the cache/meta data about the installation status.
It would help to know in which file i can fix this. In the source it seems it loads a string about the installation path and checks for empty values, but i don't know much about electron.

**Comment by flavioislima** [comment]
Yes, I noticed this issue, at least the behavior is not changed its just the label.
I'll fix it on 1.8.3 that I'll release probably this weekend with other fixes as well.

**Comment by flavioislima** [comment]
This was fixed, will be on next release!
