### ISSUE TITLE
Default Installation Path | Windows

### ISSUE THREAD

**Issue by Razuuu** [Heroic-Games-Launcher/HeroicGamesLauncher#537]
**Describe the bug**
"Linux" Slash in Default Installation Path
' on choose Folder

**To Reproduce**
-

**Expected behavior**
The Default Settings are (UserPath)/Games/Heroic but it should like (UserPath)\Games\Heroic

When i choose my custom Folder for the Installation Path then it will place on the beginning a ' and at the end a '
Like this: 'E:\Spiele\Heroic'

**Screenshots**
https://s-upload.xyz/i/Heroic_X0IIJvKTiQ.png
https://s-upload.xyz/i/Heroic_ngMCIhjq2f.png

**Desktop**

- OS: Windows 11
- Version 1.8.2
- Game: -
- Wine/Proton version: -
- Hardware specs (RAM, CPU, GPU): -

**Additional context**
Would be nice if this will be fixxed :)

**Comment by flavioislima** [comment]
Hi!
I tested here and the games are being installed on the right path.
You're having issues with the games being installed on the wrong folder? Or its just aesthetics?

**Comment by flavioislima** [comment]
Anyway, fixed:
![image](https://user-images.githubusercontent.com/26871415/125643457-9ebbcad5-adb4-488a-bdb2-038929ea49df.png)

**Comment by Razuuu** [comment]
Just aesthetic
