### ISSUE TITLE
Heroic 1.8.* do not start

### ISSUE THREAD

**Issue by KittenEvil** [Heroic-Games-Launcher/HeroicGamesLauncher#545]
**Describe the bug**
Running /opt/Heroic/heroic no longer runs the program (no window).

**Expected behavior**
The programs runs as usual, able to start games etc

**Desktop (please complete the following information):**

- OS: Fedora 
- Version 33
- Game: heroic-1.8.2.x86_64.rpm (from github, not from copr)
- Wine/Proton version: wine 6.11-1.fc33

**Additional context**

 /opt/Heroic/heroic 
(node:9684) UnhandledPromiseRejectionWarning: Error: Command failed: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary status
Traceback (most recent call last):
  File "legendary/cli.py", line 1375, in <module>
  File "legendary/cli.py", line 1361, in main
  File "legendary/cli.py", line 1034, in status
  File "legendary/core.py", line 221, in get_game_list
  File "legendary/core.py", line 252, in get_game_and_dlc_list
AttributeError: 'NoneType' object has no attribute 'is_dlc'
[9722] Failed to execute script cli

    at ChildProcess.exithandler (child_process.js:317:12)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1048:16)
    at Socket.<anonymous> (internal/child_process.js:439:11)
    at Socket.emit (events.js:315:20)
    at Pipe.<anonymous> (net.js:673:12)
(Use `heroic --trace-warnings ...` to show where the warning was created)
(node:9684) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:9684) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:9684) UnhandledPromiseRejectionWarning: Error: Command failed: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary status
Traceback (most recent call last):
  File "legendary/cli.py", line 1375, in <module>
  File "legendary/cli.py", line 1361, in main
  File "legendary/cli.py", line 1034, in status
  File "legendary/core.py", line 221, in get_game_list
  File "legendary/core.py", line 252, in get_game_and_dlc_list
AttributeError: 'NoneType' object has no attribute 'is_dlc'
[9721] Failed to execute script cli

    at ChildProcess.exithandler (child_process.js:317:12)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1048:16)
    at Socket.<anonymous> (internal/child_process.js:439:11)
    at Socket.emit (events.js:315:20)
    at Pipe.<anonymous> (net.js:673:12)
(node:9684) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)

**Comment by flavioislima** [comment]
This error seems to be with legendary as we can see on the python output. Really weird. Have you bought any new game recently? Dlc or anything? Also, can you try other heroic versions like 1.7.2? Even thought if it s a legendary issue it won't work as well.
And can you run this ont terminal:
` /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary status`

**Comment by KittenEvil** [comment]
> This error seems to be with legendary as we can see on the python output. Really weird. Have you bought any new game recently? Dlc or anything? Also, can you try other heroic versions like 1.7.2? Even thought if it s a legendary issue it won't work as well.
1.7.2 works fine. No recent buys for money, but a few days ago I added the (free at that time) Offworld Trading Company.

I have just updated to 1.8.2 and run status, and then auth, then Heroic. Funny enough, now everything works totally fine.

```$  /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary status
[Core] INFO: Trying to re-use existing login session...
Epic account: ***
Games available: 33
Games installed: 1
EGL Sync enabled: False
Config directory: /home/***/.config/legendary
$  /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary auth
[cli] INFO: Testing existing login data if present...
[Core] INFO: Trying to re-use existing login session...
[cli] INFO: Stored credentials are still valid, if you wish to switch to a different account, run "legendary auth --delete" and try again.

**Comment by flavioislima** [comment]
> > This error seems to be with legendary as we can see on the python output. Really weird. Have you bought any new game recently? Dlc or anything? Also, can you try other heroic versions like 1.7.2? Even thought if it s a legendary issue it won't work as well.
> 
> 1.7.2 works fine. A few days ago I added the (free at that time) Offworld Trading Company.
> 
> I have just updated to 1.8.2 and run status, and then auth, then Heroic. Funny enough, now everything works totally fine.
> 
> ```
> [Core] INFO: Trying to re-use existing login session...
> Epic account: ***
> Games available: 33
> Games installed: 1
> EGL Sync enabled: False
> Config directory: /home/***/.config/legendary
> $  /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary auth
> [cli] INFO: Testing existing login data if present...
> [Core] INFO: Trying to re-use existing login session...
> [cli] INFO: Stored credentials are still valid, if you wish to switch to a different account, run "legendary auth --delete" and try again.
> ```

So now Heroic runs well? Yeah, maybe it was just some weird error that happens from time to time and "restarting" or rebooting the PC fixes it 😂

**Comment by flavioislima** [comment]
Just got here that game you said and I had no issues as well so it seems it was just a temporary issue. If this happens again, feel free to open a new issue or go to our discord where the support is faster :)
