### ISSUE TITLE
Integration with SteamOS

### ISSUE THREAD

**Issue by ArturWroblewski** [Heroic-Games-Launcher/HeroicGamesLauncher#546]
**Integration with SteamOS**
Currently, integration with SteamOS version 2.x and in summer this year integration with SteamOS 3.x

**Reason**
If we have the only working epic games store for Steam Deck on the day of Steam Deck launch, it will bring a lot of popularity to Heroic.
We can say that it will be the only simple alternative to play Epic games without flashing the device and loading windows.

**Execution proposal**
The easiest way to do this is as a full-screen application that will run as an epic Heroic store.
It will be harder to integrate this as a plugin.

**Essential**
This version of the Heroic Store requires the Steam OS color scheme. Lest the user / customer see the difference when entering the Heroic Store and think it is a natural part of Steam OS, he would not see the difference between the two.

**Comment by flavioislima** [comment]
Hi!
Yes, I'm already doing some research on how we can have a full screen and gamepad/touch driven interface and it will be ready for Steam Deck Launch :)

**Comment by ArturWroblewski** [comment]
Cool. I've already ordered Steam Deck, so I'll be happy to test it when it's ready.

Anyone with Steam OS experience? How to add additions there?

**Comment by flavioislima** [comment]
I don't have experience, I'll need to check the docs on how to add it as an Add-on or something.
I'll let you know once we have something to test :)

**Comment by JacoG-RH** [comment]
Not sure how active/well maintained this is, but might be useful here. https://github.com/CorporalQuesadilla/Steam-Shortcut-Manager

**Comment by flavioislima** [comment]
> Not sure how active/well maintained this is, but might be useful here. https://github.com/CorporalQuesadilla/Steam-Shortcut-Manager

Thanks, we can use this to add a new option to add a shortcut of the game on steam on Heroic, I think Lutris has this option and would not be too much to implement I guess.

**Comment by JacoG-RH** [comment]
I have poking at Lutris for this and it does not seem to have this feature.

**Comment by flavioislima** [comment]
> I have poking at Lutris for this and it does not seem to have this feature.

that's true, I could not find it as well. I think I'm confused 😅

**Comment by toalex77** [comment]
I don't know if it can be useful, but I wrote a little wrapper to run legendary inside the Steam Linux Runtime 2 (soldier), to run my Epic games inside Steam (as a non-steam app), in a sandboxed environment, with the Steam Overlay available and, of course, with the ability to use the Steam Controller.

This is the code:

```
#!/bin/bash
steamLinuxRuntime_bin="/mnt/data/steam-library/steamapps/common/SteamLinuxRuntime_soldier/run"
legendary_bin="$(which legendary)"

# LC_ALL=en_US.UTF-8 it's necessary to "legendary list-installed" command, to not crash when it encounter a game title with UTF-8 characters
export LC_ALL=en_US.UTF-8
export PRESSURE_VESSEL_FILESYSTEMS_RO="${legendary_bin}"

if [ $# -ge 1 ]; then
  GAME_NAME="$1"

  if [ $# -ge 2 ]; then
    PROTON_VER="$2"
  else
    PROTON_VER="Proton-6.14-GE-2"
  fi

  LEGENDARY_LINE="$(${legendary_bin} list-installed --show-dirs --tsv | grep "${GAME_NAME}" | tr -d '\n\r')"
  
  if [ "${LEGENDARY_LINE}" != "" ]; then
    EPIC_GAME_NAME="$(echo -n "${LEGENDARY_LINE}" | cut -f 1)"
    GAME_DIR="$(echo -n "${LEGENDARY_LINE}" | cut -f 7)"

    GAME_DIRNAME="$(basename "$(echo -n "${GAME_DIR}")")"

    # Where I've installed my Epic Games
    HEROIC_BASEDIR="$(dirname "$(echo -n "${GAME_DIR}")")"
    # Where I put all the Wine Prefixes for the games
    PREFIX_BASEDIR="${HEROIC_BASEDIR}/WinePrefix"
    PROTON_BASEDIR="${HOME}/.steam/root/compatibilitytools.d/${PROTON_VER}"

    export DXVK_FRAME_RATE="0"
    #export DXVK_HUD="fps,scale=0.75"
    export STEAM_COMPAT_CLIENT_INSTALL_PATH=${HOME}/.steam/steam
    export STEAM_COMPAT_DATA_PATH="${PREFIX_BASEDIR}/${GAME_DIRNAME}"
    export PYTHONHOME=/usr
    export PYTHONPATH=/usr/lib64/python3.8/lib-dynload:/usr/lib64/python3.8
    export WINEDLLPATH="${PROTON_BASEDIR}/files/lib64/wine:${PROTON_BASEDIR}/files/lib/wine"

    if [ ! -d "${STEAM_COMPAT_DATA_PATH}" ]; then
      mkdir -p "${STEAM_COMPAT_DATA_PATH}"
    fi

    ${steamLinuxRuntime_bin} -- ${legendary_bin} launch "${EPIC_GAME_NAME}" --language it --no-wine --wrapper "'${PROTON_BASEDIR}/proton' waitforexitandrun"
  fi
fi

```

It need a little bit of works, to get automatically the correct paths insted of the actually fixed in the code itself (steamLinuxRuntime_bin, PROTON_BASEDIR, a check if the Proton version required really exists, ... ).

This wrapper expects as first, obbligatory parameter, the name of the game (ex. "Absolute Drift") and as a second optional parameter, the desired Proton version to run the game (or it force the one written in the code, actually "Proton-6.14-GE-2").
Then set some necessary environment variables and subsequently it runs legendary inside Soldier.

**Comment by toalex77** [comment]
I've done some of the needed works, and uploaded on github https://github.com/toalex77/steam-legendary-wrapper/blob/main/steam-legendary-wrapper.sh
Now the wrapper get some of the needed information from the system.

**Comment by sasquatchs** [comment]
@toalex77 cool script. How are you getting that to work with the Steam Overlay though? The games I've tried launch fine but there's no overlay

**Comment by toalex77** [comment]
In the last eight days I've updated a lot the script, and I've added a [README](https://github.com/toalex77/steam-legendary-wrapper/blob/main/README.md) with all the necessary instruction. Take a look at it.
Actually some manual steps are needed (to add programmatically a non-steam-game, is needed to modify a binary file, while Steam is not running, so at the moment I've given up).

Here is an extract of the README, where I explain the steps to add as a Non-Steam-Game the wrapper:

> Now you can create in the Steam Client for Linux a non-Steam Game (Games -> Add a Non-Steam Game to My Library), specifying the full path to where you have put steam-legendary-wrapper.sh (ex. ~/bin/steam-legendary-wrapper.sh) and the game name in the Launch Options, surrounded by double quotes, if the name containing spaces (ex. "Absolute Drift").
> In the Launch Options, you can specify also a second optional parameter, with the desired Proton Version (ex. "Proton 6.3"). If omitted, at the moment, the wrapper set "Proton-6.14-GE-2".
> Then you can specify also a third optional parameter, with the desired Steam Linux Runtime version. If omitted, at the moment, the wrapper set "Steam Linux Runtime - Soldier".
> 

Anyway you can obtain the same results, without the wrapper, by add Legendary as a Non-Steam-Game, with these parameters "launch "EPIC_GAME_ID" --no-wine --wrapper "'PATH_TO_PROTON/proton' waitforexitandrun" and by settings as "Compatibility", force the use of "Steam Linux Runtime" (to force to run legendary inside the sandboxed Steam Runtime, Soldier).
I think it is possible also to add Heroic Game Launcher as a Non-Steam-Game, but I've not tested this.

**Comment by Citrinate** [comment]
> @toalex77 cool script. How are you getting that to work with the Steam Overlay though? The games I've tried launch fine but there's no overlay

Same issue, I was able to resolve it by changing the line:
`steamLinuxRuntime_bin="${STEAM_LINUX_RUNTIME_BASEDIR}/common/${STEAM_LINUX_RUNTIME_INSTALLDIR}/run"`
to:
`steamLinuxRuntime_bin="${STEAM_LINUX_RUNTIME_BASEDIR}/common/${STEAM_LINUX_RUNTIME_INSTALLDIR}/_v2-entry-point"`

**Comment by toalex77** [comment]
> > @toalex77 cool script. How are you getting that to work with the Steam Overlay though? The games I've tried launch fine but there's no overlay
> 
> Same issue, I was able to resolve it by changing the line:
> `steamLinuxRuntime_bin="${STEAM_LINUX_RUNTIME_BASEDIR}/common/${STEAM_LINUX_RUNTIME_INSTALLDIR}/run"`
> to:
> `steamLinuxRuntime_bin="${STEAM_LINUX_RUNTIME_BASEDIR}/common/${STEAM_LINUX_RUNTIME_INSTALLDIR}/_v2-entry-point"`

Hi,
just today I've updated the script, with that piece of code reviewed: now I get the command line used by the Steam Linux Runtime, from its toolmanifest.vdf file.

Anyway I think any other message about my script, is better if is being posted on my repository, because here can be out of context. I posted here my script only to let to know that there is some work done to integrate legendary inside the Steam Client, and that this work, if desired, can be used in any other project.

**Comment by flavioislima** [comment]
I will consider this done after releasing Heroic Flatpak since it can be installed on the deck and used from there
