### ISSUE TITLE
Windows Fresh install - Default Path discrepancy 

### ISSUE THREAD

**Issue by Kacper-DevSecOps** [Heroic-Games-Launcher/HeroicGamesLauncher#548]
**Describe the bug**
On windows default installation path have slashes instead of the backslashes 
Just a small nitpick as everything installs and launches just fine 

**To Reproduce**

1. Do a fresh install 
2. Look at the default path in settings 

**Expected behavior**
All the (back)slashes should match the way of the OS intended use of them 

**Screenshots**
![image](https://user-images.githubusercontent.com/51424308/126067403-dfc7b6c8-f7b6-42b2-aa0d-9b847b692778.png)
![image](https://user-images.githubusercontent.com/51424308/126067460-70d33eef-6104-4ce6-9359-f3be4ddc16aa.png)

**Desktop (please complete the following information):**

- OS: Windows 10
- release 1.8.2 - from 2 weeks ago

**Comment by Kacper-DevSecOps** [comment]
Never mind that 
 I see somebody pushed a change 4 days ago for this exact issue

**Comment by flavioislima** [comment]
> Never mind that
> I see somebody pushed a change 4 days ago for this exact issue

Yes, will be fixed on next release.
