### ISSUE TITLE
How does syncing work?

### ISSUE THREAD

**Issue by kcthrn** [Heroic-Games-Launcher/HeroicGamesLauncher#55]
1. For automatic syncing to work, does Heroic detect where the save data is located or do I have to manually declare the path to the save data?
2. What's the purpose of Forced Upload/Forced Download?
3. When does automatic syncing occur if enabled?

**Comment by flavioislima** [comment]
There is no way for Heroic to guess the right saves folder so you need to choose it manually on the sync settings page.
All we get from Epic is that info that I put that starts with `{AppData}/...`. Then you will need to find the right folder and choose it.
Another idea and the one I personally use is to go to the PC Gaming Wiki website and check the Save folder there. 

So should be like this:

1. find out the right folder where the save files are stored.
2. go to Game > Settings > Sync and choose the folder.
3. You can use the Download Button to download the saves right away.

The Automatic Sync works exactly like in the Epic Launcher, every time before and after the game runs it will upload the updated save game, or download if there is a new one ( in case you played the game on the official epic launcher and get back to Heroic)

The Force-upload and download work as follows:
` --force-upload      Force upload even if local saves are older
  --force-download    Force download even if local saves are newer`

**Comment by kcthrn** [comment]
Thank you. Currently, automatic syncing can be toggled on if no path to a save directory is given, and when the game is launched the _Play Now_ button is stuck on _Syncing Saves_ until I go back to the Library.

Similarly, the sync dropdown box is also interactable. Perhaps the toggle and dropdown controls can be disabled until a path is given?

**Comment by kcthrn** [comment]
@flavioislima **A possible solution to automatically detecting cloud save location:**

Since strings like {AppData} are Windows environment variables, can Heroic use wine to expand the variables to get the path?

For example: Heroic states Pikuniku's save location as `{AppData}/../LocalLow/Sectordub/Pikuniku/saves/`.
Using `wineconsole`, I entered `echo %AppData%` which returned `C:\users\<my name>\Application Data`, which allowed me to use the rest of the path  `..\LocalLow\Sectordub\Pikuniku\saves\` to correctly find the save location.

Some strings like {InstallDir} (Celeste `{InstallDir}/Saves/`) and {UserDir} (20XX `{UserDir}/20XX/`; Darkest Dungeon `{UserDir}/Darkest/`) are not Windows envs will have to be replaced by Heroic. I determined {InstallDir} to be where Heroic installed the game, and {UserDir} to be the user's Documents/My Documents folder within the Wine prefix.

**Comment by flavioislima** [comment]
> Thank you. Currently, automatic syncing can be toggled on if no path to a save directory is given, and when the game is launched the _Play Now_ button is stuck on _Syncing Saves_ until I go back to the Library.
> 
> Similarly, the sync dropdown box is also interactable. Perhaps the toggle and dropdown controls can be disabled until a path is given?

Good, forgot to set them to disabled. Will do that in the future.

About the auto-sync solution. Yeah, I was trying to do something like this but it would take too much effort. The names that we got from epic do not have a pattern. For instance, sometimes we got {AppData} and some times {appdata} So it would be crazy to simple treat all cases. Right now, legendary supports this 'guessing' feature, but it is not 100% accurate afaik, so I don't know. I think this time the user will need to think a little, unless we find some other solution in the future. I'm in touch with the Legendary devs and maybe we can think about that in the future. But if it would be too much effort, I don't know.

**Comment by kcthrn** [comment]
Would partial support for automatically setting the path work? So, for path strings from Epic that Heroic **is 100% not confident in resolving**, on a game's info page, there would be text telling the user that manual intervention for cloud saves was needed.

For paths strings that are easy to resolve, Heroic would set the path automatically?

Also, I think that on Windows, environment variables are case-insensitive.

**Comment by flavioislima** [comment]
@kcthrn i noticed that when epic says` {AppData}/directory`, it is actually `user/Local Settings/Application Data`. Then when it is `{AppData}/../LocalRow`, then is the actual `user/AppData`. At least for Control and Alien: Isolation it is like this. I'll make some tests this weekend to try to add a 'guessing' function to get at least the most common paths.

**Comment by flavioislima** [comment]
I started to work on improving this and it is working good so far, if all my tests go well I'll try to put the feature on next release.
@kcthrn

**Comment by daydreamercodes** [comment]
Hello, sync preferences are not appearing in game/app settings for me. Is this expected or am I missing something? @flavioislima
![image](https://user-images.githubusercontent.com/61342411/108856788-75e33e00-75fb-11eb-9344-c58d76ad8427.png)
![image](https://user-images.githubusercontent.com/61342411/108856879-91e6df80-75fb-11eb-83c3-e93a16292306.png)

**Comment by flavioislima** [comment]
> Hello, sync preferences are not appearing in game/app settings for me. Is this expected or am I missing something? @flavioislima
> ![image](https://user-images.githubusercontent.com/61342411/108856788-75e33e00-75fb-11eb-9344-c58d76ad8427.png)
> ![image](https://user-images.githubusercontent.com/61342411/108856879-91e6df80-75fb-11eb-83c3-e93a16292306.png)

That's because not all games have this feature. When a game supports it you will see the information on the game page.
