### ISSUE TITLE
(Windows) Heroic doesnt start

### ISSUE THREAD

**Issue by Kroggieboy57** [Heroic-Games-Launcher/HeroicGamesLauncher#554]
I use heroic in Windows10. I have installed it for the first time in this machine. However the laucher doesn't start. I tried running the launcher with administrator thinking that might fix this, but it didn't ;-; pls help

**Comment by flavioislima** [comment]
Try uninstalling and installing it again.
Also, are you changing the default installation path?

**Comment by Kroggieboy57** [comment]
I tried that before opening this issue :/ but didn't work. I don't think I changed the installation path I just  click the installer and it installs without any options

**Comment by flavioislima** [comment]
Strange. Do you have Powershell enabled, right? Because I know some debloat scripts remove or disable it and Heroic depends on powershell for everything on Windows.

Also, check if a `.config` folder was created on your user folder and delete the legendary and heroic folder inside it.

**Comment by Kroggieboy57** [comment]
I deleted the heroic folder inside `.config` and still the same :/
I have powershell enabled too

**Comment by Kroggieboy57** [comment]
You mean cmd right?
i am on windows not linux

**Comment by Kroggieboy57** [comment]
(node:8040) UnhandledPromiseRejectionWarning: Error: Command failed: C:\Users\my name\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\legendary.exe status
'C:\Users\my' is not recognized as an internal or external command,
operable program or batch file.

    at ChildProcess.exithandler (child_process.js:317:12)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1048:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
(Use `heroic --trace-warnings ...` to show where the warning was created)
(node:8040) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:8040) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:8040) UnhandledPromiseRejectionWarning: Error: Command failed: C:\Users\my name\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\legendary.exe status
'C:\Users\my' is not recognized as an internal or external command,
operable program or batch file.

    at ChildProcess.exithandler (child_process.js:317:12)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1048:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
(node:8040) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:8040) UnhandledPromiseRejectionWarning: Error: Command failed: C:\Users\my name\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\legendary.exe status
'C:\Users\my' is not recognized as an internal or external command,
operable program or batch file.

    at ChildProcess.exithandler (child_process.js:317:12)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1048:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
(node:8040) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)

**Comment by Kroggieboy57** [comment]
This is the error i get

**Comment by flavioislima** [comment]
I see, I'll generate a test version in a few minutes. I think I know the issue.
Is your name a mix of two names? like you added there: "my name" ?

**Comment by flavioislima** [comment]
Try this one: https://drive.google.com/file/d/1Tmsv3K4_ZkLSyBJb2J2mXKmQMdBhpu6p/view?usp=sharing

I'm not sure if it will fix it but will give us more information about the error.

**Comment by flavioislima** [comment]
Ignore the previous one. I did some research about this bug in windows with spaces and I think now I fixed it:
https://drive.google.com/file/d/1-7p-iHU55y2nzCfSnMVxpPj81HnQpoF2/view?usp=sharing

**Comment by Kroggieboy57** [comment]
Yes my name is a mix of two names
I will try the fix

**Comment by Kroggieboy57** [comment]
heroic

C:\Users\my name\AppData\Local\Programs\heroic>
INFO: Trying to get user information
INFO: Trying to get user information
ERROR: Error: Command failed: C:\Users\my name\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\legendary.exe status
'C:\Users\my' is not recognized as an internal or external command,
operable program or batch file.

ERROR: Error: Command failed: C:\Users\my name\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\legendary.exe status
'C:\Users\my' is not recognized as an internal or external command,
operable program or batch file.

(node:11468) UnhandledPromiseRejectionWarning: Error: Command failed: C:\Users\my name\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\legendary.exe status
'C:\Users\my' is not recognized as an internal or external command,
operable program or batch file.

    at ChildProcess.exithandler (child_process.js:317:12)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1048:16)
    at Socket.<anonymous> (internal/child_process.js:439:11)
    at Socket.emit (events.js:315:20)
    at Pipe.<anonymous> (net.js:673:12)
(Use `heroic --trace-warnings ...` to show where the warning was created)
(node:11468) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:11468) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by Kroggieboy57** [comment]
This error comes for that

**Comment by flavioislima** [comment]
So it didn't fix? I'll check other alternatives then

**Comment by Kroggieboy57** [comment]
Ok, thank you!

**Comment by flavioislima** [comment]
Ok, I think I've missed something last time. Lets try it now:
https://drive.google.com/file/d/1w31bcbmQgRbkCC9JZXbCqg96Qf_rNh09/view?usp=sharing

**Comment by Kroggieboy57** [comment]
Do I need to delete the previous version before installing this?

**Comment by flavioislima** [comment]
> Do I need to delete the previous version before installing this?

I think it will overwrite, but maybe do a clean install, would be better,
uninstall and install this other one.

**Comment by Kroggieboy57** [comment]
IT WORKS YESSSSSSS. Thanks a lot!!

**Comment by flavioislima** [comment]
Amazing, test all basic features when you can because something else might have some issues.
And thanks for finding and reporting this issues because probably some other people might have it as well. :D

**Comment by Kroggieboy57** [comment]
Um sorry but I still have an issue now ._.
![image](https://user-images.githubusercontent.com/66489697/126804329-431ca9a7-6790-4628-a7d5-034377801348.png)
It doesn't load

**Comment by flavioislima** [comment]
> Um sorry but I still have an issue now ._.
> ![image](https://user-images.githubusercontent.com/66489697/126804329-431ca9a7-6790-4628-a7d5-034377801348.png)
> It doesn't load

Yes, so there is an issue with the refresh library function.
Probably the same but can you show the logs?

**Comment by flavioislima** [comment]
So, I made a portable version, since everything is packed inside, should have no issues with path as spaces and etc.
I think I'll made this the main windows version now:
https://drive.google.com/file/d/1W4I9XIZTz6AhsKEsU8FWub7VPsY_MguH/view?usp=sharing

**Comment by Kroggieboy57** [comment]
> So then we need to debug the issue.
> Open the folder where the Heroic.exe is installed and then open a terminal there and run:
> `heroic`
> Heroic will open and show some error on the terminal.

Logs meaning this right?

**Comment by flavioislima** [comment]
> > So then we need to debug the issue.
> > Open the folder where the Heroic.exe is installed and then open a terminal there and run:
> > `heroic`
> > Heroic will open and show some error on the terminal.
> 
> Logs meaning this right?

Yes. But forget about that and just run the latest one I sent that is portable. I think it will work.

**Comment by Kroggieboy57** [comment]
Okay lemme run it

**Comment by Kroggieboy57** [comment]
Yes it works, let me try running a game

**Comment by Kroggieboy57** [comment]
Rocket league works but it is not connecting to epic games online service :/

**Comment by flavioislima** [comment]
> Rocket league works but it is not connecting to epic games online service :/

Yes, that's another thing not related to heroic but in short, for that you will need epic overlay, that's something neither heroic or legendary supports since its proprietary to epic.
So, any game that does need it for anything, will work only when using the epic launcher 😕

Since heroic worked now for login, library, install, etc. I think the issues was fixed with the portable version.
