### ISSUE TITLE
Heroic Has Not Received Update For GTA V

### ISSUE THREAD

**Issue by SonicRoshan** [Heroic-Games-Launcher/HeroicGamesLauncher#555]
### Open here only issues with Heroic like: Heroic doesn't open, some button is out of place, Heroic closes unexpectedly, installs got interrupted, etc.

**Describe the bug**
An update game to gta yesterday however heroic games launcher has not detected it. However my friend who uses heroic has got the update. I have reinstalled the game twice but I get the old version.

**To Reproduce**

Download gta v

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS: Arch
- Version 5.12
- Game: GTA V
- Wine/Proton version: wine tkg 6.1
- Hardware specs (RAM, CPU, GPU):

**Additional context**

**Comment by flavioislima** [comment]
Not an heroic issue. Try getting help on our discord.

**Comment by SonicRoshan** [comment]
Sorry the game was updated, my bad
