### ISSUE TITLE
Setup a CDN for the locales

### ISSUE THREAD

**Issue by dragonDScript** [Heroic-Games-Launcher/HeroicGamesLauncher#574]

**Comment by arielj** [comment]
Is this issue still relevant? it's not clear what it means and why it's marked as high priority

**Comment by flavioislima** [comment]
This could be useful to update translations without the need of a release but we never really decided on how to do that.

**Comment by flavioislima** [comment]
Not possible, I mean, possible but we would need to change all translations for all 42 languages we support actually, this should have been planned before Heroic started. 

In the future moving to a new repo might be ideal
