### ISSUE TITLE
Word not breaking when too long on the wine information on game page

### ISSUE THREAD

**Issue by Taza53** [Heroic-Games-Launcher/HeroicGamesLauncher#576]
![image](https://user-images.githubusercontent.com/34032665/127412492-54671643-03d7-40d7-b70e-7e8a05ad6e42.png)

Fix could be text wrapping in.

BTW love the new update

**Comment by flavioislima** [comment]
Fixed
![image](https://user-images.githubusercontent.com/26871415/128568007-3e45f47b-bc8e-4ddf-9fc2-5ec5d1f02bb7.png)
