### ISSUE TITLE
Slackware(64) 14.2 & HeroicGamesLauncher AppImage

### ISSUE THREAD

**Issue by inukaze** [Heroic-Games-Launcher/HeroicGamesLauncher#578]
$ `./Heroic-1.9.0.AppImage `

> Fontconfig warning: "/etc/fonts/fonts.conf", line 102: unknown element "blank"
> INFO: Trying to get user information
> INFO: Trying to get user information
> INFO: User Not Found, removing it from Store
> INFO: Trying to get user information
> ERROR: Failed to register protocol with OS.
> WARNING: python command not found
> WARNING: Command python3 version '3.7.2' not supported.
> ERROR: Heroic requires Python 3.8 or newer.
> INFO: Trying to get user information
> INFO: Trying to get user information
> INFO: checking for heroic updates
> Check failed: chdir(current_directory) == 0
> INFO: Logging with Legendary...

```
stderr: [1309] Error loading Python lib '/tmp/_MEIXKcGGZ/libpython3.8.so.1.0': dlopen: /lib64/libc.so.6: 
version `GLIBC_2.25' not found (required by /tmp/_MEIXKcGGZ/libpython3.8.so.1.0)

```

> finished login
> INFO: Frontend: Called Login
> INFO: Trying to get user information
> INFO: Refreshing library...
> 

`reset ; echo -ne 'GLIBC Versions Supported by Slakware64 14.2 :\n\n' ; strings /lib64/libc.so.6 | grep -E "^GLIBC_.{3,4}$" | sort -V | uniq`
Output : 

> GLIBC Versions Supported by Slakware64 14.2 :

> GLIBC_2.3
> GLIBC_2.4
> GLIBC_2.5
> GLIBC_2.6
> GLIBC_2.7
> GLIBC_2.8
> GLIBC_2.9
> GLIBC_2.10
> GLIBC_2.11
> GLIBC_2.12
> GLIBC_2.13
> GLIBC_2.14
> GLIBC_2.15
> GLIBC_2.16
> GLIBC_2.17
> GLIBC_2.18
> GLIBC_2.22
> GLIBC_2.23

Some guide how to compile under Slackware(32,64) 14.2 ?

**Comment by flavioislima** [comment]
Since this is not an heroic issue, go to out discord to get some help.
But in the end, you will need python 3.8 or greater and glibc 2.25 or greater.
