### ISSUE TITLE
Add Heroic Check for update settings to the UI.

### ISSUE THREAD

**Issue by dragonDScript** [Heroic-Games-Launcher/HeroicGamesLauncher#580]
We can't change the minute interval nor can we disable updates right now.

**Comment by Shotweb** [comment]
Does this also cover the bug where it is not possible to disable checking for updates?

**Comment by dragonDScript** [comment]
> Does this also cover the bug where it is not possible to disable checking for updates?

There are two ways to check for updates in heroic right now, one that actually updates the app and another where it only redirects to the github. Which do you mean?

**Comment by Shotweb** [comment]
On my Debian system, it doesn't save disabling "Check for updates on startup". I guess that's something else then, that I should make a separate bug report for.
