### ISSUE TITLE
MacOSX Menu Bar Icon Way Too Big

### ISSUE THREAD

**Issue by highjeans** [Heroic-Games-Launcher/HeroicGamesLauncher#581]
### Try to get help on our Wiki first: https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/wiki/Troubleshooting

**Describe the bug**
The menu bar icon on macOS is way too big as shown in the screenshot attached

**To Reproduce**
Open heroic games launcher 1.9.0 on macOS and look at the menu bar icon

**Expected behavior**
I expected the icon to be a lot smaller

**Screenshots**

**Desktop (please complete the following information):**

- OS: macOS Big Sur 11.5.1
- Version 1.9.0
<img width="652" alt="Screen Shot 2021-08-01 at 6 09 15 PM" src="https://user-images.githubusercontent.com/77588045/127791813-8b1890b8-bb52-4476-af89-16edd0addbb3.png">

**Comment by flavioislima** [comment]
Crazy hell! that's not right. We changed the icons and I thought that Mac would resize it automatically like Linux and Windows does. So maybe we will need smaller icons for mac only.
