### ISSUE TITLE
Add Game Context Menu on the GameCard

### ISSUE THREAD

**Issue by flavioislima** [Heroic-Games-Launcher/HeroicGamesLauncher#582]
**Is your feature request related to a problem? Please describe.**
Add a Right-Click Menu on the game card with options like:
- Launch
- Configure
- Install
- Uninstall
- Update

**Describe the solution you'd like**
When clicking with the right button on the game card, no option is shown, would be nice to have some things like I said above.

**Additional context**
I'm most sure if it's possible to do it with some electron feature or will need to be done with React code.

**Comment by flavioislima** [comment]
Maybe this might help:
https://www.npmjs.com/package/electron-context-menu

**Comment by dragonDScript** [comment]
I can realize this without the need of any third party module.

**Comment by flavioislima** [comment]
> I can realize this without the need of any third party module.
> 
> Would you prefer a native context menu, like the npm module you passed, or a well-looking one?

Would be better to create one with HTML, React, ofc. :)

**Comment by flavioislima** [comment]
Done!
