### ISSUE TITLE
Bug ao retornar ao Heroic Game Launcher depois de fechar o jogo

### ISSUE THREAD

**Issue by Aelsoncf10** [Heroic-Games-Launcher/HeroicGamesLauncher#586]
![Captura de tela de 2021-08-03 10-55-17](https://user-images.githubusercontent.com/85807626/128027880-bd811dcd-021b-431d-be96-c3162e86f2ff.png)

**Comment by Aelsoncf10** [comment]
sempre ficar nessa tela então tenhoque fechar o launcher e abrir de novo.

**Comment by flavioislima** [comment]
Se quiser supporte em portugues, use o Discord. Aqui no GH só em inglês, senão fica ruim pra galera depois.
https://discord.gg/TRbJCxwe
