### ISSUE TITLE
Portable mode

### ISSUE THREAD

**Issue by dragonDScript** [Heroic-Games-Launcher/HeroicGamesLauncher#587]
**Is your feature request related to a problem? Please describe.**
Both Linux AppImage and Windows portable are designed to have their configs in the installation directory, and not in HOME. This way people can move their folder and they will conserve the config. No need to install it in another machine with an installer.

**Describe the solution you'd like**
Portable configuration. For legendary, it is possible to pass this environment variable: `XDG_CONFIG_HOME` (see [Legendary/#287](https://github.com/derrod/legendary/issues/287)). For Heroic config, we need to use a custom solution.

For detecting if you are in portable mode in Electron.js, use electron-builder.

**Describe alternatives you've considered**
None

**Additional context**
See the discord for more context.

**Comment by AndhikaWB** [comment]
It seems that the solution above no longer work. Heroic will still launch but it won't login to Epic account no matter how many times I tried. No, it's not captcha/bot issue, the login was successful but Heroic/Legendary won't detect it (no account/games added).

Apart from Legendary `XDG_CONFIG_HOME` issue, using `--user-data-dir=XXXX` parameter when launching Heroic will also cause it to hang (just idling in background) without showing the launcher. All other Electron based apps work fine though (e.g. WhatsApp, Discord).

Maybe those 2 paths were hardcoded somewhere so changing it will cause weird issues. If we don't want to move/backup data on each start/exit, the solution right now is by using junction/symlink which is kinda dirty. Attached below is my PortableApps.com launcher configured for Heroic (hopefully not as permanent workaround). Windows only.

[Heroic Portable.zip](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/files/12139104/Heroic.Portable.zip)
