### ISSUE TITLE
Game downloads slow down considerably after a few gigabytes.

### ISSUE THREAD

**Issue by DuhonTheGuy** [Heroic-Games-Launcher/HeroicGamesLauncher#593]
### Try to get help on our Wiki first: https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/wiki/Troubleshooting

**Describe the bug**
I am trying to install Grand Theft Auto V (Quite big game), and I noticed the download were going at a snail's pace, about 3 megabytes a second compared to 50 like they were when I started. After cancelling the download (when asked to keep the files I chose yes), it ran a little "installing..." message and was back at good download speeds. It continues to repeat this.

**To Reproduce**
As far as I am aware, just download any game big enough so that you'll have to do that. I am not sure if it is a me issue, but that is about it.

**Expected behavior**
Expected consistent download speeds.

**Screenshots**

**Desktop (please complete the following information):**

- OS: Ubuntu 20.04
- Version 1.9.0
- Game: GTA 5, however this also happened with other games.
- Wine/Proton version: Proton 6.3
- Hardware specs (RAM, CPU, GPU): GTX 1050, Intel i5 8300H CPU @ 2.3GHz, 8 Gigabytes of RAM.

**Additional context**
Just installed the 1.9 version of the launcher.

**Comment by flavioislima** [comment]
Sorry but download speeds are not related with heroic since this depends on two things: Epic's servers, that's are really unstable recently, and the amount of cores do you have. If the amount of workers on the general settings is set to Max, then heroic is doing its best.
