### ISSUE TITLE
Add patreons to the about page

### ISSUE THREAD

**Issue by dragonDScript** [Heroic-Games-Launcher/HeroicGamesLauncher#594]
Patreons are really helpful to this project. We should include them in the about page (like "special thanks" in some games).

# Alternatives

A "sponsors" button that redirects to patreon website or our own website and that shows all the protons. This is a simpler approach but personally I'd prefer the first one.

**Comment by flavioislima** [comment]
@dragonDScript can you improve the ticket description?

**Comment by flavioislima** [comment]
better do  #2018 instead
