### ISSUE TITLE
(MacOs) Heroic 1.9.0 - Launcher Black Screen

### ISSUE THREAD

**Issue by greggggggggg** [Heroic-Games-Launcher/HeroicGamesLauncher#595]
### Try to get help on our Wiki first: https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/wiki/Troubleshooting

**Describe the bug**
Blue/Black screen stops Heroic Launcher from working

**To Reproduce**

1. Go to 'Heroic' Application
2. Wait for 5-15 seconds and the app will show a blue/black screen 

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS: Big Sur 11.4
- Version: 1.9.0 'Mihawk'

**Additional context**

when i open Heroic Launcher for about 5-15 seconds, it shows a blue/black screen with no buttons, so you have to close and reopen it. this happens every time i open it. I am on an 8GB M1 Macbook Air, Big Sur 11.4
<img width="1282" alt="Screenshot 2021-08-05 at 16 35 20" src="https://user-images.githubusercontent.com/88501569/128378648-5d61c6bc-998d-4484-bae1-a5beeeb0e939.png">

**Comment by flavioislima** [comment]
Hi!
I cannot reproduce it on a MacBook 2019, I don't have an M1 to try and I'm not on BigSur.
Can you also try version 1.8.2 and check if the error happens.

Check this on how to run Heroic from the terminal: 
https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/wiki/Troubleshooting#running-heroic-from-terminalpowershell-to-debug-errors

And this on how to get the frontend errors:
https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/wiki/Troubleshooting#debugging-frontend-errors

**Comment by greggggggggg** [comment]
I don't know how, but it seems to have fixed itself, i did view>reload a couple of times, and now it is perfectly normal

**Comment by flavioislima** [comment]
I see. I guess macos somehow is slower to write the cache and that's why it worked after keep trying. I'll try to find a fix on next version.

**Comment by flavioislima** [comment]
I was able to reproduce the error running from the DMG file, the App should be copied to the applications folder, otherwise it won't be able to write the cache files and will crash.
