### ISSUE TITLE
Option to limit download bandwidth

### ISSUE THREAD

**Issue by Fjantom** [Heroic-Games-Launcher/HeroicGamesLauncher#597]
Downloading at the full capacity of my internet connection causes others on my network to have a bad experience just browsing the web or other light tasks. I usually fix this by limiting downloads to around 90% of full capacity. Would be great if such an option was available in Heroic.

**Comment by flavioislima** [comment]
We have this option, not exactly a download limiter but you can use the max workers option to limit the download speed as well.
Just go to settings and set a limit lower than the amount of cpu threads you have.

**Comment by Fjantom** [comment]
I would argue this does not fulfill the functionality I am talking about. I have a modern processor with high single-threaded performance, so limiting the download to a single thread is still close to saturating my connection. Someone else with a faster CPU or a slower connection could still run into issues.

**Comment by flavioislima** [comment]
Yes, I know. The thing is, its not heroic that download the games, Lengedary does, and for now it doesn't support limiting the download, so there is not much we can do about it.

**Comment by Fjantom** [comment]
Thanks for the info, I see this issue has been posted on the Legendary page already, but marked low priority.

**Comment by Arcitec** [comment]
It's a difficult problem to solve. The Legendary discussion is here:

https://github.com/derrod/legendary/issues/132
