### ISSUE TITLE
incorrect sizing on cover art

### ISSUE THREAD

**Issue by LukeVader-IV** [Heroic-Games-Launcher/HeroicGamesLauncher#603]
**Describe the bug**
not all the game artwork is the same aspect ratio. Cover art with a wider or taller aspect ratio to be cut off on the bottom or right side, this only happens on the library page and not the game page.

**To Reproduce**

check your library

**Expected behaviour**

stretched artwork

**Screenshots**

![image](https://user-images.githubusercontent.com/15455108/128636863-aa5f6636-f3e7-46d6-9d56-91aa4cbff33c.png)

expected:
![image](https://user-images.githubusercontent.com/15455108/128637384-cbda1d4b-58f2-49ac-9a51-e01dc38bd400.png)

**Desktop**

— OS: Fedora 34
— Version 1.9.1
— Game: any game with a wider aspect ratio (e.g., “Unreal Tournament”, “Watch Dogs”, “Control”, “AER Memories Of Old”, “Killing Floor 2”, “Overcooked” “World War Z”, Etc…)

**Additional context**

This can be easily solved by changing ```background-size: cover;``` to ```background-size: 100% 100%;``` or even better, completely removing the line.
![image](https://user-images.githubusercontent.com/15455108/128637473-8383802b-684f-4180-8479-9604d6fa4966.png)

I can't for the life of me find where this line is in the source code.

**Comment by LukeVader-IV** [comment]
PS: stretching the game to fit works well in some cases and looks weird in others.

Our once tall basketball player
![image](https://user-images.githubusercontent.com/15455108/128637578-c5b61a6c-ee80-46aa-8c2c-353a81621aae.png)
is a bit too short to play now xD
![image](https://user-images.githubusercontent.com/15455108/128637592-bc87f51e-dc6f-43f8-8459-087eeac9db07.png)

**Comment by flavioislima** [comment]
Ok. I'll leave this as Good first issue since seems simple to solve and could be good to new contributors.

**Comment by flegald** [comment]
I can get this fixed

**Comment by lesourcil** [comment]
I have the same problem using the flatpak version and DPI scaling to 115% in Fedora

<img width="1639" height="379" alt="Image" src="https://github.com/user-attachments/assets/302c4fe8-dd59-437f-a13f-dbbdb15437f0" />

**Comment by LukeVader-IV** [comment]
@flavioislima could this issue be re-opened?

**Comment by flavioislima** [comment]
> @flavioislima could this issue be re-opened?

I'm not sure it's the same issue though. Because the gog, epic and Amazon looks fine. For the latest message I believe the issue is with sideloaded games and for those we have no control over the arts, since it can be anything.
