### ISSUE TITLE
After installing a game the main library page still shows game as uninstalled

### ISSUE THREAD

**Issue by ajhbh** [Heroic-Games-Launcher/HeroicGamesLauncher#604]
### Try to get help on our Wiki first: https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/wiki/Troubleshooting

**Describe the bug**
Install a new game. The game installs correctly but Heroic does not refresh the library to show this fact until restarting Heroic. Seems introduced in the latest version 1.9.1 as I hadn't noticed this behaviour in previous versions.

**To Reproduce**

1. Install a game.
2. Note once the install is completed the individual game page still shows 'game not installed'.
3. Navigate to the main library and note the library still shows the game as uninstalled.
4. Navigating back to the game page now shows the game as installed.
5. Restarting Heroic recognises the status of the game as installed on the main library page.

**Expected behavior**
In previous Heroic versions the library would update the status of a newly installed game immediately upon install completing.

**Screenshots**

**Desktop (please complete the following information):**

- OS: Linux Mint 20.2
- Version: Heroic v1.9.1
- Game: Any.
- Wine/Proton version: n/a
- Hardware specs (RAM, CPU, GPU): n/a

**Additional context**

**Comment by flavioislima** [comment]
Fixed on 1.9.2
