### ISSUE TITLE
Question:How to skip snap and AppImage build?

### ISSUE THREAD

**Issue by katnatek** [Heroic-Games-Launcher/HeroicGamesLauncher#607]
I try to package you application for mageia, all goes fine until the process try
`building        target=AppImage`

I don't want to build the snap and the AppImage, its possible to skip or avoid that?

**Comment by flavioislima** [comment]
yes, just do:
`yarn dist {package format}`
for instance: `yarn dist rpm` or `yarn dist deb`.

For questions please use discussions or ask on discord.

What package format does mageia uses btw?

**Comment by katnatek** [comment]
> yes, just do:
> `yarn dist {package format}`
> for instance: `yarn dist rpm` or `yarn dist deb`.
> 
> For questions please use discussions or ask on discord.
> 
> What package format does mageia uses btw?

rpm but i want to make some changes, by example not put in /opt , i generate with success a linux-unpacked dir
and i can do the necessary in the spec to install the files where i need

For the moment i unpack and repack your rpm, but i want to make a package building from sources

**Comment by katnatek** [comment]
I found it, in package.json i add --dir after --linux.
Thank you for the attention and sorry for wrong place this
