### ISSUE TITLE
Doesn't show installed games from 2 different directories [Win 10]

### ISSUE THREAD

**Issue by dephunk** [Heroic-Games-Launcher/HeroicGamesLauncher#608]
**Is your feature request related to a problem? Please describe.**
I have games installed both on C: and D: drive, but only 1 can be selected in Heroic settings.

**Describe the solution you'd like**
Being able to choose more than 1 directory to install games to.

**Comment by Razuuu** [comment]
+1

**Comment by flavioislima** [comment]
What do you guys mean? You can choose wherever directory to install your games.
The settings its only for the DEFAULT one, but you can choose: INSTALL ON ANOTHER PATH. And choose any place.
