### ISSUE TITLE
Heroic launcher doesn't open properly

### ISSUE THREAD

**Issue by maceonik** [Heroic-Games-Launcher/HeroicGamesLauncher#609]
After installing it, putting the code etc  it opens to the game library but only for a few seconds. The games dissapear and the screen stays purple. Refreshing it fixes this, but again, only for a few seconds. Turn the computer on and off, the behavior didn't change. Initially the program worked properly without issues, but this started happened when I "purchased" one of the current free games on the Epic Store. Also I also have the Epic Games Launcher installed, didn't want to unistall it until making sure I got this launcher working. Mentioning it in case it causes conflicts. 

- OS: Windows 10 Pro
- Version: 10.0.19042

**Comment by flavioislima** [comment]
Try the Portable version, the setup one has a bug. 
Also, there is no issue in having the EGS installed, you can even synchronize the installed games between heroic and EGS

**Comment by fatfop** [comment]
This happens to me too, and I've tried the setup exe and the normal exe.

**Comment by flavioislima** [comment]
@fatfop and @maceonik 
try running heroic from terminal and check the logs. Follow these steps:
https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/wiki/Troubleshooting#running-heroic-from-terminalpowershell-to-debug-errors
