### ISSUE TITLE
Anno 1800 not launching

### ISSUE THREAD

**Issue by MathieuMQc** [Heroic-Games-Launcher/HeroicGamesLauncher#613]
**Describe the bug**
Nothings happens when I try to play Anno1800. I click on play when installed but doesn't do nothing.

**Expected behavior**
Should install Ubisoft software and play the game.

**Desktop (please complete the following information):**

- OS: Pop OS 21.04
- Game: Anno 1800
- Wine/Proton version: Proton-6.14-GE-2
- Hardware specs (RAM, CPU, GPU): Ryzen 7 3800x, radeon 6800xt, 64gb 3600 ram.

Thanks a lot for the great software !!

**Comment by adityaruplaha** [comment]
UPlay isn't supported yet. And probably won't be in the near future, but we do wanna get to it eventually.

**Comment by flavioislima** [comment]
Hi! For Game support try our discord: https://discord.gg/Ba3UBPYH

Github should be used for issues with Heroic itself.
