### ISSUE TITLE
Integrate an Epic login into the app (but not directly)

### ISSUE THREAD

**Issue by dragonDScript** [Heroic-Games-Launcher/HeroicGamesLauncher#614]
**Is your feature request related to a problem? Please describe.**
The current SID implementation is confusing.
**Describe the solution you'd like**
An epic login, but outside Heroic (so open epic login in a browser) and then redirect to heroic with our protocol (heroic://login/SID) automatically. So the user only needs to login and that's it!

**Describe alternatives you've considered**
None

**Additional context**
See #42

**Comment by ArjixWasTaken** [comment]
It's pretty simple.
When the user clicks to login you will open the auth page on the browser and launch a local server that will wait for the redirect to send the data over.
Once the data is received in-app you can close the local server and that's all.

**Comment by dragonDScript** [comment]
> It's pretty simple.
> When the user clicks to login you will open the auth page on the browser and launch a local server that will wait for the redirect to send the data over.
> Once the data is received in-app you can close the local server and that's all.
> 
> There is no need for a custom protocol.

launching a local server is a security risk

**Comment by arielj** [comment]
I was looking into this. I tried adding a heroic://... url for the redirectUrl parameter of the login url but epic does not allow custom urls there

![image](https://user-images.githubusercontent.com/188464/140252418-3ac66c3a-b9f8-4b9e-913c-7c117b75b6cb.png)

unless I'm missing something


I'm also not sure I understand the idea of the local server either



what about opening the login url but in a webview inside the app? then we can use the webview events (https://www.electronjs.org/docs/latest/api/webview-tag/#event-did-stop-loading for example) to know when it finished doing something and then we inspect the content to look for the sid?

**Comment by derrod** [comment]
The only real way of doing this (since you need the credentials of the "real" launcher) is to embed the login. Doing so requires a few things to be added to the `window` object so the website thinks it's being opened within the launcher.

See what I did for legendary for reference: https://github.com/derrod/legendary/blob/master/legendary/utils/webview_login.py

**Comment by dragonDScript** [comment]
> I was looking into this. I tried adding a heroic://... url for the redirectUrl parameter of the login url but epic does not allow custom urls there
> 
> ![image](https://user-images.githubusercontent.com/188464/140252418-3ac66c3a-b9f8-4b9e-913c-7c117b75b6cb.png)
> 
> unless I'm missing something
> 
> I'm also not sure I understand the idea of the local server either
> 
> what about opening the login url but in a webview inside the app? then we can use the webview events (https://www.electronjs.org/docs/latest/api/webview-tag/#event-did-stop-loading for example) to know when it finished doing something and then we inspect the content to look for the sid? though it will require the user to login in the webview and if you use something like login with google you then need to login with google too, which is not ideal

When we have the website ready we can have a redirect URL.

**Comment by derrod** [comment]
No you can't. Because any URL that's not epic's own domain won't work.

**Comment by dragonDScript** [comment]
> No you can't. Because any URL that's not epic's own domain won't work.

Are you sure?

**Comment by derrod** [comment]
Yes, just try it: https://www.epicgames.com/id/login?redirectUrl=https://notanepicdomain.com/redirect

**Comment by no95typem** [comment]
Hello everyone! What is really confusing on my opinion, it is the fact that for successful login we need only one value from authenticated browser!
And where is security? MFA for example? 
No offense! It's not legendary or this launcher problem! I just think about security of my epic account in general after that...
Or my cautions are wrong and sid can't be used on another pc? I just can't understand then how it works. For now, for me it looks like MFA is completely useless and epic doesn't check app that uses token (sid).

**Comment by dragonDScript** [comment]
> Hello everyone! What is really confusing on my opinion, it is the fact that for successful login we need only one value from authenticated browser! And where is security? MFA for example? No offense! It's not legendary or this launcher problem! I just think about security of my epic account in general after that... Or my cautions are wrong and sid can't be used on another pc? I just can't understand then how it works. For now, for me it looks like MFA is completely useless and epic doesn't check app that uses token (sid).

SID is pretty much secure. You can only download your games that are in the library already. No payment, auth, etc.

**Comment by derrod** [comment]
> Hello everyone! What is really confusing on my opinion, it is the fact that for successful login we need only one value from authenticated browser! And where is security? MFA for example? No offense! It's not legendary or this launcher problem! I just think about security of my epic account in general after that... Or my cautions are wrong and sid can't be used on another pc? I just can't understand then how it works. For now, for me it looks like MFA is completely useless and epic doesn't check app that uses token (sid).

An SID can only be used once, after that it's invalid, it is also not stored anywhere. The API session created by the Epic Launcher/Legendary can also not be used to create another SID (although it can be used to create more API sessions, which is used for games). The API authentication cannot be used to make any changes to the account.

**Comment by flavioislima** [comment]
> I was looking into this. I tried adding a heroic://... url for the redirectUrl parameter of the login url but epic does not allow custom urls there
> 
> ![image](https://user-images.githubusercontent.com/188464/140252418-3ac66c3a-b9f8-4b9e-913c-7c117b75b6cb.png)
> 
> unless I'm missing something
> 
> I'm also not sure I understand the idea of the local server either
> 
> what about opening the login url but in a webview inside the app? then we can use the webview events (https://www.electronjs.org/docs/latest/api/webview-tag/#event-did-stop-loading for example) to know when it finished doing something and then we inspect the content to look for the sid? though it will require the user to login in the webview and if you use something like login with google you then need to login with google too, which is not ideal

I'm trying this approach and it worked fine once, but now it doesn't.
I mean, I load the webview, login on epic website, then it shows the Object with the SID.
Then I used the webview function selectAll to select the content, then it was selecting the whole text, then I copied it, then get the content from clipboard and parse it to be a JSON.
with that, I get the sid and call legendary auth with it.
It worked fine once, but now, for some F@#$ reason, the selectAll function is selecting everything since Heroic, not only the content inside the webview.

Then, I tried to use the find function to pass a Regex to select everything inside the `{}`, but this function only accepts strings 🤦🏽 

so, I'll start from scratch on that and try to use a different approach.

**Comment by flavioislima** [comment]
Good news!
I noticed that the problem was that the webview was losing focus after redirecting so `webview.focus()` did the trick 🎉
