### ISSUE TITLE
Watch Dogs 2 does not install correctly

### ISSUE THREAD

**Issue by Voidwalker60** [Heroic-Games-Launcher/HeroicGamesLauncher#617]
**Describe the bug**
Watch Dogs 2 does not install, instead imports

**To Reproduce**

1. Open Heroic
2. Try to install Watch Dogs 2
3. Choose install folder
4. Imports Instead of downloading

- OS: Arch Linux
- Version: 1.9.2-1
- Hardware specs (RAM, CPU, GPU):16GB Ram, Intel i5-10400, NVIDIA GeForce GTX 1060 3GB

**Comment by flavioislima** [comment]
Yes, it's not supported by legendary. I'll add it to the not supported list. This is legendary's output:
```
[cli] INFO: Installation requirements check returned the following results:
[cli] WARNING: This game requires launching via Uplay, it is recommended to install the game via Uplay instead.
[cli] WARNING: This game requires linking to and activating on a Ubisoft account first, this is not currently supported.
[cli] CRITICAL: This game requires installation via Uplay and does not ship executable game files.
[cli] ERROR: Installation cannot proceed, exiting.
```

I don't know if first you need to open the official EPIC store using lutris, for instance, then installing uplay on the same prefix. Running the game from there and then activating it on uplay. After that, install the game using uplay and make it run. After that, Launching should work from Heroic, but I haven't tried.

**Comment by flavioislima** [comment]
also, this informations is on the first page of our WIKI: https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/wiki#which-games-does-heroic-not-support
