### ISSUE TITLE
[Feature Request] multiaccount login

### ISSUE THREAD

**Issue by Taza53** [Heroic-Games-Launcher/HeroicGamesLauncher#62]
[Feature Request] Login to a second epic games account without login out.

**Comment by flavioislima** [comment]
Not sure about that, legendary does not support it.

Theoretically, I could keep two legendary folders and then move them when changing accounts. But not sure if this is the best way to do that 🤔

**Comment by adityaruplaha** [comment]
Basically this would require implementing multiple legendary configs.

**Comment by flavioislima** [comment]
Won't do.

**Comment by Superanton** [comment]
I can understand that this has no priority, but I have two amazon accounts with different games, so multiaccount would be handy.

**Comment by builder-main** [comment]
Yup multiple account for Epic here too.
