### ISSUE TITLE
Window becomes blank when typing '\' on the search bar.

### ISSUE THREAD

**Issue by rafalb8** [Heroic-Games-Launcher/HeroicGamesLauncher#620]
**Describe the bug**
Writing backslash symbol '\\' in search bar, clears window. Backspace doesn't fix window. Buttons: Library, Settings, etc. disappear. 

**To Reproduce**

1. Go to 'Library'
2. Write in search bar '\\' 
3. See error

**Expected behavior**
Game with backslash in game title or empty list. 

**Screenshots**
Before:
![Screenshot from 2021-08-17 19-37-23](https://user-images.githubusercontent.com/19816812/129774474-471b493e-b8fb-4ea3-a6cf-70d29a9ac79c.png)

After:
![Screenshot from 2021-08-17 19-37-28](https://user-images.githubusercontent.com/19816812/129774532-55197de2-04e3-4e7a-a803-2c82736446d3.png)

**Desktop (please complete the following information):**

- OS: Arch Linux
- Version: Heroic Launcher from AUR, 1.9.2-1

**Comment by flavioislima** [comment]
Fixed upstream
