### ISSUE TITLE
Korean Translation Issue

### ISSUE THREAD

**Issue by BraINstinct0** [Heroic-Games-Launcher/HeroicGamesLauncher#624]
Trying to translate HGL to Korean (might take long, tho.).
But as in https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/discussions/408, it says that it's locked. Is there any workaround/issues related to this, or should I just wait for it to unlock?

**Comment by BraINstinct0** [comment]
UPDATE: This seems to be an issue affecting _all languages_ of HGL over at Weblate.
```
Could not merge the repository.
Weblate could not merge upstream changes while updating the repository.

Auto-merging public/locales/uk/translation.json
CONFLICT (add/add): Merge conflict in public/locales/uk/translation.json
Auto-merging public/locales/uk/login.json
CONFLICT (add/add): Merge conflict in public/locales/uk/login.json
Auto-merging public/locales/uk/gamepage.json
CONFLICT (add/add): Merge conflict in public/locales/uk/gamepage.json
Automatic merge failed; fix conflicts and then commit the result.
 (1)
```

**Comment by flavioislima** [comment]
Hi!
Yes, got some conflicts on weblate but they are fixed now. 

Thanks for helping translating heroic :)
