### ISSUE TITLE
Heroic Kills User Session

### ISSUE THREAD

**Issue by coodos** [Heroic-Games-Launcher/HeroicGamesLauncher#626]
**Describe the bug**
Heroic Games launcher kills my user session when I interact with the UI, I am taken back to my login screen

**To Reproduce**
1. Click on any game to install
2. Choose a folder 
3. once I have chosen a folder and click any button my user session is immediately killed

**Expected behavior**
Nothing should happen and it should work

**Desktop (please complete the following information):**

- OS: Arch linux
- Version Kernel 5.12.12
- Game: All games cause this
- Wine/Proton version: 
- Hardware specs (RAM, CPU, GPU): 16GB Ram, Ryzen 7 2700x, Rx 570 graphics card

**Comment by coodos** [comment]
something to mention though is that I use XMonad as my tiling window manager

**Comment by flavioislima** [comment]
HI!
I have no idea on what might be happening and I don't have a distro with Xmonad to test. 
Try running heroic from the terminal and check if it outputs come logs.
For a specific issue like that is better to get help on our discord.
Also, try on other distros or other Window managers to check if this will happen.

Its really hard for us to test and debug on every distro configuration out there so we test on Arch based like Manjaro, Garuda with KDE and GNOME and Ubuntu and derivatives like POP_OS.
