### ISSUE TITLE
Heroic launches into a blank screen at startup((Versions 1.8.2+))

### ISSUE THREAD

**Issue by BahaaElboraey** [Heroic-Games-Launcher/HeroicGamesLauncher#627]
![Screenshot 2021-08-20 160340](https://user-images.githubusercontent.com/34317159/130245440-93da5f87-ade3-45ce-9096-6b3a606d3cb5.png)
lp.

**Comment by flavioislima** [comment]
HI. Please use the template when opening an issue. We don't have time to be guessing operating system or any other thing that might be happening with you. Leave to us as much information as possible and everything that you have tried.
If on windows, try the portable version first before opening an issue.
