### ISSUE TITLE
Feature Request: Download Manager

### ISSUE THREAD

**Issue by EndlessEden** [Heroic-Games-Launcher/HeroicGamesLauncher#631]
**Is your feature request related to a problem? Please describe.**
A lack of a Download Manager, means its impossible to tell what is currently downloading, what is currently queued and no way to manipulate the queue.

**Describe the solution you'd like**
A download management page, something similiar to what Steam offers would be ideal. With net/disk rate information, Queue list, pause/start option and list of failed/successfully installed games(recent)

**Comment by FunMLG** [comment]
Love the idea ! I need it too

**Comment by aha999** [comment]
I'm specially interested in the data flow, how much data the update process is consuming...

**Comment by flavioislima** [comment]
just noticed that this is a duplicate of #457
