### ISSUE TITLE
Can't disable "Check for updates on startup" through GUI

### ISSUE THREAD

**Issue by Shotweb** [Heroic-Games-Launcher/HeroicGamesLauncher#632]
When I toggle "Check for updates on startup" in Settings, it doesn't save. When I leave settings and go in there again, it is enabled again. It also doesn't actually change it in config.json. I have now set it manually to false in config.json, but it still comes up as enabled in Settings. I guess I will find out when the next version is released if it has actually disabled it.

This is on Heroic 1.9.2 on Debian 11.

**Comment by flavioislima** [comment]
That's weird. Just tried here on 1.9.2 and it works. Since we have 1.9.3 now I could test it and I disabled the check updates on settings, restarted Heroic and I didn't get the update.
Also, on the terminal I get the info:
`INFO: skipping heroic updates`

So I'm not sure what's happening on your machine but try to update to 1.9.3 now to check if the setting is saved.

**Comment by Shotweb** [comment]
I just got the pop-up for 1.9.3, so disabling it in the config.json didn't work. And it still doesn't save when I disable it in the GUI.

**Comment by hollowleviathan** [comment]
I also experience this, on 1.10.3 Kizaru. Disabling this option in the GUI, then navigating away from and back to the options, it's enabled again, and I get popups for that game updating

**Comment by flavioislima** [comment]
@hollowleviathan @Shotweb 
Quick question, do you guys mean GAMES updates or HEROIC updates?
Because this toggle is to check for HEROIC updates, not games.

**Comment by Shotweb** [comment]
I was talking about updates for Heroic.

**Comment by hollowleviathan** [comment]
I misunderstood what the setting did, sorry, but it still doesn't disable for me when I tried to turn it off.

**Comment by cachandlerdev** [comment]
I can confirm that this issue still exists. Here's a short clip demonstrating the problem.

https://user-images.githubusercontent.com/70250943/152922063-a7be5b18-a7e9-4c1d-84d0-3fcd059af410.mp4

**Comment by redromnon** [comment]
This issue has been fixed - #980
