### ISSUE TITLE
When launching game i get box.error (en)

### ISSUE THREAD

**Issue by poopman97** [Heroic-Games-Launcher/HeroicGamesLauncher#633]
### Try to get help on our Wiki first: https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/wiki/Troubleshooting

**Describe the bug**
When i try to launch a game with proton it just says box.error (en)

**To Reproduce**
I don't know how to reproduce.

1. Go to 'settings'
2. Click on 'proton (any version)'
3. Launch game

**Expected behavior**
i expected the game to launch

**Screenshots**
![Screenshot_20210829_183139](https://user-images.githubusercontent.com/81973468/131258005-47a08517-8ec8-4899-bc01-452a9accdf28.jpeg)

**Desktop (please complete the following information):**

- OS: [Kubuntu]
- Version [21.04]
- Game: Dark siders II Deathinitive edition
- Wine/Proton version: Proton-6.16-GE-1
- Hardware specs (RAM, CPU, GPU): ram: 16gb ddr4 cpu: 1th Gen Intel Core i7-1165G7 gpu: Nvidia Geforce mx450

**Additional context**
Here is the log:

´[Core] WARNING: Could not determine locale, falling back to en-US
[cli] INFO: Logging in...
[Core] INFO: Trying to re-use existing login session...
[cli] INFO: Checking for updates...
[Core] INFO: Getting authentication token...
[cli] INFO: Launching Hoki...
Proton: Upgrading prefix from None to 6.16-GE-1 (/home/vidak/.wine/)
Traceback (most recent call last):
  File "/home/vidak/.config/heroic/tools/proton/Proton-6.16-GE-1/proton", line 1472, in <module>
    g_session.init_session(sys.argv[1] != "runinprefix")
  File "/home/vidak/.config/heroic/tools/proton/Proton-6.16-GE-1/proton", line 1255, in init_session
    g_compatdata.setup_prefix()
  File "/home/vidak/.config/heroic/tools/proton/Proton-6.16-GE-1/proton", line 888, in setup_prefix
    self.update_builtin_libs(builtin_dll_copy)
  File "/home/vidak/.config/heroic/tools/proton/Proton-6.16-GE-1/proton", line 547, in update_builtin_libs
    with open(self.tracked_files_file, "r") as tracked_files:
FileNotFoundError: [Errno 2] No such file or directory: '/home/vidak/.wine/tracked_files'`

**Comment by flavioislima** [comment]
HI, this is a game issue, please go to our discord to get help about it.
The error box there is with some translation issue, but the game is being launched. Try WINE-GE instead of proton, try wine staging wth DXVK, anyway. Or go to our Discord.
