### ISSUE TITLE
Can't log in to Heroic Game Launcher

### ISSUE THREAD

**Issue by kjvi** [Heroic-Games-Launcher/HeroicGamesLauncher#637]
https://i.imgur.com/chridWs.png

Just let me know what should I do to provide more info. Sorry I am new.

I am on Arch and I was playing before this happened, it says my login is expired and asked for the sid code again which I did and now it is not letting me, just says error and this is the first time I experienced this.

Before when this happened I can just login again without any problems. Hope someone can help.

**Comment by kjvi** [comment]
[https://imgur.com/a/nwlkErJ](url)

Just let me know what should I do to provide more info. Sorry I am new.

**Comment by flavioislima** [comment]
Yes, we are aware of that. Epic changed their API so we need a fix from the Legendary team and then release a new version of Heroic with it.
Wait for a new Heroic release as soon as this is fixed.

**Comment by kjvi** [comment]
I see, thank you very much for your reply and hopefully this gets fixed soon, because I don't want to install Lutris just for Epic Games Store hehe.

**Comment by flavioislima** [comment]
Ok, fixed on new release. Check it out!

**Comment by kjvi** [comment]
> Ok, fixed on new release. Check it out!

Yes, I confirm that it is fixed. Thank you very much.

**Comment by flavioislima** [comment]
NIce!
