### ISSUE TITLE
(MacOS) Heroic being stucked at login - Heroic 1.9.3

### ISSUE THREAD

**Issue by Albertamere** [Heroic-Games-Launcher/HeroicGamesLauncher#642]
When I open Heroic, i clic on "Epic Store Here" I copy my SID (it changes everytime i click on the link and there's an error message. is this normal ? : 

![Screen Shot 2021-09-05 at 03 36 36](https://user-images.githubusercontent.com/71387711/132112078-66de0d7b-47b1-4e40-8dc3-3a3e38bf555a.png) ),
paste it, and then click on login. 
There, it get stuck : 

![Screen Shot 2021-09-05 at 03 37 32](https://user-images.githubusercontent.com/71387711/132112953-56d44afe-2b38-497a-a503-927d4153962f.png)

When i run it through the terminal : 
![Screen Shot 2021-09-05 at 03 45 53](https://user-images.githubusercontent.com/71387711/132112205-450056bf-86da-4d07-ba3f-70793781b1fa.png)

OS : Mac OS El Capitan 10.11.6
Heroic  1.9.3
Intel Core i7 ~3,5 GHz
GTX 750 Ti

Thx

**Comment by OmegaMetor** [comment]
I am having this exact problem on a macos 11.4 m1 device using the same app version.

**Comment by Endle** [comment]
I'musing macM1 and I hit this issue too.
I failed to login with both 1.9.2 and 1.9.3

**Comment by wickedfunges9** [comment]
have the same issue

**Comment by flavioislima** [comment]
Hmm. 🤔
I tested only on a mac Pro 2019 with Intel. And I have compiled the legendary binary on it so I'm not sure if it will work on M1.
I'm not sure also if heroic will work on old mac versions like 10.11 we just tested on 10.14 and 10.15.
One idea is for you guys to compile legendary yourselves, the instructions are on their github. And replace the current binary that comes with heroic. You can find it on the asar unpack folder that is on the Heroic folder under applications folder.

If this works, then we will need to distribute a different binary but that would be complicated.

Also, heroic 1.9.2 won't work for login because epic has changed their login api and this was fixed on latest legendary version that is the one Heroic uses on 1.9.3.

So let me know if you need further help compiling legendary but it's basically 3 command lines if you have git and python 3.8+ installed with pip3 as well.

**Comment by Albertamere** [comment]
> One idea is for you guys to compile legendary yourselves, the instructions are on their github. And replace the current binary that comes with heroic. 

I'll try this thx

**Comment by Albertamere** [comment]
I didn't make it to work so ... if anyone has another solution ? Maybe i'll try to run legendary on it's own
thx anyway

**Comment by wickedfunges9** [comment]
legendery is not supported on Mac 
i try it and it don' t work with legendery

**Comment by Albertamere** [comment]
i know but did not the devs make a compatible version ? If not, why there's a HGL.dmg ?

**Comment by flavioislima** [comment]
> i know but did not the devs make a compatible version ? If not, why there's a HGL.dmg ?

That's different. Legendary doesn't support Macos. 
But Heroic runs on Mac with a legendary binary compiled on a mac. It wasn't my idea to create it and the person who started it disappeared. 

But I keep releasing it and I test on a Intel mac book pro with macOS 10.14 and it runs fine. But I have no way to test on all mac versions and on a M1 and we have just a few users that uses the mac version and fewer that goes to our discord to help us improve heroic for mac.

So here is what I'm going to do: I'll change the Heroic read me and say we support only Mac OS X running Intel and version 10.14. So it might or not work on other versions. But if it stops working for good I'll simple drop support for Mac from next version.

**Comment by flavioislima** [comment]
@Albertamere looking at the terminal, might be that your issue is that the legendary binary is not set as executable.
Can you run `chmod +x path/to/legendary` And see if it works? Because that ENOENT error might be file not found but also might be not executable permissions.

**Comment by flavioislima** [comment]
> > One idea is for you guys to compile legendary yourselves, the instructions are on their github. And replace the current binary that comes with heroic.
> 
> I'll try this thx
> 
> If i've undestand, have to :
> go to Heroic/Contents/Ressource/app.asar.unpacked/ and delete "build" and then compile legendary ?

No. Just replace the legendary binary with the compiled one. But check the exec permissions first.

**Comment by wickedfunges9** [comment]
> > > One idea is for you guys to compile legendary yourselves, the instructions are on their github. And replace the current binary that comes with heroic.
> > 
> > 
> > I'll try this thx
> > If i've undestand, have to :
> > go to Heroic/Contents/Ressource/app.asar.unpacked/ and delete "build" and then compile legendary ?
> 
> No. Just replace the legendary binary with the compiled one. But check the exec permissions first.

it work first but one .3 it don't work

**Comment by Cooldude069** [comment]
I just tried a few things on my M1 MacBook Air and heroic started working like a charm.

First install python 3 on your MacBook. You can just google it and install it.
Once installed, download the(zip file) source code of legendary from [here](https://github.com/derrod/legendary/releases)

extract the zip file into a folder and then open the folder in your terminal. You can do this by typing "cd " and then dragging and dropping the folder into your terminal. It will show up as a path in your terminal. Press return.

Once this is done, type "pip3 install ." in the terminal and hit return. This might take some time.

now once it is over, type "which legendary" in the terminal. It will show you the path to legendary. go to that path in Finder and copy the legendary binary/executable. 

Now go to /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin 

here you will find the legendary binary/executable. Delete it and paste the legendary executable you just copied.

Now launch heroic and it should log in.

Hope this helps!

**Comment by flavioislima** [comment]
> I just tried a few things on my M1 MacBook Air and heroic started working like a charm.
> 
> First install python 3 on your MacBook. You can just google it and install it.
> Once installed, download the(zip file) source code of legendary from [here](https://github.com/derrod/legendary/releases)
> 
> extract the zip file into a folder and then open the folder in your terminal. You can do this by typing "cd " and then dragging and dropping the folder into your terminal. It will show up as a path in your terminal. Press return.
> 
> Once this is done, type "pip3 install ." in the terminal and hit return. This might take some time.
> 
> now once it is over, type "which legendary" in the terminal. It will show you the path to legendary. go to that path in Finder and copy the legendary binary/executable.
> 
> Now go to /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin
> 
> here you will find the legendary binary/executable. Delete it and paste the legendary executable you just copied.
> 
> Now launch heroic and it should log in.
> 
> Hope this helps!

Nice!
I'll add this to our Troubleshooting guide on our Wiki. Everyone that has the same issue with any MacOS version might need to do that to compile legendary to that exact version.

**Comment by FadedController** [comment]
> I just tried a few things on my M1 MacBook Air and heroic started working like a charm.
> 
> First install python 3 on your MacBook. You can just google it and install it.
> Once installed, download the(zip file) source code of legendary from [here](https://github.com/derrod/legendary/releases)
> 
> extract the zip file into a folder and then open the folder in your terminal. You can do this by typing "cd " and then dragging and dropping the folder into your terminal. It will show up as a path in your terminal. Press return.
> 
> Once this is done, type "pip3 install ." in the terminal and hit return. This might take some time.
> 
> now once it is over, type "which legendary" in the terminal. It will show you the path to legendary. go to that path in Finder and copy the legendary binary/executable.
> 
> Now go to /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin
> 
> here you will find the legendary binary/executable. Delete it and paste the legendary executable you just copied.
> 
> Now launch heroic and it should log in.
> 
> Hope this helps!

Hey there! Just confirming this worked and solved the issue on a M1 MacBook Air (8gb / 256gb)

Thanks for your help!

**Comment by bruhshedBred** [comment]
> I just tried a few things on my M1 MacBook Air and heroic started working like a charm.
> 
> First install python 3 on your MacBook. You can just google it and install it.
> Once installed, download the(zip file) source code of legendary from [here](https://github.com/derrod/legendary/releases)
> 
> extract the zip file into a folder and then open the folder in your terminal. You can do this by typing "cd " and then dragging and dropping the folder into your terminal. It will show up as a path in your terminal. Press return.
> 
> Once this is done, type "pip3 install ." in the terminal and hit return. This might take some time.
> 
> now once it is over, type "which legendary" in the terminal. It will show you the path to legendary. go to that path in Finder and copy the legendary binary/executable.
> 
> Now go to /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin
> 
> here you will find the legendary binary/executable. Delete it and paste the legendary executable you just copied.
> 
> Now launch heroic and it should log in.
> 
> Hope this helps!

Hey, i tried this after 1.9.3 was stuck at login but I can't seem to get the "pip3 install" part right.
It says it needs at least one requirement to install, I don't understand what it means could someone help.
Thanks.

**Comment by Cooldude069** [comment]
> > I just tried a few things on my M1 MacBook Air and heroic started working like a charm.
> > First install python 3 on your MacBook. You can just google it and install it.
> > Once installed, download the(zip file) source code of legendary from [here](https://github.com/derrod/legendary/releases)
> > extract the zip file into a folder and then open the folder in your terminal. You can do this by typing "cd " and then dragging and dropping the folder into your terminal. It will show up as a path in your terminal. Press return.
> > Once this is done, type "pip3 install ." in the terminal and hit return. This might take some time.
> > now once it is over, type "which legendary" in the terminal. It will show you the path to legendary. go to that path in Finder and copy the legendary binary/executable.
> > Now go to /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin
> > here you will find the legendary binary/executable. Delete it and paste the legendary executable you just copied.
> > Now launch heroic and it should log in.
> > Hope this helps!
> 
> Hey, i tried this after 1.9.3 was stuck at login but I can't seem to get the "pip3 install" part right.
> It says it needs at least one requirement to install, I don't understand what it means could someone help.
> Thanks.

The command is "pip3 install ." i guess you forgot the period. Try it and tell me if it doesn't work.

**Comment by Gentlyr** [comment]
> > I just tried a few things on my M1 MacBook Air and heroic started working like a charm.
> > First install python 3 on your MacBook. You can just google it and install it.
> > Once installed, download the(zip file) source code of legendary from [here](https://github.com/derrod/legendary/releases)
> > extract the zip file into a folder and then open the folder in your terminal. You can do this by typing "cd " and then dragging and dropping the folder into your terminal. It will show up as a path in your terminal. Press return.
> > Once this is done, type "pip3 install ." in the terminal and hit return. This might take some time.
> > now once it is over, type "which legendary" in the terminal. It will show you the path to legendary. go to that path in Finder and copy the legendary binary/executable.
> > Now go to /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin
> > here you will find the legendary binary/executable. Delete it and paste the legendary executable you just copied.
> > Now launch heroic and it should log in.
> > Hope this helps!
> 
> Hey, i tried this after 1.9.3 was stuck at login but I can't seem to get the "pip3 install" part right.
> It says it needs at least one requirement to install, I don't understand what it means could someone help.
> Thanks.



Can you show me how to resolve this problem,can you do it on video?

**Comment by wickedfunges9** [comment]
> > I just tried a few things on my M1 MacBook Air and heroic started working like a charm.
> > First install python 3 on your MacBook. You can just google it and install it.
> > Once installed, download the(zip file) source code of legendary from [here](https://github.com/derrod/legendary/releases)
> > extract the zip file into a folder and then open the folder in your terminal. You can do this by typing "cd " and then dragging and dropping the folder into your terminal. It will show up as a path in your terminal. Press return.
> > Once this is done, type "pip3 install ." in the terminal and hit return. This might take some time.
> > now once it is over, type "which legendary" in the terminal. It will show you the path to legendary. go to that path in Finder and copy the legendary binary/executable.
> > Now go to /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin
> > here you will find the legendary binary/executable. Delete it and paste the legendary executable you just copied.
> > Now launch heroic and it should log in.
> > Hope this helps!
> 
> Hey, i tried this after 1.9.3 was stuck at login but I can't seem to get the "pip3 install" part right.
> It says it needs at least one requirement to install, I don't understand what it means could someone help.
> Thanks.

same

**Comment by flavioislima** [comment]
Like he said above, the correct command is:
`pip3 install .`
And not:
`pip3 install`

check the period.

After it install Legendary, just copy the binary with:
`cp -fv /usr/local/bin/legendary /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/ `

**Comment by wickedfunges9** [comment]
> You can try this first:
> `chmod +x cp -fv /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/legendary`
> 
> If it doesn't work, do like the comment above but the right command is
> `pip3 install .`
> And not:
> `pip3 install`
> 
> check the period.
> 
> After it install Legendary, just copy the binary with:
> `cp -fv /usr/local/bin/legendary /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/`

it not works I think it s with my python3 that it not work.

**Comment by flavioislima** [comment]
> > You can try this first:
> > `chmod +x cp -fv /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/legendary`
> > If it doesn't work, do like the comment above but the right command is
> > `pip3 install .`
> > And not:
> > `pip3 install`
> > check the period.
> > After it install Legendary, just copy the binary with:
> > `cp -fv /usr/local/bin/legendary /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/`
> 
> it not works I think it s with my python3 that it not work.

The first command didn't work?

**Comment by flavioislima** [comment]
I've updated the DMG file with different permissions. Download it again from the releases page and let me know if it works.

**Comment by Gentlyr** [comment]
> I've updated the DMG file with different permissions. Download it again from the releases page and let me know if it works.

I just try it and it the same Loggin in problem

**Comment by flavioislima** [comment]
@Cooldude069 can you drop here the legendary binary so others can use it instead of compiling it? if it works fine I can update the DMG later with yours since the one I'm building is not working.

**Comment by syto203** [comment]
check this one syto203@7bcfa1b
it should support Apple Silicon along with Intel
OR
this one is for Apple Silicon ONLY syto203@40b41ce

unless the tester knows how to check if the running binary is Intel or Apple then just try the second one.

instructions to run:
1. Download this https://github.com/syto203/HeroicGamesLauncher/raw/40b41cef51e15cbb7c8e6f7863fae2b4bc524ae1/public/bin/darwin/legendary
2. open Terminal and run the following one by one
```
cd ~/Downloads
chmod +x legendary
./legendary
```
3. if it doesn't produce an error then it worked.

**Comment by flavioislima** [comment]
Thanks, @syto203 .
If it works, just copy the binary like this:
`cp -fv legendary /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/`

**Comment by Cooldude069** [comment]
> > > I just tried a few things on my M1 MacBook Air and heroic started working like a charm.
> > > First install python 3 on your MacBook. You can just google it and install it.
> > > Once installed, download the(zip file) source code of legendary from [here](https://github.com/derrod/legendary/releases)
> > > extract the zip file into a folder and then open the folder in your terminal. You can do this by typing "cd " and then dragging and dropping the folder into your terminal. It will show up as a path in your terminal. Press return.
> > > Once this is done, type "pip3 install ." in the terminal and hit return. This might take some time.
> > > now once it is over, type "which legendary" in the terminal. It will show you the path to legendary. go to that path in Finder and copy the legendary binary/executable.
> > > Now go to /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin
> > > here you will find the legendary binary/executable. Delete it and paste the legendary executable you just copied.
> > > Now launch heroic and it should log in.
> > > Hope this helps!
> > 
> > 
> > Hey, i tried this after 1.9.3 was stuck at login but I can't seem to get the "pip3 install" part right.
> > It says it needs at least one requirement to install, I don't understand what it means could someone help.
> > Thanks.
> 
> Can you show me how to solve this problem,can you do it on video?



> > > I just tried a few things on my M1 MacBook Air and heroic started working like a charm.
> > > First install python 3 on your MacBook. You can just google it and install it.
> > > Once installed, download the(zip file) source code of legendary from [here](https://github.com/derrod/legendary/releases)
> > > extract the zip file into a folder and then open the folder in your terminal. You can do this by typing "cd " and then dragging and dropping the folder into your terminal. It will show up as a path in your terminal. Press return.
> > > Once this is done, type "pip3 install ." in the terminal and hit return. This might take some time.
> > > now once it is over, type "which legendary" in the terminal. It will show you the path to legendary. go to that path in Finder and copy the legendary binary/executable.
> > > Now go to /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin
> > > here you will find the legendary binary/executable. Delete it and paste the legendary executable you just copied.
> > > Now launch heroic and it should log in.
> > > Hope this helps!
> > 
> > 
> > Hey, i tried this after 1.9.3 was stuck at login but I can't seem to get the "pip3 install" part right.
> > It says it needs at least one requirement to install, I don't understand what it means could someone help.
> > Thanks.
> 
> Can you show me how to solve this problem,can you do it on video?

 Just try downloading the legendary binary directly from [here](https://github.com/Cooldude069/leg-binary) Copy it and paste it in /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin

**Comment by syto203** [comment]
@Cooldude069 would you mind trying one of the binaries I submitted so it can be pushed.

**Comment by wickedfunges9** [comment]
> > > > I just tried a few things on my M1 MacBook Air and heroic started working like a charm.
> > > > First install python 3 on your MacBook. You can just google it and install it.
> > > > Once installed, download the(zip file) source code of legendary from [here](https://github.com/derrod/legendary/releases)
> > > > extract the zip file into a folder and then open the folder in your terminal. You can do this by typing "cd " and then dragging and dropping the folder into your terminal. It will show up as a path in your terminal. Press return.
> > > > Once this is done, type "pip3 install ." in the terminal and hit return. This might take some time.
> > > > now once it is over, type "which legendary" in the terminal. It will show you the path to legendary. go to that path in Finder and copy the legendary binary/executable.
> > > > Now go to /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin
> > > > here you will find the legendary binary/executable. Delete it and paste the legendary executable you just copied.
> > > > Now launch heroic and it should log in.
> > > > Hope this helps!
> > > 
> > > 
> > > Hey, i tried this after 1.9.3 was stuck at login but I can't seem to get the "pip3 install" part right.
> > > It says it needs at least one requirement to install, I don't understand what it means could someone help.
> > > Thanks.
> > 
> > 
> > Can you show me how to solve this problem,can you do it on video?
> 
> > > > I just tried a few things on my M1 MacBook Air and heroic started working like a charm.
> > > > First install python 3 on your MacBook. You can just google it and install it.
> > > > Once installed, download the(zip file) source code of legendary from [here](https://github.com/derrod/legendary/releases)
> > > > extract the zip file into a folder and then open the folder in your terminal. You can do this by typing "cd " and then dragging and dropping the folder into your terminal. It will show up as a path in your terminal. Press return.
> > > > Once this is done, type "pip3 install ." in the terminal and hit return. This might take some time.
> > > > now once it is over, type "which legendary" in the terminal. It will show you the path to legendary. go to that path in Finder and copy the legendary binary/executable.
> > > > Now go to /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin
> > > > here you will find the legendary binary/executable. Delete it and paste the legendary executable you just copied.
> > > > Now launch heroic and it should log in.
> > > > Hope this helps!
> > > 
> > > 
> > > Hey, i tried this after 1.9.3 was stuck at login but I can't seem to get the "pip3 install" part right.
> > > It says it needs at least one requirement to install, I don't understand what it means could someone help.
> > > Thanks.
> > 
> > 
> > Can you show me how to solve this problem,can you do it on video?
> 
> Just try downloading the legendary binary directly from [here](https://github.com/Cooldude069/leg-binary) Copy it and paste it in /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin

it don't work

**Comment by syto203** [comment]
@wickedfunges9 try one of these https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/issues/642#issuecomment-919585329

**Comment by darus90** [comment]
any solution for appimage?

**Comment by flavioislima** [comment]
> any solution for appimage?

Whats up with the appImage? If you have any trouble go to our discord for quick help. L

**Comment by bruhshedBred** [comment]
> @Cooldude069 would you mind trying one of the binaries I submitted so it can be pushed.

hey, I tried it and it works fine. Thanks man

**Comment by flavioislima** [comment]
Works on my side as well with @syto203 binary (the first one).
So I've updated the release with a new DMG with that binary. 

I do appreciate if you guys can test and then I'll send the binary upstream.
Thanks @syto203 for the help.

**Comment by syto203** [comment]
Np happy to help.

**Comment by Albertamere** [comment]
> @Albertamere looking at the terminal, might be that your issue is that the legendary binary is not set as executable.
> Can you run `chmod +x path/to/legendary` And see if it works? Because that ENOENT error might be file not found but also might be not executable permissions.

i'll test (by the way sorry i was on vacation)

**Comment by flavioislima** [comment]
Closing this since it was fixed.
