### ISSUE TITLE
Can't login from 1.9.3, stuck on logging in

### ISSUE THREAD

**Issue by bruhshedBred** [Heroic-Games-Launcher/HeroicGamesLauncher#645]
**Describe the bug**
After entering SID it keeps spinning saying "logging in" and doesn't progress. No error message is given.

**To Reproduce**

Open Heroic
Follow steps for login
Enter SID and press login
Stuck in logging in loop

**Expected behavior**
-

**Screenshots**
-

**Desktop (please complete the following information):**

- OS: Big Sur
- Version: 11.5.2
- Game:
- Wine/Proton version:
- Hardware specs (RAM, CPU, GPU): 8GB, M1

**Additional context**
Tried using 1.9.2 after uninstalling latest ver. Gives error message after saying "logging in" for a while

**Comment by wickedfunges9** [comment]
same lol

**Comment by wickedfunges9** [comment]
but by me first work it then the update come it don't work anymore

**Comment by flavioislima** [comment]
This is the same as #642 please continue there
