### ISSUE TITLE
Wine Default Not Found

### ISSUE THREAD

**Issue by WyffGoaL** [Heroic-Games-Launcher/HeroicGamesLauncher#649]
Hi everyone,

I'm on macOS Big Sur 11.5.2 and using the 1.9.3 Heroic Games Launcher. But I can't install any games as it says Wine default not found as shown in the screenshot below. Is there anything I need to do other than installing the launcher .dmg file on my Mac?

Your help will be very much appreciated.

Thanks in advance.

![Screenshot 2021-09-14 at 3 18 18 PM](https://user-images.githubusercontent.com/90670790/133213158-23e1c169-580c-476c-b299-a623fa7e1fe6.png)

**Comment by flavioislima** [comment]
Yes. you need Wine or Crossover to run the games on MacOS since those are all Windows Games.
You can get more help on our discord.
