### ISSUE TITLE
Log web logs to main process console

### ISSUE THREAD

**Issue by dragonDScript** [Heroic-Games-Launcher/HeroicGamesLauncher#656]
**Is your feature request related to a problem? Please describe.**
Debugging the renderer process is hard.

**Describe the solution you'd like**
Use the `<BrowserWindow>.webContents` 'console-message' event.

**Describe alternatives you've considered**
An internal logger

**Comment by flavioislima** [comment]
I added a IPC call from the renderer to the main process in the latest versions so now it's easier to debug it. So we might not need this anymore.

**Comment by dragonDScript** [comment]
> I added a IPC call from the renderer to the main process in the latest versions so now it's easier to debug it. So we might not need this anymore.

But what about react errors? They will be logged with console.error (throw)
