### ISSUE TITLE
Legendary config.ini interference

### ISSUE THREAD

**Issue by SimpliFly03** [Heroic-Games-Launcher/HeroicGamesLauncher#659]
**Describe the bug**
config.ini of Legendary interferes with configuration inside of Heroic launcher.

**To Reproduce**

1. Define start_params for any game with contents "-param1 -param2" on config.ini of Legendary.
2. Define "Game Arguments" for the same game on Heroic as "-param3 -param4"
3. Game is launched with "-param1 -param2 -param3 -param4"
4. This may lead unexpected behaviours on game. 
5. Similar problems also happens with other list based settings as well. For the single variable stuff (such as path to wine prefix) the Heroic is straight up ignored. Also, for the environment variable if both contains the same variable with different value the Heroic is ignored and config.ini is used.

**Expected behavior**
I could expect 3 possible things:
1. Being in sync with Legendary config.ini
2. Completely ignoring config.ini
3. Warning the user whenever a game has configuration on config.ini.

**Screenshots**
Not applicable.

**Desktop (please complete the following information):**

- OS: Arch Linux
- Version: Rolling
- Game: Satisfactory (Only realized on that game. Problem is general.)
- Wine/Proton version: wine-tkg-staging-fsync-opt-git 6.17.r10.ga1db1dfc-326
- Hardware specs (RAM, CPU, GPU): 16GB i7-8750H UHD630+GTX1050Ti(Prime Render Offload)

**Additional context**
For example, today Satisfactory got Vulkan update on experimental. However it constantly crashes or if it doesn't crash it ignores any config vulkan related. After digging the logs of the game it turns out in addition to "-vulkan" parameter from the Heroic, "-d3d11" was also coming from the Legendary config.ini. This lead to crash when I put in "-vulkan" or game to ignore in game setting since "-d3d11" is being passed without me knowing.

**Comment by Myricaulus** [comment]
Just for curiosity, have you installed the redist files which came with the update for satisfactory? If yes, how?

**Comment by flavioislima** [comment]
HI.

I understand the issue and ofc you can use legendary along with heroic, that's not an issue, but at the same time would be ideal that you set your parameters on one side only. You can pass other legendary params to the game on the launcher arguments on the game settings. So you can keep it clean on the legendary side and pass the extra ones on heroic. That would be the ideal.
So I don't see this as an issue, it's just we use the settings on one side only to avoid interference.

**Comment by SimpliFly03** [comment]
What I was trying to say is that there should be a warning about potential of an undesired behavior if there is configuration at Legendary config.ini other than the default contents of the file. Sometimes a user might set something there in the past (like before Heroic existed) for a game. However, if a user haven't played that game for a long time and later decided to return to playing it using Heroic, there is a chance that the user might forgot about the existence of the configuration made in the past. Thus, a small reminder would be great for such cases.
