### ISSUE TITLE
Improve support for CrossOver on Mac/Linux

### ISSUE THREAD

**Issue by mrpippy** [Heroic-Games-Launcher/HeroicGamesLauncher#660]
**Is your feature request related to a problem? Please describe.**
I work at CodeWeavers, we would like to make it easier for Heroic to launch games with CrossOver's Wine on Mac and Linux.

**Describe the solution you'd like**
I think the following changes would help with this:
- detect CrossOver installations and list them in the Wine Version dropdown (next to Proton, Lutris, etc.)
- add a setting for the user to specify the "bottle"/prefix for CrossOver to use
- fix any other bugs that arise

I have the first one working, and in-progress on the second. Will create a PR once ready.

**Describe alternatives you've considered**
An alternate method would be to run the Windows version of Heroic inside of Wine, this avoids any need to set up prefixes/Wine installs. Heroic itself runs (with a Wine-side hack needed for CEF), but Legendary is built with an older PyInstaller that doesn't work under Wine. Legendary upstream isn't interested in supporting this usage (https://github.com/derrod/legendary/issues/341)

**Additional context**

**Comment by flavioislima** [comment]
Thanks for the initiative @mrpippy That would be great if it works. I do not play on mac so I don't have a Crossover installation (or wine) to test it. If you could do that would be of great value for Mac users. :)

**Comment by Nocccer** [comment]
Implemented.
