### ISSUE TITLE
Mouse clicks not working

### ISSUE THREAD

**Issue by FranGarc** [Heroic-Games-Launcher/HeroicGamesLauncher#667]
### Try to get help on our Wiki first: https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/wiki/Troubleshooting

**Describe the bug**
When clicking any of the mouse buttons (left/right/center) the cursor dissapears from wherever it was and reappears on top-left corner. If clicked on a button, it does nothing.
This happens in the game Mutant Year Zero and didn't happen before this last update. 

**To Reproduce**

1. Go to  Main Screen on Mutant Year Zero (it's the only game I'm playing on Heroic Launcher and, as stated, worked perfectly up until now)
2. Click on any of the buttons (bottom of the screen)
3. Cursor dissapears and reappears on top left corner of the screen, clicks never get registered by the buttons.

**Expected behavior**
Click should take effect on the buttons, but it doesn't. Not even the exit button.

**Screenshots**

**Desktop (please complete the following information):**

- OS: Manjaro Arch
- Version up-to-date 
- Game: Mutant Year Zero
- Wine/Proton version: wine-6.16
- Hardware specs (RAM, CPU, GPU): 16 DG RAM, AMD Ryzen 5 1500X 3.5GHZ, Nvidia GTX 1060 

**Additional context**
As stated, have been playing this game for quite a time with 0 issues up until last update. I launched the game OK, but couldn't continue/load/new game nor exit since I couldn't click on the buttons.

**Comment by flavioislima** [comment]
Hi.

This is a issue with a game, not heroic. Please read the rules when opening issues. You can have gaming support on our discord.
