### ISSUE TITLE
Heroic Launcher not starting on Manjaro when installed through AUR

### ISSUE THREAD

**Issue by Dave-van-der-Meer** [Heroic-Games-Launcher/HeroicGamesLauncher#668]
### Is this a game issue?  If YES please use our Discord to get help.
No, it concerns the Launcher itself.

### Open here only issues with Heroic like: Heroic doesn't open, some button is out of place, Heroic closes unexpectedly, installs got interrupted, etc.
Heroic doesn't open.

### Try to get help on our Wiki first: https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/wiki/Troubleshooting

**Describe the bug**
After I installed the Heroic Games Launcher through AUR with _trizen_ as AUT-helper, the Heroic Launcher did not start when I was starting it through the GNOME search bar. There is no error message. When using the terminal to start the program, I get a Javascript error message (see below).

**To Reproduce**
Steps to reproduce the behaviour:

1. Install Heroic Games LAuncher through AUR helper: `trizen -S heroic-games-launcher-bin`
2. type command `heroic` in terminal.
3. See the following error:

```
A JavaScript error occurred in the main process
Uncaught Exception:
SyntaxError: Unexpected token o in JSON at position 1
    at JSON.parse (<anonymous>)
    at Function.get (/opt/Heroic/resources/app.asar/build/config.js:35:28)
    at Object.<anonymous> (/opt/Heroic/resources/app.asar/build/main.js:60:27)
    at Module._compile (internal/modules/cjs/loader.js:1078:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1108:10)
    at Module.load (internal/modules/cjs/loader.js:935:32)
    at Module._load (internal/modules/cjs/loader.js:776:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
    at Object.<anonymous> (electron/js2c/browser_init.js:193:3237)
    at Object../lib/browser/init.ts (electron/js2c/browser_init.js:193:3441)
```

**Expected behaviour**
I expect the Heroic Launcher to open, but it doesn't start.

**Screenshots**
![image](https://user-images.githubusercontent.com/47270949/134803709-f83474f2-96b3-4623-8dae-771b2995def6.png)

**Desktop (please complete the following information):**

- OS: Manjaro Linux x86_64
- Version rolling-release (with latest updates installed)
- Game: Heroic Games Launcher
- Wine/Proton version: n.a.
- Hardware specs (RAM, CPU, GPU): 16 GB RAM, AMD® Ryzen 5 2600x six-core processor × 12 , Radeon RX Vega (VEGA10, DRM 3.41.0, 5.13.15-1-MANJARO, LLVM 12.0.1), GNOME version 40.4.0, X11 windowing system

**Additional context**

**Comment by flavioislima** [comment]
Seems like some corrupted json file. Can you try removing the heroic folder under .config?
Also, have you used heroic before? This happens after login or the login screen doesn't even open?

**Comment by Dave-van-der-Meer** [comment]
Removing the ~/.config/heroic directory worked. Thanks.
Indeed, I had it installed before, but it stopped working a while ago so I removed it and now I wanted to try again.
It crashed even before I could see any login screen or any window in general.

Thanks for the help :)
