### ISSUE TITLE
Game Missing from Library

### ISSUE THREAD

**Issue by redromnon** [Heroic-Games-Launcher/HeroicGamesLauncher#673]
I believe this is a Heroic related issue and not the game's.

I had added Star Wars Battlefront 2 to my **Epic Games library** on Windows when it was available as a free download. I had encountered a bug that listed the game _"Unavailable"_ until I went to the Store Page and clicked _"Game Owned "_ button. It was working after that.

The problem arises in Heroic Games Launcher. It does not list the game in my library in spite of refreshing the library and signing in again. What causes this problem?

**Comment by flavioislima** [comment]
Yes, the current Heroic version doesn't support games that use Origin or Uplay, which will be fixed on the next Major version (2.0). So for now you will need to use EGS to link the game and use Origin to play it.

**Comment by redromnon** [comment]
Noted.
