### ISSUE TITLE
Can't launch games if they have an update

### ISSUE THREAD

**Issue by mascali33** [Heroic-Games-Launcher/HeroicGamesLauncher#679]
**Describe the bug**
Launching a game that need an update and answering no to the update prompt doesn't launch the game

**To Reproduce**
1. Go to a game with an update needed
2. Try to launch it
3. Answer no to the update prompt
4. Game doesn't start
5. Heroic logs throws an error:
```
Error occurred in handler for 'launch': TypeError: Cannot destructure property 'title' of '(intermediate value)' as it is null.
    at /opt/Heroic/resources/app.asar/build/main.js:434:13
    at async electron/js2c/browser_init.js:197:563
```

**Expected behavior**
Heroic should have launched the game with the "--skip-version-check" of legendary (note that launching legendary with the added args launches the game correctly)

**Desktop (please complete the following information):**

- OS: Manjaro (with kernel 5.13.19)
- Version: 1.9.3 Mihawk
- Game: Jurassic World Evolution (but any game with an update throws the same error)
- Wine/Proton version: Proton 6.3
- Hardware specs (RAM, CPU, GPU): 16Gb RAM, Ryzen 5 2600x, NV 1660 TI (with driver 470.63)

**Comment by flavioislima** [comment]
Hi!

Yes, found the issue. I'll Push a fix soon.
