### ISSUE TITLE
io-slave error from shortcut

### ISSUE THREAD

**Issue by Darkfull-Dante** [Heroic-Games-Launcher/HeroicGamesLauncher#689]
### Try to get help on our Wiki first: https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/wiki/Troubleshooting

**Describe the bug**
get io-slave, unknown protocol 'heroic' when trying to launch a game from a shortcut

**To Reproduce**

1. Go to game page in heroic launcher (Satisfactory Early Access in my case)
2. Click on "Add shortcut"
3. Click on newly created shortcut
4. Get error "Unable to create io-slave. Unknown protocol 'heroic'."

**Expected behavior**
Game launches

**Screenshots**
![error_screenshot](https://i.imgur.com/GNG7C5q.png)

**Desktop (please complete the following information):**

- OS: [e.g. Kubuntu]
- Version [e.g. 21.04]
- Game: Satisfactory Early Access (CrabEA)
- Wine/Proton version: Proton 6.3
- Hardware specs (RAM, CPU, GPU):
    - AMD Ryzen 7 3800X (16) @ 3,900GHz
    - Nvidia GeForce RTX 2070 SUPER
    - 16GB 3200MHz CL16

**Additional context**
Game runs without problem from launcher

**Comment by Darkfull-Dante** [comment]
@flavioislima could you point to which one of the troubleshooting I should check because I did verify it first and none of them seem to point to shortcut related problem. I clearly missed it.

**Comment by GitThisBugOff** [comment]
I'm still having issues with this. Did the symbolic link as suggested, then added the x-scheme heroic line on mimeapps.list; still gives me the same error.

**Comment by GitThisBugOff** [comment]
```
xdg-open heroic://launch/Calluna
admin@3600-UBUNTU:~$ command= "/opt/Heroic/heroic %u --enable-features=UseOzonePlatform --ozone-platform=wayland" args= ("/opt/Heroic/heroic %u --enable-features=UseOzonePlatform --ozone-platform=wayland", "heroic://launch/Calluna")
kf.kio.core: Protocol Class of url QUrl("heroic://launch/Calluna") , isn't ':local', cancelling job.
Copying QUrl("heroic://launch/Calluna")  to QUrl("file:///home/raphael/.cache/kioexec/krun/10794_0/Calluna")
kf.kio.core: couldn't create slave: "Unknown protocol 'heroic'."
All files downloaded, will call slotRunApp shortly
No files downloaded -> exiting
kf.kio.slaves.file: readData() returned -1
```

This is my output after launching the xdg-open command manually from a terminal

**Comment by flavioislima** [comment]
I think this is a general issue with electron right now. We should probably open an issue there but I'll do more investigation if we are registering the protocol the right way. I think so because on some DEs works fine, on windows and mac also works fine. So might be something on their side.

**Comment by GitThisBugOff** [comment]
For what it's worth I'm Kubuntu with Plasma-Wayland v5.23.2. This also happens in X11 and in v5.22

**Comment by KuleRucket** [comment]
The first game I added the shortcut for adding the following to .config/mimeapps.list, and I got the error reported
x-scheme-handler/heroic=<Game>.desktop
I changed this to the following:
x-scheme-handler/heroic=heroic.desktop
Now all links work fine
Having the link to mimeapps.list in .local/share/applications/ made no difference.
