### ISSUE TITLE
Database of running games

### ISSUE THREAD

**Issue by PrzemekSkw** [Heroic-Games-Launcher/HeroicGamesLauncher#692]
Hello, It will be very nice to start website with database like protondb where users will see what games are working on Heroic. From my experience I know that some games works better on Heroic and some better on Lutris with Epic installed. Some games are not working at all so it would be convenient for other users not to download and install games that don't work, that someone has already tested.

Regards,
Przemek

**Comment by flavioislima** [comment]
That would be nice but should come from the community. You can take this discussion to our discord and think on a way to do that. we need a website, which I didn't have the time to start yet, and on this site we could collect the info like they do on protondb.
