### ISSUE TITLE
Allow setting multiple EXE for Game

### ISSUE THREAD

**Issue by JakobDev** [Heroic-Games-Launcher/HeroicGamesLauncher#693]
I noticed that Legendary allows changing the EXE file for bypassing stupid launchers, which is a really great change! There is just 1 problem: You can only set a single EXE. If you have a Game Collection which needed to bypass the Launcher e.g. [KINGDOM HEARTS HD 1.5 + 2.5 ReMIX](https://www.epicgames.com/store/de/p/kingdom-hearts-hd-1-5-2-5-remix) you need to change the EXE each time you like to run another Game. It would be really cool if Heroic allows setting multiple EXE files. If you start Game with multiple EXE, a Window appears in which you can choose what to launch like Steam does with Titles who have multiple files.

**Comment by flavioislima** [comment]
Hi, this feature is too specific. In the future it's planned to add support for games outside epic, like lutris does, so this might be the case.
