### ISSUE TITLE
Can't disable offline mode on borderands 3

### ISSUE THREAD

**Issue by IagoFloriano** [Heroic-Games-Launcher/HeroicGamesLauncher#697]
### Try to get help on our Wiki first: https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/wiki/Troubleshooting

**Describe the bug**
Today i was trying to play the game with a friend and neither of us could connect to each other. I saw that my game had "Run Offline: YES" so i think that is the problem. I've tried going into settings and disabling it but it was already disabled.

**To Reproduce**
I dont know how to reproduce it, made no modifications on the game (even tried Verify and Repair option) and when i toggle the offline mode option to off it still says "Run Offline: YES"

**Expected behavior**
I expected to be outputed "Run Offline: NO" or something like that when the toggle for offline mode is off.

**Screenshots**
![2021-10-12-204029_1916x1057_scrot](https://user-images.githubusercontent.com/61942425/137043240-9d36af48-575a-4296-a698-568a1fcc65c7.png)

![2021-10-12-204037_1916x1057_scrot](https://user-images.githubusercontent.com/61942425/137043254-83d9ff92-9470-46c6-9bbc-1cbed65d2a62.png)

**Desktop (please complete the following information):**

- OS: Arch Linux
- Version: Kernel Linux 5.14.11-zen1-1-zen
- Game: Borderlands 3
- Wine/Proton version: proton-ge-custom-bin 6.19_GE_2-1 (proton ge from the aur)
- Hardware specs (RAM, CPU, GPU): 16GB ram, Intel core i7-7700, NVIDIA GeForce GTX 1050 Ti.

**Additional context**
$HOME/.config/heroic/config.json :
```
{
  "defaultSettings": {
    "altLegendaryBin": "",
    "addDesktopShortcuts": false,
    "addStartMenuShortcuts": false,
    "audioFix": false,
    "autoInstallDxvk": true,
    "checkForUpdatesOnStartup": true,
    "customWinePaths": [],
    "darkTrayIcon": false,
    "defaultInstallPath": "/home/yv/Games/Heroic",
    "discordRPC": true,
    "egsLinkedPath": "",
    "enableEsync": false,
    "enableFsync": false,
    "exitToTray": false,
    "language": "en",
    "maxRecentGames": 5,
    "maxWorkers": 0,
    "nvidiaPrime": false,
    "offlineMode": false,
    "otherOptions": "",
    "showFps": false,
    "showMangohud": true,
    "startInTray": false,
    "useGameMode": false,
    "wineCrossoverBottle": "Heroic",
    "winePrefix": "/home/yv/.wine",
    "wineVersion": {
      "bin": "'/usr/share/steam/compatibilitytools.d/proton-ge-custom/proton'",
      "name": "Proton - proton-ge-custom"
    }
  },
  "version": "v0"
}
```

Dont know which of the following files should be useful:
ls $HOME/.config/heroic/GamesConfig :
`Catnip.json  Catnip-lastPlay.log  Catnip.log  Eagle.json  Garlic.json  Garlic-lastPlay.log  Garlic.log`

**Comment by flavioislima** [comment]
Hi. That info under the game page is just saying that the game supports running if you are offline. Not that the game is running offline. (I will rename it on next versions) 

To be sure, run heroic from the terminal, launch the game and check if there is a - -offline tag on the launch command.

Maybe go to our discord to see if someone could play the game online, I don't have it on my library to test.
