### ISSUE TITLE
A Certain Game does not show up in my library.

### ISSUE THREAD

**Issue by germaniii** [Heroic-Games-Launcher/HeroicGamesLauncher#698]
**Describe the bug**
So I was trying to browse games in my library. I remembered that I had Star Wars Battlefront II in my library, but to my surprise, it is not listed there(See photo 1). When I checked the store, it shows that it is in my library already(see photo 2 below). 

**To Reproduce**
1. Open Heroic
2. Browse Library without searching
3. Browse Library searching for the game
4. Game not found
5. Look for it at the store > Game is in library.

**Expected behavior**
The Game should be listed in the library since it shows it is in my library in the store.

**Screenshots**
If applicable, add screenshots to help explain your problem

Photo 1
![image](https://user-images.githubusercontent.com/54576359/137054564-9131747d-0ca1-45fc-80d4-84c3d5b52cf5.png)

No Star Wars in list 
![image](https://user-images.githubusercontent.com/54576359/137055111-76d0497e-6f3d-463b-b0d3-50d91bccfbe4.png)

Photo 2
![image](https://user-images.githubusercontent.com/54576359/137054605-8e06e2bf-123a-4563-b6d7-01c58794ec36.png)

**Desktop (please complete the following information):**
- OS: Arch Linux
- Version 5.14.9
- Game: Star Wars Battlefront II Celebration Edition
- Wine/Proton version: N/A
- Hardware specs (RAM, CPU, GPU): 16 GB RAM, Ryzen 5 3600, MSI RX560 4GB

EDIT: I do not know if this applies to other games also, so I made the title vague.

**Comment by lucifertdark** [comment]
Star Wars Battlefront II is one of those games that uses the Origin launcher, so for now it doesn't show up or install through Heroic.

**Comment by flavioislima** [comment]
Yes, this will be implemented on future versions but it's not supported right now.
