### ISSUE TITLE
Add option to enable DXVK NVAPI/DLSS

### ISSUE THREAD

**Issue by Sultech** [Heroic-Games-Launcher/HeroicGamesLauncher#699]
**Is your feature request related to a problem? Please describe.**
DLSS does not work for games without DXVK NVAPI 

**Describe the solution you'd like**
Add a option to enable DXVK NVAPI in heroic for DLSS

**Additional context**
Lutris has an option to enable DXVK NVAPI here is a screenshot
![Screenshot from 2021-10-13 03-22-02](https://user-images.githubusercontent.com/30802163/137056349-bbf35805-3069-4e05-a9d2-f9b201390ff3.png)

**Comment by Sultech** [comment]
I have also explained how lutris does this here https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/issues/700 and I think it would be good if you make it work the same as lutris

**Comment by flavioislima** [comment]
Do we still need this one since Proton enables the DLSS by default on almost every game now?

**Comment by LethalManBoob** [comment]
Why have we been lacking this feature for 2 flipping years???

**Comment by Etaash-mathamsetty** [comment]
> Why have we been lacking this feature for 2 flipping years???

because you can use proton (not recommended though), but at least it works without manual configuration

**Comment by YousofMersal** [comment]
Would also really like to see this feature

**Comment by Etaash-mathamsetty** [comment]
> Would also really like to see this feature

could any of you wanting to use this feature test this? 
https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/pull/2567
