### ISSUE TITLE
gamesUpdates turns null when scrolling through games library

### ISSUE THREAD

**Issue by etiennedevilliers** [Heroic-Games-Launcher/HeroicGamesLauncher#701]
While scrolling through my library the `gameUpdates` object at src/screens/Library/index.tsx turns null (error occurs at line 72). When this happens an error is posted to the console.

**To Reproduce**
1. Go to library page
2. Scroll through library slowly. 
3. See error

**Expected behavior**
Normal browse through games behaviour.

**Screenshots**
<img width="1640" alt="image" src="https://user-images.githubusercontent.com/11314676/137208492-2ccd9bad-f1b3-4e5d-b0b3-07c8bbe821a4.png">

https://user-images.githubusercontent.com/11314676/137208607-8ad04aac-b208-48e0-ac45-297edde1d3a1.mp4

**Desktop (please complete the following information):**
- OS: macOS
- Version 12.0 Beta (21A5534d)
- Game: N/A
- Wine/Proton version: Crossover Latest?
- Hardware specs (RAM, CPU, GPU): M1; 16GB 

**Additional context**
None

**Comment by flavioislima** [comment]
It's weird that only on mac the check update function from legendary is not working. I'll see how can I fix that but there is already an opened issue for that. We can talk there on #681
