### ISSUE TITLE
Heroic window doesn't open on launching the app on MacOS

### ISSUE THREAD

**Issue by navy5356** [Heroic-Games-Launcher/HeroicGamesLauncher#716]
On launching the app on MacOS, the app opens, but has no window to interact with. Tested on Macbook Air with Apple Silicon (M1) running MacOS 12.0.1 Monterey

**Comment by flavioislima** [comment]
Please do not erase the template when opening an issue.
Also, go to the troubleshooting guide of the wiki, run heroic from the terminal as states there and put some logs when opening an issue.
Things like just saying it's not opening doesn't help.

Open an new issue with the information we ask and attach some logs.
