### ISSUE TITLE
Heroic: marketplace items have many duplicates

### ISSUE THREAD

**Issue by Ryder17z** [Heroic-Games-Launcher/HeroicGamesLauncher#717]
**Describe the bug**
[image](https://user-images.githubusercontent.com/2000703/139540173-ca3e33ba-9392-44fd-9f3e-f251506ac431.png)

Many items are duplicates.

**To Reproduce**

Unsure, this is from running the AUR steps, launching Heroic, signing in and then switching to marketplace tab.

**Expected behavior**
There shouldn't be any duplicates. E.g. I have Graph Formatter listed 7 times, instead of once.

**Screenshots**
see above.

**Desktop (please complete the following information):**

- OS: Manjaro Linux
- Version 21.1.6
- Game:
- Wine/Proton version: not relevant?
- Hardware specs: Ryzen 3800x, 32GB, GTX1080

**Additional context**
N/A

**Comment by derrod** [comment]
This is simply due to that fact that marketplace items have separate "apps" for each Unreal Engine version they support.

**Comment by Ryder17z** [comment]
> This is simply due to that fact that marketplace items have separate "apps" for each Unreal Engine version they support.

Oh?
Can they be grouped somehow?

**Comment by derrod** [comment]
Possibly, maybe there's a unique identifier in the metadata that would make that possible. The Epic Games Launcher uses a separate API for marketplace assets that contains additional information and doesn't have this issue. But that is not currently supported in legendary.

**Comment by flavioislima** [comment]
Yes, for now there eis not much we can do about it unfortunately. I also have no way to try it since I have no epic assets in my account.

**Comment by Ryder17z** [comment]
> Yes, for now there eis not much we can do about it unfortunately. I also have no way to try it since I have no epic assets in my account.

You can just grab some of the free assets though. https://www.unrealengine.com/marketplace/en-US/free

**Comment by flavioislima** [comment]
Ok, I'll try to do some tests and create a filter on the frontend when I have the time.

**Comment by Ryder17z** [comment]
I'm not sure how useful it is, but https://github.com/AchetaGames/Epic-Asset-Manager  does have some filtering.

It could be worth looking into how they do it.

**Comment by arielj** [comment]
I'm closing this, we don't have enough resources to implement anything close to what epic-asset-manager can do and we are not going to support handing the marketplace inside Heroic anytime soon.

**Comment by arielj** [comment]
I understand the next version of heroic won't have any marketplace configuration at all.

**Comment by Ryder17z** [comment]
Oh. That would suffice until fixed.
