### ISSUE TITLE
Feature request: Marketplace: toggle titles for icons

### ISSUE THREAD

**Issue by Ryder17z** [Heroic-Games-Launcher/HeroicGamesLauncher#718]
**Is your feature request related to a problem? Please describe.**
I have some trouble navigating the list of marketplace items I own because they are only similar icons and only a few actually have a text in the icon.

**Describe the solution you'd like**
A toggle to show the title under the icon.

**Describe alternatives you've considered**
I don't know of any.

**Additional context**
Mock-up: 
![image](https://user-images.githubusercontent.com/2000703/139541186-a8ee4e90-3ab6-43dd-90d4-37fdf2a354be.png)

**Comment by flavioislima** [comment]
This option will be removed from Heroic since now you have better options to manage the assets and also none of our devs have experience with it.
