### ISSUE TITLE
[Linux] Cyberpunk 2077 install/manage page won't open

### ISSUE THREAD

**Issue by idontbyte** [Heroic-Games-Launcher/HeroicGamesLauncher#720]
**Describe the bug**
When opening the install/manage game page for Cyberpunk 2077 from heroic 1.10.3 I only see a blue screen and no logs in terminal.

**To Reproduce**

1. Open Heroic launcher
2. Click on Cyberpunk 2077
3. See only a blue background

**Expected behavior**
Open the game install / manage page

**Desktop (please complete the following information):**

- OS: Pop OS
- Version 21.04
- Game: Cyberpunk 2077

**Additional context**
There are no logs in terminal or crash log.
Manually running 'legendary info Ginger' returns expected information about cyberpunk and there seems to be no problems with it.
[cyberpunkinfo.txt](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/files/7447358/cyberpunkinfo.txt)

**Comment by flavioislima** [comment]
Can you please upload the Ginger manifest file found under .`config/legendary/metadata` and the output of `legendary -J info Ginger --json` as well, so I can check which field is breaking.

**Comment by idontbyte** [comment]
[legendary-json.txt](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/files/7447407/legendary-json.txt)

**Comment by idontbyte** [comment]
[Ginger.txt](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/files/7447414/Ginger.txt)

**Comment by flavioislima** [comment]
What happens if you click on the install icon instead of opening the game page?

**Comment by flavioislima** [comment]
Do you know how to run Heroic from the source?
I cannot find anything wrong with the info you sent. It's just like any other game. So It's hard to debug without a proper error message.

**Comment by flavioislima** [comment]
Actually I just remembered that if you run heroic like this:
`ELECTRON_ENABLE_LOGGING=true heroic` it will show the frontend errors on the console as well.
So whenever you click on the Cyberpunk card it will throw an error.
If possible, rename your `.config/heroic` folder before launching heroic like this so we can get the error without any caching involved.

**Comment by SsNiPeR1** [comment]
i have an idea, why that fails. the cp2077 has a custom, yellow store and library page. maybe it makes a bug somehow?

**Comment by flavioislima** [comment]
> i have an idea, why that fails. the cp2077 has a custom, yellow store and library page. maybe it makes a bug somehow?

Could be that some info we are trying to get from the store is missing and breaking the Game page on heroic but it's hard to guess.
Try Heroic Beta 2 to see if it fixes it. If not, run heroic with the command I said above for us to have any clue.
Also, on the heroic menu you can see the DEBUG option, it will open the dev tools, so we can see if some error appear there.

**Comment by polarn** [comment]
@flavioislima I am also getting this behavior, and using the above debug, then I get this output:
```
[14317:1219/094113.180771:INFO:CONSOLE(2)] "TypeError: Invalid attempt to spread non-iterable instance.
In order to be iterable, non-array objects must have a [Symbol.iterator]() method.", source: file:///usr/lib64/heroic-games-launcher-bin/resources/app.asar/build/static/js/3.a346c093.chunk.js (2)
[14317:1219/094113.180796:INFO:CONSOLE(2)] "Uncaught TypeError: Invalid attempt to spread non-iterable instance.
In order to be iterable, non-array objects must have a [Symbol.iterator]() method.", source: file:///usr/lib64/heroic-games-launcher-bin/resources/app.asar/build/static/js/3.a346c093.chunk.js (2)
``` 
Not sure that helps?

**Comment by flavioislima** [comment]
> @flavioislima I am also getting this behavior, and using the above debug, then I get this output:
> 
> ```
> [14317:1219/094113.180771:INFO:CONSOLE(2)] "TypeError: Invalid attempt to spread non-iterable instance.
> In order to be iterable, non-array objects must have a [Symbol.iterator]() method.", source: file:///usr/lib64/heroic-games-launcher-bin/resources/app.asar/build/static/js/3.a346c093.chunk.js (2)
> [14317:1219/094113.180796:INFO:CONSOLE(2)] "Uncaught TypeError: Invalid attempt to spread non-iterable instance.
> In order to be iterable, non-array objects must have a [Symbol.iterator]() method.", source: file:///usr/lib64/heroic-games-launcher-bin/resources/app.asar/build/static/js/3.a346c093.chunk.js (2)
> ```
> 
> Not sure that helps?

This is shown on the console, right?
And what happens if you open heroic, then click debug on the menu to open the dev tools and then go to the game page?

**Comment by flavioislima** [comment]
@polarn @idontbyte @SsNiPeR1 
Try this AppImage:
https://drive.google.com/file/d/19CdFJETv5C6LmbHvpLyt6ELkhr5ydO2t/view?usp=sharing

run it from terminal:
`chmod +x /Heroic-1.11.0-beta.3.AppImage`
`./Heroic-1.11.0-beta.3.AppImage`

It might not fix it but I added some logs on some points where we get the Epic Data to try to find where it's breaking.

**Comment by polarn** [comment]
@flavioislima 
Not getting that much more output from your AppImage. First is the console log in the shell, after is the browser console log after enabling debug in the menu.
```
➜  Downloads (⎈ |N/A:default) ELECTRON_ENABLE_LOGGING=true ./Heroic-1.11.0-beta.3.AppImage                                                                                                                                           ()
INFO: Trying to get user information
INFO: Heroic Version 1.11.0-beta.2
INFO: Trying to get user information
INFO: Legendary Version  0.20.21 Anticitizen One (hotfix #2)

INFO: Trying to get user information
INFO: Trying to get user information
WARNING: Protocol already registered.
[39862:1219/124009.004505:ERROR:browser_main_loop.cc(269)] Gtk: gtk_widget_add_accelerator: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed
[39862:1219/124009.004548:ERROR:browser_main_loop.cc(269)] Gtk: gtk_widget_add_accelerator: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed
INFO: Command 'python' found. Version: '3.10.0'
INFO: Frontend: Refreshing Library
INFO: Refreshing library...
INFO: Legendary: Refreshing Epic Games...
INFO: Refreshing Epic Games...
[cli] INFO: Logging in...

[Core] INFO: Trying to re-use existing login session...

[cli] INFO: Getting game list... (this may take a while)

INFO: Updating game list
INFO: Game List Updated
INFO: Checking for game updates
INFO: Found 0 game(s) to update
INFO: Trying to get user information
INFO: checking for heroic updates
[39862:1219/124016.160299:INFO:CONSOLE(2)] "TypeError: Invalid attempt to spread non-iterable instance.
In order to be iterable, non-array objects must have a [Symbol.iterator]() method.", source: file:///tmp/.mount_Heroic2sNEa0/resources/app.asar/build/static/js/4.1a9feb2e.chunk.js (2)
[39862:1219/124016.160415:INFO:CONSOLE(2)] "Uncaught TypeError: Invalid attempt to spread non-iterable instance.
In order to be iterable, non-array objects must have a [Symbol.iterator]() method.", source: file:///tmp/.mount_Heroic2sNEa0/resources/app.asar/build/static/js/4.1a9feb2e.chunk.js (2)
```

```
react-dom.production.min.js:216 TypeError: Invalid attempt to spread non-iterable instance.
In order to be iterable, non-array objects must have a [Symbol.iterator]() method.
    at nonIterableSpread.js:2
    at i (toConsumableArray.js:6)
    at D (index.tsx:105)
    at ro (react-dom.production.min.js:157)
    at Vo (react-dom.production.min.js:180)
    at $u (react-dom.production.min.js:269)
    at Pl (react-dom.production.min.js:250)
    at Cl (react-dom.production.min.js:250)
    at Ol (react-dom.production.min.js:250)
    at gl (react-dom.production.min.js:243)
uu @ react-dom.production.min.js:216
n.callback @ react-dom.production.min.js:216
fi @ react-dom.production.min.js:131
hu @ react-dom.production.min.js:220
Nl @ react-dom.production.min.js:259
t.unstable_runWithPriority @ scheduler.production.min.js:18
Wa @ react-dom.production.min.js:122
_l @ react-dom.production.min.js:252
gl @ react-dom.production.min.js:243
(anonymous) @ react-dom.production.min.js:123
t.unstable_runWithPriority @ scheduler.production.min.js:18
Wa @ react-dom.production.min.js:122
qa @ react-dom.production.min.js:123
I @ scheduler.production.min.js:16
k.port1.onmessage @ scheduler.production.min.js:12
nonIterableSpread.js:2 Uncaught TypeError: Invalid attempt to spread non-iterable instance.
In order to be iterable, non-array objects must have a [Symbol.iterator]() method.
    at nonIterableSpread.js:2
    at i (toConsumableArray.js:6)
    at D (index.tsx:105)
    at ro (react-dom.production.min.js:157)
    at Vo (react-dom.production.min.js:180)
    at $u (react-dom.production.min.js:269)
    at Pl (react-dom.production.min.js:250)
    at Cl (react-dom.production.min.js:250)
    at Ol (react-dom.production.min.js:250)
    at gl (react-dom.production.min.js:243)
(anonymous) @ nonIterableSpread.js:2
i @ toConsumableArray.js:6
D @ index.tsx:105
ro @ react-dom.production.min.js:157
Vo @ react-dom.production.min.js:180
$u @ react-dom.production.min.js:269
Pl @ react-dom.production.min.js:250
Cl @ react-dom.production.min.js:250
Ol @ react-dom.production.min.js:250
gl @ react-dom.production.min.js:243
(anonymous) @ react-dom.production.min.js:123
t.unstable_runWithPriority @ scheduler.production.min.js:18
Wa @ react-dom.production.min.js:122
qa @ react-dom.production.min.js:123
I @ scheduler.production.min.js:16
k.port1.onmessage @ scheduler.production.min.js:12
```

**Comment by flavioislima** [comment]
Yes, the error doesn't point where it happens.
But, when you click on cyberpunk page can you check the terminal as well?

Also, remove the file `.config/heroic/store/gameinfo.json`
, try to open the game page again. 
It should show something like "getting info from epic api" and "getting info from legendary info", or something like this on the terminal.

**Comment by polarn** [comment]
Yeah the TypeError rows are written in the terminal when I click the cyberpunk game.

I removed that file and when I click the cyberpunk game, only the TypeError shows up. When I click another game, then yeah I get that getting info from epic api:
```
INFO: Getting Info from Epic API
INFO: Getting More details with Legendary info command... 
```

So something goes wrong before that for cyberpunk.

**Comment by flavioislima** [comment]
@polarn ok thanks. I'll keep investigating then and might come with another test appimage later.

**Comment by polarn** [comment]
I opened the code up in vscode, ran it and here is some more info:
```
TypeError: mandatoryTags is not iterable
```
https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/blob/main/src/screens/Game/GamePage/index.tsx#L101

I added a simple console log and it is undefined for cyberpunk. For other games it is not. Here is where my typescript expertise ends. :joy: I will try to check some more..

**Comment by flavioislima** [comment]
Yes, I just found out as well. I have overridden a game with the Cyperpunk info and could get this error. I'm generating an AppImage for you to test but I think it's fixed now.

**Comment by flavioislima** [comment]
Ok try it now:
https://drive.google.com/file/d/1H3IWIyon2HX53LqsM51kziYJ-QOUDm1o/view?usp=sharing

Hope it will work :)

**Comment by polarn** [comment]
Checking the `SelectiveDownload` then there are no mandatory tags for Cyberpunk, so the `filter` would end up with nothing, so thus the `mandatoryTags` will be undefined?

**Comment by flavioislima** [comment]
Yes, but actually the error was on this line:
https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/blob/7bd8d18fd7cf42fd53bebcaa2f833a159787a435/src/screens/Game/GamePage/index.tsx#L103

I could be passing the whole array but for some reason, I was getting the item and trying to iterate on it. 
Since Fortnite has a mandatory chunk, it worked fine and that's the only game I have on my list that has SDL.
But when a game didn't, it was breaking. So it was probably breaking Beyond two souls as well.

**Comment by polarn** [comment]
With that appimage, the CyberPunk page loads when I click it, but when I try to install it I get the same blank screen and from the looks of it, the same TypeError. At least I got the "getting info from epic api" this time. :)
```
INFO: Getting Info from Epic API
INFO: Getting More details with Legendary info command... 
[72297:1219/142046.902041:INFO:CONSOLE(2)] "TypeError: Invalid attempt to spread non-iterable instance.
In order to be iterable, non-array objects must have a [Symbol.iterator]() method.", source: file:///tmp/.mount_HeroicLosLwR/resources/app.asar/build/static/js/4.1a9feb2e.chunk.js (2)
[72297:1219/142046.902242:INFO:CONSOLE(2)] "Uncaught TypeError: Invalid attempt to spread non-iterable instance.
In order to be iterable, non-array objects must have a [Symbol.iterator]() method.", source: file:///tmp/.mount_HeroicLosLwR/resources/app.asar/build/static/js/4.1a9feb2e.chunk.js (2)
```

(I joined your discord if that helps in debugging)

**Comment by flavioislima** [comment]
Yes, I forgot to change the InstallModal as well 🤦🏽 
I'm updating the AppImage.

This SDL stuff is actually not required on the game page anymore.
So I'm removing it.
Only the Install dialog should have it.

**Comment by flavioislima** [comment]
Ok:
https://drive.google.com/file/d/1Dyjm80wcDFcHV3vGZTnzao3Jgykt5edS/view?usp=sharing

**Comment by polarn** [comment]
Awesome, now it is installing! Thanks for these quick updates.

The new UI looks nicer as well, so hoping it will be released soon!

**Comment by flavioislima** [comment]
Ah perfect, thanks for your help as well.
Yes, the new version should be released soon, before 2022.

**Comment by Brax68** [comment]
Hey I was wondering if you could repost the fixed version? Your drive link says it was moved to your trash! It would be great if I could get it running right now.

**Comment by flavioislima** [comment]
> Hey I was wondering if you could repost the fixed version? Your drive link says it was moved to your trash! It would be great if I could get it running right now.

Beta 3 has the fix https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/releases/tag/v1.11.0-beta.3

But it has issues with dxvk installation.
Might be better to wait for the new version later today or to download the appimage from the build on the latest commit in the main branch.

**Comment by flavioislima** [comment]
> Is this issue back or was it never fixed? I'm having that problem on the Steam Deck. Trying to install Kingdom Hearts III since it stopped working on Epic Games (or rather EGS is now incompatible with Proton 5.1) but I only get a blank page, uninstalling Heroic and reinstalling doesn't help
> 
> So for the record,
> 
> * SteamOS
> * Version 3.2
> * Kingdom Hearts III

It is only this game?
Open a new issue and attach the logs.
Add logs from the debug (Dev tools) window as well > right-click on heroic  tray icon > Debug > Console
