### ISSUE TITLE
Adding a game shortcut only creates the Start Menu shortcut but not the desktop shortcut on non-english system

### ISSUE THREAD

**Issue by arielj** [Heroic-Games-Launcher/HeroicGamesLauncher#721]
**Describe the bug**

The `Add shortcut` action says `Shortcuts were created on Desktop and Start Menu`, but the shortcut is only added for the Start Menu.

The problem seems to be this https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/blob/b3418e38f76a7182ad8b87a994f1018f34d7ee39/electron/legendary/games.ts#L258

Which is using always `Desktop` as the directory name which, in my system (spanish), it's `Escritorio`.

This command can be used to get the name of the directory in linux `xdg-user-dir DESKTOP`, though I don't know if this affects other operating systems.

Note this also affects removing the desktop shortcut, since it also uses the hardcoded `Desktop` directory https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/blob/b3418e38f76a7182ad8b87a994f1018f34d7ee39/electron/legendary/games.ts#L305

**To Reproduce**

1. Install a game
2. Click `Add shortcut` in the game details screen
3. See the success message
4. Check the Start Menu > Games (Icon is there)
5. Check the Desktop (Icon is not there)

**Expected behavior**

The Icon should be in both places.

**Desktop (please complete the following information):**

- OS: Linux Mint
- Version: 20.1 Cinnamon
- Cinnamon version: 4.8.6
- Game: Not specific for one game, it happens with any game
- Wine/Proton version: Proton - Experimental
- Hardware specs (RAM, CPU, GPU): 16GB, AMD Ryzen 7, AMD 5700 XT

**Additional context**

System in Spanish (desktop dir is `Escritorio`, not `Desktop`).

**Comment by flavioislima** [comment]
Yes, this shortcut stuff is actually pretty bad implemented. 
Actually now if a game fails to install sometimes the shortcut is created anyway, so it needs to be improved.
Also doesn't work on Windows and Mac so its quite limited now.

**Comment by arielj** [comment]
I'll try to implement the Mac version (I don't have windows but I think I can try with a VM too). I'll create issues for that

**Comment by flavioislima** [comment]
Sounds good! Thanks!
