### ISSUE TITLE
Support automatically adding shortcuts on Windows

### ISSUE THREAD

**Issue by arielj** [Heroic-Games-Launcher/HeroicGamesLauncher#726]
**Is your feature request related to a problem? Please describe.**

The settings for adding shortcuts automatically when a game is installed are not present on Windows.

**Describe the solution you'd like**

The settings should include the option, after #724 is closed, this can be enabled (and fixed).

**Additional context**

I tried to include this fix in the PR #725, but I hit some issue on windows where the execAsync callback is not getting executed for the `install` command. Something is wrong with the generated command since the uninstall callback works fine.

I was thinking about moving the creation of the shortcuts to the Library component that it's correctly detecting when a game finishes installing.

**Comment by flavioislima** [comment]
@arielj forgot to ask if this was done on your PR as well.

**Comment by arielj** [comment]
@flavioislima no, it was not included in the other PR becuase I was having some issues

in windows, this `then` is not getting executed https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/blob/main/electron/legendary/games.ts#L372 (what's weird is that this pretty similar promise's `then` IS executed https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/blob/main/electron/legendary/games.ts#L388)

but when the game finishes installing, this is triggered correctly https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/blob/df1809bdd1872e04fb6b23a00c5473711ec0520d/src/state/GlobalState.tsx#L221

I'll try again today or during the week, maybe the shortcut creation can be moved to that same place where the notification is displayed? seems like those 2 actions should be in the same place since both depend on the game being installed

**Comment by flavioislima** [comment]
> @flavioislima no, it was not included in the other PR becuase I was having some issues
> 
> in windows, this `then` is not getting executed https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/blob/main/electron/legendary/games.ts#L372 (what's weird is that this pretty similar promise's `then` IS executed https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/blob/main/electron/legendary/games.ts#L388)
> 
> but when the game finishes installing, this is triggered correctly
> 
> https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/blob/df1809bdd1872e04fb6b23a00c5473711ec0520d/src/state/GlobalState.tsx#L221
> 
> I'll try again today or during the week, maybe the shortcut creation can be moved to that same place where the notification is displayed? seems like those 2 actions should be in the same place since both depend on the game being installed

If you think about it, we can trigger the shortcut creation from the frontend using the same call we use when clicking on the button on the game page. you can modify the `HandleGameStatus` function on the `GlobalState` to create the shortcut from the frontend after the download is completed successfully (progress > 95%). i think its is even more safer than doing it on the backend because not always the backend understand if the game was installed or not, since we don't check the percent there,
