### ISSUE TITLE
Launcher is brought to the fore after game is closed

### ISSUE THREAD

**Issue by Slater91** [Heroic-Games-Launcher/HeroicGamesLauncher#727]
**Describe the bug**
Once I finish my session and I close the game, the launcher is brought to the fore even if it is minimised.

**To Reproduce**

1. Open game
2. Play it
3. Close it

**Expected behavior**
The launcher keeps its state, whatever that is.

**Desktop (please complete the following information):**

- OS: KDE neon - Ubuntu 20.04
- Version: 1.10.3
- Game: any
- Wine/Proton version: any
- Hardware specs (RAM, CPU, GPU): not relevant here

**Comment by flavioislima** [comment]
Ok, will be fixed on next release! 👍🏽

**Comment by Slater91** [comment]
Thank you for your help and for your work on Heroic!

**Comment by Slater91** [comment]
This is again an issue, as the launcher is unminimised after the game closes.
