### ISSUE TITLE
Add filtering games by tags

### ISSUE THREAD

**Issue by kaz-us** [Heroic-Games-Launcher/HeroicGamesLauncher#728]
**Is your feature request related to a problem? Please describe.**
Improve understanding of the game genre and filtering games

**Describe the solution you'd like**
Show tags on the game page, and add filter on Library page.

**Describe alternatives you've considered**
Must visit the game page in EGS (=

**Additional context**
Info about game you get [here](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/blob/bba82269118a83d21f51a02edcc01095059e4a6f/electron/legendary/games.ts#L138-L141). And then you can find game tags in JSON_object►pages►0►data►meta►tags►... and store it.
If we can see the tags of the game, then you can add the ability to filter games in the games list by tags. Or, when clicking on a tag on a game page, show filtered games in the list of games.
Thanks!

**Comment by wiryfuture** [comment]
Gonna stale this and link to it on a bigger issue that covers more filter options #945
