### ISSUE TITLE
Importing already installed games doesn't work.

### ISSUE THREAD

**Issue by raphipod** [Heroic-Games-Launcher/HeroicGamesLauncher#734]
**Describe the bug**
Importing an already installed game won't work

**To Reproduce**

1. Install any game in your preferred location from Windows Epic
2. Switch to Linux (I removed Windows & installed Linux)
3. Download Heroic latest & install
4. Import game from preferred location in 1.

**Expected behavior**
Heroic should recognize the game and import it into the library.

**Desktop (please complete the following information):**

- OS: Arch Linux
- Game: Rocket League, but generally any
- Wine/Proton version:
- Hardware specs (RAM, CPU, GPU): Ryzen 5 3600, GTX1660S, 16 GB

**Additional context**

### Installed version: 1.10.3 from .pacman file

Games are installed on an external drive formatted with BTRFS.

**Debug information:**

Error occurred in handler for 'importGame': Error: Command failed: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary import-game Sugar '/run/media/rkerscher/Spiele/Epic/rocketleague'
[Core] INFO: Trying to re-use existing login session...
[Core] INFO: Found EGL install metadata, verifying...
Traceback (most recent call last):
  File "legendary/cli.py", line 2061, in <module>
  File "legendary/cli.py", line 2018, in main
  File "legendary/cli.py", line 1093, in import_game
  File "legendary/core.py", line 1260, in import_game
  File "legendary/core.py", line 842, in load_manifest
  File "legendary/models/manifest.py", line 91, in read_all
  File "legendary/models/manifest.py", line 530, in read
ValueError: Did not read entire chunk data list!
[62610] Failed to execute script 'cli' due to unhandled exception!

    at ChildProcess.exithandler (node:child_process:406:12)
    at ChildProcess.emit (node:events:394:28)
    at maybeClose (node:internal/child_process:1067:16)
    at Socket.<anonymous> (node:internal/child_process:453:11)
    at Socket.emit (node:events:394:28)
    at Pipe.<anonymous> (node:net:672:12) {
  killed: false,
  code: 1,
  signal: null,
  cmd: "/opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary import-game Sugar '/run/media/rkerscher/Spiele/Epic/rocketleague'",
  stdout: '',
  stderr: '[Core] INFO: Trying to re-use existing login session...\n' +
    '[Core] INFO: Found EGL install metadata, verifying...\n' +
    'Traceback (most recent call last):\n' +
    '  File "legendary/cli.py", line 2061, in <module>\n' +
    '  File "legendary/cli.py", line 2018, in main\n' +
    '  File "legendary/cli.py", line 1093, in import_game\n' +
    '  File "legendary/core.py", line 1260, in import_game\n' +
    '  File "legendary/core.py", line 842, in load_manifest\n' +
    '  File "legendary/models/manifest.py", line 91, in read_all\n' +
    '  File "legendary/models/manifest.py", line 530, in read\n' +
    'ValueError: Did not read entire chunk data list!\n' +
    "[62610] Failed to execute script 'cli' due to unhandled exception!\n"
}

**Comment by raphipod** [comment]
I already removed ~/.config/heroic/ and ~/.config/legendary, leaving me in the state of a new install of Heroic.
Still having the same issue. It's stuck.

![Bildschirmfoto vom 2021-11-06 20-37-15](https://user-images.githubusercontent.com/56308821/140621776-c7e5af32-93f2-4422-a210-c510a4a67550.png)

**Comment by raphipod** [comment]
Fixed in 1.11.0-alpha!

**Comment by flavioislima** [comment]
Nice that the alpha version fixed it. 👍🏽
