### ISSUE TITLE
No window opens on launching Heroic on MacOS 12 with Apple Silicon

### ISSUE THREAD

**Issue by navy5356** [Heroic-Games-Launcher/HeroicGamesLauncher#735]
**Describe the bug**
After installing Heroic and launching, the application starts but no window comes into view, making it unusable

**To Reproduce**

1. Install Heroic Launcher on an Apple Silicon (M1) Mac running MacOS 12 
2. Launch the app
3. The application starts but no window appears

**Expected behavior**
A window should come into focus allowing the user to log in and use the application

**Screenshots**
<img width="1440" alt="Screenshot 2021-11-07 at 1 23 49 PM" src="https://user-images.githubusercontent.com/42543177/140637121-9fad5083-dd8e-41b1-9f36-4c123f0b50d3.png">

**Desktop (please complete the following information):**

- OS: MacOS 12 Monterey
- Version [12.0.1]
- Hardware specs (RAM, CPU, GPU): 16GB, M1 (Apple Silicon)

**Additional context**
An earlier version of Heroic worked fine on the same system running MacOS 11 Big Sur

**Comment by flavioislima** [comment]
Which heroic version are you using?
Have you tried the Alpha on the releases page?

**Comment by navy5356** [comment]
Thanks for the reply, strangely, even though I had tried the 1.11.0 alpha build previously, running it once from the terminal seems to have fixed it. Furthermore, I deleted and reinstalled the application to make sure, but it now works fine.
