### ISSUE TITLE
DXVK problem with some game

### ISSUE THREAD

**Issue by amayra** [Heroic-Games-Launcher/HeroicGamesLauncher#737]
**Is your feature request related to a problem? Please describe.**
DXVK always crash out with Memory allocation failed 

**Describe the solution you'd like**
I went option to disable DXVK in some game 

**Describe alternatives you've considered**
add Gallium Nine option ?

**Additional context**
look like some iGPU don't like DXVK maybe

**Comment by flavioislima** [comment]
Sorry. No plans to support gallium.

**Comment by amayra** [comment]
how to disable DXVK ?

**Comment by flavioislima** [comment]
> how to disable DXVK ?

On the game settings:
Toggle the Auto-Install DXVK feature OFF and create a new game prefix.
