### ISSUE TITLE
Feature Request: Add a Setting to Create a Different Wine prefix for every game, automatically

### ISSUE THREAD

**Issue by ekianjo** [Heroic-Games-Launcher/HeroicGamesLauncher#738]
Hi there,
HeroicGamesLauncher is already great in the current state, I am wondering if you could consider implementing the following:

- typically you don't want to mix all your wine environments together for all games since it will cause breakage (especially when tweaks are needed with winecfg or winetricks), so while it's possible to create different wine prefixes one by one, making it automatic (at least as an option you could turn ON/OFF in the settings, application-wide) would be really practical. This is also more or less the approach taken by Proton on Steam (to isolate each game's environment from one another) for more robustness.

If such a setting is turned on, it would by default:

- put a different wine prefix folder for every game
- that folder's name could be following a standard pattern like .heroic-<game_name>-wine-prefix

Let me know what you think

**Comment by flavioislima** [comment]
Sounds good. The idea is to have also the option to choose the wine prefix on the install modal.
So when you click install from the library it would give you the option to choose the wine version and prefix, and create a new one.
But an option to create automatically could work as well.

**Comment by ekianjo** [comment]
Do you have any roadmap as to when you think this could be implemented?

**Comment by flavioislima** [comment]
Next version.
But I wont add a setting I'll add a select wine prefix on the install dialog and will generate a path with the game name. If the person doesn't want it, it can select another folder.
