### ISSUE TITLE
Option to launch native version of a game when possible, like in Steam.

### ISSUE THREAD

**Issue by IPlayZed** [Heroic-Games-Launcher/HeroicGamesLauncher#748]
**Is your feature request related to a problem? Please describe.**
It would be nice if there was an option to play the Linux native version when there is one for a given title.

**Describe the solution you'd like**
In Steam, it automatically installs the Linux native version when possible, but of course one can choose to use Proton as well. The launcher advanced a lot, but this feature is missing. It would be nice if I could choose the Linux native version when possible.

**Describe alternatives you've considered**
The possible alternatives would be basically Steam, as that is the only other platform providing a hassle-free approach.

**Comment by arielj** [comment]
Does Epic support native linux verions? I doubt it since they don't have a native linux client, I've never seen a linux logo for any game in Epic

**Comment by flavioislima** [comment]
Epic doesn't have the linux version for the games so its impossible to download and launch them for now.
