### ISSUE TITLE
Reset Heroic Games Launcher

### ISSUE THREAD

**Issue by Thomakk1** [Heroic-Games-Launcher/HeroicGamesLauncher#749]
Hi!

I tried to reset the Eric Games Launcher. I Wanted to change the user. But when I log out and log in with the new user, it always shows the library of the last user.

I also tried to delete the Application and download it new. But always I see the old library?

How I can reset the database? I also tried "Refresh Library", it doesn't work.

I have a MacBook Pro M1 with Monterey.

Thank you in forward!

**Comment by flavioislima** [comment]
Yes. I noticed that issue recently and it's related with the cache. We need to expire it after logout. I'll try to fix on next  release.
For now just remove the folder .config/heroic on your home folder.
It's a hidden folder so you need to configure finder to show it or use the terminal to delete it.

**Comment by Thomakk1** [comment]
Thank you very much!

**Comment by flavioislima** [comment]
implemented on v2.0
