### ISSUE TITLE
Forced to log in again after updating on Windows

### ISSUE THREAD

**Issue by dgw** [Heroic-Games-Launcher/HeroicGamesLauncher#751]
**Describe the bug**
Heroic requires going through the login process again after updating, even if the saved session is still valid.

**Logs**
I could not find any relevant logs for Heroic itself, or the installer; only for individual games.

**To Reproduce**

1. Have an older version (e.g. 1.10.2) of Heroic installed and logged in
2. Start Heroic, click Yes on the prompt to update, and download the package
3. During the download, confirm and note that Heroic is logged in
3. When the download is finished, quit Heroic and run the downloaded installer/updater
4. Start Heroic again
5. Heroic presents the login screen asking for SID number

**Expected behavior**
Heroic goes right back to the games list, as all that's changed is the application version. The stored login session should still work, as proved by the fact that it _did_ still work when starting Heroic the first time, before updating the application.

**Desktop (please complete the following information):**
- OS: Windows 10 Pro x64 21H1
- Heroic Version: 1.10.3
- Game: n/a
- Wine/Proton version: n/a
- Hardware specs (RAM, CPU, GPU): 64 GB RAM, Intel Core i9-11900H, Nvidia RTX 3080 Mobile 16GB

**Comment by flavioislima** [comment]
This is not a Heroic issue. If it asked for you to Login is because your login has expired and this happens with any other launcher like Steam and Uplay.
If you do not use Heroic for quite some time you need to login again to update your credentials.

**Comment by dgw** [comment]
Please read the reproducer again.

I opened Heroic and it _was_ logged in. Quitting, installing the update, and opening Heroic again showed the login screen. How is that an expired-session issue?

**Comment by flavioislima** [comment]
That's probably another issue related to the cache that is not expiring after the login has expired. so Heroic shows the list of games even if you click logout, it just shows the login page after restarting or walking though the app for quite some time until it understands that the login has expired. This will be fixed on the next version.

But If you're sure this is an issue, can you reproduce it again?

**Comment by dgw** [comment]
I have not been able to make this happen again, not exactly as described. The real issue is probably what you spoke of with the cache persisting after the session expires, which is supposed to be fixed in the next version. I will try to remember to test this in Heroic 1.11 when it comes out. (Do you know approximately how long it takes until the session expires if Heroic is not launched? Or if there's a way to manually expire the session while Heroic is not running, for testing?)

**Comment by flavioislima** [comment]
You can take a look at:
`{userFolder}/.config/.legendary/user.json` check for the expire date.

**Comment by dgw** [comment]
Perfect, thank you! I'll make sure my GitHub notifications are set for new releases and check 1.11 as soon as I can.
