### ISSUE TITLE
Add Support for Prime Render Offloading to AMD GPUs

### ISSUE THREAD

**Issue by jath03** [Heroic-Games-Launcher/HeroicGamesLauncher#754]
**Is your feature request related to a problem? Please describe.**
There is an easy switch in the global settings for nvidia prime rendering, but not for AMD cards.

**Describe the solution you'd like**
Implement a switch on the general settings page for AMD Prime Render, or generalize the existing prime render switch to work for both team red and green.  

**Describe alternatives you've considered**
I could always go through game by game and add `DRI_PRIME=1`  to the environment variables, but that seems unnecessary and easily fixable.  

**Additional context**
https://wiki.archlinux.org/title/PRIME#PRIME_GPU_offloading

**Comment by flavioislima** [comment]
You don't need it to setup Game by Game you can use add it on the Global Settings and all new games will inherit.

But I'll add it to the same option as Nvidia prime
