### ISSUE TITLE
First / Last Played date format shoud honour system date format

### ISSUE THREAD

**Issue by riksweeney** [Heroic-Games-Launcher/HeroicGamesLauncher#755]
The first / last played date format appears to be hard coded to mm/dd/yy (American) when using English language whereas my system is dd/mm/yy (British).

See attached screenshot

![Screenshot_20211122_181057](https://user-images.githubusercontent.com/12698517/142913560-f9d5c808-1970-40aa-968f-8135d763a1e5.png)

**Comment by flavioislima** [comment]
It's not hardcoded but I think we are using the app locale for that.
The correct should be use the system locale.
