### ISSUE TITLE
Unsafe game exit ? (Satisfactory "needs an update"  might force game/server versions mismatch) 

### ISSUE THREAD

**Issue by Ryder17z** [Heroic-Games-Launcher/HeroicGamesLauncher#757]
**Describe the bug**
Exiting and relaunching Satisfactory is "unsafe" because sometimes "game needs an update" which sometimes wrecks the ability to play on the server I was playing on earlier as an update is forced and I have to wait for the server to be updated to the same version before I can reconnect. 

**Add Logs**

[cli] INFO: Logging in...
[Core] INFO: Trying to re-use existing login session...
[cli] INFO: Checking for updates...
[Core] INFO: Getting authentication token...
[cli] INFO: Launching CrabTest...
fsync: up and running.
wine: RLIMIT_NICE is <= 20, unable to use setpriority safely

(wine:433188): GStreamer-WARNING : 08:25:16.154: Failed to load plugin '/home/exilefox/.steam/steam/steamapps/common/Proton 6.3/dist/lib64/gstreamer-1.0/libgstjpeg.so': libjpeg.so.62: cannot open shared object file: No such file or directory

(wine:433188): GStreamer-WARNING : 08:25:16.154: Failed to load plugin '/home/exilefox/.steam/steam/steamapps/common/Proton 6.3/dist/lib/gstreamer-1.0/libgstjpeg.so': /home/exilefox/.steam/steam/steamapps/common/Proton 6.3/dist/lib/gstreamer-1.0/libgstjpeg.so: wrong ELF class: ELFCLASS32
0188:fixme:vkd3d_dxbc_compiler_emit_output: Unhandled component index 1.
0194:fixme:vkd3d_dxbc_compiler_emit_output: Unhandled component index 1.
01a0:fixme:vkd3d_dxbc_compiler_check_index_range: Unhandled index range write mask 0x1 (0xf).
01a0:fixme:vkd3d_dxbc_compiler_emit_dcl_index_range: Ignoring dcl_index_range 0x2 3.
01ac:fixme:vkd3d_dxbc_compiler_check_index_range: Unhandled index range write mask 0x1 (0xf).
0188:fixme:vkd3d_dxbc_compiler_check_index_range: Unhandled index range write mask 0x1 (0xf).
01ac:fixme:vkd3d_dxbc_compiler_emit_dcl_index_range: Ignoring dcl_index_range 0x2 3.
0188:fixme:vkd3d_dxbc_compiler_emit_dcl_index_range: Ignoring dcl_index_range 0x2 3.
0178:fixme:vkd3d_dxbc_compiler_check_index_range: Unhandled index range write mask 0x1 (0xf).
0178:fixme:vkd3d_dxbc_compiler_emit_dcl_index_range: Ignoring dcl_index_range 0x2 3.
Unable to read VR Path Registry from C:\users\steamuser\AppData\Local\openvr\openvrpaths.vrpath
Unable to read VR Path Registry from C:\users\steamuser\AppData\Local\openvr\openvrpaths.vrpath

**To Reproduce**

1. Install Satisfactory (experimental version recommended) 
2. Connect to a server on same version as your game 
3. Exit game
4. Re-launch the game. 
5. "Game needs an update" message shows up in heroic. 
6. Clicking "No" does not correctly launch the game, but instead it will just show game logo, then a blank screen for a couple of seconds and then the process is closed. 
Clicking 'yes' does an update which could cause a mismatch between the game version and the server version. 

**Expected behavior**
It should not force updates like this. 

**Screenshots**
N/A

**Desktop (please complete the following information):**

- OS: Manjaro 
- Heroic: 1.10.3
- Game: Satisfactory 
- Wine/Proton version: Proton 6.3
- Hardware specs (RAM, CPU, GPU): 32GB, Ryzen 7 3800x, GTX 1080 (with nvidia drivers) 

**Additional context**
This has happened 5 times so far recently.

**Comment by flavioislima** [comment]
It's not heroic who forces the update, some games can only run when updated. Heroic just checks legendary info about an update, that comes from epic, and shows the message. You can try to launch the game without the update but not all games works.

**Comment by flavioislima** [comment]
Maybe check on our discord if someone else has a better clue about this.

**Comment by Ryder17z** [comment]
> This probably is an issue with Heroic losing command line arguments when adding the `--skip-version-check` flag here: https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/blob/00f7c29127de4e2d3b8ce355e522ecb764ed95fc/src/helpers/library.ts#L226

**Comment by flavioislima** [comment]
@Ryder17z 
As you can see here:
```DXVK_HUD=fps   WINEFSYNC=1     STEAM_COMPAT_CLIENT_INSTALL_PATH=/home/flavio/.steam/steam STEAM_COMPAT_DATA_PATH='/home/flavio/.proton-exp' /usr/bin/gamemoderun  /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary launch Min   --no-wine --wrapper "'/home/flavio/.steam/steam/steamapps/common/Proton - Experimental/proton' run"  --skip-version-check```

The parameter is being called correctly. You can click on Latest Log on the Game Page >  Tools to check the whole command.
But its like I said, not all games allows playing without update. Satisfactory is probably one of those.

**Comment by Ryder17z** [comment]
I don't know about that since it is not always an issue.

**Comment by flavioislima** [comment]
> I don't know about that since it is not always an issue. Sometimes it would be possible to relaunch multiple times without forcing an update.

So this might be a game issue. I dont think it's related with legendary or heroic since other games works just fine.
