### ISSUE TITLE
Feature Request: Don't always start store at Epic's home page

### ISSUE THREAD

**Issue by jath03** [Heroic-Games-Launcher/HeroicGamesLauncher#758]
**Is your feature request related to a problem? Please describe.**
It's kind of annoying how the store tab always starts you at the epic home page, instead of remembering where you were when you click off of it.

**Describe the solution you'd like**
Make it more like a browser tab, where if you click off of the tab, it doesn't forget everything about the tab and start you at your home page.

**Comment by dragonDScript** [comment]
It'd also be good to set a "start in" setting where you can set where you start. Some options would be library, store, etc.

**Comment by flavioislima** [comment]
The problem is how the Webview works. Unfortunately, I could not find a good way of getting the URL after changing the page. For some reason it's not reliable, it works sometimes and other doesn't.

But this should be simple. We just need to store the latest URL on Localstorage and then when opening the store again, start from this stored URL if any, or from the start page instead.

**Comment by dragonDScript** [comment]
> The problem is how the Webview works. Unfortunately, I could not find a good way of getting the URL after changing the page. For some reason it's not reliable, it works sometimes and other doesn't.
> 
> But this should be simple. We just need to store the latest URL on Localstorage and then when opening the store again, start from this stored URL if any, or from the start page instead.

You just need to store the URL in RAM and then when exiting save to a file in `~/.config/heroic`. You can use `<BrowserView>.webContents.on('will-navigate', (e, URL) => {})`

**Comment by aitor-gomila** [comment]
I think I can work on this

**Comment by jath03** [comment]
To be clear, this issue wasn't originally about saving the URL between runs of HGL.  I just got annoyed that the page I was looking at disappeared whenever you click away from the store.  For example, if I'm in the store tab and I'm looking at a specific game, then switch to my library and back to the store, I'm no longer seeing that game, I'm seeing the epic home page.  Just remembering the URL while the app is open would satisfy me.  If you want to go further, feel free.

**Comment by aitor-gomila** [comment]
That makes more sense. The webview should keep running in the background though, need to check why this happens

**Comment by aitor-gomila** [comment]
I think the problem has to do with how the BrowserView is coded. A single browserview with many routes that redirect to epic store, gog store, etc. A different webview for each tab would solve the issue. Am I right @flavioislima? What do you think about this change?

**Comment by flavioislima** [comment]
> I think the problem has to do with how the BrowserView is coded. A single browserview with many routes that redirect to epic store, gog store, etc. A different webview for each tab would solve the issue. Am I right @flavioislima? What do you think about this change?

We could try. I also think this is breaking the epic login for some reason, so I was thinking on refactoring the webview components in one per URL to see if it fixes it.
