### ISSUE TITLE
[Windows] Shortcuts are not created properly if the game name has invalid characters

### ISSUE THREAD

**Issue by Arron17** [Heroic-Games-Launcher/HeroicGamesLauncher#760]
### Try to get help on our Wiki first: https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/wiki/Troubleshooting

**Describe the bug**
If you try to create a shortcut for a game that uses characters that are invalid in Windows File names, then the creation of the shortcuts do not complete correctly.

**Add Logs**
No Logs are produced when clicking on Add Shortcut

**To Reproduce**

1. Go to a game that uses special characters that Windows can't use in a file name, for example "while True: learn()"
2. Click on Add shortcut
3. Message will appear to say a shortcut has been created on the Desktop and Start Menu
4. Shortcut on the Desktop is created, however it is called while True, has no icon and is a zero byte file, not a shortcut.
5. No shortcut is made in the start menu at all

**Expected behavior**
Needs to have some logic on Windows that stops it from trying to use Invalid characters in the shortcut filenames, added example screenshot:
![image](https://user-images.githubusercontent.com/87210034/144508325-5d746f90-00a2-4cea-9dde-36af5d1be96d.png)

**Desktop (please complete the following information):**

- OS: Windows 11 21H2
- Heroic Version 1.11.0 Alpha 
- Game: while True:learn()
- Wine/Proton version: N/A
- Hardware specs (RAM, CPU, GPU): N/A

**Comment by Arron17** [comment]
#740

**Comment by flavioislima** [comment]
I see. I'll try to fix this on next version!

**Comment by dragonDScript** [comment]
Please assign it to me.

**Comment by flavioislima** [comment]
> Please assign it to me.

Done!

**Comment by dragonDScript** [comment]
Can you download this build [here](https://drive.google.com/file/d/1aTrMCUEcqiSdqdYAOK8bgecZraVwjg3t/view?usp=sharing) and see if it works now? @Arron17

**Comment by Arron17** [comment]
@dragonDScript Same problem unfortunately.

![image](https://user-images.githubusercontent.com/87210034/144715560-9715a43f-6711-43cc-8c30-ca469e504896.png)

**Comment by dragonDScript** [comment]
> @dragonDScript Same problem unfortunately.
> 
> ![image](https://user-images.githubusercontent.com/87210034/144715560-9715a43f-6711-43cc-8c30-ca469e504896.png)
> 

Have you deleted and created the shortcut again? It should work.

**Comment by Arron17** [comment]
@dragonDScript Deleted shortcut and tried it again, uninstalled the game and tried it again, changed the location of the game install and tried again. Same result each time.

**Comment by dragonDScript** [comment]
OK I will test this myself.

**Comment by Dark-Matter7232** [comment]
![Screenshot 2022-06-09 153421](https://user-images.githubusercontent.com/38481036/172821990-ba43d5ec-06e4-4674-b3e8-e97467173ba5.png)

Issue still exists.

**Comment by flavioislima** [comment]
Fixed
