### ISSUE TITLE
[MacOS] Shortcuts to games

### ISSUE THREAD

**Issue by dragonDScript** [Heroic-Games-Launcher/HeroicGamesLauncher#763]
Shortcuts have only been implemented in Linux and Windows, so we need to implement Mac too.
Useful link: https://developer.apple.com/library/archive/documentation/FileManagement/Conceptual/FileSystemProgrammingGuide/AccessingFilesandDirectories/AccessingFilesandDirectories.html#//apple_ref/doc/uid/TP40010672-CH3-SW10

**Comment by arielj** [comment]
This is a duplicate of https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/issues/723
