### ISSUE TITLE
Add heroic to flatpak and MS Store

### ISSUE THREAD

**Issue by dragonDScript** [Heroic-Games-Launcher/HeroicGamesLauncher#764]
~~https://www.electronjs.org/docs/latest/tutorial/windows-store-guide~~
https://snapcraft.io/docs/electron-apps
https://docs.flatpak.org/en/latest/electron.html

**Comment by JakobDev** [comment]
For Flatpak take a look at #515

**Comment by derrod** [comment]
There's no need to package your app for the windows store anymore. With the new store you can simply provide a download link ti the installer and a command to silently install the app (through winget).
