### ISSUE TITLE
Add DXVK FPS Limit option

### ISSUE THREAD

**Issue by redromnon** [Heroic-Games-Launcher/HeroicGamesLauncher#767]
**Is your feature request related to a problem? Please describe.**
Sometimes one wants to limit the framerate to extend battery life, avoid heating issues, etc.

**Describe the solution you'd like**
Create an option to enter the framerate limit in General & Game Settings. It will basically add the following parameter `DXVK_FRAME_RATE=`.

**Describe alternatives you've considered**
Users can use GOverlay, edit MangoHUD's config file or add the above command in Advanced Options as env variable.

**Additional context**
None.

**Comment by flavioislima** [comment]
Do you know if there is a way to limit for VKD3D games as well?
Because DXVK will be for DX9, 10 and 11.

**Comment by redromnon** [comment]
> Do you know if there is a way to limit for VKD3D games as well? Because DXVK will be for DX9, 10 and 11.

It looks like there isn't a way for VKD3D unfortunately. Most of the environment variables listed are only for debugging purposes. I took a look at [vkd3d project on GitHub](https://github.com/HansKristian-Work/vkd3d-proton#environment-variables) & the [official readme file on WineHQ](https://wiki.winehq.org/Vkd3d).

**Comment by jarrard** [comment]
VKD3D project doesn't get updated as much as DXVK. Valve should put some effort into it since allot of games will be moving to DX12 soon. (such as getting fps limiter built in)

**Comment by redromnon** [comment]
> VKD3D project doesn't get updated as much as DXVK. Valve should put some effort into it since allot of games will be moving to DX12 soon. (such as getting fps limiter built in)

Agreed.
