### ISSUE TITLE
Adapt settings UI to the new sidebar

### ISSUE THREAD

**Issue by dragonDScript** [Heroic-Games-Launcher/HeroicGamesLauncher#768]

**Comment by flavioislima** [comment]
Wdym? I think looks good the way we have today.
What would you change?

**Comment by dragonDScript** [comment]
The current design is good for the old navbar. But looks bad now. I will make a PR to let you see

**Comment by wiryfuture** [comment]
@dragonDScript  More like this? 
![image](https://user-images.githubusercontent.com/50517631/149031246-cac9d781-1235-4a68-970d-0590fc036d0d.png)
![image](https://user-images.githubusercontent.com/50517631/149031271-04f6b384-2427-4570-a11e-8033d12cd95e.png)
![image](https://user-images.githubusercontent.com/50517631/149031295-8a6292d3-8aa7-482e-86e9-165827300fdd.png)
(and when in a specific game's settings too)
![image](https://user-images.githubusercontent.com/50517631/149031343-fbc6a276-0ad1-4401-baab-5e21a3283984.png)
![image](https://user-images.githubusercontent.com/50517631/149031369-ded748da-eb31-46e6-85d2-1e9a2afda3e9.png)

**Comment by dragonDScript** [comment]
Wow! That's what I imagined. Can you link your PR? Will contribute some code

**Comment by wiryfuture** [comment]
I think this can be closed now
