### ISSUE TITLE
Window not displayed

### ISSUE THREAD

**Issue by TomDev234** [Heroic-Games-Launcher/HeroicGamesLauncher#772]
### Try to get help on our Wiki first: https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/wiki/Troubleshooting

**Describe the bug**
The Heroic window is not displayed, only the window title bar appears, when running from Mac Crossover 21.1 on Monterey 12.0.1

**Add Logs**

**To Reproduce**

try to start it from Crossover

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS: macOS Monterey 12.0.1
- Heroic Version 1.10.3
- Game:
- Wine/Proton version: Crossover 21.1
- Hardware specs (RAM, CPU, GPU): 32GB G.Skill 4000MHz, i9-9900K, Radeon™ RX 6900 XT

**Additional context**

**Comment by flavioislima** [comment]
Have you tried any of the betas?

We also need more logs. Check the wiki on how to run Heroic from the terminal on Mac.

**Comment by Kaylebor** [comment]
I have the same issue (although I don't start the launcher from Crossover, but from the bundled binary downloaded from GitHub).

Here is an attempt at running it from the terminal, which I left running for 15 minutes or so:

```
INFO: [Legendary]: Location: /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/legendary
INFO: [Backend]:
  Heroic Version: 2.1.0 Rayleigh
  Legendary Version:  0.20.25 Our Benefactors
  OS: macOS KERNEL: 21.3.0 ARCH: x64
  CPU: Intel Core™ i7-1068NG7 @2.3
  RAM: Total: 17.2 GB Available: 10.1 GB
  GRAPHICS: GPU0: Intel Iris Plus Graphics VRAM: 1536MB DRIVER:


WARNING: [Backend]: Protocol already registered.
INFO: [Frontend]: Refreshing Library
INFO: [Legendary]: Refreshing library...
INFO: [Legendary]: Refreshing Epic Games...
INFO: [Legendary]: Refreshing Epic Games...
INFO: [Legendary]: [cli] INFO: Logging in...

INFO: [Legendary]: [Core] INFO: Trying to re-use existing login session...

INFO: [Backend]: checking for heroic updates
INFO: [Legendary]: [cli] INFO: Getting game list... (this may take a while)

INFO: [Legendary]: Updating game list
INFO: [Legendary]: Game List Updated
INFO: [Legendary]: Checking for game updates
INFO: [Legendary]: Found 0 game(s) to update
```

Of note: When I first logged in, the login process didn't seem to work too well (it never actually finished), but switching tabs made the launcher try to load my game library anyway.
Restarting the launcher after that broke it, and here we are.

In the meantime, a workaround is probably to delete my current Heroic profile, but I don't know where they are (would deleting configs be enough?)

**Comment by flavioislima** [comment]
@Kaylebor check if you have `write` permission on the `user.name/.config` folder.

**Comment by Kaylebor** [comment]
Is this good?

I don't have issues with other stuff on `~/.config`, like `yarn`

```
ls -ld ~/.config
drwxr-xr-x  27 <user.name>  staff  864 Jan 19 15:34 /Users/<user.name>/.config

ls -ld ~/.config/heroic
drwxr-xr-x  6 <user.name>  staff  192 Jan 30 10:23 /Users/<user.name>/.config/heroic

ls -ld ~/.config/legendary
drwxr-xr-x  11 <user.name>  staff  352 Jan 30 10:24 /Users/<user.name>/.config/legendary
```

**Comment by TomDev234** [comment]
How can I run Heroic with Wine from a Terminal?

**Comment by imLinguin** [comment]
https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/wiki/Troubleshooting#running-heroic-from-terminalpowershell-to-debug-errors
@TomDev234

**Comment by Nocccer** [comment]
Looks like you are missing something. Which os you are using and which heroic version? Do you run the appimage ?

**Comment by TomDev234** [comment]
I am using macOS 12.1 Monterey, Crossover 21.1, a Windows 7 64-bit Bottle and Heroic.2.1.1.exe

**Comment by Nocccer** [comment]
There you have it. Use the heroic mac version not the windows version

**Comment by TomDev234** [comment]
Oh sorry. Thanks for clearing up this misunderstanding.

**Comment by wiryfuture** [comment]
Incorrect binary used, non-issue.

**Comment by Kaylebor** [comment]
Is it really a non-issue? I ran the Mac binary from Brew and also ran into this problem, as seen [a few comments above](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/issues/772#issuecomment-1025109344)

I don't have it installed on my system anymore, but I will reinstall and try again to see if the issue persists.
I'm just saying this so that a potential bug on the launcher is not discarded exclusively from user error, since I am 100% positive I didn't use the Windows Heroic Launcher binary.

**Comment by flavioislima** [comment]
@Kaylebor try the beta 2.3.0

**Comment by wiryfuture** [comment]
> Is it really a non-issue? I ran the Mac binary from Brew and also ran into this problem, as seen [a few comments above](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/issues/772#issuecomment-1025109344)
> 
> I don't have it installed on my system anymore, but I will reinstall and try again to see if the issue persists. I'm just saying this so that a potential bug on the launcher is not discarded exclusively from user error, since I am 100% positive I didn't use the Windows Heroic Launcher binary.

If you think this may be an issue with the right binary, please could you check for us?
I dont think any of us have a macos machine to check this and it would be much appreciated.

**Comment by Kaylebor** [comment]
Nevermind - I installed the latest hotfix 2.2.6 (hotfix #5) from GitHub and it shows the window properly now.

So whatever happened, it's been fixed.

I'll let you know if it happens again, sorry, and thanks!
