### ISSUE TITLE
Packages Distributions

### ISSUE THREAD

**Issue by flavioislima** [Heroic-Games-Launcher/HeroicGamesLauncher#78]
This is a thread to request and track the packages and repositories that we will distribute Heroic.

So far we can continue the conversation started on: #6 #76 #30 and #54

**Comment by dvdmuckle** [comment]
For Fedora (and IMO Ubuntu) it might be easier to use something like PackageCloud. They're distribution agnostic and you can basically store any kind of package format in there, and unlike something like COPR, they don't require you build your packages in a certain way, so long as you have a package you can still push it there. That being said, while they do have a free tier they do at some point start having to charge, and for a bigger project like this it may be worth using COPR/PPA to publish packages without more cost. I'm going to investigate if electron-builder can be wrapped in a `.spec` file, which is what COPR wants.

**Comment by dvdmuckle** [comment]
After some further reading, I think a `.spec` file would need to be written to run on COPR. They don't really like using something besides a `.spec`. There are a couple generalized examples for an npm package. Alternatively, we could try something like generating the RPM with electron-builder in the `.spec` then unpacking it.

**Comment by flavioislima** [comment]
The spec would be something like this:

`
Summary: A Native Epic Games Launcher for Linux
Name: heroic
Version: 1.3.1
Release: 1
License: GPL
Group: Applications/Games
Source: https://github.com/flavioislima/HeroicGamesLauncher/releases/download/v1.3.1/heroic-1.3.1.x86_64.rpm
URL: https://github.com/flavioislima/HeroicGamesLauncher
Distribution: Fedora Linux
Vendor: Flavio Lima
Packager: Flavio Lima <flavioislima@gmail.com>

%description
Heroic is an Open Source Game Launcher for Linux. Right now it supports launching games from the Epic Games Store using Legendary, a Linux CLI alternative to launch epic games. Heroic is built with Web Technologies like Typescript, React, NodeJS and Electron.
`

**Comment by VortexAcherontic** [comment]
May I throw in OBS (open build service) which has support for various distributions including but not limited to: openSUSE (it's their default way of packaging), Fedora, Arch Linux, Ubuntu, Debian, RHEL and more.

https://build.opensuse.org/

**Comment by flavioislima** [comment]
> 
> 
> May I throw in OBS (open build service) which has [support](https://openbuildservice.org/help/manuals/obs-user-guide/cha.obs.package_formats.html) for various distributions including but not limited to: openSUSE (it's their default way of packaging), Fedora, Arch Linux, Ubuntu, Debian, RHEL and more.
> 
> https://build.opensuse.org/

Thats a great idea. I read something about it but could not get to understand it further. It is possible to publish the deb packages on a PPA for instance? and to a OpenSuse repo as well?

**Comment by VortexAcherontic** [comment]
For openSUSE yes, they will get automatically published (if enabled) and can be found at: https://software.opensuse.org/ and can easily be submitted to show up in any official repo.

You submit it, it gets reviewed, maybe they suggest some changes to the build instructions or the use for some macros and after it got accepted in the main repo you'll still have full access to that very package. So upon updates you do not need to make a new submit or request changes. You can work right with the package there.

Build for other distros can be found there as well here is an example: https://software.opensuse.org/package/kate but I do not know if there is a way to automatically integrate them with PPAs, AUR or other community repos of other distros.

Did not though about this as I made the suggestion sorry :/

I'll ask around in the forums maybe someone there can enlighten me :D

**Comment by tim77** [comment]
@flavioislima just my 2 cents: trying to make universal packages, force users to use 3rd-party repos for their distros — was never a good idea. Please allow maintainers do their job. If you want to make real, universal package consider Flatpak.

**Comment by flavioislima** [comment]
> @flavioislima just my 2 cents: trying to make universal packages, force users to use 3rd-party repos for their distros — was never a good idea. Please allow maintainers do their job. If you want to make real, universal package consider Flatpak.

Yeah. I was able to create a flatpak and it works, but heroic is lacking some features for me to be able to launch the flatpak version. But it is planned.

**Comment by DuttaAB-dev** [comment]
> > @flavioislima just my 2 cents: trying to make universal packages, force users to use 3rd-party repos for their distros — was never a good idea. Please allow maintainers do their job. If you want to make real, universal package consider Flatpak.
> 
> Yeah. I was able to create a flatpak and it works, but heroic is lacking some features for me to be able to launch the flatpak version. But it is planned.

It would be great to  have heroic as a flatpak! Maybe then you can add winetrics/wineconfig in the same package?

**Comment by adityaruplaha** [comment]
I personally think AppImages are great for this job. Not a huge fan of Snap or Flatpak.

**Comment by flavioislima** [comment]
> > > @flavioislima just my 2 cents: trying to make universal packages, force users to use 3rd-party repos for their distros — was never a good idea. Please allow maintainers do their job. If you want to make real, universal package consider Flatpak.
> > 
> > 
> > Yeah. I was able to create a flatpak and it works, but heroic is lacking some features for me to be able to launch the flatpak version. But it is planned.
> 
> It would be great to have heroic as a flatpak! Maybe then you can add winetrics/wineconfig in the same package?

I have created a flatpack before and we have the implementation for that. BUT, need more testing and I think I'll need to make it work with Steam Flatpak and Proton-GE Flatpak and also Wine flatpak, and we don't have dedicated team members to look after it now.
But the Heroic Flatpak exists and it works (at least login and downloading a game, launching needs the above)

Maybe we will be able to have a feature to download Wine and Proton from Heroic as well, this way we wont depend on external ones.

**Comment by DuttaAB-dev** [comment]
Well, is winetricks a necessity to launch games? As most games fail to launch without it.

**Comment by flavioislima** [comment]
> Well, is winetricks a necessity to launch games? As most games fail to launch without it.

No, its not necessary. Winetricks its a tool that is used to install other windows dependencies that the game might have.
But in general, its not needed.

**Comment by dvdmuckle** [comment]
I see what you mean, looking at the spec file, that is indeed better than nothing but not ideal. I can take on as much as I can but considering the state of Electron with Fedora builds, the first two things might be hard to pull off. In any case, I can try this out. Are there any other third party package builds of Electron apps that would make for good references?

**Comment by aha999** [comment]
Will you post the Flatpak to Flathub ? That way Heroic could be conveniently downloadable in Linux' app stores instead of installing/updating manually.

**Comment by flavioislima** [comment]
> Will you post the Flatpak to Flathub ? That way Heroic could be conveniently downloadable in Linux' app stores instead of installing/updating manually.

If I can make it to work one day, ofc. But for now I have the package but has several bugs.

**Comment by tim77** [comment]
Maybe @gasinvein could help us with packaging Flatpak? Also @flavioislima you can always ask for great community support [here](https://matrix.to/#/#flatpak:matrix.org).

**Comment by TheEvilSkeleton** [comment]
There's also https://discourse.flathub.org/.

**Comment by Eric1212** [comment]
For linux, FlatPak distribution is the best for that kind of ever-updating app. Hope https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/pull/515 will end well.

**Comment by TheEvilSkeleton** [comment]
WINE Flatpak is now merged and available on Flathub! https://github.com/flathub/flathub/pull/2845#issuecomment-1054573555

**Comment by pktiuk** [comment]
> For linux, FlatPak distribution is the best for that kind of ever-updating app. Hope #515 will end well.

It would also allow easy installation of Epic and GOG games on Steam Deck. :smile:  #popularity_boost
