### ISSUE TITLE
Download Improvements

### ISSUE THREAD

**Issue by Arr4y** [Heroic-Games-Launcher/HeroicGamesLauncher#780]
**Is your feature request related to a problem? Please describe.**
Although downloading doesn't have to be complex, there are a few features that make downloading feel more fluid. Downloading one thing at a time to later on come back and remember that you want to download another thing or having to use up too much or too little resources can make downloading a bit more frustrating.

**Describe the solution you'd like**
These few download features should be added:
-> Limit download speeds (to prevent network hogging; for example: my network is 7mbps and downloading gigabytes makes using the internet a living hell when most of it is used up)
-> Download queues (again, I don't want to forget about downloading some game, wake up in the middle of the night to start another download, or just have to click that download button every few hours or so)
--> Download queue ordering (reordering downloads makes downloading some games sooner rather than later a blessing)
-> Concurrent downloads (downloading multiple games at the same time can speed up downloading, especially when downloading slows down or stops for a bit in one download)

**Describe alternatives you've considered**
Epic Games Launcher? It's counter intuitive if you ask me.

**Additional context**
Description says it all.

**Comment by wiryfuture** [comment]
Added feature req as a comment on #457
