### ISSUE TITLE
Alternative Legendary Path not being recognized

### ISSUE THREAD

**Issue by WolfangAukang** [Heroic-Games-Launcher/HeroicGamesLauncher#781]
### Try to get help on our Wiki first: https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/wiki/Troubleshooting

**Describe the bug**

I need to use a custom path for Legendary. I have set it on the Settings and the config file is showing it as expected:
```
{
  "defaultSettings": {
    "altLegendaryBin": "'/home/bjorn/Projektujo/Aliaj/nixpkgs/result/bin/legendary'",
```

But when I try to execute a game, it uses another Legendary path. See logs below.

**Add Logs**

```
·> ./result/bin/heroic
INFO: Trying to get user information
INFO: Trying to get user information
INFO: Trying to get user information
[43:1211/191240.880478:ERROR:sandbox_linux.cc(374)] InitializeSandbox() called with multiple threads in process gpu-process.
ERROR: Failed to register protocol with OS.
[2:1211/191240.908760:ERROR:browser_main_loop.cc(269)] Gtk: gtk_widget_add_accelerator: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed
WARNING: python command not found
INFO: Command 'python3' found. Version: '3.8.12'
INFO: Frontend: Refreshing Library
INFO: Refreshing library...
INFO: Legendary: Refreshing Epic Games...
INFO: Refreshing Epic Games...
[cli] INFO: Logging in...

[Core] INFO: Trying to re-use existing login session...

[cli] INFO: Getting game list... (this may take a while)

INFO: Updating game list
INFO: Game List Updated
INFO: Checking for game updates
INFO: Found 0 game(s) to update
INFO: launching Genshin Impact 41869934302e4b8cafac2d3c0e7c293d
INFO: Trying to get user information
WARNING: GameMode not installed
INFO:
 Launch Command:              /nix/store/dsa4vgnhw0mgknnqd1sanlb0ssaahyy0-heroic-1.10.3-extracted/resources/app.asar.unpacked/build/bin/linux/legendary launch 41869934302e4b8cafac2d3c0e7c293d   --wine /etc/profiles/per-user/bjorn/bin/wine --wine-prefix '/home/bjorn/.wine'
INFO: Trying to get user information
INFO: checking for heroic updates
INFO: Stopping Discord Rich Presence if running...
INFO: Stopped Discord Rich Presence.
INFO: Saving log file to /home/bjorn/.config/heroic/Crash Reports/Sat Dec 11 2021.txt
```

Crash report is empty. The launch command is executing a legendary path that seems to be the default, that I want to avoid because it won't work on NixOS, that's why I'm using another path for Legendary.

**To Reproduce**

1. Go to 'Settings'
2. Change value for 'Choose an alternative Legendary Binary to use'
3. Go to Library
4. Run any game
5. Check Launch Command (not using alt path)

**Expected behavior**
Application will use alternative path to run game.

**Screenshots**

**Desktop (please complete the following information):**

- OS: NixOS
- Heroic Version 1.10.3
- Genshin Impact (although it applies to any game)
- Wine/Proton version: 6.0.2|6.3
- Hardware specs (RAM, CPU, GPU): I think they wouldn't matter for this case :)

**Additional context**

Although this is not on an OS that is officially supported, I think that as long as the application can use the alternative path for Legendary, it would be enough to solve the issue.

**Comment by flavioislima** [comment]
Can you try this on the beta release?

**Comment by flavioislima** [comment]
Confirmed the bug, I'll fix it on next release.

**Comment by WolfangAukang** [comment]
Thank you very much!
