### ISSUE TITLE
Wine version not found with CrossOver 21.1 installed

### ISSUE THREAD

**Issue by wenhhh** [Heroic-Games-Launcher/HeroicGamesLauncher#784]
### Try to get help on our Wiki first: https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/wiki/Troubleshooting

**Describe the bug**
Wine version not found with CrossOver 21.1 installed

**Add Logs**

INFO: Trying to get user information
INFO: Trying to get user information
INFO: Trying to get user information
WARNING: Protocol already registered.
INFO: Frontend: Refreshing Library
INFO: Refreshing library...
INFO: Legendary: Refreshing Epic Games...
INFO: Refreshing Epic Games...
INFO: Trying to get user information
INFO: checking for heroic updates
[Core] WARNING: Could not determine locale, falling back to en-US

[cli] INFO: Logging in...

[Core] INFO: Trying to re-use existing login session...

[cli] INFO: Getting game list... (this may take a while)

**To Reproduce**

1. Go to 'Settings'
2. Click on 'Wine'
3. See error 'Wine version not found '

**Expected behavior**
CrossOver 21.1 in Wine Version Field

**Screenshots**
<img width="617" alt="iShot2021-12-15 21 18 09" src="https://user-images.githubusercontent.com/19700679/146195780-5275f31a-866b-4b88-985d-945692b2f4ea.png">

**Desktop (please complete the following information):**

- OS: MacOS 12.1
- Heroic Version 1.10.3
- Game:-
- Wine/Proton version: CrossOver 21.1
- Hardware specs (RAM, CPU, GPU): MacBook Pro 2021 with M1 Max chip

**Additional context**

**Comment by wenhhh** [comment]
CrossOver appeared after the first game installation.

**Comment by EugeneKey** [comment]
> CrossOver appeared after the first game installation.

Have the same issue. I installed game, but nothing changed. Maybe something else was needed to solve this?
