### ISSUE TITLE
Blank screen accessing specific game page (Chicory: A Colorful Tale)

### ISSUE THREAD

**Issue by AdrienLombard** [Heroic-Games-Launcher/HeroicGamesLauncher#785]
### Try to get help on our Wiki first: https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/wiki/Troubleshooting

**Describe the bug**
Blank screen when specifically clicking on "Chicory: A Colorful Tale" in my library

**Add Logs**

[22664:1216/105437.815730:INFO:CONSOLE(2)] "TypeError: Cannot read properties of undefined (reading 'length')", source: file:///opt/Heroic/resources/app.asar/build/static/js/3.a346c093.chunk.js (2)
[22664:1216/105437.818530:INFO:CONSOLE(1)] "Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'length')", source: file:///opt/Heroic/resources/app.asar/build/static/js/5.99c8c3e0.chunk.js (1)

**To Reproduce**

1. Start Heroic
2. Go to Library with filter set to "All" 
3. Click on "Chicory: A Colorful Tale" entry (not the install button)
4. Screen goes blank

**Expected behavior**
Game page should appear

**Screenshots**
[https://i.ibb.co/nfZXfvD/Capture-d-cran-de-2021-12-16-10-57-35.png](https://i.ibb.co/nfZXfvD/Capture-d-cran-de-2021-12-16-10-57-35.png)

**Desktop (please complete the following information):**

- OS: Manjaro Linux
- Heroic Version: 1.10.3
- Game: Chicory: A Colorful Tale
- Wine/Proton version: Wine 6.23
- Hardware specs (RAM, CPU, GPU): 32GB, AMD Ryzen 7 5700G

**Additional context**
The problem does not seem to exist on any other game of my library.
If I click the "install" button of Chicory directly from the library, it seems to install correctly
I tried to delete ~/.config/heroic and ~/.config/legendary as suggested in the troubleshooting section of the wiki, without success.

**Comment by flavioislima** [comment]
Did commit a possible fix to it. So should be fixed on next release.

**Comment by AdrienLombard** [comment]
The problem doesn't seem to be solved by the new release, but the error message in the logs slightly changed. Created issue #831 for the new error.
