### ISSUE TITLE
Language bug

### ISSUE THREAD

**Issue by qiuzhangsaer** [Heroic-Games-Launcher/HeroicGamesLauncher#789]
**Describe the bug**
When set to simplified Chinese, the game introduction is in English

**Screenshots**
Chinese Simplified：
![image](https://user-images.githubusercontent.com/57931039/146490263-cfea09b6-3f7c-4d43-853b-bb3a3eca83a0.png)
Chinese Traditional：
![image](https://user-images.githubusercontent.com/57931039/146490479-f26f972d-22c1-4800-bc4b-6637647b1b4b.png)

**Desktop:**
- OS: Windows10
- Heroic Version :Heroic.Portable.1.10.3

**Comment by flavioislima** [comment]
Can you send me the link to this game on Epic Game Store where the description is in Simplified Chinese?
Because this description is automated and we just get the info from the Epic store. But we could be getting using the wrong locale so that might be the bug.

**Comment by qiuzhangsaer** [comment]
> Can you send me the link to this game on Epic Game Store where the description is in Simplified Chinese? Because this description is automated and we just get the info from the Epic store. But we could be getting using the wrong locale so that might be the bug.

https://www.epicgames.com/store/zh-CN/p/ark

Not just this game, all games have this problem

**Comment by qiuzhangsaer** [comment]
https://www.epicgames.com/store/zh-CN/p/ark

Not just this game, all games have this problem

**Comment by flavioislima** [comment]
Ok found a Fix.
Next version will have it 👍🏽 

![image](https://user-images.githubusercontent.com/26871415/146671174-61290815-9aea-4385-8a04-b3edab608828.png)
