### ISSUE TITLE
Custom themes

### ISSUE THREAD

**Issue by sheeepdev** [Heroic-Games-Launcher/HeroicGamesLauncher#791]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
I would love if custom themes could be implemented, since this is an electron application I dont think it would be hard to implement it.

**Describe alternatives you've considered**
Modifing the files, maybe?

**Comment by flavioislima** [comment]
This is planned, just didn't have time to work on it yet·
