### ISSUE TITLE
Add option to enable/disable GPU acceleration

### ISSUE THREAD

**Issue by fubar-coder** [Heroic-Games-Launcher/HeroicGamesLauncher#797]
**Is your feature request related to a problem? Please describe.**

I installed the nvidia-495 driver and all chrome/electron apps don't render correctly (or at all) anymore. There are two possible workarounds:

* Disable hardware acceleration (e.g. via command line argument  `--disable-gpu`)
* Enable Vulkan support

Currently, I always have to start the launcher with the `--disable-gpu` argument.

**Describe the solution you'd like**

It would be nice if the app would be built with disabled hardware acceleration by default, because the launcher is fast enough even when using the software renderer.

An additional configuration option to enable hardware rendering would be useful, if hardware accelerated rendering is disabled by default.

**Describe alternatives you've considered**

* Changing the `.desktop` file to include the `--disable-gpu` argument
* Creating a new `.desktop` file on the deskop

**Additional context**

**Comment by flavioislima** [comment]
I don't know why you have this because I'm also on this nvidia driver version and have no issues with it.
No Chrome or electron apps are slow for me. Perhaps you're using wayland and are missing some settings.

**Comment by fubar-coder** [comment]
You're right. I use wayland, because Gnome on X11 is too buggy for me.

**Comment by wiryfuture** [comment]
Heroic is a platform for running games (which are a gpu hardware accelerated workload), so disabling gpu hardware acceleration for the launcher itself by default doesn't make sense. 
I suppose that given a slow enough gpu, disabling hardware acceleration in the launcher could be a feasible request (or for some other reason, just **not by default**.

**Comment by vic-bay** [comment]
> Heroic is a platform for running games (which are a gpu hardware accelerated workload), so disabling gpu hardware acceleration for the launcher itself by default doesn't make sense. I suppose that given a slow enough gpu, disabling hardware acceleration in the launcher could be a feasible request (or for some other reason, just **not by default**.

There is a good reason why disabling gpu acceleration should at least be an option in the settings. GPU accelerated apps take some dedicated GPU memory, around 300MiB for heroic launcher in my case, reported by nvtop. Even when it is minimized to tray. 

Add a browser and discord on second display, and suddenly 1GiB of VRAM is gone. 

As far as I know, Linux doesn't page in and out VRAM contents to RAM in favour of programs that need dedicated VRAM the most (games). So as soon as 100% VRAM is used and a game has at least some textures in system RAM, you get double or triple FPS drop. In some dumb games, for example Skyrim, in torture scenarios (a lot of high resolution texture mods).

**Comment by FakeMichau** [comment]
After playing for a while I've seen heroic use 2100MiB of VRAM when at the same time Discord was using 200MiB. 
``--disable-gpu`` of course works but in my opinion 2GiB of VRAM usage for a launcher is just too much to not include a fix directly in settings.

I looked at issues and haven't seen anything mentioning such high VRAM usage so that's probably worth looking into by itself.
