### ISSUE TITLE
Heroic shows blank screen while trying to load specific game in library ( cyberpunk 2077 )

### ISSUE THREAD

**Issue by r6deadinside** [Heroic-Games-Launcher/HeroicGamesLauncher#800]
### Try to get help on our Wiki first: https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/wiki/Troubleshooting

**Describe the bug**
Blank screen while trying load cyberpunk 2077 in library
Also cyberpunk icon looks kinda crappy

**Add Logs**

Check on how to [run Heroic from Terminal or Powershell](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/wiki/Troubleshooting#running-heroic-from-terminalpowershell-to-debug-errors) and put some logs here: it's empty

**To Reproduce**

1. Go to heroic
2. Click on cyberpunk
3. See blank screen

**Expected behavior**
I want to see game page!

**Screenshots**
https://i.imgur.com/n39tCFd.png -> blank screen
https://i.imgur.com/Jfkq6uS.png -> icon
For some reason for bonus content it works as it should -> https://i.imgur.com/YyCoNYl.png

**Desktop (please complete the following information):**

- OS: Gentoo Gnu/Linux
- Heroic Version [1.10.3]
- Game: Cyberpunk
- Wine/Proton version: Wine TKG 6.17
- Hardware specs (RAM, CPU, GPU):
- CPU: AMD Ryzen 5 5600x
- GPU: AMD Rx 580 8g
- g.skill trident z neo 2x16 

**Additional context**
Not installing if i press install button
Tried to delete `$XDG_CONFIG_HOME/legendary` and `$XDG_CONFIG_HOME/heroic`

**Comment by gutyina70** [comment]
I have a similar issue, instead of the game's page going blank, the loding icon just spins forever (i waited for 6 hours and it was still spinning).
This has been happening since the big UI change.

**Comment by flavioislima** [comment]
Duplicated of #720
Fixed today, will be fixed on next release.
On that issue I provided a heroic appimage that you can use to download cyberpunk if you want.
