### ISSUE TITLE
Running Heroic from App Menu makes the app unusable

### ISSUE THREAD

**Issue by gutyina70** [Heroic-Games-Launcher/HeroicGamesLauncher#801]
**Describe the bug**
Starting Heroic from gnome applications makes the app unusable. **Note: the bug doesn't occur when starting it from terminal.**
Clicking on an installed game in the library or the global settings makes the loading icon spin forever. Closing it without using process managers is impossible, it's unresponsive to Super+Q or X at the top right corner.
The whole application is just slow.

**Add Logs**
Since this bug doesn't occur when starting the app from terminal, I can't provide any logs.

**To Reproduce**
1. Install Heroic from .deb using dpkg
2. Open applications on a gnome system and start Heroic
3. Try to close the window, you can't

**Expected behavior**
I expect starting from the applications to work as well as starting from terminal.

**Screenshots**
![image](https://user-images.githubusercontent.com/29818440/146693596-45e98288-9e61-42bd-bec0-d984c0fa1435.png)

**Desktop (please complete the following information):**
- OS: Pop!_OS
- Heroic Version: 1.11.0-beta-2
- Game: -
- Wine/Proton version: - / wine-7.0-rc2 / proton 6.3
- Hardware specs (RAM, CPU, GPU):
> 00:00.0 Host bridge: Intel Corporation Xeon E3-1200 v5/E3-1500 v5/6th Gen Core Processor Host Bridge/DRAM Registers (rev 07)
> 00:01.0 PCI bridge: Intel Corporation 6th-10th Gen Core Processor PCIe Controller (x16) (rev 07)
> 00:08.0 System peripheral: Intel Corporation Xeon E3-1200 v5/v6 / E3-1500 v5 / 6th/7th/8th Gen Core Processor Gaussian Mixture Model
> 00:14.0 USB controller: Intel Corporation 100 Series/C230 Series Chipset Family USB 3.0 xHCI Controller (rev 31)
> 00:14.2 Signal processing controller: Intel Corporation 100 Series/C230 Series Chipset Family Thermal Subsystem (rev 31)
> 00:16.0 Communication controller: Intel Corporation 100 Series/C230 Series Chipset Family MEI Controller #1 (rev 31)
> 00:17.0 SATA controller: Intel Corporation Q170/Q150/B150/H170/H110/Z170/CM236 Chipset SATA Controller [AHCI Mode] (rev 31)
> 00:1c.0 PCI bridge: Intel Corporation 100 Series/C230 Series Chipset Family PCI Express Root Port #5 (rev f1)
> 00:1c.6 PCI bridge: Intel Corporation 100 Series/C230 Series Chipset Family PCI Express Root Port #7 (rev f1)
> 00:1f.0 ISA bridge: Intel Corporation H110 Chipset LPC/eSPI Controller (rev 31)
> 00:1f.2 Memory controller: Intel Corporation 100 Series/C230 Series Chipset Family Power Management Controller (rev 31)
> 00:1f.3 Audio device: Intel Corporation 100 Series/C230 Series Chipset Family HD Audio Controller (rev 31)
> 00:1f.4 SMBus: Intel Corporation 100 Series/C230 Series Chipset Family SMBus (rev 31)
> 01:00.0 VGA compatible controller: NVIDIA Corporation GP107 [GeForce GTX 1050 Ti] (rev a1)
> 01:00.1 Audio device: NVIDIA Corporation GP107GL High Definition Audio Controller (rev a1)
> 02:00.0 Ethernet controller: Realtek Semiconductor Co., Ltd. RTL8111/8168/8411 PCI Express Gigabit Ethernet Controller (rev 15)
> 03:00.0 Network controller: Realtek Semiconductor Co., Ltd. RTL8192EE PCIe Wireless Network Adapter

**Additional context**
This bug is only happening since the UI redesign (from 1.11.0 Beta to 1.11.0 Beta-2 which is the latest as of now)

**Comment by flavioislima** [comment]
Hi.
I'm aware of that, some people has talked about on our discord.
Unfortunately this is really difficult to trace, and it's only affecting Gnome or at least only Debian based distros like ubuntu and pop.
I have some suspicious that might be a bug on electron 16 so I'll compile heroic using version 15.3 that is the one used on the alpha.
I can send a deb file tomorrow for testing.

**Comment by gutyina70** [comment]
Alright, I'd be happy to test it.

**Comment by PixsaOJ** [comment]
Same problem, how can i help?

**Comment by flavioislima** [comment]
@gutyina70 @PixsaOJ 
I think my suspicions were correct. can you try this:
https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/releases/download/v1.11.0-beta.2/heroic_1.11.0-beta.3.electron.15_amd64.deb

I tested on a VM with pop 21.04 and the normal deb gives me really slow behavior and this other one works fine.

**Comment by PixsaOJ** [comment]
Yup, works fine

**Comment by flavioislima** [comment]
Good, I'll release a fix later today after work hours.

**Comment by MaoDzeDun** [comment]
I can confirm the issue persists on Pop OS 21.10 even with the new beta. Opening the appimage from the file browser causes it to severely lag and eventually crash. Running it through terminal makes everything snappy and responsive.

**Comment by PixsaOJ** [comment]
> I can confirm the issue persists on Pop OS 21.10 even with the new beta. Opening the appimage from the file browser causes it to severely lag and eventually crash. Running it through terminal makes everything snappy and responsive.

Yes I am on Pop OS 21.10 too, it is now fixed you can download from link above. Electron 16 issue.

**Comment by flavioislima** [comment]
> > I can confirm the issue persists on Pop OS 21.10 even with the new beta. Opening the appimage from the file browser causes it to severely lag and eventually crash. Running it through terminal makes everything snappy and responsive.
> 
> Yes I am on Pop OS 21.10 too, it is now fixed you can download from link above. Electron 16 issue.

Yes, the issue was fixed but I'm making more tests. For now I've updated the deb file for beta 2, so download and install that. The appimage doesn't have the fix.

**Comment by flavioislima** [comment]
Fixed on Beta 3
