### ISSUE TITLE
Stuck on checking for updates

### ISSUE THREAD

**Issue by StrangerGithuber** [Heroic-Games-Launcher/HeroicGamesLauncher#807]
Hello
I have Linux Mint and I used the deb version to install the app.

The app asked for sid so I gave it and it stuck on game list loading. So I restarted the app and opened from terminal to see the texts what happens. The reason why the app doesn't for me it seems it stuck on the checking for updates.

Maybe I am missing something to able running this app.
Screenshot:
![image](https://user-images.githubusercontent.com/1939827/146990049-851f224b-c83b-47ae-b8a1-8e3ac06d17e7.png)

What I can do?

Update: I used the _apt install python-is-python3_ command but it didn't help much, just disappeared the python error. Then no idea why it doesn't go through the heroic update checking.

**Comment by flavioislima** [comment]
can you try the new beta 3?

**Comment by StrangerGithuber** [comment]
I will try and check when I have time, working as a horse currently.🤣

**Comment by flavioislima** [comment]
I know the feeling 😅

**Comment by StrangerGithuber** [comment]
Yep it works with beta 3. Thanks.
