### ISSUE TITLE
No game installs with 1.11.0-beta.2 (and beta 3) on Mac

### ISSUE THREAD

**Issue by Stooovie** [Heroic-Games-Launcher/HeroicGamesLauncher#812]
**Describe the bug**

No game installs with1.11.0-beta.2. It displays "Installation 0%" and then quietly stops without any error message, game not installed. Issue was not present on 1.11.0 alpha

**Add Logs**

INFO: checking for heroic updates
INFO: Trying to get user information
INFO: Installing Bulbul with: /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/legendary install Bulbul --base-path '/Volumes/4TB/Games' --skip-dlcs --skip-sdl  -y |& tee "/Users/stooovie/.config/heroic/GamesConfig/Bulbul.log"
INFO: Progress: Bulbul /MiB/undefined
INFO: Progress: Bulbul /MiB/undefined
INFO: Progress: Bulbul /MiB/undefined
INFO: Progress: Bulbul /MiB/undefined
INFO: finished installing
INFO: Frontend: Refreshing Library
INFO: Refreshing library...
INFO: Updating game list
INFO: Game List Updated

**To Reproduce**

Install any game.

**Expected behavior**
Game installs.

**Screenshots**

**Desktop (please complete the following information):**

- OS: MacOS Monterey 12.1
- Heroic Version 1.11.0-beta.2 
- Game: any
- Wine/Proton version: Crossover 21.1

**Additional context**
Same with any game. Games that are already installed continue to work.

**Comment by flavioislima** [comment]
@Stooovie check the new beta, has several bugfixes and improvements for the Mac version.
Which game is that?

**Comment by Stooovie** [comment]
For example MudRunner and Sonic Mania. Both still not installing on the latest beta 3.

**Comment by Stooovie** [comment]
Most games do not install. Tried: Ape Out, 20XX, Abzu, The Talos Principle

Only the smallest games like A Short Hike or Dolores: A Thimbleweed Park do install, which may be pertinent. There's almost 3 TB free on the target HFS+ drive and permissions are ignored (it's not the system drive).

I did not encounter this issue with the alpha, ever.

**Comment by Dattito** [comment]
GTA V also doesn't download

**Comment by flavioislima** [comment]
@Stooovie can you paste this command on the terminal?
` /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/legendary install Bulbul --base-path '/Volumes/4TB/Games' --skip-dlcs --skip-sdl`

**Comment by Stooovie** [comment]
This happens:

`➜  MacOS /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/legendary install Bulbul --base-path '/Volumes/4TB/Games' --skip-dlcs --skip-sdl
[Core] INFO: Logging in...
[Core] INFO: Fetching metadata for 8 app(s).
[cli] INFO: Preparing download for "MudRunner" (Bulbul)...
[Core] INFO: Parsing game manifest...
[Core] INFO: Install path: /Volumes/GAMES/MudRunner
[Core] INFO: Selected CDN: download.epicgames.com (https)
[cli] INFO: Download size is 0, the game is either already up to date or has not changed. Exiting...`

**Comment by flavioislima** [comment]
It's like the game is installed on that folder already. whats in there?

**Comment by Stooovie** [comment]
there IS a disk named GAMES but it's a Windows NTFS drive that is unmounted in MacOS (I use it in Bootcamp).

**Comment by flavioislima** [comment]
So check this file:
`.config/legendary/installed.json` and check if the game appears there. Because it seems the game is already installed but in a different folder.

Or just rename the whole folder and login again and try to install the game.

**Comment by Stooovie** [comment]
Hi, no, Mudrunner is NOT in the installed.json file. Something else is amiss. Also, as I said, the GAMES volume is never mounted in MacOS. Logging out and back in did not fix the issue. It still says "installing" for a couple of seconds and then the Install button gets back without any message. Game is not installed.

**Comment by flavioislima** [comment]
Try to install the game on your home folder to see if it works.

**Comment by Stooovie** [comment]
it doesn't, no. same thing. I had a theory that only small games (2 GB or less) installed, but no, I have Batman Arkham Asylum (9GB) installed and working. Most games do not install at all though. It's very weird.

**Comment by flavioislima** [comment]
Yes. You're sure you have write permissions on those folders as well?

Have you tried renaming the legendary folder like I said?

**Comment by Stooovie** [comment]
Yes, I do have write permissions to everything in my Home folder and on the 4TB, perms are ignored for the whole drive (as default for secondary drives in MacOS).

I have tried deleting the .config/legendary folder altogether (zipping for backup first), zapping Heroic with AppDelete, reinstall, still the same thing.

**Comment by Stooovie** [comment]
Reinstalled the 1.11.0-alpha, it works as expected...

**Comment by flavioislima** [comment]
Hmm, so I have a guess on what might be happening.
Since heroic beta 2 we are supporting native mac games, so I guess that games that have both versions might be the issue.

To confirm that, install heroic beta 3 again and go to the folder that Mac store application data, like AppData on windows. I forgot to add the path to the wiki and I'm not at home now.
But you should find a folder called store and inside it a few json files. One of them should be installInfo.json

Perhaps delete all of them, this will clear heroic cache.

**Comment by flavioislima** [comment]
This folder:
`~/Library/Application Support/Heroic/`

**Comment by Stooovie** [comment]
Ok, I have removed the entire ~/Library/Application Support/Heroic/ folder, deleted Heroic 1.11.0-alpha, emptied the Trash, installed beta 3. 

I can confirm that both Shadowrun: Hong Kong and Mudrunner that I WAS able to install with 1.11.0-alpha, I AM NOT able to install with beta 3. AFAIK Shadowrun does have a native Mac version but Mudrunner does not.

**Comment by flavioislima** [comment]
Can you try to run:
`/Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/legendary info Bulbul`?
Or the appName you're trying to install and it's failing?

**Comment by flavioislima** [comment]
@Stooovie Install and play windows games on Beta is broken. I found the issue and fixed already.
I'll try to release new Heroic version tomorrow if no bugs are found so it will have those fixes.

**Comment by Stooovie** [comment]
That's great, thank you so much for your time and work!

**Comment by Stooovie** [comment]
Still the same issues on my system though, even with the 2.0.0. What's new, when I click Install on any game, the spinner just spins indefinitely. I deleted the ~/Library/Application Support/Heroic/ to start from scratch, still the same. I'll keep trying new releases.

**Comment by flavioislima** [comment]
Epic services are having a lot of issues right now so that's the reason, check the status here and if they are all normal and the issue continues, reopen the issue.
https://status.epicgames.com

We will need to implement some kind of warning for that on the next release.

**Comment by Stooovie** [comment]
Ah! Happy to report both downloading and playing Windows games are now working as expected! Thanks!

**Comment by flavioislima** [comment]
Good. I'll release a new heroic version that will check epic statuses and report it if they are broken wheb downloading, playing etc. Because a lot of people were thinking the issue was with heroic but it's epic that is down.
