### ISSUE TITLE
Infinite Processes getting started by Heroic..? Resulting in 100% CPU and RAM Usage.

### ISSUE THREAD

**Issue by Withoutruless** [Heroic-Games-Launcher/HeroicGamesLauncher#813]
**Platform**
Operating system and version:
OS: Windows 10 Build 19043
Legendary version: 0.20.22 Anticitizen One (hotfix #3)
Heroic version: 1.11.0 Beta 3

**Expected Behavior**
Download a game normally without 100% cpu usage and without 100% ram usage

**Current Behavior**

When pressing download the legendary.exe service starts and produces more and more powershell processes with it, causing my ram to go up to 100% usage and freezes my computer unless i stop the process from task manager

**Steps to Reproduce**

Try Downloading Among Us (the issue occurs i have on that game, i havent checked others)

https://ibb.co/YXCYhnD - Ram at 56% (30 Processes)
https://ibb.co/HYPqkcC - Ram at 67% (100 Processes)
https://ibb.co/qMK8qYP - System hardly usable, Ram at 88% (182 Processes)

^^^^^^^^^^^^^^^^

the ram usage increases over time, the cpu stays at 100%

**Additional information**
CPU: AMD E2-9010 Dual Core 2.2GhZ
RAM: 1x4GB

0.20.22 Anticitizen One (hotfix #2) which is included when installing heroic game launcher does the same thing, just switched it out for 0.20.22 Anticitizen One (hotfix #3) hoping it would fix the issue.
also tried the 0.20.18 - Entanglement (EGL Sync Hotfix) version, which again, didnt fix the issue.

(Im sorry if the report is badly written)

**Comment by flavioislima** [comment]
Try go to settings and lower the amount of service workers. It should use less ram and cpu.

**Comment by Withoutruless** [comment]
That's the first thing i've tried, it does the exact same thing.

**Comment by flavioislima** [comment]
Hmm, I see. I think we had someone with this issue in the past and the problem was with windows. After a clean install it worked fine. I tried to debug at the time but could not reproduce it in different windows machines, on windows 10 and 11.

**Comment by Withoutruless** [comment]
Is there any way I can help fix this bug? i wrote the exact same report on Legendary's github page and they said the issue is not on their end and it only occurs on alpha heroic launcher afaik cause ive used the stable version and it worked perfectly.

**Comment by Withoutruless** [comment]
i think it may be because of something in the new UI update.

**Comment by Withoutruless** [comment]
the issue is way, way less intensive on the ram if you dont stay in the library and you switch to another tab like settings while downloading a game, it doesnt create nearly as much processes aswell, if you switch back to the library it'll create more powershell processes until you switch back over to another tab, then the processes will very very slowly start dying until it stops and then you can go back to the library without the issue and the game is downloaded.

(this is what i tried on v1.10.3 Heroic Launcher which was working perfectly before.)

**Comment by flavioislima** [comment]
Have you tried the latest beta?

**Comment by Withoutruless** [comment]
do you mean Heroic 1.11.0 Beta 3? if so, yes.

**Comment by Scarlet-Phonavis** [comment]
Can double confirm this is an actual problem, 
Phenom x2 555
Windows 10 Ver 2004
Heroic Ver 1.11.0 Beta 3

Thread count doesn't seem to effect it at all

**Comment by flavioislima** [comment]
I still cannot reproduce the issue although I might have a clue why this happens and might be related on how we get the installation progress. I'll try to figure it out another way of getting this project, not on next release since this will require more time to code and test, but after it.

**Comment by Withoutruless** [comment]
i suspect it might be cause of the download progress bar, it just doesnt update, maybe it just keeps trying and opens infinite powershells in the process?

**Comment by Withoutruless** [comment]
went and got the new update and can confirm the issue is still there. the app works perfectly, its just that i cant update neither download games from the app cause the bug is still there so i just have to do it from legendary.exe

**Comment by flavioislima** [comment]
Yes, use legendary for now. I have an idea on how to fix it so might be on next release.

**Comment by Withoutruless** [comment]
Well, after updating to {2.1.0 Rayleigh} the issue got fixed for me, im not sure if other people are still experiencing this so i guess i'll leave this issue open.

**Comment by Withoutruless** [comment]
> Can double confirm this is an actual problem, Phenom x2 555 Windows 10 Ver 2004 Heroic Ver 1.11.0 Beta 3
> 
> Thread count doesn't seem to effect it at all

Hey, try the new update and see if it fixes the issue for you, it did the trick for me.

**Comment by Withoutruless** [comment]
im not sure if this is useful information but i think it may have gotten fixed cause i removed all vc redist apps from my computer using add or remove and reinstalled them using aio redist pack.

**Comment by cronyakatsuki** [comment]
I think I have also another reason why this happens. If you have anything in your powershell profile no mater what it is it start spawning the processes. It happens on both the powershell that is preinstalled on windows 10/11 or the powershell core (version 7) .

I tested it just now on my system that only had the chocolatey setup inside the powershell and it started spawning the processes. After deleting those line from the profile it worked completely normally without spawing the processes.

One of the fixes is for the user then to make sure their powershell profile is empty and make it read-only.
Or for Heroic to include the '-NoProfile' option in all powershell commands.

**Comment by flavioislima** [comment]
Is this still happening?
If yes feel free to reopen the issue.
