### ISSUE TITLE
Add archive directory settings

### ISSUE THREAD

**Issue by qiuzhangsaer** [Heroic-Games-Launcher/HeroicGamesLauncher#817]
Add archive directory settings，Set up a unified archive directory for all games.

Since we use heroicgameslancher, it means we don't want to install epic, so the cloud archive of epic may not be available;So I use folder mapping and onedrive to build my own cloud archiving system;However, the cloud archive directory set in heroicgameslancherer must be epic platform. You want to add a custom directory, which is very important for players who use folder mapping and onedrive to establish a cloud archive system

**Comment by flavioislima** [comment]
HI!
I don't think I understand it but do you want to have an alternative server to download the epic games?
I don't know how this applies to Heroic itself.

**Comment by qiuzhangsaer** [comment]
> HI! I don't think I understand it but do you want to have an alternative server to download the epic games? I don't know how this applies to Heroic itself.

Sorry, my English is not very good, so I use Google Translate.
What I mean is, can you add a unified archive directory so that game archives can be backed up to this directory instead of only being backed up to the cloud archive directory of the epic platform.

**Comment by flavioislima** [comment]
You mean the save games?

**Comment by qiuzhangsaer** [comment]
> You mean the save games?

emmm....Single-Player Game Archive，I don't know if that's right

**Comment by wiryfuture** [comment]
Sorry, could you clarify, do you want to be able to customise in the launcher where games upload their cloud saves and make them use a custom directory instead?
If you still want something, could you head into [our discord](https://discord.com/invite/rHJ2uqdquK) so we could figure out what the issue should be called?
Cheers.
