### ISSUE TITLE
Enable GPU for games

### ISSUE THREAD

**Issue by jay-tux** [Heroic-Games-Launcher/HeroicGamesLauncher#820]
**Is your feature request related to a problem? Please describe.**
When starting a game, it always launches on my integrated graphics. There seems to be no option to run games with prime-run?

**Describe the solution you'd like**
Perhaps a simple textfield to run a game with a certain command before (e.g. prime-run) or a toggle enabling/disabling prime-run specifically?

**Describe alternatives you've considered**
No idea how to fix

**Additional context**
I'm using Arch Linux + i3; setup has Intel integrated & dedicated nVidia. I can run applications on my dedicated card.

**Comment by flavioislima** [comment]
Have you tried enabling the NVIDIA Prime Render on the Game Settings?

**Comment by jay-tux** [comment]
Doesn't seem to work. `nvtop` still only displays X11

**Comment by jay-tux** [comment]
Semi-unrelated, but once I swap i3 workspaces (or active window in general), the game freezes and stays stuck?

**Comment by flavioislima** [comment]
> Semi-unrelated, but once I swap i3 workspaces (or active window in general), the game freezes and stays stuck?

I've stopped using i3 because I had issues with gaming on it for several times. Not only with heroic.

But, about the nvidia prime. So then how do you run your games on other platforms. There is any variable you pass or you start the game with prime-run or something?
Because the solution we have in heroic is the same we have for lutris, same flags. At least at the time I've implemented that setting.

**Comment by jay-tux** [comment]
After some more trying, it seems that no wine-game works with prime-run. (E.g. glxgears (yeah, I know, default example) works fine) - same goes with the Lutris flags.... Maybe it's an i3 issue? I'll see if it persists on e.g. KDE

**Comment by flavioislima** [comment]
Yeah, might be. I3 is awesome but not for gaming unfortunately.

**Comment by jay-tux** [comment]
Using KDE doesn't fix either issue :(
