### ISSUE TITLE
Wine version not found with CrossOver 21.1 installed

### ISSUE THREAD

**Issue by EugeneKey** [Heroic-Games-Launcher/HeroicGamesLauncher#821]
### Try to get help on our Wiki first: https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/wiki/Troubleshooting

**Describe the bug**
Wine version not found with CrossOver 21.1 installed

**Add Logs**

INFO: Legendary location: /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/legendary
INFO: Checking if credentials are still valid...
INFO: Heroic Version 1.11.0-beta.3
INFO: Checking if credentials are still valid...
INFO: Legendary Version  0.20.21 Anticitizen One (hotfix #2)

INFO: Checking if credentials are still valid...
INFO: Checking if credentials are still valid...
WARNING: Protocol already registered.
INFO: Frontend: Refreshing Library
INFO: Refreshing library...
INFO: Legendary: Refreshing Epic Games...
INFO: Refreshing Epic Games...
INFO: Checking if credentials are still valid...
INFO: Checking if credentials are still valid...
INFO: checking for heroic updates
[cli] INFO: Logging in...

[Core] INFO: Trying to re-use existing login session...

[cli] INFO: Getting game list... (this may take a while)

INFO: Updating game list
INFO: Game List Updated
INFO: Checking if credentials are still valid...
INFO: Checking for game updates
INFO: Found 0 game(s) to update

**To Reproduce**

1. Go to 'Settings'
2. Click on 'Wine'
3. See error 'Wine version not found '

**Expected behavior**
CrossOver 21.1 in Wine Version Field

**Screenshots**
<img width="567" alt="Screen Shot 2021-12-27 at 16 17 25" src="https://user-images.githubusercontent.com/8057694/147450873-0f456eed-f417-415f-a979-c259a7987485.png">
<img width="768" alt="Screen Shot 2021-12-27 at 16 18 19" src="https://user-images.githubusercontent.com/8057694/147450932-d9fa7f41-79ba-4035-9cf4-e450b3b102c0.png">
<img width="672" alt="Screen Shot 2021-12-27 at 16 23 16" src="https://user-images.githubusercontent.com/8057694/147451403-23cf8c77-efdf-498e-a452-5670611ffaed.png">

**Desktop (please complete the following information):**

- OS: macOS Monterey 12.1
- Heroic Version 1.10.3 and 1.11.0-beta.3
- Game: GTA V
- Wine/Proton version: CrossOver 21.1
- Hardware specs (RAM, CPU, GPU): MacBook Air 2020 with M1 chip

**Additional context**

**Comment by flavioislima** [comment]
Where is your Crossover installed? under /Applications ?
Unless they changed something, I'm not sure what's happening.

@mrpippy perhaps you can help us on that.

**Comment by EugeneKey** [comment]
@flavioislima yes, the standard path is /Applications/CrossOver.app, I tried to install the beta and stable version from codeweavers and also tried to install via Homebrew. Nothing changes in Heroic. Also I reinstalled Heroic with stable and beta version.
Maybe I should add manually to WinePrefix and Custom Wine Paths. I have tried several different paths without successful.

**Comment by EugeneKey** [comment]
@flavioislima I found the issue. For some reason Spotlight Search was disable on my mac.
Without Spotlight not working find app command: 'mdfind kMDItemCFBundleIdentifier = "com.codeweavers.CrossOver"'
After enabling Spotlight Heroic found the CrossOver wine.
