### ISSUE TITLE
Security issue regarding <webview>

### ISSUE THREAD

**Issue by dragonDScript** [Heroic-Games-Launcher/HeroicGamesLauncher#825]
>  ⚠️ Under no circumstances should you load and execute remote code with Node.js integration enabled. Instead, use only local files (packaged together with your application) to execute Node.js code. To display remote content, use the <webview> tag or BrowserView, make sure to disable the nodeIntegration and enable contextIsolation.

All webviews have node integration enabled by default with the current implementation. See: https://www.electronjs.org/docs/latest/tutorial/security

**Comment by flavioislima** [comment]
How is this relevant if we use Webview to show epic store and wiki? This is a security issue if you give the user the ability to load any url. Or unsafe content. Also if the user does that for some reason, like going through links in github until some unsafe content is found, this is their responsibility and will harm only their machines.
