### ISSUE TITLE
add an exit button.

### ISSUE THREAD

**Issue by LithRakoon** [Heroic-Games-Launcher/HeroicGamesLauncher#826]
**Is your feature request related to a problem? Please describe.**
When installing a game theres a pop up giving the option to import or to install the game but not to exit the installation, it is very unclear that you need to click outside the pop up for it to stop the installer

**Describe the solution you'd like**
the solution is adding an X button to the pop up so its easy to know where you need to click to exit it.

**Describe alternatives you've considered**
add a third button to the button on the left side preferably that says cancel or exit

**Additional context**
very rough example of the first solution:
![image](https://user-images.githubusercontent.com/41258148/147605820-5223a221-ace3-4fd9-b399-11265846ea0a.png)

rough example second solution:
![image](https://user-images.githubusercontent.com/41258148/147606346-e01b30f6-368e-4177-a220-72d300b705bd.png)

**Comment by Artumira96** [comment]
Hello, I would like to work on this issue :)

**Comment by flavioislima** [comment]
> Hello, I would like to work on this issue :)

Feel free to send a PR.
Any questions or if you get stuck just got to our Development channel on our discord server. :)

**Comment by Artumira96** [comment]
Hi! there's my PR for this issue along a quick video showing it's functionality, if anything comes up please let me know, thanks! :)
