### ISSUE TITLE
add default wine prefix folder to settings

### ISSUE THREAD

**Issue by LithRakoon** [Heroic-Games-Launcher/HeroicGamesLauncher#827]
**Is your feature request related to a problem? Please describe.**
there is no option to have a default wineprefix creation folder other then ~/Games/Heroic/Prefixes/

**Describe the solution you'd like**
in the new 2.0.0 version of heroic the game will automaticly make a wineprefix in the folder ~/Games/Heroic/Prefixes/
it would be nice to have a setting so that i can change the default folder of where the wineprefixes get created.

for example i have all my prefixes on a second hard drive the path to that is /media/murrit/prefixes
so it would be nice if in heroic i could set that where the new prefixes get created.

**Describe alternatives you've considered**
a dropdown menu of paths for the prefix creation

**Comment by flavioislima** [comment]
Yes, noticed that today but I didn't want to wait for this to release 2.0. This will be improved on next release. For now just create a symbolic link.

**Comment by LithRakoon** [comment]
fixed in 2.0.1
