### ISSUE TITLE
background blur doesnt cover the whole screen

### ISSUE THREAD

**Issue by LithRakoon** [Heroic-Games-Launcher/HeroicGamesLauncher#828]
### Try to get help on our Wiki first: https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/wiki/Troubleshooting

**Describe the bug**
background blur from the installer pop up does not cover all of heroic

**To Reproduce**

1. click on the installer option of any game
2. look at the bottom of the screen
3. see that the blur doesnt cover the whole screen

**Expected behavior**
the background blur covers the whole screen

**Screenshots**
full screen:
![image](https://user-images.githubusercontent.com/41258148/147607057-ba3586f3-1379-4ca8-84f2-d3e336a564f1.png)

windowed:
![image](https://user-images.githubusercontent.com/41258148/147607086-6aa2051e-eb12-4a35-8a96-e75c112f7f4c.png)

fullscreen diffrent game:
![image](https://user-images.githubusercontent.com/41258148/147607118-bb344b7b-c24c-49ed-bc9a-7a3474a904ad.png)

windowed diffrent game:
![image](https://user-images.githubusercontent.com/41258148/147607144-8b6dd254-e206-45b1-9d58-cc0d16f445f1.png)

**Desktop (please complete the following information):**

- OS: Arch Linux
- Heroic Version 2.0.0
- Game: any
- Wine/Proton version: not needed to reproduce
- Hardware specs (RAM, CPU, GPU): 8gbs, ryzen 3 2200g, gtx 1050ti

**Comment by NayeBeckham** [comment]
Hello, I would like to try this!

**Comment by flavioislima** [comment]
Fixed
