### ISSUE TITLE
"Loading Website" and icon visible after website has begun loading

### ISSUE THREAD

**Issue by wiryfuture** [Heroic-Games-Launcher/HeroicGamesLauncher#829]
**Describe the bug**
When switching into the webview from Library or Settings pages the loading context will still be visible momentarily after the website loads. This occurs on the github wiki and the epic store, however is barely noticeable with the wiki because github is much more lightweight.

This feels like it has to do with waiting for the DOM to have fully loaded; you can see in the screenshots of the store that not everything is loaded in when this occurs, and it jumps up when everything is fully loaded in. Instead of waiting for the DOM to have fully rendered, it could wait for first contentful paint instead (as soon as stuff starts being rendered). This should also increase how responsive and 'fast' the loading of the store and wiki pages feels.

**To Reproduce**
1. Begin on Library or Settings page
2. Click Store or Wiki pages and scroll down
3. Site should be visible below loading context before jumping up when the loading context disappears.

**Expected behavior**
"Loading website" context immediately disappears when the site loads OR site is not visible at all until "Loading website" disappears.

**Screenshots**
![Screenshot_20211228_220958](https://user-images.githubusercontent.com/50517631/147610768-e4403d70-d647-4e12-ad4b-8f3e7104c8a4.png)
![Screenshot_20211228_221104](https://user-images.githubusercontent.com/50517631/147610831-22318739-f7f9-401f-b14c-9c2721a84c47.png)

(Normal after load)
![Screenshot_20211228_221304](https://user-images.githubusercontent.com/50517631/147610907-81bf63e8-97e3-4c9d-8c89-a923add05598.png)

**Desktop:**

- OS: Fedora 35 KDE Plasma
- Heroic Version: 2.0.0
- Hardware specs (CPU, GPU): r5 2600, r7 450

**Comment by flavioislima** [comment]
Yes, I find it slow as well but without it, the website was completely blank then loaded. So I think was worse since we had no loading feedback.

**Comment by wiryfuture** [comment]
Resolved with #836 b67668e
