### ISSUE TITLE
Unable to install game from my library

### ISSUE THREAD

**Issue by JKakaofanatiker** [Heroic-Games-Launcher/HeroicGamesLauncher#832]
### Try to get help on our Wiki first: https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/wiki/Troubleshooting

**Describe the bug**
I tried to install Slime Rancher which I already bought. After confirming the install path and clicking install an empty loading bar appears and after a while is gone and the install button is back. Nothing were downloaded and no directories were created in the install path. The `Install Finished` notification still pops up.

**Logs**

[https://jkakaofanatiker.tk/dl/heroic_log.txt](url)

**To Reproduce**

1. Open Heroic
2. Click on the cover of Slime Rancher
3. Click INSTALL
4. Click INSTALL
5. Wait
6. Error (nothing installs)

**Expected behavior**
Heroic should install the game

**Screenshots**
![image](https://user-images.githubusercontent.com/53398711/147683610-f2175e06-a150-4caa-aac1-61f6951e5796.png)
![image](https://user-images.githubusercontent.com/53398711/147683666-4e91f9b7-9b9d-4475-bd56-c7b639372775.png)
![image](https://user-images.githubusercontent.com/53398711/147683731-3b943834-22b0-4c0c-8878-0c389d619b62.png)

**Desktop (please complete the following information):**

- OS: Manjaro (DE: KDE Plasma)
- Heroic Version: 2.0.0
- Game: Slime Rancher (Installation)
- Wine/Proton version: Wine 6.23
- Hardware specs:
CPU: Intel i5-9600K
GPU: NVIDIA GeForce GTX 1070 Ti
RAM: 47 Gigabyte

**Comment by flavioislima** [comment]
Epic services is having a lot of issues right now so that's the reason, check the status here and if they are all normal and the issue continues, reopen the issue.
https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/blob/7c5983472293e395ce8b48ff0b0ec29aec8f455a/electron/main.ts#L508
