### ISSUE TITLE
Unable to launch games after upgrading from 1.10.3 to 2.0.0 (macOS)

### ISSUE THREAD

**Issue by firefinchdev** [Heroic-Games-Launcher/HeroicGamesLauncher#833]
I am unable to start Rocket league (only game I installed) after upgrading from 1.10.3 to 2.0.0

I have tried logging out and logging in again.

Reverting back to 1.10.3 solves the problem.

OS: macOS 12.0.1

**Comment by firefinchdev** [comment]
Logs:
```
INFO: Legendary location: /Applications/Heroic2.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/legendary
INFO:
  Heroic Version: 2.0.0 Roronoa Zoro
  Legendary Version:  0.20.22 Anticitizen One (hotfix #3)
  OS: macOS KERNEL: 21.1.0 ARCH: x64
  CPU: Apple M1 @2.4
  RAM: Total: 17.2 GB Available: 16.3 GB
  GRAPHICS: GPU0: Apple G13G VRAM: nullMB DRIVER:


WARNING: Protocol already registered.
INFO: launching Rocket League® Sugar
WARNING: GameMode not installed
INFO:
 Launch Command:  CX_BOTTLE=default            /Applications/Heroic2.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/legendary launch Sugar   --wine '/Applications/CrossOver.app/Contents/SharedSupport/CrossOver/bin/wine'

```

**Comment by rxmarcelo** [comment]
Same here, but on Ubuntu 20.04.3 LTS.

Same errors on log.

**Comment by slaide** [comment]
not sure where the log would be, but i have the same issue: not a single game actually launches when i click the button, after the update from 1.something to 2.0 ( manjaro linux, kernel 5.15.7 )

**Comment by flavioislima** [comment]
as you can see on the error,  Epic services are having a lot of issues right now so that's the reason, check the status here and if they are all normal and the issue continues, reopen the issue.
https://status.epicgames.com

We will need to implement some kind of warning for that on the next release.

**Comment by firefinchdev** [comment]
Ok seems like now it is working. Tried launching rocket league without any change, it launched perfectly.

**Comment by flavioislima** [comment]
Yes, it seems to be back now for a while
