### ISSUE TITLE
Persian Language Should use RTL Direction for Elements

### ISSUE THREAD

**Issue by PS-Professional** [Heroic-Games-Launcher/HeroicGamesLauncher#834]
### Try to get help on our Wiki first: https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/wiki/Troubleshooting

**Describe the bug**
In the Persian language, the buttons' place and text format aren't correct. Also, the place of words is not correct when English and Persian Words are combined together.

**To Reproduce**

1. Go to 'Setting'
2. Click on 'Language'
3. Scroll down to 'فارسی'
4. See the result

**Expected behavior**
The text should be on the right side and the buttons should be on the left side. Also, the place of English words among Persian words is not correct.

**Screenshots**
![Screenshot from 2021-12-29 20-16-17](https://user-images.githubusercontent.com/75311882/147686403-2619cd77-c682-47fd-96a3-cce465a52b6c.png)

**Desktop (please complete the following information):**

- OS: Ubuntu 20.04.03 LTS
- Heroic Version 2.0.0
- Game: Any
- Wine/Proton version: not needed to reproduce
- Hardware specs (RAM, CPU, GPU): 10 GB, AMD A4-6210 APU, AMD ATI Radeon HD 8550M

**Comment by PS-Professional** [comment]
Since that I did the Persian Translation, I can fix some parts of it but how can I have a preview of my changes without actually applying them on ![translation project](https://hosted.weblate.org/projects/heroic-games-launcher/)?

**Comment by flavioislima** [comment]
so we would need to implement some RTL layout, right?

**Comment by PS-Professional** [comment]
> so we would need to implement some RTL layout, right?

Yes.
And how can I perform translate and check it without actually applying it on [weblate](https://hosted.weblate.org/projects/heroic-games-launcher/)?

**Comment by flavioislima** [comment]
something like this?
![image](https://user-images.githubusercontent.com/26871415/147733799-8e677b7d-ae81-447a-b54f-25113c9809b6.png)

To test without applying on website you will need to run the development mode, you can find the instructions on the README. And edit manually the files for the Persian translation on the folder: `public/locales/fa`

**Comment by PS-Professional** [comment]
Yes, it is the right format of elements on Persian language. If it get applied to project, then the translation doesn't need to be changed.

**Comment by flavioislima** [comment]
Ok, Do you know any other language we currently support that needs this change?

**Comment by PS-Professional** [comment]
I didn't check Arabic language but it should be like Persian.

**Comment by flavioislima** [comment]
@PS-Professional  fixed it now.
Btw, take a look on weblate when you have the time since some keys are not translated yet on 2.0

**Comment by PS-Professional** [comment]
> @PS-Professional fixed it now. Btw, take a look on weblate when you have the time since some keys are not translated yet on 2.0

Yeah, I already checked it. Some parts of the translation didn't require translation acroding to fact that they were special names.
