### ISSUE TITLE
Wine prefixes are not created. ~/Games/ folder is empty.

### ISSUE THREAD

**Issue by allora** [Heroic-Games-Launcher/HeroicGamesLauncher#840]
### Is this a game issue? If YES please use our Discord to get help.
No

### Try to get help on our Wiki first: https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/wiki/Troubleshooting

**Describe the bug**
Heroic does not appear to create child directories of ~/Games/Heroic or ~/Games/Heroic/Prefixes or any installed games prefix under this directory. For example when i download and install The Pathless, the installation process seems to go fine. However when i hit play it does the following

```
INFO: Updating game list
INFO: Game List Updated
INFO: Checking for game updates
INFO: Found 0 game(s) to update
INFO: Getting More details with Legendary info command... 
INFO: launching The Pathless geum
INFO: creating new prefix /home/<user>/Games/Heroic/Prefixes/The-Pathless
ERROR: Error: Command failed: WINEPREFIX='/home/<user>/Games/Heroic/Prefixes/The-Pathless' '/usr/bin/wineboot' -i &&  '/usr/bin/wineserver' --wait
wine: chdir to /home/<user>/Games/Heroic/Prefixes/The-Pathless : No such file or directory

WARNING: DXVK cannot be installed on a Proton or a invalid prefix!
WARNING: GameMode not installed
INFO: 
 Launch Command:     WINEESYNC=1         /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary launch geum   --wine /usr/bin/wine --wine-prefix '/home/<user>/Games/Heroic/Prefixes/The-Pathless'  
INFO: Getting More details with Legendary info command... 
INFO: checking for heroic updates
/bin/sh: line 1: hostname: command not found
INFO: Log was written
INFO: Getting More details with Legendary info command... 
INFO: Getting More details with Legendary info command... 
```

Obviously, i have full write access to this folder, and if i create the folders manually, everything seems to work and the game launches.

Maybe the wrong mkdir (or similar) command is being used when trying to create the full path for the game (or Heroic on first boot isnt creating its folder? That is what I would suspect anyway.

**Add Logs**

Check on how to [run Heroic from Terminal or Powershell](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/wiki/Troubleshooting#running-heroic-from-terminalpowershell-to-debug-errors) and put some logs here

Full log of attempting to run the game:
```
INFO: Legendary location: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary
[23497:1230/141122.748976:ERROR:sandbox_linux.cc(374)] InitializeSandbox() called with multiple threads in process gpu-process.
INFO: 
  Heroic Version: 2.0.0 Roronoa Zoro
  Legendary Version:  0.20.22 Anticitizen One (hotfix #3)
  OS: Arch KERNEL: 5.15.12-arch1-1 ARCH: x64
  CPU: AMD Ryzen 9 5950X 16-Core Processor @3.4 GOVERNOR: schedutil
  RAM: Total: 67.4 GB Available: 61.1 GB
  GRAPHICS: GPU0: Navi 22 [Radeon RX 6700/6700 XT / 6800M] VRAM: 1MB DRIVER:  
  PROTOCOL: tty
  
ERROR: Failed to register protocol with OS.
[23465:1230/141123.177000:ERROR:browser_main_loop.cc(269)] Gtk: gtk_widget_add_accelerator: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed
[23465:1230/141123.177038:ERROR:browser_main_loop.cc(269)] Gtk: gtk_widget_add_accelerator: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed
[23465:1230/141123.177065:ERROR:browser_main_loop.cc(269)] Gtk: gtk_widget_add_accelerator: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed
INFO: Command 'python' found. Version: '3.10.1'
INFO: Frontend: Refreshing Library
INFO: Refreshing library...
INFO: Legendary: Refreshing Epic Games...
INFO: Refreshing Epic Games...
[cli] INFO: Logging in...

[Core] INFO: Trying to re-use existing login session...

[cli] INFO: Getting game list... (this may take a while)

INFO: Updating game list
INFO: Game List Updated
[23465:1230/141124.802835:INFO:CONSOLE(1)] "refreshing", source: file:///opt/Heroic/resources/app.asar/build/static/js/main.cfbee006.chunk.js (1)
INFO: Getting More details with Legendary info command... 
INFO: Checking for game updates
INFO: Found 0 game(s) to update
INFO: Getting More details with Legendary info command... 
INFO: checking for heroic updates
INFO: launching The Pathless geum
INFO: creating new prefix /home/allie/Games/Heroic/Prefixes/The-Pathless
ERROR: Error: Command failed: WINEPREFIX='/home/allie/Games/Heroic/Prefixes/The-Pathless' '/usr/bin/wineboot' -i &&  '/usr/bin/wineserver' --wait
wine: chdir to /home/allie/Games/Heroic/Prefixes/The-Pathless : No such file or directory

WARNING: DXVK cannot be installed on a Proton or a invalid prefix!
WARNING: GameMode not installed
INFO: 
 Launch Command:     WINEESYNC=1         /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary launch geum   --wine /usr/bin/wine --wine-prefix '/home/allie/Games/Heroic/Prefixes/The-Pathless'  
INFO: Getting More details with Legendary info command... 
INFO: Log was written
INFO: Getting More details with Legendary info command... 
```

**To Reproduce**

1. Ensure ~/Games folder does not exist in your home directory
2. After a fresh install of Heroic, download and install a game
2. Launch the game
3. Game does not start (see logs)
4. Check for ~/Games/Heroic and any related folders (in my case they did not exist)

**Expected behavior**
The game creates its prefix in the prefix folder and installs things like DXVK and launches.

**Screenshots**

**Desktop (please complete the following information):**

- OS: Arch Linux (updated as of this posting)
- Heroic Version 2.0.0 Roronoa Zoro
- Game: The Pathless (though this seems to happen to any game)
- Wine/Proton version: wine-7.0-rc1 (Staging)
- Hardware specs (RAM, CPU, GPU): 
- CPU: AMD Ryzen 9 5950X
- RAM: 64GB
- GPU: Radeon 6700XT, Driver: Mesa 21.3.2-1 (RADV)
- HD Space: 320GB free

**Additional context**
If I create the Heroic folder in ~/Games/Heroic, the Prefixes folder and and game specific prefix folder are created properly.

**Comment by allora** [comment]
Also, wanted to add another thing I noticed related to directory creation: Some games have an Apostrophe in them (') and when a wine prefix is getting created with these names, the directory creation predictably craps out:

```
INFO: launching Tony Hawk's™ Pro Skater™ 1 + 2 Guppy
WARNING: 
 You are using Proton, this can lead to some bugs,
              please do not open issues with bugs related with games Proton - Proton - Experimental
ERROR: Error - Command failed: mkdir '/home/allie/Games/Heroic/Prefixes/Tony-Hawk's-Pro-Skater-1--2' -p
/bin/bash: -c: line 1: unexpected EOF while looking for matching `''
/bin/bash: -c: line 2: syntax error: unexpected end of file
```

**Comment by imLinguin** [comment]
I know where the issue is. Current implementation creates the command string and executes it. Using build into node fs API should do the trick `fs.mkdirSync("not/existing/path", {recursive:true})`. If I'm right I'll create a PR later.

**Comment by allora** [comment]
> I know where the issue is. Current implementation creates the command string and executes it. Using build into node fs API should do the trick `fs.mkdirSync("not/existing/path", {recursive:true})`. If I'm right I'll create a PR later. Exact place where prefix is being created: https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/blob/main/electron/legendary/games.ts#L674

Great glad it was an easy fix to spot :) Just to confirm, will using the fs api handle characters like an apostrophe correctly too? (noted in my second comment)

**Comment by imLinguin** [comment]
> Great glad it was an easy fix to spot :) Just to confirm, will using the fs api handle characters like an apostrophe correctly too? (noted in my second comment)

Yes, especially that issue will be gone.

**Comment by wiryfuture** [comment]
Fixed
