### ISSUE TITLE
Invalid Path

### ISSUE THREAD

**Issue by DocMAX** [Heroic-Games-Launcher/HeroicGamesLauncher#846]
I installed Heroic 2.0 on Windows 11 and i get Invalid Path on EG Sync toggle. What is the Problem?
Epic Games is installed of course.
![grafik](https://user-images.githubusercontent.com/5351323/147825744-45f12f01-b9a6-4924-8d23-3aa3b8e1eac8.png)

**Comment by DocMAX** [comment]
I could see the path with legendary.exe egl-sync. Fixed this.

**Comment by flavioislima** [comment]
I'll keep this issue opened since it looks like a bug on windows.

**Comment by Aszarsha** [comment]
I'm getting the same issue, EGS installed on a Win10 (ntfs drive mounted from kernel 5.16.2 ntfs3 driver).
