### ISSUE TITLE
“Heroic.app” cannot be opened because the developer cannot be verified.

### ISSUE THREAD

**Issue by ajtazer** [Heroic-Games-Launcher/HeroicGamesLauncher#849]
**“Heroic.app” cannot be opened because the developer cannot be verified.**

<img width="280" alt="Screenshot 2022-01-01 at 2 58 35 AM" src="https://user-images.githubusercontent.com/37796611/147839383-020c08e5-5e36-434c-bad6-65fb4ea1a631.png">

Device:-
MacBook Air (M1, 2020)
macOS Monterey v12.1
Memory 8 gig

**Comment by flavioislima** [comment]
You need to go to security and click open. Then it won't prompt you anymore.
This happens because we have no way to pay 100 dollars per year to have a developer account on apple.
