### ISSUE TITLE
Cant switch accounts

### ISSUE THREAD

**Issue by Clovenxd** [Heroic-Games-Launcher/HeroicGamesLauncher#851]
### Try to get help on our Wiki first: https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/wiki/Troubleshooting

**Describe the bug**
I click logout to switch to a different epic games account but it automatically logs right back into the account i clicked logout on.

**Add Logs**

**To Reproduce**

1. Click logout

**Expected behavior**
it loads the login screen really quick and auto logins to same account then gets the same account SID and uses that.

**Screenshots**

**Desktop (please complete the following information):**

- OS: [e.g. Ubuntu]
- Heroic Version [e.g. 22]
- Game:
- Wine/Proton version:
- Hardware specs (RAM, CPU, GPU):

**Additional context**
I just want to switch to a different epic games account in order to play different games but i cant because of the bug that auto logins to the same account. I've tried to clear Heroic's cache and resetting Heroic but that hasn't helped. Could there be a saved cookie somewhere for epic games that keeps me logged in that i can delete?

**Comment by imLinguin** [comment]
It's a known bug, Workaround for now: Go to Store tab and sign out from there. Then sign out from Heroic

**Comment by Clovenxd** [comment]
> It's a known bug, Workaround for now: Go to Store tab and sign out from there. Then logout from Heroic

Thank you it worked perfectly.

**Comment by flavioislima** [comment]
I am not decided if this is a bug or a feature, I like to think that as a feature since it shares your login across heroic and the store instead of needing to log in twice.
What we could do is to try to erase all cookies once you log out from heroic.

**Comment by imLinguin** [comment]
@flavioislima Maybe there is a way to delete Epic Games cookies when user wants to logout. It's just unintuitive currently.

**Comment by flavioislima** [comment]
Yes, exactly.
Just fixed now.
From now on when logging out from Heroic Store will be logged out as well
