### ISSUE TITLE
No games shortcuts created in KDE (Arch Linux)

### ISSUE THREAD

**Issue by Pabxy** [Heroic-Games-Launcher/HeroicGamesLauncher#856]
### Try to get help on our Wiki first: https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/wiki/Troubleshooting

**Describe the bug**

**Add Logs**

Check on how to [run Heroic from Terminal or Powershell](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/wiki/Troubleshooting#running-heroic-from-terminalpowershell-to-debug-errors) and put some logs here

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS: [e.g. Ubuntu]
- Heroic Version [e.g. 22]
- Game:
- Wine/Proton version:
- Hardware specs (RAM, CPU, GPU):

**Additional context**

**Comment by flavioislima** [comment]
This is fixed on the code, will be fixed on next release.
