### ISSUE TITLE
Store Page button opens the link in a new window instead of the webview

### ISSUE THREAD

**Issue by arielj** [Heroic-Games-Launcher/HeroicGamesLauncher#863]
**Describe the bug**

When clicking the Store Page link of a game, it opens in a new window. It's weird since the Store link on the sidebar opens the store in the webview inside the main Heroic window.

~~the Check Compatibility link behaves the same.~~

**To Reproduce**

1. Go to the Tools tag of any game
2. Click on Store Page or Check Compatibility
3. The page will open in a new window

**Expected behavior**

I would expect at least the store page to open in the webview, the same way the Store link of the sidebar works.

EDIT: this issue now applies only to the Store Page button, not the compatibility button

**Desktop (please complete the following information):**

- OS: Linux Mint 20.02
- Heroic Version: Main branch
- Game: any
- Wine/Proton version: -
- Hardware specs (RAM, CPU, GPU): -

**Comment by flavioislima** [comment]
The Webview component accepts a url as parameter so we can perhaps route to the store with the url.

In theory is a simple fix.

**Comment by flavioislima** [comment]
But to be honest, I think would be better to keep as it is today. 
Because will be weird to open protondb on the STORE page. so we would need to have another Webview route, this would add unnecessary complexity imo.

**Comment by arielj** [comment]
@flavioislima What about only doing this fix for the Store Page link? It's taking the user to the Store, it should behave like the Store link of the sidebar.

I agree the protondb url is ok if it stays the same (it's a bit weird, but it's also weired if it ends up in the `Store` screen)

**Comment by flavioislima** [comment]
Yes, should be an easy fix then. Makes sense in this case.
