### ISSUE TITLE
Focus the search bar when pressing Ctrl+F (CMD+F on mac?)

### ISSUE THREAD

**Issue by arielj** [Heroic-Games-Launcher/HeroicGamesLauncher#867]
**Is your feature request related to a problem? Please describe.**

Thinking about accessibility, if you are cycling through the games grid with the Tab key, you have to go all the way back up to the header if you want to search for something.

It's a really common pattern in many applications to press Ctrl+F to trigger a search functionality.

**Describe the solution you'd like**

We could listen to the same key combination to focus the search bar in the Library screen.

**Describe alternatives you've considered**

On Mac I think it's Command+F the common pattern.

Not sure if it's possible to let the user pick the shortcuts, I know in spanish is really common for apps to use Ctrl+B (from `Buscar`), but maybe it can be an extra for the future.

**Comment by flavioislima** [comment]
Yes, I was looking into this library some time ago, don't know if it is being updated (or even needed anymore)
https://github.com/ccampbell/mousetrap

I think we could have an event listener on the search component that could listen to the keyboard and this specific combination
