### ISSUE TITLE
The language is reset to default at restart until going to the Settings page

### ISSUE THREAD

**Issue by LovUFOSSCommunity** [Heroic-Games-Launcher/HeroicGamesLauncher#870]
### Try to get help on our Wiki first: https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/wiki/Troubleshooting

**Describe the bug**
When I launch Heroic, it sometimes (often when I didn't use it for some time) resets to default language, English, instead of French for me. And as soon as I click on "Settings", it switches back to French (without needing to manually re-select French in the language menu).

If I remember well, this bug only occurred since Version 2.0.0.

**Add Logs**

Logs here : [heroic_log.log](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/files/7809682/heroic_log.log)

**To Reproduce**
Steps to reproduce the behaviour:

1. Change your language to "French"
2. Close Heroic
3. Wait an unknown amount of time (minimum 1 minute I think)
4. Launch Heroic
5. See the error: the interface is in English
6. (Optional) If you go in your library, the store or the wiki page, nothing changes
7. Click on "Settings": the interface come back to French

**Expected behaviour**
Heroic should be in French at startup.

**Screenshots**
(Not useful)

**Desktop (please complete the following information):**

- OS: Linux Mint 19.3 (DE : Cinnamon)
- Heroic Version: 2.0.0 Roronoa Zoro
- Game: irrelevant
- Wine/Proton version: irrelevant
- Hardware specs (RAM, CPU, GPU):
    - CPU: Intel© Core™ i5-9300H CPU @ 2.40GHz × 4
    - RAM: 7.6 Go
    - GPU: NVIDIA GeForce GTX 1650

**Additional context**
This bugs _seems_ to exist for all languages. So far, I tried it in French, Russian and Spanish.

**Comment by flavioislima** [comment]
could not reproduce it. Can you record the screen or something?
Try to clear the cache maybe

**Comment by LovUFOSSCommunity** [comment]
Hi, thanks for your answer!

Clearing the cache didn't change anything. Here is a recording of my screen while having the bug.

https://user-images.githubusercontent.com/88347735/148706869-598d4bb2-a28c-4c49-9edb-cee9f907b637.mp4

**Comment by flavioislima** [comment]
Interesting. I still cannot reproduce it but I have a clue.
Open the Dev tools by going to the Tray Icon > Debug.
Then go to the Application tab > Storage > Local Storage > select the only item there.
On the right side search for the `language` key. Check if it's being changed somehow.

**Comment by LovUFOSSCommunity** [comment]
Thanks for your answer.

I went in Application tab > Storage > Local Storage > file://, and here are the keys and values _when the interface is in English instead of French_ :

Key|Value
---|---
i18nxtLng|en
language|fr
layout|grid
category|games
filter|all
updates|undefined

After clicking on Settings, the language sets back to French, and the value of `i18nxtLng` changes to `fr` (and `updates` changes to `[]` but I guess it's irrelevant here)

I hope it will help you!

Have a great day, and thanks again for this software, it rocks!

**Comment by flavioislima** [comment]
hmm, weird. I dont know from where i18nxtLng is coming from. Can you try removing it ?

**Comment by LovUFOSSCommunity** [comment]
When I remove it, it reappears every time I go in the Settings tab... And when it does, the value is always `fr`.
It seems that the value changes to `en` when Heroic is closed.

Could it come from my OS? (which would be weird too, as my system locale is French too)

**Comment by LovUFOSSCommunity** [comment]
So i18next seems to be a tool for JavaScript to facilitate the internationalization of a piece of software: https://www.i18next.com/

Maybe I have another software which uses i18next and thus creates this variable system-wide, then Heroic reads it?

**Comment by flavioislima** [comment]
no, I don't think that's the case. I think it was a bug with Language detector, a plugin for i18next that we are not actually using right now. So after removing it that key is not created anymore so this should fix the issue for you.

**Comment by LovUFOSSCommunity** [comment]
I'm sorry, I didnt quite understand what you mean by "removing it": should I remove the Language detector plugin? If so, how? (and how do you think it came from in the first place?)

Thanks a lot for your help.

**Comment by flavioislima** [comment]
No, that's on us to do and I did already. So your problem should be fixed on next version.

**Comment by LovUFOSSCommunity** [comment]
Great, thanks!

**Comment by hunabku94** [comment]
Hi, i have the same issue in 2.5.2.

**Comment by hunabku94** [comment]
up ?

**Comment by LovUFOSSCommunity** [comment]
That's weird, it does not happen to me, this problem was effectively fixed a long time ago for me.

**Comment by hunabku94** [comment]
I am at your disposal for all the necessary tests
