### ISSUE TITLE
can't find the "create shortcut option on heroic launcher 2.0" mac

### ISSUE THREAD

**Issue by hndq** [Heroic-Games-Launcher/HeroicGamesLauncher#871]
### Open here only issues with Heroic like: Heroic doesn't open, some button is out of place, Heroic closes unexpectedly, installs got interrupted, etc.
<img width="1440" alt="Screenshot 2022-01-05 at 8 50 11 PM" src="https://user-images.githubusercontent.com/67551487/148242327-9522e1d7-c13e-47ff-b4e5-e6ac2a09fee7.png">

### Try to get help on our Wiki first: https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/wiki/Troubleshooting

**Describe the bug**

**Add Logs**

Check on how to [run Heroic from Terminal or Powershell](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/wiki/Troubleshooting#running-heroic-from-terminalpowershell-to-debug-errors) and put some logs here

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS: [e.g. Ubuntu]
- Heroic Version [e.g. 22]
- Game:
- Wine/Proton version:
- Hardware specs (RAM, CPU, GPU):

**Additional context**
same as title

**Comment by imLinguin** [comment]
![obraz](https://user-images.githubusercontent.com/62100117/148243084-1d494e00-badc-4e0c-ad9b-d2f71661f6e2.png)
I think that's what you are looking for. For the future please ask on Discord. GitHub Issues should be a place to report bugs and feature requests

**Comment by arielj** [comment]
Shortcuts on Mac are not supported yet https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/issues/723.
