### ISSUE TITLE
[Windows] Sync with EGL Issues

### ISSUE THREAD

**Issue by meeeeeeeeeeeeeeee** [Heroic-Games-Launcher/HeroicGamesLauncher#874]
**System**
Heroic Version: 2.0.0 (installed through the setup program)
Game: Grand Theft Auto 5
OS: Windows 7 professional SP1 64 bit
Wine/Proton version: None
Hardware specs: Dell Latitude E6510 Laptop with Intel core i7 740QM, Nvidia NVS 3100M (512MB), 8GB of DDR3 1333MHz RAM (2x 4GB modules) and a 250GB Seagate HDD

**Is this a game issue?**

No, the game worked when started through the epic games launcher or desktop shortcut before removing the epic games launcher

**The problem**

there is no button in heroic to add games to the library that have been installed through the epic games launcher (legendary has an import option but that has to be used through the command prompt), starting a game from the shortcut on the desktop shows an error that says "application not found" and all the files for the game I'm trying to play are still in C:\Program Files\Rockstar Games\GTAV

**To Reproduce (on windows only)**

1. Install the epic games launcher
2. Install a game through the epic games launcher
3. Install heroic and legendary
4. Delete all epic games launcher executables from C:\Program Files (x86) and C:\Users\[username]\AppData\Local, DO NOT UNINSTALL THE EPIC GAMES LAUNCHER THROUGH THE CONTROL PANEL OR THE GAMES WILL BE UNINSTALLED TOO, replace C: with whatever drive these files were installed to (mine is C: because my laptop and my tower only have one HDD and I don't use more partitions than the 2 windows creates during setup)
5. Try to launch a game from the shortcut on the desktop and an error should pop up then go into heroic to find no import button on the windows version (the linux version had an import button on the older version that I used  a couple months ago on linux mint 19.1 mate)

**To fix**
add a button to the windows version for importing games that have already been installed so legendary's import command does not have to be used through the command prompt

**Screenshots**

![Capture](https://user-images.githubusercontent.com/42124824/148278891-07adebef-6966-4221-ad6a-4608aa43926e.PNG)

**Comment by flavioislima** [comment]
There are two ways of importing games in heroic. On the install dialog there is the import gsnw button. On the Heroic settings there is a button to sync with EGL, importing and importing all your games at once.
Those features are available on all platforms.

**Comment by meeeeeeeeeeeeeeee** [comment]
I found out what part of the problem was, After installation I used the login button in heroic to log into my account and it didn't log in correctly, by downloading the exe for legendary and using it's auth command to login now the library button and all my games show up (they didn't before) but all of them show as not installed, now there's a different problem, Because I improperly uninstalled the epic games launcher (so it wouldn't remove GTA 5 which would need 12+ hours to reinstall over the half megabit internet connection I'm on) I cannot repair or uninstall the epic games launcher with their MSI file or use the sync button in the settings, if I use the download button in heroic for any game it does nothing just a spining circle and no HDD activity

**Comment by flavioislima** [comment]
@meeeeeeeeeeeeeeee try using the portable EXE instead of the Setup.
also this EGL sync, check if this path exists:
'C:/ProgramData/Epic/EpicGamesLauncher/Data/Manifests'

**Comment by meeeeeeeeeeeeeeee** [comment]
I tried the portable version and the installer for 2.0.2 and it still wasn't working right, I got rid of the new version completely (uninstalled through control panel and deleted all the folders for heroic and legendary that I found) and used the installer for version 1.11.0-beta 3, the sign in worked like it's supposed to on that version and I was able to sign into my epic games account through my nintendo account, after signing in the sync button in the settings worked and now all 52 of my games from epic are showing in the library, the three that are installed are displayed with a color icon and a green play button.

**Comment by flavioislima** [comment]
That's weird because we didn't have any change on the EGL sync part. I wonder if legendary had changed something on their side.

I believe you can get back to 2.0.2 now.
