### ISSUE TITLE
Add Clear Button to Search Bar 

### ISSUE THREAD

**Issue by LithRakoon** [Heroic-Games-Launcher/HeroicGamesLauncher#877]
**Is your feature request related to a problem? Please describe.**
when you use the search bar and theres text in it there is no easy way to dismiss the text, an easy fix for that is to make the "Library" button act as that dismissal since this feels very natural 

**Describe the solution you'd like**
make the "library" button dismiss text and return you to the home page

**Describe alternatives you've considered**
add an X to the end of the search bar

**Comment by flavioislima** [comment]
I dont know, it was like this before and some people asked to keep the text there.
I think we could add a clear button to the search bar, might be more intuitive.

**Comment by arielj** [comment]
I'd go with the `X` at the end of the input. It's a known pattern in many applications and the logic lives in the same component
