### ISSUE TITLE
Make installing games appear at the top

### ISSUE THREAD

**Issue by LithRakoon** [Heroic-Games-Launcher/HeroicGamesLauncher#878]
**Is your feature request related to a problem? Please describe.**
When installing a game youd like to check on its progress on a fast and easy way, right now you have to use the search bar or scroll down to find the game youre installing, both only work for 1 game at the time which consume more time.
my suggestion is to make games that are installing appear at the top of the list until they are installed.

**Describe the solution you'd like**
Make the game appear at the top of the list when they are installing

**Describe alternatives you've considered**
make a dedicated download page

**Comment by flavioislima** [comment]
There is a Download Filter that will show the downloading games but this can be replaced with your idea.

**Comment by AlanMauricioC** [comment]
is there some one working on this? I would like to try to work on.

**Comment by flavioislima** [comment]
> is there some one working on this? I would like to try to work on.

I don't think someone is working on that. Feel free to pick up it ans assign to your self.
