### ISSUE TITLE
Heroic Games Launcher 2.0.1 not showing library anymore

### ISSUE THREAD

**Issue by pzlingo** [Heroic-Games-Launcher/HeroicGamesLauncher#883]
After login, Heroic does not show the own game library anymore.
Just showing this after login: {"redirectUrl":"https://epicgames.com/account/personal","authorizationCode":null,"sid":"my_sid_number"}

Tried to login either with epic account and with sid-login. Happenes on both

Tested with Heroic 2.0 and 2.0.1
Opensuse 15.2 x64

<edit> Seem to be glibc related. My system has glibc 2.27. I think this may be the problem. Please remove request </edit>

**Comment by flavioislima** [comment]
Yes, we had other issues in the past related with OpenSuse. It seems only Tumbleeweed works fine, but they have updated glibc once and it broke again.
OpenSuse is nice but perhaps try another distro more gaming-focused like Garuda or Pop_OS!
