### ISSUE TITLE
Problems installing from Ubuntu 20.04 LTS

### ISSUE THREAD

**Issue by Zedenar** [Heroic-Games-Launcher/HeroicGamesLauncher#884]
apt-fast install -y heroic

Working... this may take a while.
E: Unable to locate package heroic
Package manager quit with exit code.

**Comment by flavioislima** [comment]
@rauldipeas can you help me on that?

**Comment by rauldipeas** [comment]
Ubuntu doesn't have Heroic at the `apt` repository.

Do You add the **MAD Linux** repository as described here?
https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher#debian-third-party-apt-repository
