### ISSUE TITLE
Launcher never loads

### ISSUE THREAD

**Issue by i-like-trains72** [Heroic-Games-Launcher/HeroicGamesLauncher#885]
### Is this a game issue? If YES please use our Discord to get help.
No

### Try to get help on our Wiki first: https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/wiki/Troubleshooting

**Describe the bug**
When I start the launcher, it stays stuck on a white window with a Heroic label and the windows default icon for a program.

**Add Logs**

Check on how to [run Heroic from Terminal or Powershell](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/wiki/Troubleshooting#running-heroic-from-terminalpowershell-to-debug-errors) and put some logs here

**To Reproduce**

1. Launch Heroic games launcher
2. Watch it never load

**Expected behavior**

I was expecting to see the main menu of the launcher 
**Screenshots**
![image](https://user-images.githubusercontent.com/82773235/148617549-65dc0bbe-414d-495d-9712-48f73cd869a8.png)

**Desktop (please complete the following information):**

- OS: Windows 10 Pro
- Heroic Version 2.0.0
- Game: N/A
- Wine/Proton version: N/A
- Hardware specs 16GB DDR3 RAM, intel i5 5300U, Geforce 830M

**Additional context**
It worked the first time I installed the launcher to play Satisfactory. This is my second launch and it does not work.

**Comment by i-like-trains72** [comment]
I'm trying to get logs but the program isn't installed in C:\Users\myuser\AppData\Local\Programs

**Comment by flavioislima** [comment]
Which exe have you downloaded?

**Comment by flavioislima** [comment]
Ah, I'm blind, I can see on the screenshot that its the Portable version.
Try the Setup.
The portable doesn't run from the terminal, I mean, run, but I don't think its possible to have output.

**Comment by wiryfuture** [comment]
Closing because stale/abandoned?
