### ISSUE TITLE
Option to prevent screen saver when playing a game

### ISSUE THREAD

**Issue by SomeoneIsWorking** [Heroic-Games-Launcher/HeroicGamesLauncher#887]
**Is your feature request related to a problem? Please describe.**
Games go in screen saver when playing with a controller

**Describe the solution you'd like**
Disable screen saver during game option like in Lutris

![image](https://user-images.githubusercontent.com/9450683/148657682-bc22b825-1f7e-4833-b914-52a5974e6de1.png)

**Comment by flavioislima** [comment]
You can use Game Mode for that. Enable it on the game settings.
You need to install it but I know its available for most distros.

**Comment by SomeoneIsWorking** [comment]
Okay, thank you.
