### ISSUE TITLE
Install button won\t show when DLC list is too long

### ISSUE THREAD

**Issue by Maranoid123** [Heroic-Games-Launcher/HeroicGamesLauncher#891]
### Try to get help on our Wiki first: https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/wiki/Troubleshooting

**Describe the bug**

-----------------------------------------------------------------------------------------------------------------------------------------------
I tried to install the game HITMAN3, but the installation interface shows that the installed game content is too long, so the install button cannot be displayed, and I cannot install this game！！！！！！！！！！！！！！！
-----------------------------------------------------------------------------------------------------------------------------------------------

**Add Logs**

Check on how to [run Heroic from Terminal or Powershell](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/wiki/Troubleshooting#running-heroic-from-terminalpowershell-to-debug-errors) and put some logs here

**To Reproduce**

**Expected behavior**

**Screenshots**
![Problem](https://user-images.githubusercontent.com/97498731/148887519-1761b050-489b-4850-8868-079aa889a901.png)

**Desktop (please complete the following information):**

Version Windows 10 Pro
Version number 21H1
Installation Date ‎2021/‎10/‎15
OS Build 19043.1288
Experience Windows Feature Experience Pack 120.2212.3920.0

- Heroic Version [e.g. 22] 2.0.2
- Game:HITMAN3
- Wine/Proton version: 
- Hardware specs (RAM, CPU, GPU):
- CPU: Inter Core i7 7700HQ 
- GPU: Geforce GTX  1050TI
- RAM: SAMSUNG 24GB 2400Mhz

**Additional context**
Can you add an install button？Thank you very much!!!!!!!!!!!!!!!!!!

**Comment by flavioislima** [comment]
That looks beautiful 😅
I see the issue on the code, we will fix on next release.

for now:

- Click on the Heroic Icon close to the clock
- Click Debug
- it will open the dev tools
- select the install dialog

then if you have some CSS skills you can make the install button visible (it's on the right side of the import game button).
I guess if you enable scrolling horizontally you would be able to see the whole content.
