### ISSUE TITLE
Getting "Install Canceled" notification on succesfull game installation

### ISSUE THREAD

**Issue by Sl1van** [Heroic-Games-Launcher/HeroicGamesLauncher#897]
### Try to get help on our Wiki first: https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/wiki/Troubleshooting

**Describe the bug**

**Add Logs**

[DLManager]
INFO: Progress: Hoatzin 73.94%/901.99MiB/00:00:05
[DLManager]
INFO: Progress: Hoatzin 79.71%/1028.97MiB/00:00:04
[DLManager]
INFO: Progress: Hoatzin 89.18%/1091.13MiB/00:00:02
[DLManager]
INFO: Legendary: Installed game list updated
ERROR: SyntaxError: Unexpected end of JSON input
INFO: Legendary: Installed game list updated
INFO: Installaton canceled
INFO: finished installing
INFO: Frontend: Refreshing Library
INFO: Refreshing library...
INFO: Updating game list
INFO: Game List Updated
INFO: Progress: Hoatzin 94.79%/undefinedMiB/00:00:01
[DLManager]
[8540:0112/152710.484:ERROR:gpu_init.cc(453)] Passthrough is not supported, GL is disabled, ANGLE is
INFO: launching Totally Reliable Delivery Service Hoatzin
INFO:
 Launch Command: C:\Users\silva\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\legendary.exe launch Hoatzin

**To Reproduce**

1. Download/Install any game
2. Wait for Download to finish
3. Wait for the "Install Canceled" notification.
4. Play the game because the installation is just fine

**Expected behavior**
Some sort of notifaction that indicates that the installation was successfull and not "Install Canceled".

**Screenshots**
-

**Desktop (please complete the following information):**

- OS: Windows 11
- Heroic Version 2.02
- Game: tested on "Totally Reliable Delivery Service" and MafiaDE
- Wine/Proton version: -
- Hardware specs (RAM, CPU, GPU):-

**Additional context**

**Comment by flavioislima** [comment]
Yes, I can confirm this one. Noticed last time I tested on windows.
For some reason even if the installation is successful we get an error message.

**Comment by dragonDScript** [comment]
Is there a way to fix this? I'm not getting the update

**Comment by flavioislima** [comment]
@aitor try on latest commit.

**Comment by dragonDScript** [comment]
Later

**Comment by flavioislima** [comment]
I believe this was fixed.

**Comment by Sl1van** [comment]
Everything now works fine now.
Thanks for fixing the bug.
