### ISSUE TITLE
Lutris-like DXVK-NVAPI / DLSS switch

### ISSUE THREAD

**Issue by aronjanosch** [Heroic-Games-Launcher/HeroicGamesLauncher#903]
**Is your feature request related to a problem? Please describe.**

I had trouble getting DLSS working in games like Rise of the Tomb Raider.
DLSS is a great feature and supported with modern versions of Wine/Proton builds.

Screenshot of the way Lutris is handling it:
![image](https://user-images.githubusercontent.com/20959518/149518988-301bae7e-dc2c-45e9-b06a-d6de978b8176.png)

**Describe the solution you'd like**

To get DLSS working you need to set some Arguments/ENV-Vars. It would be easier if its just a switch like in Lutris.

**Describe alternatives you've considered**

See the answer above

**Comment by flavioislima** [comment]
We have a similar feature request already:
#699
