### ISSUE TITLE
Verifying game files

### ISSUE THREAD

**Issue by billcipher225** [Heroic-Games-Launcher/HeroicGamesLauncher#915]
**Is your feature request related to a problem? Please describe.**
I had an issue with one of my games that could only be fixed by verifying the game files or reinstalling the game.

**Describe the solution you'd like**
An option to verify when you right-click on a game or go to game settings

**Additional context**
Epic Games Launcher has one ¯\_(ツ)_/¯
![image](https://user-images.githubusercontent.com/97811645/149979274-1f0adf06-43e7-46f7-b530-6f3a4ebb3a26.png)

**Comment by imLinguin** [comment]
You can already do it from Game Page
![obraz](https://user-images.githubusercontent.com/62100117/149981235-251a8154-2f4e-49d2-af75-9b2fd2bb11b7.png)

**Comment by billcipher225** [comment]
> 

Oh, I'm an idiot lol
