### ISSUE TITLE
can't change the command used for wine or proton

### ISSUE THREAD

**Issue by MightyPrince1** [Heroic-Games-Launcher/HeroicGamesLauncher#922]
I"ve installed wine and proton as flatpak packages and I'd like to use this launcher, but they don't show up as options. How could I add them?

**Comment by flavioislima** [comment]
Hi!
This is not a Heroic issue. Please refer to this page to check how to add custom wine proton:
https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/wiki/How-To:-Wine-and-Proton

Heroic v2.1 also now allows you to download wine and proton directly. so check this new feature.
