### ISSUE TITLE
Python 3.8 error

### ISSUE THREAD

**Issue by remivamp** [Heroic-Games-Launcher/HeroicGamesLauncher#924]
### Is this a game issue? If YES please use our Discord to get help.
no

### Try to get help on our Wiki first: https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/wiki/Troubleshooting

**Describe the bug**
With python 3.8 installed, get "Heroic requires python 3.8 or newer" before the launcher opens

**Add Logs**
INFO: [Legendary]: Location: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary
[5930:0125/175604.840807:ERROR:sandbox_linux.cc(374)] InitializeSandbox() called with multiple threads in process gpu-process.
INFO: [Backend]: 
  Heroic Version: 2.1.0 Rayleigh
  Legendary Version:  0.20.25 Our Benefactors
  OS: LinuxMint KERNEL: 5.10.0-0.bpo.9-amd64 ARCH: x64
  CPU: AMD Ryzen 5 3600 6-Core Processor @3.6 GOVERNOR: schedutil
  RAM: Total: 16.7 GB Available: 5.63 GB
  GRAPHICS: GPU0: Ellesmere [Radeon RX 470/480] VRAM: 256MB DRIVER:  
  PROTOCOL: x11
  
INFO: [Backend]: User Not Found, removing it from Store
WARNING: [Backend]: Protocol already registered.
[5898:0125/175605.117480:ERROR:browser_main_loop.cc(269)] Gtk: gtk_widget_add_accelerator: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed
[5898:0125/175605.117528:ERROR:browser_main_loop.cc(269)] Gtk: gtk_widget_add_accelerator: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed
[5898:0125/175605.117572:ERROR:browser_main_loop.cc(269)] Gtk: gtk_widget_add_accelerator: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed
WARNING: [Backend]: python command not found
WARNING: [Backend]: Command python3 version '3.7.3' not supported.
ERROR: [Backend]: Heroic requires Python 3.8 or newer.

Check on how to [run Heroic from Terminal or Powershell](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/wiki/Troubleshooting#running-heroic-from-terminalpowershell-to-debug-errors) and put some logs here

**To Reproduce**

1. Open Terminal or go to LMDE4's start menu
2. type "heroic" or open Heroic Games Launcher

**Expected behavior**
Python 3.8 to be recognized and heroic to open

**Screenshots**
https://i.imgur.com/2gwMjHo.png

**Desktop (please complete the following information):**

- OS: LMDE4
- Heroic Version 2.1.0
- Game: n/a
- Wine/Proton version: n/a
- Hardware specs (RAM, CPU, GPU):
  OS: LinuxMint KERNEL: 5.10.0-0.bpo.9-amd64 ARCH: x64
  CPU: AMD Ryzen 5 3600 6-Core Processor @3.6 GOVERNOR: schedutil
  RAM: Total: 16.7 GB Available: 5.63 GB
  GRAPHICS: GPU0: Ellesmere [Radeon RX 470/480] VRAM: 256MB DRIVER:  

**Additional context**
If it's not 3.6 or 3.8 then I'm lost

**Comment by flavioislima** [comment]
Are you sure you have python 3.8? Actually, 3.9 would be ideal but 3.8 should work for now.
Run this on the terminal:
`python3 --version`

**Comment by Nocccer** [comment]
Check the log. It says python 3.7.1 was found. We checking for python which points mostly to python2 and python3. Maybe legendary supports setting the python path or atleast looks also for python39? If so we could implement that, too
