### ISSUE TITLE
No Games found on the Library (Epic services check issue)

### ISSUE THREAD

**Issue by asxo999** [Heroic-Games-Launcher/HeroicGamesLauncher#930]
![Screenshot 2022-01-28 at 1 38 58 PM](https://user-images.githubusercontent.com/98580953/151510739-31390737-7781-460d-9c90-cb4690f8fccb.png)
![Screenshot 2022-01-28 at 1 39 30 PM](https://user-images.githubusercontent.com/98580953/151510746-3d89b931-ee7f-45dc-96bf-88e7b7cd9b5a.png)

- OS: macOS
- Heroic Version [Latest]
- Game: ROCKET LEAGUE
- Wine/Proton version: idk
- Hardware specs (RAM, CPU, GPU):8gb ( MacBook air m1)

**Comment by Nocccer** [comment]
Epic games server have some troubles. Check later as soon as epic games server working again.

**Comment by asxo999** [comment]
No in epic games it show, but not on heroic game launcher

**Comment by Nocccer** [comment]
Ok problem was that we checked for all epic services and not for the epic games store service. Right now Fortnite is down, thats why we thought epic games store is also down. New version with hotfix will be released soon (today, tomorrow)

**Comment by asxo999** [comment]
is it fixed

**Comment by Nocccer** [comment]
With the next hotfix release, yes. But it shoud also work now.
