### ISSUE TITLE
Downloading a new wine build via Wine Downloader doesn't work with controller input

### ISSUE THREAD

**Issue by Leopard1907** [Heroic-Games-Launcher/HeroicGamesLauncher#933]
**Describe the bug**
It is not possible to download a Wine build in Wine Downloader with using a gamepad, while controller works fine with the other app features. Such as launching games, toggling switches etc etc.

**Add Logs**

There were no useful data on terminal.

**To Reproduce**

1. Go to 'Wine Downloader'
2. Try to download any of the Wine builds from there with using a gamepad. I used a DualShock 4 so pressing to X on controller should have worked for me. 

**Expected behavior**
Being able to download builds in there with gamepad input. 

**Desktop (please complete the following information):**

- OS: Arch
- Heroic Version: 2.1.0 from AUR

**Comment by Nocccer** [comment]
@arielj Can you look over it, if you have time ?

**Comment by arielj** [comment]
oops I never saw this mention, I just pushed a PR to fix this
