### ISSUE TITLE
[BUG] Offline mode Unknown error.

### ISSUE THREAD

**Issue by onurbbr** [Heroic-Games-Launcher/HeroicGamesLauncher#934]
**Describe the bug**
Offline mode does not work properly in cases where there is no Internet connection. I've tried any game, but it won't open.

**To Reproduce**

1. Go to Library
2. Click on any Game (GTA V)
3. See error

**Expected behavior**
I expect a result like the screenshot.
![Screenshot_7](https://user-images.githubusercontent.com/47495526/151652804-ae755dfd-64a6-461f-892c-f6a9d600173a.png)

**Screenshots**
![Screenshot_5](https://user-images.githubusercontent.com/47495526/151652701-d4bb71c8-2813-4af6-8ec9-d955e057a13a.png)

**Desktop (please complete the following information):**

- OS: Windows 10 IoT Enterprise LTSC 21H2 Version 19044.1503
- Heroic Version: 2.1.0 Rayleigh
- Game: Grand Theft Auto V
- Wine/Proton version: -
- Hardware specs (RAM, CPU, GPU): 16GB RAM, Intel i7-10750H, Nvidia RTX 2060 Mobile

Edit: I upgraded my operating system to Windows 11 Pro. The problem still persists.

**Comment by Nocccer** [comment]
Can you provide as a log by running heroic from terminal?
Also provide the game log which you can open via Game Page -> Tools -> Latest Log

**Comment by onurbbr** [comment]
> Can you provide as a log by running heroic from terminal? Also provide the game log which you can open via Game Page -> Tools -> Latest Log

ERROR: [Backend]: Open undefined failed with Error: ENOENT: no such file or directory, open 'C:\Users\Onur/.config/heroic//Logs/heroic-2022-02-03T05:49:01.957Z.log'
INFO: [Legendary]: Location: C:\Users\Onur\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\legendary.exe
ERROR: [Backend]: Writing log file failed with Error: ENOENT: no such file or directory, open 'C:\Users\Onur/.config/heroic//Logs/heroic-2022-02-03T05:49:01.957Z.log'
INFO: [Backend]:
  Heroic Version: 2.1.0 Rayleigh
  Legendary Version:  0.20.25 Our Benefactors
  OS: Microsoft Windows 11 Pro KERNEL: 10.0.22000 ARCH: x64
  CPU: Intel CoreΓäó i7-10750H @2.6
  RAM: Total: 17 GB Available: 10.1 GB
  GRAPHICS: GPU0: NVIDIA GeForce RTX 2060 VRAM: 6144MB DRIVER: 511.23 GPU1: Intel(R) UHD Graphics VRAM: 1024MB DRIVER:


ERROR: [Backend]: Writing log file failed with Error: ENOENT: no such file or directory, open 'C:\Users\Onur/.config/heroic//Logs/heroic-2022-02-03T05:49:01.957Z.log'
WARNING: [Backend]: Protocol already registered.
ERROR: [Backend]: Writing log file failed with Error: ENOENT: no such file or directory, open 'C:\Users\Onur/.config/heroic//Logs/heroic-2022-02-03T05:49:01.957Z.log'
INFO: [Frontend]: Refreshing Library
ERROR: [Backend]: Writing log file failed with Error: ENOENT: no such file or directory, open 'C:\Users\Onur/.config/heroic//Logs/heroic-2022-02-03T05:49:01.957Z.log'
INFO: [Legendary]: Refreshing library...
ERROR: [Backend]: Writing log file failed with Error: ENOENT: no such file or directory, open 'C:\Users\Onur/.config/heroic//Logs/heroic-2022-02-03T05:49:01.957Z.log'
INFO: [Legendary]: Refreshing Epic Games...
ERROR: [Backend]: Writing log file failed with Error: ENOENT: no such file or directory, open 'C:\Users\Onur/.config/heroic//Logs/heroic-2022-02-03T05:49:01.957Z.log'
INFO: [Legendary]: Refreshing Epic Games...
ERROR: [Backend]: Writing log file failed with Error: ENOENT: no such file or directory, open 'C:\Users\Onur/.config/heroic//Logs/heroic-2022-02-03T05:49:01.957Z.log'
Error occurred in handler for 'refreshLibrary': TypeError: convertToStringArray(...).join is not a function
    at logError (C:\Users\Onur\AppData\Local\Programs\heroic\resources\app.asar\build\logger.js:54:76)
    at LegendaryLibrary.getGames (C:\Users\Onur\AppData\Local\Programs\heroic\resources\app.asar\build\legendary\library.js:127:39)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async C:\Users\Onur\AppData\Local\Programs\heroic\resources\app.asar\build\main.js:505:12
    at async node:electron/js2c/browser_init:201:563
ERROR: [Frontend]: Error: Error invoking remote method 'refreshLibrary': TypeError: convertToStringArray(...).join is not a function
ERROR: [Backend]: Writing log file failed with Error: ENOENT: no such file or directory, open 'C:\Users\Onur/.config/heroic//Logs/heroic-2022-02-03T05:49:01.957Z.log'
Error occurred in handler for 'checkGameUpdates': Error: getaddrinfo ENOTFOUND status.epicgames.com
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:71:26) {
  errno: -3008,
  code: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'status.epicgames.com',
  config: {
    url: 'https://status.epicgames.com/api/v2/status.json',
    method: 'get',
    headers: {
      Accept: 'application/json, text/plain, */*',
      'User-Agent': 'axios/0.21.4'
    },
    transformRequest: [ [Function: transformRequest] ],
    transformResponse: [ [Function: transformResponse] ],
    timeout: 0,
    adapter: [Function: httpAdapter],
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    maxBodyLength: -1,
    validateStatus: [Function: validateStatus],
    transitional: {
      silentJSONParsing: true,
      forcedJSONParsing: true,
      clarifyTimeoutError: false
    },
    data: undefined
  },
  request: <ref *1> Writable {
    _writableState: WritableState {
      objectMode: false,
      highWaterMark: 16384,
      finalCalled: false,
      needDrain: false,
      ending: false,
      ended: false,
      finished: false,
      destroyed: false,
      decodeStrings: true,
      defaultEncoding: 'utf8',
      length: 0,
      writing: false,
      corked: 0,
      sync: true,
      bufferProcessing: false,
      onwrite: [Function: bound onwrite],
      writecb: null,
      writelen: 0,
      afterWriteTickInfo: null,
      buffered: [],
      bufferedIndex: 0,
      allBuffers: true,
      allNoop: true,
      pendingcb: 0,
      constructed: true,
      prefinished: false,
      errorEmitted: false,
      emitClose: true,
      autoDestroy: true,
      errored: null,
      closed: false,
      closeEmitted: false,
      [Symbol(kOnFinished)]: []
    },
    _events: [Object: null prototype] {
      response: [Function: handleResponse],
      error: [Function: handleRequestError]
    },
    _eventsCount: 2,
    _maxListeners: undefined,
    _options: {
      maxRedirects: 21,
      maxBodyLength: 10485760,
      protocol: 'https:',
      path: '/api/v2/status.json',
      method: 'GET',
      headers: [Object],
      agent: undefined,
      agents: [Object],
      auth: undefined,
      hostname: 'status.epicgames.com',
      port: null,
      nativeProtocols: [Object],
      pathname: '/api/v2/status.json'
    },
    _ended: true,
    _ending: true,
    _redirectCount: 0,
    _redirects: [],
    _requestBodyLength: 0,
    _requestBodyBuffers: [],
    _onNativeResponse: [Function (anonymous)],
    _currentRequest: ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 7,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      destroyed: false,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: false,
      _defaultKeepAlive: true,
      useChunkedEncodingByDefault: false,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      _contentLength: 0,
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      _closed: false,
      socket: [TLSSocket],
      _header: 'GET /api/v2/status.json HTTP/1.1\r\n' +
        'Accept: application/json, text/plain, */*\r\n' +
        'User-Agent: axios/0.21.4\r\n' +
        'Host: status.epicgames.com\r\n' +
        'Connection: close\r\n' +
        '\r\n',
      _keepAliveTimeout: 0,
      _onPendingData: [Function: nop],
      agent: [Agent],
      socketPath: undefined,
      method: 'GET',
      maxHeaderSize: undefined,
      insecureHTTPParser: undefined,
      path: '/api/v2/status.json',
      _ended: false,
      res: null,
      aborted: false,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      reusedSocket: false,
      host: 'status.epicgames.com',
      protocol: 'https:',
      _redirectable: [Circular *1],
      [Symbol(kCapture)]: false,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype]
    },
    _currentUrl: 'https://status.epicgames.com/api/v2/status.json',
    [Symbol(kCapture)]: false
  },
  response: undefined,
  isAxiosError: true,
  toJSON: [Function: toJSON]
}
ERROR: [Frontend]: Error: Error invoking remote method 'checkGameUpdates': Error: getaddrinfo ENOTFOUND status.epicgames.com
ERROR: [Backend]: Writing log file failed with Error: ENOENT: no such file or directory, open 'C:\Users\Onur/.config/heroic//Logs/heroic-2022-02-03T05:49:01.957Z.log'
INFO: [Backend]: checking for heroic updates
ERROR: [Backend]: Writing log file failed with Error: ENOENT: no such file or directory, open 'C:\Users\Onur/.config/heroic//Logs/heroic-2022-02-03T05:49:01.957Z.log'
ERROR: [Backend]: Could not check for new version of heroic
ERROR: [Backend]: Writing log file failed with Error: ENOENT: no such file or directory, open 'C:\Users\Onur/.config/heroic//Logs/heroic-2022-02-03T05:49:01.957Z.log'
Error occurred in handler for 'getInstallInfo': TypeError: convertToStringArray(...).join is not a function
    at logError (C:\Users\Onur\AppData\Local\Programs\heroic\resources\app.asar\build\logger.js:54:76)
    at C:\Users\Onur\AppData\Local\Programs\heroic\resources\app.asar\build\main.js:458:31
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async node:electron/js2c/browser_init:201:563
ERROR: [Frontend]: Error: Error invoking remote method 'getInstallInfo': TypeError: convertToStringArray(...).join is not a function
ERROR: [Backend]: Writing log file failed with Error: ENOENT: no such file or directory, open 'C:\Users\Onur/.config/heroic//Logs/heroic-2022-02-03T05:49:01.957Z.log'
Error occurred in handler for 'getInstallInfo': TypeError: convertToStringArray(...).join is not a function
    at logError (C:\Users\Onur\AppData\Local\Programs\heroic\resources\app.asar\build\logger.js:54:76)
    at C:\Users\Onur\AppData\Local\Programs\heroic\resources\app.asar\build\main.js:458:31
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async node:electron/js2c/browser_init:201:563
ERROR: [Frontend]: Error: Error invoking remote method 'getInstallInfo': TypeError: convertToStringArray(...).join is not a function
ERROR: [Backend]: Writing log file failed with Error: ENOENT: no such file or directory, open 'C:\Users\Onur/.config/heroic//Logs/heroic-2022-02-03T05:49:01.957Z.log'
Error occurred in handler for 'getInstallInfo': TypeError: convertToStringArray(...).join is not a function
    at logError (C:\Users\Onur\AppData\Local\Programs\heroic\resources\app.asar\build\logger.js:54:76)
    at C:\Users\Onur\AppData\Local\Programs\heroic\resources\app.asar\build\main.js:458:31
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async node:electron/js2c/browser_init:201:563
ERROR: [Frontend]: Error: Error invoking remote method 'getInstallInfo': TypeError: convertToStringArray(...).join is not a function
ERROR: [Backend]: Writing log file failed with Error: ENOENT: no such file or directory, open 'C:\Users\Onur/.config/heroic//Logs/heroic-2022-02-03T05:49:01.957Z.log'

**Comment by onurbbr** [comment]
I couldn't find the other log you mentioned.

**Comment by Nocccer** [comment]
First of all GTA5 does not run offline. It is pointed out in the game page:
![image](https://user-images.githubusercontent.com/61798668/152586397-9063721b-6ea9-4616-ac82-3fdac467e45d.png)
Can you try another game which allows offline mode ?

This error 
```
ERROR: [Frontend]: Error: Error invoking remote method 'getInstallInfo': TypeError: convertToStringArray(...).join is not a function
```
 will be fixed in the next release.
 
 This error 
 ```
 ERROR: [Backend]: Writing log file failed with Error: ENOENT: no such file or directory, open 'C:\Users\Onur/.config/heroic//Logs/heroic-2022-02-03T05:49:01.957Z.log'
 ```
 i need to fix, but does not impact the offline situation. Do you have any spaces or special characters in your username folder ? 
 
 @flavioislima we should disable the offline setting if the game requires to be online!

**Comment by spider3000** [comment]
I'm not sure if my issue is related to this issue.

I've just installed EndeavourOS, coming from Pop!_OS. I've installed wine, Nvidia drivers, etc., and can run proton and wine games in Steam and Lutris. I've installed the AUR version of Heroic.

I can't launch any games in Heroic. When pressing on play, nothing happens and presumably the game exits almost immediately. The latest log always only shows:
`TypeError - convertToStringArray(...).join is not a function`

I'm not using the "Run Game Offline" option.

I've tried different Wine versions, installed for Lutris, from the system, and Heroic's new Wine manager.

If I disable "Auto Install/Update DXVK/VKD3D on Prefix", I get the following popup:
![image](https://user-images.githubusercontent.com/5098895/152591124-0a640eeb-eb8e-42a1-a256-7877ea5e7e31.png)

And the following log: 
[f38de9fa4c6d43eabac080942cb394a1-lastPlay.log](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/files/8005723/f38de9fa4c6d43eabac080942cb394a1-lastPlay.log)

**Comment by Nocccer** [comment]
@spider3000 not related to this issue. Please head over to our discord server and ask for help in the linux channel. Maybe someone can help there

**Comment by onurbbr** [comment]
In fact, GTA V can open offline. The main problem is that none of the games in the library are opened offline. Alien: Isolation is a game that can be played offline, but it does not open in offline mode. I tried it on Epic Games and there was no problem. Heroic can't open it.
