### ISSUE TITLE
Add AppImage update information

### ISSUE THREAD

**Issue by tazihad** [Heroic-Games-Launcher/HeroicGamesLauncher#935]
Appimage release doesn't support auto update using the [appimage official updater](https://github.com/AppImage/AppImageUpdate)
I hope you add the necessary information to appimage build so that we can update with official tool.

```
Error reading AppImage: Could not find update information in the AppImage. Please contact the author of the AppImage and ask them to embed update information.
```

**Comment by flavioislima** [comment]
@dragonDScript was working on it I think its halfway done.

**Comment by dragonDScript** [comment]
Yep
