### ISSUE TITLE
Use fuzzy search in library

### ISSUE THREAD

**Issue by plata** [Heroic-Games-Launcher/HeroicGamesLauncher#936]
examples:
- "QUBE" doesn't find "Q.U.B.E"
- "Batman Arkham Asylum" doesn't find "Batman™ Arkham Asylum"
- "A Total War Saga Troy" doesn't find "A Total War Saga: Troy"
- "Assassin's Creed" doesn't find "Assassin's Creed" (written title is "Assassins Creed")
- "Inner Space" doesn't find "InnerSpace"
- "Yooka Laylee" doesn't find "Yooka-Laylee"

**Comment by flavioislima** [comment]
Working on it.
Now even writting the wrong title will get the results:
![image](https://user-images.githubusercontent.com/26871415/171610629-9b41286a-9cab-431a-b9b3-9455e84b7131.png)
![image](https://user-images.githubusercontent.com/26871415/171610752-523addb2-e852-42e7-8ad0-00a841e9dcb6.png)
