### ISSUE TITLE
Add wine-proton builds to Wine Manager

### ISSUE THREAD

**Issue by Ahmed-E-86** [Heroic-Games-Launcher/HeroicGamesLauncher#942]
There are **wine-proton** builds which are similar to **wine-ge** builds that can be downloaded from **Wine Manager** since the latest version.

These builds are made by Kron4ek -> https://github.com/Kron4ek/Wine-Builds

You can download them from this link -> https://mega.nz/folder/ZZUV1K7J#kIenmTQoi0if-SAcMSuAHA/folder/UItyyTID

I know that wine-ge and proton-ge are included, but it will be easier to check the compatibility of a game, then use the Proton version included in user reports from Wine Manager.

**Comment by flavioislima** [comment]
HI!
For now, we think we are good at having Wine-GE. As you said, this one is similar so should not make any difference since Wine-GE is already the most compatible.

If we change our minds we might add other sources in the future.

**Comment by Ahmed-E-86** [comment]
Wine-GE is not similar to Wine-Proton. There are many releases of Wine & Wine-GE, but there are a few releases of Wine-Proton, and there are a lot of reports at protondb.com for Proton already.

**Comment by Nocccer** [comment]
What is wine-proton? Actually we try to avoid the usage of proton in heroic because proton is only developed for steam and breaks all the time outside of it. A lot of people asking for help in discord and it is like 50% only the prpblem that they used proton and not wine-ge

**Comment by Ahmed-E-86** [comment]
@Nocccer Wine-Proton is like Wine-GE which can be used outside of Proton without any issues. Try it yourself.

**Comment by Nocccer** [comment]
@flavioislima what do you think if we make a list where the user can mark which repository he wants to fetch? By default wine-ge and wine-lutris are marked.

**Comment by flavioislima** [comment]
> @Nocccer Wine-Proton is like Wine-GE which can be used outside of Steam without any issues. Try it yourself.

But how it is different from Wine-GE that is built by the guy that makes proton-ge with all the fixes backported to wine?

I belive in practice they will have the same result. Perhaps @CommandMC can have a better opinion on this.

@Nocccer if it is easier enough, sure. We need to add a new setting as well on heroic to select the repositories and also the number of releases to fetch.

**Comment by Nocccer** [comment]
> > @Nocccer Wine-Proton is like Wine-GE which can be used outside of Steam without any issues. Try it yourself.
> 
> But how it is different from Wine-GE that is built by the guy that makes proton-ge with all the fixes backported to wine?
> 
> I belive in practice they will have the same result. Perhaps @CommandMC can have a better opinion on this.
> 
> @Nocccer if it is easier enough, sure. We need to add a new setting as well on heroic to select the repositories and also the number of releases to fetch.

I don't know how different they are. But lutris-wine and wine-ge are mostly alos the same.

**Comment by flavioislima** [comment]
Nice! Perhaps then we don't need a Settings page, only an enable CheckBox and an input to put the number of releases to get.

**Comment by Nocccer** [comment]
@Ahmed-E-86 can you open a ticket here to add the wanted wine-proton?
https://github.com/Heroic-Games-Launcher/heroic-wine-downloader

**Comment by Ahmed-E-86** [comment]
@Nocccer https://github.com/Heroic-Games-Launcher/heroic-wine-downloader/issues/5

**Comment by Nocccer** [comment]
Ok actually implementing this is is not that easy, because the archive does not contain wine64 and there are also only 200mb unzipped? 
@Ahmed-E-86 how do they actually work. Defently not like wine-ge, Wine-Lutris, Proton or Proton-Ge.

**Comment by Nocccer** [comment]
@flavioislima this wine-proton takes each peace apart and there wine executable is not split in wine64 and wine. I saw that our wine detecter only looks for wine64 if it seems. To actually support wine-proton we need to look for wine aswell, if wine64 was not found. At least people can install wine-proton manually.

**Comment by flavioislima** [comment]
> @flavioislima this wine-proton takes each peace apart and there wine executable is not split in wine64 and wine. I saw that our wine detecter only looks for wine64 if it seems. To actually support wine-proton we need to look for wine aswell, if wine64 was not found. So people can installa and use wine-proton manually.

would be better to test it using as a custom wine, then you can choose the wine binary.
But I still cannot see how this wine-proton would be better than Wine-GE itself.

**Comment by Nocccer** [comment]
Me neither. Ok did not saw that you can use custom wine paths. So we could close the ticket because it is possible to set it up if someone wanna use it.
