### ISSUE TITLE
Update to Electron 14 to support XDG Desktop Portal, allowing Qt-based DE users to use native file choosers.

### ISSUE THREAD

**Issue by ImperatorStorm** [Heroic-Games-Launcher/HeroicGamesLauncher#943]
**Is your feature request related to a problem? Please describe.**
https://github.com/electron/electron/issues/2911

**Describe the solution you'd like**
Update Heroic to use Electron 14 or greater, in order to support the XDG Desktop Portal specification.

**Describe alternatives you've considered**
Implement the XDG Desktop Portal specfication _without_ updating Electron, if possible.

**Additional context**
https://github.com/electron/electron/pull/19159

**Comment by flavioislima** [comment]
We are using Electron 15 for a while now.
