### ISSUE TITLE
More options to filter and sort your game library

### ISSUE THREAD

**Issue by yoshimo** [Heroic-Games-Launcher/HeroicGamesLauncher#945]
With GoG coming and maybe other stores that cover more platforms than just windows i think it becomes necessary to allow for a more granular filter system.

Not just installed/not installed but  things like platform (windows/mac/linux/other) to see native games, store to prefer a drm less store like gog over epic if you happen to own the game multiple times and so on.

I've attached a couple of screenshots from the galaxy client that show how it could look 
![HeroicFilters_GeneralLibrary](https://user-images.githubusercontent.com/17909/151986899-32d02043-1987-4ffc-9039-049025e388da.png)
![HeroicFilters_Genre](https://user-images.githubusercontent.com/17909/151986934-baa79fcf-0e6a-44e4-b7b8-f5f8a18dc117.png)
![HeroicFilters_platform](https://user-images.githubusercontent.com/17909/151986957-1e931df3-087c-473f-abcd-ff5d373ec94b.png)
![HeroicFilters_status](https://user-images.githubusercontent.com/17909/151986969-87f3c183-fbec-456a-b50a-c2f0fd059c00.png)

**Comment by GenocideStomper** [comment]
I would even be happy with a "simple" custom tag/category/group feature, like Steam, EGS and GOG have. I would like to use it to sort games by things like whether I've played/completed them, whether I they are on my "to-play" list, etc.

Basically what #728 suggested.

**Comment by lgcavalheiro** [comment]
I believe the current release addresses some, if not all, of these suggestions:
https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/releases/tag/v2.11.0

**Comment by arielj** [comment]
I'm closing this since we seem to have all the features mentioned here:
- filter by store
- filter by platform
- custom categories

We don't have genre filtering (and we probably won't have it any time soon) because we would need to fetch the information for every game one by one and it's overkill as the library grows.
