### ISSUE TITLE
No error notification when free space on drive is lower than space required for installation.

### ISSUE THREAD

**Issue by Emerald-glitch** [Heroic-Games-Launcher/HeroicGamesLauncher#951]
### Is this a game issue? If YES please use our Discord to get help.
No
### Try to get help on our Wiki first: https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/wiki/Troubleshooting

**Describe the bug**
When free space on hard drive is less than required for installation heroic stops downloading and throws "installation completed" notification without ever telling that space is not enough not even in terminal logs.
**Add Logs**

INFO: [Legendary]: Getting More details with Legendary info command...
INFO: [Backend]: Progress: bcbc03d8812a44c18f41cf7d5f849265 /MiB/undefined
INFO: [Legendary]: Getting More details with Legendary info command...
INFO: [Backend]: Progress: bcbc03d8812a44c18f41cf7d5f849265 /MiB/undefined
INFO: [Backend]: Progress: bcbc03d8812a44c18f41cf7d5f849265 /MiB/undefined
INFO: [Backend]: Progress: bcbc03d8812a44c18f41cf7d5f849265 /MiB/undefined
INFO: [Backend]: finished installing
INFO: [Frontend]: Refreshing Library
INFO: [Legendary]: Refreshing library...
INFO: [Legendary]: Updating game list
INFO: [Legendary]: Game List Updated

Check on how to [run Heroic from Terminal or Powershell](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/wiki/Troubleshooting#running-heroic-from-terminalpowershell-to-debug-errors) and put some logs here

**To Reproduce**

Step1 - Have a small hard drive.
Step2 - Try Installing a big game.

**Expected behavior**
Maybe a Notification that i don't have enough space for installation.

**Screenshots**

**Desktop (please complete the following information):**

- OS:  Artix (Arch)
- Heroic Version 2.1.0-1
- Game:
- Wine/Proton version:
- Hardware specs (RAM, CPU, GPU):

**Additional context**

**Comment by flavioislima** [comment]
same as #967, lets discuss there
