### ISSUE TITLE
Can not launch any games recently

### ISSUE THREAD

**Issue by VortexAcherontic** [Heroic-Games-Launcher/HeroicGamesLauncher#952]
**Describe the bug**
When ever I try to launch any games it play button just silently went beck to "Play now".  
Running Heroic from CLI showed the following error:

ERROR: [Backend]: TypeError - convertToStringArray(...).join is not a function

Happens with the RPM as well as with the AppImage

**Add Logs**

````
vortex@Z004 AppImages: ./Heroic-2.1.0.AppImage 
INFO: [Legendary]: Location: /tmp/.mount_HeroicS2Fm5Y/resources/app.asar.unpacked/build/bin/linux/legendary
Xlib:  extension "NV-GLX" missing on display ":0".
Xlib:  extension "NV-GLX" missing on display ":0".
libva error: /usr/lib64/dri/vdpau_drv_video.so init failed
INFO: [Backend]: 
  Heroic Version: 2.1.0 Rayleigh
  Legendary Version:  0.20.25 Our Benefactors
  OS: openSUSE Tumbleweed KERNEL: 5.16.4-1-default ARCH: x64
  CPU: AMD Ryzen 7 1800X Eight-Core Processor @3.6 GOVERNOR: performance
  RAM: Total: 16.7 GB Available: 8 GB
  GRAPHICS: GPU0: NVIDIA GeForce RTX 3080 VRAM: 10240MB DRIVER: 510.47.03 
  PROTOCOL: wayland
  
ERROR: [Backend]: Failed to register protocol with OS.
[18372:0205/091825.360725:ERROR:browser_main_loop.cc(269)] Gtk: gtk_widget_add_accelerator: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed
[18372:0205/091825.360803:ERROR:browser_main_loop.cc(269)] Gtk: gtk_widget_add_accelerator: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed
[18372:0205/091825.360863:ERROR:browser_main_loop.cc(269)] Gtk: gtk_widget_add_accelerator: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed
WARNING: [Backend]: python command not found
INFO: [Backend]: Command 'python3' found. Version: '3.8.12'
INFO: [Frontend]: Refreshing Library
INFO: [Legendary]: Refreshing library...
INFO: [Legendary]: Refreshing Epic Games...
INFO: [Legendary]: Refreshing Epic Games...
INFO: [Legendary]: [cli] INFO: Logging in...

INFO: [Legendary]: [Core] INFO: Trying to re-use existing login session...

INFO: [Legendary]: [cli] INFO: Getting game list... (this may take a while)

INFO: [Legendary]: Updating game list
INFO: [Legendary]: Game List Updated
INFO: [Legendary]: Checking for game updates
INFO: [Legendary]: Found 0 game(s) to update
INFO: [Backend]: checking for heroic updates
INFO: [Legendary]: Getting More details with Legendary info command... 
INFO: [Backend]: launching DAEMON X MACHINA f4f0d39fbb4640e0be62aa91d9eca87d
INFO: [DXVKInstaller]: installing dxvk on... /home/vortex/Games/Heroic/Prefixes/DAEMON-X-MACHINA
INFO: [Legendary]: Getting More details with Legendary info command... 
ERROR: [Backend]: TypeError - convertToStringArray(...).join is not a function
INFO: [Legendary]: Getting More details with Legendary info command... 
````

**To Reproduce**

1. Open Heroic from command line
2. Launch game
3. See error in output

**Expected behavior**
Games should just launch

**Screenshots**
None required

**Desktop (please complete the following information):**

- OS: openSUSE Tumbleweed
- Heroic Version 2.1.0
- Game: All
- Wine/Proton version: All
- Hardware specs (RAM, CPU, GPU):
  - CPU: AMD Ryzen 7 1800X
  - GPU: RTX 3080
  - RAM: 16 GB
- Display server: GBM/Wayland
- NVidia Driver: 510.47.03
- DE/WM: Gnome 41.3 with Mutter 41.3

**Comment by Nocccer** [comment]
`ERROR: [Backend]: TypeError - convertToStringArray(...).join is not a function` is fixed in next release.
Your problem is somewhere else and not related to heroic. See Game logs ( Game Page -> Tools -> Latest logs) to see what causes the issue. You can get some help in our discord server -> channel linux.

DAEMON-X-MACHINA runs well for me with wine-ge 6.21 (downloaded via wine-manager) and dxvk enabled.

Close the issue because it is not a issue with heroic.

**Comment by VortexAcherontic** [comment]
The latest logs only tell me the same things I already gathered for this issue report.

What makes me wonder is that even the AppImage suffers from this issue which should bundle all dependencies on it's own afaik?

**Comment by Nocccer** [comment]
Try latest appimage which is not yet released:
https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/suites/5183703970/artifacts/157567434

**Comment by VortexAcherontic** [comment]
that one works like a charm, many thanks 😃 

Guess I'll then just wait for the next release
