### ISSUE TITLE
Heroic not opening on my m1 MacBook Pro 

### ISSUE THREAD

**Issue by Aayush4700** [Heroic-Games-Launcher/HeroicGamesLauncher#953]
When I opened heroic after only 2 hours after the last time it started opening for 2 sec and cancels itself
I reinstalled it but still it did not work

**Comment by Hectorotto** [comment]
i have the same device, I open the app then the dot underneath the app appear but nothing happen

**Comment by Nocccer** [comment]
Can you run it from the terminal and pass the log output here ? How to run it from terminal, had over ro our wiki and search for it in section troubleshooting.

**Comment by flavioislima** [comment]
@Aayush4700 @Hectorotto can you guys try on Beta 3?

**Comment by Hectorotto** [comment]
@flavioislima 

I'll try it asap

**Comment by Nocccer** [comment]
Colsing the ticket. If the bug still exist, reopen it and provide more information (terminal output, logs, ...)
