### ISSUE TITLE
Save-game locations are changed!

### ISSUE THREAD

**Issue by Ahmed-E-86** [Heroic-Games-Launcher/HeroicGamesLauncher#955]
Lately, save games for some of my games are not recognized by Wine-staging 7.1, Wine-GE 7.0, and Wine-TKG 7.1. 
I did not have time to troubleshoot this issue, but that is what I have found today:

`~/.wine/drive_c/users/username/Local Settings/Application Data/` is moved to this new location:

`~/.wine/drive_c/users/username/AppData/Local/`

`~/.wine/drive_c/users/username/Application Data/` is moved to this new location:

`~/.wine/drive_c/users/username/AppData/Roaming/`

Keep also in mind that after you change Windows from 7 to 10

`~/.wine/drive_c/users/username/My Documents/` will be changed to:

`~/.wine/drive_c/users/username/Documents/`

Are you aware of these new changes?

**Comment by flavioislima** [comment]
Interesting.
I think we will need to check the wine registry for the right paths then. we will need to find a way.

**Comment by Ahmed-E-86** [comment]
The path on Wine | The equivlant path on Windows
-- | --
~/.wine/drive_c/users/[username]/AppData/LocalLow | C:\Users\[username]\AppData\LocalLow
~/.wine/drive_c/users/[username]/Local Settings/Application Data | C:\Users\[username]\AppData\Local
~/.wine/drive_c/users/[username]/AppData/Local | C:\Users\[username]\AppData\Local
~/.wine/drive_c/users/[username]/Application Data | C:\Users\[username]\AppData\Roaming
~/.wine/drive_c/users/username/AppData/Roaming | C:\Users\[username]\AppData\Roaming
~/.wine/drive_c/users/[username]/Saved Games | C:\Users\[username]\Saved Games
~/.wine/drive_c/users/[username]/My Documents | C:\Users\[username]\My Documents

**Comment by wiryfuture** [comment]
Appears to be unrelated to Heroic itself, so cant fix.
