### ISSUE TITLE
Add a command-line switch to run fullscreen

### ISSUE THREAD

**Issue by clebercasali** [Heroic-Games-Launcher/HeroicGamesLauncher#961]
This would go very nice with the new gamepad interface.
Like Steam Big Picture, add a command-line switch to start Heroic in fullscreen or in a maximized undecorated window.

**Comment by Nocccer** [comment]
As workaround for version v2.1.x you can just maximize heroic. It then always start with the size it was closed.

**Comment by arielj** [comment]
Pressing F11 turns the app full screen (more than maximize, no OS panels, no window decorations). I think that's what the OP is asking for.

Though the state of F11/fullscreen is not restored when closing/opening the app.
