### ISSUE TITLE
Warning for "not enough disk space" does not appear on macOS

### ISSUE THREAD

**Issue by StupidRepo** [Heroic-Games-Launcher/HeroicGamesLauncher#967]
### Try to get help on our Wiki first: https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/wiki/Troubleshooting

**Describe the bug**
So, what happens is that I'm on a Mac, trying to download Hitman™ but it seems that it can't get the Download Size and/or Install Size meaning that when I press Download, it stalls for like 3s (saying "Installing 0%...") then it says the download was complete, when it wasn't.

I think it's because since it can't calculate Download Size or Install Size, it thinks the game has been downloaded. It only happens on Hitman™ therefor making the game uninstallable

**To Reproduce**

1. Log into an account that has Hitman™ on it.
2. Go to the Library
3. Click on HITMAN
4. Click Install
5. Wait for like 5s
6. Witness bug

**Expected behavior**
Game is supposed to install.

**Screenshots**
<img width="277" alt="Screenshot 2022-02-08 at 7 48 06 PM" src="https://user-images.githubusercontent.com/69256931/153064187-c0773620-d30f-4efc-8bca-cd7519624c0d.png">

**Desktop (please complete the following information):**

- OS: macOS 11
- Heroic Version: 2.1.1
- Game: Hitman™
- Wine/Proton version: CrossOver
- Hardware specs (RAM, CPU, GPU): M1

**Additional context**

**Comment by StupidRepo** [comment]
If you can't reproduce this bug, try getting a game that was put up for free (Like Rocket League, etc.) and then try downloading it through Heroic, it simply won't do it. It happens for all games you got for free (and then went up for sale after some time)

**Comment by CommandMC** [comment]
https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/blob/1723f1c7bdd2d3c3fdecfbd251daaff8fbbdc704/electron/utils.ts#L224
this check should find the error and display a message box. It seems like it's not working on macOS for some reason

**Comment by StupidRepo** [comment]
Hm, ok.

**Comment by flavioislima** [comment]
I believe this might be affecting other systems as well so let's investigate

**Comment by flavioislima** [comment]
Can you guys try the version here after the build finishes?
https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/actions/runs/2157692390

**Comment by flavioislima** [comment]
It seems this isnt fixed.
