### ISSUE TITLE
Open epic store here links gives error (kubuntu 22.04)

### ISSUE THREAD

**Issue by GM-Script-Writer-62850** [Heroic-Games-Launcher/HeroicGamesLauncher#971]
### Try to get help on our Wiki first: https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/wiki/Troubleshooting

**Describe the bug**

Check failed: chdir(current_directory) == 0

![Screenshot_20220212_134014](https://user-images.githubusercontent.com/564653/153723985-a80a8879-f577-4afe-9957-6814b8290fcf.png)

**Add Logs**

Check on how to [run Heroic from Terminal or Powershell](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/wiki/Troubleshooting#running-heroic-from-terminalpowershell-to-debug-errors) and put some logs here

**To Reproduce**

1. Go toLogin with SID
2. Click on 'Epic Store here'
3. System crash manager detects crash
4. Console output when this happens is `Check failed: chdir(current_directory) == 0`

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

Operating System: Kubuntu 22.04
KDE Plasma Version: 5.24.0
KDE Frameworks Version: 5.90.0
Qt Version: 5.15.2
Kernel Version: 5.16.8-051608-generic (64-bit)
Graphics Platform: X11
Processors: 12 × AMD Ryzen 5 3600 6-Core Processor
Memory: 15.6 GiB of RAM
Graphics Processor: AMD Radeon RX 580 Series

**Additional context**

**Comment by imLinguin** [comment]
Looks like this is the same problem as #968

**Comment by GM-Script-Writer-62850** [comment]
sounds link the same thing, not sure is every link location needs changes or if it would be done in a function

**Comment by flavioislima** [comment]
We need to fix the function that open files and urls since right now it's working with files and folders only.
Should be an easy fix.

**Comment by wiryfuture** [comment]
Fixed?
