### ISSUE TITLE
[Feature Request] Seperate Proton, Wine & Lutris in Wine Manager

### ISSUE THREAD

**Issue by redromnon** [Heroic-Games-Launcher/HeroicGamesLauncher#975]
**Is your feature request related to a problem? Please describe.**
All the Wine tools are displayed in a single top-to-down list. This makes it quite difficult to search between specific tools - **Wine-GE, Proton-GE & Lutris-Wine.**

**Describe the solution you'd like**
Create separate tabs or columns for each of the tools mentioned above for easier navigation.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by Nocccer** [comment]
Yes i have that in mind. But didn't find the time yet.

**Comment by flavioislima** [comment]
done
