### ISSUE TITLE
[Solus Port] Heroic Games Launcher

### ISSUE THREAD

**Issue by pelicanfuture** [Heroic-Games-Launcher/HeroicGamesLauncher#976]
Hey this really isn't a feature request, but rather me just wanting to share a fork of this repo I made for anyone looking for a working Solus package of the Heroic Games Launcher. I will be updating the fork as this repo gets updated, I may not do it right away depending on if I am busy, but I'll try to keep it consistent. Also, if the original creator is looking to add the Solus package to the official releases to make it much less complicated, I am happy to help them with this.

### Anyway, here's the [link to the fork](https://github.com/pelicanfuture/HeroicGamesLauncher)!

If there are any issues with specifically the Solus port or something Solus related, feel free to leave a reply to this issues page, otherwise, please refer to the original github repo.

**Comment by infinitymdm** [comment]
Hi @pelicanfuture , I'm glad my work helped you out! 

At present, I'm working on getting Heroic included in the official Solus repository. It's currently in review [here](https://dev.getsol.us/D12883l). If I understand things correctly, as long as it gets accepted before tomorrow it will appear in the eopkg index at the time of the Friday sync.

**Comment by pelicanfuture** [comment]
Oh okay, that's great news! When it'll be included I will remove the GitHub fork, as it won't be needed. But thank you for providing the framework for creating the eopkg.

**Comment by infinitymdm** [comment]
@pelicanfuture if you're interested in helping me keep this up to date, you're welcome to contribute to [my repo here](https://github.com/infinitymdm/heroic-games-solus) as new releases of Heroic come out. If for some reason I miss a Heroic release, your contributions will be welcome.

If I understand things correctly, what matters is the version of the .tar.gz specified in the package.yml. So we don't have to keep a copy of the whole Heroic codebase, we just have to keep the package.yml up to date with the most current stable release.

Having a secondary place where the .eopkg exists seems like a good idea to me, especially in light of the recent issues with the RIT server outages. This way it isn't a single point of failure.

**Comment by infinitymdm** [comment]
Heroic has been accepted into the Solus repository. If you're on the unstable repository, you should be able to install it via `eopkg` or the Software Center. Stable users will see it appear after the Friday sync. 

@pelicanfuture in the meantime, thanks for helping make this available to folks!

**Comment by flavioislima** [comment]
Thats good news!

**Comment by wiryfuture** [comment]
Fixed then?
