### ISSUE TITLE
Check for Updates On Startup does not toggle off

### ISSUE THREAD

**Issue by redromnon** [Heroic-Games-Launcher/HeroicGamesLauncher#978]
### Try to get help on our Wiki first: https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/wiki/Troubleshooting

**Describe the bug**
The checkbox _Check for Updates on Startup_, under General (Global) Settings, always toggles itself on despite turning it off. When I reopen the app or move to another tab/window and come back to the General Settings window, the checkbox is turned on automatically. I believe the toggle's state doesn't get saved and thus leads to this issue.

**Add Logs**
None

**To Reproduce**
1. Go to Settings
2. Click General
3. Under Global Settings 
4. Uncheck the _Check for Updates on Startup_ checkbox

**Expected behavior**
The checkbox should be always unchecked when done so. 

**Screenshots**
![Check_for_Updates_Heroic](https://user-images.githubusercontent.com/74495920/154425388-2eda4876-1a80-4d44-9d88-762ddc24db6e.png)

**Desktop (please complete the following information):**

- OS: Pop_OS 20.04
- Heroic Version - 2.1.1 Rayleigh

**Additional context**
None

**Comment by Nocccer** [comment]
Can reproduce it. Will try to fix it.

**Comment by flavioislima** [comment]
> Can reproduce it. Will try to fix it.

I believe the issue is on this line:
https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/blob/5d72a3860e427ba68267b7d5906b11ba0c3d27f1/src/screens/Settings/index.tsx#L94

Because this settings'  default is `true`, but on this line, it starts as `false`. So there is some conflict.
changing here to true should fix the issue.

**Comment by Nocccer** [comment]
@flavioislima already fixed it for ~2h
