### ISSUE TITLE
[Windows] Shortcuts open Heroic window

### ISSUE THREAD

**Issue by Rafii2198** [Heroic-Games-Launcher/HeroicGamesLauncher#982]
**Is your feature request related to a problem? Please describe.**
This is more for convenience, to make it work more like Steam, a bit more "user friendly".

**Describe the solution you'd like**
Just like Steam I think it should be hidden when launching a game through a shortcut. Steam opens small window informing it is launching or updating if there is an update but whole is not showing. I think this would more "user friendly" although I don't know if this term is right here, but basically, if user open a Dauntless shortcut, they would expect Dauntless to show up, not Heroic.
So if it is possible for Heroic to no show up when using a shortcut, it would be great!
(Or maybe make it into an option so if someone likes current behavior then they can keep it.)

**Comment by flavioislima** [comment]
You can toggle `Start Minimized` on Heroic settings to get that behavior.
You need to enable the setting to close to Tray Icon first and then this second option will appear.

**Comment by Rafii2198** [comment]
The thing is I have set it on and when Heroic is not running it works as it launches minimized.
Now after I restarted my PC after installing, it seems to be broken, as I said when Heroic is not running it works, but when it is running it just appears and no game is launched at all.
