### ISSUE TITLE
Launcher Doesn't List Unreal Marketplace Items / Infinite Loading Screen

### ISSUE THREAD

**Issue by cachandlerdev** [Heroic-Games-Launcher/HeroicGamesLauncher#985]
**Describe the bug**

The launcher doesn't find any results for items I have obtained in the Unreal Marketplace, and when I hit the refresh button, I get an infinite loading screen.

**Add Logs**

```
(13:00:00) INFO:    [Legendary]:       Location: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary
[131464:0219/130000.464293:ERROR:vaapi_wrapper.cc(1104)] vaQuerySurfaceAttributes failed, VA error: invalid parameter
[131464:0219/130000.464410:ERROR:vaapi_wrapper.cc(1051)] FillProfileInfo_Locked failed for va_profile VAProfileH264Main and entrypoint VAEntrypointVLD
[131464:0219/130000.464520:ERROR:vaapi_wrapper.cc(1104)] vaQuerySurfaceAttributes failed, VA error: invalid parameter
[131464:0219/130000.464600:ERROR:vaapi_wrapper.cc(1051)] FillProfileInfo_Locked failed for va_profile VAProfileH264High and entrypoint VAEntrypointVLD
(13:00:00) INFO:    [Backend]:         
  Heroic Version: 2.1.1 Rayleigh
  Legendary Version:  0.20.25 Our Benefactors
  OS: ManjaroLinux KERNEL: 5.16.7-1-MANJARO ARCH: x64
  CPU: Intel Core™ i7-10700 @2.9 GOVERNOR: powersave
  RAM: Total: 33.5 GB Available: 26.8 GB
  GRAPHICS: GPU0: NVIDIA GeForce RTX 2070 SUPER VRAM: 8192MB DRIVER: 510.47.03 
  PROTOCOL: x11
  
(13:00:00) WARNING: [Backend]:         Protocol already registered.
[131430:0219/130000.954651:ERROR:browser_main_loop.cc(269)] Gtk: gtk_widget_add_accelerator: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed
[131430:0219/130000.954697:ERROR:browser_main_loop.cc(269)] Gtk: gtk_widget_add_accelerator: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed
[131430:0219/130000.954739:ERROR:browser_main_loop.cc(269)] Gtk: gtk_widget_add_accelerator: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed
(13:00:01) INFO:    [Frontend]:        Refreshing Library
(13:00:01) INFO:    [Legendary]:       Refreshing library...
(13:00:01) INFO:    [Legendary]:       Refreshing Epic Games...
(13:00:01) INFO:    [Legendary]:       Refreshing Epic Games...
(13:00:02) INFO:    [Legendary]:       [cli] INFO: Logging in...
(13:00:02) INFO:    [Legendary]:       [Core] INFO: Trying to re-use existing login session...
(13:00:02) INFO:    [Legendary]:       [cli] INFO: Getting game list... (this may take a while)
(13:00:05) INFO:    [Backend]:         checking for heroic updates
(13:00:05) INFO:    [Backend]:         skipping heroic updates
```

**To Reproduce**

1. Enable the Unreal Marketplace.
2. Launch Heroic (See Nothing Issue).
3. Hit Refresh Button (See Infinite Loading Screen Issue)

**Expected behavior**

The application should display the marketplace items, and shouldn't give me an infinite loading screen when I try to refresh the page.

**Screenshots**

The first image shows the screen I get when I open the Marketplace section. The second one shows the loading screen.
![image](https://user-images.githubusercontent.com/70250943/154819032-5375420f-29ae-4c03-b538-93853fc96e85.png)
![image](https://user-images.githubusercontent.com/70250943/154819061-9504aa7a-97f5-4a9d-a2d7-acf247738ed8.png)

**Desktop (please complete the following information):**

- OS: Manjaro Linux
- Heroic Version: 2.1.1 Rayleigh
- Game: None
- Wine/Proton version: None
- Hardware specs (RAM, CPU, GPU): 32GB, i7-10700, RTX 2070 Super

**Additional context**
* Legendary displays the marketplace assets fine when I run `legendary list --include-ue` , so this seems to be a Heroic issue.
* Games are displayed properly. It's just an issue with the Unreal Marketplace.

**Comment by flavioislima** [comment]
Yes, depending on how many items you have now Heroic cant handle, this is a known issue. Unfortunately, we do not have any developer focused on the Unreal Marketplace anymore so its complicated to put some effort to improve it.
Let's wait until someone wants to contribute to that again.

**Comment by etoven** [comment]
> **Describe the bug**
> 
> The launcher doesn't find any results for items I have obtained in the Unreal Marketplace, and when I hit the refresh button, I get an infinite loading screen.
> 
> **Add Logs**
> 
> ```
> (13:00:00) INFO:    [Legendary]:       Location: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary
> [131464:0219/130000.464293:ERROR:vaapi_wrapper.cc(1104)] vaQuerySurfaceAttributes failed, VA error: invalid parameter
> [131464:0219/130000.464410:ERROR:vaapi_wrapper.cc(1051)] FillProfileInfo_Locked failed for va_profile VAProfileH264Main and entrypoint VAEntrypointVLD
> [131464:0219/130000.464520:ERROR:vaapi_wrapper.cc(1104)] vaQuerySurfaceAttributes failed, VA error: invalid parameter
> [131464:0219/130000.464600:ERROR:vaapi_wrapper.cc(1051)] FillProfileInfo_Locked failed for va_profile VAProfileH264High and entrypoint VAEntrypointVLD
> (13:00:00) INFO:    [Backend]:         
>   Heroic Version: 2.1.1 Rayleigh
>   Legendary Version:  0.20.25 Our Benefactors
>   OS: ManjaroLinux KERNEL: 5.16.7-1-MANJARO ARCH: x64
>   CPU: Intel Core™ i7-10700 @2.9 GOVERNOR: powersave
>   RAM: Total: 33.5 GB Available: 26.8 GB
>   GRAPHICS: GPU0: NVIDIA GeForce RTX 2070 SUPER VRAM: 8192MB DRIVER: 510.47.03 
>   PROTOCOL: x11
>   
> (13:00:00) WARNING: [Backend]:         Protocol already registered.
> [131430:0219/130000.954651:ERROR:browser_main_loop.cc(269)] Gtk: gtk_widget_add_accelerator: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed
> [131430:0219/130000.954697:ERROR:browser_main_loop.cc(269)] Gtk: gtk_widget_add_accelerator: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed
> [131430:0219/130000.954739:ERROR:browser_main_loop.cc(269)] Gtk: gtk_widget_add_accelerator: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed
> (13:00:01) INFO:    [Frontend]:        Refreshing Library
> (13:00:01) INFO:    [Legendary]:       Refreshing library...
> (13:00:01) INFO:    [Legendary]:       Refreshing Epic Games...
> (13:00:01) INFO:    [Legendary]:       Refreshing Epic Games...
> (13:00:02) INFO:    [Legendary]:       [cli] INFO: Logging in...
> (13:00:02) INFO:    [Legendary]:       [Core] INFO: Trying to re-use existing login session...
> (13:00:02) INFO:    [Legendary]:       [cli] INFO: Getting game list... (this may take a while)
> (13:00:05) INFO:    [Backend]:         checking for heroic updates
> (13:00:05) INFO:    [Backend]:         skipping heroic updates
> ```
> 
> **To Reproduce**
> 
> 1. Enable the Unreal Marketplace.
> 2. Launch Heroic (See Nothing Issue).
> 3. Hit Refresh Button (See Infinite Loading Screen Issue)
> 
> **Expected behavior**
> 
> The application should display the marketplace items, and shouldn't give me an infinite loading screen when I try to refresh the page.
> 
> **Screenshots**
> 
> The first image shows the screen I get when I open the Marketplace section. The second one shows the loading screen. ![image](https://user-images.githubusercontent.com/70250943/154819032-5375420f-29ae-4c03-b538-93853fc96e85.png) ![image](https://user-images.githubusercontent.com/70250943/154819061-9504aa7a-97f5-4a9d-a2d7-acf247738ed8.png)
> 
> **Desktop (please complete the following information):**
> 
> * OS: Manjaro Linux
> * Heroic Version: 2.1.1 Rayleigh
> * Game: None
> * Wine/Proton version: None
> * Hardware specs (RAM, CPU, GPU): 32GB, i7-10700, RTX 2070 Super
> 
> **Additional context**
> 
> * Legendary displays the marketplace assets fine when I run `legendary list --include-ue` , so this seems to be a Heroic issue.
> * Games are displayed properly. It's just an issue with the Unreal Marketplace.

This is big for me. Having access to my unreal assets the the whole thing that got me to try heroic in the first place.
Legendary not having a issue. Doesn't seem that complicated. 

I might consider working on the issue and submitting a pull request. If it's not fixed soon.

**Comment by etoven** [comment]
I have been playing with the issue today. The bug appears to be in the UI or caching code. I am still digesting the source tree. But have been able to determine it's pulling the list just fine.

**Comment by olivatooo** [comment]
:rotating_light:

**Comment by flavioislima** [comment]
I am closing this one since we decided to drop support for the marketplace on next release.
