### ISSUE TITLE
[BUG] Can't use Proton 7.0

### ISSUE THREAD

**Issue by onurbbr** [Heroic-Games-Launcher/HeroicGamesLauncher#986]
**Describe the bug**
I can't open GTA V, Alien: Isolation, Rocket League and other library games with Proton 7.0. Proton 7.0 does not appear in the Wine Version menu.

**To Reproduce**

1. Go to settings
2. Click on wine menu
3. Check wine version
4. See the available wine options. 

**Expected behavior**
Being able to see Proton 7.0 in the Wine version section.

**Desktop (please complete the following information):**

- OS: Arch Linux
- Heroic Version: 2.1.1-1 (Rayleigh)
- Game: GTA V, Alien: Isolation, Rocket League(Epic Library)
- Wine/Proton version: 7.0-1
- Hardware specs (RAM, CPU, GPU): 16 GB RAM, Intel Core i7-10750H, NVIDIA GeForce RTX 2060 Mobile

**Additional context**
Screenshots:
![Screenshot_20220220_001152](https://user-images.githubusercontent.com/47495526/154819207-fd13a815-3de7-4cf6-8d58-771fa76dc095.png)

**Comment by flavioislima** [comment]
Is it installed on your home folder?
Where is proton installed?

**Comment by onurbbr** [comment]
> Is it installed on your home folder? Where is proton installed?

I installed Proton via steam.

**Comment by flavioislima** [comment]
Heroic will find proton only on the library on tmyour home folder, not other partitions.
Check our wiki to know the exact paths heroic searches for.

**Comment by onurbbr** [comment]
I can play games such as Among Us and Sea of Thieves with Proton 7.0 on Steam, but Heroic cannot see Proton 7.0. The compabilitytools.d folder is empty but I can run steam games with Proton 7.0.

**Comment by flavioislima** [comment]
The problem is not if it is installed, I can see it is installed.
The Problem is WHERE it is installed.
You need to enable TOOLS on STEAM, then select Proton 7 > Properties > Move >  Select Library on Home Folder.

Heroic will find Proton on this places only:
~/.config/heroic/tools/proton
~/.steam/root/compatibilitytools.d
~/.steam/steam/steamapps/common


also, you can use Heroic to download and install Proton and Wine versions using the Wine Manager above the Discord Button.

**Comment by eccentric-j** [comment]
Running into a similar issue. It seems steam uses the install path `~/.local/share/Steam/steamapps/common` and not `~/.steam/steam/steamapps/common` and only shows Proton GE and Wine options. I can manually add proton 7 but then it's listed as Custom Proton path. When I use Steam to try and move the installation I can only choose whatever disk it's not installed on, no extra file locations. Maybe this is a steamdeck specific problem?
