### ISSUE TITLE
Masking some joystick inputs when a Steam Virtual Controller is active

### ISSUE THREAD

**Issue by dazchipsugar** [Heroic-Games-Launcher/HeroicGamesLauncher#989]
### Problem description

This issue is only in effect when Steam is also installed and "Configuration Support" is enabled in Steam for your controller type. I use this to emulate Xbox controller support on linux/wine for my old PS2 controller so this is affecting me.

When using the Steam Virtual Controller support with linux the Steam client creates extra /dev/input/event* and /dev/input/js* entries. This means that some programs (like Heroic) will register 2 button/axis presses in their UI as both the actual joystick and the emulated device register presses at the same time. In the UI this makes using navigation using the gamepad very restrictive.

### Feature description

When the Steam client is loaded and Heroic is launched the UI could either ignore the Steam Controller or "only" see the Steam controller, or could include some extra logic to see which controller the Steam Controller should mask and should ignore that specific controller instead.

### Alternatives

Setting up xboxdrv, but this has been problematic for other reasons, although using Steam should not mean creating problems for other applications.

### Additional information

A separate but also connected issue is that when using wine this sometimes creates another issue. Some games will register input from both the virtual and actual devices. Lutris offered the option of disabling non-steam controllers in the wine prefix. This may also be worth considering as a separate option in Heroic's Wine settings menu.

**Comment by flavioislima** [comment]
Would be good to investigate how Lutris is masking the controllers. I believe that should be the best option to avoid missing input when steam is opened.

**Comment by arielj** [comment]
Can you share the output of both controllers in this website using a chromium-based browser? https://gamepad-tester.com

Maybe there's some identifier that we can use to ignore a controller.

**Comment by mdeguzis** [comment]
Any update on this? 2 years is quite some time... With how popular the Steak Deck is, it makes using it in game mode really difficult without mousing around.

**Comment by bmsuseluda** [comment]
I have the same problem with my app. The masked gamepad has the id "Microsoft X-Box 360 pad 0 (STANDARD GAMEPAD Vendor: 28de Product: 11ff)" in Chrome.

The vendor 28de is valve. This is good. Sadly the steam deck built in gamepad has the same id. Therefore you can not filter this id :(

**Comment by mdeguzis** [comment]
Probably not a solution, in other emulators like Supermodel 3, I used SDL and disabled steam input in game mode.
