### ISSUE TITLE
Resetting OS display resolution once a game closes.

### ISSUE THREAD

**Issue by dazchipsugar** [Heroic-Games-Launcher/HeroicGamesLauncher#990]
### Problem description

Not all games play nice when closing down, and some seem to think it is asking far too much for them to return the display to the same resolution it was at before we started the game. Also I'm using Linux and if there is a compatibility issue in Wine and a game crashes as a result the resolution won't always reset either.

### Feature description

Heroic could have an option to query the current desktop resolution for the relevant displays and change back to that resolution when the game closes/crashes.

### Alternatives

Another solution could be for there to be another Heroic option to allow users to run their own scripts/commands before running the game and after the game closes.

**Comment by Nocccer** [comment]
This seems impossible. We could run `xrandr -s 0` afterwards, but this goes always back to the max resolution of the screen. If a user does not want it, we break is default resolution.

Would be better to allow to run a command after a game is finished. I think @CommandMC has something in mind with postLaunch? I am correct?

**Comment by CommandMC** [comment]
Well it's not impossible, we could just remember the screen resolution that was set when starting the game, and then return to that once it's closed

The real solution would be to just use Wine's Virtual Desktop to avoid problems like this entirely

Yes, pre- and post-launch commands are something I wanted to implement, but they're pretty low on my endless to-do list

**Comment by arielj** [comment]
Since the latest release supports pre/post game scripts, this can be solved manually with some scripts instead of having a generic solution in Heroic (which would be too hard to do).

Closing this.
