### ISSUE TITLE
Among Us not playable

### ISSUE THREAD

**Issue by EdwardRodriguezzz** [Heroic-Games-Launcher/HeroicGamesLauncher#993]
### Describe the bug

for some reason neither Among Us nor Celeste are playable, they don't even pop up on my screen, I have not tried any other games

I have tried using proton experimental, proton 7.2-GE-2, proton 6.21-GE-2, wine-lutris-7.1 and wine-7.2-GE-2

(the log says something about freetype but I do have it installed from the official arch repositories, should I seek another form of installation for it?)

### Add logs

Launch Command:           STEAM_COMPAT_CLIENT_INSTALL_PATH=/home/ed/.steam/steam STEAM_COMPAT_DATA_PATH='/home/ed/Games/Heroic/Prefixes/Among-Us'   /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary launch 963137e4c29d4c79a81323b8fab03a40   --no-wine --wrapper "'/home/ed/.steam/steam/steamapps/common/Proton - Experimental/proton' run"   
        System Info:
        
  Heroic Version: 2.1.1 Rayleigh
  Legendary Version:  0.20.25 Our Benefactors
  OS: EndeavourOS KERNEL: 5.16.10-arch1-1 ARCH: x64
  CPU: AMD Ryzen 5 3500U with Radeon Vega Mobile Gfx @2.1 GOVERNOR: schedutil
  RAM: Total: 6.16 GB Available: 4.03 GB
  GRAPHICS: GPU0: Picasso/Raven 2 [Radeon Vega Series / Radeon Vega Mobile Series] VRAM: 512MB DRIVER:  
  PROTOCOL: x11
  
        Game Settings: {
	"audioFix": false,
	"autoInstallDxvk": false,
	"autoInstallVkd3d": false,
	"autoSyncSaves": false,
	"enableEsync": false,
	"enableFSR": false,
	"enableFsync": false,
	"maxSharpness": 2,
	"enableResizableBar": false,
	"nvidiaPrime": false,
	"offlineMode": false,
	"otherOptions": "",
	"savesPath": "",
	"showFps": false,
	"showMangohud": false,
	"targetExe": "",
	"useGameMode": false,
	"wineCrossoverBottle": "Heroic",
	"winePrefix": "/home/ed/Games/Heroic/Prefixes/Among-Us",
	"wineVersion": {
		"bin": "'/home/ed/.steam/steam/steamapps/common/Proton - Experimental/proton'",
		"name": "Proton - Proton - Experimental"
	}
}

        Legendary Log:
        [cli] INFO: Logging in...
[Core] INFO: Trying to re-use existing login session...
[cli] INFO: Checking for updates...
[Core] INFO: Getting authentication token...
[cli] INFO: Launching 963137e4c29d4c79a81323b8fab03a40...
Proton: Upgrading prefix from None to 7.0-100 (/home/ed/Games/Heroic/Prefixes/Among-Us/)
fsync: up and running.
wine: RLIMIT_NICE is <= 20, unable to use setpriority safely
Wine cannot find the FreeType font library.  To enable Wine to
use TrueType fonts please install a version of FreeType greater than
or equal to 2.0.5.
http://www.freetype.org
Wine cannot find the FreeType font library.  To enable Wine to
use TrueType fonts please install a version of FreeType greater than
or equal to 2.0.5.
http://www.freetype.org
wine: Unhandled page fault on execute access to 00000000 at address 00000000 (thread 0190), starting debugger...
wine: Unhandled page fault on execute access to 00000000 at address 00000000 (thread 0118), starting debugger...

        

### Steps to reproduce

installing and playing among us

### Expected behavior

the game should be executed

### System Information

- OS [e. g. "Ubuntu"]: EndeavourOS
- Heroic Version [e. g. 2.1.1]: I'm not sure where I'm supposed to find this information

**Comment by imLinguin** [comment]
Proton isn't meant to be used outside of steam, use Wine-GE and refer to this for workarounds. https://github.com/CommandMC/EpicLinux/wiki/Among-Us

**Comment by flavioislima** [comment]
Also, this is not a Heroic issue.
Github should be used for issues with Heroic only not Wine, Proton or game-related.
If you need further help try our Discord or open a Discussion
