### ISSUE TITLE
can't load gog library

### ISSUE THREAD

**Issue by sneekee-stache** [Heroic-Games-Launcher/HeroicGamesLauncher#999]
### Describe the bug

heroic can't load the gog library
it seems that  it can't get the covers for the goodies or for games that were removed from gog like stranger things so it doesn't load the library at all

### Add logs

(21:28:51) INFO:    [Legendary]:       Location: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary
(21:28:51) INFO:    [Gog]:             Location: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl
(21:28:51) INFO:    [Backend]:         
  Heroic Version: 2.2.0 Rayleigh
  Legendary Version:  0.20.25 Our Benefactors
  OS: Fedora Linux KERNEL: 5.16.10-201.fsync.fc35.x86_64 ARCH: x64
  CPU: Intel Core™ i7-4770 @3.4 GOVERNOR: schedutil
  RAM: Total: 20.9 GB Available: 14.3 GB
  GRAPHICS: GPU0: Ellesmere [Radeon RX 470/480/570/570X/580/580X/590] VRAM: 256MB DRIVER:  
  PROTOCOL: x11
  
(21:28:51) INFO:    [Gog]:             Getting data about the user
(21:28:52) WARNING: [Backend]:         Protocol already registered.
(21:28:52) INFO:    [Gog]:             Saved user data to config
(21:28:52) INFO:    [Frontend]:        Refreshing Library
(21:28:52) INFO:    [Gog]:             Getting GOG library
(21:28:52) INFO:    [Gog]:             Number of library pages: 3
(21:28:52) INFO:    [Gog]:             Getting data for page 2
(21:28:53) INFO:    [Gog]:             Getting data for page 3
(21:28:58) WARNING: [Gog]:             Unable to get covers from gamesdb for Cyberpunk 2077 Goodies Collection. Trying to get it from api.gog.com
(21:28:58) INFO:    [Backend]:         checking for heroic updates
(21:28:58) ERROR:   [Frontend]:        Error: Error invoking remote method 'refreshLibrary': TypeError: Cannot read properties of null (reading '_links')
(21:28:59) INFO:    [Legendary]:       Checking for game updates
(21:28:59) INFO:    [Legendary]:       Found 0 game(s) to update
(21:28:59) INFO:    [Gog]:             Found 0 game(s) to update

### Steps to reproduce

just launch the heroic game launcher with a library that as some goodies or games removed from the store

### Expected behavior

having my gog library appear in heroic

### System Information

- OS ["fedora 35, kernel 5.16.10-201.fsync.x86_64"]: 
- Heroic Version [2.2.0]:

**Comment by Weetile** [comment]
I'm having the same issue.
`(20:36:45) INFO:    [Legendary]:       Location: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary
(20:36:45) INFO:    [Gog]:             Location: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl
(20:36:46) INFO:    [Backend]:         
  Heroic Version: 2.2.0 Rayleigh
  Legendary Version:  0.20.25 Our Benefactors
  OS: ManjaroLinux KERNEL: 5.16.7-1-MANJARO ARCH: x64
  CPU: Intel Core™ i5-6500 @3.2 GOVERNOR: powersave
  RAM: Total: 16.7 GB Available: 5.44 GB
  GRAPHICS: GPU0: Ellesmere [Radeon RX 470/480/570/570X/580/580X/590] VRAM: 256MB DRIVER:  
  PROTOCOL: x11
  
(20:36:46) INFO:    [Gog]:             Getting data about the user
(20:36:46) WARNING: [Backend]:         Protocol already registered.
(20:36:46) INFO:    [Gog]:             Saved user data to config
(20:36:47) INFO:    [Frontend]:        Refreshing Library
(20:36:47) INFO:    [Gog]:             Getting GOG library
(20:36:47) INFO:    [Gog]:             Number of library pages: 1
(20:36:47) WARNING: [Gog]:             Unable to get covers from gamesdb for Cyberpunk 2077 Goodies Collection. Trying to get it from api.gog.com
(20:36:48) ERROR:   [Frontend]:        Error: Error invoking remote method 'refreshLibrary': TypeError: Cannot read properties of null (reading '_links')
(20:36:50) INFO:    [Legendary]:       Checking for game updates
(20:36:50) INFO:    [Legendary]:       Found 0 game(s) to update
(20:36:50) INFO:    [Gog]:             Found 0 game(s) to update
(20:36:51) INFO:    [Backend]:         checking for heroic updates
`

**Comment by PetrosStavrakakis** [comment]
Hi.
I have the same problem with a different game, but the error ist the same (cover, gamesdb,refreshLibrary)

(21:43:50) INFO:    [Legendary]:       Location: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary
(21:43:50) INFO:    [Gog]:             Location: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl
(21:43:51) INFO:    [Backend]:         
  Heroic Version: 2.2.0 Rayleigh
  Legendary Version:  0.20.25 Our Benefactors
  OS: ManjaroLinux KERNEL: 5.16.7-1-MANJARO ARCH: x64
  CPU: Intel Xeon® E5-1620 v2 @3.7 GOVERNOR: schedutil
  RAM: Total: 67.3 GB Available: 62.4 GB
  GRAPHICS: GPU0: NVIDIA GeForce GTX 1060 6GB VRAM: 6144MB DRIVER: 510.47.03 
  PROTOCOL: x11
  
(21:43:51) INFO:    [Gog]:             Getting data about the user
(21:43:51) WARNING: [Backend]:         Protocol already registered.
(21:43:51) INFO:    [Gog]:             Saved user data to config
(21:43:52) INFO:    [Frontend]:        Refreshing Library
(21:43:52) INFO:    [Gog]:             Getting GOG library
(21:43:53) INFO:    [Gog]:             Number of library pages: 2
(21:43:53) INFO:    [Gog]:             Getting data for page 2
(21:43:53) WARNING: [Gog]:             Unable to get covers from gamesdb for Cave Story®'s Secret Santa. Trying to get it from api.gog.com
(21:43:53) ERROR:   [Frontend]:        Error: Error invoking remote method 'refreshLibrary': TypeError: Cannot read properties of null (reading '_links')
(21:43:55) INFO:    [Legendary]:       Checking for game updates
(21:43:55) INFO:    [Legendary]:       Found 0 game(s) to update
(21:43:55) INFO:    [Gog]:             Found 0 game(s) to update
(21:43:57) INFO:    [Backend]:         checking for heroic updates

**Comment by VitonatorPL** [comment]
Same here, Witcher goodies in my case.

(22:26:51) INFO:    [Legendary]:       Location: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary
(22:26:51) INFO:    [Gog]:             Location: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl
[325815:0223/222651.958201:ERROR:sandbox_linux.cc(377)] InitializeSandbox() called with multiple threads in process gpu-process.
(22:26:52) INFO:    [Backend]:         
  Heroic Version: 2.2.0 Rayleigh
  Legendary Version:  0.20.25 Our Benefactors
  OS: Pop KERNEL: 5.15.24-xanmod1 ARCH: x64
  CPU: Intel Core™ i7-7700HQ @2.8 GOVERNOR: performance
  RAM: Total: 12.4 GB Available: 7.34 GB
  GRAPHICS: GPU0: HD Graphics 630  VRAM: 256MB DRIVER:  GPU1: NVIDIA GeForce GTX 1050 Ti VRAM: 4096MB DRIVER: 510.54 
  PROTOCOL: x11
  
(22:26:52) INFO:    [Gog]:             Getting data about the user
(22:26:52) WARNING: [Backend]:         Protocol already registered.
[325780:0223/222652.459563:ERROR:browser_main_loop.cc(267)] Gtk: gtk_widget_add_accelerator: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed
[325780:0223/222652.459698:ERROR:browser_main_loop.cc(267)] Gtk: gtk_widget_add_accelerator: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed
[325780:0223/222652.459814:ERROR:browser_main_loop.cc(267)] Gtk: gtk_widget_add_accelerator: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed
(22:26:52) INFO:    [Gog]:             Saved user data to config
(22:26:53) INFO:    [Frontend]:        Refreshing Library
(22:26:53) INFO:    [Gog]:             Getting GOG library
(22:26:53) INFO:    [Gog]:             Number of library pages: 1
(22:26:54) WARNING: [Gog]:             Unable to get covers from gamesdb for The Witcher Goodies Collection. Trying to get it from api.gog.com
Error occurred in handler for 'refreshLibrary': TypeError: Cannot read properties of null (reading '_links')
    at GOGLibrary.gogToUnifiedInfo (/opt/Heroic/resources/app.asar/build/gog/library.js:263:25)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async GOGLibrary.sync (/opt/Heroic/resources/app.asar/build/gog/library.js:81:33)
    at async /opt/Heroic/resources/app.asar/build/main.js:526:5
    at async node:electron/js2c/browser_init:193:563
(22:26:54) ERROR:   [Frontend]:        Error: Error invoking remote method 'refreshLibrary': TypeError: Cannot read properties of null (reading '_links')
(22:26:55) INFO:    [Legendary]:       Checking for game updates
(22:26:55) INFO:    [Legendary]:       Found 0 game(s) to update
(22:26:55) INFO:    [Gog]:             Found 0 game(s) to update
(22:26:57) INFO:    [Backend]:         checking for heroic updates

**Comment by imLinguin** [comment]
See if it solves those issues. Hotfix release will be tomorrow

https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/actions/runs/1889888011

**Comment by sergen213** [comment]
> See if it solves those issues. Hotfix release will be tomorrow
> 
> https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/actions/runs/1889888011

This build works thank you.

**Comment by VitonatorPL** [comment]
> See if it solves those issues. Hotfix release will be tomorrow
> 
> https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/actions/runs/1889888011

I can confirm that this fix shows my library now, dobra robota, dzięki !

**Comment by sergen213** [comment]
> > See if it solves those issues. Hotfix release will be tomorrow
> > https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/actions/runs/1889888011
> 
> This build works thank you. Oh and I'm on Windows. ![Capture](https://user-images.githubusercontent.com/20866366/155421203-bf0f3583-4244-4314-a990-0dd4659faaac.PNG)

But now it doesn't install GOG games. It starts downloading and then just defaults back to Install button. It only downloads 10mb of data.

**Comment by imLinguin** [comment]
@sergen213 could you ping me on Discord with logs?

**Comment by flavioislima** [comment]
Fixed on new release
